**** SOURCE FILE : M0004132.V07   ***
*
C
C
      SUBROUTINE GO(HMOD,ADRESS)
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'LDEF.INC'
      INCLUDE 'IFXCOR.INC'
C
      DIMENSION ADRESS(*)
      IF(JDS) CALL APT211(0,'NOCS    ',IDUM)
c      if(jds) then
c         dummy= apt211(0,'nocs    ',idum)
c      endif
C-IBM-      CALL APT241
       CALL APT241
c      IF(IAERR.EQ.1)GO TO 10
C-VAX-ESTABLISH CONDITION HANDLER
c      CALL APT241
c   20 IF(ICTDEF.NE.0.AND.IGOTO.EQ.0)CALL AERR(20201,'GO      ')
c      IF (IAERR.EQ.1) GOTO 10
c      CALL GO2(HMOD,ADRESS)
c      IF (IAERR.EQ.1) GOTO 20
C-VAX- REVERT TO DEFAULT CONDITION HANDLER
c   10 CALL LIB$REVERT
      RETURN
      END
