**** SOURCE FILE : PUNCHC00.ORG   ***
*
      SUBROUTINE PUNCHC(N,A,J,K)
*
*  * PUNCHC *   VAX-11 FORTRAN 77 VERSION 29.11.82 E.MCLELLAN
*               REVISED FOR CHARACTER HANDLING 5.9.85 E.MCL.
*
*  PURPOSE     TO GENERATE REQUIRED PAPER TAPE CODES FOR CHARACTERS
*
*  CALLING SEQUENCE
*              CALL PUNCHC(N,A,J,K)
*  ARGUMENTS
*              N NUMBER OF CHARACTERS IN A
*              A CHARACTER STRING TO BE PUNCHED
*              J NUMBER OF CHARACTERS PUNCHED
*              K -2  BLANKS AND PERIODS IGNORED
*                -1  PERIODS IGNORED
*                 0  BLANKS IGNORED
*                >0  BLANKS ARE PROCESSED
*
*  ALTERNATE ENTRY
*              CALL PUNCHD(N,A,J,K)
*
C
C...BYTE VARIABLES IN THIS VAX IMPLEMENTATION MIGHT BE ABLE TO BE LOGICA
C...ON OTHER SYSTEMS
C
      COMMON/PUNTAB/PUNCOD
      BYTE PUNCOD(128),ILEGAL
*
      CHARACTER*512 A
      CHARACTER*512 INFIL,OUTFIL
      BYTE PUNOUT(512)
      LOGICAL OD
C
      INCLUDE 'DARRAY.INC'
C
c      DATA ILEGAL/ZEE/
      data ilegal/z'ee'/
C
C
      ENTRY PUNCHD(N,A,J,K)
C
      INFIL=A
C
      M=N
C
      IF (K.LE.0) THEN
         L=1
         DO 10 I=1,N
           IF ((INFIL(I:I).EQ.' ').AND.((K.EQ.0).OR.(K.EQ.-2))) THEN
              GO TO 10
           ELSE IF ((INFIL(I:I).EQ.'.').AND.(K.LT.0)) THEN
              GO TO 10
           ELSE
              OUTFIL(L:L)=INFIL(I:I)
              L=L+1
           END IF
   10    CONTINUE
         M=L-1
      ELSE
C
      OUTFIL=INFIL
C
      END IF
C
C.....CONVERT TO REQUIRED TAPE CODE
C
      JC=0
      DO 100 I=1,M
      IC=ICHAR(OUTFIL(I:I))+1
      IF (PUNCOD(IC).EQ.ILEGAL) THEN
         CALL CFORM('**** ILLEGAL CHARACTER CONVERSION IN PUNCHC ****',
     1              DARRAY,2,48)
         CALL CPRINT(DARRAY)
         GO TO 100
      END IF
C
      JC=JC+1
      PUNOUT(JC)=PUNCOD(IC)
  100 CONTINUE
C
C.....OUTPUT TO PUNCH FILE, JC IS NO OF BYTES
C
      CALL TAPEPN(PUNOUT,JC)
      J=JC
      RETURN
      END
