**** SOURCE FILE : GCHK.V01   ***
*
      SUBROUTINE GCHK(SURF,SIDE,R ,TE ,TA ,NPAT ,UP ,VP ,
     +                          RL,TEL,TAL,NPATL,UPL,VPL,
     +                          TOLCOM,TOLI,TOLO,GFAC,IRET)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DIMENSION SURF(*),R(32),TE(3),TA(3),RL(32),TEL(3),TAL(3)
      DIMENSION RM(32),TP(3),TPL(3),XTP(3),XTPL(3),DEV(3),TN(3)
C
      CHARACTER*20 BADMSG
C
      INCLUDE 'IBUGG.INC'
C
      DATA Z1EM10/1.0D-10/,ZERO/0.0D0/,ONE/1.0D0/
C
C.... COMPUTE PARAMETRIC MIDPINT
C
      CALL MIDPNT(SURF,NPAT,UP,VP,NPATL,UPL,VPL,RM)
C
C.... COMPUTE SURFACE CURVATURE AT MIDPOINT IN CHORD DIRECTION
C
      CALL MIDKUR(RM,R,RL,SIDE,SKRM)
C
C.... COMPUTE TOOL CONTACT POINT AT CURRENT AND LAST LOCATION
C     AND TOOL NORMAL AT MIDPOINT
C
      OFFSET=TOLCOM*SIDE
      DO 10 I=1,3
        TP(I)=R(I)+OFFSET*R(28+I)
        TPL(I)=RL(I)+OFFSET*RL(28+I)
        TN(I)=SIDE*RM(I+28)
   10 CONTINUE
C
C.... COMPUTE THE TWO TOOL POINTS, XTP AND XTPL THAT CORRESPOND
C     TO THE TOOL CONTACT POINT AT THE ALTERNATIVE TOOL LOCATION
C
      CALL XTPCAL(TP,TE,TA,TPL,TEL,TAL,XTP,XTPL)
C
C.... COMPUTE DEVIATION OF MIDPOINT FROM CHORD
C     BETWEEN TOOL CONTACT POINTS
C
      CALL DEVCAL(RM,TN,TP,TPL,DEV(1))
C
C.... COMPUTE DEVIATION OF MIDPOINT FROM CHORD
C     BETWEEN TOOL CONTACT POINT AND CORRESPONDING POINT (XTP OR XTPL)
C     FOR BOTH TOOL LOCATIONS
C
      CALL DEVCAL(RM,TN,TP,XTPL,DEV(2))
      CALL DEVCAL(RM,TN,TPL,XTP,DEV(3))
C
C.... COMPUTE MAXIMUM AND MINIMUM DEVIATION
C
      DEVMAX=ZERO
      DEVMIN=ZERO
      DO 20 I=1,3
        IF (DEV(I).GT.DEVMAX) DEVMAX=DEV(I)
        IF (DEV(I).LT.DEVMIN) DEVMIN=DEV(I)
  20  CONTINUE
C
C.... IS THE APPROPRIATE TOLERANCE BAND VIOLATED
C
      IF ( (SKRM.GT.ZERO).AND.(ABS(DEVMIN).GT.TOLO) ) THEN
C.... EXCESS MATERIAL WILL BE LEFT ON
        IRET=-1
C.... COMPUTE STEP REDUCTION FACTOR
        IF (TOLO.GT.Z1EM10) THEN
          GFAC=TOLO/ABS(DEVMIN)
          GFAC=MIN(GFAC,0.95D0)
        ELSE
          GFAC=0.75
        ENDIF
      ELSE IF ( (SKRM.LT.ZERO).AND.(DEVMAX.GT.TOLI) ) THEN
C.... GOUGING OF SURFACE WILL OCCUR
        IRET=1
C.... COMPUTE STEP REDUCTION FACTOR
        IF (TOLI.GT.Z1EM10) THEN
          GFAC=TOLI/DEVMAX
          GFAC=MIN(GFAC,0.95D0)
        ELSE
          GFAC=0.75
        ENDIF
      ELSE
        IRET=0
        GFAC=ONE
      ENDIF
C
      IF (IBUG.EQ.11) THEN
         BADMSG= ' AFTER GCHK'
         CALL CPRINT(BADMSG)
         CALL BAD(1,1,'SKRM',SKRM)
         CALL BAD(1,1,'TOLI',TOLI)
         CALL BAD(-1,1,'TOLO',TOLO)
         CALL BAD(1,1,'DVMX',DEVMAX)
         CALL BAD(1,1,'DVMN',DEVMIN)
         CALL BAD(1,0,'IRET',IRET)
         CALL BAD(-1,1,'GFAC',GFAC)
      ENDIF
C
      END
