**** SOURCE FILE : M0011518.V01   ***
*
CK    SUBROUTINE    ABW       FORT      3-D     GEOLAN       WEISS
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++790724
C   LETZTE AENDERUNG: D790724.T0835
C     SUBROUTINE ABW(X1,X2,T1,T2,ERR)
C     *********************************
C
C     KURZBESCHREIBUNG:
C     DAS UNTERPROGRAMM BERECHNET DIE MAXIMALE ABWEICHUNG EINER
C     SPLINE-KURVE ZWISCHEN ZWEI PUNKTEN VON DER VERBINDENDEN
C     GERADEN
C
C     EINGABE:
C     X1      KOORDINATEN DES ERSTEN PUNKTES, BLOCK DER LAENGE 3
C     X2      KOORDINATEN DES ZWEITEN PUNKTES, BLOCK DER LAENGE 3
C     T1      TANGENTENVEKTOR IM ERSTEN PUNKT,BLOCK DER LAENGE 3
C     T2      TANGENTENVEKTOR IM ZWEITEN PUNKT, BLOCK DER LAENGE 3
C
C     ERGEBNIS:
C     ERR     GESCHAETZTE ABSOLUTE ABWEICHUNG
C
C     UNTERPROGRAMME: DOTF FUER SCALP
C
C     ERSTELLER: WEISS, GDT4
C                PLARRE,CAMI-UMSTELLUNG
C
      SUBROUTINE ABW(X1,X2,T1,T2,ERR)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DOUBLE PRECISION X1(3),X2(3),T1(3),T2(3),A(3)
      KQ = 6
      PI = 3.1415926535
      DO 1 I = 1,3
    1 A(I) = X2(I) - X1(I)
      CALL DOTF(AL,A,A)
      AL = DSQRT(AL)
      CALL DOTF(COS1,A,T1)
      COS1 = COS1/AL
      IF(DABS(COS1) .LE. 1.0) GOTO 3
      IF (COS1 .GT. 1.0) COS1 = 1.0
      IF (COS1 .LT. -1.0) COS1 = -1.0
    3 B1  = DARCOS(COS1)
      BETA = B1*180.0/PI
      CALL DOTF(COS2,A,T2)
      COS2 = COS2/AL
      IF (DABS(COS2) .LE. 1.0) GOTO 5
      IF (COS2 .LT. -1.0) COS2 = -1.0
      IF (COS2 .GT. 1.0) COS2 = 1.0
    5 C1 = DARCOS(COS2)
      GAMMA = C1*180.0/PI
      A1 = (180.0 - BETA - GAMMA)*PI/180.0
      C = AL*DSIN(C1)/DSIN(A1)
      ERR = C*DSIN(B1)*0.1
      ERR = DABS(ERR)
      IF (KQ .NE. 0) WRITE(KQ,2)X1,X2,T1,T2,ERR
    2 FORMAT(' ABW:X1,X2,T1,T2,ERR:',
     */,1H ,13F10.4)
      RETURN
      END
