**** SOURCE FILE : ADDRSS00.ORG   ***
*
      INTEGER FUNCTION ADDRSS(X)
*
*  * ADDRSS *   VAX11 FORTRAN VERSION    18.2.82  E.MCLELLAN
*
*  PURPOSE     ADDRSS RETURNS AN INTEGER WHICH IS THE
*              ACTUAL MACHINE ADDRESS OF THE ARGUMENT
*
*  CALLING SEQUENCE
*              VALUE=ADDRSS(X)
*  ARGUMENTS
*              X  VARIABLE WHOSE ADDRESS IS TO BE RETURNED
*
      DOUBLE PRECISION X
c      ADDRSS=%LOC(X)
c      addrss=loc(x)
C
      RETURN
      END
