**** SOURCE FILE : M0002795.V03   ***
*
C
C.....FORTRAN SUBROUTINE             APT027...              3/1/68   GK
C
C              FORTRAN SUBROUTINE APT027
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A CIRCLE DEFINED
C              AS PASSING THROUGH THREE GIVEN POINTS BY THE
C              FOLLOWING APT STATEMENT
C              RESULT = CIRCLE/PN1, PN2, PN3
C
C LINKAGE      CALL APT027 (RESULT, PN1, PN2, PN3)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM OF
C                      THE RESULTING CIRCLE
C              PN1     ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE FIRST INPUT POINT
C              PN2     ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE SECOND INPUT POINT
C              PN3     ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE THIRD INPUT POINT
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT075
C              SUBROUTINE          APT081
C              SUBROUTINE          APT083
C              SUBROUTINE          DEFEXT
C              SUBROUTINE          ERROR
C              REAL FUNCTION       SQRT
C
      SUBROUTINE APT027(RESULT,PN1,PN2,PN3)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION RESULT(7),PN1(3),PN2(3),PN3(3)
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'ZNUMBR.INC'
      INCLUDE 'IDEF.INC'
      INCLUDE 'ISHR16.INC'
      INCLUDE 'KNUMBR.INC'
C
C
      DATA ZLIT1/4.D0/
C
C...     TRANSFORM COORDINATES, FORM P ARRAY, CHECK VALIDITY
C...     WARNING IF POINTS NOT IN HORIZONTAL PLANE
      CALL APT081 (PN3,0 )
      DO 10 I=1,3
   10 P(I+8) =P(I)
      CALL APT081 (PN2,0)
      DO 20 I=1,3
   20 P(I+4) =P(I)
      CALL APT081 (PN1,0)
      IF (P(3).NE.P(7).OR. P(3).NE.P(11)) CALL ERROR(K30,'APT027  ')
C
C
C...     SOLVE 3 SIMULTANEOUS EQUATIONS FOR COEFFICIENTS OF CIRCLE EQ.
   30 DO 40 I=1,9,4
      P(I+3)=P(I)**2+P(I+1)**2
   40 P(I+2)=Z1
      CALL APT075 (R,P)
      IF (IERROR.NE. 0) IERROR=K29
   50 R(7)=DSQRT(R(1)**2+R(2)**2+ZLIT1*R(3))/Z2
      DO 60 I=1,2
      R(I)=R(I)/Z2
   60 R(I+2)=Z0
      R(5) = Z0
      R(6) = Z1
      CALL APT083(R,KM1)
      CALL DEFEXT (RESULT)
      RETURN
       END
