**** SOURCE FILE : M0000827.V03   ***
*
C
C.....FORTRAN SUBROUTINE             APT077...              5/1/68   GK
C
C              FORTRAN SUBROUTINE APT077
C
C PURPOSE      TO SET UP THE COMPLETE PARAMETER LIST FOR THE
C              TRANSFORMATION OF THE CANONICAL FORM OF A LINE
C              OR PLANE WHEN A REFSYS STATEMENT IS IN EFFECT.
C
C LINKAGE      CALL APT077 (SI, IE)
C
C ARGUMENTS    SI      ARRAY CONTAINING THE CANONICAL FORM TO BE
C                      TRANSFORMED.
C              IE      INTEGER WHICH INDICATES TRANSFORMATION
C                      DIRECTION, AND AN ERROR CODE NUMBER WHEN
C                      AN INPUT LINE IS TO BE CHECKED TO BE SURE
C                      IT IS A VERTICAL PLANE.
C                      IE + O TRANSFORM LOCAL TO BASE
C                      IE = O TRANSFORM BASE TO LOCAL
C                      IE = O TRANSFORM BASE TO LOCAL AND CHECK
C                          FOR VERTICAL PLANE
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          TRANSF
C
      SUBROUTINE APT077 (SI,IE)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION SI(10)
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'KNUMBR.INC'
C
C
      CALL TRANSF (L,SI,K4,K4,IE)
       RETURN
       END
