**** SOURCE FILE : M0000756.V02   ***
*
C.....FORTRAN SUBROUTINE             APT006...              3/1/68   GK
C
C              FORTRAN SUBROUTINE APT006
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A POINT ON
C              THE CIRCUMFERENCE OF A CIRCLE, DEFINED SUCH
C              THAT A VECTOR FROM THE CENTER OF THE CIRCLE TO
C              THE POINT MAKES A SPECIFIED ANGLE WITH THE
C              POSITIVE X AXIS, BY THE FOLLOWING APT STATEMENT
C              RESULT = POINT/CIRC1, ATANGL, A
C
C LINKAGE      CALL APT006 (RESULT, CIRC1, A)
C
C ARGUMENT     RESULT  ARRAY TO CONTAIN THE CANONICAL FORM OF THE
C                      RESULTING POINT
C              CIRC1   ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE INPUT CIRCLE
C              A       REAL VARIABLE CONTAINING THE SIZE OF
C                      THE ANGLE IN DEGREES
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT083
C              SUBROUTINE          APT001
C
      SUBROUTINE APT006 (RESULT,CIRC1,ANG)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION RESULT(3),CIRC1(7)
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'ZNUMBR.INC'
      INCLUDE 'ISHR16.INC'
      INCLUDE 'KNUMBR.INC'
C
C
C
C...     TRANSFORM CANONICAL FORM AND CHECK INPUT VALIDITY
C
      CALL APT083(CIRC1,K7)
      SC(1) =ANG *DEGRAD
      SC(2)=DSIN(SC(1))
      SC(1)=DCOS(SC(1))
      DO 10 I =1,2
   10 RESULT(I) =C(I) +C(7)*SC(I)
      CALL APT001(RESULT)
       RETURN
       END
