**** SOURCE FILE : M0000770.V03   ***
*
C
C.....FORTRAN SUBROUTINE             APT020...              3/1/68   GK
C
C              FORTRAN SUBROUTINE APT020
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A LINE DEFINED
C              AS PARALLEL TO, AND AT A GIVEN DISTANCE FROM A
C              GIVEN LINE BY THE FOLLOWING APT STATEMENT
C              RESULT = LINE/PARLEL, LN, ****, DT
C                   **** = XLARGE, YLARGE, XSMALL, YSMALL
C
C LINKAGE      CALL APT020 (RESULT, LN, M, DT)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM OF THE
C                      RESULTING LINE
C              LN      ARRAY CONTAINING THE CANONICAL FORM OF THE
C                      INPUT LINE
C              M       INTEGER EQUIVALENT OF THE MODIFIER
C                      1 = XLARGE
C                      2 = YLARGE
C                      4 = XSMALL
C                      5 = YSMALL
C              DT      REAL VARIABLE CONTAINING THE DISTANCE
C                      BETWEEN THE LINES
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT047
C              SUBROUTINE          APT077
C
      SUBROUTINE APT020 (RESULT,LN,MN,DT)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION(O-Z)
      DIMENSION RESULT(4),LN(4)
      DOUBLE PRECISION LN
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'ISHR16.INC'
      INCLUDE 'KNUMBR.INC'
C
C
C
C...     CHECK VALIDITY OF LN IN LOCAL SYSTEM
C
      CALL APT077 (LN, 92)
C
C...     SOLVE FOR PLANE PARLEL TO LN, DISTANCE DT - APT047 (BASE SYS)
C
      CALL APT047(RESULT,LN,MN,DT)
      RETURN
       END
