**** SOURCE FILE : M0000794.V02   ***
*
C.....FORTRAN SUBROUTINE             APT044...              6/10/68 EAN
C
C              FORTRAN SUBROUTINE APT044
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A PLANE
C              FROM THE COEFFICIENTS OF ITS EQUATION BY THE
C              FOLLOWING APT STATEMENT
C              RESULT = PLANE/A, B, C, D
C
C LINKAGE      CALL APT044 (RESULT, AN, BN, CN, DN)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM
C                      OF THE RESULTING PLANE
C              AN      REAL VARIABLE CONTAINING THE VALUE
C                      OF COEFFICIENT OF X
C              BN      REAL VARIABLE CONTAINING THE VALUE
C                      OF COEFFICIENT OF Y
C              CN      REAL VARIABLE CONTAINING THE VALUE
C                      OF COEFFICIENT OF Z
C              DN      REAL VARIABLE CONTAINING THE VALUE
C                      OF CONSTANT TERM
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT077
C              SUBROUTINE          DEFEXT
C              REAL FUNCTION       SQRT
C
      SUBROUTINE APT044 (RESULT,AN,BN,CN,DN)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION RESULT(4)
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'ZNUMBR.INC'
      INCLUDE 'IDEF.INC'
      INCLUDE 'ISHR16.INC'
      INCLUDE 'KNUMBR.INC'
C
C
C
      S1 = AN**2 +BN**2 +CN**2
      IF (S1.LE.Z1EM5) GO TO 20
      S1=DSQRT(S1)
      R(1)=AN /S1
      R(2)=BN /S1
      R(3)=CN/S1
      R(4)=DN /S1
      CALL APT077(R,KM1)
   10 CALL DEFEXT (RESULT)
      RETURN
   20 IERROR=K44
      GO TO 10
       END
