**** SOURCE FILE : M0000752.V03   ***
*
C.....FORTRAN SUBROUTINE  ....APT001         8/68                 SR
C
C LINKAGE      CALL APT001 (RESULT)
C
C ARGUMENT     RESULT  ARRAY CONTAINING THE X AND Y CO-
C              ORDINATES OF THE INPUT POINT.
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          DEFEXT
C              SUBROUTINE          APT081
C
      SUBROUTINE APT001(RESULT)
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
      DIMENSION RESULT(3)
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'ZNUMBR.INC'
      INCLUDE 'LDEF.INC'
      INCLUDE 'IDEF.INC'
      INCLUDE 'ISHR16.INC'
      INCLUDE 'KNUMBR.INC'
C
C
      IF(UNFLAG)GO TO 40
C
      RESULT(3)=Z0
C
C...     TEST FOR ZSURF
C
      IF (ZFLAG) GO TO 30
C
C...     TEST FOR REFSYS
C
      I=K1
      IF (REFFLG) I=K2
      IF (REF(I,3).EQ.Z0) GO TO 10
      RESULT(3)=(REF(I,4)-REF(I,1)*RESULT(1)-REF(I,2)*RESULT(2))/
     1          REF(I,3)
C
C...     CONVERT TO BASE SYSTEM
C
   30 CALL TRANSF(P,RESULT,K2,K3,KM1)
   40 CALL DEFEXT(RESULT)
C
      RETURN
   10 CONTINUE
      UNFLAG=.TRUE.
      GO TO 40
       END
