**** SOURCE FILE : M0000782.V03   ***
*
C
C.....FORTRAN SUBROUTINE             APT032...              3/1/68   GK
C
C              FORTRAN SUBROUTINE APT032
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A CIRCLE DEFINED
C              AS TANGENT TO A GIVEN LINE AND A GIVEN CIRCLE AND
C              HAVING A GIVEN RADIUS BY THE FOLLOWING APT STATEMENT
C              RESULT = CIRCLE/ *****, LN, *****, ***, CIR, RADIUS,
C                       RAD
C               ***** = XLARGE, YLARGE, XSMALL, YSMALL
C                 *** = IN OR OUT
C
C LINKAGE      CALL APT032 (RESULT, M1, LN, M2, M3, CIR, RAD)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM OF THE
C                      RESULTING CIRCLE
C              M1      INTEGER EQUIVALENT OF THE FIRST MODIFIER
C                             1 = XLARGE       2 = YLARGE
C                             4 = XSMALL       5 = YSMALL
C              LN      ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE INPUT LINE
C              M2      INTEGER EQUIVALENT OF THE SECOND MODIFIER
C                             1 = XLARGE       2 = YLARGE
C                             4 = XSMALL       5 = YSMALL
C              M3      INTEGER EQUIVALENT OF THIRD MODIFIER
C                             1 = IN           2 = OUT
C              CIR     ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE INPUT CIRCLE
C              RAD     REAL VARIABLE CONTAINING THE VALUE OF THE
C                      DESIRED RADIUS
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT004
C              SUBROUTINE          APT020
C              SUBROUTINE          APT078
C              REAL FUNCTION       ABS
C
      SUBROUTINE APT032 (RESULT,M1,LN,M2,M3,CIR,RAD)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION RESULT(7),LN(4),CIR(7)
      DOUBLE PRECISION LN
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'ZNUMBR.INC'
      INCLUDE 'ISHR16.INC'
      INCLUDE 'KNUMBR.INC'
C
C
C
C...     FORM VERTICAL CYLINDER WITH RADIUS RAD, TRANSFORM TO BASE SYS.
C
      CALL APT078(R(4),KM1)
      DO 10 I=1,3
   10 SC(I+10) = R(I)
      SC(14)=RAD
C
C...     DEFINE LN1 PARALLEL TO LN, RAD AWAY
C
      CALL APT020(LN1(2),LN,M1,SC(14))
C
C...     MODIFY RADIUS OF CIR BY RAD, SOLVE FOR INTERS.OF LN1 AND CIR
C
      DO 15 I=1,7
   15 C1(I+1)=CIR(I)
      DUMMY1 = M3
      C1(8)=DABS(C1(8)+(Z2*DUMMY1-Z3)*SC(14))
      DO 50 I=4,7
   50 R(I)=SC(I+7)
      CALL APT004(RESULT,M2,LN1(2),C1(2))
      DO 20 I=4,7
   20 RESULT(I)= SC(I+7)
      RETURN
       END
