**** SOURCE FILE : M0000789.V02   ***
*
C.....FORTRAN SUBROUTINE             APT039...              3/1/68   GK
C
C              FORTRAN SUBROUTINE APT039
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A VECTOR
C              DEFINED AS THE SUM OF TWO GIVEN VECTORS BY
C              THE APT FOLLOWING STATEMENTS
C              RESULT = VECTOR/VEC1, PLUS, VEC2
C
C LINKAGE      CALL APT039 (RESULT, VEC1, VEC2)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM
C                      OF THE RESULTING VECTOR
C              VEC1    ARRAY CONTAINING THE CANONICAL FORM
C                      OF THE FIRST INPUT VECTOR
C              VEC2    ARRAY CONTAINING THE CANONICAL FORM
C                      OF THE SECOND INPUT VECTOR
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          DEFEXT
C              LOGICAL FUNCTION    CKDEF
C
      SUBROUTINE APT039 (RESULT,VEC1,VEC2)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION RESULT(3),VEC1(3),VEC2(3)
      LOGICAL CKDEF
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'LDEF.INC'
      INCLUDE 'ISHR16.INC'
C
C
C
      UNFLAG=CKDEF(VEC1).OR.CKDEF(VEC2)
C
C...     RESULTANT VECTOR IS SUM OF COMPONENTS OF VEC1,VEC2
C
      DO 10 I=1,3
   10 R(I)=VEC1(I)+VEC2(I)
      CALL DEFEXT(RESULT)
      RETURN
       END
