**** SOURCE FILE : M0000757.V02   ***
*
C.....FORTRAN SUBROUTINE             APT007...              3/1/68   GK
C
C              FORTRAN SUBROUTINE APT007
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A POINT
C              DEFINED AS THE CENTER OF A CIRCLE BY THE
C              FOLLOWING APT STATEMENT
C              RESULT = POINT/CENTER, CIRC1
C
C LINKAGE      CALL APT007 (RESULT, CIRC1)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM OF THE
C                      RESULTING POINT
C              CIRC1   ARRAY CONTAINING THE CANONICAL FORM
C                      OF THE INPUT CIRCLE
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT083
C              SUBROUTINE          APT001
C
      SUBROUTINE APT007 (RESULT,CIRC1)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION(O-Z)
      DIMENSION RESULT(3),CIRC1(7)
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'ISHR16.INC'
      INCLUDE 'KNUMBR.INC'
C
C
C
C...     TRANSFORM CANONICAL FORM AND CHECK INPUT VALIDITY
C
      CALL APT083 (CIRC1,K7)
C
C...     SET X AND Y
C
      RESULT(1)=C(1)
      RESULT(2)=C(2)
C
C...     GET Z COORDINATE
C
      CALL APT001 (RESULT)
       RETURN
       END
