**** SOURCE FILE : M0000787.V02   ***
*
C.....FORTRAN SUBROUTINE             APT037...              3/1/68   GK
C
C              FORTRAN SUBROUTINE APT037
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A VECTOR DEFINED
C              AS A GIVEN SCALAR TIMES A GIVEN VECTOR OR POINT
C              BY THE FOLLOWING APT STATEMENT
C              RESULT  VECTOR/SCA, TIMES, VEC
C
C LINKAGE      CALL APT037 (RESULT, SCA, VEC)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM OF
C                      THE RESULTING VECTOR
C              SCA     REAL VARIABLE CONTAINING THE VALUE OF
C                      THE SCALAR
C              VEC     ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE INPUT VECTOR OR POINT
C
C SUBSIDIARIES TYPE                ENTRY
C              LOGICAL FUNCTION    CKDEF
C              SUBROUTINE          DEFEXT
C
      SUBROUTINE APT037 (RESULT,SCA,VEC)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION RESULT(3),VEC(3)
      LOGICAL CKDEF
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'LDEF.INC'
      INCLUDE 'ISHR16.INC'
C
C
      UNFLAG=CKDEF(VEC)
      DO 10 I=1,3
   10 R(I)=SCA*VEC(I)
      CALL DEFEXT(RESULT)
      RETURN
       END
