**** SOURCE FILE : M0000801.V02   ***
*
C.....FORTRAN SUBROUTINE             APT051...              3/1/68   GK
C
C              FORTRAN SUBROUTINE APT051
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A SPHERE
C              DEFINED AS HAVING ITS CENTER AT A GIVEN POINT
C              AND PASSING THROUGH A GIVEN POINT BY THE
C              FOLLOWING APT STATEMENT
C              RESULT = SPHERE/CENTER, PN1, PN2
C
C LINKAGE      CALL APT051 (RESULT, PN1, PN2)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN CANONICAL FORM OF THE
C                      RESULTING SPHERE
C              PN1     ARRAY CONTAINING CANONICAL FORM OF THE
C                      INPUT POINT (CENTER)
C              PN2     ARRAY CONTAINING CANONICAL FORM OF THE
C                      INPUT POINT (ON SPHERE)
C
C SUBSIDIARIES TYPE                ENTRY
C              LOGICAL FUNCTION    CKDEF
C              SUBROUTINE          DEFEXT
C              REAL FUNCTION       SQRT
C
      SUBROUTINE APT051 (RESULT,PN1,PN2)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION RESULT(4),PN1(3),PN2(3)
      LOGICAL CKDEF
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'LDEF.INC'
      INCLUDE 'ISHR16.INC'
C
C
C
C...     COMPUTE RADIUS OF RESULT, MOVE PN1 TO CENTER
C
      DO 10 I=1,3
      R(I)=PN1(I)
   10 R(4)=R(4)+(R(I)-PN2(I))**2
      UNFLAG=CKDEF(R).OR.CKDEF(PN2)
C
      R(4)=DSQRT(R(4))
      CALL DEFEXT(RESULT)
      RETURN
       END
