**** SOURCE FILE : M0000790.V03   ***
*
C.....FORTRAN SUBROUTINE  ....APT040         8/68                    RN
C.....FORTRAN SUBROUTINE             APT040...              3/1/68   GK
C                                      6/69      RW
C
C              FORTRAN SUBROUTINE APT040
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A VECTOR
C              DEFINED AS THE NORMALIZATION OF A GIVEN VECTOR
C              BY THE FOLLOWING APT STATEMENT
C              RESULT = VECTOR/UNIT, VC
C
C LINKAGE      CALL APT040 (RESULT, VC)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM
C                      OF THE RESULTING VECTOR
C              VC      ARRAY CONTAINING THE CANONICAL FORM
C                      OF THE INPUT VECTOR
C
C SUBSIDIARIES TYPE                ENTRY
C              LOGICAL FUNCTION    CKDEF
C              SUBROUTINE          UNDEF
C              SUBROUTINE          VNORM
C
      SUBROUTINE APT040 (RESULT,VC)
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'LDEF.INC'
C
      LOGICAL CKDEF
      DIMENSION RESULT(3),VC(3)
C
C
C
      IF (CKDEF(VC)) GO TO 10
      CALL VNORM(VC,RESULT)
      IF (PRNTON) GO TO 20
      RETURN
   10 CALL UNDEF(RESULT)
      RETURN
C...  IF PRINTON WANT TO PRINT ONLY IF CALLED BY PART PROGRAM.
   20 CALL UNPACK(RESULT,MODE,IDUMMY,IDUMMY)
      IF (MODE .EQ. 20) CALL PRINT(3,RESULT,1)
      RETURN
      END
