**** SOURCE FILE : M0000805.V02   ***
*
C.....FORTRAN SUBROUTINE             APT055...              3/1/68   GK
C
C              FORTRAN SUBROUTINE APT055
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A CYLINDER
C              DEFINED AS HAVING A GIVEN POINT ON ITS AXIS,
C              A GIVEN AXIS VECTOR AND A GIVEN RADIUS, BY
C              THE FOLLOWING APT STATEMENT
C              RESULT = CYLNDR/PN, VE, R
C
C LINKAGE      CALL APT055 (RESULT, PN, VE, RAD)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM
C                      OF THE RESULTING CYLINDER
C              PN      ARRAY CONTAINING THE CANONICAL FORM
C                      OF THE INPUT POINT
C              VE      ARRAY CONTAINING THE CANONICAL FORM
C                      OF THE INPUT VECTOR
C              RAD     REAL VARIABLE CONTAINING THE VALUE
C                      OF THE DESIRED RADIUS
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT040
C              LOGICAL FUNCTION    CKDEF
C              SUBROUTINE          DEFEXT
C              LOGICAL FUNCTION    ZVECT
C
      SUBROUTINE APT055 (RESULT,PN,VE,RAD)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION RESULT(7),PN(3),VE(3)
      LOGICAL CKDEF,ZVECT
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'LDEF.INC'
      INCLUDE 'IDEF.INC'
      INCLUDE 'ISHR16.INC'
      INCLUDE 'KNUMBR.INC'
C
C
      DATA K58/58/
C
C...     CHECK INPUT, MOVE ARGUMENTS
C
      DO 10 I=1,3
      R(I+3)=VE(I)
   10 R(I)=PN(I)
      UNFLAG=CKDEF(R)
C
C...     CHECK FOR ZERO VECTOR, NORMALIZE
C
      IF (.NOT. ZVECT(R(4))) IERROR = K58
      CALL APT040(R(4),R(4))
      R(7)=RAD
      CALL DEFEXT (RESULT)
      RETURN
       END
