**** SOURCE FILE : M0000769.V02   ***
*
C.....FORTRAN SUBROUTINE              APT019                3/6/68
C
C              FORTRAN SUBROUTINE APT019
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A LINE DEFINED
C              AS PASSING THROUGH A POINT AND PERPENDICULAR TO
C              A GIVEN LINE BY THE FOLLOWING APT STATEMENT
C              RESULT = LINE/PNT, PERPTO, LN
C
C LINKAGE      CALL APT019 (RESULT, PNT, LN)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM OF
C                      THE RESULTING LINE
C              PNT     ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE INPUT POINT
C              LN      ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE INPUT LINE
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT022
C
      SUBROUTINE APT019(RESULT,PNT,LN)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION(O-Z)
      DIMENSION RESULT(4),PNT(3),LN(4)
      DOUBLE PRECISION LN
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'ZNUMBR.INC'
      INCLUDE 'ISHR16.INC'
C
C
C
C...     USE APT022 TO FIND LINE THRU PNT, AT 90 DEGREES WITH LN
C
      CALL APT022 (RESULT,PNT,1,Z90,LN)
      RETURN
       END
