**** SOURCE FILE : M0002787.V03   ***
*
C
C.... FORTRAN SUBROUTINE              APT004               4/17/68
C
C              FORTRAN SUBROUTINE APT004
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A POINT
C              DEFINED AS THE INTERSECTION OF A LINE AND A
C              CIRCLE BY THE FOLLOWING APT STATEMENT
C              RESULT = POINT/****, INTOF, LINE1, CIRC1
C                 **** = XLARGE, YLARGE, XSMALL, OR YSMALL
C
C LINKAGE      CALL APT004 (RESULT, M, LINE1, CIRC1)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM
C                      OF THE RESULTING POINT
C              M       INTEGER EQUIVALENT OF THE MODIFIER
C                      1 = XLARGE 2 = YLARGE
C                      4 = XSMALL 5 = YSMALL
C              LINE1   ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE INPUT LINE
C              CIRC1   ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE INPUT CIRCLE
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT077
C              SUBROUTINE          APT083
C              SUBROUTINE          DEFEXT
C              SUBROUTINE          ERROR
C              SUBROUTINE          APT001
C              REAL FUNCTION       ABS
C              REAL FUNCTION       SQRT
C              REAL FUNCTION       SIGN
C
      SUBROUTINE APT004 (RESULT,MN,LINE1,CIRC1)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION(O-Z)
      DIMENSION RESULT(3),LINE1(4),CIRC1(7)
      DOUBLE PRECISION LINE1
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'ZNUMBR.INC'
      INCLUDE 'LDEF.INC'
      INCLUDE 'IDEF.INC'
      INCLUDE 'ISHR16.INC'
      INCLUDE 'KNUMBR.INC'
C
C
C
C...     TRANSFORM CANONICAL FORMS AND CHECK INPUT VALIDITY
C
      CALL APT077 (LINE1,K5)
      CALL APT083 (CIRC1,K7)
      M = MN
C
C...     COMPUTE DISTANCE FROM CENTER TO LINE AND TEST FOR INTERSECTION
C
      S1  =L(4)-L(1)*C(1)-L(2)*C(2)
      IF (DABS(DABS(S1)-C(7)).LE.Z1EM5) GO TO 270
      IF ((DABS(S1)-C(7)).GT.Z1EM5) GO TO 330
C
C...     COMPUTE CHORD LENGTH AND CHECK MODIFIER FOR VALIDITY
C
      S2 = DSQRT(C(7)**2-S1**2)
      GO TO (140,170,170,140,170),M
  140 IF (L(2)) 400,150,410
  150 CALL ERROR(K8,'APT004  ')
      IF ((M.EQ.K2).OR.(M.EQ.K3).OR.(M.EQ.K5)) GO TO 330
  170 IF (L(1)) 410,180,400
  180 CALL ERROR(K9,'APT004  ')
      IF ((M.EQ.K1).OR.(M.EQ.K4)) GO TO 330
      GO TO 140
C
C...     S(1)=RADIUS,MAKE CHORD LENGTH 0
C
  270 S2  =Z0
      S1 = DSIGN(C(7),S1)
      GO TO 430
C
C...     LINE AND CIRCLE DO NOT INTERSECT
C
  330 IERROR=K6
      UNFLAG=.TRUE.
  300 CALL DEFEXT(RESULT)
      GO TO 9999
C
C...     COMPUTE X AND Y, STORE IN RESULT AND CALL APT001 TO GET Z
C
  400 IF (M.GT.K3) GO TO 430
  420 S2=-S2
      GO TO 430
  410 IF (M.GT.K3) GO TO 420
  430 RESULT(1)=C(1)+ S1 *L(1)+ S2 *L(2)
      RESULT(2)=C(2)+S1*L(2)-S2*L(1)
      CALL APT001(RESULT)
 9999 CONTINUE
       RETURN
       END
