**** SOURCE FILE : M0011443.W01   ***
*
      SUBROUTINE APT110(ARG1,ARG2)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C-- MAIN PROGRAM FOR REGIONAL MILLING(SMIL OR SCON)
C-- PART PROGRAMMER INPUT LANGUAGE IS RESIDENT IN BLANK COMMON.
C
      INCLUDE 'BLANKCOM.INC'
C
      COMMON/IBUGG/IBUG,IPCOLC,IPCOMC
      CHARACTER*6 XSMIL,TEST,BADMSG*66
      DIMENSION XSMIL(7),FDUMMY(2)
      DATA XSMIL/'SCON  ','SMIL  ','GCLEAR','GOMILL',
     +           'INTSEC','GOLOFT','PLOTFT'/
      DATA ZERO/0.0D0/
C
      NT=SSCAN(2)
      NT=NT*2
      IF(IBUG.EQ.11) CALL BAD(-NT,2,'CANN',SSCAN)
      CALL HOLFRM(ARG1,TEST,1,6,NWD)
      DO 8 I=1,7
      IF(TEST.NE.XSMIL(I))GOTO 8
      MODE=5
      FDUMMY(1)=ZERO
      FDUMMY(2)=SSCAN(2)-1.D0
      ZWI=SSCAN(1)
      CALL APT094(MODE,FDUMMY,SSCAN)
      SSCAN(1)=ZWI
      GOTO(1,2,3,4,5,6,6),I
    1 CALL SCON
      GOTO 30
    2 CALL SMIL
      GOTO 30
    3 CALL GCLEAR(ARG2)
      GOTO 30
    4 CALL GOMILL
      GOTO 30
    5 CALL INTSEC
      GOTO 30
    6 CALL GOLOVO(ARG2)
      GOTO 30
    8 CONTINUE
   10 BADMSG=' ARGUMENT '//TEST//' NOT VALID IN CALL TO APT110'
      CALL CPRINT(BADMSG)
   30 RETURN
      END
