**** SOURCE FILE : M0000852.V02   ***
*
C.....FORTRAN SUBROUTINE             APT232...              4/1/68   GK
      SUBROUTINE APT232(NUMBER,TOLRNS,TAUS,ONE)
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
C
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'SV.INC'
      INCLUDE 'ZNUMBR.INC'
      INCLUDE 'ISV.INC'
      INCLUDE 'IFXCOR.INC'
      INCLUDE 'ISHR18.INC'
      INCLUDE 'KNUMBR.INC'
      dimension tolrns(4),taus(1)
C
      DATA ZLIT1/.02D0/
C
C
C
c      DIMENSION TOLRNS(4),TAUS(1)
      IS=IPS
      DO 50 I=1,NUMSFS
   10 TAUS(IS)=ONE*TOLRNS(I)
      TAU(IS)=TAU1(IS)-TAU2(IS)
      EPS1(IS)=Z1EM1*TAU(IS)
      EPS2(IS)=Z1-EPS1(IS)
      EPS3(IS)=Z2*EPS1(IS)
      EPS4(IS)=Z2*TAU(IS)
      EPS6(IS) = ZLIT1*EPS1(IS)
      EPS8(IS)=EPS1(IS)
      IF(IS-ICS)20,30,30
   20 IS=IS+LSV
      IF(NUMBER-I)10,10,50
   30 IF(I-NUMBER)40,60,60
   40 IS=IS+LSV1
   50 CONTINUE
   60 JENT(IPS) = K1
      JENT(IDS) = K1
C
C
      RETURN
       END
