**** SOURCE FILE : M0000442.V02   ***
*
C
C.....FORTRAN SUBROUTINE                APT341...            8/1/68  AR
C
C PURPOSE      COMPUTES THE ALTERED TOOL POSITION. THE TILT
C              ANGLE IS PRORATED OVER THE TOTAL MOVE FROM
C              VTLAXS/ON TO OFF
C LINKAGE      CALL APT341
C ARGUMENTS    NONE
C SUBSIDIARIES APT315,APT342
C********************************************************************
      SUBROUTINE APT341
C***********************************************************************
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
C********************************************************************
C     SYSTEM COMMON,DIMENSION, AND EQUIVALENCE STATEMENTS
      COMMON /EDITOR/EDITOR
C
      DIMENSION EDITOR(1500)
C
      DIMENSION  AREA1(1500), AREA2(1000), AREA3(250)
      EQUIVALENCE (EDITOR(1500),AREA1 (1500),AREA2 (1000),AREA3 (250))
      EQUIVALENCE  (AREA3(82),X1),  (AREA3(83),X2),
     +             (AREA3(87),Y1),  (AREA3(88),Y2)
      COMMON/R5AXIS/
     1Z1    ,Z2    ,ZSTART,YSTART,XSTART,ZD    ,YD    ,XD    ,ZCV   ,
     2YCV   ,XCV   ,ZDO   ,YDO   ,XDO   ,ZCC  ,YCC    ,XCC    ,ZUN   ,
     3YUN   ,XUN   ,ZTR   ,YTR   ,XTR   ,ZTA   ,YTA   ,XTA   ,Z     ,
     4STANG ,ENDANG,DANG  ,CANG  ,DLNGTH,TLNGTH,CUTTER,TEST  ,CRADUS
      COMMON/I5AXIS/
     1IVTFLG,IS,IR,IL,IE,JSUBER,IABOVE,NRECEX,NRECCL,NCFLSV
C
C...    PRORATE TILT ANGLE
      CANG=STANG+(DLNGTH/TLNGTH)*DANG
      TSIN=DSIN(CANG)
      TSIN1 =DABS(TSIN)
      TCOS=DCOS(CANG)
      CALL APT342(ZCV,ZUN,ZTR)
      CALL APT315(ZTR,ZTR)
C...    IS CANG .GT. 80 DEGREES
      IF(DABS(TCOS)-.1736) 5, 5, 90
90    CONTINUE
C...    CALCULATE XYZ COORDINATES OF NEW CUTTER POSITION
      IF(CRADUS)  100, 110, 100
100   CONTINUE
      Z = CRADUS*(1.0-TCOS)+(CUTTER-CRADUS)*TSIN1
      GOTO  120
110   CONTINUE
      Z =DABS(CUTTER*TSIN)
  120 IF(CANG*ZUN)  130, 150, 150
  130 IF(CRADUS)   140, 170, 140
  140 TEST = CRADUS*(TCOS-TSIN1+(TSIN1-1.0)/TCOS)-CUTTER*(TCOS-2.0/TCOS
     1+1.0)
      TEST = -TEST
      GOTO 9
  150 IF(CRADUS)  160,  8, 160
  160 TEST = CRADUS*(TCOS-TSIN1+(TSIN1-1.0)/TCOS)+CUTTER*(1.0-TCOS)
      GOTO 9
  170 IF(IABOVE)  3,  6,  3
    3 Z = -Z
      GOTO 8
    5 JSUBER=30007
C...    ERROR 30007 - TILT ANGLE IS GREATER THAN 80 DEGREES.
      GOTO  40
    6 TEST =-(2.0*CUTTER/TCOS-CUTTER-CUTTER*TCOS)
      GOTO 9
    8 TEST = CUTTER*(1.0-TCOS)
    9 XDO = TEST*XTR
      YDO =TEST*YTR
      ZDO =TEST*ZTR
      XCC=X2+XDO
      YCC=Y2+YDO
      ZCC=Z2+Z
C...    CALCULATE IJK COMPONENTS OF NEW TLAXIS VECTOR
      XTR=TCOS*XTR
      YTR=TCOS*YTR
      IF(ZUN) 10, 20,20
   10 ZTR=TSIN
      CALL APT342(ZCV,ZTR,ZTA)
      GOTO 30
   20 ZTR=-TSIN
      CALL APT342(ZTR,ZCV,ZTA)
   30 CALL APT315(ZTA,ZTA)
      X1=X2
      Y1=Y2
      Z1=Z2
   40 CONTINUE
      RETURN
       END
