**** SOURCE FILE : M0000428.V05   ***
*
C
C.....FORTRAN SUBROUTINE                   APT312
C PURPOSE      TO BLOCK AND WRITE CLFILE AND TO AUGMENT EACH
C              RECORD WRITTEN BY A UNIQUE SEQUENCE NUMBER.
C LINKAGE      CALL APT312
C ARGUMENTS    NONE
C SUBSIDIARIES NONE
      SUBROUTINE APT312
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
C
C       THIS ROUTINE BLOCKS AND WRITES CLFILE FROM RECORD
C
      COMMON /EDITOR/EDITOR
      DIMENSION  EDITOR(1500),RECORD(256),IRECRD(256),JRECRD(512)
      DOUBLE PRECISION IRECRD
      EQUIVALENCE  (EDITOR(1),IRECRD(1),RECORD(1),JRECRD(1))
      EQUIVALENCE  (EDITOR(388),NRECN1), (JRECRD(6),NUMWDS)
      EQUIVALENCE (EDITOR(477),SAVSEQ)
      CHARACTER*8 AERR,TEST
      CHARACTER*4 KFINI,ATEST
C
C...            SYSTEM I/O FILE NAMES
C
      INCLUDE 'SYMFIL.INC'
      INTEGER EBUFF(516)
      DATA K/2/,N/0/,KFINI/'FINI'/,EBUFF(1)/1/
      DATA AERR /'AERR    '/
C
      CALL HOLFRM(RECORD(1),TEST,1,8,NWD)
      IF (TEST .NE. AERR) GO TO 10
      IREC=JRECRD(4)
      GO TO 20
C
   10 IREC=(JRECRD(4))/10000
      IREC=JRECRD(4)-IREC*10000
      IREC=IREC+NRECN1*10000
      JRECRD(4)=IREC
      SAVSEQ=IRECRD(2)
   20 NRECN1=NRECN1+1
C.... IF APT4 TYPE POST PROCESSOR USE FORTRAN READ STATEMENT,
C     USE NEXT FORTRAN WRITE
C     WRITE(CLFILE) RECORD(1),IPOW,IREC,IPOW,NUMWDS,
C    1  (RECORD(I+3),I=1,NUMWDS)
C..... IF APT4 TYPE POST PROCESSOR USE APT4 I/O,
C      USE NEXT APT4 I/O WRITE
      J=(NUMWDS+3)*2
C
      IF(K+J.GT.514) GO TO 101
  110 N = N + 1
      EBUFF(K+1) = N
      EBUFF(K+2) = J
      K = K + 2
      DO 120 I = 1,J
      K = K + 1
  120 EBUFF(K) = JRECRD(I)
      CALL HOLFRM(JRECRD(1),ATEST,1,4,NWD)
      IF(ATEST.EQ.KFINI) GO TO 130
      RETURN
  101 EBUFF(2) = N
      NR = 0
      CALL AWRITE(CLFILE,NR,EBUFF,K,IR)
      K = 2
      EBUFF(1) = N + 1
      GO TO 110
  130 EBUFF(2) = N
      NR = 0
      CALL AWRITE(CLFILE,NR,EBUFF,K,IR)
      RETURN
      END
