**** SOURCE FILE : M0002942.V03   ***
*
C
C.....FORTRAN SUBROUTINE                   APT314
C PURPOSE      TO READ EXFILE OR AN OLD CLFILE AND PLACE THE
C              RECORD IN THE ARRAY RECORD.
C LINKAGE      CALL APT314
C ARGUMENTS    NONE
C SUBSIDIARIES NONE
      SUBROUTINE APT314 (NTAPE,NREC)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
C
C       THIS SUBROUTINE READS AND UNBLOCKS CLFILE INTO RECORD
C
      COMMON /EDITOR/EDITOR
      DIMENSION  EDITOR(1500),RECORD(256),IRECRD(256),JRECRD(512)
      DOUBLE PRECISION IRECRD
      EQUIVALENCE  (EDITOR(1),IRECRD(1),RECORD(1),JRECRD(1))
C
      INTEGER EBUFF(516)
      IF(NREC.EQ.0)NREC=1
      IF(NREC.NE.-1) GO TO 100
      N=0
      NB=0
      M=0
      K=3
      RETURN
C
  100 IF(NREC.GT.M) GO TO 10
      IF(NREC.LT.N) GO TO 20
      IF(NREC.EQ.EBUFF(K)) GO TO 30
      K=3
    3 IF(NREC.EQ.EBUFF(K)) GO TO 30
      K=K+EBUFF(K+1)+2
      IF(K.GT.516) CALL HELP
      GO TO 3
   30 K=K+1
      L=EBUFF(K)
      DO 31 I=1,L
   31 JRECRD(I)=EBUFF(K+I)
      K=K+L+1
      RETURN
   10 NB=NB+1
   15 K=516
      CALL AREAD(NTAPE,NB,EBUFF,K,IR)
      K=3
      N=EBUFF(1)
      M=EBUFF(2)
      GO TO 100
   20 NB=NB-1
      GO TO 15
      END
