**** SOURCE FILE : M0006617.V01   ***
*
C
C              FORTRAN SUBROUTINE ARGGEN
C
C LINKAGE      SUBROUTINE ARGGEN
C
C          SUBSIDIARIES                  CALLED BY
C          TYPE          ENTRY           TYPE          ENTRY
C          SUBROUTINE    ARGCVT          SUBROUTINE    PRO020
C                                        SUBROUTINE    PRO021
C                                        SUBROUTINE    PRO026
C                                        SUBROUTINE    RECOG
C
      SUBROUTINE ARGGEN
C
      IMPLICIT INTEGER (A-Z)
C
C        2.    STACK AND POINTER STORAGE
C
      COMMON/STKLST/STKLST
      DIMENSION STKLST(300),ARGSTK(99)
C ARGTOP:      POINTER TO LAST ARGSTK ENTRY
      EQUIVALENCE (ARGTOP,STKLST(2))
C ARGSTK:      ARGUMENT STACK
      EQUIVALENCE (ARGSTK(1),STKLST(202))
C*
C PURPOSE      OUTPUTS ENTIRE CONTENTS OF THE ARGUMENT
C              STACK (ARGSTK) TO THE I.L. INTERNAL RECORD
C              IMAGE (ILFILE).
C NOTES        THE ARGUMENTS ARE PLACED IN ILFILE IN THE
C              REVERSE ORDER IN WHICH THEY ARE STORED IN
C              ARGSTK.
C**
C...     FETCH ITEMS FROM ARGSTK IN REVERSE ORDER TO THAT IN WHICH
C...     THEY WERE INSERTED, AND OUTPUT TO ILFILE USING ARGCVT.
C
      DO 1 II = 1,ARGTOP
      I = ARGTOP-II+1
      K = ARGSTK(I)
    1 CALL ARGCVT(K)
C
C...     SET ARGTOP TO ZERO (I.E. CLEAR ARGSTK) AND RETURN
C
      ARGTOP = 0
      RETURN
       END
