**** SOURCE FILE : BDINID.ORG   ***
*
      BLOCK DATA BDINID
C
C.... INITIALIZE INTERFERENCE CHECKING INITIAL DATA
C
      INCLUDE 'INIDAT.INC'
C
      PARAMETER (MXNP24=24*MXNP)
      DATA CXHULL/MXNP24*0.D0/,DULIM/MXNP*0.D0/,DVLIM/MXNP*0.D0/
      DATA CURMAX/MXNP*0.D0/,CURMIN/MXNP*0.D0/
      DATA NCXHUL/MXNP*0.D0/,NGP/0/,ICURSF/0/
C
      END
