**** SOURCE FILE : M0012242.V01   ***
*
      BLOCK DATA BDPLGL
C
C  INITIALISE COMMON FOR  >GOLOFT/PLOTFT<
C
C
C  VALUES FOR  >GOLOFT/PLOTFT<
      INTEGER IPLGO(26)
C
C  USED CUTTER SEGMENT
      INTEGER JCSEG
C
C  NUMBER OF VALID CUTTER SEGMENTS
      INTEGER NCSEG
C
C  CUTTER SEGMENT IN TLLDAT ARRAYS
      INTEGER ICSEG(10)
C
C  NATURE OF SEGMENT
      INTEGER NLIOCI(10)
C
C  COMPONENTS OF SEGMENT AND UNIT NORMAL POINTING INTO THE CUTTER
      DOUBLE PRECISION COSAL(10)
      DOUBLE PRECISION SINAL(10)
C
C  DISTANCE PARALLEL TO THE CUTTER AXIS
      DOUBLE PRECISION CUTY(10)
C
C  DISTANCE TO THE CUTTER AXIS
      DOUBLE PRECISION CUTX(10)
C
C  ELEMENT LENGTH
      DOUBLE PRECISION CUTL(10)
C
C  VECTOR-COMPONENTS OF THE TOOL-AXIS-VECTOR
      DOUBLE PRECISION VTA(3)
C
      COMMON/PLGOL/IPLGO,JCSEG,NCSEG,ICSEG,NLIOCI,
     *             COSAL,SINAL,
     *             CUTY,CUTX,CUTL,
     *             VTA
C
      DATA IPLGO  /26*0/
      DATA JCSEG  /0/
      DATA NCSEG  /0/
      DATA ICSEG  /10*0/
      DATA NLIOCI /10*0/
      DATA SINAL  /10*0.D0/
      DATA COSAL  /10*0.D0/
      DATA CUTY   /10*0.D0/
      DATA CUTX   /10*0.D0/
      DATA CUTL   /10*0.D0/
      DATA VTA    /3*0.D0/
C
      END
