**** SOURCE FILE : BDSDP000.ORG   ***
*
      BLOCK DATA BDSDP
C
C  PURPOSE TO INITIALIZE SYSTEM DEPENDENT PARAMETERS
C
      INCLUDE 'SDP.INC'
C
C     NBCHAR:  NO. OF BITS PER BYTE
c     DATA NBCHAR/8/
C     NBWRD:   NO OF BITS PER WORD
c     DATA NBWRD/32/
C     IWRD:    NO OF BYTES PER WORD
c     DATA IWRD/4/
C     IFAC:    BYTE LEFT SHIFT MULTIPLICATION FACTOR
c     DATA IFAC/256/
      data nbchar,nbwrd,iwrd,ifac/8,32,4,256/
C
      END
