**** SOURCE FILE : M0001050.W01   ***
*
      SUBROUTINE CHKSET(IDTYPE,PDIR,PAR,IFIN)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON/IBUGG/IBUG,IPCOLC,IPCOLM
      DIMENSION PLIM(4),PAR(*)
      CHARACTER*20 BADMSG
      DATA ZERO,ONE,SMAL/0.0D0,1.0D0,1.0D-14/
C---PURPOSE IS TO CHECK WHETHER PARAMETER PAIR PAR(1-2) IS
C--- WITHIN LEGITIMATE BOUNDS.  THESE BOUNDS ARE SET WHEN
C--- IFIN=-121 ON INPUT.  OTHERWISE IFIN NON ZERO ON OUTPUT
C--- MEANS THAT P IS OUT OF BOUNDS.  P WILL ALSO BE TRUNCATED
C--- TO LIE WITHIN BOUNDS.
C
      IF(IFIN.NE.-121) GO TO 15
      DO 10 I=1,4
   10 PLIM(I)=PAR(I)
      GO TO 999
C
   15 CONTINUE
      IFIN=0
      ITYP=2
      IF(IDTYPE.LT.2) ITYP=1
      I=ITYP
      INDEX=2*I-1
      IF(PAR(I).GT.PLIM(INDEX)+SMAL) GO TO 20
      PAR(I)=PLIM(INDEX)
      IF(PDIR.GT.ZERO) GO TO 20
      IFIN=1
   20 CONTINUE
      INDEX=2*I
      IF(PAR(I).LT.PLIM(INDEX)-SMAL) GO TO 40
      PAR(I)=PLIM(INDEX)
      IF(PDIR.LT.ZERO) GO TO 40
      IFIN=1
   40 CONTINUE
C
  999 CONTINUE
      IF(IBUG.NE.11) GO TO 1999
      CALL BAD(-1,0,' ',0)
      BADMSG=' AFTER CHKSET'
      CALL CPRINT(BADMSG)
      CALL BAD(1,1,'PDIR',PDIR)
      CALL BAD(1,0,'IFIN',IFIN)
      CALL BAD(-2,1,'PAR ',PAR)
 1999 CONTINUE
      RETURN
      END
