**** SOURCE FILE : M0001051.V01   ***
*
      SUBROUTINE CHKTOP(U,V,ITOP,IOK)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DIMENSION ITOP(6,4)
      dimension icomp(2,3,3)
      DATA ZERO,ONE/0.0D0,1.0D0/
c      DIMENSION ICOMP(2,3,3)
      DATA ICOMP/ 1,2, 1,0, 1,3, 2,0, 0,0, 3,0, 2,4, 4,0, 4,3/
C           /-PURPOSE IS TO SEE IF U,V, VALUES OF PATCH WITH TOPOLOGY
C           /-TABLE ITOP ARE IN A VALID SECTOR FOR THIS SURFACE
C           /-IOK=0 MEANS SECTOR IS OKAY. OTHERWISE IOK POINTS TO INVALI
C           /-SECTOR
C           /-NOTE THAT UNIT SQUARE DIVIDES SPACE INTO 9 SECTORS
C
C           /-FIRST DETERMINE THE SECTOR OF U,V
      IU=2
      IF(U.LT.ZERO) IU=1
      IF(U.GT.ONE) IU=3
      IV=2
      IF(V.LT.ZERO) IV=1
      IF(V.GT.ONE) IV=3
C           /-NOW COMPARE THIS SECTOR FOR FREE BOUNDARIES
      IOK=0
      DO 10 J=1,2
      K=ICOMP(J,IU,IV)
      IF(K.EQ.0) GO TO 10
      IF(ITOP(2,K).NE.0) IOK=ITOP(2,K)
   10 CONTINUE
      RETURN
      END
