**** SOURCE FILE : M0006626.W04   ***
*
C
C              FORTRAN SUBROUTINE CILOUT
C
C LINKAGE      SUBROUTINE CILOUT(COMAND,COUNT,CODE)
C
C          SUBSIDIARIES                  CALLED BY
C          TYPE          ENTRY           TYPE          ENTRY
C          SUBROUTINE    HOLFRM           SUBROUTINE    ICMPRS
C          SUBROUTINE    CPRINT
C          SUBROUTINE    ICONV
C          SUBROUTINE    RLSBUF
C          SUBROUTINE    ABCDBN
C
      SUBROUTINE CILOUT(COMAND,COUNT,CODE)
C
      IMPLICIT INTEGER (A-Z)
C
C        1.    NAME TABLE AND TABLE LIMITS
C
      INCLUDE 'NAMETB.INC'
C
C       14.    I. L. LIST OPTION FLAGS
C
      COMMON/PRT/PRT
      LOGICAL CILPRT
      DIMENSION PRT(7)
C CILPRT:      TRUE WHEN COMPRESSED I.L. PRINTING REQUESTED
      EQUIVALENCE (CILPRT,PRT(1))
C
C       20.    IO - ARRAY
C
      INCLUDE 'DARRAY.INC'
C
C       34.    COMMON BLOCK FOR INTERPRETIVE C.I.L. OUTPUT
C
      INCLUDE 'OUTBUF.INC'
C LABFLG:      INDICATES I.L. COMMAND IS LABEL (INTERPRETER)
C RSVFLG:      TRUE IF I.L. COMMAND IS A RESRV (INTERPRETER)
C IBUF:        NUMBER OF RECORDS IN BUFFER ARRAY
C ILBUF:       NUMBER OF ITEMS IN THE LABBUF ARRAY (INTERPRETER)
C BUFFER:      TEMPORARY STORAGE FOR INTERPRETER OUTPUT (PAGES)
C LABBUF:      TEMPORARY STORAGE FOR LABEL,HOLDAT ENTRY AND RESRV I.L.
C
C       45.    NUMBER TABLE INDICES
C
      INCLUDE 'NUMBLK.INC'
C
C MNMBND:      LAST NAME TABLE ENTRY TO MACRO ASSIGNED NUMBER SECTION
C  NMBRS:      QUANTITY OF NUMBERS IN THE CURRENT STATEMENT
C*
      DIMENSION CODE(90)
C**
C...     IS THIS A HOLDAT STATEMENT
C
      IF( COMAND.EQ.21)GOTO 200
      IBF=COUNT
      IF (COMAND.NE.9) IBF=COUNT+NMBRS
      GOTO 20
C
C...     IS THIS A LABEL OR RESRV STATEMENT
C
   1  IF ((LABFLG).OR.(RSVFLG)) GOTO 100
C
C...     NO
C...     CODE TO GO INTO BUFFER. TEST IF THERE IS ROOM
C
      IF((IBUF+IBF+4).GT.256)CALL RLSBUF
      BUFFER(IBUF+3) = COMAND
      BUFFER(IBUF+4) = IBF
      IBUF=IBUF+2
      IF(COUNT.EQ.0) RETURN
      DO 10 I=1,COUNT
      J=CODE(I)
      IF (J.LE.NAMMAX) GOTO 5
      IF (CODE(I-1).NE.7) GOTO 5
      J=J-NAMMAX
      CALL ABCDBN(CNUMTB(J),BUFFER(IBUF+3),1)
      IBUF=IBUF+1
      GOTO 10
    5 BUFFER(IBUF+3)=J
   10 IBUF=IBUF+1
      IF (COMAND.NE.9)NMBRS=0
      RETURN
C
C...     IS CILPRT MARKER SET
C
   20 IF(.NOT.CILPRT) GOTO 1
C
      CALL ICONV(COMAND,DARRAY,1,6)
      CALL ICONV(IBF,DARRAY,7,6)
      L=13
      DO 1000 I=1,COUNT
      IF (CODE(I).GT.NAMMAX) THEN
        IF (CODE(I-1).EQ.7) THEN
          CALL CFORM(CNUMTB(CODE(I)-NAMMAX),DARRAY,L+2,12)
          L=L+14
        ELSE
          CALL ICONV(CODE(I),DARRAY,L,6)
          L=L+6
        ENDIF
      ELSE
        CALL ICONV(CODE(I),DARRAY,L,6)
        L=L+6
      ENDIF
      IF(L.LE.106) GO TO 1000
      L=13
      CALL CPRINT(DARRAY)
 1000 CONTINUE
      CALL CPRINT(DARRAY)
      GOTO 1
C
C...     LABEL OR RESRV STATEMENT.
C        CODE TO GO INTO LABBUF. TEST IF THERE IS ROOM
C
  100 IF((ILBUF+COUNT+4).GT.254)CALL RLSBUF
      LABBUF(ILBUF+3) = COMAND
      LABBUF(ILBUF+4) = COUNT
      ILBUF=ILBUF+2
      DO 110 I=1,COUNT
      LABBUF(ILBUF+3)=CODE(I)
  110 ILBUF=ILBUF+1
      RETURN
C
C...     HOLDAT STATEMENT
C
  200 LABFLG = .TRUE.
      IF((ILBUF+2*COUNT).GT.256) CALL RLSBUF
      LABFLG = .FALSE.
      LABBUF(ILBUF+3)= COMAND
      LABBUF(ILBUF+5)=CODE(1)
      LABBUF(ILBUF+6)=CODE(2)
C
C
      LABBUF(ILBUF+4)=COUNT
      ILBUF=ILBUF+4
      DO 210 I=3,COUNT
      LABBUF(ILBUF+3)=CODE(I)
  210 ILBUF=ILBUF+1
C
C...     IS CILPRT MARKER SET
C
      IF(.NOT.CILPRT)RETURN
C
      KOUNT = CODE(2)
      CALL ICONV(COMAND,DARRAY,1,6)
      CALL ICONV(COUNT,DARRAY,7,6)
      CALL ICONV(CODE(1),DARRAY,13,6)
      CALL ICONV(CODE(2),DARRAY,19,6)
      L=3
 1001 IF(KOUNT.LE.93) GO TO 1002
      CALL HOLFRM(CODE(L),DARRAY,27,92,NWD)
      CALL CPRINT(DARRAY)
      KOUNT = KOUNT-92
      L=L+23
      GO TO 1001
 1002 CALL HOLFRM (CODE(L),DARRAY,27,KOUNT,NWD)
      CALL CPRINT(DARRAY)
      RETURN
       END
