**** SOURCE FILE : M0000396.V02   ***
*
C
C....  FORTRAN SUBROUTINE  CLRD4                          8/1/72
C  PURPOSE     TO READ CLFIL2 AND PLACE RHE RECORD IN THE ARRAY.
C  LINKAGE     CALL CLRD4  (FILE,NR,NBUFF,IR)
C
C  ARGUMENTS   FILE    FILE NUMBER IN THE SYMFIL COMMON.
C                      IF FILE=-1, RESET ALL COUNTERS FOR OTHER FILE.
C              NR      CONTAINING RECORD NUMBER TO BE RETRIEVED.
C              NBUFF   DATA ARRAY TO CONTAIN THE RETRIEVED RECORD.
C              IR      RETURN ERROR FLAG. =0 NOERROR, =1 ERROR.
C
      SUBROUTINE CLRD4  (FILE,NR,NBUFF,IR)
      INTEGER FILE,EBUFF(516),NBUFF(2)
      SAVE N,NB,M,K
      DATA N/0/,NB/0/,M/0/,K/3/
      IF(FILE.NE.-1) GO TO 100
C     INITIALIZE FLAGS
C     N IS MAXIMUM RECORD NUMBER IN THIS BLOCK
      N=0
C     NB IS BLOCK NUMBER COUNTER
      NB=0
C     M IS MINIMUM RECORD NUMBER IN THIS BLOCK
      M=0
C     K IS POINTER OF BUFFER
      K=3
C     CHECK SPECIFIED RECORD IS IN CURRENT BLOCK
  100 IF(NR.GT.M) GO TO 10
      IF(NR.LT.N) GO TO 20
C     YES, SPECIFIED RECORD IS IN CURRENT BLOCK
      IF(NR.EQ.EBUFF(K)) GO TO 30
      K=3
C     FIND THE POSITION OF THE RECORD
    3 IF (NR.EQ.EBUFF(K)) GO TO 30
      K=K+EBUFF(K+1)+2
      IF(K.GT.516) GO TO 200
      GO TO 3
   30 K=K+1
C     GET THE SIZE OF RECORD
      L=EBUFF(K)
C     MOVE THE RECORD
      DO 31 I=1,L
   31 NBUFF(I)=EBUFF(K+I)
      K=K+L+1
      RETURN
C     TRY NEXT BLOCK
   10 NB=NB+1
   15 K=516
      CALL AREAD(FILE,NB,EBUFF,K,KR)
      IF(KR.EQ.3) GO TO 200
      K=3
      N=EBUFF(1)
      M=EBUFF(2)
      GO TO 100
C     TRY PREVIOUS RECORD
   20 NB = NB -1
      GO TO 15
  200 IR=1
      RETURN
      END
