**** SOURCE FILE : M0001088.V03   ***
*
      SUBROUTINE CPRINT(ARRAY)
C---       PURPOSE IS TO CONTROL COMPRESSION OF PRINTOUT
C---       IF ICMTES IS GT 0, STRINGS OF BLANKS ARE COMPRESSED
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON/CMPTST/ICMTES
      CHARACTER ARRAY*(*)
      INTEGER SLEN
C
      SLEN=LEN(ARRAY)
      IF(ICMTES.EQ.0) GO TO 10
C
      CALL CMPRES(ARRAY,SLEN)
C
   10 CONTINUE
      CALL SPRINT(ARRAY(:SLEN))
C
      RETURN
      END
