**** SOURCE FILE : CREAD000.ORG   ***
*
*
*  *  CREAD  *   FORTRAN 77 VERSION   4-DEC-85   E.MCLELLAN
*
*  PURPOSE     TO READ A RECORD FROM SYSTEM INPUT DEVICE
*
*  CALLING SEQUENCE
*              CALL CREAD(REC,FLAG)
*  ARGUMENTS
*              REC     CHARACTER STRING TO CONTAIN INPUT RECORD
*              FLAG    =0  NORMAL RETURN
*                      =1 END OF FILE DETECTED
*
      SUBROUTINE CREAD(REC,FLAG)
C
      INCLUDE 'SYMFIL.INC'
C
      CHARACTER*80 REC
      INTEGER FLAG
C
      READ (INFILE,'(A80)',IOSTAT=FLAG) REC
      FLAG=ABS(FLAG)
      RETURN
      END
