**** SOURCE FILE : M0000623.V01   ***
*
      SUBROUTINE CURFIT( PA, PB, PC, PD, TA, TD, KTYP, IRR )
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DIMENSION PA(3),PB(3),PC(3),PD(3),TA(3),TD(3)
      DIMENSION CCOEF(3,4), RP(3), RDN(3)
      IDIAG = 27000
      IRR = 0
C------INPUT IS FOUR POINTS PA,PB,PC,PD IN LINEAR ORDER
C------OUTPUT IS TANGENT VECTORS TA,TD OF A SMOOTH CUBIC CURVE
C------WHICH PASSES THRU THE INPUT POINTS.  IF IRR.NE.0 , THEN
C------THERE IS POTENTIAL TROUBLE IN THE INPUT POINTS
C------THE FIRST STEP IS A CHECK FOR EQUALITY OF PB AND PC
C------KTYP IS OUTPUT CURVE TYPE. 1=NULL CURVE,
C------2=STRAIGHT SEGMENT, 3= THREE POINT CURVE, 4= FOUR PT CURVE
      D1=DSQRT((PB(1)-PA(1))**2+(PB(2)-PA(2))**2+(PB(3)-PA(3))**2)
      D2=DSQRT((PC(1)-PB(1))**2+(PC(2)-PB(2))**2+(PC(3)-PB(3))**2)
      D3=DSQRT((PD(1)-PC(1))**2+(PD(2)-PC(2))**2+(PD(3)-PC(3))**2)
      DT = D1 + D2 + D3
C------VARIOUS CHECKS ARE MADE ON THE INPUT TO DETECT DEGENERATE CASES
C------FOR EXAMPLE PA=PB=PC.NE.PD WILL INDICATE A SRAIGHT LINE THRU
C------PA AND PD.
      CRIT = 0.00001
      IF( DT .GT. CRIT ) GO TO 100
C------THIS IS CASE OF A ZERO CURVE
      DO 10 I = 1, 3
      TA(I) = 0.
   10 TD(I) = 0.
      KTYP = 1
      GO TO 999
  100 CONTINUE
      IF ( D1 .GT. CRIT .AND. D2 .GT. CRIT ) GO TO 200
      IF ( D1 .GT. CRIT .AND. D3 .GT. CRIT ) GO TO 200
      IF ( D2 .GT. CRIT .AND. D3 .GT. CRIT ) GO TO 200
C------THE STRAIGHT LINE CASE
      DO 120 I = 1, 3
      TA(I) = PD(I) - PA(I)
  120 TD(I) = TA(I)
      KTYP = 2
      GO TO 999
C------FINALLY CHECK FOR THREE POINT DEGENERACY
  200 CONTINUE
      IF ( D1 .LT. CRIT ) GO TO 400
      IF ( D2 .LT. CRIT ) GO TO 400
      IF ( D3 .LT. CRIT ) GO TO 400
C------THE NON TRIVIAL FOUR POINT CURVE FOLLOWS
      CALL FORCUB ( PA, PB, PC, PD, TA, TD, IRR )
      IF ( IRR .EQ. 0 ) GO TO 310
C------TRY A MORE RUDIMENTARY ESTIMATE OF TA AND TD
      DO 320 I = 1, 3
      TA(I) = ( PB(I) - PA(I) )*DT/D1
      TD(I) = ( PD(I) - PC(I) )*DT/D3
  320 CONTINUE
  310 CONTINUE
C------NOW PROJECT PB AND PC ONTO THE INITIAL ESTIMATED CURVE
      DO 330 I = 1, 3
      CCOEF(I,1) = PA(I)
      CCOEF(I,2) = PD(I)
      CCOEF(I,3) = TA(I)
  330 CCOEF(I,4) = TD(I)
      DF1=PD(1)-PA(1)
      DF2=PD(2)-PA(2)
      DF3=PD(3)-PA(3)
      DDF=DF1*DF1+DF2*DF2+DF3*DF3+1.0D-30
      B=((PB(1)-PA(1))*DF1+(PB(2)-PA(2))*DF2+(PB(3)-PA(3))*DF3)/DDF
      C=((PC(1)-PA(1))*DF1+(PC(2)-PA(2))*DF2+(PC(3)-PA(3))*DF3)/DDF
      CALL PARMPT ( PA, PD, PB, B, PC, C, TA, TD, IRR)
      KTYP = 4
      GO TO 999
C------THE THREE POINT DEGENERATE CASE FOLLOWS
  400 CONTINUE
C------PB SHOULD BE THE NONTRIVIAL THIRD POINT
      IF ( D1 .GT. CRIT ) GO TO 410
      DO 420 I = 1, 3
  420 PB(I) = PC(I)
  410 CONTINUE
      CALL PARINT ( PA, PB, PD, TA, R, 1, IRR)
      IF ( IRR .NE. 0) GO TO 430
      CALL PARINT ( PA, PB, PD, TD, R, 3, IRR)
      GO TO 450
  430 CONTINUE
      IRR=0
      DO 440 I = 1, 3
      TA(I) = ( PB(I) - PA(I) )/DMAX1(D1,D2)
      TD(I) = ( PD(I) - PB(I) )/DMAX1(D2,D3)
  440 CONTINUE
  450 CONTINUE
C------NOW PROJECT THE PB ONTO THE INITIAL CURVE
      DF1=PD(1)-PA(1)
      DF2=PD(2)-PA(2)
      DF3=PD(3)-PA(3)
      DDF=DF1*DF1+DF2*DF2+DF3*DF3+1.0D-12
      B=((PB(1)-PA(1))*DF1+(PB(2)-PA(2))*DF2+(PB(3)-PA(3))*DF3)/DDF
C------DETERMINE A SCALAR X SUCH THAT THE VECTORS X*TA AND X*TD
C------MAKE A CLOSEST APPROACH TO THE POINT PB AT THE PARAMETER
C------VALUE B.
      BSQ  = B*B
      BCB  = B*BSQ
      SUMA = 0.
      SUMB = 0.
      DO 470 I = 1, 3
      DEL = PD(I) - PA(I)
      R   = PA(I) + DEL*( 3*BSQ - 2*BCB )
      S   = TA(I)*( B - BSQ - BSQ + BCB ) + TD(I)*( -BSQ + BCB )
C------MINIMIZE THE FORM (R+ X*S - PB)**2 WITH RESPECT TO X
      R   = R - PB(I)
      SUMA = SUMA + R*S
      SUMB = SUMB + S*S
  470 CONTINUE
      IF ( DABS(SUMB) .LT. 1.0D-8 ) X = 1.0
      IF ( DABS(SUMB) .GE. 1.0D-8 ) X = -SUMA/SUMB
      DO 480 I = 1, 3
      TA(I) = X*TA(I)
  480 TD(I) = X*TD(I)
      KTYP = 3
      IRR = 0
  999 RETURN
      END
