**** SOURCE FILE : DISPAT00.ORG   ***
*
      SUBROUTINE DISPAT
*
*  * DISPAT *  VAX 11 FORTRAN 77 VERSION  20.09.82  E.MCLELLAN
*
*  PURPOSE     TO TERMINATE A POSTPROCESSOR
*
      STOP ' CURRENT POSTPROCESSOR COMPLETE'
      END
