**** SOURCE FILE : ETORUS.ORG   ***
*
      SUBROUTINE ETORUS(U,V,GEO,RESULT,MODE)
      DOUBLE PRECISION U,V,UA,VA,SU,SV,CU,CV,RP,TOT
      DOUBLE PRECISION GEO(15),RESULT(4,8),AP(3),SN(3)
      INTEGER MODE
C PARAMETRIC EVALUATOR FOR TORUS.
C TORUS PATCH CANONICAL DATA IS IN GEO(15)
C  GEO(1)-GEO(3) = AXIS OF TORUS
C  GEO(4)-GEO(6) = CENTRE OF TORUS
C  GEO(7)-GEO(9) = REF. AXIS (I.E. DEFINES U=0,V=0)
C  GEO(10)       = MAJOR RADIUS R1
C  GEO(11)       = MINOR RADIUS R2
C  GEO(12)       = UMIN (IN RADIANS)
C  GEO(13)       = UMAX (IN RADIANS)
C  GEO(14)       = VMIN (IN RADIANS)
C  GEO(15)       = VMAX (IN RADIANS)
C RESULT RETURNS IN HOMOGENEOUS COORDINATES POINT, FIRST DERIVATIVES,
C 2ND DERIVATIVES, NORMAL AND UNIT NORMAL AT (U,V)
      UA=U*(GEO(13)-GEO(12)) + GEO(12)
      VA=V*(GEO(15)-GEO(14)) + GEO(14)
      SU=SIN(UA)
      SV=SIN(VA)
      CU=COS(UA)
      CV=COS(VA)
      R1=GEO(10)
      R2=GEO(11)
C AP IS THIRD ORTHOGONAL AXIS P*A
      AP(1)=-GEO(2)*GEO(9)+GEO(3)*GEO(8)
      AP(2)=-GEO(3)*GEO(7)+GEO(1)*GEO(9)
      AP(3)=-GEO(1)*GEO(8)+GEO(2)*GEO(7)
      RP=R1+R2*CU
      DO 10 I=1,3
       RESULT(I,1)=GEO(I+3)+R2*SU*GEO(I)+CV*RP*GEO(I+6)+SV*RP*AP(I)
  10  CONTINUE
      RESULT(4,1)=1.0
C POINT EVALUATED, NOW FIND DERIVATIVES RU,RV
      DO 20 I=1,3
       RESULT(I,2)=R2*CU*GEO(I)-R2*CV*SU*GEO(I+6)-R2*SV*SU*AP(I)
       RESULT(I,3)=-RP*SV*GEO(I+6)+CV*RP*AP(I)
  20  CONTINUE
C FIND 2ND DERIVATIVES RUU, RUV AND RVV
      DO 30 I=1,3
       RESULT(I,4)=-R2*SU*GEO(I)-R2*CU*(CV*GEO(I+6)+SV*AP(I))
       RESULT(I,5)=R2*SU*(SV*GEO(I+6)-CV*AP(I))
       RESULT(I,6)=-RP*(CV*GEO(I+6)+SV*AP(I))
  30  CONTINUE
C EVALUATE SURFACE NORMAL SN
      SN(1)=RESULT(2,2)*RESULT(3,3)-RESULT(3,2)*RESULT(2,3)
      SN(2)=RESULT(3,2)*RESULT(1,3)-RESULT(1,2)*RESULT(3,3)
      SN(3)=RESULT(1,2)*RESULT(2,3)-RESULT(2,2)*RESULT(1,3)
      TOT=0.0
      DO 40 I=1,3
       RESULT(I,7)=SN(I)
       TOT=TOT+SN(I)*SN(I)
  40  CONTINUE
      TOT=DSQRT(TOT)
      IF(TOT.LE.1.0E-8) GO TO 55
      DO 50 I=1,3
       RESULT(I,8)=SN(I)/TOT
  50  CONTINUE
C SET W COMPONENT OF ALL VECTOR QUANTITIES TO 0.0 (?)
  55  DO 60 I=2,8
       RESULT(4,I)=0.0
  60  CONTINUE
      RETURN
      END
