**** SOURCE FILE : EVALSS.ORG   ***
*
      SUBROUTINE EVALSS(NPATCH,U,V,ISIZE,GEO,MODE,
     1                  R,RU,RV,RUU,RUV,RVV,RNORM,NORMOK)
C
C.... EVALUATE SURFACE
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DIMENSION GEO(ISIZE)
      DIMENSION R(3),RU(3),RV(3),RUU(3),RUV(3),RVV(3),RNORM(3)
      DIMENSION B(64),IFLAG(4),ITOP(24),SPV(32)
C
      SAVE B,IFLAG,ITOP,ICPAT
C
      DATA ICPAT/0/
C
C.... HAS PATCH ALREADY BEEN LOADED
C
      IF (NPATCH.NE.ICPAT) THEN
C
C.... LOAD CURRENT PATCH DATA
C
        CALL LODPCH(GEO,B,IFLAG,ITOP,NPATCH,1)
C
        ICPAT=NPATCH
C
      ENDIF
C
C.... EVALUATE POINT AND DERIVATIVES
C
      MM=1
      CALL CNSURF(U,V,B,SPV,IFLAG,MM)
C
      DO 10 I=1,3
        R(I)=SPV(I)
        RU(I)=SPV(I+4)
        RV(I)=SPV(I+8)
        RUU(I)=SPV(I+12)
        RUV(I)=SPV(I+16)
        RVV(I)=SPV(I+20)
        RNORM(I)=SPV(I+28)
 10   CONTINUE
C
      NORMOK=NINT(SPV(32))
C
      END
