**** SOURCE FILE : M0000903.V06   ***
*
C.....FORTRAN SUBROUTINE  ....FINI           8/68                 AR,HG
C.....FORTRAN SUBROUTINE             FINI.....              3/1/68   GK
      SUBROUTINE FINI
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
C
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'IFXCOR.INC'
      INCLUDE 'ISHR18.INC'
      INCLUDE 'KNUMBR.INC'
C
C...            SYSTEM I/O FILE NAMES
C
      INCLUDE 'SYMFIL.INC'
C
      DIMENSION KFINI(8)
C
      INTEGER Z4E,BCDF
      PARAMETER (Z4E=1308622848)
      LOGICAL FIRST
      SAVE KFINI,FIRST
      DATA KFINI /0,0,Z4E,0,Z4E,1,Z4E,1/,FIRST/.TRUE./
C... INITIALIZE FINI RECORD
      IF (FIRST) THEN
        KFINI(1)=BCDF('FINI')
        KFINI(2)=BCDF('    ')
        FIRST=.FALSE.
      ENDIF
C
C...  WRITE EXFILE RECORD
C
      CALL APT298(4,X,X)
      CALL RECORD(KFINI(4))
      NR=0
      CALL EWRITE(EXFILE,NR,KFINI,8,IR)
      CALL TAPOP(EXFILE,-2)
      CALL TAPOP(ELFIL2,-1)
      CALL TAPOP(ELFIL3,-1)
      CALL TAPOP(AXFILE,-1)
      CALL TAPOP(XNUM,-1)
      RETURN
       END
