**** SOURCE FILE : M0004340.V09   ***
*
      SUBROUTINE FLOSEG(NSIZE,NSZSAV,MODE,IFLSEG,IRR)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      INCLUDE 'BLANKCOM.INC'
C
      INCLUDE 'SSPAD.INC'
      COMMON/IBUGG/IBUG,IPCOLC,IPCOLM
      DIMENSION ST(4,ISCN/4)
      EQUIVALENCE (SCAN(1),ST(1,1))
      LOGICAL IFLOW,ISEG
      DIMENSION STEMP(4,100)
      DIMENSION PP(4,3)
C
      DOUBLE PRECISION LIMIT,NORMAL
C---     THE FOLLOWING ARRAY, DARRAY, IS SHARED FOR PRINTING
      INCLUDE 'DARRAY.INC'
      INTEGER IZAL2(3),IZAL3(6),IZAL4(3),IZAL5(3)
      CHARACTER*8 RNAM1,RNAM2,RNAM3,RNAM4,RNAM5,RNAMA,RNAME
      CHARACTER*8 SEG,ARC,PARAM,CHORD,FLOW,LENGTH,ANGLE,TEST
C
      DATA MAXNOP/30/
      DATA NHD/1/
      DATA POINT /19./
      DATA VECTOR/20./
      DATA AREAL /21./
      DATA AFLOW,ASEG/149.0D0,150.0D0/
C---      LSTEMX IS THE MAXIMUM NUMBER OF ROWS IN STEMP
      DATA MAXSC,LSTEMX/96,100/
      DATA SEG/'SEG     '/
      DATA ARC/'ARC     '/
      DATA PARAM/'PARAM   '/
      DATA CHORD/'CHORD   '/
      DATA FLOW/'FLOW    '/
      DATA LENGTH/'LENGTH  '/
      DATA ANGLE/'ANGLE   '/
      DATA ZERO,ONE,SMAL,BIG/0.0D0, 1.0D0, 1.0D-7, 99999999.0D0/
      DATA TOLR/0.005D0/
      DATA    RNAM1   /'FLOSEG  '/,RNAM2   /'ANGSEG  '/,
     *          RNAM3   /'CHDSEG  '/,RNAM4   /'ARCSEG  '/,
     *          RNAM5   /'ANGDER  '/,
     *          RNAMA   /'FLOSEG??'/,RNAME   /'        '/
      DATA IMAX2/ 3/,IZAL2
     *                  / 5508, 5509, 5510/
      DATA IMAX3/ 6/,IZAL3
     *                  / 5502, 5503, 5504, 5505, 5506, 5507/
      DATA IMAX4/ 3/,IZAL4
     *                  / 5501, 5522, 5523/
      DATA IMAX5/ 3/,IZAL5
     *                  / 5519, 5511, 5512/
C
C
      NP=0
      NH=41
      ANH=NH
      NHD1=NHD+1
      NS=NH+8
C--- MODE=2 MEANS PROCESS FLOW COMMANDS PREVIOUSLY STORED
C---      IN STEMP
C--- MODE=1 MEANS PERFORM PRELIMINARY SCAN OF SCURV INPUT-STREAM
C---      AND STORE FLOW DATA, IF ANY, IN STEMP.
      IF(MODE.EQ.2) GO TO 2000
C
C---     PERFORM A PRELIMINARY SCAN OF DATA TO LOCATE FLOW
C---     AND SEGMENT INFORMATION IN THE DEFINITION
C---     LSTEMP IS THE POINTER TO THE LAST USED ROW IN STEMP
C---     IFLOW IS TRUE ONLY WHILE PROCESSING FLOW BLOCKS
C---     ISEG IS TRUE ONLY WHILE PROCESSING SEGMENT BLOCKS
C---     NSEGST POINTS TO THE STARTING ROW FOR SEGMENT INFORMATION
C---     NFLOST POINTS TO THE STARTING ROW FOR FLOW INFORMATION
      IFLOW=.FALSE.
      ISEG=.FALSE.
      NFLOST=0
      NSEGST=0
      LSTEMP=0
      NUMSEG=0
      IFLSEG=0
C
C---     SEARCH FOR FLOW AND SEGMENT BLOCKS AND TRANSFER
C---     INFORMATION IN EDITED FORM INTO THE STEMP ARRAY
C
      NLOC=NS
   34 CONTINUE
      IF(NLOC.GE.NSIZE) GO TO 1034
C
C---     NLOC POINTS TO THE STARTING LOCATION OF THE CURRENT
C---     SUBSTRING BEING EXAMINED. IT IS UPDATED TO THE NEXT SUBSTRING
C---     AT THE TERMINATION OF CODE FOR EACH SUBSTRING.
      T=CANON(NLOC)
      CALL HOLFRM(T,TEST,1,8,NWD)
      IF(TEST.EQ.FLOW) GO TO 40
      IF(TEST.EQ.SEG) GO TO 50
      CALL HOLFRM(CANON(NLOC+1),TEST,1,8,NWD)
      IF(TEST.EQ.SEG) GO TO 51
C---     IF FLOW OR SEG HAVE NOT BEEN FOUND, CONTINUE SEARCH
      IF(.NOT.IFLOW.AND..NOT.ISEG) NLOC=NLOC+1
      IF(.NOT.IFLOW.AND..NOT.ISEG) GO TO 31
      IF(IFLOW) GO TO 60
C---     ISEG MUST BE TRUE SO CHECK FOR SEGMENT BLOCKS
      T=CANON(NLOC+1)
      CALL HOLFRM(T,TEST,1,8,NWD)
      IF(TEST.EQ.LENGTH.OR.TEST.EQ.PARAM) GO TO 35
C****    PROPER MINOR WORD DID NOT FOLLOW HERE.
      IRR=1
      GO TO 30
   35 CONTINUE
      LSTEMP=LSTEMP+1
      IF(LSTEMP.LE.LSTEMX) GO TO 36
C****    NO ROOM AVAILABLE IN BUFFER FOR FLOW/SEG DATA
      IRR=2
      GO TO 30
   36 CONTINUE
      STEMP(1,LSTEMP)=T
      IF(CANON(NLOC+2).EQ.AREAL.AND.CANON(NLOC+4).EQ.AREAL) GO TO 38
C****    AT LEAST TWO SCALARS SHOULD FOLLOW
      IRR=3
      GO TO 30
   38 CONTINUE
      STEMP(2,LSTEMP)=CANON(NLOC+3)
      STEMP(3,LSTEMP)=CANON(NLOC+5)
      STEMP(4,LSTEMP)=ONE
      NLOC=NLOC+6
      NUMSEG=NUMSEG+1
      GO TO 31
C
C---     CHECK FOR PROPER WORDS FOR FLOW INFORMATION
   60 CONTINUE
      T=CANON(NLOC+1)
      MSIZE=1
      CALL HOLFRM(T,TEST,1,8,NWD)
      IF(TEST.EQ.ARC.OR.TEST.EQ.PARAM) GO TO 65
      MSIZE=4
      IF(TEST.EQ.CHORD) GO TO 65
      MSIZE=4
      IF(TEST.EQ.ANGLE) GO TO 65
C****   NONE OF THE REQUIRED KEYWORDS HAS FOLLOWED
      MSIZE=0
      IRR=4
      GO TO 30
C
   65 CONTINUE
      ASIZE=MSIZE
      IF(CANON(NLOC+2).EQ.AREAL.AND.CANON(NLOC+4).EQ.AREAL) GO TO 70
C****    AT LEAST TWO SCALARS SHOULD FOLLOW
      IRR=5
      GO TO 30
   70 CONTINUE
      LSTEMP=LSTEMP+1
      IF(LSTEMP+MSIZE-1.LE.LSTEMX) GO TO 75
C****    NO ROOM TO BUFFER ARC/FLOW DATA
      IRR=6
      GO TO 30
   75 CONTINUE
      STEMP(1,LSTEMP)=T
      STEMP(2,LSTEMP)=CANON(NLOC+3)
      STEMP(3,LSTEMP)=CANON(NLOC+5)
      STEMP(4,LSTEMP)=ASIZE+TOLR
      NLOC=NLOC+6
      IF(CANON(NLOC).NE.AREAL) GO TO 76
C---     LOAD A USER SUPPLIED TOLERANCE , IF ACCEPTABLE
      T=CANON(NLOC+1)
      IF(T.GT.SMAL.AND.T.LT.ONE) STEMP(4,LSTEMP)=ASIZE+T
      NLOC=NLOC+2
   76 CONTINUE
      IF(MSIZE.LT.2) GO TO 89
C---     SCAN FOR MODIFYING POINTS AND VECTORS FOR FLOW SPECIFICATION
      MM=MSIZE-1
      DO 80 L=1,MM
      DO 80 K=1,4
      STEMP(K,L+LSTEMP)=ZERO
   80 CONTINUE
      T=CANON(NLOC)
      IF(T.NE.POINT.OR.MSIZE.LT.2) GO TO 83
      DO 81 L=1,3
      STEMP(L,LSTEMP+1)=CANON(NLOC+L)
   81 CONTINUE
      STEMP(4,LSTEMP+1)=ONE
      NLOC=NLOC+4
      T=CANON(NLOC)
   83 CONTINUE
      IF(T.NE.POINT.OR.MSIZE.LT.3) GO TO 87
      DO 86 L=1,3
      STEMP(L,LSTEMP+2)=CANON(NLOC+L)
   86 CONTINUE
      STEMP(4,LSTEMP+2)=ONE
      NLOC=NLOC+4
      T=CANON(NLOC)
   87 CONTINUE
      IF(T.NE.VECTOR.OR.MSIZE.LT.4) GO TO 89
      DO 88 L=1,3
      STEMP(L,LSTEMP+3)=CANON(NLOC+L)
   88 CONTINUE
      STEMP(4,LSTEMP+3)=ONE
      NLOC=NLOC+4
   89 CONTINUE
C---     UPDATE FLOW BLOCK POINTER TO NEXT AVAILABLE SPACE.
C---     NSEGST FINALLY POINTS TO START OF SEGMENT INFORMATION
      LSTEMP=LSTEMP+MSIZE-1
      GO TO 31
C
C---     INITIALIZE DATA FOR FLOW INFORMATION
   40 CONTINUE
      IRR=7
C****    NEITHER FLOW NOR SEG SHOULD HAVE BEEN ENCOUNTERED
      NLOC=NLOC+1
      IF(CANON(NLOC-2).NE.AFLOW) GO TO 31
      IF(IFLOW.OR.ISEG) GO TO 30
      IF(NSEGST.GT.0.OR.NFLOST.GT.0) GO TO 30
      IFLOW=.TRUE.
      NFLOST=1
C---     STORE THE DATA SIZE OF INPUT UP TO THE FIRST FLOW COMMAND
      NSZSAV=NLOC-3
      GO TO 31
C---     INITIALIZE DATA FOR SEGMENT INFORMATION.
   51 CONTINUE
      NLOC=NLOC+1
   50 CONTINUE
      NLOC=NLOC+1
      IRR=8
C****    FLOW SHOULD HAVE BEEN ENCOUNTERED BUT NOT SEG
      IF(CANON(NLOC-2).NE.ASEG) GO TO 31
      IF(.NOT.IFLOW.OR.ISEG) GO TO 30
      IF(NSEGST.GT.0.OR.NFLOST.LE.0) GO TO 30
      IFLOW=.FALSE.
      ISEG=.TRUE.
      NSEGST=LSTEMP+1
      GO TO 31
C
   31 CONTINUE
C
      IRR=0
   32 CONTINUE
C---     END OF LOOP TO SCAN FOR SEGMENT/FLOW BLOCKS
      GO TO 34
C
 1034 CONTINUE
C
C
      IF(IBUG.NE.11) GO TO 33
      CALL BAD(-54,1,'STEM',STEMP)
   33 CONTINUE
C
      IF (IRR.EQ.0) GO TO 90
C
C---     ERROR PATH, UNDEFINE CANON FORM AND QUIT
   30 CONTINUE
C---     WRITE OUT INFORMATION FOR DIAGNOSING PROBLEM
      NDIF=NSIZE-NS+1
      CALL BAD(-NDIF,1,'CAN ',CANON(NS))
      NLOC=NLOC-NS+1
      CALL BAD(-1,0,'NLOC',NLOC)
      CALL BAD(1,0,'NSEG',NSEGST)
      CALL BAD(1,0,'I   ',I)
      CALL BAD(1,0,'M   ',M)
      CALL BAD(1,1,'AN1 ',AN1)
      CALL BAD(1,1,'AN2 ',AN2)
      CALL BAD(-1,1,'BPNT',BPNTS)
C
      IERROR=5500+IABS(IRR)
      CALL ERROR(IERROR,RNAM1)
C
   90 CONTINUE
      IF(IFLOW.OR.ISEG) IFLSEG=1
      GO TO 999
C
C----------------------------------------------------------
 2000 CONTINUE
C
C
C---     FLOW INFORMATION IS AVAILABLE, SO START FLOW PROCESSING
C---     FIRST SCAN THE FLOW AND SEGMENT BLOCKS AND CHECK FOR
C---     INPUT CONSISTENCY.
C
      ANPTS=CANON(NH+3)+ONE
      NPTS=ANPTS
      BPNTS=ANPTS-ONE
C---     INCREMENT CURVE TYPE BY 10 TO INDICATE FLOW PRESENCE.
      CANON(NH+2)=CANON(NH+2)+10.
C
C---     I IS CURRENT ROW, M INCREMENT TO NEXT, N2 LAST POINT
      I=0
      M=1
      AN2=ZERO
 1010 I=I+M
      IF(I.GE.NSEGST) GO TO 1080
      AN1=STEMP(2,I)
      IF(DABS(AN2-AN1).LT.SMAL) GO TO 1020
C****    PREVIOUS POINT AND PRESENT SHOULD BE EQUAL
      IRR=13
      GO TO 30
 1020 CONTINUE
      AN2=STEMP(3,I)
      M=STEMP(4,I)
      IF(AN1+SMAL.LT.AN2.AND.AN2.LT.BPNTS+SMAL) GO TO 1010
C****    REFERENCES TO CURVE POINTS ARE INVALID.
      IRR=14
      GO TO 30
 1080 CONTINUE
      IF(DABS(AN2-BPNTS).LT.SMAL) GO TO 1090
C****    LAST POINT REFERENCE SHOULD EQUAL LAST PT OF CURVE
      IRR=15
      GO TO 30
 1090 CONTINUE
C
C---    NOW SCAN SEGMENT DATA AND CHECK FOR CONSISTENCY
C
      I=NSEGST-1
      M=1
      AN2=ZERO
 1110 I=I+M
      IF(I.GT.LSTEMP) GO TO 1180
      AN1=STEMP(2,I)
      IF(DABS(AN1-AN2).LT.SMAL) GO TO 1120
C****    AN1,AN2 HAVE INVALID RELATION
      IRR=16
      GO TO 30
 1120 CONTINUE
      AN2=STEMP(3,I)
      IF(AN1.LT.AN2+SMAL.AND.AN2.LT.BPNTS+SMAL) GO TO 1110
C****    CURRENT TWO SCALARS HAVE INCONSISTENT RELATION
      IRR=17
      GO TO 30
 1180 IF(DABS(AN2-BPNTS).LT.SMAL) GO TO 1190
C****    LAST SEGMENT MUST TERMINATE IN LAST POINT
      IRR=18
      GO TO 30
 1190 CONTINUE
C------------------------------------------------
C---     CONSISTENCY CHECKING COMPLETED ON FLOW/SEGMENT INPUT
C
C---     MAJOR FLOW PROCESSING, ALL FLOW COMMAND INFORMATION
C---     IS STORED IN THE STEMP ARRAY WHOSE ROWS WILL BE INDEXED
C---     BY IST.  FLOW INFORMATION, INCLUDING ARC SUMMARY BLOCKS
C---     AND FLOW RATE SPLINES ARE CONTAINED IN THE ARRAY ST
C---     SUMMARY INFORMATION IS INDEXED BY IST AND SPLINE
C---     FUNCTIONS ARE INDEXED BY IFLAVL
C
C---     SAVE STARTING VALUES FOR  FLOW AND SEGMENT SUMMARY
C---     BLOCKS
      IFLOST=1
      ISEGST=NPTS
      ISPLST=ISEGST+NUMSEG
C---     INITIALIZE INDICES TO AVAILABLE SPACE
      IST=IFLOST
      ISPL=ISPLST
      ISTMAX=MAXSC*6
C---     ARRAY ST (=SC) WILL BE USED TO BUFFER AND ACCUMULATE
C---     FLOW AND SEGMENT SUMMARY INFORMATION.  THIS DATA
C---     WILL THEN BE EXAMINED FOR ERRORS AND LATER BE
C---     CONSOLIDATED WITH THE REMAINING DEFINED CURVE CANON
C---     FORM, PROVIDED NO ERRORS HAVE OCCURRED.
C
      ISTEM=0
      INCTEM=1
      IRCT=0
C
 1200 CONTINUE
      ISTEM=ISTEM+INCTEM
      IF(ISTEM.GE.NSEGST) GO TO 1300
      I1=STEMP(2,ISTEM)+ONE
      I2=STEMP(3,ISTEM)
      INCTEM=STEMP(4,ISTEM)
      TOL=STEMP(4,ISTEM)-INCTEM
C---     EXECUTE THIS FLOW PROCESSING FOR EACH CURVE FROM I1 TO I2
C
      DO 1210 J=I1,I2
      ST(1,IST)=ISPL
      ISPMX=ISTMAX-ISPL
      ST(3,IST)=STEMP(1,IST)
C---     COMPUTE INDEX TO CURRENT CURVE
      NCURV=(CANON(NH+1)+J-1)*24+NH
C
      IF(IBUG.NE.11) GO TO 1219
      CALL BAD(1,0,'NCUR',NCURV)
      CALL BAD(-1,0,'J   ',J)
      CALL BAD(24,1,'CAN ',CANON(NCURV))
      CALL BAD(1,1,'TOL ',TOL)
      CALL BAD(-1,0,'ISPM',ISPMX)
 1219 CONTINUE
C
C---     BRANCH TO AREA FOR INDIVIDUAL FLOW PROCESSING
      CALL HOLFRM(STEMP(1,ISTEM),TEST,1,8,NWD)
      IF(TEST.EQ.ARC) GO TO 1320
      IF(TEST.EQ.ANGLE) GO TO 1340
      IF(TEST.EQ.CHORD) GO TO 1360
      IF(TEST.EQ.PARAM) GO TO 1380
C****    INVALID SPECIFICATION FOR FLOW
      IR=20
      GO TO 1290
C
C---     FLOW PROCESSING FOR ONE CUBIC ARC BY ARC LENGTH.
 1320 CONTINUE
      CALL ARCSEG(CANON(NCURV),ST(1,ISPL),TOL,NUM,ISPMX,IR)
      GO TO 1290
C---     FLOW PROCESSING FOR ONE CUBIC ARC BY ANGLE.
 1340 CONTINUE
      CALL ANGSEG(CANON(NCURV),ST(1,ISPL),TOL,NUM,ISPMX,IR,
     X STEMP(1,ISTEM+1),STEMP(1,ISTEM+3))
      GO TO 1290
C---     FLOW PROCESSING FOR ONE CUBIC ARC BY CHORD PROJECTION
 1360 CONTINUE
C
C---     THE SET UP OF CHORDAL PARAMETERS MAY BE IMPLIED
C---     SO BEGIN BY SETTING THEM UP FIRST.
      DO 1361 II=1,3
      DO 1361 JJ=1,3
      PP(II,JJ)=STEMP(II,ISTEM+JJ)
 1361 CONTINUE
C---     DEFAULT, CHORD IS DEFINED BY END POINTS OF COMBINED SEGMENT
      IF(STEMP(4,ISTEM+1).GT.SMAL) GO TO 1362
C
      NN=(CANON(NH+1)+I1-1)*24+NH
      CALL CNCURV(ZERO,CANON(NN),PP(1,1),0)
 1362 CONTINUE
      IF(STEMP(4,ISTEM+2).GT.SMAL) GO TO 1363
      NN=(CANON(NH+1)+I2-1)*24+NH
      CALL CNCURV(ONE,CANON(NN),PP(1,2),0)
 1363 CONTINUE
      SZ=ZERO
      DO 1364 JJ=1,3
      PP(JJ,2)=PP(JJ,2)-PP(JJ,1)
      SZ=SZ+PP(JJ,2)**2
 1364 CONTINUE
      SZ=DSQRT(SZ)
C****    TWO POINTS TOO CLOSE FOR PROPER CHORD
      IR=21
      IF(SZ.LT.SMAL) GO TO 1290
      IR=0
      DO 1365 JJ=1,3
      PP(JJ,2)=PP(JJ,2)/SZ
 1365 CONTINUE
      IF(STEMP(4,ISTEM+3).GT.SMAL) GO TO 1366
 1370 CONTINUE
C---     IF A VECTOR NORMAL TO THE PROJECTION PLANES HAS NOT BENN
C---     SUPPLIED BY THE USER, THEN THE AXIS OF THE CHORD IS CHOSEN
C---     AS A DEFAULT NORMAL VECTOR TO THESE PLANES
      PP(1,3)=PP(1,2)
      PP(2,3)=PP(2,2)
      PP(3,3)=PP(3,2)
 1366 CONTINUE
      CALL CHDSEG(CANON(NCURV),ST(1,ISPL),TOL,NUM,ISPMX,IR,
     X            PP(1,1),PP(1,2),PP(1,3))
      GO TO 1290
C---     DIRECT IDENTITY PARAMETERIZATION
 1380 CONTINUE
      IR=22
      NUM=2
      IF(ISPL+NUM.GT.ISPMX) GO TO 1290
      IR=0
C---     SET UP A SPLINE IDENTITY FUNCTION
      ST(1,ISPL)=ZERO
      ST(2,ISPL)=ZERO
      ST(3,ISPL)=ONE
      ST(4,ISPL)=ZERO
      ST(1,ISPL+1)=ONE
      ST(2,ISPL+1)=ONE
      ST(3,ISPL+1)=ONE
      ST(4,ISPL+1)=ZERO
      GO TO 1290
C
 1290 CONTINUE
      IF(IR.EQ.0) GO TO 1220
C****    ERROR PATH, INCREMENT ERROR COUNT AND RESET VALUES
      IRCT=IRCT+1
      ST(1,IST)=-IR
      ST(2,IST)=NUM
      ST(4,IST)=ZERO
      IR=0
      NUM=0
      IF(IBUG.EQ.11) CALL BAD(-4,1,'ERR=',ST(1,IST))
      IST=IST+1
      GO TO 1210
C---     NORMAL COMPLETION OF FLOW RATE FOR ONE ARC.
 1220 CONTINUE
C---     STORE SUMMARY DATA FOR FLOW SPLINES LOCATION,NUMBER,
C---     TYPE OF FLOW AND TOTAL SPAN
      ST(1,IST)=ISPL
      ST(2,IST)=NUM
C---     SAVE TYPE FLOW AND TOLERANCE IN 3RD LOCATION
      CALL HOLFRM(STEMP(1,ISTEM),TEST,1,8,NWD)
      IF(TEST.EQ.ARC)   ST(3,IST)=1.+TOL
      IF(TEST.EQ.ANGLE) ST(3,IST)=2.+TOL
      IF(TEST.EQ.CHORD) ST(3,IST)=3.+TOL
      IF(TEST.EQ.PARAM) ST(3,IST)=4.+TOL
      ST(4,IST)=ST(1,ISPL+NUM-1)-ST(1,ISPL)
      ISPL=ISPL+NUM
      IST=IST+1
      NUM=0
 1210 CONTINUE
C
      GO TO 1200
 1300 CONTINUE
C
      IF(IRCT.EQ.0.AND.IBUG.NE.11) GO TO 1401
C****    DUMP CURV INFORMATION TO DOCUMENT FAILURES
      CALL CFORM('0 ***ERRORS WHILE PROCESSING FLOW DATA FOR CURVE',
     X DARRAY,1,48)
      CALL CPRINT (DARRAY)
      JTOP=ISPL-1
      DO 1310 JJ=1,JTOP
      JJ1=IFLOST+JJ-1
      IF(JJ1.GE.IST)GO TO 1305
      IF(ST(1,JJ1).GE.0.D0)GO TO 1305
      IR=-ST(1,JJ1)
      CALL BAD(-1,0,'IRR ',IR+5500)
 1305 CONTINUE
      CALL BAD(-4,1,'CURV',ST(1,IFLOST+JJ-1))
 1310 CONTINUE
      IF(IRCT.EQ.0) GO TO 1401
C****    ERROR IN FLOW PROCESSING
      IRR=IR+5500
      RNAME=RNAMA
      DO 8002 IL2=1,IMAX2
 8002 IF (IRR.EQ.IZAL2(IL2)) RNAME=RNAM2
      DO 8003 IL3=1,IMAX3
 8003 IF (IRR.EQ.IZAL3(IL3)) RNAME=RNAM3
      DO 8004 IL4=1,IMAX4
 8004 IF (IRR.EQ.IZAL4(IL4)) RNAME=RNAM4
      DO 8005 IL5=1,IMAX5
 8005 IF (IRR.EQ.IZAL5(IL5)) RNAME=RNAM5
      CALL ERROR(IRR,RNAME)
      GO TO 999
C
C---------------------------------------------------------
C---    FLOW SPLINES HAVE BEEN CREATED FOR EACH ARC, NOW
C---     SET UP SEGMENT DATA.
 1401 CONTINUE
C---    NOW PROCESS CURVE SEGMENT INFORMATION
      ISTEM=NSEGST-1
      INCTEM=1
 1400 CONTINUE
      ISTEM=ISTEM+INCTEM
      IF(ISTEM.GT.LSTEMP) GO TO 1490
C---    PROCESS CURVE SEGMENTS, ONE AT A TIME
      ST(3,IST)=STEMP(1,ISTEM)
      ST(1,IST)=STEMP(2,ISTEM)
      ST(2,IST)=STEMP(3,ISTEM)
      ST(4,IST)=ZERO
      IF(DABS(ST(1,IST)-ST(2,IST)).LT.SMAL) GO TO 1410
C---    IN CASE OF LENGTH TOTAL SPAN IS BASED ON TOTAL FLOW LENGTH
      I1=ST(1,IST)+ONE
      I2=ST(2,IST)
      TOTLEN=ZERO
      DO 1440 II=I1,I2
      TOTLEN=TOTLEN+ST(4,II)
 1440 CONTINUE
C---    STORE TOTAL LENGTH IN SEGMENT BLOCK
      ST(4,IST)=TOTLEN
C---     TOTLEN=NUMBER OF ARCS IN SEGMENT IN CASE OF PARAM
      CALL HOLFRM(ST(3,IST),TEST,1,8,NWD)
      IF(TEST.EQ.PARAM) TOTLEN=ST(2,IST)-ST(1,IST)
C---     NOW CHANGE PARAMETER FLOW ON EACH SEGMENT, ARC BY ARC,
C---     SO THAT THE TOTAL FLOW IS FROM ZERO TO ONE FOR THE
C---     COMPLETE SEGMENT
      SUM=ZERO
      DO 1450 J=I1,I2
C---     DETERMINE THE FACTOR FOR RESETTING FLOW FOR ARC J
      SPAN=ST(4,J)
      FACTOR=ONE/TOTLEN
      CALL HOLFRM(ST(3,IST),TEST,1,8,NWD)
      IF(TEST.EQ.PARAM) FACTOR=ONE/(TOTLEN*SPAN)
C---     NOW MODIFY ALL FLOW SPLINE FUNCTIONS FOR ARC J TO
C---     CHANGE THE FLOW SCALE
      NLOC=ST(1,J)
      NN=ST(1,J)+ST(2,J)-ONE
      DO 1460 JJ=NLOC,NN
      ST(1,JJ)=ST(1,JJ)*FACTOR+SUM
      ST(3,JJ)=ST(3,JJ)/FACTOR
 1460 CONTINUE
C
      ST(4,NLOC)=SUM
      TSUM=SUM+SUM
      NLOC1=NLOC+1
      DO 1465 JJ=NLOC1,NN
      ST(4,JJ)=ST(1,JJ)-ST(1,JJ-1)+TSUM
 1465 CONTINUE
C
      CALL HOLFRM(ST(3,IST),TEST,1,8,NWD)
      IF(TEST.EQ.PARAM) SUM=SUM+ONE/TOTLEN
      IF(TEST.EQ.LENGTH) SUM=SUM+SPAN*FACTOR
 1450 CONTINUE
C
      ST(2,IST)=ST(2,IST)-ST(1,IST)
C---     CONVERT ALPHANUMERIC DATA TO NUMBER CODE
      CALL HOLFRM(ST(3,IST),TEST,1,8,NWD)
      IF(TEST.EQ.PARAM) ST(3,IST)=1.0
      IF(TEST.EQ.LENGTH) ST(3,IST)=2.0
 1410 CONTINUE
C
      IF(IBUG.NE.11) GO TO 1413
      CALL BAD(1,0,'IST ',IST)
      CALL BAD(4,1,'ST  ',ST(1,IST))
 1413 CONTINUE
C
      IST=IST+1
      GO TO 1400
C---     PROCESSING OF SEGMENT DATA FINISHED
 1490 CONTINUE
C
C-----------------------------------------------------------
C---     NOW MERGE THE ST ARRAY AND FLOW/SEGMENT INFORMATION
C---     AND RECORD REQUIRED POINTERS IN THE SCURV HEADER
C---     TABLE
C---     NLOC POINTS JUST TO THE END OF THE CUBIC CURVE BLOCKS
      ANST=(CANON(NH+1)+ANPTS-ONE)*24.+ONE
      NCT=ANST-ONE+ANH-ONE
      DO 1500 II=1,ISPL
      DO 1500 JJ=1,4
      NCT=NCT+1
C---     CONVERT ADDRESSES FROM ROW NOTATION TO SEQUENTIAL NOTATION
      IF(II.LT.NPTS) ST(1,II)=(ST(1,II)-ONE)*4.+ANST
      CANON(NCT)=ST(JJ,II)
 1500 CONTINUE
C---     NOW PLACE LOCATION POINTERS IN TO HEADER TABLE
C---     LOCATION OF POINT BLOCKS
      CANON(NH+4)=CANON(NH+1)*24.+ONE
C---     NUMBER OF FLOW BLOCKS (IF ANY) AND LOCATION
      CANON(NH+5)=CANON(NH+3)
      CANON(NH+6)=CANON(NH+4)+(ANPTS-ONE)*24.
C---     NUMBER OF SEGMENT BLOCKS AND STARTING LOCATION
      CANON(NH+7)=NUMSEG
      CANON(NH+8)=CANON(NH+6)+CANON(NH+5)*4.0
C---     NUMBER OF FLOW BLOCKS AND STARTING LOCATION
      CANON(NH+9)=ISPL-NUMSEG-NPTS
      CANON(NH+10)=CANON(NH+8)+CANON(NH+7)*4.0
C---     FINALLY SETUP THE TOTAL SIZE OF THE STRUCTURE
      CANON(NH+11)=CANON(NH+10)+4.*CANON(NH+9)-ONE
      CANON(NH+12)=ONE
C
      IF(IBUG.NE.11) GO TO 4322
      NNNN=CANON(NH+11)/4.+.1
      MMMM=-3
      DO 4321 KKK=1,NNNN
      MMMM=MMMM+4
      CALL BAD(4,1,'FCAN',CANON(NH-1+MMMM))
      CALL BAD(-1,0,'INDX',MMMM)
 4321 CONTINUE
 4322 CONTINUE
      IRR=0
C
C-------------------------------------------------
C---     THE PROCESSING OF FLOW FUNCTIONS ACROSS THE CURVE IS COMPLETE.
C
  999 CONTINUE
C
      RETURN
      END
