**** SOURCE FILE : M0001072.W01   ***
*
      SUBROUTINE GFETCH(NBIG,MAXLDA,COM,DGEOM,PGEOM,IRR)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON/IBUGG/IBUG,IPCOLC,IPCOMC
      DIMENSION DUMREC(3)
      DIMENSION COM(*),DGEOM(*),PGEOM(*)
      LOGICAL CKDEF
      EQUIVALENCE (JJ,AA)
      CHARACTER*20 BADMSG
      DATA ZERO,ONE,ASCURV,ASSURF/0.0D0,1.0D0,30.0D0,29.0D0/
      DATA DUMREC/3*0.0D0/
C--PURPOSE IS TO LOAD PART AND DRIVE GEOMETRY BOTH INTO THE
C--ARRAY COM.  THE ADDRESS OF EACH IS THEN PLACED IN THE 4TH
C--LOCATIONS OF DGEOM AND PGEOM RESPECTIVELY
C
      NLO=41
      NHI=NLO+NBIG-1
      ILOC=NHI+1
      DO 10 I=NLO,NHI
   10 COM(I)=ZERO
      IRR=1
      N=PGEOM(2)+DGEOM(2)
      IF(PGEOM(1).EQ.DGEOM(1)) N=PGEOM(2)
      N=N+NBIG
      IF(N.GT.MAXLDA) GO TO 998
C---      WRITE A NULL RECORD TO LET APT094 KNOW THAT BLANK COMMON
C---      HAS BEEN ALTERED
      DUMREC(2)=0.0
      DUMREC(3)=NBIG
      JMODE=1
      CALL APT094(JMODE,DUMREC(2),COM(41))
      IRR=4
      IF(CKDEF(DUMREC)) GO TO 998
C--LOAD PART GEOMETRY FIRST
      JMODE=3
      CALL APT094(JMODE,PGEOM(1),JJ)
      IRR=2
      IF(CKDEF(PGEOM)) GO TO 998
      PGEOM(4)=JJ
C--CHECK WHETHER PART AND DRIVE GEOMETRY ARE THE SAME
      IF(DGEOM(1).NE.PGEOM(1)) GO TO 110
      DGEOM(4)=PGEOM(4)
      GO TO 200
C--LOAD DRIVE GEOMETRY INTO CORE
  110 CONTINUE
      JMODE=3
      CALL APT094(JMODE,DGEOM(1),JJ)
      IRR=3
      IF(CKDEF(DGEOM)) GO TO 998
      DGEOM(4)=JJ
  200 CONTINUE
      IRR=0
C
  998 CONTINUE
      IF(IBUG.NE.11) GO TO 999
      CALL BAD(-1,0,' ',0)
      BADMSG=' AFTER  GFETCH'
      CALL CPRINT(BADMSG)
      CALL BAD(1,0,'IRR ',IRR)
      CALL BAD(1,0,'JMOD',JMODE)
      CALL BAD(-1,0,'ILOC',ILOC)
      CALL BAD(-4,1,'PGEM',PGEOM(1))
      CALL BAD(-4,1,'DGEM',DGEOM(1))
      CALL BAD(-3,1,'DREC',DUMREC)
C
  999 CONTINUE
      RETURN
      END
