**** SOURCE FILE : HULCUT.V01   ***
*
      SUBROUTINE HULCUT(TE,TA,TUL,SPHR,ISEG)
C
C     CALCS. PENETRATION OF CORNER RADIUS CUTTER INTO SPHERICAL CONVEX H
C     OF RADIUS RAD AND CENTRE CENT
C     IF NO PENETRATION OCCURS, THEN ISEG = -1, ELSE
C     ISEG   = 0      BOTTOM FLAT
C              1      CORNER RADIUS
C              2      CYLINDER
C     P IS PENETRATION, -VE FOR MISS
C
C     ARGUMENTS:
C
C     TE      - TOOL END
C     TA      - TOOL AXIS
C     TUL     - TOOL GEOMETRY
C     SPHR    - CENTRE AND RADIUS OF TEST SPHERE
C
      DOUBLE PRECISION TE,TA,TUL,SPHR
      DIMENSION TE(3),TA(3),TUL(7),SPHR(4)
C
C.... LOCAL VARIABLES
C
      DOUBLE PRECISION V,A,B,C,P
      DIMENSION V(3)
C
      ISEG=-1
      DO 10 I=1,3
        V(I)=TE(I)+(TUL(4)+TUL(1))*TA(I)-SPHR(I)
10    CONTINUE
      CALL VECMOD(V,B)
      CALL DOTF(A,V,TA)
      C=SQRT(B*B-A*A)
C
      IF (A.GT.0) THEN
C.... CYLINDER CASE
            P=SPHR(4)+TUL(2)-C
C.... P -VE FOR MISS
            IF (P.GT.0) ISEG=2
C
      ELSE IF (C.LE.TUL(3)) THEN
C.... BOTTOM FLAT CASE
            P=TUL(1)+TUL(4)+SPHR(4)-A
C.... P -VE FOR MISS
            IF (P.GT.0) ISEG=0
C
      ELSE
C.... CORNER RADIUS CASE
            D=C-TUL(3)
            P=TUL(1)+SPHR(4)-SQRT(D*D+A*A)
C.... P -VE FOR MISS
            IF (P.GT.0) ISEG=1
      END IF
C
      END
