**** SOURCE FILE : M0000743.V01   ***
*
C.....FORTRAN ROUTINE          ..AIMAIN..      6/69       HLG       *ID*
      SUBROUTINE IMAIN
C
C PURPOSE      THIS IS THE MAIN ROUTINE FOR THE INTERPRETIVE APPROACH.
C NOTE THE MAIN ROUTINE FOR THE ASSEMBLY APPROACH
C WILL BE CALLED AMAIN, WHEN IMPLEMENTED, & WHICH ROUTINE
C IS USED DEPENDS ON THE APPROACH  REQUESTED BY THE PART PROGRAM.
C
C CALLED BY    THE ROUTINE MAIN
C
C
C...  INITALIZE STORAGE
      CALL INIT
C
C...  GO TO INTERPRETER
      CALL INTRP
C
      RETURN
      END
