**** SOURCE FILE : MIDPNT.V01   ***
*
      SUBROUTINE MIDPNT(SURF,NPAT,UP,VP,NPATL,UPL,VPL,RM)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DIMENSION SURF(*),RM(32),B(64),IFLAG(6),ITOP(6,4)
      CHARACTER*20 BADMSG
C
      INCLUDE 'IBUGG.INC'
C
C.... COMPUTE GLOBAL PARAMETERS FOR CURRENT AND PREVIOUS POINTS
C
      CALL MESCON(SURF,U1,V1,NPAT,UP,VP,2)
      CALL MESCON(SURF,U2,V2,NPATL,UPL,VPL,2)
C
C.... COMPUTE GLOBAL PARAMETERS OF MIDPOINT
C
      U=(U1+U2)/2.0
      V=(V1+V2)/2.0
C
C.... COMPUTE PATCH NUMBER AND LOCAL PARAMETERS FOR MIDPOINT
C
      CALL MESCON(SURF,U,V,NPATM,UM,VM,1)
C
C.... LOAD PATCH COEFFICIENTS
C
      CALL LODPCH(SURF,B,IFLAG,ITOP,NPATM,0)
C
C.... EVALUATE COORDINATES OF MIDPOINT
C
      CALL CNSURF(UM,VM,B,RM,IFLAG,1)
C
      IF (IBUG.EQ.11) THEN
         BADMSG=' AFTER MIDPNT'
         CALL CPRINT(BADMSG)
         CALL BAD(1,0,'NPAT',NPAT)
         CALL BAD(1,1,'UP  ',UP)
         CALL BAD(-1,1,'VP  ',VP)
         CALL BAD(1,0,'NPTL',NPATL)
         CALL BAD(1,1,'UPL ',UPL)
         CALL BAD(-1,1,'VPL ',VPL)
         CALL BAD(1,0,'NPTM',NPATM)
         CALL BAD(1,1,'UM  ',UM)
         CALL BAD(-1,1,'VM  ',VM)
         CALL BAD(-3,1,'RM  ',RM)
      ENDIF
C
      END
