**** SOURCE FILE : M0011451.V08   ***
*
C
C...  FORTRAN SUBROUTINE     NUMF1
C
C PURPOSE      TO DETERMINE THE NUMBER OF POINTS IN A PATERN,SCURV,SSURF
C              OR PREVIOUS CL DATA
C
C LINKAGE      CALL NUMF1(RESULT,PAT)
C              CALL NUMF2(RESULT,PAT,ARG2)
C
C ARGUMENTS    RESULT  REAL VARIABLE TO CONTAIN THE RESULTING
C                      NUMBER OF POINTS
C              PAT     ARRAY CONTAINING THE I.C.F. OF THE PATERN
C              OR BCD 'CLDATA'
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT094
C              LOGICAL FUNCTION    CKDEF
C              SUBROUTINE          ERROR
C
      SUBROUTINE NUMF1(RESULT,PAT)
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
      DIMENSION RESULT(1),PAT(1)
C
C
      INCLUDE 'TOTAL.INC'
C...  REFERENCE TO LOCAL VARIABLE, IS, CHANGED TO ISIZE,
C...  BECAUSE IS OCCURS IN IFXCOR.INC
      INCLUDE 'IFXCOR.INC'
C
C
      LOGICAL CKDEF
      INCLUDE 'BLANKCOM.INC'
C
      CHARACTER*8 HCLDA,TEST
      DATA HCLDA /'CLDATA  '/
C
      CALL HOLFRM (PAT(1),TEST,1,8,NWD)
      IF(TEST.EQ.HCLDA) GO TO 95
    1 IF(CKDEF(PAT))GO TO 90
      CALL UNPACK(PAT(1),MODE,ISIZE,ISUB)
      IF(MODE.NE.26.AND.MODE.NE.29.AND.MODE.NE.30)GOTO 90
C
C          MOVE THE EXTERNAL CANONICAL FORM TO  CANON
C
      CALL APT094(3,PAT,ILOC)
      IF(CKDEF(PAT))GO TO 90
      IF(MODE.NE.26)GOTO 20
C
C  NUMBER OF POINTS IS NOW IN CANON(ILOC+3)  (PATERN)
C
      RESULT(1)=CANON(ILOC+3)
C
      RETURN
C
C  COMPUTATIONS
C      SCURV ?
   20 IF(MODE.NE.30)GOTO 30
C         SCURV GIVEN
C  OUTPUT NUMBER OF ARCS WITH >NUMF(C)<
   21 RESULT(1)=CANON(ILOC+3)
      RETURN
C      SSURF ?
   30 IF(MODE.NE.29)GOTO 90
C         SSURF GIVEN
C  OUTPUT NUMBER OF PATCHES WITH >NUMF(S)<
   31 RESULT(1)=CANON(ILOC+3)
      RETURN
C
C   OUTPUT OF NUMBER OF POINTS IN LAST CUTTER PATH WITH >NUMF(CLDATA)<
C
   95 RESULT(1) = NUMCNT
      RETURN
C
C     USED GEOMETRY UNDEFINED OR WRONG INPUT
C
   90 CALL ERROR(36,'NUMF1   ')
  120 RESULT(1)=0.D0
      RETURN
C
C     ERROR DIAGNOSTIC 96
C     CLDAT SECTION NOT FOUND OR NOT CLOSED
  110 CALL ERROR(96,'NUMF1   ')
      GOTO 120
C
      END
C
      SUBROUTINE NUMF2(RESULT,PAT,ARG2)
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
      DIMENSION RESULT(1),PAT(1),ARG2(1)
C
C
      INCLUDE 'TOTAL.INC'
C...  REFERENCE TO LOCAL VARIABLE, IS, CHANGED TO ISIZE,
C...  BECAUSE IS OCCURS IN IFXCOR.INC
      INCLUDE 'IFXCOR.INC'
C
      INCLUDE 'CLDT.INC'
C
      LOGICAL CKDEF
      INCLUDE 'BLANKCOM.INC'
C
      CHARACTER*8 HCLDA,ARC,SEG,PATCH,SPLINE,CRSSPL,TEST1,TEST2
      DATA HCLDA /'CLDATA  '/
      DATA ARC   /'ARC     '/
      DATA SEG   /'SEG     '/
      DATA PATCH /'PATCH   '/
      DATA SPLINE/'SPLINE  '/
      DATA CRSSPL/'CRSSPL  '/
C
      CALL HOLFRM(PAT(1),TEST1,1,8,NWD)
      CALL HOLFRM(ARG2(1),TEST2,1,8,NWD)
      IF(TEST1.NE.HCLDA) GO TO 1
      IARG2=ARG2(1)
      DO 15 L=1,ICLCNT
      IF(IARG2.EQ.ICLTAB(1,L))GOTO 100
   15 CONTINUE
      GOTO 110
C
    1 IF(CKDEF(PAT))GO TO 90
      CALL UNPACK(PAT(1),MODE,ISIZE,ISUB)
      IF(MODE.NE.26.AND.MODE.NE.29.AND.MODE.NE.30)GOTO 90
C
C          MOVE THE EXTERNAL CANONICAL FORM TO  CANON
C
      CALL APT094(3,PAT,ILOC)
      IF(CKDEF(PAT))GO TO 90
      IF(MODE.EQ.26)GOTO 90
C
C  COMPUTATIONS
C      SCURV ?
   20 IF(MODE.NE.30)GOTO 30
C         SCURV GIVEN
      IF(TEST2.EQ.ARC)GOTO 21
      IF(TEST2.EQ.SEG)GOTO 22
      GOTO 90
C  OUTPUT NUMBER OF ARCS WITH >NUMF(C,ARC)<
   21 RESULT(1)=CANON(ILOC+3)
      RETURN
C  OUTPUT NUMBER OF SEGMENTS WITH >NUMF(C,SEG)<
   22 RESULT(1)=CANON(ILOC+7)
      IF(RESULT(1).EQ.0.D0)GOTO 90
      RETURN
C      SSURF ?
   30 IF(MODE.NE.29)GOTO 90
C         SSURF GIVEN
      IF(TEST2.EQ.PATCH)GOTO 31
C  ERROR , IF NOT MESH TYPE
      IF(CANON(ILOC+4).NE.2.D0)GOTO 90
      IF(TEST2.EQ.SPLINE)GOTO 32
      IF(TEST2.EQ.CRSSPL)GOTO 33
      GOTO 90
C  OUTPUT NUMBER OF PATCHES WITH >NUMF(S,PATCH)<
   31 RESULT(1)=CANON(ILOC+3)
      RETURN
C  OUTPUT NUMBER OF SPLINES WITH >NUMF(S,SPLINE)<
   32 RESULT(1)=CANON(ILOC+8)
      RETURN
C  OUTPUT NUMBER OF CROSS SPLINES WITH >NUMF(S,CRSSPL)<
   33 RESULT(1)=CANON(ILOC+9)
      RETURN
C
C   OUTPUT OF NUMBER OF POINTS IN LAST CUTTER PATH WITH >NUMF(CLDATA)<
C
   95 RESULT(1) = NUMCNT
      RETURN
  100 RESULT(1) = ICLTAB(2,L)
      RETURN
C
C     USED GEOMETRY UNDEFINED OR WRONG INPUT
C
   90 CALL ERROR(36,'NUMF2   ')
  120 RESULT(1)=0.D0
      RETURN
C
C     ERROR DIAGNOSTIC 96
C     CLDAT SECTION NOT FOUND OR NOT CLOSED
  110 CALL ERROR(96,'NUMF2   ')
      GOTO 120
C
      END
