**** SOURCE FILE : M0004164.V08   ***
*
C   PARAMETER FETCH  ROUTINES
C   CALLABLE AFTER EXTRINSIC EXTRACTION OF POINT/VECTOR IN APT109
C
C
C  ENTRY WITH 1 ARGUMENT
C
      SUBROUTINE PARMF1(RES,ARG1)
C
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
C
      DOUBLE PRECISION RES(1),ARG1(*)
C
      INCLUDE 'BLANKCOM.INC'
C
      COMMON/PARMFC/UA,VA,PNUM,UT,US,FNAM
C
      LOGICAL CKDEF
      DOUBLE PRECISION FNAM1,RTS(3)
      CHARACTER*4 UVAL,VVAL,PVAL,TVAL,SVAL,TEST
      DOUBLE PRECISION UA,VA,PNUM,UT,US,FNAM
      DATA UVAL/'UVAL'/,VVAL/'VVAL'/,PVAL/'PVAL'/
      DATA TVAL/'TVAL'/,SVAL/'SVAL'/
C
C
      IART=1
      IF(FNAM.EQ.0.D0)GOTO 20
      CALL HOLFRM(ARG1,TEST,1,4,NWD)
      IF(TEST.EQ.UVAL)GOTO 1
      IF(TEST.EQ.VVAL)GOTO 2
      IF(TEST.EQ.PVAL)GOTO 3
      IF(TEST.EQ.TVAL)GOTO 4
      IF(TEST.EQ.SVAL)GOTO 5
C  LOOK FOR FUNCTION WITH GEOMETRY INPUT
   30 IF(CKDEF(ARG1))GO TO 21
      CALL UNPACK(ARG1(1),MODE,IS,ISUB)
      IF(MODE.NE.29.AND.MODE.NE.30)GOTO 21
C          CHECK,IF RIGHT GEOMETRY
      FNAM1=ARG1(IS+1)
      IF(ISUB.GE.1)FNAM1=ARG1(ISUB*IS+ISUB)
      IF(FNAM.NE.FNAM1)GOTO 20
C
C          MOVE THE EXTERNAL CANONICAL FORM TO  CANON
C
      CALL APT094(3,ARG1,ILOC)
      IF(CKDEF(ARG1))GO TO 21
C   SSURF ?
      IF(MODE.NE.29)GOTO 35
C   SSURF GIVEN
      GOTO 3
C    SCURV ?
   35 IF(MODE.NE.30)GOTO 21
C   SCURV GIVEN
C  OUTPUT FOR >PARMF(C)< OR >PARMF(C,PARAM)<
   36 RES(1)=US+UT-1.D0
      RETURN
C  OUTPUT FOR >PARMF(UVAL)< OR >PARMF(S,UPARAM)< (NON MESH TYPE)
    1 RES(1)=UA
      RETURN
C  OUTPUT FOR >PARMF(VVAL)< OR >PARMF(S,VPARAM)< (NON MESH TYPE)
    2 RES(1)=VA
      RETURN
C  OUTPUT FOR >PARMF(PVAL)< OR >PARMF(S,PATCH)<
    3 RES(1)=PNUM
      RETURN
C  OUTPUT FOR >PARMF(TVAL)<
    4 RES(1)=UT
      RETURN
C  OUTPUT FOR >PARMF(SVAL)<
    5 RES(1)=US
      RETURN
C    'NO PARAMETER EXISTING'
   20 CALL ERROR(42,'PARMF   ')
      GOTO 22
C    'WRONG PARMF CALL'
   21 CALL ERROR(43,'PARMF   ')
   22 RES(1)=0.D0
      RETURN
      END
C
C
C
C
C  ENTRY WITH TWO ARGUMENTS
      SUBROUTINE PARMF2(RES,ARG1,ARG2)
C
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
C
      DOUBLE PRECISION RES(1),ARG1(*),ARG2(1)
C
      INCLUDE 'BLANKCOM.INC'
C
      COMMON/PARMFC/UA,VA,PNUM,UT,US,FNAM
C
      LOGICAL CKDEF
      DOUBLE PRECISION FNAM1,RTS(3)
      CHARACTER*8 FLOW,PARAM,UPARAM,VPARAM,PATCH,TEST
      DOUBLE PRECISION UA,VA,PNUM,UT,US,FNAM
      DATA FLOW  /'FLOW    '/
      DATA PARAM /'PARAM   '/
      DATA UPARAM/'UPARAM  '/
      DATA VPARAM/'VPARAM  '/
      DATA PATCH /'PATCH   '/
C
C
      IART=2
      IF (FNAM.EQ.0.D0) GOTO 20
      CALL HOLFRM(ARG2,TEST,1,8,NWD)
C  LOOK FOR FUNCTION WITH GEOMETRY INPUT
   30 IF(CKDEF(ARG1))GO TO 21
      CALL UNPACK(ARG1(1),MODE,IS,ISUB)
      IF(MODE.NE.29.AND.MODE.NE.30)GOTO 21
C          CHECK,IF RIGHT GEOMETRY
      FNAM1=ARG1(IS+1)
      IF(ISUB.GE.1)FNAM1=ARG1(ISUB*IS+ISUB)
      IF(FNAM.NE.FNAM1)GOTO 20
C
C          MOVE THE EXTERNAL CANONICAL FORM TO  CANON
C
      CALL APT094(3,ARG1,ILOC)
      IF(CKDEF(ARG1))GO TO 21
C   SSURF ?
      IF(MODE.NE.29)GOTO 35
C   SSURF GIVEN
      IF(TEST.EQ.PATCH )GOTO 3
C   MESH TYPE ?
      IF(CANON(ILOC+4).EQ.2.D0)GOTO 31
      IF(TEST.EQ.UPARAM)GOTO 1
      IF(TEST.EQ.VPARAM)GOTO 2
      GOTO 21
C  MESH TYPE
   31 IP=PNUM
      NU=CANON(ILOC+9)-1.D0
      IV=(IP-1)/NU
      IF(TEST.EQ.UPARAM)GOTO 32
      IF(TEST.EQ.VPARAM)GOTO 33
      GOTO 21
C  GLOBAL U-PARAMETER  >PARMF(S,UPARAM)< (MESH TYPE)
   32 IU=IP-1-IV*NU
      RES(1)=IU+UA
      RETURN
C  GLOBAL V-PARAMETER  >PARMF(S,VPARAM)< (MESH TYPE)
   33 RES(1)=IV+VA
      RETURN
C    SCURV ?
   35 IF(MODE.NE.30)GOTO 21
C   SCURV GIVEN
      IF(TEST.EQ.PARAM )GOTO 36
      IF(TEST.EQ.FLOW  )GOTO 37
C  OUTPUT FOR >PARMF(C)< OR >PARMF(C,PARAM)<
   36 RES(1)=US+UT-1.D0
      RETURN
   37 IF(CANON(ILOC+7).EQ.0.D0)GOTO 21
C  OUTPUT FOR >PARMF(C,FLOW)<
C  SEARCH IN FLOW DESCRIPTION OF NATURAL SEGMENT
      IS=US-1.D0
      IFSEG=CANON(ILOC+6)
      IFLOW1=CANON(ILOC+IFSEG-1+4*IS)
      IFLOW2=IFLOW1+(CANON(ILOC+IFSEG+4*IS)-1.D0)*4.D0
      IFLOW1=IFLOW1+ILOC-1
      IFLOW2=IFLOW2+ILOC-1
      DO 40 IFLOW=IFLOW1,IFLOW2,4
      IF(UT.GE.CANON(IFLOW+1).AND.UT.LT.CANON(IFLOW+5)) GOTO 50
   40 CONTINUE
      GOTO 21
C  COMPUTE FLOW-PARAMETER
   50 SPAN=CANON(IFLOW+4)-CANON(IFLOW)
      UA=CANON(IFLOW+1)
      UB=CANON(IFLOW+5)
      UMA=CANON(IFLOW+2)*SPAN
      UMB=CANON(IFLOW+6)*SPAN
      W1=3.D0*(UB-UA)-UMA-UMA-UMB
      W2=2.D0*(UA-UB)+UMA+UMB
      CALL GCUBIC(W2,W1,UMA,UA-UT,RTS,MN)
      IF(MN.EQ.0) GOTO 21
      DO 60 I=1,MN
      PU=RTS(I)
      IF(PU.GE.-1.D-7.AND.PU.LT.1.0000001D0) GOTO 70
   60 CONTINUE
      GOTO 21
C COMPUTE GLOBAL FLOW PARAMETER
   70 PU=CANON(IFLOW)+PU*SPAN
      ISEG1=ILOC-1+CANON(ILOC+8)
      ISEGA=CANON(ILOC+7)
      ISEG2=ISEG1+(ISEGA-1)*4
      USN=US-1.D0
      USF=0.D0
      DO 80 ISEG=ISEG1,ISEG2,4
      IF(CANON(ISEG)+CANON(ISEG+1).GT.USN) GOTO 90
      USF=USF+1.D0
   80 CONTINUE
C COMPUTE FINAL GLOBAL FLOW PARAMETER
   90 RES(1) = USF+PU
      RETURN
C  OUTPUT FOR >PARMF(UVAL)< OR >PARMF(S,UPARAM)< (NON MESH TYPE)
    1 RES(1)=UA
      RETURN
C  OUTPUT FOR >PARMF(VVAL)< OR >PARMF(S,VPARAM)< (NON MESH TYPE)
    2 RES(1)=VA
      RETURN
C  OUTPUT FOR >PARMF(PVAL)< OR >PARMF(S,PATCH)<
    3 RES(1)=PNUM
      RETURN
C  OUTPUT FOR >PARMF(TVAL)<
    4 RES(1)=UT
      RETURN
C  OUTPUT FOR >PARMF(SVAL)<
    5 RES(1)=US
      RETURN
C    'NO PARAMETER EXISTING'
   20 CALL ERROR(42,'PARMF   ')
      GOTO 22
C    'WRONG PARMF CALL'
   21 CALL ERROR(43,'PARMF   ')
   22 RES(1)=0.D0
      RETURN
      END
