**** SOURCE FILE : M0012387.V01   ***
*
      SUBROUTINE POLMTN(NS,POED,M,N)
C
C  TO COMPUTE A M*N POLYEDRON TO SEARCH FOR ROUGH INTERSECTION
C
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
      DOUBLE PRECISION POED(3,M,N)
C
C SS - ARELEM - COMMON
      COMMON/SSARLM/BB(64,4),UU(4),VV(4),
     *              IITOP(6,4,4),IIFLAG(4,4),IPNUM(4)
C
C AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
C
      DO 1 J=1,N
      V=J-1
      V=V/4.D0
      DO 1 I=1,M
      U=I-1
      U=U/4.D0
      CALL CNSURF(U,V,BB(1,NS),POED(1,I,J),IIFLAG(1,NS),0)
    1 CONTINUE
C
      RETURN
      END
