**** SOURCE FILE : PUNIDS00.ORG   ***
*
      REAL FUNCTION PUNIDS()
*
*  * PUNIDS *  VAX-11 FORTRAN 77 VERSION  21.10.82  E.MCLELLAN
*
*  PURPOSE     TO RETREIVE CARD IDENTIFICATION AND SEQUENCE NUMBER
*
*  CALLING SEQUENCE
*              VALUE = PUNIDS()
*  ARGUMENT
*              NONE    NOTE: PARENTHESIS MUST APPEAR
*              VALUE   WILL CONTAIN 4 BCD CHARACTERS BEING IDENT
*  ALTERNATE ENTRY
*              VALUE = PUNNOM()
*
*              VALUE   WILL CONTAIN REAL*4 VALUE BEING CURRENT
*                      SEQUENCE NUMBER
*
      COMMON/PUN/PNID,PNO
C
      PUNIDS=PNID
      RETURN
C
      ENTRY PUNNOM()
      PUNNOM=PNO
      RETURN
      END
