**** SOURCE FILE : REMSCN.ORG   ***
*
      SUBROUTINE REMSCN(TE,TA,TUL,R,PSIDE,PTHICK,TOLIN,NPAT,LSUSP,NSUSP)
C
C     PURPOSE: TO TEST ALL REMOTE (NON-CURRENT) PATCHES FOR POSSIBLE
C              INTEFERENCE
C
C     ARGUMENTS:
C
C     TE      -  TOOL END COORDINATES
C     TA      -  TOOL AXIS VECTOR
C     TUL     -  TOOL GEOMETRY
C     R       -  SURFACE CONTACT POINT AND DERIVATIVES
C     PSIDE   -  1 OR -1 TO AJUST SURFACE NORMAL (RU X RV)
C     PTHICK  -  THICKNESS OFFSET FROM SURFACE
C     TOLIN   -  TOLERANCE (PS INTOL)
C     NPAT    -  PATCH NUMBER FOR CONTACT POINT
C     LSUSP   -  SUSPECT PATCHES
C     NSUSP   -  NUMBER OF SUSPECT PATCHES
C
      DOUBLE PRECISION TE,TA,TUL,R,PSIDE,PTHICK,TOLIN
      INTEGER IPSIZE,NPAT
C
      DIMENSION TE(3),TA(3),TUL(7),R(32)
C
      INTEGER NSUSP,LSUSP,MXSUSP
      PARAMETER (MXSUSP=1000)
C
      DIMENSION LSUSP(MXSUSP)
C
      DOUBLE PRECISION BIG5,ETA6
C
      PARAMETER (BIG5=1D5,ETA6=1D-6)
C
C.... LOCAL VARIABLES
C
C     TCCENT  -  CENTRE OF TOOL CONTACT SPHERE
C     TCRAD   -  RADIUS OF TOOL CONTACT SPHERE
C     TLCENT  -  CENTRE OF LARGE SHALLOW SPHERE THROUGH TE, RADIUS BIG5
C     TCENT   -  CENTRE OF TIGHT SPHERE ENVELOPING TOOL, RADIUS=TUL(2)
C     BALL    -  CUTTER TYPE FLAG = .TRUE. IF CUTTER IS BALLENDED
C                                 = .FALSE. OTHERWISE
C     ISEG    -  INDICATES SEGMENT OF TOOL THAT PENETRATES
C                         = -1 IF NO PENETRATION
C                         =  0   BOTTOM FLAT
C                         =  1   CORNER RADIUS
C                         =  2   CYLINDER
C     V1      -  VECTOR FROM TOOL TIP TO CENTRE OF PATCH SPHERE
C     V2      -  V1 X TA
C     D       -  MINIMUM DISTANCE BETWEEN CENTRE OF PATCH SPHERE
C                AND TOOL AXIS
C     D2      -  SQUARE OF DISTANCE BETWEEN TWO SPHERE CENTRES
C     A       -  MINIMUM DISTANCE BETWEEN SPHERE CENTRES TO AVOID
C                INTERFERENCE
C
      DOUBLE PRECISION TCCENT,TCRAD,TLCENT,TCENT
      DIMENSION TCCENT(3),TLCENT(3),TCENT(3)
C
      LOGICAL BALL,INTF
C
      DOUBLE PRECISION V1,V2,D,D2,A
      DIMENSION V1(3),V2(3)
C
      INCLUDE 'INIDAT.INC'
C
C.... CALCULATE TOOL CONTACT SPHERE FOR CURRENT TOOL POSITION
C
      CALL TCSPHR(TE,TA,TUL,R,PSIDE,PTHICK,TCCENT,TCRAD)
C
C.... CALCULATE CENTRE OF LARGE SHALLOW SPHERE THROUGH TE
C     AND CENTRE OF TIGHT SPHERE ENVELOPING TOOL
C
      DO 10 I=1,3
        TLCENT(I) = TE(I) + BIG5*TA(I)
        TCENT(I)  = TE(I) + TUL(2)*TA(I)
  10  CONTINUE
C
C.... SET FLAG INDICATING CUTTER TYPE
C
      IF ( ABS(TUL(1)-TUL(2)).LE.ETA6 ) THEN
C.... BALL-ENDED
        BALL=.TRUE.
      ELSE
        BALL=.FALSE.
      ENDIF
C
C.... TEST NON-CURRENT PATCHES FOR POSSIBLE INTERFERENCE
C
      NSUSP=0
      DO 1000 K=1,NGP
        IF (K.NE.NPAT) THEN
C
C.... TEST FOR INTERFERENCE OF INFINITE TOOL CYLINDER WITH
C     MINIMUM PATCH SPHERE
C
          DO 100 I=1,3
            V1(I)=CXHULL(I,1,K)-TE(I)
  100     CONTINUE
          CALL CROSS(V1,TA,V2)
          CALL VECMOD(V2,D)
          IF (D.GE.(CXHULL(4,1,K)+PTHICK+TUL(2)-TOLIN)) GOTO 1000
C
C.... STILL POSSIBLE INTERFERENCE WITH THIS PATCH
C
C.... TEST FOR INTERFERENCE OF TIGHT TOOL SPHERE
C     WITH ALL PATCH CONVEX HULL SPHERES
C
          DO 200 J=1,NCXHUL(K)
            D2=DIST2(CXHULL(1,J,K),TCENT)
            A=CXHULL(4,J,K)+PTHICK+TUL(2)-TOLIN
            IF (D.GE.A*A) GOTO 1000
  200     CONTINUE
C
C.... STILL POSSIBLE INTERFERENCE WITH THIS PATCH
C
C.... TEST FOR INTERFERENCE OF SHALLOW TOOL SPHERE
C     WITH ALL PATCH CONVEX HULL SPHERES
C
          DO 300 J=1,NCXHUL(K)
            D2=DIST2(CXHULL(1,J,K),TLCENT)
            A=CXHULL(4,J,K)+PTHICK+BIG5-TOLIN
            IF (D.GE.A*A) GOTO 1000
  300     CONTINUE
C
C.... STILL POSSIBLE INTERFERENCE WITH THIS PATCH
C
C.... TEST FOR INTERFERENCE OF TOOL CONTACT SPHERE
C     WITH ALL PATCH CONVEX HULL SPHERES
C
          DO 400 J=1,NCXHUL(K)
            D2=DIST2(CXHULL(1,J,K),TCCENT)
            A=CXHULL(4,J,K)+PTHICK+TCRAD-TOLIN
            IF (D.GE.A*A) GOTO 1000
  400     CONTINUE
C
C.... STILL POSSIBLE INTERFERENCE WITH THIS PATCH
C
C.... TEST FOR INTERFERENCE OF ACTUAL TOOL
C     WITH ALL PATCH CONVEX HULL SPHERES
C     UNLESS CUTTER IS BALL-ENDED
C
          IF (.NOT.BALL) THEN
            DO 500 J=1,NCXHUL(K)
              CALL HULCUT (TE,TA,TUL,CXHULL(1,J,K),IRET)
              IF (IRET.LT.0) GOTO 1000
  500       CONTINUE
          ENDIF
C
C.... PATCH NOT CLEARED - ADD TO SUSPECT LIST
C
          NSUSP=NSUSP+1
          LSUSP(NSUSP)=K
        ENDIF
 1000 CONTINUE
C
      END
