**** SOURCE FILE : RESET.ORG   ***
*
      SUBROUTINE RESET
C
C     PURPOSE: TO RESET INTERFERENCE TABLE FOR NEXT POINT
C
      INCLUDE 'INTERF.INC'
C
C
      DO 200 I=1,NPINTR
C
        LDINTR(I)=DINTR(I)
        LPINTR(I)=PINTR(I)
        LUINTR(I)=UINTR(I)
        LVINTR(I)=VINTR(I)
C
        DINTR(I)=0.D0
        PINTR(I)=0
        UINTR(I)=0.D0
        VINTR(I)=0.D0
C
        ISEG(I)=0
        DO 100 J=1,3
          TPINTR(J,I)=0.D0
          SPINTR(J,I)=0.D0
          SNINTR(J,I)=0.D0
  100   CONTINUE
C
  200 CONTINUE
C
      LNPINT=NPINTR
      NPINTR=0
C
      END
