**** SOURCE FILE : M0000962.V03   ***
*
C.....IMPLEMENTATION DEPENDENT SUBROUTINE ...SEQ           8/68      HG
C.....FORTRAN ROUTINE              ..SEQ..     HL GRAY 3/68         *ID*
      SUBROUTINE  SEQ (N)
C        THIS ROUTINE EXISTS ONLY BECAUSE     SQNC MAY ONLY APPEAR IN
C        A PROGRAM COMPILED IN EBCDIC.
      COMMON/SQNC/SQNC
      INTEGER  SQNC
      INTEGER N
      SQNC = N
      RETURN
      END
