**** SOURCE FILE : M0006686.V03   ***
*
C
C              FORTRAN SUBROUTINE SETMOD
C
C LINKAGE      SUBROUTINE SETMOD(PNTR,CLASS)
C
C          SUBSIDIARIES                  CALLED BY
C          NONE                          TYPE          ENTRY
C                                        SUBROUTINE    LARGES
C                                        SUBROUTINE    PRO020
C                                        SUBROUTINE    RECOG
C                                        SUBROUTINE    RECOGN
C                                        SUBROUTINE    REPLAC
C
      SUBROUTINE SETMOD(PNTR,CLASS)
C
      IMPLICIT INTEGER (A-Z)
C
C        1.    NAME TABLE AND TABLE LIMITS
C
      INCLUDE 'NAMETB.INC'
C NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY
C CNAMTB:      NAME TABLE OR DICTIONARY
C
C        2.    STACK AND POINTER STORAGE
C
      COMMON/STKLST/STKLST
      DIMENSION STKLST(300),STACK(2,99)
C STACK:       WORKING STACK
      EQUIVALENCE (STACK(1,1),STKLST(4))
C
C        3.    METALINGUISTIC VARIABLE CLASS CODES
C
      COMMON/CODE/CODE
      DIMENSION CODE(150),GEOM(2),FCN(2),PROCED(2),PERMID(2),BIGGEO(2)
C GEOM:        (1)=CODE CLASS 16000,(2)=NAMTBL INDEX OF 'GEOM  '
      EQUIVALENCE (GEOM(1),CODE(31))
C FCN:         (1)=CODE CLASS 18000,(2)=NAMTBL INDEX OF 'FCN   '
      EQUIVALENCE (FCN(1),CODE(35))
C PROCED:      (1)=CODE CLASS 19000,(2)=NAMTBL INDEX OF 'PROCED'
      EQUIVALENCE (PROCED(1),CODE(37))
C PERMID:      (1)=CODE CLASS 20000,(2)=NAMTBL INDEX OF 'PERMID'
      EQUIVALENCE (PERMID(1),CODE(39))
C BIGGEO:      (1)=CODE CLASS 44000,(2)=NAMTBL INDEX OF 'BIGGEO'
      EQUIVALENCE (BIGGEO(1),CODE(87))
C
C        4.    PRODUCTION TABLE
C
      COMMON/SRCTBL/SRCTBL
      DIMENSION SRCTBL(502),META(50)
C META:        CONTAINS INTERNAL BIT CODES FOR METALINGUISTIC CLASSES
      EQUIVALENCE (META(1),SRCTBL(3))
C
C       29.    CLASS CODE MODULI
C
      COMMON/MODULI/MODULI
      DIMENSION MODULI(2)
C MODULO:      NAMTBL CLASS AND CODE FACTOR 1000 TO DEVIDE OUT CLASS
      EQUIVALENCE (MODULO,MODULI(1))
C*
C ARGUMENTS    PNTR      WORKING STACK (STACK) POINTER OF
C                        ITEM WHOSE CLASS IS TO BE CHANGED.
C              CLASS     NEW META-LINQUISTIC CLASS ASSIGNMENT.
C
C NOTES        IF CLASS IS PERMID, PROCED, OR GEOM, IT IS
C              ASSUMED THAT PREVIOUS CLASS WAS IDENT, CONPRO,
C              OR CONGEO, RESPECTIVELY, IN WHICH CASE THE
C              ORIGINAL MODE IS RETAINED.
C
C     CHANGE THE CLASS OF A CHARACTER
C**
      DIMENSION CLASS(2)
      I=STACK(1,PNTR)
      J = CLASS(1)
       IF ((J .EQ. PERMID(1)) .OR. (J .EQ. GEOM(1)) .OR.
     /(J .EQ. BIGGEO(1)) .OR. (J .EQ. PROCED(1)))  GO TO 1
      IF(J.EQ.FCN(1))GO TO 1
      NAMTBL(I) = J
      GO TO 2
    1 NAMTBL(I) = J+(NAMTBL(I)-MODULO*(NAMTBL(I)/MODULO))
    2 J = J/MODULO
      STACK(2,PNTR)=META(J)
      RETURN
       END
