**** SOURCE FILE : M0000658.V02   ***
*
      SUBROUTINE SMMULT(L,M,N,KS,A,B,C)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C--- SCULPTURED SURFACE ROUTINE FOR MATRIX MULTIPLY
C---  A IS AN INPUT MATRIX L ROWS BY M COLUMNS
C--- B IS AN INPUT MATRIX M ROWS X N COLUMNS
C--- KS DETERMINES WHERE THE OUTPUT IS LOADED
C--- KS =1 A  KS=2 B  KS=3 C
C--- NO INPUT MATRIX IS ALTERED UNLESS REQUESTED
      DIMENSION A(*),B(*),C(*)
      DIMENSION D(16)
      KN(I,J,KK)=I+(J-1)*KK
      DO 10 JC=1,N
      DO 10 IR=1,L
      KLOC=KN(IR,JC,L)
      D(KLOC)=0.0
      DO 20 KK=1,M
      KA=KN(IR,KK,L)
      KB=KN(KK,JC,M)
      D(KLOC)=D(KLOC)+A(KA)*B(KB)
   20 CONTINUE
   10 CONTINUE
      MSIZE=L*N
      GO TO (100,200,300),KS
  100 CONTINUE
      DO 110 K=1,MSIZE
  110 A(K)=D(K)
      GO TO 999
  200 CONTINUE
      DO 210 K=1,MSIZE
  210 B(K)=D(K)
      GO TO 999
  300 CONTINUE
      DO 310 K=1,MSIZE
  310 C(K)=D(K)
  999 RETURN
      END
