*
*                MODIFIED                 9-MAY-1989  E.MCLELLAN
       SUBROUTINE SPRVIS
C... PURPOSE,  CALLS EACH PHASE OF APT4 AND EXECUTES IT.  IN ADDITION
C    IT CHECKS FOR ERROR CONDITIONS AND FLAGS WHICH CAN TERMINATE A
C    PART PROGRAM BEFORE ALL PHASES ARE COMPLETE.  BATCH PROCESSING
C    IS POSSIBLE USING THIS SUPERVISOR.
C
C CALLS  LOAD MODULES   TRANSLAT,XECUTION,CLEDITOR,POSTEXEC.
C
C
C... DICTIONARY
C
C ABEND  - FLAG INDICATING ABNORMAL TERMINATION
C ASM    - FLAG TO INDICATE IF ASSEMBLY APPROACH IS TO BE USED
C CFLAGS - SEE ERR,XC,CL,PX
C CL     - FLAG INDICATING EXECUTION TO TERMINATE AT PHASE 3
C CX     - HOLDS CURRENT STRING OF EIGHT CHARACTERS
C END      FLAG SET FALSE WHEN IT IS DETERMINED THAT ANOTHER PART
C            PROGRAM FOLLOWS
C ERR    - FLAG INDICATING ERRORS ARE NOT TO TERMINATE PROGRAM
C ERRX   - ERROR LEVEL
C ETIME  - ELAPSED TIME
C FINI   - FLAG TO INDICATE IF A FINI CARD HAS BEEN READ
C INFILE - INPUT FILE
C LXTRAS - SAME AS XTRAS
C PHASE  - NAME OF PHASE BEING EXECUTED
C PX     - FLAG INDICATING EXECUTION TO TERMINATE AT PHASE 4
C START  - TIME AT WHICH A PART PROGRAM BEGINS EXECUTION
C TIME0  - TIME AT WHICH A PHASE STARTS
C TIME1  - CURRENT TIME
C VLFILE - VARIFACATION LISTING(PRINTER) FILE
C WX     - EQUIVALENT TO CX
C X      - HOLDS CARD IMAGE
C XC     - FLAG INDICATING EXECUTION TO TERMINATE AT PHASE 2
C XTRAS(1)- CONTAINS NUMBER OF ERRORS
C
C
C
C...      32.  PARAMETERS REQUIRED BY SUPERVISOR
C
      INCLUDE 'SUPER.INC'
C
      INCLUDE 'SYMFIL.INC'
C
      DOUBLE PRECISION ETIME
      INTEGER START,TIME0,TIME1
      DIMENSION  DIAGS(33)
      CHARACTER  X(80),CX(8),T,XXXX*80
      CHARACTER*4 WX,XFINI,XBLNK,BLANK
      EQUIVALENCE (T,XBLNK)
      EQUIVALENCE (WX,CX(1))
C
C........SET UP PARAMETERS FOR ASSEMBLY APPROACH
      CHARACTER LXPARM*21,PARASM*16,IRDS*80
C
      CHARACTER*8 PHASE(4)
      CHARACTER*8 PHAS1(5)
      EQUIVALENCE (PHAS1(2),PHASE(1))
      CHARACTER*8 ACTION(3)
      COMMON/PARLST/JPAR
      CHARACTER*4 KPAR(4),JPAR(20)
C
      COMMON /AENT/ KENTRY
      COMMON /CMPTST/ICMTES
C
      CHARACTER*132 DARRAY
      CHARACTER LARRAY(132),LPCOMP*4
      EQUIVALENCE (DARRAY,LARRAY(1))
C
      DATA  WX/'    '/, XFINI/'FINI'/
      DATA  XBLNK,BLANK/'    ','    '/
      DATA  LXPARM/'OVLY,NOLIST,NOMAP,LET'/
      DATA  PARASM/'LOAD,NODECK,LIST'/
      DATA IRDS/'REMARK'/
      DATA PHASE/'TRANSLAT','XECUTION','CLEDITOR','POSTEXEC'/
      DATA PHAS1(1)/'SUPERVIS'/
      DATA ACTION/' CONTINU','TERMINAT','TERMINAT'/
      DATA KPAR/'TR  ','XC  ','CL  ','PX  '/
      DATA DARRAY/' '/
      DATA LPCOMP/'COMP'/
C  ------------------- INITIALIZE FOR PART PROGRAM ----------------
      IABND=0
      ICNT=0
      CALL GETPRM
      CALL ARTIME
C
      IRDSAV=IRDS
      END= .TRUE.
   50 FINI=.FALSE.
C
C START THE CLOCK
  100 CALL CLOCF4(START)
      TIME0 = START
C
C INTERPRETIVE METHOD IS THE DEFAULT.
      ASM  = .FALSE.
      JJEX = 0
      JEX = 0
C---      DEFAULT- OUTPUT PRINT NOT COMPRESSED
      ICMTES=0
C
C ERRORS ARE TO TERMINATE PROGRAM,ALL PHASES WILL BE PROCESSED.
      ERR=.FALSE.
      XC=.FALSE.
      CL=.FALSE.
      PX=.FALSE.
      I=1
      IF(ICNT.EQ.0) GO TO 106
      IF(JPAR(1).EQ.KPAR(1)) I=1
      IF(JPAR(1).EQ.KPAR(2)) I=2
      IF(JPAR(1).EQ.KPAR(3)) I=3
      IF(JPAR(1).EQ.KPAR(4)) I=4
  106 CONTINUE
C
C---       TEST FOR COMP IN PARM LIST
      IF(JPAR(1).EQ.LPCOMP) ICMTES=1
C START NEW PAGE ON PRINTER.
      CALL CFORM ('1',DARRAY,1,1)
      CALL CFORM('CAM-I SCULPTURED SURFACE SSV3  SYSTEM.',DARRAY,5,38)
      CALL CFORM(' CAM-I INC., ARLINGTON,TEXAS  MAY,89 ',DARRAY,43,37)
      CALL CPRINT(DARRAY)
      CALL CPRINT (DARRAY)
C
C
C  EXECUTE PHASE I
C
  119 CONTINUE
C
C SET ERROR LEVEL AT 0.
      ERRX = 0
C
C SET ERROR COUNT AT 0.
      XTRAS(1) = 0
      XTRAS(2) = 0
C
C ASSUME ABNORMAL TERMINATION.
      ABEND= .TRUE.
C
C TEST FOR ASSEMBLY APPROACH AND PHASE TWO.
      J=1
      IF(ASM.AND.I.EQ.2) GO TO 999
      IF ( JPAR(1) .EQ. KPAR(2)) ASM = .TRUE.
C
C LOAD AND EXECUTE PHASE (I).
  120 CALL LINKF (PHASE(I))
C...     SET J - DETERMINE IF PROCESSING SHOULD CONTINUE
      J = 1
C
C IF ERR LEVEL GREATER THAN 4 AND CONTINUE NOT INDICATED, END PART PROG.
      IF(ERRX.GT.JJEX) JJEX = ERRX
      IF(JEX.EQ.2.AND.I.EQ.3) J=2
      IF(.NOT.ERR.AND.(ERRX.GT.4).AND.(I.NE.2)) J=2
      IF(.NOT.ERR.AND.(ERRX.GT.4).AND.(I.EQ.2)) JEX=2
C
C IF ABEND NOT TURNED OFF OR ERR LEVEL GREATER THAN 8, TERMINATE.
      IF(ABEND.OR.ERRX.GT.8) J=3
C IF NO ERRORS, CONTINUE.
      IF(ERRX.EQ.0) GOTO 110
C
C PRINT NUMBER OF ERRS AND ACTION TO BE TAKEN.
  130 CALL ICONV(XTRAS(1),DARRAY,5,3)
      CALL CFORM('0***',DARRAY,1,4)
      CALL CFORM(' ERROR(S) AND     WARNING(S) IN THIS PHASE. PROCESSING
     / ',DARRAY,9,55)
      CALL ICONV(XTRAS(2),DARRAY,23,3)
      CALL CFORM(ACTION(J),DARRAY,64,8)
      CALL CFORM('ED.***',DARRAY,72,6)
      CALL CPRINT (DARRAY)
C
C PRINT ELAPSED TIME.
  110 CALL CLOCF4(TIME1)
      ETIME = IABS(TIME1-TIME0)/100.0
      CALL CFORM('0APT-IV   SSV3 ',DARRAY,1,15)
      CALL CFORM(PHASE(I),DARRAY,19,8)
      CALL CFORM('PHASE - CPU TIME=',DARRAY,29,17)
      CALL FCONV(ETIME,DARRAY,47,6,2)
      CALL CFORM('SECS.',DARRAY,55,5)
      CALL CPRINT (DARRAY)
C
C  IF J=1, PROCESSING CONTINUES.  IF J=2, PROCESSING TERMINATES.
C        IF J=3, ABNORMAL TERMINATION.
      GO TO (140,800,900), J
C
C WAS THERE A REQUEST TO TERMINATE AT THE END OF THIS PHASE.
  140 CONTINUE
C
      TIME0 = TIME1
      IF (I.EQ.4) GO TO 800
      I=I+1
      IF(.NOT.CFLAGS(I))GOTO 119
C
C
C
C  XC,CL OR PX APPEARS IN CONTRL/ STATEMENT OR NOPOST=CNTRL/PX
C
  600 CALL CFORM('0***PROGRAM TERMINATED AT REQUESTED PHASE***',
     C         DARRAY,1,44)
      CALL CPRINT (DARRAY)
      J=4
C
C  END OF A PART PROGRAM PROCESSING.
C
  800 ETIME = IABS(TIME1-START)/100.0
      CALL FCONV(ETIME,DARRAY,47,6,2)
      CALL CFORM('0',DARRAY,1,1)
      CALL CFORM('TOTAL - CPU TIME=',DARRAY,29,17)
      CALL CFORM('SECS.',DARRAY,55,5)
      CALL CPRINT (DARRAY)
C
C
      CALL CFORM('0APT-IV    ERROR LEVEL IN THIS PART PROGRAM =',
     C  DARRAY,1,45)
      CALL ICONV(JJEX,DARRAY,45,3)
      CALL CPRINT (DARRAY)
      IF (IABND.EQ.1) GO TO 999
C
C
C CHECK FOR END OF DATA - THAT IS, NO MORE PART PROGRAMS
  850 IF (ASM) GO TO 999
      IF (.NOT. END) GO TO 999
      CALL CREAD(IRDSAV,IRET)
      IF(IRET.EQ.1) GO TO 999
      END=.FALSE.
      CALL TAPOP(CLFIL3,-3)
      CALL TAPOP(EXFILE,-3)
      CALL TAPOP(MACTXT,-3)
      CALL TAPOP(XNUM,-3)
      CALL CFORM('0*** ONLY ONE PART PROGRAM PERMITTED***',DARRAY,1,39)
      CALL CPRINT(DARRAY)
      GOTO 999
C
C
      ENTRY ABNEND
C
      IABND=1
C
C  PHASE DID NOT HAVE A NORMAL ENDING.
C
  900 CALL CFORM('0***ABNORMAL TERMINATION OF ',DARRAY,1,28)
      CALL CFORM(PHASE(I),DARRAY,28,8)
      CALL CFORM('PHASE***',DARRAY,37,8)
      CALL CPRINT(DARRAY)
      JJEX = 16
      IF(IABND.EQ.1) GO TO 800
C
      IF(FINI) GOTO 800
C
C  NO FINI.  SKIP TO END OF PART PROGRAM.
  905 CALL CREAD(XXXX,IRET)
      WX=BLANK
      IF(IRET.EQ.1) GO TO 999
      J=1
      K=0
  920 K=K+1
      T=X(K)
      IF (XBLNK .EQ. BLANK) GO TO 920
      CX(J) = X(K)
      J=J+1
      IF (J.LE.4) GO TO 920
      IF (WX .EQ. XFINI) GO TO 800
      GOTO 905
C
C
C  END OF ALL PART PROGRAM PROCESSING.
C
  999 JRTN=JJEX
      IF ( J.EQ.1 .AND. ERRX.LT.4 ) JRTN = 0
      CALL CPUCLO
      CALL CRTN(JRTN)
      GO TO 999
C
      END
