**** SOURCE FILE : M0002864.V06   ***
*
C
C.....FORTRAN SUBROUTINE             SRFVCT...              3/1/68   GK
      SUBROUTINE SRFVCT(SRFACE,VECTOR)
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
C
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'FXCOR.INC'
      INCLUDE 'HOLRTH.INC'
      INCLUDE 'SV.INC'
      INCLUDE 'ISV.INC'
      INCLUDE 'IFXCOR.INC'
      INCLUDE 'ISHR18.INC'
      INCLUDE 'KNUMBR.INC'
C
C     25. COMMON FOR AERR INFORMATION
C
      COMMON /AERCOM/ IAERFG,NPCTPT,PCTPTS,PCTPLN,ERRPTS
      DIMENSION PCTPTS(3,20),PCTPLN(4),ERRPTS(3,3)
C
      CHARACTER*8 TEST
      INTEGER IHDS(2),BCDF
      EQUIVALENCE (IHDS,VALHDS)
C
C...  NEW DIRECTION OF MOTION IS ALONG VECTOR
C...  STORE DIRECTION VECTORS FOR DS,PS,CS AS REQUIRED
      DIMENSION VECTOR(3)
      TEMP(1)=SRFACE
    3 K=IDS
      CALL HOLFRM(TEMP(1),TEST,1,8,NWD)
      IF(HDS.EQ.TEST) GO TO 5
      K=IPS
      IF(HPS.EQ.TEST) GO TO 5
      K=ICS
      IF(HCS.NE.TEST) GO TO 50
    5 DO 10 I=1,3
      SFVCT(1,K)=VECTOR(I)
   10 CONTINUE
      CALL TRANSM (SFVCT(1,K),VECTOR,3,3,0)
      CALL VNORM(SFVCT(1,K),SFVCT(1,K))
      IF(IER)30,30,20
   30 ISVFL(K)=K1
 1000 CONTINUE
      RETURN
   20 IAERFG=1
      CALL AERR(21101,'SRFVCT  ')
      IAERR=0
      GO TO 1000
   50 CALL AERR(-21102,'SRFVCT  ')
      IHDS(1) = BCDF(HDS(1:4))
      IHDS(2) = BCDF(HDS(5:8))
      TEMP(1)=VALHDS
      GO TO 3
       END
