**** SOURCE FILE : TEVAL.V01   ***
*
      SUBROUTINE TEVAL(NAME,TRM,DATA)
C
      INCLUDE 'DARRAY.INC'
C
      DOUBLE PRECISION TRM(4,3),DATA(*)
      CHARACTER*8 NAME
C
      INTEGER SLEN,IPOS
C
      IF (NAME.EQ.'MDCS') THEN
        CALL TMDCS(TRM,DATA)
      ELSE IF (NAME.EQ.'TORUS') THEN
        CALL TTORUS(TRM,DATA)
      ELSE IF (NAME.EQ.'VDAFS') THEN
        CALL TVDAFS(TRM,DATA)
      ELSE
        SLEN=0
        CALL CFORM('0 TRANSFORMATOR FOR NON-NATIVE SURFACE TYPE :',
     +             DARRAY,1,SLEN)
        IPOS=SLEN+2
        CALL CFORM(NAME,DARRAY,IPOS,8)
        IPOS=IPOS+10
        SLEN=0
        CALL CFORM(': NOT AVAILABLE',DARRAY,IPOS,SLEN)
        CALL CPRINT(DARRAY)
        CALL ABNEND
      ENDIF
      RETURN
      END
