**** SOURCE FILE : M0012349.V02   ***
*
      SUBROUTINE TLCONV
C
C ROUTINE WILL SET AND CONVERT TOOLDATA OF THE CUTTER
C
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
C
C  CONTROL OF TEST-OUTPUT
      COMMON/SSPRT/SSPRT,SSTEST
      LOGICAL SSPRT,SSTEST
C
      INCLUDE 'GLFLGS.INC'
C
      INCLUDE 'FXCOR.INC'
C
C  COMMON FOR  >PLOTFT/GOLOFT<
C
C
C  VALUES FOR  >PLOTFT/GOLOFT<
      INTEGER IPLGO(26)
C
C  USED CUTTER SEGMENT
      INTEGER JCSEG
C
C  NUMBER OF VALID CUTTER SEGMENTS
      INTEGER NCSEG
C
C  CUTTER SEGMENT IN TLLDAT ARRAYS
      INTEGER ICSEG(10)
C
C  NATURE OF SEGMENT
      INTEGER NLIOCI(10)
C
C  COMPONENTS OF SEGMENT AND UNIT NORMAL POINTING INTO THE CUTTER
      DOUBLE PRECISION COSAL(10)
      DOUBLE PRECISION SINAL(10)
C
C  DISTANCE PARALLEL TO THE CUTTER AXIS
      DOUBLE PRECISION CUTY(10)
C
C  DISTANCE TO THE CUTTER AXIS
      DOUBLE PRECISION CUTX(10)
C
C  ELEMENT LENGTH
      DOUBLE PRECISION CUTL(10)
C  VECTOR COMPONENTS OF THE TOOL AXIS VECTOR
      DOUBLE PRECISION VTA(3)
C
      COMMON/PLGOL/IPLGO,JCSEG,NCSEG,ICSEG,NLIOCI,
     *             COSAL,SINAL,
     *             CUTY,CUTX,CUTL,VTA
C
      CHARACTER*12 BADMSG
C
C AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
C
C  THE FOLLOWING DATA ARE SET, IF CUTDAT(1).GE. 0.001:
      IF(CUTDAT(1).LT.1.D-3) GOTO 999
      NCSEG=0
      JCSEG=0
C
C FIND THE NUMBER OF VALID SEGMENTS, ==> NCSEG
      DO 801 I=0,7
      IF(TCONT(I).NE.-1.D0) GOTO 801
      N=I+1
      GOTO 802
  801 CONTINUE
C
  802 DO 800 J=N,8
      IF(TCONT(J).EQ.0.D0) GOTO 800
      NCSEG=NCSEG+1
C
C NUMBER OF RELATET SEGMENT IN TLLDAT
      ICSEG(NCSEG)=J
C
C SEGMENT LINE OR CIRCLE
      NLIOCI(NCSEG)=TLINC(J)
C
      IF(TLINC(J).NE.0.D0) GOTO 10
C
C SEGMENT IS AN ARC (CIRCLE)
      IF(TANHI(J).GT.-1.D38) GOTO 11
      SINAL(NCSEG)=0.D0
      GOTO 12
   11 SINAL(NCSEG)=1.D0/DSQRT(1.D0+(TANHI(J)*TANHI(J)))
C
   12 IF(TANHI(J).GT.-1.D38) GOTO 13
      COSAL(NCSEG)=-1.D0
      GOTO 14
   13 COSAL(NCSEG)=TANHI(J)*SINAL(NCSEG)
C
   14 CUTY(NCSEG)=TLHITE(J)
      CUTX(NCSEG)=RI(J)
      CUTL(NCSEG)=CORRAD(J)
      GOTO 800
C
   10 IF(TLINC(J).NE.1.D0) GOTO 20
C
C SEGMENT IS A LINE
      SINAL(NCSEG)=SINL(J)
      COSAL(NCSEG)=COSL(J)
      CUTY(NCSEG)=TLHITE(J)
      CUTX(NCSEG)=RI(J)
      CUTL(NCSEG)=UMAX(J)
      GOTO 800
C
C WRONG DATA IN TLINC, VALUE NOT LINE OR NOT CIRCLE
   20 CALL AERR(22218,'TLCONV  ')
  800 CONTINUE
C
C TEST PRINT-OUT OF THE CONVERTET AND CALCUALTED VALUES
      IF(.NOT.SSTEST) GOTO 999
      CALL RECORD(NSEQ)
      BADMSG=' NEW CUTTER:'
      CALL CPRINT(BADMSG)
      CALL BAD (-1,0,'ISN ',NSEQ)
C
      DO 808 I=1,NCSEG
      LIOC=NLIOCI(I)
      CALL BAD ( 1,0,'LIOC',LIOC)
      CALL BAD ( 1,1,'COAL',COSAL(I))
      CALL BAD ( 1,1,'SIAL',SINAL(I))
      CALL BAD ( 1,1,'CUTY',CUTY(I))
      CALL BAD ( 1,1,'CUTX',CUTX(I))
      CALL BAD (-1,1,'CUTL',CUTL(I))
  808 CONTINUE
C
  999 RETURN
      END
