**** SOURCE FILE : TTORUS.ORG   ***
*
      SUBROUTINE TTORUS(TRM,DATA)
C
C.... TRANSFORMATOR FOR NON-NATIVE TORUS
C
      DOUBLE PRECISION TRM(4,3),DATA(15),A(3)
C
C.... AXIS, CENTER AND REF AXIS FOR TORUS REQUIRE ROTATION
C
      DO 10 I=1,7,3
       A(1)=TRM(1,1)*DATA(I)+TRM(2,1)*DATA(I+1)+TRM(3,1)*DATA(I+2)
       A(2)=TRM(1,2)*DATA(I)+TRM(2,2)*DATA(I+1)+TRM(3,2)*DATA(I+2)
       A(3)=TRM(1,3)*DATA(I)+TRM(2,3)*DATA(I+1)+TRM(3,3)*DATA(I+2)
       DATA(I)=A(1)
       DATA(I+1)=A(2)
       DATA(I+2)=A(3)
  10  CONTINUE
C
C.... CENTER ALSO NEEDS TRANSLATION
C
      DATA(4)=DATA(4)+TRM(4,1)
      DATA(5)=DATA(5)+TRM(4,2)
      DATA(6)=DATA(6)+TRM(4,3)
C
      RETURN
      END
         
