**** SOURCE FILE : M0002783.W02   ***
*
C
      SUBROUTINE UNITS(IMOD)
C        NEW ROUTINE TO HANDLE UNITS/ IMPLEMENTATION
C
C        IMOD= FIRST FOUR CHAR. OF UNITS/ ARGUMENT
C
C        CALLED BY NO OTHER ROUTINE
C
C        CALLS SUBROUTINES  RECORD, ERROR, CUTTER(ENTRY CUTRED)
C
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'FXCOR.INC'
      INCLUDE 'SV.INC'
      INCLUDE 'ISV.INC'
      INCLUDE 'IFXCOR.INC'
C
C
      LOGICAL FIRST
      INTEGER W,Z4E,BCDF
      DIMENSION W(10)
      PARAMETER (Z4E=1308622848)
      DIMENSION UNITC(4),MODC(4)
      SAVE W,FIRST,MODC
      COMMON /ADDCOM/ ELMAX,ADDC(24)
      INCLUDE 'SYMFIL.INC'
      INCLUDE 'XUNITS.INC'
      DATA W/0,0,Z4E,0,Z4E,2,Z4E,2,0,0/
      DATA FIRST/.TRUE./
      DATA UNITC(1),UNITC(2),UNITC(3),UNITC(4)
     1    /304.8   ,  30.48 ,   12.0 ,  1.0  /
      IF (FIRST) THEN
        W(1) = BCDF('UNIT')
        W(2) = BCDF('S   ')
        IBL  = BCDF('    ')
        INS  = BCDF('ES  ')
        MODC(1) = BCDF('MM  ')
        MODC(2) = BCDF('CM  ')
        MODC(3) = BCDF('INCH')
        MODC(4) = BCDF('FEET')
        FIRST =.FALSE.
      ENDIF
C
      NUMOD=IMOD
      IOLDMD=BCDF(OLDMOD(1:4))
      IF ( NUMOD .EQ. IOLDMD ) RETURN
C
      DO 1 I = 1,4
    1  IF(NUMOD .EQ. MODC(I)) GO TO 2
      CALL ERROR (91,'UNITS   ')
      RETURN
C
    2 SCALE= UNITC(I) / UNITC(IOLD)
      IOLDMD= NUMOD
      CALL HOLFRM(IOLDMD,OLDMOD,1,4,NWD)
      IOLD = I
      TABEXT=TABEXT*SCALE
      SSEXT=SSEXT*SCALE
      TLHIT = TLHIT * SCALE
      DO 3 I= 1,4
    3 CUTDAT(I) = CUTDAT(I) * SCALE
      CUTDAT(1) = CUTDAT(1) * 2.
      CUTDAT(7) = CUTDAT(7) * SCALE
      DPMAX = DPMAX * SCALE
      ELMAX =ELMAX  * SCALE
      HI = HI * SCALE
      RA = RA * SCALE
      RC1 = RC1 * SCALE
      I= IPS
      J=1
   10 TAU (I)=TAU (I) * SCALE
      TAU1(I)=TAU1(I) * SCALE
      TAU2(I)=TAU2(I) * SCALE
      EPS1(I)=EPS1(I) * SCALE
      EPS2(I)=EPS2(I) * SCALE
      EPS3(I)=EPS3(I) * SCALE
      EPS4(I)=EPS4(I) * SCALE
      EPS6(I)=EPS6(I) * SCALE
      EPS8(I)=EPS8(I) * SCALE
      IF (I-ICS) 4,5,5
    4 I = I + LSV
      J = J + 1
      GO TO 10
    5 IF (J- 4 ) 6,7,7
    6 I = I + LSV1
      J=J+1
      GO TO 10
    7 CALL CUTRED
      JENT(IPS) = 1
      JENT(IPS+LSV) = 1
      CALL RECORD(W(4))
      W(9)=IOLDMD
      W(10)=IBL
      IF(IOLD  .EQ.3) W(10)= INS
      NR = 0
      CALL EWRITE(EXFILE,NR,W,10,IR)
      RETURN
      END
