**** SOURCE FILE : VSCALE.ORG   ***
*
      SUBROUTINE VSCALE(S,V1,V2)
C
C    PURPOSE: TO APPLY A SCALE FACTOR TO A VECTOR  ( V2=S*V1 )
C
      DOUBLE PRECISION S,V1,V2
      DIMENSION V1(3),V2(3)
C
      DO 10 I=1,3
        V2(I)=S*V1(I)
   10 CONTINUE
C
      END
