**** SOURCE FILE : XTPCAL.V01   ***
*
      SUBROUTINE XTPCAL(TP,TE,TA,TPL,TEL,TAL,XTP,XTPL)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DIMENSION TP(3),TE(3),TA(3),TPL(3),TEL(3),TAL(3),XTP(3),XTPL(3)
      DIMENSION FWD(3),VN(3),VNL(3),TF(3),TFL(3),TPV(3),TPVL(3)
      CHARACTER*20 BADMSG
C
      INCLUDE 'IBUGG.INC'
C
C.... COMPUTE UNIT FORWARD VECTOR FROM TEL TO TE
C
      DO 10 I=1,3
        FWD(I)=TE(I)-TEL(I)
   10 CONTINUE
      CALL VNORM(FWD,FWD)
C
C.... COMPUTE TWO VECTORS NORMAL TO FWD AND EACH TA
C
      CALL CROSSV(TA,FWD,VN)
      CALL CROSSV(TAL,FWD,VNL)
C
C.... COMPUTE ORTHOGONAL VECTORS TF AND TFL
C
      CALL CROSSV(VN,TA,TF)
      CALL CROSSV(VNL,TAL,TFL)
C
C.... COMPUTE VECTORS FROM TOOL TIP TO SURFACE CONTACT POINT FOR
C     EACH CASE
C
      DO 20 I=1,3
        TPV(I)=TP(I)-TE(I)
        TPVL(I)=TPL(I)-TEL(I)
   20 CONTINUE
C
C.... PROJECT INTO LOCAL TOOL AXIS SYSTEM
C
      CALL DOTF(X,TPV,TF)
      CALL DOTF(Y,TPV,VN)
      CALL DOTF(Z,TPV,TA)
C
      CALL DOTF(XL,TPVL,TFL)
      CALL DOTF(YL,TPVL,VNL)
      CALL DOTF(ZL,TPVL,TAL)
C
C.... COMPUTE CORRESPONDING POINTS ON TOOL
C
      DO 30 I=1,3
        XTP(I)=TE(I)+XL*TF(I)+YL*VN(I)+ZL*TA(I)
        XTPL(I)=TEL(I)+X*TFL(I)+Y*VNL(I)+Z*TAL(I)
   30 CONTINUE
C
      IF (IBUG.EQ.11) THEN
         BADMSG=' AFTER XTPCAL'
         CALL CPRINT(BADMSG)
         CALL BAD(3,1,'TP  ',TP)
         CALL BAD(-3,1,'TPL ',TPL)
         CALL BAD(3,1,'TE  ',TE)
         CALL BAD(-3,1,'TEL ',TEL)
         CALL BAD(3,1,'TA  ',TA)
         CALL BAD(-3,1,'TAL ',TAL)
         CALL BAD(-3,1,'FWD ',FWD)
         CALL BAD(3,1,'VN  ',VN)
         CALL BAD(-3,1,'VNL ',VNL)
         CALL BAD(3,1,'TF  ',TF)
         CALL BAD(-3,1,'TFL ',TFL)
         CALL BAD(3,1,'TPV ',TPV)
         CALL BAD(-3,1,'TPVL',TPVL)
         CALL BAD(1,1,'X   ',X)
         CALL BAD(1,1,'Y   ',Y)
         CALL BAD(1,1,'Z   ',Z)
         CALL BAD(1,1,'XL  ',XL)
         CALL BAD(1,1,'YL  ',YL)
         CALL BAD(-1,1,'ZL  ',ZL)
         CALL BAD(3,1,'XTP ',XTP)
         CALL BAD(-3,1,'XTPL',XTPL)
      ENDIF
C
      END
