**** SOURCE FILE : M0002876.V03   ***
*
C
C.....FORTRAN SUBROUTINE             ZSURF....              6/10/68 EAN
C
C              FORTRAN SUBROUTINE ZSURF
C
C PURPOSE      TO DEFINE A PLANE WHICH WILL GIVE THE Z COORDINATE
C              OF A POINT WHICH HAS NOT BEEN EXPLICITY DEFINED, BY
C              THE FOLLOWING APT STATEMENT
C                   ZSURF/P
C
C LINKAGE      CALL ZSURF (PL)
C
C ARGUMENTS    PL      ARRAY CONTAINING THE CANONICAL FORM OF THE
C                      INPUT PLANE
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT077
C              REAL FUNCTION       ABS
C              SUBROUTINE          ERROR
C
      SUBROUTINE ZSURF (PL)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION PL(4)
C
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'ZNUMBR.INC'
      INCLUDE 'LDEF.INC'
C...  13. IBRKPT BLOCK. USED FOR DYNDMP BREAKPNTS. INTEGER EQUIVALENCED
C...      TO ISV(30).
C
      INCLUDE 'ISHR16.INC'
      INCLUDE 'KNUMBR.INC'
C
C
      DATA ZLIT1/1.0D-1/
C
C
C
C...     CHECK VALIDITY AND TRANSFORM
C
      CALL APT077 (PL,K0)
      IF (UNFLAG) GO TO 30
C.... ERROR WHEN ZSURF IS PARALEL TO ZAXIS OF LOCAL SYSTEM
      IF(DABS(L(3)).LT.ZLIT1) GO TO 30
      ZFLAG=.FALSE.
C
C...     MOVE ZSURF INTO REF ARRAY
C
      DO 10 I=1,4
      REF(1,I) = PL(I)
   10 REF(2,I) =  L(I)
C
   20 CONTINUE
      RETURN
   30 CALL ERROR (49,'ZSURF   ')
      GO TO 20
       END
