**** SOURCE FILE : M0001044.V02   ***
*
      SUBROUTINE BALTOL(R,SIDE,TC,RAD,TD,DIST,TOL,IOK)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C           /-PURPOSE IS TO VERIFY THAT CUTTER IS WITHIN TOLERANCE OF
C           /-SURFACE AT THIS POINT
C           /-IOK=0 IF IT IS AND SET TO NON-ZERO VALUE OTHERWISE
C
      DIMENSION R(*),TC(*),TD(*)
      DIMENSION ST(3)
      DATA ZERO,ONE,SMAL,FLIPCK/0.0D0,1.0D0,1.D-22,.99995D0/
C
      FAC=SIDE*RAD
      DO 10 I=1,3
   10 ST(I)=TC(I)+DIST*TD(I)-R(I)-FAC*R(I+28)
      CALL DOTV(STLEN,ST,ST)
      IOK=0
C            /-IF STLEN IS VERY SMALL, ACCEPT THIS RESULT
      IF(STLEN.LT.SMAL) GO TO 999
      STLEN=DSQRT(STLEN)
      IOK=1
C            /-IF STLEN EXCEEDS TOLERANCE, DO NOT ACCEPT
      IF(STLEN.GT.TOL) GO TO 999
C            /-MEASURE ANGLE FROM NORMAL TO ST
      DO 20 I=1,3
   20 ST(I)=TC(I)+DIST*TD(I)-R(I)
      CALL DOTV(STLEN,ST,ST)
      IF(STLEN.LT.SMAL) GO TO 999
      CALL DOTV(ANG,ST,R(29))
      ANG=ANG/DSQRT(STLEN)*SIDE
      IOK=2
C            /-VECTOR LINEUP IS REQUIRED ONLY FOR NON ZERO RADIUS
      IF(RAD.GT.SMAL.AND.ANG.LT.FLIPCK) GO TO 999
      IOK=0
  999 CONTINUE
      RETURN
      END
