**** SOURCE FILE : M0001052.V02   ***
*
      SUBROUTINE CLIFT(TE,CLRPLN,TX)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DIMENSION TE(*),CLRPLN(*),TX(*)
C---PURPOSE IS TO LIFT TOOL END TE TO POSITION TX ON CLEARANCE
C---PLANE CLRPLN.  MOVE IS IN DIRECTION OF PLANE NORMAL.
C
      DATA ZERO/0.D0/
C
      SUM=ZERO
      DO 10 I=1,3
      SUM=(TE(I)-CLRPLN(4)*CLRPLN(I))*CLRPLN(I)+SUM
   10 CONTINUE
      DO 20 I=1,3
   20 TX(I)=TE(I)-SUM*CLRPLN(I)
      RETURN
      END
