**** SOURCE FILE : M0001053.W02   ***
*
      SUBROUTINE CLPUT(ATEX,ATAX,MODE)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'FXCOR.INC'
      INCLUDE 'IFXCOR.INC'
C
      CHARACTER*20 BADMSG
      DIMENSION ATEX(3),ATAX(3)
      COMMON/IBUGG/IBUG,IPCOLC,IPCOLM
      INCLUDE 'SYMFIL.INC'
C
      INTEGER Z4E
      PARAMETER (Z4E=1308622848)
      INTEGER BCDF
      LOGICAL FIRST
      SAVE FIRST,KCLDAT
      DIMENSION KCLDAT(10)
      DATA KCLDAT/0,0,Z4E,0,Z4E,2,
     X            Z4E, 1,0,0/
      DATA FIRST/.TRUE./
C
C
      IF (FIRST)THEN
        KCLDAT(1) = BCDF('CLDA')
        KCLDAT(2) = BCDF('TA  ')
        KCLDAT(9) = BCDF('GOTO')
        KCLDAT(10) = BCDF('    ')
        FIRST=.FALSE.
      END IF
C
      CALL RECORD(ISEQNO)
      IF(MODE.GE.0) GO TO 100
      IF(MODE.LT.-1) GO TO 999
C--OUTPUT HEADER FOR A RECORD OF CL DATA
      KCLDAT(4)=ISEQNO
      NR=0
      CALL EWRITE(EXFILE,NR,KCLDAT,10,IR)
      GO TO 999
C
  100 CONTINUE
      ICL=0
      IF(MODE.EQ.0) ICL=2
      IF(MODE.EQ.1) ICL=3
      DO 110 I=1,3
      TE(I)=ATEX(I)
      TA(I)=ATAX(I)
  110 CONTINUE
      CALL ATAPE
      GO TO 999
C
  999 CONTINUE
      IF(IBUG.NE.11) GO TO 1999
      CALL BAD(-1,0,' ',0)
      BADMSG=' AFTER CLPUT'
      CALL CPRINT(BADMSG)
      CALL BAD(-1,0,'MODE',MODE)
      CALL BAD(3,1,'ATEX',ATEX)
      CALL BAD(-3,1,'ATAX',ATAX)
 1999 CONTINUE
C
      RETURN
      END
