**** SOURCE FILE : M0011490.ORG   ***
*
      SUBROUTINE GOMILL
C
C      DUMMY ROUTINE.   SODO   M0009479               DESIGNATED
C      TO PROCESS THE START UP, THE SINGLE CUT AND THE MULTI CUT
C      SEQUENCE STATEMENT OF THE PROPOSED REGIONAL MILLING.
C
      RETURN
      END
