**** SOURCE FILE : M0001082.W01   ***
*
      SUBROUTINE PCHG(PCUR,PDIR,PDEL)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON/IBUGG/IBUG,IPCOLC,IPCOLM
      CHARACTER*20 BADMSG
      DATA ZERO,ONE,HALF,SMAL/0.D0,1.D0,0.5D0,1.D-14/
      DATA SMAL1/1.0D-10/
C--PURPOSE IS TO MODIFY THE PARAMETRIC CHANGE PDEL SO AS
C--TO HIT OR APPROACH A JUNCTION POINT SMOOTHLY.
C
      PIN=PDEL
      A=ZERO
      XX=PCUR
      I=IDINT(XX)
      A=I
      IF(DABS(A-PCUR).GT.SMAL) GO TO 10
      PDEL=DMIN1(HALF,PDEL)
      GO TO 999
C
   10 CONTINUE
      PTARG=ZERO
      XX=PDIR+PCUR
      I=IDINT(XX)
      PTARG=I
      PMAX=DABS(PTARG-PCUR)
      PDEL=DMIN1(PMAX,PDEL)
      PHALF=HALF*PMAX
      IF(PDEL.LT.PMAX.AND.PDEL.GT.PHALF) PDEL=PHALF
C
  999 CONTINUE
      PDEL=PDEL+SMAL1
      IF(IBUG.NE.11) GO TO 1999
      CALL BAD(-1,0,' ',0)
      BADMSG=' AFTER PCHG'
      CALL CPRINT(BADMSG)
      CALL BAD(1,1,'PCUR',PCUR)
      CALL BAD(1,1,'PDIR',PDIR)
      CALL BAD(1,1,'PDEL',PDEL)
      CALL BAD(-1,1,'PIN ',PIN)
 1999 CONTINUE
      RETURN
      END
