**** SOURCE FILE : BDGLFL.ORG   ***
*
      BLOCK DATA BDGLFL
C
C.... INITIALIZE COMMON/GLFLGS/
C
      INCLUDE 'GLFLGS.INC'
C
      DATA REGFLG/0/
      DATA RINGFG/.FALSE./
      DATA MOTDIR/0/
      DATA IAUTOG/0/
C
      END
