**** SOURCE FILE : M0011488.V01   ***
*
      SUBROUTINE GCLEAR(CNAME)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C PROCESSES THE GCLEAR STATEMENT
C
      COMMON/CCLEAR/ DIRMOT(3,4)
     *              ,GOFEED(4)
     *              ,GLFEED
     *              ,REGLDA(2)
     *              ,IRETRO(4)
     *              ,IDIRMO(4)
     *              ,ICANIN(4)
      INCLUDE 'BLANKCOM.INC'
C
      LOGICAL CKDEF
      CHARACTER*6 HPOS,HARG,TEST
      DIMENSION HPOS(6),HARG(5),LCNN(7),CNAME(1)
      INTEGER ADDRSS
C
      DATA HPOS /'START ','AWAY  ','BACK  ','THRU  ','ON    ','OFF   '/
      DATA HARG /'MOTDIR','NORMAL','PARLEL','FEED  ','CLEARS'/
      DATA LCNN /7,7,10,10,7,4,10/
C
C AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
C
C SET DEFAULT GLFEED
      IF(GLFEED.EQ.0.D0) GLFEED=50.D0
C
      IS=4
      IE=SSCAN(2)-1
C
C             DEFINE COLUMN, I.E. POSITION OF TOOL MOTION
      K=0
      DO 10 MP=1,6
      CALL HOLFRM(SSCAN(IS),TEST,1,6,NWD)
      IF(TEST.NE.HPOS(MP)) GOTO 10
      IF(MP-5)20,4,6
    4 K=1
    6 DO 8 I=1,4
    8 IRETRO(I)=K
      GOTO 15
   10 CONTINUE
C
C             NO CONDITIONS CHANGED
   15 GOTO 999
C
C             ZERO LOCATIONS MP IN THE /CCLEAR/ ARRAYS
   20 IS=IS+2
      IRETRO(  MP)=0
      CALL HOLFRM(SSCAN(IS),TEST,1,6,NWD)
      IF(TEST.EQ.HPOS(6)) GOTO 15
      IRETRO(  MP)=1
      IF(TEST.EQ.HPOS(5)) GOTO 15
C
C FEED PARAMETER
      IF(TEST.NE.HARG(4)) GOTO 25
      GOFEED(MP)=SSCAN(IS+2)
      IS=IS+4
      IF(IS.LT.IE) GOTO 25
      GOTO 115
C
   25 DO 30 I=1,3
   30 DIRMOT(I,MP)=0.D0
      IDIRMO(  MP)=0
      ICANIN(  MP)=0
C
C             SET FLAGS AND VALUES FOR MOTION CONDITIONS
   40 CALL HOLFRM(SSCAN(IS),TEST,1,6,NWD)
      DO 50 I=1,5
      IF(TEST.NE.HARG(I)) GOTO 50
      GOTO( 60, 60, 70, 80, 90),I
   50 CONTINUE
C
C             NO FURTHER CONDITION CHANGE
      GOTO 999
C
C             MOTION DIRECTION OR NORMAL DIRECTION (FLAG AND VALUE)
   60 IDIRMO(MP)=1
      DIRMOT(I,MP)=SSCAN(IS+2)
      GOTO 100
C
C             MOTION DIRECTION OR NORMAL DIRECTION (FLAG AND VALUE)
   70 IS=IS+2
      IF(CKDEF(SSCAN(IS)))GOTO 130
      K=IS-1
      DO 75 I=1,3
   75 DIRMOT(I,MP)=SSCAN(K+I)
      IDIRMO(MP)=2
      GOTO 100
C
C             SPECIAL FEEDRATES
   80 GOFEED(MP)=SSCAN(IS+2)
      GOTO 100
C
C             CLEARANCE SURFACES
   90 IF(CKDEF(SSCAN(IS+2)))GOTO 130
      ICANIN(MP)=(ADDRSS(CNAME(1))-ADDRSS(COM(1)))/8+1
      I=SSCAN(IS+1)
      K=5
      IF(I.LT.8)K=LCNN(I)
      IS=IS+K
      GOTO 110
C
  100 IS=IS+4
  110 IF(IS.LT.IE)GOTO 40
C
C IF NO MOTION, SET MOTION-DIRECTION ZERO
  115 IF(DIRMOT(1,MP).EQ.0.D0.AND.
     *   DIRMOT(2,MP).EQ.0.D0.AND.
     *   DIRMOT(3,MP).EQ.0.D0) IDIRMO(MP)=0
C
C SET DEFAULT FOR FEED, IF ZERO-FEDRAT GIVEN
      IF(GOFEED(MP).EQ.0.D0) GOFEED(MP)=50.D0
C
  120 GOTO 999
C
  130 CALL ERROR(5157,'GCLEAR  ')
      GOTO 120
C
  999 CONTINUE
      RETURN
      END
