**** SOURCE FILE : M0000420.V01   ***
*
C.....FORTRAN SUBROUTINE              APT303                12/67
C PURPOSE      TO TRANSFORM THE CANONICAL FORM OF A POINT BY
C              A GIVEN MATRIX.
C LINKAGE      CALL APT303 (RESULT, MATRX, PN)
C ARGUMENTS    RESULT    ARRAY TO CONTAIN THE CANONICAL FORM OF
C                        THE RESULTANT POINT
C              MATRX     ARRAY CONTAINING THE INPUT TRANSFORMATION
C                        MATRIX
C              PN        ARRAY CONTAINING THE CANONICAL FORM OF
C                        THE INPUT POINT
C SUBSIDIARIES NONE
      SUBROUTINE APT303 (RESULT,MATRX,PN)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
C     THIS ROUTINE TRANSFORMS THE CANONICAL FORM OF A POINT
C     BY A GIVEN MATRIX
      DOUBLE PRECISION MATRX
      DIMENSION RESULT(3), PN(3), P(3), MATRX(3,4)
      DO 20 I=1,3
   20 P(I) =PN(I)
      DO 70 I=1,3
      RESULT(I)=MATRX(I,4)
      DO 70 J=1,3
      RESULT(I)=RESULT(I)+ P(J)* MATRX(I,J)
   70 CONTINUE
      RETURN
       END
