**** SOURCE FILE : M0008178.V02   ***
*
      SUBROUTINE TMDCS(TRM,DATA)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C PROGRAM TO TRANSFORM THE PATCH GEOMETRY
C  OF "MASTER DIMENSION CONTOUR SURFACE"
C
C   TRANSFORMATION MATRIX
      DOUBLE PRECISION TRM(12)
C   PATCH DATA
      DIMENSION DATA(120)
C   AUXILIARY MATRIX
      DOUBLE PRECISION TRM1(12)
C   'NO TRANSFORMATION' MATRIX
      DOUBLE PRECISION NTRM(12)
C   SCALE FACTOR
      DOUBLE PRECISION SCALE,SCALES
C
      DATA NTRM/1.D0,4*0.D0,1.D0,4*0.D0,1.D0,0.D0/
C
C   TEST PRINT
C     WRITE(6,100)
C 100 FORMAT('0TMDCSSSS WAS CALLED')
C    PRESET OF SCALE FACTOR
      SCALE=1.D0
C    SQUARED SCALE FACTOR
      SCALES=TRM(1)**2+TRM(2)**2+TRM(3)**2
C    COMPUTATION OF SCALE FACTOR
      IF(DABS(SCALES-1.D0).GE.1.D-10)SCALE=DSQRT(SCALES)
C    TEST IF ALL SCALE FACTORS EQUAL
      IF(DABS(TRM( 5)**2+TRM( 6)**2+TRM( 7)**2-SCALES).LT.1.D-10.AND.
     *   DABS(TRM( 9)**2+TRM(10)**2+TRM(11)**2-SCALES).LT.1.D-10)
     *GOTO 1
C    NO TRANSFORMATION AND ERROR MESSAGE
      CALL ERROR(97,'TMDCSSSS')
      GOTO 99
C    MOVE OLD MATRIX TO SCATCH AREA
    1 DO 2 I=1,12
    2 TRM1(I)=DATA(I+18)
C    COMPUTE NEW TRANSFORMATION MATRIX
      CALL APT066(DATA(19),TRM,TRM1,0)
C    PRESET SCALE FACTOR OF MATRIX
      DATA(18)=SCALE
C    CHECK THE RESULT MATRIX FOR 'NO TRANSFORMATION'
      DO 3 I=1,12
      IF(DABS(DATA(I+18)-NTRM(I)).GE.1.D-10)GOTO 99
    3 CONTINUE
C    SWITCH OFF TRANSFORMATION
      DATA(18)=0.D0
   99 RETURN
      END
