**** SOURCE FILE : M0000832.V04   ***
*
C
C.....FORTRAN SUBROUTINE             APT085...              5/1/68   GK
C
C              FORTRAN SUBROUTINE APT085
C
C PURPOSE      TO SET THE REFSYS FLAG, REFFLG, .FALSE. AND
C              SET UP THE CANONICAL FORM OF THE ZSURF PLANE
C              EQUATION IN THE LOCAL COORDINATE SYSTEM EQUAL
C              TO THE CANONICAL FORM IN THE BASE SYSTEM.
C
C LINKAGE      CALL APT085
C
C ARGUMENTS    NONE
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          ZSURF
C
      SUBROUTINE APT085
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
C
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'LDEF.INC'
C
C
C
      DIMENSION SC(4)
      REFFLG = .FALSE.
      IF (ZFLAG) GOTO 20
      DO 10 I=1,4
   10 SC(I) = REF(2,I)
      CALL ZSURF(SC)
   20 RETURN
       END
