**** SOURCE FILE : M0000695.V06   ***
*
C
C              FORTRAN SUBROUTINE APT024
C
C PURPOSE      TO SET XECUTION FLAGS SPECIFIED BY THE PPOPTN STATEMENT.
C
C LINKAGE      CALL APT024(IARG)
C
C ARGUMENT     IARG  =1, REFMOT ON
C                    =2, REFMOT OFF
C                    =3, ALTMLT ON
C                    =4, ALTMLT OFF
C
      SUBROUTINE APT024(IARG)
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'LDEF.INC'
C
      LOGICAL CILPRT
      COMMON/CONST/KCOMT,KCOMF,CILPRT,KCBN
      INCLUDE 'DARRAY.INC'
C
      GO TO (1,2,3,4,5,6),IARG
    1 REFMOT=.TRUE.
      GO TO 9
    2 REFMOT=.FALSE.
      GO TO 9
    3 ALTMLT=.TRUE.
      GO TO 9
    4 ALTMLT=.FALSE.
      GO TO 9
    5 CILPRT=.TRUE.
      CALL CFORM('0 CILPRT TURNED ON',DARRAY,1,18)
      CALL CPRINT(DARRAY)
      GO TO 9
    6 CILPRT=.FALSE.
      CALL CFORM('0 CILPRT TURNED OFF',DARRAY,1,19)
      CALL CPRINT(DARRAY)
      GO TO 9
    9 CONTINUE
      RETURN
      END
