**** SOURCE FILE : M0004117.V11   ***
*
C
C...  FORTRAN SUBROUTINE                    APT298
      SUBROUTINE  APT298(CODE,PPROC1,PPROC2)
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'IFXCOR.INC'
C
C... LOCAL VARIABLES
C
      INTEGER CLPRNT,CNVERT,CODE,PPFLG,ONE,PPFLAG
C
C
      DIMENSION PPS(2,10),PPLIBR(10),NAME(2)
C
      DIMENSION A4ARY(24)
      DIMENSION I4ARY(48)
      EQUIVALENCE (A4ARY(1),I4ARY(1))
      EQUIVALENCE (ONE,I4ARY(2))
      EQUIVALENCE (NOPPS,I4ARY(3))
      EQUIVALENCE (CLPRNT,I4ARY(4))
      EQUIVALENCE (CNVERT,I4ARY(5))
      EQUIVALENCE (PPFLG,I4ARY(6))
      EQUIVALENCE (MLTFLG,I4ARY(7))
      EQUIVALENCE (PPS(1,1),I4ARY(9))
      SAVE I4ARY
      COMMON/SUPER/ERR,XC,CL,PX,ERRX,END,FINI,ASM,ABEND,XTRAS(7),
     C           IRDSAV(20)
      LOGICAL ERR,XC,CL,PX,END,FINI,ASM,ABEND
      INTEGER ERRX,XTRAS
C
C          SYMFIL I/O FILES NAME
C
      INCLUDE 'SYMFIL.INC'
      CHARACTER*8 PPLIBR,PROC1
C
      INTEGER BCDF
C
      DATA ONE,LIBTOP,NOPPS,CLPRNT,CNVERT,PPFLAG,PPFLG
     / /   1,  10,    0,    0,     0,     0,     0    /
      DATA PPS(1,1),PPS(2,1) /0. ,0./
C
C...     APT4 POSTPROCESSOR LIBRARY
      DATA PPLIBR/'APT4PP','CLCMP4',8*'      '/
C
C ********************************************************************
C
      GO TO (10,20,30,100), CODE
   10 CLPRNT=1
      RETURN
   20 PPFLAG=1
      PX=.TRUE.
      CNVERT=0
      PPFLG=0
      NOPPS=0
      RETURN
   30 CONTINUE
      PPNAME=PPROC1
      CALL HOLFRM(PPNAME,PROC1,1,8,NWD)
C
C...     CHECK FOR APT4 POSTPROCESSOR
   38 DO 40 I=1,LIBTOP
      IF (PPLIBR(I) .EQ. PROC1) GO TO 70
   40 CONTINUE
C
      IF(PPFLAG.EQ.0) CNVERT=1
      GO TO 90
C
   70 IF(PPFLAG.EQ.0) PPFLG=1
C
C     STORE POSTPROCESSOR NAME
C
   90 NOPPS = NOPPS + 1
      PPS(1,NOPPS)=PPNAME
      PPS(2,NOPPS) = PPROC2
      RETURN
C
  100 MLTFLG=MULOUT
      CALL TAPOP(CPFILE,-1)
  110 NR =0
      NOPPS=NOPPS*2
      I4ARY(1)=BCDF('CPFL')
      CALL AWRITE(CPFILE,NR,I4ARY,48,IR)
C
      CALL TAPOP(CPFILE,-2)
C
      RETURN
      END
