**** SOURCE FILE : M0000873.V02   ***
*
C.....FORTRAN SUBROUTINE ....CHKRET              8/68               RN
C
C              FORTRAN SUBROUTINE CHKRET
C
C PURPOSE      THIS SUBROUTINE IS A TABCYL INTERVAL SCREENING TECHNIQUE
C              THAT CONSTRUCTS A RECTANGLE AROUND THE INTERVAL BEING
C              CONSIDERED.
C
C LINKAGE      CALL CHKRET(IHU,RAD,INTRCT,D,S)
C
C ARGUMENTS    IHU    INDEX OF CURRENT TABCYL SEGMENT
C              RAD    THE RADIUS OF THE CIRCLE
C              INTRCT
C
C              D      THE ARRAY CONTAINING THE TABCYL EXTERNAL
C                     CANONICAL FORM
C              S      THE ARRAY CONTAINING LINE CANONICAL FORM
C SUBSIDIARIES  NONE
C
      SUBROUTINE CHKRET(IHU,RAD,INTRCT,D,S)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION PX(6),PY(6),D(*),S(4)
      IVERTL=0
      MINUS=0
      IPLUS=0
  400 DELY=D(IHU+8)-D(IHU+1)
      DELX=D(IHU+7)-D(IHU)
      DIHU4=D(IHU+4)
      IF(DABS(DIHU4).LT.1.0D-7) DIHU4=1.0D-7
      SL1Y=DELY/DIHU4
      SL1X=DELX/DIHU4
      SL2Y=SL1X
      SL2X=-SL1Y
      RD=RAD+1.0D-6
      BO1=RD*SL1X
      BO2=RD*SL1Y
      BO3=DABS(D(IHU+5))+RD
      BO4=BO3*SL2X
      BO5=BO3*SL2Y
      BO6=DABS(D(IHU+6))+RD
      BO7=BO6*SL2X
      BO8=BO6*SL2Y
      PX(5)=D(IHU)-BO1
      PY(5)=D(IHU+1)-BO2
      PX(1)=PX(5)+BO4
      PY(1)=PY(5)+BO5
      PX(4)=PX(5)-BO7
      PY(4)=PY(5)-BO8
      PX(6)=D(IHU+7)+BO1
      PY(6)=D(IHU+8)+BO2
      PX(2)=PX(6)+BO4
      PY(2)=PY(6)+BO5
      PX(3)=PX(6)-BO7
      PY(3)=PY(6)-BO8
      XPLINE=S(1)*S(4)
      IF(DABS(S(2))-1.0D-7)1,1,2
    1 IVERTL=1
      GO TO 3
    2 SLPLIN=-S(1)/S(2)
      X1PLIN=S(1)*S(4)
      Y1PLIN=S(2)*S(4)
      BPLIN=Y1PLIN-SLPLIN*X1PLIN
    3 DO 10 I=1,4
      IF(IVERTL) 5,5,6
    5 YPLINE=(SLPLIN)*PX(I)+BPLIN
      VALUE=PY(I)-YPLINE
      GO TO 4
    6 VALUE=PX(I)-XPLINE
    4 IF(VALUE) 11,12,13
   11 MINUS=1
      GO TO 10
   13 IPLUS=1
   10 CONTINUE
   14 IF(MINUS-IPLUS) 15,12,15
C
C     THE APPROPRIATE LINE, THAT IS,THE ACTUAL LINE FOR TABPNT OR THE
C     RADIUS PARALLEL LINE FOR TABCIR DOES NOT INTERSECT THE RECTANGLE
C     THUS THIS INTERVAL IS ELIMINATED FROM FURTHER CONSIDERATION.
C
   15 INTRCT=0
      GO TO 16
C
C     THE APPROPRIATE LINE DOES INTERSECT THE RECTANGLE SO THIS INTERVAL
C     MUST BE EXAMINED FURTHER
C
   12 INTRCT=1
   16 CONTINUE
      RETURN
      END
