**** SOURCE FILE : M0002823.V03   ***
*
C.....FORTRAN SUBROUTINE             CIRDEF...              5/1/68   GK
C
C              FORTRAN LOGICAL FUNCTION CIRDEF
C
C PURPOSE      TO DETERMINE WHETHER A CIRCLE HAS BEEN DEFINED
C              AND IS A VERTICAL CYLINDER.
C
C LINKAGE      CALL CIRDEF (A, N)
C
C ARGUMENTS    A       ARRAY CONTAINING THE CANONICAL FORM OF THE
C                      CIRCLE
C              N       ERROR CODE OF THE DIAGNOSTIC TO BE PRINTED
C                      IN CASE THE CYLINDER IS NOT VERTICAL
C
C SUBSIDIARIES TYPE                ENTRY
C              REAL FUNCTION       ABS
C              LOGICAL FUNCTION    CKDEF
C              SUBROUTINE          ERROR
C
      LOGICAL FUNCTION CIRDEF (CIR,MN)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION CIR(7)
      LOGICAL CKDEF
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'ZNUMBR.INC'
C
C
C...     CHECK WHETHER INPUT CANONICAL FORM IS DEFINED
C
      IF (CKDEF(CIR)) GO TO 1
C
C...     CHECK WHETHER CYLINDER IS WITHIN TOLERANCE OF VERTICAL
C
      IF (DABS(DABS(CIR(6))-Z1).LE.Z1EM5
     1    .AND.DABS(CIR(4)) .LE.Z1EM5
     2    .AND.DABS(CIR(5)) .LE.Z1EM5) GO TO 2
C
C...     ISSUE DIAGNOSTIC
C
      CALL ERROR(MN,'CIRDEF  ')
C
C...     RETURN VALUE TRUE
C
    1 CIRDEF=.TRUE.
      GO TO 9
C
C...     RETURN VALUE FALSE
C
    2 CIRDEF=.FALSE.
    9 RETURN
       END
