**** SOURCE FILE : M0011447.V10   ***
*
C.....FORTRAN SUBROUTINE  ....ERROR          8/68                    HG
C...  FORTRAN SUBROUTINE               ERROR
C
C              FORTRAN SUBROUTINE ERROR
C
C PURPOSE      TO PRINT THE ERROR CODE OF A GEOMETRIC DIAGNOSTIC.
C
C LINKAGE      CALL ERROR (I,SUBNAM)
C
C ARGUMENTS    I       INTEGER ERROR CODE OF DIAGNOSTIC
C
C SUBSIDIARIES NONE
C
      SUBROUTINE ERROR (IARG,SUBNAM)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
C
      INCLUDE 'TOTAL.INC'
C
C...            SYSTEM I/O FILE NAMES
C
      INCLUDE 'SYMFIL.INC'
      CHARACTER*8 SUBNAM,ERRR,ERRO,WARN
C
      LOGICAL FIRST
      DIMENSION KGERR(10)
      SAVE KGERR,FIRST
C
C...      32.  PARAMETERS REQUIRED BY SUPERVISOR
C
          COMMON/SUPER/ERR,XC,CL,PX,ERRX,END,FINI,ASM,ABEND,XTRAS
          DIMENSION XTRAS(7),CFLAGS(4),LXTRAS(7)
          INTEGER   ERRX,XTRAS
          LOGICAL   ERR,FINI,XC,CL,ASM,LXTRAS,CFLAGS,PX,END,ABEND
          EQUIVALENCE (LXTRAS(1),XTRAS(1)),(CFLAGS(1),ERR)
      INCLUDE 'DARRAY.INC'
      INTEGER Z4E,BCDF
      PARAMETER (Z4E=1308622848)
C... INITILIZE ARRAY INDICATING WHICH ERRORS ARE OF SEVERITY LEVEL FOUR.
      INTEGER ERRLEV(20),IERRN
      DATA IERRN/20/,ERRLEV/2,3,8,9,30,40,45,49,50,71,84,92,94,5129,6*0/
      DATA WARN/' WARNING'/,ERRO/'  ERROR '/
      DATA KGERR/0,0,Z4E,0,Z4E,1,Z4E,0,2*0/,FIRST/.TRUE./
      IF (FIRST) THEN
        KGERR(1) = BCDF('GERR')
        KGERR(2) = BCDF('    ')
        FIRST = .FALSE.
      ENDIF
C
      LARG=IARG
C... SET ERROR LEVEL INDICATOR FOR THE SUPERVISOR.
      KERRX=4
      DO 5 IERR=1,IERRN
      IF (LARG .EQ.ERRLEV(IERR))GOTO 8
    5 CONTINUE
      KERRX=8
    8 XTRAS(8/KERRX) = XTRAS(8/KERRX) + 1
      KGERR(8)=LARG
      CALL CPRINT(DARRAY)
      CALL RECORD(KGERR(4))
      ERRR = WARN
      IF(KERRX.GT.4) ERRR = ERRO
      IF(KERRX.EQ.4.AND.ERRX.LT.4) ERRX=4
      IF(KERRX.EQ.8.AND.ERRX.LT.8) ERRX=8
      NR=0
      KGERR( 9) = BCDF(SUBNAM(1:4))
      KGERR(10) = BCDF(SUBNAM(5:8))
      CALL CFORM(' ***** DEFINITION ',DARRAY,1,18)
      CALL CFORM(ERRR,DARRAY,19,8)
      CALL ICONV(LARG,DARRAY,27,5)
      CALL CFORM('ISN',DARRAY,36,3)
      CALL ICONV(KGERR(4),DARRAY,39,5)
      CALL CFORM(' FROM SUBROUTINE ',DARRAY,44,17)
      CALL CFORM(SUBNAM,DARRAY,61,8)
      CALL CFORM('*****',DARRAY,69,5)
      CALL CPRINT(DARRAY)
      CALL ERROUT(LARG)
      KGERR( 6)=2
      CALL EWRITE(EXFILE,NR,KGERR,10,IR)
      RETURN
       END
