**** SOURCE FILE : M0002844.V04   ***
*
C
C.....FORTRAN SUBROUTINE             LINDEF...              5/1/68   GK
C
C              FORTRAN LOGICAL FUNCTION LINDEF
C
C PURPOSE      TO DETERMINE WHETHER A LINE HAS BEEN DEFINED
C              AND IS A VERTICAL PLANE.
C
C LINKAGE      CALL LINDEF (A, N)
C
C ARGUMENTS    A       ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE LINE
C              N       ERROR CODE OF THE DIAGNOSTIC TO BE PRINTED
C                      IN CASE THE PLANE IS NOT VERTICAL
C
C SUBSIDIARIES TYPE                ERROR
C              REAL FUNCTION       ABS
C              LOGICAL FUNCTION    CKDEF
C              SUBROUTINE          ERROR
C
      LOGICAL FUNCTION LINDEF (LIN,NM)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION LIN(4)
      DOUBLE PRECISION LIN
      LOGICAL CKDEF
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'ZNUMBR.INC'
      MN=NM
C
C
C...     CHECK WHETHER INPUT CANONICAL FORM IS DEFINED
C
      IF (CKDEF(LIN)) GO TO 1
C
C...     CHECK WHETHER LINE IS WITHIN TOLERANCE OF VERTICAL
C
      IF (DABS(LIN(3)).LE.Z1EM5) GO TO 2
C
C...     ISSUE DIAGNOSTIC
C
      CALL ERROR(MN,'LINDEF  ')
      IF(MN.EQ.2.OR.MN.EQ.3.OR.MN.EQ.92) GO TO 2
C
C...     RETURN VALUE TRUE
C
    1 LINDEF=.TRUE.
      GO TO 9
C
C...     RETURN VALUE FALSE
C
    2 LINDEF=.FALSE.
    9 RETURN
       END
