**** SOURCE FILE : M0002856.V03   ***
*
C.....FORTRAN SUBROUTINE  ....REFSYS         8/68                    RN
C.....FORTRAN SUBROUTINE             REFSYS...              3/1/68   GK
C
C              FORTRAN SUBROUTINE REFSYS
C PURPOSE      TO DEFINE THE TRANSFORMATION MATRICES FOR
C              LOCAL TO BASE AND BASE TO LOCAL COORDINATE
C              SYSTEMS AND TO GENERATE THE ZSURF PLANE CANONICAL
C              FORM IN THE LOCAL SYSTEM.
C
C LINKAGE      CALL REFSYS (MATRIX)
C
C ARGUMENTS    MATRIX  ARRAY CONTAINING THE TRANSFORMATION
C                      MATRIX RELATING A NEW REFERENCE SYSTEM
C                      TO THE BASE COORDINATE SYSTEM
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT067
C              LOGICAL FUNCTION    CKDEF
C              SUBROUTINE          ERROR
C              SUBROUTINE          ZSURF
C
      SUBROUTINE REFSYS (MATRIX)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION MATRIX(12)
      DOUBLE PRECISION MATRIX
      LOGICAL CKDEF
C
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'LDEF.INC'
      INCLUDE 'ISHR16.INC'
C
C
C
C
C
C...     CHECK INPUT DEFINED
C
      IF (.NOT.CKDEF(MATRIX)) GO TO 10
      CALL ERROR( 53,'REFSYS  ')
      GO TO 9
C
C...     MOVE MATRIX TO A(1,2) AND THE INVERSE TO A(2,2) FOR TRANSF
C
   10 DO 20 I=1,12
   20 A(I,2)=MATRIX(I)
      CALL APT067 (A(1,1),A(1,2))
C
C...     IF ZSURF IS IN EFFECT TRANSFORM ZSURF PLANE
C
      IF (ZFLAG) GO TO 30
      DO 25 I= 1,4
   25 SC(I)=REF(1,I)
      CALL ZSURF (SC)
   30 REFFLG=.TRUE.
    9 RETURN
       END
