**** SOURCE FILE : M0000960.V01   ***
*
C...  FORTRAN SUBROUTINE               ROTAT
      SUBROUTINE ROTAT(ARRAY,XMATRX)
      IMPLICIT DOUBLE PRECISION(A-H), DOUBLE PRECISION(O-Z)
C                  SUBROUTINE USED TO ROTATE THE AXIS SYSTEM IN ARLM2
C                  SO THAT THE TOOL AXIS POINTS IN THE Z-DIRECTION
      DIMENSION ARRAY(3),XMATRX(3,3),TMP(3)
      DO 2 K=1,3
      TMP(K) = 0.0
      DO 2 J=1,3
      TMP(K) = TMP(K)+XMATRX(J,K)*ARRAY(J)
 2    CONTINUE
      DO 4 I=1,3
 4    ARRAY(I) = TMP(I)
      RETURN
       END
