**** SOURCE FILE : M0000978.V01   ***
*
C.....FORTRAN SUBROUTINE ....TRANRO              8/68               RN
C
C              FORTRAN SUBROUTINE TRANRO
C
C PURPOSE      ROTATE (X1,Y1) BY ANGLE RA IN DIRECTION DETERMINED
C              BY SIGN OF IZ.
C              PUT ROTATED COORDINATES IN (X11,Y11).
C
      SUBROUTINE TRANRO (X1,Y1,X11,Y11,RA,IZ)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DOUBLE PRECISION X1,Y1,X11,Y11,RA
      TS = DSIN(RA)
      TC = DCOS(RA)
      IF(IZ.LT.0) GO TO 1
      X11=X1*TC-Y1*TS
      Y11=X1*TS+Y1*TC
      GO TO 2
    1 X11=X1*TC+Y1*TS
      Y11=-X1*TS+Y1*TC
    2 CONTINUE
      RETURN
      END
