**** SOURCE FILE : M0001056.V02   ***
*
      SUBROUTINE CNSURH(U,V,B,SPV,IFLAG,MMODE)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C------  INTERPOLATION FORMULAS FOR VARIOUS TYPES OF GENCUR
C------  PATCHES ARE HERE.
C---     BLANK COMMON INCLUDED TO PROVIDE ACCESS TO SURFACE
C---     FOR THE SPECIAL CASE OF A SURFACE THRU GENERAL CURVES
C
      INCLUDE 'BLANKCOM.INC'
C
      DIMENSION B(64),SPV(32),IFLAG(4)
      DIMENSION SPW(32),FV(12)
      DIMENSION RK(32,2)
      DIMENSION R(32),RT(32)
      EQUIVALENCE (RK(1,1),R(1)),(RK(1,2),RT(1))
      DIMENSION IFLX(4)
      DATA IFLX/4,4,4,1/
C--- INPUT CONSISTS OF PARAMETRIC U,V COORDINATES.  THE UNIT SQUARE
C--- DIVIDES THE PLANE INTO 9 SECTORS.  THIS ROUTINE DETERMINES THE
C--- CORRECT SECTOR FOR U,V AND THEN COMPUTES SURFACE DIFFERENTIAL
C--- QUANTITIES FOR THE NATURAL PATCH OR ELSE FOR ITS RULED EXTENSIONS
C
      DATA ZERO,ONE/0.0D0,1.0D0/
C
      U1=U
      V1=V
      MODE=MMODE
C
C---     SPECIAL PATH FOR HANDLING A PATCH THRU GENERAL CURVES.
C---     FIRST DECOMPOSE THE PATCH FLAG INTO COMPONENTS FOR
C---     INTERPOLATING BOUNDARIES 1 AND 2 AND BOUNDARIES 3 AND 4
C
  100 CONTINUE
      II=DABS(B(1))
      IA=MOD(II,10)
      IB=II/10
      IB=MOD(IB,10)
C---     LEVEL OF INTERPOLATION IS DIFFERENT FOR RULED INTERPOLATION
C---     AND HIGHER LEVEL OF INTERPOLATION
      IF(IA.LT.2) JLEV=1
      IF(IA.GT.1) JLEV=2
C
C---     OBTAIN DERIVATIVES AT CORRESPONDING EDGES OF BOUNDARIES
C---     NUMBERED 1 AND 2
      DO 110 I=1,2
      LOC=IFLAG(I)
      CALL CURFLO(U,CANON(LOC),RK(1,I),JLEV,1)
  110 CONTINUE
C---      BRANCH TO NON RULED TYPE OF INTERPOLATION
      IF(IA.GT.1) GO TO 200
C---     RULED TYPE OF INTERPOLATION FOLLOWS
      VA=ONE-V1
      VB=V1
      DO 120 I=1,3
      SPV(I)=RK(I,1)*VA+RK(I,2)*VB
      IF(MODE.EQ.0) GO TO 120
      SPV(I+4)=RK(I+4,1)*VA+RK(I+4,2)*VB
      SPV(I+12)=RK(I+8,1)*VA+RK(I+8,2)*VB
      SPV(I+8)=RK(I,2)-RK(I,1)
      SPV(I+20)=ZERO
      SPV(I+16)=RK(I+4,2)-RK(I+4,1)
  120 CONTINUE
C
  140 CONTINUE
C
      GO TO 999
C
C---     THE CASE OF NON-RULED INTERPOLATION
  200 CONTINUE
      CALL BLENDF(V,FV)
      DO 210 I=1,3
      SPV(I)=
     C FV(1)*RK(I,1)+FV(2)*RK(I,2)+FV(3)*RK(I+16,1)+FV(4)*RK(I+16,2)
      IF(MODE.EQ.0) GO TO 210
      SPV(I+4)=
     C FV(1)*RK(I+4,1)+FV(2)*RK(I+4,2)+FV(3)*RK(I+20,1)+FV(4)*RK(I+20,2)
      SPV(I+8)=
     C FV(5)*RK(I,1)+FV(6)*RK(I,2)+FV(7)*RK(I+16,1)+FV(8)*RK(I+16,2)
      SPV(I+12)=
     C FV(1)*RK(I+8,1)+FV(2)*RK(I+8,2)+FV(3)*RK(I+24,1)+FV(4)*RK(I+24,2)
      SPV(I+16)=
     C FV(5)*RK(I+4,1)+FV(6)*RK(I+4,2)+FV(7)*RK(I+20,1)+FV(8)*RK(I+20,2)
      SPV(I+20)=
     C FV(9)*RK(I,1)+FV(10)*RK(I,2)+FV(11)*RK(I+16,1)+FV(12)*RK(I+16,2)
  210 CONTINUE
C
      IF(IB.LT.2) GO TO 140
C
C---     THE FULL CROSS CURVE CASE, TWO MORE LEVELS OF INTERPOLATION
C---     ARE NOW REQUIRED.
C
C---     FIRST LOAD THE TWO CROSS CURVES AND INTERPOLATE THEM
      DO 410 I=3,4
      LOC=IFLAG(I)
      II=I-2
      CALL CURFLO(V,CANON(LOC),RK(1,II),JLEV,1)
  410 CONTINUE
      BSAVE=B(1)
      CALL BLENDF(U,FV)
      DO 420 I=1,3
      SPW(I)=SPV(I)+
     C FV(1)*RK(I,1)+FV(2)*RK(I,2)+FV(3)*RK(I+16,1)+FV(4)*RK(I+16,2)
      IF(MODE.EQ.0) GO TO 420
      SPW(I+4)=SPV(I+8)+
     C FV(1)*RK(I+4,1)+FV(2)*RK(I+4,2)+FV(3)*RK(I+20,1)+FV(4)*RK(I+20,2)
      SPW(I+8)=SPV(I+4)+
     C FV(5)*RK(I,1)+FV(6)*RK(I,2)+FV(7)*RK(I+16,1)+FV(8)*RK(I+16,2)
      SPW(I+12)=SPV(I+20)+
     C FV(1)*RK(I+8,1)+FV(2)*RK(I+8,2)+FV(3)*RK(I+24,1)+FV(4)*RK(I+24,2)
      SPW(I+16)=SPV(I+16)+
     C FV(5)*RK(I+4,1)+FV(6)*RK(I+4,2)+FV(7)*RK(I+20,1)+FV(8)*RK(I+20,2)
      SPW(I+20)=SPV(I+12)+
     C FV(9)*RK(I,1)+FV(10)*RK(I,2)+FV(11)*RK(I+16,1)+FV(12)*RK(I+16,2)
  420 CONTINUE
C---     FINALLY SET UP MATRIX FOR CONVENTIONAL COONS INTERPOLATION
C
      DO 470 I=1,2
C
      LOC=IFLAG(I)
      DO 470 J=1,2
      UT=J-1
      CALL CURFLO(UT,CANON(LOC),R(1),2,1)
      IN=J+(I-1)*4-1
      KINC=0
      DO 430 K=1,33,16
      KINC=KINC+1
      B(IN+K)=R(KINC)
      B(IN+K+2)=R(KINC+4)
      B(IN+K+8)=R(KINC+16)
      B(IN+K+10)=R(KINC+20)
  430 CONTINUE
C---     SET THE W MATRIX
      DO 435 L=51,64
      B(L)=ZERO
  435 CONTINUE
      B(49)=ONE
      B(50)=ONE
      B(53)=ONE
      B(54)=ONE
C
  470 CONTINUE
C
C---     NOW EVALUATE COONS INTERPOLATION OF SURFACE POINT
C
      CALL CNSURG(U,V,B,SPV,IFLX,MODE)
C
C---     NOWSUBTRACT THIS POINT AND DERIVATIVES FROM SPW
C---     TO OBTAIN THE CONSTRAINED INTERPOLATION.
C
      DO 450 I=1,3
      SPV(I)=SPW(I)-SPV(I)
      IF(MODE.LT.1) GO TO 450
      SPV(I+4)=SPW(I+8)-SPV(I+4)
      SPV(I+8)=SPW(I+4)-SPV(I+8)
      SPV(I+12)=SPW(I+20)-SPV(I+12)
      SPV(I+16)=SPW(I+16)-SPV(I+16)
      SPV(I+20)=SPW(I+12)-SPV(I+20)
  450 CONTINUE
C---     NOW RESTORE THE B MATRIX
      DO 480 I=2,64
  480 B(I)=ZERO
      B(49)=ONE
      B(50)=ONE
      B(53)=ONE
      B(54)=ONE
      B(1)=BSAVE
C
  999 CONTINUE
      RETURN
      END
