*
C.....FORTRAN SUBROUTINE             DOTF.....              5/1/68   GK
C                      THE FIRST INPUT VECTOR
C              ARG2    ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE SECOND INPUT VECTOR
C
C SUBSIDIARIES TYPE                ENTRY
C              LOGICAL FUNCTION    CKDEF
C              SUBROUTINE          ERROR
C
      SUBROUTINE DOTF (RESULT,ARG1,ARG2)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION ARG1(3),ARG2(3),DS(6)
      DOUBLE PRECISION DS
      LOGICAL CKDEF
C
C
C
      INCLUDE (TOTAL)
      INCLUDE (ZNUMBR)
      INCLUDE (KNUMBR)
C
      IF (CKDEF(ARG1).OR.CKDEF(ARG2)) GO TO 20
C
C...     MOVE ARGUMENTS TO DOUBLE PRECISION SCRATCH LOCATIONS
C
C
      DO 10 I=1,3
      DS(I)=ARG1(I)
      DS(I+3)=ARG2(I)
   10 CONTINUE
C
C...     COMPUTE DOT PRODUCT
C
      RESULT = DS(1)*DS(4) +DS(2)*DS(5) +DS(3)*DS(6)
      GO TO 9
C
C...     ISSUE DIAGNOSTIC, INPUT UNDEFINED, RESULT=0
C
   20 CALL ERROR (10,'DOTF   ')
      RESULT = Z0
    9 RETURN
       END
