My Project: ABUFTP.c File Reference
ABUFTP.c File Reference
#include "f2c.h"
Macros
#define filtab_1 filtab_
#define ifiltb_1 ifiltb_
#define darray_1 darray_
Functions
int abuftp_0_ (int n__, integer *no, integer *n)
int abuftp_ (integer *no, integer *n)
int bufftp_ (integer *no, integer *n)
Variables
struct {
char filnam [480]
char filacc [300]
char filfmt [330]
char opstat [210]
char clstat [180]
} filtab_
struct {
integer u [30]
integer rl [30]
integer nxtrec [30]
integer lstrec [30]
} ifiltb_
struct {
char darray [120]
} darray_
static integer c__2 = 2
static integer c__35 = 35
static integer c__37 = 37
static integer c__42 = 42
static integer c_n4 = -4
static integer c_n3 = -3
static integer c__51 = 51
Macro Definition Documentation
#define darray_1 darray_
Definition at line 33 of file ABUFTP.c.
Referenced by abuftp_0_().
#define filtab_1 filtab_
Definition at line 21 of file ABUFTP.c.
#define ifiltb_1 ifiltb_
Definition at line 27 of file ABUFTP.c.
Referenced by abuftp_0_().
Function Documentation
int abuftp_ (integer * no, integer * n)
Definition at line 210 of file ABUFTP.c.
References abuftp_0_().
 {
     return abuftp_0_(0, no, n);
     }
int abuftp_0_ (int n__, integer * no, integer * n)
Definition at line 47 of file ABUFTP.c.
References abnend_(), c__2, c__35, c__37, c__42, c__51, c_n3, c_n4, cform_(), cprint_(), darray_1, filopn_(), id, ifiltb_1, no, and tapop_().
Referenced by abuftp_(), and bufftp_().
 {
     /* System generated locals */
     inlist ioin__1;
     /* Builtin functions */
     integer f_inqu(inlist *);
     /* Local variables */
     static integer id;
     static logical od;
     static integer ifil;
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen), tapop_(integer *, integer *), abnend_(void),
         filopn_(integer *), cprint_(char *, ftnlen);
 /*  *  ABUFTP  *  VAX-11 VERSION   08.07.82  E.MCLELLAN */
 /*  PURPOSE     TO PROVIDE FILE HANDLING  CAPABILITY */
 /*              COMPATABLE  WITH APT 111 POST PROCESSOR USAGE */
 /*  CALLING SEQUENCE */
 /*              CALL ABUFTP(NO,N) */
 /*  ARGUMENTS */
 /*              NO    FILE NUMBER */
 /*                    FOR NC 360 HELD IN SECOND HALF */
 /*                    OF REAL*8 WORD */
 /*              N=1   OPEN FILE IN WRITE MODE */
 /*               =2   OPEN FILE IN READ MODE */
 /*               =3   REWIND FILE */
 /*               =9   CLOSE FILE */
 /*  ALTERNATIVE ENTRY */
 /*              CALL BUFFTP(NO,N) */
 /*  *  FILE ATTRIBUTES  * */
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
     /* Parameter adjustments */
     --no;
     /* Function Body */
     switch(n__) {
     case 1: goto L_bufftp;
     }
 L_bufftp:
     ifil = no[1];
     if (no[1] == 0) {
     ifil = no[2];
     }
     if (ifil < 1 || ifil > 50) {
     cform_(" *** FILE NUMBER OUTSIDE RANGE 1-50", darray_1.darray, &c__2,
         &c__35, (ftnlen)35, (ftnlen)120);
     cform_(" REQUESTED IN CALL TO ABUFTP OR BUFFTP ***", darray_1.darray,
         &c__37, &c__42, (ftnlen)42, (ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     abnend_();
     } else {
     id = ifiltb_1.u[ifil - 1];
     if (*n == 1) {
 /* ....    OPEN FILE IN WRITE MODE */
         ioin__1.inerr = 0;
         ioin__1.inunit = id;
         ioin__1.infile = 0;
         ioin__1.inex = 0;
         ioin__1.inopen = &od;
         ioin__1.innum = 0;
         ioin__1.innamed = 0;
         ioin__1.inname = 0;
         ioin__1.inacc = 0;
         ioin__1.inseq = 0;
         ioin__1.indir = 0;
         ioin__1.infmt = 0;
         ioin__1.inform = 0;
         ioin__1.inunf = 0;
         ioin__1.inrecl = 0;
         ioin__1.innrec = 0;
         ioin__1.inblank = 0;
         f_inqu(&ioin__1);
         if (od) {
         return 0;
         } else {
         filopn_(&ifil);
         }
     } else if (*n == 2) {
 /* .....   OPEN FILE IN READ MODE */
         ioin__1.inerr = 0;
         ioin__1.inunit = id;
         ioin__1.infile = 0;
         ioin__1.inex = 0;
         ioin__1.inopen = &od;
         ioin__1.innum = 0;
         ioin__1.innamed = 0;
         ioin__1.inname = 0;
         ioin__1.inacc = 0;
         ioin__1.inseq = 0;
         ioin__1.indir = 0;
         ioin__1.infmt = 0;
         ioin__1.inform = 0;
         ioin__1.inunf = 0;
         ioin__1.inrecl = 0;
         ioin__1.innrec = 0;
         ioin__1.inblank = 0;
         f_inqu(&ioin__1);
         if (od) {
         return 0;
         } else {
         filopn_(&ifil);
         }
     } else if (*n == 3) {
 /* .....   REWIND FILE */
         tapop_(&ifil, &c_n4);
     } else if (*n == 9) {
 /* .....   CLOSE FILE */
         tapop_(&ifil, &c_n3);
     } else {
 /* .....   INVALID ARGUMENT */
         cform_(" *** INVALID ARGUMENT IN CALL TO ABUFTP(BUFFTP) ***",
             darray_1.darray, &c__2, &c__51, (ftnlen)51, (ftnlen)120);
         cprint_(darray_1.darray, (ftnlen)120);
         abnend_();
     }
     }
     return 0;
 } /* abuftp_ */
int bufftp_ (integer * no, integer * n)
Definition at line 215 of file ABUFTP.c.
References abuftp_0_().
 {
     return abuftp_0_(1, no, n);
     }
Variable Documentation
integer c__2 = 2 static
Definition at line 37 of file ABUFTP.c.
Referenced by abuftp_0_().
integer c__35 = 35 static
Definition at line 38 of file ABUFTP.c.
Referenced by abuftp_0_().
integer c__37 = 37 static
Definition at line 39 of file ABUFTP.c.
Referenced by abuftp_0_().
integer c__42 = 42 static
Definition at line 40 of file ABUFTP.c.
Referenced by abuftp_0_().
integer c__51 = 51 static
Definition at line 43 of file ABUFTP.c.
Referenced by abuftp_0_().
integer c_n3 = -3 static
Definition at line 42 of file ABUFTP.c.
Referenced by abuftp_0_().
integer c_n4 = -4 static
Definition at line 41 of file ABUFTP.c.
Referenced by abuftp_0_().
char clstat[180]
Definition at line 18 of file ABUFTP.c.
char darray[120]
Definition at line 30 of file ABUFTP.c.
struct { ... } darray_
char filacc[300]
Definition at line 18 of file ABUFTP.c.
char filfmt[330]
Definition at line 18 of file ABUFTP.c.
char filnam[480]
Definition at line 18 of file ABUFTP.c.
struct { ... } filtab_
struct { ... } ifiltb_
integer lstrec[30]
Definition at line 24 of file ABUFTP.c.
integer nxtrec[30]
Definition at line 24 of file ABUFTP.c.
char opstat[210]
Definition at line 18 of file ABUFTP.c.
integer rl[30]
Definition at line 24 of file ABUFTP.c.
Referenced by gchk_(), smooth_(), sspath_(), and stepck_().
integer u[30]
Definition at line 24 of file ABUFTP.c.