My Project: ADDRSS.c File Reference
ADDRSS.c File Reference
#include "f2c.h"
Functions
integer addrss_ (doublereal *x)
Function Documentation
integer addrss_ (doublereal * x)
Definition at line 17 of file ADDRSS.c.
Referenced by apt094_(), apt103_(), apt104_(), apt202_(), gclear_(), print_(), and punch_().
 {
     /* System generated locals */
     integer ret_val;
 /*  * ADDRSS *   VAX11 FORTRAN VERSION    18.2.82  E.MCLELLAN */
 /*  PURPOSE     ADDRSS RETURNS AN INTEGER WHICH IS THE */
 /*              ACTUAL MACHINE ADDRESS OF THE ARGUMENT */
 /*  CALLING SEQUENCE */
 /*              VALUE=ADDRSS(X) */
 /*  ARGUMENTS */
 /*              X  VARIABLE WHOSE ADDRESS IS TO BE RETURNED */
 /*      ADDRSS=%LOC(X) */
 /*      addrss=loc(x) */
     return ret_val;
 } /* addrss_ */