My Project: AERR.c File Reference
AERR.c File Reference
#include "f2c.h"
Macros
#define ifxcor_1 ifxcor_
#define symfil_1 symfil_
#define aercom_1 aercom_
#define darray_1 darray_
#define super_1 super_
#define cflags ((logical *)&super_1)
#define lxtras ((logical *)&super_1 + 9)
Functions
int aerr_ (integer *number, char *sbnam, ftnlen sbnam_len)
Variables
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
struct {
integer iaerfg
integer npctpt
doublereal pctpts [60]
doublereal pctpln [4]
doublereal errpts [9]
} aercom_
struct {
char darray [120]
} darray_
struct {
logical err
logical xc
logical cl
logical px
integer errx
logical end
logical fini
logical asm__
logical abend
integer xtras [7]
} super_
static integer c__10 = 10
static integer c__1 = 1
static integer c__26 = 26
static integer c__27 = 27
static integer c__5 = 5
static integer c__36 = 36
static integer c__3 = 3
static integer c__39 = 39
static integer c__44 = 44
static integer c__17 = 17
static integer c__61 = 61
static integer c__8 = 8
static integer c__69 = 69
Macro Definition Documentation
#define aercom_1 aercom_
Definition at line 42 of file AERR.c.
Referenced by aerr_().
#define cflags ((logical *)&super_1)
#define darray_1 darray_
Definition at line 48 of file AERR.c.
Referenced by aerr_().
#define ifxcor_1 ifxcor_
Definition at line 25 of file AERR.c.
Referenced by aerr_().
#define lxtras ((logical *)&super_1 + 9)
#define super_1 super_
Definition at line 57 of file AERR.c.
Referenced by aerr_().
#define symfil_1 symfil_
Definition at line 34 of file AERR.c.
Referenced by aerr_().
Function Documentation
int aerr_ (integer * number, char * sbnam, ftnlen sbnam_len)
Definition at line 79 of file AERR.c.
References aercom_1, aerr2_(), atape_(), bcdf_(), c__1, c__10, c__17, c__26, c__27, c__3, c__36, c__39, c__44, c__5, c__61, c__69, c__8, cform_(), cprint_(), darray_1, errout_(), ewrite_(), first, iconv_(), ifxcor_1, ir, num, number, record_(), subnam, super_1, and symfil_1.
Referenced by ajundd_(), amind_(), apt200_(), apt211_(), apt235_(), apt240_(), arlm2_(), arlm3_(), centr_(), check_(), cpldst_(), cutred_(), cutteh_(), cuttes_(), ddpara_(), ddssrf_(), ddst_(), ddtabc_(), go2_(), go_(), gochor_(), godlta_(), gol_(), golovo_(), golpln_(), gop_(), indirp_(), indirv_(), indrph_(), indrvh_(), intsec_(), lcls_(), numver_(), plane_(), pocket_(), radar_(), smil_(), srfvct_(), thick_(), thickh_(), tlaxis_(), tlconv_(), tlnorm_(), and u1comp_().
 {
     /* Initialized data */
     static integer kerr[10] = { 0,0,1308622848,1,1308622848,1,1308622848,1,0,
         0 };
     static logical first = TRUE_;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer ir, nr, isn[2], num;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int aerr2_(integer *, char *, ftnlen), atape_(
         void), cform_(char *, char *, integer *, integer *, ftnlen,
         ftnlen), iconv_(integer *, char *, integer *, integer *, ftnlen);
 #define cflags ((logical *)&super_1)
     extern /* Subroutine */ int record_(integer *);
     static char subnam[8];
     extern /* Subroutine */ int ewrite_(integer *, integer *, integer *,
         integer *, integer *), cprint_(char *, ftnlen);
 #define lxtras ((logical *)&super_1 + 9)
     extern /* Subroutine */ int errout_(integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /* ...  20. SYSTEM I/O FILE NAMES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*     25. COMMON FOR AERR INFORMATION */
 /* ...                SYSTEM I/O FILES */
 /* ...      32.  PARAMETERS REQUIRED BY SUPERVISOR */
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
 /*     ------------------------------------------------------------ */
     if (first) {
     kerr[0] = bcdf_("AERR", (ftnlen)4);
     kerr[1] = bcdf_("    ", (ftnlen)4);
     first = FALSE_;
     }
     s_copy(subnam, sbnam, (ftnlen)8, sbnam_len);
     if (*number < 0) {
     goto L10;
     }
     aerr2_(number, subnam, (ftnlen)8);
     goto L20;
 /*        WARNING DIAGNOSTIC - NO VARIABLE INFORMATION OUTPUT */
 L10:
     ++super_1.xtras[1];
     ifxcor_1.iaerr = 1;
     atape_();
     nr = 0;
     kerr[3] = 1;
     kerr[5] = 2;
     kerr[7] = *number;
     kerr[8] = bcdf_(subnam, (ftnlen)4);
     kerr[9] = bcdf_(subnam + 4, (ftnlen)4);
     ewrite_(&symfil_1.exfile, &nr, kerr, &c__10, &ir);
     if (super_1.errx < 4) {
     super_1.errx = 4;
     }
     cprint_(darray_1.darray, (ftnlen)120);
     num = abs(*number);
     ifxcor_1.iaerr = 0;
     aercom_1.iaerfg = 0;
     record_(isn);
     cform_(" ***** WARNING DIAGNOSTIC ", darray_1.darray, &c__1, &c__26, (
         ftnlen)26, (ftnlen)120);
     iconv_(&num, darray_1.darray, &c__27, &c__5, (ftnlen)120);
     cform_("ISN", darray_1.darray, &c__36, &c__3, (ftnlen)3, (ftnlen)120);
     iconv_(isn, darray_1.darray, &c__39, &c__5, (ftnlen)120);
     cform_(" FROM SUBROUTINE ", darray_1.darray, &c__44, &c__17, (ftnlen)17, (
         ftnlen)120);
     cform_(subnam, darray_1.darray, &c__61, &c__8, (ftnlen)8, (ftnlen)120);
     cform_("*****", darray_1.darray, &c__69, &c__5, (ftnlen)5, (ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     errout_(number);
 L20:
     return 0;
 } /* aerr_ */
Variable Documentation
logical abend
Definition at line 53 of file AERR.c.
struct { ... } aercom_
logical asm__
Definition at line 53 of file AERR.c.
integer axfile
Definition at line 28 of file AERR.c.
integer c__1 = 1 static
Definition at line 62 of file AERR.c.
Referenced by aerr_().
integer c__10 = 10 static
Definition at line 61 of file AERR.c.
Referenced by aerr_().
integer c__17 = 17 static
Definition at line 70 of file AERR.c.
Referenced by aerr_().
integer c__26 = 26 static
Definition at line 63 of file AERR.c.
Referenced by aerr_().
integer c__27 = 27 static
Definition at line 64 of file AERR.c.
Referenced by aerr_().
integer c__3 = 3 static
Definition at line 67 of file AERR.c.
Referenced by aerr_().
integer c__36 = 36 static
Definition at line 66 of file AERR.c.
Referenced by aerr_().
integer c__39 = 39 static
Definition at line 68 of file AERR.c.
Referenced by aerr_().
integer c__44 = 44 static
Definition at line 69 of file AERR.c.
Referenced by aerr_().
integer c__5 = 5 static
Definition at line 65 of file AERR.c.
Referenced by aerr_().
integer c__61 = 61 static
Definition at line 71 of file AERR.c.
Referenced by aerr_().
integer c__69 = 69 static
Definition at line 73 of file AERR.c.
Referenced by aerr_().
integer c__8 = 8 static
Definition at line 72 of file AERR.c.
Referenced by aerr_().
logical cl
Definition at line 51 of file AERR.c.
integer clfil3
Definition at line 28 of file AERR.c.
integer clfile
Definition at line 28 of file AERR.c.
integer clfilp
Definition at line 28 of file AERR.c.
integer cpfile
Definition at line 28 of file AERR.c.
char darray[120]
Definition at line 45 of file AERR.c.
struct { ... } darray_
integer elfil1
Definition at line 28 of file AERR.c.
integer elfil2
Definition at line 28 of file AERR.c.
integer elfil3
Definition at line 28 of file AERR.c.
integer elfil4
Definition at line 28 of file AERR.c.
integer elfile
Definition at line 28 of file AERR.c.
logical end
Definition at line 53 of file AERR.c.
logical err
Definition at line 51 of file AERR.c.
doublereal errpts[9]
Definition at line 38 of file AERR.c.
integer errx
Definition at line 52 of file AERR.c.
integer exfile
Definition at line 28 of file AERR.c.
logical fini
Definition at line 53 of file AERR.c.
integer i3dflg
Definition at line 18 of file AERR.c.
integer iaerfg
Definition at line 37 of file AERR.c.
integer iaerr
Definition at line 18 of file AERR.c.
integer iautps
Definition at line 18 of file AERR.c.
integer ibegin
Definition at line 18 of file AERR.c.
Referenced by scon_(), and smil_().
integer ic
Definition at line 18 of file AERR.c.
integer icheck
Definition at line 18 of file AERR.c.
integer icl
Definition at line 18 of file AERR.c.
integer ics
Definition at line 18 of file AERR.c.
Referenced by mesh_().
integer icscnt
Definition at line 18 of file AERR.c.
integer ictdef
Definition at line 18 of file AERR.c.
integer icut
Definition at line 18 of file AERR.c.
Referenced by apt301_().
integer ids
Definition at line 18 of file AERR.c.
integer ier
Definition at line 18 of file AERR.c.
Referenced by apt107_(), comptw_(), and smooth_().
struct { ... } ifxcor_
integer igo
Definition at line 18 of file AERR.c.
integer igoto
Definition at line 18 of file AERR.c.
Referenced by pro026_().
integer igoug
Definition at line 18 of file AERR.c.
integer igs
Definition at line 18 of file AERR.c.
integer infile__
Definition at line 28 of file AERR.c.
integer inops
Definition at line 18 of file AERR.c.
integer ips
Definition at line 18 of file AERR.c.
integer ipsdef
Definition at line 18 of file AERR.c.
integer ipt1
Definition at line 18 of file AERR.c.
integer is
Definition at line 18 of file AERR.c.
integer iseg
Definition at line 18 of file AERR.c.
Referenced by curflo_(), floseg_(), gencrv_(), and parmf2_().
integer iseqno
Definition at line 18 of file AERR.c.
Referenced by mesh_(), print_(), and sspath_().
integer ispare[26]
Definition at line 28 of file AERR.c.
integer isrch
Definition at line 18 of file AERR.c.
Referenced by balsrf_().
integer istrup
Definition at line 18 of file AERR.c.
integer it
Definition at line 18 of file AERR.c.
Referenced by apt070_(), apt331_(), cnvrt3_(), gcone_(), gochor_(), and mixal_().
integer jbr
Definition at line 18 of file AERR.c.
integer jsw
Definition at line 18 of file AERR.c.
integer ldafil
Definition at line 28 of file AERR.c.
integer libfil
Definition at line 28 of file AERR.c.
integer lsv
Definition at line 18 of file AERR.c.
integer lsv1
Definition at line 18 of file AERR.c.
integer mactxt
Definition at line 28 of file AERR.c.
integer mantax
Definition at line 18 of file AERR.c.
integer motmod
Definition at line 18 of file AERR.c.
integer msav
Definition at line 18 of file AERR.c.
integer mulout
Definition at line 18 of file AERR.c.
integer nfil12
Definition at line 28 of file AERR.c.
integer nfil13
Definition at line 28 of file AERR.c.
integer nmbseg
Definition at line 18 of file AERR.c.
integer nmpnts
Definition at line 18 of file AERR.c.
integer npctpt
Definition at line 37 of file AERR.c.
integer nrec
Definition at line 18 of file AERR.c.
Referenced by mcxtrn_().
integer numax
Definition at line 18 of file AERR.c.
integer numcnt
Definition at line 18 of file AERR.c.
integer nump
Definition at line 18 of file AERR.c.
Referenced by region_().
integer numpt1
Definition at line 18 of file AERR.c.
integer numsfs
Definition at line 18 of file AERR.c.
integer numsur
Definition at line 18 of file AERR.c.
Referenced by srfcom_().
integer nw
Definition at line 18 of file AERR.c.
Referenced by ataprd_(), and intrp_().
integer nwds
Definition at line 18 of file AERR.c.
Referenced by aserch_(), and inpat_().
doublereal pctpln[4]
Definition at line 38 of file AERR.c.
doublereal pctpts[60]
Definition at line 38 of file AERR.c.
integer pnchfl
Definition at line 28 of file AERR.c.
integer pofile
Definition at line 28 of file AERR.c.
logical px
Definition at line 51 of file AERR.c.
integer pxfile
Definition at line 28 of file AERR.c.
struct { ... } super_
struct { ... } symfil_
integer tifile
Definition at line 28 of file AERR.c.
integer vlfile
Definition at line 28 of file AERR.c.
logical xc
Definition at line 51 of file AERR.c.
integer xcan
Definition at line 28 of file AERR.c.
integer xnum
Definition at line 28 of file AERR.c.
integer xtras[7]
Definition at line 54 of file AERR.c.