My Project: APT024.c File Reference
APT024.c File Reference
#include "f2c.h"
Macros
#define ldef_1 ldef_
#define const_1 const_
#define darray_1 darray_
Functions
int apt024_ (integer *iarg)
Variables
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer kcomt
integer kcomf
logical cilprt
integer kcbn
} const_
struct {
char darray [120]
} darray_
static integer c__1 = 1
static integer c__18 = 18
static integer c__19 = 19
Macro Definition Documentation
#define const_1 const_
Definition at line 30 of file APT024.c.
Referenced by apt024_().
#define darray_1 darray_
Definition at line 36 of file APT024.c.
Referenced by apt024_().
#define ldef_1 ldef_
Definition at line 22 of file APT024.c.
Referenced by apt024_().
Function Documentation
int apt024_ (integer * iarg)
Definition at line 58 of file APT024.c.
References c__1, c__18, c__19, cform_(), const_1, cprint_(), darray_1, and ldef_1.
Referenced by xcall_().
 {
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen), cprint_(char *, ftnlen);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
     switch (*iarg) {
     case 1:  goto L1;
     case 2:  goto L2;
     case 3:  goto L3;
     case 4:  goto L4;
     case 5:  goto L5;
     case 6:  goto L6;
     }
 L1:
     ldef_1.refmot = TRUE_;
     goto L9;
 L2:
     ldef_1.refmot = FALSE_;
     goto L9;
 L3:
     ldef_1.altmlt = TRUE_;
     goto L9;
 L4:
     ldef_1.altmlt = FALSE_;
     goto L9;
 L5:
     const_1.cilprt = TRUE_;
     cform_("0 CILPRT TURNED ON", darray_1.darray, &c__1, &c__18, (ftnlen)18, (
         ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     goto L9;
 L6:
     const_1.cilprt = FALSE_;
     cform_("0 CILPRT TURNED OFF", darray_1.darray, &c__1, &c__19, (ftnlen)19,
         (ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     goto L9;
 L9:
     return 0;
 } /* apt024_ */
Variable Documentation
logical altmlt
Definition at line 18 of file APT024.c.
logical bnderr
Definition at line 18 of file APT024.c.
logical boundf
Definition at line 18 of file APT024.c.
integer c__1 = 1 static
Definition at line 40 of file APT024.c.
Referenced by apt024_().
integer c__18 = 18 static
Definition at line 41 of file APT024.c.
Referenced by apt024_().
integer c__19 = 19 static
Definition at line 42 of file APT024.c.
Referenced by apt024_().
logical canflg
Definition at line 18 of file APT024.c.
logical cilprt
Definition at line 26 of file APT024.c.
struct { ... } const_
char darray[120]
Definition at line 33 of file APT024.c.
struct { ... } darray_
logical jcs
Definition at line 18 of file APT024.c.
logical jds
Definition at line 18 of file APT024.c.
integer kcbn
Definition at line 27 of file APT024.c.
integer kcomf
Definition at line 25 of file APT024.c.
integer kcomt
Definition at line 25 of file APT024.c.
struct { ... } ldef_
logical pchlst
Definition at line 18 of file APT024.c.
logical prnton
Definition at line 18 of file APT024.c.
logical refflg
Definition at line 18 of file APT024.c.
logical refmot
Definition at line 18 of file APT024.c.
logical subflg
Definition at line 18 of file APT024.c.
logical tabprt
Definition at line 18 of file APT024.c.
logical unflag
Definition at line 18 of file APT024.c.
logical zflag
Definition at line 18 of file APT024.c.