My Project: APT016.c File Reference
APT016.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define idef_1 idef_
#define knumbr_1 knumbr_
#define s1 ((doublereal *)&dshar3_1 + 37)
#define s2 ((doublereal *)&dshar3_1 + 38)
#define s3 ((doublereal *)&dshar3_1 + 39)
#define s4 ((doublereal *)&dshar3_1 + 40)
#define s5 ((doublereal *)&dshar3_1 + 41)
Functions
int apt016_ (doublereal *result, integer *mn, doublereal *circ1, integer *nm, doublereal *circ2)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__21 = 21
static integer c__22 = 22
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT016.c.
#define dshar3_1 dshar3_
Definition at line 28 of file APT016.c.
Referenced by apt016_().
#define idef_1 idef_
Definition at line 42 of file APT016.c.
Referenced by apt016_().
#define knumbr_1 knumbr_
Definition at line 50 of file APT016.c.
Referenced by apt016_().
#define s1 ((doublereal *)&dshar3_1 + 37)
Referenced by apt016_().
#define s2 ((doublereal *)&dshar3_1 + 38)
Referenced by apt016_().
#define s3 ((doublereal *)&dshar3_1 + 39)
Referenced by apt016_().
#define s4 ((doublereal *)&dshar3_1 + 40)
Referenced by apt016_().
#define s5 ((doublereal *)&dshar3_1 + 41)
Referenced by apt016_().
#define znumbr_1 znumbr_
Definition at line 36 of file APT016.c.
Referenced by apt016_().
Function Documentation
int apt016_ (doublereal * result, integer * mn, doublereal * circ1, integer * nm, doublereal * circ2)
Definition at line 90 of file APT016.c.
References apt077_(), apt083_(), c__21, c__22, defext_(), dshar3_1, i__, idef_1, knumbr_1, result, s1, s2, s3, s4, s5, vnorm_(), and znumbr_1.
Referenced by apt015_(), and xcall_().
 {
     /* System generated locals */
     doublereal d__1, d__2;
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     static integer i__;
 #define s1 ((doublereal *)&dshar3_1 + 37)
 #define s2 ((doublereal *)&dshar3_1 + 38)
 #define s3 ((doublereal *)&dshar3_1 + 39)
 #define s4 ((doublereal *)&dshar3_1 + 40)
 #define s5 ((doublereal *)&dshar3_1 + 41)
     extern /* Subroutine */ int apt083_(doublereal *, integer *), apt077_(
         doublereal *, integer *), vnorm_(doublereal *, doublereal *),
         defext_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...     TRANSFORM CANONICAL FORMS AND CHECK INPUT VALIDITY */
     /* Parameter adjustments */
     --circ2;
     --circ1;
     --result;
     /* Function Body */
     apt083_(&circ1[1], &c__21);
     for (i__ = 1; i__ <= 7; ++i__) {
 /* L10: */
     dshar3_1.sc[i__ + 4] = dshar3_1.c__[i__ - 1];
     }
     apt083_(&circ2[1], &c__22);
 /* ...     CALCULATE DISTANCE BETWEEN CENTERS CHECK FOR CONCENTRIC, */
 /* ...        INTERSECTING CIRCLES OR CENTERS TOO CLOSE. */
 /* Computing 2nd power */
     d__1 = dshar3_1.c__[0] - dshar3_1.sc[5];
 /* Computing 2nd power */
     d__2 = dshar3_1.c__[1] - dshar3_1.sc[6];
     *s1 = sqrt(d__1 * d__1 + d__2 * d__2);
     if (*s1 <= znumbr_1.z1em5) {
     idef_1.ierror = knumbr_1.k23;
     }
     if (idef_1.ierror != 0) {
     goto L30;
     }
     if ((d__1 = dshar3_1.sc[11] - dshar3_1.c__[6], abs(d__1)) - *s1 >
         znumbr_1.z1em5) {
     idef_1.ierror = knumbr_1.k24;
     }
     if (idef_1.ierror != 0) {
     goto L30;
     }
     if (*s1 - (dshar3_1.sc[11] + dshar3_1.c__[6]) >= znumbr_1.z1em5) {
     goto L20;
     }
     if (*nm != *mn) {
     idef_1.ierror = knumbr_1.k25;
     }
 L20:
     if (idef_1.ierror != 0) {
     goto L30;
     }
 /* ...     CALCULATE SIN(ALPHA) AND COS(ALPHA) */
     *s2 = (dshar3_1.c__[1] - dshar3_1.sc[6]) / *s1;
     *s3 = (dshar3_1.c__[0] - dshar3_1.sc[5]) / *s1;
     if (*mn == *nm) {
     dshar3_1.sc[11] = -dshar3_1.sc[11];
     }
 /* ...     CALCULATE SIN(GAMMA) AND COS(GAMMA) */
     *s4 = (dshar3_1.c__[6] + dshar3_1.sc[11]) / *s1;
     *s5 = sqrt(znumbr_1.z1 - *s4 * *s4);
     if (*nm == knumbr_1.k1) {
     *s5 = -(*s5);
     }
 /* ...     SET UP CANONICAL FORM IN P AND TRANSFORM TO BASE COORDINATES */
     dshar3_1.p[0] = *s4 * *s3 + *s5 * *s2;
     dshar3_1.p[1] = *s4 * *s2 - *s5 * *s3;
     dshar3_1.p[2] = znumbr_1.z0;
     vnorm_(dshar3_1.p, dshar3_1.p);
     dshar3_1.p[3] = dshar3_1.p[0] * dshar3_1.c__[0] + dshar3_1.p[1] *
         dshar3_1.c__[1] - dshar3_1.c__[6];
     apt077_(dshar3_1.p, &knumbr_1.km1);
 L30:
     defext_(&result[1]);
     return 0;
 } /* apt016_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT016.c.
doublereal ahold[8]
Definition at line 18 of file APT016.c.
doublereal c1[8]
Definition at line 18 of file APT016.c.
doublereal c__[7]
Definition at line 25 of file APT016.c.
integer c__21 = 21 static
Definition at line 54 of file APT016.c.
Referenced by apt016_().
integer c__22 = 22 static
Definition at line 55 of file APT016.c.
Referenced by apt016_().
struct { ... } def_
doublereal degrad
Definition at line 31 of file APT016.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT016.c.
integer iblk1
Definition at line 39 of file APT016.c.
struct { ... } idef_
integer ierror
Definition at line 39 of file APT016.c.
integer k0
Definition at line 45 of file APT016.c.
integer k1
Definition at line 45 of file APT016.c.
integer k10
Definition at line 45 of file APT016.c.
integer k1013
Definition at line 45 of file APT016.c.
integer k12
Definition at line 45 of file APT016.c.
integer k13
Definition at line 45 of file APT016.c.
integer k15
Definition at line 45 of file APT016.c.
integer k16
Definition at line 45 of file APT016.c.
integer k18
Definition at line 45 of file APT016.c.
integer k19
Definition at line 45 of file APT016.c.
integer k1e4
Definition at line 45 of file APT016.c.
integer k1e6
Definition at line 45 of file APT016.c.
integer k2
Definition at line 45 of file APT016.c.
integer k23
Definition at line 45 of file APT016.c.
integer k24
Definition at line 45 of file APT016.c.
integer k25
Definition at line 45 of file APT016.c.
integer k26
Definition at line 45 of file APT016.c.
integer k27
Definition at line 45 of file APT016.c.
integer k29
Definition at line 45 of file APT016.c.
integer k3
Definition at line 45 of file APT016.c.
integer k30
Definition at line 45 of file APT016.c.
integer k31
Definition at line 45 of file APT016.c.
integer k32
Definition at line 45 of file APT016.c.
integer k33
Definition at line 45 of file APT016.c.
integer k34
Definition at line 45 of file APT016.c.
integer k4
Definition at line 45 of file APT016.c.
integer k44
Definition at line 45 of file APT016.c.
integer k45
Definition at line 45 of file APT016.c.
integer k46
Definition at line 45 of file APT016.c.
integer k47
Definition at line 45 of file APT016.c.
integer k48
Definition at line 45 of file APT016.c.
integer k5
Definition at line 45 of file APT016.c.
integer k50
Definition at line 45 of file APT016.c.
integer k51
Definition at line 45 of file APT016.c.
integer k52
Definition at line 45 of file APT016.c.
integer k6
Definition at line 45 of file APT016.c.
integer k7
Definition at line 45 of file APT016.c.
integer k8
Definition at line 45 of file APT016.c.
integer k9
Definition at line 45 of file APT016.c.
integer km1
Definition at line 45 of file APT016.c.
struct { ... } knumbr_
integer kwrdsz
Definition at line 39 of file APT016.c.
doublereal l[4]
Definition at line 25 of file APT016.c.
integer ldasiz
Definition at line 39 of file APT016.c.
doublereal ln1[5]
Definition at line 18 of file APT016.c.
doublereal p[16]
Definition at line 25 of file APT016.c.
doublereal pi
Definition at line 31 of file APT016.c.
doublereal r__[10]
Definition at line 18 of file APT016.c.
doublereal ref[8]
Definition at line 18 of file APT016.c.
doublereal sc[16]
Definition at line 25 of file APT016.c.
integer surfad[4]
Definition at line 39 of file APT016.c.
doublereal t[12]
Definition at line 25 of file APT016.c.
doublereal t1[12]
Definition at line 25 of file APT016.c.
doublereal v[10]
Definition at line 25 of file APT016.c.
doublereal z0
Definition at line 31 of file APT016.c.
doublereal z1
Definition at line 31 of file APT016.c.
doublereal z10
Definition at line 31 of file APT016.c.
doublereal z11em1
Definition at line 31 of file APT016.c.
doublereal z12em1
Definition at line 31 of file APT016.c.
doublereal z1e38
Definition at line 31 of file APT016.c.
doublereal z1e6
Definition at line 31 of file APT016.c.
doublereal z1em1
Definition at line 31 of file APT016.c.
doublereal z1em2
Definition at line 31 of file APT016.c.
doublereal z1em3
Definition at line 31 of file APT016.c.
doublereal z1em5
Definition at line 31 of file APT016.c.
doublereal z1em6
Definition at line 31 of file APT016.c.
doublereal z1em7
Definition at line 31 of file APT016.c.
doublereal z1em9
Definition at line 31 of file APT016.c.
doublereal z2
Definition at line 31 of file APT016.c.
doublereal z3
Definition at line 31 of file APT016.c.
doublereal z5
Definition at line 31 of file APT016.c.
doublereal z5em1
Definition at line 31 of file APT016.c.
doublereal z5em6
Definition at line 31 of file APT016.c.
doublereal z6em1
Definition at line 31 of file APT016.c.
doublereal z90
Definition at line 31 of file APT016.c.
doublereal z9em1
Definition at line 31 of file APT016.c.
doublereal zm1
Definition at line 31 of file APT016.c.
struct { ... } znumbr_