My Project: APT047.c File Reference
APT047.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define ldef_1 ldef_
#define idef_1 idef_
#define knumbr_1 knumbr_
#define s1 ((doublereal *)&dshar3_1 + 37)
Functions
int apt047_ (doublereal *result, doublereal *pl, integer *mn, doublereal *d__)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__0 = 0
static doublereal c_b6 = 1.
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT047.c.
#define dshar3_1 dshar3_
Definition at line 28 of file APT047.c.
Referenced by apt047_().
#define idef_1 idef_
Definition at line 49 of file APT047.c.
Referenced by apt047_().
#define knumbr_1 knumbr_
Definition at line 57 of file APT047.c.
Referenced by apt047_().
#define ldef_1 ldef_
Definition at line 43 of file APT047.c.
Referenced by apt047_().
#define s1 ((doublereal *)&dshar3_1 + 37)
Referenced by apt047_().
#define znumbr_1 znumbr_
Definition at line 36 of file APT047.c.
Referenced by apt047_().
Function Documentation
int apt047_ (doublereal * result, doublereal * pl, integer * mn, doublereal * d__)
Definition at line 98 of file APT047.c.
References apt077_(), c__0, c_b6, defext_(), dshar3_1, dummy1, i__, idef_1, k, knumbr_1, ldef_1, pl, result, s1, znumbr_1, and zvect_().
Referenced by apt020_(), and xcall_().
 {
     /* Initialized data */
     static doublereal zlit1 = 3.5;
     static integer k59 = 59;
     /* Builtin functions */
     double d_sign(doublereal *, doublereal *);
     /* Local variables */
     static integer i__, k;
 #define s1 ((doublereal *)&dshar3_1 + 37)
     extern /* Subroutine */ int apt077_(doublereal *, integer *);
     extern logical zvect_(doublereal *);
     static doublereal dummy1;
     extern /* Subroutine */ int defext_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...     TRANSFORM CANONICAL FORM TO LOCAL COORDINATE SYSTEM */
     /* Parameter adjustments */
     --pl;
     --result;
     /* Function Body */
     apt077_(&pl[1], &c__0);
     if (ldef_1.unflag) {
     goto L50;
     }
     ldef_1.unflag = ! zvect_(dshar3_1.l);
 /* ...     CHECK WHICH SIDE NEW PLANE IS ON */
     i__ = (*mn - knumbr_1.k1) % knumbr_1.k3;
     for (k = 1; k <= 3; ++k) {
     dummy1 = (doublereal) (*mn);
     *s1 = dshar3_1.l[i__] * (zlit1 - dummy1);
     if (*s1 != znumbr_1.z0) {
         goto L30;
     }
 /* ...     UNABLE TO DISTINGUISH PLANE, TRY NEXT DIMENSION */
     i__ = (i__ + knumbr_1.k1) % knumbr_1.k3;
 /* L20: */
     idef_1.ierror = k59;
     }
 /* ...     FORM DESIRED PLANE */
 L30:
     dshar3_1.l[3] += *d__ * d_sign(&c_b6, s1);
     apt077_(dshar3_1.l, &knumbr_1.km1);
 L40:
     defext_(&result[1]);
     return 0;
 L50:
     idef_1.ierror = knumbr_1.k1;
     goto L40;
 } /* apt047_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT047.c.
doublereal ahold[8]
Definition at line 18 of file APT047.c.
logical altmlt
Definition at line 39 of file APT047.c.
logical bnderr
Definition at line 39 of file APT047.c.
logical boundf
Definition at line 39 of file APT047.c.
doublereal c1[8]
Definition at line 18 of file APT047.c.
doublereal c__[7]
Definition at line 25 of file APT047.c.
integer c__0 = 0 static
Definition at line 61 of file APT047.c.
Referenced by apt047_().
doublereal c_b6 = 1. static
Definition at line 62 of file APT047.c.
Referenced by apt047_().
logical canflg
Definition at line 39 of file APT047.c.
struct { ... } def_
doublereal degrad
Definition at line 31 of file APT047.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT047.c.
integer iblk1
Definition at line 46 of file APT047.c.
struct { ... } idef_
integer ierror
Definition at line 46 of file APT047.c.
logical jcs
Definition at line 39 of file APT047.c.
logical jds
Definition at line 39 of file APT047.c.
integer k0
Definition at line 52 of file APT047.c.
integer k1
Definition at line 52 of file APT047.c.
integer k10
Definition at line 52 of file APT047.c.
integer k1013
Definition at line 52 of file APT047.c.
integer k12
Definition at line 52 of file APT047.c.
integer k13
Definition at line 52 of file APT047.c.
integer k15
Definition at line 52 of file APT047.c.
integer k16
Definition at line 52 of file APT047.c.
integer k18
Definition at line 52 of file APT047.c.
integer k19
Definition at line 52 of file APT047.c.
integer k1e4
Definition at line 52 of file APT047.c.
integer k1e6
Definition at line 52 of file APT047.c.
integer k2
Definition at line 52 of file APT047.c.
integer k23
Definition at line 52 of file APT047.c.
integer k24
Definition at line 52 of file APT047.c.
integer k25
Definition at line 52 of file APT047.c.
integer k26
Definition at line 52 of file APT047.c.
integer k27
Definition at line 52 of file APT047.c.
integer k29
Definition at line 52 of file APT047.c.
integer k3
Definition at line 52 of file APT047.c.
integer k30
Definition at line 52 of file APT047.c.
integer k31
Definition at line 52 of file APT047.c.
integer k32
Definition at line 52 of file APT047.c.
integer k33
Definition at line 52 of file APT047.c.
integer k34
Definition at line 52 of file APT047.c.
integer k4
Definition at line 52 of file APT047.c.
integer k44
Definition at line 52 of file APT047.c.
integer k45
Definition at line 52 of file APT047.c.
integer k46
Definition at line 52 of file APT047.c.
integer k47
Definition at line 52 of file APT047.c.
integer k48
Definition at line 52 of file APT047.c.
integer k5
Definition at line 52 of file APT047.c.
integer k50
Definition at line 52 of file APT047.c.
integer k51
Definition at line 52 of file APT047.c.
integer k52
Definition at line 52 of file APT047.c.
integer k6
Definition at line 52 of file APT047.c.
integer k7
Definition at line 52 of file APT047.c.
integer k8
Definition at line 52 of file APT047.c.
integer k9
Definition at line 52 of file APT047.c.
integer km1
Definition at line 52 of file APT047.c.
struct { ... } knumbr_
integer kwrdsz
Definition at line 46 of file APT047.c.
doublereal l[4]
Definition at line 25 of file APT047.c.
integer ldasiz
Definition at line 46 of file APT047.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file APT047.c.
doublereal p[16]
Definition at line 25 of file APT047.c.
logical pchlst
Definition at line 39 of file APT047.c.
doublereal pi
Definition at line 31 of file APT047.c.
logical prnton
Definition at line 39 of file APT047.c.
doublereal r__[10]
Definition at line 18 of file APT047.c.
doublereal ref[8]
Definition at line 18 of file APT047.c.
logical refflg
Definition at line 39 of file APT047.c.
logical refmot
Definition at line 39 of file APT047.c.
doublereal sc[16]
Definition at line 25 of file APT047.c.
logical subflg
Definition at line 39 of file APT047.c.
integer surfad[4]
Definition at line 46 of file APT047.c.
doublereal t[12]
Definition at line 25 of file APT047.c.
doublereal t1[12]
Definition at line 25 of file APT047.c.
logical tabprt
Definition at line 39 of file APT047.c.
logical unflag
Definition at line 39 of file APT047.c.
doublereal v[10]
Definition at line 25 of file APT047.c.
doublereal z0
Definition at line 31 of file APT047.c.
doublereal z1
Definition at line 31 of file APT047.c.
doublereal z10
Definition at line 31 of file APT047.c.
doublereal z11em1
Definition at line 31 of file APT047.c.
doublereal z12em1
Definition at line 31 of file APT047.c.
doublereal z1e38
Definition at line 31 of file APT047.c.
doublereal z1e6
Definition at line 31 of file APT047.c.
doublereal z1em1
Definition at line 31 of file APT047.c.
doublereal z1em2
Definition at line 31 of file APT047.c.
doublereal z1em3
Definition at line 31 of file APT047.c.
doublereal z1em5
Definition at line 31 of file APT047.c.
doublereal z1em6
Definition at line 31 of file APT047.c.
doublereal z1em7
Definition at line 31 of file APT047.c.
doublereal z1em9
Definition at line 31 of file APT047.c.
doublereal z2
Definition at line 31 of file APT047.c.
doublereal z3
Definition at line 31 of file APT047.c.
doublereal z5
Definition at line 31 of file APT047.c.
doublereal z5em1
Definition at line 31 of file APT047.c.
doublereal z5em6
Definition at line 31 of file APT047.c.
doublereal z6em1
Definition at line 31 of file APT047.c.
doublereal z90
Definition at line 31 of file APT047.c.
doublereal z9em1
Definition at line 31 of file APT047.c.
logical zflag
Definition at line 39 of file APT047.c.
doublereal zm1
Definition at line 31 of file APT047.c.
struct { ... } znumbr_