My Project: APT014.c File Reference
APT014.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
Functions
int apt014_ (doublereal *result, doublereal *p1, doublereal *p2)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
static integer c__0 = 0
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT014.c.
#define dshar3_1 dshar3_
Definition at line 28 of file APT014.c.
Referenced by apt014_().
Function Documentation
int apt014_ (doublereal * result, doublereal * p1, doublereal * p2)
Definition at line 58 of file APT014.c.
References apt012_(), apt081_(), c__0, dshar3_1, p1, p2, and result.
Referenced by apt070_(), and xcall_().
 {
     extern /* Subroutine */ int apt012_(doublereal *, doublereal *,
         doublereal *, doublereal *, doublereal *), apt081_(doublereal *,
         integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /* ...     CHECK INPUT VALIDITY AND TRANSFORM CANONICAL FORMS */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
     /* Parameter adjustments */
     --p2;
     --p1;
     --result;
     /* Function Body */
     apt081_(&p1[1], &c__0);
     dshar3_1.sc[0] = dshar3_1.p[0];
     dshar3_1.sc[1] = dshar3_1.p[1];
     apt081_(&p2[1], &c__0);
 /* ...     LINE THRU TWO POINTS FROM APT012 */
     apt012_(&result[1], dshar3_1.sc, &dshar3_1.sc[1], dshar3_1.p, &dshar3_1.p[
         1]);
     return 0;
 } /* apt014_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT014.c.
doublereal ahold[8]
Definition at line 18 of file APT014.c.
doublereal c1[8]
Definition at line 18 of file APT014.c.
doublereal c__[7]
Definition at line 25 of file APT014.c.
integer c__0 = 0 static
Definition at line 32 of file APT014.c.
Referenced by apt014_().
struct { ... } def_
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT014.c.
doublereal l[4]
Definition at line 25 of file APT014.c.
doublereal ln1[5]
Definition at line 18 of file APT014.c.
doublereal p[16]
Definition at line 25 of file APT014.c.
doublereal r__[10]
Definition at line 18 of file APT014.c.
doublereal ref[8]
Definition at line 18 of file APT014.c.
doublereal sc[16]
Definition at line 25 of file APT014.c.
doublereal t[12]
Definition at line 25 of file APT014.c.
doublereal t1[12]
Definition at line 25 of file APT014.c.
doublereal v[10]
Definition at line 25 of file APT014.c.