My Project: APT045.c File Reference
APT045.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define ldef_1 ldef_
#define idef_1 idef_
Functions
int apt045_ (doublereal *result, doublereal *pn1, doublereal *pn2, doublereal *pn3)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
static integer c__3 = 3
static integer c__1 = 1
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT045.c.
#define dshar3_1 dshar3_
Definition at line 28 of file APT045.c.
Referenced by apt045_().
#define idef_1 idef_
Definition at line 41 of file APT045.c.
Referenced by apt045_().
#define ldef_1 ldef_
Definition at line 35 of file APT045.c.
Referenced by apt045_().
Function Documentation
int apt045_ (doublereal * result, doublereal * pn1, doublereal * pn2, doublereal * pn3)
Definition at line 76 of file APT045.c.
References apt073_(), c__1, c__3, ckdef_(), defext_(), dshar3_1, i__, idef_1, ldef_1, print_(), and result.
Referenced by xcall_().
 {
     static integer i__;
     extern /* Subroutine */ int apt073_(doublereal *, doublereal *,
         doublereal *, doublereal *);
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int print_(integer *, doublereal *, integer *),
         defext_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
     /* Parameter adjustments */
     --pn3;
     --pn2;
     --pn1;
     --result;
     /* Function Body */
     ldef_1.unflag = ckdef_(&pn2[1]) || ckdef_(&pn3[1]);
 /* ...     VECTORS FROM PN1 TO PN2 AND PN3 */
     for (i__ = 1; i__ <= 3; ++i__) {
     dshar3_1.sc[i__ - 1] = pn1[i__] - pn2[i__];
 /* L10: */
     dshar3_1.sc[i__ + 2] = pn1[i__] - pn3[i__];
     }
 /* ...     USE APT073 TO FIND PLANE CONTAINING VECTORS AND PN1 */
     apt073_(&result[1], dshar3_1.sc, &dshar3_1.sc[3], &pn1[1]);
     if (ldef_1.unflag || idef_1.ierror != 0) {
     defext_(&result[1]);
     }
     if (ldef_1.prnton) {
     print_(&c__3, &result[1], &c__1);
     }
     return 0;
 } /* apt045_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT045.c.
doublereal ahold[8]
Definition at line 18 of file APT045.c.
logical altmlt
Definition at line 31 of file APT045.c.
logical bnderr
Definition at line 31 of file APT045.c.
logical boundf
Definition at line 31 of file APT045.c.
doublereal c1[8]
Definition at line 18 of file APT045.c.
doublereal c__[7]
Definition at line 25 of file APT045.c.
integer c__1 = 1 static
Definition at line 46 of file APT045.c.
Referenced by apt045_().
integer c__3 = 3 static
Definition at line 45 of file APT045.c.
Referenced by apt045_().
logical canflg
Definition at line 31 of file APT045.c.
struct { ... } def_
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT045.c.
integer iblk1
Definition at line 38 of file APT045.c.
struct { ... } idef_
integer ierror
Definition at line 38 of file APT045.c.
logical jcs
Definition at line 31 of file APT045.c.
logical jds
Definition at line 31 of file APT045.c.
integer kwrdsz
Definition at line 38 of file APT045.c.
doublereal l[4]
Definition at line 25 of file APT045.c.
integer ldasiz
Definition at line 38 of file APT045.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file APT045.c.
doublereal p[16]
Definition at line 25 of file APT045.c.
logical pchlst
Definition at line 31 of file APT045.c.
logical prnton
Definition at line 31 of file APT045.c.
doublereal r__[10]
Definition at line 18 of file APT045.c.
doublereal ref[8]
Definition at line 18 of file APT045.c.
logical refflg
Definition at line 31 of file APT045.c.
logical refmot
Definition at line 31 of file APT045.c.
doublereal sc[16]
Definition at line 25 of file APT045.c.
logical subflg
Definition at line 31 of file APT045.c.
integer surfad[4]
Definition at line 38 of file APT045.c.
doublereal t[12]
Definition at line 25 of file APT045.c.
doublereal t1[12]
Definition at line 25 of file APT045.c.
logical tabprt
Definition at line 31 of file APT045.c.
logical unflag
Definition at line 31 of file APT045.c.
doublereal v[10]
Definition at line 25 of file APT045.c.
logical zflag
Definition at line 31 of file APT045.c.