My Project: APT071.c File Reference
APT071.c File Reference
#include "f2c.h"
Macros
#define ldef_1 ldef_
Functions
int apt071_ (doublereal *result, doublereal *pln)
Variables
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
static integer c__3 = 3
static integer c__1 = 1
Macro Definition Documentation
#define ldef_1 ldef_
Definition at line 22 of file APT071.c.
Referenced by apt071_().
Function Documentation
int apt071_ (doublereal * result, doublereal * pln)
Definition at line 50 of file APT071.c.
References c__1, c__3, ckdef_(), error_(), i__, j, ldef_1, print_(), and undef_().
Referenced by xcall_().
 {
     /* System generated locals */
     doublereal d__1, d__2, d__3;
     /* Local variables */
     static integer i__, j;
     static doublereal scc;
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int undef_(doublereal *), error_(integer *, char *
         , ftnlen), print_(integer *, doublereal *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
     /* Parameter adjustments */
     --pln;
     result -= 5;
     /* Function Body */
     if (ckdef_(&pln[1])) {
     goto L99;
     }
     pln[4] = -pln[4];
 /* Computing 2nd power */
     d__1 = pln[1];
 /* Computing 2nd power */
     d__2 = pln[2];
 /* Computing 2nd power */
     d__3 = pln[3];
     scc = d__1 * d__1 + d__2 * d__2 + d__3 * d__3;
     for (i__ = 1; i__ <= 3; ++i__) {
     for (j = 1; j <= 4; ++j) {
         result[j + (i__ << 2)] = pln[i__] * -2. * pln[j] / scc;
         if (i__ == j) {
         result[j + (i__ << 2)] += 1.;
         }
 /* L10: */
     }
     }
     pln[4] = -pln[4];
     if (ldef_1.prnton) {
     print_(&c__3, &result[5], &c__1);
     }
     return 0;
 L99:
     error_(&c__1, "APT071  ", (ftnlen)8);
     undef_(&result[5]);
     return 0;
 } /* apt071_ */
Variable Documentation
logical altmlt
Definition at line 18 of file APT071.c.
logical bnderr
Definition at line 18 of file APT071.c.
logical boundf
Definition at line 18 of file APT071.c.
integer c__1 = 1 static
Definition at line 27 of file APT071.c.
Referenced by apt071_().
integer c__3 = 3 static
Definition at line 26 of file APT071.c.
Referenced by apt071_().
logical canflg
Definition at line 18 of file APT071.c.
logical jcs
Definition at line 18 of file APT071.c.
logical jds
Definition at line 18 of file APT071.c.
struct { ... } ldef_
logical pchlst
Definition at line 18 of file APT071.c.
logical prnton
Definition at line 18 of file APT071.c.
logical refflg
Definition at line 18 of file APT071.c.
logical refmot
Definition at line 18 of file APT071.c.
logical subflg
Definition at line 18 of file APT071.c.
logical tabprt
Definition at line 18 of file APT071.c.
logical unflag
Definition at line 18 of file APT071.c.
logical zflag
Definition at line 18 of file APT071.c.