My Project: APT067.c File Reference
APT067.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define st ((doublereal *)&dshar3_1 + 37)
Functions
int apt067_ (doublereal *result, doublereal *mx)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT067.c.
#define dshar3_1 dshar3_
Definition at line 28 of file APT067.c.
#define st ((doublereal *)&dshar3_1 + 37)
Referenced by apt067_().
#define znumbr_1 znumbr_
Definition at line 36 of file APT067.c.
Referenced by apt067_().
Function Documentation
int apt067_ (doublereal * result, doublereal * mx)
Definition at line 59 of file APT067.c.
References i__, j, st, and znumbr_1.
Referenced by apt065_(), apt068_(), refsys_(), and xcall_().
 {
     /* Local variables */
     static integer i__, j;
 #define st ((doublereal *)&dshar3_1 + 37)
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
     /* Parameter adjustments */
     mx -= 5;
     result -= 5;
     /* Function Body */
     for (i__ = 1; i__ <= 3; ++i__) {
     st[(i__ << 2) - 1] = znumbr_1.z0;
     for (j = 1; j <= 3; ++j) {
         st[j + (i__ << 2) - 5] = mx[i__ + (j << 2)];
 /* L10: */
         st[(i__ << 2) - 1] -= st[j + (i__ << 2) - 5] * mx[(j << 2) + 4];
     }
     }
     for (i__ = 1; i__ <= 4; ++i__) {
     for (j = 1; j <= 3; ++j) {
 /* L20: */
         result[i__ + (j << 2)] = st[i__ + (j << 2) - 5];
     }
     }
     return 0;
 } /* apt067_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT067.c.
doublereal ahold[8]
Definition at line 18 of file APT067.c.
doublereal c1[8]
Definition at line 18 of file APT067.c.
doublereal c__[7]
Definition at line 25 of file APT067.c.
struct { ... } def_
doublereal degrad
Definition at line 31 of file APT067.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT067.c.
doublereal l[4]
Definition at line 25 of file APT067.c.
doublereal ln1[5]
Definition at line 18 of file APT067.c.
doublereal p[16]
Definition at line 25 of file APT067.c.
doublereal pi
Definition at line 31 of file APT067.c.
doublereal r__[10]
Definition at line 18 of file APT067.c.
doublereal ref[8]
Definition at line 18 of file APT067.c.
doublereal sc[16]
Definition at line 25 of file APT067.c.
doublereal t[12]
Definition at line 25 of file APT067.c.
doublereal t1[12]
Definition at line 25 of file APT067.c.
doublereal v[10]
Definition at line 25 of file APT067.c.
doublereal z0
Definition at line 31 of file APT067.c.
doublereal z1
Definition at line 31 of file APT067.c.
doublereal z10
Definition at line 31 of file APT067.c.
doublereal z11em1
Definition at line 31 of file APT067.c.
doublereal z12em1
Definition at line 31 of file APT067.c.
doublereal z1e38
Definition at line 31 of file APT067.c.
doublereal z1e6
Definition at line 31 of file APT067.c.
doublereal z1em1
Definition at line 31 of file APT067.c.
doublereal z1em2
Definition at line 31 of file APT067.c.
doublereal z1em3
Definition at line 31 of file APT067.c.
doublereal z1em5
Definition at line 31 of file APT067.c.
doublereal z1em6
Definition at line 31 of file APT067.c.
doublereal z1em7
Definition at line 31 of file APT067.c.
doublereal z1em9
Definition at line 31 of file APT067.c.
doublereal z2
Definition at line 31 of file APT067.c.
doublereal z3
Definition at line 31 of file APT067.c.
doublereal z5
Definition at line 31 of file APT067.c.
doublereal z5em1
Definition at line 31 of file APT067.c.
doublereal z5em6
Definition at line 31 of file APT067.c.
doublereal z6em1
Definition at line 31 of file APT067.c.
doublereal z90
Definition at line 31 of file APT067.c.
doublereal z9em1
Definition at line 31 of file APT067.c.
doublereal zm1
Definition at line 31 of file APT067.c.
struct { ... } znumbr_