My Project: APT003.c File Reference
APT003.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define idef_1 idef_
#define knumbr_1 knumbr_
Functions
int apt003_ (doublereal *result, doublereal *line1, doublereal *line2)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__2 = 2
static integer c__3 = 3
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT003.c.
#define dshar3_1 dshar3_
Definition at line 28 of file APT003.c.
Referenced by apt003_().
#define idef_1 idef_
Definition at line 42 of file APT003.c.
Referenced by apt003_().
#define knumbr_1 knumbr_
Definition at line 50 of file APT003.c.
Referenced by apt003_().
#define znumbr_1 znumbr_
Definition at line 36 of file APT003.c.
Referenced by apt003_().
Function Documentation
int apt003_ (doublereal * result, doublereal * line1, doublereal * line2)
Definition at line 85 of file APT003.c.
References apt001_(), apt075_(), apt077_(), c__2, c__3, defext_(), dshar3_1, i__, idef_1, knumbr_1, result, and znumbr_1.
Referenced by apt030_(), apt102_(), and xcall_().
 {
     static integer i__;
     static doublereal pll[12]   /* was [4][3] */;
     extern /* Subroutine */ int apt001_(doublereal *), apt075_(doublereal *,
         doublereal *), apt077_(doublereal *, integer *), defext_(
         doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...     TRANSFORM CANONICAL FORM TO LOCAL SYSTEM */
     /* Parameter adjustments */
     --line2;
     --line1;
     --result;
     /* Function Body */
     apt077_(&line1[1], &c__2);
     for (i__ = 1; i__ <= 4; ++i__) {
 /* L10: */
     pll[i__ - 1] = dshar3_1.l[i__ - 1];
     }
     apt077_(&line2[1], &c__3);
     for (i__ = 1; i__ <= 4; ++i__) {
 /* L11: */
     pll[i__ + 3] = dshar3_1.l[i__ - 1];
     }
     pll[8] = znumbr_1.z0;
     pll[9] = znumbr_1.z0;
     pll[10] = znumbr_1.z1;
     pll[11] = znumbr_1.z0;
 /* ....   COMPUTE SIMULTANEOUS SOLUTION OF 3 PLANE EQUATIONS */
     apt075_(&result[1], pll);
     if (idef_1.ierror == knumbr_1.k52) {
     goto L20;
     }
     apt001_(&result[1]);
     goto L30;
 L20:
     idef_1.ierror = knumbr_1.k4;
     defext_(&result[1]);
 L30:
     return 0;
 } /* apt003_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT003.c.
doublereal ahold[8]
Definition at line 18 of file APT003.c.
doublereal c1[8]
Definition at line 18 of file APT003.c.
doublereal c__[7]
Definition at line 25 of file APT003.c.
integer c__2 = 2 static
Definition at line 54 of file APT003.c.
Referenced by apt003_().
integer c__3 = 3 static
Definition at line 55 of file APT003.c.
Referenced by apt003_().
struct { ... } def_
doublereal degrad
Definition at line 31 of file APT003.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT003.c.
integer iblk1
Definition at line 39 of file APT003.c.
struct { ... } idef_
integer ierror
Definition at line 39 of file APT003.c.
integer k0
Definition at line 45 of file APT003.c.
integer k1
Definition at line 45 of file APT003.c.
integer k10
Definition at line 45 of file APT003.c.
integer k1013
Definition at line 45 of file APT003.c.
integer k12
Definition at line 45 of file APT003.c.
integer k13
Definition at line 45 of file APT003.c.
integer k15
Definition at line 45 of file APT003.c.
integer k16
Definition at line 45 of file APT003.c.
integer k18
Definition at line 45 of file APT003.c.
integer k19
Definition at line 45 of file APT003.c.
integer k1e4
Definition at line 45 of file APT003.c.
integer k1e6
Definition at line 45 of file APT003.c.
integer k2
Definition at line 45 of file APT003.c.
integer k23
Definition at line 45 of file APT003.c.
integer k24
Definition at line 45 of file APT003.c.
integer k25
Definition at line 45 of file APT003.c.
integer k26
Definition at line 45 of file APT003.c.
integer k27
Definition at line 45 of file APT003.c.
integer k29
Definition at line 45 of file APT003.c.
integer k3
Definition at line 45 of file APT003.c.
integer k30
Definition at line 45 of file APT003.c.
integer k31
Definition at line 45 of file APT003.c.
integer k32
Definition at line 45 of file APT003.c.
integer k33
Definition at line 45 of file APT003.c.
integer k34
Definition at line 45 of file APT003.c.
integer k4
Definition at line 45 of file APT003.c.
integer k44
Definition at line 45 of file APT003.c.
integer k45
Definition at line 45 of file APT003.c.
integer k46
Definition at line 45 of file APT003.c.
integer k47
Definition at line 45 of file APT003.c.
integer k48
Definition at line 45 of file APT003.c.
integer k5
Definition at line 45 of file APT003.c.
integer k50
Definition at line 45 of file APT003.c.
integer k51
Definition at line 45 of file APT003.c.
integer k52
Definition at line 45 of file APT003.c.
integer k6
Definition at line 45 of file APT003.c.
integer k7
Definition at line 45 of file APT003.c.
integer k8
Definition at line 45 of file APT003.c.
integer k9
Definition at line 45 of file APT003.c.
integer km1
Definition at line 45 of file APT003.c.
struct { ... } knumbr_
integer kwrdsz
Definition at line 39 of file APT003.c.
doublereal l[4]
Definition at line 25 of file APT003.c.
integer ldasiz
Definition at line 39 of file APT003.c.
doublereal ln1[5]
Definition at line 18 of file APT003.c.
doublereal p[16]
Definition at line 25 of file APT003.c.
doublereal pi
Definition at line 31 of file APT003.c.
doublereal r__[10]
Definition at line 18 of file APT003.c.
doublereal ref[8]
Definition at line 18 of file APT003.c.
doublereal sc[16]
Definition at line 25 of file APT003.c.
integer surfad[4]
Definition at line 39 of file APT003.c.
doublereal t[12]
Definition at line 25 of file APT003.c.
doublereal t1[12]
Definition at line 25 of file APT003.c.
doublereal v[10]
Definition at line 25 of file APT003.c.
doublereal z0
Definition at line 31 of file APT003.c.
doublereal z1
Definition at line 31 of file APT003.c.
doublereal z10
Definition at line 31 of file APT003.c.
doublereal z11em1
Definition at line 31 of file APT003.c.
doublereal z12em1
Definition at line 31 of file APT003.c.
doublereal z1e38
Definition at line 31 of file APT003.c.
doublereal z1e6
Definition at line 31 of file APT003.c.
doublereal z1em1
Definition at line 31 of file APT003.c.
doublereal z1em2
Definition at line 31 of file APT003.c.
doublereal z1em3
Definition at line 31 of file APT003.c.
doublereal z1em5
Definition at line 31 of file APT003.c.
doublereal z1em6
Definition at line 31 of file APT003.c.
doublereal z1em7
Definition at line 31 of file APT003.c.
doublereal z1em9
Definition at line 31 of file APT003.c.
doublereal z2
Definition at line 31 of file APT003.c.
doublereal z3
Definition at line 31 of file APT003.c.
doublereal z5
Definition at line 31 of file APT003.c.
doublereal z5em1
Definition at line 31 of file APT003.c.
doublereal z5em6
Definition at line 31 of file APT003.c.
doublereal z6em1
Definition at line 31 of file APT003.c.
doublereal z90
Definition at line 31 of file APT003.c.
doublereal z9em1
Definition at line 31 of file APT003.c.
doublereal zm1
Definition at line 31 of file APT003.c.
struct { ... } znumbr_