My Project: APT073.c File Reference
APT073.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define ldef_1 ldef_
#define idef_1 idef_
#define knumbr_1 knumbr_
Functions
int apt073_ (doublereal *result, doublereal *vt1, doublereal *vt2, doublereal *pt)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT073.c.
#define dshar3_1 dshar3_
Definition at line 28 of file APT073.c.
Referenced by apt073_().
#define idef_1 idef_
Definition at line 41 of file APT073.c.
Referenced by apt073_().
#define knumbr_1 knumbr_
Definition at line 49 of file APT073.c.
Referenced by apt073_().
#define ldef_1 ldef_
Definition at line 35 of file APT073.c.
Referenced by apt073_().
Function Documentation
int apt073_ (doublereal * result, doublereal * vt1, doublereal * vt2, doublereal * pt)
Definition at line 78 of file APT073.c.
References ckdef_(), cross_(), dotf_(), dshar3_1, idef_1, knumbr_1, ldef_1, pt, result, vnorm_(), vt1, and zvect_().
Referenced by apt045_(), apt048_(), and xcall_().
 {
     extern /* Subroutine */ int dotf_(doublereal *, doublereal *, doublereal *
         );
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int cross_(doublereal *, doublereal *, doublereal
         *);
     extern logical zvect_(doublereal *);
     extern /* Subroutine */ int vnorm_(doublereal *, doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --pt;
     --vt2;
     --vt1;
     --result;
     /* Function Body */
     ldef_1.unflag = ldef_1.unflag || ckdef_(&pt[1]);
 /* ...     CALCULATE VECTOR PERPENDICULAR TO VT1, VT2 */
     cross_(&vt1[1], &vt2[1], dshar3_1.v);
     if (! zvect_(dshar3_1.v)) {
     idef_1.ierror = knumbr_1.k51;
     }
     vnorm_(dshar3_1.v, &result[1]);
 /* ...     DISTANCE TO PLANE IS DOT PRODUCT OF PT VECTOR AND UNIT NORMAL */
     dotf_(&result[4], &result[1], &pt[1]);
     return 0;
 } /* apt073_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT073.c.
doublereal ahold[8]
Definition at line 18 of file APT073.c.
logical altmlt
Definition at line 31 of file APT073.c.
logical bnderr
Definition at line 31 of file APT073.c.
logical boundf
Definition at line 31 of file APT073.c.
doublereal c1[8]
Definition at line 18 of file APT073.c.
doublereal c__[7]
Definition at line 25 of file APT073.c.
logical canflg
Definition at line 31 of file APT073.c.
struct { ... } def_
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT073.c.
integer iblk1
Definition at line 38 of file APT073.c.
struct { ... } idef_
integer ierror
Definition at line 38 of file APT073.c.
logical jcs
Definition at line 31 of file APT073.c.
logical jds
Definition at line 31 of file APT073.c.
integer k0
Definition at line 44 of file APT073.c.
integer k1
Definition at line 44 of file APT073.c.
integer k10
Definition at line 44 of file APT073.c.
integer k1013
Definition at line 44 of file APT073.c.
integer k12
Definition at line 44 of file APT073.c.
integer k13
Definition at line 44 of file APT073.c.
integer k15
Definition at line 44 of file APT073.c.
integer k16
Definition at line 44 of file APT073.c.
integer k18
Definition at line 44 of file APT073.c.
integer k19
Definition at line 44 of file APT073.c.
integer k1e4
Definition at line 44 of file APT073.c.
integer k1e6
Definition at line 44 of file APT073.c.
integer k2
Definition at line 44 of file APT073.c.
integer k23
Definition at line 44 of file APT073.c.
integer k24
Definition at line 44 of file APT073.c.
integer k25
Definition at line 44 of file APT073.c.
integer k26
Definition at line 44 of file APT073.c.
integer k27
Definition at line 44 of file APT073.c.
integer k29
Definition at line 44 of file APT073.c.
integer k3
Definition at line 44 of file APT073.c.
integer k30
Definition at line 44 of file APT073.c.
integer k31
Definition at line 44 of file APT073.c.
integer k32
Definition at line 44 of file APT073.c.
integer k33
Definition at line 44 of file APT073.c.
integer k34
Definition at line 44 of file APT073.c.
integer k4
Definition at line 44 of file APT073.c.
integer k44
Definition at line 44 of file APT073.c.
integer k45
Definition at line 44 of file APT073.c.
integer k46
Definition at line 44 of file APT073.c.
integer k47
Definition at line 44 of file APT073.c.
integer k48
Definition at line 44 of file APT073.c.
integer k5
Definition at line 44 of file APT073.c.
integer k50
Definition at line 44 of file APT073.c.
integer k51
Definition at line 44 of file APT073.c.
integer k52
Definition at line 44 of file APT073.c.
integer k6
Definition at line 44 of file APT073.c.
integer k7
Definition at line 44 of file APT073.c.
integer k8
Definition at line 44 of file APT073.c.
integer k9
Definition at line 44 of file APT073.c.
integer km1
Definition at line 44 of file APT073.c.
struct { ... } knumbr_
integer kwrdsz
Definition at line 38 of file APT073.c.
doublereal l[4]
Definition at line 25 of file APT073.c.
integer ldasiz
Definition at line 38 of file APT073.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file APT073.c.
doublereal p[16]
Definition at line 25 of file APT073.c.
logical pchlst
Definition at line 31 of file APT073.c.
logical prnton
Definition at line 31 of file APT073.c.
doublereal r__[10]
Definition at line 18 of file APT073.c.
doublereal ref[8]
Definition at line 18 of file APT073.c.
logical refflg
Definition at line 31 of file APT073.c.
logical refmot
Definition at line 31 of file APT073.c.
doublereal sc[16]
Definition at line 25 of file APT073.c.
logical subflg
Definition at line 31 of file APT073.c.
integer surfad[4]
Definition at line 38 of file APT073.c.
doublereal t[12]
Definition at line 25 of file APT073.c.
doublereal t1[12]
Definition at line 25 of file APT073.c.
logical tabprt
Definition at line 31 of file APT073.c.
logical unflag
Definition at line 31 of file APT073.c.
doublereal v[10]
Definition at line 25 of file APT073.c.
logical zflag
Definition at line 31 of file APT073.c.