My Project: APT065.c File Reference
APT065.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define ldef_1 ldef_
#define knumbr_1 knumbr_
Functions
int apt065_ (doublereal *result, doublereal *pt, doublereal *v1, doublereal *v2)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT065.c.
#define dshar3_1 dshar3_
Definition at line 28 of file APT065.c.
Referenced by apt065_().
#define knumbr_1 knumbr_
Definition at line 43 of file APT065.c.
#define ldef_1 ldef_
Definition at line 35 of file APT065.c.
Referenced by apt065_().
Function Documentation
int apt065_ (doublereal * result, doublereal * pt, doublereal * v1, doublereal * v2)
Definition at line 73 of file APT065.c.
References apt067_(), ckdef_(), cross_(), dotf_(), dshar3_1, j, ldef_1, pt, result, v1, v2, and vnorm_().
Referenced by xcall_().
 {
     static integer j;
     extern /* Subroutine */ int dotf_(doublereal *, doublereal *, doublereal *
         ), apt067_(doublereal *, doublereal *);
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int cross_(doublereal *, doublereal *, doublereal
         *), vnorm_(doublereal *, doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --v2;
     --v1;
     --pt;
     --result;
     /* Function Body */
     ldef_1.unflag = ckdef_(&pt[1]) || ckdef_(&v1[1]) || ckdef_(&v2[1]);
 /* ...     CALCULATE A VECTOR DEFINING Z,Y,X-AXIS */
     cross_(&v1[1], &v2[1], &dshar3_1.t1[8]);
     cross_(&dshar3_1.t1[8], &v1[1], &dshar3_1.t1[4]);
     for (j = 1; j <= 3; ++j) {
 /* L10: */
     dshar3_1.t1[j - 1] = v1[j];
     }
 /* ...  CALCULATE DISTANCES FROM ORIGIN TO YZPLANE,ZXPLANE,AND XYPLANE */
     for (j = 1; j <= 9; j += 4) {
     vnorm_(&dshar3_1.t1[j - 1], &dshar3_1.t1[j - 1]);
     dotf_(&dshar3_1.t1[j + 2], &dshar3_1.t1[j - 1], &pt[1]);
 /* L20: */
     dshar3_1.t1[j + 2] = -dshar3_1.t1[j + 2];
     }
 /* ...     INVERSE MATRIX */
     apt067_(&result[1], dshar3_1.t1);
     return 0;
 } /* apt065_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT065.c.
doublereal ahold[8]
Definition at line 18 of file APT065.c.
logical altmlt
Definition at line 31 of file APT065.c.
logical bnderr
Definition at line 31 of file APT065.c.
logical boundf
Definition at line 31 of file APT065.c.
doublereal c1[8]
Definition at line 18 of file APT065.c.
doublereal c__[7]
Definition at line 25 of file APT065.c.
logical canflg
Definition at line 31 of file APT065.c.
struct { ... } def_
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT065.c.
logical jcs
Definition at line 31 of file APT065.c.
logical jds
Definition at line 31 of file APT065.c.
integer k0
Definition at line 38 of file APT065.c.
integer k1
Definition at line 38 of file APT065.c.
integer k10
Definition at line 38 of file APT065.c.
integer k1013
Definition at line 38 of file APT065.c.
integer k12
Definition at line 38 of file APT065.c.
integer k13
Definition at line 38 of file APT065.c.
integer k15
Definition at line 38 of file APT065.c.
integer k16
Definition at line 38 of file APT065.c.
integer k18
Definition at line 38 of file APT065.c.
integer k19
Definition at line 38 of file APT065.c.
integer k1e4
Definition at line 38 of file APT065.c.
integer k1e6
Definition at line 38 of file APT065.c.
integer k2
Definition at line 38 of file APT065.c.
integer k23
Definition at line 38 of file APT065.c.
integer k24
Definition at line 38 of file APT065.c.
integer k25
Definition at line 38 of file APT065.c.
integer k26
Definition at line 38 of file APT065.c.
integer k27
Definition at line 38 of file APT065.c.
integer k29
Definition at line 38 of file APT065.c.
integer k3
Definition at line 38 of file APT065.c.
integer k30
Definition at line 38 of file APT065.c.
integer k31
Definition at line 38 of file APT065.c.
integer k32
Definition at line 38 of file APT065.c.
integer k33
Definition at line 38 of file APT065.c.
integer k34
Definition at line 38 of file APT065.c.
integer k4
Definition at line 38 of file APT065.c.
integer k44
Definition at line 38 of file APT065.c.
integer k45
Definition at line 38 of file APT065.c.
integer k46
Definition at line 38 of file APT065.c.
integer k47
Definition at line 38 of file APT065.c.
integer k48
Definition at line 38 of file APT065.c.
integer k5
Definition at line 38 of file APT065.c.
integer k50
Definition at line 38 of file APT065.c.
integer k51
Definition at line 38 of file APT065.c.
integer k52
Definition at line 38 of file APT065.c.
integer k6
Definition at line 38 of file APT065.c.
integer k7
Definition at line 38 of file APT065.c.
integer k8
Definition at line 38 of file APT065.c.
integer k9
Definition at line 38 of file APT065.c.
integer km1
Definition at line 38 of file APT065.c.
struct { ... } knumbr_
doublereal l[4]
Definition at line 25 of file APT065.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file APT065.c.
doublereal p[16]
Definition at line 25 of file APT065.c.
logical pchlst
Definition at line 31 of file APT065.c.
logical prnton
Definition at line 31 of file APT065.c.
doublereal r__[10]
Definition at line 18 of file APT065.c.
doublereal ref[8]
Definition at line 18 of file APT065.c.
logical refflg
Definition at line 31 of file APT065.c.
logical refmot
Definition at line 31 of file APT065.c.
doublereal sc[16]
Definition at line 25 of file APT065.c.
logical subflg
Definition at line 31 of file APT065.c.
doublereal t[12]
Definition at line 25 of file APT065.c.
doublereal t1[12]
Definition at line 25 of file APT065.c.
logical tabprt
Definition at line 31 of file APT065.c.
logical unflag
Definition at line 31 of file APT065.c.
doublereal v[10]
Definition at line 25 of file APT065.c.
logical zflag
Definition at line 31 of file APT065.c.