My Project: APT048.c File Reference
APT048.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define ldef_1 ldef_
Functions
int apt048_ (doublereal *result, doublereal *pl, doublereal *pn1, doublereal *pn2)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
static integer c__3 = 3
static integer c__1 = 1
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT048.c.
Referenced by apt048_().
#define dshar3_1 dshar3_
Definition at line 28 of file APT048.c.
#define ldef_1 ldef_
Definition at line 35 of file APT048.c.
Referenced by apt048_().
Function Documentation
int apt048_ (doublereal * result, doublereal * pl, doublereal * pn1, doublereal * pn2)
Definition at line 70 of file APT048.c.
References apt035_(), apt073_(), c__1, c__3, def_1, ldef_1, pl, print_(), and result.
Referenced by xcall_().
 {
     extern /* Subroutine */ int apt035_(doublereal *, doublereal *,
         doublereal *), apt073_(doublereal *, doublereal *, doublereal *,
         doublereal *), print_(integer *, doublereal *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /* ...     DEFINE A VECTOR IN THE DESIRED PLANE */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
     /* Parameter adjustments */
     --pn2;
     --pn1;
     --pl;
     --result;
     /* Function Body */
     apt035_(&def_1.ln1[1], &pn2[1], &pn1[1]);
 /* ...     DEFINE THE PLANE CONTAINING A POINT, THE DEFINED VECTOR, AND A */
 /* ...     NORMAL VECTOR TO THE ORIGINAL PLANE */
     apt073_(&result[1], &pl[1], &def_1.ln1[1], &pn1[1]);
     if (ldef_1.prnton) {
     print_(&c__3, &result[1], &c__1);
     }
     return 0;
 } /* apt048_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT048.c.
doublereal ahold[8]
Definition at line 18 of file APT048.c.
logical altmlt
Definition at line 31 of file APT048.c.
logical bnderr
Definition at line 31 of file APT048.c.
logical boundf
Definition at line 31 of file APT048.c.
doublereal c1[8]
Definition at line 18 of file APT048.c.
doublereal c__[7]
Definition at line 25 of file APT048.c.
integer c__1 = 1 static
Definition at line 40 of file APT048.c.
Referenced by apt048_().
integer c__3 = 3 static
Definition at line 39 of file APT048.c.
Referenced by apt048_().
logical canflg
Definition at line 31 of file APT048.c.
struct { ... } def_
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT048.c.
logical jcs
Definition at line 31 of file APT048.c.
logical jds
Definition at line 31 of file APT048.c.
doublereal l[4]
Definition at line 25 of file APT048.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file APT048.c.
doublereal p[16]
Definition at line 25 of file APT048.c.
logical pchlst
Definition at line 31 of file APT048.c.
logical prnton
Definition at line 31 of file APT048.c.
doublereal r__[10]
Definition at line 18 of file APT048.c.
doublereal ref[8]
Definition at line 18 of file APT048.c.
logical refflg
Definition at line 31 of file APT048.c.
logical refmot
Definition at line 31 of file APT048.c.
doublereal sc[16]
Definition at line 25 of file APT048.c.
logical subflg
Definition at line 31 of file APT048.c.
doublereal t[12]
Definition at line 25 of file APT048.c.
doublereal t1[12]
Definition at line 25 of file APT048.c.
logical tabprt
Definition at line 31 of file APT048.c.
logical unflag
Definition at line 31 of file APT048.c.
doublereal v[10]
Definition at line 25 of file APT048.c.
logical zflag
Definition at line 31 of file APT048.c.