My Project: APT018.c File Reference
APT018.c File Reference
#include "f2c.h"
Macros
#define knumbr_1 knumbr_
Functions
int apt018_ (doublereal *result, doublereal *pnt, doublereal *ln)
Variables
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__92 = 92
Macro Definition Documentation
#define knumbr_1 knumbr_
Definition at line 23 of file APT018.c.
Function Documentation
int apt018_ (doublereal * result, doublereal * pnt, doublereal * ln)
Definition at line 54 of file APT018.c.
References apt046_(), apt077_(), c__92, pnt, and result.
Referenced by xcall_().
 {
     extern /* Subroutine */ int apt046_(doublereal *, doublereal *,
         doublereal *), apt077_(doublereal *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /* ...     CHECK VALIDITY OF LN IN LOCAL SYSTEM */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --ln;
     --pnt;
     --result;
     /* Function Body */
     apt077_(&ln[1], &c__92);
 /* ...     SOLVE FOR PLANE PARLEL TO LN-PLANE  (APT046) */
     apt046_(&result[1], &pnt[1], &ln[1]);
     return 0;
 } /* apt018_ */
Variable Documentation
integer c__92 = 92 static
Definition at line 27 of file APT018.c.
Referenced by apt018_().
integer k0
Definition at line 18 of file APT018.c.
integer k1
Definition at line 18 of file APT018.c.
integer k10
Definition at line 18 of file APT018.c.
integer k1013
Definition at line 18 of file APT018.c.
integer k12
Definition at line 18 of file APT018.c.
integer k13
Definition at line 18 of file APT018.c.
integer k15
Definition at line 18 of file APT018.c.
integer k16
Definition at line 18 of file APT018.c.
integer k18
Definition at line 18 of file APT018.c.
integer k19
Definition at line 18 of file APT018.c.
integer k1e4
Definition at line 18 of file APT018.c.
integer k1e6
Definition at line 18 of file APT018.c.
integer k2
Definition at line 18 of file APT018.c.
integer k23
Definition at line 18 of file APT018.c.
integer k24
Definition at line 18 of file APT018.c.
integer k25
Definition at line 18 of file APT018.c.
integer k26
Definition at line 18 of file APT018.c.
integer k27
Definition at line 18 of file APT018.c.
integer k29
Definition at line 18 of file APT018.c.
integer k3
Definition at line 18 of file APT018.c.
integer k30
Definition at line 18 of file APT018.c.
integer k31
Definition at line 18 of file APT018.c.
integer k32
Definition at line 18 of file APT018.c.
integer k33
Definition at line 18 of file APT018.c.
integer k34
Definition at line 18 of file APT018.c.
integer k4
Definition at line 18 of file APT018.c.
integer k44
Definition at line 18 of file APT018.c.
integer k45
Definition at line 18 of file APT018.c.
integer k46
Definition at line 18 of file APT018.c.
integer k47
Definition at line 18 of file APT018.c.
integer k48
Definition at line 18 of file APT018.c.
integer k5
Definition at line 18 of file APT018.c.
integer k50
Definition at line 18 of file APT018.c.
integer k51
Definition at line 18 of file APT018.c.
integer k52
Definition at line 18 of file APT018.c.
integer k6
Definition at line 18 of file APT018.c.
integer k7
Definition at line 18 of file APT018.c.
integer k8
Definition at line 18 of file APT018.c.
integer k9
Definition at line 18 of file APT018.c.
integer km1
Definition at line 18 of file APT018.c.
struct { ... } knumbr_