My Project: APT004.c File Reference
APT004.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define ldef_1 ldef_
#define idef_1 idef_
#define knumbr_1 knumbr_
Functions
int apt004_ (doublereal *result, integer *mn, doublereal *line1, doublereal *circ1)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT004.c.
#define dshar3_1 dshar3_
Definition at line 28 of file APT004.c.
Referenced by apt004_().
#define idef_1 idef_
Definition at line 49 of file APT004.c.
Referenced by apt004_().
#define knumbr_1 knumbr_
Definition at line 57 of file APT004.c.
Referenced by apt004_().
#define ldef_1 ldef_
Definition at line 43 of file APT004.c.
Referenced by apt004_().
#define znumbr_1 znumbr_
Definition at line 36 of file APT004.c.
Referenced by apt004_().
Function Documentation
int apt004_ (doublereal * result, integer * mn, doublereal * line1, doublereal * circ1)
Definition at line 94 of file APT004.c.
References apt001_(), apt077_(), apt083_(), defext_(), dshar3_1, error_(), idef_1, knumbr_1, ldef_1, m, result, s1, s2, and znumbr_1.
Referenced by apt005_(), apt029_(), apt032_(), apt102_(), and xcall_().
 {
     /* System generated locals */
     doublereal d__1, d__2;
     /* Builtin functions */
     double sqrt(doublereal), d_sign(doublereal *, doublereal *);
     /* Local variables */
     static integer m;
     static doublereal s1, s2;
     extern /* Subroutine */ int apt001_(doublereal *), apt083_(doublereal *,
         integer *), apt077_(doublereal *, integer *), error_(integer *,
         char *, ftnlen), defext_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /* ...     TRANSFORM CANONICAL FORMS AND CHECK INPUT VALIDITY */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --circ1;
     --line1;
     --result;
     /* Function Body */
     apt077_(&line1[1], &knumbr_1.k5);
     apt083_(&circ1[1], &knumbr_1.k7);
     m = *mn;
 /* ...     COMPUTE DISTANCE FROM CENTER TO LINE AND TEST FOR INTERSECTION */
     s1 = dshar3_1.l[3] - dshar3_1.l[0] * dshar3_1.c__[0] - dshar3_1.l[1] *
         dshar3_1.c__[1];
     if ((d__1 = abs(s1) - dshar3_1.c__[6], abs(d__1)) <= znumbr_1.z1em5) {
     goto L270;
     }
     if (abs(s1) - dshar3_1.c__[6] > znumbr_1.z1em5) {
     goto L330;
     }
 /* ...     COMPUTE CHORD LENGTH AND CHECK MODIFIER FOR VALIDITY */
 /* Computing 2nd power */
     d__1 = dshar3_1.c__[6];
 /* Computing 2nd power */
     d__2 = s1;
     s2 = sqrt(d__1 * d__1 - d__2 * d__2);
     switch (m) {
     case 1:  goto L140;
     case 2:  goto L170;
     case 3:  goto L170;
     case 4:  goto L140;
     case 5:  goto L170;
     }
 L140:
     if (dshar3_1.l[1] < 0.) {
     goto L400;
     } else if (dshar3_1.l[1] == 0) {
     goto L150;
     } else {
     goto L410;
     }
 L150:
     error_(&knumbr_1.k8, "APT004  ", (ftnlen)8);
     if (m == knumbr_1.k2 || m == knumbr_1.k3 || m == knumbr_1.k5) {
     goto L330;
     }
 L170:
     if (dshar3_1.l[0] < 0.) {
     goto L410;
     } else if (dshar3_1.l[0] == 0) {
     goto L180;
     } else {
     goto L400;
     }
 L180:
     error_(&knumbr_1.k9, "APT004  ", (ftnlen)8);
     if (m == knumbr_1.k1 || m == knumbr_1.k4) {
     goto L330;
     }
     goto L140;
 /* ...     S(1)=RADIUS,MAKE CHORD LENGTH 0 */
 L270:
     s2 = znumbr_1.z0;
     s1 = d_sign(&dshar3_1.c__[6], &s1);
     goto L430;
 /* ...     LINE AND CIRCLE DO NOT INTERSECT */
 L330:
     idef_1.ierror = knumbr_1.k6;
     ldef_1.unflag = TRUE_;
 /* L300: */
     defext_(&result[1]);
     goto L9999;
 /* ...     COMPUTE X AND Y, STORE IN RESULT AND CALL APT001 TO GET Z */
 L400:
     if (m > knumbr_1.k3) {
     goto L430;
     }
 L420:
     s2 = -s2;
     goto L430;
 L410:
     if (m > knumbr_1.k3) {
     goto L420;
     }
 L430:
     result[1] = dshar3_1.c__[0] + s1 * dshar3_1.l[0] + s2 * dshar3_1.l[1];
     result[2] = dshar3_1.c__[1] + s1 * dshar3_1.l[1] - s2 * dshar3_1.l[0];
     apt001_(&result[1]);
 L9999:
     return 0;
 } /* apt004_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT004.c.
doublereal ahold[8]
Definition at line 18 of file APT004.c.
logical altmlt
Definition at line 39 of file APT004.c.
logical bnderr
Definition at line 39 of file APT004.c.
logical boundf
Definition at line 39 of file APT004.c.
doublereal c1[8]
Definition at line 18 of file APT004.c.
doublereal c__[7]
Definition at line 25 of file APT004.c.
logical canflg
Definition at line 39 of file APT004.c.
struct { ... } def_
doublereal degrad
Definition at line 31 of file APT004.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT004.c.
integer iblk1
Definition at line 46 of file APT004.c.
struct { ... } idef_
integer ierror
Definition at line 46 of file APT004.c.
logical jcs
Definition at line 39 of file APT004.c.
logical jds
Definition at line 39 of file APT004.c.
integer k0
Definition at line 52 of file APT004.c.
integer k1
Definition at line 52 of file APT004.c.
integer k10
Definition at line 52 of file APT004.c.
integer k1013
Definition at line 52 of file APT004.c.
integer k12
Definition at line 52 of file APT004.c.
integer k13
Definition at line 52 of file APT004.c.
integer k15
Definition at line 52 of file APT004.c.
integer k16
Definition at line 52 of file APT004.c.
integer k18
Definition at line 52 of file APT004.c.
integer k19
Definition at line 52 of file APT004.c.
integer k1e4
Definition at line 52 of file APT004.c.
integer k1e6
Definition at line 52 of file APT004.c.
integer k2
Definition at line 52 of file APT004.c.
integer k23
Definition at line 52 of file APT004.c.
integer k24
Definition at line 52 of file APT004.c.
integer k25
Definition at line 52 of file APT004.c.
integer k26
Definition at line 52 of file APT004.c.
integer k27
Definition at line 52 of file APT004.c.
integer k29
Definition at line 52 of file APT004.c.
integer k3
Definition at line 52 of file APT004.c.
integer k30
Definition at line 52 of file APT004.c.
integer k31
Definition at line 52 of file APT004.c.
integer k32
Definition at line 52 of file APT004.c.
integer k33
Definition at line 52 of file APT004.c.
integer k34
Definition at line 52 of file APT004.c.
integer k4
Definition at line 52 of file APT004.c.
integer k44
Definition at line 52 of file APT004.c.
integer k45
Definition at line 52 of file APT004.c.
integer k46
Definition at line 52 of file APT004.c.
integer k47
Definition at line 52 of file APT004.c.
integer k48
Definition at line 52 of file APT004.c.
integer k5
Definition at line 52 of file APT004.c.
integer k50
Definition at line 52 of file APT004.c.
integer k51
Definition at line 52 of file APT004.c.
integer k52
Definition at line 52 of file APT004.c.
integer k6
Definition at line 52 of file APT004.c.
integer k7
Definition at line 52 of file APT004.c.
integer k8
Definition at line 52 of file APT004.c.
integer k9
Definition at line 52 of file APT004.c.
integer km1
Definition at line 52 of file APT004.c.
struct { ... } knumbr_
integer kwrdsz
Definition at line 46 of file APT004.c.
doublereal l[4]
Definition at line 25 of file APT004.c.
integer ldasiz
Definition at line 46 of file APT004.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file APT004.c.
doublereal p[16]
Definition at line 25 of file APT004.c.
logical pchlst
Definition at line 39 of file APT004.c.
doublereal pi
Definition at line 31 of file APT004.c.
logical prnton
Definition at line 39 of file APT004.c.
doublereal r__[10]
Definition at line 18 of file APT004.c.
doublereal ref[8]
Definition at line 18 of file APT004.c.
logical refflg
Definition at line 39 of file APT004.c.
logical refmot
Definition at line 39 of file APT004.c.
doublereal sc[16]
Definition at line 25 of file APT004.c.
logical subflg
Definition at line 39 of file APT004.c.
integer surfad[4]
Definition at line 46 of file APT004.c.
doublereal t[12]
Definition at line 25 of file APT004.c.
doublereal t1[12]
Definition at line 25 of file APT004.c.
logical tabprt
Definition at line 39 of file APT004.c.
logical unflag
Definition at line 39 of file APT004.c.
doublereal v[10]
Definition at line 25 of file APT004.c.
doublereal z0
Definition at line 31 of file APT004.c.
doublereal z1
Definition at line 31 of file APT004.c.
doublereal z10
Definition at line 31 of file APT004.c.
doublereal z11em1
Definition at line 31 of file APT004.c.
doublereal z12em1
Definition at line 31 of file APT004.c.
doublereal z1e38
Definition at line 31 of file APT004.c.
doublereal z1e6
Definition at line 31 of file APT004.c.
doublereal z1em1
Definition at line 31 of file APT004.c.
doublereal z1em2
Definition at line 31 of file APT004.c.
doublereal z1em3
Definition at line 31 of file APT004.c.
doublereal z1em5
Definition at line 31 of file APT004.c.
doublereal z1em6
Definition at line 31 of file APT004.c.
doublereal z1em7
Definition at line 31 of file APT004.c.
doublereal z1em9
Definition at line 31 of file APT004.c.
doublereal z2
Definition at line 31 of file APT004.c.
doublereal z3
Definition at line 31 of file APT004.c.
doublereal z5
Definition at line 31 of file APT004.c.
doublereal z5em1
Definition at line 31 of file APT004.c.
doublereal z5em6
Definition at line 31 of file APT004.c.
doublereal z6em1
Definition at line 31 of file APT004.c.
doublereal z90
Definition at line 31 of file APT004.c.
doublereal z9em1
Definition at line 31 of file APT004.c.
logical zflag
Definition at line 39 of file APT004.c.
doublereal zm1
Definition at line 31 of file APT004.c.
struct { ... } znumbr_