My Project: APT074.c File Reference
APT074.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define ldef_1 ldef_
#define idef_1 idef_
#define knumbr_1 knumbr_
Functions
int apt074_ (doublereal *result, integer *mn, doublereal *pp1, doublereal *pp2, doublereal *pp3, doublereal *pp4, doublereal *pp5)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__71 = 71
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT074.c.
Referenced by apt074_().
#define dshar3_1 dshar3_
Definition at line 28 of file APT074.c.
#define idef_1 idef_
Definition at line 49 of file APT074.c.
Referenced by apt074_().
#define knumbr_1 knumbr_
Definition at line 57 of file APT074.c.
Referenced by apt074_().
#define ldef_1 ldef_
Definition at line 43 of file APT074.c.
Referenced by apt074_().
#define znumbr_1 znumbr_
Definition at line 36 of file APT074.c.
Referenced by apt074_().
Function Documentation
int apt074_ (doublereal * result, integer * mn, doublereal * pp1, doublereal * pp2, doublereal * pp3, doublereal * pp4, doublereal * pp5)
Definition at line 104 of file APT074.c.
References aa, apt079_(), bb, c__71, cc, def_1, defext_(), error_(), i__, idef_1, j, knumbr_1, ldef_1, p1, p2, p3, result, s, transf_(), and znumbr_1.
Referenced by xcall_().
 {
     /* System generated locals */
     doublereal d__1, d__2, d__3;
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     static integer i__, j;
     static doublereal s[4], p1[3], p2[3], p3[3], p4[3], p5[3], aa[4], bb[4],
         cc[4], sr[2], det, div;
     extern /* Subroutine */ int apt079_(doublereal *, integer *), error_(
         integer *, char *, ftnlen), defext_(doublereal *), transf_(
         doublereal *, doublereal *, integer *, integer *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --pp5;
     --pp4;
     --pp3;
     --pp2;
     --pp1;
     --result;
     /* Function Body */
     for (i__ = 1; i__ <= 4; ++i__) {
     switch (i__) {
         case 1:  goto L100;
         case 2:  goto L200;
         case 3:  goto L300;
         case 4:  goto L400;
     }
 L100:
     transf_(p1, &pp1[1], &knumbr_1.k2, &knumbr_1.k3, &knumbr_1.k0);
     if (ldef_1.unflag) {
         goto L910;
     }
     transf_(p3, &pp3[1], &knumbr_1.k2, &knumbr_1.k3, &knumbr_1.k0);
     if (ldef_1.unflag) {
         goto L910;
     }
     transf_(p5, &pp5[1], &knumbr_1.k2, &knumbr_1.k3, &knumbr_1.k0);
     if (ldef_1.unflag) {
         goto L910;
     }
     if (*mn != knumbr_1.k1) {
         goto L110;
     }
     transf_(p2, &pp2[1], &knumbr_1.k2, &knumbr_1.k3, &knumbr_1.k0);
     if (ldef_1.unflag) {
         goto L910;
     }
     sr[0] = p2[1] - p1[1];
     sr[1] = p2[0] - p1[0];
     goto L500;
 /*        4PT1SL OR 3PT2SL FORMAT */
 /*        OBTAIN FIRST SLOPE FROM P2(1), SET P2 = P1 */
 L110:
     s[i__ - 1] = pp2[1];
     p2[0] = p1[0];
     p2[1] = p1[1];
     goto L600;
 L200:
     if (*mn == knumbr_1.k3) {
         goto L210;
     }
     transf_(p4, &pp4[1], &knumbr_1.k2, &knumbr_1.k3, &knumbr_1.k0);
     if (ldef_1.unflag) {
         goto L910;
     }
     sr[0] = p5[1] - p4[1];
     sr[1] = p5[0] - p4[0];
     goto L500;
 /*        3PT2SL FORMAT */
 /*        OBTAIN SECOND SLOPE FROM P4(1), SET P4 = P5 */
 L210:
     s[i__ - 1] = pp4[1];
     for (j = 1; j <= 2; ++j) {
         p4[j - 1] = p3[j - 1];
         p3[j - 1] = p5[j - 1];
 /* L220: */
         p5[j - 1] = p4[j - 1];
     }
     goto L600;
 L300:
     sr[0] = p4[1] - p1[1];
     sr[1] = p4[0] - p1[0];
     goto L500;
 L400:
     sr[0] = p5[1] - p2[1];
     sr[1] = p5[0] - p2[0];
 /*        COMPUTE THE I TH SLOPE, S(I) */
 L500:
     if (sr[0] == znumbr_1.z0 && sr[1] == znumbr_1.z0) {
         goto L900;
     }
     if (abs(sr[0]) > abs(sr[1]) * znumbr_1.z1e6) {
         goto L510;
     }
     s[i__ - 1] = sr[0] / sr[1];
     goto L600;
 L510:
     s[i__ - 1] = sr[0] / abs(sr[0]) * znumbr_1.z1e6;
 /*        COMPUTE COEFFICIENTS AA(I), BB(I), CC(I), OF THE EQUATION */
 /*        OF THE I TH LINE */
 L600:
     div = znumbr_1.z1;
     if ((d__1 = s[i__ - 1], abs(d__1)) > znumbr_1.z1) {
 /* Computing 2nd power */
         d__2 = s[i__ - 1];
         div = sqrt(d__2 * d__2 + znumbr_1.z1);
     }
     aa[i__ - 1] = s[i__ - 1] / div;
     bb[i__ - 1] = znumbr_1.zm1 / div;
     if ((d__1 = bb[i__ - 1], abs(d__1)) < znumbr_1.z1em6) {
         bb[i__ - 1] = znumbr_1.z0;
     }
 /* L620: */
     if (i__ == knumbr_1.k2 || i__ == knumbr_1.k4) {
         goto L630;
     }
     cc[i__ - 1] = -aa[i__ - 1] * p1[0] - bb[i__ - 1] * p1[1];
     goto L700;
 L630:
     cc[i__ - 1] = -aa[i__ - 1] * p5[0] - bb[i__ - 1] * p5[1];
 L700:
     ;
     }
 /*        COMPUTE COEFFICIENTS OF THE QUADRIC EQUATION */
     sr[0] = (aa[2] * p3[0] + bb[2] * p3[1] + cc[2]) * (aa[3] * p3[0] + bb[3] *
          p3[1] + cc[3]);
     sr[1] = -(aa[0] * p3[0] + bb[0] * p3[1] + cc[0]) * (aa[1] * p3[0] + bb[1]
         * p3[1] + cc[1]);
     def_1.r__[0] = sr[0] * aa[0] * aa[1] + sr[1] * aa[2] * aa[3];
     def_1.r__[1] = sr[0] * bb[0] * bb[1] + sr[1] * bb[2] * bb[3];
     def_1.r__[2] = znumbr_1.z0;
     def_1.r__[3] = sr[0] * cc[0] * cc[1] + sr[1] * cc[2] * cc[3];
     def_1.r__[4] = znumbr_1.z0;
     def_1.r__[5] = znumbr_1.z0;
     def_1.r__[6] = znumbr_1.z5em1 * (sr[0] * (bb[0] * aa[1] + aa[0] * bb[1])
         + sr[1] * (bb[2] * aa[3] + aa[2] * bb[3]));
     def_1.r__[7] = znumbr_1.z5em1 * (sr[0] * (cc[0] * aa[1] + aa[0] * cc[1])
         + sr[1] * (cc[2] * aa[3] + aa[2] * cc[3]));
     def_1.r__[8] = znumbr_1.z5em1 * (sr[0] * (cc[0] * bb[1] + bb[0] * cc[1])
         + sr[1] * (cc[2] * bb[3] + bb[2] * cc[3]));
     def_1.r__[9] = znumbr_1.z0;
 /* Computing 2nd power */
     d__1 = def_1.r__[7];
 /* Computing 2nd power */
     d__2 = def_1.r__[6];
 /* Computing 2nd power */
     d__3 = def_1.r__[8];
     det = def_1.r__[0] * def_1.r__[1] * def_1.r__[3] - def_1.r__[1] * (d__1 *
         d__1) - def_1.r__[3] * (d__2 * d__2) - def_1.r__[0] * (d__3 *
         d__3) + def_1.r__[6] * 2 * def_1.r__[7] * def_1.r__[8];
 /*        PRINT WARNING IF THIS IS A DEGENERATE CONIC */
     if (abs(det) < znumbr_1.z1em9) {
     error_(&c__71, "APT074  ", (ftnlen)8);
     }
 /* Computing MAX */
     d__2 = max(def_1.r__[0],def_1.r__[1]), d__2 = max(d__2,def_1.r__[3]),
         d__2 = max(d__2,def_1.r__[6]), d__2 = max(d__2,def_1.r__[7]);
     if ((d__1 = det / max(d__2,def_1.r__[8]), abs(d__1)) < znumbr_1.z1em9 &&
         abs(det) >= znumbr_1.z1em9) {
     error_(&c__71, "APT074  ", (ftnlen)8);
     }
 /*        TRANSFORM TO BASE SYSTEM AND STORE ANSWER IN RESULT */
     apt079_(def_1.r__, &knumbr_1.km1);
 L800:
     defext_(&result[1]);
     return 0;
 /*        ERROR - TWO INPUT POINTS COINCIDE */
 L900:
     idef_1.ierror = 70;
     goto L800;
 /*        ERROR - INPUT POINT IS UNDEFINED */
 L910:
     idef_1.ierror = 69;
     goto L800;
 } /* apt074_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT074.c.
doublereal ahold[8]
Definition at line 18 of file APT074.c.
logical altmlt
Definition at line 39 of file APT074.c.
logical bnderr
Definition at line 39 of file APT074.c.
logical boundf
Definition at line 39 of file APT074.c.
doublereal c1[8]
Definition at line 18 of file APT074.c.
doublereal c__[7]
Definition at line 25 of file APT074.c.
integer c__71 = 71 static
Definition at line 61 of file APT074.c.
Referenced by apt074_().
logical canflg
Definition at line 39 of file APT074.c.
struct { ... } def_
doublereal degrad
Definition at line 31 of file APT074.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT074.c.
integer iblk1
Definition at line 46 of file APT074.c.
struct { ... } idef_
integer ierror
Definition at line 46 of file APT074.c.
logical jcs
Definition at line 39 of file APT074.c.
logical jds
Definition at line 39 of file APT074.c.
integer k0
Definition at line 52 of file APT074.c.
integer k1
Definition at line 52 of file APT074.c.
integer k10
Definition at line 52 of file APT074.c.
integer k1013
Definition at line 52 of file APT074.c.
integer k12
Definition at line 52 of file APT074.c.
integer k13
Definition at line 52 of file APT074.c.
integer k15
Definition at line 52 of file APT074.c.
integer k16
Definition at line 52 of file APT074.c.
integer k18
Definition at line 52 of file APT074.c.
integer k19
Definition at line 52 of file APT074.c.
integer k1e4
Definition at line 52 of file APT074.c.
integer k1e6
Definition at line 52 of file APT074.c.
integer k2
Definition at line 52 of file APT074.c.
integer k23
Definition at line 52 of file APT074.c.
integer k24
Definition at line 52 of file APT074.c.
integer k25
Definition at line 52 of file APT074.c.
integer k26
Definition at line 52 of file APT074.c.
integer k27
Definition at line 52 of file APT074.c.
integer k29
Definition at line 52 of file APT074.c.
integer k3
Definition at line 52 of file APT074.c.
integer k30
Definition at line 52 of file APT074.c.
integer k31
Definition at line 52 of file APT074.c.
integer k32
Definition at line 52 of file APT074.c.
integer k33
Definition at line 52 of file APT074.c.
integer k34
Definition at line 52 of file APT074.c.
integer k4
Definition at line 52 of file APT074.c.
integer k44
Definition at line 52 of file APT074.c.
integer k45
Definition at line 52 of file APT074.c.
integer k46
Definition at line 52 of file APT074.c.
integer k47
Definition at line 52 of file APT074.c.
integer k48
Definition at line 52 of file APT074.c.
integer k5
Definition at line 52 of file APT074.c.
integer k50
Definition at line 52 of file APT074.c.
integer k51
Definition at line 52 of file APT074.c.
integer k52
Definition at line 52 of file APT074.c.
integer k6
Definition at line 52 of file APT074.c.
integer k7
Definition at line 52 of file APT074.c.
integer k8
Definition at line 52 of file APT074.c.
integer k9
Definition at line 52 of file APT074.c.
integer km1
Definition at line 52 of file APT074.c.
struct { ... } knumbr_
integer kwrdsz
Definition at line 46 of file APT074.c.
doublereal l[4]
Definition at line 25 of file APT074.c.
integer ldasiz
Definition at line 46 of file APT074.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file APT074.c.
doublereal p[16]
Definition at line 25 of file APT074.c.
logical pchlst
Definition at line 39 of file APT074.c.
doublereal pi
Definition at line 31 of file APT074.c.
logical prnton
Definition at line 39 of file APT074.c.
doublereal r__[10]
Definition at line 18 of file APT074.c.
doublereal ref[8]
Definition at line 18 of file APT074.c.
logical refflg
Definition at line 39 of file APT074.c.
logical refmot
Definition at line 39 of file APT074.c.
doublereal sc[16]
Definition at line 25 of file APT074.c.
logical subflg
Definition at line 39 of file APT074.c.
integer surfad[4]
Definition at line 46 of file APT074.c.
doublereal t[12]
Definition at line 25 of file APT074.c.
doublereal t1[12]
Definition at line 25 of file APT074.c.
logical tabprt
Definition at line 39 of file APT074.c.
logical unflag
Definition at line 39 of file APT074.c.
doublereal v[10]
Definition at line 25 of file APT074.c.
doublereal z0
Definition at line 31 of file APT074.c.
doublereal z1
Definition at line 31 of file APT074.c.
doublereal z10
Definition at line 31 of file APT074.c.
doublereal z11em1
Definition at line 31 of file APT074.c.
doublereal z12em1
Definition at line 31 of file APT074.c.
doublereal z1e38
Definition at line 31 of file APT074.c.
doublereal z1e6
Definition at line 31 of file APT074.c.
doublereal z1em1
Definition at line 31 of file APT074.c.
doublereal z1em2
Definition at line 31 of file APT074.c.
doublereal z1em3
Definition at line 31 of file APT074.c.
doublereal z1em5
Definition at line 31 of file APT074.c.
doublereal z1em6
Definition at line 31 of file APT074.c.
doublereal z1em7
Definition at line 31 of file APT074.c.
doublereal z1em9
Definition at line 31 of file APT074.c.
doublereal z2
Definition at line 31 of file APT074.c.
doublereal z3
Definition at line 31 of file APT074.c.
doublereal z5
Definition at line 31 of file APT074.c.
doublereal z5em1
Definition at line 31 of file APT074.c.
doublereal z5em6
Definition at line 31 of file APT074.c.
doublereal z6em1
Definition at line 31 of file APT074.c.
doublereal z90
Definition at line 31 of file APT074.c.
doublereal z9em1
Definition at line 31 of file APT074.c.
logical zflag
Definition at line 39 of file APT074.c.
doublereal zm1
Definition at line 31 of file APT074.c.
struct { ... } znumbr_