My Project: APT055.c File Reference
APT055.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define ldef_1 ldef_
#define idef_1 idef_
#define knumbr_1 knumbr_
Functions
int apt055_ (doublereal *result, doublereal *pn, doublereal *ve, doublereal *rad)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT055.c.
Referenced by apt055_().
#define dshar3_1 dshar3_
Definition at line 28 of file APT055.c.
#define idef_1 idef_
Definition at line 41 of file APT055.c.
Referenced by apt055_().
#define knumbr_1 knumbr_
Definition at line 49 of file APT055.c.
#define ldef_1 ldef_
Definition at line 35 of file APT055.c.
Referenced by apt055_().
Function Documentation
int apt055_ (doublereal * result, doublereal * pn, doublereal * ve, doublereal * rad)
Definition at line 80 of file APT055.c.
References apt040_(), ckdef_(), def_1, defext_(), i__, idef_1, ldef_1, result, and zvect_().
Referenced by apt054_(), and xcall_().
 {
     /* Initialized data */
     static integer k58 = 58;
     static integer i__;
     extern /* Subroutine */ int apt040_(doublereal *, doublereal *);
     extern logical ckdef_(doublereal *), zvect_(doublereal *);
     extern /* Subroutine */ int defext_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --ve;
     --pn;
     --result;
     /* Function Body */
 /* ...     CHECK INPUT, MOVE ARGUMENTS */
     for (i__ = 1; i__ <= 3; ++i__) {
     def_1.r__[i__ + 2] = ve[i__];
 /* L10: */
     def_1.r__[i__ - 1] = pn[i__];
     }
     ldef_1.unflag = ckdef_(def_1.r__);
 /* ...     CHECK FOR ZERO VECTOR, NORMALIZE */
     if (! zvect_(&def_1.r__[3])) {
     idef_1.ierror = k58;
     }
     apt040_(&def_1.r__[3], &def_1.r__[3]);
     def_1.r__[6] = *rad;
     defext_(&result[1]);
     return 0;
 } /* apt055_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT055.c.
doublereal ahold[8]
Definition at line 18 of file APT055.c.
logical altmlt
Definition at line 31 of file APT055.c.
logical bnderr
Definition at line 31 of file APT055.c.
logical boundf
Definition at line 31 of file APT055.c.
doublereal c1[8]
Definition at line 18 of file APT055.c.
doublereal c__[7]
Definition at line 25 of file APT055.c.
logical canflg
Definition at line 31 of file APT055.c.
struct { ... } def_
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT055.c.
integer iblk1
Definition at line 38 of file APT055.c.
struct { ... } idef_
integer ierror
Definition at line 38 of file APT055.c.
logical jcs
Definition at line 31 of file APT055.c.
logical jds
Definition at line 31 of file APT055.c.
integer k0
Definition at line 44 of file APT055.c.
integer k1
Definition at line 44 of file APT055.c.
integer k10
Definition at line 44 of file APT055.c.
integer k1013
Definition at line 44 of file APT055.c.
integer k12
Definition at line 44 of file APT055.c.
integer k13
Definition at line 44 of file APT055.c.
integer k15
Definition at line 44 of file APT055.c.
integer k16
Definition at line 44 of file APT055.c.
integer k18
Definition at line 44 of file APT055.c.
integer k19
Definition at line 44 of file APT055.c.
integer k1e4
Definition at line 44 of file APT055.c.
integer k1e6
Definition at line 44 of file APT055.c.
integer k2
Definition at line 44 of file APT055.c.
integer k23
Definition at line 44 of file APT055.c.
integer k24
Definition at line 44 of file APT055.c.
integer k25
Definition at line 44 of file APT055.c.
integer k26
Definition at line 44 of file APT055.c.
integer k27
Definition at line 44 of file APT055.c.
integer k29
Definition at line 44 of file APT055.c.
integer k3
Definition at line 44 of file APT055.c.
integer k30
Definition at line 44 of file APT055.c.
integer k31
Definition at line 44 of file APT055.c.
integer k32
Definition at line 44 of file APT055.c.
integer k33
Definition at line 44 of file APT055.c.
integer k34
Definition at line 44 of file APT055.c.
integer k4
Definition at line 44 of file APT055.c.
integer k44
Definition at line 44 of file APT055.c.
integer k45
Definition at line 44 of file APT055.c.
integer k46
Definition at line 44 of file APT055.c.
integer k47
Definition at line 44 of file APT055.c.
integer k48
Definition at line 44 of file APT055.c.
integer k5
Definition at line 44 of file APT055.c.
integer k50
Definition at line 44 of file APT055.c.
integer k51
Definition at line 44 of file APT055.c.
integer k52
Definition at line 44 of file APT055.c.
integer k6
Definition at line 44 of file APT055.c.
integer k7
Definition at line 44 of file APT055.c.
integer k8
Definition at line 44 of file APT055.c.
integer k9
Definition at line 44 of file APT055.c.
integer km1
Definition at line 44 of file APT055.c.
struct { ... } knumbr_
integer kwrdsz
Definition at line 38 of file APT055.c.
doublereal l[4]
Definition at line 25 of file APT055.c.
integer ldasiz
Definition at line 38 of file APT055.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file APT055.c.
doublereal p[16]
Definition at line 25 of file APT055.c.
logical pchlst
Definition at line 31 of file APT055.c.
logical prnton
Definition at line 31 of file APT055.c.
doublereal r__[10]
Definition at line 18 of file APT055.c.
doublereal ref[8]
Definition at line 18 of file APT055.c.
logical refflg
Definition at line 31 of file APT055.c.
logical refmot
Definition at line 31 of file APT055.c.
doublereal sc[16]
Definition at line 25 of file APT055.c.
logical subflg
Definition at line 31 of file APT055.c.
integer surfad[4]
Definition at line 38 of file APT055.c.
doublereal t[12]
Definition at line 25 of file APT055.c.
doublereal t1[12]
Definition at line 25 of file APT055.c.
logical tabprt
Definition at line 31 of file APT055.c.
logical unflag
Definition at line 31 of file APT055.c.
doublereal v[10]
Definition at line 25 of file APT055.c.
logical zflag
Definition at line 31 of file APT055.c.