My Project: APT087.c File Reference
APT087.c File Reference
#include "f2c.h"
Macros
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define ldef_1 ldef_
Functions
int apt087_ (doublereal *result, doublereal *rect)
Variables
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
Macro Definition Documentation
#define dshar3_1 dshar3_
Definition at line 21 of file APT087.c.
Referenced by apt087_().
#define ldef_1 ldef_
Definition at line 36 of file APT087.c.
Referenced by apt087_().
#define znumbr_1 znumbr_
Definition at line 29 of file APT087.c.
Referenced by apt087_().
Function Documentation
int apt087_ (doublereal * result, doublereal * rect)
Definition at line 61 of file APT087.c.
References ckdef_(), dshar3_1, ldef_1, result, and znumbr_1.
Referenced by apt089_(), and xcall_().
 {
     /* System generated locals */
     doublereal d__1, d__2;
     /* Builtin functions */
     double sqrt(doublereal), atan2(doublereal, doublereal);
     /* Local variables */
     extern logical ckdef_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /* ...     CHANGE RECTANGULAR COORDINATES TO POLAR - RESULT(1)=RAD, */
 /*        RESULT(2) = ANGLE */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
     /* Parameter adjustments */
     --rect;
     --result;
     /* Function Body */
     dshar3_1.sc[0] = rect[1];
     dshar3_1.sc[1] = rect[2];
     ldef_1.unflag = ckdef_(dshar3_1.sc);
 /* Computing 2nd power */
     d__1 = dshar3_1.sc[0];
 /* Computing 2nd power */
     d__2 = dshar3_1.sc[1];
     result[1] = sqrt(d__1 * d__1 + d__2 * d__2);
     result[2] = znumbr_1.z0;
     if (result[1] != znumbr_1.z0) {
     result[2] = atan2(dshar3_1.sc[1], dshar3_1.sc[0]) / znumbr_1.degrad;
     }
     return 0;
 } /* apt087_ */
Variable Documentation
logical altmlt
Definition at line 32 of file APT087.c.
logical bnderr
Definition at line 32 of file APT087.c.
logical boundf
Definition at line 32 of file APT087.c.
doublereal c__[7]
Definition at line 18 of file APT087.c.
logical canflg
Definition at line 32 of file APT087.c.
doublereal degrad
Definition at line 24 of file APT087.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 18 of file APT087.c.
logical jcs
Definition at line 32 of file APT087.c.
logical jds
Definition at line 32 of file APT087.c.
doublereal l[4]
Definition at line 18 of file APT087.c.
struct { ... } ldef_
doublereal p[16]
Definition at line 18 of file APT087.c.
logical pchlst
Definition at line 32 of file APT087.c.
doublereal pi
Definition at line 24 of file APT087.c.
logical prnton
Definition at line 32 of file APT087.c.
logical refflg
Definition at line 32 of file APT087.c.
logical refmot
Definition at line 32 of file APT087.c.
doublereal sc[16]
Definition at line 18 of file APT087.c.
logical subflg
Definition at line 32 of file APT087.c.
doublereal t[12]
Definition at line 18 of file APT087.c.
doublereal t1[12]
Definition at line 18 of file APT087.c.
logical tabprt
Definition at line 32 of file APT087.c.
logical unflag
Definition at line 32 of file APT087.c.
doublereal v[10]
Definition at line 18 of file APT087.c.
doublereal z0
Definition at line 24 of file APT087.c.
doublereal z1
Definition at line 24 of file APT087.c.
doublereal z10
Definition at line 24 of file APT087.c.
doublereal z11em1
Definition at line 24 of file APT087.c.
doublereal z12em1
Definition at line 24 of file APT087.c.
doublereal z1e38
Definition at line 24 of file APT087.c.
doublereal z1e6
Definition at line 24 of file APT087.c.
doublereal z1em1
Definition at line 24 of file APT087.c.
doublereal z1em2
Definition at line 24 of file APT087.c.
doublereal z1em3
Definition at line 24 of file APT087.c.
doublereal z1em5
Definition at line 24 of file APT087.c.
doublereal z1em6
Definition at line 24 of file APT087.c.
doublereal z1em7
Definition at line 24 of file APT087.c.
doublereal z1em9
Definition at line 24 of file APT087.c.
doublereal z2
Definition at line 24 of file APT087.c.
doublereal z3
Definition at line 24 of file APT087.c.
doublereal z5
Definition at line 24 of file APT087.c.
doublereal z5em1
Definition at line 24 of file APT087.c.
doublereal z5em6
Definition at line 24 of file APT087.c.
doublereal z6em1
Definition at line 24 of file APT087.c.
doublereal z90
Definition at line 24 of file APT087.c.
doublereal z9em1
Definition at line 24 of file APT087.c.
logical zflag
Definition at line 32 of file APT087.c.
doublereal zm1
Definition at line 24 of file APT087.c.
struct { ... } znumbr_