My Project: APT046.c File Reference
APT046.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define ldef_1 ldef_
#define idef_1 idef_
Functions
int apt046_ (doublereal *result, doublereal *pn, doublereal *pl)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT046.c.
Referenced by apt046_().
#define dshar3_1 dshar3_
Definition at line 28 of file APT046.c.
#define idef_1 idef_
Definition at line 41 of file APT046.c.
#define ldef_1 ldef_
Definition at line 35 of file APT046.c.
Referenced by apt046_().
Function Documentation
int apt046_ (doublereal * result, doublereal * pn, doublereal * pl)
Definition at line 68 of file APT046.c.
References ckdef_(), def_1, defext_(), i__, ldef_1, pl, result, and vnorm_().
Referenced by apt018_(), and xcall_().
 {
     static integer i__;
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int vnorm_(doublereal *, doublereal *), defext_(
         doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
     /* Parameter adjustments */
     --pl;
     --pn;
     --result;
     /* Function Body */
     ldef_1.unflag = ckdef_(&pn[1]) || ckdef_(&pl[1]);
 /* ...     COMPUTE NORMAL DISTANCE TO DESIRED PLANE */
     vnorm_(&pl[1], def_1.r__);
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L10: */
     def_1.r__[3] += def_1.r__[i__ - 1] * pn[i__];
     }
     defext_(&result[1]);
     return 0;
 } /* apt046_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT046.c.
doublereal ahold[8]
Definition at line 18 of file APT046.c.
logical altmlt
Definition at line 31 of file APT046.c.
logical bnderr
Definition at line 31 of file APT046.c.
logical boundf
Definition at line 31 of file APT046.c.
doublereal c1[8]
Definition at line 18 of file APT046.c.
doublereal c__[7]
Definition at line 25 of file APT046.c.
logical canflg
Definition at line 31 of file APT046.c.
struct { ... } def_
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT046.c.
integer iblk1
Definition at line 38 of file APT046.c.
struct { ... } idef_
integer ierror
Definition at line 38 of file APT046.c.
logical jcs
Definition at line 31 of file APT046.c.
logical jds
Definition at line 31 of file APT046.c.
integer kwrdsz
Definition at line 38 of file APT046.c.
doublereal l[4]
Definition at line 25 of file APT046.c.
integer ldasiz
Definition at line 38 of file APT046.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file APT046.c.
doublereal p[16]
Definition at line 25 of file APT046.c.
logical pchlst
Definition at line 31 of file APT046.c.
logical prnton
Definition at line 31 of file APT046.c.
doublereal r__[10]
Definition at line 18 of file APT046.c.
doublereal ref[8]
Definition at line 18 of file APT046.c.
logical refflg
Definition at line 31 of file APT046.c.
logical refmot
Definition at line 31 of file APT046.c.
doublereal sc[16]
Definition at line 25 of file APT046.c.
logical subflg
Definition at line 31 of file APT046.c.
integer surfad[4]
Definition at line 38 of file APT046.c.
doublereal t[12]
Definition at line 25 of file APT046.c.
doublereal t1[12]
Definition at line 25 of file APT046.c.
logical tabprt
Definition at line 31 of file APT046.c.
logical unflag
Definition at line 31 of file APT046.c.
doublereal v[10]
Definition at line 25 of file APT046.c.
logical zflag
Definition at line 31 of file APT046.c.