My Project: APT025.c File Reference
APT025.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define knumbr_1 knumbr_
Functions
int apt025_ (doublereal *result, doublereal *pnt, doublereal *ln)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__28 = 28
static integer c__0 = 0
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT025.c.
Referenced by apt025_().
#define dshar3_1 dshar3_
Definition at line 28 of file APT025.c.
Referenced by apt025_().
#define knumbr_1 knumbr_
Definition at line 36 of file APT025.c.
Referenced by apt025_().
Function Documentation
int apt025_ (doublereal * result, doublereal * pnt, doublereal * ln)
Definition at line 72 of file APT025.c.
References apt077_(), apt081_(), apt083_(), c__0, c__28, def_1, defext_(), dshar3_1, knumbr_1, pnt, and result.
Referenced by xcall_().
 {
     /* System generated locals */
     doublereal d__1;
     /* Local variables */
     extern /* Subroutine */ int apt081_(doublereal *, integer *), apt083_(
         doublereal *, integer *), apt077_(doublereal *, integer *),
         defext_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /* ...     TRANSFORM PNT,LN, CHECK FOR VALIDITY */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --ln;
     --pnt;
     --result;
     /* Function Body */
     apt077_(&ln[1], &c__28);
     apt081_(&pnt[1], &c__0);
 /* ...     DEFINE VERTICAL CYLINDER WITH CENTER PNT,RADIUS DIST TO LN */
     def_1.r__[0] = dshar3_1.p[0];
     def_1.r__[1] = dshar3_1.p[1];
     def_1.r__[6] = (d__1 = dshar3_1.l[3] - dshar3_1.l[0] * def_1.r__[0] -
         dshar3_1.l[1] * def_1.r__[1], abs(d__1));
     apt083_(def_1.r__, &knumbr_1.km1);
 /* L20: */
     defext_(&result[1]);
     return 0;
 } /* apt025_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT025.c.
doublereal ahold[8]
Definition at line 18 of file APT025.c.
doublereal c1[8]
Definition at line 18 of file APT025.c.
doublereal c__[7]
Definition at line 25 of file APT025.c.
integer c__0 = 0 static
Definition at line 41 of file APT025.c.
Referenced by apt025_().
integer c__28 = 28 static
Definition at line 40 of file APT025.c.
Referenced by apt025_().
struct { ... } def_
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT025.c.
integer k0
Definition at line 31 of file APT025.c.
integer k1
Definition at line 31 of file APT025.c.
integer k10
Definition at line 31 of file APT025.c.
integer k1013
Definition at line 31 of file APT025.c.
integer k12
Definition at line 31 of file APT025.c.
integer k13
Definition at line 31 of file APT025.c.
integer k15
Definition at line 31 of file APT025.c.
integer k16
Definition at line 31 of file APT025.c.
integer k18
Definition at line 31 of file APT025.c.
integer k19
Definition at line 31 of file APT025.c.
integer k1e4
Definition at line 31 of file APT025.c.
integer k1e6
Definition at line 31 of file APT025.c.
integer k2
Definition at line 31 of file APT025.c.
integer k23
Definition at line 31 of file APT025.c.
integer k24
Definition at line 31 of file APT025.c.
integer k25
Definition at line 31 of file APT025.c.
integer k26
Definition at line 31 of file APT025.c.
integer k27
Definition at line 31 of file APT025.c.
integer k29
Definition at line 31 of file APT025.c.
integer k3
Definition at line 31 of file APT025.c.
integer k30
Definition at line 31 of file APT025.c.
integer k31
Definition at line 31 of file APT025.c.
integer k32
Definition at line 31 of file APT025.c.
integer k33
Definition at line 31 of file APT025.c.
integer k34
Definition at line 31 of file APT025.c.
integer k4
Definition at line 31 of file APT025.c.
integer k44
Definition at line 31 of file APT025.c.
integer k45
Definition at line 31 of file APT025.c.
integer k46
Definition at line 31 of file APT025.c.
integer k47
Definition at line 31 of file APT025.c.
integer k48
Definition at line 31 of file APT025.c.
integer k5
Definition at line 31 of file APT025.c.
integer k50
Definition at line 31 of file APT025.c.
integer k51
Definition at line 31 of file APT025.c.
integer k52
Definition at line 31 of file APT025.c.
integer k6
Definition at line 31 of file APT025.c.
integer k7
Definition at line 31 of file APT025.c.
integer k8
Definition at line 31 of file APT025.c.
integer k9
Definition at line 31 of file APT025.c.
integer km1
Definition at line 31 of file APT025.c.
struct { ... } knumbr_
doublereal l[4]
Definition at line 25 of file APT025.c.
doublereal ln1[5]
Definition at line 18 of file APT025.c.
doublereal p[16]
Definition at line 25 of file APT025.c.
doublereal r__[10]
Definition at line 18 of file APT025.c.
doublereal ref[8]
Definition at line 18 of file APT025.c.
doublereal sc[16]
Definition at line 25 of file APT025.c.
doublereal t[12]
Definition at line 25 of file APT025.c.
doublereal t1[12]
Definition at line 25 of file APT025.c.
doublereal v[10]
Definition at line 25 of file APT025.c.