My Project: APT011.c File Reference
APT011.c File Reference
#include "f2c.h"
Macros
#define _BLNK__1 _BLNK__
#define def_1 def_
#define dshar3_1 dshar3_
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define ldef_1 ldef_
#define isv_1 isv_
#define isv1_1 isv1_
#define idef_1 idef_
#define ifxcor_1 ifxcor_
#define knumbr_1 knumbr_
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int apt011_ (doublereal *result, doublereal *lin, doublereal *tab, doublereal *pt)
Variables
struct {
doublereal com [36000]
} _BLNK__
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__3 = 3
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 21 of file APT011.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
Referenced by apt011_().
#define def_1 def_
Definition at line 28 of file APT011.c.
#define dshar3_1 dshar3_
Definition at line 34 of file APT011.c.
Referenced by apt011_().
#define idef_1 idef_
Definition at line 97 of file APT011.c.
Referenced by apt011_().
#define ifxcor_1 ifxcor_
Definition at line 107 of file APT011.c.
Referenced by apt011_().
#define isv1_1 isv1_
Definition at line 91 of file APT011.c.
#define isv_1 isv_
Definition at line 84 of file APT011.c.
Referenced by apt011_().
#define knumbr_1 knumbr_
Definition at line 115 of file APT011.c.
Referenced by apt011_().
#define ldef_1 ldef_
Definition at line 75 of file APT011.c.
Referenced by apt011_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define sv1_1 sv1_
Definition at line 60 of file APT011.c.
#define sv_1 sv_
Definition at line 51 of file APT011.c.
Referenced by apt011_().
#define znumbr_1 znumbr_
Definition at line 68 of file APT011.c.
Referenced by apt011_().
Function Documentation
int apt011_ (doublereal * result, doublereal * lin, doublereal * tab, doublereal * pt)
Definition at line 154 of file APT011.c.
References apt001_(), apt094_(), c__3, canon, ckdef_(), ddtabc_(), dshar3_1, i__, idef_1, ifxcor_1, isv_1, j11, knumbr_1, ldef_1, lindef_(), pt, result, schtb_(), sv_1, tab, and znumbr_1.
Referenced by apt034_(), and xcall_().
 {
     /* Local variables */
     static integer i__, j11, m11, l11;
 #define can ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int apt001_(doublereal *), apt094_(integer *,
         doublereal *, integer *);
     static integer iabcl;
     extern logical ckdef_(doublereal *);
 #define canon ((doublereal *)&_BLNK__1)
     extern /* Subroutine */ int schtb_(doublereal *);
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int ddtabc_(doublereal *);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern logical lindef_(doublereal *, integer *);
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /* ...     TRANSFER ARRAYS, CHECK INPUT */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --pt;
     --tab;
     --lin;
     --result;
     /* Function Body */
     iabcl = 0;
     if (ldef_1.subflg) {
     iabcl = 1;
     }
     for (i__ = 1; i__ <= 2; ++i__) {
     dshar3_1.p[i__ - 1] = pt[i__];
     dshar3_1.l[i__ - 1] = lin[i__];
 /* L10: */
     dshar3_1.v[i__ - 1] = tab[i__];
     }
     dshar3_1.l[2] = lin[3];
     dshar3_1.l[3] = lin[4];
     ldef_1.unflag = lindef_(dshar3_1.l, &knumbr_1.k5) || ckdef_(dshar3_1.p) ||
          ckdef_(dshar3_1.v);
     if (ldef_1.unflag) {
     return 0;
     }
 /* ... RETRIEVE TABCYL EXTERNAL CANONICAL FORM. STORE CANON INDEX IN J11. */
     apt094_(&c__3, &tab[1], &j11);
     if (ckdef_(&tab[1])) {
     goto L99;
     }
 /* ...     FIND PART OF TABCYL CLOSEST TO INPUT POINT P, USING SCHTB */
     schtb_(&canon[j11 - 2]);
 /* ...     CONSIDER TABCYL AS A CHECK SURFACE, LINE AS TOOL NORMAL, */
 /* ...     DESIRED POINT AS SURFACE POINT -USE DDTABC TO FIND SP */
     m11 = ifxcor_1.is;
     ifxcor_1.is = ifxcor_1.ics;
     for (i__ = 1; i__ <= 3; ++i__) {
     dshar3_1.sc[i__ - 1] = sv_1.tn[i__ + ifxcor_1.ics * 3 - 4];
     dshar3_1.sc[i__ + 2] = sv_1.tp[i__ + ifxcor_1.ics * 3 - 4];
 /* L30: */
     sv_1.tp[i__ + ifxcor_1.ics * 3 - 4] = dshar3_1.l[i__ - 1] *
         dshar3_1.l[3];
     }
     sv_1.tn[ifxcor_1.ics * 3 - 3] = dshar3_1.l[1];
     sv_1.tn[ifxcor_1.ics * 3 - 2] = -dshar3_1.l[0];
     sv_1.tn[ifxcor_1.ics * 3 - 1] = znumbr_1.z0;
     l11 = isv_1.iop[ifxcor_1.ics - 1];
     isv_1.iop[ifxcor_1.ics - 1] = 0;
     ldef_1.subflg = TRUE_;
     ddtabc_(&canon[j11 - 2]);
     if (ifxcor_1.ier != knumbr_1.k0) {
     idef_1.ierror = 72;
     }
     result[1] = sv_1.sp[ifxcor_1.ics * 3 - 3];
     result[2] = sv_1.sp[ifxcor_1.ics * 3 - 2];
 /* ...     GET THIRD COORDINATE */
     if (iabcl == 1) {
     goto L88;
     }
     apt001_(&result[1]);
 L88:
     ifxcor_1.ier = 0;
     ifxcor_1.is = m11;
     isv_1.iop[ifxcor_1.ics - 1] = l11;
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tn[i__ + ifxcor_1.ics * 3 - 4] = dshar3_1.sc[i__ - 1];
 /* L40: */
     sv_1.tp[i__ + ifxcor_1.ics * 3 - 4] = dshar3_1.sc[i__ + 2];
     }
     ldef_1.subflg = FALSE_;
 L99:
     return 0;
 } /* apt011_ */
Variable Documentation
struct { ... } _BLNK__
doublereal a[24]
Definition at line 24 of file APT011.c.
doublereal ahold[8]
Definition at line 24 of file APT011.c.
logical altmlt
Definition at line 71 of file APT011.c.
logical bnderr
Definition at line 71 of file APT011.c.
logical boundf
Definition at line 71 of file APT011.c.
doublereal c1[8]
Definition at line 24 of file APT011.c.
doublereal c__[7]
Definition at line 31 of file APT011.c.
integer c__3 = 3 static
Definition at line 119 of file APT011.c.
Referenced by apt011_().
logical canflg
Definition at line 71 of file APT011.c.
doublereal cc[15]
Definition at line 37 of file APT011.c.
doublereal com[36000]
Definition at line 18 of file APT011.c.
doublereal cos1[5]
Definition at line 54 of file APT011.c.
doublereal cplfl[5]
Definition at line 54 of file APT011.c.
doublereal cptst[5]
Definition at line 54 of file APT011.c.
doublereal csd[5]
Definition at line 54 of file APT011.c.
struct { ... } def_
doublereal degrad
Definition at line 63 of file APT011.c.
doublereal dplan[15]
Definition at line 54 of file APT011.c.
doublereal dpmx1[5]
Definition at line 54 of file APT011.c.
struct { ... } dshar3_
doublereal eps1[5]
Definition at line 37 of file APT011.c.
doublereal eps2[5]
Definition at line 37 of file APT011.c.
doublereal eps3[5]
Definition at line 37 of file APT011.c.
doublereal eps4[5]
Definition at line 37 of file APT011.c.
doublereal eps6[5]
Definition at line 37 of file APT011.c.
doublereal eps8[5]
Definition at line 37 of file APT011.c.
doublereal g[10]
Definition at line 31 of file APT011.c.
integer i3dflg
Definition at line 100 of file APT011.c.
integer iaerr
Definition at line 100 of file APT011.c.
integer iafl[5]
Definition at line 78 of file APT011.c.
integer iautps
Definition at line 100 of file APT011.c.
integer ibegin
Definition at line 100 of file APT011.c.
integer iblk1
Definition at line 94 of file APT011.c.
integer ic
Definition at line 100 of file APT011.c.
integer icanon[5]
Definition at line 78 of file APT011.c.
integer icheck
Definition at line 100 of file APT011.c.
integer icl
Definition at line 100 of file APT011.c.
integer ics
Definition at line 100 of file APT011.c.
integer icscnt
Definition at line 100 of file APT011.c.
integer ictdef
Definition at line 100 of file APT011.c.
integer icut
Definition at line 100 of file APT011.c.
struct { ... } idef_
integer ids
Definition at line 100 of file APT011.c.
integer ier
Definition at line 100 of file APT011.c.
integer ierror
Definition at line 94 of file APT011.c.
integer ifar[5]
Definition at line 87 of file APT011.c.
integer ifl4[5]
Definition at line 87 of file APT011.c.
struct { ... } ifxcor_
integer igo
Definition at line 100 of file APT011.c.
integer igoto
Definition at line 100 of file APT011.c.
integer igoug
Definition at line 100 of file APT011.c.
integer igs
Definition at line 100 of file APT011.c.
integer index[5]
Definition at line 78 of file APT011.c.
integer indir__[5]
Definition at line 78 of file APT011.c.
integer inops
Definition at line 100 of file APT011.c.
integer iop[5]
Definition at line 78 of file APT011.c.
integer iopset[5]
Definition at line 78 of file APT011.c.
integer ipl[5]
Definition at line 78 of file APT011.c.
integer ips
Definition at line 100 of file APT011.c.
integer ipsdef
Definition at line 100 of file APT011.c.
integer ipt1
Definition at line 100 of file APT011.c.
integer is
Definition at line 100 of file APT011.c.
integer iseg
Definition at line 100 of file APT011.c.
integer iseqno
Definition at line 100 of file APT011.c.
integer isfidn[5]
Definition at line 78 of file APT011.c.
integer isftyp[5]
Definition at line 78 of file APT011.c.
integer isigcr[5]
Definition at line 78 of file APT011.c.
integer isrch
Definition at line 100 of file APT011.c.
integer istrup
Definition at line 100 of file APT011.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 78 of file APT011.c.
integer it
Definition at line 100 of file APT011.c.
integer itlon[5]
Definition at line 78 of file APT011.c.
integer itseg[5]
Definition at line 78 of file APT011.c.
integer itsegk[5]
Definition at line 78 of file APT011.c.
integer iunfl[5]
Definition at line 78 of file APT011.c.
integer j20[5]
Definition at line 87 of file APT011.c.
integer j21[5]
Definition at line 87 of file APT011.c.
integer j22[5]
Definition at line 87 of file APT011.c.
integer j23[5]
Definition at line 87 of file APT011.c.
integer j50[5]
Definition at line 87 of file APT011.c.
integer j51[5]
Definition at line 87 of file APT011.c.
integer jbr
Definition at line 100 of file APT011.c.
logical jcs
Definition at line 71 of file APT011.c.
logical jds
Definition at line 71 of file APT011.c.
integer jent[5]
Definition at line 78 of file APT011.c.
integer jiops[5]
Definition at line 78 of file APT011.c.
integer jph[5]
Definition at line 87 of file APT011.c.
integer jsw
Definition at line 100 of file APT011.c.
integer jtlflg[5]
Definition at line 78 of file APT011.c.
integer jtn[5]
Definition at line 78 of file APT011.c.
integer ju1[5]
Definition at line 78 of file APT011.c.
integer k0
Definition at line 110 of file APT011.c.
integer k1
Definition at line 110 of file APT011.c.
integer k10
Definition at line 110 of file APT011.c.
integer k1013
Definition at line 110 of file APT011.c.
integer k12
Definition at line 110 of file APT011.c.
integer k13
Definition at line 110 of file APT011.c.
integer k15
Definition at line 110 of file APT011.c.
integer k16
Definition at line 110 of file APT011.c.
integer k18
Definition at line 110 of file APT011.c.
integer k19
Definition at line 110 of file APT011.c.
integer k1e4
Definition at line 110 of file APT011.c.
integer k1e6
Definition at line 110 of file APT011.c.
integer k2
Definition at line 110 of file APT011.c.
integer k23
Definition at line 110 of file APT011.c.
integer k24
Definition at line 110 of file APT011.c.
integer k25
Definition at line 110 of file APT011.c.
integer k26
Definition at line 110 of file APT011.c.
integer k27
Definition at line 110 of file APT011.c.
integer k29
Definition at line 110 of file APT011.c.
integer k3
Definition at line 110 of file APT011.c.
integer k30
Definition at line 110 of file APT011.c.
integer k31
Definition at line 110 of file APT011.c.
integer k32
Definition at line 110 of file APT011.c.
integer k33
Definition at line 110 of file APT011.c.
integer k34
Definition at line 110 of file APT011.c.
integer k4
Definition at line 110 of file APT011.c.
integer k44
Definition at line 110 of file APT011.c.
integer k45
Definition at line 110 of file APT011.c.
integer k46
Definition at line 110 of file APT011.c.
integer k47
Definition at line 110 of file APT011.c.
integer k48
Definition at line 110 of file APT011.c.
integer k5
Definition at line 110 of file APT011.c.
integer k50
Definition at line 110 of file APT011.c.
integer k51
Definition at line 110 of file APT011.c.
integer k52
Definition at line 110 of file APT011.c.
integer k6
Definition at line 110 of file APT011.c.
integer k7
Definition at line 110 of file APT011.c.
integer k8
Definition at line 110 of file APT011.c.
integer k9
Definition at line 110 of file APT011.c.
integer km1
Definition at line 110 of file APT011.c.
struct { ... } knumbr_
integer kwrdsz
Definition at line 94 of file APT011.c.
doublereal l[4]
Definition at line 31 of file APT011.c.
integer ldasiz
Definition at line 94 of file APT011.c.
struct { ... } ldef_
integer limfl[5]
Definition at line 78 of file APT011.c.
doublereal ln1[5]
Definition at line 24 of file APT011.c.
integer lsv
Definition at line 100 of file APT011.c.
integer lsv1
Definition at line 100 of file APT011.c.
integer mantax
Definition at line 100 of file APT011.c.
integer motmod
Definition at line 100 of file APT011.c.
integer msav
Definition at line 100 of file APT011.c.
integer mulout
Definition at line 100 of file APT011.c.
integer nmbseg
Definition at line 100 of file APT011.c.
integer nmpnts
Definition at line 100 of file APT011.c.
integer notan[5]
Definition at line 87 of file APT011.c.
integer nrec
Definition at line 100 of file APT011.c.
integer numax
Definition at line 100 of file APT011.c.
integer numcnt
Definition at line 100 of file APT011.c.
integer nump
Definition at line 100 of file APT011.c.
integer numpt1
Definition at line 100 of file APT011.c.
integer numsfs
Definition at line 100 of file APT011.c.
integer numsur
Definition at line 100 of file APT011.c.
integer nw
Definition at line 100 of file APT011.c.
integer nwds
Definition at line 100 of file APT011.c.
doublereal p[16]
Definition at line 31 of file APT011.c.
doublereal past[5]
Definition at line 37 of file APT011.c.
logical pchlst
Definition at line 71 of file APT011.c.
doublereal pi
Definition at line 63 of file APT011.c.
doublereal plncs[5]
Definition at line 54 of file APT011.c.
doublereal plnd[5]
Definition at line 37 of file APT011.c.
doublereal plnd1[5]
Definition at line 54 of file APT011.c.
doublereal plnv[15]
Definition at line 37 of file APT011.c.
doublereal pltst[5]
Definition at line 54 of file APT011.c.
logical prnton
Definition at line 71 of file APT011.c.
doublereal r__[10]
Definition at line 24 of file APT011.c.
doublereal rc[5]
Definition at line 37 of file APT011.c.
doublereal ref[8]
Definition at line 24 of file APT011.c.
logical refflg
Definition at line 71 of file APT011.c.
logical refmot
Definition at line 71 of file APT011.c.
doublereal s[5]
Definition at line 37 of file APT011.c.
doublereal save[5]
Definition at line 37 of file APT011.c.
doublereal sc[16]
Definition at line 31 of file APT011.c.
doublereal sfvct[15]
Definition at line 37 of file APT011.c.
doublereal sk[15]
Definition at line 37 of file APT011.c.
doublereal slx[15]
Definition at line 37 of file APT011.c.
doublereal sn[15]
Definition at line 37 of file APT011.c.
doublereal snk[15]
Definition at line 37 of file APT011.c.
doublereal snl[15]
Definition at line 37 of file APT011.c.
doublereal sp[15]
Definition at line 37 of file APT011.c.
doublereal spk[15]
Definition at line 37 of file APT011.c.
doublereal spl[15]
Definition at line 37 of file APT011.c.
doublereal stck[5]
Definition at line 54 of file APT011.c.
doublereal stck1[5]
Definition at line 54 of file APT011.c.
doublereal stck2[5]
Definition at line 54 of file APT011.c.
doublereal stckn[5]
Definition at line 54 of file APT011.c.
logical subflg
Definition at line 71 of file APT011.c.
integer surfad[4]
Definition at line 94 of file APT011.c.
struct { ... } sv1_
struct { ... } sv_
doublereal t[12]
Definition at line 31 of file APT011.c.
doublereal t1[12]
Definition at line 31 of file APT011.c.
logical tabprt
Definition at line 71 of file APT011.c.
doublereal tau[5]
Definition at line 37 of file APT011.c.
doublereal tau1[5]
Definition at line 37 of file APT011.c.
doublereal tau2[5]
Definition at line 37 of file APT011.c.
doublereal tee[15]
Definition at line 54 of file APT011.c.
doublereal th[5]
Definition at line 37 of file APT011.c.
doublereal tn[15]
Definition at line 37 of file APT011.c.
doublereal tnl[15]
Definition at line 54 of file APT011.c.
doublereal toolht[15]
Definition at line 37 of file APT011.c.
doublereal toolwd[5]
Definition at line 37 of file APT011.c.
doublereal tp[15]
Definition at line 37 of file APT011.c.
doublereal tpk[15]
Definition at line 37 of file APT011.c.
doublereal u1[15]
Definition at line 37 of file APT011.c.
doublereal u1k[15]
Definition at line 37 of file APT011.c.
logical unflag
Definition at line 71 of file APT011.c.
doublereal v[10]
Definition at line 31 of file APT011.c.
doublereal varble[5]
Definition at line 37 of file APT011.c.
doublereal vndir[15]
Definition at line 37 of file APT011.c.
doublereal vt[15]
Definition at line 37 of file APT011.c.
doublereal z0
Definition at line 63 of file APT011.c.
doublereal z1
Definition at line 63 of file APT011.c.
doublereal z10
Definition at line 63 of file APT011.c.
doublereal z11em1
Definition at line 63 of file APT011.c.
doublereal z12em1
Definition at line 63 of file APT011.c.
doublereal z1e38
Definition at line 63 of file APT011.c.
doublereal z1e6
Definition at line 63 of file APT011.c.
doublereal z1em1
Definition at line 63 of file APT011.c.
doublereal z1em2
Definition at line 63 of file APT011.c.
doublereal z1em3
Definition at line 63 of file APT011.c.
doublereal z1em5
Definition at line 63 of file APT011.c.
doublereal z1em6
Definition at line 63 of file APT011.c.
doublereal z1em7
Definition at line 63 of file APT011.c.
doublereal z1em9
Definition at line 63 of file APT011.c.
doublereal z2
Definition at line 63 of file APT011.c.
doublereal z3
Definition at line 63 of file APT011.c.
doublereal z5
Definition at line 63 of file APT011.c.
doublereal z5em1
Definition at line 63 of file APT011.c.
doublereal z5em6
Definition at line 63 of file APT011.c.
doublereal z6em1
Definition at line 63 of file APT011.c.
doublereal z90
Definition at line 63 of file APT011.c.
doublereal z9em1
Definition at line 63 of file APT011.c.
doublereal z__[5]
Definition at line 37 of file APT011.c.
logical zflag
Definition at line 71 of file APT011.c.
doublereal zm1
Definition at line 63 of file APT011.c.
struct { ... } znumbr_