My Project: APT059.c File Reference
APT059.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define knumbr_1 knumbr_
#define s1 ((doublereal *)&dshar3_1 + 37)
#define s2 ((doublereal *)&dshar3_1 + 38)
#define s3 ((doublereal *)&dshar3_1 + 39)
#define s4 ((doublereal *)&dshar3_1 + 40)
#define s5 ((doublereal *)&dshar3_1 + 41)
#define s6 ((doublereal *)&dshar3_1 + 42)
#define s7 ((doublereal *)&dshar3_1 + 43)
Functions
int apt059_ (doublereal *result, doublereal *pn, doublereal *ma, doublereal *mi, doublereal *beta, doublereal *sgn)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__40 = 40
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT059.c.
Referenced by apt059_().
#define dshar3_1 dshar3_
Definition at line 28 of file APT059.c.
Referenced by apt059_().
#define knumbr_1 knumbr_
Definition at line 44 of file APT059.c.
Referenced by apt059_().
#define s1 ((doublereal *)&dshar3_1 + 37)
Referenced by apt059_().
#define s2 ((doublereal *)&dshar3_1 + 38)
Referenced by apt059_().
#define s3 ((doublereal *)&dshar3_1 + 39)
Referenced by apt059_().
#define s4 ((doublereal *)&dshar3_1 + 40)
Referenced by apt059_().
#define s5 ((doublereal *)&dshar3_1 + 41)
Referenced by apt059_().
#define s6 ((doublereal *)&dshar3_1 + 42)
Referenced by apt059_().
#define s7 ((doublereal *)&dshar3_1 + 43)
Referenced by apt059_().
#define znumbr_1 znumbr_
Definition at line 36 of file APT059.c.
Referenced by apt059_().
Function Documentation
int apt059_ (doublereal * result, doublereal * pn, doublereal * ma, doublereal * mi, doublereal * beta, doublereal * sgn)
Definition at line 85 of file APT059.c.
References apt079_(), apt081_(), c__40, def_1, defext_(), dshar3_1, error_(), knumbr_1, result, s1, s2, s3, s4, s5, s6, s7, and znumbr_1.
Referenced by apt057_(), and apt058_().
 {
     /* System generated locals */
     doublereal d__1, d__2, d__3;
     /* Builtin functions */
     double sin(doublereal), cos(doublereal);
     /* Local variables */
 #define s1 ((doublereal *)&dshar3_1 + 37)
 #define s2 ((doublereal *)&dshar3_1 + 38)
 #define s3 ((doublereal *)&dshar3_1 + 39)
 #define s4 ((doublereal *)&dshar3_1 + 40)
 #define s5 ((doublereal *)&dshar3_1 + 41)
 #define s6 ((doublereal *)&dshar3_1 + 42)
 #define s7 ((doublereal *)&dshar3_1 + 43)
     static doublereal swop;
     extern /* Subroutine */ int apt081_(doublereal *, integer *), apt079_(
         doublereal *, integer *), error_(integer *, char *, ftnlen),
         defext_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...     TRANSFORM POINT TO LOCAL SYSTEM, CHECK VALIDITY */
     /* Parameter adjustments */
     --pn;
     --result;
     /* Function Body */
     apt081_(&pn[1], &knumbr_1.k0);
     if (*ma > *mi) {
     goto L10;
     }
     error_(&c__40, "APT059  ", (ftnlen)8);
     swop = *ma;
     *ma = *mi;
     *mi = swop;
     *beta += 90;
 L10:
     *s1 = *beta * znumbr_1.degrad;
     *s2 = sin(*s1);
     *s3 = cos(*s1);
 /* Computing 2nd power */
     d__1 = *s2;
     *s4 = d__1 * d__1;
 /* Computing 2nd power */
     d__1 = *s3;
     *s5 = d__1 * d__1;
 /* Computing 2nd power */
     d__1 = *ma;
     *s6 = *sgn * (d__1 * d__1);
 /* Computing 2nd power */
     d__1 = *mi;
     *s7 = d__1 * d__1;
     def_1.r__[0] = *s7 * *s5 + *s6 * *s4;
     def_1.r__[1] = *s7 * *s4 + *s6 * *s5;
 /* Computing 2nd power */
     d__1 = dshar3_1.p[0] * *s3 + dshar3_1.p[1] * *s2;
 /* Computing 2nd power */
     d__2 = dshar3_1.p[0] * *s2 - dshar3_1.p[1] * *s3;
 /* Computing 2nd power */
     d__3 = *ma;
     def_1.r__[3] = *s7 * (d__1 * d__1) + *s6 * (d__2 * d__2) - *s7 * (d__3 *
         d__3);
     def_1.r__[5] = znumbr_1.z0;
     def_1.r__[6] = *s2 * *s3 * (*s7 - *s6);
     def_1.r__[7] = -dshar3_1.p[1] * def_1.r__[6] - dshar3_1.p[0] * def_1.r__[
         0];
     def_1.r__[8] = -dshar3_1.p[0] * def_1.r__[6] - dshar3_1.p[1] * def_1.r__[
         1];
     apt079_(def_1.r__, &knumbr_1.km1);
     defext_(&result[1]);
     return 0;
 } /* apt059_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT059.c.
doublereal ahold[8]
Definition at line 18 of file APT059.c.
doublereal c1[8]
Definition at line 18 of file APT059.c.
doublereal c__[7]
Definition at line 25 of file APT059.c.
integer c__40 = 40 static
Definition at line 48 of file APT059.c.
Referenced by apt059_().
struct { ... } def_
doublereal degrad
Definition at line 31 of file APT059.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT059.c.
integer k0
Definition at line 39 of file APT059.c.
integer k1
Definition at line 39 of file APT059.c.
integer k10
Definition at line 39 of file APT059.c.
integer k1013
Definition at line 39 of file APT059.c.
integer k12
Definition at line 39 of file APT059.c.
integer k13
Definition at line 39 of file APT059.c.
integer k15
Definition at line 39 of file APT059.c.
integer k16
Definition at line 39 of file APT059.c.
integer k18
Definition at line 39 of file APT059.c.
integer k19
Definition at line 39 of file APT059.c.
integer k1e4
Definition at line 39 of file APT059.c.
integer k1e6
Definition at line 39 of file APT059.c.
integer k2
Definition at line 39 of file APT059.c.
integer k23
Definition at line 39 of file APT059.c.
integer k24
Definition at line 39 of file APT059.c.
integer k25
Definition at line 39 of file APT059.c.
integer k26
Definition at line 39 of file APT059.c.
integer k27
Definition at line 39 of file APT059.c.
integer k29
Definition at line 39 of file APT059.c.
integer k3
Definition at line 39 of file APT059.c.
integer k30
Definition at line 39 of file APT059.c.
integer k31
Definition at line 39 of file APT059.c.
integer k32
Definition at line 39 of file APT059.c.
integer k33
Definition at line 39 of file APT059.c.
integer k34
Definition at line 39 of file APT059.c.
integer k4
Definition at line 39 of file APT059.c.
integer k44
Definition at line 39 of file APT059.c.
integer k45
Definition at line 39 of file APT059.c.
integer k46
Definition at line 39 of file APT059.c.
integer k47
Definition at line 39 of file APT059.c.
integer k48
Definition at line 39 of file APT059.c.
integer k5
Definition at line 39 of file APT059.c.
integer k50
Definition at line 39 of file APT059.c.
integer k51
Definition at line 39 of file APT059.c.
integer k52
Definition at line 39 of file APT059.c.
integer k6
Definition at line 39 of file APT059.c.
integer k7
Definition at line 39 of file APT059.c.
integer k8
Definition at line 39 of file APT059.c.
integer k9
Definition at line 39 of file APT059.c.
integer km1
Definition at line 39 of file APT059.c.
struct { ... } knumbr_
doublereal l[4]
Definition at line 25 of file APT059.c.
doublereal ln1[5]
Definition at line 18 of file APT059.c.
doublereal p[16]
Definition at line 25 of file APT059.c.
doublereal pi
Definition at line 31 of file APT059.c.
doublereal r__[10]
Definition at line 18 of file APT059.c.
doublereal ref[8]
Definition at line 18 of file APT059.c.
doublereal sc[16]
Definition at line 25 of file APT059.c.
doublereal t[12]
Definition at line 25 of file APT059.c.
doublereal t1[12]
Definition at line 25 of file APT059.c.
doublereal v[10]
Definition at line 25 of file APT059.c.
doublereal z0
Definition at line 31 of file APT059.c.
doublereal z1
Definition at line 31 of file APT059.c.
doublereal z10
Definition at line 31 of file APT059.c.
doublereal z11em1
Definition at line 31 of file APT059.c.
doublereal z12em1
Definition at line 31 of file APT059.c.
doublereal z1e38
Definition at line 31 of file APT059.c.
doublereal z1e6
Definition at line 31 of file APT059.c.
doublereal z1em1
Definition at line 31 of file APT059.c.
doublereal z1em2
Definition at line 31 of file APT059.c.
doublereal z1em3
Definition at line 31 of file APT059.c.
doublereal z1em5
Definition at line 31 of file APT059.c.
doublereal z1em6
Definition at line 31 of file APT059.c.
doublereal z1em7
Definition at line 31 of file APT059.c.
doublereal z1em9
Definition at line 31 of file APT059.c.
doublereal z2
Definition at line 31 of file APT059.c.
doublereal z3
Definition at line 31 of file APT059.c.
doublereal z5
Definition at line 31 of file APT059.c.
doublereal z5em1
Definition at line 31 of file APT059.c.
doublereal z5em6
Definition at line 31 of file APT059.c.
doublereal z6em1
Definition at line 31 of file APT059.c.
doublereal z90
Definition at line 31 of file APT059.c.
doublereal z9em1
Definition at line 31 of file APT059.c.
doublereal zm1
Definition at line 31 of file APT059.c.
struct { ... } znumbr_