My Project: APT040.c File Reference
APT040.c File Reference
#include "f2c.h"
Macros
#define ldef_1 ldef_
Functions
int apt040_ (doublereal *result, doublereal *vc)
Variables
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
static integer c__3 = 3
static integer c__1 = 1
Macro Definition Documentation
#define ldef_1 ldef_
Definition at line 22 of file APT040.c.
Referenced by apt040_().
Function Documentation
int apt040_ (doublereal * result, doublereal * vc)
Definition at line 54 of file APT040.c.
References c__1, c__3, ckdef_(), ldef_1, mode, print_(), result, undef_(), unpack_(), and vnorm_().
Referenced by apt055_(), apt056_(), apt088_(), and xcall_().
 {
     static integer mode;
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int undef_(doublereal *), print_(integer *,
         doublereal *, integer *), vnorm_(doublereal *, doublereal *),
         unpack_(doublereal *, integer *, integer *, integer *);
     static integer idummy;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
     /* Parameter adjustments */
     --vc;
     --result;
     /* Function Body */
     if (ckdef_(&vc[1])) {
     goto L10;
     }
     vnorm_(&vc[1], &result[1]);
     if (ldef_1.prnton) {
     goto L20;
     }
     return 0;
 L10:
     undef_(&result[1]);
     return 0;
 /* ...  IF PRINTON WANT TO PRINT ONLY IF CALLED BY PART PROGRAM. */
 L20:
     unpack_(&result[1], &mode, &idummy, &idummy);
     if (mode == 20) {
     print_(&c__3, &result[1], &c__1);
     }
     return 0;
 } /* apt040_ */
Variable Documentation
logical altmlt
Definition at line 18 of file APT040.c.
logical bnderr
Definition at line 18 of file APT040.c.
logical boundf
Definition at line 18 of file APT040.c.
integer c__1 = 1 static
Definition at line 27 of file APT040.c.
Referenced by apt040_().
integer c__3 = 3 static
Definition at line 26 of file APT040.c.
Referenced by apt040_().
logical canflg
Definition at line 18 of file APT040.c.
logical jcs
Definition at line 18 of file APT040.c.
logical jds
Definition at line 18 of file APT040.c.
struct { ... } ldef_
logical pchlst
Definition at line 18 of file APT040.c.
logical prnton
Definition at line 18 of file APT040.c.
logical refflg
Definition at line 18 of file APT040.c.
logical refmot
Definition at line 18 of file APT040.c.
logical subflg
Definition at line 18 of file APT040.c.
logical tabprt
Definition at line 18 of file APT040.c.
logical unflag
Definition at line 18 of file APT040.c.
logical zflag
Definition at line 18 of file APT040.c.