My Project: APT029.c File Reference
APT029.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define ldef_1 ldef_
#define knumbr_1 knumbr_
#define s1 ((doublereal *)&dshar3_1 + 37)
Functions
int apt029_ (doublereal *result, doublereal *ln, integer *mn, doublereal *pn, doublereal *rad)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT029.c.
Referenced by apt029_().
#define dshar3_1 dshar3_
Definition at line 28 of file APT029.c.
#define knumbr_1 knumbr_
Definition at line 51 of file APT029.c.
Referenced by apt029_().
#define ldef_1 ldef_
Definition at line 43 of file APT029.c.
Referenced by apt029_().
#define s1 ((doublereal *)&dshar3_1 + 37)
Referenced by apt029_().
#define znumbr_1 znumbr_
Definition at line 36 of file APT029.c.
Referenced by apt029_().
Function Documentation
int apt029_ (doublereal * result, doublereal * ln, integer * mn, doublereal * pn, doublereal * rad)
Definition at line 89 of file APT029.c.
References apt004_(), apt020_(), apt078_(), ckdef_(), def_1, i__, knumbr_1, ldef_1, result, s1, and znumbr_1.
Referenced by xcall_().
 {
     /* Builtin functions */
     double d_sign(doublereal *, doublereal *);
     /* Local variables */
     static integer i__;
 #define s1 ((doublereal *)&dshar3_1 + 37)
     extern /* Subroutine */ int apt020_(doublereal *, doublereal *, integer *,
          doublereal *), apt004_(doublereal *, integer *, doublereal *,
         doublereal *), apt078_(doublereal *, integer *);
     extern logical ckdef_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...     TEST VALIDITY OF PN */
     /* Parameter adjustments */
     --pn;
     --ln;
     --result;
     /* Function Body */
     ldef_1.unflag = ckdef_(&pn[1]);
 /* ...     DEFINE CIRCLE C1 WITH CENTER PN, LINE LN1 PARLEL TO LN */
     apt078_(&def_1.r__[3], &knumbr_1.km1);
     def_1.c1[7] = *rad;
     def_1.ln1[4] = ln[4];
     *s1 = -def_1.ln1[4];
     for (i__ = 1; i__ <= 3; ++i__) {
     def_1.c1[i__] = pn[i__];
     def_1.c1[i__ + 3] = def_1.r__[i__ - 1];
     def_1.ln1[i__] = ln[i__];
 /* L10: */
     *s1 += def_1.ln1[i__] * def_1.c1[i__];
     }
 /* ...     TEST FOR PN ON LINE LN */
     if (abs(*s1) <= znumbr_1.z1em5) {
     goto L40;
     }
     def_1.ln1[4] += d_sign(&def_1.c1[7], s1);
 /* ...     CENTER OF DESIRED CIRCLE IS INTERSECTION OF LN1 AND C1 */
 L20:
     for (i__ = 4; i__ <= 7; ++i__) {
 /* L50: */
     def_1.r__[i__ - 1] = def_1.c1[i__];
     }
     apt004_(&result[1], mn, &def_1.ln1[1], &def_1.c1[1]);
     for (i__ = 4; i__ <= 7; ++i__) {
 /* L30: */
     result[i__] = def_1.c1[i__];
     }
     return 0;
 L40:
     apt020_(&def_1.ln1[1], &def_1.ln1[1], mn, rad);
     goto L20;
 } /* apt029_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT029.c.
doublereal ahold[8]
Definition at line 18 of file APT029.c.
logical altmlt
Definition at line 39 of file APT029.c.
logical bnderr
Definition at line 39 of file APT029.c.
logical boundf
Definition at line 39 of file APT029.c.
doublereal c1[8]
Definition at line 18 of file APT029.c.
doublereal c__[7]
Definition at line 25 of file APT029.c.
logical canflg
Definition at line 39 of file APT029.c.
struct { ... } def_
doublereal degrad
Definition at line 31 of file APT029.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT029.c.
logical jcs
Definition at line 39 of file APT029.c.
logical jds
Definition at line 39 of file APT029.c.
integer k0
Definition at line 46 of file APT029.c.
integer k1
Definition at line 46 of file APT029.c.
integer k10
Definition at line 46 of file APT029.c.
integer k1013
Definition at line 46 of file APT029.c.
integer k12
Definition at line 46 of file APT029.c.
integer k13
Definition at line 46 of file APT029.c.
integer k15
Definition at line 46 of file APT029.c.
integer k16
Definition at line 46 of file APT029.c.
integer k18
Definition at line 46 of file APT029.c.
integer k19
Definition at line 46 of file APT029.c.
integer k1e4
Definition at line 46 of file APT029.c.
integer k1e6
Definition at line 46 of file APT029.c.
integer k2
Definition at line 46 of file APT029.c.
integer k23
Definition at line 46 of file APT029.c.
integer k24
Definition at line 46 of file APT029.c.
integer k25
Definition at line 46 of file APT029.c.
integer k26
Definition at line 46 of file APT029.c.
integer k27
Definition at line 46 of file APT029.c.
integer k29
Definition at line 46 of file APT029.c.
integer k3
Definition at line 46 of file APT029.c.
integer k30
Definition at line 46 of file APT029.c.
integer k31
Definition at line 46 of file APT029.c.
integer k32
Definition at line 46 of file APT029.c.
integer k33
Definition at line 46 of file APT029.c.
integer k34
Definition at line 46 of file APT029.c.
integer k4
Definition at line 46 of file APT029.c.
integer k44
Definition at line 46 of file APT029.c.
integer k45
Definition at line 46 of file APT029.c.
integer k46
Definition at line 46 of file APT029.c.
integer k47
Definition at line 46 of file APT029.c.
integer k48
Definition at line 46 of file APT029.c.
integer k5
Definition at line 46 of file APT029.c.
integer k50
Definition at line 46 of file APT029.c.
integer k51
Definition at line 46 of file APT029.c.
integer k52
Definition at line 46 of file APT029.c.
integer k6
Definition at line 46 of file APT029.c.
integer k7
Definition at line 46 of file APT029.c.
integer k8
Definition at line 46 of file APT029.c.
integer k9
Definition at line 46 of file APT029.c.
integer km1
Definition at line 46 of file APT029.c.
struct { ... } knumbr_
doublereal l[4]
Definition at line 25 of file APT029.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file APT029.c.
doublereal p[16]
Definition at line 25 of file APT029.c.
logical pchlst
Definition at line 39 of file APT029.c.
doublereal pi
Definition at line 31 of file APT029.c.
logical prnton
Definition at line 39 of file APT029.c.
doublereal r__[10]
Definition at line 18 of file APT029.c.
doublereal ref[8]
Definition at line 18 of file APT029.c.
logical refflg
Definition at line 39 of file APT029.c.
logical refmot
Definition at line 39 of file APT029.c.
doublereal sc[16]
Definition at line 25 of file APT029.c.
logical subflg
Definition at line 39 of file APT029.c.
doublereal t[12]
Definition at line 25 of file APT029.c.
doublereal t1[12]
Definition at line 25 of file APT029.c.
logical tabprt
Definition at line 39 of file APT029.c.
logical unflag
Definition at line 39 of file APT029.c.
doublereal v[10]
Definition at line 25 of file APT029.c.
doublereal z0
Definition at line 31 of file APT029.c.
doublereal z1
Definition at line 31 of file APT029.c.
doublereal z10
Definition at line 31 of file APT029.c.
doublereal z11em1
Definition at line 31 of file APT029.c.
doublereal z12em1
Definition at line 31 of file APT029.c.
doublereal z1e38
Definition at line 31 of file APT029.c.
doublereal z1e6
Definition at line 31 of file APT029.c.
doublereal z1em1
Definition at line 31 of file APT029.c.
doublereal z1em2
Definition at line 31 of file APT029.c.
doublereal z1em3
Definition at line 31 of file APT029.c.
doublereal z1em5
Definition at line 31 of file APT029.c.
doublereal z1em6
Definition at line 31 of file APT029.c.
doublereal z1em7
Definition at line 31 of file APT029.c.
doublereal z1em9
Definition at line 31 of file APT029.c.
doublereal z2
Definition at line 31 of file APT029.c.
doublereal z3
Definition at line 31 of file APT029.c.
doublereal z5
Definition at line 31 of file APT029.c.
doublereal z5em1
Definition at line 31 of file APT029.c.
doublereal z5em6
Definition at line 31 of file APT029.c.
doublereal z6em1
Definition at line 31 of file APT029.c.
doublereal z90
Definition at line 31 of file APT029.c.
doublereal z9em1
Definition at line 31 of file APT029.c.
logical zflag
Definition at line 39 of file APT029.c.
doublereal zm1
Definition at line 31 of file APT029.c.
struct { ... } znumbr_