My Project: APT070.c File Reference
APT070.c File Reference
#include "f2c.h"
Macros
#define _BLNK__1 _BLNK__
#define def_1 def_
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define ldef_1 ldef_
#define idef_1 idef_
#define knumbr_1 knumbr_
#define d__ ((doublereal *)&_BLNK__1)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int apt070_ (doublereal *result, doublereal *pt, integer *mm, doublereal *tab, doublereal *pt2)
Variables
struct {
doublereal com [36000]
} _BLNK__
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__3 = 3
static doublereal c_b32 = 1e-14
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 21 of file APT070.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
Referenced by apt070_().
#define d__ ((doublereal *)&_BLNK__1)
Referenced by apt070_().
#define def_1 def_
Definition at line 28 of file APT070.c.
#define dshar3_1 dshar3_
Definition at line 34 of file APT070.c.
Referenced by apt070_().
#define idef_1 idef_
Definition at line 55 of file APT070.c.
Referenced by apt070_().
#define knumbr_1 knumbr_
Definition at line 63 of file APT070.c.
Referenced by apt070_().
#define ldef_1 ldef_
Definition at line 49 of file APT070.c.
Referenced by apt070_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define znumbr_1 znumbr_
Definition at line 42 of file APT070.c.
Referenced by apt070_().
Function Documentation
int apt070_ (doublereal * result, doublereal * pt, integer * mm, doublereal * tab, doublereal * pt2)
Definition at line 106 of file APT070.c.
References a1, aa, apt014_(), apt094_(), b1, c__3, c_b32, canon, cc, ckdef_(), d__, defext_(), delta, dshar3_1, i__, idef_1, ii, it, j, j11, jj, knumbr_1, ldef_1, nt, pt, ra, result, schtb_(), sq, sqroot, tab, tol, tranro_(), xc, xd, yd, and znumbr_1.
Referenced by xcall_().
 {
     /* System generated locals */
     integer i__1;
     doublereal d__1, d__2;
     /* Builtin functions */
     double d_sign(doublereal *, doublereal *), atan(doublereal), sqrt(
         doublereal);
     /* Local variables */
 #define d__ ((doublereal *)&_BLNK__1)
     static integer i__, j;
     static doublereal a1, b1, r1, aa[22], cc;
     static integer j11, nt;
     static doublereal xa;
     static integer iz;
     static doublereal ya, ra, xb, yb, xc, yc, xd, yd, ry;
     static integer ii, nn, it;
     static doublereal x11, y11, sq;
     static integer kx, jj, mx;
     static doublereal eq1, eq2;
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer ine[3], ite, ihu;
     static doublereal tol;
     static integer inz, izt;
     static doublereal equ2;
     static integer luck, ihut;
     static doublereal slop;
     static integer itry;
     extern /* Subroutine */ int apt014_(doublereal *, doublereal *,
         doublereal *), apt094_(integer *, doublereal *, integer *);
     extern logical ckdef_(doublereal *);
     static integer ifall;
     static doublereal delta;
 #define canon ((doublereal *)&_BLNK__1)
     extern /* Subroutine */ int schtb_(doublereal *);
 #define sscan ((doublereal *)&_BLNK__1 + 40)
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int defext_(doublereal *);
     static doublereal borslp;
     extern /* Subroutine */ int tranro_(doublereal *, doublereal *,
         doublereal *, doublereal *, doublereal *, integer *);
     static doublereal sqroot;
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /* ...  VARIABLES XA,YA,RA,XB,YB,XC,YC,XD,YD,TOL,EQU2,SLOP,R1,RY,BORSLP, */
 /* ...  X11,Y11,EQ1,EQ2 & DELTA WERE ALL EQUIVALENCED TO SUCCESSIVE */
 /* ...  ELEMENTS OF SC.  AS THEIR USEAGE SEEMED TO BE LOCAL, THE */
 /* ...  EQUIVALENCE HAS BEEN REMOVED. */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --pt2;
     --tab;
     --pt;
     --result;
     /* Function Body */
     for (i__ = 1; i__ <= 2; ++i__) {
     dshar3_1.p[i__ - 1] = pt2[i__];
     dshar3_1.v[i__ - 1] = pt[i__];
 /* L10: */
     dshar3_1.c__[i__ - 1] = tab[i__];
     }
     ldef_1.unflag = ckdef_(dshar3_1.p) || ckdef_(dshar3_1.v) || ckdef_(
         dshar3_1.c__);
     if (ldef_1.unflag) {
     goto L9998;
     }
 /* ... RETRIEVE TABCYL EXTERNAL CANONICAL FORM. STORE CANON INDEX IN J11. */
     apt094_(&c__3, &tab[1], &j11);
     if (ckdef_(&tab[1])) {
     goto L9998;
     }
 /* ...  FIND PART OF TABCYL CLOSEST TO INPUT P,USING SCHTB */
     schtb_(&canon[j11 - 2]);
     ihu = (integer) (canon[j11 + 10] + znumbr_1.z1em2);
     itry = knumbr_1.k0;
     nt = (integer) ((canon[j11 + 9] - znumbr_1.z1) * 7.f + 21.1f);
     --j11;
     ihu = ihu + j11 - knumbr_1.k1;
     goto L2;
 /* .....TRANSLATE AND ROTATE INTO COORDINATE SYSTEM OF THE SELECTED */
 /* .....TABCYL INTERBAL */
 L12:
     if (itry - 7 >= 0) {
     goto L13;
     } else {
     goto L2;
     }
 L2:
     xa = d__[ihu + 6] - d__[ihu - 1];
     ihut = ihu;
     if (*mm != 1) {
     goto L412;
     }
 /* L411: */
     ite = j11 + nt - 16;
     izt = j11 + 13;
     goto L413;
 /* .....EXTENSION INTERVALS ARE INCLUDED IN THE NORMAL LINE SEARCH. */
 L412:
     ite = j11 + nt - 9;
     izt = j11 + 6;
 L413:
     iz = 1;
     ya = d__[ihu + 7] - d__[ihu];
 /* Computing MAX */
     d__2 = abs(xa);
     d__1 = max(d__2,znumbr_1.z1em9);
     ra = -atan(ya / d_sign(&d__1, &xa));
     if (xa >= 0.) {
     goto L1001;
     } else {
     goto L1000;
     }
 L1000:
     ra += znumbr_1.pi;
 L1001:
     tranro_(&xa, &ya, &xb, &yb, &ra, &iz);
     xc = dshar3_1.v[0] - d__[ihu - 1];
     yc = dshar3_1.v[1] - d__[ihu];
     tranro_(&xc, &yc, &xd, &yd, &ra, &iz);
 /* .... TEST TO SEE IF GIVEN POINT IS ON OR OFF TABCYL */
     tol = znumbr_1.z1em5;
     if (xb + tol - xd >= 0.) {
     goto L71;
     } else {
     goto L206;
     }
 L71:
     if (xd + tol >= 0.) {
     goto L72;
     } else {
     goto L206;
     }
 L72:
 /* Computing 3rd power */
     d__1 = xd;
 /* Computing 2nd power */
     d__2 = xd;
     equ2 = d__[ihu + 1] * (d__1 * (d__1 * d__1)) + d__[ihu + 2] * (d__2 *
         d__2) - (d__[ihu + 1] * d__[ihu + 3] + d__[ihu + 2]) * (d__[ihu +
         3] * xd);
     if ((d__1 = yd - equ2, abs(d__1)) - tol <= 0.) {
     goto L70;
     } else {
     goto L206;
     }
 L206:
     if (*mm != 1) {
     goto L207;
     }
     goto L73;
 L70:
 /* Computing 2nd power */
     d__1 = xd;
     slop = znumbr_1.z3 * d__[ihu + 1] * (d__1 * d__1) + znumbr_1.z2 * d__[ihu
         + 2] * xd - (d__[ihu + 1] * d__[ihu + 3] + d__[ihu + 2]) * d__[
         ihu + 3];
 /* ---    CORRECTION FOR LINE/PT,PERPTO,TAB,REF */
     if (*mm == 2) {
     goto L200;
     }
 L290:
     if (slop != 0.) {
     goto L291;
     } else {
     goto L76;
     }
 L291:
     if (abs(slop) - znumbr_1.z1 >= 0.) {
     goto L74;
     } else {
     goto L76;
     }
 L74:
     r1 = xd - znumbr_1.z1 / slop;
     ry = yd - znumbr_1.z1;
     goto L79;
 L76:
     r1 = xd - znumbr_1.z1;
     ry = yd - slop;
     goto L79;
 L200:
     if (abs(slop) - znumbr_1.z1em6 >= 0.) {
     goto L202;
     } else {
     goto L201;
     }
 L201:
     if (slop >= 0.) {
     goto L204;
     } else {
     goto L203;
     }
 L203:
     borslp = 9999999.f;
     goto L205;
 L204:
     borslp = -9999999.f;
     goto L205;
 L202:
     borslp = -1.f / slop;
 L205:
     slop = borslp;
     goto L290;
 /* .....CALCULATE COEFFICIENTS OF THE CUBIC EQUATION AND SOLVE FOR */
 /*     THE POINTS OF TANGENCY */
 L73:
     aa[0] = znumbr_1.z2 * d__[ihu + 1];
     if (abs(aa[0]) - 1e-14 >= 0.) {
     goto L1237;
     } else {
     goto L1236;
     }
 L1236:
     aa[0] = d_sign(&c_b32, aa);
 L1237:
     aa[1] = d__[ihu + 2] - znumbr_1.z3 * d__[ihu + 1] * xd;
     aa[2] = -znumbr_1.z2 * d__[ihu + 2] * xd;
     aa[3] = yd + (d__[ihu + 1] * d__[ihu + 3] + d__[ihu + 2]) * (d__[ihu + 3]
         * xd);
     for (i__ = 1; i__ <= 22; ++i__) {
 /* L16: */
     dshar3_1.t[i__ - 1] = znumbr_1.z0;
     }
     ifall = knumbr_1.k0;
     ii = knumbr_1.k3;
     nn = knumbr_1.k7;
     goto L500;
 L540:
 /* .....TEST FOR ERRORS */
 /* L21: */
     if (ifall == knumbr_1.k0) {
     goto L3;
     }
     idef_1.ierror = 75;
     goto L9999;
 /* .....ROOTS FOUND OK, TEST THEIR POSITIONS WITH RESPECT TO THE */
 /* .....BOUNDARY POINTS OF THE INTERVAL */
 L3:
     it = -1;
     luck = knumbr_1.k0;
     for (i__ = 1; i__ <= 3; ++i__) {
     ine[i__ - 1] = knumbr_1.k0;
     it += knumbr_1.k2;
     if (dshar3_1.t[it] != 0.) {
         goto L24;
     } else {
         goto L30;
     }
 L30:
     if (dshar3_1.t[it - 1] + znumbr_1.z1em6 <= 0.) {
         goto L24;
     } else {
         goto L25;
     }
 L25:
     if (dshar3_1.t[it - 1] * (xb - dshar3_1.t[it - 1]) >= 0.) {
         goto L26;
     } else {
         goto L24;
     }
 L26:
     luck += knumbr_1.k1;
     ine[i__ - 1] = it;
 L24:
     ;
     }
     if ((i__1 = luck - 1) < 0) {
     goto L27;
     } else if (i__1 == 0) {
     goto L28;
     } else {
     goto L4;
     }
 /* .....MULTIPLE TANGENCY POINTS IN THE INTERVAL */
 L4:
     xa = d__[ihu + 6] - d__[ihu - 1];
     ya = d__[ihu + 7] - d__[ihu];
 /* Computing MAX */
     d__2 = abs(xa);
     d__1 = max(d__2,znumbr_1.z1em9);
     ra = -atan(ya / d_sign(&d__1, &xa));
     if (xa >= 0.) {
     goto L1003;
     } else {
     goto L1002;
     }
 L1002:
     ra += znumbr_1.pi;
 L1003:
     it = -1;
     iz = -1;
     for (i__ = 1; i__ <= 3; ++i__) {
     it += knumbr_1.k2;
     if (ine[i__ - 1] != 0) {
         goto L299;
     } else {
         goto L301;
     }
 L299:
     r1 = dshar3_1.t[it - 1];
 /* Computing 3rd power */
     d__1 = r1;
 /* Computing 2nd power */
     d__2 = r1;
     ry = d__[ihu + 1] * (d__1 * (d__1 * d__1)) + d__[ihu + 2] * (d__2 *
         d__2) - (d__[ihu + 1] * d__[ihu + 3] + d__[ihu + 2]) * (d__[
         ihu + 3] * r1);
     tranro_(&r1, &ry, &xa, &ya, &ra, &iz);
     r1 = xa + d__[ihu - 1];
     ry = ya + d__[ihu];
 L301:
     ;
     }
     idef_1.ierror = 73;
     goto L9999;
 /* .....TEST FOR NORMAL LINE WHEN GIVEN POINT */
 /*     IS NOT A POINT ON THE TABCYL */
 /*     CALCULATE COEFFICIENTS FOR A FIFTH-ORDER EQUATION */
 /*     WHICH DEFINES A POINT ON THE TABCYL INTERVAL (CUBIC EQUATION) */
 /*     WHERE THE NORMAL TO THE INTERVAL PASSES THRU THE GIVEN POINT. */
 L207:
 /* Computing 2nd power */
     d__1 = d__[ihu + 1];
     dshar3_1.t1[0] = znumbr_1.z3 * (d__1 * d__1);
     dshar3_1.t1[1] = znumbr_1.z5 * d__[ihu + 1] * d__[ihu + 2];
 /* Computing 2nd power */
     d__1 = d__[ihu + 2];
     dshar3_1.t1[2] = d__[ihu + 1] * 4.f * (znumbr_1.zm1 * (d__[ihu + 1] * d__[
         ihu + 3] + d__[ihu + 2]) * d__[ihu + 3]) + znumbr_1.z2 * (d__1 *
         d__1);
     dshar3_1.t1[3] = znumbr_1.z3 * d__[ihu + 2] * (-(d__[ihu + 1] * d__[ihu +
         3] + d__[ihu + 2]) * d__[ihu + 3]) - znumbr_1.z3 * d__[ihu + 1] *
         yd;
 /* Computing 2nd power */
     d__1 = -(d__[ihu + 1] * d__[ihu + 3] + d__[ihu + 2]) * d__[ihu + 3];
     dshar3_1.t1[4] = d__1 * d__1 - znumbr_1.z2 * d__[ihu + 2] * yd +
         znumbr_1.z1;
     dshar3_1.t1[5] = xd - yd * (d__[ihu + 1] * d__[ihu + 3] + d__[ihu + 2]) *
         d__[ihu + 3];
     dshar3_1.t1[6] = znumbr_1.z5 * dshar3_1.t1[0];
     dshar3_1.t1[7] = dshar3_1.t1[1] * 4.f;
     dshar3_1.t1[8] = znumbr_1.z3 * dshar3_1.t1[2];
     dshar3_1.t1[9] = znumbr_1.z2 * dshar3_1.t1[3];
     dshar3_1.t1[10] = dshar3_1.t1[4];
 /* .....(X11,Y11) IS THE END POINT OF THE INTERVAL BEING */
 /* .....CONSIDERED THAT IS NEAREST TO THE SPECIFIED POINT. */
     tranro_(&d__[nt - 1], &d__[nt], &x11, &y11, &ra, &iz);
     if (x11 < 0.) {
     goto L40;
     } else if (x11 == 0) {
     goto L44;
     } else {
     goto L41;
     }
 L40:
     x11 = znumbr_1.z0;
     goto L44;
 L41:
     if ((d__1 = x11 - znumbr_1.z5em1 * xb) < 0.) {
     goto L40;
     } else if (d__1 == 0) {
     goto L44;
     } else {
     goto L43;
     }
 L43:
     x11 = xb;
 /* .....NEWTONS METHOD IS USED TO SOLVE THE FIFTH ORDER */
 /*     EQUATION. X11 IS THE INITIAL ESTIMATE OF THE ROOT. */
 L44:
     for (j = 1; j <= 200; ++j) {
     eq1 = ((((dshar3_1.t1[0] * x11 + dshar3_1.t1[1]) * x11 + dshar3_1.t1[
         2]) * x11 + dshar3_1.t1[3]) * x11 + dshar3_1.t1[4]) * x11 -
         dshar3_1.t1[5];
     eq2 = (((dshar3_1.t1[6] * x11 + dshar3_1.t1[7]) * x11 + dshar3_1.t1[8]
         ) * x11 + dshar3_1.t1[9]) * x11 + dshar3_1.t1[10];
     if (znumbr_1.z1 >= 0.) {
         goto L461;
     } else {
         goto L46;
     }
 L461:
     delta = -eq1 / eq2;
     if (abs(delta) - 3e-6 >= 0.) {
         goto L46;
     } else {
         goto L47;
     }
 L46:
     x11 += delta;
 /* L45: */
     }
     goto L27;
 L47:
     if (x11 + znumbr_1.z5em6 >= 0.) {
     goto L112;
     } else {
     goto L27;
     }
 L112:
     if (xb + znumbr_1.z5em6 - x11 >= 0.) {
     goto L113;
     } else {
     goto L27;
     }
 L113:
     y11 = (d__[ihu + 1] * x11 + d__[ihu + 2]) * x11 * x11 - (d__[ihu + 1] *
         d__[ihu + 3] + d__[ihu + 2]) * (d__[ihu + 3] * x11);
     r1 = x11;
     ry = y11;
     goto L79;
 /* .....TANGENCY POINT NOT FOUND OR NOT IN INTERVAL, */
 /*     SET UP FOR RE-TRY UNTIL 3 INTERVALS ON EACH SIDE OF THE INITIAL */
 /*     INTERVAL HAVE BEEN TRIED------A TOTAL OF 7 INTERVALS. */
 /* .....  (EXTENSION INTERVALS ARE INCLUDED FOR NORMAL LINE ONLY) */
 L27:
     ++itry;
     switch (itry) {
     case 1:  goto L29;
     case 2:  goto L900;
     case 3:  goto L904;
     case 4:  goto L905;
     case 5:  goto L906;
     case 6:  goto L907;
     case 7:  goto L13;
     }
 L29:
     ihu += 7;
 L902:
     if (ihu - ite >= 0) {
     goto L27;
     } else {
     goto L12;
     }
 L900:
     ihu += -14;
 L903:
     if (ihu - izt <= 0) {
     goto L27;
     } else {
     goto L12;
     }
 L904:
     ihu += 21;
     goto L902;
 L905:
     ihu += -28;
     goto L903;
 L906:
     ihu += 35;
     goto L902;
 L907:
     ihu += -42;
     goto L903;
 L13:
     if (*mm != 1) {
     goto L408;
     }
     idef_1.ierror = 74;
     goto L9999;
 L408:
     idef_1.ierror = 74;
     goto L9999;
 /* .....TANGENCY POINT FOUND, CALCULATE SECOND COORDINATE AND TRANSFORM */
 /*     THE POINT BACK TO THE XY-PLANE */
 L28:
     for (i__ = 1; i__ <= 3; ++i__) {
     if (ine[i__ - 1] != 0) {
         goto L33;
     }
 /* L32: */
     }
 L33:
     inz = ine[i__ - 1];
     r1 = dshar3_1.t[inz - 1];
 /* L9: */
 /* Computing 2nd power */
     d__1 = r1;
     ry = (d__[ihu + 1] * r1 + d__[ihu + 2]) * (d__1 * d__1) - (d__[ihu + 1] *
         d__[ihu + 3] + d__[ihu + 2]) * (d__[ihu + 3] * r1);
 L79:
     iz = -1;
     xa = d__[ihu + 6] - d__[ihu - 1];
     ya = d__[ihu + 7] - d__[ihu];
 /* Computing MAX */
     d__2 = abs(xa);
     d__1 = max(d__2,znumbr_1.z1em9);
     ra = -atan(ya / d_sign(&d__1, &xa));
     if (xa >= 0.) {
     goto L1005;
     } else {
     goto L1004;
     }
 L1004:
     ra += znumbr_1.pi;
 L1005:
     tranro_(&r1, &ry, &xa, &ya, &ra, &iz);
     dshar3_1.g[0] = d__[ihu - 1] + xa;
     dshar3_1.g[1] = d__[ihu] + ya;
     dshar3_1.g[2] = znumbr_1.z0;
 /* .....CALCULATE CANONICAL FORM OF A LINE THRU TWO POINTS IN */
 /*     THE XY-PLANE */
     dshar3_1.v[2] = znumbr_1.z0;
     apt014_(&result[1], dshar3_1.v, dshar3_1.g);
 L163:
     return 0;
 L9998:
     idef_1.ierror = 76;
 L9999:
     defext_(&result[1]);
     goto L163;
 L500:
     a1 = znumbr_1.z3 * aa[0];
     b1 = znumbr_1.z2 * aa[1];
     cc = aa[2];
     sqroot = d__[ihu + 3];
 /* Computing 2nd power */
     d__1 = b1;
     sq = d__1 * d__1 - a1 * 4.f * cc;
     if (abs(sq) >= znumbr_1.z1em7) {
     goto L501;
     }
     kx = knumbr_1.k2;
     dshar3_1.t[1] = -b1 / (znumbr_1.z2 * a1);
     goto L504;
 L501:
     if (sq <= 0.) {
     goto L502;
     } else {
     goto L503;
     }
 L502:
     kx = knumbr_1.k0;
     goto L504;
 L503:
     kx = knumbr_1.k3;
     d__1 = sqrt(sq);
     sq = -b1 - d_sign(&d__1, &b1);
     if (sq <= znumbr_1.z0) {
     goto L502;
     }
     dshar3_1.t[1] = znumbr_1.z2 * cc / sq;
     if (sq <= znumbr_1.z0) {
     goto L502;
     }
     dshar3_1.t[2] = sq / (znumbr_1.z2 * a1);
     goto L521;
 L504:
     dshar3_1.t[0] = znumbr_1.z5em1 * sqroot;
     goto L510;
 L521:
     for (jj = 1; jj <= 2; ++jj) {
 /* L505: */
     dshar3_1.t1[jj - 1] = ((aa[0] * dshar3_1.t[jj] + aa[1]) * dshar3_1.t[
         jj] + aa[2]) * dshar3_1.t[jj] + aa[3];
     }
     if (dshar3_1.t1[0] * dshar3_1.t1[1] >= 0.) {
     goto L507;
     } else {
     goto L506;
     }
 L506:
     dshar3_1.t[0] = (dshar3_1.t[1] + dshar3_1.t[2]) * znumbr_1.z5em1;
     goto L510;
 L507:
     if (abs(dshar3_1.t1[0]) - abs(dshar3_1.t1[1]) >= 0.) {
     goto L509;
     } else {
     goto L508;
     }
 L508:
     dshar3_1.t[0] = znumbr_1.z12em1 * dshar3_1.t[2] - dshar3_1.t[1] * .2f;
     goto L510;
 L509:
     dshar3_1.t[0] = znumbr_1.z12em1 * dshar3_1.t[1] - dshar3_1.t[2] * .2f;
 L510:
 /* Computing MIN */
     d__1 = max(dshar3_1.t[0],znumbr_1.z0);
     dshar3_1.t[0] = min(d__1,sqroot);
     dshar3_1.t1[0] = znumbr_1.z3 * aa[0];
     dshar3_1.t1[1] = znumbr_1.z2 * aa[1];
     dshar3_1.t1[2] = aa[2];
     for (mx = 1; mx <= 100; ++mx) {
     dshar3_1.t1[3] = (dshar3_1.t1[0] * dshar3_1.t[0] + dshar3_1.t1[1]) *
         dshar3_1.t[0] + dshar3_1.t1[2];
     if (abs(dshar3_1.t1[3]) - 1e-20 >= 0.) {
         goto L512;
     } else {
         goto L511;
     }
 L511:
     dshar3_1.t[0] += znumbr_1.z1em6;
     goto L520;
 L512:
     dshar3_1.t1[3] = (((aa[0] * dshar3_1.t[0] + aa[1]) * dshar3_1.t[0] +
         aa[2]) * dshar3_1.t[0] + aa[3]) / dshar3_1.t1[3];
     if (abs(dshar3_1.t1[3]) < znumbr_1.z1em6 * abs(dshar3_1.t[0])) {
         goto L530;
     }
     dshar3_1.t[0] -= dshar3_1.t1[3];
 L520:
     ;
     }
     ifall = 1;
 L530:
     dshar3_1.t[1] = znumbr_1.z0;
     a1 = aa[0];
     b1 = aa[0] * dshar3_1.t[0] + aa[1];
     cc = b1 * dshar3_1.t[0] + aa[2];
 /* Computing 2nd power */
     d__1 = b1;
     sq = d__1 * d__1 - a1 * 4.f * cc;
     if (abs(sq) >= znumbr_1.z1em7) {
     goto L531;
     }
     dshar3_1.t[2] = -b1 / (znumbr_1.z2 * a1);
     dshar3_1.t[3] = znumbr_1.z0;
     dshar3_1.t[5] = znumbr_1.z1;
     goto L539;
 L531:
     if (sq <= 0.) {
     goto L532;
     } else {
     goto L533;
     }
 L532:
     dshar3_1.t[3] = znumbr_1.z1;
     dshar3_1.t[5] = znumbr_1.z1;
     goto L539;
 L533:
     d__1 = sqrt(sq);
     sq = -b1 - d_sign(&d__1, &b1);
     if (sq <= znumbr_1.z0) {
     goto L532;
     }
     dshar3_1.t[2] = znumbr_1.z2 * cc / sq;
     if (sq <= znumbr_1.z0) {
     goto L532;
     }
     dshar3_1.t[4] = sq / (znumbr_1.z2 * a1);
     dshar3_1.t[3] = znumbr_1.z0;
     dshar3_1.t[5] = znumbr_1.z0;
 L539:
     goto L540;
 } /* apt070_ */
Variable Documentation
struct { ... } _BLNK__
doublereal a[24]
Definition at line 24 of file APT070.c.
doublereal ahold[8]
Definition at line 24 of file APT070.c.
logical altmlt
Definition at line 45 of file APT070.c.
logical bnderr
Definition at line 45 of file APT070.c.
logical boundf
Definition at line 45 of file APT070.c.
doublereal c1[8]
Definition at line 24 of file APT070.c.
doublereal c__[7]
Definition at line 31 of file APT070.c.
integer c__3 = 3 static
Definition at line 67 of file APT070.c.
Referenced by apt070_().
doublereal c_b32 = 1e-14 static
Definition at line 68 of file APT070.c.
Referenced by apt070_().
logical canflg
Definition at line 45 of file APT070.c.
doublereal com[36000]
Definition at line 18 of file APT070.c.
struct { ... } def_
doublereal degrad
Definition at line 37 of file APT070.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 31 of file APT070.c.
integer iblk1
Definition at line 52 of file APT070.c.
struct { ... } idef_
integer ierror
Definition at line 52 of file APT070.c.
logical jcs
Definition at line 45 of file APT070.c.
logical jds
Definition at line 45 of file APT070.c.
integer k0
Definition at line 58 of file APT070.c.
integer k1
Definition at line 58 of file APT070.c.
integer k10
Definition at line 58 of file APT070.c.
integer k1013
Definition at line 58 of file APT070.c.
integer k12
Definition at line 58 of file APT070.c.
integer k13
Definition at line 58 of file APT070.c.
integer k15
Definition at line 58 of file APT070.c.
integer k16
Definition at line 58 of file APT070.c.
integer k18
Definition at line 58 of file APT070.c.
integer k19
Definition at line 58 of file APT070.c.
integer k1e4
Definition at line 58 of file APT070.c.
integer k1e6
Definition at line 58 of file APT070.c.
integer k2
Definition at line 58 of file APT070.c.
integer k23
Definition at line 58 of file APT070.c.
integer k24
Definition at line 58 of file APT070.c.
integer k25
Definition at line 58 of file APT070.c.
integer k26
Definition at line 58 of file APT070.c.
integer k27
Definition at line 58 of file APT070.c.
integer k29
Definition at line 58 of file APT070.c.
integer k3
Definition at line 58 of file APT070.c.
integer k30
Definition at line 58 of file APT070.c.
integer k31
Definition at line 58 of file APT070.c.
integer k32
Definition at line 58 of file APT070.c.
integer k33
Definition at line 58 of file APT070.c.
integer k34
Definition at line 58 of file APT070.c.
integer k4
Definition at line 58 of file APT070.c.
integer k44
Definition at line 58 of file APT070.c.
integer k45
Definition at line 58 of file APT070.c.
integer k46
Definition at line 58 of file APT070.c.
integer k47
Definition at line 58 of file APT070.c.
integer k48
Definition at line 58 of file APT070.c.
integer k5
Definition at line 58 of file APT070.c.
integer k50
Definition at line 58 of file APT070.c.
integer k51
Definition at line 58 of file APT070.c.
integer k52
Definition at line 58 of file APT070.c.
integer k6
Definition at line 58 of file APT070.c.
integer k7
Definition at line 58 of file APT070.c.
integer k8
Definition at line 58 of file APT070.c.
integer k9
Definition at line 58 of file APT070.c.
integer km1
Definition at line 58 of file APT070.c.
struct { ... } knumbr_
integer kwrdsz
Definition at line 52 of file APT070.c.
doublereal l[4]
Definition at line 31 of file APT070.c.
integer ldasiz
Definition at line 52 of file APT070.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 24 of file APT070.c.
doublereal p[16]
Definition at line 31 of file APT070.c.
logical pchlst
Definition at line 45 of file APT070.c.
doublereal pi
Definition at line 37 of file APT070.c.
logical prnton
Definition at line 45 of file APT070.c.
doublereal r__[10]
Definition at line 24 of file APT070.c.
doublereal ref[8]
Definition at line 24 of file APT070.c.
logical refflg
Definition at line 45 of file APT070.c.
logical refmot
Definition at line 45 of file APT070.c.
doublereal sc[16]
Definition at line 31 of file APT070.c.
logical subflg
Definition at line 45 of file APT070.c.
integer surfad[4]
Definition at line 52 of file APT070.c.
doublereal t[12]
Definition at line 31 of file APT070.c.
doublereal t1[12]
Definition at line 31 of file APT070.c.
logical tabprt
Definition at line 45 of file APT070.c.
logical unflag
Definition at line 45 of file APT070.c.
doublereal v[10]
Definition at line 31 of file APT070.c.
doublereal z0
Definition at line 37 of file APT070.c.
doublereal z1
Definition at line 37 of file APT070.c.
doublereal z10
Definition at line 37 of file APT070.c.
doublereal z11em1
Definition at line 37 of file APT070.c.
doublereal z12em1
Definition at line 37 of file APT070.c.
doublereal z1e38
Definition at line 37 of file APT070.c.
doublereal z1e6
Definition at line 37 of file APT070.c.
doublereal z1em1
Definition at line 37 of file APT070.c.
doublereal z1em2
Definition at line 37 of file APT070.c.
doublereal z1em3
Definition at line 37 of file APT070.c.
doublereal z1em5
Definition at line 37 of file APT070.c.
doublereal z1em6
Definition at line 37 of file APT070.c.
doublereal z1em7
Definition at line 37 of file APT070.c.
doublereal z1em9
Definition at line 37 of file APT070.c.
doublereal z2
Definition at line 37 of file APT070.c.
doublereal z3
Definition at line 37 of file APT070.c.
doublereal z5
Definition at line 37 of file APT070.c.
doublereal z5em1
Definition at line 37 of file APT070.c.
doublereal z5em6
Definition at line 37 of file APT070.c.
doublereal z6em1
Definition at line 37 of file APT070.c.
doublereal z90
Definition at line 37 of file APT070.c.
doublereal z9em1
Definition at line 37 of file APT070.c.
logical zflag
Definition at line 45 of file APT070.c.
doublereal zm1
Definition at line 37 of file APT070.c.
struct { ... } znumbr_