My Project: APT094.c File Reference
APT094.c File Reference
#include "f2c.h"
Macros
#define _BLNK__1 _BLNK__
#define symfil_1 symfil_
#define maxlda_1 maxlda_
#define idef_1 idef_
#define aaa (equiv_4)
#define can ((doublereal *)&_BLNK__1 + 40)
#define jjj ((integer *)equiv_4)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int apt094_ (integer *ldaflg, doublereal *ldaary, doublereal *canloc)
Variables
struct {
doublereal com [36000]
} _BLNK__
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
struct {
integer maxlda
} maxlda_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
static integer c__5061 = 5061
static integer c__5062 = 5062
static integer c__5060 = 5060
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 21 of file APT094.c.
#define aaa (equiv_4)
Referenced by apt094_().
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Referenced by apt094_().
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
Referenced by apt094_().
#define idef_1 idef_
Definition at line 42 of file APT094.c.
#define jjj ((integer *)equiv_4)
Referenced by apt094_(), apt102_(), pro027_(), and punch_().
#define maxlda_1 maxlda_
Definition at line 36 of file APT094.c.
Referenced by apt094_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define symfil_1 symfil_
Definition at line 30 of file APT094.c.
Referenced by apt094_().
Function Documentation
int apt094_ (integer * ldaflg, doublereal * ldaary, doublereal * canloc)
Definition at line 52 of file APT094.c.
References aaa, addrss_(), aread_(), awrite_(), bcanon, c__5060, c__5061, c__5062, canloc, canon, ckdef_(), error_(), i__, ir, j, jjj, k, maxlda_1, n, symfil_1, tapop_(), and undef_().
Referenced by ajundd_(), apt011_(), apt033_(), apt034_(), apt070_(), apt088_(), apt089_(), apt090_(), apt100_(), apt106_(), apt107_(), apt108_(), apt109_(), apt110_(), apt240_(), ddst_(), gencrv_(), gfetch_(), gol_(), gotopn_(), intsec_(), ldard_(), lodpch_(), numf1_(), numf2_(), numver_(), parmf1_(), parmf2_(), punch_(), region_(), srfcom_(), sstra_(), and xcall_().
 {
     /* Initialized data */
     static integer maxldc = 40;
     static integer recnum = 0;
     static integer noldas = 0;
     static integer ldacor[80]   /* was [2][40] */ = { 0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0 };
     /* System generated locals */
     integer i__1;
     doublereal d__1;
     static doublereal equiv_4[1];
     /* Local variables */
     static integer i__, j, k, n, ir, nn, nr;
 #define aaa (equiv_4)
     static integer lda[2];
 #define can ((doublereal *)&_BLNK__1 + 40)
 #define jjj ((integer *)equiv_4)
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int aread_(integer *, integer *, doublereal *,
         integer *, integer *);
 #define canon ((doublereal *)&_BLNK__1)
     extern /* Subroutine */ int undef_(doublereal *);
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int tapop_(integer *, integer *), error_(integer *
         , char *, ftnlen);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     static integer kanind;
     extern integer addrss_(doublereal *);
     static integer ldatop;
     extern /* Subroutine */ int awrite_(integer *, integer *, doublereal *,
         integer *, integer *);
     static integer cortop;
 /* PURPOSE      THE PURPOSE OF THIS SUBROUTINE IS TO READ OR WRITE LARGE */
 /*              DATA ARRAY CANONICAL FORMS IN OR OUT OF UNLABELED COMMON */
 /*              AND TO UNDEFINE ERRONEOUS L.D.A. CANONICAL FORMS. */
 /* ARGUMENTS    LDAFLG        =1, IF WRITE */
 /*                            =2, IF READ INTO A SPECIFIC LOCATION.(USED */
 /*                                  TO INCORPORATE PREVIOUSLY DEFINED */
 /*                                  CANONICAL FORMS INTO A NEWLY CREATED */
 /*                                  CANONICAL FORM) */
 /*                            =3, IF READ INTO NEXT AVAILABLE UNLABELED */
 /*                                COMMON AREA.(USED TO RETRIEVE CANONICAL */
 /*                                  FORMS FOR USE IN ARLEM MOTION */
 /*                                  STATEMENT PROCESSSING) */
 /*                            =4, IF DEFINITION ERROR. */
 /*                            =5, LIKE =1 WITHOUT WRITING:FOR SPACE- */
 /*                                RESERVATION IN BLANK COMMON FOR NEW */
 /*                                GEOMETRY OR OTHER USE OF SPACE BEGINN- */
 /*                                ING AT >BCANON(1)< . */
 /*                            =6, UPDATE IN PLACE (ON FILE) */
 /*                            =7, READ THE FIRST TWO WORDS OF DATA */
 /*              LDAARY        SURFACE */
 /*              CANLOC        THE LOCATION IN UNLABELED COMMON FROM WHICH */
 /*                            TO READ OR WRITE. IF LDAFLG = 3, THEN THE */
 /*                            CANONICAL FORM IS READ INTO THE NEXT */
 /*                            AVAILABLE LOCATION AND ITS CANON INDEX IS */
 /*                            RETURNED IN CANLOC. */
 /* SUBSIDIARIES MACHINE LANGUAGE SUBROUTINE        UNDEF */
 /*              FORTRAN SUBROUTINE                 ERROR */
 /* LOCAL VARIABLES */
 /*              LDATOP        BCANON INDEX INDICATING THE STARTING */
 /*                            POSITION FOR THE NEXT CANONICAL FORM TO */
 /*                            BE READ INTO CORE. */
 /*              LDACOR        ARRAY CONTAINING THE RECORD NUMBER AND */
 /*                            BCANON INDEX OF EACH CANONICAL FORM */
 /*                            CURRENTLY IN CORE. THE ORDER OF LDACOR */
 /*                            ENTRIES CORRESPONDS TO THE RELATIVE */
 /*                            POSITION OF THEIR ASSOCIATED FORMS IN */
 /*                            BCANON. */
 /*              CORTOP        LDACOR INDEX INDICATING RELATIVE POSITION */
 /*                            OF FORM BEGINNING AT LDATOP IN BCANON. */
 /*              NOLDAS        TOTAL NUMBER OF FORMS CURRENTLY IN CORE. */
 /*              RECNUM        LAST RECORD NUMBER ASSIGNED TO A FORM. */
 /*              KANIND        CANONICAL FORM INDEX IN BLANK COMMON */
 /* NOTES        THE FIRST 40 POSITIONS OF UNLABELED COMMON ARE RESERVED */
 /*              FOR NON LARGE DATA ARRAY CANONICAL FORMS OF SURFACES */
 /*              USED IN A MOTION STATEMENT AND ARE REFERED TO BY */
 /*              REFERENCING THE CANON ARRAY. THE REMAINING SPACE IS USED */
 /*              FOR LARGE DATA ARRAY CANONICAL FORM STORAGE AND IS */
 /*              REFERENCED BY REFERING TO THE BCANON ARRAY. MAXLDA */
 /*              CONTAINS THE SIZE OF BCANON. */
 /* IMPLIED ASSUMPTION.  IF LDAFLG=1 FOR WRITE, IT IS ASSUMED THAT */
 /*         THE CANON FORM IS LOCATED IN CANON(41) ON, EVEN THOUGH */
 /*         LARGE DATA IS PASSED AS AN ADDRESS. */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /* ...                SYSTEM I/O FILES */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   STORAGE ADDRESS FUNCTION */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /* ---       LOCAL VARIABLES */
 /* ... SAVE LOCAL VARIABLES */
     /* Parameter adjustments */
     --canloc;
     --ldaary;
     /* Function Body */
 /* ---      DETERMINE IF A READ, WRITE, OR AN UNDEFINITION. */
     lda[1] = (integer) ldaary[2];
     if (! ckdef_(&ldaary[1])) {
     lda[0] = (integer) ldaary[1];
     }
     switch (*ldaflg) {
     case 1:  goto L10;
     case 2:  goto L200;
     case 3:  goto L220;
     case 4:  goto L500;
     case 5:  goto L10;
     case 6:  goto L700;
     case 7:  goto L800;
     }
 /* RETURN, WHEN WRONG LDAFLG */
     return 0;
 /* ---      WRITE NEWLY CREATED CANONICAL FORM. */
 /* ---      ASSIGN THE C.F. A RECORD NUMBER. */
 L10:
     recnum = -5;
     tapop_(&symfil_1.axfile, &recnum);
     canloc[1] = (doublereal) recnum;
     lda[0] = recnum;
 /* ---      WRITE THE CANONICAL FORM AND UPDATE THE DICTIONARY OF CANONICA */
 /* ---      FORMS CURRENTLY IN MEMORY. */
     nr = 0;
 /* ---      BRANCH TO ERROR IF LDA EXCEEDED SPACE AVAILABLE */
     if (lda[1] >= maxlda_1.maxlda) {
     goto L410;
     }
     if (*ldaflg == 5) {
     goto L12;
     }
     j = lda[1] << 1;
 /* ---      COMPUTE R*8 FIELD INDEX OF CANONICAL FORM IN BLANK COMMON */
     kanind = (addrss_(&ldaary[1]) - addrss_(canon)) / 8 + 1;
 /* ---      REPLACE ON EXTERNAL STORAGE RECORD NUMBER BY STORAGE INDEX */
     canloc[1] = (doublereal) kanind;
     awrite_(&symfil_1.axfile, &nr, &canloc[1], &j, &ir);
 /* ---      RESTORE RECORD NUMBER */
     canloc[1] = (doublereal) lda[0];
     if (ir != 0) {
     goto L409;
     }
 L12:
     ldatop = 1;
     cortop = 1;
 /*  KONTROLLE OB DIE OBERFLAECHE AN DER VERMUTETEN STELLE LIEGT */
     for (i__ = 1; i__ <= 10; ++i__) {
     if (canloc[i__] != bcanon[i__ - 1]) {
         goto L235;
     }
 /* L11: */
     }
     goto L250;
 /* ---      READ A CANONICAL FORM INTO A SPECIFIC LOCATION. */
 /* ---      READ THE CANONICAL FORM AND RETURN TO CALLER. */
 L200:
     j = lda[1] << 1;
     aread_(&symfil_1.axfile, lda, &canloc[1], &j, &ir);
     kanind = (integer) canloc[1];
     if ((d__1 = canon[kanind - 1] - ldaary[1], abs(d__1)) > .5f) {
     goto L1100;
     }
     canloc[1] = (doublereal) lda[0];
     goto L9999;
 /* ---      READ A CANONICAL FORM INTO THE NEXT AVAILABLE AREA. */
 /* ---      CHECK TO SEE IF CANONICAL FORM IS ALREADY IN CORE. */
 L220:
     *aaa = canloc[1];
     if (noldas == 0) {
     goto L231;
     }
     i__1 = noldas;
     for (i__ = 1; i__ <= i__1; ++i__) {
     if (ldacor[(i__ << 1) - 2] != lda[0]) {
         goto L230;
     }
     *jjj = ldacor[(i__ << 1) - 1] + 40;
     canloc[1] = *aaa;
     goto L9999;
 L230:
     ;
     }
 L231:
 /* ---      CANONICAL FORM IS NOT IN CORE,POSITION TAPE TO FORM RECORD */
 /* ---      READ FORM INTO NEXT AVAILABLE LOCATION IN UNLABELED COMMON */
 /* ---      CHECK IF FORM WILL FIT ABOVE LDATOP */
 L235:
     if (maxlda_1.maxlda - ldatop < lda[1]) {
     goto L400;
     }
 /* ---      FORM WILL FIT */
 /* L240: */
     *jjj = ldatop + 40;
     canloc[1] = *aaa;
 /*   LDACOR(2,MAXLDC) KANN UEBERSPEICHERT WERDEN */
     if (cortop >= maxldc) {
     goto L400;
     }
     j = lda[1] << 1;
     aread_(&symfil_1.axfile, lda, &bcanon[ldatop - 1], &j, &ir);
     kanind = (integer) bcanon[ldatop - 1];
     if ((d__1 = canon[kanind - 1] - ldaary[1], abs(d__1)) > .5f) {
     goto L1100;
     }
     bcanon[ldatop - 1] = (doublereal) lda[0];
     ++cortop;
 L250:
     k = 0;
 /* ---      CHECK IF NEW CORTOP LESS THAN NOLDAS */
     if (noldas - cortop >= 0) {
     goto L260;
     } else {
     goto L320;
     }
 /* ---      DETERMINE THE NUMBER OF FORMS ABOVE LDATOP THAT WERE OVERLAID */
 L260:
     i__1 = noldas;
     for (n = cortop; n <= i__1; ++n) {
     if (ldacor[(n << 1) - 1] >= ldatop + lda[1]) {
         goto L280;
     }
 /* L270: */
     ++k;
     }
     goto L320;
 /* ---      DETERMINE WHETHER LDACOR ENTRIES HAVE TO BE REPOSITIONED */
 L280:
     if ((i__1 = k - 1) < 0) {
     goto L290;
     } else if (i__1 == 0) {
     goto L320;
     } else {
     goto L310;
     }
 /* ---      SLIDE ENTRIES STARTING WITH CORTOP UP ONE POSITION */
 L290:
     if (noldas < maxldc) {
     goto L291;
     }
     k = 1;
     goto L320;
 L291:
     i__1 = noldas;
     for (i__ = cortop; i__ <= i__1; ++i__) {
     j = noldas + cortop - i__;
     ldacor[(j + 1 << 1) - 2] = ldacor[(j << 1) - 2];
 /* L300: */
     ldacor[(j + 1 << 1) - 1] = ldacor[(j << 1) - 1];
     }
     goto L320;
 /* ---      SLIDE GOOD ENTRIES ABOVE CORTOP + 1 DOWN SO THAT THE FIRST GOO */
 /* ---      ENTRY COINCIDES WITH CORTOP + 1 */
 L310:
     i__1 = noldas;
     for (i__ = n; i__ <= i__1; ++i__) {
     j = cortop + 1 - n + i__;
     ldacor[(j << 1) - 2] = ldacor[(i__ << 1) - 2];
 /* L315: */
     ldacor[(j << 1) - 1] = ldacor[(i__ << 1) - 1];
     }
 /* ---      INSERT NEW ENTRY IN LDACOR, ADJUST LDATOP AND NOLDAS */
 L320:
     ldacor[(cortop << 1) - 2] = lda[0];
     ldacor[(cortop << 1) - 1] = ldatop;
     ldatop += lda[1];
     noldas = noldas - k + 1;
     goto L9999;
 /* ---      FORM WILL NOT FIT ABOVE LDATOP. READ IT IN STARTING AT BCANON( */
 L400:
     if (maxlda_1.maxlda >= lda[1]) {
     goto L401;
     }
 /* NOT ENOUGH ROOM IN >LDA< */
 L410:
     error_(&c__5061, "APT094  ", (ftnlen)8);
     goto L500;
 /* NOT ENOUGH ROOM ON FILE 9(EXTERNAL LDA) */
 L409:
     error_(&c__5062, "APT094  ", (ftnlen)8);
     ldatop = 1;
     cortop = 1;
     noldas = 0;
     goto L510;
 L401:
     *jjj = 41;
     canloc[1] = *aaa;
 /* L402: */
     j = lda[1] << 1;
     aread_(&symfil_1.axfile, lda, bcanon, &j, &ir);
     kanind = (integer) bcanon[0];
     if ((d__1 = canon[kanind - 1] - ldaary[1], abs(d__1)) > .5f) {
     goto L1100;
     }
     bcanon[0] = (doublereal) lda[0];
     ldatop = 1;
     cortop = 1;
     goto L250;
 /* ---      DEFINITION ERROR : ELIMINATE LDA FROM LIST */
 L500:
     if (noldas == 0) {
     goto L510;
     }
     i__1 = noldas;
     for (i__ = 1; i__ <= i__1; ++i__) {
     if (ldacor[(i__ << 1) - 2] == lda[0]) {
         goto L506;
     }
 /* L503: */
     }
     goto L510;
 L506:
     if (i__ <= cortop) {
     --cortop;
     }
     --noldas;
     if (noldas == 0) {
     goto L510;
     }
     if (noldas < i__) {
     goto L510;
     }
     i__1 = noldas;
     for (n = i__; n <= i__1; ++n) {
     ldacor[(n << 1) - 2] = ldacor[(n + 1 << 1) - 2];
 /* L508: */
     ldacor[(n << 1) - 1] = ldacor[(n + 1 << 1) - 1];
     }
 L510:
     undef_(&ldaary[1]);
     goto L9998;
 /* ERROR DURING READ OF A LARGE DATA ARRAY >LDA< FROM FILE 9. */
 /* ---      RECORD NUMBER ERROR */
 /* ---      PRINT ERROR MESSAGE ON VLFILE AND UNDEFINE THE CANONICAL FORM. */
 L1100:
     error_(&c__5060, "APT094  ", (ftnlen)8);
     goto L500;
 L9999:
     ldaary[1] = (doublereal) lda[0];
 /* . */
 L9998:
     return 0;
 /*  UPDATE IN PLACE */
 L700:
     if (noldas == 0) {
     goto L730;
     }
     i__1 = noldas;
     for (i__ = 1; i__ <= i__1; ++i__) {
     if (ldacor[(i__ << 1) - 2] == lda[0]) {
         goto L720;
     }
 /* L710: */
     }
     goto L730;
 /*   GEOMETRIE IN CORE */
 L720:
     n = lda[1];
     nn = ldacor[(i__ << 1) - 1];
     i__1 = n;
     for (i__ = 1; i__ <= i__1; ++i__) {
     bcanon[nn - 1] = canloc[i__];
 /* L725: */
     ++nn;
     }
 /*  WRITE UPDATE */
 L730:
     j = lda[1] << 1;
     nr = lda[0];
 /* ---      COMPUTE R*8 FIELD INDEX OF CANONICAL FORM IN BLANK COMMON */
     kanind = (addrss_(&ldaary[1]) - addrss_(canon)) / 8 + 1;
 /* ---      REPLACE ON EXTERNAL STORAGE RECORD NUMBER BY STORAGE INDEX */
     canloc[1] = (doublereal) kanind;
     awrite_(&symfil_1.axfile, &nr, &canloc[1], &j, &ir);
 /* ---      RESTORE RECORD NUMBER */
     canloc[1] = (doublereal) lda[0];
     return 0;
 /* ---      READ SHORT */
 L800:
     j = 2;
     aread_(&symfil_1.axfile, lda, &canloc[1], &j, &ir);
     kanind = (integer) canloc[1];
     return 0;
 } /* apt094_ */
Variable Documentation
struct { ... } _BLNK__
integer axfile
Definition at line 24 of file APT094.c.
integer c__5060 = 5060 static
Definition at line 48 of file APT094.c.
Referenced by apt094_().
integer c__5061 = 5061 static
Definition at line 46 of file APT094.c.
Referenced by apt094_().
integer c__5062 = 5062 static
Definition at line 47 of file APT094.c.
Referenced by apt094_().
integer clfil3
Definition at line 24 of file APT094.c.
integer clfile
Definition at line 24 of file APT094.c.
integer clfilp
Definition at line 24 of file APT094.c.
doublereal com[36000]
Definition at line 18 of file APT094.c.
integer cpfile
Definition at line 24 of file APT094.c.
integer elfil1
Definition at line 24 of file APT094.c.
integer elfil2
Definition at line 24 of file APT094.c.
integer elfil3
Definition at line 24 of file APT094.c.
integer elfil4
Definition at line 24 of file APT094.c.
integer elfile
Definition at line 24 of file APT094.c.
integer exfile
Definition at line 24 of file APT094.c.
integer iblk1
Definition at line 39 of file APT094.c.
struct { ... } idef_
integer ierror
Definition at line 39 of file APT094.c.
integer infile__
Definition at line 24 of file APT094.c.
integer ispare[26]
Definition at line 24 of file APT094.c.
integer kwrdsz
Definition at line 39 of file APT094.c.
integer ldafil
Definition at line 24 of file APT094.c.
integer ldasiz
Definition at line 39 of file APT094.c.
integer libfil
Definition at line 24 of file APT094.c.
integer mactxt
Definition at line 24 of file APT094.c.
integer maxlda
Definition at line 33 of file APT094.c.
struct { ... } maxlda_
integer nfil12
Definition at line 24 of file APT094.c.
integer nfil13
Definition at line 24 of file APT094.c.
integer pnchfl
Definition at line 24 of file APT094.c.
integer pofile
Definition at line 24 of file APT094.c.
integer pxfile
Definition at line 24 of file APT094.c.
integer surfad[4]
Definition at line 39 of file APT094.c.
struct { ... } symfil_
integer tifile
Definition at line 24 of file APT094.c.
integer vlfile
Definition at line 24 of file APT094.c.
integer xcan
Definition at line 24 of file APT094.c.
integer xnum
Definition at line 24 of file APT094.c.