My Project: APT053.c File Reference
APT053.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define ldef_1 ldef_
#define idef_1 idef_
#define knumbr_1 knumbr_
#define pt ((doublereal *)&dshar3_1 + 21)
#define st ((doublereal *)&dshar3_1 + 37)
Functions
int apt053_ (doublereal *result, doublereal *pt1, doublereal *pt2, doublereal *pt3, doublereal *pt4)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file APT053.c.
Referenced by apt053_().
#define dshar3_1 dshar3_
Definition at line 28 of file APT053.c.
#define idef_1 idef_
Definition at line 49 of file APT053.c.
Referenced by apt053_().
#define knumbr_1 knumbr_
Definition at line 57 of file APT053.c.
Referenced by apt053_().
#define ldef_1 ldef_
Definition at line 43 of file APT053.c.
Referenced by apt053_().
#define pt ((doublereal *)&dshar3_1 + 21)
Referenced by apt053_().
#define st ((doublereal *)&dshar3_1 + 37)
Referenced by apt053_(), and baltol_().
#define znumbr_1 znumbr_
Definition at line 36 of file APT053.c.
Referenced by apt053_().
Function Documentation
int apt053_ (doublereal * result, doublereal * pt1, doublereal * pt2, doublereal * pt3, doublereal * pt4)
Definition at line 90 of file APT053.c.
References apt075_(), ckdef_(), def_1, defext_(), i__, idef_1, j, knumbr_1, ldef_1, pt, pt1, result, st, and znumbr_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static integer k57 = 57;
     /* System generated locals */
     doublereal d__1, d__2;
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     static integer i__, j;
 #define pt ((doublereal *)&dshar3_1 + 21)
 #define st ((doublereal *)&dshar3_1 + 37)
     extern /* Subroutine */ int apt075_(doublereal *, doublereal *);
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int defext_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --pt4;
     --pt3;
     --pt2;
     --pt1;
     --result;
     /* Function Body */
 /* ...     MOVE INPUTS TO SCRATCH STORAGE, CHECK INPUT */
     ldef_1.unflag = ckdef_(&pt4[1]);
     for (i__ = 1; i__ <= 3; ++i__) {
     st[i__ * 3 - 3] = pt1[i__];
     st[i__ * 3 - 2] = pt2[i__];
     st[i__ * 3 - 1] = pt3[i__];
 /* L10: */
     ldef_1.unflag = ldef_1.unflag || ckdef_(&st[i__ - 1]);
     }
 /* ...     FORM EQUATION COEFFICIENTS */
     for (i__ = 1; i__ <= 3; ++i__) {
     pt[(i__ << 2) - 1] = znumbr_1.z0;
     for (j = 1; j <= 3; ++j) {
         pt[i__ + (j << 2) - 5] = st[j + i__ * 3 - 4] - pt4[i__];
 /* L20: */
 /* Computing 2nd power */
         d__1 = st[i__ + j * 3 - 4];
 /* Computing 2nd power */
         d__2 = pt4[j];
         pt[(i__ << 2) - 1] = pt[(i__ << 2) - 1] + d__1 * d__1 - d__2 *
             d__2;
     }
 /* L30: */
 /* Computing 2nd power */
     d__1 = pt4[i__];
     def_1.r__[3] += d__1 * d__1;
     }
 /* ...     SOLVE FOR SPHERE EQUATION COEFFS. */
     apt075_(def_1.r__, pt);
 /* ...     CHECK FOR COPLANAR POINTS */
     if (idef_1.ierror >= knumbr_1.k1) {
     idef_1.ierror = k57;
     }
 /* ...     COMPUTE RADIUS TERM */
     for (i__ = 1; i__ <= 3; ++i__) {
     def_1.r__[i__ - 1] /= znumbr_1.z2;
 /* L40: */
     def_1.r__[3] += def_1.r__[i__ - 1] * (def_1.r__[i__ - 1] -
         znumbr_1.z2 * pt4[i__]);
     }
     def_1.r__[3] = sqrt(def_1.r__[3]);
     defext_(&result[1]);
     return 0;
 } /* apt053_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file APT053.c.
doublereal ahold[8]
Definition at line 18 of file APT053.c.
logical altmlt
Definition at line 39 of file APT053.c.
logical bnderr
Definition at line 39 of file APT053.c.
logical boundf
Definition at line 39 of file APT053.c.
doublereal c1[8]
Definition at line 18 of file APT053.c.
doublereal c__[7]
Definition at line 25 of file APT053.c.
logical canflg
Definition at line 39 of file APT053.c.
struct { ... } def_
doublereal degrad
Definition at line 31 of file APT053.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file APT053.c.
integer iblk1
Definition at line 46 of file APT053.c.
struct { ... } idef_
integer ierror
Definition at line 46 of file APT053.c.
logical jcs
Definition at line 39 of file APT053.c.
logical jds
Definition at line 39 of file APT053.c.
integer k0
Definition at line 52 of file APT053.c.
integer k1
Definition at line 52 of file APT053.c.
integer k10
Definition at line 52 of file APT053.c.
integer k1013
Definition at line 52 of file APT053.c.
integer k12
Definition at line 52 of file APT053.c.
integer k13
Definition at line 52 of file APT053.c.
integer k15
Definition at line 52 of file APT053.c.
integer k16
Definition at line 52 of file APT053.c.
integer k18
Definition at line 52 of file APT053.c.
integer k19
Definition at line 52 of file APT053.c.
integer k1e4
Definition at line 52 of file APT053.c.
integer k1e6
Definition at line 52 of file APT053.c.
integer k2
Definition at line 52 of file APT053.c.
integer k23
Definition at line 52 of file APT053.c.
integer k24
Definition at line 52 of file APT053.c.
integer k25
Definition at line 52 of file APT053.c.
integer k26
Definition at line 52 of file APT053.c.
integer k27
Definition at line 52 of file APT053.c.
integer k29
Definition at line 52 of file APT053.c.
integer k3
Definition at line 52 of file APT053.c.
integer k30
Definition at line 52 of file APT053.c.
integer k31
Definition at line 52 of file APT053.c.
integer k32
Definition at line 52 of file APT053.c.
integer k33
Definition at line 52 of file APT053.c.
integer k34
Definition at line 52 of file APT053.c.
integer k4
Definition at line 52 of file APT053.c.
integer k44
Definition at line 52 of file APT053.c.
integer k45
Definition at line 52 of file APT053.c.
integer k46
Definition at line 52 of file APT053.c.
integer k47
Definition at line 52 of file APT053.c.
integer k48
Definition at line 52 of file APT053.c.
integer k5
Definition at line 52 of file APT053.c.
integer k50
Definition at line 52 of file APT053.c.
integer k51
Definition at line 52 of file APT053.c.
integer k52
Definition at line 52 of file APT053.c.
integer k6
Definition at line 52 of file APT053.c.
integer k7
Definition at line 52 of file APT053.c.
integer k8
Definition at line 52 of file APT053.c.
integer k9
Definition at line 52 of file APT053.c.
integer km1
Definition at line 52 of file APT053.c.
struct { ... } knumbr_
integer kwrdsz
Definition at line 46 of file APT053.c.
doublereal l[4]
Definition at line 25 of file APT053.c.
integer ldasiz
Definition at line 46 of file APT053.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file APT053.c.
doublereal p[16]
Definition at line 25 of file APT053.c.
logical pchlst
Definition at line 39 of file APT053.c.
doublereal pi
Definition at line 31 of file APT053.c.
logical prnton
Definition at line 39 of file APT053.c.
doublereal r__[10]
Definition at line 18 of file APT053.c.
doublereal ref[8]
Definition at line 18 of file APT053.c.
logical refflg
Definition at line 39 of file APT053.c.
logical refmot
Definition at line 39 of file APT053.c.
doublereal sc[16]
Definition at line 25 of file APT053.c.
logical subflg
Definition at line 39 of file APT053.c.
integer surfad[4]
Definition at line 46 of file APT053.c.
doublereal t[12]
Definition at line 25 of file APT053.c.
doublereal t1[12]
Definition at line 25 of file APT053.c.
logical tabprt
Definition at line 39 of file APT053.c.
logical unflag
Definition at line 39 of file APT053.c.
doublereal v[10]
Definition at line 25 of file APT053.c.
doublereal z0
Definition at line 31 of file APT053.c.
doublereal z1
Definition at line 31 of file APT053.c.
doublereal z10
Definition at line 31 of file APT053.c.
doublereal z11em1
Definition at line 31 of file APT053.c.
doublereal z12em1
Definition at line 31 of file APT053.c.
doublereal z1e38
Definition at line 31 of file APT053.c.
doublereal z1e6
Definition at line 31 of file APT053.c.
doublereal z1em1
Definition at line 31 of file APT053.c.
doublereal z1em2
Definition at line 31 of file APT053.c.
doublereal z1em3
Definition at line 31 of file APT053.c.
doublereal z1em5
Definition at line 31 of file APT053.c.
doublereal z1em6
Definition at line 31 of file APT053.c.
doublereal z1em7
Definition at line 31 of file APT053.c.
doublereal z1em9
Definition at line 31 of file APT053.c.
doublereal z2
Definition at line 31 of file APT053.c.
doublereal z3
Definition at line 31 of file APT053.c.
doublereal z5
Definition at line 31 of file APT053.c.
doublereal z5em1
Definition at line 31 of file APT053.c.
doublereal z5em6
Definition at line 31 of file APT053.c.
doublereal z6em1
Definition at line 31 of file APT053.c.
doublereal z90
Definition at line 31 of file APT053.c.
doublereal z9em1
Definition at line 31 of file APT053.c.
logical zflag
Definition at line 39 of file APT053.c.
doublereal zm1
Definition at line 31 of file APT053.c.
struct { ... } znumbr_