My Project: APT110.c File Reference
APT110.c File Reference
#include "f2c.h"
Macros
#define _BLNK__1 _BLNK__
#define ibugg_1 ibugg_
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int apt110_ (doublereal *arg1, doublereal *arg2)
Variables
struct {
doublereal com [36000]
} _BLNK__
struct {
integer ibug
integer ipcolc
integer ipcomc
} ibugg_
static integer c__2 = 2
static integer c__1 = 1
static integer c__6 = 6
static integer c__3 = 3
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 21 of file APT110.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define ibugg_1 ibugg_
Definition at line 27 of file APT110.c.
Referenced by apt110_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
Referenced by apt110_().
Function Documentation
int apt110_ (doublereal * arg1, doublereal * arg2)
Definition at line 38 of file APT110.c.
References apt094_(), bad_(), c__1, c__2, c__3, c__6, cprint_(), gclear_(), golovo_(), gomill_(), holfrm_(), i__, ibugg_1, intsec_(), mode, nt, scon_(), smil_(), sscan, test, and zero.
Referenced by xcall_().
 {
     /* Initialized data */
     static char xsmil[6*7] = "SCON  " "SMIL  " "GCLEAR" "GOMILL" "INTSEC"
         "GOLOFT" "PLOTFT";
     static doublereal zero = 0.;
     /* System generated locals */
     address a__1[3];
     integer i__1, i__2[3];
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Subroutine */ int s_cat(char *, char **, integer *, integer *, ftnlen);
     /* Local variables */
     static integer i__, nt;
     extern /* Subroutine */ int bad_(integer *, integer *, char *, doublereal
         *, ftnlen);
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer nwd;
     static doublereal zwi;
     static integer mode;
     extern /* Subroutine */ int scon_(void), smil_(void);
     static char test[6];
     extern /* Subroutine */ int apt094_(integer *, doublereal *, doublereal *)
         ;
 #define canon ((doublereal *)&_BLNK__1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     static char badmsg[66];
     extern /* Subroutine */ int gclear_(doublereal *);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int gomill_(void), intsec_(void), holfrm_(
         doublereal *, char *, integer *, integer *, integer *, ftnlen),
         cprint_(char *, ftnlen);
     static doublereal fdummy[2];
     extern /* Subroutine */ int golovo_(doublereal *);
 /* -- MAIN PROGRAM FOR REGIONAL MILLING(SMIL OR SCON) */
 /* -- PART PROGRAMMER INPUT LANGUAGE IS RESIDENT IN BLANK COMMON. */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
     nt = (integer) sscan[1];
     nt <<= 1;
     if (ibugg_1.ibug == 11) {
     i__1 = -nt;
     bad_(&i__1, &c__2, "CANN", sscan, (ftnlen)4);
     }
     holfrm_(arg1, test, &c__1, &c__6, &nwd, (ftnlen)6);
     for (i__ = 1; i__ <= 7; ++i__) {
     if (s_cmp(test, xsmil + (i__ - 1) * 6, (ftnlen)6, (ftnlen)6) != 0) {
         goto L8;
     }
     mode = 5;
     fdummy[0] = zero;
     fdummy[1] = sscan[1] - 1.;
     zwi = sscan[0];
     apt094_(&mode, fdummy, sscan);
     sscan[0] = zwi;
     switch (i__) {
         case 1:  goto L1;
         case 2:  goto L2;
         case 3:  goto L3;
         case 4:  goto L4;
         case 5:  goto L5;
         case 6:  goto L6;
         case 7:  goto L6;
     }
 L1:
     scon_();
     goto L30;
 L2:
     smil_();
     goto L30;
 L3:
     gclear_(arg2);
     goto L30;
 L4:
     gomill_();
     goto L30;
 L5:
     intsec_();
     goto L30;
 L6:
     golovo_(arg2);
     goto L30;
 L8:
     ;
     }
 /* L10: */
 /* Writing concatenation */
     i__2[0] = 10, a__1[0] = " ARGUMENT ";
     i__2[1] = 6, a__1[1] = test;
     i__2[2] = 28, a__1[2] = " NOT VALID IN CALL TO APT110";
     s_cat(badmsg, a__1, i__2, &c__3, (ftnlen)66);
     cprint_(badmsg, (ftnlen)66);
 L30:
     return 0;
 } /* apt110_ */
Variable Documentation
struct { ... } _BLNK__
integer c__1 = 1 static
Definition at line 32 of file APT110.c.
Referenced by apt110_().
integer c__2 = 2 static
Definition at line 31 of file APT110.c.
Referenced by apt110_().
integer c__3 = 3 static
Definition at line 34 of file APT110.c.
Referenced by apt110_().
integer c__6 = 6 static
Definition at line 33 of file APT110.c.
Referenced by apt110_().
doublereal com[36000]
Definition at line 18 of file APT110.c.
integer ibug
Definition at line 24 of file APT110.c.
struct { ... } ibugg_
integer ipcolc
Definition at line 24 of file APT110.c.
integer ipcomc
Definition at line 24 of file APT110.c.