My Project: APT106.c File Reference
APT106.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define znumbr_1 znumbr_
#define idef_1 idef_
#define _BLNK__1 _BLNK__
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int apt106_ (doublereal *result, doublereal *pat, doublereal *rn)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
doublereal com [36000]
} _BLNK__
static integer c__2 = 2
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 42 of file APT106.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Referenced by apt106_().
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define def_1 def_
Definition at line 22 of file APT106.c.
Referenced by apt106_().
#define idef_1 idef_
Definition at line 36 of file APT106.c.
Referenced by apt106_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define znumbr_1 znumbr_
Definition at line 30 of file APT106.c.
Referenced by apt106_().
Function Documentation
int apt106_ (doublereal * result, doublereal * pat, doublereal * rn)
Definition at line 67 of file APT106.c.
References apt094_(), bcanon, c__2, ckdef_(), def_1, defext_(), idef_1, n, npat_(), pat, result, and znumbr_1.
Referenced by xcall_().
 {
     /* Local variables */
     static integer n;
 #define can ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int npat_(doublereal *, integer *), apt094_(
         integer *, doublereal *, doublereal *);
     extern logical ckdef_(doublereal *);
 #define canon ((doublereal *)&_BLNK__1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int defext_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
     /* Parameter adjustments */
     --pat;
     --result;
     /* Function Body */
     if (ckdef_(&pat[1])) {
     goto L90;
     }
 /*              MOVE THE EXTERNAL CANONICAL FORM TO BCANON */
     apt094_(&c__2, &pat[1], bcanon);
     if (ckdef_(&pat[1])) {
     goto L90;
     }
 /*              CHECK TO SEE THAT N IS LESS THAN OR EQUAL TO */
 /*              THE NUMBER OF POINTS IN THIS PATERN */
     if (*rn > bcanon[3]) {
     goto L95;
     }
     n = (integer) (*rn + znumbr_1.z1em5);
 /*          DETERMINE AND STORE THE COORDINATES OF THE POINT */
     npat_(def_1.r__, &n);
 L10:
     defext_(&result[1]);
     return 0;
 /*          REFERENCED PATERN HAS NOT BEEN PREVIOUSLY CORRECTLY DEFINED */
 L90:
     idef_1.ierror = 37;
     goto L10;
 /*          THE NUMBER OF THE REQUESTED POINT IS GREATER THAN THE */
 /*          NUMBER OF POINTS IN THE PATERN */
 L95:
     idef_1.ierror = 38;
     goto L10;
 } /* apt106_ */
Variable Documentation
struct { ... } _BLNK__
doublereal a[24]
Definition at line 18 of file APT106.c.
doublereal ahold[8]
Definition at line 18 of file APT106.c.
doublereal c1[8]
Definition at line 18 of file APT106.c.
integer c__2 = 2 static
Definition at line 46 of file APT106.c.
Referenced by apt106_().
doublereal com[36000]
Definition at line 39 of file APT106.c.
struct { ... } def_
doublereal degrad
Definition at line 25 of file APT106.c.
integer iblk1
Definition at line 33 of file APT106.c.
struct { ... } idef_
integer ierror
Definition at line 33 of file APT106.c.
integer kwrdsz
Definition at line 33 of file APT106.c.
integer ldasiz
Definition at line 33 of file APT106.c.
doublereal ln1[5]
Definition at line 18 of file APT106.c.
doublereal pi
Definition at line 25 of file APT106.c.
doublereal r__[10]
Definition at line 18 of file APT106.c.
doublereal ref[8]
Definition at line 18 of file APT106.c.
integer surfad[4]
Definition at line 33 of file APT106.c.
doublereal z0
Definition at line 25 of file APT106.c.
doublereal z1
Definition at line 25 of file APT106.c.
doublereal z10
Definition at line 25 of file APT106.c.
doublereal z11em1
Definition at line 25 of file APT106.c.
doublereal z12em1
Definition at line 25 of file APT106.c.
doublereal z1e38
Definition at line 25 of file APT106.c.
doublereal z1e6
Definition at line 25 of file APT106.c.
doublereal z1em1
Definition at line 25 of file APT106.c.
doublereal z1em2
Definition at line 25 of file APT106.c.
doublereal z1em3
Definition at line 25 of file APT106.c.
doublereal z1em5
Definition at line 25 of file APT106.c.
doublereal z1em6
Definition at line 25 of file APT106.c.
doublereal z1em7
Definition at line 25 of file APT106.c.
doublereal z1em9
Definition at line 25 of file APT106.c.
doublereal z2
Definition at line 25 of file APT106.c.
doublereal z3
Definition at line 25 of file APT106.c.
doublereal z5
Definition at line 25 of file APT106.c.
doublereal z5em1
Definition at line 25 of file APT106.c.
doublereal z5em6
Definition at line 25 of file APT106.c.
doublereal z6em1
Definition at line 25 of file APT106.c.
doublereal z90
Definition at line 25 of file APT106.c.
doublereal z9em1
Definition at line 25 of file APT106.c.
doublereal zm1
Definition at line 25 of file APT106.c.
struct { ... } znumbr_