My Project: APT103.c File Reference
APT103.c File Reference
#include "f2c.h"
Macros
#define ldef_1 ldef_
#define idef_1 idef_
#define _BLNK__1 _BLNK__
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define ttest (equiv_4)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define dlrtst ((logical *)equiv_4)
Functions
int apt103_ (doublereal *objctn, doublereal *boundn, integer *m)
Variables
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
doublereal com [36000]
} _BLNK__
static integer c__1 = 1
static integer c__3 = 3
static integer c__85 = 85
static integer c__86 = 86
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 34 of file APT103.c.
Referenced by apt103_().
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define dlrtst ((logical *)equiv_4)
Referenced by apt103_().
#define idef_1 idef_
Definition at line 28 of file APT103.c.
Referenced by apt103_().
#define ldef_1 ldef_
Definition at line 22 of file APT103.c.
Referenced by apt103_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define ttest (equiv_4)
Referenced by apt103_().
Function Documentation
int apt103_ (doublereal * objctn, doublereal * boundn, integer * m)
Definition at line 99 of file APT103.c.
References _BLNK__1, addrss_(), c__1, c__3, c__85, c__86, ckstr_(), dlr, dlrtst, error_(), holfrm_(), idef_1, incan_(), isize, isub, ldef_1, mode, n, print_(), test, ttest, undef_(), and unpack_().
Referenced by xcall_().
 {
     /* Initialized data */
     static char dlr[1] = "$";
     /* System generated locals */
     static doublereal equiv_4[4];
     /* Local variables */
     static integer n;
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer nwd, mode, isub;
     static logical err85, err86;
     static char test[1];
     extern /* Subroutine */ int incan_(integer *);
 #define canon ((doublereal *)&_BLNK__1)
     static integer iobjn;
     extern /* Subroutine */ int undef_(doublereal *);
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     static integer isize;
     extern logical ckstr_(doublereal *);
     extern /* Subroutine */ int error_(integer *, char *, ftnlen), print_(
         integer *, doublereal *, integer *);
 #define ttest (equiv_4)
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern integer addrss_(doublereal *);
     extern /* Subroutine */ int unpack_(doublereal *, integer *, integer *,
         integer *), holfrm_(logical *, char *, integer *, integer *,
         integer *, ftnlen);
     static integer iobjsz;
 #define dlrtst ((logical *)equiv_4)
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /*                                                                   *CD* */
     /* Parameter adjustments */
     --boundn;
     --objctn;
     /* Function Body */
 /*                                                                   *CD* */
     if (*m > 1) {
     goto L2;
     }
     n = 0;
     err85 = FALSE_;
     err86 = FALSE_;
     unpack_(&objctn[1], &mode, &iobjsz, &isub);
     if (*m == 0) {
     *m = 3;
     }
 L2:
     n += 2;
 /* ...  MAKE SURE OBJCTN IS NOT REDEFINED ERRONEOUSLY. */
     if (n > iobjsz) {
     goto L20;
     }
 /* ...  MAKE SURE BOUNDN IS PROPERLY DEFINED. */
     unpack_(&boundn[1], &mode, &isize, &isub);
     if (ckstr_(&boundn[1]) || isub != 0) {
     goto L10;
     }
 /*        * STORE NAME IN CANONICAL FORM */
     objctn[n - 1] = boundn[isize + 1];
 /* ...  IF BOUNDN IS AN UNASSIGNED NESTED ARGUMENT, GENERATE DIAGNOSTIC. */
     *ttest = objctn[n - 1];
     holfrm_(dlrtst, test, &c__1, &c__1, &nwd, (ftnlen)1);
     if (*(unsigned char *)test == *(unsigned char *)&dlr[0]) {
     err85 = TRUE_;
     }
 /* ...  DETERMINE INDEX FOR BOUNDN */
     iobjn = (addrss_(&boundn[1]) - addrss_(_BLNK__1.com)) / idef_1.kwrdsz + 1;
     if (ldef_1.canflg) {
     incan_(&iobjn);
     }
     objctn[n] = (doublereal) (iobjn - idef_1.iblk1);
 L5:
     if (*m == 3) {
     goto L30;
     }
     return 0;
 /* ...  ERROR 85:  REFERENCED ELEMENT NOT PROPERLY DEFINED. */
 L10:
     undef_(&objctn[n - 1]);
     objctn[n] = 0.;
     err85 = TRUE_;
     goto L5;
 /* ...  ERROR 86:  BOUNDED GEOMETRY ELEMENT HAS BEEN REDEFINED WITH */
 /*     A DIFFERENT NUMBER OF OPERANDS. */
 L20:
     err86 = TRUE_;
     if (*m != 3) {
     goto L40;
     }
 L30:
     if (n != iobjsz) {
     err86 = TRUE_;
     }
     if (ldef_1.prnton) {
     print_(&c__3, &objctn[1], &c__1);
     }
     if (err85) {
     error_(&c__85, "APT103  ", (ftnlen)8);
     }
     if (err86) {
     error_(&c__86, "APT103  ", (ftnlen)8);
     }
     if (err86 || err85) {
     ldef_1.bnderr = TRUE_;
     }
 L40:
     return 0;
 } /* apt103_ */
Variable Documentation
struct { ... } _BLNK__
logical altmlt
Definition at line 18 of file APT103.c.
logical bnderr
Definition at line 18 of file APT103.c.
logical boundf
Definition at line 18 of file APT103.c.
integer c__1 = 1 static
Definition at line 38 of file APT103.c.
Referenced by apt103_().
integer c__3 = 3 static
Definition at line 39 of file APT103.c.
Referenced by apt103_().
integer c__85 = 85 static
Definition at line 40 of file APT103.c.
Referenced by apt103_().
integer c__86 = 86 static
Definition at line 41 of file APT103.c.
Referenced by apt103_().
logical canflg
Definition at line 18 of file APT103.c.
doublereal com[36000]
Definition at line 31 of file APT103.c.
integer iblk1
Definition at line 25 of file APT103.c.
struct { ... } idef_
integer ierror
Definition at line 25 of file APT103.c.
logical jcs
Definition at line 18 of file APT103.c.
logical jds
Definition at line 18 of file APT103.c.
integer kwrdsz
Definition at line 25 of file APT103.c.
integer ldasiz
Definition at line 25 of file APT103.c.
struct { ... } ldef_
logical pchlst
Definition at line 18 of file APT103.c.
logical prnton
Definition at line 18 of file APT103.c.
logical refflg
Definition at line 18 of file APT103.c.
logical refmot
Definition at line 18 of file APT103.c.
logical subflg
Definition at line 18 of file APT103.c.
integer surfad[4]
Definition at line 25 of file APT103.c.
logical tabprt
Definition at line 18 of file APT103.c.
logical unflag
Definition at line 18 of file APT103.c.
logical zflag
Definition at line 18 of file APT103.c.