My Project: APT104.c File Reference
APT104.c File Reference
#include "f2c.h"
Macros
#define _BLNK__1 _BLNK__
#define ldef_1 ldef_
#define idef_1 idef_
#define knumbr_1 knumbr_
#define symfil_1 symfil_
#define darray_1 darray_
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int apt104_ (doublereal *part)
Variables
struct {
doublereal com [36000]
} _BLNK__
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
struct {
doublereal darray [15]
} darray_
static integer c__0 = 0
static integer c__1 = 1
static integer c__6 = 6
static integer c__7 = 7
static integer c__13 = 13
static integer c__68 = 68
static integer c__114 = 114
static integer c__85 = 85
static integer c__5 = 5
static integer c__11 = 11
static integer c__12 = 12
static integer c__3 = 3
static integer c__8 = 8
static integer c__30 = 30
static integer c__89 = 89
static integer c__90 = 90
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 21 of file APT104.c.
Referenced by apt104_().
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define darray_1 darray_
Definition at line 57 of file APT104.c.
Referenced by apt104_().
#define idef_1 idef_
Definition at line 34 of file APT104.c.
Referenced by apt104_().
#define knumbr_1 knumbr_
Definition at line 42 of file APT104.c.
Referenced by apt104_().
#define ldef_1 ldef_
Definition at line 28 of file APT104.c.
Referenced by apt104_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define symfil_1 symfil_
Definition at line 51 of file APT104.c.
Function Documentation
int apt104_ (doublereal * part)
Definition at line 123 of file APT104.c.
References _BLNK__1, addrss_(), badnam_(), bcdf_(), c__0, c__1, c__11, c__114, c__12, c__13, c__3, c__30, c__5, c__6, c__68, c__7, c__8, c__85, c__89, c__90, cform_(), ckdtr_(), ckstr_(), cprint_(), darray_1, error_(), gsurf_(), i__, iarray, iconv_(), idef_1, incan_(), index, is, isize, isub, k, knumbr_1, l, ldef_1, m, mode, unpack_(), and xcanon_().
Referenced by xcall_().
 {
     /* Initialized data */
     static integer kmax = 30;
     static integer ksmax = 24;
     /* Format strings */
     static char fmt_90[] = "";
     static char fmt_100[] = "";
     /* System generated locals */
     integer i__1, i__2;
     /* Local variables */
     static integer i__, k, l, m, nn, ks, is;
 #define can ((doublereal *)&_BLNK__1 + 40)
     extern integer bcdf_(char *, ftnlen);
     static integer iabs, mode, isub, mstk[30], isiz;
     extern /* Subroutine */ int incan_(integer *);
 #define canon ((doublereal *)&_BLNK__1)
     extern /* Subroutine */ int cform_();
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     extern logical ckdtr_(doublereal *);
     static integer index;
     extern /* Subroutine */ int iconv_(integer *, doublereal *, integer *,
         integer *);
     static integer isize[31];
     extern logical ckstr_(doublereal *);
     extern /* Subroutine */ int gsurf_(doublereal *, doublereal *, integer *,
         integer *, logical *), error_(integer *, char *, ftnlen), badnam_(
         doublereal *);
     static logical bndflg;
     static doublereal bndnam;
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     static doublereal coebuf[10];
     static integer iwhich[30], iarray[48]   /* was [2][24] */;
     static doublereal bndary[24];
     static logical errflg;
     extern integer addrss_(doublereal *), xcanon_(integer *);
     extern /* Subroutine */ int unpack_(doublereal *, integer *, integer *,
         integer *), cprint_(doublereal *);
     /* Assigned format variables */
     static char *m_fmt;
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /* ...            SYSTEM I/O FILE NAMES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...                SYSTEM I/O FILES */
 /* ...  LOCAL VARIABLES */
     /* Parameter adjustments */
     --part;
     /* Function Body */
 /* ...  INITIALIZE. */
     k = 1;
     bndflg = FALSE_;
 /* ...  DETERMINE VIRTUAL INDEX OF PART(1) IN COM-ARRAY. */
     iabs = (addrss_(&part[1]) - addrss_(_BLNK__1.com)) / idef_1.kwrdsz + 1;
     index = iabs;
     if (ldef_1.canflg) {
     incan_(&index);
     }
     index -= idef_1.iblk1;
 /* ...  DETERMINE SIZE AND MODE OF CANONICAL FORM FOR PART. */
     unpack_(&_BLNK__1.com[iabs - 1], &mode, isize, &isub);
     if (mode != 28) {
     goto L900;
     }
 /* ...  PRINT VERIFICATION LISTING. */
     nn = isize[0] + 1;
     bndnam = part[nn];
     cform_("0", darray_1.darray, &c__0, &c__1, (ftnlen)1);
     cform_("CFSAVE/", darray_1.darray, &c__6, &c__7, (ftnlen)7);
     cform_(&bndnam, darray_1.darray, &c__13, &c__6);
     cprint_(darray_1.darray);
     cform_("NAME PRI.  SUB      * * *  B O U N D I N G   S U R F   A C E S  "
         " * * *", darray_1.darray, &c__1, &c__68, (ftnlen)70);
     cprint_(darray_1.darray);
     cform_("SURF       1ST   SUB MOD  2ND   SUB MOD  3RD   SUB    MOD  4TH  "
         " SUB MOD  5TH   SUB MOD 6TH   SUB MOD  7TH   SUB MOD     ",
         darray_1.darray, &c__6, &c__114, (ftnlen)121);
     cprint_(darray_1.darray);
     goto L40;
 /* ...  DETERMINE MODE, SIZE AND SUBSCRIPT OF NEXT FORM AND CHECK VALIDITY */
 L20:
     nn = k + 1;
     unpack_(&_BLNK__1.com[iabs - 1], &mode, &isiz, &isub);
     if (isiz <= 0 || isiz > 48 || isub < 0 || isub > 999 || mode <= 0) {
     goto L900;
     }
     isize[nn - 1] = isiz;
     m = 0;
     m_fmt = fmt_90;
 /* ...  DETERMINE IF FORM HAS BEEN DEFINED AND CHECK ITS MODE. */
 /*     BYPASS WRITING OF BEVISION INPUT FILE IF PRIOR ERRORS HAVE OCCURED */
     if (mode - 28 >= 0) {
     goto L30;
     } else {
     goto L25;
     }
 L25:
     if (ckdtr_(&_BLNK__1.com[iabs - 1])) {
     goto L28;
     }
     if (mode == 27) {
     goto L60;
     }
 /* ...  BYPASS WRITING CFSAVE FILE IF PRIOR BOUNDED GEOM. ERR DETECTED. */
     if (ldef_1.bnderr) {
     goto L140;
     }
     gsurf_(coebuf, &_BLNK__1.com[iabs - 1], &mode, &isiz, &errflg);
     if (! errflg) {
     goto L110;
     }
 /* ...  ERROR 85 - REFERENCED ELEMENT NOT PROPERLY DEFINED. */
 L28:
     ldef_1.bnderr = TRUE_;
     error_(&c__85, "APT104  ", (ftnlen)8);
     goto L140;
 /* ...  AN OBJECT. */
 L30:
     ++k;
     if (k > kmax) {
     goto L910;
     }
 /* ...  SET MAIN STACK. */
 L40:
     mstk[k - 1] = index;
     iwhich[k - 1] = index + 1;
     if (mode != 28) {
     goto L70;
     }
 /* ...  MAKE SURE CANONICAL FORM IN OBJECT ARGUMENT IS NOT ERRONEOUSLY DE- */
 /*     FINED.  SAVE ITS VIRTUAL INDEX. */
 L45:
     if (ckstr_(&_BLNK__1.com[iabs - 1])) {
     goto L900;
     }
     index = (integer) _BLNK__1.com[iabs];
 /* ...  DETERMINE ABSOLUTE INDEX. */
 L50:
     iabs = index + idef_1.iblk1;
     if (ldef_1.canflg) {
     i__1 = iabs - 1;
     iabs = xcanon_(&i__1) + 1;
     }
     goto L20;
 /* ...  A BOUNDS. */
 /*     IF NOT THE FIRST BOUND AFTER AN OBJECT GO GET PRIMARY SURFACE. */
 L60:
     if (bndflg) {
     goto L65;
     }
 /* ...  FOR FIRST BOUND AFTER ENCOUNTERING AN OBJECT STATEMENT, PUT ON STK */
     bndflg = TRUE_;
     goto L30;
 /* ...  SET TO SAVE HALF-SPACE MODIFIER ASSOCIATED WITH BOUNDS ARGUMENT. */
 L65:
     m = 1;
     m_fmt = fmt_100;
     goto L80;
 /* ...  FIRST TIME THRU A BOUNDS STATEMENT.  SET TO PRINT ITS NAME. */
 L70:
     ks = 1;
     nn = isize[k - 1];
     bndnam = _BLNK__1.com[iabs + nn - 1];
 /* ...  DETERMINE VIRTUAL INDEX AND SUBSCRIPT FROM BOUNDS PACKED WORD. */
 /*     SAVE ITS NAME IN BNDARY(KS), HALF-SPACE MODIFIER IN IARRAY(1,KS), */
 /*     AND SUBSCRIPT IN IARRAY(2,KS). */
 L80:
     bndary[ks - 1] = _BLNK__1.com[iabs - 1];
     nn = (integer) _BLNK__1.com[iabs];
     index = nn / knumbr_1.k1e4;
     iarray[(ks << 1) - 1] = (nn - index * knumbr_1.k1e4) / knumbr_1.k10;
     switch (m) {
     case 0: goto L90;
     case 1: goto L100;
     }
 /* ...  SAVE OLD HALF-SPACE MODIFIER IF BOUNDS ARGUMENT IS A BOUNDS. */
 L90:
     iarray[(ks << 1) - 2] = nn - index * knumbr_1.k1e4 - iarray[(ks << 1) - 1]
          * knumbr_1.k10;
 /* ...  IF CANONICAL FORM IN BOUNDS ARGUMENT IS ERRONEOUSLY DEFINED, */
 /*     SKIP IT.  IF OKAY, DETERMINE ITS ABSOLUTE INDEX. */
 L100:
     if (! ckstr_(&_BLNK__1.com[iabs - 1])) {
     goto L50;
     }
     badnam_(&bndary[ks - 1]);
     goto L140;
 /* ...  WRITE BEVISION INPUT FILE. */
 L110:
     if (ks == 1) {
     goto L120;
     }
 /*     WRITE BOUNDING SURFACE COEFFICIENTS. */
 /*     WRITE (CFSFIL,112) IARRAY(1,KS),(COEBUF(I), I=1,10) */
 /* L112: */
     goto L140;
 /*     WRITE NUMBER OF BOUNDS. */
 L120:
     isiz = (isize[k - 1] - 2) / 2;
 /*     WRITE (CFSFIL,125) ISIZ */
 /* L125: */
 /*     WRITE PRIMARY SURFACE COEFFICIENTS. */
 /*     WRITE (CFSFIL,128) (COEBUF(I), I=1,10) */
 /* L128: */
 /* ...  LOOK AT NEXT BOUNDS ARGUMENT AND SAVE POINTER UNTIL ALL BOUNDS */
 /*     ARE FOUND. */
 L140:
     index = iwhich[k - 1] + 2;
     is = mstk[k - 1];
 /* ...  TEST FOR END OF A BOUNDS STATEMENT. */
     if (index > is + isize[k - 1]) {
     goto L150;
     }
     ++ks;
     if (ks > ksmax) {
     goto L910;
     }
 /* ...  MORE BOUNDING SURFACES. */
     iwhich[k - 1] = index;
     iabs = idef_1.iblk1 + index - 1;
     if (ldef_1.canflg) {
     iabs = xcanon_(&iabs);
     }
     goto L80;
 /* ...  END OF A BOUNDS STATEMENT.  WRITE IT OUT ON VERIFICATION LISTING. */
 L150:
     i__1 = ks;
     for (i__ = 2; i__ <= i__1; ++i__) {
     if ((i__2 = iarray[(i__ << 1) - 2] - 2) < 0) {
         goto L152;
     } else if (i__2 == 0) {
         goto L154;
     } else {
         goto L156;
     }
 L152:
     iarray[(i__ << 1) - 2] = bcdf_("IN  ", (ftnlen)4);
     goto L160;
 L154:
     iarray[(i__ << 1) - 2] = bcdf_("OUT ", (ftnlen)4);
     goto L160;
 L156:
     iarray[(i__ << 1) - 2] = bcdf_("  * ", (ftnlen)4);
 L160:
     ;
     }
     cform_(&bndnam, darray_1.darray, &c__1, &c__6);
     cprint_(darray_1.darray);
     cform_(bndary, darray_1.darray, &c__5, &c__6);
     cform_("(   )", darray_1.darray, &c__11, &c__5, (ftnlen)5);
     iconv_(&iarray[1], darray_1.darray, &c__12, &c__3);
     l = 16;
     i__1 = ks;
     for (i__ = 2; i__ <= i__1; ++i__) {
     cform_(&bndary[i__ - 1], darray_1.darray, &l, &c__6);
     i__2 = l + 6;
     cform_("(   )", darray_1.darray, &i__2, &c__5, (ftnlen)5);
     i__2 = l + 7;
     iconv_(&iarray[(i__ << 1) - 1], darray_1.darray, &i__2, &c__3);
     i__2 = l + 11;
     cform_(&iarray[(i__ << 1) - 2], darray_1.darray, &i__2, &c__3);
     l += 15;
     if (i__ == ks) {
         goto L164;
     }
     if (l < 110) {
         goto L165;
     }
 L164:
     cprint_(darray_1.darray);
     l = 16;
 L165:
     ;
     }
     bndflg = FALSE_;
 L170:
     --k;
 /* ...  ARE WE FINISHED. */
     if (k == 0) {
     goto L180;
     }
     index = iwhich[k - 1] + 2;
     is = mstk[k - 1];
 /* ...  TEST FOR END OF OBJECT STATEMENT. */
     if (index > is + isize[k - 1]) {
     goto L170;
     }
 /* ...  MORE OBJECT ARGUMENTS. */
     iwhich[k - 1] = index;
     iabs = idef_1.iblk1 + index - 1;
     if (ldef_1.canflg) {
     iabs = xcanon_(&iabs);
     }
     goto L45;
 /* ...  WRITE MESSAGE IF PRIOR ERRORS DETECTED. */
 L180:
     if (ldef_1.bnderr) {
     goto L998;
     }
     cform_("GEOMETRY GENERATION COMPLETED.", darray_1.darray, &c__8, &c__30, (
         ftnlen)30);
     cprint_(darray_1.darray);
     goto L999;
 /* ...  ERROR 89 - INVALID OR ERRONEOUS CANONICAL FORM ENCOUNTERED. */
 /*     BOUNDED GEOMETRY PROCESSING TERMINATED. */
 L900:
     error_(&c__89, "APT104  ", (ftnlen)8);
     goto L998;
 /* ...  ERROR 90 - TOO MUCH EMBEDDEDNESS IN BOUNDS AND OBJECT STATEMENTS. */
 /*     BOUNDED GEOMETRY PROCESSING TERMINATED. */
 L910:
     error_(&c__90, "APT104  ", (ftnlen)8);
 L998:
     cform_("***BOUNDED GEOMETRY ERRORS DETECTED. NO BEVISION INP  UT FILE WR"
         "ITTEN.", darray_1.darray, &c__8, &c__68, (ftnlen)70);
     cprint_(darray_1.darray);
 /*     REWIND CFSFIL */
 /* ...  WRITE END OF FILE INDICATOR. */
 L999:
 /*     WRITE (CFSFIL,125) KM1 */
 /*     END FILE CFSFIL */
 /*     REWIND CFSFIL */
     return 0;
 } /* apt104_ */
Variable Documentation
struct { ... } _BLNK__
logical altmlt
Definition at line 24 of file APT104.c.
integer axfile
Definition at line 45 of file APT104.c.
logical bnderr
Definition at line 24 of file APT104.c.
logical boundf
Definition at line 24 of file APT104.c.
integer c__0 = 0 static
Definition at line 61 of file APT104.c.
Referenced by apt104_().
integer c__1 = 1 static
Definition at line 62 of file APT104.c.
Referenced by apt104_().
integer c__11 = 11 static
Definition at line 70 of file APT104.c.
Referenced by apt104_().
integer c__114 = 114 static
Definition at line 67 of file APT104.c.
Referenced by apt104_().
integer c__12 = 12 static
Definition at line 71 of file APT104.c.
Referenced by apt104_().
integer c__13 = 13 static
Definition at line 65 of file APT104.c.
Referenced by apt104_().
integer c__3 = 3 static
Definition at line 72 of file APT104.c.
Referenced by apt104_().
integer c__30 = 30 static
Definition at line 74 of file APT104.c.
Referenced by apt104_().
integer c__5 = 5 static
Definition at line 69 of file APT104.c.
Referenced by apt104_().
integer c__6 = 6 static
Definition at line 63 of file APT104.c.
Referenced by apt104_().
integer c__68 = 68 static
Definition at line 66 of file APT104.c.
Referenced by apt104_().
integer c__7 = 7 static
Definition at line 64 of file APT104.c.
Referenced by apt104_().
integer c__8 = 8 static
Definition at line 73 of file APT104.c.
Referenced by apt104_().
integer c__85 = 85 static
Definition at line 68 of file APT104.c.
Referenced by apt104_().
integer c__89 = 89 static
Definition at line 75 of file APT104.c.
Referenced by apt104_().
integer c__90 = 90 static
Definition at line 76 of file APT104.c.
Referenced by apt104_().
logical canflg
Definition at line 24 of file APT104.c.
integer clfil3
Definition at line 45 of file APT104.c.
integer clfile
Definition at line 45 of file APT104.c.
integer clfilp
Definition at line 45 of file APT104.c.
doublereal com[36000]
Definition at line 18 of file APT104.c.
integer cpfile
Definition at line 45 of file APT104.c.
doublereal darray[15]
Definition at line 54 of file APT104.c.
struct { ... } darray_
integer elfil1
Definition at line 45 of file APT104.c.
integer elfil2
Definition at line 45 of file APT104.c.
integer elfil3
Definition at line 45 of file APT104.c.
integer elfil4
Definition at line 45 of file APT104.c.
integer elfile
Definition at line 45 of file APT104.c.
integer exfile
Definition at line 45 of file APT104.c.
integer iblk1
Definition at line 31 of file APT104.c.
struct { ... } idef_
integer ierror
Definition at line 31 of file APT104.c.
integer infile__
Definition at line 45 of file APT104.c.
integer ispare[26]
Definition at line 45 of file APT104.c.
logical jcs
Definition at line 24 of file APT104.c.
logical jds
Definition at line 24 of file APT104.c.
integer k0
Definition at line 37 of file APT104.c.
integer k1
Definition at line 37 of file APT104.c.
integer k10
Definition at line 37 of file APT104.c.
integer k1013
Definition at line 37 of file APT104.c.
integer k12
Definition at line 37 of file APT104.c.
integer k13
Definition at line 37 of file APT104.c.
integer k15
Definition at line 37 of file APT104.c.
integer k16
Definition at line 37 of file APT104.c.
integer k18
Definition at line 37 of file APT104.c.
integer k19
Definition at line 37 of file APT104.c.
integer k1e4
Definition at line 37 of file APT104.c.
integer k1e6
Definition at line 37 of file APT104.c.
integer k2
Definition at line 37 of file APT104.c.
integer k23
Definition at line 37 of file APT104.c.
integer k24
Definition at line 37 of file APT104.c.
integer k25
Definition at line 37 of file APT104.c.
integer k26
Definition at line 37 of file APT104.c.
integer k27
Definition at line 37 of file APT104.c.
integer k29
Definition at line 37 of file APT104.c.
integer k3
Definition at line 37 of file APT104.c.
integer k30
Definition at line 37 of file APT104.c.
integer k31
Definition at line 37 of file APT104.c.
integer k32
Definition at line 37 of file APT104.c.
integer k33
Definition at line 37 of file APT104.c.
integer k34
Definition at line 37 of file APT104.c.
integer k4
Definition at line 37 of file APT104.c.
integer k44
Definition at line 37 of file APT104.c.
integer k45
Definition at line 37 of file APT104.c.
integer k46
Definition at line 37 of file APT104.c.
integer k47
Definition at line 37 of file APT104.c.
integer k48
Definition at line 37 of file APT104.c.
integer k5
Definition at line 37 of file APT104.c.
integer k50
Definition at line 37 of file APT104.c.
integer k51
Definition at line 37 of file APT104.c.
integer k52
Definition at line 37 of file APT104.c.
integer k6
Definition at line 37 of file APT104.c.
integer k7
Definition at line 37 of file APT104.c.
integer k8
Definition at line 37 of file APT104.c.
integer k9
Definition at line 37 of file APT104.c.
integer km1
Definition at line 37 of file APT104.c.
struct { ... } knumbr_
integer kwrdsz
Definition at line 31 of file APT104.c.
integer ldafil
Definition at line 45 of file APT104.c.
integer ldasiz
Definition at line 31 of file APT104.c.
struct { ... } ldef_
integer libfil
Definition at line 45 of file APT104.c.
integer mactxt
Definition at line 45 of file APT104.c.
integer nfil12
Definition at line 45 of file APT104.c.
integer nfil13
Definition at line 45 of file APT104.c.
logical pchlst
Definition at line 24 of file APT104.c.
integer pnchfl
Definition at line 45 of file APT104.c.
integer pofile
Definition at line 45 of file APT104.c.
logical prnton
Definition at line 24 of file APT104.c.
integer pxfile
Definition at line 45 of file APT104.c.
logical refflg
Definition at line 24 of file APT104.c.
logical refmot
Definition at line 24 of file APT104.c.
logical subflg
Definition at line 24 of file APT104.c.
integer surfad[4]
Definition at line 31 of file APT104.c.
struct { ... } symfil_
logical tabprt
Definition at line 24 of file APT104.c.
integer tifile
Definition at line 45 of file APT104.c.
logical unflag
Definition at line 24 of file APT104.c.
integer vlfile
Definition at line 45 of file APT104.c.
integer xcan
Definition at line 45 of file APT104.c.
integer xnum
Definition at line 45 of file APT104.c.
logical zflag
Definition at line 24 of file APT104.c.