My Project: APT235.c File Reference
APT235.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define hblock_1 hblock_
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define symfil_1 symfil_
#define dsname_1 dsname_
#define _BLNK__1 _BLNK__
#define can ((doublereal *)&_BLNK__1 + 40)
#define hcl ((doublereal *)&equiv_2)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define canon ((doublereal *)&_BLNK__1)
#define iferm ((integer *)equiv_3)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define hcldta ((integer *)&equiv_2)
#define fermod (equiv_3)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int apt235_ (void)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
char hps [8]
char hds [8]
char hcs [8]
char hlft [8]
char hrgt [8]
char hfwd [8]
char hback [8]
char hup [8]
char hdown [8]
char hto [8]
char hpast [8]
char hon [8]
char htanto [8]
char hpstan [8]
char hdynp [8]
char haerr [8]
char hcldat [8]
char hgerr [8]
} hblock_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
struct {
doublereal dsname
integer namsub
} dsname_
struct {
doublereal com [36000]
} _BLNK__
static integer c__18 = 18
static integer c__32 = 32
static integer c__23501 = 23501
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 150 of file APT235.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
Referenced by apt235_().
#define charct_1 charct_
Definition at line 37 of file APT235.c.
Referenced by apt235_().
#define cosl ((doublereal *)&tlldat_1 + 16)
#define def_1 def_
Definition at line 22 of file APT235.c.
#define dsname_1 dsname_
Definition at line 144 of file APT235.c.
Referenced by apt235_().
#define fermod (equiv_3)
Referenced by apt235_().
#define fxcor_1 fxcor_
Definition at line 31 of file APT235.c.
Referenced by apt235_().
#define hblock_1 hblock_
Definition at line 52 of file APT235.c.
#define hcl ((doublereal *)&equiv_2)
Referenced by apt235_().
#define hcldta ((integer *)&equiv_2)
Referenced by apt235_().
#define iferm ((integer *)equiv_3)
Referenced by apt235_().
#define ifxcor_1 ifxcor_
Definition at line 112 of file APT235.c.
Referenced by apt235_().
#define ishr18_1 ishr18_
Definition at line 120 of file APT235.c.
#define isv1_1 isv1_
Definition at line 102 of file APT235.c.
#define isv_1 isv_
Definition at line 95 of file APT235.c.
Referenced by apt235_().
#define knumbr_1 knumbr_
Definition at line 128 of file APT235.c.
Referenced by apt235_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define sv1_1 sv1_
Definition at line 78 of file APT235.c.
#define sv_1 sv_
Definition at line 69 of file APT235.c.
#define symfil_1 symfil_
Definition at line 137 of file APT235.c.
Referenced by apt235_().
#define tlldat_1 tlldat_
Definition at line 44 of file APT235.c.
#define znumbr_1 znumbr_
Definition at line 86 of file APT235.c.
Referenced by apt235_().
Function Documentation
int apt235_ (void)
Definition at line 162 of file APT235.c.
References aerr_(), autops_(), bcdf_(), c__18, c__23501, c__32, canon, charct_1, ckdef_(), dsname_1, e_1, e_2, ewrite_(), fermod, first, fxcor_1, hcl, hcldta, i__, iferm, ifxcor_1, ir, isv_1, j, knumbr_1, l, m, record_(), symfil_1, and znumbr_1.
Referenced by apt211_(), and go2_().
 {
     /* Initialized data */
     static char hgo[8] = "GO      ";
     static logical first = TRUE_;
     static struct {
     integer e_1[32];
     doublereal e_2;
     } equiv_2 = { 0, 0, 1308622848, 0, 1308622848, 6, 1308622848, 1, 0, 0,
          1308622848, 0, 0, 0, 1308622848, 0, 1308622848, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0. };
     /* System generated locals */
     integer i__1, i__2;
     static doublereal equiv_3[1];
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, j, l, m, nr, ir;
 #define can ((doublereal *)&_BLNK__1 + 40)
 #define hcl ((doublereal *)&equiv_2)
     extern integer bcdf_(char *, ftnlen);
     static logical flag__;
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     extern logical ckdef_(doublereal *);
 #define canon ((doublereal *)&_BLNK__1)
 #define iferm ((integer *)equiv_3)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
 #define hcldta ((integer *)&equiv_2)
 #define fermod (equiv_3)
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int record_(integer *), ewrite_(integer *,
         integer *, integer *, integer *, integer *), autops_(void);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*     *** 8.  HOLRTH BLOCK *** */
 /*     ALPHA-NUMERIC LITERAL CONSTANTS. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /* ...            SYSTEM I/O FILE NAMES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...                SYSTEM I/O FILES */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
     if (first) {
     hcldta[0] = bcdf_("CLDA", (ftnlen)4);
     hcldta[1] = bcdf_("TA  ", (ftnlen)4);
     hcldta[8] = bcdf_("    ", (ftnlen)4);
     hcldta[9] = hcldta[8];
     hcldta[12] = hcldta[8];
     hcldta[13] = hcldta[8];
     first = FALSE_;
     }
     flag__ = FALSE_;
     ifxcor_1.numsur = ifxcor_1.icscnt + knumbr_1.k2;
 /* ...  PRINT  IDENTIYING FIRST CUT SEQUENCE RECORD ON EXFILE */
     record_(&ifxcor_1.iseqno);
     hcldta[3] = ifxcor_1.iseqno;
     iferm[0] = bcdf_(charct_1.modfer, (ftnlen)4);
     iferm[1] = bcdf_(charct_1.modfer + 4, (ftnlen)2);
     hcl[4] = *fermod;
     hcldta[11] = isv_1.isftyp[ifxcor_1.ids - 1];
     hcl[6] = dsname_1.dsname;
     hcldta[15] = dsname_1.namsub;
     hcldta[17] = isv_1.isfidn[ifxcor_1.ids - 1];
     if (isv_1.isfidn[ifxcor_1.ids - 1] == knumbr_1.k4 && s_cmp(
         charct_1.modfer, hgo, (ftnlen)6, (ftnlen)8) != 0) {
     goto L10;
     }
     hcldta[5] = knumbr_1.k6;
     nr = 0;
     ewrite_(&symfil_1.exfile, &nr, hcldta, &c__18, &ir);
     goto L15;
 L10:
     hcldta[5] = knumbr_1.k13;
     j = isv_1.icanon[ifxcor_1.ids - 1];
     for (i__ = 10; i__ <= 16; ++i__) {
     hcl[i__ - 1] = canon[j - 1];
 /* L11: */
     ++j;
     }
     nr = 0;
     ewrite_(&symfil_1.exfile, &nr, hcldta, &c__32, &ir);
 L15:
     if (ifxcor_1.ipsdef <= 0) {
     goto L9;
     } else {
     goto L8;
     }
 L8:
     fxcor_1.temp[0] = fxcor_1.te[2];
     fxcor_1.te[2] = znumbr_1.z0;
     autops_();
     fxcor_1.te[2] = fxcor_1.temp[0];
 L9:
     j = ifxcor_1.ips;
     l = ifxcor_1.lsv;
     i__1 = ifxcor_1.numsur;
     for (i__ = 1; i__ <= i__1; ++i__) {
     m = isv_1.icanon[j - 1];
     if (ckdef_(&canon[m - 1])) {
         flag__ = TRUE_;
     }
     if ((i__2 = j - ifxcor_1.ics) < 0) {
         goto L2;
     } else if (i__2 == 0) {
         goto L3;
     } else {
         goto L4;
     }
 L2:
     isv_1.itlon[j - 1] = isv_1.isftyp[j - 1] - knumbr_1.k3;
     goto L5;
 L3:
     l = ifxcor_1.lsv1;
 L4:
     if ((i__2 = isv_1.isftyp[j - 1] - knumbr_1.k4) < 0) {
         goto L2;
     } else if (i__2 == 0) {
         goto L6;
     } else {
         goto L7;
     }
 L6:
     isv_1.itlon[j - 1] = isv_1.itlon[ifxcor_1.ids - 1];
     if (isv_1.itlon[j - 1] != 0) {
         isv_1.itlon[j - 1] = 2;
     }
     goto L5;
 L7:
     isv_1.itlon[j - 1] = isv_1.itlon[ifxcor_1.ips - 1];
     if (isv_1.itlon[j - 1] != 0) {
         isv_1.itlon[j - 1] = 3;
     }
     isv_1.isftyp[j - 1] = knumbr_1.k4;
 L5:
     isv_1.iafl[j - 1] = -knumbr_1.k1;
 /* L1: */
     j += l;
     }
     if (flag__) {
     aerr_(&c__23501, "APT235  ", (ftnlen)8);
     }
     return 0;
 } /* apt235_ */
Variable Documentation
struct { ... } _BLNK__
doublereal a[24]
Definition at line 18 of file APT235.c.
doublereal ahold[8]
Definition at line 18 of file APT235.c.
doublereal alp
Definition at line 25 of file APT235.c.
doublereal ax4[3]
Definition at line 25 of file APT235.c.
integer axfile
Definition at line 131 of file APT235.c.
doublereal c1[8]
Definition at line 18 of file APT235.c.
integer c__18 = 18 static
Definition at line 154 of file APT235.c.
Referenced by apt235_().
integer c__23501 = 23501 static
Definition at line 156 of file APT235.c.
Referenced by apt235_().
integer c__32 = 32 static
Definition at line 155 of file APT235.c.
Referenced by apt235_().
doublereal cagl
Definition at line 25 of file APT235.c.
doublereal cc[15]
Definition at line 55 of file APT235.c.
struct { ... } charct_
integer clfil3
Definition at line 131 of file APT235.c.
integer clfile
Definition at line 131 of file APT235.c.
integer clfilp
Definition at line 131 of file APT235.c.
doublereal com[36000]
Definition at line 147 of file APT235.c.
doublereal corrad[8]
Definition at line 40 of file APT235.c.
doublereal cos1[5]
Definition at line 72 of file APT235.c.
integer cpfile
Definition at line 131 of file APT235.c.
doublereal cplfl[5]
Definition at line 72 of file APT235.c.
doublereal cptst[5]
Definition at line 72 of file APT235.c.
doublereal csd[5]
Definition at line 72 of file APT235.c.
doublereal cutdat[7]
Definition at line 25 of file APT235.c.
struct { ... } def_
doublereal degrad
Definition at line 81 of file APT235.c.
doublereal dplan[15]
Definition at line 72 of file APT235.c.
doublereal dpmax
Definition at line 25 of file APT235.c.
doublereal dpmx1[5]
Definition at line 72 of file APT235.c.
doublereal dsname
Definition at line 140 of file APT235.c.
struct { ... } dsname_
integer elfil1
Definition at line 131 of file APT235.c.
integer elfil2
Definition at line 131 of file APT235.c.
integer elfil3
Definition at line 131 of file APT235.c.
integer elfil4
Definition at line 131 of file APT235.c.
integer elfile
Definition at line 131 of file APT235.c.
doublereal eps1[5]
Definition at line 55 of file APT235.c.
doublereal eps2[5]
Definition at line 55 of file APT235.c.
doublereal eps3[5]
Definition at line 55 of file APT235.c.
doublereal eps4[5]
Definition at line 55 of file APT235.c.
doublereal eps6[5]
Definition at line 55 of file APT235.c.
doublereal eps8[5]
Definition at line 55 of file APT235.c.
integer exfile
Definition at line 131 of file APT235.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 25 of file APT235.c.
char haerr[8]
Definition at line 47 of file APT235.c.
char hback[8]
Definition at line 47 of file APT235.c.
struct { ... } hblock_
char hcldat[8]
Definition at line 47 of file APT235.c.
char hcs[8]
Definition at line 47 of file APT235.c.
char hdown[8]
Definition at line 47 of file APT235.c.
char hds[8]
Definition at line 47 of file APT235.c.
char hdynp[8]
Definition at line 47 of file APT235.c.
char hfwd[8]
Definition at line 47 of file APT235.c.
char hgerr[8]
Definition at line 47 of file APT235.c.
doublereal hi
Definition at line 25 of file APT235.c.
char hlft[8]
Definition at line 47 of file APT235.c.
char hon[8]
Definition at line 47 of file APT235.c.
char hpast[8]
Definition at line 47 of file APT235.c.
char hps[8]
Definition at line 47 of file APT235.c.
char hpstan[8]
Definition at line 47 of file APT235.c.
char hrgt[8]
Definition at line 47 of file APT235.c.
char htanto[8]
Definition at line 47 of file APT235.c.
char hto[8]
Definition at line 47 of file APT235.c.
char hup[8]
Definition at line 47 of file APT235.c.
integer i3dflg
Definition at line 105 of file APT235.c.
integer iaerr
Definition at line 105 of file APT235.c.
integer iafl[5]
Definition at line 89 of file APT235.c.
integer iamdct
Definition at line 115 of file APT235.c.
integer iautps
Definition at line 105 of file APT235.c.
integer ibegin
Definition at line 105 of file APT235.c.
integer ic
Definition at line 105 of file APT235.c.
integer icanon[5]
Definition at line 89 of file APT235.c.
integer icheck
Definition at line 105 of file APT235.c.
integer icl
Definition at line 105 of file APT235.c.
integer ics
Definition at line 105 of file APT235.c.
integer icscnt
Definition at line 105 of file APT235.c.
integer ictdef
Definition at line 105 of file APT235.c.
integer icut
Definition at line 105 of file APT235.c.
integer ids
Definition at line 105 of file APT235.c.
integer ier
Definition at line 105 of file APT235.c.
integer ifar[5]
Definition at line 98 of file APT235.c.
integer ifl4[5]
Definition at line 98 of file APT235.c.
struct { ... } ifxcor_
integer igo
Definition at line 105 of file APT235.c.
integer igoto
Definition at line 105 of file APT235.c.
integer igoug
Definition at line 105 of file APT235.c.
integer igs
Definition at line 105 of file APT235.c.
integer index[5]
Definition at line 89 of file APT235.c.
integer indir__[5]
Definition at line 89 of file APT235.c.
integer infile__
Definition at line 131 of file APT235.c.
integer inops
Definition at line 105 of file APT235.c.
integer iop[5]
Definition at line 89 of file APT235.c.
integer iopset[5]
Definition at line 89 of file APT235.c.
integer ipdpl
Definition at line 115 of file APT235.c.
integer ipl[5]
Definition at line 89 of file APT235.c.
integer ips
Definition at line 105 of file APT235.c.
integer ipsdef
Definition at line 105 of file APT235.c.
integer ipt
Definition at line 115 of file APT235.c.
integer ipt1
Definition at line 105 of file APT235.c.
integer is
Definition at line 105 of file APT235.c.
integer iseg
Definition at line 105 of file APT235.c.
integer iseqno
Definition at line 105 of file APT235.c.
integer isfidn[5]
Definition at line 89 of file APT235.c.
integer isftyp[5]
Definition at line 89 of file APT235.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 89 of file APT235.c.
integer ispare[26]
Definition at line 131 of file APT235.c.
integer isrch
Definition at line 105 of file APT235.c.
integer istrup
Definition at line 105 of file APT235.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 89 of file APT235.c.
integer it
Definition at line 105 of file APT235.c.
integer itlon[5]
Definition at line 89 of file APT235.c.
integer itseg[5]
Definition at line 89 of file APT235.c.
integer itsegk[5]
Definition at line 89 of file APT235.c.
integer iunfl[5]
Definition at line 89 of file APT235.c.
integer iws
Definition at line 115 of file APT235.c.
integer j10
Definition at line 115 of file APT235.c.
integer j12
Definition at line 115 of file APT235.c.
integer j13
Definition at line 115 of file APT235.c.
integer j20[5]
Definition at line 98 of file APT235.c.
integer j21[5]
Definition at line 98 of file APT235.c.
integer j22[5]
Definition at line 98 of file APT235.c.
integer j23[5]
Definition at line 98 of file APT235.c.
integer j50[5]
Definition at line 98 of file APT235.c.
integer j51[5]
Definition at line 98 of file APT235.c.
integer j54
Definition at line 115 of file APT235.c.
integer jbr
Definition at line 105 of file APT235.c.
integer jckr
Definition at line 115 of file APT235.c.
integer jcnt1
Definition at line 115 of file APT235.c.
integer jcnt2
Definition at line 115 of file APT235.c.
integer jcnt3
Definition at line 115 of file APT235.c.
integer jcpr
Definition at line 115 of file APT235.c.
integer jcr
Definition at line 115 of file APT235.c.
integer jdr
Definition at line 115 of file APT235.c.
integer jent[5]
Definition at line 89 of file APT235.c.
integer jfind
Definition at line 115 of file APT235.c.
integer jgr
Definition at line 115 of file APT235.c.
integer jiops[5]
Definition at line 89 of file APT235.c.
integer jmin
Definition at line 115 of file APT235.c.
integer jminr
Definition at line 115 of file APT235.c.
integer jph[5]
Definition at line 98 of file APT235.c.
integer jpr
Definition at line 115 of file APT235.c.
integer jpxr
Definition at line 115 of file APT235.c.
integer jsw
Definition at line 105 of file APT235.c.
integer jtkf
Definition at line 115 of file APT235.c.
integer jtlflg[5]
Definition at line 89 of file APT235.c.
integer jtn[5]
Definition at line 89 of file APT235.c.
integer jtr
Definition at line 115 of file APT235.c.
integer ju1[5]
Definition at line 89 of file APT235.c.
integer k0
Definition at line 123 of file APT235.c.
integer k1
Definition at line 123 of file APT235.c.
integer k10
Definition at line 123 of file APT235.c.
integer k1013
Definition at line 123 of file APT235.c.
integer k12
Definition at line 123 of file APT235.c.
integer k13
Definition at line 123 of file APT235.c.
integer k15
Definition at line 123 of file APT235.c.
integer k16
Definition at line 123 of file APT235.c.
integer k18
Definition at line 123 of file APT235.c.
integer k19
Definition at line 123 of file APT235.c.
integer k1e4
Definition at line 123 of file APT235.c.
integer k1e6
Definition at line 123 of file APT235.c.
integer k2
Definition at line 123 of file APT235.c.
integer k23
Definition at line 123 of file APT235.c.
integer k24
Definition at line 123 of file APT235.c.
integer k25
Definition at line 123 of file APT235.c.
integer k26
Definition at line 123 of file APT235.c.
integer k27
Definition at line 123 of file APT235.c.
integer k29
Definition at line 123 of file APT235.c.
integer k3
Definition at line 123 of file APT235.c.
integer k30
Definition at line 123 of file APT235.c.
integer k31
Definition at line 123 of file APT235.c.
integer k32
Definition at line 123 of file APT235.c.
integer k33
Definition at line 123 of file APT235.c.
integer k34
Definition at line 123 of file APT235.c.
integer k4
Definition at line 123 of file APT235.c.
integer k44
Definition at line 123 of file APT235.c.
integer k45
Definition at line 123 of file APT235.c.
integer k46
Definition at line 123 of file APT235.c.
integer k47
Definition at line 123 of file APT235.c.
integer k48
Definition at line 123 of file APT235.c.
integer k5
Definition at line 123 of file APT235.c.
integer k50
Definition at line 123 of file APT235.c.
integer k51
Definition at line 123 of file APT235.c.
integer k52
Definition at line 123 of file APT235.c.
integer k6
Definition at line 123 of file APT235.c.
integer k7
Definition at line 123 of file APT235.c.
integer k8
Definition at line 123 of file APT235.c.
integer k9
Definition at line 123 of file APT235.c.
integer km1
Definition at line 123 of file APT235.c.
struct { ... } knumbr_
integer ldafil
Definition at line 131 of file APT235.c.
integer libfil
Definition at line 131 of file APT235.c.
integer limfl[5]
Definition at line 89 of file APT235.c.
doublereal ln1[5]
Definition at line 18 of file APT235.c.
integer lsv
Definition at line 105 of file APT235.c.
integer lsv1
Definition at line 105 of file APT235.c.
integer mactxt
Definition at line 131 of file APT235.c.
integer mantax
Definition at line 105 of file APT235.c.
integer mdic
Definition at line 115 of file APT235.c.
char modfer[6]
Definition at line 34 of file APT235.c.
integer motmod
Definition at line 105 of file APT235.c.
integer msav
Definition at line 105 of file APT235.c.
integer mulout
Definition at line 105 of file APT235.c.
integer namsub
Definition at line 141 of file APT235.c.
integer nfil12
Definition at line 131 of file APT235.c.
integer nfil13
Definition at line 131 of file APT235.c.
integer nmbseg
Definition at line 105 of file APT235.c.
integer nmpnts
Definition at line 105 of file APT235.c.
integer notan[5]
Definition at line 98 of file APT235.c.
integer nrec
Definition at line 105 of file APT235.c.
integer numax
Definition at line 105 of file APT235.c.
integer numcnt
Definition at line 105 of file APT235.c.
integer nump
Definition at line 105 of file APT235.c.
integer numpt1
Definition at line 105 of file APT235.c.
integer numsfs
Definition at line 105 of file APT235.c.
integer numsur
Definition at line 105 of file APT235.c.
integer nw
Definition at line 105 of file APT235.c.
integer nwds
Definition at line 105 of file APT235.c.
doublereal past[5]
Definition at line 55 of file APT235.c.
doublereal pi
Definition at line 81 of file APT235.c.
doublereal plncs[5]
Definition at line 72 of file APT235.c.
doublereal plnd[5]
Definition at line 55 of file APT235.c.
doublereal plnd1[5]
Definition at line 72 of file APT235.c.
doublereal plnv[15]
Definition at line 55 of file APT235.c.
doublereal pltst[5]
Definition at line 72 of file APT235.c.
doublereal pmove[3]
Definition at line 25 of file APT235.c.
integer pnchfl
Definition at line 131 of file APT235.c.
integer pofile
Definition at line 131 of file APT235.c.
integer pxfile
Definition at line 131 of file APT235.c.
doublereal r__[10]
Definition at line 18 of file APT235.c.
doublereal ra
Definition at line 25 of file APT235.c.
doublereal rc[5]
Definition at line 55 of file APT235.c.
doublereal rc1
Definition at line 25 of file APT235.c.
doublereal ref[8]
Definition at line 18 of file APT235.c.
doublereal ri[8]
Definition at line 40 of file APT235.c.
doublereal s[5]
Definition at line 55 of file APT235.c.
doublereal sagl
Definition at line 25 of file APT235.c.
doublereal save[5]
Definition at line 55 of file APT235.c.
doublereal sfvct[15]
Definition at line 55 of file APT235.c.
doublereal sk[15]
Definition at line 55 of file APT235.c.
doublereal slx[15]
Definition at line 55 of file APT235.c.
doublereal sn[15]
Definition at line 55 of file APT235.c.
doublereal snk[15]
Definition at line 55 of file APT235.c.
doublereal snl[15]
Definition at line 55 of file APT235.c.
doublereal sp[15]
Definition at line 55 of file APT235.c.
doublereal spk[15]
Definition at line 55 of file APT235.c.
doublereal spl[15]
Definition at line 55 of file APT235.c.
doublereal stck[5]
Definition at line 72 of file APT235.c.
doublereal stck1[5]
Definition at line 72 of file APT235.c.
doublereal stck2[5]
Definition at line 72 of file APT235.c.
doublereal stckn[5]
Definition at line 72 of file APT235.c.
doublereal strtno
Definition at line 25 of file APT235.c.
doublereal surd
Definition at line 25 of file APT235.c.
struct { ... } sv1_
struct { ... } sv_
struct { ... } symfil_
doublereal ta[3]
Definition at line 25 of file APT235.c.
doublereal tak[3]
Definition at line 25 of file APT235.c.
doublereal tal[3]
Definition at line 25 of file APT235.c.
doublereal tanhi[8]
Definition at line 40 of file APT235.c.
doublereal tanlo[8]
Definition at line 40 of file APT235.c.
doublereal tau[5]
Definition at line 55 of file APT235.c.
doublereal tau1[5]
Definition at line 55 of file APT235.c.
doublereal tau2[5]
Definition at line 55 of file APT235.c.
doublereal tcont[9]
Definition at line 40 of file APT235.c.
doublereal te[3]
Definition at line 25 of file APT235.c.
doublereal tee[15]
Definition at line 72 of file APT235.c.
doublereal tek[3]
Definition at line 25 of file APT235.c.
doublereal tel[3]
Definition at line 25 of file APT235.c.
doublereal tem[10]
Definition at line 25 of file APT235.c.
doublereal temp[24]
Definition at line 25 of file APT235.c.
doublereal th[5]
Definition at line 55 of file APT235.c.
doublereal ti[3]
Definition at line 25 of file APT235.c.
integer tifile
Definition at line 131 of file APT235.c.
doublereal tik[3]
Definition at line 25 of file APT235.c.
doublereal til[3]
Definition at line 25 of file APT235.c.
doublereal tlhit
Definition at line 25 of file APT235.c.
doublereal tlhite[8]
Definition at line 40 of file APT235.c.
doublereal tlinc[9]
Definition at line 40 of file APT235.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 25 of file APT235.c.
doublereal tn[15]
Definition at line 55 of file APT235.c.
doublereal tnl[15]
Definition at line 72 of file APT235.c.
doublereal toolht[15]
Definition at line 55 of file APT235.c.
doublereal toolwd[5]
Definition at line 55 of file APT235.c.
doublereal tp[15]
Definition at line 55 of file APT235.c.
doublereal tpk[15]
Definition at line 55 of file APT235.c.
doublereal u1[15]
Definition at line 55 of file APT235.c.
doublereal u1k[15]
Definition at line 55 of file APT235.c.
doublereal umax[8]
Definition at line 40 of file APT235.c.
doublereal varble[5]
Definition at line 55 of file APT235.c.
integer vlfile
Definition at line 131 of file APT235.c.
doublereal vndir[15]
Definition at line 55 of file APT235.c.
doublereal vt[15]
Definition at line 55 of file APT235.c.
doublereal vtem
Definition at line 25 of file APT235.c.
integer xcan
Definition at line 131 of file APT235.c.
integer xnum
Definition at line 131 of file APT235.c.
doublereal z0
Definition at line 81 of file APT235.c.
doublereal z1
Definition at line 81 of file APT235.c.
doublereal z10
Definition at line 81 of file APT235.c.
doublereal z11em1
Definition at line 81 of file APT235.c.
doublereal z12em1
Definition at line 81 of file APT235.c.
doublereal z1e38
Definition at line 81 of file APT235.c.
doublereal z1e6
Definition at line 81 of file APT235.c.
doublereal z1em1
Definition at line 81 of file APT235.c.
doublereal z1em2
Definition at line 81 of file APT235.c.
doublereal z1em3
Definition at line 81 of file APT235.c.
doublereal z1em5
Definition at line 81 of file APT235.c.
doublereal z1em6
Definition at line 81 of file APT235.c.
doublereal z1em7
Definition at line 81 of file APT235.c.
doublereal z1em9
Definition at line 81 of file APT235.c.
doublereal z2
Definition at line 81 of file APT235.c.
doublereal z3
Definition at line 81 of file APT235.c.
doublereal z5
Definition at line 81 of file APT235.c.
doublereal z5em1
Definition at line 81 of file APT235.c.
doublereal z5em6
Definition at line 81 of file APT235.c.
doublereal z6em1
Definition at line 81 of file APT235.c.
doublereal z90
Definition at line 81 of file APT235.c.
doublereal z9em1
Definition at line 81 of file APT235.c.
doublereal z__[5]
Definition at line 55 of file APT235.c.
doublereal zm1
Definition at line 81 of file APT235.c.
struct { ... } znumbr_