My Project: apt211.c File Reference
apt211.c File Reference
#include "f2c.h"
Macros
#define dshar4_1 dshar4_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define hblock_1 hblock_
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define ldef_1 ldef_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define knumbr_1 knumbr_
#define symfil_1 symfil_
#define hold_1 hold_
#define hsave_1 hsave_
#define sqnc_1 sqnc_
#define _BLNK__1 _BLNK__
#define can ((doublereal *)&_BLNK__1 + 40)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define holrth ((char *)&hblock_1 + 24)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
integer apt211_ (doublereal *adress, doublereal *hdrect, integer *iaeee)
Variables
struct {
doublereal a
doublereal b
doublereal c__
doublereal cendis
doublereal cmove [3]
doublereal com1
doublereal com4
doublereal dir [3]
doublereal dp
doublereal dpe
doublereal dpcnt
doublereal dpi
doublereal dpl
doublereal dp1
doublereal d1
doublereal d2a
doublereal flipck
doublereal fwd [3]
doublereal ogle [3]
doublereal p1 [3]
doublereal p2 [3]
doublereal rdrn
doublereal refpnt [3]
doublereal tangl
doublereal tes [3]
doublereal tew [3]
doublereal uvec [3]
doublereal u2 [3]
doublereal v [3]
doublereal vl
doublereal zl
doublereal zlnorm [3]
doublereal zlpnt [3]
doublereal zl1
doublereal param [6]
doublereal r__ [6]
doublereal savpar [4]
doublereal seg [9]
doublereal slope
doublereal sqroot
doublereal unn
doublereal upp
doublereal vint
doublereal vnn
doublereal vpp
} dshar4_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
char hps [8]
char hds [8]
char hcs [8]
char hlft [8]
char hrgt [8]
char hfwd [8]
char hback [8]
char hup [8]
char hdown [8]
char hto [8]
char hpast [8]
char hon [8]
char htanto [8]
char hpstan [8]
char hdynp [8]
char haerr [8]
char hcldat [8]
char hgerr [8]
} hblock_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
struct {
integer jhldfg
integer ithcnt
integer itabh [100]
} hold_
struct {
doublereal saveh [50]
} hsave_
struct {
integer lseqno
} sqnc_
struct {
doublereal com [36000]
} _BLNK__
static integer c__1 = 1
static integer c__8 = 8
static integer c__20104 = 20104
static integer c__20109 = 20109
static integer c__20102 = 20102
static integer c__20103 = 20103
static integer c__20105 = 20105
static integer c__20106 = 20106
static integer c__20107 = 20107
static integer c__20108 = 20108
static integer c__20110 = 20110
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 163 of file apt211.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
Referenced by apt211_().
#define charct_1 charct_
Definition at line 40 of file apt211.c.
Referenced by apt211_().
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dshar4_1 dshar4_
Definition at line 25 of file apt211.c.
Referenced by apt211_().
#define fxcor_1 fxcor_
Definition at line 34 of file apt211.c.
Referenced by apt211_().
#define hblock_1 hblock_
Definition at line 55 of file apt211.c.
Referenced by apt211_().
#define hold_1 hold_
Definition at line 145 of file apt211.c.
Referenced by apt211_().
#define holrth ((char *)&hblock_1 + 24)
Referenced by apt211_().
#define hsave_1 hsave_
Definition at line 151 of file apt211.c.
#define ifxcor_1 ifxcor_
Definition at line 122 of file apt211.c.
Referenced by apt211_().
#define isv1_1 isv1_
Definition at line 112 of file apt211.c.
Referenced by apt211_().
#define isv_1 isv_
Definition at line 105 of file apt211.c.
Referenced by apt211_().
#define knumbr_1 knumbr_
Definition at line 130 of file apt211.c.
Referenced by apt211_().
#define ldef_1 ldef_
Definition at line 96 of file apt211.c.
Referenced by apt211_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sqnc_1 sqnc_
Definition at line 157 of file apt211.c.
Referenced by apt211_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define sv1_1 sv1_
Definition at line 81 of file apt211.c.
#define sv_1 sv_
Definition at line 72 of file apt211.c.
Referenced by apt211_().
#define symfil_1 symfil_
Definition at line 139 of file apt211.c.
Referenced by apt211_().
#define tlldat_1 tlldat_
Definition at line 47 of file apt211.c.
#define znumbr_1 znumbr_
Definition at line 89 of file apt211.c.
Referenced by apt211_().
Function Documentation
integer apt211_ (doublereal * adress, doublereal * hdrect, integer * iaeee)
Definition at line 179 of file apt211.c.
References aerr_(), amind_(), apt200_(), apt234_(), apt235_(), apt236_(), apt240_(), arlm2_(), arlm3_(), bcdf_(), c__1, c__20102, c__20103, c__20104, c__20105, c__20106, c__20107, c__20108, c__20109, c__20110, c__8, canon, charct_1, cross_(), cuth_(), cutteh_(), dntcuh_(), dshar4_1, ewrite_(), first, fxcor_1, hblock_1, hold_1, holfrm_(), holrth, i__, ifxcor_1, indrph_(), indrvh_(), intolh_(), ir, isv1_1, isv_1, jj, k, knumbr_1, ldef_1, maxdph_(), outmsg_(), outtoh_(), sqnc_1, sv_1, symfil_1, test, thickh_(), tolerh_(), vnorm_(), and znumbr_1.
Referenced by apt201_(), and go_().
 {
     /* Initialized data */
     static integer modtyp[18]   /* was [3][6] */ = { 1,2,3,2,1,3,4,4,4,4,4,4,
         1,2,3,2,1,3 };
     static doublereal zlit2 = .0349;
     static logical first = TRUE_;
     static integer holdpp[8] = { 0,0,1308622848,1,1308622848,1,1308622848,1 };
     static char hnocs[8] = "NOCS    ";
     /* System generated locals */
     integer ret_val;
     doublereal d__1;
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, k, j6, nr, ir, jj, kk;
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer jap, tds[2], i20106;
     static logical kcs;
     static integer nwd, kfl4, iit;
     extern integer bcdf_(char *, ftnlen);
     static integer kcan, kfar;
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static char test[8];
     static integer isav, lsav, kipl;
     extern /* Subroutine */ int cuth_(void), apt200_(integer *, doublereal *,
         doublereal *), apt240_(integer *), apt234_(integer *, doublereal *
         ), apt235_(void), apt236_(void), arlm3_(void), arlm2_(void),
         amind_(void);
     static integer kfidn;
 #define canon ((doublereal *)&_BLNK__1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     static integer klmfl, kunfl, kstyp, ktlon;
     static doublereal spast;
     extern /* Subroutine */ int vnorm_(doublereal *, doublereal *), cross_(
         doublereal *, doublereal *, doublereal *);
 #define holrth ((char *)&hblock_1 + 24)
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     static doublereal cssave[10];
     extern /* Subroutine */ int holfrm_(doublereal *, char *, integer *,
         integer *, integer *, ftnlen);
     static integer kseqno, jseqno, kcscnt;
     extern /* Subroutine */ int ewrite_(integer *, integer *, integer *,
         integer *, integer *);
     static integer numdim;
     extern /* Subroutine */ int outmsg_(char *, ftnlen), tolerh_(void),
         cutteh_(void), dntcuh_(void), intolh_(void), outtoh_(void),
         maxdph_(void), indrvh_(void), indrph_(void), thickh_(void);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*     *** 8.  HOLRTH BLOCK *** */
 /*     ALPHA-NUMERIC LITERAL CONSTANTS. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /* ...            SYSTEM I/O FILE NAMES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...                SYSTEM I/O FILES */
 /* ++++ FLAG TO ALLOW A SECOND TRY WITHOUT CHECKING TA TO OVERCOME */
 /* ++++ ERROR 20106 */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
     /* Parameter adjustments */
     --adress;
     /* Function Body */
     if (first) {
     holdpp[0] = bcdf_("HOLD", (ftnlen)4);
     holdpp[1] = bcdf_("PP  ", (ftnlen)4);
     tds[0] = bcdf_(hblock_1.hds, (ftnlen)4);
     tds[1] = bcdf_(hblock_1.hds + 4, (ftnlen)4);
     first = FALSE_;
     }
     holfrm_(hdrect, test, &c__1, &c__8, &nwd, (ftnlen)8);
     if (*iaeee == 1) {
     goto L8010;
     }
     if (ifxcor_1.iaerr == 1) {
     goto L1000;
     }
     if (s_cmp(test, hnocs, (ftnlen)8, (ftnlen)8) == 0) {
     goto L8000;
     }
     if (ifxcor_1.igoto + ifxcor_1.ictdef <= 0) {
     goto L1;
     } else {
     goto L3000;
     }
 L1:
     for (i__ = 1; i__ <= 6; ++i__) {
     if (s_cmp(test, holrth + (i__ - 1 << 3), (ftnlen)8, (ftnlen)8) == 0) {
         goto L4002;
     }
 /* L4001: */
     }
     aerr_(&c__20104, "APT211  ", (ftnlen)8);
     goto L1000;
 L4002:
     isav = i__;
     if (! ldef_1.jds) {
     goto L4000;
     }
     kseqno = sqnc_1.lseqno;
     sqnc_1.lseqno = jseqno;
     kcscnt = ifxcor_1.icscnt;
     kcs = ldef_1.jcs;
     lsav = isv_1.isftyp[ifxcor_1.ids - 1];
     isv_1.isftyp[ifxcor_1.ids - 1] = ifxcor_1.msav;
     ifxcor_1.icscnt = 0;
     kipl = isv_1.ipl[ifxcor_1.ics - 1];
     klmfl = isv_1.limfl[ifxcor_1.ics - 1];
     kunfl = isv_1.iunfl[ifxcor_1.ics - 1];
     kfidn = isv_1.isfidn[ifxcor_1.ics - 1];
     kstyp = isv_1.isftyp[ifxcor_1.ics - 1];
     ktlon = isv_1.itlon[ifxcor_1.ics - 1];
     spast = sv_1.past[ifxcor_1.ics - 1];
     kcan = isv_1.icanon[ifxcor_1.ics - 1];
     kfl4 = isv1_1.ifl4[ifxcor_1.ics - 1];
     kfar = isv1_1.ifar[ifxcor_1.ics - 1];
     for (iit = 1; iit <= 10; ++iit) {
 /* L1530: */
     cssave[iit - 1] = canon[iit + 19];
     }
     apt200_(tds, &adress[1], &znumbr_1.z1);
     if (ifxcor_1.iaerr != 0) {
     goto L1000;
     }
     if (ifxcor_1.motmod == 0) {
     goto L4004;
     }
     isv_1.isftyp[ifxcor_1.ics - 1] = modtyp[ifxcor_1.motmod + isav * 3 - 4];
     if (isv_1.isftyp[ifxcor_1.ics - 1] == 2) {
     sv_1.past[ifxcor_1.ics - 1] = (doublereal) (-knumbr_1.k1);
     }
     ifxcor_1.is = ifxcor_1.ids;
     goto L9200;
 L4000:
     s_copy(charct_1.modfer, test, (ftnlen)6, (ftnlen)8);
     ifxcor_1.igo = isav;
     ifxcor_1.msav = isv_1.isftyp[ifxcor_1.ids - 1];
     ifxcor_1.is = ifxcor_1.ids;
     apt234_(tds, &adress[1]);
     if (ifxcor_1.iaerr != 0) {
     goto L1000;
     }
     if (ldef_1.jcs) {
     goto L9200;
     }
     jseqno = sqnc_1.lseqno;
     ldef_1.jds = TRUE_;
 /*     INTEG.ON EXFILE DP. 1ST WD UNNORM POWER,2ND INTEG VALUE */
     nr = 0;
     ewrite_(&symfil_1.exfile, &nr, holdpp, &c__8, &ir);
     hold_1.jhldfg = 1;
     goto L9999;
 L4004:
     aerr_(&c__20109, "APT211  ", (ftnlen)8);
     goto L1000;
 L9200:
     apt235_();
     if (ifxcor_1.iaerr <= 0) {
     goto L6000;
     } else {
     goto L1000;
     }
 L6000:
     apt240_(&numdim);
 /* L14: */
     ifxcor_1.icl = knumbr_1.k2;
     ifxcor_1.nw = 0;
 /* L19: */
     if (fxcor_1.cutdat[5] == 0.f) {
     goto L32;
     }
     numdim = knumbr_1.k1;
     goto L32;
 L72:
     apt236_();
     if (ifxcor_1.iaerr != 0) {
     goto L4006;
     }
     if (ldef_1.jds) {
     goto L4005;
     }
 L4006:
     hold_1.jhldfg = 0;
     hold_1.ithcnt = 1;
     ldef_1.jcs = FALSE_;
     ldef_1.jds = FALSE_;
     goto L9999;
 L4005:
     ldef_1.jcs = kcs;
     hold_1.jhldfg = 0;
     goto L9500;
 L9600:
     nr = 0;
     holdpp[7] = knumbr_1.k2;
     ewrite_(&symfil_1.exfile, &nr, holdpp, &c__8, &ir);
     holdpp[7] = knumbr_1.k1;
     isv_1.isftyp[ifxcor_1.ids - 1] = lsav;
     sqnc_1.lseqno = kseqno;
     if (! ldef_1.jcs) {
     goto L4000;
     }
     isv_1.ipl[ifxcor_1.ics - 1] = kipl;
     isv_1.limfl[ifxcor_1.ics - 1] = klmfl;
     isv_1.isfidn[ifxcor_1.ics - 1] = kfidn;
     isv_1.isftyp[ifxcor_1.ics - 1] = kstyp;
     isv_1.itlon[ifxcor_1.ics - 1] = ktlon;
     sv_1.past[ifxcor_1.ics - 1] = spast;
     isv_1.icanon[ifxcor_1.ics - 1] = kcan;
     isv1_1.ifl4[ifxcor_1.ics - 1] = kfl4;
     isv1_1.ifar[ifxcor_1.ics - 1] = kfar;
     ifxcor_1.icscnt = kcscnt;
     ldef_1.jds = FALSE_;
     for (iit = 1; iit <= 10; ++iit) {
 /* L1531: */
     canon[iit + 19] = cssave[iit - 1];
     }
     goto L4000;
 L32:
     j6 = 0;
     ifxcor_1.is = ifxcor_1.ips;
 /*  INITIALIZE VARIABLES FOR AMIND */
 L33:
     if (isv_1.jent[ifxcor_1.is - 1] != 0) {
     goto L301;
     } else {
     goto L302;
     }
 L301:
     isv_1.jtn[ifxcor_1.is - 1] = knumbr_1.k0;
     isv_1.iopset[ifxcor_1.is - 1] = 0;
     isv_1.ju1[ifxcor_1.is - 1] = 0;
     isv_1.jiops[ifxcor_1.is - 1] = 0;
 L302:
     jap = knumbr_1.k1;
 L201:
     amind_();
     if (ifxcor_1.iaerr != 0) {
     goto L1000;
     } else {
     goto L2000;
     }
 L2000:
     if (isv_1.ipl[ifxcor_1.is - 1] != 0) {
     goto L141;
     } else {
     goto L140;
     }
 L141:
     if ((d__1 = sv_1.s[ifxcor_1.is - 1]) < 0.) {
     goto L142;
     } else if (d__1 == 0) {
     goto L39;
     } else {
     goto L143;
     }
 L142:
     if (sv_1.s[ifxcor_1.is - 1] - sv_1.tau2[ifxcor_1.is - 1] + 1e-4 >= 0.) {
     goto L39;
     } else {
     goto L36;
     }
 L143:
     if (sv_1.s[ifxcor_1.is - 1] - sv_1.tau1[ifxcor_1.is - 1] - 1e-4 <= 0.) {
     goto L39;
     } else {
     goto L36;
     }
 L140:
     if ((d__1 = sv_1.rc[ifxcor_1.is - 1] * sv_1.s[ifxcor_1.is - 1]) < 0.) {
     goto L34;
     } else if (d__1 == 0) {
     goto L39;
     } else {
     goto L35;
     }
 L34:
     if ((d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1)) - znumbr_1.z9em1 *
         sv_1.tau[ifxcor_1.is - 1] - 1e-4 <= 0.) {
     goto L39;
     } else {
     goto L36;
     }
 L35:
     if ((d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1)) - sv_1.eps1[ifxcor_1.is -
         1] - .01 <= 0.) {
     goto L39;
     } else {
     goto L36;
     }
 L36:
     switch (jap) {
     case 1:  goto L505;
     case 2:  goto L508;
     case 3:  goto L504;
     case 4:  goto L204;
     }
 L505:
     if (isv_1.ipl[ifxcor_1.is - 1] != 0) {
     goto L506;
     } else {
     goto L202;
     }
 L202:
     if (isv_1.isftyp[ifxcor_1.is - 1] - knumbr_1.k3 != 0) {
     goto L504;
     } else {
     goto L507;
     }
 L504:
     sv_1.rc[ifxcor_1.is - 1] = -sv_1.rc[ifxcor_1.is - 1];
     jap += knumbr_1.k1;
     goto L201;
 L506:
     if (sv_1.th[ifxcor_1.is - 1] <= 0.) {
     goto L510;
     } else {
     goto L204;
     }
 L507:
     jap = knumbr_1.k4;
 L203:
     sv_1.z__[ifxcor_1.is - 1] = -sv_1.z__[ifxcor_1.is - 1];
     goto L201;
 L510:
     if (isv_1.iafl[ifxcor_1.is - 1] != 0) {
     goto L507;
     } else {
     goto L511;
     }
 L511:
     isv_1.jent[ifxcor_1.is - 1] = -knumbr_1.k1;
     jap = knumbr_1.k4;
     goto L201;
 L508:
     if (sv_1.th[ifxcor_1.is - 1] >= 0.) {
     goto L204;
     } else {
     goto L509;
     }
 L509:
     jap += knumbr_1.k1;
     goto L203;
 L204:
     if (j6 != 0) {
     goto L38;
     } else {
     goto L37;
     }
 /*  CUTTER NOT WITHIN TOLERANCE OF DRIVE SURFACE AT START OF CUT SEQUENCE */
 L38:
     aerr_(&c__20102, "APT211  ", (ftnlen)8);
     goto L1000;
 /*  CUTTER NOT WITHIN TOLERANCE OF PART SURFACE AT START OF CUT SEQUENCE */
 L37:
     aerr_(&c__20103, "APT211  ", (ftnlen)8);
     goto L1000;
 L40:
     j6 = knumbr_1.k1;
     ifxcor_1.is = ifxcor_1.ids;
     goto L33;
 L39:
     if (jap - knumbr_1.k1 != 0) {
     goto L480;
     } else {
     goto L481;
     }
 L480:
     sv_1.tpk[ifxcor_1.is * 3 - 3] = sv_1.tp[ifxcor_1.is * 3 - 3];
     sv_1.tpk[ifxcor_1.is * 3 - 2] = sv_1.tp[ifxcor_1.is * 3 - 2];
     sv_1.tpk[ifxcor_1.is * 3 - 1] = sv_1.tp[ifxcor_1.is * 3 - 1];
     sv_1.snk[ifxcor_1.is * 3 - 3] = sv_1.sn[ifxcor_1.is * 3 - 3];
     sv_1.snk[ifxcor_1.is * 3 - 2] = sv_1.sn[ifxcor_1.is * 3 - 2];
     sv_1.snk[ifxcor_1.is * 3 - 1] = sv_1.sn[ifxcor_1.is * 3 - 1];
     sv_1.sk[ifxcor_1.is * 3 - 3] = sv_1.s[ifxcor_1.is - 1];
 L481:
     if (j6 != 0) {
     goto L41;
     } else {
     goto L40;
     }
 /*  DETERMINE GENERAL DIRECTION OF FIRST CUT VECTOR AND STORE IN FWD */
 L41:
     for (k = 1; k <= 3; ++k) {
 /* L42: */
     dshar4_1.fwd[k - 1] = fxcor_1.te[k - 1] - fxcor_1.tek[k - 1];
     }
 /* L2001: */
     vnorm_(dshar4_1.fwd, dshar4_1.fwd);
 /*  IGO =1 IF LFT, =2 IF RGT, =3 IF FWD, =4 IF BACK, =5 IF UP, =6 IF DOWN */
 /*  RELATIVE TO LAST COMMAND */
     if (knumbr_1.k4 - ifxcor_1.igo >= 0) {
     goto L45;
     } else {
     goto L43;
     }
 L43:
     for (k = 1; k <= 3; ++k) {
 /* L44: */
     dshar4_1.fwd[k - 1] = fxcor_1.ta[k - 1];
     }
     goto L50;
 L45:
     cross_(dshar4_1.fwd, fxcor_1.ta, dshar4_1.fwd);
     vnorm_(dshar4_1.fwd, dshar4_1.fwd);
     if (fxcor_1.vtem > znumbr_1.z1em6) {
     goto L48;
     }
 /* L46: */
     cross_(fxcor_1.pmove, fxcor_1.ta, dshar4_1.fwd);
     vnorm_(dshar4_1.fwd, dshar4_1.fwd);
     if (ifxcor_1.ier != 0) {
     goto L47;
     } else {
     goto L48;
     }
 /*  FWD DIRECTION CANNOT BE DETERMINED */
 L47:
     aerr_(&c__20105, "APT211  ", (ftnlen)8);
     goto L1000;
 L48:
     if (knumbr_1.k3 - ifxcor_1.igo <= 0) {
     goto L49;
     } else {
     goto L50;
     }
 L49:
     cross_(fxcor_1.ta, dshar4_1.fwd, dshar4_1.fwd);
     vnorm_(dshar4_1.fwd, dshar4_1.fwd);
     if (ifxcor_1.ier != 0) {
     goto L147;
     } else {
     goto L50;
     }
 L147:
     goto L47;
 L50:
     switch (ifxcor_1.igo) {
     case 1:  goto L52;
     case 2:  goto L54;
     case 3:  goto L54;
     case 4:  goto L52;
     case 5:  goto L54;
     case 6:  goto L52;
     }
 L52:
     for (k = 1; k <= 3; ++k) {
 /* L53: */
     dshar4_1.fwd[k - 1] = -dshar4_1.fwd[k - 1];
     }
 /*  CALCULATE TI VECTOR PERPENDICULAR TO BOTH PART AND DRIVE SURFACE */
 /*  NORMALS */
 L54:
     cross_(&sv_1.sn[ifxcor_1.ips * 3 - 3], &sv_1.sn[ifxcor_1.ids * 3 - 3],
         fxcor_1.ti);
     vnorm_(fxcor_1.ti, fxcor_1.ti);
     if (ifxcor_1.ier != 0) {
     goto L58;
     } else {
     goto L60;
     }
 L58:
     for (k = 1; k <= 3; ++k) {
 /* L59: */
     fxcor_1.ti[k - 1] = dshar4_1.fwd[k - 1];
     }
     goto L67;
 /*  TI VECTOR AND FWD VECTOR SHOULD NOT BE ORTHOGONAL. IF SO CALL AERR */
 L60:
     fxcor_1.tem[0] = fxcor_1.ti[0] * dshar4_1.fwd[0] + fxcor_1.ti[1] *
         dshar4_1.fwd[1] + fxcor_1.ti[2] * dshar4_1.fwd[2];
     if (abs(fxcor_1.tem[0]) - zlit2 <= 0.) {
     goto L64;
     } else {
     goto L63;
     }
 L64:
     if (i20106 == 0) {
 /* ++++ HAVE SECOND TRY WITHOUT CHECKING TA TO AVOID ERROR 20106 */
     i20106 = 1;
     outmsg_("*** WARNING: ERROR 20106 IN APT201 ***", (ftnlen)38);
     outmsg_("*** TRY WITHOUT CHECKING TA        ***", (ftnlen)38);
     for (k = 1; k <= 3; ++k) {
         dshar4_1.fwd[k - 1] = fxcor_1.te[k - 1] - fxcor_1.tek[k - 1];
 /* L641: */
     }
     vnorm_(dshar4_1.fwd, dshar4_1.fwd);
     goto L50;
     } else {
     aerr_(&c__20106, "APT211  ", (ftnlen)8);
     goto L1000;
     }
 L63:
     if (fxcor_1.tem[0] <= 0.) {
     goto L65;
     } else {
     goto L67;
     }
 L65:
     for (k = 1; k <= 3; ++k) {
 /* L66: */
     fxcor_1.ti[k - 1] = -fxcor_1.ti[k - 1];
     }
 L67:
     if (numdim <= 0) {
     goto L68;
     } else {
     goto L73;
     }
 /*  ICSCNT = NUMBER OF CHECK SURFACES. IF MORE THAN ONE CHECK SURFACE 3D */
 /*  ROUTES USED */
 L68:
 /* L168: */
     if (ifxcor_1.i3dflg - knumbr_1.k1 != 0) {
     goto L130;
     } else {
     goto L73;
     }
 L130:
     if (ifxcor_1.icscnt - knumbr_1.k2 >= 0) {
     goto L73;
     } else {
     goto L69;
     }
 /*  IF THICKNESS OF PART, DRIVE, AND CHECK SURFACE NOT ZERO 3D ROUTES */
 /*  FOLLOWED */
 L69:
     if (sv_1.th[ifxcor_1.ips - 1] != 0.) {
     goto L173;
     } else {
     goto L70;
     }
 L173:
     goto L73;
 L70:
     if (sv_1.th[ifxcor_1.ids - 1] != 0.) {
     goto L174;
     } else {
     goto L71;
     }
 L174:
     goto L73;
 L71:
     if (sv_1.th[ifxcor_1.ics - 1] != 0.) {
     goto L73;
     } else {
     goto L76;
     }
 L73:
 /*  ENTRY FOR 3D CALCULATIONS */
 /* L732: */
     arlm3_();
     ret_val = (integer) (fxcor_1.temp[0] + .5f);
 L101:
     if (ifxcor_1.iaerr != 0) {
     goto L1000;
     } else {
     goto L72;
     }
 L76:
     ifxcor_1.is = ifxcor_1.ics;
     if (isv_1.isfidn[ifxcor_1.ids - 1] - knumbr_1.k3 >= 0) {
     goto L86;
     } else {
     goto L80;
     }
 L80:
     if (isv_1.isfidn[ifxcor_1.ics - 1] - knumbr_1.k3 >= 0) {
     goto L81;
     } else {
     goto L82;
     }
 /*  LINE TO LINE CASE */
 L82:
     ifxcor_1.jbr = knumbr_1.k3;
     goto L83;
 /*  CIRCLE TO LINE OR CIRCLE TO CIRCLE CASE */
 L86:
     ifxcor_1.jbr = knumbr_1.k1;
 /*  ENTRY FOR 2D CALCULATIONS */
 L83:
     arlm2_();
     ret_val = (integer) znumbr_1.z1;
     goto L101;
 /*  LINE TO CIRCLE CASE */
 L81:
     ifxcor_1.jbr = knumbr_1.k2;
     goto L83;
 L6001:
     if (ifxcor_1.igoto <= 0) {
     goto L3001;
     } else {
     goto L3002;
     }
 L3001:
     aerr_(&c__20107, "APT211  ", (ftnlen)8);
     goto L1000;
 L3002:
     aerr_(&c__20108, "APT211  ", (ftnlen)8);
 L1000:
 L6002:
     ret_val = (integer) znumbr_1.z1;
     goto L72;
 L3000:
     if (ifxcor_1.isrch <= 0) {
     goto L6001;
     } else {
     goto L6002;
     }
 L9999:
     return ret_val;
 L9500:
     jj = 0;
 L9510:
     ++jj;
     if (jj == hold_1.ithcnt) {
     goto L9590;
     }
     kk = hold_1.itabh[jj - 1];
     switch (kk) {
     case 1:  goto L9510;
     case 2:  goto L9510;
     case 3:  goto L9510;
     case 4:  goto L9504;
     case 5:  goto L9505;
     case 6:  goto L9506;
     case 7:  goto L9507;
     case 8:  goto L9508;
     case 9:  goto L9509;
     case 10:  goto L9550;
     case 11:  goto L9511;
     case 12:  goto L9512;
     case 13:  goto L9513;
     }
 L9504:
     tolerh_();
     goto L9510;
 L9505:
     cutteh_();
     goto L9510;
 L9506:
     cuth_();
     goto L9510;
 L9507:
     dntcuh_();
     goto L9510;
 L9508:
     intolh_();
     goto L9510;
 L9509:
     outtoh_();
     goto L9510;
 L9550:
     maxdph_();
     goto L9510;
 L9511:
     indrvh_();
     goto L9510;
 L9512:
     indrph_();
     goto L9510;
 L9513:
     thickh_();
     goto L9510;
 L9590:
     hold_1.ithcnt = 1;
     if (*iaeee == 1) {
     goto L8020;
     }
     goto L9600;
 L8000:
     kseqno = sqnc_1.lseqno;
     sqnc_1.lseqno = jseqno;
     apt235_();
     *iaeee = 1;
     aerr_(&c__20110, "APT211  ", (ftnlen)8);
 L8010:
     ifxcor_1.iaerr = 0;
     goto L9500;
 L8020:
     ifxcor_1.iaerr = 1;
     nr = 0;
     holdpp[7] = knumbr_1.k2;
     ewrite_(&symfil_1.exfile, &nr, holdpp, &c__8, &ir);
     holdpp[7] = knumbr_1.k1;
     sqnc_1.lseqno = kseqno;
 /* ....   RETURN TO CALLER */
     goto L1000;
 } /* apt211_ */
Variable Documentation
struct { ... } _BLNK__
doublereal a
Definition at line 18 of file apt211.c.
doublereal alp
Definition at line 28 of file apt211.c.
logical altmlt
Definition at line 92 of file apt211.c.
doublereal ax4[3]
Definition at line 28 of file apt211.c.
integer axfile
Definition at line 133 of file apt211.c.
doublereal b
Definition at line 18 of file apt211.c.
logical bnderr
Definition at line 92 of file apt211.c.
logical boundf
Definition at line 92 of file apt211.c.
doublereal c__
Definition at line 18 of file apt211.c.
integer c__1 = 1 static
Definition at line 167 of file apt211.c.
Referenced by apt211_().
integer c__20102 = 20102 static
Definition at line 171 of file apt211.c.
Referenced by apt211_().
integer c__20103 = 20103 static
Definition at line 172 of file apt211.c.
Referenced by apt211_().
integer c__20104 = 20104 static
Definition at line 169 of file apt211.c.
Referenced by apt211_().
integer c__20105 = 20105 static
Definition at line 173 of file apt211.c.
Referenced by apt211_().
integer c__20106 = 20106 static
Definition at line 174 of file apt211.c.
Referenced by apt211_().
integer c__20107 = 20107 static
Definition at line 175 of file apt211.c.
Referenced by apt211_().
integer c__20108 = 20108 static
Definition at line 176 of file apt211.c.
Referenced by apt211_().
integer c__20109 = 20109 static
Definition at line 170 of file apt211.c.
Referenced by apt211_().
integer c__20110 = 20110 static
Definition at line 177 of file apt211.c.
Referenced by apt211_().
integer c__8 = 8 static
Definition at line 168 of file apt211.c.
Referenced by apt211_().
doublereal cagl
Definition at line 28 of file apt211.c.
logical canflg
Definition at line 92 of file apt211.c.
doublereal cc[15]
Definition at line 58 of file apt211.c.
doublereal cendis
Definition at line 18 of file apt211.c.
struct { ... } charct_
integer clfil3
Definition at line 133 of file apt211.c.
integer clfile
Definition at line 133 of file apt211.c.
integer clfilp
Definition at line 133 of file apt211.c.
doublereal cmove[3]
Definition at line 18 of file apt211.c.
doublereal com[36000]
Definition at line 160 of file apt211.c.
doublereal com1
Definition at line 18 of file apt211.c.
doublereal com4
Definition at line 18 of file apt211.c.
doublereal corrad[8]
Definition at line 43 of file apt211.c.
doublereal cos1[5]
Definition at line 75 of file apt211.c.
integer cpfile
Definition at line 133 of file apt211.c.
doublereal cplfl[5]
Definition at line 75 of file apt211.c.
doublereal cptst[5]
Definition at line 75 of file apt211.c.
doublereal csd[5]
Definition at line 75 of file apt211.c.
doublereal cutdat[7]
Definition at line 28 of file apt211.c.
doublereal d1
Definition at line 18 of file apt211.c.
doublereal d2a
Definition at line 18 of file apt211.c.
doublereal degrad
Definition at line 84 of file apt211.c.
doublereal dir[3]
Definition at line 18 of file apt211.c.
doublereal dp
Definition at line 18 of file apt211.c.
doublereal dp1
Definition at line 18 of file apt211.c.
doublereal dpcnt
Definition at line 18 of file apt211.c.
doublereal dpe
Definition at line 18 of file apt211.c.
doublereal dpi
Definition at line 18 of file apt211.c.
doublereal dpl
Definition at line 18 of file apt211.c.
doublereal dplan[15]
Definition at line 75 of file apt211.c.
doublereal dpmax
Definition at line 28 of file apt211.c.
doublereal dpmx1[5]
Definition at line 75 of file apt211.c.
struct { ... } dshar4_
integer elfil1
Definition at line 133 of file apt211.c.
integer elfil2
Definition at line 133 of file apt211.c.
integer elfil3
Definition at line 133 of file apt211.c.
integer elfil4
Definition at line 133 of file apt211.c.
integer elfile
Definition at line 133 of file apt211.c.
doublereal eps1[5]
Definition at line 58 of file apt211.c.
doublereal eps2[5]
Definition at line 58 of file apt211.c.
doublereal eps3[5]
Definition at line 58 of file apt211.c.
doublereal eps4[5]
Definition at line 58 of file apt211.c.
doublereal eps6[5]
Definition at line 58 of file apt211.c.
doublereal eps8[5]
Definition at line 58 of file apt211.c.
integer exfile
Definition at line 133 of file apt211.c.
doublereal flipck
Definition at line 18 of file apt211.c.
doublereal fwd[3]
Definition at line 18 of file apt211.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file apt211.c.
char haerr[8]
Definition at line 50 of file apt211.c.
char hback[8]
Definition at line 50 of file apt211.c.
struct { ... } hblock_
char hcldat[8]
Definition at line 50 of file apt211.c.
char hcs[8]
Definition at line 50 of file apt211.c.
char hdown[8]
Definition at line 50 of file apt211.c.
char hds[8]
Definition at line 50 of file apt211.c.
char hdynp[8]
Definition at line 50 of file apt211.c.
char hfwd[8]
Definition at line 50 of file apt211.c.
char hgerr[8]
Definition at line 50 of file apt211.c.
doublereal hi
Definition at line 28 of file apt211.c.
char hlft[8]
Definition at line 50 of file apt211.c.
struct { ... } hold_
char hon[8]
Definition at line 50 of file apt211.c.
char hpast[8]
Definition at line 50 of file apt211.c.
char hps[8]
Definition at line 50 of file apt211.c.
char hpstan[8]
Definition at line 50 of file apt211.c.
char hrgt[8]
Definition at line 50 of file apt211.c.
struct { ... } hsave_
char htanto[8]
Definition at line 50 of file apt211.c.
char hto[8]
Definition at line 50 of file apt211.c.
char hup[8]
Definition at line 50 of file apt211.c.
integer i3dflg
Definition at line 115 of file apt211.c.
integer iaerr
Definition at line 115 of file apt211.c.
integer iafl[5]
Definition at line 99 of file apt211.c.
integer iautps
Definition at line 115 of file apt211.c.
integer ibegin
Definition at line 115 of file apt211.c.
integer ic
Definition at line 115 of file apt211.c.
integer icanon[5]
Definition at line 99 of file apt211.c.
integer icheck
Definition at line 115 of file apt211.c.
integer icl
Definition at line 115 of file apt211.c.
integer ics
Definition at line 115 of file apt211.c.
integer icscnt
Definition at line 115 of file apt211.c.
integer ictdef
Definition at line 115 of file apt211.c.
integer icut
Definition at line 115 of file apt211.c.
integer ids
Definition at line 115 of file apt211.c.
integer ier
Definition at line 115 of file apt211.c.
integer ifar[5]
Definition at line 108 of file apt211.c.
integer ifl4[5]
Definition at line 108 of file apt211.c.
struct { ... } ifxcor_
integer igo
Definition at line 115 of file apt211.c.
integer igoto
Definition at line 115 of file apt211.c.
integer igoug
Definition at line 115 of file apt211.c.
integer igs
Definition at line 115 of file apt211.c.
integer index[5]
Definition at line 99 of file apt211.c.
integer indir__[5]
Definition at line 99 of file apt211.c.
integer infile__
Definition at line 133 of file apt211.c.
integer inops
Definition at line 115 of file apt211.c.
integer iop[5]
Definition at line 99 of file apt211.c.
integer iopset[5]
Definition at line 99 of file apt211.c.
integer ipl[5]
Definition at line 99 of file apt211.c.
integer ips
Definition at line 115 of file apt211.c.
integer ipsdef
Definition at line 115 of file apt211.c.
integer ipt1
Definition at line 115 of file apt211.c.
integer is
Definition at line 115 of file apt211.c.
integer iseg
Definition at line 115 of file apt211.c.
integer iseqno
Definition at line 115 of file apt211.c.
integer isfidn[5]
Definition at line 99 of file apt211.c.
integer isftyp[5]
Definition at line 99 of file apt211.c.
integer isigcr[5]
Definition at line 99 of file apt211.c.
integer ispare[26]
Definition at line 133 of file apt211.c.
integer isrch
Definition at line 115 of file apt211.c.
integer istrup
Definition at line 115 of file apt211.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 99 of file apt211.c.
integer it
Definition at line 115 of file apt211.c.
integer itabh[100]
Definition at line 142 of file apt211.c.
integer ithcnt
Definition at line 142 of file apt211.c.
integer itlon[5]
Definition at line 99 of file apt211.c.
integer itseg[5]
Definition at line 99 of file apt211.c.
integer itsegk[5]
Definition at line 99 of file apt211.c.
integer iunfl[5]
Definition at line 99 of file apt211.c.
integer j20[5]
Definition at line 108 of file apt211.c.
integer j21[5]
Definition at line 108 of file apt211.c.
integer j22[5]
Definition at line 108 of file apt211.c.
integer j23[5]
Definition at line 108 of file apt211.c.
integer j50[5]
Definition at line 108 of file apt211.c.
integer j51[5]
Definition at line 108 of file apt211.c.
integer jbr
Definition at line 115 of file apt211.c.
logical jcs
Definition at line 92 of file apt211.c.
logical jds
Definition at line 92 of file apt211.c.
integer jent[5]
Definition at line 99 of file apt211.c.
integer jhldfg
Definition at line 142 of file apt211.c.
integer jiops[5]
Definition at line 99 of file apt211.c.
integer jph[5]
Definition at line 108 of file apt211.c.
integer jsw
Definition at line 115 of file apt211.c.
integer jtlflg[5]
Definition at line 99 of file apt211.c.
integer jtn[5]
Definition at line 99 of file apt211.c.
integer ju1[5]
Definition at line 99 of file apt211.c.
integer k0
Definition at line 125 of file apt211.c.
integer k1
Definition at line 125 of file apt211.c.
integer k10
Definition at line 125 of file apt211.c.
integer k1013
Definition at line 125 of file apt211.c.
integer k12
Definition at line 125 of file apt211.c.
integer k13
Definition at line 125 of file apt211.c.
integer k15
Definition at line 125 of file apt211.c.
integer k16
Definition at line 125 of file apt211.c.
integer k18
Definition at line 125 of file apt211.c.
integer k19
Definition at line 125 of file apt211.c.
integer k1e4
Definition at line 125 of file apt211.c.
integer k1e6
Definition at line 125 of file apt211.c.
integer k2
Definition at line 125 of file apt211.c.
integer k23
Definition at line 125 of file apt211.c.
integer k24
Definition at line 125 of file apt211.c.
integer k25
Definition at line 125 of file apt211.c.
integer k26
Definition at line 125 of file apt211.c.
integer k27
Definition at line 125 of file apt211.c.
integer k29
Definition at line 125 of file apt211.c.
integer k3
Definition at line 125 of file apt211.c.
integer k30
Definition at line 125 of file apt211.c.
integer k31
Definition at line 125 of file apt211.c.
integer k32
Definition at line 125 of file apt211.c.
integer k33
Definition at line 125 of file apt211.c.
integer k34
Definition at line 125 of file apt211.c.
integer k4
Definition at line 125 of file apt211.c.
integer k44
Definition at line 125 of file apt211.c.
integer k45
Definition at line 125 of file apt211.c.
integer k46
Definition at line 125 of file apt211.c.
integer k47
Definition at line 125 of file apt211.c.
integer k48
Definition at line 125 of file apt211.c.
integer k5
Definition at line 125 of file apt211.c.
integer k50
Definition at line 125 of file apt211.c.
integer k51
Definition at line 125 of file apt211.c.
integer k52
Definition at line 125 of file apt211.c.
integer k6
Definition at line 125 of file apt211.c.
integer k7
Definition at line 125 of file apt211.c.
integer k8
Definition at line 125 of file apt211.c.
integer k9
Definition at line 125 of file apt211.c.
integer km1
Definition at line 125 of file apt211.c.
struct { ... } knumbr_
integer ldafil
Definition at line 133 of file apt211.c.
struct { ... } ldef_
integer libfil
Definition at line 133 of file apt211.c.
integer limfl[5]
Definition at line 99 of file apt211.c.
integer lseqno
Definition at line 154 of file apt211.c.
integer lsv
Definition at line 115 of file apt211.c.
integer lsv1
Definition at line 115 of file apt211.c.
integer mactxt
Definition at line 133 of file apt211.c.
integer mantax
Definition at line 115 of file apt211.c.
char modfer[6]
Definition at line 37 of file apt211.c.
integer motmod
Definition at line 115 of file apt211.c.
integer msav
Definition at line 115 of file apt211.c.
integer mulout
Definition at line 115 of file apt211.c.
integer nfil12
Definition at line 133 of file apt211.c.
integer nfil13
Definition at line 133 of file apt211.c.
integer nmbseg
Definition at line 115 of file apt211.c.
integer nmpnts
Definition at line 115 of file apt211.c.
integer notan[5]
Definition at line 108 of file apt211.c.
integer nrec
Definition at line 115 of file apt211.c.
integer numax
Definition at line 115 of file apt211.c.
integer numcnt
Definition at line 115 of file apt211.c.
integer nump
Definition at line 115 of file apt211.c.
integer numpt1
Definition at line 115 of file apt211.c.
integer numsfs
Definition at line 115 of file apt211.c.
integer numsur
Definition at line 115 of file apt211.c.
integer nw
Definition at line 115 of file apt211.c.
integer nwds
Definition at line 115 of file apt211.c.
doublereal ogle[3]
Definition at line 18 of file apt211.c.
doublereal p1[3]
Definition at line 18 of file apt211.c.
doublereal p2[3]
Definition at line 18 of file apt211.c.
doublereal param[6]
Definition at line 18 of file apt211.c.
doublereal past[5]
Definition at line 58 of file apt211.c.
logical pchlst
Definition at line 92 of file apt211.c.
doublereal pi
Definition at line 84 of file apt211.c.
doublereal plncs[5]
Definition at line 75 of file apt211.c.
doublereal plnd[5]
Definition at line 58 of file apt211.c.
doublereal plnd1[5]
Definition at line 75 of file apt211.c.
doublereal plnv[15]
Definition at line 58 of file apt211.c.
doublereal pltst[5]
Definition at line 75 of file apt211.c.
doublereal pmove[3]
Definition at line 28 of file apt211.c.
integer pnchfl
Definition at line 133 of file apt211.c.
integer pofile
Definition at line 133 of file apt211.c.
logical prnton
Definition at line 92 of file apt211.c.
integer pxfile
Definition at line 133 of file apt211.c.
doublereal r__[6]
Definition at line 18 of file apt211.c.
doublereal ra
Definition at line 28 of file apt211.c.
doublereal rc[5]
Definition at line 58 of file apt211.c.
doublereal rc1
Definition at line 28 of file apt211.c.
doublereal rdrn
Definition at line 18 of file apt211.c.
logical refflg
Definition at line 92 of file apt211.c.
logical refmot
Definition at line 92 of file apt211.c.
doublereal refpnt[3]
Definition at line 18 of file apt211.c.
doublereal ri[8]
Definition at line 43 of file apt211.c.
doublereal s[5]
Definition at line 58 of file apt211.c.
doublereal sagl
Definition at line 28 of file apt211.c.
doublereal save[5]
Definition at line 58 of file apt211.c.
doublereal saveh[50]
Definition at line 148 of file apt211.c.
doublereal savpar[4]
Definition at line 18 of file apt211.c.
doublereal seg[9]
Definition at line 18 of file apt211.c.
doublereal sfvct[15]
Definition at line 58 of file apt211.c.
doublereal sk[15]
Definition at line 58 of file apt211.c.
doublereal slope
Definition at line 18 of file apt211.c.
doublereal slx[15]
Definition at line 58 of file apt211.c.
doublereal sn[15]
Definition at line 58 of file apt211.c.
doublereal snk[15]
Definition at line 58 of file apt211.c.
doublereal snl[15]
Definition at line 58 of file apt211.c.
doublereal sp[15]
Definition at line 58 of file apt211.c.
doublereal spk[15]
Definition at line 58 of file apt211.c.
doublereal spl[15]
Definition at line 58 of file apt211.c.
struct { ... } sqnc_
doublereal sqroot
Definition at line 18 of file apt211.c.
doublereal stck[5]
Definition at line 75 of file apt211.c.
doublereal stck1[5]
Definition at line 75 of file apt211.c.
doublereal stck2[5]
Definition at line 75 of file apt211.c.
doublereal stckn[5]
Definition at line 75 of file apt211.c.
doublereal strtno
Definition at line 28 of file apt211.c.
logical subflg
Definition at line 92 of file apt211.c.
doublereal surd
Definition at line 28 of file apt211.c.
struct { ... } sv1_
struct { ... } sv_
struct { ... } symfil_
doublereal ta[3]
Definition at line 28 of file apt211.c.
logical tabprt
Definition at line 92 of file apt211.c.
doublereal tak[3]
Definition at line 28 of file apt211.c.
doublereal tal[3]
Definition at line 28 of file apt211.c.
doublereal tangl
Definition at line 18 of file apt211.c.
doublereal tanhi[8]
Definition at line 43 of file apt211.c.
doublereal tanlo[8]
Definition at line 43 of file apt211.c.
doublereal tau[5]
Definition at line 58 of file apt211.c.
doublereal tau1[5]
Definition at line 58 of file apt211.c.
doublereal tau2[5]
Definition at line 58 of file apt211.c.
doublereal tcont[9]
Definition at line 43 of file apt211.c.
doublereal te[3]
Definition at line 28 of file apt211.c.
doublereal tee[15]
Definition at line 75 of file apt211.c.
doublereal tek[3]
Definition at line 28 of file apt211.c.
doublereal tel[3]
Definition at line 28 of file apt211.c.
doublereal tem[10]
Definition at line 28 of file apt211.c.
doublereal temp[24]
Definition at line 28 of file apt211.c.
doublereal tes[3]
Definition at line 18 of file apt211.c.
doublereal tew[3]
Definition at line 18 of file apt211.c.
doublereal th[5]
Definition at line 58 of file apt211.c.
doublereal ti[3]
Definition at line 28 of file apt211.c.
integer tifile
Definition at line 133 of file apt211.c.
doublereal tik[3]
Definition at line 28 of file apt211.c.
doublereal til[3]
Definition at line 28 of file apt211.c.
doublereal tlhit
Definition at line 28 of file apt211.c.
doublereal tlhite[8]
Definition at line 43 of file apt211.c.
doublereal tlinc[9]
Definition at line 43 of file apt211.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file apt211.c.
doublereal tn[15]
Definition at line 58 of file apt211.c.
doublereal tnl[15]
Definition at line 75 of file apt211.c.
doublereal toolht[15]
Definition at line 58 of file apt211.c.
doublereal toolwd[5]
Definition at line 58 of file apt211.c.
doublereal tp[15]
Definition at line 58 of file apt211.c.
doublereal tpk[15]
Definition at line 58 of file apt211.c.
doublereal u1[15]
Definition at line 58 of file apt211.c.
doublereal u1k[15]
Definition at line 58 of file apt211.c.
doublereal u2[3]
Definition at line 18 of file apt211.c.
doublereal umax[8]
Definition at line 43 of file apt211.c.
logical unflag
Definition at line 92 of file apt211.c.
doublereal unn
Definition at line 18 of file apt211.c.
doublereal upp
Definition at line 18 of file apt211.c.
doublereal uvec[3]
Definition at line 18 of file apt211.c.
doublereal v[3]
Definition at line 18 of file apt211.c.
doublereal varble[5]
Definition at line 58 of file apt211.c.
doublereal vint
Definition at line 18 of file apt211.c.
doublereal vl
Definition at line 18 of file apt211.c.
integer vlfile
Definition at line 133 of file apt211.c.
doublereal vndir[15]
Definition at line 58 of file apt211.c.
doublereal vnn
Definition at line 18 of file apt211.c.
doublereal vpp
Definition at line 18 of file apt211.c.
doublereal vt[15]
Definition at line 58 of file apt211.c.
doublereal vtem
Definition at line 28 of file apt211.c.
integer xcan
Definition at line 133 of file apt211.c.
integer xnum
Definition at line 133 of file apt211.c.
doublereal z0
Definition at line 84 of file apt211.c.
doublereal z1
Definition at line 84 of file apt211.c.
doublereal z10
Definition at line 84 of file apt211.c.
doublereal z11em1
Definition at line 84 of file apt211.c.
doublereal z12em1
Definition at line 84 of file apt211.c.
doublereal z1e38
Definition at line 84 of file apt211.c.
doublereal z1e6
Definition at line 84 of file apt211.c.
doublereal z1em1
Definition at line 84 of file apt211.c.
doublereal z1em2
Definition at line 84 of file apt211.c.
doublereal z1em3
Definition at line 84 of file apt211.c.
doublereal z1em5
Definition at line 84 of file apt211.c.
doublereal z1em6
Definition at line 84 of file apt211.c.
doublereal z1em7
Definition at line 84 of file apt211.c.
doublereal z1em9
Definition at line 84 of file apt211.c.
doublereal z2
Definition at line 84 of file apt211.c.
doublereal z3
Definition at line 84 of file apt211.c.
doublereal z5
Definition at line 84 of file apt211.c.
doublereal z5em1
Definition at line 84 of file apt211.c.
doublereal z5em6
Definition at line 84 of file apt211.c.
doublereal z6em1
Definition at line 84 of file apt211.c.
doublereal z90
Definition at line 84 of file apt211.c.
doublereal z9em1
Definition at line 84 of file apt211.c.
doublereal z__[5]
Definition at line 58 of file apt211.c.
logical zflag
Definition at line 92 of file apt211.c.
doublereal zl
Definition at line 18 of file apt211.c.
doublereal zl1
Definition at line 18 of file apt211.c.
doublereal zlnorm[3]
Definition at line 18 of file apt211.c.
doublereal zlpnt[3]
Definition at line 18 of file apt211.c.
doublereal zm1
Definition at line 84 of file apt211.c.
struct { ... } znumbr_