My Project: APT299.c File Reference
APT299.c File Reference
#include "f2c.h"
Macros
#define knumbr_1 knumbr_
#define symfil_1 symfil_
Functions
int apt299_ (integer *arg1, integer *arg2, integer *arg3, integer *arg4)
Variables
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
Macro Definition Documentation
#define knumbr_1 knumbr_
Definition at line 23 of file APT299.c.
Referenced by apt299_().
#define symfil_1 symfil_
Definition at line 32 of file APT299.c.
Referenced by apt299_().
Function Documentation
int apt299_ (integer * arg1, integer * arg2, integer * arg3, integer * arg4)
Definition at line 70 of file APT299.c.
References arg1, arg2, bcdf_(), blank, ewrite_(), first, i__, ir, j, knumbr_1, l, l1, record_(), symfil_1, t, and w.
Referenced by cldat_(), comp3d_(), cut_(), cuth_(), cutred_(), cutteh_(), cuttes_(), dntcuh_(), dntcut_(), fedput_(), gotopn_(), gougck_(), intol_(), intolh_(), maxdp_(), maxdph_(), multax_(), ndtest_(), numpts_(), outtoh_(), outtol_(), pocket_(), smil_(), thick_(), thickh_(), toler_(), tolerh_(), and xcall_().
 {
     /* Initialized data */
     static logical first = TRUE_;
     static integer iunorm = 1308622848;
     static integer clsize[27] = { 1,1,4,4,7,7,4,10,10,10,7,10,0,0,79,10,0,0,0,
         12,3,3,1,1,1,1,0 };
     /* System generated locals */
     integer i__1, i__2;
     /* Local variables */
     static integer i__, j, l, t, w[200], l1, nr, ir;
     static logical odd;
     static integer ido;
     extern integer bcdf_(char *, ftnlen);
     static integer size, blank, start;
     extern /* Subroutine */ int record_(integer *);
     static integer nopair;
     extern /* Subroutine */ int ewrite_(integer *, integer *, integer *,
         integer *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ......  LOCAL VARIABLES */
 /* ...                SYSTEM I/O FILES */
     /* Parameter adjustments */
     --arg4;
     --arg3;
     --arg2;
     --arg1;
     /* Function Body */
 /* ******************************************************************** */
 /* ... CHECK IF THIS IS THE FIRST CALL TO APT299 FOR THE CURRENT EXFILE */
 /* ... RECORD BEING CREATED. IF NOT,CONTINUE INSERTING ITEMS IN THE */
 /* ... RECORD. IF IT IS THE FIRST CALL,DO HOUSEKEEPING. */
     if (! first) {
     goto L15;
     }
 /* ... SET FIRST CALL FLAG FALSE. */
     first = FALSE_;
 /*    INITIALIZE BLANK */
     blank = bcdf_("    ", (ftnlen)4);
 /* ... SET NOPAIR = THE NUMBER OF DATA ITEM ARGUMENT PAIRS. */
     nopair = arg1[1];
 /* ... SET FIRST RECORD WORD = MAJOR WORD. */
 /* ... SET SECOND RECORD WORD = PART PROGRAM STATEMENT INTERNAL SEQUENCE */
 /* ... NUMBER */
     w[2] = iunorm;
     w[0] = arg2[1];
     w[1] = arg2[2];
     record_(&w[3]);
 /* ... IF THERE ARE NO MORE ARGUMENTS,ADD ALPHANUMERIC DATA ITEM */
 /* ... AND WRITE THE RECORD. */
     if (nopair > knumbr_1.k0) {
     goto L10;
     }
 /* L5: */
     w[6] = iunorm;
     w[7] = knumbr_1.k2;
     w[8] = blank;
     w[9] = blank;
     j = 10;
     goto L80;
 /* ... INITIALIZE RECORD INDEX */
 L10:
     j = knumbr_1.k6;
 /* ... INSERT DATA ITEMS IN RECORD. */
 /* ... INITIALIZE DO LOOP INDEX */
     ido = knumbr_1.k1;
 L15:
     start = ido;
     i__1 = nopair;
     for (i__ = start; i__ <= i__1; ++i__) {
 /* ... IF I IS EVEN,SET ODD = .FALSE. INDICATING ARG1 AND ARG2 ARE TO BE */
 /* ...    USED DURING THIS ITERATION. */
 /* ... IF I IS ODD, SET ODD = .TRUE. INDICATING ARG3 AND ARG4 ARE TO BE */
 /* ...    USED DURING THIS ITERATION. */
     odd = TRUE_;
     if (i__ - knumbr_1.k2 * (i__ / knumbr_1.k2) == knumbr_1.k0) {
         odd = FALSE_;
     }
 /* ... INSERT ITEM INDICATOR CODE IN RECORD. */
     j += knumbr_1.k2;
     w[j - 2] = iunorm;
     w[j - 1] = arg1[1];
     if (odd) {
         w[j - 1] = arg3[1];
     }
     t = w[j - 1];
     if (t > knumbr_1.k2 && t < knumbr_1.k27) {
         w[j - 1] = knumbr_1.k4;
     }
     if (t == knumbr_1.k27) {
         w[j - 1] = knumbr_1.k3;
     }
 /* ... SET SIZE = CLSIZE FOR THIS ITEM. FROM THE MAGNITUDE OF SIZE */
 /* ... DETERMINE THE TYPE OF THE ITEM. */
     size = clsize[t - 1];
     if ((i__2 = size - knumbr_1.k1) < 0) {
         goto L20;
     } else if (i__2 == 0) {
         goto L40;
     } else {
         goto L30;
     }
 /* ... ALPHANUMERIC DATA ITEM STRING --- INSERT NUMBER OF ITEMS,TOTAL */
 /* ... CHARACTER COUNT, AND DATA ITEMS IN THE RECORD. */
 /* ... RESET SIZE = NUMBER OF ITEMS IN THE STRING. */
 L20:
     j += knumbr_1.k4;
     w[j - 2] = iunorm;
     w[j - 4] = iunorm;
     size = arg4[1];
     w[j - 1] = arg4[2];
     if (odd) {
         goto L22;
     }
     size = arg2[1];
     w[j - 1] = arg2[2];
     goto L25;
 L22:
     if (w[j - 1] != knumbr_1.k0) {
         goto L25;
     }
     w[j - 3] = knumbr_1.k2;
     j += knumbr_1.k2;
     w[j - 2] = blank;
     w[j - 1] = blank;
     goto L80;
 /* ... SET STRING ARRAY SUBSCRIPT =3. */
 L25:
     w[j - 3] = (size + knumbr_1.k1) / knumbr_1.k2;
     l = knumbr_1.k3;
     goto L50;
 /* ... GEOMETRIC VARIABLE --- INSERT NUMBER OF ITEMS AND GEOMETRIC DATA. */
 L30:
     j += knumbr_1.k2;
     w[j - 2] = iunorm;
     w[j - 1] = size;
 /* ... FLOATING POINT OR ALPHANUMERIC DATA ITEM.--- SET ARRAY SUBSCRIPT */
 /* ... =1. */
 L40:
     l = knumbr_1.k1;
     size <<= 1;
 /* ... ADD ARRAY ELEMENTS TO RECORD. */
 L50:
     l1 = l;
     i__2 = size;
     for (l = l1; l <= i__2; ++l) {
         j += knumbr_1.k1;
         w[j - 1] = arg2[l];
         if (odd) {
         w[j - 1] = arg4[l];
         }
 /* L60: */
     }
 /* ... CHECK IF IT IS NECESSARY TO RETURN TO THE PART PROGRAM FOR MORE */
 /* ... ARGUMENTS. */
     if (! odd || i__ == nopair) {
         goto L70;
     }
     ido = i__ + 1;
     goto L99;
 L70:
     ;
     }
 /* ... SET THIRD RECORD WORD = NUMBER OF DATA ITEMS, RESET FIRST CALL FLAG */
 /* ... .TRUE., WRITE RECORD TO EXFILE ,AND RETURN TO CALLER. */
 L80:
     w[4] = iunorm;
     if (j - knumbr_1.k2 * (j / knumbr_1.k2) == knumbr_1.k0) {
     goto L85;
     }
     ++j;
     w[j - 1] = blank;
 L85:
     w[5] = j / 2 - knumbr_1.k3;
     first = TRUE_;
     nr = 0;
     ewrite_(&symfil_1.exfile, &nr, w, &j, &ir);
 L99:
     return 0;
 } /* apt299_ */
Variable Documentation
integer axfile
Definition at line 26 of file APT299.c.
integer clfil3
Definition at line 26 of file APT299.c.
integer clfile
Definition at line 26 of file APT299.c.
integer clfilp
Definition at line 26 of file APT299.c.
integer cpfile
Definition at line 26 of file APT299.c.
integer elfil1
Definition at line 26 of file APT299.c.
integer elfil2
Definition at line 26 of file APT299.c.
integer elfil3
Definition at line 26 of file APT299.c.
integer elfil4
Definition at line 26 of file APT299.c.
integer elfile
Definition at line 26 of file APT299.c.
integer exfile
Definition at line 26 of file APT299.c.
integer infile__
Definition at line 26 of file APT299.c.
integer ispare[26]
Definition at line 26 of file APT299.c.
integer k0
Definition at line 18 of file APT299.c.
integer k1
Definition at line 18 of file APT299.c.
integer k10
Definition at line 18 of file APT299.c.
integer k1013
Definition at line 18 of file APT299.c.
integer k12
Definition at line 18 of file APT299.c.
integer k13
Definition at line 18 of file APT299.c.
integer k15
Definition at line 18 of file APT299.c.
integer k16
Definition at line 18 of file APT299.c.
integer k18
Definition at line 18 of file APT299.c.
integer k19
Definition at line 18 of file APT299.c.
integer k1e4
Definition at line 18 of file APT299.c.
integer k1e6
Definition at line 18 of file APT299.c.
integer k2
Definition at line 18 of file APT299.c.
integer k23
Definition at line 18 of file APT299.c.
integer k24
Definition at line 18 of file APT299.c.
integer k25
Definition at line 18 of file APT299.c.
integer k26
Definition at line 18 of file APT299.c.
integer k27
Definition at line 18 of file APT299.c.
integer k29
Definition at line 18 of file APT299.c.
integer k3
Definition at line 18 of file APT299.c.
integer k30
Definition at line 18 of file APT299.c.
integer k31
Definition at line 18 of file APT299.c.
integer k32
Definition at line 18 of file APT299.c.
integer k33
Definition at line 18 of file APT299.c.
integer k34
Definition at line 18 of file APT299.c.
integer k4
Definition at line 18 of file APT299.c.
integer k44
Definition at line 18 of file APT299.c.
integer k45
Definition at line 18 of file APT299.c.
integer k46
Definition at line 18 of file APT299.c.
integer k47
Definition at line 18 of file APT299.c.
integer k48
Definition at line 18 of file APT299.c.
integer k5
Definition at line 18 of file APT299.c.
integer k50
Definition at line 18 of file APT299.c.
integer k51
Definition at line 18 of file APT299.c.
integer k52
Definition at line 18 of file APT299.c.
integer k6
Definition at line 18 of file APT299.c.
integer k7
Definition at line 18 of file APT299.c.
integer k8
Definition at line 18 of file APT299.c.
integer k9
Definition at line 18 of file APT299.c.
integer km1
Definition at line 18 of file APT299.c.
struct { ... } knumbr_
integer ldafil
Definition at line 26 of file APT299.c.
integer libfil
Definition at line 26 of file APT299.c.
integer mactxt
Definition at line 26 of file APT299.c.
integer nfil12
Definition at line 26 of file APT299.c.
integer nfil13
Definition at line 26 of file APT299.c.
integer pnchfl
Definition at line 26 of file APT299.c.
integer pofile
Definition at line 26 of file APT299.c.
integer pxfile
Definition at line 26 of file APT299.c.
struct { ... } symfil_
integer tifile
Definition at line 26 of file APT299.c.
integer vlfile
Definition at line 26 of file APT299.c.
integer xcan
Definition at line 26 of file APT299.c.
integer xnum
Definition at line 26 of file APT299.c.