My Project: APT233.c File Reference
APT233.c File Reference
#include "f2c.h"
Macros
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define hblock_1 hblock_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define dsname_1 dsname_
#define symfil_1 symfil_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define iferm ((integer *)equiv_2)
#define dcldat ((doublereal *)&equiv_3)
#define kcldat ((integer *)&equiv_3)
#define fermod (equiv_2)
Functions
int apt233_ (void)
Variables
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
char hps [8]
char hds [8]
char hcs [8]
char hlft [8]
char hrgt [8]
char hfwd [8]
char hback [8]
char hup [8]
char hdown [8]
char hto [8]
char hpast [8]
char hon [8]
char htanto [8]
char hpstan [8]
char hdynp [8]
char haerr [8]
char hcldat [8]
char hgerr [8]
} hblock_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
doublereal dsname
integer namsub
} dsname_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
static integer c__10 = 10
static integer c__18 = 18
Macro Definition Documentation
#define charct_1 charct_
Definition at line 30 of file APT233.c.
Referenced by apt233_().
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dcldat ((doublereal *)&equiv_3)
Referenced by apt233_().
#define dsname_1 dsname_
Definition at line 78 of file APT233.c.
Referenced by apt233_().
#define fermod (equiv_2)
Referenced by apt233_().
#define fxcor_1 fxcor_
Definition at line 24 of file APT233.c.
Referenced by apt233_().
#define hblock_1 hblock_
Definition at line 45 of file APT233.c.
#define iferm ((integer *)equiv_2)
Referenced by apt233_().
#define ifxcor_1 ifxcor_
Definition at line 55 of file APT233.c.
Referenced by apt233_().
#define ishr18_1 ishr18_
Definition at line 63 of file APT233.c.
#define kcldat ((integer *)&equiv_3)
Referenced by apt233_(), clput_(), and pocket_().
#define knumbr_1 knumbr_
Definition at line 71 of file APT233.c.
Referenced by apt233_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define symfil_1 symfil_
Definition at line 87 of file APT233.c.
Referenced by apt233_().
#define tlldat_1 tlldat_
Definition at line 37 of file APT233.c.
Function Documentation
int apt233_ (void)
Definition at line 98 of file APT233.c.
References atape_(), bcdf_(), c__10, c__18, charct_1, dcldat, dsname_1, e_1, e_2, ewrite_(), fermod, first, fxcor_1, iferm, ifxcor_1, ir, j, kcldat, knumbr_1, record_(), symfil_1, and vnorm_().
Referenced by cut_(), cuth_(), from_(), godlta_(), goto_(), and gotopn_().
 {
     /* Initialized data */
     static logical first = TRUE_;
     static char hgdlta[6] = "GODLTA";
     static doublereal zlit1 = .997;
     static struct {
     integer e_1[18];
     doublereal e_2;
     } equiv_3 = { 0, 0, 1308622848, 0, 1308622848, 2, 1308622848, 1, 0, 0,
          1308622848, 0, 0, 0, 1308622848, 0, 1308622848, 0, 0. };
     /* System generated locals */
     doublereal d__1;
     static doublereal equiv_2[1];
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer j, nr, ir;
     extern integer bcdf_(char *, ftnlen);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     extern /* Subroutine */ int atape_(void);
 #define iferm ((integer *)equiv_2)
     extern /* Subroutine */ int vnorm_(doublereal *, doublereal *);
 #define dcldat ((doublereal *)&equiv_3)
 #define kcldat ((integer *)&equiv_3)
 #define fermod (equiv_2)
     extern /* Subroutine */ int record_(integer *), ewrite_(integer *,
         integer *, integer *, integer *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*     *** 8.  HOLRTH BLOCK *** */
 /*     ALPHA-NUMERIC LITERAL CONSTANTS. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...            SYSTEM I/O FILE NAMES */
 /* ...                SYSTEM I/O FILES */
     if (first) {
     kcldat[0] = bcdf_("CLDA", (ftnlen)4);
     kcldat[1] = bcdf_("TA  ", (ftnlen)4);
     kcldat[8] = bcdf_("    ", (ftnlen)4);
     kcldat[9] = kcldat[8];
     kcldat[12] = kcldat[8];
     kcldat[13] = kcldat[8];
     first = FALSE_;
     }
 /* ...  STORES THE CUTTER POSITION (TE) IN TCDAT */
 /* ...  CALLED BY SUBROUTINES FROM,GODLTA,AND GOTO */
     record_(&ifxcor_1.iseqno);
     iferm[0] = bcdf_(charct_1.modfer, (ftnlen)4);
     iferm[1] = bcdf_(charct_1.modfer + 4, (ftnlen)2);
     if (s_cmp(charct_1.modfer, hgdlta, (ftnlen)6, (ftnlen)6) != 0) {
     goto L10;
     }
     nr = 0;
     kcldat[3] = ifxcor_1.iseqno;
     dcldat[4] = *fermod;
     ewrite_(&symfil_1.exfile, &nr, kcldat, &c__10, &ir);
     goto L70;
 /* ...  TI IS THE NORMALIZED CUT VECTOR */
 L10:
     for (j = 1; j <= 3; ++j) {
 /* L20: */
     fxcor_1.temp[j - 1] = fxcor_1.te[j - 1] - fxcor_1.tek[j - 1];
     }
     vnorm_(fxcor_1.temp, fxcor_1.ti);
     if (ifxcor_1.ier <= 0) {
     goto L25;
     } else {
     goto L50;
     }
 L25:
     if ((d__1 = fxcor_1.ti[0] * fxcor_1.ta[0] + fxcor_1.ti[1] * fxcor_1.ta[1]
         + fxcor_1.ti[2] * fxcor_1.ta[2], abs(d__1)) - zlit1 <= 0.) {
     goto L30;
     } else {
     goto L50;
     }
 /* ...  IF TI IS NOT IN LINE WITH TA,SAVE IN PMOVE */
 L30:
     for (j = 1; j <= 3; ++j) {
 /* L40: */
     fxcor_1.pmove[j - 1] = fxcor_1.ti[j - 1];
     }
 L50:
     nr = 0;
     kcldat[3] = ifxcor_1.iseqno;
     kcldat[5] = 6;
     dcldat[4] = *fermod;
     dcldat[6] = dsname_1.dsname;
     kcldat[15] = dsname_1.namsub;
     ewrite_(&symfil_1.exfile, &nr, kcldat, &c__18, &ir);
     kcldat[5] = 2;
 L70:
     ifxcor_1.icl = knumbr_1.k3;
     atape_();
     return 0;
 } /* apt233_ */
Variable Documentation
doublereal alp
Definition at line 18 of file APT233.c.
doublereal ax4[3]
Definition at line 18 of file APT233.c.
integer axfile
Definition at line 81 of file APT233.c.
integer c__10 = 10 static
Definition at line 91 of file APT233.c.
Referenced by apt233_().
integer c__18 = 18 static
Definition at line 92 of file APT233.c.
Referenced by apt233_().
doublereal cagl
Definition at line 18 of file APT233.c.
struct { ... } charct_
integer clfil3
Definition at line 81 of file APT233.c.
integer clfile
Definition at line 81 of file APT233.c.
integer clfilp
Definition at line 81 of file APT233.c.
doublereal corrad[8]
Definition at line 33 of file APT233.c.
integer cpfile
Definition at line 81 of file APT233.c.
doublereal cutdat[7]
Definition at line 18 of file APT233.c.
doublereal dpmax
Definition at line 18 of file APT233.c.
doublereal dsname
Definition at line 74 of file APT233.c.
struct { ... } dsname_
integer elfil1
Definition at line 81 of file APT233.c.
integer elfil2
Definition at line 81 of file APT233.c.
integer elfil3
Definition at line 81 of file APT233.c.
integer elfil4
Definition at line 81 of file APT233.c.
integer elfile
Definition at line 81 of file APT233.c.
integer exfile
Definition at line 81 of file APT233.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 18 of file APT233.c.
char haerr[8]
Definition at line 40 of file APT233.c.
char hback[8]
Definition at line 40 of file APT233.c.
struct { ... } hblock_
char hcldat[8]
Definition at line 40 of file APT233.c.
char hcs[8]
Definition at line 40 of file APT233.c.
char hdown[8]
Definition at line 40 of file APT233.c.
char hds[8]
Definition at line 40 of file APT233.c.
char hdynp[8]
Definition at line 40 of file APT233.c.
char hfwd[8]
Definition at line 40 of file APT233.c.
char hgerr[8]
Definition at line 40 of file APT233.c.
doublereal hi
Definition at line 18 of file APT233.c.
char hlft[8]
Definition at line 40 of file APT233.c.
char hon[8]
Definition at line 40 of file APT233.c.
char hpast[8]
Definition at line 40 of file APT233.c.
char hps[8]
Definition at line 40 of file APT233.c.
char hpstan[8]
Definition at line 40 of file APT233.c.
char hrgt[8]
Definition at line 40 of file APT233.c.
char htanto[8]
Definition at line 40 of file APT233.c.
char hto[8]
Definition at line 40 of file APT233.c.
char hup[8]
Definition at line 40 of file APT233.c.
integer i3dflg
Definition at line 48 of file APT233.c.
integer iaerr
Definition at line 48 of file APT233.c.
integer iamdct
Definition at line 58 of file APT233.c.
integer iautps
Definition at line 48 of file APT233.c.
integer ibegin
Definition at line 48 of file APT233.c.
integer ic
Definition at line 48 of file APT233.c.
integer icheck
Definition at line 48 of file APT233.c.
integer icl
Definition at line 48 of file APT233.c.
integer ics
Definition at line 48 of file APT233.c.
integer icscnt
Definition at line 48 of file APT233.c.
integer ictdef
Definition at line 48 of file APT233.c.
integer icut
Definition at line 48 of file APT233.c.
integer ids
Definition at line 48 of file APT233.c.
integer ier
Definition at line 48 of file APT233.c.
struct { ... } ifxcor_
integer igo
Definition at line 48 of file APT233.c.
integer igoto
Definition at line 48 of file APT233.c.
integer igoug
Definition at line 48 of file APT233.c.
integer igs
Definition at line 48 of file APT233.c.
integer infile__
Definition at line 81 of file APT233.c.
integer inops
Definition at line 48 of file APT233.c.
integer ipdpl
Definition at line 58 of file APT233.c.
integer ips
Definition at line 48 of file APT233.c.
integer ipsdef
Definition at line 48 of file APT233.c.
integer ipt
Definition at line 58 of file APT233.c.
integer ipt1
Definition at line 48 of file APT233.c.
integer is
Definition at line 48 of file APT233.c.
integer iseg
Definition at line 48 of file APT233.c.
integer iseqno
Definition at line 48 of file APT233.c.
struct { ... } ishr18_
integer ispare[26]
Definition at line 81 of file APT233.c.
integer isrch
Definition at line 48 of file APT233.c.
integer istrup
Definition at line 48 of file APT233.c.
integer it
Definition at line 48 of file APT233.c.
integer iws
Definition at line 58 of file APT233.c.
integer j10
Definition at line 58 of file APT233.c.
integer j12
Definition at line 58 of file APT233.c.
integer j13
Definition at line 58 of file APT233.c.
integer j54
Definition at line 58 of file APT233.c.
integer jbr
Definition at line 48 of file APT233.c.
integer jckr
Definition at line 58 of file APT233.c.
integer jcnt1
Definition at line 58 of file APT233.c.
integer jcnt2
Definition at line 58 of file APT233.c.
integer jcnt3
Definition at line 58 of file APT233.c.
integer jcpr
Definition at line 58 of file APT233.c.
integer jcr
Definition at line 58 of file APT233.c.
integer jdr
Definition at line 58 of file APT233.c.
integer jfind
Definition at line 58 of file APT233.c.
integer jgr
Definition at line 58 of file APT233.c.
integer jmin
Definition at line 58 of file APT233.c.
integer jminr
Definition at line 58 of file APT233.c.
integer jpr
Definition at line 58 of file APT233.c.
integer jpxr
Definition at line 58 of file APT233.c.
integer jsw
Definition at line 48 of file APT233.c.
integer jtkf
Definition at line 58 of file APT233.c.
integer jtr
Definition at line 58 of file APT233.c.
integer k0
Definition at line 66 of file APT233.c.
integer k1
Definition at line 66 of file APT233.c.
integer k10
Definition at line 66 of file APT233.c.
integer k1013
Definition at line 66 of file APT233.c.
integer k12
Definition at line 66 of file APT233.c.
integer k13
Definition at line 66 of file APT233.c.
integer k15
Definition at line 66 of file APT233.c.
integer k16
Definition at line 66 of file APT233.c.
integer k18
Definition at line 66 of file APT233.c.
integer k19
Definition at line 66 of file APT233.c.
integer k1e4
Definition at line 66 of file APT233.c.
integer k1e6
Definition at line 66 of file APT233.c.
integer k2
Definition at line 66 of file APT233.c.
integer k23
Definition at line 66 of file APT233.c.
integer k24
Definition at line 66 of file APT233.c.
integer k25
Definition at line 66 of file APT233.c.
integer k26
Definition at line 66 of file APT233.c.
integer k27
Definition at line 66 of file APT233.c.
integer k29
Definition at line 66 of file APT233.c.
integer k3
Definition at line 66 of file APT233.c.
integer k30
Definition at line 66 of file APT233.c.
integer k31
Definition at line 66 of file APT233.c.
integer k32
Definition at line 66 of file APT233.c.
integer k33
Definition at line 66 of file APT233.c.
integer k34
Definition at line 66 of file APT233.c.
integer k4
Definition at line 66 of file APT233.c.
integer k44
Definition at line 66 of file APT233.c.
integer k45
Definition at line 66 of file APT233.c.
integer k46
Definition at line 66 of file APT233.c.
integer k47
Definition at line 66 of file APT233.c.
integer k48
Definition at line 66 of file APT233.c.
integer k5
Definition at line 66 of file APT233.c.
integer k50
Definition at line 66 of file APT233.c.
integer k51
Definition at line 66 of file APT233.c.
integer k52
Definition at line 66 of file APT233.c.
integer k6
Definition at line 66 of file APT233.c.
integer k7
Definition at line 66 of file APT233.c.
integer k8
Definition at line 66 of file APT233.c.
integer k9
Definition at line 66 of file APT233.c.
integer km1
Definition at line 66 of file APT233.c.
struct { ... } knumbr_
integer ldafil
Definition at line 81 of file APT233.c.
integer libfil
Definition at line 81 of file APT233.c.
integer lsv
Definition at line 48 of file APT233.c.
integer lsv1
Definition at line 48 of file APT233.c.
integer mactxt
Definition at line 81 of file APT233.c.
integer mantax
Definition at line 48 of file APT233.c.
integer mdic
Definition at line 58 of file APT233.c.
char modfer[6]
Definition at line 27 of file APT233.c.
integer motmod
Definition at line 48 of file APT233.c.
integer msav
Definition at line 48 of file APT233.c.
integer mulout
Definition at line 48 of file APT233.c.
integer namsub
Definition at line 75 of file APT233.c.
integer nfil12
Definition at line 81 of file APT233.c.
integer nfil13
Definition at line 81 of file APT233.c.
integer nmbseg
Definition at line 48 of file APT233.c.
integer nmpnts
Definition at line 48 of file APT233.c.
integer nrec
Definition at line 48 of file APT233.c.
integer numax
Definition at line 48 of file APT233.c.
integer numcnt
Definition at line 48 of file APT233.c.
integer nump
Definition at line 48 of file APT233.c.
integer numpt1
Definition at line 48 of file APT233.c.
integer numsfs
Definition at line 48 of file APT233.c.
integer numsur
Definition at line 48 of file APT233.c.
integer nw
Definition at line 48 of file APT233.c.
integer nwds
Definition at line 48 of file APT233.c.
doublereal pmove[3]
Definition at line 18 of file APT233.c.
integer pnchfl
Definition at line 81 of file APT233.c.
integer pofile
Definition at line 81 of file APT233.c.
integer pxfile
Definition at line 81 of file APT233.c.
doublereal ra
Definition at line 18 of file APT233.c.
doublereal rc1
Definition at line 18 of file APT233.c.
doublereal ri[8]
Definition at line 33 of file APT233.c.
doublereal sagl
Definition at line 18 of file APT233.c.
doublereal strtno
Definition at line 18 of file APT233.c.
doublereal surd
Definition at line 18 of file APT233.c.
struct { ... } symfil_
doublereal ta[3]
Definition at line 18 of file APT233.c.
doublereal tak[3]
Definition at line 18 of file APT233.c.
doublereal tal[3]
Definition at line 18 of file APT233.c.
doublereal tanhi[8]
Definition at line 33 of file APT233.c.
doublereal tanlo[8]
Definition at line 33 of file APT233.c.
doublereal tcont[9]
Definition at line 33 of file APT233.c.
doublereal te[3]
Definition at line 18 of file APT233.c.
doublereal tek[3]
Definition at line 18 of file APT233.c.
doublereal tel[3]
Definition at line 18 of file APT233.c.
doublereal tem[10]
Definition at line 18 of file APT233.c.
doublereal temp[24]
Definition at line 18 of file APT233.c.
doublereal ti[3]
Definition at line 18 of file APT233.c.
integer tifile
Definition at line 81 of file APT233.c.
doublereal tik[3]
Definition at line 18 of file APT233.c.
doublereal til[3]
Definition at line 18 of file APT233.c.
doublereal tlhit
Definition at line 18 of file APT233.c.
doublereal tlhite[8]
Definition at line 33 of file APT233.c.
doublereal tlinc[9]
Definition at line 33 of file APT233.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 18 of file APT233.c.
doublereal umax[8]
Definition at line 33 of file APT233.c.
integer vlfile
Definition at line 81 of file APT233.c.
doublereal vtem
Definition at line 18 of file APT233.c.
integer xcan
Definition at line 81 of file APT233.c.
integer xnum
Definition at line 81 of file APT233.c.