My Project: APT241.c File Reference
APT241.c File Reference
#include "f2c.h"
Functions
int apt241_ (void)
int apt242_ (void)
integer handl_ (integer *s, integer *m)
Function Documentation
int apt241_ (void)
Definition at line 17 of file APT241.c.
References handl_(), and libsestablish_().
Referenced by apt201_(), cutter_(), and go_().
 {
     extern integer handl_();
     extern /* Subroutine */ int libsestablish_(I_fp);
 /*      CALL LIB$ESTABLISH(HANDL) */
     libsestablish_((I_fp)handl_);
     return 0;
 } /* apt241_ */
int apt242_ (void)
Definition at line 29 of file APT241.c.
Referenced by aerr2_().
 {
 /*      CALL LIB$SIGNAL(%VAL(SS$_ACCVIO)) */
     return 0;
 } /* apt242_ */
integer handl_ (integer * s, integer * m)
Definition at line 37 of file APT241.c.
References m, and s.
Referenced by apt241_().
 {
     /* System generated locals */
     integer ret_val;
     /* Local variables */
     extern /* Subroutine */ int abort_(void);
 /*      INCLUDE 'SYS$LIBRARY:SIGDEF' */
 /*      HANDL=SS$_RESIGNAL */
 /*      IF (S(2).EQ.SS$_UNWIND) THEN */
 /*      RETURN */
 /*      END IF */
 /*      CALL SYS$UNWIND(,) */
 /*   i don't know what to replace this with right now, so.. */
     /* Parameter adjustments */
     --m;
     --s;
     /* Function Body */
     abort_();
     return ret_val;
 } /* handl_ */