My Project: APT201.c File Reference
APT201.c File Reference
#include "f2c.h"
Functions
integer apt201_ (doublereal *adress, doublereal *hdrect)
Function Documentation
integer apt201_ (doublereal * adress, doublereal * hdrect)
Definition at line 393 of file APT201.c.
References apt211_(), apt241_(), and libsrevert_().
Referenced by autops_(), godlta_(), goto_(), and xcall_().
 {
     /* System generated locals */
     integer ret_val;
     /* Local variables */
     extern /* Subroutine */ int libsrevert_(void);
     extern integer apt211_(doublereal *, doublereal *, integer *);
     extern /* Subroutine */ int apt241_(void);
     static integer iaeee;
     /* Parameter adjustments */
     --adress;
     /* Function Body */
     iaeee = 0;
 /* ...ESTABLISH CONDITION HANDLER FOR AERR ERROR */
 L1:
     apt241_();
     ret_val = apt211_(&adress[1], hdrect, &iaeee);
     if (iaeee == 1) {
     goto L1;
     }
 /* ...REVERT TO DEFAULT CONDITION HANDLER */
 /*      CALL LIB$REVERT */
     libsrevert_();
     return ret_val;
 } /* apt201_ */