My Project: APT236.c File Reference
APT236.c File Reference
#include "f2c.h"
Macros
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define addcom_1 addcom_
#define jlin ((integer *)&addcom_1 + 46)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define elmax ((doublereal *)&addcom_1)
#define ibtflg ((integer *)&addcom_1 + 44)
#define clngth ((doublereal *)&addcom_1 + 1)
Functions
int apt236_ (void)
Variables
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
doublereal addcom [25]
} addcom_
Macro Definition Documentation
#define addcom_1 addcom_
Definition at line 111 of file APT236.c.
#define charct_1 charct_
Definition at line 30 of file APT236.c.
#define clngth ((doublereal *)&addcom_1 + 1)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define elmax ((doublereal *)&addcom_1)
#define fxcor_1 fxcor_
Definition at line 24 of file APT236.c.
Referenced by apt236_().
#define ibtflg ((integer *)&addcom_1 + 44)
#define ifxcor_1 ifxcor_
Definition at line 89 of file APT236.c.
Referenced by apt236_().
#define ishr18_1 ishr18_
Definition at line 97 of file APT236.c.
#define isv1_1 isv1_
Definition at line 79 of file APT236.c.
#define isv_1 isv_
Definition at line 72 of file APT236.c.
Referenced by apt236_().
#define jlin ((integer *)&addcom_1 + 46)
#define knumbr_1 knumbr_
Definition at line 105 of file APT236.c.
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sv1_1 sv1_
Definition at line 63 of file APT236.c.
#define sv_1 sv_
Definition at line 54 of file APT236.c.
Referenced by apt236_().
#define tlldat_1 tlldat_
Definition at line 37 of file APT236.c.
Function Documentation
int apt236_ (void)
Definition at line 116 of file APT236.c.
References fxcor_1, i__, ifxcor_1, isv_1, j, k, sv_1, and vnorm_().
Referenced by aerr2_(), apt211_(), and go2_().
 {
     /* Initialized data */
     static doublereal zlit1 = .997;
     /* System generated locals */
     integer i__1;
     doublereal d__1;
     /* Local variables */
     static integer i__, j, k;
 #define jlin ((integer *)&addcom_1 + 46)
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
 #define elmax ((doublereal *)&addcom_1)
     extern /* Subroutine */ int vnorm_(doublereal *, doublereal *);
 #define ibtflg ((integer *)&addcom_1 + 44)
 #define clngth ((doublereal *)&addcom_1 + 1)
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /* ...  21. ADDCOM BLOCK */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     for (k = 1; k <= 3; ++k) {
     ifxcor_1.inops = 0;
     ifxcor_1.icscnt = 0;
     fxcor_1.temp[k - 1] = fxcor_1.te[k - 1] - fxcor_1.tek[k - 1];
     sv_1.tpk[k + ifxcor_1.ips * 3 - 4] = sv_1.tp[k + ifxcor_1.ips * 3 - 4]
         ;
     sv_1.spk[k + ifxcor_1.ips * 3 - 4] = sv_1.sp[k + ifxcor_1.ips * 3 - 4]
         ;
     sv_1.u1k[k + ifxcor_1.ips * 3 - 4] = sv_1.u1[k + ifxcor_1.ips * 3 - 4]
         ;
     sv_1.snk[k + ifxcor_1.ips * 3 - 4] = sv_1.sn[k + ifxcor_1.ips * 3 - 4]
         ;
 /* L1: */
     }
     isv_1.itsegk[ifxcor_1.ips - 1] = isv_1.itseg[ifxcor_1.ips - 1];
     vnorm_(fxcor_1.temp, fxcor_1.temp);
     if (ifxcor_1.ier <= 0) {
     goto L2;
     } else {
     goto L4;
     }
 L2:
     if ((d__1 = fxcor_1.temp[0] * fxcor_1.ta[0] + fxcor_1.temp[1] *
         fxcor_1.ta[1] + fxcor_1.temp[2] * fxcor_1.ta[2], abs(d__1)) -
         zlit1 <= 0.) {
     goto L3;
     } else {
     goto L4;
     }
 L3:
     fxcor_1.pmove[0] = fxcor_1.temp[0];
     fxcor_1.pmove[1] = fxcor_1.temp[1];
     fxcor_1.pmove[2] = fxcor_1.temp[2];
 L4:
     i__ = ifxcor_1.ips;
     i__1 = ifxcor_1.numsur;
     for (j = 1; j <= i__1; ++j) {
     isv_1.indir__[i__ - 1] = 0;
     isv_1.isvfl[i__ - 1] = 0;
     if (i__ >= ifxcor_1.ics) {
         goto L7;
     }
 /* L6: */
     i__ += ifxcor_1.lsv;
     goto L5;
 L7:
     i__ += ifxcor_1.lsv1;
 L5:
     ;
     }
     return 0;
 } /* apt236_ */
Variable Documentation
doublereal addcom[25]
Definition at line 108 of file APT236.c.
struct { ... } addcom_
doublereal alp
Definition at line 18 of file APT236.c.
doublereal ax4[3]
Definition at line 18 of file APT236.c.
doublereal cagl
Definition at line 18 of file APT236.c.
doublereal cc[15]
Definition at line 40 of file APT236.c.
struct { ... } charct_
doublereal corrad[8]
Definition at line 33 of file APT236.c.
doublereal cos1[5]
Definition at line 57 of file APT236.c.
doublereal cplfl[5]
Definition at line 57 of file APT236.c.
doublereal cptst[5]
Definition at line 57 of file APT236.c.
doublereal csd[5]
Definition at line 57 of file APT236.c.
doublereal cutdat[7]
Definition at line 18 of file APT236.c.
doublereal dplan[15]
Definition at line 57 of file APT236.c.
doublereal dpmax
Definition at line 18 of file APT236.c.
doublereal dpmx1[5]
Definition at line 57 of file APT236.c.
doublereal eps1[5]
Definition at line 40 of file APT236.c.
doublereal eps2[5]
Definition at line 40 of file APT236.c.
doublereal eps3[5]
Definition at line 40 of file APT236.c.
doublereal eps4[5]
Definition at line 40 of file APT236.c.
doublereal eps6[5]
Definition at line 40 of file APT236.c.
doublereal eps8[5]
Definition at line 40 of file APT236.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 18 of file APT236.c.
doublereal hi
Definition at line 18 of file APT236.c.
integer i3dflg
Definition at line 82 of file APT236.c.
integer iaerr
Definition at line 82 of file APT236.c.
integer iafl[5]
Definition at line 66 of file APT236.c.
integer iamdct
Definition at line 92 of file APT236.c.
integer iautps
Definition at line 82 of file APT236.c.
integer ibegin
Definition at line 82 of file APT236.c.
integer ic
Definition at line 82 of file APT236.c.
integer icanon[5]
Definition at line 66 of file APT236.c.
integer icheck
Definition at line 82 of file APT236.c.
integer icl
Definition at line 82 of file APT236.c.
integer ics
Definition at line 82 of file APT236.c.
integer icscnt
Definition at line 82 of file APT236.c.
integer ictdef
Definition at line 82 of file APT236.c.
integer icut
Definition at line 82 of file APT236.c.
integer ids
Definition at line 82 of file APT236.c.
integer ier
Definition at line 82 of file APT236.c.
integer ifar[5]
Definition at line 75 of file APT236.c.
integer ifl4[5]
Definition at line 75 of file APT236.c.
struct { ... } ifxcor_
integer igo
Definition at line 82 of file APT236.c.
integer igoto
Definition at line 82 of file APT236.c.
integer igoug
Definition at line 82 of file APT236.c.
integer igs
Definition at line 82 of file APT236.c.
integer index[5]
Definition at line 66 of file APT236.c.
integer indir__[5]
Definition at line 66 of file APT236.c.
integer inops
Definition at line 82 of file APT236.c.
integer iop[5]
Definition at line 66 of file APT236.c.
integer iopset[5]
Definition at line 66 of file APT236.c.
integer ipdpl
Definition at line 92 of file APT236.c.
integer ipl[5]
Definition at line 66 of file APT236.c.
integer ips
Definition at line 82 of file APT236.c.
integer ipsdef
Definition at line 82 of file APT236.c.
integer ipt
Definition at line 92 of file APT236.c.
integer ipt1
Definition at line 82 of file APT236.c.
integer is
Definition at line 82 of file APT236.c.
integer iseg
Definition at line 82 of file APT236.c.
integer iseqno
Definition at line 82 of file APT236.c.
integer isfidn[5]
Definition at line 66 of file APT236.c.
integer isftyp[5]
Definition at line 66 of file APT236.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 66 of file APT236.c.
integer isrch
Definition at line 82 of file APT236.c.
integer istrup
Definition at line 82 of file APT236.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 66 of file APT236.c.
integer it
Definition at line 82 of file APT236.c.
integer itlon[5]
Definition at line 66 of file APT236.c.
integer itseg[5]
Definition at line 66 of file APT236.c.
integer itsegk[5]
Definition at line 66 of file APT236.c.
integer iunfl[5]
Definition at line 66 of file APT236.c.
integer iws
Definition at line 92 of file APT236.c.
integer j10
Definition at line 92 of file APT236.c.
integer j12
Definition at line 92 of file APT236.c.
integer j13
Definition at line 92 of file APT236.c.
integer j20[5]
Definition at line 75 of file APT236.c.
integer j21[5]
Definition at line 75 of file APT236.c.
integer j22[5]
Definition at line 75 of file APT236.c.
integer j23[5]
Definition at line 75 of file APT236.c.
integer j50[5]
Definition at line 75 of file APT236.c.
integer j51[5]
Definition at line 75 of file APT236.c.
integer j54
Definition at line 92 of file APT236.c.
integer jbr
Definition at line 82 of file APT236.c.
integer jckr
Definition at line 92 of file APT236.c.
integer jcnt1
Definition at line 92 of file APT236.c.
integer jcnt2
Definition at line 92 of file APT236.c.
integer jcnt3
Definition at line 92 of file APT236.c.
integer jcpr
Definition at line 92 of file APT236.c.
integer jcr
Definition at line 92 of file APT236.c.
integer jdr
Definition at line 92 of file APT236.c.
integer jent[5]
Definition at line 66 of file APT236.c.
integer jfind
Definition at line 92 of file APT236.c.
integer jgr
Definition at line 92 of file APT236.c.
integer jiops[5]
Definition at line 66 of file APT236.c.
integer jmin
Definition at line 92 of file APT236.c.
integer jminr
Definition at line 92 of file APT236.c.
integer jph[5]
Definition at line 75 of file APT236.c.
integer jpr
Definition at line 92 of file APT236.c.
integer jpxr
Definition at line 92 of file APT236.c.
integer jsw
Definition at line 82 of file APT236.c.
integer jtkf
Definition at line 92 of file APT236.c.
integer jtlflg[5]
Definition at line 66 of file APT236.c.
integer jtn[5]
Definition at line 66 of file APT236.c.
integer jtr
Definition at line 92 of file APT236.c.
integer ju1[5]
Definition at line 66 of file APT236.c.
integer k0
Definition at line 100 of file APT236.c.
integer k1
Definition at line 100 of file APT236.c.
integer k10
Definition at line 100 of file APT236.c.
integer k1013
Definition at line 100 of file APT236.c.
integer k12
Definition at line 100 of file APT236.c.
integer k13
Definition at line 100 of file APT236.c.
integer k15
Definition at line 100 of file APT236.c.
integer k16
Definition at line 100 of file APT236.c.
integer k18
Definition at line 100 of file APT236.c.
integer k19
Definition at line 100 of file APT236.c.
integer k1e4
Definition at line 100 of file APT236.c.
integer k1e6
Definition at line 100 of file APT236.c.
integer k2
Definition at line 100 of file APT236.c.
integer k23
Definition at line 100 of file APT236.c.
integer k24
Definition at line 100 of file APT236.c.
integer k25
Definition at line 100 of file APT236.c.
integer k26
Definition at line 100 of file APT236.c.
integer k27
Definition at line 100 of file APT236.c.
integer k29
Definition at line 100 of file APT236.c.
integer k3
Definition at line 100 of file APT236.c.
integer k30
Definition at line 100 of file APT236.c.
integer k31
Definition at line 100 of file APT236.c.
integer k32
Definition at line 100 of file APT236.c.
integer k33
Definition at line 100 of file APT236.c.
integer k34
Definition at line 100 of file APT236.c.
integer k4
Definition at line 100 of file APT236.c.
integer k44
Definition at line 100 of file APT236.c.
integer k45
Definition at line 100 of file APT236.c.
integer k46
Definition at line 100 of file APT236.c.
integer k47
Definition at line 100 of file APT236.c.
integer k48
Definition at line 100 of file APT236.c.
integer k5
Definition at line 100 of file APT236.c.
integer k50
Definition at line 100 of file APT236.c.
integer k51
Definition at line 100 of file APT236.c.
integer k52
Definition at line 100 of file APT236.c.
integer k6
Definition at line 100 of file APT236.c.
integer k7
Definition at line 100 of file APT236.c.
integer k8
Definition at line 100 of file APT236.c.
integer k9
Definition at line 100 of file APT236.c.
integer km1
Definition at line 100 of file APT236.c.
struct { ... } knumbr_
integer limfl[5]
Definition at line 66 of file APT236.c.
integer lsv
Definition at line 82 of file APT236.c.
integer lsv1
Definition at line 82 of file APT236.c.
integer mantax
Definition at line 82 of file APT236.c.
integer mdic
Definition at line 92 of file APT236.c.
char modfer[6]
Definition at line 27 of file APT236.c.
integer motmod
Definition at line 82 of file APT236.c.
integer msav
Definition at line 82 of file APT236.c.
integer mulout
Definition at line 82 of file APT236.c.
integer nmbseg
Definition at line 82 of file APT236.c.
integer nmpnts
Definition at line 82 of file APT236.c.
integer notan[5]
Definition at line 75 of file APT236.c.
integer nrec
Definition at line 82 of file APT236.c.
integer numax
Definition at line 82 of file APT236.c.
integer numcnt
Definition at line 82 of file APT236.c.
integer nump
Definition at line 82 of file APT236.c.
integer numpt1
Definition at line 82 of file APT236.c.
integer numsfs
Definition at line 82 of file APT236.c.
integer numsur
Definition at line 82 of file APT236.c.
integer nw
Definition at line 82 of file APT236.c.
integer nwds
Definition at line 82 of file APT236.c.
doublereal past[5]
Definition at line 40 of file APT236.c.
doublereal plncs[5]
Definition at line 57 of file APT236.c.
doublereal plnd[5]
Definition at line 40 of file APT236.c.
doublereal plnd1[5]
Definition at line 57 of file APT236.c.
doublereal plnv[15]
Definition at line 40 of file APT236.c.
doublereal pltst[5]
Definition at line 57 of file APT236.c.
doublereal pmove[3]
Definition at line 18 of file APT236.c.
doublereal ra
Definition at line 18 of file APT236.c.
doublereal rc[5]
Definition at line 40 of file APT236.c.
doublereal rc1
Definition at line 18 of file APT236.c.
doublereal ri[8]
Definition at line 33 of file APT236.c.
doublereal s[5]
Definition at line 40 of file APT236.c.
doublereal sagl
Definition at line 18 of file APT236.c.
doublereal save[5]
Definition at line 40 of file APT236.c.
doublereal sfvct[15]
Definition at line 40 of file APT236.c.
doublereal sk[15]
Definition at line 40 of file APT236.c.
doublereal slx[15]
Definition at line 40 of file APT236.c.
doublereal sn[15]
Definition at line 40 of file APT236.c.
doublereal snk[15]
Definition at line 40 of file APT236.c.
doublereal snl[15]
Definition at line 40 of file APT236.c.
doublereal sp[15]
Definition at line 40 of file APT236.c.
doublereal spk[15]
Definition at line 40 of file APT236.c.
doublereal spl[15]
Definition at line 40 of file APT236.c.
doublereal stck[5]
Definition at line 57 of file APT236.c.
doublereal stck1[5]
Definition at line 57 of file APT236.c.
doublereal stck2[5]
Definition at line 57 of file APT236.c.
doublereal stckn[5]
Definition at line 57 of file APT236.c.
doublereal strtno
Definition at line 18 of file APT236.c.
doublereal surd
Definition at line 18 of file APT236.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 18 of file APT236.c.
doublereal tak[3]
Definition at line 18 of file APT236.c.
doublereal tal[3]
Definition at line 18 of file APT236.c.
doublereal tanhi[8]
Definition at line 33 of file APT236.c.
doublereal tanlo[8]
Definition at line 33 of file APT236.c.
doublereal tau[5]
Definition at line 40 of file APT236.c.
doublereal tau1[5]
Definition at line 40 of file APT236.c.
doublereal tau2[5]
Definition at line 40 of file APT236.c.
doublereal tcont[9]
Definition at line 33 of file APT236.c.
doublereal te[3]
Definition at line 18 of file APT236.c.
doublereal tee[15]
Definition at line 57 of file APT236.c.
doublereal tek[3]
Definition at line 18 of file APT236.c.
doublereal tel[3]
Definition at line 18 of file APT236.c.
doublereal tem[10]
Definition at line 18 of file APT236.c.
doublereal temp[24]
Definition at line 18 of file APT236.c.
doublereal th[5]
Definition at line 40 of file APT236.c.
doublereal ti[3]
Definition at line 18 of file APT236.c.
doublereal tik[3]
Definition at line 18 of file APT236.c.
doublereal til[3]
Definition at line 18 of file APT236.c.
doublereal tlhit
Definition at line 18 of file APT236.c.
doublereal tlhite[8]
Definition at line 33 of file APT236.c.
doublereal tlinc[9]
Definition at line 33 of file APT236.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 18 of file APT236.c.
doublereal tn[15]
Definition at line 40 of file APT236.c.
doublereal tnl[15]
Definition at line 57 of file APT236.c.
doublereal toolht[15]
Definition at line 40 of file APT236.c.
doublereal toolwd[5]
Definition at line 40 of file APT236.c.
doublereal tp[15]
Definition at line 40 of file APT236.c.
doublereal tpk[15]
Definition at line 40 of file APT236.c.
doublereal u1[15]
Definition at line 40 of file APT236.c.
doublereal u1k[15]
Definition at line 40 of file APT236.c.
doublereal umax[8]
Definition at line 33 of file APT236.c.
doublereal varble[5]
Definition at line 40 of file APT236.c.
doublereal vndir[15]
Definition at line 40 of file APT236.c.
doublereal vt[15]
Definition at line 40 of file APT236.c.
doublereal vtem
Definition at line 18 of file APT236.c.
doublereal z__[5]
Definition at line 40 of file APT236.c.