My Project: APT200.c File Reference
APT200.c File Reference
#include "f2c.h"
Macros
#define ldef_1 ldef_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define knumbr_1 knumbr_
#define aercom_1 aercom_
Functions
int apt200_ (doublereal *hmod, doublereal *adress, doublereal *xntsct)
Variables
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
integer iaerfg
integer npctpt
doublereal pctpts [60]
doublereal pctpln [4]
doublereal errpts [9]
} aercom_
static integer c__20001 = 20001
Macro Definition Documentation
#define aercom_1 aercom_
Definition at line 64 of file APT200.c.
Referenced by apt200_().
#define ifxcor_1 ifxcor_
Definition at line 48 of file APT200.c.
Referenced by apt200_().
#define isv1_1 isv1_
Definition at line 38 of file APT200.c.
Referenced by apt200_().
#define isv_1 isv_
Definition at line 31 of file APT200.c.
Referenced by apt200_().
#define knumbr_1 knumbr_
Definition at line 56 of file APT200.c.
Referenced by apt200_().
#define ldef_1 ldef_
Definition at line 22 of file APT200.c.
Referenced by apt200_().
Function Documentation
int apt200_ (doublereal * hmod, doublereal * adress, doublereal * xntsct)
Definition at line 74 of file APT200.c.
References aercom_1, aerr_(), apt234_(), c__20001, ifxcor_1, isv1_1, isv_1, knumbr_1, and ldef_1.
Referenced by apt211_(), and xcall_().
 {
     /* System generated locals */
     integer i__1;
     /* Local variables */
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen), apt234_(
         doublereal *, doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*     25. COMMON FOR AERR INFORMATION */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...  ESTABLISHES CHECK SURFACE PARAMETERS FOR EACH CHECK SURFACE */
 /* ...  ADVANCE THE CHECK SURFACE COUNTER */
     /* Parameter adjustments */
     --adress;
     /* Function Body */
     if (ifxcor_1.iaerr == 1) {
     goto L1000;
     }
     ifxcor_1.icscnt += knumbr_1.k1;
     if (ifxcor_1.numsfs >= ifxcor_1.icscnt + knumbr_1.k2) {
     goto L1;
     }
     aercom_1.iaerfg = 1;
     aerr_(&c__20001, "APT200  ", (ftnlen)8);
     goto L1000;
 L1:
     ifxcor_1.is = ifxcor_1.ics + (ifxcor_1.icscnt - knumbr_1.k1) *
         ifxcor_1.lsv1;
     apt234_(hmod, &adress[1]);
     if (ifxcor_1.iaerr <= 0) {
     goto L5;
     } else {
     goto L1000;
     }
 /* ...  SET IFL4=1 IF PSTAN,0 IF TANTO */
 L5:
     if ((i__1 = isv_1.isftyp[ifxcor_1.is - 1] - knumbr_1.k4) < 0) {
     goto L30;
     } else if (i__1 == 0) {
     goto L10;
     } else {
     goto L20;
     }
 L10:
     isv1_1.ifl4[ifxcor_1.is - 1] = 0;
     goto L30;
 L20:
     isv1_1.ifl4[ifxcor_1.is - 1] = knumbr_1.k1;
 /* ...  SET CS INTERSECTION COUNTER */
 L30:
     isv1_1.ifar[ifxcor_1.is - 1] = (integer) (*xntsct);
     ldef_1.jcs = TRUE_;
 L1000:
     return 0;
 } /* apt200_ */
Variable Documentation
struct { ... } aercom_
logical altmlt
Definition at line 18 of file APT200.c.
logical bnderr
Definition at line 18 of file APT200.c.
logical boundf
Definition at line 18 of file APT200.c.
integer c__20001 = 20001 static
Definition at line 68 of file APT200.c.
Referenced by apt200_().
logical canflg
Definition at line 18 of file APT200.c.
doublereal errpts[9]
Definition at line 60 of file APT200.c.
integer i3dflg
Definition at line 41 of file APT200.c.
integer iaerfg
Definition at line 59 of file APT200.c.
integer iaerr
Definition at line 41 of file APT200.c.
integer iafl[5]
Definition at line 25 of file APT200.c.
integer iautps
Definition at line 41 of file APT200.c.
integer ibegin
Definition at line 41 of file APT200.c.
integer ic
Definition at line 41 of file APT200.c.
integer icanon[5]
Definition at line 25 of file APT200.c.
integer icheck
Definition at line 41 of file APT200.c.
integer icl
Definition at line 41 of file APT200.c.
integer ics
Definition at line 41 of file APT200.c.
integer icscnt
Definition at line 41 of file APT200.c.
integer ictdef
Definition at line 41 of file APT200.c.
integer icut
Definition at line 41 of file APT200.c.
integer ids
Definition at line 41 of file APT200.c.
integer ier
Definition at line 41 of file APT200.c.
integer ifar[5]
Definition at line 34 of file APT200.c.
integer ifl4[5]
Definition at line 34 of file APT200.c.
struct { ... } ifxcor_
integer igo
Definition at line 41 of file APT200.c.
integer igoto
Definition at line 41 of file APT200.c.
integer igoug
Definition at line 41 of file APT200.c.
integer igs
Definition at line 41 of file APT200.c.
integer index[5]
Definition at line 25 of file APT200.c.
integer indir__[5]
Definition at line 25 of file APT200.c.
integer inops
Definition at line 41 of file APT200.c.
integer iop[5]
Definition at line 25 of file APT200.c.
integer iopset[5]
Definition at line 25 of file APT200.c.
integer ipl[5]
Definition at line 25 of file APT200.c.
integer ips
Definition at line 41 of file APT200.c.
integer ipsdef
Definition at line 41 of file APT200.c.
integer ipt1
Definition at line 41 of file APT200.c.
integer is
Definition at line 41 of file APT200.c.
integer iseg
Definition at line 41 of file APT200.c.
integer iseqno
Definition at line 41 of file APT200.c.
integer isfidn[5]
Definition at line 25 of file APT200.c.
integer isftyp[5]
Definition at line 25 of file APT200.c.
integer isigcr[5]
Definition at line 25 of file APT200.c.
integer isrch
Definition at line 41 of file APT200.c.
integer istrup
Definition at line 41 of file APT200.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 25 of file APT200.c.
integer it
Definition at line 41 of file APT200.c.
integer itlon[5]
Definition at line 25 of file APT200.c.
integer itseg[5]
Definition at line 25 of file APT200.c.
integer itsegk[5]
Definition at line 25 of file APT200.c.
integer iunfl[5]
Definition at line 25 of file APT200.c.
integer j20[5]
Definition at line 34 of file APT200.c.
integer j21[5]
Definition at line 34 of file APT200.c.
integer j22[5]
Definition at line 34 of file APT200.c.
integer j23[5]
Definition at line 34 of file APT200.c.
integer j50[5]
Definition at line 34 of file APT200.c.
integer j51[5]
Definition at line 34 of file APT200.c.
integer jbr
Definition at line 41 of file APT200.c.
logical jcs
Definition at line 18 of file APT200.c.
logical jds
Definition at line 18 of file APT200.c.
integer jent[5]
Definition at line 25 of file APT200.c.
integer jiops[5]
Definition at line 25 of file APT200.c.
integer jph[5]
Definition at line 34 of file APT200.c.
integer jsw
Definition at line 41 of file APT200.c.
integer jtlflg[5]
Definition at line 25 of file APT200.c.
integer jtn[5]
Definition at line 25 of file APT200.c.
integer ju1[5]
Definition at line 25 of file APT200.c.
integer k0
Definition at line 51 of file APT200.c.
integer k1
Definition at line 51 of file APT200.c.
integer k10
Definition at line 51 of file APT200.c.
integer k1013
Definition at line 51 of file APT200.c.
integer k12
Definition at line 51 of file APT200.c.
integer k13
Definition at line 51 of file APT200.c.
integer k15
Definition at line 51 of file APT200.c.
integer k16
Definition at line 51 of file APT200.c.
integer k18
Definition at line 51 of file APT200.c.
integer k19
Definition at line 51 of file APT200.c.
integer k1e4
Definition at line 51 of file APT200.c.
integer k1e6
Definition at line 51 of file APT200.c.
integer k2
Definition at line 51 of file APT200.c.
integer k23
Definition at line 51 of file APT200.c.
integer k24
Definition at line 51 of file APT200.c.
integer k25
Definition at line 51 of file APT200.c.
integer k26
Definition at line 51 of file APT200.c.
integer k27
Definition at line 51 of file APT200.c.
integer k29
Definition at line 51 of file APT200.c.
integer k3
Definition at line 51 of file APT200.c.
integer k30
Definition at line 51 of file APT200.c.
integer k31
Definition at line 51 of file APT200.c.
integer k32
Definition at line 51 of file APT200.c.
integer k33
Definition at line 51 of file APT200.c.
integer k34
Definition at line 51 of file APT200.c.
integer k4
Definition at line 51 of file APT200.c.
integer k44
Definition at line 51 of file APT200.c.
integer k45
Definition at line 51 of file APT200.c.
integer k46
Definition at line 51 of file APT200.c.
integer k47
Definition at line 51 of file APT200.c.
integer k48
Definition at line 51 of file APT200.c.
integer k5
Definition at line 51 of file APT200.c.
integer k50
Definition at line 51 of file APT200.c.
integer k51
Definition at line 51 of file APT200.c.
integer k52
Definition at line 51 of file APT200.c.
integer k6
Definition at line 51 of file APT200.c.
integer k7
Definition at line 51 of file APT200.c.
integer k8
Definition at line 51 of file APT200.c.
integer k9
Definition at line 51 of file APT200.c.
integer km1
Definition at line 51 of file APT200.c.
struct { ... } knumbr_
struct { ... } ldef_
integer limfl[5]
Definition at line 25 of file APT200.c.
integer lsv
Definition at line 41 of file APT200.c.
integer lsv1
Definition at line 41 of file APT200.c.
integer mantax
Definition at line 41 of file APT200.c.
integer motmod
Definition at line 41 of file APT200.c.
integer msav
Definition at line 41 of file APT200.c.
integer mulout
Definition at line 41 of file APT200.c.
integer nmbseg
Definition at line 41 of file APT200.c.
integer nmpnts
Definition at line 41 of file APT200.c.
integer notan[5]
Definition at line 34 of file APT200.c.
integer npctpt
Definition at line 59 of file APT200.c.
integer nrec
Definition at line 41 of file APT200.c.
integer numax
Definition at line 41 of file APT200.c.
integer numcnt
Definition at line 41 of file APT200.c.
integer nump
Definition at line 41 of file APT200.c.
integer numpt1
Definition at line 41 of file APT200.c.
integer numsfs
Definition at line 41 of file APT200.c.
integer numsur
Definition at line 41 of file APT200.c.
integer nw
Definition at line 41 of file APT200.c.
integer nwds
Definition at line 41 of file APT200.c.
logical pchlst
Definition at line 18 of file APT200.c.
doublereal pctpln[4]
Definition at line 60 of file APT200.c.
doublereal pctpts[60]
Definition at line 60 of file APT200.c.
logical prnton
Definition at line 18 of file APT200.c.
logical refflg
Definition at line 18 of file APT200.c.
logical refmot
Definition at line 18 of file APT200.c.
logical subflg
Definition at line 18 of file APT200.c.
logical tabprt
Definition at line 18 of file APT200.c.
logical unflag
Definition at line 18 of file APT200.c.
logical zflag
Definition at line 18 of file APT200.c.