My Project: APT296.c File Reference
APT296.c File Reference
#include "f2c.h"
Macros
#define ifxcor_1 ifxcor_
#define symfil_1 symfil_
Functions
int apt296_ (void)
int apt297_ (void)
Variables
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
static integer c__8 = 8
Macro Definition Documentation
#define ifxcor_1 ifxcor_
Definition at line 25 of file APT296.c.
#define symfil_1 symfil_
Definition at line 34 of file APT296.c.
Referenced by apt296_(), and apt297_().
Function Documentation
int apt296_ (void)
Definition at line 42 of file APT296.c.
References bcdf_(), c__8, ewrite_(), first, ir, record_(), and symfil_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static integer kholdp[8] = { 0,0,1308622848,0,1308622848,1,1308622848,3 };
     static logical first = TRUE_;
     static integer ir, nr;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int record_(integer *), ewrite_(integer *,
         integer *, integer *, integer *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /* ...            SYSTEM I/O FILE NAMES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /* ...                SYSTEM I/O FILES */
 /*     THIS SUBROUTINE WRITES THE HOLDPP */
 /*      RECORD ON EXFILE AT THE BEGINNING OF MACRO OUT PUT */
     if (first) {
     kholdp[0] = bcdf_("HOLD", (ftnlen)4);
     kholdp[1] = bcdf_("PP  ", (ftnlen)4);
     first = FALSE_;
     }
     record_(&kholdp[3]);
     nr = 0;
     ewrite_(&symfil_1.exfile, &nr, kholdp, &c__8, &ir);
     return 0;
 } /* apt296_ */
int apt297_ (void)
Definition at line 92 of file APT296.c.
References bcdf_(), c__8, ewrite_(), first, ir, record_(), and symfil_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static integer kholdp[8] = { 0,0,1308622848,0,1308622848,1,1308622848,4 };
     static logical first = TRUE_;
     static integer ir, nr;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int record_(integer *), ewrite_(integer *,
         integer *, integer *, integer *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /* ...            SYSTEM I/O FILE NAMES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /* ...                SYSTEM I/O FILES */
 /*     THIS SUBROUTINE WRITES THE HOLDPP */
 /*      RECORD ON EXFILE AT THE BEGINNING OF MACRO OUT PUT */
     if (first) {
     kholdp[0] = bcdf_("HOLD", (ftnlen)4);
     kholdp[1] = bcdf_("PP  ", (ftnlen)4);
     first = FALSE_;
     }
     record_(&kholdp[3]);
     nr = 0;
     ewrite_(&symfil_1.exfile, &nr, kholdp, &c__8, &ir);
     return 0;
 } /* apt297_ */
Variable Documentation
integer axfile
Definition at line 28 of file APT296.c.
integer c__8 = 8 static
Definition at line 38 of file APT296.c.
Referenced by apt296_(), and apt297_().
integer clfil3
Definition at line 28 of file APT296.c.
integer clfile
Definition at line 28 of file APT296.c.
integer clfilp
Definition at line 28 of file APT296.c.
integer cpfile
Definition at line 28 of file APT296.c.
integer elfil1
Definition at line 28 of file APT296.c.
integer elfil2
Definition at line 28 of file APT296.c.
integer elfil3
Definition at line 28 of file APT296.c.
integer elfil4
Definition at line 28 of file APT296.c.
integer elfile
Definition at line 28 of file APT296.c.
integer exfile
Definition at line 28 of file APT296.c.
integer i3dflg
Definition at line 18 of file APT296.c.
integer iaerr
Definition at line 18 of file APT296.c.
integer iautps
Definition at line 18 of file APT296.c.
integer ibegin
Definition at line 18 of file APT296.c.
integer ic
Definition at line 18 of file APT296.c.
integer icheck
Definition at line 18 of file APT296.c.
integer icl
Definition at line 18 of file APT296.c.
integer ics
Definition at line 18 of file APT296.c.
integer icscnt
Definition at line 18 of file APT296.c.
integer ictdef
Definition at line 18 of file APT296.c.
integer icut
Definition at line 18 of file APT296.c.
integer ids
Definition at line 18 of file APT296.c.
integer ier
Definition at line 18 of file APT296.c.
struct { ... } ifxcor_
integer igo
Definition at line 18 of file APT296.c.
integer igoto
Definition at line 18 of file APT296.c.
integer igoug
Definition at line 18 of file APT296.c.
integer igs
Definition at line 18 of file APT296.c.
integer infile__
Definition at line 28 of file APT296.c.
integer inops
Definition at line 18 of file APT296.c.
integer ips
Definition at line 18 of file APT296.c.
integer ipsdef
Definition at line 18 of file APT296.c.
integer ipt1
Definition at line 18 of file APT296.c.
integer is
Definition at line 18 of file APT296.c.
integer iseg
Definition at line 18 of file APT296.c.
integer iseqno
Definition at line 18 of file APT296.c.
integer ispare[26]
Definition at line 28 of file APT296.c.
integer isrch
Definition at line 18 of file APT296.c.
integer istrup
Definition at line 18 of file APT296.c.
integer it
Definition at line 18 of file APT296.c.
integer jbr
Definition at line 18 of file APT296.c.
integer jsw
Definition at line 18 of file APT296.c.
integer ldafil
Definition at line 28 of file APT296.c.
integer libfil
Definition at line 28 of file APT296.c.
integer lsv
Definition at line 18 of file APT296.c.
integer lsv1
Definition at line 18 of file APT296.c.
integer mactxt
Definition at line 28 of file APT296.c.
integer mantax
Definition at line 18 of file APT296.c.
integer motmod
Definition at line 18 of file APT296.c.
integer msav
Definition at line 18 of file APT296.c.
integer mulout
Definition at line 18 of file APT296.c.
integer nfil12
Definition at line 28 of file APT296.c.
integer nfil13
Definition at line 28 of file APT296.c.
integer nmbseg
Definition at line 18 of file APT296.c.
integer nmpnts
Definition at line 18 of file APT296.c.
integer nrec
Definition at line 18 of file APT296.c.
integer numax
Definition at line 18 of file APT296.c.
integer numcnt
Definition at line 18 of file APT296.c.
integer nump
Definition at line 18 of file APT296.c.
integer numpt1
Definition at line 18 of file APT296.c.
integer numsfs
Definition at line 18 of file APT296.c.
integer numsur
Definition at line 18 of file APT296.c.
integer nw
Definition at line 18 of file APT296.c.
integer nwds
Definition at line 18 of file APT296.c.
integer pnchfl
Definition at line 28 of file APT296.c.
integer pofile
Definition at line 28 of file APT296.c.
integer pxfile
Definition at line 28 of file APT296.c.
struct { ... } symfil_
integer tifile
Definition at line 28 of file APT296.c.
integer vlfile
Definition at line 28 of file APT296.c.
integer xcan
Definition at line 28 of file APT296.c.
integer xnum
Definition at line 28 of file APT296.c.