My Project: APT238.c File Reference
APT238.c File Reference
#include "f2c.h"
Macros
#define dshar4_1 dshar4_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define hblock_1 hblock_
#define sv_1 sv_
#define sv1_1 sv1_
#define isv_1 isv_
#define isv1_1 isv1_
#define ibrkpt_1 ibrkpt_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int apt238_ (integer *number)
Variables
struct {
doublereal a
doublereal b
doublereal c__
doublereal cendis
doublereal cmove [3]
doublereal com1
doublereal com4
doublereal dir [3]
doublereal dp
doublereal dpe
doublereal dpcnt
doublereal dpi
doublereal dpl
doublereal dp1
doublereal d1
doublereal d2a
doublereal flipck
doublereal fwd [3]
doublereal ogle [3]
doublereal p1 [3]
doublereal p2 [3]
doublereal rdrn
doublereal refpnt [3]
doublereal tangl
doublereal tes [3]
doublereal tew [3]
doublereal uvec [3]
doublereal u2 [3]
doublereal v [3]
doublereal vl
doublereal zl
doublereal zlnorm [3]
doublereal zlpnt [3]
doublereal zl1
doublereal param [6]
doublereal r__ [6]
doublereal savpar [4]
doublereal seg [9]
doublereal slope
doublereal sqroot
doublereal unn
doublereal upp
doublereal vint
doublereal vnn
doublereal vpp
} dshar4_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
char hps [8]
char hds [8]
char hcs [8]
char hlft [8]
char hrgt [8]
char hfwd [8]
char hback [8]
char hup [8]
char hdown [8]
char hto [8]
char hpast [8]
char hon [8]
char htanto [8]
char hpstan [8]
char hdynp [8]
char haerr [8]
char hcldat [8]
char hgerr [8]
} hblock_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer ibrkpt [51]
} ibrkpt_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c_n1 = -1
static integer c__0 = 0
static integer c__1 = 1
static integer c__3 = 3
static integer c_n3 = -3
Macro Definition Documentation
#define charct_1 charct_
Definition at line 40 of file APT238.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dshar4_1 dshar4_
Definition at line 25 of file APT238.c.
Referenced by apt238_().
#define fxcor_1 fxcor_
Definition at line 34 of file APT238.c.
Referenced by apt238_().
#define hblock_1 hblock_
Definition at line 55 of file APT238.c.
#define ibrkpt_1 ibrkpt_
Definition at line 103 of file APT238.c.
Referenced by apt238_().
#define ifxcor_1 ifxcor_
Definition at line 113 of file APT238.c.
Referenced by apt238_().
#define ishr18_1 ishr18_
Definition at line 121 of file APT238.c.
Referenced by apt238_().
#define isv1_1 isv1_
Definition at line 97 of file APT238.c.
Referenced by apt238_().
#define isv_1 isv_
Definition at line 90 of file APT238.c.
Referenced by apt238_().
#define knumbr_1 knumbr_
Definition at line 129 of file APT238.c.
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sv1_1 sv1_
Definition at line 81 of file APT238.c.
Referenced by apt238_().
#define sv_1 sv_
Definition at line 72 of file APT238.c.
Referenced by apt238_().
#define tlldat_1 tlldat_
Definition at line 47 of file APT238.c.
Function Documentation
int apt238_ (integer * number)
Definition at line 143 of file APT238.c.
References bad_(), c__0, c__1, c__3, c_n1, c_n3, dshar4_1, fxcor_1, ibrkpt_1, ifxcor_1, ishr18_1, isv1_1, isv_1, n, number, sv1_1, and sv_1.
Referenced by ajundd_(), amind_(), arlm3_(), centr_(), cplan_(), ddst_(), and go2_().
 {
     /* Local variables */
     static integer n, nn1, nn2;
     extern /* Subroutine */ int bad_();
     static integer is01, is02;
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static integer kfix;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*     *** 8.  HOLRTH BLOCK *** */
 /*     ALPHA-NUMERIC LITERAL CONSTANTS. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*   *** IBRKPT *** */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     n = *number;
     if (ibrkpt_1.ibrkpt[n - 1] != 0) {
     goto L2;
     } else {
     goto L1;
     }
 L2:
     kfix = (integer) fxcor_1.strtno;
     if (ifxcor_1.nmpnts - ifxcor_1.numpt1 < kfix) {
     goto L1;
     }
     is01 = ifxcor_1.is + 1;
     is02 = ifxcor_1.is + 2;
     bad_(&c_n1, &c__0, " ", &c__0, (ftnlen)1);
     nn1 = *number / 10 + 1;
     nn2 = *number % 10;
     nn1 = nn1 * 100 + nn2;
     bad_(&c__1, &c__0, "DYND", &nn1, (ftnlen)4);
     bad_(&c_n1, &c__0, "SEQN", &ifxcor_1.iseqno, (ftnlen)4);
     switch (n) {
     case 1:  goto L101;
     case 2:  goto L102;
     case 3:  goto L103;
     case 4:  goto L104;
     case 5:  goto L105;
     case 6:  goto L106;
     case 7:  goto L107;
     case 8:  goto L999;
     case 9:  goto L999;
     case 10:  goto L999;
     case 11:  goto L201;
     case 12:  goto L202;
     case 13:  goto L203;
     case 14:  goto L204;
     case 15:  goto L205;
     case 16:  goto L206;
     case 17:  goto L207;
     case 18:  goto L208;
     case 19:  goto L209;
     case 20:  goto L210;
     case 21:  goto L211;
     case 22:  goto L212;
     case 23:  goto L213;
     case 24:  goto L214;
     case 25:  goto L215;
     case 26:  goto L216;
     case 27:  goto L217;
     case 28:  goto L999;
     case 29:  goto L999;
     case 30:  goto L999;
     case 31:  goto L401;
     case 32:  goto L402;
     case 33:  goto L403;
     case 34:  goto L404;
     case 35:  goto L999;
     case 36:  goto L999;
     case 37:  goto L999;
     case 38:  goto L999;
     case 39:  goto L999;
     case 40:  goto L999;
     case 41:  goto L501;
     case 42:  goto L502;
     case 43:  goto L503;
     case 44:  goto L504;
     case 45:  goto L505;
     case 46:  goto L999;
     case 47:  goto L999;
     case 48:  goto L999;
     case 49:  goto L999;
     case 50:  goto L999;
     }
 /* *101 CALL APT239(1,S(IS),TP(IS),TP(IS01),TP(IS02),TN(IS),TN(IS01), */
 /* *   C TN(IS02)) */
 /* *    GO TO 1 */
 /* *102 CALL APT239(2,S(IS),SP(IS),SP(IS01),SP(IS02),SN(IS), */
 /* *   C SN(IS01),SN(IS02)) */
 /* *    GO TO 1 */
 /* *103 CALL APT239(3,IS,JENT(IS),JTN(IS),IOPSET(IS),JU1(IS), */
 /* *   C TE(1),TE(2),TE(3),TA(1),TA(2),TA(3)) */
 /* *    GO TO 1 */
 /* *104 CALL APT239(4,IS,S(IS),ISIGCR(IS),Z(IS),RC(IS),CC(IS),CC(IS01), */
 /* *   C CC(IS02),SP(IS),SP(IS01),SP(IS02),SPL(IS),SPL(IS01),SPL(IS02), */
 /* *   2 SN(IS),SN(IS01),SN(IS02)) */
 /* *    GO TO 1 */
 /* *105 CALL APT239 (5,IS,TP(IS),TP(IS01),TP(IS02),TN(IS), */
 /* *   C TN(IS01),TN(IS02)) */
 /* *    GO TO 1 */
 /* *106 CALL APT239(6,IS,S(IS),Z(IS),FLIPCK,IAMDCT,SP(IS), */
 /* *   C SP(IS01),SP(IS02),SN(IS),SN(IS01),SN(IS02), */
 /* *   2 TP(IS),TP(IS01),TP(IS02),TN(IS),TN(IS01),TN(IS02)) */
 /* *    GO TO 1 */
 /* *107 CALL APT239(7,IS,S(IS),TAU1(IS),TAU2(IS),Z(IS), */
 /* *   C FLIPCK,IAMDCT,TH(IS),RC(IS), */
 /* *   2 SP(IS),SP(IS01),SP(IS02),SN(IS),SN(IS01),SN(IS02),TP(IS),TP(IS01) */
 /* *   3,TP(IS02),TN(IS),TN(IS01),TN(IS02),CC(IS),CC(IS01),CC(IS02), */
 /* *   4 VT(IS),VT(IS01),VT(IS02)) */
 /* *    GO TO 1 */
 /* *201 CALL APT239(11,TEK(1),TEK(2),TEK(3),TAK(1),TAK(2),TAK(3), */
 /* *   C TIK(1),TIK(2),TIK(3),SPK(IPS),SPK(IPS+1),SPK(IPS+2), */
 /* *   2 TPK(IPS),TPK(IPS+1),TPK(IPS+2),SPK(IDS),SPK(IDS+1),SPK(IDS+2), */
 /* *   3 TPK(IDS),TPK(IDS+1),TPK(IDS+2)) */
 /* *    GO TO 1 */
 /* *202 CALL APT239(12,DP,DPI) */
 /* *    GO TO 1 */
 /* *203 CALL APT239(13,IS,CSD(IS),DPI) */
 /* *    GO TO 1 */
 /* *204 CALL APT239(14,DP,CMOVE(1),CMOVE(2),CMOVE(3),TEL(1),TEL(2),TEL(3), */
 /* *   C TAL(1),TAL(2),TAL(3),TE(1),TE(2),TE(3),TA(1),TA(2),TA(3)) */
 /* *    GO TO 1 */
 /* *205 CALL APT239(15,IS,JCR,TE(1),TE(2),TE(3),TA(1),TA(2),TA(3)) */
 /* *    GO TO 1 */
 /* *206 CALL APT239(16,JDR,DP) */
 /* *    GO TO 1 */
 /* *207 CALL APT239(17,IS,JCKR,CSD(IS)) */
 /* *    GO TO 1 */
 /* *208 CALL APT239(18,VL,NUMPT1) */
 /* *    GO TO 1 */
 /* *209 CALL APT239(19,JCR,IWS,TEE(IS),TEE(IS01),TEE(IS02)) */
 /* *    GO TO 1 */
 /* *210 CALL APT239(20,IS,S(IS),Z(IS),J23(IS),STCK(IS),STCK1(IS)) */
 /* *    GO TO 1 */
 /* *211 CALL APT239(21,IS,J23(IS),STCK2(IS),STCK(IS), */
 /* *   C SN(IS),SN(IS01),SN(IS02)) */
 /* *    GO TO 1 */
 /* *212 CALL APT239 (22,IS,JDR,DP,VL) */
 /* *    GO TO 1 */
 /* *213 CALL APT239(23,IS,DP) */
 /* *    GO TO 1 */
 /* *214 CALL APT239(24,IS,JPR,CSD(IS)) */
 /* *    GO TO 1 */
 /* *215 CALL APT239(25,IS,ISFTYP(IS),J23(IS),S(IS),Z(IS),STCK(IS), */
 /* *   C STCK1(IS),STCK2(IS)) */
 /* *    GO TO 1 */
 /* *216 CALL APT239(26,ISFTYP(IS),J23(IS),STCK2(IS),STCKN(IS), */
 /* *   C SN(IS),SN(IS01),SN(IS02),TI(1),TI(2),TI(3)) */
 /* *    GO TO 1 */
 /* *217 CALL APT239(27,IS,IFAR(IS),TE(1),TE(2),TE(3),TA(1),TA(2),TA(3)) */
 /* *    GO TO 1 */
 /* *401 CALL APT239(31,JPXR,PLND(IS),PLNV(IS),PLNV(IS01),PLNV(IS02), */
 /* *   C CMOVE(1),CMOVE(2),CMOVE(3)) */
 /* *    GO TO 1 */
 /* *402 CALL APT239(32,CPTST(IS),CPLFL(IS),PLND(IS),PLNV(IS),PLNV(IS01), */
 /* *   C PLNV(IS02)) */
 /* *    GO TO 1 */
 /* *403 CALL APT239(33,IS,PLND1(IS),PLTST(IS)) */
 /* *    GO TO 1 */
 /* *404 CALL APT239(34,IT,S(IT),ISIGCR(IT),Z(IT),RC(IT),SP(IT),SP(IT+1), */
 /* *   C SP(IT+2),CC(IT),CC(IT+1),CC(IT+2),SPL(IT),SPL(IT+1),SPL(IT+2), */
 /* *   2 SN(IT),SN(IT+1),SN(IT+2)) */
 /* *    GO TO 1 */
 /* *501 CALL APT239(41,INOPS,NUMSUR,IAUTPS) */
 /* *    GO TO 1 */
 /* *502 CALL APT239(42,IS,INDIR(IS)) */
 /* *    GO TO 1 */
 /* *503 CALL APT239(43,IS,VNDIR(IS),VNDIR(IS01),VNDIR(IS02), */
 /* *   C TE(1),TE(2),TE(3)) */
 /* *    GO TO 1 */
 /* *504 CALL APT239(44,IS,ISVFL(IS),CSD(IS),SN(IS),SN(IS01),SN(IS02)) */
 /* *999 GO TO 1 */
 /* *505 CALL APT239(45,TE(1),TE(2),TE(3)) */
 /* *  1 RETURN */
 /* *    END */
 L101:
     bad_(&c__1, &c__1, "S   ", &sv_1.s[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "Z   ", &sv_1.z__[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__3, &c__1, "TP  ", &sv_1.tp[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "TN  ", &sv_1.tn[ifxcor_1.is * 3 - 3], (ftnlen)4);
     goto L1;
 L102:
     bad_(&c__1, &c__1, "S   ", &sv_1.s[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "Z   ", &sv_1.z__[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__3, &c__1, "SP  ", &sv_1.sp[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "SN  ", &sv_1.sn[ifxcor_1.is * 3 - 3], (ftnlen)4);
     goto L1;
 L103:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__0, "JENT", &isv_1.jent[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__0, "JTN ", &isv_1.jtn[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__0, "IOPS", &isv_1.iopset[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__0, "JU1 ", &isv_1.ju1[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__0, "ITLN", &isv_1.itlon[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__3, &c__1, "TE  ", fxcor_1.te, (ftnlen)4);
     bad_(&c_n3, &c__1, "TA  ", fxcor_1.ta, (ftnlen)4);
     goto L1;
 L104:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__1, "S   ", &sv_1.s[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__0, "ISGC", &isv_1.isigcr[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "Z   ", &sv_1.z__[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "RC  ", &sv_1.rc[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__3, &c__1, "SP  ", &sv_1.sp[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "SN  ", &sv_1.sn[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c__3, &c__1, "SPL ", &sv_1.spl[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "CC  ", &sv_1.cc[ifxcor_1.is * 3 - 3], (ftnlen)4);
     goto L1;
 L105:
     bad_(&c_n1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__3, &c__1, "TP  ", &sv_1.tp[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "TN  ", &sv_1.tn[ifxcor_1.is * 3 - 3], (ftnlen)4);
     goto L1;
 L106:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__1, "S   ", &sv_1.s[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "Z   ", &sv_1.z__[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "FLCK", &dshar4_1.flipck, (ftnlen)4);
     bad_(&c_n1, &c__0, "AMCT", &ishr18_1.iamdct, (ftnlen)4);
     bad_(&c__3, &c__1, "SP  ", &sv_1.sp[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "SN  ", &sv_1.sn[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c__3, &c__1, "TP  ", &sv_1.tp[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "TN  ", &sv_1.tn[ifxcor_1.is * 3 - 3], (ftnlen)4);
     goto L1;
 L107:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__1, "S   ", &sv_1.s[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "TAU1", &sv_1.tau1[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "TAU2", &sv_1.tau2[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "Z   ", &sv_1.z__[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "FLCK", &dshar4_1.flipck, (ftnlen)4);
     bad_(&c__1, &c__0, "AMCT", &ishr18_1.iamdct, (ftnlen)4);
     bad_(&c__1, &c__1, "TH  ", &sv_1.th[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "RC  ", &sv_1.rc[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__3, &c__1, "SP  ", &sv_1.sp[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "SN  ", &sv_1.sn[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c__3, &c__1, "TP  ", &sv_1.tp[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "TN  ", &sv_1.tn[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c__3, &c__1, "CC  ", &sv_1.cc[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "VT  ", &sv_1.vt[ifxcor_1.is * 3 - 3], (ftnlen)4);
     goto L1;
 L201:
     bad_(&c__3, &c__1, "TEK ", fxcor_1.tek, (ftnlen)4);
     bad_(&c_n3, &c__1, "TAK ", fxcor_1.tak, (ftnlen)4);
     bad_(&c__3, &c__1, "SPKP", &sv_1.spk[ifxcor_1.ips * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "SPKD", &sv_1.spk[ifxcor_1.ids * 3 - 3], (ftnlen)4);
     bad_(&c__3, &c__1, "TPKP", &sv_1.tpk[ifxcor_1.ips * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "TPK ", &sv_1.tpk[ifxcor_1.ids * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "TIK ", fxcor_1.tik, (ftnlen)4);
     goto L1;
 L202:
     bad_(&c__1, &c__1, "DP  ", &dshar4_1.dp, (ftnlen)4);
     bad_(&c_n1, &c__1, "DPI ", &dshar4_1.dpi, (ftnlen)4);
     goto L1;
 L203:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__1, "CSD ", &sv1_1.csd[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "DPI ", &dshar4_1.dpi, (ftnlen)4);
     goto L1;
 L204:
     bad_(&c__3, &c__1, "CMOV", dshar4_1.cmove, (ftnlen)4);
     bad_(&c_n1, &c__1, "DP  ", &dshar4_1.dp, (ftnlen)4);
     bad_(&c__3, &c__1, "TE  ", fxcor_1.te, (ftnlen)4);
     bad_(&c_n3, &c__1, "TA  ", fxcor_1.ta, (ftnlen)4);
     bad_(&c__3, &c__1, "TEL ", fxcor_1.tel, (ftnlen)4);
     bad_(&c_n3, &c__1, "TAL ", fxcor_1.tal, (ftnlen)4);
     goto L1;
 L205:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c_n1, &c__0, "JCR ", &ishr18_1.jcr, (ftnlen)4);
     bad_(&c__3, &c__1, "TE  ", fxcor_1.te, (ftnlen)4);
     bad_(&c_n3, &c__1, "TA  ", fxcor_1.ta, (ftnlen)4);
     goto L1;
 L206:
     bad_(&c__1, &c__0, "JDR ", &ishr18_1.jdr, (ftnlen)4);
     bad_(&c_n1, &c__0, "DP  ", &dshar4_1.dp, (ftnlen)4);
     goto L1;
 L207:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__0, "JCKR", &ishr18_1.jckr, (ftnlen)4);
     bad_(&c_n1, &c__0, "CSD ", &sv1_1.csd[ifxcor_1.is - 1], (ftnlen)4);
     goto L1;
 L208:
     bad_(&c__1, &c__0, "NMPT", &ifxcor_1.numpt1, (ftnlen)4);
     bad_(&c_n1, &c__1, "VL  ", &dshar4_1.vl, (ftnlen)4);
     goto L1;
 L209:
     bad_(&c__1, &c__0, "JCR ", &ishr18_1.jcr, (ftnlen)4);
     bad_(&c__1, &c__0, "IWS ", &ishr18_1.iws, (ftnlen)4);
     bad_(&c_n3, &c__1, "TEE ", &sv1_1.tee[ifxcor_1.is * 3 - 3], (ftnlen)4);
     goto L1;
 L210:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__1, "S   ", &sv_1.s[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "Z   ", &sv_1.z__[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__0, "J23 ", &isv1_1.j23[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "STCK", &sv1_1.stck[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "STK1", &sv1_1.stck1[ifxcor_1.is - 1], (ftnlen)4);
     goto L1;
 L211:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__0, "J23 ", &isv1_1.j23[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "STK2", &sv1_1.stck2[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "STCK", &sv1_1.stck[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n3, &c__1, "SN  ", &sv_1.sn[ifxcor_1.is * 3 - 3], (ftnlen)4);
     goto L1;
 L212:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__0, "JDR ", &ishr18_1.jdr, (ftnlen)4);
     bad_(&c__1, &c__1, "DP  ", &dshar4_1.dp, (ftnlen)4);
     bad_(&c_n1, &c__1, "VL  ", &dshar4_1.vl, (ftnlen)4);
     goto L1;
 L213:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c_n1, &c__1, "DP  ", &dshar4_1.dp, (ftnlen)4);
     goto L1;
 L214:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__0, "JPR ", &ishr18_1.jpr, (ftnlen)4);
     bad_(&c_n1, &c__1, "CSD ", &sv1_1.csd[ifxcor_1.is - 1], (ftnlen)4);
     goto L1;
 L215:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__0, "ISFT", &isv_1.isftyp[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__0, "J23 ", &isv1_1.j23[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "S   ", &sv_1.s[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "Z   ", &sv_1.z__[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "STCK", &sv1_1.stck[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "STK1", &sv1_1.stck1[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "STK2", &sv1_1.stck2[ifxcor_1.is - 1], (ftnlen)4);
     goto L1;
 L216:
     bad_(&c__1, &c__0, "ISFT", &isv_1.isftyp[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__0, "J23 ", &isv1_1.j23[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "STK2", &sv1_1.stck2[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "STKN", &sv1_1.stckn[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__3, &c__1, "SN  ", &sv_1.sn[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "TI  ", fxcor_1.ti, (ftnlen)4);
     goto L1;
 L217:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c_n1, &c__0, "IFAR", &isv1_1.ifar[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__3, &c__1, "TE  ", fxcor_1.te, (ftnlen)4);
     bad_(&c_n3, &c__1, "TA  ", fxcor_1.ta, (ftnlen)4);
     goto L1;
 L401:
     bad_(&c__1, &c__0, "JPXR", &ishr18_1.jpxr, (ftnlen)4);
     bad_(&c_n1, &c__1, "PLND", &sv_1.plnd[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__3, &c__1, "PLNV", &sv_1.plnv[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "CMOV", dshar4_1.cmove, (ftnlen)4);
     goto L1;
 L402:
     bad_(&c__1, &c__1, "CPTS", &sv1_1.cptst[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "CPLF", &sv1_1.cplfl[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "PLND", &sv_1.plnd[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n3, &c__1, "PLNV", &sv_1.plnv[ifxcor_1.is * 3 - 3], (ftnlen)4);
     goto L1;
 L403:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__1, "PLD1", &sv1_1.plnd1[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "PLTS", &sv1_1.pltst[ifxcor_1.is - 1], (ftnlen)4);
     goto L1;
 L404:
     bad_(&c__1, &c__0, "IT  ", &ifxcor_1.it, (ftnlen)4);
     bad_(&c__1, &c__1, "S   ", &sv_1.s[ifxcor_1.it - 1], (ftnlen)4);
     bad_(&c__1, &c__0, "ISGC", &isv_1.isigcr[ifxcor_1.it - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "Z   ", &sv_1.z__[ifxcor_1.it - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "RC  ", &sv_1.rc[ifxcor_1.it - 1], (ftnlen)4);
     bad_(&c__3, &c__1, "SP  ", &sv_1.sp[ifxcor_1.it * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "SN  ", &sv_1.sn[ifxcor_1.it * 3 - 3], (ftnlen)4);
     bad_(&c__3, &c__1, "SPL ", &sv_1.spl[ifxcor_1.it * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "CC  ", &sv_1.cc[ifxcor_1.it * 3 - 3], (ftnlen)4);
     goto L1;
 L501:
     bad_(&c__1, &c__0, "INPS", &ifxcor_1.inops, (ftnlen)4);
     bad_(&c__1, &c__0, "NMSR", &ifxcor_1.numsur, (ftnlen)4);
     bad_(&c_n1, &c__0, "IAUT", &ifxcor_1.iautps, (ftnlen)4);
     goto L1;
 L502:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c_n1, &c__0, "INDR", &isv_1.indir__[ifxcor_1.is - 1], (ftnlen)4);
     goto L1;
 L503:
     bad_(&c_n1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__3, &c__1, "VNDR", &sv_1.vndir[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "TE  ", fxcor_1.te, (ftnlen)4);
     goto L1;
 L504:
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c__1, &c__0, "ISVF", &isv_1.isvfl[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "CSD ", &sv1_1.csd[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n3, &c__1, "SN  ", &sv_1.sn[ifxcor_1.is * 3 - 3], (ftnlen)4);
 L999:
     goto L1;
 L505:
     bad_(&c_n3, &c__1, "TE  ", fxcor_1.te, (ftnlen)4);
 L1:
     return 0;
 } /* apt238_ */
Variable Documentation
doublereal a
Definition at line 18 of file APT238.c.
doublereal alp
Definition at line 28 of file APT238.c.
doublereal ax4[3]
Definition at line 28 of file APT238.c.
doublereal b
Definition at line 18 of file APT238.c.
doublereal c__
Definition at line 18 of file APT238.c.
integer c__0 = 0 static
Definition at line 134 of file APT238.c.
Referenced by apt238_().
integer c__1 = 1 static
Definition at line 135 of file APT238.c.
Referenced by apt238_().
integer c__3 = 3 static
Definition at line 136 of file APT238.c.
Referenced by apt238_().
integer c_n1 = -1 static
Definition at line 133 of file APT238.c.
Referenced by apt238_().
integer c_n3 = -3 static
Definition at line 137 of file APT238.c.
Referenced by apt238_().
doublereal cagl
Definition at line 28 of file APT238.c.
doublereal cc[15]
Definition at line 58 of file APT238.c.
doublereal cendis
Definition at line 18 of file APT238.c.
struct { ... } charct_
doublereal cmove[3]
Definition at line 18 of file APT238.c.
doublereal com1
Definition at line 18 of file APT238.c.
doublereal com4
Definition at line 18 of file APT238.c.
doublereal corrad[8]
Definition at line 43 of file APT238.c.
doublereal cos1[5]
Definition at line 75 of file APT238.c.
doublereal cplfl[5]
Definition at line 75 of file APT238.c.
doublereal cptst[5]
Definition at line 75 of file APT238.c.
doublereal csd[5]
Definition at line 75 of file APT238.c.
doublereal cutdat[7]
Definition at line 28 of file APT238.c.
doublereal d1
Definition at line 18 of file APT238.c.
doublereal d2a
Definition at line 18 of file APT238.c.
doublereal dir[3]
Definition at line 18 of file APT238.c.
doublereal dp
Definition at line 18 of file APT238.c.
doublereal dp1
Definition at line 18 of file APT238.c.
doublereal dpcnt
Definition at line 18 of file APT238.c.
doublereal dpe
Definition at line 18 of file APT238.c.
doublereal dpi
Definition at line 18 of file APT238.c.
doublereal dpl
Definition at line 18 of file APT238.c.
doublereal dplan[15]
Definition at line 75 of file APT238.c.
doublereal dpmax
Definition at line 28 of file APT238.c.
doublereal dpmx1[5]
Definition at line 75 of file APT238.c.
struct { ... } dshar4_
doublereal eps1[5]
Definition at line 58 of file APT238.c.
doublereal eps2[5]
Definition at line 58 of file APT238.c.
doublereal eps3[5]
Definition at line 58 of file APT238.c.
doublereal eps4[5]
Definition at line 58 of file APT238.c.
doublereal eps6[5]
Definition at line 58 of file APT238.c.
doublereal eps8[5]
Definition at line 58 of file APT238.c.
doublereal flipck
Definition at line 18 of file APT238.c.
doublereal fwd[3]
Definition at line 18 of file APT238.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file APT238.c.
char haerr[8]
Definition at line 50 of file APT238.c.
char hback[8]
Definition at line 50 of file APT238.c.
struct { ... } hblock_
char hcldat[8]
Definition at line 50 of file APT238.c.
char hcs[8]
Definition at line 50 of file APT238.c.
char hdown[8]
Definition at line 50 of file APT238.c.
char hds[8]
Definition at line 50 of file APT238.c.
char hdynp[8]
Definition at line 50 of file APT238.c.
char hfwd[8]
Definition at line 50 of file APT238.c.
char hgerr[8]
Definition at line 50 of file APT238.c.
doublereal hi
Definition at line 28 of file APT238.c.
char hlft[8]
Definition at line 50 of file APT238.c.
char hon[8]
Definition at line 50 of file APT238.c.
char hpast[8]
Definition at line 50 of file APT238.c.
char hps[8]
Definition at line 50 of file APT238.c.
char hpstan[8]
Definition at line 50 of file APT238.c.
char hrgt[8]
Definition at line 50 of file APT238.c.
char htanto[8]
Definition at line 50 of file APT238.c.
char hto[8]
Definition at line 50 of file APT238.c.
char hup[8]
Definition at line 50 of file APT238.c.
integer i3dflg
Definition at line 106 of file APT238.c.
integer iaerr
Definition at line 106 of file APT238.c.
integer iafl[5]
Definition at line 84 of file APT238.c.
integer iamdct
Definition at line 116 of file APT238.c.
integer iautps
Definition at line 106 of file APT238.c.
integer ibegin
Definition at line 106 of file APT238.c.
integer ibrkpt[51]
Definition at line 100 of file APT238.c.
struct { ... } ibrkpt_
integer ic
Definition at line 106 of file APT238.c.
integer icanon[5]
Definition at line 84 of file APT238.c.
integer icheck
Definition at line 106 of file APT238.c.
integer icl
Definition at line 106 of file APT238.c.
integer ics
Definition at line 106 of file APT238.c.
integer icscnt
Definition at line 106 of file APT238.c.
integer ictdef
Definition at line 106 of file APT238.c.
integer icut
Definition at line 106 of file APT238.c.
integer ids
Definition at line 106 of file APT238.c.
integer ier
Definition at line 106 of file APT238.c.
integer ifar[5]
Definition at line 93 of file APT238.c.
integer ifl4[5]
Definition at line 93 of file APT238.c.
struct { ... } ifxcor_
integer igo
Definition at line 106 of file APT238.c.
integer igoto
Definition at line 106 of file APT238.c.
integer igoug
Definition at line 106 of file APT238.c.
integer igs
Definition at line 106 of file APT238.c.
integer index[5]
Definition at line 84 of file APT238.c.
integer indir__[5]
Definition at line 84 of file APT238.c.
integer inops
Definition at line 106 of file APT238.c.
integer iop[5]
Definition at line 84 of file APT238.c.
integer iopset[5]
Definition at line 84 of file APT238.c.
integer ipdpl
Definition at line 116 of file APT238.c.
integer ipl[5]
Definition at line 84 of file APT238.c.
integer ips
Definition at line 106 of file APT238.c.
integer ipsdef
Definition at line 106 of file APT238.c.
integer ipt
Definition at line 116 of file APT238.c.
integer ipt1
Definition at line 106 of file APT238.c.
integer is
Definition at line 106 of file APT238.c.
integer iseg
Definition at line 106 of file APT238.c.
integer iseqno
Definition at line 106 of file APT238.c.
integer isfidn[5]
Definition at line 84 of file APT238.c.
integer isftyp[5]
Definition at line 84 of file APT238.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 84 of file APT238.c.
integer isrch
Definition at line 106 of file APT238.c.
integer istrup
Definition at line 106 of file APT238.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 84 of file APT238.c.
integer it
Definition at line 106 of file APT238.c.
integer itlon[5]
Definition at line 84 of file APT238.c.
integer itseg[5]
Definition at line 84 of file APT238.c.
integer itsegk[5]
Definition at line 84 of file APT238.c.
integer iunfl[5]
Definition at line 84 of file APT238.c.
integer iws
Definition at line 116 of file APT238.c.
integer j10
Definition at line 116 of file APT238.c.
integer j12
Definition at line 116 of file APT238.c.
integer j13
Definition at line 116 of file APT238.c.
integer j20[5]
Definition at line 93 of file APT238.c.
integer j21[5]
Definition at line 93 of file APT238.c.
integer j22[5]
Definition at line 93 of file APT238.c.
integer j23[5]
Definition at line 93 of file APT238.c.
integer j50[5]
Definition at line 93 of file APT238.c.
integer j51[5]
Definition at line 93 of file APT238.c.
integer j54
Definition at line 116 of file APT238.c.
integer jbr
Definition at line 106 of file APT238.c.
integer jckr
Definition at line 116 of file APT238.c.
integer jcnt1
Definition at line 116 of file APT238.c.
integer jcnt2
Definition at line 116 of file APT238.c.
integer jcnt3
Definition at line 116 of file APT238.c.
integer jcpr
Definition at line 116 of file APT238.c.
integer jcr
Definition at line 116 of file APT238.c.
integer jdr
Definition at line 116 of file APT238.c.
integer jent[5]
Definition at line 84 of file APT238.c.
integer jfind
Definition at line 116 of file APT238.c.
integer jgr
Definition at line 116 of file APT238.c.
integer jiops[5]
Definition at line 84 of file APT238.c.
integer jmin
Definition at line 116 of file APT238.c.
integer jminr
Definition at line 116 of file APT238.c.
integer jph[5]
Definition at line 93 of file APT238.c.
integer jpr
Definition at line 116 of file APT238.c.
integer jpxr
Definition at line 116 of file APT238.c.
integer jsw
Definition at line 106 of file APT238.c.
integer jtkf
Definition at line 116 of file APT238.c.
integer jtlflg[5]
Definition at line 84 of file APT238.c.
integer jtn[5]
Definition at line 84 of file APT238.c.
integer jtr
Definition at line 116 of file APT238.c.
integer ju1[5]
Definition at line 84 of file APT238.c.
integer k0
Definition at line 124 of file APT238.c.
integer k1
Definition at line 124 of file APT238.c.
integer k10
Definition at line 124 of file APT238.c.
integer k1013
Definition at line 124 of file APT238.c.
integer k12
Definition at line 124 of file APT238.c.
integer k13
Definition at line 124 of file APT238.c.
integer k15
Definition at line 124 of file APT238.c.
integer k16
Definition at line 124 of file APT238.c.
integer k18
Definition at line 124 of file APT238.c.
integer k19
Definition at line 124 of file APT238.c.
integer k1e4
Definition at line 124 of file APT238.c.
integer k1e6
Definition at line 124 of file APT238.c.
integer k2
Definition at line 124 of file APT238.c.
integer k23
Definition at line 124 of file APT238.c.
integer k24
Definition at line 124 of file APT238.c.
integer k25
Definition at line 124 of file APT238.c.
integer k26
Definition at line 124 of file APT238.c.
integer k27
Definition at line 124 of file APT238.c.
integer k29
Definition at line 124 of file APT238.c.
integer k3
Definition at line 124 of file APT238.c.
integer k30
Definition at line 124 of file APT238.c.
integer k31
Definition at line 124 of file APT238.c.
integer k32
Definition at line 124 of file APT238.c.
integer k33
Definition at line 124 of file APT238.c.
integer k34
Definition at line 124 of file APT238.c.
integer k4
Definition at line 124 of file APT238.c.
integer k44
Definition at line 124 of file APT238.c.
integer k45
Definition at line 124 of file APT238.c.
integer k46
Definition at line 124 of file APT238.c.
integer k47
Definition at line 124 of file APT238.c.
integer k48
Definition at line 124 of file APT238.c.
integer k5
Definition at line 124 of file APT238.c.
integer k50
Definition at line 124 of file APT238.c.
integer k51
Definition at line 124 of file APT238.c.
integer k52
Definition at line 124 of file APT238.c.
integer k6
Definition at line 124 of file APT238.c.
integer k7
Definition at line 124 of file APT238.c.
integer k8
Definition at line 124 of file APT238.c.
integer k9
Definition at line 124 of file APT238.c.
integer km1
Definition at line 124 of file APT238.c.
struct { ... } knumbr_
integer limfl[5]
Definition at line 84 of file APT238.c.
integer lsv
Definition at line 106 of file APT238.c.
integer lsv1
Definition at line 106 of file APT238.c.
integer mantax
Definition at line 106 of file APT238.c.
integer mdic
Definition at line 116 of file APT238.c.
char modfer[6]
Definition at line 37 of file APT238.c.
integer motmod
Definition at line 106 of file APT238.c.
integer msav
Definition at line 106 of file APT238.c.
integer mulout
Definition at line 106 of file APT238.c.
integer nmbseg
Definition at line 106 of file APT238.c.
integer nmpnts
Definition at line 106 of file APT238.c.
integer notan[5]
Definition at line 93 of file APT238.c.
integer nrec
Definition at line 106 of file APT238.c.
integer numax
Definition at line 106 of file APT238.c.
integer numcnt
Definition at line 106 of file APT238.c.
integer nump
Definition at line 106 of file APT238.c.
integer numpt1
Definition at line 106 of file APT238.c.
integer numsfs
Definition at line 106 of file APT238.c.
integer numsur
Definition at line 106 of file APT238.c.
integer nw
Definition at line 106 of file APT238.c.
integer nwds
Definition at line 106 of file APT238.c.
doublereal ogle[3]
Definition at line 18 of file APT238.c.
doublereal p1[3]
Definition at line 18 of file APT238.c.
doublereal p2[3]
Definition at line 18 of file APT238.c.
doublereal param[6]
Definition at line 18 of file APT238.c.
doublereal past[5]
Definition at line 58 of file APT238.c.
doublereal plncs[5]
Definition at line 75 of file APT238.c.
doublereal plnd[5]
Definition at line 58 of file APT238.c.
doublereal plnd1[5]
Definition at line 75 of file APT238.c.
doublereal plnv[15]
Definition at line 58 of file APT238.c.
doublereal pltst[5]
Definition at line 75 of file APT238.c.
doublereal pmove[3]
Definition at line 28 of file APT238.c.
doublereal r__[6]
Definition at line 18 of file APT238.c.
doublereal ra
Definition at line 28 of file APT238.c.
doublereal rc[5]
Definition at line 58 of file APT238.c.
doublereal rc1
Definition at line 28 of file APT238.c.
doublereal rdrn
Definition at line 18 of file APT238.c.
doublereal refpnt[3]
Definition at line 18 of file APT238.c.
doublereal ri[8]
Definition at line 43 of file APT238.c.
doublereal s[5]
Definition at line 58 of file APT238.c.
doublereal sagl
Definition at line 28 of file APT238.c.
doublereal save[5]
Definition at line 58 of file APT238.c.
doublereal savpar[4]
Definition at line 18 of file APT238.c.
doublereal seg[9]
Definition at line 18 of file APT238.c.
doublereal sfvct[15]
Definition at line 58 of file APT238.c.
doublereal sk[15]
Definition at line 58 of file APT238.c.
doublereal slope
Definition at line 18 of file APT238.c.
doublereal slx[15]
Definition at line 58 of file APT238.c.
doublereal sn[15]
Definition at line 58 of file APT238.c.
doublereal snk[15]
Definition at line 58 of file APT238.c.
doublereal snl[15]
Definition at line 58 of file APT238.c.
doublereal sp[15]
Definition at line 58 of file APT238.c.
doublereal spk[15]
Definition at line 58 of file APT238.c.
doublereal spl[15]
Definition at line 58 of file APT238.c.
doublereal sqroot
Definition at line 18 of file APT238.c.
doublereal stck[5]
Definition at line 75 of file APT238.c.
doublereal stck1[5]
Definition at line 75 of file APT238.c.
doublereal stck2[5]
Definition at line 75 of file APT238.c.
doublereal stckn[5]
Definition at line 75 of file APT238.c.
doublereal strtno
Definition at line 28 of file APT238.c.
doublereal surd
Definition at line 28 of file APT238.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 28 of file APT238.c.
doublereal tak[3]
Definition at line 28 of file APT238.c.
doublereal tal[3]
Definition at line 28 of file APT238.c.
doublereal tangl
Definition at line 18 of file APT238.c.
doublereal tanhi[8]
Definition at line 43 of file APT238.c.
doublereal tanlo[8]
Definition at line 43 of file APT238.c.
doublereal tau[5]
Definition at line 58 of file APT238.c.
doublereal tau1[5]
Definition at line 58 of file APT238.c.
doublereal tau2[5]
Definition at line 58 of file APT238.c.
doublereal tcont[9]
Definition at line 43 of file APT238.c.
doublereal te[3]
Definition at line 28 of file APT238.c.
doublereal tee[15]
Definition at line 75 of file APT238.c.
doublereal tek[3]
Definition at line 28 of file APT238.c.
doublereal tel[3]
Definition at line 28 of file APT238.c.
doublereal tem[10]
Definition at line 28 of file APT238.c.
doublereal temp[24]
Definition at line 28 of file APT238.c.
doublereal tes[3]
Definition at line 18 of file APT238.c.
doublereal tew[3]
Definition at line 18 of file APT238.c.
doublereal th[5]
Definition at line 58 of file APT238.c.
doublereal ti[3]
Definition at line 28 of file APT238.c.
doublereal tik[3]
Definition at line 28 of file APT238.c.
doublereal til[3]
Definition at line 28 of file APT238.c.
doublereal tlhit
Definition at line 28 of file APT238.c.
doublereal tlhite[8]
Definition at line 43 of file APT238.c.
doublereal tlinc[9]
Definition at line 43 of file APT238.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file APT238.c.
doublereal tn[15]
Definition at line 58 of file APT238.c.
doublereal tnl[15]
Definition at line 75 of file APT238.c.
doublereal toolht[15]
Definition at line 58 of file APT238.c.
doublereal toolwd[5]
Definition at line 58 of file APT238.c.
doublereal tp[15]
Definition at line 58 of file APT238.c.
doublereal tpk[15]
Definition at line 58 of file APT238.c.
doublereal u1[15]
Definition at line 58 of file APT238.c.
doublereal u1k[15]
Definition at line 58 of file APT238.c.
doublereal u2[3]
Definition at line 18 of file APT238.c.
doublereal umax[8]
Definition at line 43 of file APT238.c.
doublereal unn
Definition at line 18 of file APT238.c.
doublereal upp
Definition at line 18 of file APT238.c.
doublereal uvec[3]
Definition at line 18 of file APT238.c.
doublereal v[3]
Definition at line 18 of file APT238.c.
doublereal varble[5]
Definition at line 58 of file APT238.c.
doublereal vint
Definition at line 18 of file APT238.c.
doublereal vl
Definition at line 18 of file APT238.c.
doublereal vndir[15]
Definition at line 58 of file APT238.c.
doublereal vnn
Definition at line 18 of file APT238.c.
doublereal vpp
Definition at line 18 of file APT238.c.
doublereal vt[15]
Definition at line 58 of file APT238.c.
doublereal vtem
Definition at line 28 of file APT238.c.
doublereal z__[5]
Definition at line 58 of file APT238.c.
doublereal zl
Definition at line 18 of file APT238.c.
doublereal zl1
Definition at line 18 of file APT238.c.
doublereal zlnorm[3]
Definition at line 18 of file APT238.c.
doublereal zlpnt[3]
Definition at line 18 of file APT238.c.