My Project: APT234.c File Reference
APT234.c File Reference
#include "f2c.h"
Macros
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define hblock_1 hblock_
#define sv_1 sv_
#define sv1_1 sv1_
#define ldef_1 ldef_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define _BLNK__1 _BLNK__
#define can ((doublereal *)&_BLNK__1 + 40)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int apt234_ (doublereal *hmod, doublereal *adress)
Variables
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
char hps [8]
char hds [8]
char hcs [8]
char hlft [8]
char hrgt [8]
char hfwd [8]
char hback [8]
char hup [8]
char hdown [8]
char hto [8]
char hpast [8]
char hon [8]
char htanto [8]
char hpstan [8]
char hdynp [8]
char haerr [8]
char hcldat [8]
char hgerr [8]
} hblock_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
doublereal com [36000]
} _BLNK__
static integer c__1 = 1
static integer c__8 = 8
static integer c__0 = 0
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 126 of file APT234.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
Referenced by apt234_().
#define charct_1 charct_
Definition at line 30 of file APT234.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define fxcor_1 fxcor_
Definition at line 24 of file APT234.c.
#define hblock_1 hblock_
Definition at line 45 of file APT234.c.
Referenced by apt234_().
#define ifxcor_1 ifxcor_
Definition at line 104 of file APT234.c.
Referenced by apt234_().
#define ishr18_1 ishr18_
Definition at line 112 of file APT234.c.
#define isv1_1 isv1_
Definition at line 94 of file APT234.c.
#define isv_1 isv_
Definition at line 87 of file APT234.c.
Referenced by apt234_().
#define knumbr_1 knumbr_
Definition at line 120 of file APT234.c.
Referenced by apt234_().
#define ldef_1 ldef_
Definition at line 78 of file APT234.c.
Referenced by apt234_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define sv1_1 sv1_
Definition at line 71 of file APT234.c.
#define sv_1 sv_
Definition at line 62 of file APT234.c.
Referenced by apt234_().
#define tlldat_1 tlldat_
Definition at line 37 of file APT234.c.
Function Documentation
int apt234_ (doublereal * hmod, doublereal * adress)
Definition at line 138 of file APT234.c.
References apt202_(), c__0, c__1, c__8, canon, ckdef_(), hblock_1, holfrm_(), i__, ifxcor_1, ir, isv_1, j, k, knumbr_1, l, ldef_1, sv_1, test, transm_(), and unpack_().
Referenced by apt200_(), apt211_(), go2_(), golovo_(), intsec_(), and psis_().
 {
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, j, k, l, ir;
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer nwd, kis;
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static char test[8];
     extern /* Subroutine */ int apt202_(doublereal *, integer *);
     extern logical ckdef_(doublereal *);
 #define canon ((doublereal *)&_BLNK__1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int holfrm_(doublereal *, char *, integer *,
         integer *, integer *, ftnlen);
     static integer isrflg;
     extern /* Subroutine */ int unpack_(doublereal *, integer *, integer *,
         integer *), transm_(doublereal *, doublereal *, integer *,
         integer *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*     *** 8.  HOLRTH BLOCK *** */
 /*     ALPHA-NUMERIC LITERAL CONSTANTS. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /* ...  ESTABLISHES SURFACE PARAMETERS FOR PS,DS,CS AND CALCULATES THE */
 /* ...  INDEX OF CANON FOR THE CANONICAL INFORMATION STORAGE */
 /* ...  CALLED BY SUBPROGRAMS - APT200,APT201,GO,PSIS */
     /* Parameter adjustments */
     --adress;
     /* Function Body */
     if (ifxcor_1.iaerr != 0) {
     goto L900;
     }
     if (ckdef_(&adress[1])) {
     goto L900;
     }
 /* ...  PRE-SET SURFACE CONDITION FLAGS */
     isv_1.ipl[ifxcor_1.is - 1] = 0;
     isv_1.limfl[ifxcor_1.is - 1] = 0;
     isv_1.iunfl[ifxcor_1.is - 1] = 0;
     sv_1.past[ifxcor_1.is - 1] = (doublereal) knumbr_1.k1;
     isv_1.jent[ifxcor_1.is - 1] = 1;
 /* ...  SET ISFTYP BASED ON HOLERITH CONTENTS OF HMOD */
     holfrm_(hmod, test, &c__1, &c__8, &nwd, (ftnlen)8);
     if (s_cmp(test, hblock_1.hds, (ftnlen)8, (ftnlen)8) == 0) {
     goto L10;
     }
     isv_1.isftyp[ifxcor_1.is - 1] = knumbr_1.k1;
     if (s_cmp(test, hblock_1.hto, (ftnlen)8, (ftnlen)8) == 0) {
     goto L10;
     }
     isv_1.isftyp[ifxcor_1.is - 1] = knumbr_1.k2;
     if (s_cmp(test, hblock_1.hpast, (ftnlen)8, (ftnlen)8) == 0) {
     goto L60;
     }
     isv_1.isftyp[ifxcor_1.is - 1] = knumbr_1.k3;
     if (s_cmp(test, hblock_1.hon, (ftnlen)8, (ftnlen)8) == 0) {
     goto L10;
     }
     isv_1.isftyp[ifxcor_1.is - 1] = knumbr_1.k4;
     if (s_cmp(test, hblock_1.htanto, (ftnlen)8, (ftnlen)8) == 0) {
     goto L10;
     }
     isv_1.isftyp[ifxcor_1.is - 1] = knumbr_1.k8;
     if (s_cmp(test, hblock_1.hpstan, (ftnlen)8, (ftnlen)8) == 0) {
     goto L10;
     }
     isv_1.isftyp[ifxcor_1.is - 1] = knumbr_1.k1;
 /* ...  SET SURFACE TYPE CODE IN ISFIDN */
 L10:
     isrflg = ifxcor_1.is / ifxcor_1.lsv - 1;
     apt202_(&adress[1], &isrflg);
     unpack_(&adress[1], &isv_1.isfidn[ifxcor_1.is - 1], &j, &k);
     l = (ifxcor_1.is - knumbr_1.k2) * knumbr_1.k10 + knumbr_1.k1;
     isv_1.icanon[ifxcor_1.is - 1] = l;
     if (! ldef_1.refflg && ! ldef_1.refmot) {
     goto L88;
     }
     kis = isv_1.isfidn[ifxcor_1.is - 1];
     if (kis <= 0 || kis > 20) {
     goto L88;
     }
     switch (kis) {
     case 1:  goto L82;
     case 2:  goto L82;
     case 3:  goto L83;
     case 4:  goto L83;
     case 5:  goto L84;
     case 6:  goto L85;
     case 7:  goto L85;
     case 8:  goto L85;
     case 9:  goto L83;
     case 10:  goto L85;
     case 11:  goto L88;
     case 12:  goto L88;
     case 13:  goto L88;
     case 14:  goto L85;
     case 15:  goto L88;
     case 16:  goto L88;
     case 17:  goto L88;
     case 18:  goto L88;
     case 19:  goto L84;
     case 20:  goto L86;
     }
     goto L88;
 L82:
     ir = 4;
     goto L87;
 L83:
     ir = 5;
     goto L87;
 L84:
     ir = 2;
     goto L87;
 L85:
     ir = 1;
     goto L87;
 L86:
     ir = 3;
 L87:
     transm_(&canon[l - 1], &adress[1], &ir, &j, &c__0);
     goto L13;
 L88:
     i__1 = j;
     for (i__ = 1; i__ <= i__1; ++i__) {
     canon[l - 1] = adress[i__];
 /* L12: */
     ++l;
     }
 L13:
     if ((i__1 = isv_1.isfidn[ifxcor_1.is - 1] - knumbr_1.k3) < 0) {
     goto L50;
     } else if (i__1 == 0) {
     goto L55;
     } else {
     goto L20;
     }
 L20:
     if (isv_1.isfidn[ifxcor_1.is - 1] - knumbr_1.k5 <= 0) {
     goto L55;
     } else {
     goto L30;
     }
 L30:
     if (isv_1.isfidn[ifxcor_1.is - 1] == 9) {
     goto L55;
     }
     if (isv_1.isfidn[ifxcor_1.is - 1] == 29 || isv_1.isfidn[ifxcor_1.is - 1]
         == 30) {
     goto L1000;
     }
     goto L1000;
 L50:
     isv_1.ipl[ifxcor_1.is - 1] = knumbr_1.k1;
 /* ...  SET IUNFL=1 IF UN CAN BE CALCULATED USING AN OFF SURFACE POINT, */
 /* ...  SET TO 0 OTHERWISE */
 L55:
     isv_1.iunfl[ifxcor_1.is - 1] = knumbr_1.k1;
 L1000:
     return 0;
 /* ...  SET PAST=-1 IF A CONDITION OF PAST EXISTS, -1 OTHERWISE */
 L60:
     sv_1.past[ifxcor_1.is - 1] = (doublereal) (-knumbr_1.k1);
     goto L10;
 /*     SURFACE NOT CORRECTLY DEFINED */
 L900:
     ifxcor_1.iaerr = 1;
     goto L1000;
 } /* apt234_ */
Variable Documentation
struct { ... } _BLNK__
doublereal alp
Definition at line 18 of file APT234.c.
logical altmlt
Definition at line 74 of file APT234.c.
doublereal ax4[3]
Definition at line 18 of file APT234.c.
logical bnderr
Definition at line 74 of file APT234.c.
logical boundf
Definition at line 74 of file APT234.c.
integer c__0 = 0 static
Definition at line 132 of file APT234.c.
Referenced by apt234_().
integer c__1 = 1 static
Definition at line 130 of file APT234.c.
Referenced by apt234_().
integer c__8 = 8 static
Definition at line 131 of file APT234.c.
Referenced by apt234_().
doublereal cagl
Definition at line 18 of file APT234.c.
logical canflg
Definition at line 74 of file APT234.c.
doublereal cc[15]
Definition at line 48 of file APT234.c.
struct { ... } charct_
doublereal com[36000]
Definition at line 123 of file APT234.c.
doublereal corrad[8]
Definition at line 33 of file APT234.c.
doublereal cos1[5]
Definition at line 65 of file APT234.c.
doublereal cplfl[5]
Definition at line 65 of file APT234.c.
doublereal cptst[5]
Definition at line 65 of file APT234.c.
doublereal csd[5]
Definition at line 65 of file APT234.c.
doublereal cutdat[7]
Definition at line 18 of file APT234.c.
doublereal dplan[15]
Definition at line 65 of file APT234.c.
doublereal dpmax
Definition at line 18 of file APT234.c.
doublereal dpmx1[5]
Definition at line 65 of file APT234.c.
doublereal eps1[5]
Definition at line 48 of file APT234.c.
doublereal eps2[5]
Definition at line 48 of file APT234.c.
doublereal eps3[5]
Definition at line 48 of file APT234.c.
doublereal eps4[5]
Definition at line 48 of file APT234.c.
doublereal eps6[5]
Definition at line 48 of file APT234.c.
doublereal eps8[5]
Definition at line 48 of file APT234.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 18 of file APT234.c.
char haerr[8]
Definition at line 40 of file APT234.c.
char hback[8]
Definition at line 40 of file APT234.c.
struct { ... } hblock_
char hcldat[8]
Definition at line 40 of file APT234.c.
char hcs[8]
Definition at line 40 of file APT234.c.
char hdown[8]
Definition at line 40 of file APT234.c.
char hds[8]
Definition at line 40 of file APT234.c.
char hdynp[8]
Definition at line 40 of file APT234.c.
char hfwd[8]
Definition at line 40 of file APT234.c.
char hgerr[8]
Definition at line 40 of file APT234.c.
doublereal hi
Definition at line 18 of file APT234.c.
char hlft[8]
Definition at line 40 of file APT234.c.
char hon[8]
Definition at line 40 of file APT234.c.
char hpast[8]
Definition at line 40 of file APT234.c.
char hps[8]
Definition at line 40 of file APT234.c.
char hpstan[8]
Definition at line 40 of file APT234.c.
char hrgt[8]
Definition at line 40 of file APT234.c.
char htanto[8]
Definition at line 40 of file APT234.c.
char hto[8]
Definition at line 40 of file APT234.c.
char hup[8]
Definition at line 40 of file APT234.c.
integer i3dflg
Definition at line 97 of file APT234.c.
integer iaerr
Definition at line 97 of file APT234.c.
integer iafl[5]
Definition at line 81 of file APT234.c.
integer iamdct
Definition at line 107 of file APT234.c.
integer iautps
Definition at line 97 of file APT234.c.
integer ibegin
Definition at line 97 of file APT234.c.
integer ic
Definition at line 97 of file APT234.c.
integer icanon[5]
Definition at line 81 of file APT234.c.
integer icheck
Definition at line 97 of file APT234.c.
integer icl
Definition at line 97 of file APT234.c.
integer ics
Definition at line 97 of file APT234.c.
integer icscnt
Definition at line 97 of file APT234.c.
integer ictdef
Definition at line 97 of file APT234.c.
integer icut
Definition at line 97 of file APT234.c.
integer ids
Definition at line 97 of file APT234.c.
integer ier
Definition at line 97 of file APT234.c.
integer ifar[5]
Definition at line 90 of file APT234.c.
integer ifl4[5]
Definition at line 90 of file APT234.c.
struct { ... } ifxcor_
integer igo
Definition at line 97 of file APT234.c.
integer igoto
Definition at line 97 of file APT234.c.
integer igoug
Definition at line 97 of file APT234.c.
integer igs
Definition at line 97 of file APT234.c.
integer index[5]
Definition at line 81 of file APT234.c.
integer indir__[5]
Definition at line 81 of file APT234.c.
integer inops
Definition at line 97 of file APT234.c.
integer iop[5]
Definition at line 81 of file APT234.c.
integer iopset[5]
Definition at line 81 of file APT234.c.
integer ipdpl
Definition at line 107 of file APT234.c.
integer ipl[5]
Definition at line 81 of file APT234.c.
integer ips
Definition at line 97 of file APT234.c.
integer ipsdef
Definition at line 97 of file APT234.c.
integer ipt
Definition at line 107 of file APT234.c.
integer ipt1
Definition at line 97 of file APT234.c.
integer is
Definition at line 97 of file APT234.c.
integer iseg
Definition at line 97 of file APT234.c.
integer iseqno
Definition at line 97 of file APT234.c.
integer isfidn[5]
Definition at line 81 of file APT234.c.
integer isftyp[5]
Definition at line 81 of file APT234.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 81 of file APT234.c.
integer isrch
Definition at line 97 of file APT234.c.
integer istrup
Definition at line 97 of file APT234.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 81 of file APT234.c.
integer it
Definition at line 97 of file APT234.c.
integer itlon[5]
Definition at line 81 of file APT234.c.
integer itseg[5]
Definition at line 81 of file APT234.c.
integer itsegk[5]
Definition at line 81 of file APT234.c.
integer iunfl[5]
Definition at line 81 of file APT234.c.
integer iws
Definition at line 107 of file APT234.c.
integer j10
Definition at line 107 of file APT234.c.
integer j12
Definition at line 107 of file APT234.c.
integer j13
Definition at line 107 of file APT234.c.
integer j20[5]
Definition at line 90 of file APT234.c.
integer j21[5]
Definition at line 90 of file APT234.c.
integer j22[5]
Definition at line 90 of file APT234.c.
integer j23[5]
Definition at line 90 of file APT234.c.
integer j50[5]
Definition at line 90 of file APT234.c.
integer j51[5]
Definition at line 90 of file APT234.c.
integer j54
Definition at line 107 of file APT234.c.
integer jbr
Definition at line 97 of file APT234.c.
integer jckr
Definition at line 107 of file APT234.c.
integer jcnt1
Definition at line 107 of file APT234.c.
integer jcnt2
Definition at line 107 of file APT234.c.
integer jcnt3
Definition at line 107 of file APT234.c.
integer jcpr
Definition at line 107 of file APT234.c.
integer jcr
Definition at line 107 of file APT234.c.
logical jcs
Definition at line 74 of file APT234.c.
integer jdr
Definition at line 107 of file APT234.c.
logical jds
Definition at line 74 of file APT234.c.
integer jent[5]
Definition at line 81 of file APT234.c.
integer jfind
Definition at line 107 of file APT234.c.
integer jgr
Definition at line 107 of file APT234.c.
integer jiops[5]
Definition at line 81 of file APT234.c.
integer jmin
Definition at line 107 of file APT234.c.
integer jminr
Definition at line 107 of file APT234.c.
integer jph[5]
Definition at line 90 of file APT234.c.
integer jpr
Definition at line 107 of file APT234.c.
integer jpxr
Definition at line 107 of file APT234.c.
integer jsw
Definition at line 97 of file APT234.c.
integer jtkf
Definition at line 107 of file APT234.c.
integer jtlflg[5]
Definition at line 81 of file APT234.c.
integer jtn[5]
Definition at line 81 of file APT234.c.
integer jtr
Definition at line 107 of file APT234.c.
integer ju1[5]
Definition at line 81 of file APT234.c.
integer k0
Definition at line 115 of file APT234.c.
integer k1
Definition at line 115 of file APT234.c.
integer k10
Definition at line 115 of file APT234.c.
integer k1013
Definition at line 115 of file APT234.c.
integer k12
Definition at line 115 of file APT234.c.
integer k13
Definition at line 115 of file APT234.c.
integer k15
Definition at line 115 of file APT234.c.
integer k16
Definition at line 115 of file APT234.c.
integer k18
Definition at line 115 of file APT234.c.
integer k19
Definition at line 115 of file APT234.c.
integer k1e4
Definition at line 115 of file APT234.c.
integer k1e6
Definition at line 115 of file APT234.c.
integer k2
Definition at line 115 of file APT234.c.
integer k23
Definition at line 115 of file APT234.c.
integer k24
Definition at line 115 of file APT234.c.
integer k25
Definition at line 115 of file APT234.c.
integer k26
Definition at line 115 of file APT234.c.
integer k27
Definition at line 115 of file APT234.c.
integer k29
Definition at line 115 of file APT234.c.
integer k3
Definition at line 115 of file APT234.c.
integer k30
Definition at line 115 of file APT234.c.
integer k31
Definition at line 115 of file APT234.c.
integer k32
Definition at line 115 of file APT234.c.
integer k33
Definition at line 115 of file APT234.c.
integer k34
Definition at line 115 of file APT234.c.
integer k4
Definition at line 115 of file APT234.c.
integer k44
Definition at line 115 of file APT234.c.
integer k45
Definition at line 115 of file APT234.c.
integer k46
Definition at line 115 of file APT234.c.
integer k47
Definition at line 115 of file APT234.c.
integer k48
Definition at line 115 of file APT234.c.
integer k5
Definition at line 115 of file APT234.c.
integer k50
Definition at line 115 of file APT234.c.
integer k51
Definition at line 115 of file APT234.c.
integer k52
Definition at line 115 of file APT234.c.
integer k6
Definition at line 115 of file APT234.c.
integer k7
Definition at line 115 of file APT234.c.
integer k8
Definition at line 115 of file APT234.c.
integer k9
Definition at line 115 of file APT234.c.
integer km1
Definition at line 115 of file APT234.c.
struct { ... } knumbr_
struct { ... } ldef_
integer limfl[5]
Definition at line 81 of file APT234.c.
integer lsv
Definition at line 97 of file APT234.c.
integer lsv1
Definition at line 97 of file APT234.c.
integer mantax
Definition at line 97 of file APT234.c.
integer mdic
Definition at line 107 of file APT234.c.
char modfer[6]
Definition at line 27 of file APT234.c.
integer motmod
Definition at line 97 of file APT234.c.
integer msav
Definition at line 97 of file APT234.c.
integer mulout
Definition at line 97 of file APT234.c.
integer nmbseg
Definition at line 97 of file APT234.c.
integer nmpnts
Definition at line 97 of file APT234.c.
integer notan[5]
Definition at line 90 of file APT234.c.
integer nrec
Definition at line 97 of file APT234.c.
integer numax
Definition at line 97 of file APT234.c.
integer numcnt
Definition at line 97 of file APT234.c.
integer nump
Definition at line 97 of file APT234.c.
integer numpt1
Definition at line 97 of file APT234.c.
integer numsfs
Definition at line 97 of file APT234.c.
integer numsur
Definition at line 97 of file APT234.c.
integer nw
Definition at line 97 of file APT234.c.
integer nwds
Definition at line 97 of file APT234.c.
doublereal past[5]
Definition at line 48 of file APT234.c.
logical pchlst
Definition at line 74 of file APT234.c.
doublereal plncs[5]
Definition at line 65 of file APT234.c.
doublereal plnd[5]
Definition at line 48 of file APT234.c.
doublereal plnd1[5]
Definition at line 65 of file APT234.c.
doublereal plnv[15]
Definition at line 48 of file APT234.c.
doublereal pltst[5]
Definition at line 65 of file APT234.c.
doublereal pmove[3]
Definition at line 18 of file APT234.c.
logical prnton
Definition at line 74 of file APT234.c.
doublereal ra
Definition at line 18 of file APT234.c.
doublereal rc[5]
Definition at line 48 of file APT234.c.
doublereal rc1
Definition at line 18 of file APT234.c.
logical refflg
Definition at line 74 of file APT234.c.
logical refmot
Definition at line 74 of file APT234.c.
doublereal ri[8]
Definition at line 33 of file APT234.c.
doublereal s[5]
Definition at line 48 of file APT234.c.
doublereal sagl
Definition at line 18 of file APT234.c.
doublereal save[5]
Definition at line 48 of file APT234.c.
doublereal sfvct[15]
Definition at line 48 of file APT234.c.
doublereal sk[15]
Definition at line 48 of file APT234.c.
doublereal slx[15]
Definition at line 48 of file APT234.c.
doublereal sn[15]
Definition at line 48 of file APT234.c.
doublereal snk[15]
Definition at line 48 of file APT234.c.
doublereal snl[15]
Definition at line 48 of file APT234.c.
doublereal sp[15]
Definition at line 48 of file APT234.c.
doublereal spk[15]
Definition at line 48 of file APT234.c.
doublereal spl[15]
Definition at line 48 of file APT234.c.
doublereal stck[5]
Definition at line 65 of file APT234.c.
doublereal stck1[5]
Definition at line 65 of file APT234.c.
doublereal stck2[5]
Definition at line 65 of file APT234.c.
doublereal stckn[5]
Definition at line 65 of file APT234.c.
doublereal strtno
Definition at line 18 of file APT234.c.
logical subflg
Definition at line 74 of file APT234.c.
doublereal surd
Definition at line 18 of file APT234.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 18 of file APT234.c.
logical tabprt
Definition at line 74 of file APT234.c.
doublereal tak[3]
Definition at line 18 of file APT234.c.
doublereal tal[3]
Definition at line 18 of file APT234.c.
doublereal tanhi[8]
Definition at line 33 of file APT234.c.
doublereal tanlo[8]
Definition at line 33 of file APT234.c.
doublereal tau[5]
Definition at line 48 of file APT234.c.
doublereal tau1[5]
Definition at line 48 of file APT234.c.
doublereal tau2[5]
Definition at line 48 of file APT234.c.
doublereal tcont[9]
Definition at line 33 of file APT234.c.
doublereal te[3]
Definition at line 18 of file APT234.c.
doublereal tee[15]
Definition at line 65 of file APT234.c.
doublereal tek[3]
Definition at line 18 of file APT234.c.
doublereal tel[3]
Definition at line 18 of file APT234.c.
doublereal tem[10]
Definition at line 18 of file APT234.c.
doublereal temp[24]
Definition at line 18 of file APT234.c.
doublereal th[5]
Definition at line 48 of file APT234.c.
doublereal ti[3]
Definition at line 18 of file APT234.c.
doublereal tik[3]
Definition at line 18 of file APT234.c.
doublereal til[3]
Definition at line 18 of file APT234.c.
doublereal tlhit
Definition at line 18 of file APT234.c.
doublereal tlhite[8]
Definition at line 33 of file APT234.c.
doublereal tlinc[9]
Definition at line 33 of file APT234.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 18 of file APT234.c.
doublereal tn[15]
Definition at line 48 of file APT234.c.
doublereal tnl[15]
Definition at line 65 of file APT234.c.
doublereal toolht[15]
Definition at line 48 of file APT234.c.
doublereal toolwd[5]
Definition at line 48 of file APT234.c.
doublereal tp[15]
Definition at line 48 of file APT234.c.
doublereal tpk[15]
Definition at line 48 of file APT234.c.
doublereal u1[15]
Definition at line 48 of file APT234.c.
doublereal u1k[15]
Definition at line 48 of file APT234.c.
doublereal umax[8]
Definition at line 33 of file APT234.c.
logical unflag
Definition at line 74 of file APT234.c.
doublereal varble[5]
Definition at line 48 of file APT234.c.
doublereal vndir[15]
Definition at line 48 of file APT234.c.
doublereal vt[15]
Definition at line 48 of file APT234.c.
doublereal vtem
Definition at line 18 of file APT234.c.
doublereal z__[5]
Definition at line 48 of file APT234.c.
logical zflag
Definition at line 74 of file APT234.c.