My Project: APT232.c File Reference
APT232.c File Reference
#include "f2c.h"
Macros
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
Functions
int apt232_ (integer *number, doublereal *tolrns, doublereal *taus, doublereal *one)
Variables
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
Macro Definition Documentation
#define ifxcor_1 ifxcor_
Definition at line 75 of file APT232.c.
Referenced by apt232_().
#define ishr18_1 ishr18_
Definition at line 83 of file APT232.c.
#define isv1_1 isv1_
Definition at line 65 of file APT232.c.
#define isv_1 isv_
Definition at line 58 of file APT232.c.
Referenced by apt232_().
#define knumbr_1 knumbr_
Definition at line 91 of file APT232.c.
Referenced by apt232_().
#define sv1_1 sv1_
Definition at line 41 of file APT232.c.
#define sv_1 sv_
Definition at line 32 of file APT232.c.
Referenced by apt232_().
#define znumbr_1 znumbr_
Definition at line 49 of file APT232.c.
Referenced by apt232_().
Function Documentation
int apt232_ (integer * number, doublereal * tolrns, doublereal * taus, doublereal * one)
Definition at line 96 of file APT232.c.
References i__, ifxcor_1, isv_1, knumbr_1, sv_1, tolrns, and znumbr_1.
Referenced by intol_(), intolh_(), outtoh_(), outtol_(), toler_(), and tolerh_().
 {
     /* Initialized data */
     static doublereal zlit1 = .02;
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --taus;
     --tolrns;
     /* Function Body */
 /*      DIMENSION TOLRNS(4),TAUS(1) */
     ifxcor_1.is = ifxcor_1.ips;
     i__1 = ifxcor_1.numsfs;
     for (i__ = 1; i__ <= i__1; ++i__) {
 L10:
     taus[ifxcor_1.is] = *one * tolrns[i__];
     sv_1.tau[ifxcor_1.is - 1] = sv_1.tau1[ifxcor_1.is - 1] - sv_1.tau2[
         ifxcor_1.is - 1];
     sv_1.eps1[ifxcor_1.is - 1] = znumbr_1.z1em1 * sv_1.tau[ifxcor_1.is -
         1];
     sv_1.eps2[ifxcor_1.is - 1] = znumbr_1.z1 - sv_1.eps1[ifxcor_1.is - 1];
     sv_1.eps3[ifxcor_1.is - 1] = znumbr_1.z2 * sv_1.eps1[ifxcor_1.is - 1];
     sv_1.eps4[ifxcor_1.is - 1] = znumbr_1.z2 * sv_1.tau[ifxcor_1.is - 1];
     sv_1.eps6[ifxcor_1.is - 1] = zlit1 * sv_1.eps1[ifxcor_1.is - 1];
     sv_1.eps8[ifxcor_1.is - 1] = sv_1.eps1[ifxcor_1.is - 1];
     if (ifxcor_1.is - ifxcor_1.ics >= 0) {
         goto L30;
     } else {
         goto L20;
     }
 L20:
     ifxcor_1.is += ifxcor_1.lsv;
     if (*number - i__ <= 0) {
         goto L10;
     } else {
         goto L50;
     }
 L30:
     if (i__ - *number >= 0) {
         goto L60;
     } else {
         goto L40;
     }
 L40:
     ifxcor_1.is += ifxcor_1.lsv1;
 L50:
     ;
     }
 L60:
     isv_1.jent[ifxcor_1.ips - 1] = knumbr_1.k1;
     isv_1.jent[ifxcor_1.ids - 1] = knumbr_1.k1;
     return 0;
 } /* apt232_ */
Variable Documentation
doublereal cc[15]
Definition at line 18 of file APT232.c.
doublereal cos1[5]
Definition at line 35 of file APT232.c.
doublereal cplfl[5]
Definition at line 35 of file APT232.c.
doublereal cptst[5]
Definition at line 35 of file APT232.c.
doublereal csd[5]
Definition at line 35 of file APT232.c.
doublereal degrad
Definition at line 44 of file APT232.c.
doublereal dplan[15]
Definition at line 35 of file APT232.c.
doublereal dpmx1[5]
Definition at line 35 of file APT232.c.
doublereal eps1[5]
Definition at line 18 of file APT232.c.
doublereal eps2[5]
Definition at line 18 of file APT232.c.
doublereal eps3[5]
Definition at line 18 of file APT232.c.
doublereal eps4[5]
Definition at line 18 of file APT232.c.
doublereal eps6[5]
Definition at line 18 of file APT232.c.
doublereal eps8[5]
Definition at line 18 of file APT232.c.
integer i3dflg
Definition at line 68 of file APT232.c.
integer iaerr
Definition at line 68 of file APT232.c.
integer iafl[5]
Definition at line 52 of file APT232.c.
integer iamdct
Definition at line 78 of file APT232.c.
integer iautps
Definition at line 68 of file APT232.c.
integer ibegin
Definition at line 68 of file APT232.c.
integer ic
Definition at line 68 of file APT232.c.
integer icanon[5]
Definition at line 52 of file APT232.c.
integer icheck
Definition at line 68 of file APT232.c.
integer icl
Definition at line 68 of file APT232.c.
integer ics
Definition at line 68 of file APT232.c.
integer icscnt
Definition at line 68 of file APT232.c.
integer ictdef
Definition at line 68 of file APT232.c.
integer icut
Definition at line 68 of file APT232.c.
integer ids
Definition at line 68 of file APT232.c.
integer ier
Definition at line 68 of file APT232.c.
integer ifar[5]
Definition at line 61 of file APT232.c.
integer ifl4[5]
Definition at line 61 of file APT232.c.
struct { ... } ifxcor_
integer igo
Definition at line 68 of file APT232.c.
integer igoto
Definition at line 68 of file APT232.c.
integer igoug
Definition at line 68 of file APT232.c.
integer igs
Definition at line 68 of file APT232.c.
integer index[5]
Definition at line 52 of file APT232.c.
integer indir__[5]
Definition at line 52 of file APT232.c.
integer inops
Definition at line 68 of file APT232.c.
integer iop[5]
Definition at line 52 of file APT232.c.
integer iopset[5]
Definition at line 52 of file APT232.c.
integer ipdpl
Definition at line 78 of file APT232.c.
integer ipl[5]
Definition at line 52 of file APT232.c.
integer ips
Definition at line 68 of file APT232.c.
integer ipsdef
Definition at line 68 of file APT232.c.
integer ipt
Definition at line 78 of file APT232.c.
integer ipt1
Definition at line 68 of file APT232.c.
integer is
Definition at line 68 of file APT232.c.
integer iseg
Definition at line 68 of file APT232.c.
integer iseqno
Definition at line 68 of file APT232.c.
integer isfidn[5]
Definition at line 52 of file APT232.c.
integer isftyp[5]
Definition at line 52 of file APT232.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 52 of file APT232.c.
integer isrch
Definition at line 68 of file APT232.c.
integer istrup
Definition at line 68 of file APT232.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 52 of file APT232.c.
integer it
Definition at line 68 of file APT232.c.
integer itlon[5]
Definition at line 52 of file APT232.c.
integer itseg[5]
Definition at line 52 of file APT232.c.
integer itsegk[5]
Definition at line 52 of file APT232.c.
integer iunfl[5]
Definition at line 52 of file APT232.c.
integer iws
Definition at line 78 of file APT232.c.
integer j10
Definition at line 78 of file APT232.c.
integer j12
Definition at line 78 of file APT232.c.
integer j13
Definition at line 78 of file APT232.c.
integer j20[5]
Definition at line 61 of file APT232.c.
integer j21[5]
Definition at line 61 of file APT232.c.
integer j22[5]
Definition at line 61 of file APT232.c.
integer j23[5]
Definition at line 61 of file APT232.c.
integer j50[5]
Definition at line 61 of file APT232.c.
integer j51[5]
Definition at line 61 of file APT232.c.
integer j54
Definition at line 78 of file APT232.c.
integer jbr
Definition at line 68 of file APT232.c.
integer jckr
Definition at line 78 of file APT232.c.
integer jcnt1
Definition at line 78 of file APT232.c.
integer jcnt2
Definition at line 78 of file APT232.c.
integer jcnt3
Definition at line 78 of file APT232.c.
integer jcpr
Definition at line 78 of file APT232.c.
integer jcr
Definition at line 78 of file APT232.c.
integer jdr
Definition at line 78 of file APT232.c.
integer jent[5]
Definition at line 52 of file APT232.c.
integer jfind
Definition at line 78 of file APT232.c.
integer jgr
Definition at line 78 of file APT232.c.
integer jiops[5]
Definition at line 52 of file APT232.c.
integer jmin
Definition at line 78 of file APT232.c.
integer jminr
Definition at line 78 of file APT232.c.
integer jph[5]
Definition at line 61 of file APT232.c.
integer jpr
Definition at line 78 of file APT232.c.
integer jpxr
Definition at line 78 of file APT232.c.
integer jsw
Definition at line 68 of file APT232.c.
integer jtkf
Definition at line 78 of file APT232.c.
integer jtlflg[5]
Definition at line 52 of file APT232.c.
integer jtn[5]
Definition at line 52 of file APT232.c.
integer jtr
Definition at line 78 of file APT232.c.
integer ju1[5]
Definition at line 52 of file APT232.c.
integer k0
Definition at line 86 of file APT232.c.
integer k1
Definition at line 86 of file APT232.c.
integer k10
Definition at line 86 of file APT232.c.
integer k1013
Definition at line 86 of file APT232.c.
integer k12
Definition at line 86 of file APT232.c.
integer k13
Definition at line 86 of file APT232.c.
integer k15
Definition at line 86 of file APT232.c.
integer k16
Definition at line 86 of file APT232.c.
integer k18
Definition at line 86 of file APT232.c.
integer k19
Definition at line 86 of file APT232.c.
integer k1e4
Definition at line 86 of file APT232.c.
integer k1e6
Definition at line 86 of file APT232.c.
integer k2
Definition at line 86 of file APT232.c.
integer k23
Definition at line 86 of file APT232.c.
integer k24
Definition at line 86 of file APT232.c.
integer k25
Definition at line 86 of file APT232.c.
integer k26
Definition at line 86 of file APT232.c.
integer k27
Definition at line 86 of file APT232.c.
integer k29
Definition at line 86 of file APT232.c.
integer k3
Definition at line 86 of file APT232.c.
integer k30
Definition at line 86 of file APT232.c.
integer k31
Definition at line 86 of file APT232.c.
integer k32
Definition at line 86 of file APT232.c.
integer k33
Definition at line 86 of file APT232.c.
integer k34
Definition at line 86 of file APT232.c.
integer k4
Definition at line 86 of file APT232.c.
integer k44
Definition at line 86 of file APT232.c.
integer k45
Definition at line 86 of file APT232.c.
integer k46
Definition at line 86 of file APT232.c.
integer k47
Definition at line 86 of file APT232.c.
integer k48
Definition at line 86 of file APT232.c.
integer k5
Definition at line 86 of file APT232.c.
integer k50
Definition at line 86 of file APT232.c.
integer k51
Definition at line 86 of file APT232.c.
integer k52
Definition at line 86 of file APT232.c.
integer k6
Definition at line 86 of file APT232.c.
integer k7
Definition at line 86 of file APT232.c.
integer k8
Definition at line 86 of file APT232.c.
integer k9
Definition at line 86 of file APT232.c.
integer km1
Definition at line 86 of file APT232.c.
struct { ... } knumbr_
integer limfl[5]
Definition at line 52 of file APT232.c.
integer lsv
Definition at line 68 of file APT232.c.
integer lsv1
Definition at line 68 of file APT232.c.
integer mantax
Definition at line 68 of file APT232.c.
integer mdic
Definition at line 78 of file APT232.c.
integer motmod
Definition at line 68 of file APT232.c.
integer msav
Definition at line 68 of file APT232.c.
integer mulout
Definition at line 68 of file APT232.c.
integer nmbseg
Definition at line 68 of file APT232.c.
integer nmpnts
Definition at line 68 of file APT232.c.
integer notan[5]
Definition at line 61 of file APT232.c.
integer nrec
Definition at line 68 of file APT232.c.
integer numax
Definition at line 68 of file APT232.c.
integer numcnt
Definition at line 68 of file APT232.c.
integer nump
Definition at line 68 of file APT232.c.
integer numpt1
Definition at line 68 of file APT232.c.
integer numsfs
Definition at line 68 of file APT232.c.
integer numsur
Definition at line 68 of file APT232.c.
integer nw
Definition at line 68 of file APT232.c.
integer nwds
Definition at line 68 of file APT232.c.
doublereal past[5]
Definition at line 18 of file APT232.c.
doublereal pi
Definition at line 44 of file APT232.c.
doublereal plncs[5]
Definition at line 35 of file APT232.c.
doublereal plnd[5]
Definition at line 18 of file APT232.c.
doublereal plnd1[5]
Definition at line 35 of file APT232.c.
doublereal plnv[15]
Definition at line 18 of file APT232.c.
doublereal pltst[5]
Definition at line 35 of file APT232.c.
doublereal rc[5]
Definition at line 18 of file APT232.c.
doublereal s[5]
Definition at line 18 of file APT232.c.
doublereal save[5]
Definition at line 18 of file APT232.c.
doublereal sfvct[15]
Definition at line 18 of file APT232.c.
doublereal sk[15]
Definition at line 18 of file APT232.c.
doublereal slx[15]
Definition at line 18 of file APT232.c.
doublereal sn[15]
Definition at line 18 of file APT232.c.
doublereal snk[15]
Definition at line 18 of file APT232.c.
doublereal snl[15]
Definition at line 18 of file APT232.c.
doublereal sp[15]
Definition at line 18 of file APT232.c.
doublereal spk[15]
Definition at line 18 of file APT232.c.
doublereal spl[15]
Definition at line 18 of file APT232.c.
doublereal stck[5]
Definition at line 35 of file APT232.c.
doublereal stck1[5]
Definition at line 35 of file APT232.c.
doublereal stck2[5]
Definition at line 35 of file APT232.c.
doublereal stckn[5]
Definition at line 35 of file APT232.c.
struct { ... } sv1_
struct { ... } sv_
doublereal tau[5]
Definition at line 18 of file APT232.c.
doublereal tau1[5]
Definition at line 18 of file APT232.c.
doublereal tau2[5]
Definition at line 18 of file APT232.c.
doublereal tee[15]
Definition at line 35 of file APT232.c.
doublereal th[5]
Definition at line 18 of file APT232.c.
doublereal tn[15]
Definition at line 18 of file APT232.c.
doublereal tnl[15]
Definition at line 35 of file APT232.c.
doublereal toolht[15]
Definition at line 18 of file APT232.c.
doublereal toolwd[5]
Definition at line 18 of file APT232.c.
doublereal tp[15]
Definition at line 18 of file APT232.c.
doublereal tpk[15]
Definition at line 18 of file APT232.c.
doublereal u1[15]
Definition at line 18 of file APT232.c.
doublereal u1k[15]
Definition at line 18 of file APT232.c.
doublereal varble[5]
Definition at line 18 of file APT232.c.
doublereal vndir[15]
Definition at line 18 of file APT232.c.
doublereal vt[15]
Definition at line 18 of file APT232.c.
doublereal z0
Definition at line 44 of file APT232.c.
doublereal z1
Definition at line 44 of file APT232.c.
doublereal z10
Definition at line 44 of file APT232.c.
doublereal z11em1
Definition at line 44 of file APT232.c.
doublereal z12em1
Definition at line 44 of file APT232.c.
doublereal z1e38
Definition at line 44 of file APT232.c.
doublereal z1e6
Definition at line 44 of file APT232.c.
doublereal z1em1
Definition at line 44 of file APT232.c.
doublereal z1em2
Definition at line 44 of file APT232.c.
doublereal z1em3
Definition at line 44 of file APT232.c.
doublereal z1em5
Definition at line 44 of file APT232.c.
doublereal z1em6
Definition at line 44 of file APT232.c.
doublereal z1em7
Definition at line 44 of file APT232.c.
doublereal z1em9
Definition at line 44 of file APT232.c.
doublereal z2
Definition at line 44 of file APT232.c.
doublereal z3
Definition at line 44 of file APT232.c.
doublereal z5
Definition at line 44 of file APT232.c.
doublereal z5em1
Definition at line 44 of file APT232.c.
doublereal z5em6
Definition at line 44 of file APT232.c.
doublereal z6em1
Definition at line 44 of file APT232.c.
doublereal z90
Definition at line 44 of file APT232.c.
doublereal z9em1
Definition at line 44 of file APT232.c.
doublereal z__[5]
Definition at line 18 of file APT232.c.
doublereal zm1
Definition at line 44 of file APT232.c.
struct { ... } znumbr_