My Project: APT202.c File Reference
APT202.c File Reference
#include "f2c.h"
Macros
#define ldef_1 ldef_
#define idef_1 idef_
#define dsname_1 dsname_
#define srfnam_1 srfnam_
#define _BLNK__1 _BLNK__
#define x ((doublereal *)&_BLNK__1)
#define can ((doublereal *)&_BLNK__1 + 40)
#define cval (equiv_5)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define itemp ((integer *)equiv_6)
#define iskip ((integer *)equiv_5)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define tmpnam (equiv_6)
Functions
int apt202_ (doublereal *adress, integer *isrflg)
Variables
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
struct {
doublereal dsname
integer namsub
} dsname_
struct {
doublereal psname
doublereal cs1nam
doublereal cs2nam
integer ipssub
integer ics1sb
integer ics2sb
} srfnam_
struct {
doublereal com [36000]
} _BLNK__
static integer c__1 = 1
static integer c__4 = 4
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 48 of file APT202.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define cval (equiv_5)
Referenced by apt202_().
#define dsname_1 dsname_
Definition at line 35 of file APT202.c.
Referenced by apt202_().
#define idef_1 idef_
Definition at line 28 of file APT202.c.
Referenced by apt202_().
#define iskip ((integer *)equiv_5)
Referenced by apt202_().
#define itemp ((integer *)equiv_6)
Referenced by apt202_().
#define ldef_1 ldef_
Definition at line 22 of file APT202.c.
Referenced by apt202_().
#define srfnam_1 srfnam_
Definition at line 42 of file APT202.c.
Referenced by apt202_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define tmpnam (equiv_6)
Referenced by apt202_().
#define x ((doublereal *)&_BLNK__1)
Referenced by apt202_().
Function Documentation
int apt202_ (doublereal * adress, integer * isrflg)
Definition at line 60 of file APT202.c.
References addrss_(), bcdf_(), c__1, c__4, cval, dollar, dsname_1, holfrm_(), i__, idef_1, incan_(), isize, iskip, itemp, j, k, ldef_1, mode, srfnam_1, temp, tmpnam, unpack_(), x, and xcanon_().
Referenced by apt234_(), from_(), goto_(), and gotopn_().
 {
     /* Initialized data */
     static char dollar[1] = "$";
     static char hname[8] = "NONAME  ";
     /* System generated locals */
     integer i__1;
     static doublereal equiv_5[1], equiv_6[1];
     /* Local variables */
     static integer i__, j, k;
 #define x ((doublereal *)&_BLNK__1)
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer nwd;
     extern integer bcdf_(char *, ftnlen);
     static integer mode;
 #define cval (equiv_5)
     static char temp[4];
     extern /* Subroutine */ int incan_(integer *);
 #define canon ((doublereal *)&_BLNK__1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
 #define itemp ((integer *)equiv_6)
 #define iskip ((integer *)equiv_5)
     static integer isize;
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern integer addrss_(doublereal *), xcanon_(integer *);
     extern /* Subroutine */ int unpack_(doublereal *, integer *, integer *,
         integer *);
     static integer isbsct;
     extern /* Subroutine */ int holfrm_(integer *, char *, integer *, integer
         *, integer *, ftnlen);
 #define tmpnam (equiv_6)
 /*  PURPOSE         TO STORE THE SURFACE NAMES AND SUBSCRIPTS */
 /*                  INTO COMMON BLOCKS DSNAME AND SRFNAM */
 /*  CALLING SEQNCE  CALL APT202(ADRESS,ISRFLG) */
 /*  ARGUMENTS       ADRESS    INDEX TO SURFACE DATA */
 /*                  ISRFLG    FLAG POINTER FOR SURFACE -- */
 /*                                 1.  PART SURFACE */
 /*                                 2.  DRIVE SURFACE */
 /*                                 3.  CHECK SURFACE 1 */
 /*                                 4.  CHECK SURFACE 2 */
 /*  CALLED BY       APT234,  FROM,  GOTO */
 /*  SUBSIDIARIES    UNPACK */
 /*  DIAGNOSTICS     NONE */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*        COMMON BLOCKS FOR SURFACE NAME AND SUBSCRIPT STORAGE */
 /*     23.   DSNAME BLOCK */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*     24.   SRFNAM BLOCK */
 /* ...     INFORMATION ASSOCIATED WITH CANONICAL FORMS STORAGE */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
     /* Parameter adjustments */
     --adress;
     /* Function Body */
 /*     ------------------------------------------------------------ */
     unpack_(&adress[1], &mode, &isize, &isbsct);
     if (isbsct > 1) {
     goto L200;
     }
     k = isize + 1;
     *tmpnam = adress[k];
     holfrm_(itemp, temp, &c__1, &c__4, &nwd, (ftnlen)4);
 L5:
     if (*(unsigned char *)&dollar[0] == *(unsigned char *)temp) {
     itemp[0] = bcdf_(hname, (ftnlen)4);
     itemp[1] = bcdf_(hname + 4, (ftnlen)2);
     }
 /*        BRANCH FOR PROPER SURFACE GIVEN BY ISRFLG */
     switch (*isrflg) {
     case 1:  goto L10;
     case 2:  goto L20;
     case 3:  goto L30;
     case 4:  goto L40;
     }
 L10:
     srfnam_1.psname = *tmpnam;
     srfnam_1.ipssub = isbsct;
     goto L100;
 L20:
     dsname_1.dsname = *tmpnam;
     dsname_1.namsub = isbsct;
     goto L100;
 L30:
     srfnam_1.cs1nam = *tmpnam;
     srfnam_1.ics1sb = isbsct;
     goto L100;
 L40:
     srfnam_1.cs2nam = *tmpnam;
     srfnam_1.ics2sb = isbsct;
 L100:
     return 0;
 /* ...     DETERMINE VIRTUAL INDEX OF ADRESS(1) IN X-ARRAY */
 L200:
     i__ = (addrss_(&adress[1]) - addrss_(x)) / idef_1.kwrdsz + isize + 1;
     k = i__;
     if (ldef_1.canflg) {
     incan_(&i__);
     }
 /* ...     FIND BCD NAME OF THIS SURFACE */
     i__1 = isbsct;
     for (j = 2; j <= i__1; ++j) {
 L250:
     *cval = x[k - 1];
     if (*iskip <= 0 || *iskip > 1024) {
         goto L300;
     }
     i__ += *iskip;
     k = i__;
     if (ldef_1.canflg) {
         k = xcanon_(&i__);
     }
     goto L250;
 L300:
     k = k + isize + 1;
     i__ = i__ + isize + 1;
 /* L400: */
     }
     *tmpnam = x[k - 1];
     goto L5;
 } /* apt202_ */
Variable Documentation
struct { ... } _BLNK__
logical altmlt
Definition at line 18 of file APT202.c.
logical bnderr
Definition at line 18 of file APT202.c.
logical boundf
Definition at line 18 of file APT202.c.
integer c__1 = 1 static
Definition at line 52 of file APT202.c.
Referenced by apt202_().
integer c__4 = 4 static
Definition at line 53 of file APT202.c.
Referenced by apt202_().
logical canflg
Definition at line 18 of file APT202.c.
doublereal com[36000]
Definition at line 45 of file APT202.c.
doublereal cs1nam
Definition at line 38 of file APT202.c.
doublereal cs2nam
Definition at line 38 of file APT202.c.
doublereal dsname
Definition at line 31 of file APT202.c.
struct { ... } dsname_
integer iblk1
Definition at line 25 of file APT202.c.
integer ics1sb
Definition at line 39 of file APT202.c.
integer ics2sb
Definition at line 39 of file APT202.c.
struct { ... } idef_
integer ierror
Definition at line 25 of file APT202.c.
integer ipssub
Definition at line 39 of file APT202.c.
logical jcs
Definition at line 18 of file APT202.c.
logical jds
Definition at line 18 of file APT202.c.
integer kwrdsz
Definition at line 25 of file APT202.c.
integer ldasiz
Definition at line 25 of file APT202.c.
struct { ... } ldef_
integer namsub
Definition at line 32 of file APT202.c.
logical pchlst
Definition at line 18 of file APT202.c.
logical prnton
Definition at line 18 of file APT202.c.
doublereal psname
Definition at line 38 of file APT202.c.
logical refflg
Definition at line 18 of file APT202.c.
logical refmot
Definition at line 18 of file APT202.c.
struct { ... } srfnam_
logical subflg
Definition at line 18 of file APT202.c.
integer surfad[4]
Definition at line 25 of file APT202.c.
logical tabprt
Definition at line 18 of file APT202.c.
logical unflag
Definition at line 18 of file APT202.c.
logical zflag
Definition at line 18 of file APT202.c.