My Project: APT314.c File Reference
APT314.c File Reference
#include "f2c.h"
Macros
#define editor_1 editor_
#define irecrd ((doublereal *)&editor_1)
#define jrecrd ((integer *)&editor_1)
#define record ((doublereal *)&editor_1)
Functions
int apt314_ (integer *ntape, integer *nrec)
Variables
struct {
doublereal editor [1500]
} editor_
Macro Definition Documentation
#define editor_1 editor_
Definition at line 21 of file APT314.c.
#define irecrd ((doublereal *)&editor_1)
#define jrecrd ((integer *)&editor_1)
Referenced by apt314_().
#define record ((doublereal *)&editor_1)
Function Documentation
int apt314_ (integer * ntape, integer * nrec)
Definition at line 32 of file APT314.c.
References aread_(), help_(), i__, ir, jrecrd, k, l, m, n, and nb.
Referenced by apt301_(), and apt335_().
 {
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__, k, l, m, n, nb, ir;
     extern /* Subroutine */ int help_(void), aread_(integer *, integer *,
         integer *, integer *, integer *);
     static integer ebuff[516];
 #define irecrd ((doublereal *)&editor_1)
 #define jrecrd ((integer *)&editor_1)
 #define record ((doublereal *)&editor_1)
 /*       THIS SUBROUTINE READS AND UNBLOCKS CLFILE INTO RECORD */
     if (*nrec == 0) {
     *nrec = 1;
     }
     if (*nrec != -1) {
     goto L100;
     }
     n = 0;
     nb = 0;
     m = 0;
     k = 3;
     return 0;
 L100:
     if (*nrec > m) {
     goto L10;
     }
     if (*nrec < n) {
     goto L20;
     }
     if (*nrec == ebuff[k - 1]) {
     goto L30;
     }
     k = 3;
 L3:
     if (*nrec == ebuff[k - 1]) {
     goto L30;
     }
     k = k + ebuff[k] + 2;
     if (k > 516) {
     help_();
     }
     goto L3;
 L30:
     ++k;
     l = ebuff[k - 1];
     i__1 = l;
     for (i__ = 1; i__ <= i__1; ++i__) {
 /* L31: */
     jrecrd[i__ - 1] = ebuff[k + i__ - 1];
     }
     k = k + l + 1;
     return 0;
 L10:
     ++nb;
 L15:
     k = 516;
     aread_(ntape, &nb, ebuff, &k, &ir);
     k = 3;
     n = ebuff[0];
     m = ebuff[1];
     goto L100;
 L20:
     --nb;
     goto L15;
 } /* apt314_ */
Variable Documentation
doublereal editor[1500]
Definition at line 18 of file APT314.c.
struct { ... } editor_