My Project: APT305.c File Reference
APT305.c File Reference
#include "f2c.h"
Macros
#define editor_1 editor_
#define kflags_1 kflags_
#define icopy ((integer *)&editor_1 + 1188)
#define amttab ((doublereal *)&editor_1 + 286)
#define itrafl ((integer *)&kflags_1 + 4)
#define mltflg ((integer *)&editor_1 + 748)
#define tramat ((doublereal *)&editor_1 + 1021)
#define tmatrx ((doublereal *)&editor_1 + 984)
Functions
int apt305_ (void)
Variables
struct {
doublereal editor [1500]
} editor_
struct {
integer kflags [5]
} kflags_
Macro Definition Documentation
#define amttab ((doublereal *)&editor_1 + 286)
Referenced by apt305_().
#define editor_1 editor_
Definition at line 21 of file APT305.c.
#define icopy ((integer *)&editor_1 + 1188)
Referenced by apt305_().
#define itrafl ((integer *)&kflags_1 + 4)
Referenced by apt305_().
#define kflags_1 kflags_
Definition at line 27 of file APT305.c.
#define mltflg ((integer *)&editor_1 + 748)
Referenced by apt305_().
#define tmatrx ((doublereal *)&editor_1 + 984)
Referenced by apt305_().
#define tramat ((doublereal *)&editor_1 + 1021)
Referenced by apt305_().
Function Documentation
int apt305_ (void)
Definition at line 37 of file APT305.c.
References amttab, apt306_(), apt308_(), icopy, itrafl, mltflg, tmatrx, and tramat.
Referenced by apt301_(), and apt335_().
 {
     /* Local variables */
     extern /* Subroutine */ int apt306_(doublereal *, doublereal *,
         doublereal *), apt308_(doublereal *, doublereal *);
 #define icopy ((integer *)&editor_1 + 1188)
 #define amttab ((doublereal *)&editor_1 + 286)
 #define itrafl ((integer *)&kflags_1 + 4)
 #define mltflg ((integer *)&editor_1 + 748)
 #define tramat ((doublereal *)&editor_1 + 1021)
 #define tmatrx ((doublereal *)&editor_1 + 984)
 /*      THIS SUBROUTINE GENERATES TMATRX FROM AMTTAB AND TRAMAT */
 /*      DEPENDING ON COPY LEVEL (ICOPY) AND TRACUT (ITRAFL) */
 /*      MLTFLG DETERMINES MATRIX MULTIPLICATION ORDER 1=POINT 0=PATTERN */
     if (*icopy == 0) {
     goto L90;
     }
     if (*mltflg == 0) {
     goto L40;
     }
     switch (*icopy) {
     case 1:  goto L10;
     case 2:  goto L20;
     case 3:  goto L30;
     }
 L10:
     apt308_(tmatrx, amttab);
     goto L80;
 L20:
     apt306_(tmatrx, &amttab[16], amttab);
     goto L80;
 L30:
     apt306_(tmatrx, &amttab[16], amttab);
     apt306_(tmatrx, &amttab[32], tmatrx);
     goto L80;
 L40:
     switch (*icopy) {
     case 1:  goto L50;
     case 2:  goto L60;
     case 3:  goto L70;
     }
 L50:
     apt308_(tmatrx, amttab);
     goto L80;
 L60:
     apt306_(tmatrx, amttab, &amttab[16]);
     goto L80;
 L70:
     apt306_(tmatrx, amttab, &amttab[16]);
     apt306_(tmatrx, tmatrx, &amttab[32]);
 /* ...     CHECK FOR TRACUT MODIFICATION OF COPY MATRIX */
 L80:
     if (*itrafl == 0) {
     goto L100;
     }
     apt306_(tmatrx, tmatrx, tramat);
     goto L100;
 /* ...     CHECK FOR A TRACUT TRANSFORMATION ONLY */
 L90:
     if (*itrafl == 0) {
     goto L100;
     }
     apt308_(tmatrx, tramat);
 L100:
     return 0;
 } /* apt305_ */
Variable Documentation
doublereal editor[1500]
Definition at line 18 of file APT305.c.
struct { ... } editor_
integer kflags[5]
Definition at line 24 of file APT305.c.
struct { ... } kflags_