My Project: APT341.c File Reference
APT341.c File Reference
#include "f2c.h"
Macros
#define editor_1 editor_
#define r5axis_1 r5axis_
#define i5axis_1 i5axis_
#define x1 ((doublereal *)&editor_1 + 1331)
#define x2 ((doublereal *)&editor_1 + 1332)
#define y1 ((doublereal *)&editor_1 + 1336)
#define y2 ((doublereal *)&editor_1 + 1337)
#define area1 ((doublereal *)&editor_1)
#define area2 ((doublereal *)&editor_1 + 500)
#define area3 ((doublereal *)&editor_1 + 1250)
Functions
int apt341_ (void)
Variables
struct {
doublereal editor [1500]
} editor_
struct {
doublereal z1
doublereal z2
doublereal zstart
doublereal ystart
doublereal xstart
doublereal zd
doublereal yd
doublereal xd
doublereal zcv
doublereal ycv
doublereal xcv
doublereal zdo
doublereal ydo
doublereal xdo
doublereal zcc
doublereal ycc
doublereal xcc
doublereal zun
doublereal yun
doublereal xun
doublereal ztr
doublereal ytr
doublereal xtr
doublereal zta
doublereal yta
doublereal xta
doublereal z__
doublereal stang
doublereal endang
doublereal dang
doublereal cang
doublereal dlngth
doublereal tlngth
doublereal cutter
doublereal test
doublereal cradus
} r5axis_
struct {
integer ivtflg
integer is
integer ir
integer il
integer ie
integer jsuber
integer iabove
integer nrecex
integer nreccl
integer ncflsv
} i5axis_
Macro Definition Documentation
#define area1 ((doublereal *)&editor_1)
#define area2 ((doublereal *)&editor_1 + 500)
#define area3 ((doublereal *)&editor_1 + 1250)
#define editor_1 editor_
Definition at line 21 of file APT341.c.
#define i5axis_1 i5axis_
Definition at line 36 of file APT341.c.
Referenced by apt341_().
#define r5axis_1 r5axis_
Definition at line 30 of file APT341.c.
Referenced by apt341_().
#define x1 ((doublereal *)&editor_1 + 1331)
Referenced by apt341_().
#define x2 ((doublereal *)&editor_1 + 1332)
Referenced by apt341_().
#define y1 ((doublereal *)&editor_1 + 1336)
Referenced by apt341_().
#define y2 ((doublereal *)&editor_1 + 1337)
Referenced by apt341_().
Function Documentation
int apt341_ (void)
Definition at line 50 of file APT341.c.
References apt315_(), apt342_(), f, i5axis_1, r5axis_1, x1, x2, y1, and y2.
Referenced by apt311_(), and apt340_().
 {
     /* System generated locals */
     doublereal d__1;
     /* Builtin functions */
     double sin(doublereal), cos(doublereal);
     /* Local variables */
 #define x1 ((doublereal *)&editor_1 + 1331)
 #define x2 ((doublereal *)&editor_1 + 1332)
 #define y1 ((doublereal *)&editor_1 + 1336)
 #define y2 ((doublereal *)&editor_1 + 1337)
     static doublereal tcos, tsin;
 #define area1 ((doublereal *)&editor_1)
 #define area2 ((doublereal *)&editor_1 + 500)
 #define area3 ((doublereal *)&editor_1 + 1250)
     extern /* Subroutine */ int apt342_(doublereal *, doublereal *,
         doublereal *), apt315_(doublereal *, doublereal *);
     static doublereal tsin1;
 /* *********************************************************************** */
 /* ******************************************************************** */
 /*     SYSTEM COMMON,DIMENSION, AND EQUIVALENCE STATEMENTS */
 /* ...    PRORATE TILT ANGLE */
     r5axis_1.cang = r5axis_1.stang + r5axis_1.dlngth / r5axis_1.tlngth *
         r5axis_1.dang;
     tsin = sin(r5axis_1.cang);
     tsin1 = abs(tsin);
     tcos = cos(r5axis_1.cang);
     apt342_(&r5axis_1.zcv, &r5axis_1.zun, &r5axis_1.ztr);
     apt315_(&r5axis_1.ztr, &r5axis_1.ztr);
 /* ...    IS CANG .GT. 80 DEGREES */
     if (abs(tcos) - .1736f <= 0.) {
     goto L5;
     } else {
     goto L90;
     }
 L90:
 /* ...    CALCULATE XYZ COORDINATES OF NEW CUTTER POSITION */
     if (r5axis_1.cradus != 0.) {
     goto L100;
     } else {
     goto L110;
     }
 L100:
     r5axis_1.z__ = r5axis_1.cradus * (1.f - tcos) + (r5axis_1.cutter -
         r5axis_1.cradus) * tsin1;
     goto L120;
 L110:
     r5axis_1.z__ = (d__1 = r5axis_1.cutter * tsin, abs(d__1));
 L120:
     if (r5axis_1.cang * r5axis_1.zun >= 0.) {
     goto L150;
     } else {
     goto L130;
     }
 L130:
     if (r5axis_1.cradus != 0.) {
     goto L140;
     } else {
     goto L170;
     }
 L140:
     r5axis_1.test = r5axis_1.cradus * (tcos - tsin1 + (tsin1 - 1.f) / tcos) -
         r5axis_1.cutter * (tcos - 2.f / tcos + 1.f);
     r5axis_1.test = -r5axis_1.test;
     goto L9;
 L150:
     if (r5axis_1.cradus != 0.) {
     goto L160;
     } else {
     goto L8;
     }
 L160:
     r5axis_1.test = r5axis_1.cradus * (tcos - tsin1 + (tsin1 - 1.f) / tcos) +
         r5axis_1.cutter * (1.f - tcos);
     goto L9;
 L170:
     if (i5axis_1.iabove != 0) {
     goto L3;
     } else {
     goto L6;
     }
 L3:
     r5axis_1.z__ = -r5axis_1.z__;
     goto L8;
 L5:
     i5axis_1.jsuber = 30007;
 /* ...    ERROR 30007 - TILT ANGLE IS GREATER THAN 80 DEGREES. */
     goto L40;
 L6:
     r5axis_1.test = -(r5axis_1.cutter * 2.f / tcos - r5axis_1.cutter -
         r5axis_1.cutter * tcos);
     goto L9;
 L8:
     r5axis_1.test = r5axis_1.cutter * (1.f - tcos);
 L9:
     r5axis_1.xdo = r5axis_1.test * r5axis_1.xtr;
     r5axis_1.ydo = r5axis_1.test * r5axis_1.ytr;
     r5axis_1.zdo = r5axis_1.test * r5axis_1.ztr;
     r5axis_1.xcc = *x2 + r5axis_1.xdo;
     r5axis_1.ycc = *y2 + r5axis_1.ydo;
     r5axis_1.zcc = r5axis_1.z2 + r5axis_1.z__;
 /* ...    CALCULATE IJK COMPONENTS OF NEW TLAXIS VECTOR */
     r5axis_1.xtr = tcos * r5axis_1.xtr;
     r5axis_1.ytr = tcos * r5axis_1.ytr;
     if (r5axis_1.zun >= 0.) {
     goto L20;
     } else {
     goto L10;
     }
 L10:
     r5axis_1.ztr = tsin;
     apt342_(&r5axis_1.zcv, &r5axis_1.ztr, &r5axis_1.zta);
     goto L30;
 L20:
     r5axis_1.ztr = -tsin;
     apt342_(&r5axis_1.ztr, &r5axis_1.zcv, &r5axis_1.zta);
 L30:
     apt315_(&r5axis_1.zta, &r5axis_1.zta);
     *x1 = *x2;
     *y1 = *y2;
     r5axis_1.z1 = r5axis_1.z2;
 L40:
     return 0;
 } /* apt341_ */
Variable Documentation
doublereal cang
Definition at line 24 of file APT341.c.
doublereal cradus
Definition at line 24 of file APT341.c.
doublereal cutter
Definition at line 24 of file APT341.c.
doublereal dang
Definition at line 24 of file APT341.c.
doublereal dlngth
Definition at line 24 of file APT341.c.
doublereal editor[1500]
Definition at line 18 of file APT341.c.
struct { ... } editor_
doublereal endang
Definition at line 24 of file APT341.c.
struct { ... } i5axis_
integer iabove
Definition at line 33 of file APT341.c.
integer ie
Definition at line 33 of file APT341.c.
integer il
Definition at line 33 of file APT341.c.
integer ir
Definition at line 33 of file APT341.c.
integer is
Definition at line 33 of file APT341.c.
integer ivtflg
Definition at line 33 of file APT341.c.
integer jsuber
Definition at line 33 of file APT341.c.
integer ncflsv
Definition at line 33 of file APT341.c.
integer nreccl
Definition at line 33 of file APT341.c.
integer nrecex
Definition at line 33 of file APT341.c.
struct { ... } r5axis_
doublereal stang
Definition at line 24 of file APT341.c.
doublereal test
Definition at line 24 of file APT341.c.
doublereal tlngth
Definition at line 24 of file APT341.c.
doublereal xcc
Definition at line 24 of file APT341.c.
doublereal xcv
Definition at line 24 of file APT341.c.
doublereal xd
Definition at line 24 of file APT341.c.
doublereal xdo
Definition at line 24 of file APT341.c.
doublereal xstart
Definition at line 24 of file APT341.c.
doublereal xta
Definition at line 24 of file APT341.c.
doublereal xtr
Definition at line 24 of file APT341.c.
doublereal xun
Definition at line 24 of file APT341.c.
doublereal ycc
Definition at line 24 of file APT341.c.
doublereal ycv
Definition at line 24 of file APT341.c.
doublereal yd
Definition at line 24 of file APT341.c.
doublereal ydo
Definition at line 24 of file APT341.c.
doublereal ystart
Definition at line 24 of file APT341.c.
doublereal yta
Definition at line 24 of file APT341.c.
doublereal ytr
Definition at line 24 of file APT341.c.
doublereal yun
Definition at line 24 of file APT341.c.
doublereal z1
Definition at line 24 of file APT341.c.
doublereal z2
Definition at line 24 of file APT341.c.
doublereal z__
Definition at line 24 of file APT341.c.
doublereal zcc
Definition at line 24 of file APT341.c.
doublereal zcv
Definition at line 24 of file APT341.c.
doublereal zd
Definition at line 24 of file APT341.c.
doublereal zdo
Definition at line 24 of file APT341.c.
doublereal zstart
Definition at line 24 of file APT341.c.
doublereal zta
Definition at line 24 of file APT341.c.
doublereal ztr
Definition at line 24 of file APT341.c.
doublereal zun
Definition at line 24 of file APT341.c.