My Project: APT336.c File Reference
APT336.c File Reference
#include "f2c.h"
Macros
#define super_1 super_
#define csuper_1 csuper_
#define clerrw_1 clerrw_
#define clerrt_1 clerrt_
#define editor_1 editor_
#define darray_1 darray_
#define area3 ((doublereal *)&editor_1 + 1250)
#define cflags ((logical *)&super_1)
#define lxtras ((logical *)&super_1 + 9)
Functions
int apt336_ (integer *ierror, char *subnam, ftnlen subnam_len)
Variables
struct {
logical err
logical xc
logical cl
logical px
integer errx
logical end
logical fini
logical asm__
logical abend
integer xtras [7]
} super_
struct {
char irdsav [80]
} csuper_
struct {
integer cerdm
integer cercnt
integer cerad1 [34]
integer cerad2 [34]
} clerrw_
struct {
char certxt [2280]
} clerrt_
struct {
doublereal editor [1500]
} editor_
struct {
char darray [120]
} darray_
static integer c__1 = 1
static integer c__34 = 34
static integer c__36 = 36
static integer c__5 = 5
static integer c__42 = 42
static integer c__17 = 17
static integer c__59 = 59
static integer c__8 = 8
static integer c__67 = 67
static integer c__4 = 4
static integer c__15 = 15
static integer c__54 = 54
Macro Definition Documentation
#define area3 ((doublereal *)&editor_1 + 1250)
#define cflags ((logical *)&super_1)
#define clerrt_1 clerrt_
Definition at line 42 of file APT336.c.
Referenced by apt336_().
#define clerrw_1 clerrw_
Definition at line 36 of file APT336.c.
Referenced by apt336_().
#define csuper_1 csuper_
Definition at line 30 of file APT336.c.
#define darray_1 darray_
Definition at line 54 of file APT336.c.
Referenced by apt336_().
#define editor_1 editor_
Definition at line 48 of file APT336.c.
#define lxtras ((logical *)&super_1 + 9)
#define super_1 super_
Definition at line 24 of file APT336.c.
Referenced by apt336_().
Function Documentation
int apt336_ (integer * ierror, char * subnam, ftnlen subnam_len)
Definition at line 80 of file APT336.c.
References c__1, c__15, c__17, c__34, c__36, c__4, c__42, c__5, c__54, c__59, c__67, c__8, cform_(), clerrt_1, clerrw_1, cprint_(), darray_1, i__, iconv_(), j, k, l1, and super_1.
Referenced by apt301_(), apt302_(), apt311_(), apt335_(), and cnvrt3_().
 {
     /* Initialized data */
     static integer ierrn = 0;
     static integer errlev[4] = { 0,0,0,0 };
     static char notext[54] = " THERE IS NO DIAGNOSTIC MESSAGE FOR THIS ERROR"
         " NUMBER ";
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, j, k, l1;
 #define area3 ((doublereal *)&editor_1 + 1250)
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen), iconv_(integer *, char *, integer *, integer *,
         ftnlen);
 #define cflags ((logical *)&super_1)
     extern /* Subroutine */ int cprint_(char *, ftnlen);
 #define lxtras ((logical *)&super_1 + 9)
 /* ...      32.  PARAMETERS REQUIRED BY SUPERVISOR */
 /* ...COMMON/CLERR/ SPLIT INTO /CLERRW/ FOR INTEGERS & /CLERRT/ FOR TEXT */
 /* ... INITILIZE ARRAY INDICATING WHICH ERRORS ARE OF SEVERITY LEVEL FOUR. */
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
     cform_("0       ****  CL EDITING ERROR NO.", darray_1.darray, &c__1, &
         c__34, (ftnlen)34, (ftnlen)120);
     iconv_(ierror, darray_1.darray, &c__36, &c__5, (ftnlen)120);
     cform_(" FROM SUBROUTINE ", darray_1.darray, &c__42, &c__17, (ftnlen)17, (
         ftnlen)120);
     cform_(subnam, darray_1.darray, &c__59, &c__8, (ftnlen)8, (ftnlen)120);
     cform_("****", darray_1.darray, &c__67, &c__4, (ftnlen)4, (ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     i__1 = clerrw_1.cerdm;
     for (i__ = 1; i__ <= i__1; ++i__) {
     if (*ierror == clerrw_1.cerad1[i__ - 1]) {
         goto L40;
     }
 /* L10: */
     }
     cform_(notext, darray_1.darray, &c__15, &c__54, (ftnlen)54, (ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     goto L60;
 L40:
     k = clerrw_1.cerad2[i__ - 1];
     if (i__ == 1) {
     j = 1;
     } else {
     j = clerrw_1.cerad2[i__ - 2] + 1;
     }
     l1 = 11;
     i__1 = k;
     for (i__ = j; i__ <= i__1; ++i__) {
     if (l1 >= 113) {
         cprint_(darray_1.darray, (ftnlen)120);
         l1 = 11;
     }
     l1 += 4;
     s_copy(darray_1.darray + (l1 - 1), clerrt_1.certxt + (i__ - 1 << 2), (
         ftnlen)4, (ftnlen)4);
 /* L50: */
     }
     cprint_(darray_1.darray, (ftnlen)120);
 /* ... SET ERROR LEVEL INDICATOR FOR SUPERVISOR. */
 L60:
     ++super_1.xtras[0];
     if (super_1.errx > 4) {
     goto L320;
     }
     super_1.errx = 4;
     i__1 = ierrn;
     for (i__ = 1; i__ <= i__1; ++i__) {
     if (*ierror == errlev[i__ - 1]) {
         goto L320;
     }
 /* L310: */
     }
     super_1.errx = 8;
 L320:
     return 0;
 } /* apt336_ */
Variable Documentation
logical abend
Definition at line 20 of file APT336.c.
logical asm__
Definition at line 20 of file APT336.c.
integer c__1 = 1 static
Definition at line 58 of file APT336.c.
Referenced by apt336_().
integer c__15 = 15 static
Definition at line 68 of file APT336.c.
Referenced by apt336_().
integer c__17 = 17 static
Definition at line 63 of file APT336.c.
Referenced by apt336_().
integer c__34 = 34 static
Definition at line 59 of file APT336.c.
Referenced by apt336_().
integer c__36 = 36 static
Definition at line 60 of file APT336.c.
Referenced by apt336_().
integer c__4 = 4 static
Definition at line 67 of file APT336.c.
Referenced by apt336_().
integer c__42 = 42 static
Definition at line 62 of file APT336.c.
Referenced by apt336_().
integer c__5 = 5 static
Definition at line 61 of file APT336.c.
Referenced by apt336_().
integer c__54 = 54 static
Definition at line 69 of file APT336.c.
Referenced by apt336_().
integer c__59 = 59 static
Definition at line 64 of file APT336.c.
Referenced by apt336_().
integer c__67 = 67 static
Definition at line 66 of file APT336.c.
Referenced by apt336_().
integer c__8 = 8 static
Definition at line 65 of file APT336.c.
Referenced by apt336_().
integer cerad1[34]
Definition at line 33 of file APT336.c.
integer cerad2[34]
Definition at line 33 of file APT336.c.
integer cercnt
Definition at line 33 of file APT336.c.
integer cerdm
Definition at line 33 of file APT336.c.
char certxt[2280]
Definition at line 39 of file APT336.c.
logical cl
Definition at line 18 of file APT336.c.
struct { ... } clerrt_
struct { ... } clerrw_
struct { ... } csuper_
char darray[120]
Definition at line 51 of file APT336.c.
struct { ... } darray_
doublereal editor[1500]
Definition at line 45 of file APT336.c.
struct { ... } editor_
logical end
Definition at line 20 of file APT336.c.
logical err
Definition at line 18 of file APT336.c.
integer errx
Definition at line 19 of file APT336.c.
logical fini
Definition at line 20 of file APT336.c.
char irdsav[80]
Definition at line 27 of file APT336.c.
logical px
Definition at line 18 of file APT336.c.
struct { ... } super_
logical xc
Definition at line 18 of file APT336.c.
integer xtras[7]
Definition at line 21 of file APT336.c.