My Project: ARGCVT.c File Reference
ARGCVT.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define code_1 code_
#define opmod_1 opmod_
#define moduli_1 moduli_
#define dlr ((integer *)&opmod_1 + 1)
#define vbl ((integer *)&code_1 + 60)
#define temp ((integer *)&code_1 + 32)
#define label ((integer *)&code_1 + 42)
#define dbldlr ((integer *)&opmod_1 + 2)
#define implab ((integer *)&code_1 + 44)
#define modhlf ((integer *)&moduli_1 + 1)
#define modulo ((integer *)&moduli_1)
#define nought ((integer *)&opmod_1)
#define trpdlr ((integer *)&opmod_1 + 3)
Functions
int argcvt_ (integer *index)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer code [150]
} code_
struct {
integer opmod [6]
} opmod_
struct {
integer moduli [2]
} moduli_
Macro Definition Documentation
#define cnamtb_1 cnamtb_
Definition at line 28 of file ARGCVT.c.
#define code_1 code_
Definition at line 34 of file ARGCVT.c.
#define dbldlr ((integer *)&opmod_1 + 2)
Referenced by argcvt_().
#define dlr ((integer *)&opmod_1 + 1)
Referenced by apt103_(), and argcvt_().
#define implab ((integer *)&code_1 + 44)
Referenced by argcvt_().
#define label ((integer *)&code_1 + 42)
Referenced by argcvt_().
#define modhlf ((integer *)&moduli_1 + 1)
Referenced by argcvt_().
#define moduli_1 moduli_
Definition at line 46 of file ARGCVT.c.
#define modulo ((integer *)&moduli_1)
Referenced by argcvt_().
#define nametb_1 nametb_
Definition at line 22 of file ARGCVT.c.
Referenced by argcvt_().
#define nought ((integer *)&opmod_1)
Referenced by argcvt_().
#define opmod_1 opmod_
Definition at line 40 of file ARGCVT.c.
#define temp ((integer *)&code_1 + 32)
Referenced by argcvt_().
#define trpdlr ((integer *)&opmod_1 + 3)
Referenced by argcvt_().
#define vbl ((integer *)&code_1 + 60)
Referenced by argcvt_().
Function Documentation
int argcvt_ (integer * index)
Definition at line 82 of file ARGCVT.c.
References dbldlr, dlr, implab, l, label, modhlf, modulo, nametb_1, nought, temp, trpdlr, twoarg_(), and vbl.
Referenced by arggen_(), asnadz_(), boolif_(), goloft_(), gopat_(), inpat_(), isscod_(), larges_(), lcanon_(), loop_(), macrec_(), motion_(), pro020_(), pro021_(), pro026_(), pro027_(), pro028_(), recog_(), recogn_(), refgen_(), refref_(), replac_(), ssdef_(), subcod_(), and tssmil_().
 {
     /* Local variables */
     static integer l;
 #define dlr ((integer *)&opmod_1 + 1)
 #define vbl ((integer *)&code_1 + 60)
 #define temp ((integer *)&code_1 + 32)
 #define label ((integer *)&code_1 + 42)
 #define dbldlr ((integer *)&opmod_1 + 2)
 #define implab ((integer *)&code_1 + 44)
 #define modhlf ((integer *)&moduli_1 + 1)
 #define modulo ((integer *)&moduli_1)
     extern /* Subroutine */ int twoarg_(integer *, integer *);
 #define nought ((integer *)&opmod_1)
 #define trpdlr ((integer *)&opmod_1 + 3)
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /* NAMMAX:      NAMTBL INDEX OF END OF THE PART PROGRAM NAME SECTION */
 /*        3.    METALINGUISTIC VARIABLE CLASS CODES */
 /* TEMP:        (1)=CODE CLASS 17000,(2)=NAMTBL INDEX OF 'TEMP  ' */
 /* LABEL:       (1)=CODE CLASS 22000,(2)=NAMTBL INDEX OF 'LABEL ' */
 /* IMPLAB:      (1)=CODE CLASS 23000,(2)=NAMTBL INDEX OF 'IMPLAB' */
 /* VBL:         (1)=CODE CLASS 31000,(2)=NAMTBL INDEX OF 'VBL   ' */
 /*       27.    OPERAND MODIFIERS */
 /* NOUGHT:      CONTAINS OPERAND TYPE 0 */
 /* DLR:         CONTAINS OPERAND TYPE CODE 1 */
 /* DBLDLR:      CONTAINS OPERAND TYPE CODE 2 */
 /* TRPDLR:      CONTAINS OPERAND TYPE CODE 3 */
 /*       29.    CLASS CODE MODULI */
 /* MODULO:      NAMTBL CLASS AND CODE FACTOR 1000 TO DEVIDE OUT CLASS */
 /* MODHLF:      NORMAL MODE CODE LIMIT 500 */
 /* * */
 /* PURPOSE      TO DETERMINE THE LITERAL DESIGNATION OF AN */
 /*              ARGUMENT AND OUTPUT THE APPROPRIATE ARGUMENT- */
 /*              PAIR TO THE I.L. INTERNAL RECORD IMAGE */
 /*              (ILFILE) */
 /* ARGUMENTS    INDEX    NAME TABLE (NAMTBL) INDEX OF ARGUMENT. */
 /* ** */
 /* ...     IS INDEX A POINTER TO A NUMBER */
     if (*index > nametb_1.nammax) {
     goto L20;
     }
 /* ...     NO. CALCULATE CLASS OF THIS ITEM. */
     l = *modulo * (nametb_1.namtbl[*index - 1] / *modulo);
 /* ...     IS MODE OF ITEM GREATER THAN MODHLF */
 /* ...     I.E. IS IT AN INDIRECT ADDRESS */
     if (nametb_1.namtbl[*index - 1] - l < *modhlf) {
     goto L10;
     }
 /* ...     YES. CALL TWOARG WITH MODIFIER OF 3 ($$$) */
     twoarg_(trpdlr, index);
     goto L100;
 /* ...     NOT AN INDIRECT ADDRESS. */
 /* ...     IS IT OF CLASS VBL, TEMP, LABEL, OR IMPLAB. */
 L10:
     if (l != vbl[0] && l != temp[0] && l != label[0] && l != implab[0]) {
     goto L30;
     }
 /* ...     YES. CALL TWOARG WITH MODIFIER OF 0 */
     twoarg_(nought, index);
     goto L100;
 /* ...     NUMBER. CALL TWOARG WITH MODIFIER OF 1 ($) */
 L20:
     twoarg_(dlr, index);
     goto L100;
 /* ...     BCD CHARACTER INDEX. CALL TWOARG WITH MODIFIER OF 2 ($$) */
 L30:
     twoarg_(dbldlr, index);
 L100:
     return 0;
 } /* argcvt_ */
Variable Documentation
integer charnd
Definition at line 18 of file ARGCVT.c.
integer charst
Definition at line 18 of file ARGCVT.c.
char cnamtb[18000]
Definition at line 25 of file ARGCVT.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file ARGCVT.c.
integer code[150]
Definition at line 31 of file ARGCVT.c.
struct { ... } code_
integer ifixnd
Definition at line 18 of file ARGCVT.c.
integer ifixst
Definition at line 18 of file ARGCVT.c.
integer inamnd
Definition at line 18 of file ARGCVT.c.
integer inamst
Definition at line 18 of file ARGCVT.c.
integer moduli[2]
Definition at line 43 of file ARGCVT.c.
struct { ... } moduli_
integer namest
Definition at line 18 of file ARGCVT.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file ARGCVT.c.
integer namtbl[3000]
Definition at line 18 of file ARGCVT.c.
integer numbnd
Definition at line 18 of file ARGCVT.c.
integer numbst
Definition at line 18 of file ARGCVT.c.
integer opmod[6]
Definition at line 37 of file ARGCVT.c.
struct { ... } opmod_