My Project: ARGGEN.c File Reference
ARGGEN.c File Reference
#include "f2c.h"
Macros
#define stklst_1 stklst_
#define argstk ((integer *)&stklst_1 + 201)
#define argtop ((integer *)&stklst_1 + 1)
Functions
int arggen_ (void)
Variables
struct {
integer stklst [300]
} stklst_
Macro Definition Documentation
#define argstk ((integer *)&stklst_1 + 201)
Referenced by arggen_().
#define argtop ((integer *)&stklst_1 + 1)
Referenced by arggen_().
#define stklst_1 stklst_
Definition at line 21 of file ARGGEN.c.
Function Documentation
int arggen_ (void)
Definition at line 37 of file ARGGEN.c.
References argcvt_(), argstk, argtop, i__, ii, and k.
Referenced by pro020_(), pro021_(), pro026_(), pro028_(), and recog_().
 {
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__, k, ii;
     extern /* Subroutine */ int argcvt_(integer *);
 #define argstk ((integer *)&stklst_1 + 201)
 #define argtop ((integer *)&stklst_1 + 1)
 /*        2.    STACK AND POINTER STORAGE */
 /* ARGTOP:      POINTER TO LAST ARGSTK ENTRY */
 /* ARGSTK:      ARGUMENT STACK */
 /* * */
 /* PURPOSE      OUTPUTS ENTIRE CONTENTS OF THE ARGUMENT */
 /*              STACK (ARGSTK) TO THE I.L. INTERNAL RECORD */
 /*              IMAGE (ILFILE). */
 /* NOTES        THE ARGUMENTS ARE PLACED IN ILFILE IN THE */
 /*              REVERSE ORDER IN WHICH THEY ARE STORED IN */
 /*              ARGSTK. */
 /* ** */
 /* ...     FETCH ITEMS FROM ARGSTK IN REVERSE ORDER TO THAT IN WHICH */
 /* ...     THEY WERE INSERTED, AND OUTPUT TO ILFILE USING ARGCVT. */
     i__1 = *argtop;
     for (ii = 1; ii <= i__1; ++ii) {
     i__ = *argtop - ii + 1;
     k = argstk[i__ - 1];
 /* L1: */
     argcvt_(&k);
     }
 /* ...     SET ARGTOP TO ZERO (I.E. CLEAR ARGSTK) AND RETURN */
     *argtop = 0;
     return 0;
 } /* arggen_ */
Variable Documentation
integer stklst[300]
Definition at line 18 of file ARGGEN.c.
struct { ... } stklst_