My Project: ARLM3.c File Reference
ARLM3.c File Reference
#include "f2c.h"
Macros
#define dshar4_1 dshar4_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define addcom_1 addcom_
#define cgoug_1 cgoug_
#define jlin ((integer *)&addcom_1 + 46)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define elmax ((doublereal *)&addcom_1)
#define ibtflg ((integer *)&addcom_1 + 44)
#define clngth ((doublereal *)&addcom_1 + 1)
#define kdynfl ((integer *)&addcom_1 + 48)
Functions
int arlm3_ (void)
Variables
struct {
doublereal a
doublereal b
doublereal c__
doublereal cendis
doublereal cmove [3]
doublereal com1
doublereal com4
doublereal dir [3]
doublereal dp
doublereal dpe
doublereal dpcnt
doublereal dpi
doublereal dpl
doublereal dp1
doublereal d1
doublereal d2a
doublereal flipck
doublereal fwd [3]
doublereal ogle [3]
doublereal p1 [3]
doublereal p2 [3]
doublereal rdrn
doublereal refpnt [3]
doublereal tangl
doublereal tes [3]
doublereal tew [3]
doublereal uvec [3]
doublereal u2 [3]
doublereal v [3]
doublereal vl
doublereal zl
doublereal zlnorm [3]
doublereal zlpnt [3]
doublereal zl1
doublereal param [6]
doublereal r__ [6]
doublereal savpar [4]
doublereal seg [9]
doublereal slope
doublereal sqroot
doublereal unn
doublereal upp
doublereal vint
doublereal vnn
doublereal vpp
} dshar4_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
doublereal addcom [25]
} addcom_
struct {
doublereal talt [3]
doublereal svgl
doublereal shilf
doublereal gflg
doublereal tpg [3]
doublereal spg [3]
} cgoug_
Macro Definition Documentation
#define addcom_1 addcom_
Definition at line 129 of file ARLM3.c.
#define cgoug_1 cgoug_
Definition at line 135 of file ARLM3.c.
Referenced by arlm3_().
#define charct_1 charct_
Definition at line 40 of file ARLM3.c.
#define clngth ((doublereal *)&addcom_1 + 1)
Referenced by arlm3_().
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dshar4_1 dshar4_
Definition at line 25 of file ARLM3.c.
Referenced by arlm3_().
#define elmax ((doublereal *)&addcom_1)
Referenced by arlm3_().
#define fxcor_1 fxcor_
Definition at line 34 of file ARLM3.c.
Referenced by arlm3_().
#define ibtflg ((integer *)&addcom_1 + 44)
#define ifxcor_1 ifxcor_
Definition at line 107 of file ARLM3.c.
Referenced by arlm3_().
#define ishr18_1 ishr18_
Definition at line 115 of file ARLM3.c.
Referenced by arlm3_().
#define isv1_1 isv1_
Definition at line 97 of file ARLM3.c.
Referenced by arlm3_().
#define isv_1 isv_
Definition at line 90 of file ARLM3.c.
Referenced by arlm3_().
#define jlin ((integer *)&addcom_1 + 46)
#define kdynfl ((integer *)&addcom_1 + 48)
Referenced by arlm3_().
#define knumbr_1 knumbr_
Definition at line 123 of file ARLM3.c.
Referenced by arlm3_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sv1_1 sv1_
Definition at line 73 of file ARLM3.c.
Referenced by arlm3_().
#define sv_1 sv_
Definition at line 64 of file ARLM3.c.
Referenced by arlm3_().
#define tlldat_1 tlldat_
Definition at line 47 of file ARLM3.c.
#define znumbr_1 znumbr_
Definition at line 81 of file ARLM3.c.
Referenced by arlm3_().
Function Documentation
int arlm3_ (void)
Definition at line 141 of file ARLM3.c.
References aerr_(), amind_(), apt238_(), atape_(), centr_(), cgoug_1, check_(), clngth, cross_(), delta_(), dshar4_1, elmax, fxcor_1, i__, ifxcor_1, ishr18_1, isv1_1, isv_1, j, k, kdynfl, knumbr_1, l, plane_(), sv1_1, sv_1, vnorm_(), zero, and znumbr_1.
Referenced by apt211_().
 {
     /* Initialized data */
     static integer k14 = 14;
     static integer k17 = 17;
     static integer k20 = 20;
     static integer k21 = 21;
     static integer k22 = 22;
     static doublereal zero = 0.;
     static doublereal zlit1 = .125;
     static integer k11 = 11;
     /* Format strings */
     static char fmt_175[] = "";
     static char fmt_190[] = "";
     static char fmt_230[] = "";
     static char fmt_330[] = "";
     static char fmt_360[] = "";
     static char fmt_440[] = "";
     static char fmt_550[] = "";
     static char fmt_560[] = "";
     static char fmt_565[] = "";
     static char fmt_630[] = "";
     static char fmt_635[] = "";
     static char fmt_740[] = "";
     static char fmt_745[] = "";
     static char fmt_760[] = "";
     static char fmt_810[] = "";
     static char fmt_820[] = "";
     static char fmt_846[] = "";
     static char fmt_875[] = "";
     static char fmt_950[] = "";
     static char fmt_980[] = "";
     static char fmt_1000[] = "";
     static char fmt_1025[] = "";
     static char fmt_1140[] = "";
     static char fmt_1145[] = "";
     static char fmt_1220[] = "";
     static char fmt_1260[] = "";
     static char fmt_1265[] = "";
     static char fmt_1348[] = "";
     static char fmt_1350[] = "";
     static char fmt_1415[] = "";
     static char fmt_1430[] = "";
     static char fmt_1445[] = "";
     /* System generated locals */
     integer i__1, i__2;
     doublereal d__1;
     /* Builtin functions */
     double sqrt(doublereal), d_sign(doublereal *, doublereal *);
     /* Local variables */
     static integer i__, j, k, l;
     static doublereal ps1, ps2, ps3, ps4, ps5, ps6, ps7, ps8, ps9, ds1, ds2,
         ds3, ds4, ds5, ds6, ds7, ds8, ds9, aab, tv;
     static integer jaa, jwr, jpr1, jpr2, ils1;
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen);
 #define jlin ((integer *)&addcom_1 + 46)
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static integer isto;
     static doublereal rc1sc;
     extern /* Subroutine */ int apt238_(integer *);
     static doublereal u1sav[3];
     extern /* Subroutine */ int check_(void), amind_(void), delta_(void),
         atape_(void), plane_(void);
     static doublereal tnsav[3], tpsav[3];
 #define elmax ((doublereal *)&addcom_1)
     static doublereal vtsav[3], spsav[3];
     static integer inmbr, iretn, itsav;
     extern /* Subroutine */ int cross_(doublereal *, doublereal *, doublereal
         *), vnorm_(doublereal *, doublereal *);
     static integer ipchn;
     extern /* Subroutine */ int centr_(void);
 #define ibtflg ((integer *)&addcom_1 + 44)
 #define clngth ((doublereal *)&addcom_1 + 1)
     static integer ipchnl;
 #define kdynfl ((integer *)&addcom_1 + 48)
     /* Assigned format variables */
     static char *iretn_fmt;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /* ...  21. ADDCOM BLOCK */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /*        USE RC1SC FOR PROPER UNITS/ IMPLEMENTATION */
     rc1sc = fxcor_1.rc1 / 4500.;
     cgoug_1.gflg = zero;
     ifxcor_1.numpt1 = ifxcor_1.nmpnts;
     *clngth = (doublereal) knumbr_1.k0;
     jpr1 = knumbr_1.k0;
     jpr2 = ifxcor_1.icscnt;
     ils1 = ifxcor_1.ics + (ifxcor_1.icscnt - knumbr_1.k1) * ifxcor_1.lsv1;
 /*                  INITIALIZATION FOR EACH CS. */
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.tek[i__ - 1] = fxcor_1.te[i__ - 1];
     dshar4_1.tew[i__ - 1] = fxcor_1.te[i__ - 1];
 /* L100: */
     fxcor_1.tak[i__ - 1] = fxcor_1.ta[i__ - 1];
     }
     if (isv_1.ipl[ifxcor_1.ips - 1] == knumbr_1.k0 || isv_1.ipl[ifxcor_1.ids
         - 1] == knumbr_1.k0) {
     goto L130;
     }
     ishr18_1.ipdpl = knumbr_1.k1;
     goto L140;
 L130:
     ishr18_1.ipdpl = 0;
 L140:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* ... SAVE PREVIOUS TI VALUE IN TALT */
     cgoug_1.talt[i__ - 1] = fxcor_1.ti[i__ - 1];
     fxcor_1.tik[i__ - 1] = fxcor_1.ti[i__ - 1];
     i__1 = ils1;
     i__2 = ifxcor_1.lsv1;
     for (k = ifxcor_1.ics; i__2 < 0 ? k >= i__1 : k <= i__1; k += i__2) {
         sv_1.tn[i__ + k * 3 - 4] = fxcor_1.ti[i__ - 1];
 /* L150: */
     }
     }
 L160:
     ishr18_1.j12 = 0;
     jaa = knumbr_1.k0;
     ifxcor_1.is = ifxcor_1.ics;
     ishr18_1.j10 = knumbr_1.k1;
     dshar4_1.dp = fxcor_1.dpmax;
     dshar4_1.dpl = fxcor_1.dpmax;
     i__2 = ils1;
     i__1 = ifxcor_1.lsv1;
     for (i__ = ifxcor_1.ics; i__1 < 0 ? i__ >= i__2 : i__ <= i__2; i__ +=
         i__1) {
     isv1_1.j20[i__ - 1] = 0;
     isv1_1.j23[i__ - 1] = knumbr_1.k1;
     isv1_1.j50[i__ - 1] = -ishr18_1.ipdpl;
     isv1_1.j51[i__ - 1] = 0;
     isv1_1.jph[i__ - 1] = 0;
     isv1_1.notan[i__ - 1] = 0;
 /* L170: */
     sv1_1.dpmx1[i__ - 1] = fxcor_1.dpmax;
     }
     inmbr = k11;
     iretn = 0;
     iretn_fmt = fmt_175;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L175:
     if (ishr18_1.ipdpl != 0) {
     goto L180;
     } else {
     goto L310;
     }
 /*                  CALL CHECK FOR CSD. ADJUST DP SO CS NOT PASSED ON */
 /*                  FIRST DP STEP-OUT. */
 L180:
     inmbr = knumbr_1.k12;
     iretn = 1;
     iretn_fmt = fmt_190;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L190:
     for (l = 1; l <= 3; ++l) {
 /* L200: */
     fxcor_1.ta[l - 1] = fxcor_1.tak[l - 1];
     }
 L210:
     ifxcor_1.is = ifxcor_1.ics;
     jpr2 = -knumbr_1.k1;
     ishr18_1.iws = ifxcor_1.is;
     dshar4_1.dp1 = znumbr_1.z1e6 * rc1sc;
 L220:
     if (isv_1.isftyp[ifxcor_1.is - 1] - 99 >= 0) {
     goto L460;
     } else {
     goto L221;
     }
 L221:
     fxcor_1.te[0] = dshar4_1.tew[0];
     fxcor_1.te[1] = dshar4_1.tew[1];
     fxcor_1.te[2] = dshar4_1.tew[2];
     jpr2 = ifxcor_1.icscnt;
     iretn = 2;
     iretn_fmt = fmt_230;
     goto L9010;
 L230:
     if (ifxcor_1.ier != 0) {
 /* .... OUTPUT WARNING IF NEGATIVE DISTANCE TO CS AT START OF CUT */
     inmbr = -24007;
     aerr_(&inmbr, "ARLM3", (ftnlen)5);
     }
     isv1_1.j50[ifxcor_1.is - 1] = (isv1_1.j50[ifxcor_1.is - 1] + knumbr_1.k1)
         / knumbr_1.k2;
 /* L231: */
     if (znumbr_1.z1 * rc1sc - sv1_1.csd[ifxcor_1.is - 1] >= 0.) {
     goto L238;
     } else {
     goto L232;
     }
 L232:
     if (ishr18_1.ipdpl != 0) {
     goto L236;
     } else {
     goto L260;
     }
 L260:
     if (dshar4_1.dp - sv1_1.csd[ifxcor_1.is - 1] <= 0.) {
     goto L234;
     } else {
     goto L239;
     }
 L234:
     if (sv1_1.csd[ifxcor_1.is - 1] - znumbr_1.z2 * dshar4_1.dp >= 0.) {
     goto L241;
     } else {
     goto L235;
     }
 L235:
     dshar4_1.dp = znumbr_1.z6em1 * sv1_1.csd[ifxcor_1.is - 1];
     goto L241;
 L236:
     if (sv1_1.csd[ifxcor_1.is - 1] - dshar4_1.dp <= 0.) {
     goto L237;
     } else {
     goto L241;
     }
 L237:
     dshar4_1.dp = znumbr_1.z9em1 * sv1_1.csd[ifxcor_1.is - 1];
     goto L241;
 L238:
     if ((d__1 = sv1_1.csd[ifxcor_1.is - 1], abs(d__1)) - sv_1.tau[ifxcor_1.is
         - 1] >= 0.) {
     goto L260;
     } else {
     goto L240;
     }
 L239:
     dshar4_1.dp = sv1_1.csd[ifxcor_1.is - 1];
     goto L241;
 L240:
     dshar4_1.dp = sv_1.tau[ifxcor_1.is - 1];
 L241:
     goto L430;
 /*                  DS AND PS NOT BOTH PLANE. THUS INITIAL STEP-OUT + */
 /*                  CENTR + DELTA FOR INITIAL VALUE DP. */
 L310:
     for (l = 1; l <= 3; ++l) {
 /* L320: */
     fxcor_1.te[l - 1] += zlit1 * rc1sc * fxcor_1.ti[l - 1];
     }
     iretn = 3;
     iretn_fmt = fmt_330;
     goto L9020;
 L330:
     if (ishr18_1.jcr == knumbr_1.k0) {
     goto L350;
     }
     dshar4_1.dp = znumbr_1.z1em2 * fxcor_1.dpmax;
     goto L180;
 L350:
     iretn = 4;
     iretn_fmt = fmt_360;
     goto L9030;
 L360:
     if (ishr18_1.jdr != knumbr_1.k0) {
     goto L180;
     }
     if (dshar4_1.dpl > fxcor_1.dpmax) {
     goto L390;
     }
     dshar4_1.dp = dshar4_1.dpl;
     goto L180;
 L390:
     dshar4_1.dp = fxcor_1.dpmax;
     goto L180;
 /*                  DO ADJUSTMENT OF DP FOR ALL CS. SET DP TO ITS MIN */
 /*                  VALUE, AND IWS TO THE CORRESPONDING IS. */
 L430:
     inmbr = knumbr_1.k13;
     iretn = 5;
     iretn_fmt = fmt_440;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L440:
     if (dshar4_1.dp - dshar4_1.dp1 >= 0.) {
     goto L460;
     } else {
     goto L450;
     }
 L450:
     ishr18_1.iws = ifxcor_1.is;
     dshar4_1.dp1 = dshar4_1.dp;
 L460:
     ifxcor_1.is += ifxcor_1.lsv1;
     if (ils1 >= ifxcor_1.is) {
     goto L220;
     }
     ifxcor_1.is = ishr18_1.iws;
     if (jpr2 >= 0) {
     goto L462;
     } else {
     goto L461;
     }
 L461:
     inmbr = 24006;
     goto L9040;
 /*                  SET DPCNT TO 10. (ERROR 801 WHEN 0.0). IF CS NEAR */
 /*                  (J50=1) AND PS,DS NOT BOTH PLANE THEN BRANCH */
 L462:
     dshar4_1.dpcnt = 30.f;
     dshar4_1.dp = dshar4_1.dp1;
     if (isv1_1.j50[ifxcor_1.is - 1] > knumbr_1.k0 && ishr18_1.ipdpl ==
         knumbr_1.k0) {
     goto L750;
     }
 L490:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L500: */
     fxcor_1.tel[i__ - 1] = fxcor_1.te[i__ - 1];
     }
     if (ishr18_1.ipdpl != knumbr_1.k0) {
     goto L600;
     }
     itsav = isv_1.itseg[ifxcor_1.ips - 1];
     for (i__ = 1; i__ <= 3; ++i__) {
     tnsav[i__ - 1] = sv_1.tn[i__ + ifxcor_1.ips * 3 - 4];
     tpsav[i__ - 1] = sv_1.tp[i__ + ifxcor_1.ips * 3 - 4];
     u1sav[i__ - 1] = sv_1.u1[i__ + ifxcor_1.ips * 3 - 4];
     vtsav[i__ - 1] = sv_1.vt[i__ + ifxcor_1.ips * 3 - 4];
     spsav[i__ - 1] = sv_1.sp[i__ + ifxcor_1.ips * 3 - 4];
 /* L520: */
     dshar4_1.tes[i__ - 1] = fxcor_1.tek[i__ - 1];
     }
 /*                  ********** MAIN LOOP. STEP-OUT DP. ***************** */
 /*                  ***** BRANCH IF DS,PS BOTH PLANE. ELSE CENTR TO **** */
 /*                  ***** PS,DS AND THEN DELTA. IF CUT VECTOR TOO   **** */
 /*                  ***** LONG (JDR=1),THEN TRY AGAIN WITH SHORTER  **** */
 /*                  ***** CUT VECTOR. IF DPCNT=1, FAIL           ******* */
 /*                        CODING 580 TO 600 FOR SETTING CS FAR AWAY */
 L530:
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.ta[i__ - 1] = fxcor_1.tak[i__ - 1];
     dshar4_1.cmove[i__ - 1] = dshar4_1.dp * fxcor_1.tik[i__ - 1];
 /* L540: */
     fxcor_1.te[i__ - 1] = dshar4_1.tes[i__ - 1] + dshar4_1.cmove[i__ - 1];
     }
     inmbr = k14;
     iretn = 6;
     iretn_fmt = fmt_550;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L550:
     if (ishr18_1.ipdpl != knumbr_1.k0) {
     goto L1250;
     }
     iretn = 7;
     iretn_fmt = fmt_560;
     goto L9020;
 L560:
     inmbr = knumbr_1.k15;
     iretn = 8;
     iretn_fmt = fmt_565;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L565:
     if (ishr18_1.jcr == knumbr_1.k0) {
     goto L620;
     }
     if (dshar4_1.dpcnt > znumbr_1.z1) {
     goto L636;
     }
     inmbr = 24001;
     goto L9040;
 L580:
     isv1_1.j20[ifxcor_1.is - 1] = knumbr_1.k1;
     isv1_1.j21[ifxcor_1.is - 1] = knumbr_1.k1;
     sv1_1.csd[ifxcor_1.is - 1] = znumbr_1.z0;
     sv1_1.stck[ifxcor_1.is - 1] = znumbr_1.z1;
     isv1_1.jph[ifxcor_1.is - 1] = knumbr_1.k1;
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.te[i__ - 1] = fxcor_1.tek[i__ - 1];
 /* L590: */
     fxcor_1.ta[i__ - 1] = fxcor_1.tak[i__ - 1];
     }
     isv1_1.j50[ifxcor_1.is - 1] = 0;
     isv1_1.j51[ifxcor_1.is - 1] = 0;
     goto L490;
 L600:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L610: */
     dshar4_1.tes[i__ - 1] = fxcor_1.te[i__ - 1];
     }
     goto L530;
 L620:
     ishr18_1.j10 = 0;
     iretn = 9;
     iretn_fmt = fmt_630;
     goto L9030;
 L630:
     inmbr = knumbr_1.k16;
     iretn = 10;
     iretn_fmt = fmt_635;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L635:
     if (ishr18_1.jdr == knumbr_1.k0) {
     goto L700;
     }
     if (dshar4_1.dpcnt == znumbr_1.z1) {
     goto L1460;
     }
 L636:
     dshar4_1.dpcnt -= znumbr_1.z1;
     isv_1.itseg[ifxcor_1.ips - 1] = itsav;
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tp[i__ + ifxcor_1.ips * 3 - 4] = tpsav[i__ - 1];
     sv_1.tn[i__ + ifxcor_1.ips * 3 - 4] = tnsav[i__ - 1];
     sv_1.u1[i__ + ifxcor_1.ips * 3 - 4] = u1sav[i__ - 1];
     sv_1.vt[i__ + ifxcor_1.ips * 3 - 4] = vtsav[i__ - 1];
     sv_1.sp[i__ + ifxcor_1.ips * 3 - 4] = spsav[i__ - 1];
 /* L660: */
     }
     goto L530;
 /*                  CUT VECTOR OKED BY DELTA. COMPUTE NEW TI */
 L670:
     if (fxcor_1.ti[0] * fxcor_1.tik[0] + fxcor_1.ti[1] * fxcor_1.tik[1] +
         fxcor_1.ti[2] * fxcor_1.tik[2] >= 0.) {
     goto L730;
     } else {
     goto L680;
     }
 L680:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L690: */
     fxcor_1.ti[i__ - 1] = -fxcor_1.ti[i__ - 1];
     }
     goto L730;
 L700:
     for (i__ = 1; i__ <= 3; ++i__) {
     cgoug_1.talt[i__ - 1] = fxcor_1.ti[i__ - 1];
 /* L701: */
     }
     cross_(&sv_1.sn[ifxcor_1.ips * 3 - 3], &sv_1.sn[ifxcor_1.ids * 3 - 3],
         fxcor_1.ti);
     vnorm_(fxcor_1.ti, fxcor_1.ti);
     if (ifxcor_1.ier != 0) {
     goto L710;
     } else {
     goto L670;
     }
 L710:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L720: */
     fxcor_1.ti[i__ - 1] = fxcor_1.te[i__ - 1] - fxcor_1.tek[i__ - 1];
     }
     vnorm_(fxcor_1.ti, fxcor_1.ti);
 /*                  CALL CHECK FOR CSD. IF JCKR = 0, CS NOT NEAR AND TE */
 /*                  IS OUTPUT TO ATAPE. IF JCKR = 1, CS NEAR. THEN SET */
 /*                  TEE TO TE AND DO 3 SURF CENTR,DS,PS,CS. */
 L730:
     iretn = 11;
     iretn_fmt = fmt_740;
     goto L9010;
 L740:
     inmbr = k17;
     iretn = 12;
     iretn_fmt = fmt_745;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L745:
     if (ishr18_1.jckr == knumbr_1.k0) {
     goto L840;
     }
 L750:
     sv1_1.tee[ifxcor_1.is * 3 - 3] = fxcor_1.te[0];
     sv1_1.tee[ifxcor_1.is * 3 - 2] = fxcor_1.te[1];
     sv1_1.tee[ifxcor_1.is * 3 - 1] = fxcor_1.te[2];
     iretn = 13;
     iretn_fmt = fmt_760;
     goto L9020;
 /*                  JCR RETURN FROM 3 SURF PS,DS,CS CENTR  HAS 3 VALUES. */
 /*                  JCR =-1,RESTART CONDITION. IF GT 1 CS, SET FIRST */
 /*                  CS FAR AWAY. STEP-OUT DP ETC. JCR =2, FALSE TANGENCY. */
 /*                  IN THIS CASE IF CENTR MOVE IN TI DIRECTION, RESET */
 /*                  CS FAR AWAY. OTHERWISE IGNORE THIS CENTR MOVE. */
 /*                  IF JCR=0, 3 SURF O.K. GO TO 940. */
 L760:
     if ((i__1 = ishr18_1.jcr - knumbr_1.k1) < 0) {
     goto L770;
     } else if (i__1 == 0) {
     goto L940;
     } else {
     goto L790;
     }
 L770:
     if (ifxcor_1.icscnt > knumbr_1.k1) {
     goto L830;
     }
     inmbr = 24002;
     goto L9040;
 L790:
     if ((fxcor_1.te[0] - sv1_1.tee[ifxcor_1.is * 3 - 3]) * fxcor_1.ti[0] + (
         fxcor_1.te[1] - sv1_1.tee[ifxcor_1.is * 3 - 2]) * fxcor_1.ti[1] +
         (fxcor_1.te[2] - sv1_1.tee[ifxcor_1.is * 3 - 1]) * fxcor_1.ti[2]
         <= 0.) {
     goto L800;
     } else {
     goto L1090;
     }
 L800:
     sv_1.s[ifxcor_1.is - 1] = znumbr_1.z0;
     fxcor_1.te[0] = sv1_1.tee[ifxcor_1.is * 3 - 3];
     fxcor_1.te[1] = sv1_1.tee[ifxcor_1.is * 3 - 2];
     fxcor_1.te[2] = sv1_1.tee[ifxcor_1.is * 3 - 1];
     isto = ifxcor_1.is;
     ifxcor_1.is = ifxcor_1.ips;
     iretn = 14;
     iretn_fmt = fmt_810;
     goto L9050;
 L810:
     ifxcor_1.is = ifxcor_1.ids;
     iretn = 15;
     iretn_fmt = fmt_820;
     goto L9050;
 L820:
     ifxcor_1.is = isto;
     goto L840;
 L830:
     sv_1.s[ifxcor_1.is - 1] = znumbr_1.z5 * dshar4_1.dp;
     goto L180;
 /*                  CS NOT REACHED IN DP STEP-OUT. THEREFORE TE OUTPUT.** */
 /*                  CHECK NMPNTS AND CLNGTH O.K. UPDATE TEK ETC */
 L840:
     iretn = 16;
     iretn_fmt = fmt_846;
     goto L9060;
 L846:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L847: */
     fxcor_1.temp[i__ - 1] = fxcor_1.te[i__ - 1] - fxcor_1.tek[i__ - 1];
     }
 /* L848: */
     fxcor_1.temp[3] = sqrt(fxcor_1.temp[0] * fxcor_1.temp[0] + fxcor_1.temp[1]
          * fxcor_1.temp[1] + fxcor_1.temp[2] * fxcor_1.temp[2]);
     *clngth += fxcor_1.temp[3];
     if (*elmax - *clngth >= 0.) {
     goto L850;
     } else {
     goto L849;
     }
 L849:
     inmbr = 24005;
     goto L9040;
 L850:
     if (ifxcor_1.numpt1 > knumbr_1.k0) {
     goto L870;
     }
     inmbr = 24003;
     goto L9040;
 L870:
     ifxcor_1.numpt1 -= knumbr_1.k1;
     inmbr = knumbr_1.k18;
     iretn = 17;
     iretn_fmt = fmt_875;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L875:
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.tek[i__ - 1] = fxcor_1.te[i__ - 1];
     fxcor_1.tak[i__ - 1] = fxcor_1.ta[i__ - 1];
     fxcor_1.tik[i__ - 1] = fxcor_1.ti[i__ - 1];
     i__1 = ifxcor_1.numsur;
     for (j = ifxcor_1.ips; j <= i__1; ++j) {
         sv_1.tpk[i__ + j * 3 - 4] = sv_1.tp[i__ + j * 3 - 4];
         sv_1.spk[i__ + j * 3 - 4] = sv_1.sp[i__ + j * 3 - 4];
         sv_1.snk[i__ + j * 3 - 4] = sv_1.sn[i__ + j * 3 - 4];
         sv_1.sk[i__ + j * 3 - 4] = sv_1.s[j - 1];
         sv_1.u1k[i__ + j * 3 - 4] = sv_1.u1[i__ + j * 3 - 4];
 /* L900: */
     }
     }
     ipchnl = ipchn;
     dshar4_1.dp1 = dshar4_1.dp;
     isv_1.itsegk[ifxcor_1.ips - 1] = isv_1.itseg[ifxcor_1.ips - 1];
     isv_1.itsegk[ifxcor_1.ids - 1] = isv_1.itseg[ifxcor_1.ids - 1];
     if (isv1_1.j20[ifxcor_1.is - 1] != knumbr_1.k2) {
     goto L920;
     }
 /*                  TERMINATING CUT SEQUENCE COMPUTATION. RESTORE SURF */
 /*                  DATA AT TEE POSITION. */
     fxcor_1.te[0] = sv1_1.tee[ifxcor_1.is * 3 - 3];
     fxcor_1.te[1] = sv1_1.tee[ifxcor_1.is * 3 - 2];
     fxcor_1.te[2] = sv1_1.tee[ifxcor_1.is * 3 - 1];
     fxcor_1.ta[0] = fxcor_1.tal[0];
     fxcor_1.ta[1] = fxcor_1.tal[1];
     fxcor_1.ta[2] = fxcor_1.tal[2];
     sv_1.tp[ifxcor_1.ips * 3 - 3] = ps1;
     sv_1.tp[ifxcor_1.ips * 3 - 2] = ps2;
     sv_1.tp[ifxcor_1.ips * 3 - 1] = ps3;
     sv_1.sn[ifxcor_1.ips * 3 - 3] = ps4;
     sv_1.sn[ifxcor_1.ips * 3 - 2] = ps5;
     sv_1.sn[ifxcor_1.ips * 3 - 1] = ps6;
     sv_1.sp[ifxcor_1.ips * 3 - 3] = ps7;
     sv_1.sp[ifxcor_1.ips * 3 - 2] = ps8;
     sv_1.sp[ifxcor_1.ips * 3 - 1] = ps9;
     sv_1.tp[ifxcor_1.ids * 3 - 3] = ds1;
     sv_1.tp[ifxcor_1.ids * 3 - 2] = ds2;
     sv_1.tp[ifxcor_1.ids * 3 - 1] = ds3;
     sv_1.sn[ifxcor_1.ids * 3 - 3] = ds4;
     sv_1.sn[ifxcor_1.ids * 3 - 2] = ds5;
     sv_1.sn[ifxcor_1.ids * 3 - 1] = ds6;
     sv_1.sp[ifxcor_1.ids * 3 - 3] = ds7;
     sv_1.sp[ifxcor_1.ids * 3 - 2] = ds8;
     sv_1.sp[ifxcor_1.ids * 3 - 1] = ds9;
     goto L1070;
 /*                  NON-TERMINATING CUT VECTOR. IF MORE THAN ONE CS, */
 /*                  RETURN TO FIND CRITICAL CS.ELSE GO TO DP STEP-OUT. */
 L920:
     ifxcor_1.is = ifxcor_1.ics;
     if (ifxcor_1.icscnt <= knumbr_1.k1) {
     goto L260;
     }
     dshar4_1.tew[0] = fxcor_1.te[0];
     dshar4_1.tew[1] = fxcor_1.te[1];
     dshar4_1.tew[2] = fxcor_1.te[2];
     goto L220;
 /*                  3 SURF CENTR TO PS,DS,CS O.K. IF ANY CS VIOLATED */
 /*                  IN THIS MOVE,INDEX THIS AS CRITICAL CS,AND AGAIN DO */
 /*                  3 SURF CENTR. */
 L940:
     sv1_1.tee[ifxcor_1.is * 3 - 3] = fxcor_1.te[0];
     sv1_1.tee[ifxcor_1.is * 3 - 2] = fxcor_1.te[1];
     sv1_1.tee[ifxcor_1.is * 3 - 1] = fxcor_1.te[2];
     ishr18_1.iws = ifxcor_1.is;
     ifxcor_1.is = ifxcor_1.ics;
     inmbr = knumbr_1.k19;
     iretn = 18;
     iretn_fmt = fmt_950;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L950:
     if (ifxcor_1.is > ils1) {
     goto L1040;
     }
     if (ifxcor_1.is == ishr18_1.iws) {
     goto L1030;
     }
     iretn = 19;
     iretn_fmt = fmt_980;
     goto L9050;
 L980:
     if (isv_1.isftyp[ifxcor_1.is - 1] - knumbr_1.k4 != 0) {
     goto L981;
     } else {
     goto L1010;
     }
 L981:
     if (isv1_1.j23[ifxcor_1.is - 1] > knumbr_1.k0) {
     goto L1030;
     }
     sv1_1.stck[ifxcor_1.is - 1] = sv_1.s[ifxcor_1.is - 1] * sv_1.z__[
         ifxcor_1.is - 1] * sv1_1.stck1[ifxcor_1.is - 1];
     inmbr = k20;
     iretn = 20;
     iretn_fmt = fmt_1000;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L1000:
     if (sv1_1.stck[ifxcor_1.is - 1] <= 0.) {
     goto L750;
     } else {
     goto L1030;
     }
 L1010:
     if (isv1_1.j22[ifxcor_1.is - 1] <= 0) {
     goto L1030;
     } else {
     goto L1020;
     }
 L1020:
     ifxcor_1.it = ifxcor_1.ids;
     if (isv1_1.ifl4[ifxcor_1.is - 1] != 0) {
     goto L1021;
     } else {
     goto L1022;
     }
 L1021:
     ifxcor_1.it = ifxcor_1.ips;
 L1022:
     fxcor_1.temp[0] = (sv_1.sp[ifxcor_1.is * 3 - 3] - sv_1.sp[ifxcor_1.it * 3
         - 3]) * sv_1.tn[ifxcor_1.is * 3 - 3] + (sv_1.sp[ifxcor_1.is * 3 -
         2] - sv_1.sp[ifxcor_1.it * 3 - 2]) * sv_1.tn[ifxcor_1.is * 3 - 2]
         + (sv_1.sp[ifxcor_1.is * 3 - 1] - sv_1.sp[ifxcor_1.it * 3 - 1]) *
         sv_1.tn[ifxcor_1.is * 3 - 1];
     sv1_1.stckn[ifxcor_1.is - 1] = fxcor_1.temp[0] * (sv_1.tn[ifxcor_1.is * 3
         - 3] * fxcor_1.ti[0] + sv_1.tn[ifxcor_1.is * 3 - 2] * fxcor_1.ti[
         1] + sv_1.tn[ifxcor_1.is * 3 - 1] * fxcor_1.ti[2]);
     inmbr = k21;
     iretn = 21;
     iretn_fmt = fmt_1025;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L1025:
     if (sv1_1.stckn[ifxcor_1.is - 1] <= 0.) {
     goto L750;
     } else {
     goto L1030;
     }
 L1030:
     ifxcor_1.is += ifxcor_1.lsv1;
     goto L950;
 /*                  CRITICAL CS INDEXED. COMPUTE TI AND SAVE SURF DATA. */
 /*                  COMPUTE V=TEE - TEK. IF THIS MOVE BACKWARDS,SET */
 /*                  S = 5*DP TO  SET THIS CS FAR AWAY */
 L1040:
     ifxcor_1.is = ishr18_1.iws;
     fxcor_1.tal[0] = fxcor_1.ta[0];
     fxcor_1.tal[1] = fxcor_1.ta[1];
     fxcor_1.tal[2] = fxcor_1.ta[2];
     cross_(&sv_1.sn[ifxcor_1.ips * 3 - 3], &sv_1.sn[ifxcor_1.ids * 3 - 3],
         fxcor_1.til);
     vnorm_(fxcor_1.til, fxcor_1.til);
     if (ifxcor_1.ier == knumbr_1.k0) {
     goto L1060;
     }
     fxcor_1.til[0] = fxcor_1.te[0] - fxcor_1.tek[0];
     fxcor_1.til[1] = fxcor_1.te[1] - fxcor_1.tek[1];
     fxcor_1.til[2] = fxcor_1.te[2] - fxcor_1.tek[2];
     vnorm_(fxcor_1.til, fxcor_1.til);
 L1060:
     ps1 = sv_1.tp[ifxcor_1.ips * 3 - 3];
     ps2 = sv_1.tp[ifxcor_1.ips * 3 - 2];
     ps3 = sv_1.tp[ifxcor_1.ips * 3 - 1];
     ps4 = sv_1.sn[ifxcor_1.ips * 3 - 3];
     ps5 = sv_1.sn[ifxcor_1.ips * 3 - 2];
     ps6 = sv_1.sn[ifxcor_1.ips * 3 - 1];
     ps7 = sv_1.sp[ifxcor_1.ips * 3 - 3];
     ps8 = sv_1.sp[ifxcor_1.ips * 3 - 2];
     ps9 = sv_1.sp[ifxcor_1.ips * 3 - 1];
     ds1 = sv_1.tp[ifxcor_1.ids * 3 - 3];
     ds2 = sv_1.tp[ifxcor_1.ids * 3 - 2];
     ds3 = sv_1.tp[ifxcor_1.ids * 3 - 1];
     ds4 = sv_1.sn[ifxcor_1.ids * 3 - 3];
     ds5 = sv_1.sn[ifxcor_1.ids * 3 - 2];
     ds6 = sv_1.sn[ifxcor_1.ids * 3 - 1];
     ds7 = sv_1.sp[ifxcor_1.ids * 3 - 3];
     ds8 = sv_1.sp[ifxcor_1.ids * 3 - 2];
     ds9 = sv_1.sp[ifxcor_1.ids * 3 - 1];
 L1070:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L1080: */
     dshar4_1.v[i__ - 1] = fxcor_1.te[i__ - 1] - fxcor_1.tek[i__ - 1];
     }
     aab = dshar4_1.v[0] * fxcor_1.tik[0] + dshar4_1.v[1] * fxcor_1.tik[1] +
         dshar4_1.v[2] * fxcor_1.tik[2];
 /*     IF(DABS(AAB)- 0.2*TAU(IS))1090,1090,1085 */
 /* L1085: */
     if (aab >= 0.) {
     goto L1100;
     } else {
     goto L1090;
     }
 L1090:
     sv_1.s[ifxcor_1.is - 1] = znumbr_1.z5 * dshar4_1.dp;
     goto L580;
 /*                  MOVE V FORWARD. REVERSE TN(CS) AND RE-DO 3 SURF */
 /*                  CENTR FOR 'PAST' CASE. TEST IF V O.K. BY DELTA */
 L1100:
     dshar4_1.vl = sqrt(dshar4_1.v[0] * dshar4_1.v[0] + dshar4_1.v[1] *
         dshar4_1.v[1] + dshar4_1.v[2] * dshar4_1.v[2]);
     if (isv_1.isftyp[ifxcor_1.is - 1] == knumbr_1.k4) {
     goto L1130;
     }
     if ((sv_1.tn[ifxcor_1.is * 3 - 3] * (fxcor_1.te[0] - fxcor_1.tek[0]) +
         sv_1.tn[ifxcor_1.is * 3 - 2] * (fxcor_1.te[1] - fxcor_1.tek[1]) +
         sv_1.tn[ifxcor_1.is * 3 - 1] * (fxcor_1.te[2] - fxcor_1.tek[2])) *
          sv_1.past[ifxcor_1.is - 1] >= 0.) {
     goto L1130;
     } else {
     goto L1120;
     }
 L1120:
     isv1_1.j50[ifxcor_1.is - 1] = knumbr_1.k1;
     isv1_1.j51[ifxcor_1.is - 1] = knumbr_1.k1;
     sv1_1.plnd1[ifxcor_1.is - 1] = 0.;
     isv1_1.notan[ifxcor_1.is - 1] = 0;
     sv_1.tn[ifxcor_1.is * 3 - 3] = -sv_1.tn[ifxcor_1.is * 3 - 3];
     sv_1.tn[ifxcor_1.is * 3 - 2] = -sv_1.tn[ifxcor_1.is * 3 - 2];
     sv_1.tn[ifxcor_1.is * 3 - 1] = -sv_1.tn[ifxcor_1.is * 3 - 1];
     goto L750;
 L1130:
     ishr18_1.j10 = knumbr_1.k1;
     iretn = 22;
     iretn_fmt = fmt_1140;
     goto L9030;
 L1140:
     inmbr = k22;
     iretn = 23;
     iretn_fmt = fmt_1145;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L1145:
     if (ishr18_1.jdr == knumbr_1.k0) {
     goto L1200;
     }
 /*                  MOVE V NOT O.K. BY DELTA. CSD = 1.2*LENGTH V */
 /*                  ADJUST VALUE OF DP. SET J20=2 FOR SPECIAL */
 /*                  CUT SEQUENCE TERMINATING CALCULATIONS. */
     sv1_1.csd[ifxcor_1.is - 1] = znumbr_1.z12em1 * dshar4_1.vl;
     if (dshar4_1.dp > sv1_1.csd[ifxcor_1.is - 1]) {
     goto L1180;
     }
     if (sv1_1.csd[ifxcor_1.is - 1] < znumbr_1.z2 * dshar4_1.dp) {
     dshar4_1.dp = znumbr_1.z6em1 * sv1_1.csd[ifxcor_1.is - 1];
     }
     goto L1190;
 L1180:
     dshar4_1.dp = sv1_1.csd[ifxcor_1.is - 1];
 L1190:
     dshar4_1.dpcnt = znumbr_1.z10;
     isv1_1.j50[ifxcor_1.is - 1] = 0;
     isv1_1.j51[ifxcor_1.is - 1] = 0;
     isv1_1.j20[ifxcor_1.is - 1] = knumbr_1.k2;
     inmbr = knumbr_1.k23;
     iretn = 24;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
     goto L490;
 /*                  MOVE V O.K.. TEST IFAR FOR CORRECT INTERSECTION */
 L1200:
     jpr2 = ifxcor_1.icscnt;
     if (isv1_1.ifar[ifxcor_1.is - 1] == knumbr_1.k1) {
     goto L1420;
     }
     isv1_1.ifar[ifxcor_1.is - 1] -= knumbr_1.k1;
     if (ishr18_1.ipdpl != knumbr_1.k0) {
     goto L1230;
     }
     iretn = 25;
     iretn_fmt = fmt_1220;
     goto L9060;
 L1220:
     tv = fxcor_1.ti[0] * fxcor_1.til[0] + fxcor_1.ti[1] * fxcor_1.til[1] +
         fxcor_1.ti[2] * fxcor_1.til[2];
     fxcor_1.temp[0] = d_sign(&znumbr_1.z1, &tv);
     fxcor_1.ti[0] = fxcor_1.temp[0] * fxcor_1.til[0];
     fxcor_1.ti[1] = fxcor_1.temp[0] * fxcor_1.til[1];
     fxcor_1.ti[2] = fxcor_1.temp[0] * fxcor_1.til[2];
 L1230:
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.tek[i__ - 1] = fxcor_1.te[i__ - 1];
     fxcor_1.tak[i__ - 1] = fxcor_1.ta[i__ - 1];
 /* L1240: */
     dshar4_1.tew[i__ - 1] = znumbr_1.z3 * sv_1.tau[ifxcor_1.is - 1] *
         fxcor_1.ti[i__ - 1] + fxcor_1.te[i__ - 1];
     }
     jaa = knumbr_1.k1;
     goto L140;
 /*                  ********** SPECIAL ROUTE. DS,PS BOTH PLANE, */
 L1250:
     iretn = 26;
     iretn_fmt = fmt_1260;
     goto L9070;
 L1260:
     inmbr = knumbr_1.k24;
     iretn = 27;
     iretn_fmt = fmt_1265;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L1265:
     if (ishr18_1.jpr < 0) {
     goto L1280;
     } else if (ishr18_1.jpr == 0) {
     goto L1270;
     } else {
     goto L1266;
     }
 L1266:
     jpr1 = 0;
     goto L1290;
 L1270:
     dshar4_1.tew[0] = fxcor_1.te[0];
     dshar4_1.tew[1] = fxcor_1.te[1];
     dshar4_1.tew[2] = fxcor_1.te[2];
     goto L210;
 /*     FALSE TANGENCY - MOVE AWAY FROM STOPPING POINT. */
 L1280:
     if (ishr18_1.jpr + knumbr_1.k2 <= 0) {
     goto L1351;
     } else {
     goto L1281;
     }
 L1281:
     if ((fxcor_1.te[0] - dshar4_1.tew[0]) * fxcor_1.ti[0] + (fxcor_1.te[1] -
         dshar4_1.tew[1]) * fxcor_1.ti[1] + (fxcor_1.te[2] - dshar4_1.tew[
         2]) * fxcor_1.ti[2] <= 0.) {
     goto L1352;
     } else {
     goto L1282;
     }
 L1282:
     fxcor_1.te[0] = znumbr_1.z5em1 * rc1sc * fxcor_1.ti[0] + fxcor_1.te[0];
     fxcor_1.te[1] = znumbr_1.z5em1 * rc1sc * fxcor_1.ti[1] + fxcor_1.te[1];
     fxcor_1.te[2] = znumbr_1.z5em1 * rc1sc * fxcor_1.ti[2] + fxcor_1.te[2];
 /*     IS THIS THE ONLY CHECK SURFACE */
 L1290:
     ishr18_1.iws = ifxcor_1.is;
     ifxcor_1.is = ifxcor_1.ics;
 L1300:
     if (ils1 - ifxcor_1.is >= 0) {
     goto L1330;
     } else {
     goto L1310;
     }
 L1310:
     ifxcor_1.is = ishr18_1.iws;
     if (ishr18_1.jpr >= 0) {
     goto L1200;
     } else {
     goto L1311;
     }
 /*     LOOK FOR TRUE INTERSECTION WITH CHECK SURFACE */
 L1311:
     dshar4_1.tew[0] = fxcor_1.te[0];
     dshar4_1.tew[1] = fxcor_1.te[1];
     dshar4_1.tew[2] = fxcor_1.te[2];
     goto L160;
 L1320:
     ifxcor_1.is += ifxcor_1.lsv1;
     goto L1300;
 L1330:
     if (ifxcor_1.is - ishr18_1.iws != 0) {
     goto L1331;
     } else {
     goto L1320;
     }
 L1331:
     if (isv_1.isftyp[ifxcor_1.is - 1] - 99 >= 0) {
     goto L1320;
     } else {
     goto L1332;
     }
 L1332:
     if (jpr2 <= 0) {
     goto L1310;
     } else {
     goto L1333;
     }
 L1333:
     if (isv_1.isftyp[ifxcor_1.is - 1] - knumbr_1.k4 >= 0) {
     goto L1340;
     } else {
     goto L1334;
     }
 L1334:
     sv_1.tn[ifxcor_1.is * 3 - 3] = sv_1.past[ifxcor_1.is - 1] * fxcor_1.ti[0];
     sv_1.tn[ifxcor_1.is * 3 - 2] = sv_1.past[ifxcor_1.is - 1] * fxcor_1.ti[1];
     sv_1.tn[ifxcor_1.is * 3 - 1] = sv_1.past[ifxcor_1.is - 1] * fxcor_1.ti[2];
 L1340:
     jwr = 0;
     isv_1.jent[ifxcor_1.is - 1] = knumbr_1.k1;
     isv_1.iopset[ifxcor_1.is - 1] = 0;
     isv_1.jtn[ifxcor_1.is - 1] = knumbr_1.k1;
     isv_1.ju1[ifxcor_1.is - 1] = knumbr_1.k1;
     isv_1.jiops[ifxcor_1.is - 1] = 0;
     iretn = 28;
     iretn_fmt = fmt_1348;
     goto L9050;
 L1348:
     if (isv_1.isftyp[ifxcor_1.is - 1] - knumbr_1.k4 != 0) {
     goto L1349;
     } else {
     goto L1400;
     }
 L1349:
     if (isv1_1.j23[ifxcor_1.is - 1] > knumbr_1.k0) {
     goto L1320;
     }
     sv1_1.stck[ifxcor_1.is - 1] = sv1_1.stck1[ifxcor_1.is - 1] * sv_1.z__[
         ifxcor_1.is - 1] * sv_1.s[ifxcor_1.is - 1];
     inmbr = knumbr_1.k25;
     iretn = 29;
     iretn_fmt = fmt_1350;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L1350:
     if (sv1_1.stck[ifxcor_1.is - 1] > (doublereal) knumbr_1.k0) {
     goto L1320;
     }
     goto L1380;
 /*     MOVE WAS BACKWARDS - RESTART TWICE THEN GIVE UP */
 L1351:
     jpr1 += knumbr_1.k1;
     if ((i__1 = jpr1 - knumbr_1.k2) < 0) {
     goto L1270;
     } else if (i__1 == 0) {
     goto L1353;
     } else {
     goto L1352;
     }
 /*     THIS SURFACE INVALID - ELIMINATE FROM CONSIDERATION */
 L1352:
     isv_1.isftyp[ifxcor_1.is - 1] = 99;
     jpr1 = 0;
     fxcor_1.te[0] = fxcor_1.tek[0];
     fxcor_1.te[1] = fxcor_1.tek[1];
     fxcor_1.te[2] = fxcor_1.tek[2];
     goto L1270;
 L1353:
     sv_1.s[ifxcor_1.is - 1] += znumbr_1.z2 * dshar4_1.dp;
     goto L1270;
 L1380:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L1390: */
     fxcor_1.te[i__ - 1] = fxcor_1.tel[i__ - 1];
     }
     jpr2 -= knumbr_1.k1;
     dshar4_1.dp = znumbr_1.z11em1 * sv1_1.csd[ifxcor_1.is - 1];
     goto L1250;
 L1400:
     if (isv1_1.j22[ifxcor_1.is - 1] <= 0) {
     goto L1320;
     } else {
     goto L1410;
     }
 L1410:
     ifxcor_1.it = ifxcor_1.ids;
     if (isv1_1.ifl4[ifxcor_1.is - 1] != 0) {
     goto L1411;
     } else {
     goto L1412;
     }
 L1411:
     ifxcor_1.it = ifxcor_1.ips;
 L1412:
     fxcor_1.temp[0] = (sv_1.sp[ifxcor_1.is * 3 - 3] - sv_1.sp[ifxcor_1.it * 3
         - 3]) * sv_1.tn[ifxcor_1.is * 3 - 3] + (sv_1.sp[ifxcor_1.is * 3 -
         2] - sv_1.sp[ifxcor_1.it * 3 - 2]) * sv_1.tn[ifxcor_1.is * 3 - 2]
         + (sv_1.sp[ifxcor_1.is * 3 - 1] - sv_1.sp[ifxcor_1.it * 3 - 1]) *
         sv_1.tn[ifxcor_1.is * 3 - 1];
     sv1_1.stckn[ifxcor_1.is - 1] = fxcor_1.temp[0] * (sv_1.tn[ifxcor_1.is * 3
         - 3] * fxcor_1.ti[0] + sv_1.tn[ifxcor_1.is * 3 - 2] * fxcor_1.ti[
         1] + sv_1.tn[ifxcor_1.is * 3 - 1] * fxcor_1.ti[2]);
     inmbr = knumbr_1.k26;
     iretn = 30;
     iretn_fmt = fmt_1415;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L1415:
     if (sv1_1.stckn[ifxcor_1.is - 1] <= 0.) {
     goto L1380;
     } else {
     goto L1320;
     }
 L1420:
     inmbr = knumbr_1.k27;
     iretn = 31;
     iretn_fmt = fmt_1430;
     if (*kdynfl != knumbr_1.k0) {
     goto L9000;
     }
 L1430:
     ifxcor_1.icl = knumbr_1.k3;
 /* L1440: */
     iretn = 32;
     iretn_fmt = fmt_1445;
     goto L9060;
 L1445:
     fxcor_1.temp[0] = (doublereal) ((ifxcor_1.is - ifxcor_1.ics) /
         ifxcor_1.lsv1 + knumbr_1.k1);
 L1450:
     return 0;
 L1460:
     inmbr = 24004;
     goto L9040;
 /*     ALL CALLS EXCEPT THOSE TO VNORM AND CROSS HAVE BEEN PLACED IN THIS */
 /*     SECTION TO MINIMIZE STORAGE REQUIREMENTS OF THE 360 */
 L9000:
     apt238_(&inmbr);
     switch (iretn) {
     case 0: goto L175;
     case 1: goto L190;
     case 2: goto L230;
     case 3: goto L330;
     case 4: goto L360;
     case 5: goto L440;
     case 6: goto L550;
     case 7: goto L560;
     case 8: goto L565;
     case 9: goto L630;
     case 10: goto L635;
     case 11: goto L740;
     case 12: goto L745;
     case 13: goto L760;
     case 14: goto L810;
     case 15: goto L820;
     case 16: goto L846;
     case 17: goto L875;
     case 18: goto L950;
     case 19: goto L980;
     case 20: goto L1000;
     case 21: goto L1025;
     case 22: goto L1140;
     case 23: goto L1145;
     case 24: goto L490;
     case 25: goto L1220;
     case 26: goto L1260;
     case 27: goto L1265;
     case 28: goto L1348;
     case 29: goto L1350;
     case 30: goto L1415;
     case 31: goto L1430;
     case 32: goto L1445;
     }
 L9010:
     check_();
     if (ifxcor_1.iaerr > knumbr_1.k0) {
     goto L1450;
     }
     switch (iretn) {
     case 0: goto L175;
     case 1: goto L190;
     case 2: goto L230;
     case 3: goto L330;
     case 4: goto L360;
     case 5: goto L440;
     case 6: goto L550;
     case 7: goto L560;
     case 8: goto L565;
     case 9: goto L630;
     case 10: goto L635;
     case 11: goto L740;
     case 12: goto L745;
     case 13: goto L760;
     case 14: goto L810;
     case 15: goto L820;
     case 16: goto L846;
     case 17: goto L875;
     case 18: goto L950;
     case 19: goto L980;
     case 20: goto L1000;
     case 21: goto L1025;
     case 22: goto L1140;
     case 23: goto L1145;
     case 24: goto L490;
     case 25: goto L1220;
     case 26: goto L1260;
     case 27: goto L1265;
     case 28: goto L1348;
     case 29: goto L1350;
     case 30: goto L1415;
     case 31: goto L1430;
     case 32: goto L1445;
     }
 L9020:
     centr_();
     if (ifxcor_1.iaerr > knumbr_1.k0) {
     goto L1450;
     }
     switch (iretn) {
     case 0: goto L175;
     case 1: goto L190;
     case 2: goto L230;
     case 3: goto L330;
     case 4: goto L360;
     case 5: goto L440;
     case 6: goto L550;
     case 7: goto L560;
     case 8: goto L565;
     case 9: goto L630;
     case 10: goto L635;
     case 11: goto L740;
     case 12: goto L745;
     case 13: goto L760;
     case 14: goto L810;
     case 15: goto L820;
     case 16: goto L846;
     case 17: goto L875;
     case 18: goto L950;
     case 19: goto L980;
     case 20: goto L1000;
     case 21: goto L1025;
     case 22: goto L1140;
     case 23: goto L1145;
     case 24: goto L490;
     case 25: goto L1220;
     case 26: goto L1260;
     case 27: goto L1265;
     case 28: goto L1348;
     case 29: goto L1350;
     case 30: goto L1415;
     case 31: goto L1430;
     case 32: goto L1445;
     }
 L9030:
     delta_();
     if (ifxcor_1.iaerr > knumbr_1.k0) {
     goto L1450;
     }
     switch (iretn) {
     case 0: goto L175;
     case 1: goto L190;
     case 2: goto L230;
     case 3: goto L330;
     case 4: goto L360;
     case 5: goto L440;
     case 6: goto L550;
     case 7: goto L560;
     case 8: goto L565;
     case 9: goto L630;
     case 10: goto L635;
     case 11: goto L740;
     case 12: goto L745;
     case 13: goto L760;
     case 14: goto L810;
     case 15: goto L820;
     case 16: goto L846;
     case 17: goto L875;
     case 18: goto L950;
     case 19: goto L980;
     case 20: goto L1000;
     case 21: goto L1025;
     case 22: goto L1140;
     case 23: goto L1145;
     case 24: goto L490;
     case 25: goto L1220;
     case 26: goto L1260;
     case 27: goto L1265;
     case 28: goto L1348;
     case 29: goto L1350;
     case 30: goto L1415;
     case 31: goto L1430;
     case 32: goto L1445;
     }
 L9040:
     aerr_(&inmbr, "ARLM3   ", (ftnlen)8);
     goto L1450;
 L9050:
     amind_();
     if (ifxcor_1.iaerr > knumbr_1.k0) {
     goto L1450;
     }
     switch (iretn) {
     case 0: goto L175;
     case 1: goto L190;
     case 2: goto L230;
     case 3: goto L330;
     case 4: goto L360;
     case 5: goto L440;
     case 6: goto L550;
     case 7: goto L560;
     case 8: goto L565;
     case 9: goto L630;
     case 10: goto L635;
     case 11: goto L740;
     case 12: goto L745;
     case 13: goto L760;
     case 14: goto L810;
     case 15: goto L820;
     case 16: goto L846;
     case 17: goto L875;
     case 18: goto L950;
     case 19: goto L980;
     case 20: goto L1000;
     case 21: goto L1025;
     case 22: goto L1140;
     case 23: goto L1145;
     case 24: goto L490;
     case 25: goto L1220;
     case 26: goto L1260;
     case 27: goto L1265;
     case 28: goto L1348;
     case 29: goto L1350;
     case 30: goto L1415;
     case 31: goto L1430;
     case 32: goto L1445;
     }
 L9060:
     atape_();
     switch (iretn) {
     case 0: goto L175;
     case 1: goto L190;
     case 2: goto L230;
     case 3: goto L330;
     case 4: goto L360;
     case 5: goto L440;
     case 6: goto L550;
     case 7: goto L560;
     case 8: goto L565;
     case 9: goto L630;
     case 10: goto L635;
     case 11: goto L740;
     case 12: goto L745;
     case 13: goto L760;
     case 14: goto L810;
     case 15: goto L820;
     case 16: goto L846;
     case 17: goto L875;
     case 18: goto L950;
     case 19: goto L980;
     case 20: goto L1000;
     case 21: goto L1025;
     case 22: goto L1140;
     case 23: goto L1145;
     case 24: goto L490;
     case 25: goto L1220;
     case 26: goto L1260;
     case 27: goto L1265;
     case 28: goto L1348;
     case 29: goto L1350;
     case 30: goto L1415;
     case 31: goto L1430;
     case 32: goto L1445;
     }
 L9070:
     plane_();
     if (ifxcor_1.iaerr > knumbr_1.k0) {
     goto L1450;
     }
     switch (iretn) {
     case 0: goto L175;
     case 1: goto L190;
     case 2: goto L230;
     case 3: goto L330;
     case 4: goto L360;
     case 5: goto L440;
     case 6: goto L550;
     case 7: goto L560;
     case 8: goto L565;
     case 9: goto L630;
     case 10: goto L635;
     case 11: goto L740;
     case 12: goto L745;
     case 13: goto L760;
     case 14: goto L810;
     case 15: goto L820;
     case 16: goto L846;
     case 17: goto L875;
     case 18: goto L950;
     case 19: goto L980;
     case 20: goto L1000;
     case 21: goto L1025;
     case 22: goto L1140;
     case 23: goto L1145;
     case 24: goto L490;
     case 25: goto L1220;
     case 26: goto L1260;
     case 27: goto L1265;
     case 28: goto L1348;
     case 29: goto L1350;
     case 30: goto L1415;
     case 31: goto L1430;
     case 32: goto L1445;
     }
 } /* arlm3_ */
Variable Documentation
doublereal a
Definition at line 18 of file ARLM3.c.
doublereal addcom[25]
Definition at line 126 of file ARLM3.c.
struct { ... } addcom_
doublereal alp
Definition at line 28 of file ARLM3.c.
doublereal ax4[3]
Definition at line 28 of file ARLM3.c.
doublereal b
Definition at line 18 of file ARLM3.c.
doublereal c__
Definition at line 18 of file ARLM3.c.
doublereal cagl
Definition at line 28 of file ARLM3.c.
doublereal cc[15]
Definition at line 50 of file ARLM3.c.
doublereal cendis
Definition at line 18 of file ARLM3.c.
struct { ... } cgoug_
struct { ... } charct_
doublereal cmove[3]
Definition at line 18 of file ARLM3.c.
doublereal com1
Definition at line 18 of file ARLM3.c.
doublereal com4
Definition at line 18 of file ARLM3.c.
doublereal corrad[8]
Definition at line 43 of file ARLM3.c.
doublereal cos1[5]
Definition at line 67 of file ARLM3.c.
doublereal cplfl[5]
Definition at line 67 of file ARLM3.c.
doublereal cptst[5]
Definition at line 67 of file ARLM3.c.
doublereal csd[5]
Definition at line 67 of file ARLM3.c.
doublereal cutdat[7]
Definition at line 28 of file ARLM3.c.
doublereal d1
Definition at line 18 of file ARLM3.c.
doublereal d2a
Definition at line 18 of file ARLM3.c.
doublereal degrad
Definition at line 76 of file ARLM3.c.
doublereal dir[3]
Definition at line 18 of file ARLM3.c.
doublereal dp
Definition at line 18 of file ARLM3.c.
doublereal dp1
Definition at line 18 of file ARLM3.c.
doublereal dpcnt
Definition at line 18 of file ARLM3.c.
doublereal dpe
Definition at line 18 of file ARLM3.c.
doublereal dpi
Definition at line 18 of file ARLM3.c.
doublereal dpl
Definition at line 18 of file ARLM3.c.
doublereal dplan[15]
Definition at line 67 of file ARLM3.c.
doublereal dpmax
Definition at line 28 of file ARLM3.c.
doublereal dpmx1[5]
Definition at line 67 of file ARLM3.c.
struct { ... } dshar4_
doublereal eps1[5]
Definition at line 50 of file ARLM3.c.
doublereal eps2[5]
Definition at line 50 of file ARLM3.c.
doublereal eps3[5]
Definition at line 50 of file ARLM3.c.
doublereal eps4[5]
Definition at line 50 of file ARLM3.c.
doublereal eps6[5]
Definition at line 50 of file ARLM3.c.
doublereal eps8[5]
Definition at line 50 of file ARLM3.c.
doublereal flipck
Definition at line 18 of file ARLM3.c.
doublereal fwd[3]
Definition at line 18 of file ARLM3.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file ARLM3.c.
doublereal gflg
Definition at line 132 of file ARLM3.c.
doublereal hi
Definition at line 28 of file ARLM3.c.
integer i3dflg
Definition at line 100 of file ARLM3.c.
integer iaerr
Definition at line 100 of file ARLM3.c.
integer iafl[5]
Definition at line 84 of file ARLM3.c.
integer iamdct
Definition at line 110 of file ARLM3.c.
integer iautps
Definition at line 100 of file ARLM3.c.
integer ibegin
Definition at line 100 of file ARLM3.c.
integer ic
Definition at line 100 of file ARLM3.c.
integer icanon[5]
Definition at line 84 of file ARLM3.c.
integer icheck
Definition at line 100 of file ARLM3.c.
integer icl
Definition at line 100 of file ARLM3.c.
integer ics
Definition at line 100 of file ARLM3.c.
integer icscnt
Definition at line 100 of file ARLM3.c.
integer ictdef
Definition at line 100 of file ARLM3.c.
integer icut
Definition at line 100 of file ARLM3.c.
integer ids
Definition at line 100 of file ARLM3.c.
integer ier
Definition at line 100 of file ARLM3.c.
integer ifar[5]
Definition at line 93 of file ARLM3.c.
integer ifl4[5]
Definition at line 93 of file ARLM3.c.
struct { ... } ifxcor_
integer igo
Definition at line 100 of file ARLM3.c.
integer igoto
Definition at line 100 of file ARLM3.c.
integer igoug
Definition at line 100 of file ARLM3.c.
integer igs
Definition at line 100 of file ARLM3.c.
integer index[5]
Definition at line 84 of file ARLM3.c.
integer indir__[5]
Definition at line 84 of file ARLM3.c.
integer inops
Definition at line 100 of file ARLM3.c.
integer iop[5]
Definition at line 84 of file ARLM3.c.
integer iopset[5]
Definition at line 84 of file ARLM3.c.
integer ipdpl
Definition at line 110 of file ARLM3.c.
integer ipl[5]
Definition at line 84 of file ARLM3.c.
integer ips
Definition at line 100 of file ARLM3.c.
integer ipsdef
Definition at line 100 of file ARLM3.c.
integer ipt
Definition at line 110 of file ARLM3.c.
integer ipt1
Definition at line 100 of file ARLM3.c.
integer is
Definition at line 100 of file ARLM3.c.
integer iseg
Definition at line 100 of file ARLM3.c.
integer iseqno
Definition at line 100 of file ARLM3.c.
integer isfidn[5]
Definition at line 84 of file ARLM3.c.
integer isftyp[5]
Definition at line 84 of file ARLM3.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 84 of file ARLM3.c.
integer isrch
Definition at line 100 of file ARLM3.c.
integer istrup
Definition at line 100 of file ARLM3.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 84 of file ARLM3.c.
integer it
Definition at line 100 of file ARLM3.c.
integer itlon[5]
Definition at line 84 of file ARLM3.c.
integer itseg[5]
Definition at line 84 of file ARLM3.c.
integer itsegk[5]
Definition at line 84 of file ARLM3.c.
integer iunfl[5]
Definition at line 84 of file ARLM3.c.
integer iws
Definition at line 110 of file ARLM3.c.
integer j10
Definition at line 110 of file ARLM3.c.
integer j12
Definition at line 110 of file ARLM3.c.
integer j13
Definition at line 110 of file ARLM3.c.
integer j20[5]
Definition at line 93 of file ARLM3.c.
integer j21[5]
Definition at line 93 of file ARLM3.c.
integer j22[5]
Definition at line 93 of file ARLM3.c.
integer j23[5]
Definition at line 93 of file ARLM3.c.
integer j50[5]
Definition at line 93 of file ARLM3.c.
integer j51[5]
Definition at line 93 of file ARLM3.c.
integer j54
Definition at line 110 of file ARLM3.c.
integer jbr
Definition at line 100 of file ARLM3.c.
integer jckr
Definition at line 110 of file ARLM3.c.
integer jcnt1
Definition at line 110 of file ARLM3.c.
integer jcnt2
Definition at line 110 of file ARLM3.c.
integer jcnt3
Definition at line 110 of file ARLM3.c.
integer jcpr
Definition at line 110 of file ARLM3.c.
integer jcr
Definition at line 110 of file ARLM3.c.
integer jdr
Definition at line 110 of file ARLM3.c.
integer jent[5]
Definition at line 84 of file ARLM3.c.
integer jfind
Definition at line 110 of file ARLM3.c.
integer jgr
Definition at line 110 of file ARLM3.c.
integer jiops[5]
Definition at line 84 of file ARLM3.c.
integer jmin
Definition at line 110 of file ARLM3.c.
integer jminr
Definition at line 110 of file ARLM3.c.
integer jph[5]
Definition at line 93 of file ARLM3.c.
integer jpr
Definition at line 110 of file ARLM3.c.
integer jpxr
Definition at line 110 of file ARLM3.c.
integer jsw
Definition at line 100 of file ARLM3.c.
integer jtkf
Definition at line 110 of file ARLM3.c.
integer jtlflg[5]
Definition at line 84 of file ARLM3.c.
integer jtn[5]
Definition at line 84 of file ARLM3.c.
integer jtr
Definition at line 110 of file ARLM3.c.
integer ju1[5]
Definition at line 84 of file ARLM3.c.
integer k0
Definition at line 118 of file ARLM3.c.
integer k1
Definition at line 118 of file ARLM3.c.
integer k10
Definition at line 118 of file ARLM3.c.
integer k1013
Definition at line 118 of file ARLM3.c.
integer k12
Definition at line 118 of file ARLM3.c.
integer k13
Definition at line 118 of file ARLM3.c.
integer k15
Definition at line 118 of file ARLM3.c.
integer k16
Definition at line 118 of file ARLM3.c.
integer k18
Definition at line 118 of file ARLM3.c.
integer k19
Definition at line 118 of file ARLM3.c.
integer k1e4
Definition at line 118 of file ARLM3.c.
integer k1e6
Definition at line 118 of file ARLM3.c.
integer k2
Definition at line 118 of file ARLM3.c.
integer k23
Definition at line 118 of file ARLM3.c.
integer k24
Definition at line 118 of file ARLM3.c.
integer k25
Definition at line 118 of file ARLM3.c.
integer k26
Definition at line 118 of file ARLM3.c.
integer k27
Definition at line 118 of file ARLM3.c.
integer k29
Definition at line 118 of file ARLM3.c.
integer k3
Definition at line 118 of file ARLM3.c.
integer k30
Definition at line 118 of file ARLM3.c.
integer k31
Definition at line 118 of file ARLM3.c.
integer k32
Definition at line 118 of file ARLM3.c.
integer k33
Definition at line 118 of file ARLM3.c.
integer k34
Definition at line 118 of file ARLM3.c.
integer k4
Definition at line 118 of file ARLM3.c.
integer k44
Definition at line 118 of file ARLM3.c.
integer k45
Definition at line 118 of file ARLM3.c.
integer k46
Definition at line 118 of file ARLM3.c.
integer k47
Definition at line 118 of file ARLM3.c.
integer k48
Definition at line 118 of file ARLM3.c.
integer k5
Definition at line 118 of file ARLM3.c.
integer k50
Definition at line 118 of file ARLM3.c.
integer k51
Definition at line 118 of file ARLM3.c.
integer k52
Definition at line 118 of file ARLM3.c.
integer k6
Definition at line 118 of file ARLM3.c.
integer k7
Definition at line 118 of file ARLM3.c.
integer k8
Definition at line 118 of file ARLM3.c.
integer k9
Definition at line 118 of file ARLM3.c.
integer km1
Definition at line 118 of file ARLM3.c.
struct { ... } knumbr_
integer limfl[5]
Definition at line 84 of file ARLM3.c.
integer lsv
Definition at line 100 of file ARLM3.c.
integer lsv1
Definition at line 100 of file ARLM3.c.
integer mantax
Definition at line 100 of file ARLM3.c.
integer mdic
Definition at line 110 of file ARLM3.c.
char modfer[6]
Definition at line 37 of file ARLM3.c.
integer motmod
Definition at line 100 of file ARLM3.c.
integer msav
Definition at line 100 of file ARLM3.c.
integer mulout
Definition at line 100 of file ARLM3.c.
integer nmbseg
Definition at line 100 of file ARLM3.c.
integer nmpnts
Definition at line 100 of file ARLM3.c.
integer notan[5]
Definition at line 93 of file ARLM3.c.
integer nrec
Definition at line 100 of file ARLM3.c.
integer numax
Definition at line 100 of file ARLM3.c.
integer numcnt
Definition at line 100 of file ARLM3.c.
integer nump
Definition at line 100 of file ARLM3.c.
integer numpt1
Definition at line 100 of file ARLM3.c.
integer numsfs
Definition at line 100 of file ARLM3.c.
integer numsur
Definition at line 100 of file ARLM3.c.
integer nw
Definition at line 100 of file ARLM3.c.
integer nwds
Definition at line 100 of file ARLM3.c.
doublereal ogle[3]
Definition at line 18 of file ARLM3.c.
doublereal p1[3]
Definition at line 18 of file ARLM3.c.
doublereal p2[3]
Definition at line 18 of file ARLM3.c.
doublereal param[6]
Definition at line 18 of file ARLM3.c.
doublereal past[5]
Definition at line 50 of file ARLM3.c.
doublereal pi
Definition at line 76 of file ARLM3.c.
doublereal plncs[5]
Definition at line 67 of file ARLM3.c.
doublereal plnd[5]
Definition at line 50 of file ARLM3.c.
doublereal plnd1[5]
Definition at line 67 of file ARLM3.c.
doublereal plnv[15]
Definition at line 50 of file ARLM3.c.
doublereal pltst[5]
Definition at line 67 of file ARLM3.c.
doublereal pmove[3]
Definition at line 28 of file ARLM3.c.
doublereal r__[6]
Definition at line 18 of file ARLM3.c.
doublereal ra
Definition at line 28 of file ARLM3.c.
doublereal rc[5]
Definition at line 50 of file ARLM3.c.
doublereal rc1
Definition at line 28 of file ARLM3.c.
doublereal rdrn
Definition at line 18 of file ARLM3.c.
doublereal refpnt[3]
Definition at line 18 of file ARLM3.c.
doublereal ri[8]
Definition at line 43 of file ARLM3.c.
doublereal s[5]
Definition at line 50 of file ARLM3.c.
doublereal sagl
Definition at line 28 of file ARLM3.c.
doublereal save[5]
Definition at line 50 of file ARLM3.c.
doublereal savpar[4]
Definition at line 18 of file ARLM3.c.
doublereal seg[9]
Definition at line 18 of file ARLM3.c.
doublereal sfvct[15]
Definition at line 50 of file ARLM3.c.
doublereal shilf
Definition at line 132 of file ARLM3.c.
doublereal sk[15]
Definition at line 50 of file ARLM3.c.
doublereal slope
Definition at line 18 of file ARLM3.c.
doublereal slx[15]
Definition at line 50 of file ARLM3.c.
doublereal sn[15]
Definition at line 50 of file ARLM3.c.
doublereal snk[15]
Definition at line 50 of file ARLM3.c.
doublereal snl[15]
Definition at line 50 of file ARLM3.c.
doublereal sp[15]
Definition at line 50 of file ARLM3.c.
doublereal spg[3]
Definition at line 132 of file ARLM3.c.
doublereal spk[15]
Definition at line 50 of file ARLM3.c.
doublereal spl[15]
Definition at line 50 of file ARLM3.c.
doublereal sqroot
Definition at line 18 of file ARLM3.c.
doublereal stck[5]
Definition at line 67 of file ARLM3.c.
doublereal stck1[5]
Definition at line 67 of file ARLM3.c.
doublereal stck2[5]
Definition at line 67 of file ARLM3.c.
doublereal stckn[5]
Definition at line 67 of file ARLM3.c.
doublereal strtno
Definition at line 28 of file ARLM3.c.
doublereal surd
Definition at line 28 of file ARLM3.c.
struct { ... } sv1_
struct { ... } sv_
doublereal svgl
Definition at line 132 of file ARLM3.c.
doublereal ta[3]
Definition at line 28 of file ARLM3.c.
doublereal tak[3]
Definition at line 28 of file ARLM3.c.
doublereal tal[3]
Definition at line 28 of file ARLM3.c.
doublereal talt[3]
Definition at line 132 of file ARLM3.c.
doublereal tangl
Definition at line 18 of file ARLM3.c.
doublereal tanhi[8]
Definition at line 43 of file ARLM3.c.
doublereal tanlo[8]
Definition at line 43 of file ARLM3.c.
doublereal tau[5]
Definition at line 50 of file ARLM3.c.
doublereal tau1[5]
Definition at line 50 of file ARLM3.c.
doublereal tau2[5]
Definition at line 50 of file ARLM3.c.
doublereal tcont[9]
Definition at line 43 of file ARLM3.c.
doublereal te[3]
Definition at line 28 of file ARLM3.c.
doublereal tee[15]
Definition at line 67 of file ARLM3.c.
doublereal tek[3]
Definition at line 28 of file ARLM3.c.
doublereal tel[3]
Definition at line 28 of file ARLM3.c.
doublereal tem[10]
Definition at line 28 of file ARLM3.c.
doublereal temp[24]
Definition at line 28 of file ARLM3.c.
doublereal tes[3]
Definition at line 18 of file ARLM3.c.
doublereal tew[3]
Definition at line 18 of file ARLM3.c.
doublereal th[5]
Definition at line 50 of file ARLM3.c.
doublereal ti[3]
Definition at line 28 of file ARLM3.c.
doublereal tik[3]
Definition at line 28 of file ARLM3.c.
doublereal til[3]
Definition at line 28 of file ARLM3.c.
doublereal tlhit
Definition at line 28 of file ARLM3.c.
doublereal tlhite[8]
Definition at line 43 of file ARLM3.c.
doublereal tlinc[9]
Definition at line 43 of file ARLM3.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file ARLM3.c.
doublereal tn[15]
Definition at line 50 of file ARLM3.c.
doublereal tnl[15]
Definition at line 67 of file ARLM3.c.
doublereal toolht[15]
Definition at line 50 of file ARLM3.c.
doublereal toolwd[5]
Definition at line 50 of file ARLM3.c.
doublereal tp[15]
Definition at line 50 of file ARLM3.c.
doublereal tpg[3]
Definition at line 132 of file ARLM3.c.
doublereal tpk[15]
Definition at line 50 of file ARLM3.c.
doublereal u1[15]
Definition at line 50 of file ARLM3.c.
doublereal u1k[15]
Definition at line 50 of file ARLM3.c.
doublereal u2[3]
Definition at line 18 of file ARLM3.c.
doublereal umax[8]
Definition at line 43 of file ARLM3.c.
doublereal unn
Definition at line 18 of file ARLM3.c.
doublereal upp
Definition at line 18 of file ARLM3.c.
doublereal uvec[3]
Definition at line 18 of file ARLM3.c.
doublereal v[3]
Definition at line 18 of file ARLM3.c.
doublereal varble[5]
Definition at line 50 of file ARLM3.c.
doublereal vint
Definition at line 18 of file ARLM3.c.
doublereal vl
Definition at line 18 of file ARLM3.c.
doublereal vndir[15]
Definition at line 50 of file ARLM3.c.
doublereal vnn
Definition at line 18 of file ARLM3.c.
doublereal vpp
Definition at line 18 of file ARLM3.c.
doublereal vt[15]
Definition at line 50 of file ARLM3.c.
doublereal vtem
Definition at line 28 of file ARLM3.c.
doublereal z0
Definition at line 76 of file ARLM3.c.
doublereal z1
Definition at line 76 of file ARLM3.c.
doublereal z10
Definition at line 76 of file ARLM3.c.
doublereal z11em1
Definition at line 76 of file ARLM3.c.
doublereal z12em1
Definition at line 76 of file ARLM3.c.
doublereal z1e38
Definition at line 76 of file ARLM3.c.
doublereal z1e6
Definition at line 76 of file ARLM3.c.
doublereal z1em1
Definition at line 76 of file ARLM3.c.
doublereal z1em2
Definition at line 76 of file ARLM3.c.
doublereal z1em3
Definition at line 76 of file ARLM3.c.
doublereal z1em5
Definition at line 76 of file ARLM3.c.
doublereal z1em6
Definition at line 76 of file ARLM3.c.
doublereal z1em7
Definition at line 76 of file ARLM3.c.
doublereal z1em9
Definition at line 76 of file ARLM3.c.
doublereal z2
Definition at line 76 of file ARLM3.c.
doublereal z3
Definition at line 76 of file ARLM3.c.
doublereal z5
Definition at line 76 of file ARLM3.c.
doublereal z5em1
Definition at line 76 of file ARLM3.c.
doublereal z5em6
Definition at line 76 of file ARLM3.c.
doublereal z6em1
Definition at line 76 of file ARLM3.c.
doublereal z90
Definition at line 76 of file ARLM3.c.
doublereal z9em1
Definition at line 76 of file ARLM3.c.
doublereal z__[5]
Definition at line 50 of file ARLM3.c.
doublereal zl
Definition at line 18 of file ARLM3.c.
doublereal zl1
Definition at line 18 of file ARLM3.c.
doublereal zlnorm[3]
Definition at line 18 of file ARLM3.c.
doublereal zlpnt[3]
Definition at line 18 of file ARLM3.c.
doublereal zm1
Definition at line 76 of file ARLM3.c.
struct { ... } znumbr_