My Project: ARTIME.c File Reference
ARTIME.c File Reference
#include "f2c.h"
Macros
#define atime_1 atime_
Functions
int artime_ (void)
Variables
struct {
char ctime [8]
char cdate [9]
} atime_
Macro Definition Documentation
#define atime_1 atime_
Definition at line 21 of file ARTIME.c.
Referenced by artime_().
Function Documentation
int artime_ (void)
Definition at line 52 of file ARTIME.c.
References atime_1, date_(), and time_().
Referenced by sprvis_0_().
 {
     extern /* Subroutine */ int date_(char *, ftnlen), time_(char *, ftnlen);
     time_(atime_1.ctime, (ftnlen)8);
     date_(atime_1.cdate, (ftnlen)9);
     return 0;
 } /* artime_ */
Variable Documentation
struct { ... } atime_
char cdate[9]
Definition at line 18 of file ARTIME.c.
char ctime[8]
Definition at line 18 of file ARTIME.c.