My Project: ASNADZ.c File Reference
ASNADZ.c File Reference
#include "f2c.h"
Macros
#define il_1 il_
#define asnadd ((integer *)&il_1 + 14)
Functions
int asnadz_ (integer *iadd, integer *itake)
Variables
struct {
integer il [21]
} il_
Macro Definition Documentation
#define asnadd ((integer *)&il_1 + 14)
Referenced by asnadz_().
#define il_1 il_
Definition at line 21 of file ASNADZ.c.
Function Documentation
int asnadz_ (integer * iadd, integer * itake)
Definition at line 37 of file ASNADZ.c.
References argcvt_(), asnadd, onearg_(), opcode_(), and rlslin_().
Referenced by comstr_(), and macrec_().
 {
     /* Local variables */
 #define asnadd ((integer *)&il_1 + 14)
     extern /* Subroutine */ int opcode_(integer *), onearg_(integer *),
         argcvt_(integer *), rlslin_(void);
 /*       16.    LITERALS FOR I. L. OPERATION CODES */
 /* ASNADD:      CONTAINS COMMAND CODE (15) FOR ASNADD COMMAND */
 /* * */
 /* PURPOSE      TO GENERATE AND OUTPUT TO THE I.L. INTERNAL */
 /*              RECORD IMAGE (ILFILE) THE ASNADD I.L. COMMAND */
 /*              THAT STORES THE ADDRESS OF AN ASSIGNED VALUE */
 /*              AS THE VALUE OF A MACRO VARIABLE. */
 /* ARGUMENTS    IADD     NAME TABLE (NAMTBL) INDEX OF MACRO VARIABLE */
 /*              ITAKE    NAME TABLE INDEX OF ASSIGNED VALUE. */
 /* NOTES        INDIRECT ADDRESSING EMPLOYED TO RETRIEVE */
 /*              ASSIGNED VALUE. */
 /* ** */
     opcode_(asnadd);
     onearg_(iadd);
     argcvt_(itake);
     rlslin_();
     return 0;
 } /* asnadz_ */
Variable Documentation
integer il[21]
Definition at line 18 of file ASNADZ.c.
struct { ... } il_