My Project: ASNJPZ.c File Reference
ASNJPZ.c File Reference
#include "f2c.h"
Macros
#define il_1 il_
#define asnjmp ((integer *)&il_1 + 15)
Functions
int asnjpz_ (integer *ilbl, integer *itake)
Variables
struct {
integer il [21]
} il_
Macro Definition Documentation
#define asnjmp ((integer *)&il_1 + 15)
Referenced by asnjpz_().
#define il_1 il_
Definition at line 21 of file ASNJPZ.c.
Function Documentation
int asnjpz_ (integer * ilbl, integer * itake)
Definition at line 36 of file ASNJPZ.c.
References asnjmp, opcode_(), rlslin_(), and twoarg_().
Referenced by comstr_().
 {
     /* Local variables */
     extern /* Subroutine */ int opcode_(integer *);
 #define asnjmp ((integer *)&il_1 + 15)
     extern /* Subroutine */ int twoarg_(integer *, integer *), rlslin_(void);
 /*       16.    LITERALS FOR I. L. OPERATION CODES */
 /* ASNJMP:      CONTAINS COMMAND CODE (16) FOR ASNJMP COMMAND */
 /* * */
 /* PURPOSE      TO GENERATE AND OUTPUT TO THE I.L. INTERNAL */
 /*              RECORD IMAGE (ILFILE) THE ASNJPZ I.L. */
 /*              COMMAND THAT STORES THE ADDRESS OF A LABEL */
 /*              AS THE VALUE OF A MACRO VARIABLE. */
 /* ARGUMENTS    ILBL    NAME TABLE (NAMTBL) INDEX OF MACRO VARIABLE. */
 /*              ITAKE   NAME TABLE (NAMTBL) INDEX OF LABEL. */
 /* ** */
     opcode_(asnjmp);
     twoarg_(ilbl, itake);
     rlslin_();
     return 0;
 } /* asnjpz_ */
Variable Documentation
integer il[21]
Definition at line 18 of file ASNJPZ.c.
struct { ... } il_