My Project: ATAPXC.c File Reference
ATAPXC.c File Reference
#include "f2c.h"
Functions
int atapxc_0_ (int n__, integer *file1, integer *file2)
int atapxc_ (integer *file1, integer *file2)
int tapech_ (integer *file1, integer *file2)
Function Documentation
int atapxc_ (integer * file1, integer * file2)
Definition at line 48 of file ATAPXC.c.
References atapxc_0_().
 {
     return atapxc_0_(0, file1, file2);
     }
int atapxc_0_ (int n__, integer * file1, integer * file2)
Definition at line 17 of file ATAPXC.c.
References i__.
Referenced by atapxc_(), and tapech_().
 {
     static integer i__;
 /*  * ATAPXC *  VAX11 FORTRAN 77 VERSION  27.8.82 E.MCLELLAN */
 /*  PURPOSE     TO INTERCHANGE TWO FILES */
 /*  CALLING SEQUENCE */
 /*              CALL ATAPXC(FILE1,FILE2) */
 /*  ARGUMENTS */
 /*              FILE1  FILE NUMBER OF FIRST FILE */
 /*              FILE2  FILE NUMBER OF SECOND FILE */
 /*  ALTERNATE ENTRY */
 /*              CALL TAPECH(FILE1,FILE2) */
     switch(n__) {
     case 1: goto L_tapech;
     }
 L_tapech:
     i__ = *file1;
     *file1 = *file2;
     *file2 = i__;
     return 0;
 } /* atapxc_ */
int tapech_ (integer * file1, integer * file2)
Definition at line 53 of file ATAPXC.c.
References atapxc_0_().
 {
     return atapxc_0_(1, file1, file2);
     }