My Project: AWRITE.c File Reference
AWRITE.c File Reference
#include "f2c.h"
Macros
#define filtab_1 filtab_
#define ifiltb_1 ifiltb_
Functions
int awrite_ (integer *no, integer *irecno, real *data, integer *isize, integer *iret)
Variables
struct {
char filnam [480]
char filacc [300]
char filfmt [330]
char opstat [210]
char clstat [180]
} filtab_
struct {
integer u [30]
integer rl [30]
integer nxtrec [30]
integer lstrec [30]
} ifiltb_
static integer c__1 = 1
static integer c__2 = 2
Macro Definition Documentation
#define filtab_1 filtab_
Definition at line 21 of file AWRITE.c.
Referenced by awrite_().
#define ifiltb_1 ifiltb_
Definition at line 27 of file AWRITE.c.
Referenced by awrite_().
Function Documentation
int awrite_ (integer * no, integer * irecno, real * data, integer * isize, integer * iret)
Definition at line 95 of file AWRITE.c.
References c__1, c__2, cform_(), cprint_(), darray, filopn_(), filtab_1, i1, i2, i__, iconv_(), id, ifiltb_1, irec, isize, j, and num.
Referenced by apt094_(), apt298_(), apt312_(), eread_(), ewrite_(), ieplog_(), mcxtrn_(), pocket_(), rlsbuf_(), and xcanon_().
 {
     /* Initialized data */
     static char darray[80] = "                                              "
         "                                  ";
     static real dum[256] = { 0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,0.f,
         0.f,0.f,0.f,0.f };
     /* System generated locals */
     integer i__1, i__2;
     inlist ioin__1;
     /* Builtin functions */
     integer f_inqu(inlist *), s_cmp(char *, char *, ftnlen, ftnlen), s_wdue(
         cilist *), do_uio(integer *, char *, ftnlen), e_wdue(void),
         s_wsue(cilist *), e_wsue(void);
     /* Local variables */
     static integer i__, j, i1, i2, id;
     static logical od;
     static integer num;
     static char iacc[12];
     static integer irec, slen, posn, irecl;
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen), iconv_(integer *, char *, integer *, integer *,
         ftnlen), filopn_(integer *), cprint_(char *, ftnlen);
     /* Fortran I/O blocks */
     static cilist io___8 = { 1, 0, 0, 0, 0 };
     static cilist io___14 = { 1, 0, 0, 0, 0 };
     static cilist io___15 = { 1, 0, 0, 0, 0 };
     static cilist io___16 = { 0, 0, 0, 0, 0 };
 /*  *  FILE ATTRIBUTES  * */
     /* Parameter adjustments */
     --data;
     /* Function Body */
     id = ifiltb_1.u[(0 + (0 + (*no - 1 << 2))) / 4];
 /* ---- IS FILE OPENED, IF NOT OPEN */
     ioin__1.inerr = 0;
     ioin__1.inunit = id;
     ioin__1.infile = 0;
     ioin__1.inex = 0;
     ioin__1.inopen = &od;
     ioin__1.innum = 0;
     ioin__1.innamed = 0;
     ioin__1.inname = 0;
     ioin__1.inacc = 0;
     ioin__1.inseq = 0;
     ioin__1.indir = 0;
     ioin__1.infmt = 0;
     ioin__1.inform = 0;
     ioin__1.inunf = 0;
     ioin__1.inrecl = 0;
     ioin__1.innrec = 0;
     ioin__1.inblank = 0;
     f_inqu(&ioin__1);
     if (od) {
     goto L10;
     }
 /* ---- OPEN UNIT */
     filopn_(no);
 /* ---- CHECK FILE ACCESS */
 L10:
     ioin__1.inerr = 0;
     ioin__1.inunit = id;
     ioin__1.infile = 0;
     ioin__1.inex = 0;
     ioin__1.inopen = 0;
     ioin__1.innum = 0;
     ioin__1.innamed = 0;
     ioin__1.inname = 0;
     ioin__1.inacclen = 12;
     ioin__1.inacc = iacc;
     ioin__1.inseq = 0;
     ioin__1.indir = 0;
     ioin__1.infmt = 0;
     ioin__1.inform = 0;
     ioin__1.inunf = 0;
     ioin__1.inrecl = 0;
     ioin__1.innrec = 0;
     ioin__1.inblank = 0;
     f_inqu(&ioin__1);
     if (s_cmp(iacc, "DIRECT", (ftnlen)12, (ftnlen)6) == 0) {
 /* ---- DIRECT ACCESS FILE */
     irecl = ifiltb_1.rl[*no - 1];
     if (*irecno == 0) {
         *irecno = ifiltb_1.lstrec[*no - 1] + 1;
     }
     irec = *irecno;
     if (*isize <= irecl) {
         io___8.ciunit = id;
         io___8.cirec = irec;
         *iret = s_wdue(&io___8);
         if (*iret != 0) {
         goto L90;
         }
         i__1 = *isize;
         for (i__ = 1; i__ <= i__1; ++i__) {
         *iret = do_uio(&c__1, (char *)&data[i__], (ftnlen)sizeof(real)
             );
         if (*iret != 0) {
             goto L90;
         }
         }
         *iret = e_wdue();
         if (*iret != 0) {
         goto L90;
         }
     } else {
         num = *isize / irecl;
         i__1 = num;
         for (j = 1; j <= i__1; ++j) {
         i1 = (j - 1) * irecl + 1;
         i2 = j * irecl;
         io___14.ciunit = id;
         io___14.cirec = irec;
         *iret = s_wdue(&io___14);
         if (*iret != 0) {
             goto L90;
         }
         i__2 = i2;
         for (i__ = i1; i__ <= i__2; ++i__) {
             *iret = do_uio(&c__1, (char *)&data[i__], (ftnlen)sizeof(
                 real));
             if (*iret != 0) {
             goto L90;
             }
         }
         *iret = e_wdue();
         if (*iret != 0) {
             goto L90;
         }
 /* L20: */
         ++irec;
         }
         if (*isize - num * irecl > 0) {
         i1 = num * irecl + 1;
         i2 = (num + 1) * irecl - *isize;
         io___15.ciunit = id;
         io___15.cirec = irec;
         *iret = s_wdue(&io___15);
         if (*iret != 0) {
             goto L90;
         }
         i__1 = *isize;
         for (i__ = i1; i__ <= i__1; ++i__) {
             *iret = do_uio(&c__1, (char *)&data[i__], (ftnlen)sizeof(
                 real));
             if (*iret != 0) {
             goto L90;
             }
         }
         i__2 = i2;
         for (i__ = 1; i__ <= i__2; ++i__) {
             *iret = do_uio(&c__1, (char *)&dum[i__ - 1], (ftnlen)
                 sizeof(real));
             if (*iret != 0) {
             goto L90;
             }
         }
         *iret = e_wdue();
         if (*iret != 0) {
             goto L90;
         }
         } else {
         --irec;
         }
     }
     if (irec > ifiltb_1.lstrec[*no - 1]) {
         ifiltb_1.lstrec[*no - 1] = irec;
     }
     ifiltb_1.nxtrec[*no - 1] = irec + 1;
     } else {
 /* ---- SEQUENTIAL ACCESS FILE */
     io___16.ciunit = id;
     s_wsue(&io___16);
     i__1 = *isize;
     for (i__ = 1; i__ <= i__1; ++i__) {
         do_uio(&c__1, (char *)&data[i__], (ftnlen)sizeof(real));
     }
     e_wsue();
     }
     return 0;
 L90:
     slen = 0;
     cform_(" *** ERROR WRITING BY AWRITE ON FILE :", darray, &c__2, &slen, (
         ftnlen)38, (ftnlen)80);
     posn = slen + 3;
     slen = 0;
     cform_(filtab_1.filnam + (*no - 1 << 4), darray, &posn, &slen, (ftnlen)16,
          (ftnlen)80);
     posn = posn + slen + 2;
     slen = 0;
     cform_("RECNO :", darray, &posn, &slen, (ftnlen)7, (ftnlen)80);
     posn = posn + slen + 1;
     slen = 6;
     iconv_(irecno, darray, &posn, &slen, (ftnlen)80);
     cprint_(darray, (ftnlen)80);
     *iret = 1;
     return 0;
 } /* awrite_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 31 of file AWRITE.c.
Referenced by awrite_().
integer c__2 = 2 static
Definition at line 32 of file AWRITE.c.
Referenced by awrite_().
char clstat[180]
Definition at line 18 of file AWRITE.c.
char filacc[300]
Definition at line 18 of file AWRITE.c.
char filfmt[330]
Definition at line 18 of file AWRITE.c.
char filnam[480]
Definition at line 18 of file AWRITE.c.
struct { ... } filtab_
struct { ... } ifiltb_
integer lstrec[30]
Definition at line 24 of file AWRITE.c.
integer nxtrec[30]
Definition at line 24 of file AWRITE.c.
char opstat[210]
Definition at line 18 of file AWRITE.c.
integer rl[30]
Definition at line 24 of file AWRITE.c.
integer u[30]
Definition at line 24 of file AWRITE.c.