My Project: BAD.c File Reference
BAD.c File Reference
#include "f2c.h"
Macros
#define darray_1 darray_
#define aa (equiv_0)
#define ii ((integer *)equiv_0)
Functions
int bad_ (integer *icntrl, integer *itype, char *id, integer *value, ftnlen id_len)
Variables
struct {
char darray [120]
} darray_
static integer c__1 = 1
static integer c__4 = 4
static integer c__10 = 10
static integer c__3 = 3
static integer c__13 = 13
static integer c__5 = 5
static integer c__6 = 6
static integer c__2 = 2
Macro Definition Documentation
#define aa (equiv_0)
Referenced by bad_().
#define darray_1 darray_
Definition at line 21 of file BAD.c.
Referenced by bad_().
#define ii ((integer *)equiv_0)
Referenced by alarm_(), altcmv_(), apt070_(), apt102_(), apt107_(), apt108_(), apt309_(), apt330_(), arggen_(), bad_(), cldat_(), cldatf_(), cleror_(), cnsurh_(), conbcd_(), ddssrf_(), errout_(), floseg_(), gelg_(), gencrv_(), input_(), intsrf_(), larges_(), macrec_(), npat_(), pchprc_(), plapol_(), polpol_(), print_(), pro027_(), pro028_(), prtil_(), read_(), recog_(), recogn_(), reserv_(), revolv_(), scpict_(), sctra_(), smooth_(), srfcom_(), ssdef_(), sspict_(), sstra_(), subcod_(), and tlaxis_().
Function Documentation
int bad_ (integer * icntrl, integer * itype, char * id, integer * value, ftnlen id_len)
Definition at line 36 of file BAD.c.
References aa, blank, c__1, c__10, c__13, c__2, c__3, c__4, c__5, c__6, cform_(), cprint_(), darray_1, fconv_(), ic, iconv_(), and ii.
Referenced by angder_(), angseg_(), aprix_(), apt107_(), apt108_(), apt109_(), apt110_(), apt238_(), arcseg_(), avctrl_(), avoid_(), axset_(), baltwo_(), chdseg_(), chkset_(), clput_(), cpldst_(), crvlen_(), ctrans_(), curflo_(), curint_(), cutreg_(), ddssrf_(), devcal_(), dgeom_(), fedput_(), floseg_(), gchk_(), gencrv_(), getapt_(), gfetch_(), gop_(), init_(), intchk_(), kursrf_(), mescon_(), mesh_(), midkur_(), midpnt_(), mixal_(), paral_(), pchg_(), pchprc_(), puvloc_(), region_(), remint_(), scdump_(), scon_(), scurv_(), smil_(), srfcom_(), srfdir_(), srftol_(), sspath_(), stepck_(), tecalc_(), tlconv_(), tulpos_(), xcanon_(), and xtpcal_().
 {
     /* Initialized data */
     static char blank[3] = "   ";
     static char star[2] = "**";
     static integer ncol = 4;
     static char equal[1] = "=";
     /* System generated locals */
     static doublereal equiv_0[1];
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
 #define aa (equiv_0)
     static integer ic;
 #define ii ((integer *)equiv_0)
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen), fconv_(doublereal *, char *, integer *, integer *
         , integer *, ftnlen);
     static integer irlse;
     extern /* Subroutine */ int iconv_(integer *, char *, integer *, integer *
         , ftnlen);
     static integer input;
     static logical bufful;
     extern /* Subroutine */ int cprint_(char *, ftnlen);
     static integer icntrx;
 /* ---  ROUTINE TO FORMAT AND PRINT LINES OF PRINT FOR DEBUGGING */
 /* ---  EACH LINE CONTAINS UP TO SIX VALUES WITH IDENTIFIERS FOR EACH */
 /* ---  ICNTRL=-1  MEANS RELEASE THE BUFFER (DARRAY) FOR PRINTING AND BLNK */
 /* ---  ICNTRL=0 MEANS BLANK THE BUFFER AND SET COLUMN POINTER NCOL TO 4 */
 /* ---  ICNTRL GT 0 MEANS  TO PLACE ICNTRL ITEMS INTO THE BUFFER AND */
 /* ---  ICNTRL=-N MEANS PRINT N ITEMS AND THEN RELEASE BUFFER TO PRINT. */
 /* ---  AUTOMATICALLY PRINT THE BUFFER AS ROOM IS EXHAUSTED */
 /* ---  ITYPE =0 MEANS PRINT THE INTEGER AT VALUE */
 /* ---    AND =1 MEANS PRINT THE DOUBLE PRECISION */
 /* ---  ID IS THE 4 CHARACTER IDENTIFYING NAME FOR VALUE AND VALUE */
 /* ---     IS THE DATA TO BE FORMATTED INTO THE PRINT LINE. */
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
 /* ---     BUFFUL IS A FLAG TO SIGNAL THAT A BUFFER IS NOW FULL */
 /* ---     SO THAT IT SHOULD NOW BE EMPTIED BEFORE INSERTING MORE DATA */
     /* Parameter adjustments */
     --value;
     /* Function Body */
 /* --- */
 /* ---  IC IS A COUNT DOWN VARIABLE FOR CASES WHEN ICNTRL GT 1 */
     ic = 0;
     bufful = FALSE_;
 /* ---     TRANSFER ICNTRL TO ICNTRX SO ICNTRL IS NOT ALTERED */
     icntrx = *icntrl;
 /* ---     THIS IS A PATCH TO ENABLE DUMPING OF DATA AT END OF CALL */
 /* ---     IF ICNTRX IS NEGATIVE, THEN DATA SHOULD BE DUMPED AT */
 /* ---     AT THE END OF THE CURRENT CALL */
     irlse = 1;
     if (icntrx < 0) {
     irlse = -1;
     }
 /* ---     IF ID IS ZERO AND ICNTRX IS NEGATIVE THEN RELEASE NOW */
     if (*(unsigned char *)id == ' ' && icntrx < 0) {
     goto L300;
     }
 /* ---     SET ICNTRX POSITIVE, SINCE IRLSE HOLDS THE NEGATIVE INDICATION */
     icntrx = abs(icntrx);
     if (icntrx < 0) {
     goto L300;
     } else if (icntrx == 0) {
     goto L100;
     } else {
     goto L200;
     }
 /* ---  INITIALIZE THE BUFFER BY BLANK FILLING AND COLUMN SETTING */
 L100:
     s_copy(darray_1.darray, blank, (ftnlen)120, (ftnlen)3);
     ncol = 4;
     if (! bufful) {
     goto L999;
     }
 /* ---  BUFFER HAS JUST BEEN AUTOMATICALLY EMPTIED.  NOW INSERT DATA */
     bufful = FALSE_;
     goto L210;
 /* ---   ADD A NEW DATA ELEMENT INTO THE BUFFER LINE */
 L200:
     bufful = TRUE_;
     if (ncol + 18 > 120) {
     goto L300;
     }
 L210:
     cform_(blank, darray_1.darray, &ncol, &c__1, (ftnlen)3, (ftnlen)120);
     ++ncol;
     ++ic;
 /* ---   PLACE AN ID FOR THE FIRST ARRAY EL, COUNTERS THEREAFTER */
     if (ic == 1) {
     cform_(id, darray_1.darray, &ncol, &c__4, (ftnlen)4, (ftnlen)120);
     }
     if (ic > 1) {
     iconv_(&ic, darray_1.darray, &ncol, &c__4, (ftnlen)120);
     }
     ncol += 4;
     cform_(equal, darray_1.darray, &ncol, &c__1, (ftnlen)1, (ftnlen)120);
     ++ncol;
 /* ---   BRANCH BASED ON TYPE OF DATA -- INTEGER OR REAL */
     if (*itype == 0) {
 /* ---   ADD AN INTEGER TO THE LINE BUFFER */
 /* ---  THE INTEGER JJ IS SETUP BY THE MOVEMENT OF VALUE INTO AA */
     iconv_(&value[ic], darray_1.darray, &ncol, &c__10, (ftnlen)120);
     ncol += 10;
     cform_(blank, darray_1.darray, &ncol, &c__3, (ftnlen)3, (ftnlen)120);
     ncol += 3;
     } else if (*itype == 1) {
 /* ---   ADD A REAL TO THE LINE BUFFER */
 /* ---  CARE MUST BE TAKEN TO TRANSFER DATA TO A DOUBLE WORD  BOUNDARY */
     ii[0] = value[(ic << 1) - 1];
     ii[1] = value[ic * 2];
 /* ---  THE DOUBLE VALUE IS NOW AVAILABLE IN AA THRU EQUIVALENCE */
     input = value[(ic << 1) - 1];
     fconv_(aa, darray_1.darray, &ncol, &c__13, &c__5, (ftnlen)120);
     ncol += 13;
     } else {
     cform_("******", darray_1.darray, &ncol, &c__6, (ftnlen)6, (ftnlen)
         120);
     ncol += 13;
     }
     goto L999;
 /* ---   PRINT THE BUFFER AND BLANK THE LINE */
 L300:
 /* ---  IF THE BUFFER IS EMPTIED AUTOMATICALLY, MARK IT WITH STARS */
     if (! bufful) {
     goto L310;
     }
     if (irlse > 0) {
     cform_(star, darray_1.darray, &c__2, &c__2, (ftnlen)2, (ftnlen)120);
     }
 L310:
     cprint_(darray_1.darray, (ftnlen)120);
     goto L100;
 /* --- */
 L999:
 /* ---  CHECK TO SEE IF AN ARRAY HAS BEEN EXHAUSTED */
     if (icntrx > 0 && ic < icntrx) {
     goto L200;
     }
 /* ---     IF IRLSE IS NEGATIVE THEN THE BUFFER SHOULD BE */
 /* ---     RELEASED NOW */
     if (irlse > 0) {
     goto L9999;
     }
     if (ncol == 4) {
     goto L9999;
     }
 /* ---     DATA IS PRESENT SO RELEASE THE BUFFER */
     cprint_(darray_1.darray, (ftnlen)120);
     ncol = 4;
 L9999:
     return 0;
 } /* bad_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 25 of file BAD.c.
Referenced by bad_().
integer c__10 = 10 static
Definition at line 27 of file BAD.c.
Referenced by bad_().
integer c__13 = 13 static
Definition at line 29 of file BAD.c.
Referenced by bad_().
integer c__2 = 2 static
Definition at line 32 of file BAD.c.
Referenced by bad_().
integer c__3 = 3 static
Definition at line 28 of file BAD.c.
Referenced by bad_().
integer c__4 = 4 static
Definition at line 26 of file BAD.c.
Referenced by bad_().
integer c__5 = 5 static
Definition at line 30 of file BAD.c.
Referenced by bad_().
integer c__6 = 6 static
Definition at line 31 of file BAD.c.
Referenced by bad_().
char darray[120]
Definition at line 18 of file BAD.c.
struct { ... } darray_