My Project: BADNAM.c File Reference
BADNAM.c File Reference
#include "f2c.h"
Functions
int badnam_ (integer *iword)
Function Documentation
int badnam_ (integer * iword)
Definition at line 37 of file BADNAM.c.
References bcdf_(), first, and iword.
Referenced by apt104_(), and print_().
 {
     /* Initialized data */
     static logical first = TRUE_;
     extern integer bcdf_(char *, ftnlen);
     static integer ibdnam[2];
     /* Parameter adjustments */
     --iword;
     /* Function Body */
     if (first) {
     ibdnam[0] = bcdf_("BADN", (ftnlen)4);
     ibdnam[1] = bcdf_("AM  ", (ftnlen)4);
     first = FALSE_;
     }
     iword[1] = ibdnam[0];
     iword[2] = ibdnam[1];
     return 0;
 } /* badnam_ */