My Project: BALONE.c File Reference
BALONE.c File Reference
#include "f2c.h"
Functions
int balone_ (doublereal *r__, doublereal *side, doublereal *tc, doublereal *rad, doublereal *td, doublereal *du, doublereal *dv, doublereal *dist, integer *irr)
Function Documentation
int balone_ (doublereal * r__, doublereal * side, doublereal * tc, doublereal * rad, doublereal * td, doublereal * du, doublereal * dv, doublereal * dist, integer * irr)
Definition at line 17 of file BALONE.c.
References dotf_(), i__, r__, and zero.
Referenced by balloc_(), and balsrf_().
 {
     /* Initialized data */
     static doublereal zero = 0.;
     static doublereal smal = 1e-18;
     /* System generated locals */
     doublereal d__1;
     /* Local variables */
     static integer i__;
     static doublereal del[3], suu, suv, svv, delu, delv;
     extern /* Subroutine */ int dotf_(doublereal *, doublereal *, doublereal *
         );
     static doublereal rmod[3], tdsn, discr, factor;
 /*           /-PURPOSE TO USE LINEAR ESTIMATE OF SURFACE(STORED IN R ) TO */
 /*           /-CALCULATE DISTANCE TO MOVE BALL CUTTER CENTERED AT TC */
 /*           /-IN DIRECTION TD TOWARD SURFACE */
 /*           /-INPUT FOLLOWS */
 /*           /-R(1-32) CONTAINS SURFACE COORDS,FIRST AND SECOND DERIVATIV */
 /*           /-TC,TD DENOTE TOOL CENTER AND TOOL DIRECTION TO SURFACE */
 /*           /-RAD DENOTES THE RADIUS OF THE BALL TOOL */
 /*           /-SIDE DENOTES NON MATERIAL SIDE OF SURFACE(+1 FOR U X V ) */
 /*           /-OUTPUT */
 /*           /-DIST DISTANCE TOOL CENTER SHOULD BE MOVED TO CONTACT PLANE */
 /*           /-DU,DV SURFACE COORDINATE CHANGES FOR TOOL CONTACT PT. */
 /*           /-IRR IS NON ZERO ON OUTPUT IF AN ERROR OCCURRED HERE. */
     /* Parameter adjustments */
     --td;
     --tc;
     --r__;
     /* Function Body */
 /*           /-COMPUTE MODIFIED SURFACE POINT FOR INTERSECTION PLANE */
     factor = *side * *rad;
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L10: */
     rmod[i__ - 1] = r__[i__] + factor * r__[i__ + 28];
     }
 /*           /-COMPUTE DISTANCE OF TC ALONG TD TO THIS PLANE */
 /*           /- DIST SATISFIES EQN, (TC+DIST*TD-RMOD,SN)=0 */
     dotf_(&tdsn, &td[1], &r__[29]);
     *irr = 1;
     if (abs(tdsn) < smal) {
     goto L999;
     }
     *dist = zero;
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L20: */
     *dist += (rmod[i__ - 1] - tc[i__]) * r__[i__ + 28];
     }
     *dist /= tdsn;
 /*           /-COMPUTE INCREMENTAL VECTOR FROM RMOD TO TC , TD PIERCE POI */
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L30: */
     del[i__ - 1] = tc[i__] + *dist * td[i__] - rmod[i__ - 1];
     }
 /*           /-COMPUTE CHANGE IN U,V TO REACH DEL */
     dotf_(&suu, &r__[5], &r__[5]);
     dotf_(&suv, &r__[5], &r__[9]);
     dotf_(&svv, &r__[9], &r__[9]);
     dotf_(&delu, del, &r__[5]);
     dotf_(&delv, del, &r__[9]);
 /* Computing 2nd power */
     d__1 = suv;
     discr = suu * svv - d__1 * d__1;
     *irr = 2;
     if (abs(discr) < smal) {
     goto L999;
     }
     *du = (delu * svv - delv * suv) / discr;
     *dv = (suu * delv - suv * delu) / discr;
     *irr = 0;
 L999:
     return 0;
 } /* balone_ */