My Project: BALSCN.c File Reference
BALSCN.c File Reference
#include "f2c.h"
Functions
int balscn_ (doublereal *surf, doublereal *side, doublereal *tc, doublereal *rad, doublereal *td, doublereal *u, doublereal *v, doublereal *dist, integer *npat, integer *irr)
Variables
static integer c__3 = 3
Function Documentation
int balscn_ (doublereal * surf, doublereal * side, doublereal * tc, doublereal * rad, doublereal * td, doublereal * u, doublereal * v, doublereal * dist, integer * npat, integer * irr)
Definition at line 21 of file BALSCN.c.
References b, balloc_(), c__3, chktop_(), i__, iflag, ir, itop, lodpch_(), u1, and v1.
Referenced by balsrf_().
 {
     /* Initialized data */
     static doublereal half = .5;
     static doublereal big = 1e22;
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static doublereal b[64];
     static integer i__;
     static doublereal u1, v1, da;
     static integer ir, iok, itop[24]    /* was [6][4] */, iflag[6], ifree;
     extern /* Subroutine */ int balloc_(doublereal *, integer *, integer *,
         doublereal *, doublereal *, doublereal *, doublereal *,
         doublereal *, doublereal *, doublereal *, integer *, integer *,
         integer *), lodpch_(doublereal *, doublereal *, integer *,
         integer *, integer *, integer *), chktop_(doublereal *,
         doublereal *, integer *, integer *);
     static integer maxrep, numpat;
 /*           /-PURPOSE IS TO SCAN ALL PATCHES IN SURFACE AND SELECT */
 /*           /-BEST CANDIDATE FOR LINEUP WITH TOOL */
 /*           /-INPUT */
 /*           /-SURF- INPUT SCULPTURED SURFACE LARGE DATA ARRAY */
 /*           /-OUTPUT */
 /*           /-NPAT PATCH NUMBER OF BEST CANDIDATE */
 /*           /-PATCH U,V COORDINATES AT ESTIMATED CONTACT POINT */
 /*           /-DIST ESTIMATED DISPLACEMENT FROM CURRENT CUTTER POSN TO SU */
     /* Parameter adjustments */
     --td;
     --tc;
     --surf;
     /* Function Body */
     *u = half;
     *v = half;
     *npat = 1;
     *dist = big;
     ir = 1;
     numpat = (integer) surf[4];
     i__1 = numpat;
     for (i__ = 1; i__ <= i__1; ++i__) {
 /*           /-LOAD THE ITH PATCH */
     lodpch_(&surf[1], b, iflag, itop, &i__, &c__3);
     maxrep = 5;
     ifree = 0;
     u1 = half;
     v1 = half;
     *irr = 0;
     balloc_(b, iflag, itop, side, &tc[1], rad, &td[1], &u1, &v1, &da, &
         maxrep, &ifree, irr);
     if (*irr != 0) {
         goto L20;
     }
     chktop_(&u1, &v1, itop, &iok);
     if (iok == 0) {
         goto L30;
     }
 L20:
     if (abs(*dist) < big) {
         goto L10;
     }
     u1 = half;
     v1 = half;
     maxrep = 1;
     ifree = 1;
     *irr = 0;
     balloc_(b, iflag, itop, side, &tc[1], rad, &td[1], &u1, &v1, &da, &
         maxrep, &ifree, irr);
     if (*irr != 0) {
         goto L10;
     }
 L30:
     if (abs(*dist) < abs(da)) {
         goto L10;
     }
 /*           /-UPDATE BEST PATCH BASED ON SMALLEST DISTANCE */
     *dist = da;
     *u = u1;
     *v = v1;
     *npat = i__;
     ir = 0;
 /*           /-UPDATE ERROR FLAG TO INDICATE SUCCESS */
 L10:
     ;
     }
     *irr = ir;
     return 0;
 } /* balscn_ */
Variable Documentation
integer c__3 = 3 static
Definition at line 17 of file BALSCN.c.
Referenced by balscn_().