My Project: BCDBIN.c File Reference
BCDBIN.c File Reference
#include "f2c.h"
Functions
int bcdbin_ (char *word, integer *i__, integer *count, ftnlen word_len)
Function Documentation
int bcdbin_ (char * word, integer * i__, integer * count, ftnlen word_len)
Definition at line 35 of file BCDBIN.c.
References blank, j, num, w, and zero.
Referenced by binchk_(), inpat_(), motion_(), pro026_(), pro027_(), recog_(), reserv_(), and resred_().
 {
     /* Initialized data */
     static char period[1] = ".";
     static char blank[1] = " ";
     static char zero[1] = "0";
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer j;
     static char w[8];
     static integer num;
     static char char__[1];
     s_copy(w, word, (ftnlen)8, (ftnlen)8);
     *i__ = 0;
     for (j = 1; j <= 8; ++j) {
     *count = j;
     *(unsigned char *)char__ = *(unsigned char *)&w[j - 1];
     if (*(unsigned char *)char__ == *(unsigned char *)&period[0] || *(
         unsigned char *)char__ == *(unsigned char *)&blank[0]) {
         goto L100;
     }
     num = *(unsigned char *)char__ - *(unsigned char *)&zero[0];
     if (num > 9 || num < 0) {
         goto L400;
     }
     *i__ = *i__ * 10 + num;
 /* L300: */
     }
 L200:
     return 0;
 L100:
     --(*count);
     goto L200;
 L400:
     *count = -1;
     goto L200;
 } /* bcdbin_ */