My Project: BCDF.c File Reference
BCDF.c File Reference
#include "f2c.h"
Macros
#define sdp_1 sdp_
Functions
integer bcdf_ (char *str, ftnlen str_len)
Variables
struct {
integer nbchar
integer nbwrd
integer iwrd
integer ifac
} sdp_
static integer c__2 = 2
Macro Definition Documentation
#define sdp_1 sdp_
Definition at line 21 of file BCDF.c.
Referenced by bcdf_().
Function Documentation
integer bcdf_ (char * str, ftnlen str_len)
Definition at line 62 of file BCDF.c.
References c__2, i__, and sdp_1.
Referenced by aerr2_(), aerr_(), apt100_(), apt104_(), apt202_(), apt211_(), apt233_(), apt235_(), apt296_(), apt297_(), apt298_(), apt299_(), apt301_(), apt311_(), apt331_(), atape_(), badnam_(), cldat_(), cldatf_(), clput_(), cnvrt3_(), comp3d_(), cut_(), cuth_(), cutred_(), cutteh_(), cuttes_(), dnonam_(), dntcuh_(), dntcut_(), eread_(), error_(), ewrite_(), fedput_(), fini_(), godlta_(), gol_(), golovo_(), gop_(), goretr_(), gougck_(), indirp_(), indirv_(), indrph_(), indrvh_(), init_(), intol_(), intolh_(), intout_(), intsec_(), ldard_(), macrec_(), maxdp_(), maxdph_(), multax_(), name_(), ndtest_(), numpts_(), outtoh_(), outtol_(), pocket_(), print_(), punch_(), recog_(), region_(), resrv_(), smil_(), srfvct_(), sycurv_(), thick_(), thickh_(), toler_(), tolerh_(), and units_().
 {
     /* System generated locals */
     address a__1[2];
     integer ret_val, i__1[2], i__2;
     /* Builtin functions */
     /* Subroutine */ int s_cat(char *, char **, integer *, integer *, ftnlen);
     integer lbit_shift(integer, integer);
     /* Local variables */
     static integer i__, bcd;
     static char tstr[10];
     bcd = 0;
 /* Writing concatenation */
     i__1[0] = str_len, a__1[0] = str;
     i__1[1] = 1, a__1[1] = " ";
     s_cat(tstr, a__1, i__1, &c__2, (ftnlen)10);
     i__2 = sdp_1.iwrd;
     for (i__ = 1; i__ <= i__2; ++i__) {
     bcd = lbit_shift(bcd, sdp_1.nbchar) + *(unsigned char *)&tstr[i__ - 1]
         ;
 /* L10: */
     }
     ret_val = bcd;
     return ret_val;
 } /* bcdf_ */
Variable Documentation
integer c__2 = 2 static
Definition at line 25 of file BCDF.c.
Referenced by bcdf_().
integer ifac
Definition at line 18 of file BCDF.c.
integer iwrd
Definition at line 18 of file BCDF.c.
Referenced by mcxtrn_().
integer nbchar
Definition at line 18 of file BCDF.c.
integer nbwrd
Definition at line 18 of file BCDF.c.
struct { ... } sdp_