My Project: BDEBUF.c File Reference
BDEBUF.c File Reference
#include "f2c.h"
Data Structures
struct ebuf_1_
Macros
#define ebuf_1 (*(struct ebuf_1_ *) &ebuf_)
#define cldt_1 cldt_
#define chcldt_1 chcldt_
Functions
int bdebuf_ (void)
int ewrite_ (integer *exfile, integer *mr, integer *icldat, integer *j, integer *ir)
int eread_ (integer *exfile, integer *ibuff, integer *nn, integer *nbf, integer *nrf, integer *nrp, integer *isz, integer *ir)
Variables
struct {
logical cldfg
integer iclcod
integer iclcnt
integer icline
integer iclblk
integer iclrcd
integer icltab [500]
integer iptvec [9]
} cldt_
struct {
char pntvct [72]
} chcldt_
struct {
integer fill_1 [516]
integer e_2 [4]
} ebuf_ = { {0}, 2, 0, 1, 0 }
Macro Definition Documentation
#define chcldt_1 chcldt_
Definition at line 35 of file BDEBUF.c.
#define cldt_1 cldt_
Definition at line 29 of file BDEBUF.c.
Referenced by eread_(), and ewrite_().
#define ebuf_1 (*(struct ebuf_1_ *) &ebuf_)
Definition at line 21 of file BDEBUF.c.
Referenced by eread_(), and ewrite_().
Function Documentation
int bdebuf_ (void)
Definition at line 47 of file BDEBUF.c.
 {
     return 0;
 } /* bdebuf_ */
int eread_ (integer * exfile, integer * ibuff, integer * nn, integer * nbf, integer * nrf, integer * nrp, integer * isz, integer * ir)
Definition at line 170 of file BDEBUF.c.
References aread_(), awrite_(), bcdf_(), cldt_1, ebuf_1, first, help_(), i__, j, jj, and nb.
Referenced by ataper_().
 {
     /* Initialized data */
     static logical goflg = FALSE_;
     static logical first = TRUE_;
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__, j, nb, jj, kk, mm, ks, nr, ncl[2];
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int help_(void);
     static integer minn, maxn;
     extern /* Subroutine */ int aread_(integer *, integer *, integer *,
         integer *, integer *);
     static integer godlt;
     extern /* Subroutine */ int awrite_(integer *, integer *, integer *,
         integer *, integer *);
     /* Parameter adjustments */
     --ibuff;
     /* Function Body */
     if (first) {
     ncl[0] = bcdf_("CLDA", (ftnlen)4);
     ncl[1] = bcdf_("TA  ", (ftnlen)4);
     godlt = bcdf_("GODL", (ftnlen)4);
     first = FALSE_;
     }
 /*     WRITE THE CURRENT BLOCK */
     if (ebuf_1.k == 2) {
     goto L100;
     }
     nr = 0;
     awrite_(exfile, &nr, ebuf_1.ebuff, &ebuf_1.k, ir);
     cldt_1.iclblk = nr;
     ebuf_1.keb = ebuf_1.n + 1;
     ebuf_1.k = 2;
 /*     RETRIEVE A DEFINED BLOCK CONTAINING THE LAST MOTION COMMAND. */
 L100:
     if (*isz > 0) {
     goto L130;
     }
     if (nb == *nbf) {
     goto L110;
     }
     ks = 516;
     nb = *nbf;
     aread_(exfile, &nb, ebuf_1.ebuff, &ks, ir);
 /*     STANDARD EXFILE RECORD FORMAT */
 L110:
     jj = ks + 3 + (*isz << 1) * (*nrp - *nn + 1);
     mm = jj - 3 - (*isz << 1);
     i__1 = mm;
     for (i__ = jj; i__ <= i__1; ++i__) {
 /* L120: */
     ibuff[i__ - jj + 1] = ebuf_1.ebuff[i__ - 1];
     }
     return 0;
 /*     EXFILE RECORD EXTENDED FORMAT. MORE THAN ONE MOTION COMMAND. */
 L130:
     if (ebuf_1.krf != *nrf) {
     goto L150;
     }
     if (*nn > maxn) {
     goto L205;
     }
     if (*nn > minn) {
     goto L230;
     }
 L150:
     nb = *nbf - 1;
     minn = 0;
     ebuf_1.krf = *nrf;
 /*     READ FIRST BLOCK OF THE CLDAT SECTION. */
 L160:
     ++nb;
     if (nb > cldt_1.iclblk) {
     help_();
     }
     ks = 516;
     aread_(exfile, &nb, ebuf_1.ebuff, &ks, ir);
     if (*nrf > ebuf_1.ebuff[1]) {
     goto L160;
     }
 /*     START OF THE CLDAT SECTION FOUND. */
 /* L170: */
     kk = 3;
     goto L185;
 L180:
     kk = kk + ebuf_1.ebuff[kk] + 2;
     if (kk >= ks) {
     help_();
     }
 L185:
     if (ebuf_1.ebuff[kk - 1] < *nrf) {
     goto L180;
     }
 /*     IS IT A MOTION COMMAND ? */
 L190:
     if (ebuf_1.ebuff[kk + 1] == ncl[0]) {
     goto L220;
     }
 L200:
     kk = kk + ebuf_1.ebuff[kk] + 2;
     if (kk >= ks - 1) {
     goto L160;
     }
     goto L190;
 L205:
     minn = maxn;
 L210:
     goflg = FALSE_;
     goto L200;
 /*     IS IT A CLDATA RECORD GIVING POSITIONS ? */
 L220:
     if (ebuf_1.ebuff[kk + 2] != ncl[1]) {
     goto L200;
     }
     if (ebuf_1.ebuff[kk + 9] == godlt) {
     goflg = TRUE_;
     }
     if (ebuf_1.ebuff[kk + 8] == 1) {
     goto L200;
     }
     if (goflg) {
     goto L210;
     }
 /*     IS DEMANDED POSITION WITHIN THAT RECORD ? */
     maxn = minn + ebuf_1.ebuff[kk + 6] / *isz;
     if (maxn >= *nn) {
     goto L230;
     }
     minn = maxn;
     goto L200;
 /*     POSITION FOUND */
 L230:
     jj = kk + (*isz << 1) * (*nn - minn - 1);
     if (*nrp == 0) {
     goto L240;
     }
 /*     EXFILE RECORD EXTENDED FORMAT. */
     jj = jj + (*nrp << 3) + 4;
     mm = jj + 5;
     goto L250;
 /*     EXFILE RECORD STANDARD FORMAT. */
 L240:
     jj += 10;
     mm = jj + (*isz << 1) - 3;
 L250:
     i__ = 0;
     i__1 = mm;
     for (j = jj; j <= i__1; ++j) {
     ++i__;
     if (*nrp > 0) {
         ibuff[i__ + 6] = ebuf_1.ebuff[j - 1];
     }
 /* L260: */
     ibuff[i__] = ebuf_1.ebuff[j - 1];
     }
     return 0;
 } /* eread_ */
int ewrite_ (integer * exfile, integer * mr, integer * icldat, integer * j, integer * ir)
Definition at line 72 of file BDEBUF.c.
References awrite_(), bcdf_(), cldt_1, ebuf_1, first, i__, and j.
Referenced by aerr2_(), aerr_(), apt211_(), apt233_(), apt235_(), apt296_(), apt297_(), apt299_(), atape_(), clput_(), error_(), fini_(), gol_(), gop_(), goretr_(), intout_(), pocket_(), and units_().
 {
     /* Initialized data */
     static logical first = TRUE_;
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__, nr;
     extern integer bcdf_(char *, ftnlen);
     static integer kfini;
     extern /* Subroutine */ int awrite_(integer *, integer *, integer *,
         integer *, integer *);
     /* Parameter adjustments */
     --icldat;
     /* Function Body */
     if (first) {
     kfini = bcdf_("FINI", (ftnlen)4);
     first = FALSE_;
     }
     if (ebuf_1.k + *j > 514) {
     goto L1;
     }
 L10:
     ++ebuf_1.n;
     cldt_1.iclrcd = ebuf_1.n;
 /* L15: */
     ebuf_1.ebuff[0] = ebuf_1.keb;
     ebuf_1.ebuff[1] = ebuf_1.n;
     ebuf_1.ebuff[ebuf_1.k] = ebuf_1.n;
     ebuf_1.ebuff[ebuf_1.k + 1] = *j;
     ebuf_1.k += 2;
     i__1 = *j;
     for (i__ = 1; i__ <= i__1; ++i__) {
     ++ebuf_1.k;
 /* L20: */
     ebuf_1.ebuff[ebuf_1.k - 1] = icldat[i__];
     }
 /*     IF THE RECORD IS FINI,  TRUNCATE THE BLOCK */
 /*       AND WRITE OUT TO EXFILE. */
     if (icldat[1] == kfini) {
     goto L30;
     }
     *mr = ebuf_1.n;
     return 0;
 /*     BUFFER IS FULL, WRITE THE BLOCK ON EXFILE */
 L1:
     nr = 0;
     awrite_(exfile, &nr, ebuf_1.ebuff, &ebuf_1.k, ir);
     cldt_1.iclblk = nr;
     ebuf_1.k = 2;
     ebuf_1.keb = ebuf_1.n + 1;
     goto L10;
 L30:
     ebuf_1.ebuff[1] = ebuf_1.n;
     nr = 0;
     awrite_(exfile, &nr, ebuf_1.ebuff, &ebuf_1.k, ir);
     return 0;
 } /* ewrite_ */
Variable Documentation
struct { ... } chcldt_
logical cldfg
Definition at line 24 of file BDEBUF.c.
struct { ... } cldt_
integer e_2[4]
Definition at line 41 of file BDEBUF.c.
struct { ... } ebuf_
integer fill_1[516]
Definition at line 40 of file BDEBUF.c.
integer iclblk
Definition at line 25 of file BDEBUF.c.
integer iclcnt
Definition at line 25 of file BDEBUF.c.
integer iclcod
Definition at line 25 of file BDEBUF.c.
integer icline
Definition at line 25 of file BDEBUF.c.
integer iclrcd
Definition at line 25 of file BDEBUF.c.
integer icltab[500]
Definition at line 25 of file BDEBUF.c.
integer iptvec[9]
Definition at line 25 of file BDEBUF.c.
char pntvct[72]
Definition at line 32 of file BDEBUF.c.