My Project: BDIZEL.c File Reference
BDIZEL.c File Reference
#include "f2c.h"
Data Structures
struct izeill_1_
Macros
#define izeill_1 (*(struct izeill_1_ *) &izeill_)
Functions
int bdizel_ (void)
int cprin1_ (char *a, ftnlen a_len)
int vorsch_ (integer *i__, char *a, ftnlen a_len)
Variables
struct {
integer e_1
} izeill_ = { 1 }
Macro Definition Documentation
#define izeill_1 (*(struct izeill_1_ *) &izeill_)
Definition at line 21 of file BDIZEL.c.
Referenced by cprin1_(), and vorsch_().
Function Documentation
int bdizel_ (void)
Definition at line 32 of file BDIZEL.c.
 {
     return 0;
 } /* bdizel_ */
int cprin1_ (char * a, ftnlen a_len)
Definition at line 40 of file BDIZEL.c.
References cprint_(), and izeill_1.
Referenced by scpict_(), and sspict_().
 {
     /* Initialized data */
     static char sv[1] = "1";
     static char ez[1] = " ";
     static char zz[1] = "0";
     extern /* Subroutine */ int cprint_(char *, ftnlen);
     if (*(unsigned char *)a != *(unsigned char *)&sv[0]) {
     goto L1;
     }
     izeill_1.izeil = 1;
     goto L5;
 L1:
     if (*(unsigned char *)a != *(unsigned char *)&ez[0]) {
     goto L2;
     }
     ++izeill_1.izeil;
     goto L5;
 L2:
     if (*(unsigned char *)a != *(unsigned char *)&zz[0]) {
     goto L5;
     }
     izeill_1.izeil += 2;
 L5:
     cprint_(a, (ftnlen)120);
     return 0;
 } /* cprin1_ */
int vorsch_ (integer * i__, char * a, ftnlen a_len)
Definition at line 74 of file BDIZEL.c.
References b, cprint_(), izeill_1, and j.
Referenced by scpict_(), and sspict_().
 {
     /* Initialized data */
     static char sv[1] = "1";
     static char b[120];
     static integer j;
     extern /* Subroutine */ int cprint_(char *, ftnlen);
     if (izeill_1.izeil + *i__ < 67) {
     return 0;
     }
     for (j = 1; j <= 120; ++j) {
 /* L6: */
     *(unsigned char *)&b[j - 1] = *(unsigned char *)&a[j - 1];
     }
     *(unsigned char *)b = *(unsigned char *)&sv[0];
     izeill_1.izeil = 1;
     cprint_(b, (ftnlen)120);
     return 0;
 } /* vorsch_ */
Variable Documentation
integer e_1
Definition at line 26 of file BDIZEL.c.
struct { ... } izeill_