My Project: BINBCD.c File Reference
BINBCD.c File Reference
#include "f2c.h"
Functions
int binbcd_ (integer *jntger, char *symbol, integer *count, ftnlen symbol_len)
Variables
static integer c__1 = 1
static integer c__2 = 2
Function Documentation
int binbcd_ (integer * jntger, char * symbol, integer * count, ftnlen symbol_len)
Definition at line 25 of file BINBCD.c.
References blank, c__1, c__2, i__, and j.
Referenced by alarm_(), gettmp_(), goloft_(), inpat_(), isscod_(), labcon_(), lcanon_(), macrec_(), oppair_(), prtil_(), puttmp_(), recog_(), rlslin_(), ssdef_(), and tssmil_().
 {
     /* Initialized data */
     static char blank[1] = " ";
     /* System generated locals */
     address a__1[2];
     integer i__1[2];
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     integer s_wsfi(icilist *), do_fio(integer *, char *, ftnlen), e_wsfi(void)
         ;
     /* Subroutine */ int s_cat(char *, char **, integer *, integer *, ftnlen);
     /* Local variables */
     static integer i__, j;
     static char bcd[8];
     static integer intger;
     /* Fortran I/O blocks */
     static icilist io___5 = { 0, bcd, 0, "(I8)", 8, 1 };
     intger = *jntger;
     *count = 0;
     s_copy(bcd, blank, (ftnlen)8, (ftnlen)1);
     if (intger < 0) {
     s_copy(symbol, bcd, symbol_len, (ftnlen)8);
     } else {
     s_wsfi(&io___5);
     do_fio(&c__1, (char *)&intger, (ftnlen)sizeof(integer));
     e_wsfi();
     for (i__ = 1; i__ <= 8; ++i__) {
         if (*(unsigned char *)&bcd[i__ - 1] != *(unsigned char *)&blank[0]
             ) {
         j = i__;
         goto L20;
         }
 /* L10: */
     }
 L20:
     *count = 9 - j;
 /* Writing concatenation */
     i__1[0] = 8 - (j - 1), a__1[0] = bcd + (j - 1);
     i__1[1] = 1, a__1[1] = blank;
     s_cat(symbol, a__1, i__1, &c__2, symbol_len);
     }
     return 0;
 } /* binbcd_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 17 of file BINBCD.c.
Referenced by binbcd_().
integer c__2 = 2 static
Definition at line 18 of file BINBCD.c.
Referenced by binbcd_().