My Project: BLENDF.c File Reference
BLENDF.c File Reference
#include "f2c.h"
Functions
int blendf_ (doublereal *u, doublereal *fu)
Function Documentation
int blendf_ (doublereal * u, doublereal * fu)
Definition at line 17 of file BLENDF.c.
References dif, four, i__, one, six, three, two, u, u2, and zero.
Referenced by cncurv_(), cnsurg_(), cnsurh_(), crblen_(), and crsfit_().
 {
     /* Initialized data */
     static doublereal zero = 0.;
     static doublereal one = 1.;
     static doublereal two = 2.;
     static doublereal three = 3.;
     static doublereal four = 4.;
     static doublereal six = 6.;
     static integer i__;
     static doublereal u2, u3, dif;
     /* Parameter adjustments */
     --fu;
     /* Function Body */
 /* ------ INPUT IS A SCALAR U */
 /* ------ OUTPUT ARE VALUES OF COONS CUBIC BLEND FUNCTIONS */
 /* ------ (FU(I),I=1,4), THEIR FIRST AND SECOND */
     if (*u < zero || *u > one) {
     goto L100;
     }
 /* ------ DERIVATIVES (FU(I),I=5,12) */
     u2 = *u * *u;
     u3 = u2 * *u;
     dif = u3 - u2;
     fu[1] = dif + dif - u2 + one;
     fu[2] = -fu[1] + one;
     fu[3] = dif - u2 + *u;
     fu[4] = dif;
     dif = three * (u2 - *u);
     fu[5] = dif + dif;
     fu[6] = -fu[5];
     fu[7] = dif - *u + one;
     fu[8] = dif + *u;
     dif = six * *u;
     fu[9] = dif + dif - six;
     fu[10] = -fu[9];
     fu[11] = dif - four;
     fu[12] = dif - two;
     return 0;
 L100:
     for (i__ = 1; i__ <= 12; ++i__) {
 /* L110: */
     fu[i__] = zero;
     }
     if (*u > one) {
     goto L200;
     }
 /* ---  U IS LESS THAN ZERO */
     fu[1] = one;
     fu[3] = *u;
     fu[7] = one;
     return 0;
 L200:
     fu[2] = one;
     fu[4] = *u - one;
     fu[8] = one;
     return 0;
 } /* blendf_ */