My Project: CALCB.c File Reference
CALCB.c File Reference
#include "f2c.h"
Macros
#define interf_1 interf_
Functions
int calcb_ (doublereal *w, doublereal *fwd, doublereal *r__, integer *intloc, doublereal *b, char *type__, doublereal *tl, ftnlen type_len)
Variables
struct {
doublereal dintr [1000]
doublereal uintr [1000]
doublereal vintr [1000]
doublereal ldintr [1000]
doublereal luintr [1000]
doublereal lvintr [1000]
doublereal tpintr [3000]
doublereal spintr [3000]
doublereal snintr [3000]
integer pintr [1000]
integer lpintr [1000]
integer iseg [1000]
integer npintr
integer lnpint
} interf_
static doublereal c_b9 = 1.
Macro Definition Documentation
#define interf_1 interf_
Definition at line 25 of file CALCB.c.
Referenced by calcb_().
Function Documentation
int calcb_ (doublereal * w, doublereal * fwd, doublereal * r__, integer * intloc, doublereal * b, char * type__, doublereal * tl, ftnlen type_len)
Definition at line 33 of file CALCB.c.
References a, c__, c_b9, cross_(), crossv_(), dotf_(), fwd, i__, interf_1, phi, r__, s, t, tl, u, v, vnorm_(), and w.
Referenced by avoid_().
 {
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     double acos(doublereal), d_sign(doublereal *, doublereal *);
     /* Local variables */
     static doublereal a[3], c__;
     static integer i__;
     static doublereal s[3], t[3], u[3], v[3], si, su, sv, phi, spa[3], tpa[3],
          cphi;
     extern /* Subroutine */ int dotf_(doublereal *, doublereal *, doublereal *
         ), cross_(doublereal *, doublereal *, doublereal *), vnorm_(
         doublereal *, doublereal *), crossv_(doublereal *, doublereal *,
         doublereal *);
 /*     PURPOSE:  TO COMPUTE TILT ANGLE B TO AVOID INTERFERENCE */
 /*               AT WORST LOCATION (INTLOC) */
 /*     ARGUMENTS: */
 /*       W      - AXIS THROUGH CONTACT POINT PARLLEL TO TA */
 /*       FWD    - DS FORWARD DIRECTION */
 /*       R      - SURFACE CONTACT POINT AND DERIVATIVES */
 /*       INTLOC - LOCATION IN INTERFERENCE TABLE OF WORST PENETRATION */
 /*       B      - TILT ANGLE TO CLEAR INTERFERENCE */
 /*       TYPE   - TYPE OF TILT (ROLL OR PITCH) */
 /*       TL     - APPROP. LOCAL AXIS THAT DEFINES PLANE OF TILT WITH TA */
 /*     GLOBAL VARIABLES: */
 /*     LOCAL VARIABLES: */
 /*       U      - LOCAL AXIS IN FORWARD DIRECTION PERPTO W */
 /*       V      - LOCAL AXIS ORTHOGONAL TO W AND U */
 /*       S      - SPINTR AT INTLOC WRT LOCAL ORIGIN AT CONTACT POINT */
 /*       T      - TPINTR AT INTLOC WRT LOCAL ORIGIN AT CONTACT POINT */
 /*       SPA    - PROJECTION OF S ONTO WU PLANE */
 /*       TPA    - PROJECTION OF T ONTO WU PLANE */
 /*       CPHI   - COS(PHI) */
 /*       PHI    - TILT ANGLE */
 /*       A      - TPA X SPA */
 /*       SI     - DIRECTION OF PHI (+VE IN FWD DIRECTION) */
 /*       SU,SV  - PROJECTIONS OF S ONTO U AND V AXES */
 /*       C      - WORK VARIABLE */
 /*    INTERFERENCE TABLE */
 /* .... COMPUTE LOCAL AXES AT CONTACT POINT */
     /* Parameter adjustments */
     --tl;
     --r__;
     --fwd;
     --w;
     /* Function Body */
     crossv_(&w[1], &fwd[1], v);
     crossv_(v, &w[1], u);
 /* .... COMPUTE S,T */
     for (i__ = 1; i__ <= 3; ++i__) {
     s[i__ - 1] = interf_1.spintr[i__ + *intloc * 3 - 4] - r__[i__];
     t[i__ - 1] = interf_1.tpintr[i__ + *intloc * 3 - 4] - r__[i__];
 /* L10: */
     }
 /* .... PROJECT S ONTO LOCAL UV PLANE */
     dotf_(&su, s, u);
     dotf_(&sv, s, v);
     if (abs(sv) < 1e-6) {
     c__ = 1e6;
     } else {
     c__ = su / sv;
     }
 /* .... SELECT DIRECTION OF TILT */
     if (abs(c__) >= 1.) {
 /* .... PITCH TOOL - TILT ABOUT V */
     s_copy(type__, "PITCH", (ftnlen)5, (ftnlen)5);
     for (i__ = 1; i__ <= 3; ++i__) {
         tl[i__] = u[i__ - 1];
 /* L20: */
     }
     } else {
 /* .... ROLL TOOL - TILT ABOUT U */
     s_copy(type__, "ROLL", (ftnlen)5, (ftnlen)4);
     for (i__ = 1; i__ <= 3; ++i__) {
         tl[i__] = v[i__ - 1];
 /* L30: */
     }
     }
 /* .... PROJECT S,T ONTO LOCAL PLANE OF TILT */
     if (s_cmp(type__, "PITCH", (ftnlen)5, (ftnlen)5) == 0) {
     dotf_(spa, s, u);
     spa[1] = 0.;
     dotf_(tpa, t, u);
     tpa[1] = 0.;
     } else {
     spa[0] = 0.;
     dotf_(&spa[1], s, v);
     tpa[0] = 0.;
     dotf_(&tpa[1], s, v);
     }
     dotf_(&spa[2], s, &w[1]);
     dotf_(&tpa[2], t, &w[1]);
 /* .... COMPUTE TILT ANGLE PHI */
     vnorm_(spa, spa);
     vnorm_(tpa, tpa);
     dotf_(&cphi, spa, tpa);
     phi = acos(cphi);
 /* .... DETERMINE DIRECTION OF PHI */
     cross_(tpa, spa, a);
     if (s_cmp(type__, "PITCH", (ftnlen)5, (ftnlen)5) == 0) {
     dotf_(&si, a, v);
     } else {
     dotf_(&si, a, u);
     }
     si = d_sign(&c_b9, &si);
 /* .... COMPUTE TILT ANGLE */
     *b = si * phi;
     return 0;
 } /* calcb_ */
Variable Documentation
doublereal c_b9 = 1. static
Definition at line 29 of file CALCB.c.
Referenced by calcb_().
doublereal dintr[1000]
Definition at line 18 of file CALCB.c.
struct { ... } interf_
integer iseg[1000]
Definition at line 22 of file CALCB.c.
doublereal ldintr[1000]
Definition at line 18 of file CALCB.c.
integer lnpint
Definition at line 22 of file CALCB.c.
integer lpintr[1000]
Definition at line 22 of file CALCB.c.
doublereal luintr[1000]
Definition at line 18 of file CALCB.c.
doublereal lvintr[1000]
Definition at line 18 of file CALCB.c.
integer npintr
Definition at line 22 of file CALCB.c.
integer pintr[1000]
Definition at line 22 of file CALCB.c.
doublereal snintr[3000]
Definition at line 18 of file CALCB.c.
doublereal spintr[3000]
Definition at line 18 of file CALCB.c.
doublereal tpintr[3000]
Definition at line 18 of file CALCB.c.
doublereal uintr[1000]
Definition at line 18 of file CALCB.c.
doublereal vintr[1000]
Definition at line 18 of file CALCB.c.