My Project: CALLZZ.c File Reference
CALLZZ.c File Reference
#include "f2c.h"
Macros
#define il_1 il_
#define call ((integer *)&il_1 + 17)
Functions
int callzz_ (integer *index)
Variables
struct {
integer il [21]
} il_
Macro Definition Documentation
#define call ((integer *)&il_1 + 17)
Referenced by callzz_().
#define il_1 il_
Definition at line 21 of file CALLZZ.c.
Function Documentation
int callzz_ (integer * index)
Definition at line 52 of file CALLZZ.c.
References call, onearg_(), and opcode_().
Referenced by boolif_(), comstr_(), goloft_(), gopat_(), inpat_(), larges_(), lcanon_(), macrec_(), motion_(), pro020_(), pro021_(), pro026_(), pro027_(), pro028_(), recog_(), recogn_(), refgen_(), refref_(), ssdef_(), and tssmil_().
 {
     /* Local variables */
 #define call ((integer *)&il_1 + 17)
     extern /* Subroutine */ int opcode_(integer *), onearg_(integer *);
 /*       16.    LITERALS FOR I. L. OPERATION CODES */
 /* CALL:        CONTAINS COMMAND CODE (18) FOR CALL COMMAND */
 /* * */
 /* PURPOSE      TO GENERATE THE I.L. FOR A CALL OPCODE AND */
 /*              THE PROCEDURE INDEX. */
 /* ARGUMENTS    INDEX  NAME TABLE (NAMTBL) INDEX OF THE PROCEDURE NAME. */
 /* ** */
 /* ...     GENERATE CALL OPCODE, AND FIRST ARGUMENT (PROCEDURE INDEX) */
     opcode_(call);
     onearg_(index);
     return 0;
 } /* callzz_ */
Variable Documentation
integer il[21]
Definition at line 18 of file CALLZZ.c.
struct { ... } il_