My Project: CALMCX.c File Reference
CALMCX.c File Reference
#include "f2c.h"
Macros
#define il_1 il_
#define calmc ((integer *)&il_1 + 13)
Functions
int calmcx_ (integer *npntr, integer *lev, integer *indx)
Variables
struct {
integer il [21]
} il_
Macro Definition Documentation
#define calmc ((integer *)&il_1 + 13)
Referenced by calmcx_().
#define il_1 il_
Definition at line 21 of file CALMCX.c.
Function Documentation
int calmcx_ (integer * npntr, integer * lev, integer * indx)
Definition at line 37 of file CALMCX.c.
References calmc, onearg_(), opcode_(), rlslin_(), and twoarg_().
Referenced by input_(), macrec_(), and path_().
 {
     /* Local variables */
 #define calmc ((integer *)&il_1 + 13)
     extern /* Subroutine */ int opcode_(integer *), onearg_(integer *),
         twoarg_(integer *, integer *), rlslin_(void);
 /*       16.    LITERALS FOR I. L. OPERATION CODES */
 /* CALMC:       CONTAINS COMMAND CODE (14) FOR CALMC COMMAND */
 /* * */
 /* PURPOSE      TO GENERATE AND OUTPUT TO THE I.L. INTERNAL */
 /*              RECORD IMAGE (ILFILE) THE CALMC I.L. COMMAND */
 /*              THAT ESTABLISHES LINKAGE WITH REMOTE APT */
 /*              MACRO I.L.. */
 /* ARGUMENTS    NPNTR  NAME TABLE (NAMTBL) INDEX OF LABEL. */
 /*              LEV    LEVEL OF CALL TO MACRO. */
 /* **            INDX   INDEX REGISTER NUMBER. */
 /* ...     GENERATE I.L. CALMC COMMAND */
     opcode_(calmc);
     onearg_(npntr);
     twoarg_(lev, indx);
     rlslin_();
     return 0;
 } /* calmcx_ */
Variable Documentation
integer il[21]
Definition at line 18 of file CALMCX.c.
struct { ... } il_