My Project: CANF.c File Reference
CANF.c File Reference
#include "f2c.h"
Functions
int canf_ (doublereal *res, doublereal *ort, doublereal *arg)
Variables
static integer c__0 = 0
static integer c__39 = 39
static integer c__40 = 40
static integer c__41 = 41
Function Documentation
int canf_ (doublereal * res, doublereal * ort, doublereal * arg)
Definition at line 42 of file CANF.c.
References a, c__0, c__39, c__40, c__41, ckdef_(), error_(), i__, ir, isize, isub, mode, transf_(), undef_(), and unpack_().
Referenced by xcall_().
 {
     /* Initialized data */
     static integer ir[20] = { 4,4,5,5,2,1,1,1,5,1,0,0,0,1,0,0,0,0,2,3 };
     static doublereal a[12];
     static integer i__, mode, isub;
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int undef_(doublereal *);
     static integer isize;
     extern /* Subroutine */ int error_(integer *, char *, ftnlen), unpack_(
         doublereal *, integer *, integer *, integer *), transf_(
         doublereal *, doublereal *, integer *, integer *, integer *);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
 /* ...     CHECK OB KANONISCHE FORM DEFINIERT */
     if (ckdef_(&arg[1])) {
     goto L20;
     }
 /* ...     KONTROLLE OB KANONISCHE FORM LANG GENUG */
     i__ = (integer) (*ort);
     unpack_(&arg[1], &mode, &isize, &isub);
     if (i__ <= 0) {
     goto L22;
     }
     if (i__ > isize) {
     goto L21;
     }
 /* ...     KONTROLLE OB TRANSFORMIERT WERDEN KANN UND TRANSFORMATION */
     if (mode == 18) {
     goto L10;
     }
     if (mode <= 0 || mode > 20 || ir[mode - 1] == 0) {
     goto L20;
     }
     transf_(a, &arg[1], &ir[mode - 1], &isize, &c__0);
     res[1] = a[i__ - 1];
     return 0;
 /*   MATRIX-ABGRIFF */
 L10:
     res[1] = arg[i__];
     return 0;
 /* ...   'GEOMETRIE NICHT DEFINIERT' */
 L20:
     error_(&c__39, "CANF    ", (ftnlen)8);
     goto L23;
 /* ...   'KANONISCHE FORM ZU KURZ FUER INDEX ODER INDEX NICHT DEFINIERT' */
 L21:
     error_(&c__40, "CANF    ", (ftnlen)8);
     goto L23;
 /* ...   'INDEX KLEINER ODER GLEICH NULL' */
 L22:
     error_(&c__41, "CANF    ", (ftnlen)8);
 L23:
     undef_(&res[1]);
     return 0;
 } /* canf_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 17 of file CANF.c.
Referenced by canf_().
integer c__39 = 39 static
Definition at line 18 of file CANF.c.
Referenced by canf_().
integer c__40 = 40 static
Definition at line 19 of file CANF.c.
Referenced by canf_().
integer c__41 = 41 static
Definition at line 20 of file CANF.c.
Referenced by canf_().