My Project: CCURV.c File Reference
CCURV.c File Reference
#include "f2c.h"
Macros
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int ccurv_ (integer *issto, doublereal *sp3, doublereal *spl3, doublereal *sn3)
Variables
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
Macro Definition Documentation
#define charct_1 charct_
Definition at line 30 of file CCURV.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define fxcor_1 fxcor_
Definition at line 24 of file CCURV.c.
Referenced by ccurv_().
#define ifxcor_1 ifxcor_
Definition at line 89 of file CCURV.c.
Referenced by ccurv_().
#define ishr18_1 ishr18_
Definition at line 97 of file CCURV.c.
#define isv1_1 isv1_
Definition at line 79 of file CCURV.c.
#define isv_1 isv_
Definition at line 72 of file CCURV.c.
Referenced by ccurv_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sv1_1 sv1_
Definition at line 63 of file CCURV.c.
#define sv_1 sv_
Definition at line 54 of file CCURV.c.
Referenced by ccurv_().
#define tlldat_1 tlldat_
Definition at line 37 of file CCURV.c.
Function Documentation
int ccurv_ (integer * issto, doublereal * sp3, doublereal * spl3, doublereal * sn3)
Definition at line 102 of file CCURV.c.
References dotf_(), fxcor_1, i__, ifxcor_1, isv_1, n, sv_1, vnorm_(), w1, z1em3, z1em9, and zero.
Referenced by amind_(), cplan_(), delta_(), and tlnorm_().
 {
     /* Initialized data */
     static doublereal z1em3 = .001;
     static doublereal z1em4 = 1e-5;
     static doublereal z1em9 = 1e-9;
     static doublereal zero = 0.;
     static doublereal z100 = 100.;
     /* System generated locals */
     doublereal d__1;
     /* Builtin functions */
     double d_sign(doublereal *, doublereal *);
     /* Local variables */
     static integer i__, n;
     static doublereal w1;
     extern /* Subroutine */ int dotf_(doublereal *, doublereal *, doublereal *
         );
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     extern /* Subroutine */ int vnorm_(doublereal *, doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
     /* Parameter adjustments */
     --sn3;
     --spl3;
     --sp3;
     /* Function Body */
 /*             /-INPUT SURFACE PT -SP3, AND NORMAL SN3, AND LAST POINT SP */
 /*             /-ISSTO IS INDEX TO CURRENT SURFACE(2=PART,3=DRIVE ETC) */
 /*             /-FIND SURFACE CENTER OF CURVATURE AND RADIUS(CC,RC) */
     if (isv_1.ipl[(120 + (0 + (*issto - 1 << 2)) - 120) / 4] == 0) {
     goto L1;
     }
 /*             /-PLANAR SURFACE CASE - IPL=1 */
     isv_1.isigcr[*issto - 1] = -1;
     goto L6;
 L1:
 /*             /-NON-PLANAR GENERAL CASE */
 /*             /-CHECK FOR SIGNIFICANCE OF SP-SPL */
 /*             /-N=0 MEANS SP-SPL IS TOO SMALL FOR CALCULATION */
     n = 1;
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.temp[i__ - 1] = sp3[i__] - spl3[i__];
     if ((d__1 = fxcor_1.temp[i__ - 1], abs(d__1)) > z1em3) {
         n = 0;
     }
 /* L2: */
     }
     if (n <= 0) {
     goto L3;
     }
 /*             /-SP-SPL INSIGNIFICANT, USE LAST RC */
     isv_1.isigcr[*issto - 1] = 1;
     goto L6;
 L3:
 /*             /-NORMAL CASE FOR GENERAL SURFACE */
     vnorm_(fxcor_1.temp, &fxcor_1.temp[3]);
     dotf_(&w1, &fxcor_1.temp[3], &sn3[1]);
     if (abs(w1) >= z1em4) {
     goto L4;
     }
 /*             /-SP-SPL ALMOST PERPENDICULAR TO SN . SET RC 45 INCH */
 L30:
     d__1 = fxcor_1.rc1 / z100;
     sv_1.rc[*issto - 1] = d_sign(&d__1, &sv_1.rc[*issto - 1]);
     isv_1.isigcr[*issto - 1] = -1;
     goto L6;
 L4:
 /*     CHECK, WHETHER SURFACE IS LOCALLY ALMOST PLANAR */
     dotf_(&w1, fxcor_1.ta, &sn3[1]);
     if (abs(w1) >= 1. - z1em4 && ifxcor_1.mantax < 2) {
     goto L30;
     }
 /*             /-GENERAL CASE, CALCULATE R SO THAT (SP-R*SN-SPL)**2=R**2 */
 /*             /-CENTER OF CURV. IS ON SIDE OF SN IF RC NEGATIVE. */
     dotf_(&w1, fxcor_1.temp, &sn3[1]);
     dotf_(&sv_1.rc[*issto - 1], fxcor_1.temp, fxcor_1.temp);
 /*             /-R=D**2/(2*(D,SN)) WHERE D=SP-SPL */
     sv_1.rc[*issto - 1] /= w1 + w1;
 /*             /-SET FLAG TO NORMAL CASE */
     isv_1.isigcr[*issto - 1] = 0;
 /*             /-COMMON RETURN POINT FOR ALL CASES */
 L6:
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.cc[i__ + *issto * 3 - 4] = sp3[i__] - sv_1.rc[*issto - 1] * sn3[
         i__];
     if ((d__1 = sv_1.cc[i__ + *issto * 3 - 4], abs(d__1)) < z1em9) {
         sv_1.cc[i__ + *issto * 3 - 4] = zero;
     }
 /* L7: */
     }
     return 0;
 } /* ccurv_ */
Variable Documentation
doublereal alp
Definition at line 18 of file CCURV.c.
doublereal ax4[3]
Definition at line 18 of file CCURV.c.
doublereal cagl
Definition at line 18 of file CCURV.c.
doublereal cc[15]
Definition at line 40 of file CCURV.c.
struct { ... } charct_
doublereal corrad[8]
Definition at line 33 of file CCURV.c.
doublereal cos1[5]
Definition at line 57 of file CCURV.c.
doublereal cplfl[5]
Definition at line 57 of file CCURV.c.
doublereal cptst[5]
Definition at line 57 of file CCURV.c.
doublereal csd[5]
Definition at line 57 of file CCURV.c.
doublereal cutdat[7]
Definition at line 18 of file CCURV.c.
doublereal dplan[15]
Definition at line 57 of file CCURV.c.
doublereal dpmax
Definition at line 18 of file CCURV.c.
doublereal dpmx1[5]
Definition at line 57 of file CCURV.c.
doublereal eps1[5]
Definition at line 40 of file CCURV.c.
doublereal eps2[5]
Definition at line 40 of file CCURV.c.
doublereal eps3[5]
Definition at line 40 of file CCURV.c.
doublereal eps4[5]
Definition at line 40 of file CCURV.c.
doublereal eps6[5]
Definition at line 40 of file CCURV.c.
doublereal eps8[5]
Definition at line 40 of file CCURV.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 18 of file CCURV.c.
doublereal hi
Definition at line 18 of file CCURV.c.
integer i3dflg
Definition at line 82 of file CCURV.c.
integer iaerr
Definition at line 82 of file CCURV.c.
integer iafl[5]
Definition at line 66 of file CCURV.c.
integer iamdct
Definition at line 92 of file CCURV.c.
integer iautps
Definition at line 82 of file CCURV.c.
integer ibegin
Definition at line 82 of file CCURV.c.
integer ic
Definition at line 82 of file CCURV.c.
integer icanon[5]
Definition at line 66 of file CCURV.c.
integer icheck
Definition at line 82 of file CCURV.c.
integer icl
Definition at line 82 of file CCURV.c.
integer ics
Definition at line 82 of file CCURV.c.
integer icscnt
Definition at line 82 of file CCURV.c.
integer ictdef
Definition at line 82 of file CCURV.c.
integer icut
Definition at line 82 of file CCURV.c.
integer ids
Definition at line 82 of file CCURV.c.
integer ier
Definition at line 82 of file CCURV.c.
integer ifar[5]
Definition at line 75 of file CCURV.c.
integer ifl4[5]
Definition at line 75 of file CCURV.c.
struct { ... } ifxcor_
integer igo
Definition at line 82 of file CCURV.c.
integer igoto
Definition at line 82 of file CCURV.c.
integer igoug
Definition at line 82 of file CCURV.c.
integer igs
Definition at line 82 of file CCURV.c.
integer index[5]
Definition at line 66 of file CCURV.c.
integer indir__[5]
Definition at line 66 of file CCURV.c.
integer inops
Definition at line 82 of file CCURV.c.
integer iop[5]
Definition at line 66 of file CCURV.c.
integer iopset[5]
Definition at line 66 of file CCURV.c.
integer ipdpl
Definition at line 92 of file CCURV.c.
integer ipl[5]
Definition at line 66 of file CCURV.c.
integer ips
Definition at line 82 of file CCURV.c.
integer ipsdef
Definition at line 82 of file CCURV.c.
integer ipt
Definition at line 92 of file CCURV.c.
integer ipt1
Definition at line 82 of file CCURV.c.
integer is
Definition at line 82 of file CCURV.c.
integer iseg
Definition at line 82 of file CCURV.c.
integer iseqno
Definition at line 82 of file CCURV.c.
integer isfidn[5]
Definition at line 66 of file CCURV.c.
integer isftyp[5]
Definition at line 66 of file CCURV.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 66 of file CCURV.c.
integer isrch
Definition at line 82 of file CCURV.c.
integer istrup
Definition at line 82 of file CCURV.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 66 of file CCURV.c.
integer it
Definition at line 82 of file CCURV.c.
integer itlon[5]
Definition at line 66 of file CCURV.c.
integer itseg[5]
Definition at line 66 of file CCURV.c.
integer itsegk[5]
Definition at line 66 of file CCURV.c.
integer iunfl[5]
Definition at line 66 of file CCURV.c.
integer iws
Definition at line 92 of file CCURV.c.
integer j10
Definition at line 92 of file CCURV.c.
integer j12
Definition at line 92 of file CCURV.c.
integer j13
Definition at line 92 of file CCURV.c.
integer j20[5]
Definition at line 75 of file CCURV.c.
integer j21[5]
Definition at line 75 of file CCURV.c.
integer j22[5]
Definition at line 75 of file CCURV.c.
integer j23[5]
Definition at line 75 of file CCURV.c.
integer j50[5]
Definition at line 75 of file CCURV.c.
integer j51[5]
Definition at line 75 of file CCURV.c.
integer j54
Definition at line 92 of file CCURV.c.
integer jbr
Definition at line 82 of file CCURV.c.
integer jckr
Definition at line 92 of file CCURV.c.
integer jcnt1
Definition at line 92 of file CCURV.c.
integer jcnt2
Definition at line 92 of file CCURV.c.
integer jcnt3
Definition at line 92 of file CCURV.c.
integer jcpr
Definition at line 92 of file CCURV.c.
integer jcr
Definition at line 92 of file CCURV.c.
integer jdr
Definition at line 92 of file CCURV.c.
integer jent[5]
Definition at line 66 of file CCURV.c.
integer jfind
Definition at line 92 of file CCURV.c.
integer jgr
Definition at line 92 of file CCURV.c.
integer jiops[5]
Definition at line 66 of file CCURV.c.
integer jmin
Definition at line 92 of file CCURV.c.
integer jminr
Definition at line 92 of file CCURV.c.
integer jph[5]
Definition at line 75 of file CCURV.c.
integer jpr
Definition at line 92 of file CCURV.c.
integer jpxr
Definition at line 92 of file CCURV.c.
integer jsw
Definition at line 82 of file CCURV.c.
integer jtkf
Definition at line 92 of file CCURV.c.
integer jtlflg[5]
Definition at line 66 of file CCURV.c.
integer jtn[5]
Definition at line 66 of file CCURV.c.
integer jtr
Definition at line 92 of file CCURV.c.
integer ju1[5]
Definition at line 66 of file CCURV.c.
integer limfl[5]
Definition at line 66 of file CCURV.c.
integer lsv
Definition at line 82 of file CCURV.c.
integer lsv1
Definition at line 82 of file CCURV.c.
integer mantax
Definition at line 82 of file CCURV.c.
integer mdic
Definition at line 92 of file CCURV.c.
char modfer[6]
Definition at line 27 of file CCURV.c.
integer motmod
Definition at line 82 of file CCURV.c.
integer msav
Definition at line 82 of file CCURV.c.
integer mulout
Definition at line 82 of file CCURV.c.
integer nmbseg
Definition at line 82 of file CCURV.c.
integer nmpnts
Definition at line 82 of file CCURV.c.
integer notan[5]
Definition at line 75 of file CCURV.c.
integer nrec
Definition at line 82 of file CCURV.c.
integer numax
Definition at line 82 of file CCURV.c.
integer numcnt
Definition at line 82 of file CCURV.c.
integer nump
Definition at line 82 of file CCURV.c.
integer numpt1
Definition at line 82 of file CCURV.c.
integer numsfs
Definition at line 82 of file CCURV.c.
integer numsur
Definition at line 82 of file CCURV.c.
integer nw
Definition at line 82 of file CCURV.c.
integer nwds
Definition at line 82 of file CCURV.c.
doublereal past[5]
Definition at line 40 of file CCURV.c.
doublereal plncs[5]
Definition at line 57 of file CCURV.c.
doublereal plnd[5]
Definition at line 40 of file CCURV.c.
doublereal plnd1[5]
Definition at line 57 of file CCURV.c.
doublereal plnv[15]
Definition at line 40 of file CCURV.c.
doublereal pltst[5]
Definition at line 57 of file CCURV.c.
doublereal pmove[3]
Definition at line 18 of file CCURV.c.
doublereal ra
Definition at line 18 of file CCURV.c.
doublereal rc[5]
Definition at line 40 of file CCURV.c.
doublereal rc1
Definition at line 18 of file CCURV.c.
doublereal ri[8]
Definition at line 33 of file CCURV.c.
doublereal s[5]
Definition at line 40 of file CCURV.c.
doublereal sagl
Definition at line 18 of file CCURV.c.
doublereal save[5]
Definition at line 40 of file CCURV.c.
doublereal sfvct[15]
Definition at line 40 of file CCURV.c.
doublereal sk[15]
Definition at line 40 of file CCURV.c.
doublereal slx[15]
Definition at line 40 of file CCURV.c.
doublereal sn[15]
Definition at line 40 of file CCURV.c.
doublereal snk[15]
Definition at line 40 of file CCURV.c.
doublereal snl[15]
Definition at line 40 of file CCURV.c.
doublereal sp[15]
Definition at line 40 of file CCURV.c.
doublereal spk[15]
Definition at line 40 of file CCURV.c.
doublereal spl[15]
Definition at line 40 of file CCURV.c.
doublereal stck[5]
Definition at line 57 of file CCURV.c.
doublereal stck1[5]
Definition at line 57 of file CCURV.c.
doublereal stck2[5]
Definition at line 57 of file CCURV.c.
doublereal stckn[5]
Definition at line 57 of file CCURV.c.
doublereal strtno
Definition at line 18 of file CCURV.c.
doublereal surd
Definition at line 18 of file CCURV.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 18 of file CCURV.c.
doublereal tak[3]
Definition at line 18 of file CCURV.c.
doublereal tal[3]
Definition at line 18 of file CCURV.c.
doublereal tanhi[8]
Definition at line 33 of file CCURV.c.
doublereal tanlo[8]
Definition at line 33 of file CCURV.c.
doublereal tau[5]
Definition at line 40 of file CCURV.c.
doublereal tau1[5]
Definition at line 40 of file CCURV.c.
doublereal tau2[5]
Definition at line 40 of file CCURV.c.
doublereal tcont[9]
Definition at line 33 of file CCURV.c.
doublereal te[3]
Definition at line 18 of file CCURV.c.
doublereal tee[15]
Definition at line 57 of file CCURV.c.
doublereal tek[3]
Definition at line 18 of file CCURV.c.
doublereal tel[3]
Definition at line 18 of file CCURV.c.
doublereal tem[10]
Definition at line 18 of file CCURV.c.
doublereal temp[24]
Definition at line 18 of file CCURV.c.
doublereal th[5]
Definition at line 40 of file CCURV.c.
doublereal ti[3]
Definition at line 18 of file CCURV.c.
doublereal tik[3]
Definition at line 18 of file CCURV.c.
doublereal til[3]
Definition at line 18 of file CCURV.c.
doublereal tlhit
Definition at line 18 of file CCURV.c.
doublereal tlhite[8]
Definition at line 33 of file CCURV.c.
doublereal tlinc[9]
Definition at line 33 of file CCURV.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 18 of file CCURV.c.
doublereal tn[15]
Definition at line 40 of file CCURV.c.
doublereal tnl[15]
Definition at line 57 of file CCURV.c.
doublereal toolht[15]
Definition at line 40 of file CCURV.c.
doublereal toolwd[5]
Definition at line 40 of file CCURV.c.
doublereal tp[15]
Definition at line 40 of file CCURV.c.
doublereal tpk[15]
Definition at line 40 of file CCURV.c.
doublereal u1[15]
Definition at line 40 of file CCURV.c.
doublereal u1k[15]
Definition at line 40 of file CCURV.c.
doublereal umax[8]
Definition at line 33 of file CCURV.c.
doublereal varble[5]
Definition at line 40 of file CCURV.c.
doublereal vndir[15]
Definition at line 40 of file CCURV.c.
doublereal vt[15]
Definition at line 40 of file CCURV.c.
doublereal vtem
Definition at line 18 of file CCURV.c.
doublereal z__[5]
Definition at line 40 of file CCURV.c.