My Project: CENTR.c File Reference
CENTR.c File Reference
#include "f2c.h"
Macros
#define dshar4_1 dshar4_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define addcom_1 addcom_
#define chang_1 chang_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define kdynfl ((integer *)&addcom_1 + 48)
Functions
int centr_ (void)
Variables
struct {
doublereal a
doublereal b
doublereal c__
doublereal cendis
doublereal cmove [3]
doublereal com1
doublereal com4
doublereal dir [3]
doublereal dp
doublereal dpe
doublereal dpcnt
doublereal dpi
doublereal dpl
doublereal dp1
doublereal d1
doublereal d2a
doublereal flipck
doublereal fwd [3]
doublereal ogle [3]
doublereal p1 [3]
doublereal p2 [3]
doublereal rdrn
doublereal refpnt [3]
doublereal tangl
doublereal tes [3]
doublereal tew [3]
doublereal uvec [3]
doublereal u2 [3]
doublereal v [3]
doublereal vl
doublereal zl
doublereal zlnorm [3]
doublereal zlpnt [3]
doublereal zl1
doublereal param [6]
doublereal r__ [6]
doublereal savpar [4]
doublereal seg [9]
doublereal slope
doublereal sqroot
doublereal unn
doublereal upp
doublereal vint
doublereal vnn
doublereal vpp
} dshar4_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
doublereal addcom [25]
} addcom_
struct {
integer jteneu
} chang_
static integer c__25009 = 25009
static integer c__25008 = 25008
static integer c__25007 = 25007
static integer c__25004 = 25004
static integer c__25003 = 25003
static integer c__25005 = 25005
static integer c__25002 = 25002
Macro Definition Documentation
#define addcom_1 addcom_
Definition at line 129 of file CENTR.c.
#define chang_1 chang_
Definition at line 135 of file CENTR.c.
Referenced by centr_().
#define charct_1 charct_
Definition at line 40 of file CENTR.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dshar4_1 dshar4_
Definition at line 25 of file CENTR.c.
Referenced by centr_().
#define fxcor_1 fxcor_
Definition at line 34 of file CENTR.c.
Referenced by centr_().
#define ifxcor_1 ifxcor_
Definition at line 107 of file CENTR.c.
Referenced by centr_().
#define ishr18_1 ishr18_
Definition at line 115 of file CENTR.c.
Referenced by centr_().
#define isv1_1 isv1_
Definition at line 97 of file CENTR.c.
Referenced by centr_().
#define isv_1 isv_
Definition at line 90 of file CENTR.c.
Referenced by centr_().
#define kdynfl ((integer *)&addcom_1 + 48)
Referenced by centr_().
#define knumbr_1 knumbr_
Definition at line 123 of file CENTR.c.
Referenced by centr_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sv1_1 sv1_
Definition at line 73 of file CENTR.c.
Referenced by centr_().
#define sv_1 sv_
Definition at line 64 of file CENTR.c.
Referenced by centr_().
#define tlldat_1 tlldat_
Definition at line 47 of file CENTR.c.
#define znumbr_1 znumbr_
Definition at line 81 of file CENTR.c.
Referenced by centr_().
Function Documentation
int centr_ (void)
Definition at line 151 of file CENTR.c.
References aerr_(), altcmv_(), amind_(), apt238_(), c__25002, c__25003, c__25004, c__25005, c__25007, c__25008, c__25009, chang_1, cplan_(), cross_(), dshar4_1, f, fxcor_1, gauss_(), i__, ifxcor_1, ishr18_1, isv1_1, isv_1, kdynfl, knumbr_1, sv1_1, sv_1, tinkr_(), vnorm_(), and znumbr_1.
Referenced by arlm3_(), go2_(), and plane_().
 {
     /* Format strings */
     static char fmt_210[] = "";
     static char fmt_600[] = "";
     static char fmt_1000[] = "";
     static char fmt_302[] = "";
     static char fmt_310[] = "";
     static char fmt_900[] = "";
     static char fmt_320[] = "";
     static char fmt_410[] = "";
     static char fmt_1400[] = "";
     static char fmt_420[] = "";
     static char fmt_471[] = "";
     static char fmt_482[] = "";
     static char fmt_510[] = "";
     static char fmt_520[] = "";
     static char fmt_531[] = "";
     static char fmt_532[] = "";
     static char fmt_550[] = "";
     static char fmt_570[] = "";
     static char fmt_605[] = "";
     static char fmt_922[] = "";
     /* System generated locals */
     integer i__1, i__2;
     doublereal d__1, d__2, d__3, d__4, d__5;
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     static integer i__, im, ik;
     static doublereal acc;
     static integer iii, jfpd;
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static doublereal teza[3];
     static logical lret;
     static integer jtrc;
     static doublereal ptol;
     static integer jtol;
     extern /* Subroutine */ int apt238_(integer *), amind_(void), cplan_(void)
         ;
     static integer itink;
     static doublereal smove, saves;
     extern /* Subroutine */ int cross_(doublereal *, doublereal *, doublereal
         *), vnorm_(doublereal *, doublereal *), gauss_(doublereal *,
         doublereal *, doublereal *, doublereal *, doublereal *,
         doublereal *, doublereal *, integer *);
     static doublereal simax, bcmov;
     static integer issto;
     extern /* Subroutine */ int tinkr_(void);
     static integer j2surf, jfndck;
     static doublereal tanang;
     static integer jcplan;
     static doublereal saveta[3];
 #define kdynfl ((integer *)&addcom_1 + 48)
     static doublereal savete[3];
     static integer itolfl, jcmove, jtstck;
     extern /* Subroutine */ int altcmv_(integer *, doublereal *, doublereal *,
          integer *, integer *, doublereal *, doublereal *, doublereal *,
         doublereal *, logical *);
     static integer jtstpd;
     /* Assigned format variables */
     static char *j2surf_fmt, *jfpd_fmt, *jfndck_fmt, *jtstpd_fmt, *jtstck_fmt,
          *jcplan_fmt, *jcmove_fmt;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /* ...  21. ADDCOM BLOCK */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ---- FLAG INTRODUCED BY VW - USED TO INDICATE IF TE HAS CHANGED */
 /*                             JTENEU = 1 NO CHANGE FOR TE */
 /*                                    = 0 TE HAS CHANGED */
 /*                   ACC       FUDGE TERM FOR DISTANCE MEASUREMENTS, SET */
 /*                             AT 5.E-6 */
 /*                  IM       FLAG USED IN ORIENTING TANGENT CS NORMAL */
 /*                           WITH OTHER SURFACE NORMAL. */
 /*                   PTOL      FRACTION OF TOTAL TOLERANCE BAND ABOUT */
 /*                             PLANES WITHIN WHICH TOOL IS CONSTRAINED */
 /*                             TO LIE. INITIALLY .2, ENLARGED TO 1.0 AS */
 /*                             ITERATION COUNT INCREASES. */
 /*                   SAVETA(3) SAVES TOOL AXIS DURING NOTAN STEP. */
 /*                   SAVETE(3) SAVES TOOL END POSITION DURING NOTAN STEP. */
 /*                   SAVES     SAVES DISTANCE TO ALL 3 SURFACES ON ENTRY */
 /*                             TO NOTAN STEP.  USED AS A CRITERION FOR */
 /*                             POSSIBLE RESTART FROM ENTRY TO NOTAN. */
 /*                   SMOVE     MAGNITUDE OF SMALLEST VECTOR WHICH CAN BE */
 /*                             ADDED TO TOOL END WITHIN SINGLE PRECISION. */
 /*                             SET ON ENTRY TO CENTR.   ALL MOVE VECTORS */
 /*                             ARE ENLARGED TO THIS SIZE IF NECESSARY */
 /*                   TANANG    CRITERION FOR ESTABLISHING PSEUDO-TANGENCY */
 /*                             IS DOT(CHECK SURF NORMAL, OTHER SURF */
 /*                             NORMAL) .GT. TANANG.  SET AT 1-.5*TAU. */
 /*                   PURPOSE   TO ITERATE CUTTER TO DESIRED POSITION */
 /*                             RELATIVE TO 2 OR 3 SURFACES */
 /* ----------------------------------------------------------------------- */
 /*     MAIN ROUTINE */
 /* ...                INITIALIZATIONS */
     itink = 0;
     itolfl = 0;
     ishr18_1.jtkf = 0;
     for (i__ = 1; i__ <= 3; ++i__) {
     teza[i__ - 1] = fxcor_1.te[i__ - 1];
 /* L1: */
     }
 /*                                       TINKR FAILURE COUNTER */
     jtrc = 10;
 /*                                       PLANE TOLERANCE LIMIT FACTOR */
     ptol = .2f;
 /*                                       PARALLEL SURFACE TOLERANCE */
     tanang = 1.f - sv_1.tau[ifxcor_1.is - 1] * .5f;
     if (tanang < znumbr_1.z9em1) {
     tanang = znumbr_1.z9em1;
     }
 /*                                       EPSILON FOR DISTANCES */
     acc = 5e-6;
 /*                                       MAGNITUDE OF SMALLEST MOVE WHICH */
 /*                                       CAN BE MADE IN SINGLE PRECISION */
 /* Computing MAX */
     d__1 = abs(fxcor_1.te[0]), d__2 = abs(fxcor_1.te[1]), d__1 = max(d__1,
         d__2), d__2 = abs(fxcor_1.te[2]);
     smove = max(d__1,d__2) * 1e-7;
 /*                                       CPLAN FLAGS */
     sv1_1.cplfl[ifxcor_1.is - 1] = 0.f;
     sv1_1.cptst[ifxcor_1.is - 1] = 0.f;
 /* ...                SET ITERATION COUNTERS */
 /*                                       5-AXIS RESTART COUNTER */
     ishr18_1.jcnt3 = 25;
 /*                                       NOTAN CPLAN COUNTER */
 L100:
     ishr18_1.jcnt2 = 25;
 /*                                       BASIC CMOVE ITERATION COUNTER */
     ishr18_1.jcnt1 = 25;
 /* ...                CALL 2 SURF IF 2 SURFACE ITERATION */
 L105:
     if (isv1_1.j51[ifxcor_1.is - 1] <= 0) {
     goto L200;
     } else {
     goto L120;
     }
 /* ...                CALL TANTO FOR TANGENT CS, OTHERWISE 3 SURF */
 L120:
     if (isv_1.isftyp[ifxcor_1.is - 1] - 4 != 0) {
     goto L300;
     } else {
     goto L400;
     }
 /*                                       GO TO EXIT */
 L130:
     goto L1100;
 /* ----------------------------------------------------------------------- */
 /*     2 SURF - ITERATE TOOL INTO PART AND DRIVE ONLY */
 /* ...                CALL 2 SURF ITERAT */
 L200:
     j2surf = 0;
     j2surf_fmt = fmt_210;
     goto L600;
 /* ...                SET FLAG, 2 SURFACE ITERATION SUCCESSFUL */
 L210:
     ishr18_1.jcr = 0;
 /* ...                RETURN TO MAIN PROGRAM */
     goto L130;
 /* ----------------------------------------------------------------------- */
 /*     3 SURF - ITERATE TOOL TO PART, DRIVE, AND CHECK SURFACES */
 /* ...                FIND PART AND DRIVE SURFACES */
 L300:
     jfpd = 0;
     jfpd_fmt = fmt_1000;
 /* ...                FIND CHECK SURFACE */
     jfndck = 0;
     jfndck_fmt = fmt_302;
     goto L800;
 /* ...                FETCH CHECK DATA */
 /*                                       NORMAL */
 L302:
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.plnv[i__ + ifxcor_1.is * 3 - 4] = sv_1.tn[i__ + ifxcor_1.is * 3
         - 4];
 /* L305: */
     }
 /*                                       DISTANCE */
     sv_1.plnd[ifxcor_1.is - 1] = sv_1.s[ifxcor_1.is - 1];
 /* ...                TEST PART AND DRIVE SURFACES */
     jtstpd = 0;
     jtstpd_fmt = fmt_310;
     goto L900;
 L310:
     if (jtol <= 0) {
     goto L330;
     } else {
     goto L315;
     }
 /* ...                BOTH WITHIN LIMIT, CALL TEST CHECK SURF */
 L315:
     jtstck = 0;
     jtstck_fmt = fmt_320;
     goto L1300;
 L320:
     if (jtol <= 0) {
     goto L330;
     } else {
     goto L380;
     }
 /* ...                TEST IF PSEUDO-TANGENCY ALREADY HANDLED */
 L330:
     if (isv1_1.notan[ifxcor_1.is - 1] >= 0) {
     goto L340;
     } else {
     goto L365;
     }
 /* ...                TEST IF PSEUDO-TANGENCY HAS DEVELOPED */
 /*                                       TEST CHECK SURF BEYOND STEP */
 L340:
     if ((d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1)) - dshar4_1.dp <= 0.) {
     goto L350;
     } else {
     goto L365;
     }
 /*                                       TEST SURFACE TANGENCY */
 L350:
     i__1 = ifxcor_1.ids;
     i__2 = ifxcor_1.lsv;
     for (i__ = ifxcor_1.ips; i__2 < 0 ? i__ >= i__1 : i__ <= i__1; i__ +=
         i__2) {
     if (tanang - (d__1 = sv_1.sn[ifxcor_1.is * 3 - 3] * sv_1.sn[i__ * 3 -
         3] + sv_1.sn[ifxcor_1.is * 3 - 2] * sv_1.sn[i__ * 3 - 2] +
         sv_1.sn[ifxcor_1.is * 3 - 1] * sv_1.sn[i__ * 3 - 1], abs(d__1)
         ) >= 0.) {
         goto L360;
     } else {
         goto L370;
     }
 L360:
     ;
     }
 /*                                       NO PSEUDO-TAN */
 /* ...                CALL CMOVE AND LOOP */
 L365:
     jcmove = 0;
     goto L700;
 /* ...                PSEUDO TANGENCY CASE */
 /*                                       SET FLAG FOR TANGENT SURF */
 L370:
     isv1_1.ifl4[ifxcor_1.is - 1] = (ifxcor_1.ids - i__) / ifxcor_1.lsv;
 /*                                       CALL NOTAN AND LOOP */
     goto L500;
 /* ...                SET FLAG, SUCCESSFUL 3-SURF ITERATION */
 L380:
     ishr18_1.jcr = 1;
     goto L1100;
 /* ----------------------------------------------------------------------- */
 /*     TANTO -  3 SURFACE ITERATION IN TANTO OR PSTAN CASE */
 /* ...                CALL FIND PART AND DRIVE */
 L400:
     if (isv1_1.ifl4[ifxcor_1.is - 1] == 0 && (isv_1.isfidn[ifxcor_1.ids - 1]
         > 2 || isv_1.isfidn[ifxcor_1.ics - 1] > 2)) {
     goto L402;
     }
     if (isv1_1.ifl4[ifxcor_1.is - 1] == 1 && (isv_1.isfidn[ifxcor_1.ips - 1]
         > 2 || isv_1.isfidn[ifxcor_1.ics - 1] > 2)) {
     goto L402;
     }
     if (isv_1.isfidn[ifxcor_1.ips - 1] <= 2) {
     aerr_(&c__25009, "CENTR   ", (ftnlen)8);
     }
 L402:
     im = -1;
     jfpd = 1;
     jfpd_fmt = fmt_410;
     goto L800;
 /* ...                CALL FIND CHECK */
 L410:
     jfndck = 1;
     jfndck_fmt = fmt_1400;
 /* ...                CALL CPLAN SURF */
     jcplan = 0;
     jcplan_fmt = fmt_420;
     goto L1000;
 /* ...                TEST WHETHER NORMALS HAVE SAME ORIENTATION */
 L420:
     if (sv1_1.plncs[ifxcor_1.is - 1] >= 0.) {
     goto L460;
     } else {
     goto L430;
     }
 /* ...                OPPOSITE, TEST WHETHER TOOL NORMAL ALREADY REVERSED */
 L430:
     if (im >= 0) {
     goto L450;
     } else {
     goto L440;
     }
 /* ...                NOT REVERSED, REVERSE AND SET FLAG */
 L440:
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = -sv_1.tn[i__ + ifxcor_1.is * 3 -
         4];
 /* L445: */
     }
     im = 0;
     goto L410;
 /* ...                NORMAL REVERSED, TEST WHETHER NORMALS NEAR ORTHOG */
 L450:
     if ((d__1 = sv1_1.plncs[ifxcor_1.is - 1], abs(d__1)) - .01f >= 0.) {
     goto L452;
     } else {
     goto L455;
     }
 /* ...                NEAR ORTHOGONAL, ERROR EXIT */
 L452:
     aerr_(&c__25008, "CENTR   ", (ftnlen)8);
 /* ...                RESET TOOL NORM REVERSAL FLAG */
 L455:
     im = -1;
 /* ...                TEST WHETHER WITHIN 2*TAU OF CPLAN */
 L460:
     if ((d__1 = sv_1.plnd[ifxcor_1.is - 1], abs(d__1)) - sv_1.eps4[
         ifxcor_1.is - 1] <= 0.) {
     goto L462;
     } else {
     goto L464;
     }
 /* ...                WITHIN 2*TAU, TEST WHETHER NORMALS PARALLEL */
 L462:
     if (tanang - (d__1 = sv_1.sn[ifxcor_1.is * 3 - 3] * sv_1.sn[ifxcor_1.it *
         3 - 3] + sv_1.sn[ifxcor_1.is * 3 - 2] * sv_1.sn[ifxcor_1.it * 3 -
         2] + sv_1.sn[ifxcor_1.is * 3 - 1] * sv_1.sn[ifxcor_1.it * 3 - 1],
         abs(d__1)) <= 0.) {
     goto L480;
     } else {
     goto L464;
     }
 /* ...                CALL CMOVE, USING CPLAN DATA */
 L464:
     jcmove = 1;
     jcmove_fmt = fmt_471;
     goto L700;
 /* ...                CALL 2 SURFACE ITERATION AND LOOP */
 L471:
     im = -1;
     if (*kdynfl != knumbr_1.k0) {
     apt238_(&knumbr_1.k31);
     }
     j2surf = 1;
     goto L600;
 /* ...                NORMALS PARALLEL, CALL TEST CHECK SURF */
 /*                                       RETURN TO MAIN IF IN TOL */
 L480:
     jtstck = 1;
     jtstck_fmt = fmt_482;
     goto L1300;
 L482:
     if (jtol <= 0) {
     goto L486;
     } else {
     goto L483;
     }
 L483:
     ishr18_1.jcr = 1;
     goto L130;
 /* ...                NOT WITHIN TOL, TEST WHETHER WITHIN 8*TAU */
 L486:
     if (sv_1.tau[ifxcor_1.is - 1] * 8.f - (d__1 = sv_1.s[ifxcor_1.is - 1],
         abs(d__1)) <= 0.) {
     goto L488;
     } else {
     goto L464;
     }
 /* ...                NOT WITHIN 8*TAU, FALSE TANGENCY EXIT */
 L488:
     ishr18_1.jcr = 2;
     goto L1100;
 /* ----------------------------------------------------------------------- */
 /*     NOTAN - PSEUDO-TANGENCY CALCULATION */
 /*                                       FLAG- PSEUDO TANGENCY DONE */
 L500:
     isv1_1.notan[ifxcor_1.is - 1] = -1;
 /*                                       SAVE CUTTER POSITION FOR */
 /*                                       RESET IF NECESSARY */
     for (i__ = 1; i__ <= 3; ++i__) {
     savete[i__ - 1] = fxcor_1.te[i__ - 1];
     saveta[i__ - 1] = fxcor_1.ta[i__ - 1];
 /* L502: */
     }
 /*                                       CURRENT DISTANCE FROM SURFACES */
     saves = (d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1)) + (d__2 = sv_1.s[
         ifxcor_1.ids - 1], abs(d__2)) + (d__3 = sv_1.s[ifxcor_1.ips - 1],
         abs(d__3));
 /* ...                CALL FIND PART AND DRIVE */
     jfpd = 2;
     jfpd_fmt = fmt_510;
     goto L800;
 /* ...                CALL FIND CHECK */
 L510:
     jfndck = 1;
     jfndck_fmt = fmt_1400;
 /* ...                CALL CPLAN SURF */
     jcplan = 1;
     jcplan_fmt = fmt_520;
     goto L1000;
 /* ...                TEST WHETHER WITHIN 2*TAU OF CPLAN */
 L520:
     if ((d__1 = sv_1.plnd[ifxcor_1.is - 1], abs(d__1)) - sv_1.eps4[
         ifxcor_1.is - 1] <= 0.) {
     goto L540;
     } else {
     goto L530;
     }
 /* ...                                    CALL CMOVE */
 L530:
     jcmove = 2;
     jcmove_fmt = fmt_600;
 /* ...                                    CALL 2 SURF ITERAT */
     j2surf = 2;
     j2surf_fmt = fmt_531;
     goto L700;
 /* ...                CALL FIND CHECK */
 L531:
     jfndck = 2;
     jfndck_fmt = fmt_532;
     goto L1000;
 /* ...                RESTORE IF MOVED AWAY FROM SURFACES */
 L532:
     if ((d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1)) - saves * 2.f <= 0.) {
     goto L510;
     } else {
     goto L535;
     }
 L535:
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.te[i__ - 1] = savete[i__ - 1];
     fxcor_1.ta[i__ - 1] = saveta[i__ - 1];
 /* L537: */
     }
 /*                                       RETURN TO 3 SURF */
     goto L300;
 /* ...                TEST WHETHER CHECK SURF WITHIN TOL */
 L540:
     jtstck = 2;
     jtstck_fmt = fmt_550;
     goto L1300;
 L550:
     if (jtol <= 0) {
     goto L555;
     } else {
     goto L565;
     }
 /* ...                TEST WHETHER CHECK SURF WITHIN 8*TAU */
 /*                                       RETURN TO 3 SURF IF SO */
 L555:
     if (sv_1.tau[ifxcor_1.is - 1] * 8 - (d__1 = sv_1.s[ifxcor_1.is - 1], abs(
         d__1)) <= 0.) {
     goto L560;
     } else {
     goto L535;
     }
 /* ...                SET FALSE TANGENCY FLAG AND EXIT */
 L560:
     ishr18_1.jcr = 2;
     goto L1100;
 /* ...                CALL TEST PART AND DRIVE */
 L565:
     jtstpd = 1;
     jtstpd_fmt = fmt_570;
     goto L900;
 /* ...                RETURN TO 3-SURF IF BOTH WITHIN TOL, */
 /* ...                FALSE TANGENCY IF NOT */
 L570:
     if (jtol <= 0) {
     goto L560;
     } else {
     goto L300;
     }
 /* ----------------------------------------------------------------------- */
 /*     2 SURF ITERATE - ITERATE TOOL INTO PART AND DRIVE SURFACES */
 /* ...                FIND PART AND DRIVE SURFACES */
 L600:
     jfpd = 3;
     jfpd_fmt = fmt_900;
 /* ...                TEST PART AND DRIVE SURFACES */
     jtstpd = 2;
     jtstpd_fmt = fmt_605;
     goto L800;
 /* ...                RETURN IF BOTH WITHIN TOL */
 L605:
     if (jtol <= 0) {
     goto L615;
     } else {
     goto L610;
     }
 /*                                       RETURN */
 L610:
     switch (j2surf) {
     case 0: goto L210;
     case 1: goto L410;
     case 2: goto L531;
     }
 /* ...                CREATE PSEUDO CHECK SURFACE NORMAL TO */
 /* ...                PART AND DRIVE */
 L615:
     cross_(&sv_1.tn[ifxcor_1.ips * 3 - 3], &sv_1.tn[ifxcor_1.ids * 3 - 3], &
         sv_1.plnv[ifxcor_1.is * 3 - 3]);
     vnorm_(&sv_1.plnv[ifxcor_1.is * 3 - 3], &sv_1.plnv[ifxcor_1.is * 3 - 3]);
     sv_1.plnd[ifxcor_1.is - 1] = 0.f;
 /* ...                CALL CMOVE AND LOOP */
     jcmove = 2;
     goto L700;
 /* ----------------------------------------------------------------------- */
 /*     CMOVE - COMPUTE AND APPLY MOVE VECTOR */
 /* ...                IN CASE OF PLANE PART AND DRIVE SURFACES, MODIFY */
 /* ...                DISTANCES TO DIRECT TOOL TOWARD CENTER OF TOLERANCE */
 /* ...                BAND AS ITERATION COUNT INCREASES */
 L700:
     i__2 = ifxcor_1.ids;
     i__1 = ifxcor_1.lsv;
     for (i__ = ifxcor_1.ips; i__1 < 0 ? i__ >= i__2 : i__ <= i__2; i__ +=
         i__1) {
 /*                                       SKIP IF SURF NOT A PLANE */
     if (isv_1.ipl[i__ - 1] != 0) {
         goto L705;
     } else {
         goto L701;
     }
 /*                                       ADAUST DIST TOWARD CENTER */
 L705:
     sv_1.s[i__ - 1] -= (sv_1.tau1[i__ - 1] + sv_1.tau2[i__ - 1]) / 2.f * (
         ptol - .2f) / .8f;
 L701:
     ;
     }
 /* .... SPECIAL TREATMENT FOR 2 SURFACE APPROACH WHEN DIST TO */
 /*     ONE SURFACE IS ZERO */
     if (isv1_1.j51[ifxcor_1.is - 1] == 0) {
     if (sv_1.s[ifxcor_1.ids - 1] != znumbr_1.z0) {
     } else {
         for (iii = 1; iii <= 3; ++iii) {
         dshar4_1.cmove[iii - 1] = znumbr_1.z9em1 * sv_1.tn[iii +
             ifxcor_1.ips * 3 - 4] * sv_1.s[ifxcor_1.ips - 1];
 /* L702: */
         }
         goto L720;
     }
     }
 /* ...                COMPUTE MOVE VECTOR */
     gauss_(&sv_1.tn[ifxcor_1.ips * 3 - 3], &sv_1.s[ifxcor_1.ips - 1], &
         sv_1.tn[ifxcor_1.ids * 3 - 3], &sv_1.s[ifxcor_1.ids - 1], &
         sv_1.plnv[ifxcor_1.is * 3 - 3], &sv_1.plnd[ifxcor_1.is - 1],
         dshar4_1.cmove, &ishr18_1.jpxr);
 /* ....  DETERMINE MAXIMUM DIST TO SURFACES */
 /* Computing MAX */
     d__4 = (d__1 = sv_1.s[ifxcor_1.ips - 1], abs(d__1)), d__5 = (d__2 =
         sv_1.s[ifxcor_1.ids - 1], abs(d__2)), d__4 = max(d__4,d__5), d__5
         = (d__3 = sv_1.plnd[ifxcor_1.is - 1], abs(d__3));
     simax = max(d__4,d__5);
     if (ishr18_1.jpxr != 0) {
 /* .... GAUSS FAILED - COMPUTE CMOVE BY ALTERNATIVE METHODS */
     altcmv_(&ishr18_1.jpxr, sv_1.tn, sv_1.s, &ifxcor_1.ips, &ifxcor_1.ids,
          &sv_1.plnd[ifxcor_1.is - 1], &sv_1.plnv[ifxcor_1.is * 3 - 3],
          &sv_1.eps1[ifxcor_1.is - 1], dshar4_1.cmove, &lret);
     ishr18_1.jpxr = 1;
 /* .... IS TOOL IN TOLERANCE OD CS WHEN PS PARALLEL TO CS */
     if (lret) {
         goto L380;
     }
     }
 /* ...                TEST FOR ITERATION 10, 5, OR 3 OF 3 SURF */
 L720:
     if ((ishr18_1.jcnt1 - 18) * (ishr18_1.jcnt1 - 9) * (ishr18_1.jcnt1 - 3) +
         (ishr18_1.jcnt1 - 22) != 0) {
     goto L735;
     } else {
     goto L725;
     }
 /* ...                IF SO, WIDEN TOLERANCE LIMIT AND HALVE MOVE */
 L725:
     sv_1.eps8[ifxcor_1.ips - 1] *= 1.709976f;
     sv_1.eps8[ifxcor_1.ids - 1] *= 1.709976f;
     sv_1.eps8[ifxcor_1.is - 1] *= 1.709976f;
     ptol *= 1.709976f;
     for (i__ = 1; i__ <= 3; ++i__) {
     dshar4_1.cmove[i__ - 1] *= .5f;
 /* L730: */
     }
 /* .... ENSURE CMOVE IS LESS THAN LARGEST ACTUAL DISTANCE TO SURFACES */
     bcmov = sqrt(dshar4_1.cmove[0] * dshar4_1.cmove[0] + dshar4_1.cmove[1] *
         dshar4_1.cmove[1] + dshar4_1.cmove[2] * dshar4_1.cmove[2]);
     if (bcmov > simax) {
     for (ik = 1; ik <= 3; ++ik) {
         dshar4_1.cmove[ik - 1] = simax / bcmov * dshar4_1.cmove[ik - 1];
 /* L731: */
     }
     }
 /* ...                ADD MOVE TO TOOL END */
 /*                                       FACTOR TO ENLARGE MOVE TO MINIM- */
 /*                                       AL SIZE IF NECESSARY */
 L735:
 /* Computing MAX */
 /* Computing MAX */
     d__3 = abs(dshar4_1.cmove[0]), d__4 = abs(dshar4_1.cmove[1]), d__3 = max(
         d__3,d__4), d__4 = abs(dshar4_1.cmove[2]);
     d__1 = znumbr_1.z1, d__2 = smove / max(d__3,d__4);
     fxcor_1.temp[0] = max(d__1,d__2);
 /*                                       ADD MOVE */
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.te[i__ - 1] += fxcor_1.temp[0] * dshar4_1.cmove[i__ - 1];
 /* L740: */
     }
 /* ...                 STEP COUNTER, AND RETURN */
     if (ishr18_1.jcnt1 <= 0) {
     goto L750;
     } else {
     goto L745;
     }
 L745:
     --ishr18_1.jcnt1;
 /*                                       RETURN */
     switch (jcmove) {
     case 0: goto L300;
     case 1: goto L471;
     case 2: goto L600;
     }
 /* ...                IF COUNTER EXHAUSTED, ISSUE WARNING */
 /*                                       BRANCH TO ERROR */
 L750:
     goto L1600;
 /* ----------------------------------------------------------------------- */
 /*     FIND PART DRIVE - DETERMINE NORMALS AND DISTANCES FOR PART */
 /*                       AND DRIVE SURFACES */
 /*                                       SAVE INDEX */
 L800:
     issto = ifxcor_1.is;
 /*                                       CALL FOR PART SURFACE */
     ifxcor_1.is = ifxcor_1.ips;
     ishr18_1.jminr = 1;
     amind_();
     ifxcor_1.is = issto;
     if (ishr18_1.jmin == 1) {
     goto L1600;
     }
 /*                                       CALL FOR DRIVE SURFACE */
     ifxcor_1.is = ifxcor_1.ids;
     ishr18_1.jminr = 1;
     amind_();
     ifxcor_1.is = issto;
     if (ishr18_1.jmin == 1) {
     goto L1600;
     }
 /*                                       RESTORE INDEX */
 /*                                       RETURN */
     switch (jfpd) {
     case 0: goto L1000;
     case 1: goto L410;
     case 2: goto L510;
     case 3: goto L900;
     case 4: goto L922;
     }
 /* ----------------------------------------------------------------------- */
 /*     TEST PART DRIVE - SET JTOL +1 IF BOTH PART AND DRIVE SURFACE */
 /*                       DISTANCES ARE ACCEPTABLE */
 /* ...                CALL TINKR FOR 5-AXIS CASE */
 L900:
     if (ifxcor_1.mantax - 2 >= 0) {
     goto L910;
     } else {
     goto L925;
     }
 L910:
     if (itink <= 0) {
     goto L925;
     }
     tinkr_();
 /*                                       TEST IF TA MOVED */
     if (ishr18_1.jtr < 0) {
     goto L915;
     } else if (ishr18_1.jtr == 0) {
     goto L921;
     } else {
     goto L925;
     }
 L915:
     --jtrc;
     if (jtrc >= 0) {
     goto L925;
     } else {
     goto L920;
     }
 /*                                       ERROR IF COUNTER EXHAUSTED */
 L920:
     aerr_(&c__25007, "CENTR   ", (ftnlen)8);
 /*                                       IF SO,REESTABLISH */
 /*                                       FIND PART AND DRIVE */
 L921:
     jfpd = 4;
     jfpd_fmt = fmt_922;
     goto L800;
 /*                                       RE-ADJUST AXIS */
 L922:
     if (itink <= 0) {
     goto L925;
     }
     tinkr_();
 /* ...                TEST PART AND DRIVE SURFACES */
 L925:
     i__1 = ifxcor_1.ids;
     i__2 = ifxcor_1.lsv;
     for (i__ = ifxcor_1.ips; i__2 < 0 ? i__ >= i__1 : i__ <= i__1; i__ +=
         i__2) {
 /*                                       TEST WHETHER SURFACE A PLANE */
     if (isv_1.ipl[i__ - 1] <= 0) {
         goto L930;
     } else {
         goto L935;
     }
 /*                                       NON-PLANAR */
 L930:
     if ((d__1 = sv_1.s[i__ - 1], abs(d__1)) - sv_1.eps8[i__ - 1] <= 0.) {
         goto L950;
     } else {
         goto L965;
     }
 /*                                       PLANE, TEST WHICH SIDE */
 L935:
     if ((d__1 = sv_1.s[i__ - 1]) < 0.) {
         goto L940;
     } else if (d__1 == 0) {
         goto L950;
     } else {
         goto L945;
     }
 L940:
     if (sv_1.s[i__ - 1] - ptol * sv_1.tau2[i__ - 1] + 1e-6f >= 0.) {
         goto L950;
     } else {
         goto L965;
     }
 L945:
     if (sv_1.s[i__ - 1] - ptol * sv_1.tau1[i__ - 1] - 1e-6f <= 0.) {
         goto L950;
     } else {
         goto L965;
     }
 L950:
     ;
     }
 /* ...                BOTH WITHIN TOLERANCE */
 /* L960: */
     jtol = 1;
     goto L970;
 /* ...                NOT BOTH WITHIN TOL */
 L965:
     jtol = -1;
 /* ...                RETURN */
 L970:
     switch (jtstpd) {
     case 0: goto L310;
     case 1: goto L570;
     case 2: goto L605;
     }
 /* ----------------------------------------------------------------------- */
 /*     FIND CHECK - DETERMINE NORMAL AND DISTANCE TO CHECK SURFACE */
 /* ...                CALL AMIND FOR CHECK SURFACE */
 /*                                       RETURN IF AMIND ERROR */
 L1000:
     ishr18_1.jminr = 1;
     amind_();
 /*                                       RESET RETURN FLAG */
     ishr18_1.jminr = 0;
 /*                                       BRANCH IF ERROR */
     if (ishr18_1.jmin <= 0) {
     goto L1010;
     } else {
     goto L1600;
     }
 /*                                       RETURN */
 L1010:
     switch (jfndck) {
     case 0: goto L302;
     case 1: goto L1400;
     case 2: goto L532;
     }
 /* ----------------------------------------------------------------------- */
 /*     EXIT - RESET QUANTITIES AND RETURN */
 /* ...                IF 5-AXIS CASE, VERIFY TOOL AXIS SATISFACTORY */
 L1100:
     if (2 - ifxcor_1.mantax <= 0) {
     goto L1102;
     } else {
     goto L1108;
     }
 L1102:
     if (itink == 0) {
     itink = 1;
     goto L105;
     } else if (itink == -1) {
     goto L1108;
     } else {
 /*                                       RESET AXIS IF NECESSARY */
     tinkr_();
     }
 /*                                       TEST WHETHER AXIS MOVED */
     if (ishr18_1.jtr < 0) {
     goto L1103;
     } else if (ishr18_1.jtr == 0) {
     goto L1104;
     } else {
     goto L1108;
     }
 /*                                       TINKR ERROR */
 L1103:
     aerr_(&c__25004, "CENTR   ", (ftnlen)8);
 /*                                       AXIS MOVED, INDEX COUNTER */
 /*                                       AND RESTART */
 L1104:
     if (ishr18_1.jcnt3 >= 0) {
     goto L1106;
     } else {
     goto L1105;
     }
 /*                                       COUNTER EXHAUSTED */
 L1105:
     aerr_(&c__25003, "CENTR   ", (ftnlen)8);
 L1106:
     --ishr18_1.jcnt3;
     goto L100;
 /* ...                RESET   3-SURFACE FLAGS AND TOLERANCE BAND LIMITS */
 L1108:
     if (isv1_1.j51[ifxcor_1.is - 1] <= 0) {
     goto L1120;
     } else {
     goto L1110;
     }
 L1110:
     isv1_1.j50[ifxcor_1.is - 1] = 0;
     isv1_1.j51[ifxcor_1.is - 1] = 0;
     sv_1.eps8[ifxcor_1.ips - 1] = sv_1.eps1[ifxcor_1.ips - 1];
     sv_1.eps8[ifxcor_1.ids - 1] = sv_1.eps1[ifxcor_1.ids - 1];
     sv_1.eps8[ifxcor_1.is - 1] = sv_1.eps1[ifxcor_1.is - 1];
     isv1_1.notan[ifxcor_1.is - 1] = 0;
 /* ...                RETURN TO CALLING PROGRAM */
 L1120:
 /* ... HAS TE CHANGED */
     if (teza[0] != fxcor_1.te[0] || teza[1] != fxcor_1.te[1] || teza[2] !=
         fxcor_1.te[2]) {
     chang_1.jteneu = 1;
     } else {
     chang_1.jteneu = 0;
     }
     return 0;
 /* ----------------------------------------------------------------------- */
 /*     TEST CHECK SURFACE */
 /*                                       BRANCH IF SURF A PLANE */
 L1300:
     if (isv_1.ipl[ifxcor_1.is - 1] <= 0) {
     goto L1310;
     } else {
     goto L1330;
     }
 /*                                       TEST FOR INNER OR OUTER SIDE */
 L1310:
     if ((d__1 = (doublereal) ((isv_1.jtn[ifxcor_1.is - 1] << 1) - 1) *
         sv_1.rc[ifxcor_1.is - 1] * sv_1.s[ifxcor_1.is - 1]) < 0.) {
     goto L1315;
     } else if (d__1 == 0) {
     goto L1350;
     } else {
     goto L1320;
     }
 /*                                       INNER SIDE */
 L1315:
     if ((d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1)) - sv_1.eps8[ifxcor_1.is -
         1] - 5e-6 <= 0.) {
     goto L1350;
     } else {
     goto L1360;
     }
 /*                                       OUTER SIDE */
 L1320:
     if ((d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1)) - (sv_1.tau[ifxcor_1.is -
         1] - sv_1.eps8[ifxcor_1.is - 1] + znumbr_1.z5em6) <= 0.) {
     goto L1350;
     } else {
     goto L1360;
     }
 /*                                       PLANE SURFACE */
 /*                                       TEST INNER OR OUTER */
 L1330:
     if (sv_1.s[ifxcor_1.is - 1] <= 0.) {
     goto L1340;
     } else {
     goto L1335;
     }
 /*                                       INNER */
 L1335:
     if (sv_1.s[ifxcor_1.is - 1] - acc - sv_1.tau1[ifxcor_1.is - 1] <= 0.) {
     goto L1350;
     } else {
     goto L1360;
     }
 /*                                       OUTER */
 L1340:
     if (sv_1.s[ifxcor_1.is - 1] + acc - sv_1.tau2[ifxcor_1.is - 1] >= 0.) {
     goto L1350;
     } else {
     goto L1360;
     }
 /* ...                WITHIN TOLERANCE BAND */
 L1350:
     jtol = 1;
     goto L1370;
 /* ...                NOT WITHIN TOLERANCE BAND */
 L1360:
     jtol = -1;
 /*                                       RETURN */
 L1370:
     switch (jtstck) {
     case 0: goto L320;
     case 1: goto L482;
     case 2: goto L550;
     }
 /* ----------------------------------------------------------------------- */
 /*     CPLAN SURF - OBTAIN PSEUDO CHECK SURFACE DATA FROM CPLAN */
 /*                  ROUTINE */
 L1400:
     cplan_();
     ifxcor_1.it = ifxcor_1.it;
 /* ...                BRANCH IF CPLAN FAILURE */
     if (ishr18_1.jcpr != 0) {
     goto L1420;
     } else {
     goto L1410;
     }
 /* ...                RETURN */
 L1410:
     switch (jcplan) {
     case 0: goto L420;
     case 1: goto L520;
     }
 /* ...                CPLAN ERROR */
 L1420:
     aerr_(&c__25005, "CENTR   ", (ftnlen)8);
 /* ----------------------------------------------------------------------- */
 /*     ERROR -                REDUCE STEPSIZE IF POSSIBLE, AND SET */
 /*                            FLAG FOR RESTART */
 /*                                       BRANCH IF 3 SURFACE CALL */
 L1600:
     if (isv1_1.j51[ifxcor_1.is - 1] <= 0) {
     goto L1610;
     } else {
     goto L1630;
     }
 /*                                       REDUCE STEPSIZE */
 L1610:
     dshar4_1.dp *= .6f;
 /*                                       ERROR IF STEPSIZE .LT. TOLERANCE */
     if (dshar4_1.dp - (d__1 = sv_1.tau[ifxcor_1.is - 1], abs(d__1)) <= 0.) {
     goto L1620;
     } else {
     goto L1630;
     }
 /*                                       ERROR ROUTINE */
 L1620:
     aerr_(&c__25002, "CENTR   ", (ftnlen)8);
 /*                                       SET FLAG FOR RESTART */
 L1630:
     ishr18_1.jcr = -1;
 /*                                       BRANCH TO EXIT */
     goto L1100;
 } /* centr_ */
Variable Documentation
doublereal a
Definition at line 18 of file CENTR.c.
doublereal addcom[25]
Definition at line 126 of file CENTR.c.
struct { ... } addcom_
doublereal alp
Definition at line 28 of file CENTR.c.
doublereal ax4[3]
Definition at line 28 of file CENTR.c.
doublereal b
Definition at line 18 of file CENTR.c.
doublereal c__
Definition at line 18 of file CENTR.c.
integer c__25002 = 25002 static
Definition at line 145 of file CENTR.c.
Referenced by centr_().
integer c__25003 = 25003 static
Definition at line 143 of file CENTR.c.
Referenced by centr_().
integer c__25004 = 25004 static
Definition at line 142 of file CENTR.c.
Referenced by centr_().
integer c__25005 = 25005 static
Definition at line 144 of file CENTR.c.
Referenced by centr_().
integer c__25007 = 25007 static
Definition at line 141 of file CENTR.c.
Referenced by centr_().
integer c__25008 = 25008 static
Definition at line 140 of file CENTR.c.
Referenced by centr_().
integer c__25009 = 25009 static
Definition at line 139 of file CENTR.c.
Referenced by centr_().
doublereal cagl
Definition at line 28 of file CENTR.c.
doublereal cc[15]
Definition at line 50 of file CENTR.c.
doublereal cendis
Definition at line 18 of file CENTR.c.
struct { ... } chang_
struct { ... } charct_
doublereal cmove[3]
Definition at line 18 of file CENTR.c.
doublereal com1
Definition at line 18 of file CENTR.c.
doublereal com4
Definition at line 18 of file CENTR.c.
doublereal corrad[8]
Definition at line 43 of file CENTR.c.
doublereal cos1[5]
Definition at line 67 of file CENTR.c.
doublereal cplfl[5]
Definition at line 67 of file CENTR.c.
doublereal cptst[5]
Definition at line 67 of file CENTR.c.
doublereal csd[5]
Definition at line 67 of file CENTR.c.
doublereal cutdat[7]
Definition at line 28 of file CENTR.c.
doublereal d1
Definition at line 18 of file CENTR.c.
doublereal d2a
Definition at line 18 of file CENTR.c.
doublereal degrad
Definition at line 76 of file CENTR.c.
doublereal dir[3]
Definition at line 18 of file CENTR.c.
doublereal dp
Definition at line 18 of file CENTR.c.
doublereal dp1
Definition at line 18 of file CENTR.c.
doublereal dpcnt
Definition at line 18 of file CENTR.c.
doublereal dpe
Definition at line 18 of file CENTR.c.
doublereal dpi
Definition at line 18 of file CENTR.c.
doublereal dpl
Definition at line 18 of file CENTR.c.
doublereal dplan[15]
Definition at line 67 of file CENTR.c.
doublereal dpmax
Definition at line 28 of file CENTR.c.
doublereal dpmx1[5]
Definition at line 67 of file CENTR.c.
struct { ... } dshar4_
doublereal eps1[5]
Definition at line 50 of file CENTR.c.
doublereal eps2[5]
Definition at line 50 of file CENTR.c.
doublereal eps3[5]
Definition at line 50 of file CENTR.c.
doublereal eps4[5]
Definition at line 50 of file CENTR.c.
doublereal eps6[5]
Definition at line 50 of file CENTR.c.
doublereal eps8[5]
Definition at line 50 of file CENTR.c.
doublereal flipck
Definition at line 18 of file CENTR.c.
doublereal fwd[3]
Definition at line 18 of file CENTR.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file CENTR.c.
doublereal hi
Definition at line 28 of file CENTR.c.
integer i3dflg
Definition at line 100 of file CENTR.c.
integer iaerr
Definition at line 100 of file CENTR.c.
integer iafl[5]
Definition at line 84 of file CENTR.c.
integer iamdct
Definition at line 110 of file CENTR.c.
integer iautps
Definition at line 100 of file CENTR.c.
integer ibegin
Definition at line 100 of file CENTR.c.
integer ic
Definition at line 100 of file CENTR.c.
integer icanon[5]
Definition at line 84 of file CENTR.c.
integer icheck
Definition at line 100 of file CENTR.c.
integer icl
Definition at line 100 of file CENTR.c.
integer ics
Definition at line 100 of file CENTR.c.
integer icscnt
Definition at line 100 of file CENTR.c.
integer ictdef
Definition at line 100 of file CENTR.c.
integer icut
Definition at line 100 of file CENTR.c.
integer ids
Definition at line 100 of file CENTR.c.
integer ier
Definition at line 100 of file CENTR.c.
integer ifar[5]
Definition at line 93 of file CENTR.c.
integer ifl4[5]
Definition at line 93 of file CENTR.c.
struct { ... } ifxcor_
integer igo
Definition at line 100 of file CENTR.c.
integer igoto
Definition at line 100 of file CENTR.c.
integer igoug
Definition at line 100 of file CENTR.c.
integer igs
Definition at line 100 of file CENTR.c.
integer index[5]
Definition at line 84 of file CENTR.c.
integer indir__[5]
Definition at line 84 of file CENTR.c.
integer inops
Definition at line 100 of file CENTR.c.
integer iop[5]
Definition at line 84 of file CENTR.c.
integer iopset[5]
Definition at line 84 of file CENTR.c.
integer ipdpl
Definition at line 110 of file CENTR.c.
integer ipl[5]
Definition at line 84 of file CENTR.c.
integer ips
Definition at line 100 of file CENTR.c.
integer ipsdef
Definition at line 100 of file CENTR.c.
integer ipt
Definition at line 110 of file CENTR.c.
integer ipt1
Definition at line 100 of file CENTR.c.
integer is
Definition at line 100 of file CENTR.c.
integer iseg
Definition at line 100 of file CENTR.c.
integer iseqno
Definition at line 100 of file CENTR.c.
integer isfidn[5]
Definition at line 84 of file CENTR.c.
integer isftyp[5]
Definition at line 84 of file CENTR.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 84 of file CENTR.c.
integer isrch
Definition at line 100 of file CENTR.c.
integer istrup
Definition at line 100 of file CENTR.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 84 of file CENTR.c.
integer it
Definition at line 100 of file CENTR.c.
integer itlon[5]
Definition at line 84 of file CENTR.c.
integer itseg[5]
Definition at line 84 of file CENTR.c.
integer itsegk[5]
Definition at line 84 of file CENTR.c.
integer iunfl[5]
Definition at line 84 of file CENTR.c.
integer iws
Definition at line 110 of file CENTR.c.
integer j10
Definition at line 110 of file CENTR.c.
integer j12
Definition at line 110 of file CENTR.c.
integer j13
Definition at line 110 of file CENTR.c.
integer j20[5]
Definition at line 93 of file CENTR.c.
integer j21[5]
Definition at line 93 of file CENTR.c.
integer j22[5]
Definition at line 93 of file CENTR.c.
integer j23[5]
Definition at line 93 of file CENTR.c.
integer j50[5]
Definition at line 93 of file CENTR.c.
integer j51[5]
Definition at line 93 of file CENTR.c.
integer j54
Definition at line 110 of file CENTR.c.
integer jbr
Definition at line 100 of file CENTR.c.
integer jckr
Definition at line 110 of file CENTR.c.
integer jcnt1
Definition at line 110 of file CENTR.c.
integer jcnt2
Definition at line 110 of file CENTR.c.
integer jcnt3
Definition at line 110 of file CENTR.c.
integer jcpr
Definition at line 110 of file CENTR.c.
integer jcr
Definition at line 110 of file CENTR.c.
integer jdr
Definition at line 110 of file CENTR.c.
integer jent[5]
Definition at line 84 of file CENTR.c.
integer jfind
Definition at line 110 of file CENTR.c.
integer jgr
Definition at line 110 of file CENTR.c.
integer jiops[5]
Definition at line 84 of file CENTR.c.
integer jmin
Definition at line 110 of file CENTR.c.
integer jminr
Definition at line 110 of file CENTR.c.
integer jph[5]
Definition at line 93 of file CENTR.c.
integer jpr
Definition at line 110 of file CENTR.c.
integer jpxr
Definition at line 110 of file CENTR.c.
integer jsw
Definition at line 100 of file CENTR.c.
integer jteneu
Definition at line 132 of file CENTR.c.
integer jtkf
Definition at line 110 of file CENTR.c.
integer jtlflg[5]
Definition at line 84 of file CENTR.c.
integer jtn[5]
Definition at line 84 of file CENTR.c.
integer jtr
Definition at line 110 of file CENTR.c.
integer ju1[5]
Definition at line 84 of file CENTR.c.
integer k0
Definition at line 118 of file CENTR.c.
integer k1
Definition at line 118 of file CENTR.c.
integer k10
Definition at line 118 of file CENTR.c.
integer k1013
Definition at line 118 of file CENTR.c.
integer k12
Definition at line 118 of file CENTR.c.
integer k13
Definition at line 118 of file CENTR.c.
integer k15
Definition at line 118 of file CENTR.c.
integer k16
Definition at line 118 of file CENTR.c.
integer k18
Definition at line 118 of file CENTR.c.
integer k19
Definition at line 118 of file CENTR.c.
integer k1e4
Definition at line 118 of file CENTR.c.
integer k1e6
Definition at line 118 of file CENTR.c.
integer k2
Definition at line 118 of file CENTR.c.
integer k23
Definition at line 118 of file CENTR.c.
integer k24
Definition at line 118 of file CENTR.c.
integer k25
Definition at line 118 of file CENTR.c.
integer k26
Definition at line 118 of file CENTR.c.
integer k27
Definition at line 118 of file CENTR.c.
integer k29
Definition at line 118 of file CENTR.c.
integer k3
Definition at line 118 of file CENTR.c.
integer k30
Definition at line 118 of file CENTR.c.
integer k31
Definition at line 118 of file CENTR.c.
integer k32
Definition at line 118 of file CENTR.c.
integer k33
Definition at line 118 of file CENTR.c.
integer k34
Definition at line 118 of file CENTR.c.
integer k4
Definition at line 118 of file CENTR.c.
integer k44
Definition at line 118 of file CENTR.c.
integer k45
Definition at line 118 of file CENTR.c.
integer k46
Definition at line 118 of file CENTR.c.
integer k47
Definition at line 118 of file CENTR.c.
integer k48
Definition at line 118 of file CENTR.c.
integer k5
Definition at line 118 of file CENTR.c.
integer k50
Definition at line 118 of file CENTR.c.
integer k51
Definition at line 118 of file CENTR.c.
integer k52
Definition at line 118 of file CENTR.c.
integer k6
Definition at line 118 of file CENTR.c.
integer k7
Definition at line 118 of file CENTR.c.
integer k8
Definition at line 118 of file CENTR.c.
integer k9
Definition at line 118 of file CENTR.c.
integer km1
Definition at line 118 of file CENTR.c.
struct { ... } knumbr_
integer limfl[5]
Definition at line 84 of file CENTR.c.
integer lsv
Definition at line 100 of file CENTR.c.
integer lsv1
Definition at line 100 of file CENTR.c.
integer mantax
Definition at line 100 of file CENTR.c.
integer mdic
Definition at line 110 of file CENTR.c.
char modfer[6]
Definition at line 37 of file CENTR.c.
integer motmod
Definition at line 100 of file CENTR.c.
integer msav
Definition at line 100 of file CENTR.c.
integer mulout
Definition at line 100 of file CENTR.c.
integer nmbseg
Definition at line 100 of file CENTR.c.
integer nmpnts
Definition at line 100 of file CENTR.c.
integer notan[5]
Definition at line 93 of file CENTR.c.
integer nrec
Definition at line 100 of file CENTR.c.
integer numax
Definition at line 100 of file CENTR.c.
integer numcnt
Definition at line 100 of file CENTR.c.
integer nump
Definition at line 100 of file CENTR.c.
integer numpt1
Definition at line 100 of file CENTR.c.
integer numsfs
Definition at line 100 of file CENTR.c.
integer numsur
Definition at line 100 of file CENTR.c.
integer nw
Definition at line 100 of file CENTR.c.
integer nwds
Definition at line 100 of file CENTR.c.
doublereal ogle[3]
Definition at line 18 of file CENTR.c.
doublereal p1[3]
Definition at line 18 of file CENTR.c.
doublereal p2[3]
Definition at line 18 of file CENTR.c.
doublereal param[6]
Definition at line 18 of file CENTR.c.
doublereal past[5]
Definition at line 50 of file CENTR.c.
doublereal pi
Definition at line 76 of file CENTR.c.
doublereal plncs[5]
Definition at line 67 of file CENTR.c.
doublereal plnd[5]
Definition at line 50 of file CENTR.c.
doublereal plnd1[5]
Definition at line 67 of file CENTR.c.
doublereal plnv[15]
Definition at line 50 of file CENTR.c.
doublereal pltst[5]
Definition at line 67 of file CENTR.c.
doublereal pmove[3]
Definition at line 28 of file CENTR.c.
doublereal r__[6]
Definition at line 18 of file CENTR.c.
doublereal ra
Definition at line 28 of file CENTR.c.
doublereal rc[5]
Definition at line 50 of file CENTR.c.
doublereal rc1
Definition at line 28 of file CENTR.c.
doublereal rdrn
Definition at line 18 of file CENTR.c.
doublereal refpnt[3]
Definition at line 18 of file CENTR.c.
doublereal ri[8]
Definition at line 43 of file CENTR.c.
doublereal s[5]
Definition at line 50 of file CENTR.c.
doublereal sagl
Definition at line 28 of file CENTR.c.
doublereal save[5]
Definition at line 50 of file CENTR.c.
doublereal savpar[4]
Definition at line 18 of file CENTR.c.
doublereal seg[9]
Definition at line 18 of file CENTR.c.
doublereal sfvct[15]
Definition at line 50 of file CENTR.c.
doublereal sk[15]
Definition at line 50 of file CENTR.c.
doublereal slope
Definition at line 18 of file CENTR.c.
doublereal slx[15]
Definition at line 50 of file CENTR.c.
doublereal sn[15]
Definition at line 50 of file CENTR.c.
doublereal snk[15]
Definition at line 50 of file CENTR.c.
doublereal snl[15]
Definition at line 50 of file CENTR.c.
doublereal sp[15]
Definition at line 50 of file CENTR.c.
doublereal spk[15]
Definition at line 50 of file CENTR.c.
doublereal spl[15]
Definition at line 50 of file CENTR.c.
doublereal sqroot
Definition at line 18 of file CENTR.c.
doublereal stck[5]
Definition at line 67 of file CENTR.c.
doublereal stck1[5]
Definition at line 67 of file CENTR.c.
doublereal stck2[5]
Definition at line 67 of file CENTR.c.
doublereal stckn[5]
Definition at line 67 of file CENTR.c.
doublereal strtno
Definition at line 28 of file CENTR.c.
doublereal surd
Definition at line 28 of file CENTR.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 28 of file CENTR.c.
doublereal tak[3]
Definition at line 28 of file CENTR.c.
doublereal tal[3]
Definition at line 28 of file CENTR.c.
doublereal tangl
Definition at line 18 of file CENTR.c.
doublereal tanhi[8]
Definition at line 43 of file CENTR.c.
doublereal tanlo[8]
Definition at line 43 of file CENTR.c.
doublereal tau[5]
Definition at line 50 of file CENTR.c.
doublereal tau1[5]
Definition at line 50 of file CENTR.c.
doublereal tau2[5]
Definition at line 50 of file CENTR.c.
doublereal tcont[9]
Definition at line 43 of file CENTR.c.
doublereal te[3]
Definition at line 28 of file CENTR.c.
doublereal tee[15]
Definition at line 67 of file CENTR.c.
doublereal tek[3]
Definition at line 28 of file CENTR.c.
doublereal tel[3]
Definition at line 28 of file CENTR.c.
doublereal tem[10]
Definition at line 28 of file CENTR.c.
doublereal temp[24]
Definition at line 28 of file CENTR.c.
doublereal tes[3]
Definition at line 18 of file CENTR.c.
doublereal tew[3]
Definition at line 18 of file CENTR.c.
doublereal th[5]
Definition at line 50 of file CENTR.c.
doublereal ti[3]
Definition at line 28 of file CENTR.c.
doublereal tik[3]
Definition at line 28 of file CENTR.c.
doublereal til[3]
Definition at line 28 of file CENTR.c.
doublereal tlhit
Definition at line 28 of file CENTR.c.
doublereal tlhite[8]
Definition at line 43 of file CENTR.c.
doublereal tlinc[9]
Definition at line 43 of file CENTR.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file CENTR.c.
doublereal tn[15]
Definition at line 50 of file CENTR.c.
doublereal tnl[15]
Definition at line 67 of file CENTR.c.
doublereal toolht[15]
Definition at line 50 of file CENTR.c.
doublereal toolwd[5]
Definition at line 50 of file CENTR.c.
doublereal tp[15]
Definition at line 50 of file CENTR.c.
doublereal tpk[15]
Definition at line 50 of file CENTR.c.
doublereal u1[15]
Definition at line 50 of file CENTR.c.
doublereal u1k[15]
Definition at line 50 of file CENTR.c.
doublereal u2[3]
Definition at line 18 of file CENTR.c.
doublereal umax[8]
Definition at line 43 of file CENTR.c.
doublereal unn
Definition at line 18 of file CENTR.c.
doublereal upp
Definition at line 18 of file CENTR.c.
doublereal uvec[3]
Definition at line 18 of file CENTR.c.
doublereal v[3]
Definition at line 18 of file CENTR.c.
doublereal varble[5]
Definition at line 50 of file CENTR.c.
doublereal vint
Definition at line 18 of file CENTR.c.
doublereal vl
Definition at line 18 of file CENTR.c.
doublereal vndir[15]
Definition at line 50 of file CENTR.c.
doublereal vnn
Definition at line 18 of file CENTR.c.
doublereal vpp
Definition at line 18 of file CENTR.c.
doublereal vt[15]
Definition at line 50 of file CENTR.c.
doublereal vtem
Definition at line 28 of file CENTR.c.
doublereal z0
Definition at line 76 of file CENTR.c.
doublereal z1
Definition at line 76 of file CENTR.c.
doublereal z10
Definition at line 76 of file CENTR.c.
doublereal z11em1
Definition at line 76 of file CENTR.c.
doublereal z12em1
Definition at line 76 of file CENTR.c.
doublereal z1e38
Definition at line 76 of file CENTR.c.
doublereal z1e6
Definition at line 76 of file CENTR.c.
doublereal z1em1
Definition at line 76 of file CENTR.c.
doublereal z1em2
Definition at line 76 of file CENTR.c.
doublereal z1em3
Definition at line 76 of file CENTR.c.
doublereal z1em5
Definition at line 76 of file CENTR.c.
doublereal z1em6
Definition at line 76 of file CENTR.c.
doublereal z1em7
Definition at line 76 of file CENTR.c.
doublereal z1em9
Definition at line 76 of file CENTR.c.
doublereal z2
Definition at line 76 of file CENTR.c.
doublereal z3
Definition at line 76 of file CENTR.c.
doublereal z5
Definition at line 76 of file CENTR.c.
doublereal z5em1
Definition at line 76 of file CENTR.c.
doublereal z5em6
Definition at line 76 of file CENTR.c.
doublereal z6em1
Definition at line 76 of file CENTR.c.
doublereal z90
Definition at line 76 of file CENTR.c.
doublereal z9em1
Definition at line 76 of file CENTR.c.
doublereal z__[5]
Definition at line 50 of file CENTR.c.
doublereal zl
Definition at line 18 of file CENTR.c.
doublereal zl1
Definition at line 18 of file CENTR.c.
doublereal zlnorm[3]
Definition at line 18 of file CENTR.c.
doublereal zlpnt[3]
Definition at line 18 of file CENTR.c.
doublereal zm1
Definition at line 76 of file CENTR.c.
struct { ... } znumbr_