My Project: CFORM.c File Reference
CFORM.c File Reference
#include "f2c.h"
Functions
int cform_ (char *string, char *buffer, integer *posn, integer *length, ftnlen string_len, ftnlen buffer_len)
Function Documentation
int cform_ (char * string, char * buffer, integer * posn, integer * length, ftnlen string_len, ftnlen buffer_len)
Definition at line 47 of file CFORM.c.
Referenced by abuftp_0_(), aerr2_(), aerr_(), alarm_(), apt024_(), apt089_(), apt104_(), apt107_(), apt301_(), apt302_(), apt309_(), apt330_(), apt331_(), apt335_(), apt336_(), aread_(), atapop_0_(), ataprd_(), atapwt_(), avmsg_(), avoid_(), awrite_(), bad_(), cardpn_(), chread_(), chwrit_(), cilout_(), cleror_(), conbcd_(), crblen_(), curflo_(), errlod_(), error_(), errout_(), eval_(), filopn_(), floseg_(), fread_(), gol_(), gop_(), init_(), intmsg_(), intout_(), intrp_(), ldard_(), lib_(), linkf_(), mesh_(), mixal_(), page_(), parnom_0_(), print_(), punch_(), puncha_0_(), punchc_0_(), read_(), resred_(), scpict_(), sctra_(), set_(), sprvis_0_(), srfcom_(), sspath_(), sspict_(), sstra_(), tapepn_(), tapop_(), tecalc_(), teval_(), tulpos_(), and xcanon_().
 {
     /* Builtin functions */
     integer i_len(char *, ftnlen);
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
 /* .....IF LENGTH IS ZERO ON INPUT RETURN ACTUAL LENGTH OF STRING */
     if (*length == 0) {
     *length = i_len(string, string_len);
     }
 /* .....INSERT CHARACTER STRING IN PRINT BUFFER */
     s_copy(buffer + (*posn - 1), string, *posn + *length - 1 - (*posn - 1), (*
         length));
     return 0;
 } /* cform_ */