My Project: CHECK.c File Reference
CHECK.c File Reference
#include "f2c.h"
Macros
#define dshar4_1 dshar4_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define chekfl_1 chekfl_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int check_ (void)
Variables
struct {
doublereal a
doublereal b
doublereal c__
doublereal cendis
doublereal cmove [3]
doublereal com1
doublereal com4
doublereal dir [3]
doublereal dp
doublereal dpe
doublereal dpcnt
doublereal dpi
doublereal dpl
doublereal dp1
doublereal d1
doublereal d2a
doublereal flipck
doublereal fwd [3]
doublereal ogle [3]
doublereal p1 [3]
doublereal p2 [3]
doublereal rdrn
doublereal refpnt [3]
doublereal tangl
doublereal tes [3]
doublereal tew [3]
doublereal uvec [3]
doublereal u2 [3]
doublereal v [3]
doublereal vl
doublereal zl
doublereal zlnorm [3]
doublereal zlpnt [3]
doublereal zl1
doublereal param [6]
doublereal r__ [6]
doublereal savpar [4]
doublereal seg [9]
doublereal slope
doublereal sqroot
doublereal unn
doublereal upp
doublereal vint
doublereal vnn
doublereal vpp
} dshar4_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
integer ichekf
} chekfl_
static integer c_b10 = -24201
static integer c_b61 = -24202
Macro Definition Documentation
#define charct_1 charct_
Definition at line 40 of file CHECK.c.
#define chekfl_1 chekfl_
Definition at line 129 of file CHECK.c.
Referenced by check_().
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dshar4_1 dshar4_
Definition at line 25 of file CHECK.c.
Referenced by check_().
#define fxcor_1 fxcor_
Definition at line 34 of file CHECK.c.
Referenced by check_().
#define ifxcor_1 ifxcor_
Definition at line 107 of file CHECK.c.
Referenced by check_().
#define ishr18_1 ishr18_
Definition at line 115 of file CHECK.c.
Referenced by check_().
#define isv1_1 isv1_
Definition at line 97 of file CHECK.c.
Referenced by check_().
#define isv_1 isv_
Definition at line 90 of file CHECK.c.
Referenced by check_().
#define knumbr_1 knumbr_
Definition at line 123 of file CHECK.c.
Referenced by check_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sv1_1 sv1_
Definition at line 73 of file CHECK.c.
Referenced by check_().
#define sv_1 sv_
Definition at line 64 of file CHECK.c.
Referenced by check_().
#define tlldat_1 tlldat_
Definition at line 47 of file CHECK.c.
#define znumbr_1 znumbr_
Definition at line 81 of file CHECK.c.
Referenced by check_().
Function Documentation
int check_ (void)
Definition at line 140 of file CHECK.c.
References aerr_(), amind_(), c_b10, c_b61, chekfl_1, cplan_(), ddlim_(), ddst_(), dotf_(), dshar4_1, fxcor_1, i__, ifxcor_1, ishr18_1, isv1_1, isv_1, k, knumbr_1, sv1_1, sv_1, vnorm_(), and znumbr_1.
Referenced by arlm3_(), go2_(), and plane_().
 {
     /* System generated locals */
     integer i__1;
     doublereal d__1;
     /* Builtin functions */
     double d_sign(doublereal *, doublereal *);
     /* Local variables */
     static integer i__, k, jwr;
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen), dotf_(
         doublereal *, doublereal *, doublereal *);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static integer itry;
     extern /* Subroutine */ int ddst_(void), amind_(void), ddlim_(void),
         cplan_(void);
     static doublereal tiold[3];
     static integer itang;
     static doublereal dtisn;
     extern /* Subroutine */ int vnorm_(doublereal *, doublereal *);
     static doublereal tnhelp[3];
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ---- FLAG INTRODUCED BY VW - USED TO DETERMINE 'CORRECT' SIDE OF CUTTER */
     if (isv_1.isftyp[ifxcor_1.is - 1] >= knumbr_1.k4) {
     goto L401;
     }
     itang = 0;
     fxcor_1.temp[7] = znumbr_1.z10 * fxcor_1.dpmax;
     if (isv_1.jent[ifxcor_1.is - 1] != knumbr_1.k1) {
     dotf_(&dtisn, fxcor_1.ti, &sv_1.sn[ifxcor_1.is * 3 - 3]);
     if (abs(dtisn) < .05) {
         itang = 1;
         isv1_1.j21[ifxcor_1.is - 1] = knumbr_1.k1;
         goto L401;
     }
     }
     sv_1.tn[ifxcor_1.is * 3 - 3] = sv_1.past[ifxcor_1.is - 1] * fxcor_1.ti[0];
     sv_1.tn[ifxcor_1.is * 3 - 2] = sv_1.past[ifxcor_1.is - 1] * fxcor_1.ti[1];
     sv_1.tn[ifxcor_1.is * 3 - 1] = sv_1.past[ifxcor_1.is - 1] * fxcor_1.ti[2];
 L401:
     if ((i__1 = isv1_1.j20[ifxcor_1.is - 1] - knumbr_1.k1) < 0) {
     goto L1;
     } else if (i__1 == 0) {
     goto L8;
     } else {
     goto L3;
     }
 L1:
     jwr = 0;
     sv1_1.stck[ifxcor_1.is - 1] = znumbr_1.z1e6;
     sv1_1.csd[ifxcor_1.is - 1] = znumbr_1.z0;
     isv1_1.j20[ifxcor_1.is - 1] = knumbr_1.k1;
     isv1_1.j21[ifxcor_1.is - 1] = knumbr_1.k1;
     isv1_1.j22[ifxcor_1.is - 1] = 0;
     isv_1.jent[ifxcor_1.is - 1] = knumbr_1.k1;
 /* L2: */
     isv_1.iopset[ifxcor_1.is - 1] = 0;
     isv_1.jtn[ifxcor_1.is - 1] = knumbr_1.k1;
     isv_1.ju1[ifxcor_1.is - 1] = knumbr_1.k1;
     isv_1.jiops[ifxcor_1.is - 1] = 0;
     goto L9;
 L3:
     if (fxcor_1.tik[0] * (sv1_1.tee[ifxcor_1.is * 3 - 3] - fxcor_1.tek[0]) +
         fxcor_1.tik[1] * (sv1_1.tee[ifxcor_1.is * 3 - 2] - fxcor_1.tek[1])
          + fxcor_1.tik[2] * (sv1_1.tee[ifxcor_1.is * 3 - 1] - fxcor_1.tek[
         2]) - sv_1.eps1[ifxcor_1.is - 1] <= 0.) {
     goto L4;
     } else {
     goto L66;
     }
 L4:
     aerr_(&c_b10, "CHECK   ", (ftnlen)8);
     sv_1.s[ifxcor_1.is - 1] = znumbr_1.z3 * dshar4_1.dp;
     sv1_1.csd[ifxcor_1.is - 1] = znumbr_1.z0;
     goto L11;
 L66:
     isv1_1.j21[ifxcor_1.is - 1] = 0;
     dshar4_1.cmove[0] = sv1_1.tee[ifxcor_1.is * 3 - 3] - fxcor_1.tek[0];
     fxcor_1.temp[0] = fxcor_1.te[0] - fxcor_1.tek[0];
     dshar4_1.cmove[1] = sv1_1.tee[ifxcor_1.is * 3 - 2] - fxcor_1.tek[1];
     fxcor_1.temp[1] = fxcor_1.te[1] - fxcor_1.tek[1];
     dshar4_1.cmove[2] = sv1_1.tee[ifxcor_1.is * 3 - 1] - fxcor_1.tek[2];
     fxcor_1.temp[2] = fxcor_1.te[2] - fxcor_1.tek[2];
     vnorm_(dshar4_1.cmove, fxcor_1.tem);
     sv1_1.csd[ifxcor_1.is - 1] = fxcor_1.vtem;
     vnorm_(fxcor_1.temp, fxcor_1.temp);
     if (abs(dshar4_1.zl) < znumbr_1.z1em9) {
     dshar4_1.zl = znumbr_1.z1em9;
     }
     sv1_1.csd[ifxcor_1.is - 1] = (sv1_1.csd[ifxcor_1.is - 1] - fxcor_1.vtem) *
          (dshar4_1.dpi / dshar4_1.zl) * znumbr_1.z11em1;
     if (sv1_1.csd[ifxcor_1.is - 1] - sv_1.eps1[ifxcor_1.is - 1] <= 0.) {
     goto L7;
     } else {
     goto L16;
     }
 L7:
     fxcor_1.te[0] = sv1_1.tee[ifxcor_1.is * 3 - 3];
     fxcor_1.te[1] = sv1_1.tee[ifxcor_1.is * 3 - 2];
     fxcor_1.te[2] = sv1_1.tee[ifxcor_1.is * 3 - 1];
     goto L18;
 L8:
     if (isv_1.isftyp[ifxcor_1.is - 1] - 4 >= 0) {
     goto L84;
     } else {
     goto L85;
     }
 L84:
     if (isv1_1.jph[ifxcor_1.is - 1] != 0) {
     goto L11;
     } else {
     goto L9;
     }
 L85:
     sv_1.s[ifxcor_1.is - 1] -= dshar4_1.dp;
     if (sv_1.s[ifxcor_1.is - 1] < znumbr_1.z5 || sv_1.s[ifxcor_1.is - 1] <
         znumbr_1.z5 * dshar4_1.dp) {
     goto L9;
     }
 /* L86: */
     if (fxcor_1.ti[0] * tiold[0] + fxcor_1.ti[1] * tiold[1] + fxcor_1.ti[2] *
         tiold[2] - .9f >= 0.) {
     goto L11;
     } else {
     goto L9;
     }
 L9:
     itry = 0;
     chekfl_1.ichekf = 1;
 L901:
     for (i__ = 1; i__ <= 3; ++i__) {
     tnhelp[i__ - 1] = sv_1.tn[i__ + ifxcor_1.is * 3 - 4];
 /* L98: */
     }
     ++itry;
     ishr18_1.jminr = knumbr_1.k1;
 L99:
     amind_();
     chekfl_1.ichekf = 0;
     ishr18_1.jminr = knumbr_1.k0;
     for (i__ = 1; i__ <= 3; ++i__) {
     tiold[i__ - 1] = fxcor_1.ti[i__ - 1];
 /* L87: */
     }
     if (ifxcor_1.iaerr != 0) {
     goto L17;
     } else {
     goto L91;
     }
 L91:
     if (ishr18_1.jmin != 0) {
     goto L10;
     } else {
     goto L19;
     }
 L10:
     if (itry == 1) {
     goto L901;
     }
     sv_1.s[ifxcor_1.is - 1] = znumbr_1.z0;
 L11:
     isv1_1.j21[ifxcor_1.is - 1] = 0;
 L12:
     if (sv1_1.csd[ifxcor_1.is - 1] - sv_1.eps1[ifxcor_1.is - 1] >= 0.) {
     goto L15;
     } else {
     goto L13;
     }
 L13:
     if (ifxcor_1.istrup <= 0) {
     goto L14;
     } else {
     goto L16;
     }
 L14:
     sv1_1.csd[ifxcor_1.is - 1] = znumbr_1.z2 * sv1_1.dpmx1[ifxcor_1.is - 1];
 L15:
     if (sv1_1.stck[ifxcor_1.is - 1] <= znumbr_1.z0) {
     goto L18;
     }
     if (itang == knumbr_1.k1 && fxcor_1.temp[7] < dshar4_1.dp && sv1_1.stck[
         ifxcor_1.is - 1] < znumbr_1.z2 * sv_1.tau[ifxcor_1.is - 1]) {
     goto L18;
     }
 L16:
     ishr18_1.jckr = 0;
 L17:
     isv1_1.jph[ifxcor_1.is - 1] = knumbr_1.k0;
     return 0;
 L18:
     isv1_1.j50[ifxcor_1.is - 1] = knumbr_1.k1;
     isv1_1.j51[ifxcor_1.is - 1] = knumbr_1.k1;
     sv1_1.plnd1[ifxcor_1.is - 1] = znumbr_1.z0;
     isv1_1.notan[ifxcor_1.is - 1] = 0;
     ishr18_1.jckr = knumbr_1.k1;
     goto L17;
 L19:
     if (isv_1.isftyp[ifxcor_1.is - 1] - knumbr_1.k4 >= 0) {
     goto L22;
     } else {
     goto L190;
     }
 L190:
     if (isv1_1.j23[ifxcor_1.is - 1] != 0) {
     goto L20;
     } else {
     goto L21;
     }
 L20:
     if ((d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1)) < znumbr_1.z1em9) {
     goto L2001;
     }
     d__1 = sv_1.z__[ifxcor_1.is - 1] * sv_1.s[ifxcor_1.is - 1];
     sv1_1.stck1[ifxcor_1.is - 1] = d_sign(&znumbr_1.z1, &d__1);
     isv1_1.j23[ifxcor_1.is - 1] = 0;
     goto L22;
 L2001:
     isv1_1.j20[ifxcor_1.is - 1] = 0;
     goto L16;
 L21:
     sv1_1.stck[ifxcor_1.is - 1] = sv1_1.stck1[ifxcor_1.is - 1] * sv_1.z__[
         ifxcor_1.is - 1] * sv_1.s[ifxcor_1.is - 1];
 L22:
     sv1_1.cos1[ifxcor_1.is - 1] = sv_1.tn[ifxcor_1.is * 3 - 3] * fxcor_1.ti[0]
          + sv_1.tn[ifxcor_1.is * 3 - 2] * fxcor_1.ti[1] + sv_1.tn[
         ifxcor_1.is * 3 - 1] * fxcor_1.ti[2];
     if ((i__1 = isv_1.isftyp[ifxcor_1.is - 1] - knumbr_1.k2) < 0) {
     goto L23;
     } else if (i__1 == 0) {
     goto L30;
     } else {
     goto L39;
     }
 L23:
     if (sv1_1.cos1[ifxcor_1.is - 1] >= 0.) {
     goto L25;
     } else {
     goto L24;
     }
 L24:
     sv_1.tn[ifxcor_1.is * 3 - 3] = -sv_1.tn[ifxcor_1.is * 3 - 3];
     sv_1.tn[ifxcor_1.is * 3 - 2] = -sv_1.tn[ifxcor_1.is * 3 - 2];
     sv_1.tn[ifxcor_1.is * 3 - 1] = -sv_1.tn[ifxcor_1.is * 3 - 1];
     sv_1.rc[ifxcor_1.is - 1] = -sv_1.rc[ifxcor_1.is - 1];
     isv1_1.j23[ifxcor_1.is - 1] = knumbr_1.k1;
     goto L99;
 L25:
     if (sv_1.tau[ifxcor_1.is - 1] > sv_1.s[ifxcor_1.is - 1]) {
     goto L32;
     }
     if (itang == knumbr_1.k1 && znumbr_1.z5 * sv_1.tau[ifxcor_1.is - 1] >
         sv_1.s[ifxcor_1.is - 1]) {
     goto L32;
     }
 L26:
     if (sv1_1.cos1[ifxcor_1.is - 1] != 0.) {
     goto L27;
     } else {
     goto L28;
     }
 L27:
     sv1_1.csd[ifxcor_1.is - 1] = (d__1 = sv_1.s[ifxcor_1.is - 1] / sv1_1.cos1[
         ifxcor_1.is - 1], abs(d__1));
     goto L29;
 L28:
     sv1_1.csd[ifxcor_1.is - 1] = (d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1))
         + sv_1.tau[ifxcor_1.is - 1];
 L29:
     if (dshar4_1.dp - sv1_1.csd[ifxcor_1.is - 1] >= 0.) {
     goto L201;
     } else {
     goto L11;
     }
 L201:
     if (sv1_1.csd[ifxcor_1.is - 1] > znumbr_1.z9em1 * dshar4_1.dp) {
     if (dshar4_1.dp > fxcor_1.dpmax * sv_1.tau[ifxcor_1.is - 1]) {
         dshar4_1.dp *= .75;
         goto L11;
     }
     }
     if (isv1_1.j50[ifxcor_1.is - 1] >= 0) {
     goto L18;
     } else {
     goto L202;
     }
 L202:
     if (sv_1.tau[ifxcor_1.is - 1] - sv1_1.csd[ifxcor_1.is - 1] >= 0.) {
     goto L18;
     } else {
     goto L11;
     }
 L30:
     if (sv1_1.cos1[ifxcor_1.is - 1] <= 0.) {
     goto L31;
     } else {
     goto L24;
     }
 L31:
     if (sv_1.tau[ifxcor_1.is - 1] - sv_1.s[ifxcor_1.is - 1] <= 0.) {
     goto L32;
     } else {
     goto L26;
     }
 L32:
     if (isv1_1.j21[ifxcor_1.is - 1] <= 0) {
     goto L301;
     } else {
     goto L33;
     }
 L301:
     if (ishr18_1.ipdpl <= 0) {
     goto L15;
     } else {
     goto L18;
     }
 L33:
     for (k = 1; k <= 3; ++k) {
     fxcor_1.temp[k - 1] = sv_1.tp[k + ifxcor_1.is * 3 - 4];
     fxcor_1.temp[k + 2] = sv_1.tn[k + ifxcor_1.is * 3 - 4];
     sv_1.tp[k + ifxcor_1.is * 3 - 4] = sv_1.sp[k + ifxcor_1.is * 3 - 4] +
         sv_1.tau[ifxcor_1.is - 1] * fxcor_1.ti[k - 1];
 /* L37: */
     sv_1.tn[k + ifxcor_1.is * 3 - 4] = fxcor_1.ti[k - 1];
     }
     isv_1.iop[ifxcor_1.is - 1] = knumbr_1.k1;
     fxcor_1.temp[6] = sv_1.s[ifxcor_1.is - 1];
     if (isv_1.limfl[ifxcor_1.is - 1] != 0) {
     goto L34;
     } else {
     goto L35;
     }
 L34:
     ddlim_();
     goto L36;
 L35:
     chekfl_1.ichekf = 1;
     ddst_();
     chekfl_1.ichekf = 0;
 L36:
     for (k = 1; k <= 3; ++k) {
     sv_1.tp[k + ifxcor_1.is * 3 - 4] = fxcor_1.temp[k - 1];
     sv_1.tn[k + ifxcor_1.is * 3 - 4] = fxcor_1.temp[k + 2];
 /* L361: */
     }
     if (ifxcor_1.ier != 0) {
     goto L38;
     } else {
     goto L55;
     }
 L38:
     sv1_1.csd[ifxcor_1.is - 1] = 0.;
     sv_1.s[ifxcor_1.is - 1] = znumbr_1.z5 * dshar4_1.dp;
     goto L12;
 L39:
     if (knumbr_1.k3 - isv_1.isftyp[ifxcor_1.is - 1] != 0) {
     goto L40;
     } else {
     goto L23;
     }
 L40:
     sv1_1.cptst[ifxcor_1.is - 1] = znumbr_1.z0;
     sv1_1.cplfl[ifxcor_1.is - 1] = znumbr_1.z0;
     cplan_();
     ifxcor_1.it = ifxcor_1.it;
     if (ishr18_1.jcpr != 0) {
     goto L41;
     } else {
     goto L45;
     }
 L41:
     aerr_(&c_b61, "CHECK   ", (ftnlen)8);
     goto L11;
 L45:
     if (sv1_1.plncs[ifxcor_1.is - 1] >= 0.) {
     goto L46;
     } else {
     goto L24;
     }
 L46:
     fxcor_1.temp[0] = sv_1.plnv[ifxcor_1.is * 3 - 3] * fxcor_1.ti[0] +
         sv_1.plnv[ifxcor_1.is * 3 - 2] * fxcor_1.ti[1] + sv_1.plnv[
         ifxcor_1.is * 3 - 1] * fxcor_1.ti[2];
     if (fxcor_1.temp[0] != 0.) {
     goto L47;
     } else {
     goto L48;
     }
 L47:
     sv1_1.csd[ifxcor_1.is - 1] = (d__1 = sv_1.plnd[ifxcor_1.is - 1] /
         fxcor_1.temp[0], abs(d__1));
 L48:
     fxcor_1.temp[0] = (sv_1.sp[ifxcor_1.is * 3 - 3] - sv_1.sp[ifxcor_1.it * 3
         - 3]) * sv_1.tn[ifxcor_1.is * 3 - 3] + (sv_1.sp[ifxcor_1.is * 3 -
         2] - sv_1.sp[ifxcor_1.it * 3 - 2]) * sv_1.tn[ifxcor_1.is * 3 - 2]
         + (sv_1.sp[ifxcor_1.is * 3 - 1] - sv_1.sp[ifxcor_1.it * 3 - 1]) *
         sv_1.tn[ifxcor_1.is * 3 - 1];
     fxcor_1.temp[0] *= sv_1.tn[ifxcor_1.is * 3 - 3] * fxcor_1.ti[0] + sv_1.tn[
         i__ * 3 - 2] * fxcor_1.ti[1] + sv_1.tn[ifxcor_1.is * 3 - 1] *
         fxcor_1.ti[2];
     if (isv1_1.j22[ifxcor_1.is - 1] != 0) {
     goto L607;
     } else {
     goto L51;
     }
 L607:
     sv1_1.stckn[ifxcor_1.is - 1] = sv1_1.stck2[ifxcor_1.is - 1] *
         fxcor_1.temp[0];
 /*                   STPCK IF SURFACE PASSED */
     if (sv1_1.stckn[ifxcor_1.is - 1] >= 0.) {
     goto L6071;
     } else {
     goto L18;
     }
 /*                   STPCK IF SURFACE NEARBY */
 L6071:
     if ((d__1 = sv_1.plnd[ifxcor_1.is - 1], abs(d__1)) - znumbr_1.z2 *
         dshar4_1.dp <= 0.) {
     goto L6072;
     } else {
     goto L11;
     }
 L6072:
     if ((d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1)) - dshar4_1.dp <= 0.) {
     goto L18;
     } else {
     goto L11;
     }
 L51:
     sv1_1.stck2[ifxcor_1.is - 1] = fxcor_1.temp[0];
     if (sv1_1.stck2[ifxcor_1.is - 1] >= 0.) {
     goto L502;
     } else {
     goto L11;
     }
 L502:
     isv1_1.j22[ifxcor_1.is - 1] = knumbr_1.k1;
     goto L11;
 L52:
     if (sv1_1.csd[ifxcor_1.is - 1] - znumbr_1.z2 * dshar4_1.dp >= 0.) {
     goto L12;
     } else {
     goto L53;
     }
 L53:
     for (i__ = 1; i__ <= 3; ++i__) {
     dshar4_1.cmove[i__ - 1] = fxcor_1.temp[7] * fxcor_1.ti[i__ - 1];
 /* L54: */
     fxcor_1.te[i__ - 1] += dshar4_1.cmove[i__ - 1];
     }
     goto L18;
 L55:
     sv1_1.csd[ifxcor_1.is - 1] = (d__1 = fxcor_1.temp[6] / sv1_1.cos1[
         ifxcor_1.is - 1] + sv_1.s[ifxcor_1.is - 1] + sv_1.tau[ifxcor_1.is
         - 1], abs(d__1));
     fxcor_1.temp[7] = sv_1.s[ifxcor_1.is - 1];
     if (sv1_1.csd[ifxcor_1.is - 1] - znumbr_1.z5 * dshar4_1.dp >= 0.) {
     goto L102;
     } else {
     goto L101;
     }
 L101:
     sv_1.s[ifxcor_1.is - 1] = sv1_1.csd[ifxcor_1.is - 1];
     goto L152;
 L102:
     sv_1.s[ifxcor_1.is - 1] = znumbr_1.z5 * dshar4_1.dp;
 L152:
     if (sv_1.s[ifxcor_1.is - 1] - abs(fxcor_1.temp[6]) >= 0.) {
     goto L52;
     } else {
     goto L153;
     }
 L153:
     sv_1.s[ifxcor_1.is - 1] = abs(fxcor_1.temp[6]);
     goto L52;
 } /* check_ */
Variable Documentation
doublereal a
Definition at line 18 of file CHECK.c.
doublereal alp
Definition at line 28 of file CHECK.c.
doublereal ax4[3]
Definition at line 28 of file CHECK.c.
doublereal b
Definition at line 18 of file CHECK.c.
doublereal c__
Definition at line 18 of file CHECK.c.
integer c_b10 = -24201 static
Definition at line 133 of file CHECK.c.
Referenced by check_().
integer c_b61 = -24202 static
Definition at line 134 of file CHECK.c.
Referenced by check_().
doublereal cagl
Definition at line 28 of file CHECK.c.
doublereal cc[15]
Definition at line 50 of file CHECK.c.
doublereal cendis
Definition at line 18 of file CHECK.c.
struct { ... } charct_
struct { ... } chekfl_
doublereal cmove[3]
Definition at line 18 of file CHECK.c.
doublereal com1
Definition at line 18 of file CHECK.c.
doublereal com4
Definition at line 18 of file CHECK.c.
doublereal corrad[8]
Definition at line 43 of file CHECK.c.
doublereal cos1[5]
Definition at line 67 of file CHECK.c.
doublereal cplfl[5]
Definition at line 67 of file CHECK.c.
doublereal cptst[5]
Definition at line 67 of file CHECK.c.
doublereal csd[5]
Definition at line 67 of file CHECK.c.
doublereal cutdat[7]
Definition at line 28 of file CHECK.c.
doublereal d1
Definition at line 18 of file CHECK.c.
doublereal d2a
Definition at line 18 of file CHECK.c.
doublereal degrad
Definition at line 76 of file CHECK.c.
doublereal dir[3]
Definition at line 18 of file CHECK.c.
doublereal dp
Definition at line 18 of file CHECK.c.
doublereal dp1
Definition at line 18 of file CHECK.c.
doublereal dpcnt
Definition at line 18 of file CHECK.c.
doublereal dpe
Definition at line 18 of file CHECK.c.
doublereal dpi
Definition at line 18 of file CHECK.c.
doublereal dpl
Definition at line 18 of file CHECK.c.
doublereal dplan[15]
Definition at line 67 of file CHECK.c.
doublereal dpmax
Definition at line 28 of file CHECK.c.
doublereal dpmx1[5]
Definition at line 67 of file CHECK.c.
struct { ... } dshar4_
doublereal eps1[5]
Definition at line 50 of file CHECK.c.
doublereal eps2[5]
Definition at line 50 of file CHECK.c.
doublereal eps3[5]
Definition at line 50 of file CHECK.c.
doublereal eps4[5]
Definition at line 50 of file CHECK.c.
doublereal eps6[5]
Definition at line 50 of file CHECK.c.
doublereal eps8[5]
Definition at line 50 of file CHECK.c.
doublereal flipck
Definition at line 18 of file CHECK.c.
doublereal fwd[3]
Definition at line 18 of file CHECK.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file CHECK.c.
doublereal hi
Definition at line 28 of file CHECK.c.
integer i3dflg
Definition at line 100 of file CHECK.c.
integer iaerr
Definition at line 100 of file CHECK.c.
integer iafl[5]
Definition at line 84 of file CHECK.c.
integer iamdct
Definition at line 110 of file CHECK.c.
integer iautps
Definition at line 100 of file CHECK.c.
integer ibegin
Definition at line 100 of file CHECK.c.
integer ic
Definition at line 100 of file CHECK.c.
integer icanon[5]
Definition at line 84 of file CHECK.c.
integer icheck
Definition at line 100 of file CHECK.c.
integer ichekf
Definition at line 126 of file CHECK.c.
integer icl
Definition at line 100 of file CHECK.c.
integer ics
Definition at line 100 of file CHECK.c.
integer icscnt
Definition at line 100 of file CHECK.c.
integer ictdef
Definition at line 100 of file CHECK.c.
integer icut
Definition at line 100 of file CHECK.c.
integer ids
Definition at line 100 of file CHECK.c.
integer ier
Definition at line 100 of file CHECK.c.
integer ifar[5]
Definition at line 93 of file CHECK.c.
integer ifl4[5]
Definition at line 93 of file CHECK.c.
struct { ... } ifxcor_
integer igo
Definition at line 100 of file CHECK.c.
integer igoto
Definition at line 100 of file CHECK.c.
integer igoug
Definition at line 100 of file CHECK.c.
integer igs
Definition at line 100 of file CHECK.c.
integer index[5]
Definition at line 84 of file CHECK.c.
integer indir__[5]
Definition at line 84 of file CHECK.c.
integer inops
Definition at line 100 of file CHECK.c.
integer iop[5]
Definition at line 84 of file CHECK.c.
integer iopset[5]
Definition at line 84 of file CHECK.c.
integer ipdpl
Definition at line 110 of file CHECK.c.
integer ipl[5]
Definition at line 84 of file CHECK.c.
integer ips
Definition at line 100 of file CHECK.c.
integer ipsdef
Definition at line 100 of file CHECK.c.
integer ipt
Definition at line 110 of file CHECK.c.
integer ipt1
Definition at line 100 of file CHECK.c.
integer is
Definition at line 100 of file CHECK.c.
integer iseg
Definition at line 100 of file CHECK.c.
integer iseqno
Definition at line 100 of file CHECK.c.
integer isfidn[5]
Definition at line 84 of file CHECK.c.
integer isftyp[5]
Definition at line 84 of file CHECK.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 84 of file CHECK.c.
integer isrch
Definition at line 100 of file CHECK.c.
integer istrup
Definition at line 100 of file CHECK.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 84 of file CHECK.c.
integer it
Definition at line 100 of file CHECK.c.
integer itlon[5]
Definition at line 84 of file CHECK.c.
integer itseg[5]
Definition at line 84 of file CHECK.c.
integer itsegk[5]
Definition at line 84 of file CHECK.c.
integer iunfl[5]
Definition at line 84 of file CHECK.c.
integer iws
Definition at line 110 of file CHECK.c.
integer j10
Definition at line 110 of file CHECK.c.
integer j12
Definition at line 110 of file CHECK.c.
integer j13
Definition at line 110 of file CHECK.c.
integer j20[5]
Definition at line 93 of file CHECK.c.
integer j21[5]
Definition at line 93 of file CHECK.c.
integer j22[5]
Definition at line 93 of file CHECK.c.
integer j23[5]
Definition at line 93 of file CHECK.c.
integer j50[5]
Definition at line 93 of file CHECK.c.
integer j51[5]
Definition at line 93 of file CHECK.c.
integer j54
Definition at line 110 of file CHECK.c.
integer jbr
Definition at line 100 of file CHECK.c.
integer jckr
Definition at line 110 of file CHECK.c.
integer jcnt1
Definition at line 110 of file CHECK.c.
integer jcnt2
Definition at line 110 of file CHECK.c.
integer jcnt3
Definition at line 110 of file CHECK.c.
integer jcpr
Definition at line 110 of file CHECK.c.
integer jcr
Definition at line 110 of file CHECK.c.
integer jdr
Definition at line 110 of file CHECK.c.
integer jent[5]
Definition at line 84 of file CHECK.c.
integer jfind
Definition at line 110 of file CHECK.c.
integer jgr
Definition at line 110 of file CHECK.c.
integer jiops[5]
Definition at line 84 of file CHECK.c.
integer jmin
Definition at line 110 of file CHECK.c.
integer jminr
Definition at line 110 of file CHECK.c.
integer jph[5]
Definition at line 93 of file CHECK.c.
integer jpr
Definition at line 110 of file CHECK.c.
integer jpxr
Definition at line 110 of file CHECK.c.
integer jsw
Definition at line 100 of file CHECK.c.
integer jtkf
Definition at line 110 of file CHECK.c.
integer jtlflg[5]
Definition at line 84 of file CHECK.c.
integer jtn[5]
Definition at line 84 of file CHECK.c.
integer jtr
Definition at line 110 of file CHECK.c.
integer ju1[5]
Definition at line 84 of file CHECK.c.
integer k0
Definition at line 118 of file CHECK.c.
integer k1
Definition at line 118 of file CHECK.c.
integer k10
Definition at line 118 of file CHECK.c.
integer k1013
Definition at line 118 of file CHECK.c.
integer k12
Definition at line 118 of file CHECK.c.
integer k13
Definition at line 118 of file CHECK.c.
integer k15
Definition at line 118 of file CHECK.c.
integer k16
Definition at line 118 of file CHECK.c.
integer k18
Definition at line 118 of file CHECK.c.
integer k19
Definition at line 118 of file CHECK.c.
integer k1e4
Definition at line 118 of file CHECK.c.
integer k1e6
Definition at line 118 of file CHECK.c.
integer k2
Definition at line 118 of file CHECK.c.
integer k23
Definition at line 118 of file CHECK.c.
integer k24
Definition at line 118 of file CHECK.c.
integer k25
Definition at line 118 of file CHECK.c.
integer k26
Definition at line 118 of file CHECK.c.
integer k27
Definition at line 118 of file CHECK.c.
integer k29
Definition at line 118 of file CHECK.c.
integer k3
Definition at line 118 of file CHECK.c.
integer k30
Definition at line 118 of file CHECK.c.
integer k31
Definition at line 118 of file CHECK.c.
integer k32
Definition at line 118 of file CHECK.c.
integer k33
Definition at line 118 of file CHECK.c.
integer k34
Definition at line 118 of file CHECK.c.
integer k4
Definition at line 118 of file CHECK.c.
integer k44
Definition at line 118 of file CHECK.c.
integer k45
Definition at line 118 of file CHECK.c.
integer k46
Definition at line 118 of file CHECK.c.
integer k47
Definition at line 118 of file CHECK.c.
integer k48
Definition at line 118 of file CHECK.c.
integer k5
Definition at line 118 of file CHECK.c.
integer k50
Definition at line 118 of file CHECK.c.
integer k51
Definition at line 118 of file CHECK.c.
integer k52
Definition at line 118 of file CHECK.c.
integer k6
Definition at line 118 of file CHECK.c.
integer k7
Definition at line 118 of file CHECK.c.
integer k8
Definition at line 118 of file CHECK.c.
integer k9
Definition at line 118 of file CHECK.c.
integer km1
Definition at line 118 of file CHECK.c.
struct { ... } knumbr_
integer limfl[5]
Definition at line 84 of file CHECK.c.
integer lsv
Definition at line 100 of file CHECK.c.
integer lsv1
Definition at line 100 of file CHECK.c.
integer mantax
Definition at line 100 of file CHECK.c.
integer mdic
Definition at line 110 of file CHECK.c.
char modfer[6]
Definition at line 37 of file CHECK.c.
integer motmod
Definition at line 100 of file CHECK.c.
integer msav
Definition at line 100 of file CHECK.c.
integer mulout
Definition at line 100 of file CHECK.c.
integer nmbseg
Definition at line 100 of file CHECK.c.
integer nmpnts
Definition at line 100 of file CHECK.c.
integer notan[5]
Definition at line 93 of file CHECK.c.
integer nrec
Definition at line 100 of file CHECK.c.
integer numax
Definition at line 100 of file CHECK.c.
integer numcnt
Definition at line 100 of file CHECK.c.
integer nump
Definition at line 100 of file CHECK.c.
integer numpt1
Definition at line 100 of file CHECK.c.
integer numsfs
Definition at line 100 of file CHECK.c.
integer numsur
Definition at line 100 of file CHECK.c.
integer nw
Definition at line 100 of file CHECK.c.
integer nwds
Definition at line 100 of file CHECK.c.
doublereal ogle[3]
Definition at line 18 of file CHECK.c.
doublereal p1[3]
Definition at line 18 of file CHECK.c.
doublereal p2[3]
Definition at line 18 of file CHECK.c.
doublereal param[6]
Definition at line 18 of file CHECK.c.
doublereal past[5]
Definition at line 50 of file CHECK.c.
doublereal pi
Definition at line 76 of file CHECK.c.
doublereal plncs[5]
Definition at line 67 of file CHECK.c.
doublereal plnd[5]
Definition at line 50 of file CHECK.c.
doublereal plnd1[5]
Definition at line 67 of file CHECK.c.
doublereal plnv[15]
Definition at line 50 of file CHECK.c.
doublereal pltst[5]
Definition at line 67 of file CHECK.c.
doublereal pmove[3]
Definition at line 28 of file CHECK.c.
doublereal r__[6]
Definition at line 18 of file CHECK.c.
doublereal ra
Definition at line 28 of file CHECK.c.
doublereal rc[5]
Definition at line 50 of file CHECK.c.
doublereal rc1
Definition at line 28 of file CHECK.c.
doublereal rdrn
Definition at line 18 of file CHECK.c.
doublereal refpnt[3]
Definition at line 18 of file CHECK.c.
doublereal ri[8]
Definition at line 43 of file CHECK.c.
doublereal s[5]
Definition at line 50 of file CHECK.c.
doublereal sagl
Definition at line 28 of file CHECK.c.
doublereal save[5]
Definition at line 50 of file CHECK.c.
doublereal savpar[4]
Definition at line 18 of file CHECK.c.
doublereal seg[9]
Definition at line 18 of file CHECK.c.
doublereal sfvct[15]
Definition at line 50 of file CHECK.c.
doublereal sk[15]
Definition at line 50 of file CHECK.c.
doublereal slope
Definition at line 18 of file CHECK.c.
doublereal slx[15]
Definition at line 50 of file CHECK.c.
doublereal sn[15]
Definition at line 50 of file CHECK.c.
doublereal snk[15]
Definition at line 50 of file CHECK.c.
doublereal snl[15]
Definition at line 50 of file CHECK.c.
doublereal sp[15]
Definition at line 50 of file CHECK.c.
doublereal spk[15]
Definition at line 50 of file CHECK.c.
doublereal spl[15]
Definition at line 50 of file CHECK.c.
doublereal sqroot
Definition at line 18 of file CHECK.c.
doublereal stck[5]
Definition at line 67 of file CHECK.c.
doublereal stck1[5]
Definition at line 67 of file CHECK.c.
doublereal stck2[5]
Definition at line 67 of file CHECK.c.
doublereal stckn[5]
Definition at line 67 of file CHECK.c.
doublereal strtno
Definition at line 28 of file CHECK.c.
doublereal surd
Definition at line 28 of file CHECK.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 28 of file CHECK.c.
doublereal tak[3]
Definition at line 28 of file CHECK.c.
doublereal tal[3]
Definition at line 28 of file CHECK.c.
doublereal tangl
Definition at line 18 of file CHECK.c.
doublereal tanhi[8]
Definition at line 43 of file CHECK.c.
doublereal tanlo[8]
Definition at line 43 of file CHECK.c.
doublereal tau[5]
Definition at line 50 of file CHECK.c.
doublereal tau1[5]
Definition at line 50 of file CHECK.c.
doublereal tau2[5]
Definition at line 50 of file CHECK.c.
doublereal tcont[9]
Definition at line 43 of file CHECK.c.
doublereal te[3]
Definition at line 28 of file CHECK.c.
doublereal tee[15]
Definition at line 67 of file CHECK.c.
doublereal tek[3]
Definition at line 28 of file CHECK.c.
doublereal tel[3]
Definition at line 28 of file CHECK.c.
doublereal tem[10]
Definition at line 28 of file CHECK.c.
doublereal temp[24]
Definition at line 28 of file CHECK.c.
doublereal tes[3]
Definition at line 18 of file CHECK.c.
doublereal tew[3]
Definition at line 18 of file CHECK.c.
doublereal th[5]
Definition at line 50 of file CHECK.c.
doublereal ti[3]
Definition at line 28 of file CHECK.c.
doublereal tik[3]
Definition at line 28 of file CHECK.c.
doublereal til[3]
Definition at line 28 of file CHECK.c.
doublereal tlhit
Definition at line 28 of file CHECK.c.
doublereal tlhite[8]
Definition at line 43 of file CHECK.c.
doublereal tlinc[9]
Definition at line 43 of file CHECK.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file CHECK.c.
doublereal tn[15]
Definition at line 50 of file CHECK.c.
doublereal tnl[15]
Definition at line 67 of file CHECK.c.
doublereal toolht[15]
Definition at line 50 of file CHECK.c.
doublereal toolwd[5]
Definition at line 50 of file CHECK.c.
doublereal tp[15]
Definition at line 50 of file CHECK.c.
doublereal tpk[15]
Definition at line 50 of file CHECK.c.
doublereal u1[15]
Definition at line 50 of file CHECK.c.
doublereal u1k[15]
Definition at line 50 of file CHECK.c.
doublereal u2[3]
Definition at line 18 of file CHECK.c.
doublereal umax[8]
Definition at line 43 of file CHECK.c.
doublereal unn
Definition at line 18 of file CHECK.c.
doublereal upp
Definition at line 18 of file CHECK.c.
doublereal uvec[3]
Definition at line 18 of file CHECK.c.
doublereal v[3]
Definition at line 18 of file CHECK.c.
doublereal varble[5]
Definition at line 50 of file CHECK.c.
doublereal vint
Definition at line 18 of file CHECK.c.
doublereal vl
Definition at line 18 of file CHECK.c.
doublereal vndir[15]
Definition at line 50 of file CHECK.c.
doublereal vnn
Definition at line 18 of file CHECK.c.
doublereal vpp
Definition at line 18 of file CHECK.c.
doublereal vt[15]
Definition at line 50 of file CHECK.c.
doublereal vtem
Definition at line 28 of file CHECK.c.
doublereal z0
Definition at line 76 of file CHECK.c.
doublereal z1
Definition at line 76 of file CHECK.c.
doublereal z10
Definition at line 76 of file CHECK.c.
doublereal z11em1
Definition at line 76 of file CHECK.c.
doublereal z12em1
Definition at line 76 of file CHECK.c.
doublereal z1e38
Definition at line 76 of file CHECK.c.
doublereal z1e6
Definition at line 76 of file CHECK.c.
doublereal z1em1
Definition at line 76 of file CHECK.c.
doublereal z1em2
Definition at line 76 of file CHECK.c.
doublereal z1em3
Definition at line 76 of file CHECK.c.
doublereal z1em5
Definition at line 76 of file CHECK.c.
doublereal z1em6
Definition at line 76 of file CHECK.c.
doublereal z1em7
Definition at line 76 of file CHECK.c.
doublereal z1em9
Definition at line 76 of file CHECK.c.
doublereal z2
Definition at line 76 of file CHECK.c.
doublereal z3
Definition at line 76 of file CHECK.c.
doublereal z5
Definition at line 76 of file CHECK.c.
doublereal z5em1
Definition at line 76 of file CHECK.c.
doublereal z5em6
Definition at line 76 of file CHECK.c.
doublereal z6em1
Definition at line 76 of file CHECK.c.
doublereal z90
Definition at line 76 of file CHECK.c.
doublereal z9em1
Definition at line 76 of file CHECK.c.
doublereal z__[5]
Definition at line 50 of file CHECK.c.
doublereal zl
Definition at line 18 of file CHECK.c.
doublereal zl1
Definition at line 18 of file CHECK.c.
doublereal zlnorm[3]
Definition at line 18 of file CHECK.c.
doublereal zlpnt[3]
Definition at line 18 of file CHECK.c.
doublereal zm1
Definition at line 76 of file CHECK.c.
struct { ... } znumbr_