My Project: CILOUT.c File Reference
CILOUT.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define prt_1 prt_
#define darray_1 darray_
#define outbuf_1 outbuf_
#define numblk_1 numblk_
#define cilprt ((logical *)&prt_1)
Functions
int cilout_ (integer *comand, integer *count, integer *code)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer prt [7]
} prt_
struct {
char darray [120]
} darray_
struct {
integer pagpak
integer isc
integer iscarr
integer icform
integer ifloat
integer icom
integer macwds
integer ppwrds
logical macflg
logical labflg
logical rsvflg
integer lpage
integer buffer [256]
integer labbuf [256]
integer ibuf
integer ilbuf
integer pppage
integer mcpage
} outbuf_
struct {
integer mnmbnd
integer numidx
integer nmbrs
integer lstchr
integer masgnd
} numblk_
static integer c__1 = 1
static integer c__6 = 6
static integer c__7 = 7
static integer c__12 = 12
static integer c__13 = 13
static integer c__19 = 19
static integer c__27 = 27
static integer c__92 = 92
Macro Definition Documentation
#define cilprt ((logical *)&prt_1)
Referenced by cilout_().
#define cnamtb_1 cnamtb_
Definition at line 28 of file CILOUT.c.
Referenced by cilout_().
#define darray_1 darray_
Definition at line 40 of file CILOUT.c.
Referenced by cilout_().
#define nametb_1 nametb_
Definition at line 22 of file CILOUT.c.
Referenced by cilout_().
#define numblk_1 numblk_
Definition at line 54 of file CILOUT.c.
Referenced by cilout_().
#define outbuf_1 outbuf_
Definition at line 48 of file CILOUT.c.
Referenced by cilout_().
#define prt_1 prt_
Definition at line 34 of file CILOUT.c.
Function Documentation
int cilout_ (integer * comand, integer * count, integer * code)
Definition at line 82 of file CILOUT.c.
References abcdbn_(), c__1, c__12, c__13, c__19, c__27, c__6, c__7, c__92, cform_(), cilprt, cnamtb_1, code, count, cprint_(), darray_1, holfrm_(), i__, iconv_(), j, l, nametb_1, numblk_1, outbuf_1, and rlsbuf_().
Referenced by icmprs_().
 {
     /* System generated locals */
     integer i__1, i__2;
     /* Local variables */
     static integer i__, j, l, ibf, nwd;
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen), iconv_(integer *, char *, integer *, integer *,
         ftnlen);
     static integer kount;
     extern /* Subroutine */ int abcdbn_(char *, integer *, integer *, ftnlen),
          holfrm_(integer *, char *, integer *, integer *, integer *,
         ftnlen);
 #define cilprt ((logical *)&prt_1)
     extern /* Subroutine */ int rlsbuf_(void), cprint_(char *, ftnlen);
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /*       14.    I. L. LIST OPTION FLAGS */
 /* CILPRT:      TRUE WHEN COMPRESSED I.L. PRINTING REQUESTED */
 /*       20.    IO - ARRAY */
 /*       34.    COMMON BLOCK FOR INTERPRETIVE C.I.L. OUTPUT */
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
 /* LABFLG:      INDICATES I.L. COMMAND IS LABEL (INTERPRETER) */
 /* RSVFLG:      TRUE IF I.L. COMMAND IS A RESRV (INTERPRETER) */
 /* IBUF:        NUMBER OF RECORDS IN BUFFER ARRAY */
 /* ILBUF:       NUMBER OF ITEMS IN THE LABBUF ARRAY (INTERPRETER) */
 /* BUFFER:      TEMPORARY STORAGE FOR INTERPRETER OUTPUT (PAGES) */
 /* LABBUF:      TEMPORARY STORAGE FOR LABEL,HOLDAT ENTRY AND RESRV I.L. */
 /*       45.    NUMBER TABLE INDICES */
 /* MNMBND:      LAST NAME TABLE ENTRY TO MACRO ASSIGNED NUMBER SECTION */
 /*  NMBRS:      QUANTITY OF NUMBERS IN THE CURRENT STATEMENT */
 /* * */
 /*       45.    NUMBER TABLE INDICES */
 /* MNMBND:      LAST NAME TABLE ENTRY TO MACRO ASSIGNED NUMBER SECTION */
 /* NUMIDX:      NAMTBL INDEX OF A NUMBER GIVEN IN THE CURRENT STATEMENT */
 /*  NMBRS:      QUANTITY OF NUMBERS IN THE CURRENT STATEMENT */
 /* LSTCHR:      LAST CHARACTER OF A NUMBER */
 /* MASGND:      NAME TABLE INDEX OF SECTION END FOR NUMBERS ASSIGNMENT */
 /* ** */
 /* ...     IS THIS A HOLDAT STATEMENT */
     /* Parameter adjustments */
     --code;
     /* Function Body */
     if (*comand == 21) {
     goto L200;
     }
     ibf = *count;
     if (*comand != 9) {
     ibf = *count + numblk_1.nmbrs;
     }
     goto L20;
 /* ...     IS THIS A LABEL OR RESRV STATEMENT */
 L1:
     if (outbuf_1.labflg || outbuf_1.rsvflg) {
     goto L100;
     }
 /* ...     NO */
 /* ...     CODE TO GO INTO BUFFER. TEST IF THERE IS ROOM */
     if (outbuf_1.ibuf + ibf + 4 > 256) {
     rlsbuf_();
     }
     outbuf_1.buffer[outbuf_1.ibuf + 2] = *comand;
     outbuf_1.buffer[outbuf_1.ibuf + 3] = ibf;
     outbuf_1.ibuf += 2;
     if (*count == 0) {
     return 0;
     }
     i__1 = *count;
     for (i__ = 1; i__ <= i__1; ++i__) {
     j = code[i__];
     if (j <= nametb_1.nammax) {
         goto L5;
     }
     if (code[i__ - 1] != 7) {
         goto L5;
     }
     j -= nametb_1.nammax;
     abcdbn_(cnamtb_1.cnumtb + (j - 1) * 12, &outbuf_1.buffer[
         outbuf_1.ibuf + 2], &c__1, (ftnlen)12);
     ++outbuf_1.ibuf;
     goto L10;
 L5:
     outbuf_1.buffer[outbuf_1.ibuf + 2] = j;
 L10:
     ++outbuf_1.ibuf;
     }
     if (*comand != 9) {
     numblk_1.nmbrs = 0;
     }
     return 0;
 /* ...     IS CILPRT MARKER SET */
 L20:
     if (! (*cilprt)) {
     goto L1;
     }
     iconv_(comand, darray_1.darray, &c__1, &c__6, (ftnlen)120);
     iconv_(&ibf, darray_1.darray, &c__7, &c__6, (ftnlen)120);
     l = 13;
     i__1 = *count;
     for (i__ = 1; i__ <= i__1; ++i__) {
     if (code[i__] > nametb_1.nammax) {
         if (code[i__ - 1] == 7) {
         i__2 = l + 2;
         cform_(cnamtb_1.cnumtb + (code[i__] - nametb_1.nammax - 1) *
             12, darray_1.darray, &i__2, &c__12, (ftnlen)12, (
             ftnlen)120);
         l += 14;
         } else {
         iconv_(&code[i__], darray_1.darray, &l, &c__6, (ftnlen)120);
         l += 6;
         }
     } else {
         iconv_(&code[i__], darray_1.darray, &l, &c__6, (ftnlen)120);
         l += 6;
     }
     if (l <= 106) {
         goto L1000;
     }
     l = 13;
     cprint_(darray_1.darray, (ftnlen)120);
 L1000:
     ;
     }
     cprint_(darray_1.darray, (ftnlen)120);
     goto L1;
 /* ...     LABEL OR RESRV STATEMENT. */
 /*        CODE TO GO INTO LABBUF. TEST IF THERE IS ROOM */
 L100:
     if (outbuf_1.ilbuf + *count + 4 > 254) {
     rlsbuf_();
     }
     outbuf_1.labbuf[outbuf_1.ilbuf + 2] = *comand;
     outbuf_1.labbuf[outbuf_1.ilbuf + 3] = *count;
     outbuf_1.ilbuf += 2;
     i__1 = *count;
     for (i__ = 1; i__ <= i__1; ++i__) {
     outbuf_1.labbuf[outbuf_1.ilbuf + 2] = code[i__];
 /* L110: */
     ++outbuf_1.ilbuf;
     }
     return 0;
 /* ...     HOLDAT STATEMENT */
 L200:
     outbuf_1.labflg = TRUE_;
     if (outbuf_1.ilbuf + (*count << 1) > 256) {
     rlsbuf_();
     }
     outbuf_1.labflg = FALSE_;
     outbuf_1.labbuf[outbuf_1.ilbuf + 2] = *comand;
     outbuf_1.labbuf[outbuf_1.ilbuf + 4] = code[1];
     outbuf_1.labbuf[outbuf_1.ilbuf + 5] = code[2];
     outbuf_1.labbuf[outbuf_1.ilbuf + 3] = *count;
     outbuf_1.ilbuf += 4;
     i__1 = *count;
     for (i__ = 3; i__ <= i__1; ++i__) {
     outbuf_1.labbuf[outbuf_1.ilbuf + 2] = code[i__];
 /* L210: */
     ++outbuf_1.ilbuf;
     }
 /* ...     IS CILPRT MARKER SET */
     if (! (*cilprt)) {
     return 0;
     }
     kount = code[2];
     iconv_(comand, darray_1.darray, &c__1, &c__6, (ftnlen)120);
     iconv_(count, darray_1.darray, &c__7, &c__6, (ftnlen)120);
     iconv_(&code[1], darray_1.darray, &c__13, &c__6, (ftnlen)120);
     iconv_(&code[2], darray_1.darray, &c__19, &c__6, (ftnlen)120);
     l = 3;
 L1001:
     if (kount <= 93) {
     goto L1002;
     }
     holfrm_(&code[l], darray_1.darray, &c__27, &c__92, &nwd, (ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     kount += -92;
     l += 23;
     goto L1001;
 L1002:
     holfrm_(&code[l], darray_1.darray, &c__27, &kount, &nwd, (ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     return 0;
 } /* cilout_ */
Variable Documentation
integer buffer[256]
Definition at line 45 of file CILOUT.c.
integer c__1 = 1 static
Definition at line 58 of file CILOUT.c.
Referenced by cilout_().
integer c__12 = 12 static
Definition at line 61 of file CILOUT.c.
Referenced by cilout_().
integer c__13 = 13 static
Definition at line 62 of file CILOUT.c.
Referenced by cilout_().
integer c__19 = 19 static
Definition at line 63 of file CILOUT.c.
Referenced by cilout_().
integer c__27 = 27 static
Definition at line 64 of file CILOUT.c.
Referenced by cilout_().
integer c__6 = 6 static
Definition at line 59 of file CILOUT.c.
Referenced by cilout_().
integer c__7 = 7 static
Definition at line 60 of file CILOUT.c.
Referenced by cilout_().
integer c__92 = 92 static
Definition at line 65 of file CILOUT.c.
Referenced by cilout_().
integer charnd
Definition at line 18 of file CILOUT.c.
integer charst
Definition at line 18 of file CILOUT.c.
char cnamtb[18000]
Definition at line 25 of file CILOUT.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file CILOUT.c.
char darray[120]
Definition at line 37 of file CILOUT.c.
struct { ... } darray_
integer ibuf
Definition at line 45 of file CILOUT.c.
integer icform
Definition at line 43 of file CILOUT.c.
integer icom
Definition at line 43 of file CILOUT.c.
integer ifixnd
Definition at line 18 of file CILOUT.c.
integer ifixst
Definition at line 18 of file CILOUT.c.
integer ifloat
Definition at line 43 of file CILOUT.c.
integer ilbuf
Definition at line 45 of file CILOUT.c.
integer inamnd
Definition at line 18 of file CILOUT.c.
integer inamst
Definition at line 18 of file CILOUT.c.
integer isc
Definition at line 43 of file CILOUT.c.
integer iscarr
Definition at line 43 of file CILOUT.c.
integer labbuf[256]
Definition at line 45 of file CILOUT.c.
logical labflg
Definition at line 44 of file CILOUT.c.
integer lpage
Definition at line 45 of file CILOUT.c.
integer lstchr
Definition at line 51 of file CILOUT.c.
logical macflg
Definition at line 44 of file CILOUT.c.
integer macwds
Definition at line 43 of file CILOUT.c.
integer masgnd
Definition at line 51 of file CILOUT.c.
integer mcpage
Definition at line 45 of file CILOUT.c.
integer mnmbnd
Definition at line 51 of file CILOUT.c.
integer namest
Definition at line 18 of file CILOUT.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file CILOUT.c.
integer namtbl[3000]
Definition at line 18 of file CILOUT.c.
integer nmbrs
Definition at line 51 of file CILOUT.c.
struct { ... } numblk_
integer numbnd
Definition at line 18 of file CILOUT.c.
integer numbst
Definition at line 18 of file CILOUT.c.
integer numidx
Definition at line 51 of file CILOUT.c.
struct { ... } outbuf_
integer pagpak
Definition at line 43 of file CILOUT.c.
integer pppage
Definition at line 45 of file CILOUT.c.
integer ppwrds
Definition at line 43 of file CILOUT.c.
integer prt[7]
Definition at line 31 of file CILOUT.c.
struct { ... } prt_
logical rsvflg
Definition at line 44 of file CILOUT.c.