My Project: CIRDEF.c File Reference
CIRDEF.c File Reference
#include "f2c.h"
Macros
#define znumbr_1 znumbr_
Functions
logical cirdef_ (doublereal *cir, integer *mn)
Variables
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
Macro Definition Documentation
#define znumbr_1 znumbr_
Definition at line 23 of file CIRDEF.c.
Referenced by cirdef_().
Function Documentation
logical cirdef_ (doublereal * cir, integer * mn)
Definition at line 46 of file CIRDEF.c.
References ckdef_(), error_(), and znumbr_1.
Referenced by transf_().
 {
     /* System generated locals */
     doublereal d__1;
     logical ret_val;
     /* Local variables */
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /* ...     CHECK WHETHER INPUT CANONICAL FORM IS DEFINED */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
     /* Parameter adjustments */
     --cir;
     /* Function Body */
     if (ckdef_(&cir[1])) {
     goto L1;
     }
 /* ...     CHECK WHETHER CYLINDER IS WITHIN TOLERANCE OF VERTICAL */
     if ((d__1 = abs(cir[6]) - znumbr_1.z1, abs(d__1)) <= znumbr_1.z1em5 &&
         abs(cir[4]) <= znumbr_1.z1em5 && abs(cir[5]) <= znumbr_1.z1em5) {
     goto L2;
     }
 /* ...     ISSUE DIAGNOSTIC */
     error_(mn, "CIRDEF  ", (ftnlen)8);
 /* ...     RETURN VALUE TRUE */
 L1:
     ret_val = TRUE_;
     goto L9;
 /* ...     RETURN VALUE FALSE */
 L2:
     ret_val = FALSE_;
 L9:
     return ret_val;
 } /* cirdef_ */
Variable Documentation
doublereal degrad
Definition at line 18 of file CIRDEF.c.
doublereal pi
Definition at line 18 of file CIRDEF.c.
doublereal z0
Definition at line 18 of file CIRDEF.c.
doublereal z1
Definition at line 18 of file CIRDEF.c.
doublereal z10
Definition at line 18 of file CIRDEF.c.
doublereal z11em1
Definition at line 18 of file CIRDEF.c.
doublereal z12em1
Definition at line 18 of file CIRDEF.c.
doublereal z1e38
Definition at line 18 of file CIRDEF.c.
doublereal z1e6
Definition at line 18 of file CIRDEF.c.
doublereal z1em1
Definition at line 18 of file CIRDEF.c.
doublereal z1em2
Definition at line 18 of file CIRDEF.c.
doublereal z1em3
Definition at line 18 of file CIRDEF.c.
doublereal z1em5
Definition at line 18 of file CIRDEF.c.
doublereal z1em6
Definition at line 18 of file CIRDEF.c.
doublereal z1em7
Definition at line 18 of file CIRDEF.c.
doublereal z1em9
Definition at line 18 of file CIRDEF.c.
doublereal z2
Definition at line 18 of file CIRDEF.c.
doublereal z3
Definition at line 18 of file CIRDEF.c.
doublereal z5
Definition at line 18 of file CIRDEF.c.
doublereal z5em1
Definition at line 18 of file CIRDEF.c.
doublereal z5em6
Definition at line 18 of file CIRDEF.c.
doublereal z6em1
Definition at line 18 of file CIRDEF.c.
doublereal z90
Definition at line 18 of file CIRDEF.c.
doublereal z9em1
Definition at line 18 of file CIRDEF.c.
doublereal zm1
Definition at line 18 of file CIRDEF.c.
struct { ... } znumbr_