My Project: CKDEF.c File Reference
CKDEF.c File Reference
#include "f2c.h"
Macros
#define sdp_1 sdp_
Functions
logical ckdef_ (integer *arg)
logical ckstr_ (integer *arg)
logical ckdtr_ (integer *arg)
Variables
struct {
integer nbchar
integer nbwrd
integer iwrd
integer ifac
} sdp_
static integer c__1 = 1
Macro Definition Documentation
#define sdp_1 sdp_
Definition at line 21 of file CKDEF.c.
Referenced by ckdef_(), ckdtr_(), and ckstr_().
Function Documentation
logical ckdef_ (integer * arg)
Definition at line 37 of file CKDEF.c.
References c__1, error_(), first, i2, and sdp_1.
Referenced by anglb_(), anglf_(), apt009_(), apt011_(), apt029_(), apt034_(), apt035_(), apt037_(), apt038_(), apt039_(), apt040_(), apt043_(), apt045_(), apt046_(), apt050_(), apt051_(), apt052_(), apt053_(), apt055_(), apt056_(), apt065_(), apt068_(), apt069_(), apt070_(), apt071_(), apt073_(), apt087_(), apt088_(), apt090_(), apt094_(), apt100_(), apt106_(), apt107_(), apt108_(), apt109_(), apt234_(), apt235_(), canf_(), cirdef_(), ddpara_(), distf_(), dotf_(), gclear_(), gencrv_(), gfetch_(), golovo_(), gotopn_(), intrp_(), intsec_(), lindef_(), lnthf_(), numf1_(), numf2_(), parmf1_(), parmf2_(), pocket_(), refsys_(), scon_(), smil_(), spatf_(), srfcom_(), transf_(), and zvect_().
 {
     /* Initialized data */
     static logical first = TRUE_;
     /* System generated locals */
     logical ret_val;
     /* Builtin functions */
     integer lbit_shift(integer, integer);
     /* Local variables */
     static integer i2, i3, ash, dtr, str;
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
     /* Parameter adjustments */
     --arg;
     /* Function Body */
     if (first) {
     i3 = sdp_1.nbchar * 3;
     i2 = sdp_1.nbchar << 1;
     str = lbit_shift('*', i3) + lbit_shift('T', sdp_1.nbchar) + 'R';
     dtr = lbit_shift('$', i3) + lbit_shift('T', sdp_1.nbchar) + 'R';
     ash = lbit_shift('A', i3) + lbit_shift('S', i2) + lbit_shift('H',
         sdp_1.nbchar);
     first = FALSE_;
     }
     if (arg[1] == str && arg[2] == ash) {
     ret_val = TRUE_;
     error_(&c__1, "CKDEF   ", (ftnlen)8);
     } else if (arg[1] == dtr && arg[2] == ash) {
     ret_val = TRUE_;
     } else {
     ret_val = FALSE_;
     }
     return ret_val;
 } /* ckdef_ */
logical ckdtr_ (integer * arg)
Definition at line 139 of file CKDEF.c.
References first, i2, and sdp_1.
Referenced by apt104_(), print_(), and punch_().
 {
     /* Initialized data */
     static logical first = TRUE_;
     /* System generated locals */
     logical ret_val;
     /* Builtin functions */
     integer lbit_shift(integer, integer);
     /* Local variables */
     static integer i2, i3, ash, dtr;
     /* Parameter adjustments */
     --arg;
     /* Function Body */
     if (first) {
     i3 = sdp_1.nbchar * 3;
     i2 = sdp_1.nbchar << 1;
     dtr = lbit_shift('$', i3) + lbit_shift('T', sdp_1.nbchar) + 'R';
     ash = lbit_shift('A', i3) + lbit_shift('S', i2) + lbit_shift('H',
         sdp_1.nbchar);
     first = FALSE_;
     }
     if (arg[1] == dtr && arg[2] == ash) {
     ret_val = TRUE_;
     } else {
     ret_val = FALSE_;
     }
     return ret_val;
 } /* ckdtr_ */
logical ckstr_ (integer * arg)
Definition at line 91 of file CKDEF.c.
References first, i2, and sdp_1.
Referenced by apt103_(), apt104_(), print_(), and punch_().
 {
     /* Initialized data */
     static logical first = TRUE_;
     /* System generated locals */
     logical ret_val;
     /* Builtin functions */
     integer lbit_shift(integer, integer);
     /* Local variables */
     static integer i2, i3, ash, str;
     /* Parameter adjustments */
     --arg;
     /* Function Body */
     if (first) {
     i3 = sdp_1.nbchar * 3;
     i2 = sdp_1.nbchar << 1;
     str = lbit_shift('*', i3) + lbit_shift('T', sdp_1.nbchar) + 'R';
     ash = lbit_shift('A', i3) + lbit_shift('S', i2) + lbit_shift('H',
         sdp_1.nbchar);
     first = FALSE_;
     }
     if (arg[1] == str && arg[2] == ash) {
     ret_val = TRUE_;
     } else {
     ret_val = FALSE_;
     }
     return ret_val;
 } /* ckstr_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 25 of file CKDEF.c.
Referenced by ckdef_().
integer ifac
Definition at line 18 of file CKDEF.c.
integer iwrd
Definition at line 18 of file CKDEF.c.
integer nbchar
Definition at line 18 of file CKDEF.c.
integer nbwrd
Definition at line 18 of file CKDEF.c.
struct { ... } sdp_