My Project: CLDATF.c File Reference
CLDATF.c File Reference
#include "f2c.h"
Functions
int cldatf_ (doublereal *result, doublereal *arg1, integer *arg2, doublereal *arg3)
Variables
static integer c__93 = 93
Function Documentation
int cldatf_ (doublereal * result, doublereal * arg1, integer * arg2, doublereal * arg3)
Definition at line 38 of file CLDATF.c.
References ataper_(), bcdf_(), c__93, error_(), first, ii, and p.
Referenced by region_(), and xcall_().
 {
     /* Initialized data */
     static logical first = TRUE_;
     static doublereal p[6];
     static integer ii, iee;
     extern integer bcdf_(char *, ftnlen);
     static integer isct, ipnt, ityp, narg2[6];
     extern /* Subroutine */ int error_(integer *, char *, ftnlen), ataper_(
         doublereal *, integer *, integer *, integer *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
     if (first) {
     narg2[0] = bcdf_("UDS ", (ftnlen)4);
     narg2[1] = bcdf_("VDS ", (ftnlen)4);
     narg2[2] = bcdf_("PDS ", (ftnlen)4);
     narg2[3] = bcdf_("UPS ", (ftnlen)4);
     narg2[4] = bcdf_("VPS ", (ftnlen)4);
     narg2[5] = bcdf_("PPS ", (ftnlen)4);
     first = FALSE_;
     }
     for (ii = 1; ii <= 6; ++ii) {
     if (narg2[ii - 1] == *arg2) {
         goto L20;
     }
 /* L10: */
     }
 L15:
     error_(&c__93, "CLDATF  ", (ftnlen)8);
     *result = 0.;
     return 0;
 L20:
     ityp = ii / 4 + 8;
     isct = (integer) (*arg1);
     ipnt = (integer) (*arg3);
     ataper_(p, &ipnt, &isct, &ityp, &iee);
     if (iee == 0) {
     goto L30;
     }
     goto L15;
 L30:
     if (ii > 3) {
     ii += -3;
     }
     *result = p[ii - 1];
 /* L40: */
     return 0;
 } /* cldatf_ */
Variable Documentation
integer c__93 = 93 static
Definition at line 17 of file CLDATF.c.
Referenced by cldatf_().