My Project: CLDAT.c File Reference
CLDAT.c File Reference
#include "f2c.h"
Macros
#define ifxcor_1 ifxcor_
#define cldt_1 cldt_
#define chcldt_1 chcldt_
#define clr (equiv_0)
#define nclr ((integer *)equiv_0)
Functions
int cldat_ (integer *arg1, integer *arg2, integer *arg3, integer *arg4)
Variables
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
logical cldfg
integer iclcod
integer iclcnt
integer icline
integer iclblk
integer iclrcd
integer icltab [500]
integer iptvec [9]
} cldt_
struct {
char pntvct [72]
} chcldt_
static integer c__94 = 94
static integer c__95 = 95
Macro Definition Documentation
#define chcldt_1 chcldt_
Definition at line 39 of file CLDAT.c.
Referenced by cldat_().
#define cldt_1 cldt_
Definition at line 33 of file CLDAT.c.
Referenced by cldat_().
#define clr (equiv_0)
Referenced by cldat_().
#define ifxcor_1 ifxcor_
Definition at line 25 of file CLDAT.c.
Referenced by cldat_().
#define nclr ((integer *)equiv_0)
Referenced by cldat_().
Function Documentation
int cldat_ (integer * arg1, integer * arg2, integer * arg3, integer * arg4)
Definition at line 49 of file CLDAT.c.
References apt299_(), arg1, arg2, bcdf_(), c__94, c__95, chcldt_1, cldt_1, clr, error_(), first, i__, ifxcor_1, ii, j, k, and nclr.
Referenced by xcall_().
 {
     /* Initialized data */
     static integer icldm = 100;
     static logical first = TRUE_;
     /* System generated locals */
     integer i__1;
     static doublereal equiv_0[1];
     /* Local variables */
     static integer i__, j, k, ii;
 #define clr (equiv_0)
     extern integer bcdf_(char *, ftnlen);
 #define nclr ((integer *)equiv_0)
     static integer nomo, norm, ityp;
     extern /* Subroutine */ int apt299_(integer *, integer *, integer *,
         integer *);
     static integer clwrd;
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
     static integer start, iclidx, nptvct[18]    /* was [2][9] */;
 /*   PURPOSE: TO CONTROL AND STORE CLDAT PARAMETERS AND INDICATORS. */
 /*     ICLTAB   (1,X)  INDEX OF THE CLDAT SECTION. */
 /*     ICLTAB   (2,X)  NUMBER OF POINTS IN THE CLDAT SECTION. */
 /*     ICLTAB   (3,X)  FORM OF STORAGE ON EXFILE (TP,TA,TV,...). */
 /*     ICLTAB   (4,X)  FIRST EXFILE BLOCK  OF THE CLDAT SECTION. */
 /*     ICLTAB   (5,X)  FIRST EXFILE RECORD OF THE CLDAT SECTION. */
 /*     CLDFG           FLAG TRUE = A CLDAT-SECTION IS OPENED, COUNTING */
 /*                     OF THE POINTS IN ATAPE. */
 /*     ICLCNT          POINTER TO THE LAST ICLTAB ENTRY. */
 /*     ICLINE          ICLTAB INDEX. */
 /*     ICLIDX          ICLTAB INDEX. */
 /*     ICLCOD = ICLTAB   (3,X)    ;   ICLBLK = ICLTAB   (4,X) */
 /*     ICLRCD = ICLTAB   (5,X) */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
     /* Parameter adjustments */
     --arg4;
     --arg3;
     --arg2;
     --arg1;
     /* Function Body */
     if (first) {
     start = bcdf_("STAR", (ftnlen)4);
     clwrd = bcdf_("CLDA", (ftnlen)4);
     norm = bcdf_("NORM", (ftnlen)4);
     nomo = bcdf_("NOMO", (ftnlen)4);
     first = FALSE_;
     }
     for (i__ = 1; i__ <= 9; ++i__) {
     nptvct[(i__ << 1) - 2] = bcdf_(chcldt_1.pntvct + (i__ - 1 << 3), (
         ftnlen)4);
 /* L2: */
     }
     if (arg2[1] != clwrd) {
     goto L10;
     }
     ityp = arg4[1];
     if (ityp == norm) {
     goto L75;
     }
     if (ityp != start && ityp != nomo) {
     goto L5;
     }
     goto L100;
 /* CLDAT/TP,TA,TV,...ETC. */
 L5:
     cldt_1.iclcod = 1;
     j = ityp;
     goto L85;
 L10:
     if (arg1[1] != 1) {
     goto L80;
     }
     nclr[0] = arg2[1];
     nclr[1] = arg2[2];
     j = arg4[1];
     if (ityp != start) {
     goto L50;
     }
 /* CLDAT/START,IDX,......... */
     iclidx = (integer) (*clr);
     i__1 = cldt_1.iclcnt;
     for (cldt_1.icline = 1; cldt_1.icline <= i__1; ++cldt_1.icline) {
     if (cldt_1.icltab[cldt_1.icline * 5 - 5] != iclidx) {
         goto L20;
     }
 /* WARNING DIAGNOSTIC 94 */
 /* MULTIPLE DEFINED CLDAT-SECTION. FORMER SECTION DELETED. */
     error_(&c__94, "CLDAT   ", (ftnlen)8);
     goto L40;
 L20:
     ;
     }
 /* IS ICLTAB FILLED ? */
     if (cldt_1.iclcnt < icldm) {
     goto L30;
     }
 /* ERROR DIAGNOSTIC 95 */
 /* ARRAY ICLTAB FILLED. USE A FORMER DEFINED INDEX OR REDIMENSION ARRAY. */
     error_(&c__95, "CLDAT   ", (ftnlen)8);
     goto L100;
 L30:
     ++cldt_1.iclcnt;
     cldt_1.icline = cldt_1.iclcnt;
 L40:
     cldt_1.cldfg = TRUE_;
     cldt_1.iclcod = 1;
     cldt_1.icltab[cldt_1.icline * 5 - 5] = iclidx;
     cldt_1.icltab[cldt_1.icline * 5 - 4] = 0;
     cldt_1.icltab[cldt_1.icline * 5 - 3] = cldt_1.iclcod;
     cldt_1.icltab[cldt_1.icline * 5 - 2] = cldt_1.iclblk + 1;
     cldt_1.icltab[cldt_1.icline * 5 - 1] = cldt_1.iclrcd + 3;
     ifxcor_1.numcnt = 0;
     if (j == 0) {
     goto L100;
     }
     goto L85;
 /* CLDAT/NOMORE,IDX */
 L50:
     ii = (integer) (*clr);
 /* WARNING DIAGNOSTIC 94 */
 /* CLDAT INDEXES ARE DIFFERENT. FIRST INDEX REMAINS VALID. */
 /* L70: */
     if (ii != iclidx) {
     error_(&c__94, "CLDAT   ", (ftnlen)8);
     }
     cldt_1.icltab[cldt_1.icline * 5 - 4] += ifxcor_1.numcnt;
     cldt_1.cldfg = FALSE_;
 /* CLDAT/NORMAL */
 L75:
     cldt_1.iclcod = 0;
     goto L100;
 L80:
     if (cldt_1.iclcod == 0) {
     goto L100;
     }
     j = arg2[1];
 L85:
     k = arg4[1];
     for (ii = 1; ii <= 9; ++ii) {
     if (j != nptvct[(ii << 1) - 2] && k != nptvct[(ii << 1) - 2]) {
         goto L90;
     }
     if (cldt_1.iclcod % cldt_1.iptvec[ii - 1] != 0) {
         cldt_1.iclcod *= cldt_1.iptvec[ii - 1];
     }
     if (cldt_1.cldfg) {
         cldt_1.icltab[cldt_1.icline * 5 - 3] = cldt_1.iclcod;
     }
 L90:
     ;
     }
 /* OUTPUT CLDAT COMMAND ON EXFILE */
 L100:
     apt299_(&arg1[1], &arg2[1], &arg3[1], &arg4[1]);
     return 0;
 } /* cldat_ */
Variable Documentation
integer c__94 = 94 static
Definition at line 43 of file CLDAT.c.
Referenced by cldat_().
integer c__95 = 95 static
Definition at line 44 of file CLDAT.c.
Referenced by cldat_().
struct { ... } chcldt_
logical cldfg
Definition at line 28 of file CLDAT.c.
struct { ... } cldt_
integer i3dflg
Definition at line 18 of file CLDAT.c.
integer iaerr
Definition at line 18 of file CLDAT.c.
integer iautps
Definition at line 18 of file CLDAT.c.
integer ibegin
Definition at line 18 of file CLDAT.c.
integer ic
Definition at line 18 of file CLDAT.c.
integer icheck
Definition at line 18 of file CLDAT.c.
integer icl
Definition at line 18 of file CLDAT.c.
integer iclblk
Definition at line 29 of file CLDAT.c.
integer iclcnt
Definition at line 29 of file CLDAT.c.
integer iclcod
Definition at line 29 of file CLDAT.c.
integer icline
Definition at line 29 of file CLDAT.c.
integer iclrcd
Definition at line 29 of file CLDAT.c.
integer icltab[500]
Definition at line 29 of file CLDAT.c.
integer ics
Definition at line 18 of file CLDAT.c.
integer icscnt
Definition at line 18 of file CLDAT.c.
integer ictdef
Definition at line 18 of file CLDAT.c.
integer icut
Definition at line 18 of file CLDAT.c.
integer ids
Definition at line 18 of file CLDAT.c.
integer ier
Definition at line 18 of file CLDAT.c.
struct { ... } ifxcor_
integer igo
Definition at line 18 of file CLDAT.c.
integer igoto
Definition at line 18 of file CLDAT.c.
integer igoug
Definition at line 18 of file CLDAT.c.
integer igs
Definition at line 18 of file CLDAT.c.
integer inops
Definition at line 18 of file CLDAT.c.
integer ips
Definition at line 18 of file CLDAT.c.
integer ipsdef
Definition at line 18 of file CLDAT.c.
integer ipt1
Definition at line 18 of file CLDAT.c.
integer iptvec[9]
Definition at line 29 of file CLDAT.c.
integer is
Definition at line 18 of file CLDAT.c.
integer iseg
Definition at line 18 of file CLDAT.c.
integer iseqno
Definition at line 18 of file CLDAT.c.
integer isrch
Definition at line 18 of file CLDAT.c.
integer istrup
Definition at line 18 of file CLDAT.c.
integer it
Definition at line 18 of file CLDAT.c.
integer jbr
Definition at line 18 of file CLDAT.c.
integer jsw
Definition at line 18 of file CLDAT.c.
integer lsv
Definition at line 18 of file CLDAT.c.
integer lsv1
Definition at line 18 of file CLDAT.c.
integer mantax
Definition at line 18 of file CLDAT.c.
integer motmod
Definition at line 18 of file CLDAT.c.
integer msav
Definition at line 18 of file CLDAT.c.
integer mulout
Definition at line 18 of file CLDAT.c.
integer nmbseg
Definition at line 18 of file CLDAT.c.
integer nmpnts
Definition at line 18 of file CLDAT.c.
integer nrec
Definition at line 18 of file CLDAT.c.
integer numax
Definition at line 18 of file CLDAT.c.
integer numcnt
Definition at line 18 of file CLDAT.c.
integer nump
Definition at line 18 of file CLDAT.c.
integer numpt1
Definition at line 18 of file CLDAT.c.
integer numsfs
Definition at line 18 of file CLDAT.c.
integer numsur
Definition at line 18 of file CLDAT.c.
integer nw
Definition at line 18 of file CLDAT.c.
integer nwds
Definition at line 18 of file CLDAT.c.
char pntvct[72]
Definition at line 36 of file CLDAT.c.