My Project: CLPUT.c File Reference
CLPUT.c File Reference
#include "f2c.h"
Macros
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define ifxcor_1 ifxcor_
#define ibugg_1 ibugg_
#define symfil_1 symfil_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int clput_ (doublereal *atex, doublereal *atax, integer *mode)
Variables
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer ibug
integer ipcolc
integer ipcolm
} ibugg_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
static integer c__10 = 10
static integer c_n1 = -1
static integer c__0 = 0
static integer c__3 = 3
static integer c__1 = 1
static integer c_n3 = -3
Macro Definition Documentation
#define charct_1 charct_
Definition at line 30 of file CLPUT.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define fxcor_1 fxcor_
Definition at line 24 of file CLPUT.c.
Referenced by clput_().
#define ibugg_1 ibugg_
Definition at line 53 of file CLPUT.c.
Referenced by clput_().
#define ifxcor_1 ifxcor_
Definition at line 47 of file CLPUT.c.
Referenced by clput_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define symfil_1 symfil_
Definition at line 62 of file CLPUT.c.
Referenced by clput_().
#define tlldat_1 tlldat_
Definition at line 37 of file CLPUT.c.
Function Documentation
int clput_ (doublereal * atex, doublereal * atax, integer * mode)
Definition at line 75 of file CLPUT.c.
References atape_(), bad_(), bcdf_(), c__0, c__1, c__10, c__3, c_n1, c_n3, cprint_(), ewrite_(), first, fxcor_1, i__, ibugg_1, ifxcor_1, ir, kcldat, record_(), and symfil_1.
Referenced by cutreg_(), smil_(), and sspath_().
 {
     /* Initialized data */
     static integer kcldat[10] = { 0,0,1308622848,0,1308622848,2,1308622848,1,
         0,0 };
     static logical first = TRUE_;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, ir, nr;
     extern /* Subroutine */ int bad_();
     extern integer bcdf_(char *, ftnlen);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     extern /* Subroutine */ int atape_(void);
     static char badmsg[20];
     extern /* Subroutine */ int record_(integer *), ewrite_(integer *,
         integer *, integer *, integer *, integer *), cprint_(char *,
         ftnlen);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /* ...                SYSTEM I/O FILES */
     /* Parameter adjustments */
     --atax;
     --atex;
     /* Function Body */
     if (first) {
     kcldat[0] = bcdf_("CLDA", (ftnlen)4);
     kcldat[1] = bcdf_("TA  ", (ftnlen)4);
     kcldat[8] = bcdf_("GOTO", (ftnlen)4);
     kcldat[9] = bcdf_("    ", (ftnlen)4);
     first = FALSE_;
     }
     record_(&ifxcor_1.iseqno);
     if (*mode >= 0) {
     goto L100;
     }
     if (*mode < -1) {
     goto L999;
     }
 /* --OUTPUT HEADER FOR A RECORD OF CL DATA */
     kcldat[3] = ifxcor_1.iseqno;
     nr = 0;
     ewrite_(&symfil_1.exfile, &nr, kcldat, &c__10, &ir);
     goto L999;
 L100:
     ifxcor_1.icl = 0;
     if (*mode == 0) {
     ifxcor_1.icl = 2;
     }
     if (*mode == 1) {
     ifxcor_1.icl = 3;
     }
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.te[i__ - 1] = atex[i__];
     fxcor_1.ta[i__ - 1] = atax[i__];
 /* L110: */
     }
     atape_();
     goto L999;
 L999:
     if (ibugg_1.ibug != 11) {
     goto L1999;
     }
     bad_(&c_n1, &c__0, " ", &c__0, (ftnlen)1);
     s_copy(badmsg, " AFTER CLPUT", (ftnlen)20, (ftnlen)12);
     cprint_(badmsg, (ftnlen)20);
     bad_(&c_n1, &c__0, "MODE", mode, (ftnlen)4);
     bad_(&c__3, &c__1, "ATEX", &atex[1], (ftnlen)4);
     bad_(&c_n3, &c__1, "ATAX", &atax[1], (ftnlen)4);
 L1999:
     return 0;
 } /* clput_ */
Variable Documentation
doublereal alp
Definition at line 18 of file CLPUT.c.
doublereal ax4[3]
Definition at line 18 of file CLPUT.c.
integer axfile
Definition at line 56 of file CLPUT.c.
integer c__0 = 0 static
Definition at line 68 of file CLPUT.c.
Referenced by clput_().
integer c__1 = 1 static
Definition at line 70 of file CLPUT.c.
Referenced by clput_().
integer c__10 = 10 static
Definition at line 66 of file CLPUT.c.
Referenced by clput_().
integer c__3 = 3 static
Definition at line 69 of file CLPUT.c.
Referenced by clput_().
integer c_n1 = -1 static
Definition at line 67 of file CLPUT.c.
Referenced by clput_().
integer c_n3 = -3 static
Definition at line 71 of file CLPUT.c.
Referenced by clput_().
doublereal cagl
Definition at line 18 of file CLPUT.c.
struct { ... } charct_
integer clfil3
Definition at line 56 of file CLPUT.c.
integer clfile
Definition at line 56 of file CLPUT.c.
integer clfilp
Definition at line 56 of file CLPUT.c.
doublereal corrad[8]
Definition at line 33 of file CLPUT.c.
integer cpfile
Definition at line 56 of file CLPUT.c.
doublereal cutdat[7]
Definition at line 18 of file CLPUT.c.
doublereal dpmax
Definition at line 18 of file CLPUT.c.
integer elfil1
Definition at line 56 of file CLPUT.c.
integer elfil2
Definition at line 56 of file CLPUT.c.
integer elfil3
Definition at line 56 of file CLPUT.c.
integer elfil4
Definition at line 56 of file CLPUT.c.
integer elfile
Definition at line 56 of file CLPUT.c.
integer exfile
Definition at line 56 of file CLPUT.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 18 of file CLPUT.c.
doublereal hi
Definition at line 18 of file CLPUT.c.
integer i3dflg
Definition at line 40 of file CLPUT.c.
integer iaerr
Definition at line 40 of file CLPUT.c.
integer iautps
Definition at line 40 of file CLPUT.c.
integer ibegin
Definition at line 40 of file CLPUT.c.
integer ibug
Definition at line 50 of file CLPUT.c.
struct { ... } ibugg_
integer ic
Definition at line 40 of file CLPUT.c.
integer icheck
Definition at line 40 of file CLPUT.c.
integer icl
Definition at line 40 of file CLPUT.c.
integer ics
Definition at line 40 of file CLPUT.c.
integer icscnt
Definition at line 40 of file CLPUT.c.
integer ictdef
Definition at line 40 of file CLPUT.c.
integer icut
Definition at line 40 of file CLPUT.c.
integer ids
Definition at line 40 of file CLPUT.c.
integer ier
Definition at line 40 of file CLPUT.c.
struct { ... } ifxcor_
integer igo
Definition at line 40 of file CLPUT.c.
integer igoto
Definition at line 40 of file CLPUT.c.
integer igoug
Definition at line 40 of file CLPUT.c.
integer igs
Definition at line 40 of file CLPUT.c.
integer infile__
Definition at line 56 of file CLPUT.c.
integer inops
Definition at line 40 of file CLPUT.c.
integer ipcolc
Definition at line 50 of file CLPUT.c.
integer ipcolm
Definition at line 50 of file CLPUT.c.
integer ips
Definition at line 40 of file CLPUT.c.
integer ipsdef
Definition at line 40 of file CLPUT.c.
integer ipt1
Definition at line 40 of file CLPUT.c.
integer is
Definition at line 40 of file CLPUT.c.
integer iseg
Definition at line 40 of file CLPUT.c.
integer iseqno
Definition at line 40 of file CLPUT.c.
integer ispare[26]
Definition at line 56 of file CLPUT.c.
integer isrch
Definition at line 40 of file CLPUT.c.
integer istrup
Definition at line 40 of file CLPUT.c.
integer it
Definition at line 40 of file CLPUT.c.
integer jbr
Definition at line 40 of file CLPUT.c.
integer jsw
Definition at line 40 of file CLPUT.c.
integer ldafil
Definition at line 56 of file CLPUT.c.
integer libfil
Definition at line 56 of file CLPUT.c.
integer lsv
Definition at line 40 of file CLPUT.c.
integer lsv1
Definition at line 40 of file CLPUT.c.
integer mactxt
Definition at line 56 of file CLPUT.c.
integer mantax
Definition at line 40 of file CLPUT.c.
char modfer[6]
Definition at line 27 of file CLPUT.c.
integer motmod
Definition at line 40 of file CLPUT.c.
integer msav
Definition at line 40 of file CLPUT.c.
integer mulout
Definition at line 40 of file CLPUT.c.
integer nfil12
Definition at line 56 of file CLPUT.c.
integer nfil13
Definition at line 56 of file CLPUT.c.
integer nmbseg
Definition at line 40 of file CLPUT.c.
integer nmpnts
Definition at line 40 of file CLPUT.c.
integer nrec
Definition at line 40 of file CLPUT.c.
integer numax
Definition at line 40 of file CLPUT.c.
integer numcnt
Definition at line 40 of file CLPUT.c.
integer nump
Definition at line 40 of file CLPUT.c.
integer numpt1
Definition at line 40 of file CLPUT.c.
integer numsfs
Definition at line 40 of file CLPUT.c.
integer numsur
Definition at line 40 of file CLPUT.c.
integer nw
Definition at line 40 of file CLPUT.c.
integer nwds
Definition at line 40 of file CLPUT.c.
doublereal pmove[3]
Definition at line 18 of file CLPUT.c.
integer pnchfl
Definition at line 56 of file CLPUT.c.
integer pofile
Definition at line 56 of file CLPUT.c.
integer pxfile
Definition at line 56 of file CLPUT.c.
doublereal ra
Definition at line 18 of file CLPUT.c.
doublereal rc1
Definition at line 18 of file CLPUT.c.
doublereal ri[8]
Definition at line 33 of file CLPUT.c.
doublereal sagl
Definition at line 18 of file CLPUT.c.
doublereal strtno
Definition at line 18 of file CLPUT.c.
doublereal surd
Definition at line 18 of file CLPUT.c.
struct { ... } symfil_
doublereal ta[3]
Definition at line 18 of file CLPUT.c.
doublereal tak[3]
Definition at line 18 of file CLPUT.c.
doublereal tal[3]
Definition at line 18 of file CLPUT.c.
doublereal tanhi[8]
Definition at line 33 of file CLPUT.c.
doublereal tanlo[8]
Definition at line 33 of file CLPUT.c.
doublereal tcont[9]
Definition at line 33 of file CLPUT.c.
doublereal te[3]
Definition at line 18 of file CLPUT.c.
doublereal tek[3]
Definition at line 18 of file CLPUT.c.
doublereal tel[3]
Definition at line 18 of file CLPUT.c.
doublereal tem[10]
Definition at line 18 of file CLPUT.c.
doublereal temp[24]
Definition at line 18 of file CLPUT.c.
doublereal ti[3]
Definition at line 18 of file CLPUT.c.
integer tifile
Definition at line 56 of file CLPUT.c.
doublereal tik[3]
Definition at line 18 of file CLPUT.c.
doublereal til[3]
Definition at line 18 of file CLPUT.c.
doublereal tlhit
Definition at line 18 of file CLPUT.c.
doublereal tlhite[8]
Definition at line 33 of file CLPUT.c.
doublereal tlinc[9]
Definition at line 33 of file CLPUT.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 18 of file CLPUT.c.
doublereal umax[8]
Definition at line 33 of file CLPUT.c.
integer vlfile
Definition at line 56 of file CLPUT.c.
doublereal vtem
Definition at line 18 of file CLPUT.c.
integer xcan
Definition at line 56 of file CLPUT.c.
integer xnum
Definition at line 56 of file CLPUT.c.