My Project: COMPRS.c File Reference
COMPRS.c File Reference
#include "f2c.h"
Macros
#define prt_1 prt_
#define assemb ((logical *)&prt_1 + 3)
#define interp ((logical *)&prt_1 + 2)
Functions
int comprs_ (void)
Variables
struct {
integer prt [7]
} prt_
Macro Definition Documentation
#define assemb ((logical *)&prt_1 + 3)
#define interp ((logical *)&prt_1 + 2)
#define prt_1 prt_
Definition at line 21 of file COMPRS.c.
Function Documentation
int comprs_ (void)
Definition at line 35 of file COMPRS.c.
References icmprs_(), and prolog_().
Referenced by rlslin_().
 {
     /* Initialized data */
     static logical prosw = TRUE_;
     /* Local variables */
 #define assemb ((logical *)&prt_1 + 3)
     extern /* Subroutine */ int icmprs_(void);
 #define interp ((logical *)&prt_1 + 2)
     extern /* Subroutine */ int prolog_(void);
 /*       14.    I. L. LIST OPTION FLAGS */
 /* INTERP:      NORMALLY TRUE,INDICATING INTERPRETIVE APPROACH DEFAULT */
 /* ASSEMB:      SET TRUE INDICATES ASSEMBLY APPROACH (CONTRL/ASMBLE) */
 /* * */
 /* ** */
     if (prosw) {
     goto L100;
     }
 /*  10 IF(ASSEMB)CALL ACMPRS */
 /*     IF(INTERP)CALL ICMPRS */
 L10:
     icmprs_();
     return 0;
 L100:
     prosw = FALSE_;
     prolog_();
     goto L10;
 } /* comprs_ */
Variable Documentation
integer prt[7]
Definition at line 18 of file COMPRS.c.
struct { ... } prt_