My Project: COMP3D.c File Reference
COMP3D.c File Reference
#include "f2c.h"
Macros
#define ifxcor_1 ifxcor_
#define knumbr_1 knumbr_
#define rmflgs_1 rmflgs_
Functions
int comp3d_ (void)
int ndtest_ (void)
int gougck_ (doublereal *donoff)
Variables
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
logical lgchk
logical lintck
logical lavctl
logical lvaxis
} rmflgs_
static integer c__0 = 0
static integer c__1 = 1
static integer c__2 = 2
Macro Definition Documentation
#define ifxcor_1 ifxcor_
Definition at line 25 of file COMP3D.c.
Referenced by comp3d_(), gougck_(), and ndtest_().
#define knumbr_1 knumbr_
Definition at line 33 of file COMP3D.c.
#define rmflgs_1 rmflgs_
Definition at line 39 of file COMP3D.c.
Referenced by gougck_().
Function Documentation
int comp3d_ (void)
Definition at line 50 of file COMP3D.c.
References apt299_(), bcdf_(), c__0, and ifxcor_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static char pp1[8] = "3DCALC  ";
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt299_(integer *, integer *, integer *,
         integer *);
     static integer ppword[2];
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     ifxcor_1.i3dflg = 1;
     ppword[0] = bcdf_(pp1, (ftnlen)4);
     ppword[1] = bcdf_(pp1 + 4, (ftnlen)4);
     apt299_(&c__0, ppword, &c__0, &c__0);
     return 0;
 } /* comp3d_ */
int gougck_ (doublereal * donoff)
Definition at line 142 of file COMP3D.c.
References apt299_(), bcdf_(), c__1, c__2, holfrm_(), ifxcor_1, rmflgs_1, and test.
Referenced by xcall_().
 {
     /* Initialized data */
     static char pp3[8] = "GOUGCK  ";
     static char don[2] = "ON";
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer nwd;
     extern integer bcdf_(char *, ftnlen);
     static char test[2];
     extern /* Subroutine */ int apt299_(), holfrm_(doublereal *, char *,
         integer *, integer *, integer *, ftnlen);
     static integer ppword[2];
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* .... NEW REGIONAL MILLING FLAGS */
 /*     LGCHK  - GOUGE CHECK FLAG */
 /*     LINTCK - INTERFERENCE CHECKING FLAG */
 /*     LAVCTL - AVOIDANCE CONTROL FLAG */
 /*     LVAXIS - VARIABLE TOOL AXIS FLAG */
     holfrm_(donoff, test, &c__1, &c__2, &nwd, (ftnlen)2);
     if (s_cmp(test, don, (ftnlen)2, (ftnlen)2) == 0) {
     ifxcor_1.igoug = 1;
     rmflgs_1.lgchk = TRUE_;
     } else {
     ifxcor_1.igoug = 0;
     rmflgs_1.lgchk = FALSE_;
     }
     ppword[0] = bcdf_(pp3, (ftnlen)4);
     ppword[1] = bcdf_(pp3 + 4, (ftnlen)4);
     apt299_(&c__1, ppword, &c__2, donoff);
     return 0;
 } /* gougck_ */
int ndtest_ (void)
Definition at line 96 of file COMP3D.c.
References apt299_(), bcdf_(), c__0, and ifxcor_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static char pp2[8] = "2DCALC  ";
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt299_(integer *, integer *, integer *,
         integer *);
     static integer ppword[2];
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     ifxcor_1.i3dflg = 0;
     ppword[0] = bcdf_(pp2, (ftnlen)4);
     ppword[1] = bcdf_(pp2 + 4, (ftnlen)4);
     apt299_(&c__0, ppword, &c__0, &c__0);
     return 0;
 } /* ndtest_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 43 of file COMP3D.c.
Referenced by comp3d_(), and ndtest_().
integer c__1 = 1 static
Definition at line 44 of file COMP3D.c.
Referenced by gougck_().
integer c__2 = 2 static
Definition at line 45 of file COMP3D.c.
Referenced by gougck_().
integer i3dflg
Definition at line 18 of file COMP3D.c.
integer iaerr
Definition at line 18 of file COMP3D.c.
integer iautps
Definition at line 18 of file COMP3D.c.
integer ibegin
Definition at line 18 of file COMP3D.c.
integer ic
Definition at line 18 of file COMP3D.c.
integer icheck
Definition at line 18 of file COMP3D.c.
integer icl
Definition at line 18 of file COMP3D.c.
integer ics
Definition at line 18 of file COMP3D.c.
integer icscnt
Definition at line 18 of file COMP3D.c.
integer ictdef
Definition at line 18 of file COMP3D.c.
integer icut
Definition at line 18 of file COMP3D.c.
integer ids
Definition at line 18 of file COMP3D.c.
integer ier
Definition at line 18 of file COMP3D.c.
struct { ... } ifxcor_
integer igo
Definition at line 18 of file COMP3D.c.
integer igoto
Definition at line 18 of file COMP3D.c.
integer igoug
Definition at line 18 of file COMP3D.c.
integer igs
Definition at line 18 of file COMP3D.c.
integer inops
Definition at line 18 of file COMP3D.c.
integer ips
Definition at line 18 of file COMP3D.c.
integer ipsdef
Definition at line 18 of file COMP3D.c.
integer ipt1
Definition at line 18 of file COMP3D.c.
integer is
Definition at line 18 of file COMP3D.c.
integer iseg
Definition at line 18 of file COMP3D.c.
integer iseqno
Definition at line 18 of file COMP3D.c.
integer isrch
Definition at line 18 of file COMP3D.c.
integer istrup
Definition at line 18 of file COMP3D.c.
integer it
Definition at line 18 of file COMP3D.c.
integer jbr
Definition at line 18 of file COMP3D.c.
integer jsw
Definition at line 18 of file COMP3D.c.
integer k0
Definition at line 28 of file COMP3D.c.
integer k1
Definition at line 28 of file COMP3D.c.
integer k10
Definition at line 28 of file COMP3D.c.
integer k1013
Definition at line 28 of file COMP3D.c.
integer k12
Definition at line 28 of file COMP3D.c.
integer k13
Definition at line 28 of file COMP3D.c.
integer k15
Definition at line 28 of file COMP3D.c.
integer k16
Definition at line 28 of file COMP3D.c.
integer k18
Definition at line 28 of file COMP3D.c.
integer k19
Definition at line 28 of file COMP3D.c.
integer k1e4
Definition at line 28 of file COMP3D.c.
integer k1e6
Definition at line 28 of file COMP3D.c.
integer k2
Definition at line 28 of file COMP3D.c.
integer k23
Definition at line 28 of file COMP3D.c.
integer k24
Definition at line 28 of file COMP3D.c.
integer k25
Definition at line 28 of file COMP3D.c.
integer k26
Definition at line 28 of file COMP3D.c.
integer k27
Definition at line 28 of file COMP3D.c.
integer k29
Definition at line 28 of file COMP3D.c.
integer k3
Definition at line 28 of file COMP3D.c.
integer k30
Definition at line 28 of file COMP3D.c.
integer k31
Definition at line 28 of file COMP3D.c.
integer k32
Definition at line 28 of file COMP3D.c.
integer k33
Definition at line 28 of file COMP3D.c.
integer k34
Definition at line 28 of file COMP3D.c.
integer k4
Definition at line 28 of file COMP3D.c.
integer k44
Definition at line 28 of file COMP3D.c.
integer k45
Definition at line 28 of file COMP3D.c.
integer k46
Definition at line 28 of file COMP3D.c.
integer k47
Definition at line 28 of file COMP3D.c.
integer k48
Definition at line 28 of file COMP3D.c.
integer k5
Definition at line 28 of file COMP3D.c.
integer k50
Definition at line 28 of file COMP3D.c.
integer k51
Definition at line 28 of file COMP3D.c.
integer k52
Definition at line 28 of file COMP3D.c.
integer k6
Definition at line 28 of file COMP3D.c.
integer k7
Definition at line 28 of file COMP3D.c.
integer k8
Definition at line 28 of file COMP3D.c.
integer k9
Definition at line 28 of file COMP3D.c.
integer km1
Definition at line 28 of file COMP3D.c.
struct { ... } knumbr_
logical lavctl
Definition at line 36 of file COMP3D.c.
logical lgchk
Definition at line 36 of file COMP3D.c.
logical lintck
Definition at line 36 of file COMP3D.c.
integer lsv
Definition at line 18 of file COMP3D.c.
integer lsv1
Definition at line 18 of file COMP3D.c.
logical lvaxis
Definition at line 36 of file COMP3D.c.
integer mantax
Definition at line 18 of file COMP3D.c.
integer motmod
Definition at line 18 of file COMP3D.c.
integer msav
Definition at line 18 of file COMP3D.c.
integer mulout
Definition at line 18 of file COMP3D.c.
integer nmbseg
Definition at line 18 of file COMP3D.c.
integer nmpnts
Definition at line 18 of file COMP3D.c.
integer nrec
Definition at line 18 of file COMP3D.c.
integer numax
Definition at line 18 of file COMP3D.c.
integer numcnt
Definition at line 18 of file COMP3D.c.
integer nump
Definition at line 18 of file COMP3D.c.
integer numpt1
Definition at line 18 of file COMP3D.c.
integer numsfs
Definition at line 18 of file COMP3D.c.
integer numsur
Definition at line 18 of file COMP3D.c.
integer nw
Definition at line 18 of file COMP3D.c.
integer nwds
Definition at line 18 of file COMP3D.c.
struct { ... } rmflgs_