My Project: CONCAT.c File Reference
CONCAT.c File Reference
#include "f2c.h"
Functions
int concat_ (char *chr, char *bcd, ftnlen chr_len, ftnlen bcd_len)
Variables
static integer c__1 = 1
Function Documentation
int concat_ (char * chr, char * bcd, ftnlen chr_len, ftnlen bcd_len)
Definition at line 21 of file CONCAT.c.
References c__1, chr, and k.
Referenced by goloft_(), isscod_(), lcanon_(), recog_(), ssdef_(), and tssmil_().
 {
     /* System generated locals */
     icilist ici__1;
     /* Builtin functions */
     integer s_rsfi(icilist *), do_fio(integer *, char *, ftnlen), e_rsfi(void)
         , s_wsfi(icilist *), e_wsfi(void);
     /* Local variables */
     static integer k, nchr;
 /* .....INSERT A SINGLE CHARACTER, BCD, INTO NEXT AVAILABLE POSITION */
 /* .....IN STRING OF CHARACTERS, CHR */
 /* .....THE NUMBER OF CHARACTERS IN THE STRING IS HELD IN THE FIRST 3 CHAR */
 /* .....LOCATIONS OF CHR */
     ici__1.icierr = 0;
     ici__1.iciend = 0;
     ici__1.icirnum = 1;
     ici__1.icirlen = chr_len;
     ici__1.iciunit = chr;
     ici__1.icifmt = "(I3)";
     s_rsfi(&ici__1);
     do_fio(&c__1, (char *)&nchr, (ftnlen)sizeof(integer));
     e_rsfi();
     ++nchr;
     ici__1.icierr = 0;
     ici__1.icirnum = 1;
     ici__1.icirlen = 3;
     ici__1.iciunit = chr;
     ici__1.icifmt = "(I3)";
     s_wsfi(&ici__1);
     do_fio(&c__1, (char *)&nchr, (ftnlen)sizeof(integer));
     e_wsfi();
     k = nchr + 3;
     *(unsigned char *)&chr[k - 1] = *(unsigned char *)bcd;
     return 0;
 } /* concat_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 17 of file CONCAT.c.
Referenced by concat_().