My Project: CPLAN.c File Reference
CPLAN.c File Reference
#include "f2c.h"
Macros
#define dshar4_1 dshar4_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define addcom_1 addcom_
#define _BLNK__1 _BLNK__
#define can ((doublereal *)&_BLNK__1 + 40)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define canon ((doublereal *)&_BLNK__1)
#define elmax ((doublereal *)&addcom_1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define kdynfl ((integer *)&addcom_1 + 48)
Functions
int cplan_ (void)
Variables
struct {
doublereal a
doublereal b
doublereal c__
doublereal cendis
doublereal cmove [3]
doublereal com1
doublereal com4
doublereal dir [3]
doublereal dp
doublereal dpe
doublereal dpcnt
doublereal dpi
doublereal dpl
doublereal dp1
doublereal d1
doublereal d2a
doublereal flipck
doublereal fwd [3]
doublereal ogle [3]
doublereal p1 [3]
doublereal p2 [3]
doublereal rdrn
doublereal refpnt [3]
doublereal tangl
doublereal tes [3]
doublereal tew [3]
doublereal uvec [3]
doublereal u2 [3]
doublereal v [3]
doublereal vl
doublereal zl
doublereal zlnorm [3]
doublereal zlpnt [3]
doublereal zl1
doublereal param [6]
doublereal r__ [6]
doublereal savpar [4]
doublereal seg [9]
doublereal slope
doublereal sqroot
doublereal unn
doublereal upp
doublereal vint
doublereal vnn
doublereal vpp
} dshar4_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
doublereal addcom [25]
} addcom_
struct {
doublereal com [36000]
} _BLNK__
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 135 of file CPLAN.c.
#define addcom_1 addcom_
Definition at line 129 of file CPLAN.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
Referenced by cplan_().
#define charct_1 charct_
Definition at line 40 of file CPLAN.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dshar4_1 dshar4_
Definition at line 25 of file CPLAN.c.
#define elmax ((doublereal *)&addcom_1)
#define fxcor_1 fxcor_
Definition at line 34 of file CPLAN.c.
Referenced by cplan_().
#define ifxcor_1 ifxcor_
Definition at line 107 of file CPLAN.c.
Referenced by cplan_().
#define ishr18_1 ishr18_
Definition at line 115 of file CPLAN.c.
Referenced by cplan_().
#define isv1_1 isv1_
Definition at line 97 of file CPLAN.c.
Referenced by cplan_().
#define isv_1 isv_
Definition at line 90 of file CPLAN.c.
Referenced by cplan_().
#define kdynfl ((integer *)&addcom_1 + 48)
Referenced by cplan_().
#define knumbr_1 knumbr_
Definition at line 123 of file CPLAN.c.
Referenced by cplan_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define sv1_1 sv1_
Definition at line 73 of file CPLAN.c.
Referenced by cplan_().
#define sv_1 sv_
Definition at line 64 of file CPLAN.c.
Referenced by cplan_().
#define tlldat_1 tlldat_
Definition at line 47 of file CPLAN.c.
#define znumbr_1 znumbr_
Definition at line 81 of file CPLAN.c.
Referenced by cplan_().
Function Documentation
int cplan_ (void)
Definition at line 142 of file CPLAN.c.
References apt238_(), canon, ccurv_(), cross_(), ddst_(), fxcor_1, ifxcor_1, ishr18_1, isv1_1, isv_1, kdynfl, knumbr_1, sv1_1, sv_1, temp1, tlnorm_(), u1comp_(), vnorm_(), and znumbr_1.
Referenced by centr_(), and check_().
 {
     /* Initialized data */
     static doublereal zlit1 = .05;
     /* System generated locals */
     integer i__1;
     doublereal d__1;
     /* Builtin functions */
     double d_sign(doublereal *, doublereal *);
     /* Local variables */
     static doublereal tv;
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer itt, iss, its;
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static integer isis;
     extern /* Subroutine */ int ddst_(void), apt238_(integer *);
     static doublereal temp1;
 #define canon ((doublereal *)&_BLNK__1)
 #define elmax ((doublereal *)&addcom_1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int cross_(doublereal *, doublereal *, doublereal
         *), vnorm_(doublereal *, doublereal *), ccurv_(integer *,
         doublereal *, doublereal *, doublereal *), u1comp_(void);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
 #define kdynfl ((integer *)&addcom_1 + 48)
     extern /* Subroutine */ int tlnorm_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
     fxcor_1.temp[19] = sv_1.rc[(560 + (0 + (ifxcor_1.is - 1 << 3)) - 560) / 8]
         ;
 /*                  TEST IF CYLINDER IT SURF,PLANE IS SURF */
     if (isv_1.ipl[ifxcor_1.is - 1] != 0) {
     goto L10;
     } else {
     goto L1010;
     }
 L10:
     if (isv1_1.ifl4[ifxcor_1.is - 1] != 0) {
     goto L20;
     } else {
     goto L30;
     }
 L20:
     ifxcor_1.it = ifxcor_1.ips;
     goto L50;
 L30:
     ifxcor_1.it = ifxcor_1.ids;
 L50:
     goto L3000;
 L1010:
     cross_(&sv_1.sn[ifxcor_1.is * 3 - 3], &sv_1.snk[ifxcor_1.is * 3 - 3],
         fxcor_1.temp);
 /* L1020: */
     vnorm_(fxcor_1.temp, fxcor_1.temp);
 /* L1030: */
     if (ifxcor_1.ier != 0) {
     goto L1040;
     } else {
     goto L1050;
     }
 L1050:
     temp1 = fxcor_1.temp[0] * (sv_1.sp[ifxcor_1.is * 3 - 3] - sv_1.spk[
         ifxcor_1.is * 3 - 3]) + fxcor_1.temp[1] * (sv_1.sp[ifxcor_1.is *
         3 - 2] - sv_1.spk[ifxcor_1.is * 3 - 2]) + fxcor_1.temp[2] * (
         sv_1.sp[ifxcor_1.is * 3 - 1] - sv_1.spk[ifxcor_1.is * 3 - 1]);
 /* L1060: */
     fxcor_1.tem[0] = sv_1.spk[ifxcor_1.is * 3 - 3] + temp1 * fxcor_1.temp[0];
     fxcor_1.tem[1] = sv_1.spk[ifxcor_1.is * 3 - 2] + temp1 * fxcor_1.temp[1];
     fxcor_1.tem[2] = sv_1.spk[ifxcor_1.is * 3 - 1] + temp1 * fxcor_1.temp[2];
 /* L1090: */
     ccurv_(&ifxcor_1.is, &sv_1.sp[ifxcor_1.is * 3 - 3], fxcor_1.tem, &sv_1.tn[
         ifxcor_1.is * 3 - 3]);
 L1120:
     if (isv1_1.ifl4[ifxcor_1.is - 1] != 0) {
     goto L1130;
     } else {
     goto L1140;
     }
 L1130:
     ifxcor_1.it = ifxcor_1.ips;
     itt = ifxcor_1.ids;
     goto L1150;
 L1040:
     sv_1.rc[ifxcor_1.is - 1] = fxcor_1.rc1 * d_sign(&znumbr_1.z1, &sv_1.rc[
         ifxcor_1.is - 1]);
     goto L1120;
 L1140:
     ifxcor_1.it = ifxcor_1.ids;
     itt = ifxcor_1.ips;
 L1150:
     if ((d__1 = sv_1.sp[ifxcor_1.it * 3 - 1] - sv_1.spk[ifxcor_1.it * 3 - 1],
         abs(d__1)) - znumbr_1.z1em3 >= 0.) {
     goto L1;
     } else {
     goto L2;
     }
 L2:
     fxcor_1.tem[0] = fxcor_1.ti[0];
     fxcor_1.tem[1] = fxcor_1.ti[1];
     fxcor_1.tem[2] = fxcor_1.ti[2];
     goto L5;
 L1:
     cross_(&sv_1.sn[ifxcor_1.it * 3 - 3], &sv_1.sn[itt * 3 - 3], fxcor_1.tem);
     vnorm_(fxcor_1.tem, fxcor_1.tem);
     if (ifxcor_1.ier != 0) {
     goto L2;
     } else {
     goto L3;
     }
 L3:
     if (fxcor_1.ti[0] * fxcor_1.tem[0] + fxcor_1.ti[1] * fxcor_1.tem[1] +
         fxcor_1.ti[2] * fxcor_1.tem[2] >= 0.) {
     goto L5;
     } else {
     goto L4;
     }
 L4:
     fxcor_1.tem[0] = -fxcor_1.tem[0];
     fxcor_1.tem[1] = -fxcor_1.tem[1];
     fxcor_1.tem[2] = -fxcor_1.tem[2];
 L5:
     isis = ifxcor_1.is;
     ifxcor_1.is = ifxcor_1.it;
     fxcor_1.temp[3] = sv_1.s[ifxcor_1.is - 1];
     fxcor_1.temp[0] = sv_1.tp[ifxcor_1.is * 3 - 3];
     fxcor_1.temp[1] = sv_1.tp[ifxcor_1.is * 3 - 2];
     fxcor_1.temp[2] = sv_1.tp[ifxcor_1.is * 3 - 1];
     sv_1.tp[ifxcor_1.is * 3 - 3] -= zlit1 * fxcor_1.tem[0];
     sv_1.tp[ifxcor_1.is * 3 - 2] -= zlit1 * fxcor_1.tem[1];
     sv_1.tp[ifxcor_1.is * 3 - 1] -= zlit1 * fxcor_1.tem[2];
     ddst_();
     fxcor_1.tem[0] = sv_1.tp[ifxcor_1.is * 3 - 3] + sv_1.s[ifxcor_1.is - 1] *
         sv_1.tn[ifxcor_1.is * 3 - 3];
     fxcor_1.tem[1] = sv_1.tp[ifxcor_1.is * 3 - 2] + sv_1.s[ifxcor_1.is - 1] *
         sv_1.tn[ifxcor_1.is * 3 - 2];
     fxcor_1.tem[2] = sv_1.tp[ifxcor_1.is * 3 - 1] + sv_1.s[ifxcor_1.is - 1] *
         sv_1.tn[ifxcor_1.is * 3 - 1];
     sv_1.tp[ifxcor_1.is * 3 - 3] = fxcor_1.temp[0];
     sv_1.tp[ifxcor_1.is * 3 - 2] = fxcor_1.temp[1];
     sv_1.tp[ifxcor_1.is * 3 - 1] = fxcor_1.temp[2];
     sv_1.s[ifxcor_1.is - 1] = fxcor_1.temp[3];
     ifxcor_1.is = isis;
 /* L1200: */
     sv1_1.plncs[ifxcor_1.is - 1] = sv_1.tn[ifxcor_1.it * 3 - 3] * sv_1.tn[
         ifxcor_1.is * 3 - 3] + sv_1.tn[ifxcor_1.it * 3 - 2] * sv_1.tn[
         ifxcor_1.is * 3 - 2] + sv_1.tn[ifxcor_1.it * 3 - 1] * sv_1.tn[
         ifxcor_1.is * 3 - 1];
 /* L1210: */
     if (sv_1.eps2[ifxcor_1.is - 1] - (d__1 = sv1_1.plncs[ifxcor_1.is - 1],
         abs(d__1)) >= 0.) {
     goto L1240;
     } else {
     goto L1220;
     }
 L1220:
     if (sv1_1.cplfl[ifxcor_1.is - 1] != 0.) {
     goto L1250;
     } else {
     goto L1230;
     }
 L1230:
     sv1_1.dplan[ifxcor_1.is * 3 - 3] = sv_1.tn[itt * 3 - 3];
     sv1_1.dplan[ifxcor_1.is * 3 - 2] = sv_1.tn[itt * 3 - 2];
     sv1_1.dplan[ifxcor_1.is * 3 - 1] = sv_1.tn[itt * 3 - 1];
     goto L1250;
 L1240:
     cross_(&sv_1.tn[ifxcor_1.is * 3 - 3], &sv_1.tn[ifxcor_1.it * 3 - 3], &
         sv1_1.dplan[ifxcor_1.is * 3 - 3]);
 L1250:
     if (isv_1.ipl[ifxcor_1.it - 1] != 0) {
     goto L1600;
     } else {
     goto L1260;
     }
 /*        USE RC1   FOR PROPER UNITS/ IMPLEMENTATION */
 L1600:
     if ((d__1 = sv_1.rc[ifxcor_1.is - 1], abs(d__1)) - fxcor_1.rc1 >= 0.) {
     goto L1620;
     } else {
     goto L1610;
     }
 L1610:
     fxcor_1.temp[0] = sv_1.tn[ifxcor_1.it * 3 - 3];
     fxcor_1.temp[1] = sv_1.tn[ifxcor_1.it * 3 - 2];
     fxcor_1.temp[2] = sv_1.tn[ifxcor_1.it * 3 - 1];
     goto L1380;
 L1620:
     sv1_1.cptst[ifxcor_1.is - 1] = -znumbr_1.z1;
     sv_1.plnd[ifxcor_1.is - 1] = sv_1.s[ifxcor_1.is - 1];
     sv1_1.cplfl[ifxcor_1.is - 1] = -znumbr_1.z1;
     sv_1.plnv[ifxcor_1.is * 3 - 3] = sv_1.tn[ifxcor_1.is * 3 - 3];
     sv_1.plnv[ifxcor_1.is * 3 - 2] = sv_1.tn[ifxcor_1.is * 3 - 2];
     sv_1.plnv[ifxcor_1.is * 3 - 1] = sv_1.tn[ifxcor_1.is * 3 - 1];
 L9998:
     ishr18_1.jcpr = 0;
 L9999:
     sv_1.rc[ifxcor_1.is - 1] = fxcor_1.temp[19];
     if (*kdynfl != knumbr_1.k0) {
     apt238_(&knumbr_1.k31);
     }
     return 0;
 L1260:
     ccurv_(&ifxcor_1.it, &sv_1.sp[ifxcor_1.it * 3 - 3], fxcor_1.tem, &sv_1.sn[
         ifxcor_1.it * 3 - 3]);
     if (*kdynfl != knumbr_1.k0) {
     apt238_(&knumbr_1.k34);
     }
 /* L1310: */
     if ((d__1 = sv_1.rc[ifxcor_1.it - 1], abs(d__1)) - fxcor_1.rc1 >= 0.) {
     goto L1600;
     } else {
     goto L1320;
     }
 L1320:
     if (isv_1.ipl[ifxcor_1.is - 1] != 0) {
     goto L1340;
     } else {
     goto L1330;
     }
 L1340:
     sv_1.cc[ifxcor_1.is * 3 - 3] = sv_1.cc[ifxcor_1.it * 3 - 3];
     sv_1.cc[ifxcor_1.is * 3 - 2] = sv_1.cc[ifxcor_1.it * 3 - 2];
     sv_1.cc[ifxcor_1.is * 3 - 1] = sv_1.cc[ifxcor_1.it * 3 - 1];
     fxcor_1.temp[0] = sv_1.tn[ifxcor_1.is * 3 - 3];
     fxcor_1.temp[1] = sv_1.tn[ifxcor_1.is * 3 - 2];
     fxcor_1.temp[2] = sv_1.tn[ifxcor_1.is * 3 - 1];
     goto L1380;
 L1330:
     if ((d__1 = sv_1.rc[ifxcor_1.is - 1], abs(d__1)) - fxcor_1.rc1 >= 0.) {
     goto L1340;
     } else {
     goto L1370;
     }
 L1370:
     fxcor_1.temp[0] = sv_1.cc[ifxcor_1.it * 3 - 3] - sv_1.cc[ifxcor_1.is * 3
         - 3];
     fxcor_1.temp[1] = sv_1.cc[ifxcor_1.it * 3 - 2] - sv_1.cc[ifxcor_1.is * 3
         - 2];
     fxcor_1.temp[2] = sv_1.cc[ifxcor_1.it * 3 - 1] - sv_1.cc[ifxcor_1.is * 3
         - 1];
     vnorm_(fxcor_1.temp, fxcor_1.temp);
     if (ifxcor_1.ier <= 0) {
     goto L1380;
     } else {
     goto L1340;
     }
 L1380:
     cross_(fxcor_1.temp, &sv1_1.dplan[ifxcor_1.is * 3 - 3], &sv_1.plnv[
         ifxcor_1.is * 3 - 3]);
     vnorm_(&sv_1.plnv[ifxcor_1.is * 3 - 3], &sv_1.plnv[ifxcor_1.is * 3 - 3]);
 /* L1390: */
     if (ifxcor_1.ier != 0) {
     goto L1400;
     } else {
     goto L1410;
     }
 L1400:
     ishr18_1.jcpr = 1;
     goto L9999;
 /*                  FIND EXTREME POINT ON TOOL IN DIRECTION OF TEMP */
 L1410:
     iss = ifxcor_1.is;
     ifxcor_1.igs = 1;
     ifxcor_1.is = ifxcor_1.igs;
     its = ifxcor_1.it;
 /*                  IF TAXIS NORM IT SURF, THEN TP = TE */
     if ((i__1 = ifxcor_1.mantax - 2) < 0) {
     goto L1460;
     } else if (i__1 == 0) {
     goto L1415;
     } else {
     goto L1417;
     }
 L1415:
     if (ifxcor_1.it - ifxcor_1.ips != 0) {
     goto L1460;
     } else {
     goto L1418;
     }
 L1417:
     if (ifxcor_1.it - ifxcor_1.ids != 0) {
     goto L1460;
     } else {
     goto L1418;
     }
 L1418:
     sv_1.tp[ifxcor_1.is * 3 - 3] = fxcor_1.te[0];
     sv_1.tp[ifxcor_1.is * 3 - 2] = fxcor_1.te[1];
     sv_1.tp[ifxcor_1.is * 3 - 1] = fxcor_1.te[2];
     goto L1470;
 L1460:
     tv = fxcor_1.temp[0] * sv_1.tn[ifxcor_1.it * 3 - 3] + fxcor_1.temp[1] *
         sv_1.tn[ifxcor_1.it * 3 - 2] + fxcor_1.temp[2] * sv_1.tn[
         ifxcor_1.it * 3 - 1];
     fxcor_1.tem[0] = d_sign(&znumbr_1.z1, &tv);
     sv_1.sn[ifxcor_1.is * 3 - 3] = -fxcor_1.tem[0] * fxcor_1.temp[0];
     sv_1.sn[ifxcor_1.is * 3 - 2] = -fxcor_1.tem[0] * fxcor_1.temp[1];
     sv_1.sn[ifxcor_1.is * 3 - 1] = -fxcor_1.tem[0] * fxcor_1.temp[2];
 /*                  USE TLNORM TO ESTABLISH CORRECT TOOL POINT */
     sv_1.rc[ifxcor_1.is - 1] = fxcor_1.rc1;
     sv_1.cc[ifxcor_1.is * 3 - 3] = sv_1.tp[ifxcor_1.it * 3 - 3] - sv_1.rc[
         ifxcor_1.is - 1] * sv_1.sn[ifxcor_1.is * 3 - 3];
     sv_1.cc[ifxcor_1.is * 3 - 2] = sv_1.tp[ifxcor_1.it * 3 - 2] - sv_1.rc[
         ifxcor_1.is - 1] * sv_1.sn[ifxcor_1.is * 3 - 2];
     sv_1.cc[ifxcor_1.is * 3 - 1] = sv_1.tp[ifxcor_1.it * 3 - 1] - sv_1.rc[
         ifxcor_1.is - 1] * sv_1.sn[ifxcor_1.is * 3 - 1];
     isv_1.jtn[ifxcor_1.is - 1] = (integer) znumbr_1.z0;
     u1comp_();
     isv_1.itseg[ifxcor_1.is - 1] = 1;
     isv_1.itlon[ifxcor_1.is - 1] = isv_1.itlon[iss - 1];
     isv_1.iafl[ifxcor_1.is - 1] = -1;
     isv_1.jtlflg[ifxcor_1.is - 1] = isv_1.jtlflg[iss - 1];
     isv_1.ipl[ifxcor_1.is - 1] = (integer) znumbr_1.z1;
     tlnorm_(&sv_1.u1[ifxcor_1.is * 3 - 3]);
 /*                  COMPUTE MOVE TO BRING THIS TP ON TO THE CPLAN */
 L1470:
     sv_1.plnd[iss - 1] = sv_1.plnv[iss * 3 - 3] * (sv_1.cc[iss * 3 - 3] -
         sv_1.tp[ifxcor_1.is * 3 - 3]) + sv_1.plnv[iss * 3 - 2] * (sv_1.cc[
         iss * 3 - 2] - sv_1.tp[ifxcor_1.is * 3 - 2]) + sv_1.plnv[iss * 3
         - 1] * (sv_1.cc[iss * 3 - 1] - sv_1.tp[ifxcor_1.is * 3 - 1]);
 /*                  RETURN */
     ifxcor_1.is = iss;
     ifxcor_1.it = its;
 /* L1510: */
     sv1_1.cplfl[ifxcor_1.is - 1] = 1.f;
 L1520:
     sv1_1.cptst[ifxcor_1.is - 1] += sv1_1.cplfl[ifxcor_1.is - 1];
 /* L1530: */
     if (sv1_1.cptst[ifxcor_1.is - 1] != 0.) {
     goto L9998;
     } else {
     goto L1520;
     }
 /*                  SPECIAL ROUTE FOR CYLINDER IT SURF + PLANE IS SURF */
 /*                  COMPUTE CPLAN POISTION FROM CANONICAL FORMS */
 L3000:
     if (isv_1.isfidn[ifxcor_1.it - 1] > knumbr_1.k4 || isv_1.isfidn[
         ifxcor_1.it - 1] < knumbr_1.k3) {
     goto L1010;
     }
     ifxcor_1.ic = isv_1.icanon[ifxcor_1.it - 1];
     fxcor_1.temp[6] = canon[ifxcor_1.ic + 2];
     fxcor_1.temp[7] = canon[ifxcor_1.ic + 3];
     fxcor_1.temp[8] = canon[ifxcor_1.ic + 4];
     cross_(&fxcor_1.temp[6], &sv_1.sn[ifxcor_1.is * 3 - 3], &sv_1.plnv[
         ifxcor_1.is * 3 - 3]);
     vnorm_(&sv_1.plnv[ifxcor_1.is * 3 - 3], &sv_1.plnv[ifxcor_1.is * 3 - 3]);
     sv_1.cc[ifxcor_1.is * 3 - 3] = canon[ifxcor_1.ic - 1];
     sv_1.cc[ifxcor_1.is * 3 - 2] = canon[ifxcor_1.ic];
     sv_1.cc[ifxcor_1.is * 3 - 1] = canon[ifxcor_1.ic + 1];
     sv1_1.plncs[ifxcor_1.is - 1] = sv_1.tn[ifxcor_1.it * 3 - 3] * sv_1.tn[
         ifxcor_1.is * 3 - 3] + sv_1.tn[ifxcor_1.it * 3 - 2] * sv_1.tn[
         ifxcor_1.is * 3 - 2] + sv_1.tn[ifxcor_1.it * 3 - 1] * sv_1.tn[
         ifxcor_1.is * 3 - 1];
     fxcor_1.temp[0] = sv_1.tn[ifxcor_1.is * 3 - 3];
     fxcor_1.temp[1] = sv_1.tn[ifxcor_1.is * 3 - 2];
     fxcor_1.temp[2] = sv_1.tn[ifxcor_1.is * 3 - 1];
     goto L1410;
 } /* cplan_ */
Variable Documentation
struct { ... } _BLNK__
doublereal a
Definition at line 18 of file CPLAN.c.
doublereal addcom[25]
Definition at line 126 of file CPLAN.c.
struct { ... } addcom_
doublereal alp
Definition at line 28 of file CPLAN.c.
doublereal ax4[3]
Definition at line 28 of file CPLAN.c.
doublereal b
Definition at line 18 of file CPLAN.c.
doublereal c__
Definition at line 18 of file CPLAN.c.
doublereal cagl
Definition at line 28 of file CPLAN.c.
doublereal cc[15]
Definition at line 50 of file CPLAN.c.
doublereal cendis
Definition at line 18 of file CPLAN.c.
struct { ... } charct_
doublereal cmove[3]
Definition at line 18 of file CPLAN.c.
doublereal com[36000]
Definition at line 132 of file CPLAN.c.
doublereal com1
Definition at line 18 of file CPLAN.c.
doublereal com4
Definition at line 18 of file CPLAN.c.
doublereal corrad[8]
Definition at line 43 of file CPLAN.c.
doublereal cos1[5]
Definition at line 67 of file CPLAN.c.
doublereal cplfl[5]
Definition at line 67 of file CPLAN.c.
doublereal cptst[5]
Definition at line 67 of file CPLAN.c.
doublereal csd[5]
Definition at line 67 of file CPLAN.c.
doublereal cutdat[7]
Definition at line 28 of file CPLAN.c.
doublereal d1
Definition at line 18 of file CPLAN.c.
doublereal d2a
Definition at line 18 of file CPLAN.c.
doublereal degrad
Definition at line 76 of file CPLAN.c.
doublereal dir[3]
Definition at line 18 of file CPLAN.c.
doublereal dp
Definition at line 18 of file CPLAN.c.
doublereal dp1
Definition at line 18 of file CPLAN.c.
doublereal dpcnt
Definition at line 18 of file CPLAN.c.
doublereal dpe
Definition at line 18 of file CPLAN.c.
doublereal dpi
Definition at line 18 of file CPLAN.c.
doublereal dpl
Definition at line 18 of file CPLAN.c.
doublereal dplan[15]
Definition at line 67 of file CPLAN.c.
doublereal dpmax
Definition at line 28 of file CPLAN.c.
doublereal dpmx1[5]
Definition at line 67 of file CPLAN.c.
struct { ... } dshar4_
doublereal eps1[5]
Definition at line 50 of file CPLAN.c.
doublereal eps2[5]
Definition at line 50 of file CPLAN.c.
doublereal eps3[5]
Definition at line 50 of file CPLAN.c.
doublereal eps4[5]
Definition at line 50 of file CPLAN.c.
doublereal eps6[5]
Definition at line 50 of file CPLAN.c.
doublereal eps8[5]
Definition at line 50 of file CPLAN.c.
doublereal flipck
Definition at line 18 of file CPLAN.c.
doublereal fwd[3]
Definition at line 18 of file CPLAN.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file CPLAN.c.
doublereal hi
Definition at line 28 of file CPLAN.c.
integer i3dflg
Definition at line 100 of file CPLAN.c.
integer iaerr
Definition at line 100 of file CPLAN.c.
integer iafl[5]
Definition at line 84 of file CPLAN.c.
integer iamdct
Definition at line 110 of file CPLAN.c.
integer iautps
Definition at line 100 of file CPLAN.c.
integer ibegin
Definition at line 100 of file CPLAN.c.
integer ic
Definition at line 100 of file CPLAN.c.
integer icanon[5]
Definition at line 84 of file CPLAN.c.
integer icheck
Definition at line 100 of file CPLAN.c.
integer icl
Definition at line 100 of file CPLAN.c.
integer ics
Definition at line 100 of file CPLAN.c.
integer icscnt
Definition at line 100 of file CPLAN.c.
integer ictdef
Definition at line 100 of file CPLAN.c.
integer icut
Definition at line 100 of file CPLAN.c.
integer ids
Definition at line 100 of file CPLAN.c.
integer ier
Definition at line 100 of file CPLAN.c.
integer ifar[5]
Definition at line 93 of file CPLAN.c.
integer ifl4[5]
Definition at line 93 of file CPLAN.c.
struct { ... } ifxcor_
integer igo
Definition at line 100 of file CPLAN.c.
integer igoto
Definition at line 100 of file CPLAN.c.
integer igoug
Definition at line 100 of file CPLAN.c.
integer igs
Definition at line 100 of file CPLAN.c.
integer index[5]
Definition at line 84 of file CPLAN.c.
integer indir__[5]
Definition at line 84 of file CPLAN.c.
integer inops
Definition at line 100 of file CPLAN.c.
integer iop[5]
Definition at line 84 of file CPLAN.c.
integer iopset[5]
Definition at line 84 of file CPLAN.c.
integer ipdpl
Definition at line 110 of file CPLAN.c.
integer ipl[5]
Definition at line 84 of file CPLAN.c.
integer ips
Definition at line 100 of file CPLAN.c.
integer ipsdef
Definition at line 100 of file CPLAN.c.
integer ipt
Definition at line 110 of file CPLAN.c.
integer ipt1
Definition at line 100 of file CPLAN.c.
integer is
Definition at line 100 of file CPLAN.c.
integer iseg
Definition at line 100 of file CPLAN.c.
integer iseqno
Definition at line 100 of file CPLAN.c.
integer isfidn[5]
Definition at line 84 of file CPLAN.c.
integer isftyp[5]
Definition at line 84 of file CPLAN.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 84 of file CPLAN.c.
integer isrch
Definition at line 100 of file CPLAN.c.
integer istrup
Definition at line 100 of file CPLAN.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 84 of file CPLAN.c.
integer it
Definition at line 100 of file CPLAN.c.
integer itlon[5]
Definition at line 84 of file CPLAN.c.
integer itseg[5]
Definition at line 84 of file CPLAN.c.
integer itsegk[5]
Definition at line 84 of file CPLAN.c.
integer iunfl[5]
Definition at line 84 of file CPLAN.c.
integer iws
Definition at line 110 of file CPLAN.c.
integer j10
Definition at line 110 of file CPLAN.c.
integer j12
Definition at line 110 of file CPLAN.c.
integer j13
Definition at line 110 of file CPLAN.c.
integer j20[5]
Definition at line 93 of file CPLAN.c.
integer j21[5]
Definition at line 93 of file CPLAN.c.
integer j22[5]
Definition at line 93 of file CPLAN.c.
integer j23[5]
Definition at line 93 of file CPLAN.c.
integer j50[5]
Definition at line 93 of file CPLAN.c.
integer j51[5]
Definition at line 93 of file CPLAN.c.
integer j54
Definition at line 110 of file CPLAN.c.
integer jbr
Definition at line 100 of file CPLAN.c.
integer jckr
Definition at line 110 of file CPLAN.c.
integer jcnt1
Definition at line 110 of file CPLAN.c.
integer jcnt2
Definition at line 110 of file CPLAN.c.
integer jcnt3
Definition at line 110 of file CPLAN.c.
integer jcpr
Definition at line 110 of file CPLAN.c.
integer jcr
Definition at line 110 of file CPLAN.c.
integer jdr
Definition at line 110 of file CPLAN.c.
integer jent[5]
Definition at line 84 of file CPLAN.c.
integer jfind
Definition at line 110 of file CPLAN.c.
integer jgr
Definition at line 110 of file CPLAN.c.
integer jiops[5]
Definition at line 84 of file CPLAN.c.
integer jmin
Definition at line 110 of file CPLAN.c.
integer jminr
Definition at line 110 of file CPLAN.c.
integer jph[5]
Definition at line 93 of file CPLAN.c.
integer jpr
Definition at line 110 of file CPLAN.c.
integer jpxr
Definition at line 110 of file CPLAN.c.
integer jsw
Definition at line 100 of file CPLAN.c.
integer jtkf
Definition at line 110 of file CPLAN.c.
integer jtlflg[5]
Definition at line 84 of file CPLAN.c.
integer jtn[5]
Definition at line 84 of file CPLAN.c.
integer jtr
Definition at line 110 of file CPLAN.c.
integer ju1[5]
Definition at line 84 of file CPLAN.c.
integer k0
Definition at line 118 of file CPLAN.c.
integer k1
Definition at line 118 of file CPLAN.c.
integer k10
Definition at line 118 of file CPLAN.c.
integer k1013
Definition at line 118 of file CPLAN.c.
integer k12
Definition at line 118 of file CPLAN.c.
integer k13
Definition at line 118 of file CPLAN.c.
integer k15
Definition at line 118 of file CPLAN.c.
integer k16
Definition at line 118 of file CPLAN.c.
integer k18
Definition at line 118 of file CPLAN.c.
integer k19
Definition at line 118 of file CPLAN.c.
integer k1e4
Definition at line 118 of file CPLAN.c.
integer k1e6
Definition at line 118 of file CPLAN.c.
integer k2
Definition at line 118 of file CPLAN.c.
integer k23
Definition at line 118 of file CPLAN.c.
integer k24
Definition at line 118 of file CPLAN.c.
integer k25
Definition at line 118 of file CPLAN.c.
integer k26
Definition at line 118 of file CPLAN.c.
integer k27
Definition at line 118 of file CPLAN.c.
integer k29
Definition at line 118 of file CPLAN.c.
integer k3
Definition at line 118 of file CPLAN.c.
integer k30
Definition at line 118 of file CPLAN.c.
integer k31
Definition at line 118 of file CPLAN.c.
integer k32
Definition at line 118 of file CPLAN.c.
integer k33
Definition at line 118 of file CPLAN.c.
integer k34
Definition at line 118 of file CPLAN.c.
integer k4
Definition at line 118 of file CPLAN.c.
integer k44
Definition at line 118 of file CPLAN.c.
integer k45
Definition at line 118 of file CPLAN.c.
integer k46
Definition at line 118 of file CPLAN.c.
integer k47
Definition at line 118 of file CPLAN.c.
integer k48
Definition at line 118 of file CPLAN.c.
integer k5
Definition at line 118 of file CPLAN.c.
integer k50
Definition at line 118 of file CPLAN.c.
integer k51
Definition at line 118 of file CPLAN.c.
integer k52
Definition at line 118 of file CPLAN.c.
integer k6
Definition at line 118 of file CPLAN.c.
integer k7
Definition at line 118 of file CPLAN.c.
integer k8
Definition at line 118 of file CPLAN.c.
integer k9
Definition at line 118 of file CPLAN.c.
integer km1
Definition at line 118 of file CPLAN.c.
struct { ... } knumbr_
integer limfl[5]
Definition at line 84 of file CPLAN.c.
integer lsv
Definition at line 100 of file CPLAN.c.
integer lsv1
Definition at line 100 of file CPLAN.c.
integer mantax
Definition at line 100 of file CPLAN.c.
integer mdic
Definition at line 110 of file CPLAN.c.
char modfer[6]
Definition at line 37 of file CPLAN.c.
integer motmod
Definition at line 100 of file CPLAN.c.
integer msav
Definition at line 100 of file CPLAN.c.
integer mulout
Definition at line 100 of file CPLAN.c.
integer nmbseg
Definition at line 100 of file CPLAN.c.
integer nmpnts
Definition at line 100 of file CPLAN.c.
integer notan[5]
Definition at line 93 of file CPLAN.c.
integer nrec
Definition at line 100 of file CPLAN.c.
integer numax
Definition at line 100 of file CPLAN.c.
integer numcnt
Definition at line 100 of file CPLAN.c.
integer nump
Definition at line 100 of file CPLAN.c.
integer numpt1
Definition at line 100 of file CPLAN.c.
integer numsfs
Definition at line 100 of file CPLAN.c.
integer numsur
Definition at line 100 of file CPLAN.c.
integer nw
Definition at line 100 of file CPLAN.c.
integer nwds
Definition at line 100 of file CPLAN.c.
doublereal ogle[3]
Definition at line 18 of file CPLAN.c.
doublereal p1[3]
Definition at line 18 of file CPLAN.c.
doublereal p2[3]
Definition at line 18 of file CPLAN.c.
doublereal param[6]
Definition at line 18 of file CPLAN.c.
doublereal past[5]
Definition at line 50 of file CPLAN.c.
doublereal pi
Definition at line 76 of file CPLAN.c.
doublereal plncs[5]
Definition at line 67 of file CPLAN.c.
doublereal plnd[5]
Definition at line 50 of file CPLAN.c.
doublereal plnd1[5]
Definition at line 67 of file CPLAN.c.
doublereal plnv[15]
Definition at line 50 of file CPLAN.c.
doublereal pltst[5]
Definition at line 67 of file CPLAN.c.
doublereal pmove[3]
Definition at line 28 of file CPLAN.c.
doublereal r__[6]
Definition at line 18 of file CPLAN.c.
doublereal ra
Definition at line 28 of file CPLAN.c.
doublereal rc[5]
Definition at line 50 of file CPLAN.c.
doublereal rc1
Definition at line 28 of file CPLAN.c.
doublereal rdrn
Definition at line 18 of file CPLAN.c.
doublereal refpnt[3]
Definition at line 18 of file CPLAN.c.
doublereal ri[8]
Definition at line 43 of file CPLAN.c.
doublereal s[5]
Definition at line 50 of file CPLAN.c.
doublereal sagl
Definition at line 28 of file CPLAN.c.
doublereal save[5]
Definition at line 50 of file CPLAN.c.
doublereal savpar[4]
Definition at line 18 of file CPLAN.c.
doublereal seg[9]
Definition at line 18 of file CPLAN.c.
doublereal sfvct[15]
Definition at line 50 of file CPLAN.c.
doublereal sk[15]
Definition at line 50 of file CPLAN.c.
doublereal slope
Definition at line 18 of file CPLAN.c.
doublereal slx[15]
Definition at line 50 of file CPLAN.c.
doublereal sn[15]
Definition at line 50 of file CPLAN.c.
doublereal snk[15]
Definition at line 50 of file CPLAN.c.
doublereal snl[15]
Definition at line 50 of file CPLAN.c.
doublereal sp[15]
Definition at line 50 of file CPLAN.c.
doublereal spk[15]
Definition at line 50 of file CPLAN.c.
doublereal spl[15]
Definition at line 50 of file CPLAN.c.
doublereal sqroot
Definition at line 18 of file CPLAN.c.
doublereal stck[5]
Definition at line 67 of file CPLAN.c.
doublereal stck1[5]
Definition at line 67 of file CPLAN.c.
doublereal stck2[5]
Definition at line 67 of file CPLAN.c.
doublereal stckn[5]
Definition at line 67 of file CPLAN.c.
doublereal strtno
Definition at line 28 of file CPLAN.c.
doublereal surd
Definition at line 28 of file CPLAN.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 28 of file CPLAN.c.
doublereal tak[3]
Definition at line 28 of file CPLAN.c.
doublereal tal[3]
Definition at line 28 of file CPLAN.c.
doublereal tangl
Definition at line 18 of file CPLAN.c.
doublereal tanhi[8]
Definition at line 43 of file CPLAN.c.
doublereal tanlo[8]
Definition at line 43 of file CPLAN.c.
doublereal tau[5]
Definition at line 50 of file CPLAN.c.
doublereal tau1[5]
Definition at line 50 of file CPLAN.c.
doublereal tau2[5]
Definition at line 50 of file CPLAN.c.
doublereal tcont[9]
Definition at line 43 of file CPLAN.c.
doublereal te[3]
Definition at line 28 of file CPLAN.c.
doublereal tee[15]
Definition at line 67 of file CPLAN.c.
doublereal tek[3]
Definition at line 28 of file CPLAN.c.
doublereal tel[3]
Definition at line 28 of file CPLAN.c.
doublereal tem[10]
Definition at line 28 of file CPLAN.c.
doublereal temp[24]
Definition at line 28 of file CPLAN.c.
doublereal tes[3]
Definition at line 18 of file CPLAN.c.
doublereal tew[3]
Definition at line 18 of file CPLAN.c.
doublereal th[5]
Definition at line 50 of file CPLAN.c.
doublereal ti[3]
Definition at line 28 of file CPLAN.c.
doublereal tik[3]
Definition at line 28 of file CPLAN.c.
doublereal til[3]
Definition at line 28 of file CPLAN.c.
doublereal tlhit
Definition at line 28 of file CPLAN.c.
doublereal tlhite[8]
Definition at line 43 of file CPLAN.c.
doublereal tlinc[9]
Definition at line 43 of file CPLAN.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file CPLAN.c.
doublereal tn[15]
Definition at line 50 of file CPLAN.c.
doublereal tnl[15]
Definition at line 67 of file CPLAN.c.
doublereal toolht[15]
Definition at line 50 of file CPLAN.c.
doublereal toolwd[5]
Definition at line 50 of file CPLAN.c.
doublereal tp[15]
Definition at line 50 of file CPLAN.c.
doublereal tpk[15]
Definition at line 50 of file CPLAN.c.
doublereal u1[15]
Definition at line 50 of file CPLAN.c.
doublereal u1k[15]
Definition at line 50 of file CPLAN.c.
doublereal u2[3]
Definition at line 18 of file CPLAN.c.
doublereal umax[8]
Definition at line 43 of file CPLAN.c.
doublereal unn
Definition at line 18 of file CPLAN.c.
doublereal upp
Definition at line 18 of file CPLAN.c.
doublereal uvec[3]
Definition at line 18 of file CPLAN.c.
doublereal v[3]
Definition at line 18 of file CPLAN.c.
doublereal varble[5]
Definition at line 50 of file CPLAN.c.
doublereal vint
Definition at line 18 of file CPLAN.c.
doublereal vl
Definition at line 18 of file CPLAN.c.
doublereal vndir[15]
Definition at line 50 of file CPLAN.c.
doublereal vnn
Definition at line 18 of file CPLAN.c.
doublereal vpp
Definition at line 18 of file CPLAN.c.
doublereal vt[15]
Definition at line 50 of file CPLAN.c.
doublereal vtem
Definition at line 28 of file CPLAN.c.
doublereal z0
Definition at line 76 of file CPLAN.c.
doublereal z1
Definition at line 76 of file CPLAN.c.
doublereal z10
Definition at line 76 of file CPLAN.c.
doublereal z11em1
Definition at line 76 of file CPLAN.c.
doublereal z12em1
Definition at line 76 of file CPLAN.c.
doublereal z1e38
Definition at line 76 of file CPLAN.c.
doublereal z1e6
Definition at line 76 of file CPLAN.c.
doublereal z1em1
Definition at line 76 of file CPLAN.c.
doublereal z1em2
Definition at line 76 of file CPLAN.c.
doublereal z1em3
Definition at line 76 of file CPLAN.c.
doublereal z1em5
Definition at line 76 of file CPLAN.c.
doublereal z1em6
Definition at line 76 of file CPLAN.c.
doublereal z1em7
Definition at line 76 of file CPLAN.c.
doublereal z1em9
Definition at line 76 of file CPLAN.c.
doublereal z2
Definition at line 76 of file CPLAN.c.
doublereal z3
Definition at line 76 of file CPLAN.c.
doublereal z5
Definition at line 76 of file CPLAN.c.
doublereal z5em1
Definition at line 76 of file CPLAN.c.
doublereal z5em6
Definition at line 76 of file CPLAN.c.
doublereal z6em1
Definition at line 76 of file CPLAN.c.
doublereal z90
Definition at line 76 of file CPLAN.c.
doublereal z9em1
Definition at line 76 of file CPLAN.c.
doublereal z__[5]
Definition at line 50 of file CPLAN.c.
doublereal zl
Definition at line 18 of file CPLAN.c.
doublereal zl1
Definition at line 18 of file CPLAN.c.
doublereal zlnorm[3]
Definition at line 18 of file CPLAN.c.
doublereal zlpnt[3]
Definition at line 18 of file CPLAN.c.
doublereal zm1
Definition at line 76 of file CPLAN.c.
struct { ... } znumbr_