My Project: CPRINT.c File Reference
CPRINT.c File Reference
#include "f2c.h"
Macros
#define cmptst_1 cmptst_
Functions
int cprint_ (char *array, ftnlen array_len)
Variables
struct {
integer icmtes
} cmptst_
Macro Definition Documentation
#define cmptst_1 cmptst_
Definition at line 21 of file CPRINT.c.
Referenced by cprint_().
Function Documentation
int cprint_ (char * array, ftnlen array_len)
Definition at line 25 of file CPRINT.c.
References cmpres_(), cmptst_1, and sprint_().
Referenced by abuftp_0_(), aerr2_(), aerr_(), aprix_(), apt024_(), apt089_(), apt104_(), apt110_(), apt301_(), apt302_(), apt309_(), apt330_(), apt331_(), apt335_(), apt336_(), aread_(), atapop_0_(), ataprd_(), atapwt_(), avctrl_(), avmsg_(), avoid_(), awrite_(), axset_(), bad_(), baltwo_(), cardpn_(), chkset_(), chread_(), chwrit_(), cilout_(), cleror_(), clput_(), conbcd_(), cprin1_(), crblen_(), crvlen_(), curflo_(), devcal_(), dgeom_(), errlod_(), error_(), errout_(), eval_(), filopn_(), floseg_(), foutxx_(), fread_(), gchk_(), gfetch_(), gol_(), gop_(), init_(), intchk_(), intmsg_(), intout_(), intrp_(), ldard_(), lib_(), linkf_(), mescon_(), mesh_(), midkur_(), midpnt_(), mixal_(), page_(), parnom_0_(), pchg_(), pchprc_(), print_(), punch_(), puncha_0_(), punchc_0_(), puvloc_(), read_(), region_(), sctra_(), scurv_(), set_(), smil_(), sprvis_0_(), srfcom_(), srfdir_(), srftol_(), sspath_(), sstra_(), stepck_(), tapepn_(), tapop_(), tecalc_(), teval_(), tlconv_(), tulpos_(), vorsch_(), xcanon_(), and xtpcal_().
 {
     /* Builtin functions */
     integer i_len(char *, ftnlen);
     /* Local variables */
     static integer slen;
     extern /* Subroutine */ int cmpres_(char *, integer *, ftnlen), sprint_(
         char *, ftnlen);
 /* ---       PURPOSE IS TO CONTROL COMPRESSION OF PRINTOUT */
 /* ---       IF ICMTES IS GT 0, STRINGS OF BLANKS ARE COMPRESSED */
     slen = i_len(array, array_len);
     if (cmptst_1.icmtes == 0) {
     goto L10;
     }
     cmpres_(array, &slen, array_len);
 L10:
     sprint_(array, slen);
     return 0;
 } /* cprint_ */
Variable Documentation
struct { ... } cmptst_
integer icmtes
Definition at line 18 of file CPRINT.c.