My Project: CPUNCH.c File Reference
CPUNCH.c File Reference
#include "f2c.h"
Macros
#define symfil_1 symfil_
#define filtab_1 filtab_
#define ifiltb_1 ifiltb_
Functions
int cpunch_ (char *array, integer *flagg, ftnlen array_len)
int cpuclo_ (void)
Variables
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
struct {
char filnam [480]
char filacc [300]
char filfmt [330]
char opstat [210]
char clstat [180]
} filtab_
struct {
integer u [30]
integer rl [30]
integer nxtrec [30]
integer lstrec [30]
} ifiltb_
static integer c__1 = 1
Macro Definition Documentation
#define filtab_1 filtab_
Definition at line 30 of file CPUNCH.c.
#define ifiltb_1 ifiltb_
Definition at line 36 of file CPUNCH.c.
Referenced by cpuclo_(), and cpunch_().
#define symfil_1 symfil_
Definition at line 24 of file CPUNCH.c.
Referenced by cpuclo_(), and cpunch_().
Function Documentation
int cpuclo_ (void)
Definition at line 138 of file CPUNCH.c.
References id, ifiltb_1, and symfil_1.
Referenced by sprvis_0_().
 {
     /* System generated locals */
     cllist cl__1;
     inlist ioin__1;
     /* Builtin functions */
     integer f_inqu(inlist *), f_clos(cllist *);
     /* Local variables */
     static integer id;
     static logical od;
 /* ...                SYSTEM I/O FILES */
 /*  *  FILE ATTRIBUTES  * */
     id = ifiltb_1.u[symfil_1.pnchfl - 1];
     ioin__1.inerr = 0;
     ioin__1.inunit = id;
     ioin__1.infile = 0;
     ioin__1.inex = 0;
     ioin__1.inopen = &od;
     ioin__1.innum = 0;
     ioin__1.innamed = 0;
     ioin__1.inname = 0;
     ioin__1.inacc = 0;
     ioin__1.inseq = 0;
     ioin__1.indir = 0;
     ioin__1.infmt = 0;
     ioin__1.inform = 0;
     ioin__1.inunf = 0;
     ioin__1.inrecl = 0;
     ioin__1.innrec = 0;
     ioin__1.inblank = 0;
     f_inqu(&ioin__1);
     if (od) {
     cl__1.cerr = 0;
     cl__1.cunit = id;
     cl__1.csta = "KEEP";
     f_clos(&cl__1);
     }
     return 0;
 } /* cpuclo_ */
int cpunch_ (char * array, integer * flagg, ftnlen array_len)
Definition at line 44 of file CPUNCH.c.
References c__1, filopn_(), id, ifiltb_1, and symfil_1.
Referenced by intout_(), and punch_().
 {
     /* System generated locals */
     inlist ioin__1;
     /* Builtin functions */
     integer f_inqu(inlist *), s_wsfe(cilist *), do_fio(integer *, char *,
         ftnlen), e_wsfe(void);
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer id;
     static logical od;
     extern /* Subroutine */ int filopn_(integer *);
     /* Fortran I/O blocks */
     static cilist io___3 = { 0, 0, 0, "(A80)", 0 };
 /*  *  CPUNCH  *   VAX11 FORTRAN VERSION  13.5.82  E.MCLELLAN */
 /*  PURPOSE     TO FORMAT A RECORD FOR PUNCHING ON PNCHFL */
 /*  CALLING SEQUENCE */
 /*              CALL CPUNCH(ARRAY,FLAGG) */
 /*  ARGUMENTS */
 /*              ARRAY   80 BYTE ARRAY CONTAINING THE */
 /*                      BCD CHARACTERS TO BE PUNCHED */
 /*              FLAGG   .EQ.0 BLANK FILL ARRAY AFTER PUNCHING */
 /*                      .NE.0 OMIT BLANKING */
 /* ...                 SYSTEM I/O FILES */
 /* ...     FILE ATTRIBUTES */
 /* ...                SYSTEM I/O FILES */
 /*  *  FILE ATTRIBUTES  * */
 /* .... UNIT NO FOR PNCHFL */
     id = ifiltb_1.u[symfil_1.pnchfl - 1];
 /* ---- IS PNCHFL OPEN, IF NOT, OPEN PNCHFL */
     ioin__1.inerr = 0;
     ioin__1.inunit = id;
     ioin__1.infile = 0;
     ioin__1.inex = 0;
     ioin__1.inopen = &od;
     ioin__1.innum = 0;
     ioin__1.innamed = 0;
     ioin__1.inname = 0;
     ioin__1.inacc = 0;
     ioin__1.inseq = 0;
     ioin__1.indir = 0;
     ioin__1.infmt = 0;
     ioin__1.inform = 0;
     ioin__1.inunf = 0;
     ioin__1.inrecl = 0;
     ioin__1.innrec = 0;
     ioin__1.inblank = 0;
     f_inqu(&ioin__1);
     if (! od) {
     filopn_(&symfil_1.pnchfl);
     }
     io___3.ciunit = id;
     s_wsfe(&io___3);
     do_fio(&c__1, array, (ftnlen)80);
     e_wsfe();
     if (*flagg == 0) {
 /* ---- BLANK FILL ARRAY */
     s_copy(array, " ", (ftnlen)80, (ftnlen)1);
     }
     return 0;
 } /* cpunch_ */
Variable Documentation
integer axfile
Definition at line 18 of file CPUNCH.c.
integer c__1 = 1 static
Definition at line 40 of file CPUNCH.c.
Referenced by cpunch_().
integer clfil3
Definition at line 18 of file CPUNCH.c.
integer clfile
Definition at line 18 of file CPUNCH.c.
integer clfilp
Definition at line 18 of file CPUNCH.c.
char clstat[180]
Definition at line 27 of file CPUNCH.c.
integer cpfile
Definition at line 18 of file CPUNCH.c.
integer elfil1
Definition at line 18 of file CPUNCH.c.
integer elfil2
Definition at line 18 of file CPUNCH.c.
integer elfil3
Definition at line 18 of file CPUNCH.c.
integer elfil4
Definition at line 18 of file CPUNCH.c.
integer elfile
Definition at line 18 of file CPUNCH.c.
integer exfile
Definition at line 18 of file CPUNCH.c.
char filacc[300]
Definition at line 27 of file CPUNCH.c.
char filfmt[330]
Definition at line 27 of file CPUNCH.c.
char filnam[480]
Definition at line 27 of file CPUNCH.c.
struct { ... } filtab_
struct { ... } ifiltb_
integer infile__
Definition at line 18 of file CPUNCH.c.
integer ispare[26]
Definition at line 18 of file CPUNCH.c.
integer ldafil
Definition at line 18 of file CPUNCH.c.
integer libfil
Definition at line 18 of file CPUNCH.c.
integer lstrec[30]
Definition at line 33 of file CPUNCH.c.
integer mactxt
Definition at line 18 of file CPUNCH.c.
integer nfil12
Definition at line 18 of file CPUNCH.c.
integer nfil13
Definition at line 18 of file CPUNCH.c.
integer nxtrec[30]
Definition at line 33 of file CPUNCH.c.
char opstat[210]
Definition at line 27 of file CPUNCH.c.
integer pnchfl
Definition at line 18 of file CPUNCH.c.
integer pofile
Definition at line 18 of file CPUNCH.c.
integer pxfile
Definition at line 18 of file CPUNCH.c.
integer rl[30]
Definition at line 33 of file CPUNCH.c.
struct { ... } symfil_
integer tifile
Definition at line 18 of file CPUNCH.c.
integer u[30]
Definition at line 33 of file CPUNCH.c.
integer vlfile
Definition at line 18 of file CPUNCH.c.
integer xcan
Definition at line 18 of file CPUNCH.c.
integer xnum
Definition at line 18 of file CPUNCH.c.