My Project: CUT.c File Reference
CUT.c File Reference
#include "f2c.h"
Macros
#define hblock_1 hblock_
#define ifxcor_1 ifxcor_
#define knumbr_1 knumbr_
#define hold_1 hold_
Functions
int cut_ (void)
int cuth_ (void)
Variables
struct {
char hps [8]
char hds [8]
char hcs [8]
char hlft [8]
char hrgt [8]
char hfwd [8]
char hback [8]
char hup [8]
char hdown [8]
char hto [8]
char hpast [8]
char hon [8]
char htanto [8]
char hpstan [8]
char hdynp [8]
char haerr [8]
char hcldat [8]
char hgerr [8]
} hblock_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
integer jhldfg
integer ithcnt
integer itabh [100]
} hold_
static integer c__1 = 1
static integer c__27 = 27
Macro Definition Documentation
#define hblock_1 hblock_
Definition at line 23 of file CUT.c.
#define hold_1 hold_
Definition at line 47 of file CUT.c.
Referenced by cut_().
#define ifxcor_1 ifxcor_
Definition at line 33 of file CUT.c.
Referenced by cut_(), and cuth_().
#define knumbr_1 knumbr_
Definition at line 41 of file CUT.c.
Referenced by cut_(), and cuth_().
Function Documentation
int cut_ (void)
Definition at line 58 of file CUT.c.
References apt233_(), apt299_(), bcdf_(), c__1, c__27, hold_1, i__, ifxcor_1, and knumbr_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static char ppword[4] = "CUT ";
     static char mesage[32] = " ...LOCATION WHERE CUT RESUMES..";
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__, i4;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt233_(void), apt299_(integer *, integer *,
         integer *, integer *);
     static integer msgary[10], ippwrd[2];
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*     *** 8.  HOLRTH BLOCK *** */
 /*     ALPHA-NUMERIC LITERAL CONSTANTS. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ... */
     if (hold_1.jhldfg == 0) {
     goto L1;
     }
     hold_1.itabh[hold_1.ithcnt - 1] = 6;
     ++hold_1.ithcnt;
     return 0;
 L1:
 /* ...  OUTPUT CUTTER CENTERS ON EXFILE */
     if (ifxcor_1.icut <= 0) {
     goto L20;
     } else {
     goto L10;
     }
 /* ...     WRITE ON EXFILE A MESSAGE INDICATING START OF CUT SEQUENCE */
 L10:
     msgary[0] = 10;
     msgary[1] = 32;
     for (i__ = 1; i__ <= 8; ++i__) {
     i4 = i__ << 2;
     i__1 = i4 - 4;
     msgary[i__ + 1] = bcdf_(mesage + i__1, i4 - i__1);
 /* L15: */
     }
     ippwrd[0] = bcdf_(ppword, (ftnlen)4);
     ippwrd[1] = bcdf_("    ", (ftnlen)4);
     apt299_(&c__1, ippwrd, &c__27, msgary);
     ifxcor_1.icl = knumbr_1.k3;
     ifxcor_1.icut = 0;
     apt233_();
 L20:
     return 0;
 } /* cut_ */
int cuth_ (void)
Definition at line 150 of file CUT.c.
References apt233_(), apt299_(), bcdf_(), c__1, c__27, i__, ifxcor_1, and knumbr_1.
Referenced by apt211_().
 {
     /* Initialized data */
     static char ppword[4] = "CUT ";
     static char mesage[32] = " ...LOCATION WHERE CUT RESUMES..";
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__, i4;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt233_(void), apt299_(integer *, integer *,
         integer *, integer *);
     static integer msgary[10], ippwrd;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*     *** 8.  HOLRTH BLOCK *** */
 /*     ALPHA-NUMERIC LITERAL CONSTANTS. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ... */
 /* L1: */
 /* ...  OUTPUT CUTTER CENTERS ON EXFILE */
     if (ifxcor_1.icut <= 0) {
     goto L20;
     } else {
     goto L10;
     }
 /* ...     WRITE ON EXFILE A MESSAGE INDICATING START OF CUT SEQUENCE */
 L10:
     msgary[0] = 10;
     msgary[1] = 32;
     for (i__ = 1; i__ <= 8; ++i__) {
     i4 = i__ << 2;
     i__1 = i4 - 4;
     msgary[i__ + 1] = bcdf_(mesage + i__1, i4 - i__1);
 /* L15: */
     }
     ippwrd = bcdf_(ppword, (ftnlen)4);
     apt299_(&c__1, &ippwrd, &c__27, msgary);
     ifxcor_1.icl = knumbr_1.k3;
     ifxcor_1.icut = 0;
     apt233_();
 L20:
     return 0;
 } /* cuth_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 51 of file CUT.c.
Referenced by cut_(), and cuth_().
integer c__27 = 27 static
Definition at line 52 of file CUT.c.
Referenced by cut_(), and cuth_().
char haerr[8]
Definition at line 18 of file CUT.c.
char hback[8]
Definition at line 18 of file CUT.c.
struct { ... } hblock_
char hcldat[8]
Definition at line 18 of file CUT.c.
char hcs[8]
Definition at line 18 of file CUT.c.
char hdown[8]
Definition at line 18 of file CUT.c.
char hds[8]
Definition at line 18 of file CUT.c.
char hdynp[8]
Definition at line 18 of file CUT.c.
char hfwd[8]
Definition at line 18 of file CUT.c.
char hgerr[8]
Definition at line 18 of file CUT.c.
char hlft[8]
Definition at line 18 of file CUT.c.
struct { ... } hold_
char hon[8]
Definition at line 18 of file CUT.c.
char hpast[8]
Definition at line 18 of file CUT.c.
char hps[8]
Definition at line 18 of file CUT.c.
char hpstan[8]
Definition at line 18 of file CUT.c.
char hrgt[8]
Definition at line 18 of file CUT.c.
char htanto[8]
Definition at line 18 of file CUT.c.
char hto[8]
Definition at line 18 of file CUT.c.
char hup[8]
Definition at line 18 of file CUT.c.
integer i3dflg
Definition at line 26 of file CUT.c.
integer iaerr
Definition at line 26 of file CUT.c.
integer iautps
Definition at line 26 of file CUT.c.
integer ibegin
Definition at line 26 of file CUT.c.
integer ic
Definition at line 26 of file CUT.c.
integer icheck
Definition at line 26 of file CUT.c.
integer icl
Definition at line 26 of file CUT.c.
integer ics
Definition at line 26 of file CUT.c.
integer icscnt
Definition at line 26 of file CUT.c.
integer ictdef
Definition at line 26 of file CUT.c.
integer icut
Definition at line 26 of file CUT.c.
integer ids
Definition at line 26 of file CUT.c.
integer ier
Definition at line 26 of file CUT.c.
struct { ... } ifxcor_
integer igo
Definition at line 26 of file CUT.c.
integer igoto
Definition at line 26 of file CUT.c.
integer igoug
Definition at line 26 of file CUT.c.
integer igs
Definition at line 26 of file CUT.c.
integer inops
Definition at line 26 of file CUT.c.
integer ips
Definition at line 26 of file CUT.c.
integer ipsdef
Definition at line 26 of file CUT.c.
integer ipt1
Definition at line 26 of file CUT.c.
integer is
Definition at line 26 of file CUT.c.
integer iseg
Definition at line 26 of file CUT.c.
integer iseqno
Definition at line 26 of file CUT.c.
integer isrch
Definition at line 26 of file CUT.c.
integer istrup
Definition at line 26 of file CUT.c.
integer it
Definition at line 26 of file CUT.c.
integer itabh[100]
Definition at line 44 of file CUT.c.
integer ithcnt
Definition at line 44 of file CUT.c.
integer jbr
Definition at line 26 of file CUT.c.
integer jhldfg
Definition at line 44 of file CUT.c.
integer jsw
Definition at line 26 of file CUT.c.
integer k0
Definition at line 36 of file CUT.c.
integer k1
Definition at line 36 of file CUT.c.
integer k10
Definition at line 36 of file CUT.c.
integer k1013
Definition at line 36 of file CUT.c.
integer k12
Definition at line 36 of file CUT.c.
integer k13
Definition at line 36 of file CUT.c.
integer k15
Definition at line 36 of file CUT.c.
integer k16
Definition at line 36 of file CUT.c.
integer k18
Definition at line 36 of file CUT.c.
integer k19
Definition at line 36 of file CUT.c.
integer k1e4
Definition at line 36 of file CUT.c.
integer k1e6
Definition at line 36 of file CUT.c.
integer k2
Definition at line 36 of file CUT.c.
integer k23
Definition at line 36 of file CUT.c.
integer k24
Definition at line 36 of file CUT.c.
integer k25
Definition at line 36 of file CUT.c.
integer k26
Definition at line 36 of file CUT.c.
integer k27
Definition at line 36 of file CUT.c.
integer k29
Definition at line 36 of file CUT.c.
integer k3
Definition at line 36 of file CUT.c.
integer k30
Definition at line 36 of file CUT.c.
integer k31
Definition at line 36 of file CUT.c.
integer k32
Definition at line 36 of file CUT.c.
integer k33
Definition at line 36 of file CUT.c.
integer k34
Definition at line 36 of file CUT.c.
integer k4
Definition at line 36 of file CUT.c.
integer k44
Definition at line 36 of file CUT.c.
integer k45
Definition at line 36 of file CUT.c.
integer k46
Definition at line 36 of file CUT.c.
integer k47
Definition at line 36 of file CUT.c.
integer k48
Definition at line 36 of file CUT.c.
integer k5
Definition at line 36 of file CUT.c.
integer k50
Definition at line 36 of file CUT.c.
integer k51
Definition at line 36 of file CUT.c.
integer k52
Definition at line 36 of file CUT.c.
integer k6
Definition at line 36 of file CUT.c.
integer k7
Definition at line 36 of file CUT.c.
integer k8
Definition at line 36 of file CUT.c.
integer k9
Definition at line 36 of file CUT.c.
integer km1
Definition at line 36 of file CUT.c.
struct { ... } knumbr_
integer lsv
Definition at line 26 of file CUT.c.
integer lsv1
Definition at line 26 of file CUT.c.
integer mantax
Definition at line 26 of file CUT.c.
integer motmod
Definition at line 26 of file CUT.c.
integer msav
Definition at line 26 of file CUT.c.
integer mulout
Definition at line 26 of file CUT.c.
integer nmbseg
Definition at line 26 of file CUT.c.
integer nmpnts
Definition at line 26 of file CUT.c.
integer nrec
Definition at line 26 of file CUT.c.
integer numax
Definition at line 26 of file CUT.c.
integer numcnt
Definition at line 26 of file CUT.c.
integer nump
Definition at line 26 of file CUT.c.
integer numpt1
Definition at line 26 of file CUT.c.
integer numsfs
Definition at line 26 of file CUT.c.
integer numsur
Definition at line 26 of file CUT.c.
integer nw
Definition at line 26 of file CUT.c.
integer nwds
Definition at line 26 of file CUT.c.