My Project: DARSIN.c File Reference
DARSIN.c File Reference
#include "f2c.h"
Functions
doublereal darsin_ (doublereal *x)
doublereal darcos_ (doublereal *x)
doublereal dcotan_ (doublereal *x)
Function Documentation
doublereal darcos_ (doublereal * x)
Definition at line 35 of file DARSIN.c.
Referenced by abw_(), angder_(), anglb_(), anglf_(), arcosb_(), arcosf_(), and gcubic_().
 {
     /* System generated locals */
     doublereal ret_val;
     /* Builtin functions */
     double acos(doublereal);
 /* DOUBLE PRECISION ARC COS FUNCTION USING STANDARD FUNCTION */
     ret_val = acos(*x);
     return ret_val;
 } /* darcos_ */
doublereal darsin_ (doublereal * x)
Definition at line 17 of file DARSIN.c.
Referenced by arsinb_(), and arsinf_().
 {
     /* System generated locals */
     doublereal ret_val;
     /* Builtin functions */
     double asin(doublereal);
 /* DOUBLE PRECISION ARC SINE FUNCTION USING STANDARD FUNCTION */
     ret_val = asin(*x);
     return ret_val;
 } /* darsin_ */
doublereal dcotan_ (doublereal * x)
Definition at line 53 of file DARSIN.c.
References f, and t.
Referenced by cotanb_(), and cotanf_().
 {
     /* System generated locals */
     doublereal ret_val;
     /* Builtin functions */
     double tan(doublereal);
     /* Local variables */
     static doublereal t;
 /* DOUBLE PECISION COTANGENT USING DTAN FUNCTION */
     t = tan(*x);
     if (t != 0.f) {
     goto L10;
     }
     ret_val = 1e38;
     return ret_val;
 L10:
     ret_val = 1.f / t;
     return ret_val;
 } /* dcotan_ */