My Project: DDCYLN.c File Reference
DDCYLN.c File Reference
#include "f2c.h"
Macros
#define dshar4_1 dshar4_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int ddcyln_ (doublereal *srface)
Variables
struct {
doublereal a
doublereal b
doublereal c__
doublereal cendis
doublereal cmove [3]
doublereal com1
doublereal com4
doublereal dir [3]
doublereal dp
doublereal dpe
doublereal dpcnt
doublereal dpi
doublereal dpl
doublereal dp1
doublereal d1
doublereal d2a
doublereal flipck
doublereal fwd [3]
doublereal ogle [3]
doublereal p1 [3]
doublereal p2 [3]
doublereal rdrn
doublereal refpnt [3]
doublereal tangl
doublereal tes [3]
doublereal tew [3]
doublereal uvec [3]
doublereal u2 [3]
doublereal v [3]
doublereal vl
doublereal zl
doublereal zlnorm [3]
doublereal zlpnt [3]
doublereal zl1
doublereal param [6]
doublereal r__ [6]
doublereal savpar [4]
doublereal seg [9]
doublereal slope
doublereal sqroot
doublereal unn
doublereal upp
doublereal vint
doublereal vnn
doublereal vpp
} dshar4_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
Macro Definition Documentation
#define charct_1 charct_
Definition at line 40 of file DDCYLN.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dshar4_1 dshar4_
Definition at line 25 of file DDCYLN.c.
Referenced by ddcyln_().
#define fxcor_1 fxcor_
Definition at line 34 of file DDCYLN.c.
Referenced by ddcyln_().
#define ifxcor_1 ifxcor_
Definition at line 91 of file DDCYLN.c.
Referenced by ddcyln_().
#define ishr18_1 ishr18_
Definition at line 99 of file DDCYLN.c.
#define knumbr_1 knumbr_
Definition at line 107 of file DDCYLN.c.
Referenced by ddcyln_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sv1_1 sv1_
Definition at line 73 of file DDCYLN.c.
#define sv_1 sv_
Definition at line 64 of file DDCYLN.c.
Referenced by ddcyln_().
#define tlldat_1 tlldat_
Definition at line 47 of file DDCYLN.c.
#define znumbr_1 znumbr_
Definition at line 81 of file DDCYLN.c.
Referenced by ddcyln_().
Function Documentation
int ddcyln_ (doublereal * srface)
Definition at line 113 of file DDCYLN.c.
References cross_(), dshar4_1, fxcor_1, ifxcor_1, knumbr_1, quad_(), srface, sv_1, and znumbr_1.
Referenced by ajundd_(), ddrlsr_(), ddst_(), and radar_().
 {
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     extern /* Subroutine */ int quad_(void);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     extern /* Subroutine */ int cross_(doublereal *, doublereal *, doublereal
         *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --srface;
     /* Function Body */
     ifxcor_1.ier = knumbr_1.k0;
     if (ifxcor_1.istrup == 5) {
     goto L47;
     }
     fxcor_1.tem[0] = sv_1.tn[ifxcor_1.is * 3 - 3] * srface[4] + sv_1.tn[
         ifxcor_1.is * 3 - 2] * srface[5] + sv_1.tn[ifxcor_1.is * 3 - 1] *
         srface[6];
     dshar4_1.a = sv_1.tn[ifxcor_1.is * 3 - 3] * sv_1.tn[ifxcor_1.is * 3 - 3]
         + sv_1.tn[ifxcor_1.is * 3 - 2] * sv_1.tn[ifxcor_1.is * 3 - 2] +
         sv_1.tn[ifxcor_1.is * 3 - 1] * sv_1.tn[ifxcor_1.is * 3 - 1];
     fxcor_1.tem[1] = sv_1.tp[ifxcor_1.is * 3 - 3] - srface[1];
     fxcor_1.tem[2] = sv_1.tp[ifxcor_1.is * 3 - 2] - srface[2];
     fxcor_1.tem[3] = sv_1.tp[ifxcor_1.is * 3 - 1] - srface[3];
     fxcor_1.tem[4] = fxcor_1.tem[1] * srface[4] + fxcor_1.tem[2] * srface[5]
         + fxcor_1.tem[3] * srface[6];
     dshar4_1.b = sv_1.tn[ifxcor_1.is * 3 - 3] * fxcor_1.tem[1] + sv_1.tn[
         ifxcor_1.is * 3 - 2] * fxcor_1.tem[2] + sv_1.tn[ifxcor_1.is * 3 -
         1] * fxcor_1.tem[3];
     dshar4_1.c__ = fxcor_1.tem[1] * fxcor_1.tem[1] + fxcor_1.tem[2] *
         fxcor_1.tem[2] + fxcor_1.tem[3] * fxcor_1.tem[3];
     dshar4_1.a -= fxcor_1.tem[0] * fxcor_1.tem[0];
     dshar4_1.b -= fxcor_1.tem[0] * fxcor_1.tem[4];
 /*              CHOOSE WELL-CONDITIONED FORMULA */
     if (abs(dshar4_1.c__) < znumbr_1.z1em9) {
     goto L42;
     }
     if (fxcor_1.tem[4] * fxcor_1.tem[4] / dshar4_1.c__ - .9f <= 0.) {
     goto L42;
     } else {
     goto L44;
     }
 L42:
     dshar4_1.c__ = dshar4_1.c__ - fxcor_1.tem[4] * fxcor_1.tem[4] - srface[7]
         * srface[7];
     goto L46;
 L44:
     cross_(&srface[4], &fxcor_1.tem[1], &fxcor_1.tem[5]);
     dshar4_1.c__ = fxcor_1.tem[5] * fxcor_1.tem[5] + fxcor_1.tem[6] *
         fxcor_1.tem[6] + fxcor_1.tem[7] * fxcor_1.tem[7] - srface[7] *
         srface[7];
 L46:
     quad_();
     if (ifxcor_1.ier == 1) {
     goto L1000;
     }
     if (ifxcor_1.istrup == 4) {
     goto L50;
     }
     sv_1.spl[ifxcor_1.is * 3 - 3] = sv_1.sp[ifxcor_1.is * 3 - 3];
     sv_1.spl[ifxcor_1.is * 3 - 2] = sv_1.sp[ifxcor_1.is * 3 - 2];
     sv_1.spl[ifxcor_1.is * 3 - 1] = sv_1.sp[ifxcor_1.is * 3 - 1];
     sv_1.snl[ifxcor_1.is * 3 - 3] = sv_1.sn[ifxcor_1.is * 3 - 3];
     sv_1.snl[ifxcor_1.is * 3 - 2] = sv_1.sn[ifxcor_1.is * 3 - 2];
     sv_1.snl[ifxcor_1.is * 3 - 1] = sv_1.sn[ifxcor_1.is * 3 - 1];
 L50:
     sv_1.sp[ifxcor_1.is * 3 - 3] = sv_1.tp[ifxcor_1.is * 3 - 3] + sv_1.s[
         ifxcor_1.is - 1] * sv_1.tn[ifxcor_1.is * 3 - 3];
     sv_1.sp[ifxcor_1.is * 3 - 2] = sv_1.tp[ifxcor_1.is * 3 - 2] + sv_1.s[
         ifxcor_1.is - 1] * sv_1.tn[ifxcor_1.is * 3 - 2];
     sv_1.sp[ifxcor_1.is * 3 - 1] = sv_1.tp[ifxcor_1.is * 3 - 1] + sv_1.s[
         ifxcor_1.is - 1] * sv_1.tn[ifxcor_1.is * 3 - 1];
 L47:
     fxcor_1.tem[0] = sv_1.sp[ifxcor_1.is * 3 - 3] - srface[1];
     fxcor_1.tem[1] = sv_1.sp[ifxcor_1.is * 3 - 2] - srface[2];
     fxcor_1.tem[2] = sv_1.sp[ifxcor_1.is * 3 - 1] - srface[3];
     fxcor_1.tem[3] = fxcor_1.tem[0] * srface[4] + fxcor_1.tem[1] * srface[5]
         + fxcor_1.tem[2] * srface[6];
     fxcor_1.tem[0] -= fxcor_1.tem[3] * srface[4];
     fxcor_1.tem[1] -= fxcor_1.tem[3] * srface[5];
     fxcor_1.tem[2] -= fxcor_1.tem[3] * srface[6];
     fxcor_1.tem[4] = fxcor_1.tem[0] * fxcor_1.tem[0] + fxcor_1.tem[1] *
         fxcor_1.tem[1] + fxcor_1.tem[2] * fxcor_1.tem[2];
     if (fxcor_1.tem[4] <= 0.) {
     goto L3;
     } else {
     goto L4;
     }
 L3:
     ifxcor_1.ier = knumbr_1.k1;
     goto L1000;
 L4:
     fxcor_1.tem[4] = sqrt(fxcor_1.tem[4]);
     sv_1.sn[ifxcor_1.is * 3 - 3] = fxcor_1.tem[0] / fxcor_1.tem[4];
     sv_1.sn[ifxcor_1.is * 3 - 2] = fxcor_1.tem[1] / fxcor_1.tem[4];
     sv_1.sn[ifxcor_1.is * 3 - 1] = fxcor_1.tem[2] / fxcor_1.tem[4];
 L1000:
     return 0;
 } /* ddcyln_ */
Variable Documentation
doublereal a
Definition at line 18 of file DDCYLN.c.
doublereal alp
Definition at line 28 of file DDCYLN.c.
doublereal ax4[3]
Definition at line 28 of file DDCYLN.c.
doublereal b
Definition at line 18 of file DDCYLN.c.
doublereal c__
Definition at line 18 of file DDCYLN.c.
doublereal cagl
Definition at line 28 of file DDCYLN.c.
doublereal cc[15]
Definition at line 50 of file DDCYLN.c.
doublereal cendis
Definition at line 18 of file DDCYLN.c.
struct { ... } charct_
doublereal cmove[3]
Definition at line 18 of file DDCYLN.c.
doublereal com1
Definition at line 18 of file DDCYLN.c.
doublereal com4
Definition at line 18 of file DDCYLN.c.
doublereal corrad[8]
Definition at line 43 of file DDCYLN.c.
doublereal cos1[5]
Definition at line 67 of file DDCYLN.c.
doublereal cplfl[5]
Definition at line 67 of file DDCYLN.c.
doublereal cptst[5]
Definition at line 67 of file DDCYLN.c.
doublereal csd[5]
Definition at line 67 of file DDCYLN.c.
doublereal cutdat[7]
Definition at line 28 of file DDCYLN.c.
doublereal d1
Definition at line 18 of file DDCYLN.c.
doublereal d2a
Definition at line 18 of file DDCYLN.c.
doublereal degrad
Definition at line 76 of file DDCYLN.c.
doublereal dir[3]
Definition at line 18 of file DDCYLN.c.
doublereal dp
Definition at line 18 of file DDCYLN.c.
doublereal dp1
Definition at line 18 of file DDCYLN.c.
doublereal dpcnt
Definition at line 18 of file DDCYLN.c.
doublereal dpe
Definition at line 18 of file DDCYLN.c.
doublereal dpi
Definition at line 18 of file DDCYLN.c.
doublereal dpl
Definition at line 18 of file DDCYLN.c.
doublereal dplan[15]
Definition at line 67 of file DDCYLN.c.
doublereal dpmax
Definition at line 28 of file DDCYLN.c.
doublereal dpmx1[5]
Definition at line 67 of file DDCYLN.c.
struct { ... } dshar4_
doublereal eps1[5]
Definition at line 50 of file DDCYLN.c.
doublereal eps2[5]
Definition at line 50 of file DDCYLN.c.
doublereal eps3[5]
Definition at line 50 of file DDCYLN.c.
doublereal eps4[5]
Definition at line 50 of file DDCYLN.c.
doublereal eps6[5]
Definition at line 50 of file DDCYLN.c.
doublereal eps8[5]
Definition at line 50 of file DDCYLN.c.
doublereal flipck
Definition at line 18 of file DDCYLN.c.
doublereal fwd[3]
Definition at line 18 of file DDCYLN.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file DDCYLN.c.
doublereal hi
Definition at line 28 of file DDCYLN.c.
integer i3dflg
Definition at line 84 of file DDCYLN.c.
integer iaerr
Definition at line 84 of file DDCYLN.c.
integer iamdct
Definition at line 94 of file DDCYLN.c.
integer iautps
Definition at line 84 of file DDCYLN.c.
integer ibegin
Definition at line 84 of file DDCYLN.c.
integer ic
Definition at line 84 of file DDCYLN.c.
integer icheck
Definition at line 84 of file DDCYLN.c.
integer icl
Definition at line 84 of file DDCYLN.c.
integer ics
Definition at line 84 of file DDCYLN.c.
integer icscnt
Definition at line 84 of file DDCYLN.c.
integer ictdef
Definition at line 84 of file DDCYLN.c.
integer icut
Definition at line 84 of file DDCYLN.c.
integer ids
Definition at line 84 of file DDCYLN.c.
integer ier
Definition at line 84 of file DDCYLN.c.
struct { ... } ifxcor_
integer igo
Definition at line 84 of file DDCYLN.c.
integer igoto
Definition at line 84 of file DDCYLN.c.
integer igoug
Definition at line 84 of file DDCYLN.c.
integer igs
Definition at line 84 of file DDCYLN.c.
integer inops
Definition at line 84 of file DDCYLN.c.
integer ipdpl
Definition at line 94 of file DDCYLN.c.
integer ips
Definition at line 84 of file DDCYLN.c.
integer ipsdef
Definition at line 84 of file DDCYLN.c.
integer ipt
Definition at line 94 of file DDCYLN.c.
integer ipt1
Definition at line 84 of file DDCYLN.c.
integer is
Definition at line 84 of file DDCYLN.c.
integer iseg
Definition at line 84 of file DDCYLN.c.
integer iseqno
Definition at line 84 of file DDCYLN.c.
struct { ... } ishr18_
integer isrch
Definition at line 84 of file DDCYLN.c.
integer istrup
Definition at line 84 of file DDCYLN.c.
integer it
Definition at line 84 of file DDCYLN.c.
integer iws
Definition at line 94 of file DDCYLN.c.
integer j10
Definition at line 94 of file DDCYLN.c.
integer j12
Definition at line 94 of file DDCYLN.c.
integer j13
Definition at line 94 of file DDCYLN.c.
integer j54
Definition at line 94 of file DDCYLN.c.
integer jbr
Definition at line 84 of file DDCYLN.c.
integer jckr
Definition at line 94 of file DDCYLN.c.
integer jcnt1
Definition at line 94 of file DDCYLN.c.
integer jcnt2
Definition at line 94 of file DDCYLN.c.
integer jcnt3
Definition at line 94 of file DDCYLN.c.
integer jcpr
Definition at line 94 of file DDCYLN.c.
integer jcr
Definition at line 94 of file DDCYLN.c.
integer jdr
Definition at line 94 of file DDCYLN.c.
integer jfind
Definition at line 94 of file DDCYLN.c.
integer jgr
Definition at line 94 of file DDCYLN.c.
integer jmin
Definition at line 94 of file DDCYLN.c.
integer jminr
Definition at line 94 of file DDCYLN.c.
integer jpr
Definition at line 94 of file DDCYLN.c.
integer jpxr
Definition at line 94 of file DDCYLN.c.
integer jsw
Definition at line 84 of file DDCYLN.c.
integer jtkf
Definition at line 94 of file DDCYLN.c.
integer jtr
Definition at line 94 of file DDCYLN.c.
integer k0
Definition at line 102 of file DDCYLN.c.
integer k1
Definition at line 102 of file DDCYLN.c.
integer k10
Definition at line 102 of file DDCYLN.c.
integer k1013
Definition at line 102 of file DDCYLN.c.
integer k12
Definition at line 102 of file DDCYLN.c.
integer k13
Definition at line 102 of file DDCYLN.c.
integer k15
Definition at line 102 of file DDCYLN.c.
integer k16
Definition at line 102 of file DDCYLN.c.
integer k18
Definition at line 102 of file DDCYLN.c.
integer k19
Definition at line 102 of file DDCYLN.c.
integer k1e4
Definition at line 102 of file DDCYLN.c.
integer k1e6
Definition at line 102 of file DDCYLN.c.
integer k2
Definition at line 102 of file DDCYLN.c.
integer k23
Definition at line 102 of file DDCYLN.c.
integer k24
Definition at line 102 of file DDCYLN.c.
integer k25
Definition at line 102 of file DDCYLN.c.
integer k26
Definition at line 102 of file DDCYLN.c.
integer k27
Definition at line 102 of file DDCYLN.c.
integer k29
Definition at line 102 of file DDCYLN.c.
integer k3
Definition at line 102 of file DDCYLN.c.
integer k30
Definition at line 102 of file DDCYLN.c.
integer k31
Definition at line 102 of file DDCYLN.c.
integer k32
Definition at line 102 of file DDCYLN.c.
integer k33
Definition at line 102 of file DDCYLN.c.
integer k34
Definition at line 102 of file DDCYLN.c.
integer k4
Definition at line 102 of file DDCYLN.c.
integer k44
Definition at line 102 of file DDCYLN.c.
integer k45
Definition at line 102 of file DDCYLN.c.
integer k46
Definition at line 102 of file DDCYLN.c.
integer k47
Definition at line 102 of file DDCYLN.c.
integer k48
Definition at line 102 of file DDCYLN.c.
integer k5
Definition at line 102 of file DDCYLN.c.
integer k50
Definition at line 102 of file DDCYLN.c.
integer k51
Definition at line 102 of file DDCYLN.c.
integer k52
Definition at line 102 of file DDCYLN.c.
integer k6
Definition at line 102 of file DDCYLN.c.
integer k7
Definition at line 102 of file DDCYLN.c.
integer k8
Definition at line 102 of file DDCYLN.c.
integer k9
Definition at line 102 of file DDCYLN.c.
integer km1
Definition at line 102 of file DDCYLN.c.
struct { ... } knumbr_
integer lsv
Definition at line 84 of file DDCYLN.c.
integer lsv1
Definition at line 84 of file DDCYLN.c.
integer mantax
Definition at line 84 of file DDCYLN.c.
integer mdic
Definition at line 94 of file DDCYLN.c.
char modfer[6]
Definition at line 37 of file DDCYLN.c.
integer motmod
Definition at line 84 of file DDCYLN.c.
integer msav
Definition at line 84 of file DDCYLN.c.
integer mulout
Definition at line 84 of file DDCYLN.c.
integer nmbseg
Definition at line 84 of file DDCYLN.c.
integer nmpnts
Definition at line 84 of file DDCYLN.c.
integer nrec
Definition at line 84 of file DDCYLN.c.
integer numax
Definition at line 84 of file DDCYLN.c.
integer numcnt
Definition at line 84 of file DDCYLN.c.
integer nump
Definition at line 84 of file DDCYLN.c.
integer numpt1
Definition at line 84 of file DDCYLN.c.
integer numsfs
Definition at line 84 of file DDCYLN.c.
integer numsur
Definition at line 84 of file DDCYLN.c.
integer nw
Definition at line 84 of file DDCYLN.c.
integer nwds
Definition at line 84 of file DDCYLN.c.
doublereal ogle[3]
Definition at line 18 of file DDCYLN.c.
doublereal p1[3]
Definition at line 18 of file DDCYLN.c.
doublereal p2[3]
Definition at line 18 of file DDCYLN.c.
doublereal param[6]
Definition at line 18 of file DDCYLN.c.
doublereal past[5]
Definition at line 50 of file DDCYLN.c.
doublereal pi
Definition at line 76 of file DDCYLN.c.
doublereal plncs[5]
Definition at line 67 of file DDCYLN.c.
doublereal plnd[5]
Definition at line 50 of file DDCYLN.c.
doublereal plnd1[5]
Definition at line 67 of file DDCYLN.c.
doublereal plnv[15]
Definition at line 50 of file DDCYLN.c.
doublereal pltst[5]
Definition at line 67 of file DDCYLN.c.
doublereal pmove[3]
Definition at line 28 of file DDCYLN.c.
doublereal r__[6]
Definition at line 18 of file DDCYLN.c.
doublereal ra
Definition at line 28 of file DDCYLN.c.
doublereal rc[5]
Definition at line 50 of file DDCYLN.c.
doublereal rc1
Definition at line 28 of file DDCYLN.c.
doublereal rdrn
Definition at line 18 of file DDCYLN.c.
doublereal refpnt[3]
Definition at line 18 of file DDCYLN.c.
doublereal ri[8]
Definition at line 43 of file DDCYLN.c.
doublereal s[5]
Definition at line 50 of file DDCYLN.c.
doublereal sagl
Definition at line 28 of file DDCYLN.c.
doublereal save[5]
Definition at line 50 of file DDCYLN.c.
doublereal savpar[4]
Definition at line 18 of file DDCYLN.c.
doublereal seg[9]
Definition at line 18 of file DDCYLN.c.
doublereal sfvct[15]
Definition at line 50 of file DDCYLN.c.
doublereal sk[15]
Definition at line 50 of file DDCYLN.c.
doublereal slope
Definition at line 18 of file DDCYLN.c.
doublereal slx[15]
Definition at line 50 of file DDCYLN.c.
doublereal sn[15]
Definition at line 50 of file DDCYLN.c.
doublereal snk[15]
Definition at line 50 of file DDCYLN.c.
doublereal snl[15]
Definition at line 50 of file DDCYLN.c.
doublereal sp[15]
Definition at line 50 of file DDCYLN.c.
doublereal spk[15]
Definition at line 50 of file DDCYLN.c.
doublereal spl[15]
Definition at line 50 of file DDCYLN.c.
doublereal sqroot
Definition at line 18 of file DDCYLN.c.
doublereal stck[5]
Definition at line 67 of file DDCYLN.c.
doublereal stck1[5]
Definition at line 67 of file DDCYLN.c.
doublereal stck2[5]
Definition at line 67 of file DDCYLN.c.
doublereal stckn[5]
Definition at line 67 of file DDCYLN.c.
doublereal strtno
Definition at line 28 of file DDCYLN.c.
doublereal surd
Definition at line 28 of file DDCYLN.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 28 of file DDCYLN.c.
doublereal tak[3]
Definition at line 28 of file DDCYLN.c.
doublereal tal[3]
Definition at line 28 of file DDCYLN.c.
doublereal tangl
Definition at line 18 of file DDCYLN.c.
doublereal tanhi[8]
Definition at line 43 of file DDCYLN.c.
doublereal tanlo[8]
Definition at line 43 of file DDCYLN.c.
doublereal tau[5]
Definition at line 50 of file DDCYLN.c.
doublereal tau1[5]
Definition at line 50 of file DDCYLN.c.
doublereal tau2[5]
Definition at line 50 of file DDCYLN.c.
doublereal tcont[9]
Definition at line 43 of file DDCYLN.c.
doublereal te[3]
Definition at line 28 of file DDCYLN.c.
doublereal tee[15]
Definition at line 67 of file DDCYLN.c.
doublereal tek[3]
Definition at line 28 of file DDCYLN.c.
doublereal tel[3]
Definition at line 28 of file DDCYLN.c.
doublereal tem[10]
Definition at line 28 of file DDCYLN.c.
doublereal temp[24]
Definition at line 28 of file DDCYLN.c.
doublereal tes[3]
Definition at line 18 of file DDCYLN.c.
doublereal tew[3]
Definition at line 18 of file DDCYLN.c.
doublereal th[5]
Definition at line 50 of file DDCYLN.c.
doublereal ti[3]
Definition at line 28 of file DDCYLN.c.
doublereal tik[3]
Definition at line 28 of file DDCYLN.c.
doublereal til[3]
Definition at line 28 of file DDCYLN.c.
doublereal tlhit
Definition at line 28 of file DDCYLN.c.
doublereal tlhite[8]
Definition at line 43 of file DDCYLN.c.
doublereal tlinc[9]
Definition at line 43 of file DDCYLN.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file DDCYLN.c.
doublereal tn[15]
Definition at line 50 of file DDCYLN.c.
doublereal tnl[15]
Definition at line 67 of file DDCYLN.c.
doublereal toolht[15]
Definition at line 50 of file DDCYLN.c.
doublereal toolwd[5]
Definition at line 50 of file DDCYLN.c.
doublereal tp[15]
Definition at line 50 of file DDCYLN.c.
doublereal tpk[15]
Definition at line 50 of file DDCYLN.c.
doublereal u1[15]
Definition at line 50 of file DDCYLN.c.
doublereal u1k[15]
Definition at line 50 of file DDCYLN.c.
doublereal u2[3]
Definition at line 18 of file DDCYLN.c.
doublereal umax[8]
Definition at line 43 of file DDCYLN.c.
doublereal unn
Definition at line 18 of file DDCYLN.c.
doublereal upp
Definition at line 18 of file DDCYLN.c.
doublereal uvec[3]
Definition at line 18 of file DDCYLN.c.
doublereal v[3]
Definition at line 18 of file DDCYLN.c.
doublereal varble[5]
Definition at line 50 of file DDCYLN.c.
doublereal vint
Definition at line 18 of file DDCYLN.c.
doublereal vl
Definition at line 18 of file DDCYLN.c.
doublereal vndir[15]
Definition at line 50 of file DDCYLN.c.
doublereal vnn
Definition at line 18 of file DDCYLN.c.
doublereal vpp
Definition at line 18 of file DDCYLN.c.
doublereal vt[15]
Definition at line 50 of file DDCYLN.c.
doublereal vtem
Definition at line 28 of file DDCYLN.c.
doublereal z0
Definition at line 76 of file DDCYLN.c.
doublereal z1
Definition at line 76 of file DDCYLN.c.
doublereal z10
Definition at line 76 of file DDCYLN.c.
doublereal z11em1
Definition at line 76 of file DDCYLN.c.
doublereal z12em1
Definition at line 76 of file DDCYLN.c.
doublereal z1e38
Definition at line 76 of file DDCYLN.c.
doublereal z1e6
Definition at line 76 of file DDCYLN.c.
doublereal z1em1
Definition at line 76 of file DDCYLN.c.
doublereal z1em2
Definition at line 76 of file DDCYLN.c.
doublereal z1em3
Definition at line 76 of file DDCYLN.c.
doublereal z1em5
Definition at line 76 of file DDCYLN.c.
doublereal z1em6
Definition at line 76 of file DDCYLN.c.
doublereal z1em7
Definition at line 76 of file DDCYLN.c.
doublereal z1em9
Definition at line 76 of file DDCYLN.c.
doublereal z2
Definition at line 76 of file DDCYLN.c.
doublereal z3
Definition at line 76 of file DDCYLN.c.
doublereal z5
Definition at line 76 of file DDCYLN.c.
doublereal z5em1
Definition at line 76 of file DDCYLN.c.
doublereal z5em6
Definition at line 76 of file DDCYLN.c.
doublereal z6em1
Definition at line 76 of file DDCYLN.c.
doublereal z90
Definition at line 76 of file DDCYLN.c.
doublereal z9em1
Definition at line 76 of file DDCYLN.c.
doublereal z__[5]
Definition at line 50 of file DDCYLN.c.
doublereal zl
Definition at line 18 of file DDCYLN.c.
doublereal zl1
Definition at line 18 of file DDCYLN.c.
doublereal zlnorm[3]
Definition at line 18 of file DDCYLN.c.
doublereal zlpnt[3]
Definition at line 18 of file DDCYLN.c.
doublereal zm1
Definition at line 76 of file DDCYLN.c.
struct { ... } znumbr_