My Project: DDPARS.c File Reference
DDPARS.c File Reference
#include "f2c.h"
Macros
#define ldef_1 ldef_
#define _BLNK__1 _BLNK__
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int ddpars_ (doublereal *pcanon)
Variables
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
doublereal com [36000]
} _BLNK__
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 28 of file DDPARS.c.
Referenced by ddpars_().
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define ldef_1 ldef_
Definition at line 22 of file DDPARS.c.
Referenced by ddpars_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
Function Documentation
int ddpars_ (doublereal * pcanon)
Definition at line 32 of file DDPARS.c.
References _BLNK__1, ddpara_(), ldef_1, u, v, and xcanon_().
Referenced by ajundd_(), and ddst_().
 {
     /* Local variables */
     static doublereal u, v;
     static integer iu, iv;
 #define can ((doublereal *)&_BLNK__1 + 40)
 #define canon ((doublereal *)&_BLNK__1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int ddpara_(doublereal *, doublereal *);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern integer xcanon_(integer *);
 /*  * DDPARS *  VAX-11 FORTRAN 77 VERSION  29.8.86  E.MCLELLAN */
 /*  PURPOSE     TO SET THE ADDRESSES OF THE PARAMETERS U AND V */
 /*              IN THE ARGUMENT LIST FOR A CALL TO DDPARA AND */
 /*              TO SERVE AS A DISPATCHER BETWEEN DDST AND DDPARA */
 /*  CALLING SEQUENCE */
 /*              CALL DDPARS(PCANON) */
 /*  ARGUMENTS */
 /*              PCANON   ARRAY CONTAINING THE CANONICAL FORM OF */
 /*                      A PARAMTRIC SURFACE */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /* .....PICK UP VIRTUAL ADDRESSES OF U AND V FROM PCANON ARRAY */
     /* Parameter adjustments */
     --pcanon;
     /* Function Body */
     iu = (integer) pcanon[2];
     iv = (integer) pcanon[3];
 /* .....CONVERT TO ACTUAL ADDRESSES */
     if (ldef_1.canflg) {
     iu = xcanon_(&iu);
     }
     u = _BLNK__1.com[iu - 1];
     if (ldef_1.canflg) {
     iv = xcanon_(&iv);
     }
     v = _BLNK__1.com[iv - 1];
 /* .....CALL DDPARA(U,V) */
     ddpara_(&u, &v);
     return 0;
 } /* ddpars_ */
Variable Documentation
struct { ... } _BLNK__
logical altmlt
Definition at line 18 of file DDPARS.c.
logical bnderr
Definition at line 18 of file DDPARS.c.
logical boundf
Definition at line 18 of file DDPARS.c.
logical canflg
Definition at line 18 of file DDPARS.c.
doublereal com[36000]
Definition at line 25 of file DDPARS.c.
logical jcs
Definition at line 18 of file DDPARS.c.
logical jds
Definition at line 18 of file DDPARS.c.
struct { ... } ldef_
logical pchlst
Definition at line 18 of file DDPARS.c.
logical prnton
Definition at line 18 of file DDPARS.c.
logical refflg
Definition at line 18 of file DDPARS.c.
logical refmot
Definition at line 18 of file DDPARS.c.
logical subflg
Definition at line 18 of file DDPARS.c.
logical tabprt
Definition at line 18 of file DDPARS.c.
logical unflag
Definition at line 18 of file DDPARS.c.
logical zflag
Definition at line 18 of file DDPARS.c.