My Project: DDPLAN.c File Reference
DDPLAN.c File Reference
#include "f2c.h"
Macros
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int ddplan_ (doublereal *srface)
Variables
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
Macro Definition Documentation
#define charct_1 charct_
Definition at line 30 of file DDPLAN.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define fxcor_1 fxcor_
Definition at line 24 of file DDPLAN.c.
Referenced by ddplan_().
#define ifxcor_1 ifxcor_
Definition at line 97 of file DDPLAN.c.
Referenced by ddplan_().
#define ishr18_1 ishr18_
Definition at line 105 of file DDPLAN.c.
#define isv1_1 isv1_
Definition at line 87 of file DDPLAN.c.
#define isv_1 isv_
Definition at line 80 of file DDPLAN.c.
Referenced by ddplan_().
#define knumbr_1 knumbr_
Definition at line 113 of file DDPLAN.c.
Referenced by ddplan_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sv1_1 sv1_
Definition at line 63 of file DDPLAN.c.
#define sv_1 sv_
Definition at line 54 of file DDPLAN.c.
Referenced by ddplan_().
#define tlldat_1 tlldat_
Definition at line 37 of file DDPLAN.c.
#define znumbr_1 znumbr_
Definition at line 71 of file DDPLAN.c.
Referenced by ddplan_().
Function Documentation
int ddplan_ (doublereal * srface)
Definition at line 119 of file DDPLAN.c.
References fxcor_1, ifxcor_1, isv_1, knumbr_1, srface, sv_1, and znumbr_1.
Referenced by ajundd_(), ddrlsr_(), ddst_(), and radar_().
 {
     /* Local variables */
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static doublereal adumy;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --srface;
     /* Function Body */
     ifxcor_1.ier = knumbr_1.k0;
     if (ifxcor_1.istrup == 5) {
     goto L5;
     }
     sv_1.s[ifxcor_1.is - 1] = srface[4];
     fxcor_1.tem[0] = sv_1.tn[ifxcor_1.is * 3 - 3] * srface[1] + sv_1.tn[
         ifxcor_1.is * 3 - 2] * srface[2] + sv_1.tn[ifxcor_1.is * 3 - 1] *
         srface[3];
     sv_1.s[ifxcor_1.is - 1] -= sv_1.tp[ifxcor_1.is * 3 - 3] * srface[1] +
         sv_1.tp[ifxcor_1.is * 3 - 2] * srface[2] + sv_1.tp[ifxcor_1.is *
         3 - 1] * srface[3];
     if (abs(fxcor_1.tem[0]) - znumbr_1.z1em7 <= 0.) {
     goto L3;
     } else {
     goto L2;
     }
 L2:
     sv_1.s[ifxcor_1.is - 1] /= fxcor_1.tem[0];
     adumy = (doublereal) isv_1.iop[ifxcor_1.is - 1];
     if (isv_1.iop[ifxcor_1.is - 1] == -1) {
     goto L4;
     }
     if (adumy * sv_1.s[ifxcor_1.is - 1] >= 0.) {
     goto L4;
     } else {
     goto L3;
     }
 L3:
     ifxcor_1.ier = knumbr_1.k1;
     return 0;
 L4:
     if (ifxcor_1.istrup == 4) {
     goto L6;
     }
     sv_1.spl[ifxcor_1.is * 3 - 3] = sv_1.sp[ifxcor_1.is * 3 - 3];
     sv_1.spl[ifxcor_1.is * 3 - 2] = sv_1.sp[ifxcor_1.is * 3 - 2];
     sv_1.spl[ifxcor_1.is * 3 - 1] = sv_1.sp[ifxcor_1.is * 3 - 1];
     sv_1.snl[ifxcor_1.is * 3 - 3] = sv_1.sn[ifxcor_1.is * 3 - 3];
     sv_1.snl[ifxcor_1.is * 3 - 2] = sv_1.sn[ifxcor_1.is * 3 - 2];
     sv_1.snl[ifxcor_1.is * 3 - 1] = sv_1.sn[ifxcor_1.is * 3 - 1];
 L6:
     sv_1.sp[ifxcor_1.is * 3 - 3] = sv_1.tp[ifxcor_1.is * 3 - 3] + sv_1.s[
         ifxcor_1.is - 1] * sv_1.tn[ifxcor_1.is * 3 - 3];
     sv_1.sp[ifxcor_1.is * 3 - 2] = sv_1.tp[ifxcor_1.is * 3 - 2] + sv_1.s[
         ifxcor_1.is - 1] * sv_1.tn[ifxcor_1.is * 3 - 2];
     sv_1.sp[ifxcor_1.is * 3 - 1] = sv_1.tp[ifxcor_1.is * 3 - 1] + sv_1.s[
         ifxcor_1.is - 1] * sv_1.tn[ifxcor_1.is * 3 - 1];
 L5:
     sv_1.sn[ifxcor_1.is * 3 - 3] = srface[1];
     sv_1.sn[ifxcor_1.is * 3 - 2] = srface[2];
     sv_1.sn[ifxcor_1.is * 3 - 1] = srface[3];
     return 0;
 } /* ddplan_ */
Variable Documentation
doublereal alp
Definition at line 18 of file DDPLAN.c.
doublereal ax4[3]
Definition at line 18 of file DDPLAN.c.
doublereal cagl
Definition at line 18 of file DDPLAN.c.
doublereal cc[15]
Definition at line 40 of file DDPLAN.c.
struct { ... } charct_
doublereal corrad[8]
Definition at line 33 of file DDPLAN.c.
doublereal cos1[5]
Definition at line 57 of file DDPLAN.c.
doublereal cplfl[5]
Definition at line 57 of file DDPLAN.c.
doublereal cptst[5]
Definition at line 57 of file DDPLAN.c.
doublereal csd[5]
Definition at line 57 of file DDPLAN.c.
doublereal cutdat[7]
Definition at line 18 of file DDPLAN.c.
doublereal degrad
Definition at line 66 of file DDPLAN.c.
doublereal dplan[15]
Definition at line 57 of file DDPLAN.c.
doublereal dpmax
Definition at line 18 of file DDPLAN.c.
doublereal dpmx1[5]
Definition at line 57 of file DDPLAN.c.
doublereal eps1[5]
Definition at line 40 of file DDPLAN.c.
doublereal eps2[5]
Definition at line 40 of file DDPLAN.c.
doublereal eps3[5]
Definition at line 40 of file DDPLAN.c.
doublereal eps4[5]
Definition at line 40 of file DDPLAN.c.
doublereal eps6[5]
Definition at line 40 of file DDPLAN.c.
doublereal eps8[5]
Definition at line 40 of file DDPLAN.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 18 of file DDPLAN.c.
doublereal hi
Definition at line 18 of file DDPLAN.c.
integer i3dflg
Definition at line 90 of file DDPLAN.c.
integer iaerr
Definition at line 90 of file DDPLAN.c.
integer iafl[5]
Definition at line 74 of file DDPLAN.c.
integer iamdct
Definition at line 100 of file DDPLAN.c.
integer iautps
Definition at line 90 of file DDPLAN.c.
integer ibegin
Definition at line 90 of file DDPLAN.c.
integer ic
Definition at line 90 of file DDPLAN.c.
integer icanon[5]
Definition at line 74 of file DDPLAN.c.
integer icheck
Definition at line 90 of file DDPLAN.c.
integer icl
Definition at line 90 of file DDPLAN.c.
integer ics
Definition at line 90 of file DDPLAN.c.
integer icscnt
Definition at line 90 of file DDPLAN.c.
integer ictdef
Definition at line 90 of file DDPLAN.c.
integer icut
Definition at line 90 of file DDPLAN.c.
integer ids
Definition at line 90 of file DDPLAN.c.
integer ier
Definition at line 90 of file DDPLAN.c.
integer ifar[5]
Definition at line 83 of file DDPLAN.c.
integer ifl4[5]
Definition at line 83 of file DDPLAN.c.
struct { ... } ifxcor_
integer igo
Definition at line 90 of file DDPLAN.c.
integer igoto
Definition at line 90 of file DDPLAN.c.
integer igoug
Definition at line 90 of file DDPLAN.c.
integer igs
Definition at line 90 of file DDPLAN.c.
integer index[5]
Definition at line 74 of file DDPLAN.c.
integer indir__[5]
Definition at line 74 of file DDPLAN.c.
integer inops
Definition at line 90 of file DDPLAN.c.
integer iop[5]
Definition at line 74 of file DDPLAN.c.
integer iopset[5]
Definition at line 74 of file DDPLAN.c.
integer ipdpl
Definition at line 100 of file DDPLAN.c.
integer ipl[5]
Definition at line 74 of file DDPLAN.c.
integer ips
Definition at line 90 of file DDPLAN.c.
integer ipsdef
Definition at line 90 of file DDPLAN.c.
integer ipt
Definition at line 100 of file DDPLAN.c.
integer ipt1
Definition at line 90 of file DDPLAN.c.
integer is
Definition at line 90 of file DDPLAN.c.
integer iseg
Definition at line 90 of file DDPLAN.c.
integer iseqno
Definition at line 90 of file DDPLAN.c.
integer isfidn[5]
Definition at line 74 of file DDPLAN.c.
integer isftyp[5]
Definition at line 74 of file DDPLAN.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 74 of file DDPLAN.c.
integer isrch
Definition at line 90 of file DDPLAN.c.
integer istrup
Definition at line 90 of file DDPLAN.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 74 of file DDPLAN.c.
integer it
Definition at line 90 of file DDPLAN.c.
integer itlon[5]
Definition at line 74 of file DDPLAN.c.
integer itseg[5]
Definition at line 74 of file DDPLAN.c.
integer itsegk[5]
Definition at line 74 of file DDPLAN.c.
integer iunfl[5]
Definition at line 74 of file DDPLAN.c.
integer iws
Definition at line 100 of file DDPLAN.c.
integer j10
Definition at line 100 of file DDPLAN.c.
integer j12
Definition at line 100 of file DDPLAN.c.
integer j13
Definition at line 100 of file DDPLAN.c.
integer j20[5]
Definition at line 83 of file DDPLAN.c.
integer j21[5]
Definition at line 83 of file DDPLAN.c.
integer j22[5]
Definition at line 83 of file DDPLAN.c.
integer j23[5]
Definition at line 83 of file DDPLAN.c.
integer j50[5]
Definition at line 83 of file DDPLAN.c.
integer j51[5]
Definition at line 83 of file DDPLAN.c.
integer j54
Definition at line 100 of file DDPLAN.c.
integer jbr
Definition at line 90 of file DDPLAN.c.
integer jckr
Definition at line 100 of file DDPLAN.c.
integer jcnt1
Definition at line 100 of file DDPLAN.c.
integer jcnt2
Definition at line 100 of file DDPLAN.c.
integer jcnt3
Definition at line 100 of file DDPLAN.c.
integer jcpr
Definition at line 100 of file DDPLAN.c.
integer jcr
Definition at line 100 of file DDPLAN.c.
integer jdr
Definition at line 100 of file DDPLAN.c.
integer jent[5]
Definition at line 74 of file DDPLAN.c.
integer jfind
Definition at line 100 of file DDPLAN.c.
integer jgr
Definition at line 100 of file DDPLAN.c.
integer jiops[5]
Definition at line 74 of file DDPLAN.c.
integer jmin
Definition at line 100 of file DDPLAN.c.
integer jminr
Definition at line 100 of file DDPLAN.c.
integer jph[5]
Definition at line 83 of file DDPLAN.c.
integer jpr
Definition at line 100 of file DDPLAN.c.
integer jpxr
Definition at line 100 of file DDPLAN.c.
integer jsw
Definition at line 90 of file DDPLAN.c.
integer jtkf
Definition at line 100 of file DDPLAN.c.
integer jtlflg[5]
Definition at line 74 of file DDPLAN.c.
integer jtn[5]
Definition at line 74 of file DDPLAN.c.
integer jtr
Definition at line 100 of file DDPLAN.c.
integer ju1[5]
Definition at line 74 of file DDPLAN.c.
integer k0
Definition at line 108 of file DDPLAN.c.
integer k1
Definition at line 108 of file DDPLAN.c.
integer k10
Definition at line 108 of file DDPLAN.c.
integer k1013
Definition at line 108 of file DDPLAN.c.
integer k12
Definition at line 108 of file DDPLAN.c.
integer k13
Definition at line 108 of file DDPLAN.c.
integer k15
Definition at line 108 of file DDPLAN.c.
integer k16
Definition at line 108 of file DDPLAN.c.
integer k18
Definition at line 108 of file DDPLAN.c.
integer k19
Definition at line 108 of file DDPLAN.c.
integer k1e4
Definition at line 108 of file DDPLAN.c.
integer k1e6
Definition at line 108 of file DDPLAN.c.
integer k2
Definition at line 108 of file DDPLAN.c.
integer k23
Definition at line 108 of file DDPLAN.c.
integer k24
Definition at line 108 of file DDPLAN.c.
integer k25
Definition at line 108 of file DDPLAN.c.
integer k26
Definition at line 108 of file DDPLAN.c.
integer k27
Definition at line 108 of file DDPLAN.c.
integer k29
Definition at line 108 of file DDPLAN.c.
integer k3
Definition at line 108 of file DDPLAN.c.
integer k30
Definition at line 108 of file DDPLAN.c.
integer k31
Definition at line 108 of file DDPLAN.c.
integer k32
Definition at line 108 of file DDPLAN.c.
integer k33
Definition at line 108 of file DDPLAN.c.
integer k34
Definition at line 108 of file DDPLAN.c.
integer k4
Definition at line 108 of file DDPLAN.c.
integer k44
Definition at line 108 of file DDPLAN.c.
integer k45
Definition at line 108 of file DDPLAN.c.
integer k46
Definition at line 108 of file DDPLAN.c.
integer k47
Definition at line 108 of file DDPLAN.c.
integer k48
Definition at line 108 of file DDPLAN.c.
integer k5
Definition at line 108 of file DDPLAN.c.
integer k50
Definition at line 108 of file DDPLAN.c.
integer k51
Definition at line 108 of file DDPLAN.c.
integer k52
Definition at line 108 of file DDPLAN.c.
integer k6
Definition at line 108 of file DDPLAN.c.
integer k7
Definition at line 108 of file DDPLAN.c.
integer k8
Definition at line 108 of file DDPLAN.c.
integer k9
Definition at line 108 of file DDPLAN.c.
integer km1
Definition at line 108 of file DDPLAN.c.
struct { ... } knumbr_
integer limfl[5]
Definition at line 74 of file DDPLAN.c.
integer lsv
Definition at line 90 of file DDPLAN.c.
integer lsv1
Definition at line 90 of file DDPLAN.c.
integer mantax
Definition at line 90 of file DDPLAN.c.
integer mdic
Definition at line 100 of file DDPLAN.c.
char modfer[6]
Definition at line 27 of file DDPLAN.c.
integer motmod
Definition at line 90 of file DDPLAN.c.
integer msav
Definition at line 90 of file DDPLAN.c.
integer mulout
Definition at line 90 of file DDPLAN.c.
integer nmbseg
Definition at line 90 of file DDPLAN.c.
integer nmpnts
Definition at line 90 of file DDPLAN.c.
integer notan[5]
Definition at line 83 of file DDPLAN.c.
integer nrec
Definition at line 90 of file DDPLAN.c.
integer numax
Definition at line 90 of file DDPLAN.c.
integer numcnt
Definition at line 90 of file DDPLAN.c.
integer nump
Definition at line 90 of file DDPLAN.c.
integer numpt1
Definition at line 90 of file DDPLAN.c.
integer numsfs
Definition at line 90 of file DDPLAN.c.
integer numsur
Definition at line 90 of file DDPLAN.c.
integer nw
Definition at line 90 of file DDPLAN.c.
integer nwds
Definition at line 90 of file DDPLAN.c.
doublereal past[5]
Definition at line 40 of file DDPLAN.c.
doublereal pi
Definition at line 66 of file DDPLAN.c.
doublereal plncs[5]
Definition at line 57 of file DDPLAN.c.
doublereal plnd[5]
Definition at line 40 of file DDPLAN.c.
doublereal plnd1[5]
Definition at line 57 of file DDPLAN.c.
doublereal plnv[15]
Definition at line 40 of file DDPLAN.c.
doublereal pltst[5]
Definition at line 57 of file DDPLAN.c.
doublereal pmove[3]
Definition at line 18 of file DDPLAN.c.
doublereal ra
Definition at line 18 of file DDPLAN.c.
doublereal rc[5]
Definition at line 40 of file DDPLAN.c.
doublereal rc1
Definition at line 18 of file DDPLAN.c.
doublereal ri[8]
Definition at line 33 of file DDPLAN.c.
doublereal s[5]
Definition at line 40 of file DDPLAN.c.
doublereal sagl
Definition at line 18 of file DDPLAN.c.
doublereal save[5]
Definition at line 40 of file DDPLAN.c.
doublereal sfvct[15]
Definition at line 40 of file DDPLAN.c.
doublereal sk[15]
Definition at line 40 of file DDPLAN.c.
doublereal slx[15]
Definition at line 40 of file DDPLAN.c.
doublereal sn[15]
Definition at line 40 of file DDPLAN.c.
doublereal snk[15]
Definition at line 40 of file DDPLAN.c.
doublereal snl[15]
Definition at line 40 of file DDPLAN.c.
doublereal sp[15]
Definition at line 40 of file DDPLAN.c.
doublereal spk[15]
Definition at line 40 of file DDPLAN.c.
doublereal spl[15]
Definition at line 40 of file DDPLAN.c.
doublereal stck[5]
Definition at line 57 of file DDPLAN.c.
doublereal stck1[5]
Definition at line 57 of file DDPLAN.c.
doublereal stck2[5]
Definition at line 57 of file DDPLAN.c.
doublereal stckn[5]
Definition at line 57 of file DDPLAN.c.
doublereal strtno
Definition at line 18 of file DDPLAN.c.
doublereal surd
Definition at line 18 of file DDPLAN.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 18 of file DDPLAN.c.
doublereal tak[3]
Definition at line 18 of file DDPLAN.c.
doublereal tal[3]
Definition at line 18 of file DDPLAN.c.
doublereal tanhi[8]
Definition at line 33 of file DDPLAN.c.
doublereal tanlo[8]
Definition at line 33 of file DDPLAN.c.
doublereal tau[5]
Definition at line 40 of file DDPLAN.c.
doublereal tau1[5]
Definition at line 40 of file DDPLAN.c.
doublereal tau2[5]
Definition at line 40 of file DDPLAN.c.
doublereal tcont[9]
Definition at line 33 of file DDPLAN.c.
doublereal te[3]
Definition at line 18 of file DDPLAN.c.
doublereal tee[15]
Definition at line 57 of file DDPLAN.c.
doublereal tek[3]
Definition at line 18 of file DDPLAN.c.
doublereal tel[3]
Definition at line 18 of file DDPLAN.c.
doublereal tem[10]
Definition at line 18 of file DDPLAN.c.
doublereal temp[24]
Definition at line 18 of file DDPLAN.c.
doublereal th[5]
Definition at line 40 of file DDPLAN.c.
doublereal ti[3]
Definition at line 18 of file DDPLAN.c.
doublereal tik[3]
Definition at line 18 of file DDPLAN.c.
doublereal til[3]
Definition at line 18 of file DDPLAN.c.
doublereal tlhit
Definition at line 18 of file DDPLAN.c.
doublereal tlhite[8]
Definition at line 33 of file DDPLAN.c.
doublereal tlinc[9]
Definition at line 33 of file DDPLAN.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 18 of file DDPLAN.c.
doublereal tn[15]
Definition at line 40 of file DDPLAN.c.
doublereal tnl[15]
Definition at line 57 of file DDPLAN.c.
doublereal toolht[15]
Definition at line 40 of file DDPLAN.c.
doublereal toolwd[5]
Definition at line 40 of file DDPLAN.c.
doublereal tp[15]
Definition at line 40 of file DDPLAN.c.
doublereal tpk[15]
Definition at line 40 of file DDPLAN.c.
doublereal u1[15]
Definition at line 40 of file DDPLAN.c.
doublereal u1k[15]
Definition at line 40 of file DDPLAN.c.
doublereal umax[8]
Definition at line 33 of file DDPLAN.c.
doublereal varble[5]
Definition at line 40 of file DDPLAN.c.
doublereal vndir[15]
Definition at line 40 of file DDPLAN.c.
doublereal vt[15]
Definition at line 40 of file DDPLAN.c.
doublereal vtem
Definition at line 18 of file DDPLAN.c.
doublereal z0
Definition at line 66 of file DDPLAN.c.
doublereal z1
Definition at line 66 of file DDPLAN.c.
doublereal z10
Definition at line 66 of file DDPLAN.c.
doublereal z11em1
Definition at line 66 of file DDPLAN.c.
doublereal z12em1
Definition at line 66 of file DDPLAN.c.
doublereal z1e38
Definition at line 66 of file DDPLAN.c.
doublereal z1e6
Definition at line 66 of file DDPLAN.c.
doublereal z1em1
Definition at line 66 of file DDPLAN.c.
doublereal z1em2
Definition at line 66 of file DDPLAN.c.
doublereal z1em3
Definition at line 66 of file DDPLAN.c.
doublereal z1em5
Definition at line 66 of file DDPLAN.c.
doublereal z1em6
Definition at line 66 of file DDPLAN.c.
doublereal z1em7
Definition at line 66 of file DDPLAN.c.
doublereal z1em9
Definition at line 66 of file DDPLAN.c.
doublereal z2
Definition at line 66 of file DDPLAN.c.
doublereal z3
Definition at line 66 of file DDPLAN.c.
doublereal z5
Definition at line 66 of file DDPLAN.c.
doublereal z5em1
Definition at line 66 of file DDPLAN.c.
doublereal z5em6
Definition at line 66 of file DDPLAN.c.
doublereal z6em1
Definition at line 66 of file DDPLAN.c.
doublereal z90
Definition at line 66 of file DDPLAN.c.
doublereal z9em1
Definition at line 66 of file DDPLAN.c.
doublereal z__[5]
Definition at line 40 of file DDPLAN.c.
doublereal zm1
Definition at line 66 of file DDPLAN.c.
struct { ... } znumbr_