My Project: DDQUAD.c File Reference
DDQUAD.c File Reference
#include "f2c.h"
Macros
#define dshar4_1 dshar4_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int ddquad_ (doublereal *srface)
Variables
struct {
doublereal a
doublereal b
doublereal c__
doublereal cendis
doublereal cmove [3]
doublereal com1
doublereal com4
doublereal dir [3]
doublereal dp
doublereal dpe
doublereal dpcnt
doublereal dpi
doublereal dpl
doublereal dp1
doublereal d1
doublereal d2a
doublereal flipck
doublereal fwd [3]
doublereal ogle [3]
doublereal p1 [3]
doublereal p2 [3]
doublereal rdrn
doublereal refpnt [3]
doublereal tangl
doublereal tes [3]
doublereal tew [3]
doublereal uvec [3]
doublereal u2 [3]
doublereal v [3]
doublereal vl
doublereal zl
doublereal zlnorm [3]
doublereal zlpnt [3]
doublereal zl1
doublereal param [6]
doublereal r__ [6]
doublereal savpar [4]
doublereal seg [9]
doublereal slope
doublereal sqroot
doublereal unn
doublereal upp
doublereal vint
doublereal vnn
doublereal vpp
} dshar4_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
Macro Definition Documentation
#define charct_1 charct_
Definition at line 40 of file DDQUAD.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dshar4_1 dshar4_
Definition at line 25 of file DDQUAD.c.
Referenced by ddquad_().
#define fxcor_1 fxcor_
Definition at line 34 of file DDQUAD.c.
Referenced by ddquad_().
#define ifxcor_1 ifxcor_
Definition at line 107 of file DDQUAD.c.
Referenced by ddquad_().
#define ishr18_1 ishr18_
Definition at line 115 of file DDQUAD.c.
#define isv1_1 isv1_
Definition at line 97 of file DDQUAD.c.
#define isv_1 isv_
Definition at line 90 of file DDQUAD.c.
Referenced by ddquad_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sv1_1 sv1_
Definition at line 73 of file DDQUAD.c.
#define sv_1 sv_
Definition at line 64 of file DDQUAD.c.
Referenced by ddquad_().
#define tlldat_1 tlldat_
Definition at line 47 of file DDQUAD.c.
#define znumbr_1 znumbr_
Definition at line 81 of file DDQUAD.c.
Referenced by ddquad_().
Function Documentation
int ddquad_ (doublereal * srface)
Definition at line 121 of file DDQUAD.c.
References d__, dshar4_1, fxcor_1, i__, ifxcor_1, isv_1, quad_(), srface, sv_1, vnorm_(), and znumbr_1.
Referenced by ajundd_(), ddrlsr_(), ddst_(), and radar_().
 {
     /* System generated locals */
     doublereal d__1, d__2, d__3;
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     static doublereal d__, e;
     static integer i__;
     extern /* Subroutine */ int quad_(void);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     extern /* Subroutine */ int vnorm_(doublereal *, doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
     /* Parameter adjustments */
     --srface;
     /* Function Body */
     ifxcor_1.ier = 0;
     if (ifxcor_1.istrup == 5) {
     goto L1015;
     }
     if (ifxcor_1.jsw == 5 || ifxcor_1.jsw == 9) {
     goto L5;
     }
     for (i__ = 1; i__ <= 10; ++i__) {
 /* L1: */
     fxcor_1.tem[i__ - 1] = srface[i__];
     }
 /* Computing 2nd power */
     d__1 = sv_1.tn[ifxcor_1.is * 3 - 3];
 /* Computing 2nd power */
     d__2 = sv_1.tn[ifxcor_1.is * 3 - 2];
 /* Computing 2nd power */
     d__3 = sv_1.tn[ifxcor_1.is * 3 - 1];
     dshar4_1.a = znumbr_1.z2 * (fxcor_1.tem[5] * sv_1.tn[ifxcor_1.is * 3 - 1]
         * sv_1.tn[ifxcor_1.is * 3 - 3] + fxcor_1.tem[6] * sv_1.tn[
         ifxcor_1.is * 3 - 3] * sv_1.tn[ifxcor_1.is * 3 - 2] + fxcor_1.tem[
         4] * sv_1.tn[ifxcor_1.is * 3 - 2] * sv_1.tn[ifxcor_1.is * 3 - 1])
         + d__1 * d__1 * fxcor_1.tem[0] + d__2 * d__2 * fxcor_1.tem[1] +
         d__3 * d__3 * fxcor_1.tem[2];
     dshar4_1.b = (fxcor_1.tem[0] * sv_1.tn[ifxcor_1.is * 3 - 3] + fxcor_1.tem[
         6] * sv_1.tn[ifxcor_1.is * 3 - 2] + fxcor_1.tem[5] * sv_1.tn[
         ifxcor_1.is * 3 - 1]) * sv_1.tp[ifxcor_1.is * 3 - 3] + (
         fxcor_1.tem[6] * sv_1.tn[ifxcor_1.is * 3 - 3] + fxcor_1.tem[1] *
         sv_1.tn[ifxcor_1.is * 3 - 2] + fxcor_1.tem[4] * sv_1.tn[
         ifxcor_1.is * 3 - 1]) * sv_1.tp[ifxcor_1.is * 3 - 2] + (
         fxcor_1.tem[5] * sv_1.tn[ifxcor_1.is * 3 - 3] + fxcor_1.tem[4] *
         sv_1.tn[ifxcor_1.is * 3 - 2] + fxcor_1.tem[2] * sv_1.tn[
         ifxcor_1.is * 3 - 1]) * sv_1.tp[ifxcor_1.is * 3 - 1] + sv_1.tn[
         ifxcor_1.is * 3 - 3] * fxcor_1.tem[7] + sv_1.tn[ifxcor_1.is * 3 -
         2] * fxcor_1.tem[8] + sv_1.tn[ifxcor_1.is * 3 - 1] * fxcor_1.tem[
         9];
 /* Computing 2nd power */
     d__1 = sv_1.tp[ifxcor_1.is * 3 - 3];
 /* Computing 2nd power */
     d__2 = sv_1.tp[ifxcor_1.is * 3 - 2];
 /* Computing 2nd power */
     d__3 = sv_1.tp[ifxcor_1.is * 3 - 1];
     dshar4_1.c__ = znumbr_1.z2 * (fxcor_1.tem[5] * sv_1.tp[ifxcor_1.is * 3 -
         1] * sv_1.tp[ifxcor_1.is * 3 - 3] + fxcor_1.tem[6] * sv_1.tp[
         ifxcor_1.is * 3 - 3] * sv_1.tp[ifxcor_1.is * 3 - 2] + fxcor_1.tem[
         4] * sv_1.tp[ifxcor_1.is * 3 - 2] * sv_1.tp[ifxcor_1.is * 3 - 1]
         + sv_1.tp[ifxcor_1.is * 3 - 3] * fxcor_1.tem[7] + sv_1.tp[
         ifxcor_1.is * 3 - 2] * fxcor_1.tem[8] + sv_1.tp[ifxcor_1.is * 3 -
         1] * fxcor_1.tem[9]) + d__1 * d__1 * fxcor_1.tem[0] + d__2 * d__2
         * fxcor_1.tem[1] + d__3 * d__3 * fxcor_1.tem[2] + fxcor_1.tem[3];
     goto L1000;
 L5:
     dshar4_1.a = sv_1.tn[ifxcor_1.is * 3 - 3] * sv_1.tn[ifxcor_1.is * 3 - 3]
         + sv_1.tn[ifxcor_1.is * 3 - 2] * sv_1.tn[ifxcor_1.is * 3 - 2] +
         sv_1.tn[ifxcor_1.is * 3 - 1] * sv_1.tn[ifxcor_1.is * 3 - 1];
     fxcor_1.tem[0] = sv_1.tp[ifxcor_1.is * 3 - 3] - srface[1];
     fxcor_1.tem[1] = sv_1.tp[ifxcor_1.is * 3 - 2] - srface[2];
     fxcor_1.tem[2] = sv_1.tp[ifxcor_1.is * 3 - 1] - srface[3];
     dshar4_1.b = fxcor_1.tem[0] * sv_1.tn[ifxcor_1.is * 3 - 3] + fxcor_1.tem[
         1] * sv_1.tn[ifxcor_1.is * 3 - 2] + fxcor_1.tem[2] * sv_1.tn[
         ifxcor_1.is * 3 - 1];
     e = fxcor_1.tem[0] * fxcor_1.tem[0] + fxcor_1.tem[1] * fxcor_1.tem[1] +
         fxcor_1.tem[2] * fxcor_1.tem[2];
     if (ifxcor_1.jsw == 9) {
     goto L10;
     }
     dshar4_1.c__ = e - srface[4] * srface[4];
     goto L1000;
 L10:
     fxcor_1.tem[3] = srface[7] * srface[7];
     fxcor_1.tem[4] = dshar4_1.a;
     dshar4_1.a = sv_1.tn[ifxcor_1.is * 3 - 3] * srface[4] + sv_1.tn[
         ifxcor_1.is * 3 - 2] * srface[5] + sv_1.tn[ifxcor_1.is * 3 - 1] *
         srface[6];
     d__ = fxcor_1.tem[0] * srface[4] + fxcor_1.tem[1] * srface[5] +
         fxcor_1.tem[2] * srface[6];
     dshar4_1.b = dshar4_1.a * d__ - fxcor_1.tem[3] * dshar4_1.b;
     dshar4_1.a = dshar4_1.a * dshar4_1.a - fxcor_1.tem[4] * fxcor_1.tem[3];
     dshar4_1.c__ = d__ * d__ - fxcor_1.tem[3] * e;
     quad_();
     if (ifxcor_1.ier <= 0) {
     goto L20;
     } else {
     goto L3000;
     }
 L20:
     if ((fxcor_1.tem[0] + sv_1.s[ifxcor_1.is - 1] * sv_1.tn[ifxcor_1.is * 3 -
         3]) * srface[4] + (fxcor_1.tem[1] + sv_1.s[ifxcor_1.is - 1] *
         sv_1.tn[ifxcor_1.is * 3 - 2]) * srface[5] + (fxcor_1.tem[2] +
         sv_1.s[ifxcor_1.is - 1] * sv_1.tn[ifxcor_1.is * 3 - 1]) * srface[
         6] <= 0.) {
     goto L25;
     } else {
     goto L1011;
     }
 /*     **SOLUTION INVALID** */
 L25:
     if (fxcor_1.surd < 0.) {
     goto L30;
     } else if (fxcor_1.surd == 0) {
     goto L50;
     } else {
     goto L40;
     }
 L30:
     if (isv_1.iop[ifxcor_1.is - 1] <= 0) {
     goto L40;
     } else {
     goto L50;
     }
 L40:
     sv_1.s[ifxcor_1.is - 1] = fxcor_1.surd;
     fxcor_1.surd = znumbr_1.z0;
     goto L20;
 L50:
     ifxcor_1.ier = 1;
     goto L3000;
 L1000:
     quad_();
 /* L1010: */
     if (ifxcor_1.ier == 1) {
     goto L3000;
     }
 L1011:
     if (ifxcor_1.istrup == 4) {
     goto L1012;
     }
     sv_1.spl[ifxcor_1.is * 3 - 3] = sv_1.sp[ifxcor_1.is * 3 - 3];
     sv_1.spl[ifxcor_1.is * 3 - 2] = sv_1.sp[ifxcor_1.is * 3 - 2];
     sv_1.spl[ifxcor_1.is * 3 - 1] = sv_1.sp[ifxcor_1.is * 3 - 1];
     sv_1.snl[ifxcor_1.is * 3 - 3] = sv_1.sn[ifxcor_1.is * 3 - 3];
     sv_1.snl[ifxcor_1.is * 3 - 2] = sv_1.sn[ifxcor_1.is * 3 - 2];
     sv_1.snl[ifxcor_1.is * 3 - 1] = sv_1.sn[ifxcor_1.is * 3 - 1];
 L1012:
     sv_1.sp[ifxcor_1.is * 3 - 3] = sv_1.tp[ifxcor_1.is * 3 - 3] + sv_1.s[
         ifxcor_1.is - 1] * sv_1.tn[ifxcor_1.is * 3 - 3];
     sv_1.sp[ifxcor_1.is * 3 - 2] = sv_1.tp[ifxcor_1.is * 3 - 2] + sv_1.s[
         ifxcor_1.is - 1] * sv_1.tn[ifxcor_1.is * 3 - 2];
     sv_1.sp[ifxcor_1.is * 3 - 1] = sv_1.tp[ifxcor_1.is * 3 - 1] + sv_1.s[
         ifxcor_1.is - 1] * sv_1.tn[ifxcor_1.is * 3 - 1];
 L1015:
     if (ifxcor_1.jsw == 5 || ifxcor_1.jsw == 9) {
     goto L2000;
     }
     fxcor_1.tem[0] = srface[1] * sv_1.sp[ifxcor_1.is * 3 - 3] + srface[7] *
         sv_1.sp[ifxcor_1.is * 3 - 2] + srface[6] * sv_1.sp[ifxcor_1.is *
         3 - 1] + srface[8];
     fxcor_1.tem[1] = srface[7] * sv_1.sp[ifxcor_1.is * 3 - 3] + srface[2] *
         sv_1.sp[ifxcor_1.is * 3 - 2] + srface[5] * sv_1.sp[ifxcor_1.is *
         3 - 1] + srface[9];
     fxcor_1.tem[2] = srface[6] * sv_1.sp[ifxcor_1.is * 3 - 3] + srface[5] *
         sv_1.sp[ifxcor_1.is * 3 - 2] + srface[3] * sv_1.sp[ifxcor_1.is *
         3 - 1] + srface[10];
     vnorm_(fxcor_1.tem, &sv_1.sn[ifxcor_1.is * 3 - 3]);
     goto L3000;
 L2000:
     sv_1.sn[ifxcor_1.is * 3 - 3] = sv_1.sp[ifxcor_1.is * 3 - 3] - srface[1];
     sv_1.sn[ifxcor_1.is * 3 - 2] = sv_1.sp[ifxcor_1.is * 3 - 2] - srface[2];
     sv_1.sn[ifxcor_1.is * 3 - 1] = sv_1.sp[ifxcor_1.is * 3 - 1] - srface[3];
     vnorm_(&sv_1.sn[ifxcor_1.is * 3 - 3], &sv_1.sn[ifxcor_1.is * 3 - 3]);
     if (ifxcor_1.jsw == 5) {
     goto L3000;
     }
     if (ifxcor_1.ier <= 0) {
     goto L2002;
     } else {
     goto L2009;
     }
 L2009:
     ifxcor_1.ier = 0;
     sv_1.sn[ifxcor_1.is * 3 - 3] = -srface[4];
     sv_1.sn[ifxcor_1.is * 3 - 2] = -srface[5];
     sv_1.sn[ifxcor_1.is * 3 - 1] = -srface[6];
     goto L3000;
 L2002:
     fxcor_1.tem[3] = sv_1.sn[ifxcor_1.is * 3 - 3] * srface[4] + sv_1.sn[
         ifxcor_1.is * 3 - 2] * srface[5] + sv_1.sn[ifxcor_1.is * 3 - 1] *
         srface[6];
     fxcor_1.tem[5] = sqrt(znumbr_1.z1 - fxcor_1.tem[3] * fxcor_1.tem[3]);
     fxcor_1.tem[6] = sqrt(znumbr_1.z1 - srface[7] * srface[7]);
     fxcor_1.tem[7] = fxcor_1.tem[3] * srface[7] + fxcor_1.tem[5] *
         fxcor_1.tem[6];
     if (fxcor_1.tem[7] >= 0.) {
     goto L2005;
     } else {
     goto L3000;
     }
 L2005:
     sv_1.sn[ifxcor_1.is * 3 - 3] = (srface[7] * sv_1.sn[ifxcor_1.is * 3 - 3]
         - fxcor_1.tem[7] * srface[4]) / fxcor_1.tem[5];
     sv_1.sn[ifxcor_1.is * 3 - 2] = (srface[7] * sv_1.sn[ifxcor_1.is * 3 - 2]
         - fxcor_1.tem[7] * srface[5]) / fxcor_1.tem[5];
     sv_1.sn[ifxcor_1.is * 3 - 1] = (srface[7] * sv_1.sn[ifxcor_1.is * 3 - 1]
         - fxcor_1.tem[7] * srface[6]) / fxcor_1.tem[5];
 L3000:
     return 0;
 } /* ddquad_ */
Variable Documentation
doublereal a
Definition at line 18 of file DDQUAD.c.
doublereal alp
Definition at line 28 of file DDQUAD.c.
doublereal ax4[3]
Definition at line 28 of file DDQUAD.c.
doublereal b
Definition at line 18 of file DDQUAD.c.
doublereal c__
Definition at line 18 of file DDQUAD.c.
doublereal cagl
Definition at line 28 of file DDQUAD.c.
doublereal cc[15]
Definition at line 50 of file DDQUAD.c.
doublereal cendis
Definition at line 18 of file DDQUAD.c.
struct { ... } charct_
doublereal cmove[3]
Definition at line 18 of file DDQUAD.c.
doublereal com1
Definition at line 18 of file DDQUAD.c.
doublereal com4
Definition at line 18 of file DDQUAD.c.
doublereal corrad[8]
Definition at line 43 of file DDQUAD.c.
doublereal cos1[5]
Definition at line 67 of file DDQUAD.c.
doublereal cplfl[5]
Definition at line 67 of file DDQUAD.c.
doublereal cptst[5]
Definition at line 67 of file DDQUAD.c.
doublereal csd[5]
Definition at line 67 of file DDQUAD.c.
doublereal cutdat[7]
Definition at line 28 of file DDQUAD.c.
doublereal d1
Definition at line 18 of file DDQUAD.c.
doublereal d2a
Definition at line 18 of file DDQUAD.c.
doublereal degrad
Definition at line 76 of file DDQUAD.c.
doublereal dir[3]
Definition at line 18 of file DDQUAD.c.
doublereal dp
Definition at line 18 of file DDQUAD.c.
doublereal dp1
Definition at line 18 of file DDQUAD.c.
doublereal dpcnt
Definition at line 18 of file DDQUAD.c.
doublereal dpe
Definition at line 18 of file DDQUAD.c.
doublereal dpi
Definition at line 18 of file DDQUAD.c.
doublereal dpl
Definition at line 18 of file DDQUAD.c.
doublereal dplan[15]
Definition at line 67 of file DDQUAD.c.
doublereal dpmax
Definition at line 28 of file DDQUAD.c.
doublereal dpmx1[5]
Definition at line 67 of file DDQUAD.c.
struct { ... } dshar4_
doublereal eps1[5]
Definition at line 50 of file DDQUAD.c.
doublereal eps2[5]
Definition at line 50 of file DDQUAD.c.
doublereal eps3[5]
Definition at line 50 of file DDQUAD.c.
doublereal eps4[5]
Definition at line 50 of file DDQUAD.c.
doublereal eps6[5]
Definition at line 50 of file DDQUAD.c.
doublereal eps8[5]
Definition at line 50 of file DDQUAD.c.
doublereal flipck
Definition at line 18 of file DDQUAD.c.
doublereal fwd[3]
Definition at line 18 of file DDQUAD.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file DDQUAD.c.
doublereal hi
Definition at line 28 of file DDQUAD.c.
integer i3dflg
Definition at line 100 of file DDQUAD.c.
integer iaerr
Definition at line 100 of file DDQUAD.c.
integer iafl[5]
Definition at line 84 of file DDQUAD.c.
integer iamdct
Definition at line 110 of file DDQUAD.c.
integer iautps
Definition at line 100 of file DDQUAD.c.
integer ibegin
Definition at line 100 of file DDQUAD.c.
integer ic
Definition at line 100 of file DDQUAD.c.
integer icanon[5]
Definition at line 84 of file DDQUAD.c.
integer icheck
Definition at line 100 of file DDQUAD.c.
integer icl
Definition at line 100 of file DDQUAD.c.
integer ics
Definition at line 100 of file DDQUAD.c.
integer icscnt
Definition at line 100 of file DDQUAD.c.
integer ictdef
Definition at line 100 of file DDQUAD.c.
integer icut
Definition at line 100 of file DDQUAD.c.
integer ids
Definition at line 100 of file DDQUAD.c.
integer ier
Definition at line 100 of file DDQUAD.c.
integer ifar[5]
Definition at line 93 of file DDQUAD.c.
integer ifl4[5]
Definition at line 93 of file DDQUAD.c.
struct { ... } ifxcor_
integer igo
Definition at line 100 of file DDQUAD.c.
integer igoto
Definition at line 100 of file DDQUAD.c.
integer igoug
Definition at line 100 of file DDQUAD.c.
integer igs
Definition at line 100 of file DDQUAD.c.
integer index[5]
Definition at line 84 of file DDQUAD.c.
integer indir__[5]
Definition at line 84 of file DDQUAD.c.
integer inops
Definition at line 100 of file DDQUAD.c.
integer iop[5]
Definition at line 84 of file DDQUAD.c.
integer iopset[5]
Definition at line 84 of file DDQUAD.c.
integer ipdpl
Definition at line 110 of file DDQUAD.c.
integer ipl[5]
Definition at line 84 of file DDQUAD.c.
integer ips
Definition at line 100 of file DDQUAD.c.
integer ipsdef
Definition at line 100 of file DDQUAD.c.
integer ipt
Definition at line 110 of file DDQUAD.c.
integer ipt1
Definition at line 100 of file DDQUAD.c.
integer is
Definition at line 100 of file DDQUAD.c.
integer iseg
Definition at line 100 of file DDQUAD.c.
integer iseqno
Definition at line 100 of file DDQUAD.c.
integer isfidn[5]
Definition at line 84 of file DDQUAD.c.
integer isftyp[5]
Definition at line 84 of file DDQUAD.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 84 of file DDQUAD.c.
integer isrch
Definition at line 100 of file DDQUAD.c.
integer istrup
Definition at line 100 of file DDQUAD.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 84 of file DDQUAD.c.
integer it
Definition at line 100 of file DDQUAD.c.
integer itlon[5]
Definition at line 84 of file DDQUAD.c.
integer itseg[5]
Definition at line 84 of file DDQUAD.c.
integer itsegk[5]
Definition at line 84 of file DDQUAD.c.
integer iunfl[5]
Definition at line 84 of file DDQUAD.c.
integer iws
Definition at line 110 of file DDQUAD.c.
integer j10
Definition at line 110 of file DDQUAD.c.
integer j12
Definition at line 110 of file DDQUAD.c.
integer j13
Definition at line 110 of file DDQUAD.c.
integer j20[5]
Definition at line 93 of file DDQUAD.c.
integer j21[5]
Definition at line 93 of file DDQUAD.c.
integer j22[5]
Definition at line 93 of file DDQUAD.c.
integer j23[5]
Definition at line 93 of file DDQUAD.c.
integer j50[5]
Definition at line 93 of file DDQUAD.c.
integer j51[5]
Definition at line 93 of file DDQUAD.c.
integer j54
Definition at line 110 of file DDQUAD.c.
integer jbr
Definition at line 100 of file DDQUAD.c.
integer jckr
Definition at line 110 of file DDQUAD.c.
integer jcnt1
Definition at line 110 of file DDQUAD.c.
integer jcnt2
Definition at line 110 of file DDQUAD.c.
integer jcnt3
Definition at line 110 of file DDQUAD.c.
integer jcpr
Definition at line 110 of file DDQUAD.c.
integer jcr
Definition at line 110 of file DDQUAD.c.
integer jdr
Definition at line 110 of file DDQUAD.c.
integer jent[5]
Definition at line 84 of file DDQUAD.c.
integer jfind
Definition at line 110 of file DDQUAD.c.
integer jgr
Definition at line 110 of file DDQUAD.c.
integer jiops[5]
Definition at line 84 of file DDQUAD.c.
integer jmin
Definition at line 110 of file DDQUAD.c.
integer jminr
Definition at line 110 of file DDQUAD.c.
integer jph[5]
Definition at line 93 of file DDQUAD.c.
integer jpr
Definition at line 110 of file DDQUAD.c.
integer jpxr
Definition at line 110 of file DDQUAD.c.
integer jsw
Definition at line 100 of file DDQUAD.c.
integer jtkf
Definition at line 110 of file DDQUAD.c.
integer jtlflg[5]
Definition at line 84 of file DDQUAD.c.
integer jtn[5]
Definition at line 84 of file DDQUAD.c.
integer jtr
Definition at line 110 of file DDQUAD.c.
integer ju1[5]
Definition at line 84 of file DDQUAD.c.
integer limfl[5]
Definition at line 84 of file DDQUAD.c.
integer lsv
Definition at line 100 of file DDQUAD.c.
integer lsv1
Definition at line 100 of file DDQUAD.c.
integer mantax
Definition at line 100 of file DDQUAD.c.
integer mdic
Definition at line 110 of file DDQUAD.c.
char modfer[6]
Definition at line 37 of file DDQUAD.c.
integer motmod
Definition at line 100 of file DDQUAD.c.
integer msav
Definition at line 100 of file DDQUAD.c.
integer mulout
Definition at line 100 of file DDQUAD.c.
integer nmbseg
Definition at line 100 of file DDQUAD.c.
integer nmpnts
Definition at line 100 of file DDQUAD.c.
integer notan[5]
Definition at line 93 of file DDQUAD.c.
integer nrec
Definition at line 100 of file DDQUAD.c.
integer numax
Definition at line 100 of file DDQUAD.c.
integer numcnt
Definition at line 100 of file DDQUAD.c.
integer nump
Definition at line 100 of file DDQUAD.c.
integer numpt1
Definition at line 100 of file DDQUAD.c.
integer numsfs
Definition at line 100 of file DDQUAD.c.
integer numsur
Definition at line 100 of file DDQUAD.c.
integer nw
Definition at line 100 of file DDQUAD.c.
integer nwds
Definition at line 100 of file DDQUAD.c.
doublereal ogle[3]
Definition at line 18 of file DDQUAD.c.
doublereal p1[3]
Definition at line 18 of file DDQUAD.c.
doublereal p2[3]
Definition at line 18 of file DDQUAD.c.
doublereal param[6]
Definition at line 18 of file DDQUAD.c.
doublereal past[5]
Definition at line 50 of file DDQUAD.c.
doublereal pi
Definition at line 76 of file DDQUAD.c.
doublereal plncs[5]
Definition at line 67 of file DDQUAD.c.
doublereal plnd[5]
Definition at line 50 of file DDQUAD.c.
doublereal plnd1[5]
Definition at line 67 of file DDQUAD.c.
doublereal plnv[15]
Definition at line 50 of file DDQUAD.c.
doublereal pltst[5]
Definition at line 67 of file DDQUAD.c.
doublereal pmove[3]
Definition at line 28 of file DDQUAD.c.
doublereal r__[6]
Definition at line 18 of file DDQUAD.c.
doublereal ra
Definition at line 28 of file DDQUAD.c.
doublereal rc[5]
Definition at line 50 of file DDQUAD.c.
doublereal rc1
Definition at line 28 of file DDQUAD.c.
doublereal rdrn
Definition at line 18 of file DDQUAD.c.
doublereal refpnt[3]
Definition at line 18 of file DDQUAD.c.
doublereal ri[8]
Definition at line 43 of file DDQUAD.c.
doublereal s[5]
Definition at line 50 of file DDQUAD.c.
doublereal sagl
Definition at line 28 of file DDQUAD.c.
doublereal save[5]
Definition at line 50 of file DDQUAD.c.
doublereal savpar[4]
Definition at line 18 of file DDQUAD.c.
doublereal seg[9]
Definition at line 18 of file DDQUAD.c.
doublereal sfvct[15]
Definition at line 50 of file DDQUAD.c.
doublereal sk[15]
Definition at line 50 of file DDQUAD.c.
doublereal slope
Definition at line 18 of file DDQUAD.c.
doublereal slx[15]
Definition at line 50 of file DDQUAD.c.
doublereal sn[15]
Definition at line 50 of file DDQUAD.c.
doublereal snk[15]
Definition at line 50 of file DDQUAD.c.
doublereal snl[15]
Definition at line 50 of file DDQUAD.c.
doublereal sp[15]
Definition at line 50 of file DDQUAD.c.
doublereal spk[15]
Definition at line 50 of file DDQUAD.c.
doublereal spl[15]
Definition at line 50 of file DDQUAD.c.
doublereal sqroot
Definition at line 18 of file DDQUAD.c.
doublereal stck[5]
Definition at line 67 of file DDQUAD.c.
doublereal stck1[5]
Definition at line 67 of file DDQUAD.c.
doublereal stck2[5]
Definition at line 67 of file DDQUAD.c.
doublereal stckn[5]
Definition at line 67 of file DDQUAD.c.
doublereal strtno
Definition at line 28 of file DDQUAD.c.
doublereal surd
Definition at line 28 of file DDQUAD.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 28 of file DDQUAD.c.
doublereal tak[3]
Definition at line 28 of file DDQUAD.c.
doublereal tal[3]
Definition at line 28 of file DDQUAD.c.
doublereal tangl
Definition at line 18 of file DDQUAD.c.
doublereal tanhi[8]
Definition at line 43 of file DDQUAD.c.
doublereal tanlo[8]
Definition at line 43 of file DDQUAD.c.
doublereal tau[5]
Definition at line 50 of file DDQUAD.c.
doublereal tau1[5]
Definition at line 50 of file DDQUAD.c.
doublereal tau2[5]
Definition at line 50 of file DDQUAD.c.
doublereal tcont[9]
Definition at line 43 of file DDQUAD.c.
doublereal te[3]
Definition at line 28 of file DDQUAD.c.
doublereal tee[15]
Definition at line 67 of file DDQUAD.c.
doublereal tek[3]
Definition at line 28 of file DDQUAD.c.
doublereal tel[3]
Definition at line 28 of file DDQUAD.c.
doublereal tem[10]
Definition at line 28 of file DDQUAD.c.
doublereal temp[24]
Definition at line 28 of file DDQUAD.c.
doublereal tes[3]
Definition at line 18 of file DDQUAD.c.
doublereal tew[3]
Definition at line 18 of file DDQUAD.c.
doublereal th[5]
Definition at line 50 of file DDQUAD.c.
doublereal ti[3]
Definition at line 28 of file DDQUAD.c.
doublereal tik[3]
Definition at line 28 of file DDQUAD.c.
doublereal til[3]
Definition at line 28 of file DDQUAD.c.
doublereal tlhit
Definition at line 28 of file DDQUAD.c.
doublereal tlhite[8]
Definition at line 43 of file DDQUAD.c.
doublereal tlinc[9]
Definition at line 43 of file DDQUAD.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file DDQUAD.c.
doublereal tn[15]
Definition at line 50 of file DDQUAD.c.
doublereal tnl[15]
Definition at line 67 of file DDQUAD.c.
doublereal toolht[15]
Definition at line 50 of file DDQUAD.c.
doublereal toolwd[5]
Definition at line 50 of file DDQUAD.c.
doublereal tp[15]
Definition at line 50 of file DDQUAD.c.
doublereal tpk[15]
Definition at line 50 of file DDQUAD.c.
doublereal u1[15]
Definition at line 50 of file DDQUAD.c.
doublereal u1k[15]
Definition at line 50 of file DDQUAD.c.
doublereal u2[3]
Definition at line 18 of file DDQUAD.c.
doublereal umax[8]
Definition at line 43 of file DDQUAD.c.
doublereal unn
Definition at line 18 of file DDQUAD.c.
doublereal upp
Definition at line 18 of file DDQUAD.c.
doublereal uvec[3]
Definition at line 18 of file DDQUAD.c.
doublereal v[3]
Definition at line 18 of file DDQUAD.c.
doublereal varble[5]
Definition at line 50 of file DDQUAD.c.
doublereal vint
Definition at line 18 of file DDQUAD.c.
doublereal vl
Definition at line 18 of file DDQUAD.c.
doublereal vndir[15]
Definition at line 50 of file DDQUAD.c.
doublereal vnn
Definition at line 18 of file DDQUAD.c.
doublereal vpp
Definition at line 18 of file DDQUAD.c.
doublereal vt[15]
Definition at line 50 of file DDQUAD.c.
doublereal vtem
Definition at line 28 of file DDQUAD.c.
doublereal z0
Definition at line 76 of file DDQUAD.c.
doublereal z1
Definition at line 76 of file DDQUAD.c.
doublereal z10
Definition at line 76 of file DDQUAD.c.
doublereal z11em1
Definition at line 76 of file DDQUAD.c.
doublereal z12em1
Definition at line 76 of file DDQUAD.c.
doublereal z1e38
Definition at line 76 of file DDQUAD.c.
doublereal z1e6
Definition at line 76 of file DDQUAD.c.
doublereal z1em1
Definition at line 76 of file DDQUAD.c.
doublereal z1em2
Definition at line 76 of file DDQUAD.c.
doublereal z1em3
Definition at line 76 of file DDQUAD.c.
doublereal z1em5
Definition at line 76 of file DDQUAD.c.
doublereal z1em6
Definition at line 76 of file DDQUAD.c.
doublereal z1em7
Definition at line 76 of file DDQUAD.c.
doublereal z1em9
Definition at line 76 of file DDQUAD.c.
doublereal z2
Definition at line 76 of file DDQUAD.c.
doublereal z3
Definition at line 76 of file DDQUAD.c.
doublereal z5
Definition at line 76 of file DDQUAD.c.
doublereal z5em1
Definition at line 76 of file DDQUAD.c.
doublereal z5em6
Definition at line 76 of file DDQUAD.c.
doublereal z6em1
Definition at line 76 of file DDQUAD.c.
doublereal z90
Definition at line 76 of file DDQUAD.c.
doublereal z9em1
Definition at line 76 of file DDQUAD.c.
doublereal z__[5]
Definition at line 50 of file DDQUAD.c.
doublereal zl
Definition at line 18 of file DDQUAD.c.
doublereal zl1
Definition at line 18 of file DDQUAD.c.
doublereal zlnorm[3]
Definition at line 18 of file DDQUAD.c.
doublereal zlpnt[3]
Definition at line 18 of file DDQUAD.c.
doublereal zm1
Definition at line 76 of file DDQUAD.c.
struct { ... } znumbr_