My Project: DDSSRF.c File Reference
DDSSRF.c File Reference
#include "f2c.h"
Macros
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define modess_1 modess_
#define iddst_1 iddst_
#define ibugg_1 ibugg_
#define ssarlm_1 ssarlm_
#define chekfl_1 chekfl_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int ddssrf_ (doublereal *ss)
Variables
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer modess
integer msschk
integer mssarl
} modess_
struct {
integer iddst
} iddst_
struct {
integer ibug
integer i1
integer i2
} ibugg_
struct {
doublereal b [256]
doublereal u [4]
doublereal v [4]
integer itop [96]
integer iflag [16]
integer ipnum [4]
integer iseqls
integer nlast
integer mcat
integer iddlas [4]
integer jenlas [4]
integer lodflg [4]
integer ncalmx
integer ncmx
} ssarlm_
struct {
integer ichekf
} chekfl_
static integer c_n1 = -1
static integer c__0 = 0
static integer c__1 = 1
static integer c_n3 = -3
static integer c__3 = 3
static logical c_false = FALSE_
Macro Definition Documentation
#define charct_1 charct_
Definition at line 30 of file DDSSRF.c.
#define chekfl_1 chekfl_
Definition at line 130 of file DDSSRF.c.
Referenced by ddssrf_().
#define cosl ((doublereal *)&tlldat_1 + 16)
#define fxcor_1 fxcor_
Definition at line 24 of file DDSSRF.c.
Referenced by ddssrf_().
#define ibugg_1 ibugg_
Definition at line 115 of file DDSSRF.c.
Referenced by ddssrf_().
#define iddst_1 iddst_
Definition at line 109 of file DDSSRF.c.
Referenced by ddssrf_().
#define ifxcor_1 ifxcor_
Definition at line 89 of file DDSSRF.c.
Referenced by ddssrf_().
#define ishr18_1 ishr18_
Definition at line 97 of file DDSSRF.c.
Referenced by ddssrf_().
#define isv1_1 isv1_
Definition at line 79 of file DDSSRF.c.
#define isv_1 isv_
Definition at line 72 of file DDSSRF.c.
Referenced by ddssrf_().
#define modess_1 modess_
Definition at line 103 of file DDSSRF.c.
Referenced by ddssrf_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define ssarlm_1 ssarlm_
Definition at line 124 of file DDSSRF.c.
Referenced by ddssrf_().
#define sv1_1 sv1_
Definition at line 63 of file DDSSRF.c.
#define sv_1 sv_
Definition at line 54 of file DDSSRF.c.
Referenced by ddssrf_().
#define tlldat_1 tlldat_
Definition at line 37 of file DDSSRF.c.
Function Documentation
int ddssrf_ (doublereal * ss)
Definition at line 143 of file DDSSRF.c.
References aerr_(), bad_(), c__0, c__1, c__3, c_false, c_n1, c_n3, chekfl_1, dif, dist, dotf_(), dotv_(), fxcor_1, i__, ibugg_1, iddst_1, ifxcor_1, ii, ishr18_1, isv_1, k1, ll, lodint_(), mode, modess_1, one, pchprc_(), record_(), sqrcut_(), ssarlm_1, sv_1, ua, uu, uvdist, va, vv, w1, z5em1, and zero.
Referenced by ajundd_(), and ddst_().
 {
     /* Initialized data */
     static doublereal zero = 0.;
     static doublereal one = 1.;
     static doublereal smal = 1e-12;
     static doublereal z5em1 = .5;
     static doublereal zm5em1 = -.5;
     /* Builtin functions */
     double sqrt(doublereal), d_sign(doublereal *, doublereal *);
     /* Local variables */
     static integer i__, k1;
     static doublereal w1;
     static integer ip;
     static doublereal ua, uu, vv, va;
     static integer ii, ll, ib1, ib2;
     extern /* Subroutine */ int bad_();
     static doublereal dck, dif[3];
     static integer irr, iur, ivr, mode, lod63;
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static doublereal dsav[3];
     extern /* Subroutine */ int dotf_(doublereal *, doublereal *, doublereal *
         );
     static doublereal dist;
     extern /* Subroutine */ int dotv_(doublereal *, doublereal *, doublereal *
         ), aerr_(integer *, char *, ftnlen);
     static integer iaer1, ickbn, ipchn;
     static doublereal spsav[3], usave, vsave;
     static integer isqno, modes, idebug, idebux, ipsave, iclcur;
     extern /* Subroutine */ int lodint_(doublereal *, doublereal *,
         doublereal *, doublereal *, doublereal *, doublereal *, integer *,
          integer *, integer *, integer *), pchprc_(doublereal *,
         doublereal *, doublereal *, doublereal *, doublereal *,
         doublereal *, doublereal *, doublereal *, doublereal *,
         doublereal *, doublereal *, integer *, integer *, integer *,
         integer *, integer *, integer *, logical *);
     static integer nopatc;
     extern /* Subroutine */ int record_(integer *);
     static integer iequal, kretry;
     extern /* Subroutine */ int sqrcut_(doublereal *, doublereal *,
         doublereal *, doublereal *, doublereal *, doublereal *, integer *)
         ;
     static doublereal uvdist;
 /* ------ BEGIN SCULPTURED SURFACE TOOL RAY INTERSECTION ALGORITHM */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /* ---- FLAG INTRODUCED BY VW - USED TO DETERMINE 'CORRECT' SIDE OF CUTTER */
     /* Parameter adjustments */
     --ss;
     /* Function Body */
     ifxcor_1.iaerr = 0;
     lod63 = 0;
     idebug = 0;
     idebux = 0;
     if (ibugg_1.ibug == 1 || ibugg_1.ibug == 2) {
     idebug = 1;
     }
     if (ibugg_1.ibug == 2) {
     idebux = 1;
     }
     ++ssarlm_1.nlast;
     ip = ifxcor_1.is - 1;
 /*             /-SAVE UV,PATCH NUMBER IN CASE OF TROUBLE */
     usave = ssarlm_1.u[ip - 1];
     vsave = ssarlm_1.v[ip - 1];
     ipsave = ssarlm_1.ipnum[ip - 1];
 /*             /-SAVE OLD SP VALUE */
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L8: */
     spsav[i__ - 1] = sv_1.sp[i__ + ifxcor_1.is * 3 - 4];
     }
     if (ssarlm_1.iseqls == ifxcor_1.iseqno) {
     goto L20;
     }
 /*             /-RESET INITIALIZING DATA FOR ALL SURFACES FOR NEW STATEME */
     for (i__ = 1; i__ <= 4; ++i__) {
 /* L30: */
     ssarlm_1.lodflg[i__ - 1] = 1;
     }
 L20:
     if (isv_1.jent[ifxcor_1.is - 1] == 1 && ssarlm_1.jenlas[ip - 1] == 0) {
     ssarlm_1.lodflg[ip - 1] = 1;
     }
 /*             /-SET COUNT OF NUMBER OR RETRY-S WITHIN DDSSRF */
     kretry = 0;
 /*             /-NLAST RECORDS TOTAL NUMBER OF CALLS TO DDSSRF */
 /*             /-NCALMX IS NUMBER OF CALLS SINCE LAST CUT VECTOR */
 /*             /-NCMX IS MAX NUMBER OF CALLS ALLOWED FOR ONE CUT VECTOR */
 /*             /-ICLCUR IS NUMBER OF CURRENT CL POINT IN CUT RECORD */
 /*             /-MCAT IS LAST VALUE OF ICLCUR ON EXIT FROM DDSSRF */
     iclcur = ifxcor_1.nmpnts - ifxcor_1.numpt1 + 1;
     if (iclcur != ssarlm_1.mcat) {
     ssarlm_1.ncalmx = 0;
     }
 /*             /-RESET NUMBER OF CALLS FOR NEW DS */
     if (ssarlm_1.jenlas[ip - 1] == 0 && isv_1.jent[ifxcor_1.is - 1] == 1) {
     ssarlm_1.ncalmx = 0;
     }
     ++ssarlm_1.ncalmx;
     if (ssarlm_1.ncalmx > ssarlm_1.ncmx) {
     ifxcor_1.iaerr = 25403;
     }
     if (ifxcor_1.iaerr != 0) {
     goto L999;
     }
     if (idebug <= 0) {
     goto L40;
     }
     bad_(&c_n1, &c__0, "DSRF", &ssarlm_1.nlast, (ftnlen)4);
     bad_(&c__1, &c__0, "ISEQ", &ifxcor_1.iseqno, (ftnlen)4);
     bad_(&c__1, &c__0, "CLPT", &iclcur, (ftnlen)4);
     bad_(&c__1, &c__0, "MODS", &modess_1.modess, (ftnlen)4);
     bad_(&c__1, &c__0, "MSCK", &modess_1.msschk, (ftnlen)4);
     bad_(&c__1, &c__0, "IS  ", &ifxcor_1.is, (ftnlen)4);
     bad_(&c_n1, &c__0, "DDST", &iddst_1.iddst, (ftnlen)4);
     bad_(&c__1, &c__0, "JTN ", &isv_1.jtn[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c__1, &c__0, "MDIC", &ishr18_1.mdic, (ftnlen)4);
     bad_(&c__1, &c__0, "INDR", &isv_1.indir__[ifxcor_1.is - 1], (ftnlen)4);
     bad_(&c_n3, &c__1, "TE  ", fxcor_1.te, (ftnlen)4);
     bad_(&c__3, &c__1, "TP  ", &sv_1.tp[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "TN  ", &sv_1.tn[ifxcor_1.is * 3 - 3], (ftnlen)4);
 L40:
 /*             /-SET MODE FOR DD CALCULATION- USE SNXP WITH MODE=0, */
 /*             /-OR ELSE USE DDST WITH MODE=-1 */
 /*             /-FOR VERY FIRST ENTRY USE MODE=0 */
     mode = -1;
     if (ishr18_1.mdic > 0) {
     goto L50;
     }
     if (isv_1.indir__[ifxcor_1.is - 1] == 1 && ifxcor_1.istrup != 0 &&
         isv_1.jent[ifxcor_1.is - 1] == 1) {
     goto L50;
     }
     if (modess_1.msschk == 0 && modess_1.modess != 11) {
     goto L50;
     }
 /*             /-SET MODE TO SNXP IF ABOVE CONDITIONS DO NOT EXIST */
     mode = 0;
 L50:
 /*             /-INITIAL PHASE, SCAN SURFACE FOR BEST CANDIDATE */
 /*             /-THIS IS USED FOR ERROR RESTART OR INITIAL PROCESSING */
 /*             /-LOAD INITIAL PATCH IF DDST MODE OR MODE HAS CHANGED */
     if (ssarlm_1.iddlas[ip - 1] != iddst_1.iddst) {
     goto L63;
     }
 /*             /-DO NOT LOAD IF LODFLG IS ZERO AND MDIC IS ZERO */
     if (ssarlm_1.lodflg[ip - 1] == 0 && ishr18_1.mdic == 0) {
     goto L60;
     }
 L63:
 /*             /-LOAD A PATCH DURING ERROR PROCESSING OR INITIAL PROCESSI */
     lodint_(&ss[1], &ssarlm_1.b[(ip << 6) - 64], &ssarlm_1.u[ip - 1], &
         ssarlm_1.v[ip - 1], &sv_1.tp[ifxcor_1.is * 3 - 3], &sv_1.tn[
         ifxcor_1.is * 3 - 3], &ssarlm_1.iflag[(ip << 2) - 4], &
         ssarlm_1.itop[((ip << 2) + 1) * 6 - 30], &ssarlm_1.ipnum[ip - 1],
         &mode);
     if (idebug <= 0) {
     goto L66;
     }
     bad_(&c__1, &c__0, "LODI", &mode, (ftnlen)4);
     bad_(&c__1, &c__1, "UIP ", &ssarlm_1.u[ip - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "VIP ", &ssarlm_1.v[ip - 1], (ftnlen)4);
 L66:
 /*             /-TRUNCATE INITIAL U,V TO LIE INSIDE PATCH BOUNDARY */
     sqrcut_(&z5em1, &z5em1, &ssarlm_1.u[ip - 1], &ssarlm_1.v[ip - 1], &uu, &
         vv, &ickbn);
     ssarlm_1.u[ip - 1] = z5em1 + (uu - z5em1) * .9999;
     ssarlm_1.v[ip - 1] = z5em1 + (vv - z5em1) * .9999;
 /* L80: */
     ssarlm_1.lodflg[ip - 1] = 0;
     if (idebug <= 0) {
     goto L70;
     }
     bad_(&c__1, &c__0, "LINT", &ssarlm_1.ipnum[ip - 1], (ftnlen)4);
     bad_(&c__1, &c__0, "ICKB", &ickbn, (ftnlen)4);
     bad_(&c__1, &c__1, "UU  ", &uu, (ftnlen)4);
     bad_(&c_n1, &c__1, "VV  ", &vv, (ftnlen)4);
 L70:
 L60:
 /*             /-CALL THE MAIN ALGORITHM FOR DETERMINING THE RELATION */
 /*             /-BETWEEN THE SURFACE AND EXTERIOR POINT OR TOOL RAY */
 /* ...CALL PCHPRC.  LAST PARAMETER .FALSE. FOR NO GEOMETRIC CONSTRUCTION */
     pchprc_(&ss[1], &ssarlm_1.b[(ip << 6) - 64], &ssarlm_1.u[ip - 1], &
         ssarlm_1.v[ip - 1], &sv_1.tp[ifxcor_1.is * 3 - 3], &sv_1.tn[
         ifxcor_1.is * 3 - 3], &ua, &va, &sv_1.sp[ifxcor_1.is * 3 - 3], &
         sv_1.sn[ifxcor_1.is * 3 - 3], &sv_1.slx[ifxcor_1.is * 3 - 3], &
         ssarlm_1.iflag[(ip << 2) - 4], &ssarlm_1.itop[((ip << 2) + 1) * 6
         - 30], &ssarlm_1.ipnum[ip - 1], &mode, &idebux, &irr, &c_false);
     if (idebug <= 0) {
     goto L100;
     }
     bad_(&c__1, &c__0, "PCHP", &irr, (ftnlen)4);
     bad_(&c__1, &c__0, "MODE", &mode, (ftnlen)4);
     bad_(&c__1, &c__0, "PCNO", &ssarlm_1.ipnum[ip - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "UA  ", &ua, (ftnlen)4);
     bad_(&c_n1, &c__1, "VA  ", &va, (ftnlen)4);
     bad_(&c__3, &c__1, "SP  ", &sv_1.sp[ifxcor_1.is * 3 - 3], (ftnlen)4);
     bad_(&c_n3, &c__1, "SN  ", &sv_1.sn[ifxcor_1.is * 3 - 3], (ftnlen)4);
 L100:
     if (irr != 0) {
     goto L800;
     }
     if (chekfl_1.ichekf != 1 || lod63 == 1) {
     } else {
     lod63 = 1;
     for (i__ = 1; i__ <= 3; ++i__) {
         dif[i__ - 1] = sv_1.sp[i__ + ifxcor_1.is * 3 - 4] - sv_1.tp[i__ +
             ifxcor_1.is * 3 - 4];
 /* L109: */
     }
     dotf_(&dck, fxcor_1.ti, dif);
     if (dck < zm5em1) {
         goto L63;
     }
     }
 /*             /-CHECK FURTHER TO SEE WHETHER U,V ARE VALID */
     nopatc = (integer) ss[4];
     irr = 0;
     if (ssarlm_1.ipnum[ip - 1] < 1 || ssarlm_1.ipnum[ip - 1] > nopatc) {
     goto L70;
     }
 /* ---  DOUBLE CHECK TO SEE IF UA,VA ARE ON A LEGAL EXTENSION */
     iur = 2;
     if (ua < zero) {
     iur = 1;
     }
     if (ua > one) {
     iur = 3;
     }
     ivr = 2;
     if (va < zero) {
     ivr = 1;
     }
     if (va > one) {
     ivr = 3;
     }
     isqno = iur + (ivr - 1) * 3;
 /* ---  IF UA,VA ARE INSIDE THE PATCH BOUNDS ITS O.K. */
     if (ifxcor_1.iseqno == 5 && ip == k1) {
     ipchn = 0;
     }
     if (isqno == 5) {
     goto L230;
     }
     if (isqno % 2 != 0) {
     goto L240;
     }
 /* ---  UA,VA IS ON EXT DIRECTLY OPPOSITE A BOUNDARY */
     ib1 = isqno / 2;
 /* ---  CHECK IF A PATCH IS HOOKED TO THIS BOUNDARY */
     if (ssarlm_1.itop[(ib1 + (ip << 2)) * 6 - 29] == 0) {
     goto L230;
     }
     irr = 2;
     goto L230;
 L240:
 /* ---  UA,VA ARE ON A CORNER EXTENSION, CHECK TWO BOUNDARIES */
     ib1 = 1;
     ib2 = 2;
     if (isqno == 7) {
     ib1 = 4;
     }
     if (isqno == 3) {
     ib2 = 3;
     }
     if (isqno == 9) {
     ib1 = 4;
     }
     if (isqno == 9) {
     ib2 = 3;
     }
 /* ---  IB1,IB2 ARE THE BOUNDARIES, CHECK IF EITHER HAS A PATCH */
     if (ssarlm_1.itop[(ib1 + (ip << 2)) * 6 - 29] == 0 && ssarlm_1.itop[(ib2
         + (ip << 2)) * 6 - 29] == 0) {
     goto L230;
     }
     irr = 3;
 L230:
     if (irr == 0 || idebug <= 0) {
     goto L885;
     }
     record_(&ii);
     bad_(&c__1, &c__0, "ISEQ", &ii, (ftnlen)4);
     bad_(&c__1, &c__0, "IRR ", &irr, (ftnlen)4);
     bad_(&c__1, &c__0, "IPNM", &ssarlm_1.ipnum[ip - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "U   ", &ssarlm_1.u[ip - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "V   ", &ssarlm_1.v[ip - 1], (ftnlen)4);
     bad_(&c__1, &c__0, "ISQN", &isqno, (ftnlen)4);
     bad_(&c__1, &c__1, "UA  ", &ua, (ftnlen)4);
     bad_(&c_n1, &c__1, "VA  ", &va, (ftnlen)4);
     for (ll = 1; ll <= 4; ++ll) {
     bad_(&c__1, &c__0, "ITOP", &ssarlm_1.itop[(ll + (ip << 2)) * 6 - 29],
         (ftnlen)4);
 /* L825: */
     }
     bad_(&c_n1, &c__0, " ", &c__0, (ftnlen)1);
 L885:
 /*             /-QUIT IF IRR IS  NOT ZERO NOW */
     if (irr != 0) {
     goto L800;
     }
     ifxcor_1.ier = 0;
 /*             /-SET TN ONLY IF MODE=0 AND MODESS.NE.11(Z DETERMINATION) */
     if (mode != 0) {
     goto L310;
     }
     w1 = one;
     if (isv_1.jtn[ifxcor_1.is - 1] == 0) {
     w1 = -one;
     }
     w1 *= sv_1.z__[ifxcor_1.is - 1];
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = w1 * sv_1.sn[i__ + ifxcor_1.is *
         3 - 4];
 /* L320: */
     }
 L310:
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.temp[i__ - 1] = sv_1.sp[i__ + ifxcor_1.is * 3 - 4] - sv_1.tp[
         i__ + ifxcor_1.is * 3 - 4];
 /* L300: */
     }
 /*             /-MODIFY TN FOR CASE OF MODESS.EQ.11 */
     if (modess_1.modess != 11) {
     goto L330;
     }
     dotf_(&w1, &sv_1.tn[ifxcor_1.is * 3 - 3], fxcor_1.temp);
     if (w1 >= zero) {
     goto L330;
     }
 /*             /-REVERSE TN TO POINT TOWARD SP */
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = -sv_1.tn[i__ + ifxcor_1.is * 3 -
         4];
 /* L360: */
     }
 L330:
     dotf_(&sv_1.s[ifxcor_1.is - 1], fxcor_1.temp, fxcor_1.temp);
     sv_1.s[ifxcor_1.is - 1] = sqrt(sv_1.s[ifxcor_1.is - 1]);
     dotf_(&w1, fxcor_1.temp, &sv_1.tn[ifxcor_1.is * 3 - 3]);
     sv_1.s[ifxcor_1.is - 1] = d_sign(&one, &w1) * sv_1.s[ifxcor_1.is - 1];
     ssarlm_1.u[ip - 1] = ua;
     ssarlm_1.v[ip - 1] = va;
 /*             /-SET THE VALUE OF THE LAST SURFACE POINT */
     iequal = 1;
     for (i__ = 1; i__ <= 3; ++i__) {
     w1 = sv_1.sp[i__ + ifxcor_1.is * 3 - 4] - spsav[i__ - 1];
     if (abs(w1) > smal) {
         iequal = 0;
     }
 /* L410: */
     }
 /*             /-IF SPSAV IS DIFFERENT AND MODESS.NE.11, SET SPL=SPSAV */
     if (iequal == 1 || modess_1.modess == 11) {
     goto L420;
     }
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L430: */
     sv_1.spl[i__ + ifxcor_1.is * 3 - 4] = spsav[i__ - 1];
     }
     goto L999;
 L420:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L440: */
     sv_1.spl[i__ + ifxcor_1.is * 3 - 4] = spsav[i__ - 1];
     }
     goto L999;
 /*             /-ERROR PROCESSING */
 L800:
     ++kretry;
     if (kretry == 1) {
     goto L340;
     }
 /* .... ACCEPT SURFACE POINT */
 /* .... IF DISTANCE BETWEEN CUTTER AND SP IS LARGE (DIST.GE.10) */
 /* .... AND DISTANCE TO PATCH BOUNDARY IS SMALL (UVDIST.LE.0.05) */
     if (dist >= 10. && uvdist <= .05) {
     irr = 0;
     goto L885;
     }
     if (kretry == 2) {
     goto L350;
     }
     goto L355;
 /*             /-RELOAD INITIAL DATA AND RETRY */
 L340:
     ssarlm_1.u[ip - 1] = usave;
     ssarlm_1.v[ip - 1] = vsave;
     ssarlm_1.ipnum[ip - 1] = ipsave;
 /*             /-BRANCH BACK TO LOAD INITIAL PATCH */
     ssarlm_1.lodflg[ip - 1] = 1 - ssarlm_1.lodflg[ip - 1];
     if (mode != 0 || modes != 11) {
     goto L50;
     }
 /*     IF MODE=0, RETRY WITH NEW TE,TP */
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L345: */
     dsav[i__ - 1] = fxcor_1.te[i__ - 1] - sv_1.tp[i__ + ifxcor_1.is * 3 -
         4];
     }
     dotv_(&w1, dsav, dsav);
     w1 = sqrt(w1);
     if (abs(w1) < smal) {
     goto L355;
     }
     for (i__ = 1; i__ <= 3; ++i__) {
     dsav[i__ - 1] /= w1;
 /* L346: */
     }
     w1 *= .5;
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.te[i__ - 1] += w1 * dsav[i__ - 1];
 /* L347: */
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] += w1 * dsav[i__ - 1];
     }
     goto L50;
 L350:
     ifxcor_1.ier = irr;
     if (mode == 0) {
     goto L355;
     }
     ifxcor_1.ier = 0;
     if (iddst_1.iddst == 1) {
     goto L999;
     }
     ifxcor_1.ier = 0;
     mode = 0;
     ishr18_1.mdic = 1;
     goto L63;
 L355:
 /*             /- FATAL ERROR IN SNXP MODE */
 /*                IF IBUG=1 OR 2, DO AGAIN TO GET DYDMP-LIST */
     if (ibugg_1.ibug <= 0) {
     goto L356;
     }
     idebug = 1;
     idebux = 1;
     goto L50;
 L356:
     ifxcor_1.iaerr = 25402;
     goto L999;
 L999:
     if (idebug > 0) {
     bad_(&c__1, &c__0, "IER ", &ifxcor_1.ier, (ftnlen)4);
     }
     if (idebug > 0) {
     bad_(&c_n1, &c__0, "AERR", &ifxcor_1.iaerr, (ftnlen)4);
     }
     ssarlm_1.mcat = iclcur;
     ssarlm_1.iseqls = ifxcor_1.iseqno;
     ssarlm_1.iddlas[ip - 1] = iddst_1.iddst;
     ssarlm_1.jenlas[ip - 1] = isv_1.jent[ifxcor_1.is - 1];
     if (ifxcor_1.iaerr != 0) {
     ibugg_1.ibug = 0;
     }
     if (ifxcor_1.iaerr != 0) {
     iaer1 = ifxcor_1.iaerr;
     }
     if (ifxcor_1.iaerr != 0) {
     aerr_(&iaer1, "DDSSRF  ", (ftnlen)8);
     }
     return 0;
 } /* ddssrf_ */
Variable Documentation
doublereal alp
Definition at line 18 of file DDSSRF.c.
doublereal ax4[3]
Definition at line 18 of file DDSSRF.c.
doublereal b[256]
Definition at line 118 of file DDSSRF.c.
integer c__0 = 0 static
Definition at line 135 of file DDSSRF.c.
Referenced by ddssrf_().
integer c__1 = 1 static
Definition at line 136 of file DDSSRF.c.
Referenced by ddssrf_().
integer c__3 = 3 static
Definition at line 138 of file DDSSRF.c.
Referenced by ddssrf_().
logical c_false = FALSE_ static
Definition at line 139 of file DDSSRF.c.
Referenced by ddssrf_().
integer c_n1 = -1 static
Definition at line 134 of file DDSSRF.c.
Referenced by ddssrf_().
integer c_n3 = -3 static
Definition at line 137 of file DDSSRF.c.
Referenced by ddssrf_().
doublereal cagl
Definition at line 18 of file DDSSRF.c.
doublereal cc[15]
Definition at line 40 of file DDSSRF.c.
struct { ... } charct_
struct { ... } chekfl_
doublereal corrad[8]
Definition at line 33 of file DDSSRF.c.
doublereal cos1[5]
Definition at line 57 of file DDSSRF.c.
doublereal cplfl[5]
Definition at line 57 of file DDSSRF.c.
doublereal cptst[5]
Definition at line 57 of file DDSSRF.c.
doublereal csd[5]
Definition at line 57 of file DDSSRF.c.
doublereal cutdat[7]
Definition at line 18 of file DDSSRF.c.
doublereal dplan[15]
Definition at line 57 of file DDSSRF.c.
doublereal dpmax
Definition at line 18 of file DDSSRF.c.
doublereal dpmx1[5]
Definition at line 57 of file DDSSRF.c.
doublereal eps1[5]
Definition at line 40 of file DDSSRF.c.
doublereal eps2[5]
Definition at line 40 of file DDSSRF.c.
doublereal eps3[5]
Definition at line 40 of file DDSSRF.c.
doublereal eps4[5]
Definition at line 40 of file DDSSRF.c.
doublereal eps6[5]
Definition at line 40 of file DDSSRF.c.
doublereal eps8[5]
Definition at line 40 of file DDSSRF.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 18 of file DDSSRF.c.
doublereal hi
Definition at line 18 of file DDSSRF.c.
integer i1
Definition at line 112 of file DDSSRF.c.
integer i2
Definition at line 112 of file DDSSRF.c.
integer i3dflg
Definition at line 82 of file DDSSRF.c.
integer iaerr
Definition at line 82 of file DDSSRF.c.
integer iafl[5]
Definition at line 66 of file DDSSRF.c.
integer iamdct
Definition at line 92 of file DDSSRF.c.
integer iautps
Definition at line 82 of file DDSSRF.c.
integer ibegin
Definition at line 82 of file DDSSRF.c.
integer ibug
Definition at line 112 of file DDSSRF.c.
struct { ... } ibugg_
integer ic
Definition at line 82 of file DDSSRF.c.
integer icanon[5]
Definition at line 66 of file DDSSRF.c.
integer icheck
Definition at line 82 of file DDSSRF.c.
integer ichekf
Definition at line 127 of file DDSSRF.c.
integer icl
Definition at line 82 of file DDSSRF.c.
integer ics
Definition at line 82 of file DDSSRF.c.
integer icscnt
Definition at line 82 of file DDSSRF.c.
integer ictdef
Definition at line 82 of file DDSSRF.c.
integer icut
Definition at line 82 of file DDSSRF.c.
integer iddlas[4]
Definition at line 119 of file DDSSRF.c.
integer iddst
Definition at line 106 of file DDSSRF.c.
struct { ... } iddst_
integer ids
Definition at line 82 of file DDSSRF.c.
integer ier
Definition at line 82 of file DDSSRF.c.
integer ifar[5]
Definition at line 75 of file DDSSRF.c.
integer ifl4[5]
Definition at line 75 of file DDSSRF.c.
integer iflag[16]
Definition at line 119 of file DDSSRF.c.
struct { ... } ifxcor_
integer igo
Definition at line 82 of file DDSSRF.c.
integer igoto
Definition at line 82 of file DDSSRF.c.
integer igoug
Definition at line 82 of file DDSSRF.c.
integer igs
Definition at line 82 of file DDSSRF.c.
integer index[5]
Definition at line 66 of file DDSSRF.c.
integer indir__[5]
Definition at line 66 of file DDSSRF.c.
integer inops
Definition at line 82 of file DDSSRF.c.
integer iop[5]
Definition at line 66 of file DDSSRF.c.
integer iopset[5]
Definition at line 66 of file DDSSRF.c.
integer ipdpl
Definition at line 92 of file DDSSRF.c.
integer ipl[5]
Definition at line 66 of file DDSSRF.c.
integer ipnum[4]
Definition at line 119 of file DDSSRF.c.
integer ips
Definition at line 82 of file DDSSRF.c.
integer ipsdef
Definition at line 82 of file DDSSRF.c.
integer ipt
Definition at line 92 of file DDSSRF.c.
integer ipt1
Definition at line 82 of file DDSSRF.c.
integer is
Definition at line 82 of file DDSSRF.c.
integer iseg
Definition at line 82 of file DDSSRF.c.
integer iseqls
Definition at line 119 of file DDSSRF.c.
Referenced by sspath_().
integer iseqno
Definition at line 82 of file DDSSRF.c.
integer isfidn[5]
Definition at line 66 of file DDSSRF.c.
integer isftyp[5]
Definition at line 66 of file DDSSRF.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 66 of file DDSSRF.c.
integer isrch
Definition at line 82 of file DDSSRF.c.
integer istrup
Definition at line 82 of file DDSSRF.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 66 of file DDSSRF.c.
integer it
Definition at line 82 of file DDSSRF.c.
integer itlon[5]
Definition at line 66 of file DDSSRF.c.
integer itop[96]
Definition at line 119 of file DDSSRF.c.
integer itseg[5]
Definition at line 66 of file DDSSRF.c.
integer itsegk[5]
Definition at line 66 of file DDSSRF.c.
integer iunfl[5]
Definition at line 66 of file DDSSRF.c.
integer iws
Definition at line 92 of file DDSSRF.c.
integer j10
Definition at line 92 of file DDSSRF.c.
integer j12
Definition at line 92 of file DDSSRF.c.
integer j13
Definition at line 92 of file DDSSRF.c.
integer j20[5]
Definition at line 75 of file DDSSRF.c.
integer j21[5]
Definition at line 75 of file DDSSRF.c.
integer j22[5]
Definition at line 75 of file DDSSRF.c.
integer j23[5]
Definition at line 75 of file DDSSRF.c.
integer j50[5]
Definition at line 75 of file DDSSRF.c.
integer j51[5]
Definition at line 75 of file DDSSRF.c.
integer j54
Definition at line 92 of file DDSSRF.c.
integer jbr
Definition at line 82 of file DDSSRF.c.
integer jckr
Definition at line 92 of file DDSSRF.c.
integer jcnt1
Definition at line 92 of file DDSSRF.c.
integer jcnt2
Definition at line 92 of file DDSSRF.c.
integer jcnt3
Definition at line 92 of file DDSSRF.c.
integer jcpr
Definition at line 92 of file DDSSRF.c.
integer jcr
Definition at line 92 of file DDSSRF.c.
integer jdr
Definition at line 92 of file DDSSRF.c.
integer jenlas[4]
Definition at line 119 of file DDSSRF.c.
integer jent[5]
Definition at line 66 of file DDSSRF.c.
integer jfind
Definition at line 92 of file DDSSRF.c.
integer jgr
Definition at line 92 of file DDSSRF.c.
integer jiops[5]
Definition at line 66 of file DDSSRF.c.
integer jmin
Definition at line 92 of file DDSSRF.c.
integer jminr
Definition at line 92 of file DDSSRF.c.
integer jph[5]
Definition at line 75 of file DDSSRF.c.
integer jpr
Definition at line 92 of file DDSSRF.c.
integer jpxr
Definition at line 92 of file DDSSRF.c.
integer jsw
Definition at line 82 of file DDSSRF.c.
integer jtkf
Definition at line 92 of file DDSSRF.c.
integer jtlflg[5]
Definition at line 66 of file DDSSRF.c.
integer jtn[5]
Definition at line 66 of file DDSSRF.c.
integer jtr
Definition at line 92 of file DDSSRF.c.
integer ju1[5]
Definition at line 66 of file DDSSRF.c.
integer limfl[5]
Definition at line 66 of file DDSSRF.c.
integer lodflg[4]
Definition at line 119 of file DDSSRF.c.
integer lsv
Definition at line 82 of file DDSSRF.c.
integer lsv1
Definition at line 82 of file DDSSRF.c.
integer mantax
Definition at line 82 of file DDSSRF.c.
integer mcat
Definition at line 119 of file DDSSRF.c.
integer mdic
Definition at line 92 of file DDSSRF.c.
integer modess
Definition at line 100 of file DDSSRF.c.
struct { ... } modess_
char modfer[6]
Definition at line 27 of file DDSSRF.c.
integer motmod
Definition at line 82 of file DDSSRF.c.
integer msav
Definition at line 82 of file DDSSRF.c.
integer mssarl
Definition at line 100 of file DDSSRF.c.
integer msschk
Definition at line 100 of file DDSSRF.c.
integer mulout
Definition at line 82 of file DDSSRF.c.
integer ncalmx
Definition at line 119 of file DDSSRF.c.
integer ncmx
Definition at line 119 of file DDSSRF.c.
integer nlast
Definition at line 119 of file DDSSRF.c.
integer nmbseg
Definition at line 82 of file DDSSRF.c.
integer nmpnts
Definition at line 82 of file DDSSRF.c.
integer notan[5]
Definition at line 75 of file DDSSRF.c.
integer nrec
Definition at line 82 of file DDSSRF.c.
integer numax
Definition at line 82 of file DDSSRF.c.
integer numcnt
Definition at line 82 of file DDSSRF.c.
integer nump
Definition at line 82 of file DDSSRF.c.
integer numpt1
Definition at line 82 of file DDSSRF.c.
integer numsfs
Definition at line 82 of file DDSSRF.c.
integer numsur
Definition at line 82 of file DDSSRF.c.
integer nw
Definition at line 82 of file DDSSRF.c.
integer nwds
Definition at line 82 of file DDSSRF.c.
doublereal past[5]
Definition at line 40 of file DDSSRF.c.
doublereal plncs[5]
Definition at line 57 of file DDSSRF.c.
doublereal plnd[5]
Definition at line 40 of file DDSSRF.c.
doublereal plnd1[5]
Definition at line 57 of file DDSSRF.c.
doublereal plnv[15]
Definition at line 40 of file DDSSRF.c.
doublereal pltst[5]
Definition at line 57 of file DDSSRF.c.
doublereal pmove[3]
Definition at line 18 of file DDSSRF.c.
doublereal ra
Definition at line 18 of file DDSSRF.c.
doublereal rc[5]
Definition at line 40 of file DDSSRF.c.
doublereal rc1
Definition at line 18 of file DDSSRF.c.
doublereal ri[8]
Definition at line 33 of file DDSSRF.c.
doublereal s[5]
Definition at line 40 of file DDSSRF.c.
doublereal sagl
Definition at line 18 of file DDSSRF.c.
doublereal save[5]
Definition at line 40 of file DDSSRF.c.
doublereal sfvct[15]
Definition at line 40 of file DDSSRF.c.
doublereal sk[15]
Definition at line 40 of file DDSSRF.c.
doublereal slx[15]
Definition at line 40 of file DDSSRF.c.
doublereal sn[15]
Definition at line 40 of file DDSSRF.c.
doublereal snk[15]
Definition at line 40 of file DDSSRF.c.
doublereal snl[15]
Definition at line 40 of file DDSSRF.c.
doublereal sp[15]
Definition at line 40 of file DDSSRF.c.
doublereal spk[15]
Definition at line 40 of file DDSSRF.c.
doublereal spl[15]
Definition at line 40 of file DDSSRF.c.
struct { ... } ssarlm_
doublereal stck[5]
Definition at line 57 of file DDSSRF.c.
doublereal stck1[5]
Definition at line 57 of file DDSSRF.c.
doublereal stck2[5]
Definition at line 57 of file DDSSRF.c.
doublereal stckn[5]
Definition at line 57 of file DDSSRF.c.
doublereal strtno
Definition at line 18 of file DDSSRF.c.
doublereal surd
Definition at line 18 of file DDSSRF.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 18 of file DDSSRF.c.
doublereal tak[3]
Definition at line 18 of file DDSSRF.c.
doublereal tal[3]
Definition at line 18 of file DDSSRF.c.
doublereal tanhi[8]
Definition at line 33 of file DDSSRF.c.
doublereal tanlo[8]
Definition at line 33 of file DDSSRF.c.
doublereal tau[5]
Definition at line 40 of file DDSSRF.c.
doublereal tau1[5]
Definition at line 40 of file DDSSRF.c.
doublereal tau2[5]
Definition at line 40 of file DDSSRF.c.
doublereal tcont[9]
Definition at line 33 of file DDSSRF.c.
doublereal te[3]
Definition at line 18 of file DDSSRF.c.
doublereal tee[15]
Definition at line 57 of file DDSSRF.c.
doublereal tek[3]
Definition at line 18 of file DDSSRF.c.
doublereal tel[3]
Definition at line 18 of file DDSSRF.c.
doublereal tem[10]
Definition at line 18 of file DDSSRF.c.
doublereal temp[24]
Definition at line 18 of file DDSSRF.c.
doublereal th[5]
Definition at line 40 of file DDSSRF.c.
doublereal ti[3]
Definition at line 18 of file DDSSRF.c.
doublereal tik[3]
Definition at line 18 of file DDSSRF.c.
doublereal til[3]
Definition at line 18 of file DDSSRF.c.
doublereal tlhit
Definition at line 18 of file DDSSRF.c.
doublereal tlhite[8]
Definition at line 33 of file DDSSRF.c.
doublereal tlinc[9]
Definition at line 33 of file DDSSRF.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 18 of file DDSSRF.c.
doublereal tn[15]
Definition at line 40 of file DDSSRF.c.
doublereal tnl[15]
Definition at line 57 of file DDSSRF.c.
doublereal toolht[15]
Definition at line 40 of file DDSSRF.c.
doublereal toolwd[5]
Definition at line 40 of file DDSSRF.c.
doublereal tp[15]
Definition at line 40 of file DDSSRF.c.
doublereal tpk[15]
Definition at line 40 of file DDSSRF.c.
doublereal u[4]
Definition at line 118 of file DDSSRF.c.
doublereal u1[15]
Definition at line 40 of file DDSSRF.c.
doublereal u1k[15]
Definition at line 40 of file DDSSRF.c.
doublereal umax[8]
Definition at line 33 of file DDSSRF.c.
doublereal v[4]
Definition at line 118 of file DDSSRF.c.
doublereal varble[5]
Definition at line 40 of file DDSSRF.c.
doublereal vndir[15]
Definition at line 40 of file DDSSRF.c.
doublereal vt[15]
Definition at line 40 of file DDSSRF.c.
doublereal vtem
Definition at line 18 of file DDSSRF.c.
doublereal z__[5]
Definition at line 40 of file DDSSRF.c.