My Project: DDST.c File Reference
DDST.c File Reference
#include "f2c.h"
Macros
#define dshar4_1 dshar4_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define addcom_1 addcom_
#define _BLNK__1 _BLNK__
#define iddst_1 iddst_
#define j11 ((integer *)equiv_11)
#define can ((doublereal *)&_BLNK__1 + 40)
#define jlin ((integer *)&addcom_1 + 46)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define real8 (equiv_11)
#define canon ((doublereal *)&_BLNK__1)
#define elmax ((doublereal *)&addcom_1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define ibtflg ((integer *)&addcom_1 + 44)
#define clngth ((doublereal *)&addcom_1 + 1)
#define kdynfl ((integer *)&addcom_1 + 48)
#define j11 ((integer *)equiv_11)
#define can ((doublereal *)&_BLNK__1 + 40)
#define jlin ((integer *)&addcom_1 + 46)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define real8 (equiv_11)
#define canon ((doublereal *)&_BLNK__1)
#define elmax ((doublereal *)&addcom_1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define ibtflg ((integer *)&addcom_1 + 44)
#define clngth ((doublereal *)&addcom_1 + 1)
#define kdynfl ((integer *)&addcom_1 + 48)
Functions
int ddst_ (void)
int ajundd_ (void)
Variables
struct {
doublereal a
doublereal b
doublereal c__
doublereal cendis
doublereal cmove [3]
doublereal com1
doublereal com4
doublereal dir [3]
doublereal dp
doublereal dpe
doublereal dpcnt
doublereal dpi
doublereal dpl
doublereal dp1
doublereal d1
doublereal d2a
doublereal flipck
doublereal fwd [3]
doublereal ogle [3]
doublereal p1 [3]
doublereal p2 [3]
doublereal rdrn
doublereal refpnt [3]
doublereal tangl
doublereal tes [3]
doublereal tew [3]
doublereal uvec [3]
doublereal u2 [3]
doublereal v [3]
doublereal vl
doublereal zl
doublereal zlnorm [3]
doublereal zlpnt [3]
doublereal zl1
doublereal param [6]
doublereal r__ [6]
doublereal savpar [4]
doublereal seg [9]
doublereal slope
doublereal sqroot
doublereal unn
doublereal upp
doublereal vint
doublereal vnn
doublereal vpp
} dshar4_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
doublereal addcom [25]
} addcom_
struct {
doublereal com [36000]
} _BLNK__
struct {
integer iddst
} iddst_
static integer c__2 = 2
static integer c__26203 = 26203
static integer c__1 = 1
static integer c__26204 = 26204
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 119 of file DDST.c.
#define addcom_1 addcom_
Definition at line 113 of file DDST.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
Referenced by ajundd_(), and ddst_().
#define canon ((doublereal *)&_BLNK__1)
#define charct_1 charct_
Definition at line 40 of file DDST.c.
#define clngth ((doublereal *)&addcom_1 + 1)
#define clngth ((doublereal *)&addcom_1 + 1)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dshar4_1 dshar4_
Definition at line 25 of file DDST.c.
Referenced by ddst_().
#define elmax ((doublereal *)&addcom_1)
#define elmax ((doublereal *)&addcom_1)
#define fxcor_1 fxcor_
Definition at line 34 of file DDST.c.
#define ibtflg ((integer *)&addcom_1 + 44)
#define ibtflg ((integer *)&addcom_1 + 44)
#define iddst_1 iddst_
Definition at line 125 of file DDST.c.
Referenced by ajundd_(), and ddst_().
#define ifxcor_1 ifxcor_
Definition at line 99 of file DDST.c.
Referenced by ajundd_(), and ddst_().
#define ishr18_1 ishr18_
Definition at line 107 of file DDST.c.
Referenced by ajundd_().
#define isv1_1 isv1_
Definition at line 89 of file DDST.c.
#define isv_1 isv_
Definition at line 82 of file DDST.c.
Referenced by ajundd_(), and ddst_().
#define j11 ((integer *)equiv_11)
Referenced by ajundd_(), and ddst_().
#define j11 ((integer *)equiv_11)
#define jlin ((integer *)&addcom_1 + 46)
#define jlin ((integer *)&addcom_1 + 46)
#define kdynfl ((integer *)&addcom_1 + 48)
Referenced by ajundd_(), and ddst_().
#define kdynfl ((integer *)&addcom_1 + 48)
#define real8 (equiv_11)
#define real8 (equiv_11)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define sv1_1 sv1_
Definition at line 73 of file DDST.c.
#define sv_1 sv_
Definition at line 64 of file DDST.c.
Referenced by ajundd_(), and ddst_().
#define tlldat_1 tlldat_
Definition at line 47 of file DDST.c.
Function Documentation
int ajundd_ (void)
Definition at line 394 of file DDST.c.
References aerr_(), apt094_(), apt238_(), c__1, c__2, c__26203, c__26204, canon, ddcyln_(), ddpars_(), ddplan_(), ddquad_(), ddrlsr_(), ddssrf_(), ddtabc_(), dotf_(), i__, iddst_1, ifxcor_1, ishr18_1, isv_1, j11, kdynfl, one, polcon_(), radar_(), sv_1, w1, and zero.
Referenced by amind_(), gouge_(), and tlnorm_().
 {
     /* Initialized data */
     static doublereal zero = 0.;
     static doublereal one = 1.;
     /* System generated locals */
     static doublereal equiv_11[1];
     /* Local variables */
     static integer i__;
     static doublereal w1;
 #define j11 ((integer *)equiv_11)
 #define can ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen);
 #define jlin ((integer *)&addcom_1 + 46)
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     extern /* Subroutine */ int dotf_(doublereal *, doublereal *, doublereal *
         );
 #define real8 (equiv_11)
     extern /* Subroutine */ int apt094_(integer *, doublereal *, integer *),
         apt238_(integer *), radar_(void);
 #define canon ((doublereal *)&_BLNK__1)
 #define elmax ((doublereal *)&addcom_1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int ddtabc_(doublereal *);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     static integer ifetch;
     extern /* Subroutine */ int ddplan_(doublereal *), ddquad_(doublereal *);
 #define ibtflg ((integer *)&addcom_1 + 44)
 #define clngth ((doublereal *)&addcom_1 + 1)
     extern /* Subroutine */ int ddcyln_(doublereal *);
 #define kdynfl ((integer *)&addcom_1 + 48)
     extern /* Subroutine */ int ddrlsr_(void), polcon_(doublereal *, integer *
         ), ddpars_(doublereal *), ddssrf_(doublereal *);
 /*              /-AJUNDD FOR DISTANCE AND LINEUP WITH SURFACE. */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /* ...  21. ADDCOM BLOCK */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*              /-ARRAY TO SAVE SP,SN DATA */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /*              /-J11 IS AN INDEX TO THE LOCATION OF LARGE DATA IN CANON */
 /*              /-J11 MUST BE ON A DOUBLE WORD BOUNDARY PER APT094 REQS. */
 /*              /-GIVEN TP,TN FIND SP,SN,S ON SURFACE */
 /*              /-SUCH THAT TP+S*TN=SP */
     iddst_1.iddst = 2;
     ishr18_1.mdic = 0;
 L200:
 /*              /-IC IS THE INDEX TO THE INTERNAL CANON FORM OF SURF IS */
     ifxcor_1.ic = isv_1.icanon[ifxcor_1.is - 1];
 /*              /-JSW IS THE SURFACE NUMERIC TYPE(1 THRU 30) */
     ifxcor_1.jsw = isv_1.isfidn[ifxcor_1.is - 1];
 /*             /-SET MODE TO FETCH LARGE DATA FROM EXTERNAL STORAGE. */
     ifetch = 3;
     switch (ifxcor_1.jsw) {
     case 1:  goto L1;
     case 2:  goto L1;
     case 3:  goto L3;
     case 4:  goto L3;
     case 5:  goto L6;
     case 6:  goto L6;
     case 7:  goto L6;
     case 8:  goto L6;
     case 9:  goto L6;
     case 10:  goto L6;
     case 11:  goto L11;
     case 12:  goto L12;
     case 13:  goto L13;
     case 14:  goto L6;
     case 15:  goto L15;
     case 16:  goto L99;
     case 17:  goto L99;
     case 18:  goto L99;
     case 19:  goto L99;
     case 20:  goto L99;
     case 21:  goto L99;
     case 22:  goto L99;
     case 23:  goto L99;
     case 24:  goto L99;
     case 25:  goto L99;
     case 26:  goto L99;
     case 27:  goto L99;
     case 28:  goto L99;
     case 29:  goto L29;
     case 30:  goto L30;
     }
 L99:
 /*              /-ERROR, JSW INDEX IS OUT OF RANGE */
     ifxcor_1.ier = 1;
     goto L999;
 L1:
     ddplan_(&canon[ifxcor_1.ic - 1]);
     goto L1000;
 L3:
     ddcyln_(&canon[ifxcor_1.ic - 1]);
     goto L1000;
 L6:
     ddquad_(&canon[ifxcor_1.ic - 1]);
     goto L1000;
 L11:
     apt094_(&ifetch, &canon[ifxcor_1.ic - 1], j11);
     --(*j11);
     ddtabc_(&canon[*j11 - 1]);
     goto L1000;
 L12:
     apt094_(&ifetch, &canon[ifxcor_1.ic - 1], j11);
     ifxcor_1.ic = *j11;
     ddrlsr_();
     goto L1000;
 L13:
     polcon_(&canon[ifxcor_1.ic - 1], &c__2);
     goto L1000;
 /*              /- */
 L15:
     ddpars_(&canon[ifxcor_1.ic - 1]);
     goto L1000;
 L29:
     apt094_(&ifetch, &canon[ifxcor_1.ic - 1], j11);
     ddssrf_(&canon[*j11 - 1]);
     goto L1000;
 /*             /-SYNTHETIC CURVE NOT NOW PROGRAMMED FOR ARELEM */
 L30:
     aerr_(&c__26203, "AJUNDD  ", (ftnlen)8);
     goto L999;
 L1000:
     if (*kdynfl != 0) {
     apt238_(&c__1);
     }
     if (ifxcor_1.ier == 0) {
     goto L810;
     }
 /*              /-CALL RADAR TO GENERATE A NEW TP,TN FOR INTERSECTION */
     radar_();
 /*              /-RESTART IF RADAR HAS OBTAINED A GOOD TP,TN */
     if (ifxcor_1.iaerr == 0) {
     goto L200;
     }
 /*              /-OTHERWISE, TERMINATE WITH THIS IAERR SETTING. */
     goto L999;
 L810:
     if (*kdynfl != 0) {
     apt238_(&c__2);
     }
 /*              /-RADAR EXHAUSTED ALL TRIES */
     if (ifxcor_1.ier != 0) {
     aerr_(&c__26204, "AJUNDD  ", (ftnlen)8);
     }
     if (isv_1.jtn[ifxcor_1.is - 1] == 0) {
     goto L820;
     }
 /*              /-ADJUST Z EACH TIME FOR CS, SN,TN SHOULD LIE SAME WAY. */
     dotf_(&w1, &sv_1.tn[ifxcor_1.is * 3 - 3], &sv_1.sn[ifxcor_1.is * 3 - 3]);
     sv_1.z__[ifxcor_1.is - 1] = one;
     if (w1 < zero) {
     sv_1.z__[ifxcor_1.is - 1] = -one;
     }
 L820:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L830: */
     sv_1.sn[i__ + ifxcor_1.is * 3 - 4] = sv_1.z__[ifxcor_1.is - 1] *
         sv_1.sn[i__ + ifxcor_1.is * 3 - 4];
     }
 /*              /-EXIT POINT */
 L999:
     iddst_1.iddst = 0;
     return 0;
 } /* ajundd_ */
int ddst_ (void)
Definition at line 136 of file DDST.c.
References aerr_(), apt094_(), apt238_(), c__1, c__2, c__26203, canon, ddcyln_(), ddpars_(), ddplan_(), ddquad_(), ddrlsr_(), ddssrf_(), ddtabc_(), dshar4_1, i__, iddst_1, ifxcor_1, isv_1, j11, kdynfl, polcon_(), sv_1, and zero.
Referenced by check_(), cplan_(), go2_(), and tlnorm_().
 {
     /* Initialized data */
     static doublereal zero = 0.;
     /* System generated locals */
     static doublereal equiv_11[1];
     /* Local variables */
     static integer i__;
 #define j11 ((integer *)equiv_11)
 #define can ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen);
 #define jlin ((integer *)&addcom_1 + 46)
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static doublereal stem[6];
 #define real8 (equiv_11)
     extern /* Subroutine */ int apt094_(integer *, doublereal *, integer *),
         apt238_(integer *);
 #define canon ((doublereal *)&_BLNK__1)
 #define elmax ((doublereal *)&addcom_1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int ddtabc_(doublereal *);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     static integer ifetch;
     extern /* Subroutine */ int ddplan_(doublereal *), ddquad_(doublereal *);
 #define ibtflg ((integer *)&addcom_1 + 44)
 #define clngth ((doublereal *)&addcom_1 + 1)
     extern /* Subroutine */ int ddcyln_(doublereal *);
 #define kdynfl ((integer *)&addcom_1 + 48)
     extern /* Subroutine */ int ddrlsr_(void), polcon_(doublereal *, integer *
         ), ddpars_(doublereal *), ddssrf_(doublereal *);
 /*              /-DDST FOR DIRECTED DISTANCE TO SURFACE */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /* ...  21. ADDCOM BLOCK */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*              /-ARRAY TO SAVE SP,SN DATA */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /*              /-J11 IS AN INDEX TO THE LOCATION OF LARGE DATA IN CANON */
 /*              /-J11 MUST BE ON A DOUBLE WORD BOUNDARY PER APT094 REQS. */
     iddst_1.iddst = 1;
     for (i__ = 1; i__ <= 3; ++i__) {
     stem[i__ - 1] = sv_1.sn[i__ + ifxcor_1.is * 3 - 4];
     stem[i__ + 2] = sv_1.sp[i__ + ifxcor_1.is * 3 - 4];
 /* L100: */
     }
     dshar4_1.a = zero;
     dshar4_1.b = zero;
     dshar4_1.c__ = zero;
 /*              /-IC IS THE INDEX TO THE INTERNAL CANON FORM OF SURF IS */
     ifxcor_1.ic = isv_1.icanon[ifxcor_1.is - 1];
 /*              /-JSW IS THE SURFACE NUMERIC TYPE(1 THRU 30) */
     ifxcor_1.jsw = isv_1.isfidn[ifxcor_1.is - 1];
 /*             /-SET MODE TO FETCH LARGE DATA FROM EXTERNAL STORAGE. */
     ifetch = 3;
     switch (ifxcor_1.jsw) {
     case 1:  goto L1;
     case 2:  goto L1;
     case 3:  goto L3;
     case 4:  goto L3;
     case 5:  goto L6;
     case 6:  goto L6;
     case 7:  goto L6;
     case 8:  goto L6;
     case 9:  goto L6;
     case 10:  goto L6;
     case 11:  goto L11;
     case 12:  goto L12;
     case 13:  goto L13;
     case 14:  goto L6;
     case 15:  goto L15;
     case 16:  goto L99;
     case 17:  goto L99;
     case 18:  goto L99;
     case 19:  goto L99;
     case 20:  goto L99;
     case 21:  goto L99;
     case 22:  goto L99;
     case 23:  goto L99;
     case 24:  goto L99;
     case 25:  goto L99;
     case 26:  goto L99;
     case 27:  goto L99;
     case 28:  goto L99;
     case 29:  goto L29;
     case 30:  goto L30;
     }
 L99:
 /*              /-ERROR, JSW INDEX IS OUT OF RANGE */
     ifxcor_1.ier = 1;
     goto L999;
 L1:
     ddplan_(&canon[ifxcor_1.ic - 1]);
     goto L1000;
 L3:
     ddcyln_(&canon[ifxcor_1.ic - 1]);
     goto L1000;
 L6:
     ddquad_(&canon[ifxcor_1.ic - 1]);
     goto L1000;
 L11:
     apt094_(&ifetch, &canon[ifxcor_1.ic - 1], j11);
     --(*j11);
     ddtabc_(&canon[*j11 - 1]);
     goto L1000;
 L12:
     apt094_(&ifetch, &canon[ifxcor_1.ic - 1], j11);
     ifxcor_1.ic = *j11;
     ddrlsr_();
     goto L1000;
 L13:
     polcon_(&canon[ifxcor_1.ic - 1], &c__2);
     goto L1000;
 /*              /- */
 L15:
     ddpars_(&canon[ifxcor_1.ic - 1]);
     goto L1000;
 L29:
     apt094_(&ifetch, &canon[ifxcor_1.ic - 1], j11);
     ddssrf_(&canon[*j11 - 1]);
     goto L1000;
 /*             /-SYNTHETIC CURVE NOT NOW PROGRAMMED FOR ARELEM */
 L30:
     aerr_(&c__26203, "DDST    ", (ftnlen)8);
     goto L999;
 L1000:
     if (*kdynfl != 0) {
     apt238_(&c__1);
     }
 /*              /-EXIT POINT FOR DDST ROUTINE */
 /*              /-RESTORE SURFACE DATA */
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.sn[i__ + ifxcor_1.is * 3 - 4] = stem[i__ - 1];
 /* L700: */
     sv_1.sp[i__ + ifxcor_1.is * 3 - 4] = stem[i__ + 2];
     }
 L999:
     iddst_1.iddst = 0;
     return 0;
 } /* ddst_ */
Variable Documentation
struct { ... } _BLNK__
doublereal a
Definition at line 18 of file DDST.c.
doublereal addcom[25]
Definition at line 110 of file DDST.c.
struct { ... } addcom_
doublereal alp
Definition at line 28 of file DDST.c.
doublereal ax4[3]
Definition at line 28 of file DDST.c.
doublereal b
Definition at line 18 of file DDST.c.
doublereal c__
Definition at line 18 of file DDST.c.
integer c__1 = 1 static
Definition at line 131 of file DDST.c.
Referenced by ajundd_(), and ddst_().
integer c__2 = 2 static
Definition at line 129 of file DDST.c.
Referenced by ajundd_(), and ddst_().
integer c__26203 = 26203 static
Definition at line 130 of file DDST.c.
Referenced by ajundd_(), and ddst_().
integer c__26204 = 26204 static
Definition at line 132 of file DDST.c.
Referenced by ajundd_().
doublereal cagl
Definition at line 28 of file DDST.c.
doublereal cc[15]
Definition at line 50 of file DDST.c.
doublereal cendis
Definition at line 18 of file DDST.c.
struct { ... } charct_
doublereal cmove[3]
Definition at line 18 of file DDST.c.
doublereal com[36000]
Definition at line 116 of file DDST.c.
doublereal com1
Definition at line 18 of file DDST.c.
doublereal com4
Definition at line 18 of file DDST.c.
doublereal corrad[8]
Definition at line 43 of file DDST.c.
doublereal cos1[5]
Definition at line 67 of file DDST.c.
doublereal cplfl[5]
Definition at line 67 of file DDST.c.
doublereal cptst[5]
Definition at line 67 of file DDST.c.
doublereal csd[5]
Definition at line 67 of file DDST.c.
doublereal cutdat[7]
Definition at line 28 of file DDST.c.
doublereal d1
Definition at line 18 of file DDST.c.
doublereal d2a
Definition at line 18 of file DDST.c.
doublereal dir[3]
Definition at line 18 of file DDST.c.
doublereal dp
Definition at line 18 of file DDST.c.
doublereal dp1
Definition at line 18 of file DDST.c.
doublereal dpcnt
Definition at line 18 of file DDST.c.
doublereal dpe
Definition at line 18 of file DDST.c.
doublereal dpi
Definition at line 18 of file DDST.c.
doublereal dpl
Definition at line 18 of file DDST.c.
doublereal dplan[15]
Definition at line 67 of file DDST.c.
doublereal dpmax
Definition at line 28 of file DDST.c.
doublereal dpmx1[5]
Definition at line 67 of file DDST.c.
struct { ... } dshar4_
doublereal eps1[5]
Definition at line 50 of file DDST.c.
doublereal eps2[5]
Definition at line 50 of file DDST.c.
doublereal eps3[5]
Definition at line 50 of file DDST.c.
doublereal eps4[5]
Definition at line 50 of file DDST.c.
doublereal eps6[5]
Definition at line 50 of file DDST.c.
doublereal eps8[5]
Definition at line 50 of file DDST.c.
doublereal flipck
Definition at line 18 of file DDST.c.
doublereal fwd[3]
Definition at line 18 of file DDST.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file DDST.c.
doublereal hi
Definition at line 28 of file DDST.c.
integer i3dflg
Definition at line 92 of file DDST.c.
integer iaerr
Definition at line 92 of file DDST.c.
integer iafl[5]
Definition at line 76 of file DDST.c.
integer iamdct
Definition at line 102 of file DDST.c.
integer iautps
Definition at line 92 of file DDST.c.
integer ibegin
Definition at line 92 of file DDST.c.
integer ic
Definition at line 92 of file DDST.c.
integer icanon[5]
Definition at line 76 of file DDST.c.
integer icheck
Definition at line 92 of file DDST.c.
integer icl
Definition at line 92 of file DDST.c.
integer ics
Definition at line 92 of file DDST.c.
integer icscnt
Definition at line 92 of file DDST.c.
integer ictdef
Definition at line 92 of file DDST.c.
integer icut
Definition at line 92 of file DDST.c.
integer iddst
Definition at line 122 of file DDST.c.
struct { ... } iddst_
integer ids
Definition at line 92 of file DDST.c.
integer ier
Definition at line 92 of file DDST.c.
integer ifar[5]
Definition at line 85 of file DDST.c.
integer ifl4[5]
Definition at line 85 of file DDST.c.
struct { ... } ifxcor_
integer igo
Definition at line 92 of file DDST.c.
integer igoto
Definition at line 92 of file DDST.c.
integer igoug
Definition at line 92 of file DDST.c.
integer igs
Definition at line 92 of file DDST.c.
integer index[5]
Definition at line 76 of file DDST.c.
integer indir__[5]
Definition at line 76 of file DDST.c.
integer inops
Definition at line 92 of file DDST.c.
integer iop[5]
Definition at line 76 of file DDST.c.
integer iopset[5]
Definition at line 76 of file DDST.c.
integer ipdpl
Definition at line 102 of file DDST.c.
integer ipl[5]
Definition at line 76 of file DDST.c.
integer ips
Definition at line 92 of file DDST.c.
integer ipsdef
Definition at line 92 of file DDST.c.
integer ipt
Definition at line 102 of file DDST.c.
integer ipt1
Definition at line 92 of file DDST.c.
integer is
Definition at line 92 of file DDST.c.
integer iseg
Definition at line 92 of file DDST.c.
integer iseqno
Definition at line 92 of file DDST.c.
integer isfidn[5]
Definition at line 76 of file DDST.c.
integer isftyp[5]
Definition at line 76 of file DDST.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 76 of file DDST.c.
integer isrch
Definition at line 92 of file DDST.c.
integer istrup
Definition at line 92 of file DDST.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 76 of file DDST.c.
integer it
Definition at line 92 of file DDST.c.
integer itlon[5]
Definition at line 76 of file DDST.c.
integer itseg[5]
Definition at line 76 of file DDST.c.
integer itsegk[5]
Definition at line 76 of file DDST.c.
integer iunfl[5]
Definition at line 76 of file DDST.c.
integer iws
Definition at line 102 of file DDST.c.
integer j10
Definition at line 102 of file DDST.c.
integer j12
Definition at line 102 of file DDST.c.
integer j13
Definition at line 102 of file DDST.c.
integer j20[5]
Definition at line 85 of file DDST.c.
integer j21[5]
Definition at line 85 of file DDST.c.
integer j22[5]
Definition at line 85 of file DDST.c.
integer j23[5]
Definition at line 85 of file DDST.c.
integer j50[5]
Definition at line 85 of file DDST.c.
integer j51[5]
Definition at line 85 of file DDST.c.
integer j54
Definition at line 102 of file DDST.c.
integer jbr
Definition at line 92 of file DDST.c.
integer jckr
Definition at line 102 of file DDST.c.
integer jcnt1
Definition at line 102 of file DDST.c.
integer jcnt2
Definition at line 102 of file DDST.c.
integer jcnt3
Definition at line 102 of file DDST.c.
integer jcpr
Definition at line 102 of file DDST.c.
integer jcr
Definition at line 102 of file DDST.c.
integer jdr
Definition at line 102 of file DDST.c.
integer jent[5]
Definition at line 76 of file DDST.c.
integer jfind
Definition at line 102 of file DDST.c.
integer jgr
Definition at line 102 of file DDST.c.
integer jiops[5]
Definition at line 76 of file DDST.c.
integer jmin
Definition at line 102 of file DDST.c.
integer jminr
Definition at line 102 of file DDST.c.
integer jph[5]
Definition at line 85 of file DDST.c.
integer jpr
Definition at line 102 of file DDST.c.
integer jpxr
Definition at line 102 of file DDST.c.
integer jsw
Definition at line 92 of file DDST.c.
integer jtkf
Definition at line 102 of file DDST.c.
integer jtlflg[5]
Definition at line 76 of file DDST.c.
integer jtn[5]
Definition at line 76 of file DDST.c.
integer jtr
Definition at line 102 of file DDST.c.
integer ju1[5]
Definition at line 76 of file DDST.c.
integer limfl[5]
Definition at line 76 of file DDST.c.
integer lsv
Definition at line 92 of file DDST.c.
integer lsv1
Definition at line 92 of file DDST.c.
integer mantax
Definition at line 92 of file DDST.c.
integer mdic
Definition at line 102 of file DDST.c.
char modfer[6]
Definition at line 37 of file DDST.c.
integer motmod
Definition at line 92 of file DDST.c.
integer msav
Definition at line 92 of file DDST.c.
integer mulout
Definition at line 92 of file DDST.c.
integer nmbseg
Definition at line 92 of file DDST.c.
integer nmpnts
Definition at line 92 of file DDST.c.
integer notan[5]
Definition at line 85 of file DDST.c.
integer nrec
Definition at line 92 of file DDST.c.
integer numax
Definition at line 92 of file DDST.c.
integer numcnt
Definition at line 92 of file DDST.c.
integer nump
Definition at line 92 of file DDST.c.
integer numpt1
Definition at line 92 of file DDST.c.
integer numsfs
Definition at line 92 of file DDST.c.
integer numsur
Definition at line 92 of file DDST.c.
integer nw
Definition at line 92 of file DDST.c.
integer nwds
Definition at line 92 of file DDST.c.
doublereal ogle[3]
Definition at line 18 of file DDST.c.
doublereal p1[3]
Definition at line 18 of file DDST.c.
doublereal p2[3]
Definition at line 18 of file DDST.c.
doublereal param[6]
Definition at line 18 of file DDST.c.
doublereal past[5]
Definition at line 50 of file DDST.c.
doublereal plncs[5]
Definition at line 67 of file DDST.c.
doublereal plnd[5]
Definition at line 50 of file DDST.c.
doublereal plnd1[5]
Definition at line 67 of file DDST.c.
doublereal plnv[15]
Definition at line 50 of file DDST.c.
doublereal pltst[5]
Definition at line 67 of file DDST.c.
doublereal pmove[3]
Definition at line 28 of file DDST.c.
doublereal r__[6]
Definition at line 18 of file DDST.c.
doublereal ra
Definition at line 28 of file DDST.c.
doublereal rc[5]
Definition at line 50 of file DDST.c.
doublereal rc1
Definition at line 28 of file DDST.c.
doublereal rdrn
Definition at line 18 of file DDST.c.
doublereal refpnt[3]
Definition at line 18 of file DDST.c.
doublereal ri[8]
Definition at line 43 of file DDST.c.
doublereal s[5]
Definition at line 50 of file DDST.c.
doublereal sagl
Definition at line 28 of file DDST.c.
doublereal save[5]
Definition at line 50 of file DDST.c.
doublereal savpar[4]
Definition at line 18 of file DDST.c.
doublereal seg[9]
Definition at line 18 of file DDST.c.
doublereal sfvct[15]
Definition at line 50 of file DDST.c.
doublereal sk[15]
Definition at line 50 of file DDST.c.
doublereal slope
Definition at line 18 of file DDST.c.
doublereal slx[15]
Definition at line 50 of file DDST.c.
doublereal sn[15]
Definition at line 50 of file DDST.c.
doublereal snk[15]
Definition at line 50 of file DDST.c.
doublereal snl[15]
Definition at line 50 of file DDST.c.
doublereal sp[15]
Definition at line 50 of file DDST.c.
doublereal spk[15]
Definition at line 50 of file DDST.c.
doublereal spl[15]
Definition at line 50 of file DDST.c.
doublereal sqroot
Definition at line 18 of file DDST.c.
doublereal stck[5]
Definition at line 67 of file DDST.c.
doublereal stck1[5]
Definition at line 67 of file DDST.c.
doublereal stck2[5]
Definition at line 67 of file DDST.c.
doublereal stckn[5]
Definition at line 67 of file DDST.c.
doublereal strtno
Definition at line 28 of file DDST.c.
doublereal surd
Definition at line 28 of file DDST.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 28 of file DDST.c.
doublereal tak[3]
Definition at line 28 of file DDST.c.
doublereal tal[3]
Definition at line 28 of file DDST.c.
doublereal tangl
Definition at line 18 of file DDST.c.
doublereal tanhi[8]
Definition at line 43 of file DDST.c.
doublereal tanlo[8]
Definition at line 43 of file DDST.c.
doublereal tau[5]
Definition at line 50 of file DDST.c.
doublereal tau1[5]
Definition at line 50 of file DDST.c.
doublereal tau2[5]
Definition at line 50 of file DDST.c.
doublereal tcont[9]
Definition at line 43 of file DDST.c.
doublereal te[3]
Definition at line 28 of file DDST.c.
doublereal tee[15]
Definition at line 67 of file DDST.c.
doublereal tek[3]
Definition at line 28 of file DDST.c.
doublereal tel[3]
Definition at line 28 of file DDST.c.
doublereal tem[10]
Definition at line 28 of file DDST.c.
doublereal temp[24]
Definition at line 28 of file DDST.c.
doublereal tes[3]
Definition at line 18 of file DDST.c.
doublereal tew[3]
Definition at line 18 of file DDST.c.
doublereal th[5]
Definition at line 50 of file DDST.c.
doublereal ti[3]
Definition at line 28 of file DDST.c.
doublereal tik[3]
Definition at line 28 of file DDST.c.
doublereal til[3]
Definition at line 28 of file DDST.c.
doublereal tlhit
Definition at line 28 of file DDST.c.
doublereal tlhite[8]
Definition at line 43 of file DDST.c.
doublereal tlinc[9]
Definition at line 43 of file DDST.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file DDST.c.
doublereal tn[15]
Definition at line 50 of file DDST.c.
doublereal tnl[15]
Definition at line 67 of file DDST.c.
doublereal toolht[15]
Definition at line 50 of file DDST.c.
doublereal toolwd[5]
Definition at line 50 of file DDST.c.
doublereal tp[15]
Definition at line 50 of file DDST.c.
doublereal tpk[15]
Definition at line 50 of file DDST.c.
doublereal u1[15]
Definition at line 50 of file DDST.c.
doublereal u1k[15]
Definition at line 50 of file DDST.c.
doublereal u2[3]
Definition at line 18 of file DDST.c.
doublereal umax[8]
Definition at line 43 of file DDST.c.
doublereal unn
Definition at line 18 of file DDST.c.
doublereal upp
Definition at line 18 of file DDST.c.
doublereal uvec[3]
Definition at line 18 of file DDST.c.
doublereal v[3]
Definition at line 18 of file DDST.c.
doublereal varble[5]
Definition at line 50 of file DDST.c.
doublereal vint
Definition at line 18 of file DDST.c.
doublereal vl
Definition at line 18 of file DDST.c.
doublereal vndir[15]
Definition at line 50 of file DDST.c.
doublereal vnn
Definition at line 18 of file DDST.c.
doublereal vpp
Definition at line 18 of file DDST.c.
doublereal vt[15]
Definition at line 50 of file DDST.c.
doublereal vtem
Definition at line 28 of file DDST.c.
doublereal z__[5]
Definition at line 50 of file DDST.c.
doublereal zl
Definition at line 18 of file DDST.c.
doublereal zl1
Definition at line 18 of file DDST.c.
doublereal zlnorm[3]
Definition at line 18 of file DDST.c.
doublereal zlpnt[3]
Definition at line 18 of file DDST.c.