My Project: DEFEXT.c File Reference
DEFEXT.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define ldef_1 ldef_
#define idef_1 idef_
Functions
int defext_ (doublereal *result)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer ldasiz
integer ierror
integer surfad [4]
integer kwrdsz
integer iblk1
} idef_
static integer c__3 = 3
static integer c__1 = 1
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file DEFEXT.c.
Referenced by defext_().
#define dshar3_1 dshar3_
Definition at line 28 of file DEFEXT.c.
#define idef_1 idef_
Definition at line 41 of file DEFEXT.c.
Referenced by defext_().
#define ldef_1 ldef_
Definition at line 35 of file DEFEXT.c.
Referenced by defext_().
Function Documentation
int defext_ (doublereal * result)
Definition at line 74 of file DEFEXT.c.
References c__1, c__3, def_1, error_(), i__, idef_1, in, inam, ldef_1, print_(), result, undef_(), and unpack_().
Referenced by apt001_(), apt003_(), apt004_(), apt008_(), apt009_(), apt010_(), apt012_(), apt013_(), apt016_(), apt022_(), apt023_(), apt025_(), apt026_(), apt027_(), apt028_(), apt034_(), apt035_(), apt036_(), apt037_(), apt038_(), apt039_(), apt041_(), apt042_(), apt043_(), apt044_(), apt045_(), apt046_(), apt047_(), apt049_(), apt050_(), apt051_(), apt052_(), apt053_(), apt055_(), apt056_(), apt059_(), apt060_(), apt061_(), apt062_(), apt070_(), apt074_(), apt105_(), apt106_(), apt109_(), and xcall_().
 {
     /* Initialized data */
     static integer inam[74] /* was [37][2] */ = { 4,6,15,16,18,19,23,24,
         25,27,29,37,38,43,44,47,48,51,57,58,59,69,70,73,74,75,76,77,79,93,
         5153,5154,5155,5156,5157,5158,5159,1,2,3,3,4,5,6,6,6,7,8,9,9,10,
         11,12,13,14,15,16,10,17,17,18,18,18,18,21,21,19,20,20,20,20,20,20,
         20 };
     static char rnam[8*22] = "APT003  " "APT004  " "APT008  " "APT009  "
         "APT012  " "APT016  " "APT023  " "APT027  " "APT106  " "APT013  "
         "APT044  " "APT059  " "APT056  " "APT073  " "APT053  " "APT055  "
         "APT074  " "APT070  " "APT105  " "APT109  " "APT034  " "DEFEXT??";
     static integer imax = 37;
     static integer max__ = 22;
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, in, is1, is2, is3;
     extern /* Subroutine */ int undef_(doublereal *);
     static char rname[8];
     extern /* Subroutine */ int error_(integer *, char *, ftnlen), print_(
         integer *, doublereal *, integer *), unpack_(doublereal *,
         integer *, integer *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  14.  IDEF BLOCK  *** */
 /*   INVIOLATE INTEGER VARIABLES */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
     /* Parameter adjustments */
     --result;
     /* Function Body */
 /* IMAX: ANZAHL FEHLERNUMMERN, MAX: ANZAHL ROUTINENEN-NAMEN + 1 '??' */
 /* ...     CHECK FOR ERRORS */
     if (idef_1.ierror == 0) {
     goto L20;
     }
     i__1 = imax;
     for (i__ = 1; i__ <= i__1; ++i__) {
     in = max__;
     if (idef_1.ierror != inam[i__ - 1]) {
         goto L810;
     }
     in = inam[i__ + 36];
     goto L820;
 L810:
     ;
     }
 L820:
     s_copy(rname, rnam + (in - 1 << 3), (ftnlen)8, (ftnlen)8);
     error_(&idef_1.ierror, rname, (ftnlen)8);
 L10:
     undef_(&result[1]);
     ldef_1.unflag = FALSE_;
     goto L40;
 L20:
     if (ldef_1.unflag) {
     goto L10;
     }
 /* ...     DEFINITION OK -- CHECK INTFLG, PRNTON AND MOVE R TO RESULT */
     unpack_(&result[1], &is1, &is2, &is3);
 /*   MATRIX ? */
     if (is1 == 18) {
     goto L31;
     }
     i__1 = is2;
     for (i__ = 1; i__ <= i__1; ++i__) {
 /* L30: */
     result[i__] = def_1.r__[i__ - 1];
     }
 L31:
     if (! ldef_1.prnton) {
     goto L40;
     }
     if (is1 > 0 && is1 < 27) {
     print_(&c__3, &result[1], &c__1);
     }
 L40:
     idef_1.ierror = 0;
     for (i__ = 1; i__ <= 10; ++i__) {
 /* L41: */
     def_1.r__[i__ - 1] = 0.f;
     }
     def_1.r__[5] = 1.f;
     return 0;
 } /* defext_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file DEFEXT.c.
doublereal ahold[8]
Definition at line 18 of file DEFEXT.c.
logical altmlt
Definition at line 31 of file DEFEXT.c.
logical bnderr
Definition at line 31 of file DEFEXT.c.
logical boundf
Definition at line 31 of file DEFEXT.c.
doublereal c1[8]
Definition at line 18 of file DEFEXT.c.
doublereal c__[7]
Definition at line 25 of file DEFEXT.c.
integer c__1 = 1 static
Definition at line 46 of file DEFEXT.c.
Referenced by defext_().
integer c__3 = 3 static
Definition at line 45 of file DEFEXT.c.
Referenced by defext_().
logical canflg
Definition at line 31 of file DEFEXT.c.
struct { ... } def_
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file DEFEXT.c.
integer iblk1
Definition at line 38 of file DEFEXT.c.
struct { ... } idef_
integer ierror
Definition at line 38 of file DEFEXT.c.
logical jcs
Definition at line 31 of file DEFEXT.c.
logical jds
Definition at line 31 of file DEFEXT.c.
integer kwrdsz
Definition at line 38 of file DEFEXT.c.
doublereal l[4]
Definition at line 25 of file DEFEXT.c.
integer ldasiz
Definition at line 38 of file DEFEXT.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file DEFEXT.c.
doublereal p[16]
Definition at line 25 of file DEFEXT.c.
logical pchlst
Definition at line 31 of file DEFEXT.c.
logical prnton
Definition at line 31 of file DEFEXT.c.
doublereal r__[10]
Definition at line 18 of file DEFEXT.c.
doublereal ref[8]
Definition at line 18 of file DEFEXT.c.
logical refflg
Definition at line 31 of file DEFEXT.c.
logical refmot
Definition at line 31 of file DEFEXT.c.
doublereal sc[16]
Definition at line 25 of file DEFEXT.c.
logical subflg
Definition at line 31 of file DEFEXT.c.
integer surfad[4]
Definition at line 38 of file DEFEXT.c.
doublereal t[12]
Definition at line 25 of file DEFEXT.c.
doublereal t1[12]
Definition at line 25 of file DEFEXT.c.
logical tabprt
Definition at line 31 of file DEFEXT.c.
logical unflag
Definition at line 31 of file DEFEXT.c.
doublereal v[10]
Definition at line 25 of file DEFEXT.c.
logical zflag
Definition at line 31 of file DEFEXT.c.