My Project: DEVCAL.c File Reference
DEVCAL.c File Reference
#include "f2c.h"
Macros
#define ibugg_1 ibugg_
Functions
int devcal_ (doublereal *q, doublereal *tn, doublereal *p0, doublereal *p1, doublereal *dev)
Variables
struct {
integer ibug
integer ipcolc
integer ipcolm
} ibugg_
static doublereal c_b4 = 1.
static integer c__3 = 3
static integer c__1 = 1
static integer c_n3 = -3
static integer c_n1 = -1
Macro Definition Documentation
#define ibugg_1 ibugg_
Definition at line 21 of file DEVCAL.c.
Referenced by devcal_().
Function Documentation
int devcal_ (doublereal * q, doublereal * tn, doublereal * p0, doublereal * p1, doublereal * dev)
Definition at line 33 of file DEVCAL.c.
References a, b, bad_(), c__1, c__3, c_b4, c_n1, c_n3, cprint_(), dotf_(), h2, h__, i__, ibugg_1, p1, q, s, tn, u, v, and zero.
Referenced by gchk_().
 {
     /* Initialized data */
     static doublereal z1em10 = 1e-10;
     static doublereal z1em20 = 1e-20;
     static doublereal zero = 0.;
     /* Builtin functions */
     double d_sign(doublereal *, doublereal *), sqrt(doublereal);
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static doublereal a, b, h__[3];
     static integer i__;
     static doublereal s, u, v[3], h2, vq[3];
     extern /* Subroutine */ int bad_(integer *, integer *, char *, doublereal
         *, ftnlen), dotf_(doublereal *, doublereal *, doublereal *);
     static char badmsg[20];
     extern /* Subroutine */ int cprint_(char *, ftnlen);
 /* .... DEBUG FLAGS */
     /* Parameter adjustments */
     --p1;
     --p0;
     --tn;
     --q;
     /* Function Body */
 /* .... COMPUTE (P1-P0) AND (Q-P0) */
     for (i__ = 1; i__ <= 3; ++i__) {
     v[i__ - 1] = p1[i__] - p0[i__];
     vq[i__ - 1] = q[i__] - p0[i__];
 /* L10: */
     }
 /* .... COMPUTE LOCAL U WHERE MAX DEVIATION OCCURS */
     dotf_(&a, v, vq);
     dotf_(&b, v, v);
     if (b > z1em10) {
     u = a / b;
     } else {
     u = .5f;
     }
 /* .... COMPUTE DEVIATION */
     for (i__ = 1; i__ <= 3; ++i__) {
     h__[i__ - 1] = q[i__] - p0[i__] - u * v[i__ - 1];
 /* L20: */
     }
     dotf_(&h2, h__, h__);
 /* .... ADD SIGN TO INDICATE WHETHER TOWARDS OR AWAY FROM TOOL */
 /*     POSITIVE TOWARDS TOOL, NEGATIVE AWAY FROM TOOL */
     dotf_(&s, h__, &tn[1]);
     s = d_sign(&c_b4, &s);
     if (h2 > z1em20) {
     *dev = s * sqrt(h2);
     } else {
     *dev = zero;
     }
     if (ibugg_1.ibug == 11) {
     s_copy(badmsg, " AFTER DEVCAL", (ftnlen)20, (ftnlen)13);
     cprint_(badmsg, (ftnlen)20);
     bad_(&c__3, &c__1, "P0  ", &p0[1], (ftnlen)4);
     bad_(&c_n3, &c__1, "P1  ", &p1[1], (ftnlen)4);
     bad_(&c__3, &c__1, "Q   ", &q[1], (ftnlen)4);
     bad_(&c_n3, &c__1, "TN  ", &tn[1], (ftnlen)4);
     bad_(&c__3, &c__1, "H   ", h__, (ftnlen)4);
     bad_(&c__1, &c__1, "S   ", &s, (ftnlen)4);
     bad_(&c_n1, &c__1, "DEV ", dev, (ftnlen)4);
     }
     return 0;
 } /* devcal_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 27 of file DEVCAL.c.
Referenced by devcal_().
integer c__3 = 3 static
Definition at line 26 of file DEVCAL.c.
Referenced by devcal_().
doublereal c_b4 = 1. static
Definition at line 25 of file DEVCAL.c.
Referenced by devcal_().
integer c_n1 = -1 static
Definition at line 29 of file DEVCAL.c.
Referenced by devcal_().
integer c_n3 = -3 static
Definition at line 28 of file DEVCAL.c.
Referenced by devcal_().
integer ibug
Definition at line 18 of file DEVCAL.c.
struct { ... } ibugg_
integer ipcolc
Definition at line 18 of file DEVCAL.c.
integer ipcolm
Definition at line 18 of file DEVCAL.c.