My Project: DNTCUT.c File Reference
DNTCUT.c File Reference
#include "f2c.h"
Macros
#define ifxcor_1 ifxcor_
#define knumbr_1 knumbr_
#define hold_1 hold_
Functions
int dntcut_ (void)
int dntcuh_ (void)
Variables
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
integer jhldfg
integer ithcnt
integer itabh [100]
} hold_
static integer c__0 = 0
Macro Definition Documentation
#define hold_1 hold_
Definition at line 39 of file DNTCUT.c.
Referenced by dntcut_().
#define ifxcor_1 ifxcor_
Definition at line 25 of file DNTCUT.c.
Referenced by dntcuh_(), and dntcut_().
#define knumbr_1 knumbr_
Definition at line 33 of file DNTCUT.c.
Referenced by dntcuh_(), and dntcut_().
Function Documentation
int dntcuh_ (void)
Definition at line 112 of file DNTCUT.c.
References apt299_(), bcdf_(), c__0, ifxcor_1, and knumbr_1.
Referenced by apt211_().
 {
     /* Initialized data */
     static char ppword[8] = "DNTCUT  ";
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt299_(integer *, integer *, integer *,
         integer *);
     static integer ippwrd[2];
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...  DONT OUTPUT CUTTER CENTERS ON CLTAPE */
     ippwrd[0] = bcdf_(ppword, (ftnlen)4);
     ippwrd[1] = bcdf_(ppword + 4, (ftnlen)4);
     apt299_(&c__0, ippwrd, &c__0, &c__0);
     ifxcor_1.icut = knumbr_1.k1;
     return 0;
 } /* dntcuh_ */
int dntcut_ (void)
Definition at line 50 of file DNTCUT.c.
References apt299_(), bcdf_(), c__0, hold_1, ifxcor_1, and knumbr_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static char ppword[8] = "DNTCUT  ";
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt299_(integer *, integer *, integer *,
         integer *);
     static integer ippwrd[2];
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     if (hold_1.jhldfg == 0) {
     goto L1;
     }
     hold_1.itabh[hold_1.ithcnt - 1] = 7;
     ++hold_1.ithcnt;
     return 0;
 L1:
 /* ...  DONT OUTPUT CUTTER CENTERS ON CLTAPE */
     ippwrd[0] = bcdf_(ppword, (ftnlen)4);
     ippwrd[1] = bcdf_(ppword + 4, (ftnlen)4);
     apt299_(&c__0, ippwrd, &c__0, &c__0);
     ifxcor_1.icut = knumbr_1.k1;
     return 0;
 } /* dntcut_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 43 of file DNTCUT.c.
Referenced by dntcuh_(), and dntcut_().
struct { ... } hold_
integer i3dflg
Definition at line 18 of file DNTCUT.c.
integer iaerr
Definition at line 18 of file DNTCUT.c.
integer iautps
Definition at line 18 of file DNTCUT.c.
integer ibegin
Definition at line 18 of file DNTCUT.c.
integer ic
Definition at line 18 of file DNTCUT.c.
integer icheck
Definition at line 18 of file DNTCUT.c.
integer icl
Definition at line 18 of file DNTCUT.c.
integer ics
Definition at line 18 of file DNTCUT.c.
integer icscnt
Definition at line 18 of file DNTCUT.c.
integer ictdef
Definition at line 18 of file DNTCUT.c.
integer icut
Definition at line 18 of file DNTCUT.c.
integer ids
Definition at line 18 of file DNTCUT.c.
integer ier
Definition at line 18 of file DNTCUT.c.
struct { ... } ifxcor_
integer igo
Definition at line 18 of file DNTCUT.c.
integer igoto
Definition at line 18 of file DNTCUT.c.
integer igoug
Definition at line 18 of file DNTCUT.c.
integer igs
Definition at line 18 of file DNTCUT.c.
integer inops
Definition at line 18 of file DNTCUT.c.
integer ips
Definition at line 18 of file DNTCUT.c.
integer ipsdef
Definition at line 18 of file DNTCUT.c.
integer ipt1
Definition at line 18 of file DNTCUT.c.
integer is
Definition at line 18 of file DNTCUT.c.
integer iseg
Definition at line 18 of file DNTCUT.c.
integer iseqno
Definition at line 18 of file DNTCUT.c.
integer isrch
Definition at line 18 of file DNTCUT.c.
integer istrup
Definition at line 18 of file DNTCUT.c.
integer it
Definition at line 18 of file DNTCUT.c.
integer itabh[100]
Definition at line 36 of file DNTCUT.c.
integer ithcnt
Definition at line 36 of file DNTCUT.c.
integer jbr
Definition at line 18 of file DNTCUT.c.
integer jhldfg
Definition at line 36 of file DNTCUT.c.
integer jsw
Definition at line 18 of file DNTCUT.c.
integer k0
Definition at line 28 of file DNTCUT.c.
integer k1
Definition at line 28 of file DNTCUT.c.
integer k10
Definition at line 28 of file DNTCUT.c.
integer k1013
Definition at line 28 of file DNTCUT.c.
integer k12
Definition at line 28 of file DNTCUT.c.
integer k13
Definition at line 28 of file DNTCUT.c.
integer k15
Definition at line 28 of file DNTCUT.c.
integer k16
Definition at line 28 of file DNTCUT.c.
integer k18
Definition at line 28 of file DNTCUT.c.
integer k19
Definition at line 28 of file DNTCUT.c.
integer k1e4
Definition at line 28 of file DNTCUT.c.
integer k1e6
Definition at line 28 of file DNTCUT.c.
integer k2
Definition at line 28 of file DNTCUT.c.
integer k23
Definition at line 28 of file DNTCUT.c.
integer k24
Definition at line 28 of file DNTCUT.c.
integer k25
Definition at line 28 of file DNTCUT.c.
integer k26
Definition at line 28 of file DNTCUT.c.
integer k27
Definition at line 28 of file DNTCUT.c.
integer k29
Definition at line 28 of file DNTCUT.c.
integer k3
Definition at line 28 of file DNTCUT.c.
integer k30
Definition at line 28 of file DNTCUT.c.
integer k31
Definition at line 28 of file DNTCUT.c.
integer k32
Definition at line 28 of file DNTCUT.c.
integer k33
Definition at line 28 of file DNTCUT.c.
integer k34
Definition at line 28 of file DNTCUT.c.
integer k4
Definition at line 28 of file DNTCUT.c.
integer k44
Definition at line 28 of file DNTCUT.c.
integer k45
Definition at line 28 of file DNTCUT.c.
integer k46
Definition at line 28 of file DNTCUT.c.
integer k47
Definition at line 28 of file DNTCUT.c.
integer k48
Definition at line 28 of file DNTCUT.c.
integer k5
Definition at line 28 of file DNTCUT.c.
integer k50
Definition at line 28 of file DNTCUT.c.
integer k51
Definition at line 28 of file DNTCUT.c.
integer k52
Definition at line 28 of file DNTCUT.c.
integer k6
Definition at line 28 of file DNTCUT.c.
integer k7
Definition at line 28 of file DNTCUT.c.
integer k8
Definition at line 28 of file DNTCUT.c.
integer k9
Definition at line 28 of file DNTCUT.c.
integer km1
Definition at line 28 of file DNTCUT.c.
struct { ... } knumbr_
integer lsv
Definition at line 18 of file DNTCUT.c.
integer lsv1
Definition at line 18 of file DNTCUT.c.
integer mantax
Definition at line 18 of file DNTCUT.c.
integer motmod
Definition at line 18 of file DNTCUT.c.
integer msav
Definition at line 18 of file DNTCUT.c.
integer mulout
Definition at line 18 of file DNTCUT.c.
integer nmbseg
Definition at line 18 of file DNTCUT.c.
integer nmpnts
Definition at line 18 of file DNTCUT.c.
integer nrec
Definition at line 18 of file DNTCUT.c.
integer numax
Definition at line 18 of file DNTCUT.c.
integer numcnt
Definition at line 18 of file DNTCUT.c.
integer nump
Definition at line 18 of file DNTCUT.c.
integer numpt1
Definition at line 18 of file DNTCUT.c.
integer numsfs
Definition at line 18 of file DNTCUT.c.
integer numsur
Definition at line 18 of file DNTCUT.c.
integer nw
Definition at line 18 of file DNTCUT.c.
integer nwds
Definition at line 18 of file DNTCUT.c.