My Project: DOTF.c File Reference
DOTF.c File Reference
#include "f2c.h"
Macros
#define znumbr_1 znumbr_
#define knumbr_1 knumbr_
Functions
int dotf_ (doublereal *result, doublereal *arg1, doublereal *arg2)
Variables
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__10 = 10
Macro Definition Documentation
#define knumbr_1 knumbr_
Definition at line 31 of file DOTF.c.
#define znumbr_1 znumbr_
Definition at line 23 of file DOTF.c.
Referenced by dotf_().
Function Documentation
int dotf_ (doublereal * result, doublereal * arg1, doublereal * arg2)
Definition at line 48 of file DOTF.c.
References arg1, arg2, c__10, ckdef_(), error_(), i__, and znumbr_1.
Referenced by abw_(), ader_(), ajundd_(), algo1_(), algo2_(), amind_(), apt013_(), apt065_(), apt069_(), apt073_(), apt075_(), apt088_(), apt240_(), axset_(), balone_(), baltwo_(), calcb_(), calct_(), calmxb_(), ccurv_(), check_(), crvlen_(), curcal_(), ddssrf_(), devcal_(), dgeom_(), gauss_(), gouge_(), hulcut_(), midkur_(), mixal_(), pchprc_(), pencut_(), qabpst_(), scon_(), scurv_(), shellb_(), srfdir_(), sspath_(), stepck_(), tcsphr_(), tlnorm_(), txhull_(), u1comp_(), xcall_(), and xtpcal_().
 {
     static integer i__;
     static doublereal ds[6];
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --arg2;
     --arg1;
     /* Function Body */
     if (ckdef_(&arg1[1]) || ckdef_(&arg2[1])) {
     goto L20;
     }
 /* ...     MOVE ARGUMENTS TO DOUBLE PRECISION SCRATCH LOCATIONS */
     for (i__ = 1; i__ <= 3; ++i__) {
     ds[i__ - 1] = arg1[i__];
     ds[i__ + 2] = arg2[i__];
 /* L10: */
     }
 /* ...     COMPUTE DOT PRODUCT */
     *result = ds[0] * ds[3] + ds[1] * ds[4] + ds[2] * ds[5];
     goto L9;
 /* ...     ISSUE DIAGNOSTIC, INPUT UNDEFINED, RESULT=0 */
 L20:
     error_(&c__10, "DOTF   ", (ftnlen)7);
     *result = znumbr_1.z0;
 L9:
     return 0;
 } /* dotf_ */
Variable Documentation
integer c__10 = 10 static
Definition at line 35 of file DOTF.c.
Referenced by dotf_().
doublereal degrad
Definition at line 18 of file DOTF.c.
integer k0
Definition at line 26 of file DOTF.c.
integer k1
Definition at line 26 of file DOTF.c.
integer k10
Definition at line 26 of file DOTF.c.
integer k1013
Definition at line 26 of file DOTF.c.
integer k12
Definition at line 26 of file DOTF.c.
integer k13
Definition at line 26 of file DOTF.c.
integer k15
Definition at line 26 of file DOTF.c.
integer k16
Definition at line 26 of file DOTF.c.
integer k18
Definition at line 26 of file DOTF.c.
integer k19
Definition at line 26 of file DOTF.c.
integer k1e4
Definition at line 26 of file DOTF.c.
integer k1e6
Definition at line 26 of file DOTF.c.
integer k2
Definition at line 26 of file DOTF.c.
integer k23
Definition at line 26 of file DOTF.c.
integer k24
Definition at line 26 of file DOTF.c.
integer k25
Definition at line 26 of file DOTF.c.
integer k26
Definition at line 26 of file DOTF.c.
integer k27
Definition at line 26 of file DOTF.c.
integer k29
Definition at line 26 of file DOTF.c.
integer k3
Definition at line 26 of file DOTF.c.
integer k30
Definition at line 26 of file DOTF.c.
integer k31
Definition at line 26 of file DOTF.c.
integer k32
Definition at line 26 of file DOTF.c.
integer k33
Definition at line 26 of file DOTF.c.
integer k34
Definition at line 26 of file DOTF.c.
integer k4
Definition at line 26 of file DOTF.c.
integer k44
Definition at line 26 of file DOTF.c.
integer k45
Definition at line 26 of file DOTF.c.
integer k46
Definition at line 26 of file DOTF.c.
integer k47
Definition at line 26 of file DOTF.c.
integer k48
Definition at line 26 of file DOTF.c.
integer k5
Definition at line 26 of file DOTF.c.
integer k50
Definition at line 26 of file DOTF.c.
integer k51
Definition at line 26 of file DOTF.c.
integer k52
Definition at line 26 of file DOTF.c.
integer k6
Definition at line 26 of file DOTF.c.
integer k7
Definition at line 26 of file DOTF.c.
integer k8
Definition at line 26 of file DOTF.c.
integer k9
Definition at line 26 of file DOTF.c.
integer km1
Definition at line 26 of file DOTF.c.
struct { ... } knumbr_
doublereal pi
Definition at line 18 of file DOTF.c.
doublereal z0
Definition at line 18 of file DOTF.c.
doublereal z1
Definition at line 18 of file DOTF.c.
doublereal z10
Definition at line 18 of file DOTF.c.
doublereal z11em1
Definition at line 18 of file DOTF.c.
doublereal z12em1
Definition at line 18 of file DOTF.c.
doublereal z1e38
Definition at line 18 of file DOTF.c.
doublereal z1e6
Definition at line 18 of file DOTF.c.
doublereal z1em1
Definition at line 18 of file DOTF.c.
doublereal z1em2
Definition at line 18 of file DOTF.c.
doublereal z1em3
Definition at line 18 of file DOTF.c.
doublereal z1em5
Definition at line 18 of file DOTF.c.
doublereal z1em6
Definition at line 18 of file DOTF.c.
doublereal z1em7
Definition at line 18 of file DOTF.c.
doublereal z1em9
Definition at line 18 of file DOTF.c.
doublereal z2
Definition at line 18 of file DOTF.c.
doublereal z3
Definition at line 18 of file DOTF.c.
doublereal z5
Definition at line 18 of file DOTF.c.
doublereal z5em1
Definition at line 18 of file DOTF.c.
doublereal z5em6
Definition at line 18 of file DOTF.c.
doublereal z6em1
Definition at line 18 of file DOTF.c.
doublereal z90
Definition at line 18 of file DOTF.c.
doublereal z9em1
Definition at line 18 of file DOTF.c.
doublereal zm1
Definition at line 18 of file DOTF.c.
struct { ... } znumbr_