My Project: dummy.c File Reference
dummy.c File Reference
#include "f2c.h"
Functions
int libsestablish_ (void)
int time_ (char *ct, ftnlen ct_len)
int date_ (void)
int libsrevert_ (void)
int libssignal_ (void)
int cputim_ (void)
Variables
static integer c__9 = 9
static integer c__1 = 1
Function Documentation
int cputim_ (void)
Definition at line 111 of file dummy.c.
References c__1, and c__9.
Referenced by clocf4_().
 {
     /* Builtin functions */
     integer s_wsle(cilist *), do_lio(integer *, integer *, char *, ftnlen),
         e_wsle(void);
     /* Fortran I/O blocks */
     static cilist io___6 = { 0, 6, 0, 0, 0 };
     s_wsle(&io___6);
     do_lio(&c__9, &c__1, "unimplemented VAX subroutine CPUTIM", (ftnlen)35);
     e_wsle();
     return 0;
 } /* cputim_ */
int date_ (void)
Definition at line 61 of file dummy.c.
References c__1, and c__9.
Referenced by artime_(), and punch_().
 {
     /* Builtin functions */
     integer s_wsle(cilist *), do_lio(integer *, integer *, char *, ftnlen),
         e_wsle(void);
     /* Fortran I/O blocks */
     static cilist io___3 = { 0, 6, 0, 0, 0 };
     s_wsle(&io___3);
     do_lio(&c__9, &c__1, "unimplemented VAX subroutine DATE", (ftnlen)33);
     e_wsle();
     return 0;
 } /* date_ */
int libsestablish_ (void)
Definition at line 21 of file dummy.c.
References c__1, and c__9.
Referenced by apt241_().
 {
     /* Builtin functions */
     integer s_wsle(cilist *), do_lio(integer *, integer *, char *, ftnlen),
         e_wsle(void);
     /* Fortran I/O blocks */
     static cilist io___1 = { 0, 6, 0, 0, 0 };
     s_wsle(&io___1);
     do_lio(&c__9, &c__1, "unimplemented VAX subroutine LIB$ESTABLISH", (
         ftnlen)42);
     e_wsle();
     return 0;
 } /* libsestablish_ */
int libsrevert_ (void)
Definition at line 77 of file dummy.c.
References c__1, and c__9.
Referenced by apt201_(), cutter_(), and go_().
 {
     /* Builtin functions */
     integer s_wsle(cilist *), do_lio(integer *, integer *, char *, ftnlen),
         e_wsle(void);
     /* Fortran I/O blocks */
     static cilist io___4 = { 0, 6, 0, 0, 0 };
     s_wsle(&io___4);
     do_lio(&c__9, &c__1, "unimplemented VAX subroutine LIB$REVERT", (ftnlen)
         39);
     e_wsle();
     return 0;
 } /* libsrevert_ */
int libssignal_ (void)
Definition at line 94 of file dummy.c.
References c__1, and c__9.
 {
     /* Builtin functions */
     integer s_wsle(cilist *), do_lio(integer *, integer *, char *, ftnlen),
         e_wsle(void);
     /* Fortran I/O blocks */
     static cilist io___5 = { 0, 6, 0, 0, 0 };
     s_wsle(&io___5);
     do_lio(&c__9, &c__1, "unimplemented VAX subroutine LIB$SIGNAL", (ftnlen)
         39);
     e_wsle();
     return 0;
 } /* libssignal_ */
int time_ (char * ct, ftnlen ct_len)
Definition at line 38 of file dummy.c.
References c__1, and c__9.
Referenced by artime_().
 {
     /* Builtin functions */
     integer s_wsle(cilist *), do_lio(integer *, integer *, char *, ftnlen),
         e_wsle(void);
     /* Fortran I/O blocks */
     static cilist io___2 = { 0, 6, 0, 0, 0 };
 /*     TODO */
     s_wsle(&io___2);
     do_lio(&c__9, &c__1, "unimplemented VAX subroutine TIME", (ftnlen)33);
     e_wsle();
 /*      i=time8() */
 /*      call ctime(i,ct) */
 /*      call ctime(i,ctme) */
 /*      call ltime(i,vals) */
 /*      write(*,*)ctme */
 /*      ct=ctme */
     return 0;
 } /* time_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 18 of file dummy.c.
Referenced by cputim_(), date_(), libsestablish_(), libsrevert_(), libssignal_(), and time_().
integer c__9 = 9 static
Definition at line 17 of file dummy.c.
Referenced by cputim_(), date_(), libsestablish_(), libsrevert_(), libssignal_(), and time_().