My Project: EPILOG.c File Reference
EPILOG.c File Reference
#include "f2c.h"
Macros
#define prt_1 prt_
#define macseg_1 macseg_
#define alopn ((logical *)&macseg_1)
#define assemb ((logical *)&prt_1 + 3)
#define interp ((logical *)&prt_1 + 2)
Functions
int epilog_ (void)
Variables
struct {
integer prt [7]
} prt_
struct {
integer macseg [6]
} macseg_
static integer c__2 = 2
Macro Definition Documentation
#define alopn ((logical *)&macseg_1)
Referenced by epilog_().
#define assemb ((logical *)&prt_1 + 3)
Referenced by epilog_().
#define interp ((logical *)&prt_1 + 2)
Referenced by epilog_().
#define macseg_1 macseg_
Definition at line 27 of file EPILOG.c.
#define prt_1 prt_
Definition at line 21 of file EPILOG.c.
Function Documentation
int epilog_ (void)
Definition at line 45 of file EPILOG.c.
References alopn, assemb, c__2, ieplog_(), iflag, interp, and libopc_().
Referenced by macrec_(), and pro026_().
 {
     /* Local variables */
     static integer iflag;
 #define alopn ((logical *)&macseg_1)
     extern /* Subroutine */ int libopc_(integer *, integer *);
 #define assemb ((logical *)&prt_1 + 3)
     extern /* Subroutine */ int ieplog_(void);
 #define interp ((logical *)&prt_1 + 2)
 /*       14.    I. L. LIST OPTION FLAGS */
 /* INTERP:      NORMALLY TRUE,INDICATING INTERPRETIVE APPROACH DEFAULT */
 /* ASSEMB:      SET TRUE INDICATES ASSEMBLY APPROACH (CONTRL/ASMBLE) */
 /*       36.    SYSTEM MACRO AND SEGMENT READ VARIABLES */
 /* ALOPN:       TRUE AFTER MACRO OR PART PROGRAM SEGMENT LIBRARY OPENED */
 /* ** */
 /*     IF(ASSEMB)CALL AEPLOG */
     if (*interp) {
     ieplog_();
     }
 /* ...      TERMINATE TRANSLATION */
     *assemb = FALSE_;
     *interp = FALSE_;
     if (*alopn) {
     libopc_(&c__2, &iflag);
     }
     return 0;
 } /* epilog_ */
Variable Documentation
integer c__2 = 2 static
Definition at line 31 of file EPILOG.c.
Referenced by epilog_().
integer macseg[6]
Definition at line 24 of file EPILOG.c.
struct { ... } macseg_
integer prt[7]
Definition at line 18 of file EPILOG.c.
struct { ... } prt_