My Project: ERROUT.c File Reference
ERROUT.c File Reference
#include "f2c.h"
Macros
#define exerrw_1 exerrw_
#define exerrt_1 exerrt_
Functions
int errout_ (integer *nerr)
Variables
struct {
integer errad1 [389]
integer errad2 [389]
} exerrw_
struct {
char errtxt [25152]
} exerrt_
static integer c__8 = 8
static integer c__52 = 52
Macro Definition Documentation
#define exerrt_1 exerrt_
Definition at line 27 of file ERROUT.c.
Referenced by errout_().
#define exerrw_1 exerrw_
Definition at line 21 of file ERROUT.c.
Referenced by errout_().
Function Documentation
int errout_ (integer * nerr)
Definition at line 47 of file ERROUT.c.
References b, c__52, c__8, cform_(), cprint_(), exerrt_1, exerrw_1, i__, ii, k, numb, and number.
Referenced by aerr2_(), aerr_(), errlod_(), and error_().
 {
     /* Initialized data */
     static char b[120] = "                                                  "
         "                                                                "
         "      ";
     static char notext[52] = "THERE IS NO DIAGNOSTIC MESSAGE FOR THIS ERROR "
         "NUMBER";
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, k, ii, kk, numb;
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen);
     static integer number;
     extern /* Subroutine */ int cprint_(char *, ftnlen);
     static integer nummin, nummer, nummax;
 /* ...                ...SYMBOLIC FILE DEFINITIONS... */
 /* ...                ...ERROR DIAGNOSTICS */
 /* ...     POSITION OF THE CURRENT ERROR NUMBER */
     i__ = 0;
     nummin = 1;
     nummax = 6288;
     number = abs(*nerr);
 L10:
     nummer = (nummin + nummax) / 2;
     numb = exerrw_1.errad1[nummer - 1];
     if (i__ > 389) {
     goto L40;
     }
     ++i__;
     if ((i__1 = number - numb) < 0) {
     goto L30;
     } else if (i__1 == 0) {
     goto L60;
     } else {
     goto L20;
     }
 L20:
     nummin = nummer + 1;
     goto L10;
 L30:
     nummax = nummer - 1;
     goto L10;
 L40:
     cform_(notext, b, &c__8, &c__52, (ftnlen)52, (ftnlen)120);
     cprint_(b, (ftnlen)120);
     goto L80;
 L60:
     kk = exerrw_1.errad2[nummer - 1];
     if (nummer == 1) {
     ii = 1;
     } else {
     ii = exerrw_1.errad2[nummer - 2] + 1;
     }
     k = 4;
     i__1 = kk;
     for (i__ = ii; i__ <= i__1; ++i__) {
     if (k >= 116) {
         cprint_(b, (ftnlen)120);
         k = 4;
     }
     k += 4;
     s_copy(b + (k - 1), exerrt_1.errtxt + (i__ - 1 << 2), (ftnlen)4, (
         ftnlen)4);
 /* L70: */
     }
     cprint_(b, (ftnlen)120);
 L80:
     return 0;
 } /* errout_ */
Variable Documentation
integer c__52 = 52 static
Definition at line 32 of file ERROUT.c.
Referenced by errout_().
integer c__8 = 8 static
Definition at line 31 of file ERROUT.c.
Referenced by errout_().
integer errad1[389]
Definition at line 18 of file ERROUT.c.
integer errad2[389]
Definition at line 18 of file ERROUT.c.
char errtxt[25152]
Definition at line 24 of file ERROUT.c.
struct { ... } exerrt_
struct { ... } exerrw_