My Project: ERROR.c File Reference
ERROR.c File Reference
#include "f2c.h"
Macros
#define symfil_1 symfil_
#define super_1 super_
#define darray_1 darray_
#define cflags ((logical *)&super_1)
#define lxtras ((logical *)&super_1 + 9)
Functions
int error_ (integer *iarg, char *subnam, ftnlen subnam_len)
Variables
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
struct {
logical err
logical xc
logical cl
logical px
integer errx
logical end
logical fini
logical asm__
logical abend
integer xtras [7]
} super_
struct {
char darray [120]
} darray_
static integer c__1 = 1
static integer c__18 = 18
static integer c__19 = 19
static integer c__8 = 8
static integer c__27 = 27
static integer c__5 = 5
static integer c__36 = 36
static integer c__3 = 3
static integer c__39 = 39
static integer c__44 = 44
static integer c__17 = 17
static integer c__61 = 61
static integer c__69 = 69
static integer c__10 = 10
Macro Definition Documentation
#define cflags ((logical *)&super_1)
#define darray_1 darray_
Definition at line 39 of file ERROR.c.
Referenced by error_().
#define lxtras ((logical *)&super_1 + 9)
#define super_1 super_
Definition at line 33 of file ERROR.c.
Referenced by error_().
#define symfil_1 symfil_
Definition at line 24 of file ERROR.c.
Referenced by error_().
Function Documentation
int error_ (integer * iarg, char * subnam, ftnlen subnam_len)
Definition at line 73 of file ERROR.c.
References bcdf_(), c__1, c__10, c__17, c__18, c__19, c__27, c__3, c__36, c__39, c__44, c__5, c__61, c__69, c__8, cform_(), cprint_(), darray_1, errout_(), ewrite_(), first, iarg, iconv_(), ierr, ir, record_(), super_1, and symfil_1.
Referenced by anglb_(), anglf_(), apt004_(), apt008_(), apt027_(), apt033_(), apt059_(), apt071_(), apt074_(), apt088_(), apt090_(), apt094_(), apt100_(), apt103_(), apt104_(), apt107_(), apt108_(), arcosb_(), arcosf_(), arsinb_(), arsinf_(), atape_(), canf_(), cirdef_(), ckdef_(), cldat_(), cldatf_(), defext_(), distf_(), dotf_(), floseg_(), gclear_(), gotopn_(), intsec_(), ldard_(), lindef_(), lnthf_(), log10f_(), logf_(), numf1_(), numf2_(), parmf1_(), parmf2_(), pocket_(), refsys_(), region_(), schtb_(), scon_(), spatf_(), sqrtf_(), sspath_(), tlnorm_(), tmdcs_(), units_(), and zsurf_().
 {
     /* Initialized data */
     static integer ierrn = 20;
     static integer errlev[20] = { 2,3,8,9,30,40,45,49,50,71,84,92,94,5129,0,0,
         0,0,0,0 };
     static char warn[8] = " WARNING";
     static char erro[8] = "  ERROR ";
     static integer kgerr[10] = { 0,0,1308622848,0,1308622848,1,1308622848,0,0,
         0 };
     static logical first = TRUE_;
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer ir, nr;
     extern integer bcdf_(char *, ftnlen);
     static integer larg, ierr;
     static char errr[8];
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen), iconv_(integer *, char *, integer *, integer *,
         ftnlen);
     static integer kerrx;
 #define cflags ((logical *)&super_1)
     extern /* Subroutine */ int record_(integer *), cprint_(char *, ftnlen),
         ewrite_(integer *, integer *, integer *, integer *, integer *);
 #define lxtras ((logical *)&super_1 + 9)
     extern /* Subroutine */ int errout_(integer *);
 /* ...            SYSTEM I/O FILE NAMES */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /* ...                SYSTEM I/O FILES */
 /* ...      32.  PARAMETERS REQUIRED BY SUPERVISOR */
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
 /* ... INITILIZE ARRAY INDICATING WHICH ERRORS ARE OF SEVERITY LEVEL FOUR. */
     if (first) {
     kgerr[0] = bcdf_("GERR", (ftnlen)4);
     kgerr[1] = bcdf_("    ", (ftnlen)4);
     first = FALSE_;
     }
     larg = *iarg;
 /* ... SET ERROR LEVEL INDICATOR FOR THE SUPERVISOR. */
     kerrx = 4;
     i__1 = ierrn;
     for (ierr = 1; ierr <= i__1; ++ierr) {
     if (larg == errlev[ierr - 1]) {
         goto L8;
     }
 /* L5: */
     }
     kerrx = 8;
 L8:
     ++super_1.xtras[8 / kerrx - 1];
     kgerr[7] = larg;
     cprint_(darray_1.darray, (ftnlen)120);
     record_(&kgerr[3]);
     s_copy(errr, warn, (ftnlen)8, (ftnlen)8);
     if (kerrx > 4) {
     s_copy(errr, erro, (ftnlen)8, (ftnlen)8);
     }
     if (kerrx == 4 && super_1.errx < 4) {
     super_1.errx = 4;
     }
     if (kerrx == 8 && super_1.errx < 8) {
     super_1.errx = 8;
     }
     nr = 0;
     kgerr[8] = bcdf_(subnam, (ftnlen)4);
     kgerr[9] = bcdf_(subnam + 4, (ftnlen)4);
     cform_(" ***** DEFINITION ", darray_1.darray, &c__1, &c__18, (ftnlen)18, (
         ftnlen)120);
     cform_(errr, darray_1.darray, &c__19, &c__8, (ftnlen)8, (ftnlen)120);
     iconv_(&larg, darray_1.darray, &c__27, &c__5, (ftnlen)120);
     cform_("ISN", darray_1.darray, &c__36, &c__3, (ftnlen)3, (ftnlen)120);
     iconv_(&kgerr[3], darray_1.darray, &c__39, &c__5, (ftnlen)120);
     cform_(" FROM SUBROUTINE ", darray_1.darray, &c__44, &c__17, (ftnlen)17, (
         ftnlen)120);
     cform_(subnam, darray_1.darray, &c__61, &c__8, (ftnlen)8, (ftnlen)120);
     cform_("*****", darray_1.darray, &c__69, &c__5, (ftnlen)5, (ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     errout_(&larg);
     kgerr[5] = 2;
     ewrite_(&symfil_1.exfile, &nr, kgerr, &c__10, &ir);
     return 0;
 } /* error_ */
Variable Documentation
logical abend
Definition at line 29 of file ERROR.c.
logical asm__
Definition at line 29 of file ERROR.c.
integer axfile
Definition at line 18 of file ERROR.c.
integer c__1 = 1 static
Definition at line 43 of file ERROR.c.
Referenced by error_().
integer c__10 = 10 static
Definition at line 56 of file ERROR.c.
Referenced by error_().
integer c__17 = 17 static
Definition at line 53 of file ERROR.c.
Referenced by error_().
integer c__18 = 18 static
Definition at line 44 of file ERROR.c.
Referenced by error_().
integer c__19 = 19 static
Definition at line 45 of file ERROR.c.
Referenced by error_().
integer c__27 = 27 static
Definition at line 47 of file ERROR.c.
Referenced by error_().
integer c__3 = 3 static
Definition at line 50 of file ERROR.c.
Referenced by error_().
integer c__36 = 36 static
Definition at line 49 of file ERROR.c.
Referenced by error_().
integer c__39 = 39 static
Definition at line 51 of file ERROR.c.
Referenced by error_().
integer c__44 = 44 static
Definition at line 52 of file ERROR.c.
Referenced by error_().
integer c__5 = 5 static
Definition at line 48 of file ERROR.c.
Referenced by error_().
integer c__61 = 61 static
Definition at line 54 of file ERROR.c.
Referenced by error_().
integer c__69 = 69 static
Definition at line 55 of file ERROR.c.
Referenced by error_().
integer c__8 = 8 static
Definition at line 46 of file ERROR.c.
Referenced by error_().
logical cl
Definition at line 27 of file ERROR.c.
integer clfil3
Definition at line 18 of file ERROR.c.
integer clfile
Definition at line 18 of file ERROR.c.
integer clfilp
Definition at line 18 of file ERROR.c.
integer cpfile
Definition at line 18 of file ERROR.c.
char darray[120]
Definition at line 36 of file ERROR.c.
struct { ... } darray_
integer elfil1
Definition at line 18 of file ERROR.c.
integer elfil2
Definition at line 18 of file ERROR.c.
integer elfil3
Definition at line 18 of file ERROR.c.
integer elfil4
Definition at line 18 of file ERROR.c.
integer elfile
Definition at line 18 of file ERROR.c.
logical end
Definition at line 29 of file ERROR.c.
logical err
Definition at line 27 of file ERROR.c.
integer errx
Definition at line 28 of file ERROR.c.
integer exfile
Definition at line 18 of file ERROR.c.
logical fini
Definition at line 29 of file ERROR.c.
integer infile__
Definition at line 18 of file ERROR.c.
integer ispare[26]
Definition at line 18 of file ERROR.c.
integer ldafil
Definition at line 18 of file ERROR.c.
integer libfil
Definition at line 18 of file ERROR.c.
integer mactxt
Definition at line 18 of file ERROR.c.
integer nfil12
Definition at line 18 of file ERROR.c.
integer nfil13
Definition at line 18 of file ERROR.c.
integer pnchfl
Definition at line 18 of file ERROR.c.
integer pofile
Definition at line 18 of file ERROR.c.
logical px
Definition at line 27 of file ERROR.c.
integer pxfile
Definition at line 18 of file ERROR.c.
struct { ... } super_
struct { ... } symfil_
integer tifile
Definition at line 18 of file ERROR.c.
integer vlfile
Definition at line 18 of file ERROR.c.
logical xc
Definition at line 27 of file ERROR.c.
integer xcan
Definition at line 18 of file ERROR.c.
integer xnum
Definition at line 18 of file ERROR.c.
integer xtras[7]
Definition at line 30 of file ERROR.c.