My Project: EVAL.c File Reference
EVAL.c File Reference
#include "f2c.h"
Macros
#define darray_1 darray_
Functions
int eval_ (char *name__, doublereal *u, doublereal *v, doublereal *array, doublereal *spw, integer *mode, ftnlen name_len)
Variables
struct {
char darray [120]
} darray_
static integer c__1 = 1
static integer c__8 = 8
Macro Definition Documentation
#define darray_1 darray_
Definition at line 21 of file EVAL.c.
Referenced by eval_().
Function Documentation
int eval_ (char * name__, doublereal * u, doublereal * v, doublereal * array, doublereal * spw, integer * mode, ftnlen name_len)
Definition at line 30 of file EVAL.c.
References abnend_(), array, c__1, c__8, cform_(), cprint_(), darray_1, emdcs_(), etorus_(), and evdafs_().
Referenced by cnsurf_().
 {
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer slen, ipos;
     extern /* Subroutine */ int emdcs_(doublereal *, doublereal *, doublereal
         *, doublereal *, integer *), cform_(char *, char *, integer *,
         integer *, ftnlen, ftnlen), abnend_(void), evdafs_(doublereal *,
         doublereal *, doublereal *, doublereal *, integer *), cprint_(
         char *, ftnlen), etorus_(doublereal *, doublereal *, doublereal *,
          doublereal *, integer *);
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
     /* Parameter adjustments */
     --spw;
     --array;
     /* Function Body */
     if (s_cmp(name__, "MDCS", (ftnlen)8, (ftnlen)4) == 0) {
     emdcs_(u, v, &array[1], &spw[1], mode);
     } else if (s_cmp(name__, "TORUS", (ftnlen)8, (ftnlen)5) == 0) {
     etorus_(u, v, &array[1], &spw[1], mode);
     } else if (s_cmp(name__, "VDAFS", (ftnlen)8, (ftnlen)5) == 0) {
     evdafs_(u, v, &array[1], &spw[1], mode);
     } else {
     slen = 0;
     cform_("0 EVALUATOR FOR NON-NATIVE SURFACE TYPE :", darray_1.darray, &
         c__1, &slen, (ftnlen)41, (ftnlen)120);
     ipos = slen + 2;
     cform_(name__, darray_1.darray, &ipos, &c__8, (ftnlen)8, (ftnlen)120);
     ipos += 10;
     slen = 0;
     cform_(": NOT AVAILABLE", darray_1.darray, &ipos, &slen, (ftnlen)15, (
         ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     abnend_();
     }
     return 0;
 } /* eval_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 25 of file EVAL.c.
Referenced by eval_().
integer c__8 = 8 static
Definition at line 26 of file EVAL.c.
Referenced by eval_().
char darray[120]
Definition at line 18 of file EVAL.c.
struct { ... } darray_