My Project: EXEC.c File Reference
EXEC.c File Reference
#include "f2c.h"
Macros
#define super_1 super_
#define csuper_1 csuper_
#define cflags ((logical *)&super_1)
#define lxtras ((logical *)&super_1 + 9)
Functions
int exec_ (void)
Variables
struct {
logical err
logical xc
logical cl
logical px
integer errx
logical end
logical fini
logical asm__
logical abend
integer xtras [7]
} super_
struct {
char irdsav [80]
} csuper_
Macro Definition Documentation
#define cflags ((logical *)&super_1)
#define csuper_1 csuper_
Definition at line 30 of file EXEC.c.
#define lxtras ((logical *)&super_1 + 9)
#define super_1 super_
Definition at line 24 of file EXEC.c.
Referenced by exec_().
Function Documentation
int exec_ (void)
Definition at line 37 of file EXEC.c.
References delall_(), imain_(), one, seq_(), and super_1.
Referenced by linkf_().
 {
     /* Initialized data */
     static integer one = 1;
     /* Local variables */
     extern /* Subroutine */ int seq_(integer *), imain_(void), delall_(void);
 #define cflags ((logical *)&super_1)
 #define lxtras ((logical *)&super_1 + 9)
 /* ...THIS IS THE MAIN ROUTINE FOR THE EXECUTION COMPLEX. */
 /* ...      32.  PARAMETERS REQUIRED BY SUPERVISOR */
 /* ...     SET UP INITIAL SEQUENCE NUMBER */
     seq_(&one);
 /* ... CALL THE MAIN ROUTINE FOR THE INTERPRETIVE APPROACH. */
     imain_();
 /* ... INDICATE NORMAL ENDING. */
     super_1.abend = FALSE_;
 /* ... FREEMAIN OF SECUDARY LOADED MODULS,IF NESSESARY */
     delall_();
     return 0;
 } /* exec_ */
Variable Documentation
logical abend
Definition at line 20 of file EXEC.c.
logical asm__
Definition at line 20 of file EXEC.c.
logical cl
Definition at line 18 of file EXEC.c.
struct { ... } csuper_
logical end
Definition at line 20 of file EXEC.c.
logical err
Definition at line 18 of file EXEC.c.
integer errx
Definition at line 19 of file EXEC.c.
logical fini
Definition at line 20 of file EXEC.c.
char irdsav[80]
Definition at line 27 of file EXEC.c.
logical px
Definition at line 18 of file EXEC.c.
struct { ... } super_
logical xc
Definition at line 18 of file EXEC.c.
integer xtras[7]
Definition at line 21 of file EXEC.c.