My Project: FEDPUT.c File Reference
FEDPUT.c File Reference
#include "f2c.h"
Macros
#define ibugg_1 ibugg_
#define itemp ((integer *)equiv_0)
#define fedrat (equiv_0)
Functions
int fedput_ (doublereal *feed)
Variables
struct {
integer ibug
integer ipcolc
integer ipcolm
} ibugg_
static integer c__1 = 1
static integer c_n1 = -1
static integer c__0 = 0
Macro Definition Documentation
#define fedrat (equiv_0)
Referenced by fedput_().
#define ibugg_1 ibugg_
Definition at line 21 of file FEDPUT.c.
Referenced by fedput_().
#define itemp ((integer *)equiv_0)
Referenced by fedput_().
Function Documentation
int fedput_ (doublereal * feed)
Definition at line 31 of file FEDPUT.c.
References apt299_(), bad_(), bcdf_(), c__0, c__1, c_n1, fedrat, ibugg_1, and itemp.
Referenced by cutreg_().
 {
     /* System generated locals */
     static doublereal equiv_0[1];
     /* Local variables */
     extern /* Subroutine */ int bad_();
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt299_(integer *, doublereal *, integer *,
         doublereal *);
 #define itemp ((integer *)equiv_0)
 #define fedrat (equiv_0)
     itemp[0] = bcdf_("FEDR", (ftnlen)4);
     itemp[1] = bcdf_("AT  ", (ftnlen)4);
     apt299_(&c__1, fedrat, &c__1, feed);
     if (ibugg_1.ibug != 11) {
     goto L999;
     }
     bad_(&c_n1, &c__0, " ", &c__0, (ftnlen)1);
     bad_(&c_n1, &c__1, "FEED", feed, (ftnlen)4);
     bad_(&c_n1, &c__0, " ", &c__0, (ftnlen)1);
 L999:
     return 0;
 } /* fedput_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 27 of file FEDPUT.c.
Referenced by fedput_().
integer c__1 = 1 static
Definition at line 25 of file FEDPUT.c.
Referenced by fedput_().
integer c_n1 = -1 static
Definition at line 26 of file FEDPUT.c.
Referenced by fedput_().
integer ibug
Definition at line 18 of file FEDPUT.c.
struct { ... } ibugg_
integer ipcolc
Definition at line 18 of file FEDPUT.c.
integer ipcolm
Definition at line 18 of file FEDPUT.c.