My Project: FILOPN.c File Reference
FILOPN.c File Reference
#include "f2c.h"
Macros
#define filtab_1 filtab_
#define ifiltb_1 ifiltb_
Functions
int filopn_ (integer *no)
Variables
struct {
char filnam [480]
char filacc [300]
char filfmt [330]
char opstat [210]
char clstat [180]
} filtab_
struct {
integer u [30]
integer rl [30]
integer nxtrec [30]
integer lstrec [30]
} ifiltb_
static integer c__2 = 2
Macro Definition Documentation
#define filtab_1 filtab_
Definition at line 21 of file FILOPN.c.
Referenced by filopn_().
#define ifiltb_1 ifiltb_
Definition at line 27 of file FILOPN.c.
Referenced by filopn_().
Function Documentation
int filopn_ (integer * no)
Definition at line 79 of file FILOPN.c.
References abnend_(), c__2, cform_(), cprint_(), darray, filtab_1, iconv_(), and ifiltb_1.
Referenced by abuftp_0_(), aread_(), awrite_(), chread_(), chwrit_(), cpunch_(), fread_(), and tapop_().
 {
     /* Initialized data */
     static char darray[80] = "                                              "
         "                                  ";
     /* System generated locals */
     olist o__1;
     /* Builtin functions */
     integer f_open(olist *);
     /* Local variables */
     static integer slen, iret, posn;
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen), iconv_(integer *, char *, integer *, integer *,
         ftnlen), abnend_(void), cprint_(char *, ftnlen);
 /*  *  FILE ATTRIBUTES  * */
 /* c   fortran 77 disallows a named scratch file */
 /*       if(opstat(no).eq.'SCRATCH')then */
 /*            write(*,*)'opstat is scratch' */
 /*            write(*,*)'opstat is: ',opstat(no) */
 /* c    no file name- */
 /*      open (unit=u(no),iostat=iret,err=90, */
 /*     1      status=opstat(no),access=filacc(no), */
 /*     2      form=filfmt(no),recl=rl(no)) */
 /*      else */
 /* c    file name- */
     o__1.oerr = 1;
     o__1.ounit = ifiltb_1.u[(0 + (0 + (*no - 1 << 2))) / 4];
     o__1.ofnmlen = 16;
     o__1.ofnm = filtab_1.filnam + (0 + (0 + (*no - 1 << 4)));
     o__1.orl = ifiltb_1.rl[(120 + (0 + (*no - 1 << 2)) - 120) / 4];
     o__1.osta = filtab_1.opstat + (1110 + (0 + (*no - 1) * 7) - 1110);
     o__1.oacc = filtab_1.filacc + (480 + (0 + (*no - 1) * 10) - 480);
     o__1.ofm = filtab_1.filfmt + (780 + (0 + (*no - 1) * 11) - 780);
     o__1.oblnk = 0;
     iret = f_open(&o__1);
     if (iret != 0) {
     goto L90;
     }
 /*            write(*,*)'opstat is: ',opstat(no) */
 /*      endif */
 /*      gfortran doesn't like an option in this open statement */
 /*     OPEN (UNIT=U(NO),FILE=FILNAM(NO),IOSTAT=IRET,ERR=90, */
 /*    1      STATUS=OPSTAT(NO),ACCESS=FILACC(NO), */
 /*    2      FORM=FILFMT(NO),RECL=RL(NO)) */
 /*     open (unit=u(no),file=filnam(no),iostat=iret,err=90, */
 /*      open (unit=u(no),iostat=iret,err=90, */
 /*     1      status=opstat(no),access=filacc(no), */
 /*     1      access=filacc(no), */
 /*     2      form=filfmt(no),recl=rl(no)) */
     return 0;
 L90:
     slen = 0;
     cform_(" **** ERROR OPENING FILE :", darray, &c__2, &slen, (ftnlen)26, (
         ftnlen)80);
     posn = slen + 3;
     slen = 0;
     cform_(filtab_1.filnam + (*no - 1 << 4), darray, &posn, &slen, (ftnlen)16,
          (ftnlen)80);
     posn = posn + slen + 1;
     slen = 0;
     cform_("; UNIT NO :", darray, &posn, &slen, (ftnlen)11, (ftnlen)80);
     posn = posn + slen + 1;
     iconv_(&ifiltb_1.u[*no - 1], darray, &posn, &c__2, (ftnlen)80);
     posn += 4;
     slen = 0;
     cform_("****", darray, &posn, &slen, (ftnlen)4, (ftnlen)80);
     cprint_(darray, (ftnlen)80);
     abnend_();
     return 0;
 } /* filopn_ */
Variable Documentation
integer c__2 = 2 static
Definition at line 31 of file FILOPN.c.
Referenced by filopn_().
char clstat[180]
Definition at line 18 of file FILOPN.c.
char filacc[300]
Definition at line 18 of file FILOPN.c.
char filfmt[330]
Definition at line 18 of file FILOPN.c.
char filnam[480]
Definition at line 18 of file FILOPN.c.
struct { ... } filtab_
struct { ... } ifiltb_
integer lstrec[30]
Definition at line 24 of file FILOPN.c.
integer nxtrec[30]
Definition at line 24 of file FILOPN.c.
char opstat[210]
Definition at line 18 of file FILOPN.c.
integer rl[30]
Definition at line 24 of file FILOPN.c.
integer u[30]
Definition at line 24 of file FILOPN.c.