My Project: FINI.c File Reference
FINI.c File Reference
#include "f2c.h"
Macros
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define symfil_1 symfil_
Functions
int fini_ (void)
Variables
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
static integer c__4 = 4
static integer c__8 = 8
static integer c_n2 = -2
static integer c_n1 = -1
Macro Definition Documentation
#define ifxcor_1 ifxcor_
Definition at line 25 of file FINI.c.
#define ishr18_1 ishr18_
Definition at line 33 of file FINI.c.
#define knumbr_1 knumbr_
Definition at line 41 of file FINI.c.
#define symfil_1 symfil_
Definition at line 50 of file FINI.c.
Referenced by fini_().
Function Documentation
int fini_ (void)
Definition at line 63 of file FINI.c.
References apt298_(), bcdf_(), c__4, c__8, c_n1, c_n2, ewrite_(), first, ir, record_(), symfil_1, tapop_(), and x.
Referenced by xcall_().
 {
     /* Initialized data */
     static integer kfini[8] = { 0,0,1308622848,0,1308622848,1,1308622848,1 };
     static logical first = TRUE_;
     static doublereal x;
     static integer nr, ir;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt298_(integer *, doublereal *, doublereal *)
         , tapop_(integer *, integer *), record_(integer *), ewrite_(
         integer *, integer *, integer *, integer *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /* ...            SYSTEM I/O FILE NAMES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...                SYSTEM I/O FILES */
 /* ... INITIALIZE FINI RECORD */
     if (first) {
     kfini[0] = bcdf_("FINI", (ftnlen)4);
     kfini[1] = bcdf_("    ", (ftnlen)4);
     first = FALSE_;
     }
 /* ...  WRITE EXFILE RECORD */
     apt298_(&c__4, &x, &x);
     record_(&kfini[3]);
     nr = 0;
     ewrite_(&symfil_1.exfile, &nr, kfini, &c__8, &ir);
     tapop_(&symfil_1.exfile, &c_n2);
     tapop_(&symfil_1.elfil2, &c_n1);
     tapop_(&symfil_1.elfil3, &c_n1);
     tapop_(&symfil_1.axfile, &c_n1);
     tapop_(&symfil_1.xnum, &c_n1);
     return 0;
 } /* fini_ */
Variable Documentation
integer axfile
Definition at line 44 of file FINI.c.
integer c__4 = 4 static
Definition at line 54 of file FINI.c.
Referenced by fini_().
integer c__8 = 8 static
Definition at line 55 of file FINI.c.
Referenced by fini_().
integer c_n1 = -1 static
Definition at line 57 of file FINI.c.
Referenced by fini_().
integer c_n2 = -2 static
Definition at line 56 of file FINI.c.
Referenced by fini_().
integer clfil3
Definition at line 44 of file FINI.c.
integer clfile
Definition at line 44 of file FINI.c.
integer clfilp
Definition at line 44 of file FINI.c.
integer cpfile
Definition at line 44 of file FINI.c.
integer elfil1
Definition at line 44 of file FINI.c.
integer elfil2
Definition at line 44 of file FINI.c.
integer elfil3
Definition at line 44 of file FINI.c.
integer elfil4
Definition at line 44 of file FINI.c.
integer elfile
Definition at line 44 of file FINI.c.
integer exfile
Definition at line 44 of file FINI.c.
integer i3dflg
Definition at line 18 of file FINI.c.
integer iaerr
Definition at line 18 of file FINI.c.
integer iamdct
Definition at line 28 of file FINI.c.
integer iautps
Definition at line 18 of file FINI.c.
integer ibegin
Definition at line 18 of file FINI.c.
integer ic
Definition at line 18 of file FINI.c.
integer icheck
Definition at line 18 of file FINI.c.
integer icl
Definition at line 18 of file FINI.c.
integer ics
Definition at line 18 of file FINI.c.
integer icscnt
Definition at line 18 of file FINI.c.
integer ictdef
Definition at line 18 of file FINI.c.
integer icut
Definition at line 18 of file FINI.c.
integer ids
Definition at line 18 of file FINI.c.
integer ier
Definition at line 18 of file FINI.c.
struct { ... } ifxcor_
integer igo
Definition at line 18 of file FINI.c.
integer igoto
Definition at line 18 of file FINI.c.
integer igoug
Definition at line 18 of file FINI.c.
integer igs
Definition at line 18 of file FINI.c.
integer infile__
Definition at line 44 of file FINI.c.
integer inops
Definition at line 18 of file FINI.c.
integer ipdpl
Definition at line 28 of file FINI.c.
integer ips
Definition at line 18 of file FINI.c.
integer ipsdef
Definition at line 18 of file FINI.c.
integer ipt
Definition at line 28 of file FINI.c.
integer ipt1
Definition at line 18 of file FINI.c.
integer is
Definition at line 18 of file FINI.c.
integer iseg
Definition at line 18 of file FINI.c.
integer iseqno
Definition at line 18 of file FINI.c.
struct { ... } ishr18_
integer ispare[26]
Definition at line 44 of file FINI.c.
integer isrch
Definition at line 18 of file FINI.c.
integer istrup
Definition at line 18 of file FINI.c.
integer it
Definition at line 18 of file FINI.c.
integer iws
Definition at line 28 of file FINI.c.
integer j10
Definition at line 28 of file FINI.c.
integer j12
Definition at line 28 of file FINI.c.
integer j13
Definition at line 28 of file FINI.c.
integer j54
Definition at line 28 of file FINI.c.
integer jbr
Definition at line 18 of file FINI.c.
integer jckr
Definition at line 28 of file FINI.c.
integer jcnt1
Definition at line 28 of file FINI.c.
integer jcnt2
Definition at line 28 of file FINI.c.
integer jcnt3
Definition at line 28 of file FINI.c.
integer jcpr
Definition at line 28 of file FINI.c.
integer jcr
Definition at line 28 of file FINI.c.
integer jdr
Definition at line 28 of file FINI.c.
integer jfind
Definition at line 28 of file FINI.c.
integer jgr
Definition at line 28 of file FINI.c.
integer jmin
Definition at line 28 of file FINI.c.
integer jminr
Definition at line 28 of file FINI.c.
integer jpr
Definition at line 28 of file FINI.c.
integer jpxr
Definition at line 28 of file FINI.c.
integer jsw
Definition at line 18 of file FINI.c.
integer jtkf
Definition at line 28 of file FINI.c.
integer jtr
Definition at line 28 of file FINI.c.
integer k0
Definition at line 36 of file FINI.c.
integer k1
Definition at line 36 of file FINI.c.
integer k10
Definition at line 36 of file FINI.c.
integer k1013
Definition at line 36 of file FINI.c.
integer k12
Definition at line 36 of file FINI.c.
integer k13
Definition at line 36 of file FINI.c.
integer k15
Definition at line 36 of file FINI.c.
integer k16
Definition at line 36 of file FINI.c.
integer k18
Definition at line 36 of file FINI.c.
integer k19
Definition at line 36 of file FINI.c.
integer k1e4
Definition at line 36 of file FINI.c.
integer k1e6
Definition at line 36 of file FINI.c.
integer k2
Definition at line 36 of file FINI.c.
integer k23
Definition at line 36 of file FINI.c.
integer k24
Definition at line 36 of file FINI.c.
integer k25
Definition at line 36 of file FINI.c.
integer k26
Definition at line 36 of file FINI.c.
integer k27
Definition at line 36 of file FINI.c.
integer k29
Definition at line 36 of file FINI.c.
integer k3
Definition at line 36 of file FINI.c.
integer k30
Definition at line 36 of file FINI.c.
integer k31
Definition at line 36 of file FINI.c.
integer k32
Definition at line 36 of file FINI.c.
integer k33
Definition at line 36 of file FINI.c.
integer k34
Definition at line 36 of file FINI.c.
integer k4
Definition at line 36 of file FINI.c.
integer k44
Definition at line 36 of file FINI.c.
integer k45
Definition at line 36 of file FINI.c.
integer k46
Definition at line 36 of file FINI.c.
integer k47
Definition at line 36 of file FINI.c.
integer k48
Definition at line 36 of file FINI.c.
integer k5
Definition at line 36 of file FINI.c.
integer k50
Definition at line 36 of file FINI.c.
integer k51
Definition at line 36 of file FINI.c.
integer k52
Definition at line 36 of file FINI.c.
integer k6
Definition at line 36 of file FINI.c.
integer k7
Definition at line 36 of file FINI.c.
integer k8
Definition at line 36 of file FINI.c.
integer k9
Definition at line 36 of file FINI.c.
integer km1
Definition at line 36 of file FINI.c.
struct { ... } knumbr_
integer ldafil
Definition at line 44 of file FINI.c.
integer libfil
Definition at line 44 of file FINI.c.
integer lsv
Definition at line 18 of file FINI.c.
integer lsv1
Definition at line 18 of file FINI.c.
integer mactxt
Definition at line 44 of file FINI.c.
integer mantax
Definition at line 18 of file FINI.c.
integer mdic
Definition at line 28 of file FINI.c.
integer motmod
Definition at line 18 of file FINI.c.
integer msav
Definition at line 18 of file FINI.c.
integer mulout
Definition at line 18 of file FINI.c.
integer nfil12
Definition at line 44 of file FINI.c.
integer nfil13
Definition at line 44 of file FINI.c.
integer nmbseg
Definition at line 18 of file FINI.c.
integer nmpnts
Definition at line 18 of file FINI.c.
integer nrec
Definition at line 18 of file FINI.c.
integer numax
Definition at line 18 of file FINI.c.
integer numcnt
Definition at line 18 of file FINI.c.
integer nump
Definition at line 18 of file FINI.c.
integer numpt1
Definition at line 18 of file FINI.c.
integer numsfs
Definition at line 18 of file FINI.c.
integer numsur
Definition at line 18 of file FINI.c.
integer nw
Definition at line 18 of file FINI.c.
integer nwds
Definition at line 18 of file FINI.c.
integer pnchfl
Definition at line 44 of file FINI.c.
integer pofile
Definition at line 44 of file FINI.c.
integer pxfile
Definition at line 44 of file FINI.c.
struct { ... } symfil_
integer tifile
Definition at line 44 of file FINI.c.
integer vlfile
Definition at line 44 of file FINI.c.
integer xcan
Definition at line 44 of file FINI.c.
integer xnum
Definition at line 44 of file FINI.c.