My Project: FOUTXX.c File Reference
FOUTXX.c File Reference
#include "f2c.h"
Macros
#define darray_1 darray_
Functions
int foutxx_ (integer *ifile, char *array, integer *count, ftnlen array_len)
Variables
struct {
char darray [120]
} darray_
Macro Definition Documentation
#define darray_1 darray_
Definition at line 21 of file FOUTXX.c.
Referenced by foutxx_().
Function Documentation
int foutxx_ (integer * ifile, char * array, integer * count, ftnlen array_len)
Definition at line 39 of file FOUTXX.c.
References cprint_(), and darray_1.
Referenced by alarm_(), pro027_(), prtil_(), puttmp_(), rlslin_(), and start_().
 {
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     extern /* Subroutine */ int cprint_(char *, ftnlen);
 /*       20.    IO - ARRAY */
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
 /* ** */
     s_copy(darray_1.darray, array, (*count), (*count));
     cprint_(darray_1.darray, (ftnlen)120);
     return 0;
 } /* foutxx_ */
Variable Documentation
char darray[120]
Definition at line 18 of file FOUTXX.c.
struct { ... } darray_