My Project: FROM.c File Reference
FROM.c File Reference
#include "f2c.h"
Macros
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int from_ (doublereal *point)
Variables
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__2 = 2
static integer c__3 = 3
static integer c__0 = 0
Macro Definition Documentation
#define charct_1 charct_
Definition at line 30 of file FROM.c.
Referenced by from_().
#define cosl ((doublereal *)&tlldat_1 + 16)
#define fxcor_1 fxcor_
Definition at line 24 of file FROM.c.
Referenced by from_().
#define ifxcor_1 ifxcor_
Definition at line 47 of file FROM.c.
Referenced by from_().
#define ishr18_1 ishr18_
Definition at line 55 of file FROM.c.
#define knumbr_1 knumbr_
Definition at line 63 of file FROM.c.
#define sinl ((doublereal *)&tlldat_1 + 8)
#define tlldat_1 tlldat_
Definition at line 37 of file FROM.c.
Function Documentation
int from_ (doublereal * point)
Definition at line 75 of file FROM.c.
References apt202_(), apt233_(), c__0, c__2, c__3, charct_1, fxcor_1, ifxcor_1, j, point, and transm_().
Referenced by xcall_().
 {
     /* Initialized data */
     static char hfrom[4] = "FROM";
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer j;
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     extern /* Subroutine */ int apt202_(doublereal *, integer *), apt233_(
         void), transm_(doublereal *, doublereal *, integer *, integer *,
         integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /* ...  THE PRESENT TOOL POSITION IS (POINT) */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --point;
     /* Function Body */
     ifxcor_1.iaerr = 0;
     ifxcor_1.igoto = 0;
     transm_(fxcor_1.tek, &point[1], &c__2, &c__3, &c__0);
     for (j = 1; j <= 3; ++j) {
 /* L10: */
     fxcor_1.te[j - 1] = fxcor_1.tek[j - 1];
     }
     apt202_(&point[1], &c__2);
 /* ...  SET RECORD TYPE CODE FOR CLTAPE WRITER */
     s_copy(charct_1.modfer, hfrom, (ftnlen)6, (ftnlen)4);
     apt233_();
     return 0;
 } /* from_ */
Variable Documentation
doublereal alp
Definition at line 18 of file FROM.c.
doublereal ax4[3]
Definition at line 18 of file FROM.c.
integer c__0 = 0 static
Definition at line 69 of file FROM.c.
Referenced by from_().
integer c__2 = 2 static
Definition at line 67 of file FROM.c.
Referenced by from_().
integer c__3 = 3 static
Definition at line 68 of file FROM.c.
Referenced by from_().
doublereal cagl
Definition at line 18 of file FROM.c.
struct { ... } charct_
doublereal corrad[8]
Definition at line 33 of file FROM.c.
doublereal cutdat[7]
Definition at line 18 of file FROM.c.
doublereal dpmax
Definition at line 18 of file FROM.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 18 of file FROM.c.
doublereal hi
Definition at line 18 of file FROM.c.
integer i3dflg
Definition at line 40 of file FROM.c.
integer iaerr
Definition at line 40 of file FROM.c.
integer iamdct
Definition at line 50 of file FROM.c.
integer iautps
Definition at line 40 of file FROM.c.
integer ibegin
Definition at line 40 of file FROM.c.
integer ic
Definition at line 40 of file FROM.c.
integer icheck
Definition at line 40 of file FROM.c.
integer icl
Definition at line 40 of file FROM.c.
integer ics
Definition at line 40 of file FROM.c.
integer icscnt
Definition at line 40 of file FROM.c.
integer ictdef
Definition at line 40 of file FROM.c.
integer icut
Definition at line 40 of file FROM.c.
integer ids
Definition at line 40 of file FROM.c.
integer ier
Definition at line 40 of file FROM.c.
struct { ... } ifxcor_
integer igo
Definition at line 40 of file FROM.c.
integer igoto
Definition at line 40 of file FROM.c.
integer igoug
Definition at line 40 of file FROM.c.
integer igs
Definition at line 40 of file FROM.c.
integer inops
Definition at line 40 of file FROM.c.
integer ipdpl
Definition at line 50 of file FROM.c.
integer ips
Definition at line 40 of file FROM.c.
integer ipsdef
Definition at line 40 of file FROM.c.
integer ipt
Definition at line 50 of file FROM.c.
integer ipt1
Definition at line 40 of file FROM.c.
integer is
Definition at line 40 of file FROM.c.
integer iseg
Definition at line 40 of file FROM.c.
integer iseqno
Definition at line 40 of file FROM.c.
struct { ... } ishr18_
integer isrch
Definition at line 40 of file FROM.c.
integer istrup
Definition at line 40 of file FROM.c.
integer it
Definition at line 40 of file FROM.c.
integer iws
Definition at line 50 of file FROM.c.
integer j10
Definition at line 50 of file FROM.c.
integer j12
Definition at line 50 of file FROM.c.
integer j13
Definition at line 50 of file FROM.c.
integer j54
Definition at line 50 of file FROM.c.
integer jbr
Definition at line 40 of file FROM.c.
integer jckr
Definition at line 50 of file FROM.c.
integer jcnt1
Definition at line 50 of file FROM.c.
integer jcnt2
Definition at line 50 of file FROM.c.
integer jcnt3
Definition at line 50 of file FROM.c.
integer jcpr
Definition at line 50 of file FROM.c.
integer jcr
Definition at line 50 of file FROM.c.
integer jdr
Definition at line 50 of file FROM.c.
integer jfind
Definition at line 50 of file FROM.c.
integer jgr
Definition at line 50 of file FROM.c.
integer jmin
Definition at line 50 of file FROM.c.
integer jminr
Definition at line 50 of file FROM.c.
integer jpr
Definition at line 50 of file FROM.c.
integer jpxr
Definition at line 50 of file FROM.c.
integer jsw
Definition at line 40 of file FROM.c.
integer jtkf
Definition at line 50 of file FROM.c.
integer jtr
Definition at line 50 of file FROM.c.
integer k0
Definition at line 58 of file FROM.c.
integer k1
Definition at line 58 of file FROM.c.
integer k10
Definition at line 58 of file FROM.c.
integer k1013
Definition at line 58 of file FROM.c.
integer k12
Definition at line 58 of file FROM.c.
integer k13
Definition at line 58 of file FROM.c.
integer k15
Definition at line 58 of file FROM.c.
integer k16
Definition at line 58 of file FROM.c.
integer k18
Definition at line 58 of file FROM.c.
integer k19
Definition at line 58 of file FROM.c.
integer k1e4
Definition at line 58 of file FROM.c.
integer k1e6
Definition at line 58 of file FROM.c.
integer k2
Definition at line 58 of file FROM.c.
integer k23
Definition at line 58 of file FROM.c.
integer k24
Definition at line 58 of file FROM.c.
integer k25
Definition at line 58 of file FROM.c.
integer k26
Definition at line 58 of file FROM.c.
integer k27
Definition at line 58 of file FROM.c.
integer k29
Definition at line 58 of file FROM.c.
integer k3
Definition at line 58 of file FROM.c.
integer k30
Definition at line 58 of file FROM.c.
integer k31
Definition at line 58 of file FROM.c.
integer k32
Definition at line 58 of file FROM.c.
integer k33
Definition at line 58 of file FROM.c.
integer k34
Definition at line 58 of file FROM.c.
integer k4
Definition at line 58 of file FROM.c.
integer k44
Definition at line 58 of file FROM.c.
integer k45
Definition at line 58 of file FROM.c.
integer k46
Definition at line 58 of file FROM.c.
integer k47
Definition at line 58 of file FROM.c.
integer k48
Definition at line 58 of file FROM.c.
integer k5
Definition at line 58 of file FROM.c.
integer k50
Definition at line 58 of file FROM.c.
integer k51
Definition at line 58 of file FROM.c.
integer k52
Definition at line 58 of file FROM.c.
integer k6
Definition at line 58 of file FROM.c.
integer k7
Definition at line 58 of file FROM.c.
integer k8
Definition at line 58 of file FROM.c.
integer k9
Definition at line 58 of file FROM.c.
integer km1
Definition at line 58 of file FROM.c.
struct { ... } knumbr_
integer lsv
Definition at line 40 of file FROM.c.
integer lsv1
Definition at line 40 of file FROM.c.
integer mantax
Definition at line 40 of file FROM.c.
integer mdic
Definition at line 50 of file FROM.c.
char modfer[6]
Definition at line 27 of file FROM.c.
integer motmod
Definition at line 40 of file FROM.c.
integer msav
Definition at line 40 of file FROM.c.
integer mulout
Definition at line 40 of file FROM.c.
integer nmbseg
Definition at line 40 of file FROM.c.
integer nmpnts
Definition at line 40 of file FROM.c.
integer nrec
Definition at line 40 of file FROM.c.
integer numax
Definition at line 40 of file FROM.c.
integer numcnt
Definition at line 40 of file FROM.c.
integer nump
Definition at line 40 of file FROM.c.
integer numpt1
Definition at line 40 of file FROM.c.
integer numsfs
Definition at line 40 of file FROM.c.
integer numsur
Definition at line 40 of file FROM.c.
integer nw
Definition at line 40 of file FROM.c.
integer nwds
Definition at line 40 of file FROM.c.
doublereal pmove[3]
Definition at line 18 of file FROM.c.
doublereal ra
Definition at line 18 of file FROM.c.
doublereal rc1
Definition at line 18 of file FROM.c.
doublereal ri[8]
Definition at line 33 of file FROM.c.
doublereal sagl
Definition at line 18 of file FROM.c.
doublereal strtno
Definition at line 18 of file FROM.c.
doublereal surd
Definition at line 18 of file FROM.c.
doublereal ta[3]
Definition at line 18 of file FROM.c.
doublereal tak[3]
Definition at line 18 of file FROM.c.
doublereal tal[3]
Definition at line 18 of file FROM.c.
doublereal tanhi[8]
Definition at line 33 of file FROM.c.
doublereal tanlo[8]
Definition at line 33 of file FROM.c.
doublereal tcont[9]
Definition at line 33 of file FROM.c.
doublereal te[3]
Definition at line 18 of file FROM.c.
doublereal tek[3]
Definition at line 18 of file FROM.c.
doublereal tel[3]
Definition at line 18 of file FROM.c.
doublereal tem[10]
Definition at line 18 of file FROM.c.
doublereal temp[24]
Definition at line 18 of file FROM.c.
doublereal ti[3]
Definition at line 18 of file FROM.c.
doublereal tik[3]
Definition at line 18 of file FROM.c.
doublereal til[3]
Definition at line 18 of file FROM.c.
doublereal tlhit
Definition at line 18 of file FROM.c.
doublereal tlhite[8]
Definition at line 33 of file FROM.c.
doublereal tlinc[9]
Definition at line 33 of file FROM.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 18 of file FROM.c.
doublereal umax[8]
Definition at line 33 of file FROM.c.
doublereal vtem
Definition at line 18 of file FROM.c.