My Project: GCHK.c File Reference
GCHK.c File Reference
#include "f2c.h"
Macros
#define ibugg_1 ibugg_
Functions
int gchk_ (doublereal *surf, doublereal *side, doublereal *r__, doublereal *te, doublereal *ta, integer *npat, doublereal *up, doublereal *vp, doublereal *rl, doublereal *tel, doublereal *tal, integer *npatl, doublereal *upl, doublereal *vpl, doublereal *tolcom, doublereal *toli, doublereal *tolo, doublereal *gfac, integer *iret)
Variables
struct {
integer ibug
integer ipcolc
integer ipcolm
} ibugg_
static integer c__1 = 1
static integer c_n1 = -1
static integer c__0 = 0
Macro Definition Documentation
#define ibugg_1 ibugg_
Definition at line 21 of file GCHK.c.
Referenced by gchk_().
Function Documentation
int gchk_ (doublereal * surf, doublereal * side, doublereal * r__, doublereal * te, doublereal * ta, integer * npat, doublereal * up, doublereal * vp, doublereal * rl, doublereal * tel, doublereal * tal, integer * npatl, doublereal * upl, doublereal * vpl, doublereal * tolcom, doublereal * toli, doublereal * tolo, doublereal * gfac, integer * iret)
Definition at line 31 of file GCHK.c.
References bad_(), c__0, c__1, c_n1, cprint_(), devcal_(), i__, ibugg_1, midkur_(), midpnt_(), offset, one, r__, rl, ta, tal, te, tel, tn, tp, xtpcal_(), and zero.
Referenced by sspath_().
 {
     /* Initialized data */
     static doublereal z1em10 = 1e-10;
     static doublereal zero = 0.;
     static doublereal one = 1.;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__;
     static doublereal rm[32], tn[3], tp[3];
     extern /* Subroutine */ int bad_();
     static doublereal dev[3], tpl[3], xtp[3], skrm, xtpl[3];
     static char badmsg[20];
     extern /* Subroutine */ int devcal_(doublereal *, doublereal *,
         doublereal *, doublereal *, doublereal *);
     static doublereal devmin, devmax, offset;
     extern /* Subroutine */ int midpnt_(doublereal *, integer *, doublereal *,
          doublereal *, integer *, doublereal *, doublereal *, doublereal *
         ), midkur_(doublereal *, doublereal *, doublereal *, doublereal *,
          doublereal *), xtpcal_(doublereal *, doublereal *, doublereal *,
         doublereal *, doublereal *, doublereal *, doublereal *,
         doublereal *), cprint_(char *, ftnlen);
 /* .... DEBUG FLAGS */
     /* Parameter adjustments */
     --tal;
     --tel;
     --rl;
     --ta;
     --te;
     --r__;
     --surf;
     /* Function Body */
 /* .... COMPUTE PARAMETRIC MIDPINT */
     midpnt_(&surf[1], npat, up, vp, npatl, upl, vpl, rm);
 /* .... COMPUTE SURFACE CURVATURE AT MIDPOINT IN CHORD DIRECTION */
     midkur_(rm, &r__[1], &rl[1], side, &skrm);
 /* .... COMPUTE TOOL CONTACT POINT AT CURRENT AND LAST LOCATION */
 /*     AND TOOL NORMAL AT MIDPOINT */
     offset = *tolcom * *side;
     for (i__ = 1; i__ <= 3; ++i__) {
     tp[i__ - 1] = r__[i__] + offset * r__[i__ + 28];
     tpl[i__ - 1] = rl[i__] + offset * rl[i__ + 28];
     tn[i__ - 1] = *side * rm[i__ + 27];
 /* L10: */
     }
 /* .... COMPUTE THE TWO TOOL POINTS, XTP AND XTPL THAT CORRESPOND */
 /*     TO THE TOOL CONTACT POINT AT THE ALTERNATIVE TOOL LOCATION */
     xtpcal_(tp, &te[1], &ta[1], tpl, &tel[1], &tal[1], xtp, xtpl);
 /* .... COMPUTE DEVIATION OF MIDPOINT FROM CHORD */
 /*     BETWEEN TOOL CONTACT POINTS */
     devcal_(rm, tn, tp, tpl, dev);
 /* .... COMPUTE DEVIATION OF MIDPOINT FROM CHORD */
 /*     BETWEEN TOOL CONTACT POINT AND CORRESPONDING POINT (XTP OR XTPL) */
 /*     FOR BOTH TOOL LOCATIONS */
     devcal_(rm, tn, tp, xtpl, &dev[1]);
     devcal_(rm, tn, tpl, xtp, &dev[2]);
 /* .... COMPUTE MAXIMUM AND MINIMUM DEVIATION */
     devmax = zero;
     devmin = zero;
     for (i__ = 1; i__ <= 3; ++i__) {
     if (dev[i__ - 1] > devmax) {
         devmax = dev[i__ - 1];
     }
     if (dev[i__ - 1] < devmin) {
         devmin = dev[i__ - 1];
     }
 /* L20: */
     }
 /* .... IS THE APPROPRIATE TOLERANCE BAND VIOLATED */
     if (skrm > zero && abs(devmin) > *tolo) {
 /* .... EXCESS MATERIAL WILL BE LEFT ON */
     *iret = -1;
 /* .... COMPUTE STEP REDUCTION FACTOR */
     if (*tolo > z1em10) {
         *gfac = *tolo / abs(devmin);
         *gfac = min(*gfac,.95);
     } else {
         *gfac = .75f;
     }
     } else if (skrm < zero && devmax > *toli) {
 /* .... GOUGING OF SURFACE WILL OCCUR */
     *iret = 1;
 /* .... COMPUTE STEP REDUCTION FACTOR */
     if (*toli > z1em10) {
         *gfac = *toli / devmax;
         *gfac = min(*gfac,.95);
     } else {
         *gfac = .75f;
     }
     } else {
     *iret = 0;
     *gfac = one;
     }
     if (ibugg_1.ibug == 11) {
     s_copy(badmsg, " AFTER GCHK", (ftnlen)20, (ftnlen)11);
     cprint_(badmsg, (ftnlen)20);
     bad_(&c__1, &c__1, "SKRM", &skrm, (ftnlen)4);
     bad_(&c__1, &c__1, "TOLI", toli, (ftnlen)4);
     bad_(&c_n1, &c__1, "TOLO", tolo, (ftnlen)4);
     bad_(&c__1, &c__1, "DVMX", &devmax, (ftnlen)4);
     bad_(&c__1, &c__1, "DVMN", &devmin, (ftnlen)4);
     bad_(&c__1, &c__0, "IRET", iret, (ftnlen)4);
     bad_(&c_n1, &c__1, "GFAC", gfac, (ftnlen)4);
     }
     return 0;
 } /* gchk_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 27 of file GCHK.c.
Referenced by gchk_().
integer c__1 = 1 static
Definition at line 25 of file GCHK.c.
Referenced by gchk_().
integer c_n1 = -1 static
Definition at line 26 of file GCHK.c.
Referenced by gchk_().
integer ibug
Definition at line 18 of file GCHK.c.
struct { ... } ibugg_
integer ipcolc
Definition at line 18 of file GCHK.c.
integer ipcolm
Definition at line 18 of file GCHK.c.