My Project: GETTMP.c File Reference
GETTMP.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define code_1 code_
#define tmp_1 tmp_
#define temp ((integer *)&code_1 + 32)
Functions
integer gettmp_ (integer *mode)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer code [150]
} code_
struct {
integer txxxx [64]
} tmp_
static integer c__1 = 1
Macro Definition Documentation
#define cnamtb_1 cnamtb_
Definition at line 28 of file GETTMP.c.
#define code_1 code_
Definition at line 34 of file GETTMP.c.
#define nametb_1 nametb_
Definition at line 22 of file GETTMP.c.
Referenced by gettmp_().
#define temp ((integer *)&code_1 + 32)
Referenced by gettmp_().
#define tmp_1 tmp_
Definition at line 40 of file GETTMP.c.
Referenced by gettmp_().
Function Documentation
integer gettmp_ (integer * mode)
Definition at line 70 of file GETTMP.c.
References binbcd_(), blk, c__1, count, mode, name_(), nametb_1, resrvz_(), shift_(), temp, and tmp_1.
Referenced by boolif_(), inpat_(), isscod_(), larges_(), lcanon_(), loop_(), pro020_(), pro021_(), pro026_(), pro027_(), pro028_(), recog_(), recogn_(), ssdef_(), and subcod_().
 {
     /* Initialized data */
     static char blk[1] = " ";
     /* System generated locals */
     integer ret_val, i__1;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     extern integer name_(char *, ftnlen);
 #define temp ((integer *)&code_1 + 32)
     static char symi[8];
     extern /* Subroutine */ int shift_(char *, char *, ftnlen, ftnlen);
     static integer count;
     extern /* Subroutine */ int binbcd_(integer *, char *, integer *, ftnlen);
     static char symbol[6];
     extern /* Subroutine */ int resrvz_(integer *, integer *, integer *,
         integer *);
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /*        3.    METALINGUISTIC VARIABLE CLASS CODES */
 /* TEMP:        (1)=CODE CLASS 17000,(2)=NAMTBL INDEX OF 'TEMP  ' */
 /*        6.    GHOST STACK FOR OBJECT TIME TEMPORARY ALLOCATION */
 /*              LENGTH AND CURRENT NUMBER OF ACTIVE TEMPORARY STORAGE */
 /* * */
 /* PURPOSE      THIS ROUTINE RETURNS THE NAME TABLE (NAMTBL) */
 /*              INDEX FOR THE CURRENT TEMPORARY NAME OF THIS */
 /*              MODE. */
 /* ARGUMENTS    MODE    THE MODE OF THE SURFACE REQUIRING */
 /*                      TEMPORARY STORAGE. */
 /* ARGUMENTS    MODE    THE MODE OF THE SURFACE REQUIRING */
 /*                      TEMPORARY STORAGE. */
 /* ** */
 /* ...     INCREMENT COUNTER FOR THIS MODE */
     ++tmp_1.txxxx[(0 + (0 + (2 + (*mode << 1) - 3 << 2))) / 4];
 /* ...     GENERATE NAME OF TEMPORARY LOCATION */
     s_copy(symbol, blk, (ftnlen)6, (ftnlen)1);
 /* ...           START SYMBOL WITH A $ */
     shift_(symbol, "$", (ftnlen)6, (ftnlen)1);
 /* ...     IS MODE .GT. 9 */
     if (*mode / 10 == 0) {
     goto L10;
     }
 /* ...     YES. CONVERT TENS DIGIT OF MODE TO BCD AND SHIFT INTO SYMBOL */
     i__1 = *mode / 10;
     binbcd_(&i__1, symi, &count, (ftnlen)8);
     shift_(symbol, symi, (ftnlen)6, (ftnlen)8);
 /* ...     CONVERT UNITS DIGIT TO BCD AND SHIFT INTO SYMBOL */
 L10:
     i__1 = *mode % 10;
     binbcd_(&i__1, symi, &count, (ftnlen)8);
     shift_(symbol, symi, (ftnlen)6, (ftnlen)8);
 /* ...           SHIFT T$ INTO SYMBOL */
     shift_(symbol, "T", (ftnlen)6, (ftnlen)1);
     shift_(symbol, "$", (ftnlen)6, (ftnlen)1);
 /* ...     IS COUNTER FOR THIS MODE .GT. 9 */
     if (tmp_1.txxxx[(*mode << 1) - 1] / 10 == 0) {
     goto L20;
     }
 /* ...     YES. CONVERT TENS DIGIT TO BCD AND SHIFT INTO SYMBOL */
     i__1 = tmp_1.txxxx[(*mode << 1) - 1] / 10;
     binbcd_(&i__1, symi, &count, (ftnlen)8);
     shift_(symbol, symi, (ftnlen)6, (ftnlen)8);
 /* ...     CONVERT UNITS DIGIT OF POINTER TO BCD AND SHIFT INTO SYMBOL */
 L20:
     i__1 = tmp_1.txxxx[(*mode << 1) - 1] % 10;
     binbcd_(&i__1, symi, &count, (ftnlen)8);
     shift_(symbol, symi, (ftnlen)6, (ftnlen)8);
 /* ...     FIND NAMTBL INDEX OF NAME JUST CREATED AND STORE AS GETTMP */
     ret_val = name_(symbol, (ftnlen)6);
 /* ...     IS FIRST COLUMN OF NAMTBL ZERO. */
 /* ...     IF SO, THEN THIS IS THE FIRST APPEARENCE OF THIS NAME. */
 /* ...     IF NOT, IT HAS BEEN USED BEFORE, SO RETURN. */
     if (nametb_1.namtbl[ret_val - 1] != 0) {
     return ret_val;
     }
 /* ...     FIRST APPEARENCE - GENERATE RESRV CODE AND SET CORRECT CLASS */
 /* ...     AND MODE IN COLUMN 1 OF NAMTBL. THEN RETURN. */
     resrvz_(&ret_val, mode, &tmp_1.txxxx[(*mode << 1) - 2], &c__1);
     nametb_1.namtbl[ret_val - 1] = temp[0] + *mode;
     return ret_val;
 } /* gettmp_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 44 of file GETTMP.c.
Referenced by gettmp_().
integer charnd
Definition at line 18 of file GETTMP.c.
integer charst
Definition at line 18 of file GETTMP.c.
char cnamtb[18000]
Definition at line 25 of file GETTMP.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file GETTMP.c.
integer code[150]
Definition at line 31 of file GETTMP.c.
struct { ... } code_
integer ifixnd
Definition at line 18 of file GETTMP.c.
integer ifixst
Definition at line 18 of file GETTMP.c.
integer inamnd
Definition at line 18 of file GETTMP.c.
integer inamst
Definition at line 18 of file GETTMP.c.
integer namest
Definition at line 18 of file GETTMP.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file GETTMP.c.
integer namtbl[3000]
Definition at line 18 of file GETTMP.c.
integer numbnd
Definition at line 18 of file GETTMP.c.
integer numbst
Definition at line 18 of file GETTMP.c.
struct { ... } tmp_
integer txxxx[64]
Definition at line 37 of file GETTMP.c.