My Project: GO2.c File Reference
GO2.c File Reference
#include "f2c.h"
Macros
#define dshar4_1 dshar4_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define hblock_1 hblock_
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define ldef_1 ldef_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define addcom_1 addcom_
#define _BLNK__1 _BLNK__
#define can ((doublereal *)&_BLNK__1 + 40)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define canon ((doublereal *)&_BLNK__1)
#define elmax ((doublereal *)&addcom_1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define kdynfl ((integer *)&addcom_1 + 48)
Functions
int go2_ (doublereal *hmod, doublereal *adress)
Variables
struct {
doublereal a
doublereal b
doublereal c__
doublereal cendis
doublereal cmove [3]
doublereal com1
doublereal com4
doublereal dir [3]
doublereal dp
doublereal dpe
doublereal dpcnt
doublereal dpi
doublereal dpl
doublereal dp1
doublereal d1
doublereal d2a
doublereal flipck
doublereal fwd [3]
doublereal ogle [3]
doublereal p1 [3]
doublereal p2 [3]
doublereal rdrn
doublereal refpnt [3]
doublereal tangl
doublereal tes [3]
doublereal tew [3]
doublereal uvec [3]
doublereal u2 [3]
doublereal v [3]
doublereal vl
doublereal zl
doublereal zlnorm [3]
doublereal zlpnt [3]
doublereal zl1
doublereal param [6]
doublereal r__ [6]
doublereal savpar [4]
doublereal seg [9]
doublereal slope
doublereal sqroot
doublereal unn
doublereal upp
doublereal vint
doublereal vnn
doublereal vpp
} dshar4_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
char hps [8]
char hds [8]
char hcs [8]
char hlft [8]
char hrgt [8]
char hfwd [8]
char hback [8]
char hup [8]
char hdown [8]
char hto [8]
char hpast [8]
char hon [8]
char htanto [8]
char hpstan [8]
char hdynp [8]
char haerr [8]
char hcldat [8]
char hgerr [8]
} hblock_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
doublereal addcom [25]
} addcom_
struct {
doublereal com [36000]
} _BLNK__
static integer c__20202 = 20202
static integer c__20203 = 20203
static integer c__41 = 41
static integer c__20204 = 20204
static integer c__42 = 42
static integer c__43 = 43
static integer c__20205 = 20205
static integer c__20206 = 20206
static integer c__45 = 45
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 150 of file GO2.c.
#define addcom_1 addcom_
Definition at line 144 of file GO2.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
Referenced by go2_().
#define charct_1 charct_
Definition at line 40 of file GO2.c.
Referenced by go2_().
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dshar4_1 dshar4_
Definition at line 25 of file GO2.c.
Referenced by go2_().
#define elmax ((doublereal *)&addcom_1)
#define fxcor_1 fxcor_
Definition at line 34 of file GO2.c.
Referenced by go2_().
#define hblock_1 hblock_
Definition at line 55 of file GO2.c.
#define ifxcor_1 ifxcor_
Definition at line 122 of file GO2.c.
Referenced by go2_().
#define ishr18_1 ishr18_
Definition at line 130 of file GO2.c.
Referenced by go2_().
#define isv1_1 isv1_
Definition at line 112 of file GO2.c.
Referenced by go2_().
#define isv_1 isv_
Definition at line 105 of file GO2.c.
Referenced by go2_().
#define kdynfl ((integer *)&addcom_1 + 48)
Referenced by go2_().
#define knumbr_1 knumbr_
Definition at line 138 of file GO2.c.
Referenced by go2_().
#define ldef_1 ldef_
Definition at line 96 of file GO2.c.
Referenced by go2_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define sv1_1 sv1_
Definition at line 81 of file GO2.c.
Referenced by go2_().
#define sv_1 sv_
Definition at line 72 of file GO2.c.
Referenced by go2_().
#define tlldat_1 tlldat_
Definition at line 47 of file GO2.c.
#define znumbr_1 znumbr_
Definition at line 89 of file GO2.c.
Referenced by go2_().
Function Documentation
int go2_ (doublereal * hmod, doublereal * adress)
Definition at line 167 of file GO2.c.
References aerr_(), amind_(), apt234_(), apt235_(), apt236_(), apt238_(), apt240_(), atape_(), c__20202, c__20203, c__20204, c__20205, c__20206, c__41, c__42, c__43, c__45, canon, centr_(), charct_1, check_(), cross_(), ddst_(), dshar4_1, f, fxcor_1, i__, ia, ib, id, ifxcor_1, ishr18_1, isv1_1, isv_1, isvcpy_(), k, kdynfl, knumbr_1, ldef_1, sv1_1, sv_1, svcopy_(), vnorm_(), and znumbr_1.
Referenced by go_().
 {
     /* Initialized data */
     static doublereal zlit1 = 1e-4;
     static doublereal zlit2 = .9999;
     static integer klit3 = 21;
     static char hgo[2] = "GO";
     /* System generated locals */
     integer i__1, i__2;
     doublereal d__1, d__2;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, k, ia, id, ib;
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer iii;
     static doublereal tem1, tem3, tem2;
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen);
     static doublereal xdir;
     extern /* Subroutine */ int ddst_(void);
     static integer issv;
     extern /* Subroutine */ int apt240_(integer *), apt234_(doublereal *,
         doublereal *), apt238_(integer *), apt235_(void), apt236_(void),
         check_(void), amind_(void), atape_(void);
 #define canon ((doublereal *)&_BLNK__1)
 #define elmax ((doublereal *)&addcom_1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     static integer issto, isssv;
     extern /* Subroutine */ int vnorm_(doublereal *, doublereal *), cross_(
         doublereal *, doublereal *, doublereal *), centr_(void);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
 #define kdynfl ((integer *)&addcom_1 + 48)
     static doublereal cansav[4];
     static integer icnsav, numdim, ngosrf;
     extern /* Subroutine */ int svcopy_(integer *, integer *), isvcpy_(
         integer *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*     *** 8.  HOLRTH BLOCK *** */
 /*     ALPHA-NUMERIC LITERAL CONSTANTS. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
     /* Parameter adjustments */
     --adress;
     /* Function Body */
     icnsav = knumbr_1.k0;
     dshar4_1.zl = znumbr_1.z1;
 /*                 SET IAFL FLAG */
     numdim = 0;
     ldef_1.jcs = FALSE_;
     if (ifxcor_1.igoto == knumbr_1.k0) {
     goto L1;
     }
     if (ifxcor_1.isrch != knumbr_1.k0) {
     goto L9600;
     }
 /* L502: */
     aerr_(&c__20202, "GO2     ", (ftnlen)8);
     goto L9100;
 L1:
     if (ifxcor_1.icscnt - knumbr_1.k1 <= 0) {
     goto L1101;
     } else {
     goto L1102;
     }
 L1102:
     aerr_(&c__20203, "GO2     ", (ftnlen)8);
     goto L9100;
 L1101:
     ifxcor_1.istrup = knumbr_1.k1;
     dshar4_1.dp = -1.f;
     isv_1.jent[ifxcor_1.ips - 1] = knumbr_1.k1;
     isv_1.jent[ifxcor_1.ids - 1] = knumbr_1.k1;
     ifxcor_1.is = ifxcor_1.ids;
     apt234_(hmod, &adress[1]);
     if (ifxcor_1.iaerr <= 0) {
     goto L503;
     } else {
     goto L9100;
     }
 L503:
     fxcor_1.tek[0] = fxcor_1.te[0];
     fxcor_1.tek[1] = fxcor_1.te[1];
     fxcor_1.tek[2] = fxcor_1.te[2];
     xdir = (doublereal) knumbr_1.k1;
     if (*kdynfl != knumbr_1.k0) {
     apt238_(&c__41);
     }
 /* L1000: */
     if (ifxcor_1.inops <= 0) {
     goto L6;
     } else {
     goto L2;
     }
 L2:
     if (ifxcor_1.icscnt <= 0) {
     goto L3;
     } else {
     goto L1020;
     }
 L3:
     ngosrf = knumbr_1.k1;
     goto L7;
 L1020:
     aerr_(&c__20204, "GO2     ", (ftnlen)8);
     goto L9100;
 L6:
     ngosrf = ifxcor_1.icscnt + knumbr_1.k2;
 L7:
     s_copy(charct_1.modfer, hgo, (ftnlen)6, (ftnlen)2);
     apt235_();
     if (ifxcor_1.iaerr > knumbr_1.k0) {
     goto L9100;
     }
     if (ifxcor_1.inops != knumbr_1.k1) {
     goto L1610;
     }
     for (i__ = 1; i__ <= 4; ++i__) {
 /* L1605: */
     cansav[i__ - 1] = canon[i__ - 1];
     }
     icnsav = knumbr_1.k1;
 L1610:
     apt240_(&numdim);
     id = 0;
 L1070:
     ia = knumbr_1.k1;
     ib = knumbr_1.k1;
     tem1 = znumbr_1.z0;
 L1080:
     id += knumbr_1.k1;
 /* L1090: */
     if (ngosrf - id >= 0) {
     goto L1100;
     } else {
     goto L1300;
     }
 L1100:
     if ((i__1 = id - knumbr_1.k2) < 0) {
     goto L1110;
     } else if (i__1 == 0) {
     goto L1120;
     } else {
     goto L1130;
     }
 L1110:
     ifxcor_1.is = ifxcor_1.ids;
     goto L1140;
 L1120:
     ifxcor_1.is = ifxcor_1.ips;
     goto L1140;
 L1130:
     ifxcor_1.is = ifxcor_1.ics;
 L1140:
     if (isv_1.indir__[ifxcor_1.is - 1] == 0 && isv_1.isfidn[ifxcor_1.is - 1]
         != 12) {
     goto L1160;
     }
 /* L1150: */
     ia += knumbr_1.k1;
     if (*kdynfl != knumbr_1.k0) {
     apt238_(&c__42);
     }
     goto L1080;
 L1160:
     if (*kdynfl != knumbr_1.k0) {
     apt238_(&c__43);
     }
 /* L1161: */
     if ((i__1 = isv_1.isvfl[ifxcor_1.is - 1]) < 0) {
     goto L9000;
     } else if (i__1 == 0) {
     goto L1180;
     } else {
     goto L1170;
     }
 L1170:
     fxcor_1.ti[0] = sv_1.sfvct[ifxcor_1.is * 3 - 3];
     fxcor_1.ti[1] = sv_1.sfvct[ifxcor_1.is * 3 - 2];
     fxcor_1.ti[2] = sv_1.sfvct[ifxcor_1.is * 3 - 1];
     if (ifxcor_1.is == ifxcor_1.ics) {
     goto L1173;
     }
     issto = ifxcor_1.is;
     ifxcor_1.is = ifxcor_1.ics + 1;
     svcopy_(&issto, &ifxcor_1.is);
     isvcpy_(&issto, &ifxcor_1.is);
 L1173:
     sv_1.tn[ifxcor_1.is * 3 - 3] = sv_1.sfvct[ifxcor_1.is * 3 - 3];
     sv_1.tn[ifxcor_1.is * 3 - 2] = sv_1.sfvct[ifxcor_1.is * 3 - 2];
     sv_1.tn[ifxcor_1.is * 3 - 1] = sv_1.sfvct[ifxcor_1.is * 3 - 1];
     isv1_1.j20[ifxcor_1.is - 1] = 0;
     isv1_1.j23[ifxcor_1.is - 1] = knumbr_1.k1;
     dshar4_1.dp = 0.f;
     ifxcor_1.istrup = 2;
     check_();
     if (ifxcor_1.iaerr != 0) {
     goto L9100;
     } else {
     goto L100;
     }
 L100:
     if (ifxcor_1.is == ifxcor_1.ics) {
     goto L1175;
     }
     svcopy_(&ifxcor_1.is, &issto);
     isvcpy_(&ifxcor_1.is, &issto);
     ifxcor_1.is = issto;
     if (tem3 != 0.) {
     goto L1240;
     } else {
     goto L1210;
     }
 L1175:
     if (sv1_1.csd[ifxcor_1.is - 1] != 0.) {
     goto L1239;
     } else {
     goto L1210;
     }
 L1180:
     if (ifxcor_1.is == ifxcor_1.ips) {
     goto L1181;
     }
     if (isv_1.indir__[ifxcor_1.ids - 1] == 1) {
     goto L1182;
     }
     if (isv_1.indir__[ifxcor_1.ics - 1] == 1) {
     goto L1183;
     }
     sv_1.tn[ifxcor_1.is * 3 - 3] = znumbr_1.z1;
     sv_1.tn[ifxcor_1.is * 3 - 2] = znumbr_1.z0;
     sv_1.tn[ifxcor_1.is * 3 - 1] = znumbr_1.z0;
     goto L1190;
 L1181:
     sv_1.tn[ifxcor_1.is * 3 - 3] = -fxcor_1.ta[0];
     sv_1.tn[ifxcor_1.is * 3 - 2] = -fxcor_1.ta[1];
     sv_1.tn[ifxcor_1.is * 3 - 1] = -fxcor_1.ta[2];
     goto L1190;
 L1182:
     k = ifxcor_1.ids;
     goto L1184;
 L1183:
     k = ifxcor_1.ics;
 L1184:
     sv_1.tn[ifxcor_1.is * 3 - 3] = sv_1.vndir[k * 3 - 3];
     sv_1.tn[ifxcor_1.is * 3 - 2] = sv_1.vndir[k * 3 - 2];
     sv_1.tn[ifxcor_1.is * 3 - 1] = sv_1.vndir[k * 3 - 1];
 L1190:
     isv_1.iopset[ifxcor_1.is - 1] = 0;
     isv_1.jent[ifxcor_1.is - 1] = knumbr_1.k1;
     isv_1.jtn[ifxcor_1.is - 1] = 0;
     isv_1.ju1[ifxcor_1.is - 1] = knumbr_1.k1;
     isv_1.jiops[ifxcor_1.is - 1] = 0;
     ishr18_1.jminr = knumbr_1.k1;
 /* L1200: */
     amind_();
     ishr18_1.jminr = knumbr_1.k0;
     if (ifxcor_1.iaerr != 0) {
     goto L9100;
     } else {
     goto L1210;
     }
 L1210:
     tem3 = (d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1));
     if (*kdynfl != knumbr_1.k0) {
     apt238_(&knumbr_1.k44);
     }
     goto L1240;
 L1239:
     tem3 = sv1_1.csd[ifxcor_1.is - 1];
 L1240:
     if (tem1 - (d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1)) <= 0.) {
     goto L1250;
     } else {
     goto L1260;
     }
 L1250:
     tem1 = (d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1));
 L1260:
     switch (ib) {
     case 1:  goto L1080;
     case 2:  goto L1310;
     case 3:  goto L1270;
     }
 L1270:
     ib = knumbr_1.k2;
     goto L1500;
 L1300:
     id = 0;
     ib = knumbr_1.k2;
 L1310:
     ia -= knumbr_1.k1;
 /* L1320: */
     if (ia < 0) {
     goto L9000;
     } else if (ia == 0) {
     goto L2000;
     } else {
     goto L1330;
     }
 L1330:
     id += knumbr_1.k1;
 /* L1340: */
     if (ngosrf - id >= 0) {
     goto L1350;
     } else {
     goto L9000;
     }
 L1350:
     if ((i__1 = id - knumbr_1.k2) < 0) {
     goto L1360;
     } else if (i__1 == 0) {
     goto L1370;
     } else {
     goto L1380;
     }
 L1360:
     ifxcor_1.is = ifxcor_1.ids;
     goto L1390;
 L1370:
     ifxcor_1.is = ifxcor_1.ips;
     goto L1390;
 L1380:
     ifxcor_1.is = ifxcor_1.ics;
 L1390:
     if ((i__1 = isv_1.indir__[ifxcor_1.is - 1]) < 0) {
     goto L9000;
     } else if (i__1 == 0) {
     goto L1391;
     } else {
     goto L1400;
     }
 L1391:
     if (isv_1.isfidn[ifxcor_1.is - 1] != 12) {
     goto L1330;
     }
     sv_1.vndir[ifxcor_1.is * 3 - 3] = znumbr_1.z0;
     sv_1.vndir[ifxcor_1.is * 3 - 2] = znumbr_1.z0;
     sv_1.vndir[ifxcor_1.is * 3 - 1] = znumbr_1.z0;
 L1400:
     for (k = 1; k <= 3; ++k) {
     sv_1.tp[k + ifxcor_1.is * 3 - 4] = fxcor_1.te[k - 1] + znumbr_1.z5em1
         * fxcor_1.cutdat[6] * fxcor_1.ta[k - 1] + sv_1.th[ifxcor_1.is
         - 1] * sv_1.vndir[k + ifxcor_1.is * 3 - 4];
 /* L1420: */
     sv_1.tn[k + ifxcor_1.is * 3 - 4] = sv_1.vndir[k + ifxcor_1.is * 3 - 4]
         ;
     }
     isv_1.iop[ifxcor_1.is - 1] = knumbr_1.k1;
     if (isv_1.isfidn[ifxcor_1.is - 1] == 12 && isv_1.indir__[ifxcor_1.is - 1]
         == 0) {
     isv_1.iop[ifxcor_1.is - 1] = knumbr_1.k2;
     }
     ddst_();
     isv_1.iop[ifxcor_1.is - 1] = knumbr_1.k1;
     if (ifxcor_1.ier != 0) {
     goto L1410;
     } else {
     goto L1430;
     }
 L1410:
     ib = knumbr_1.k3;
     goto L1160;
 L1430:
     tem2 = sv_1.s[ifxcor_1.is - 1];
     if (isv_1.isftyp[ifxcor_1.is - 1] - knumbr_1.k3 != 0) {
     goto L1445;
     } else {
     goto L1440;
     }
 L1445:
     tem2 -= fxcor_1.cutdat[0];
 L1440:
     issv = ifxcor_1.is;
     for (i__ = 1; i__ <= 3; ++i__) {
 /*          CHECK FOR ALL SURFACE */
     if (i__ == 1) {
         ifxcor_1.is = ifxcor_1.ids;
     }
     if (i__ == 2) {
         ifxcor_1.is = ifxcor_1.ips;
     }
     if (i__ == 3 && ifxcor_1.icscnt == 0) {
         goto L1431;
     }
     if (i__ == 3) {
         ifxcor_1.is = ifxcor_1.ics;
     }
 /*    IF ALREADY CHECKED SKIP */
 /* L1435: */
     if (ifxcor_1.is == issv) {
         goto L1431;
     }
     fxcor_1.temp[0] = sv_1.tn[ifxcor_1.is * 3 - 3];
     fxcor_1.temp[1] = sv_1.tn[ifxcor_1.is * 3 - 2];
     fxcor_1.temp[2] = sv_1.tn[ifxcor_1.is * 3 - 1];
     fxcor_1.temp[6] = sv_1.tp[ifxcor_1.is * 3 - 3];
     fxcor_1.temp[7] = sv_1.tp[ifxcor_1.is * 3 - 2];
     fxcor_1.temp[8] = sv_1.tp[ifxcor_1.is * 3 - 1];
     for (k = 1; k <= 3; ++k) {
         sv_1.tp[k + ifxcor_1.is * 3 - 4] = fxcor_1.te[k - 1] +
             znumbr_1.z5em1 * fxcor_1.cutdat[6] * fxcor_1.ta[k - 1] +
             sv_1.th[ifxcor_1.is - 1] * sv_1.vndir[k + issv * 3 - 4];
 /* L1436: */
         sv_1.tn[k + ifxcor_1.is * 3 - 4] = sv_1.vndir[k + issv * 3 - 4];
     }
     isv_1.iop[ifxcor_1.is - 1] = knumbr_1.k1;
     ddst_();
     if (ifxcor_1.ier == 1) {
         goto L1438;
     }
     tem3 = sv_1.s[ifxcor_1.is - 1];
     if (isv_1.isftyp[ifxcor_1.is - 1] != knumbr_1.k3) {
         tem3 -= fxcor_1.cutdat[0];
     }
     if (tem3 < 1e-8f) {
         goto L1438;
     }
     if (tem3 < tem2) {
         tem2 = tem3;
     }
 L1438:
     sv_1.tn[ifxcor_1.is * 3 - 3] = fxcor_1.temp[0];
     sv_1.tn[ifxcor_1.is * 3 - 2] = fxcor_1.temp[1];
     sv_1.tn[ifxcor_1.is * 3 - 1] = fxcor_1.temp[2];
     sv_1.tp[ifxcor_1.is * 3 - 3] = fxcor_1.temp[6];
     sv_1.tp[ifxcor_1.is * 3 - 2] = fxcor_1.temp[7];
     sv_1.tp[ifxcor_1.is * 3 - 1] = fxcor_1.temp[8];
 L1431:
     ;
     }
     ifxcor_1.is = issv;
     fxcor_1.temp[4] = tem2 - sv_1.tau[ifxcor_1.is - 1];
     fxcor_1.te[0] += fxcor_1.temp[4] * sv_1.vndir[ifxcor_1.is * 3 - 3];
     fxcor_1.te[1] += fxcor_1.temp[4] * sv_1.vndir[ifxcor_1.is * 3 - 2];
     fxcor_1.te[2] += fxcor_1.temp[4] * sv_1.vndir[ifxcor_1.is * 3 - 1];
     if (isv_1.indir__[ifxcor_1.ics - 1] == 1 || isv_1.isvfl[ifxcor_1.ics - 1]
         == 1 || ifxcor_1.icscnt == 0) {
     goto L1160;
     }
     isv_1.jent[ifxcor_1.ics - 1] = 1;
     ishr18_1.jminr = 1;
     isssv = ifxcor_1.is;
     ifxcor_1.is = ifxcor_1.ics;
     amind_();
     ishr18_1.jminr = 0;
     ifxcor_1.is = isssv;
     goto L1160;
 L1500:
     if (tem3 - tem1 <= 0.) {
     goto L1510;
     } else {
     goto L1520;
     }
 /*              USE SMALLEST MINIMUM DIST WHICH IS */
 /*              GREATER THAN TWO TOLERANCES */
 L1510:
     tem2 = tem1;
     i__1 = ifxcor_1.ics;
     i__2 = ifxcor_1.lsv;
     for (iii = ifxcor_1.ips; i__2 < 0 ? iii >= i__1 : iii <= i__1; iii +=
         i__2) {
     if (isv_1.isvfl[iii - 1] == 0) {
         goto L1501;
     }
     if (sv1_1.csd[iii - 1] - znumbr_1.z2 * sv_1.tau[ifxcor_1.is - 1] <=
         0.) {
         goto L1501;
     } else {
         goto L1502;
     }
 L1502:
 /* Computing MIN */
     d__1 = tem2, d__2 = sv1_1.csd[iii - 1];
     tem2 = min(d__1,d__2);
 L1501:
     ;
     }
     goto L1440;
 L1511:
     tem2 = tem1;
     goto L1440;
 L1520:
     if (tem3 - znumbr_1.z10 >= 0.) {
     goto L1511;
     } else {
     goto L1530;
     }
 L1530:
     tem2 = tem3;
     goto L1440;
 L2000:
     if ((i__2 = ngosrf - knumbr_1.k2) < 0) {
     goto L2010;
     } else if (i__2 == 0) {
     goto L3000;
     } else {
     goto L3120;
     }
 L2010:
     if ((i__2 = isv_1.indir__[ifxcor_1.ids - 1]) < 0) {
     goto L9000;
     } else if (i__2 == 0) {
     goto L2030;
     } else {
     goto L2020;
     }
 L2020:
     dshar4_1.dir[0] = sv_1.vndir[ifxcor_1.ids * 3 - 3];
     dshar4_1.dir[1] = sv_1.vndir[ifxcor_1.ids * 3 - 2];
     dshar4_1.dir[2] = sv_1.vndir[ifxcor_1.ids * 3 - 1];
     goto L2040;
 L2030:
     dshar4_1.dir[0] = sv_1.tn[ifxcor_1.ids * 3 - 3];
     dshar4_1.dir[1] = sv_1.tn[ifxcor_1.ids * 3 - 2];
     dshar4_1.dir[2] = sv_1.tn[ifxcor_1.ids * 3 - 1];
 L2040:
     if (abs(dshar4_1.dir[2]) - zlit1 <= 0.) {
     goto L2050;
     } else {
     goto L2060;
     }
 L2050:
     sv_1.plnv[ifxcor_1.ics * 3 - 3] = dshar4_1.dir[1];
     sv_1.plnv[ifxcor_1.ics * 3 - 2] = -dshar4_1.dir[0];
     sv_1.plnv[ifxcor_1.ics * 3 - 1] = znumbr_1.z0;
     goto L2090;
 L2060:
     if (abs(dshar4_1.dir[1]) - zlit1 <= 0.) {
     goto L2070;
     } else {
     goto L2080;
     }
 L2070:
     sv_1.plnv[ifxcor_1.ics * 3 - 3] = dshar4_1.dir[2];
     sv_1.plnv[ifxcor_1.ics * 3 - 2] = znumbr_1.z0;
     sv_1.plnv[ifxcor_1.ics * 3 - 1] = -dshar4_1.dir[0];
     goto L2090;
 L2080:
     if (abs(dshar4_1.dir[0]) - zlit1 <= 0.) {
     goto L2085;
     } else {
     goto L2087;
     }
 L2085:
     sv_1.plnv[ifxcor_1.ics * 3 - 3] = znumbr_1.z0;
     sv_1.plnv[ifxcor_1.ics * 3 - 2] = dshar4_1.dir[2];
     sv_1.plnv[ifxcor_1.ics * 3 - 1] = -dshar4_1.dir[1];
     goto L2090;
 L2087:
     if (abs(dshar4_1.dir[1]) - abs(dshar4_1.dir[2]) <= 0.) {
     goto L2070;
     } else {
     goto L2050;
     }
 L2090:
     vnorm_(&sv_1.plnv[ifxcor_1.ics * 3 - 3], &sv_1.plnv[ifxcor_1.ics * 3 - 3])
         ;
     cross_(dshar4_1.dir, &sv_1.plnv[ifxcor_1.ics * 3 - 3], &sv_1.plnv[
         ifxcor_1.ips * 3 - 3]);
     vnorm_(&sv_1.plnv[ifxcor_1.ips * 3 - 3], &sv_1.plnv[ifxcor_1.ips * 3 - 3])
         ;
 /* L2110: */
     sv_1.plnd[ifxcor_1.ips - 1] = sv_1.plnv[ifxcor_1.ips * 3 - 3] *
         fxcor_1.tek[0] + sv_1.plnv[ifxcor_1.ips * 3 - 2] * fxcor_1.tek[1]
         + sv_1.plnv[ifxcor_1.ips * 3 - 1] * fxcor_1.tek[2];
     sv_1.plnd[ifxcor_1.ics - 1] = sv_1.plnv[ifxcor_1.ics * 3 - 3] *
         fxcor_1.tek[0] + sv_1.plnv[ifxcor_1.ics * 3 - 2] * fxcor_1.tek[1]
         + sv_1.plnv[ifxcor_1.ics * 3 - 1] * fxcor_1.tek[2];
 /* L2120: */
     isv_1.icanon[ifxcor_1.ips - 1] = knumbr_1.k1;
     isv_1.isfidn[ifxcor_1.ips - 1] = knumbr_1.k2;
     isv_1.isftyp[ifxcor_1.ips - 1] = knumbr_1.k3;
     isv_1.itlon[ifxcor_1.ips - 1] = 0;
     canon[0] = sv_1.plnv[ifxcor_1.ips * 3 - 3];
     canon[1] = sv_1.plnv[ifxcor_1.ips * 3 - 2];
     canon[2] = sv_1.plnv[ifxcor_1.ips * 3 - 1];
     canon[3] = sv_1.plnd[ifxcor_1.ips - 1];
     isv_1.ipl[ifxcor_1.ips - 1] = knumbr_1.k1;
     isv_1.iunfl[ifxcor_1.ips - 1] = knumbr_1.k1;
     isv_1.jent[ifxcor_1.ips - 1] = knumbr_1.k1;
     isv_1.jtn[ifxcor_1.ips - 1] = 0;
     isv_1.iopset[ifxcor_1.ips - 1] = 0;
     isv_1.ju1[ifxcor_1.ips - 1] = knumbr_1.k1;
     isv_1.jiops[ifxcor_1.ips - 1] = 0;
     sv_1.tn[ifxcor_1.ips * 3 - 3] = sv_1.plnv[ifxcor_1.ips * 3 - 3];
     sv_1.tn[ifxcor_1.ips * 3 - 2] = sv_1.plnv[ifxcor_1.ips * 3 - 2];
     sv_1.tn[ifxcor_1.ips * 3 - 1] = sv_1.plnv[ifxcor_1.ips * 3 - 1];
     sv_1.past[ifxcor_1.ips - 1] = znumbr_1.z1;
     goto L3110;
 L3000:
     if ((i__2 = isv_1.indir__[ifxcor_1.ids - 1]) < 0) {
     goto L9000;
     } else if (i__2 == 0) {
     goto L3030;
     } else {
     goto L3010;
     }
 L3010:
     if ((i__2 = isv_1.indir__[ifxcor_1.ips - 1]) < 0) {
     goto L9000;
     } else if (i__2 == 0) {
     goto L3050;
     } else {
     goto L3020;
     }
 L3020:
     isv1_1.j50[ifxcor_1.ics - 1] = 0;
     isv1_1.j51[ifxcor_1.ics - 1] = 0;
     ifxcor_1.is = ifxcor_1.ics;
     centr_();
     if (ifxcor_1.iaerr != 0) {
     goto L9100;
     } else {
     goto L101;
     }
 L101:
     if (ishr18_1.jcr != 0) {
     goto L3152;
     } else {
     goto L9999;
     }
 L3030:
     if ((i__2 = isv_1.indir__[ifxcor_1.ips - 1]) < 0) {
     goto L9000;
     } else if (i__2 == 0) {
     goto L3020;
     } else {
     goto L3040;
     }
 L3040:
     ifxcor_1.is = ifxcor_1.ips;
     goto L3060;
 L3050:
     ifxcor_1.is = ifxcor_1.ids;
 L3060:
     dshar4_1.dir[0] = sv_1.vndir[ifxcor_1.is * 3 - 3];
     dshar4_1.dir[1] = sv_1.vndir[ifxcor_1.is * 3 - 2];
     dshar4_1.dir[2] = sv_1.vndir[ifxcor_1.is * 3 - 1];
     if ((d__1 = sv_1.tn[ifxcor_1.ips * 3 - 3] * sv_1.tn[ifxcor_1.ids * 3 - 3]
         + sv_1.tn[ifxcor_1.ips * 3 - 2] * sv_1.tn[ifxcor_1.ids * 3 - 2] +
         sv_1.tn[ifxcor_1.ips * 3 - 1] * sv_1.tn[ifxcor_1.ids * 3 - 1],
         abs(d__1)) > zlit1) {
     goto L3020;
     }
     cross_(&sv_1.tn[ifxcor_1.ips * 3 - 3], &sv_1.tn[ifxcor_1.ids * 3 - 3], &
         sv_1.plnv[ifxcor_1.ics * 3 - 3]);
     vnorm_(&sv_1.plnv[ifxcor_1.ics * 3 - 3], &sv_1.plnv[ifxcor_1.ics * 3 - 3])
         ;
     if (ifxcor_1.ier != 0) {
     goto L3020;
     } else {
     goto L3065;
     }
 L3065:
     cross_(&sv_1.plnv[ifxcor_1.ics * 3 - 3], dshar4_1.dir, &sv_1.plnv[
         ifxcor_1.ics * 3 - 3]);
     vnorm_(&sv_1.plnv[ifxcor_1.ics * 3 - 3], &sv_1.plnv[ifxcor_1.ics * 3 - 3])
         ;
     if (ifxcor_1.ier != 0) {
     goto L3020;
     } else {
     goto L3070;
     }
 L3070:
     cross_(&sv_1.plnv[ifxcor_1.ics * 3 - 3], dshar4_1.dir, &sv_1.plnv[
         ifxcor_1.ics * 3 - 3]);
 /* L3080: */
     vnorm_(&sv_1.plnv[ifxcor_1.ics * 3 - 3], &sv_1.plnv[ifxcor_1.ics * 3 - 3])
         ;
 /* L3090: */
     if (ifxcor_1.ier != 0) {
     goto L3020;
     } else {
     goto L4100;
     }
 L4100:
     if (isv_1.ipl[ifxcor_1.ips - 1] != 0) {
     goto L4107;
     } else {
     goto L4105;
     }
 L4105:
     if (isv_1.ipl[ifxcor_1.ids - 1] != 0) {
     goto L4108;
     } else {
     goto L3020;
     }
 L4107:
     k = ifxcor_1.ips;
     goto L4109;
 L4108:
     k = ifxcor_1.ids;
 L4109:
     ifxcor_1.ic = isv_1.icanon[k - 1];
     if ((d__1 = sv_1.plnv[ifxcor_1.ics * 3 - 3] * canon[ifxcor_1.ic - 1] +
         sv_1.plnv[ifxcor_1.ics * 3 - 2] * canon[ifxcor_1.ic] + sv_1.plnv[
         ifxcor_1.ics * 3 - 1] * canon[ifxcor_1.ic + 1], abs(d__1)) -
         zlit2 <= 0.) {
     goto L3100;
     } else {
     goto L3020;
     }
 L3100:
     sv_1.plnd[ifxcor_1.ics - 1] = sv_1.plnv[ifxcor_1.ics * 3 - 3] *
         fxcor_1.tek[0] + sv_1.plnv[ifxcor_1.ics * 3 - 2] * fxcor_1.tek[1]
         + sv_1.plnv[ifxcor_1.ics * 3 - 1] * fxcor_1.tek[2];
 L3110:
     isv_1.icanon[ifxcor_1.ics - 1] = klit3;
     isv_1.isfidn[ifxcor_1.ics - 1] = knumbr_1.k1;
     canon[20] = sv_1.plnv[ifxcor_1.ics * 3 - 3];
     canon[21] = sv_1.plnv[ifxcor_1.ics * 3 - 2];
     canon[22] = sv_1.plnv[ifxcor_1.ics * 3 - 1];
     canon[23] = sv_1.plnd[ifxcor_1.ics - 1];
     isv_1.isftyp[ifxcor_1.ics - 1] = knumbr_1.k3;
     isv_1.itlon[ifxcor_1.ics - 1] = 0;
     isv_1.iunfl[ifxcor_1.ics - 1] = knumbr_1.k1;
     isv_1.ipl[ifxcor_1.ics - 1] = knumbr_1.k1;
     isv_1.jent[ifxcor_1.ics - 1] = knumbr_1.k1;
     isv_1.jtn[ifxcor_1.ics - 1] = 0;
     isv_1.iopset[ifxcor_1.ics - 1] = 0;
     isv_1.ju1[ifxcor_1.ics - 1] = knumbr_1.k1;
     sv_1.tn[ifxcor_1.ics * 3 - 3] = sv_1.plnv[ifxcor_1.ics * 3 - 3];
     sv_1.tn[ifxcor_1.ics * 3 - 2] = sv_1.plnv[ifxcor_1.ics * 3 - 2];
     sv_1.tn[ifxcor_1.ics * 3 - 1] = sv_1.plnv[ifxcor_1.ics * 3 - 1];
     isv_1.jiops[ifxcor_1.ics - 1] = 0;
     sv_1.past[ifxcor_1.ics - 1] = znumbr_1.z1;
     isv_1.iafl[ifxcor_1.ics - 1] = knumbr_1.km1;
     ifxcor_1.icscnt = knumbr_1.k1;
 L3120:
     isv1_1.j50[ifxcor_1.ics - 1] = knumbr_1.k1;
     isv1_1.j51[ifxcor_1.ics - 1] = knumbr_1.k1;
 /* L3130: */
     ifxcor_1.is = ifxcor_1.ics;
 /* L3140: */
     centr_();
     if (ifxcor_1.iaerr != 0) {
     goto L9100;
     } else {
     goto L102;
     }
 L102:
     if (ishr18_1.jcr - knumbr_1.k1 != 0) {
     goto L3141;
     } else {
     goto L9999;
     }
 L3141:
     if (ifxcor_1.numsur - knumbr_1.k3 >= 0) {
     goto L3150;
     } else {
     goto L3020;
     }
 /*         TRY MOVING TO PS AND DS FIRST */
 L3150:
     if (xdir <= 0.) {
     goto L3152;
     } else {
     goto L3151;
     }
 L3151:
     xdir = (doublereal) knumbr_1.km1;
     isv1_1.j50[ifxcor_1.is - 1] = 0;
     isv1_1.j51[ifxcor_1.is - 1] = 0;
     ifxcor_1.is = ifxcor_1.ics;
     centr_();
     if (ishr18_1.jcr != 0) {
     goto L3152;
     } else {
     goto L1070;
     }
 L3152:
     aerr_(&c__20205, "GO2     ", (ftnlen)8);
     goto L9100;
 L9000:
     aerr_(&c__20206, "GO2     ", (ftnlen)8);
     goto L9100;
 L9999:
     ifxcor_1.icl = knumbr_1.k3;
     atape_();
     if (ifxcor_1.iaerr != 0) {
     goto L9100;
     } else {
     goto L103;
     }
 L103:
     if (*kdynfl != knumbr_1.k0) {
     apt238_(&c__45);
     }
     goto L9500;
 L9100:
     apt236_();
     goto L9900;
 L9500:
     apt236_();
     ifxcor_1.istrup = 0;
     if (isv_1.isftyp[ifxcor_1.ips - 1] != knumbr_1.k2) {
     goto L9550;
     }
     isv_1.isftyp[ifxcor_1.ips - 1] = knumbr_1.k1;
     sv_1.past[ifxcor_1.ips - 1] = znumbr_1.z1;
 L9550:
     if (isv_1.isftyp[ifxcor_1.ids - 1] != knumbr_1.k2) {
     goto L9600;
     }
     isv_1.isftyp[ifxcor_1.ids - 1] = knumbr_1.k1;
     sv_1.past[ifxcor_1.ids - 1] = znumbr_1.z1;
 L9600:
     for (k = 1; k <= 3; ++k) {
     fxcor_1.temp[k - 1] = fxcor_1.te[k - 1] - fxcor_1.tek[k - 1];
     sv_1.tpk[k + ifxcor_1.ips * 3 - 4] = sv_1.tp[k + ifxcor_1.ips * 3 - 4]
         ;
     sv_1.spk[k + ifxcor_1.ips * 3 - 4] = sv_1.sp[k + ifxcor_1.ips * 3 - 4]
         ;
     sv_1.u1k[k + ifxcor_1.ips * 3 - 4] = sv_1.u1[k + ifxcor_1.ips * 3 - 4]
         ;
     sv_1.snk[k + ifxcor_1.ips * 3 - 4] = sv_1.sn[k + ifxcor_1.ips * 3 - 4]
         ;
 /* L4112: */
     }
     sv_1.sk[ifxcor_1.ips * 3 - 3] = sv_1.s[ifxcor_1.ips - 1];
 L9900:
     if (icnsav != knumbr_1.k1) {
     goto L9990;
     }
     for (i__ = 1; i__ <= 4; ++i__) {
 /* L9910: */
     canon[i__ - 1] = cansav[i__ - 1];
     }
 L9990:
     return 0;
 } /* go2_ */
Variable Documentation
struct { ... } _BLNK__
doublereal a
Definition at line 18 of file GO2.c.
doublereal addcom[25]
Definition at line 141 of file GO2.c.
struct { ... } addcom_
doublereal alp
Definition at line 28 of file GO2.c.
logical altmlt
Definition at line 92 of file GO2.c.
doublereal ax4[3]
Definition at line 28 of file GO2.c.
doublereal b
Definition at line 18 of file GO2.c.
logical bnderr
Definition at line 92 of file GO2.c.
logical boundf
Definition at line 92 of file GO2.c.
doublereal c__
Definition at line 18 of file GO2.c.
integer c__20202 = 20202 static
Definition at line 154 of file GO2.c.
Referenced by go2_().
integer c__20203 = 20203 static
Definition at line 155 of file GO2.c.
Referenced by go2_().
integer c__20204 = 20204 static
Definition at line 157 of file GO2.c.
Referenced by go2_().
integer c__20205 = 20205 static
Definition at line 160 of file GO2.c.
Referenced by go2_().
integer c__20206 = 20206 static
Definition at line 161 of file GO2.c.
Referenced by go2_().
integer c__41 = 41 static
Definition at line 156 of file GO2.c.
Referenced by go2_().
integer c__42 = 42 static
Definition at line 158 of file GO2.c.
Referenced by go2_().
integer c__43 = 43 static
Definition at line 159 of file GO2.c.
Referenced by go2_().
integer c__45 = 45 static
Definition at line 162 of file GO2.c.
Referenced by go2_().
doublereal cagl
Definition at line 28 of file GO2.c.
logical canflg
Definition at line 92 of file GO2.c.
doublereal cc[15]
Definition at line 58 of file GO2.c.
doublereal cendis
Definition at line 18 of file GO2.c.
struct { ... } charct_
doublereal cmove[3]
Definition at line 18 of file GO2.c.
doublereal com[36000]
Definition at line 147 of file GO2.c.
doublereal com1
Definition at line 18 of file GO2.c.
doublereal com4
Definition at line 18 of file GO2.c.
doublereal corrad[8]
Definition at line 43 of file GO2.c.
doublereal cos1[5]
Definition at line 75 of file GO2.c.
doublereal cplfl[5]
Definition at line 75 of file GO2.c.
doublereal cptst[5]
Definition at line 75 of file GO2.c.
doublereal csd[5]
Definition at line 75 of file GO2.c.
doublereal cutdat[7]
Definition at line 28 of file GO2.c.
doublereal d1
Definition at line 18 of file GO2.c.
doublereal d2a
Definition at line 18 of file GO2.c.
doublereal degrad
Definition at line 84 of file GO2.c.
doublereal dir[3]
Definition at line 18 of file GO2.c.
doublereal dp
Definition at line 18 of file GO2.c.
doublereal dp1
Definition at line 18 of file GO2.c.
doublereal dpcnt
Definition at line 18 of file GO2.c.
doublereal dpe
Definition at line 18 of file GO2.c.
doublereal dpi
Definition at line 18 of file GO2.c.
doublereal dpl
Definition at line 18 of file GO2.c.
doublereal dplan[15]
Definition at line 75 of file GO2.c.
doublereal dpmax
Definition at line 28 of file GO2.c.
doublereal dpmx1[5]
Definition at line 75 of file GO2.c.
struct { ... } dshar4_
doublereal eps1[5]
Definition at line 58 of file GO2.c.
doublereal eps2[5]
Definition at line 58 of file GO2.c.
doublereal eps3[5]
Definition at line 58 of file GO2.c.
doublereal eps4[5]
Definition at line 58 of file GO2.c.
doublereal eps6[5]
Definition at line 58 of file GO2.c.
doublereal eps8[5]
Definition at line 58 of file GO2.c.
doublereal flipck
Definition at line 18 of file GO2.c.
doublereal fwd[3]
Definition at line 18 of file GO2.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file GO2.c.
char haerr[8]
Definition at line 50 of file GO2.c.
char hback[8]
Definition at line 50 of file GO2.c.
struct { ... } hblock_
char hcldat[8]
Definition at line 50 of file GO2.c.
char hcs[8]
Definition at line 50 of file GO2.c.
char hdown[8]
Definition at line 50 of file GO2.c.
char hds[8]
Definition at line 50 of file GO2.c.
char hdynp[8]
Definition at line 50 of file GO2.c.
char hfwd[8]
Definition at line 50 of file GO2.c.
char hgerr[8]
Definition at line 50 of file GO2.c.
doublereal hi
Definition at line 28 of file GO2.c.
char hlft[8]
Definition at line 50 of file GO2.c.
char hon[8]
Definition at line 50 of file GO2.c.
char hpast[8]
Definition at line 50 of file GO2.c.
char hps[8]
Definition at line 50 of file GO2.c.
char hpstan[8]
Definition at line 50 of file GO2.c.
char hrgt[8]
Definition at line 50 of file GO2.c.
char htanto[8]
Definition at line 50 of file GO2.c.
char hto[8]
Definition at line 50 of file GO2.c.
char hup[8]
Definition at line 50 of file GO2.c.
integer i3dflg
Definition at line 115 of file GO2.c.
integer iaerr
Definition at line 115 of file GO2.c.
integer iafl[5]
Definition at line 99 of file GO2.c.
integer iamdct
Definition at line 125 of file GO2.c.
integer iautps
Definition at line 115 of file GO2.c.
integer ibegin
Definition at line 115 of file GO2.c.
integer ic
Definition at line 115 of file GO2.c.
integer icanon[5]
Definition at line 99 of file GO2.c.
integer icheck
Definition at line 115 of file GO2.c.
integer icl
Definition at line 115 of file GO2.c.
integer ics
Definition at line 115 of file GO2.c.
integer icscnt
Definition at line 115 of file GO2.c.
integer ictdef
Definition at line 115 of file GO2.c.
integer icut
Definition at line 115 of file GO2.c.
integer ids
Definition at line 115 of file GO2.c.
integer ier
Definition at line 115 of file GO2.c.
integer ifar[5]
Definition at line 108 of file GO2.c.
integer ifl4[5]
Definition at line 108 of file GO2.c.
struct { ... } ifxcor_
integer igo
Definition at line 115 of file GO2.c.
integer igoto
Definition at line 115 of file GO2.c.
integer igoug
Definition at line 115 of file GO2.c.
integer igs
Definition at line 115 of file GO2.c.
integer index[5]
Definition at line 99 of file GO2.c.
integer indir__[5]
Definition at line 99 of file GO2.c.
integer inops
Definition at line 115 of file GO2.c.
integer iop[5]
Definition at line 99 of file GO2.c.
integer iopset[5]
Definition at line 99 of file GO2.c.
integer ipdpl
Definition at line 125 of file GO2.c.
integer ipl[5]
Definition at line 99 of file GO2.c.
integer ips
Definition at line 115 of file GO2.c.
integer ipsdef
Definition at line 115 of file GO2.c.
integer ipt
Definition at line 125 of file GO2.c.
integer ipt1
Definition at line 115 of file GO2.c.
integer is
Definition at line 115 of file GO2.c.
integer iseg
Definition at line 115 of file GO2.c.
integer iseqno
Definition at line 115 of file GO2.c.
integer isfidn[5]
Definition at line 99 of file GO2.c.
integer isftyp[5]
Definition at line 99 of file GO2.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 99 of file GO2.c.
integer isrch
Definition at line 115 of file GO2.c.
integer istrup
Definition at line 115 of file GO2.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 99 of file GO2.c.
integer it
Definition at line 115 of file GO2.c.
integer itlon[5]
Definition at line 99 of file GO2.c.
integer itseg[5]
Definition at line 99 of file GO2.c.
integer itsegk[5]
Definition at line 99 of file GO2.c.
integer iunfl[5]
Definition at line 99 of file GO2.c.
integer iws
Definition at line 125 of file GO2.c.
integer j10
Definition at line 125 of file GO2.c.
integer j12
Definition at line 125 of file GO2.c.
integer j13
Definition at line 125 of file GO2.c.
integer j20[5]
Definition at line 108 of file GO2.c.
integer j21[5]
Definition at line 108 of file GO2.c.
integer j22[5]
Definition at line 108 of file GO2.c.
integer j23[5]
Definition at line 108 of file GO2.c.
integer j50[5]
Definition at line 108 of file GO2.c.
integer j51[5]
Definition at line 108 of file GO2.c.
integer j54
Definition at line 125 of file GO2.c.
integer jbr
Definition at line 115 of file GO2.c.
integer jckr
Definition at line 125 of file GO2.c.
integer jcnt1
Definition at line 125 of file GO2.c.
integer jcnt2
Definition at line 125 of file GO2.c.
integer jcnt3
Definition at line 125 of file GO2.c.
integer jcpr
Definition at line 125 of file GO2.c.
integer jcr
Definition at line 125 of file GO2.c.
logical jcs
Definition at line 92 of file GO2.c.
integer jdr
Definition at line 125 of file GO2.c.
logical jds
Definition at line 92 of file GO2.c.
integer jent[5]
Definition at line 99 of file GO2.c.
integer jfind
Definition at line 125 of file GO2.c.
integer jgr
Definition at line 125 of file GO2.c.
integer jiops[5]
Definition at line 99 of file GO2.c.
integer jmin
Definition at line 125 of file GO2.c.
integer jminr
Definition at line 125 of file GO2.c.
integer jph[5]
Definition at line 108 of file GO2.c.
integer jpr
Definition at line 125 of file GO2.c.
integer jpxr
Definition at line 125 of file GO2.c.
integer jsw
Definition at line 115 of file GO2.c.
integer jtkf
Definition at line 125 of file GO2.c.
integer jtlflg[5]
Definition at line 99 of file GO2.c.
integer jtn[5]
Definition at line 99 of file GO2.c.
integer jtr
Definition at line 125 of file GO2.c.
integer ju1[5]
Definition at line 99 of file GO2.c.
integer k0
Definition at line 133 of file GO2.c.
integer k1
Definition at line 133 of file GO2.c.
integer k10
Definition at line 133 of file GO2.c.
integer k1013
Definition at line 133 of file GO2.c.
integer k12
Definition at line 133 of file GO2.c.
integer k13
Definition at line 133 of file GO2.c.
integer k15
Definition at line 133 of file GO2.c.
integer k16
Definition at line 133 of file GO2.c.
integer k18
Definition at line 133 of file GO2.c.
integer k19
Definition at line 133 of file GO2.c.
integer k1e4
Definition at line 133 of file GO2.c.
integer k1e6
Definition at line 133 of file GO2.c.
integer k2
Definition at line 133 of file GO2.c.
integer k23
Definition at line 133 of file GO2.c.
integer k24
Definition at line 133 of file GO2.c.
integer k25
Definition at line 133 of file GO2.c.
integer k26
Definition at line 133 of file GO2.c.
integer k27
Definition at line 133 of file GO2.c.
integer k29
Definition at line 133 of file GO2.c.
integer k3
Definition at line 133 of file GO2.c.
integer k30
Definition at line 133 of file GO2.c.
integer k31
Definition at line 133 of file GO2.c.
integer k32
Definition at line 133 of file GO2.c.
integer k33
Definition at line 133 of file GO2.c.
integer k34
Definition at line 133 of file GO2.c.
integer k4
Definition at line 133 of file GO2.c.
integer k44
Definition at line 133 of file GO2.c.
integer k45
Definition at line 133 of file GO2.c.
integer k46
Definition at line 133 of file GO2.c.
integer k47
Definition at line 133 of file GO2.c.
integer k48
Definition at line 133 of file GO2.c.
integer k5
Definition at line 133 of file GO2.c.
integer k50
Definition at line 133 of file GO2.c.
integer k51
Definition at line 133 of file GO2.c.
integer k52
Definition at line 133 of file GO2.c.
integer k6
Definition at line 133 of file GO2.c.
integer k7
Definition at line 133 of file GO2.c.
integer k8
Definition at line 133 of file GO2.c.
integer k9
Definition at line 133 of file GO2.c.
integer km1
Definition at line 133 of file GO2.c.
struct { ... } knumbr_
struct { ... } ldef_
integer limfl[5]
Definition at line 99 of file GO2.c.
integer lsv
Definition at line 115 of file GO2.c.
integer lsv1
Definition at line 115 of file GO2.c.
integer mantax
Definition at line 115 of file GO2.c.
integer mdic
Definition at line 125 of file GO2.c.
char modfer[6]
Definition at line 37 of file GO2.c.
integer motmod
Definition at line 115 of file GO2.c.
integer msav
Definition at line 115 of file GO2.c.
integer mulout
Definition at line 115 of file GO2.c.
integer nmbseg
Definition at line 115 of file GO2.c.
integer nmpnts
Definition at line 115 of file GO2.c.
integer notan[5]
Definition at line 108 of file GO2.c.
integer nrec
Definition at line 115 of file GO2.c.
integer numax
Definition at line 115 of file GO2.c.
integer numcnt
Definition at line 115 of file GO2.c.
integer nump
Definition at line 115 of file GO2.c.
integer numpt1
Definition at line 115 of file GO2.c.
integer numsfs
Definition at line 115 of file GO2.c.
integer numsur
Definition at line 115 of file GO2.c.
integer nw
Definition at line 115 of file GO2.c.
integer nwds
Definition at line 115 of file GO2.c.
doublereal ogle[3]
Definition at line 18 of file GO2.c.
doublereal p1[3]
Definition at line 18 of file GO2.c.
doublereal p2[3]
Definition at line 18 of file GO2.c.
doublereal param[6]
Definition at line 18 of file GO2.c.
doublereal past[5]
Definition at line 58 of file GO2.c.
logical pchlst
Definition at line 92 of file GO2.c.
doublereal pi
Definition at line 84 of file GO2.c.
doublereal plncs[5]
Definition at line 75 of file GO2.c.
doublereal plnd[5]
Definition at line 58 of file GO2.c.
doublereal plnd1[5]
Definition at line 75 of file GO2.c.
doublereal plnv[15]
Definition at line 58 of file GO2.c.
doublereal pltst[5]
Definition at line 75 of file GO2.c.
doublereal pmove[3]
Definition at line 28 of file GO2.c.
logical prnton
Definition at line 92 of file GO2.c.
doublereal r__[6]
Definition at line 18 of file GO2.c.
doublereal ra
Definition at line 28 of file GO2.c.
doublereal rc[5]
Definition at line 58 of file GO2.c.
doublereal rc1
Definition at line 28 of file GO2.c.
doublereal rdrn
Definition at line 18 of file GO2.c.
logical refflg
Definition at line 92 of file GO2.c.
logical refmot
Definition at line 92 of file GO2.c.
doublereal refpnt[3]
Definition at line 18 of file GO2.c.
doublereal ri[8]
Definition at line 43 of file GO2.c.
doublereal s[5]
Definition at line 58 of file GO2.c.
doublereal sagl
Definition at line 28 of file GO2.c.
doublereal save[5]
Definition at line 58 of file GO2.c.
doublereal savpar[4]
Definition at line 18 of file GO2.c.
doublereal seg[9]
Definition at line 18 of file GO2.c.
doublereal sfvct[15]
Definition at line 58 of file GO2.c.
doublereal sk[15]
Definition at line 58 of file GO2.c.
doublereal slope
Definition at line 18 of file GO2.c.
doublereal slx[15]
Definition at line 58 of file GO2.c.
doublereal sn[15]
Definition at line 58 of file GO2.c.
doublereal snk[15]
Definition at line 58 of file GO2.c.
doublereal snl[15]
Definition at line 58 of file GO2.c.
doublereal sp[15]
Definition at line 58 of file GO2.c.
doublereal spk[15]
Definition at line 58 of file GO2.c.
doublereal spl[15]
Definition at line 58 of file GO2.c.
doublereal sqroot
Definition at line 18 of file GO2.c.
doublereal stck[5]
Definition at line 75 of file GO2.c.
doublereal stck1[5]
Definition at line 75 of file GO2.c.
doublereal stck2[5]
Definition at line 75 of file GO2.c.
doublereal stckn[5]
Definition at line 75 of file GO2.c.
doublereal strtno
Definition at line 28 of file GO2.c.
logical subflg
Definition at line 92 of file GO2.c.
doublereal surd
Definition at line 28 of file GO2.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 28 of file GO2.c.
logical tabprt
Definition at line 92 of file GO2.c.
doublereal tak[3]
Definition at line 28 of file GO2.c.
doublereal tal[3]
Definition at line 28 of file GO2.c.
doublereal tangl
Definition at line 18 of file GO2.c.
doublereal tanhi[8]
Definition at line 43 of file GO2.c.
doublereal tanlo[8]
Definition at line 43 of file GO2.c.
doublereal tau[5]
Definition at line 58 of file GO2.c.
doublereal tau1[5]
Definition at line 58 of file GO2.c.
doublereal tau2[5]
Definition at line 58 of file GO2.c.
doublereal tcont[9]
Definition at line 43 of file GO2.c.
doublereal te[3]
Definition at line 28 of file GO2.c.
doublereal tee[15]
Definition at line 75 of file GO2.c.
doublereal tek[3]
Definition at line 28 of file GO2.c.
doublereal tel[3]
Definition at line 28 of file GO2.c.
doublereal tem[10]
Definition at line 28 of file GO2.c.
doublereal temp[24]
Definition at line 28 of file GO2.c.
doublereal tes[3]
Definition at line 18 of file GO2.c.
doublereal tew[3]
Definition at line 18 of file GO2.c.
doublereal th[5]
Definition at line 58 of file GO2.c.
doublereal ti[3]
Definition at line 28 of file GO2.c.
doublereal tik[3]
Definition at line 28 of file GO2.c.
doublereal til[3]
Definition at line 28 of file GO2.c.
doublereal tlhit
Definition at line 28 of file GO2.c.
doublereal tlhite[8]
Definition at line 43 of file GO2.c.
doublereal tlinc[9]
Definition at line 43 of file GO2.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file GO2.c.
doublereal tn[15]
Definition at line 58 of file GO2.c.
doublereal tnl[15]
Definition at line 75 of file GO2.c.
doublereal toolht[15]
Definition at line 58 of file GO2.c.
doublereal toolwd[5]
Definition at line 58 of file GO2.c.
doublereal tp[15]
Definition at line 58 of file GO2.c.
doublereal tpk[15]
Definition at line 58 of file GO2.c.
doublereal u1[15]
Definition at line 58 of file GO2.c.
doublereal u1k[15]
Definition at line 58 of file GO2.c.
doublereal u2[3]
Definition at line 18 of file GO2.c.
doublereal umax[8]
Definition at line 43 of file GO2.c.
logical unflag
Definition at line 92 of file GO2.c.
doublereal unn
Definition at line 18 of file GO2.c.
doublereal upp
Definition at line 18 of file GO2.c.
doublereal uvec[3]
Definition at line 18 of file GO2.c.
doublereal v[3]
Definition at line 18 of file GO2.c.
doublereal varble[5]
Definition at line 58 of file GO2.c.
doublereal vint
Definition at line 18 of file GO2.c.
doublereal vl
Definition at line 18 of file GO2.c.
doublereal vndir[15]
Definition at line 58 of file GO2.c.
doublereal vnn
Definition at line 18 of file GO2.c.
doublereal vpp
Definition at line 18 of file GO2.c.
doublereal vt[15]
Definition at line 58 of file GO2.c.
doublereal vtem
Definition at line 28 of file GO2.c.
doublereal z0
Definition at line 84 of file GO2.c.
doublereal z1
Definition at line 84 of file GO2.c.
doublereal z10
Definition at line 84 of file GO2.c.
doublereal z11em1
Definition at line 84 of file GO2.c.
doublereal z12em1
Definition at line 84 of file GO2.c.
doublereal z1e38
Definition at line 84 of file GO2.c.
doublereal z1e6
Definition at line 84 of file GO2.c.
doublereal z1em1
Definition at line 84 of file GO2.c.
doublereal z1em2
Definition at line 84 of file GO2.c.
doublereal z1em3
Definition at line 84 of file GO2.c.
doublereal z1em5
Definition at line 84 of file GO2.c.
doublereal z1em6
Definition at line 84 of file GO2.c.
doublereal z1em7
Definition at line 84 of file GO2.c.
doublereal z1em9
Definition at line 84 of file GO2.c.
doublereal z2
Definition at line 84 of file GO2.c.
doublereal z3
Definition at line 84 of file GO2.c.
doublereal z5
Definition at line 84 of file GO2.c.
doublereal z5em1
Definition at line 84 of file GO2.c.
doublereal z5em6
Definition at line 84 of file GO2.c.
doublereal z6em1
Definition at line 84 of file GO2.c.
doublereal z90
Definition at line 84 of file GO2.c.
doublereal z9em1
Definition at line 84 of file GO2.c.
doublereal z__[5]
Definition at line 58 of file GO2.c.
logical zflag
Definition at line 92 of file GO2.c.
doublereal zl
Definition at line 18 of file GO2.c.
doublereal zl1
Definition at line 18 of file GO2.c.
doublereal zlnorm[3]
Definition at line 18 of file GO2.c.
doublereal zlpnt[3]
Definition at line 18 of file GO2.c.
doublereal zm1
Definition at line 84 of file GO2.c.
struct { ... } znumbr_