My Project: GO.c File Reference
GO.c File Reference
#include "f2c.h"
Macros
#define ldef_1 ldef_
#define ifxcor_1 ifxcor_
Functions
int go_ (doublereal *hmod, doublereal *adress)
Variables
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
static integer c__0 = 0
static integer c__20201 = 20201
Macro Definition Documentation
#define ifxcor_1 ifxcor_
Definition at line 32 of file GO.c.
Referenced by go_().
#define ldef_1 ldef_
Definition at line 22 of file GO.c.
Referenced by go_().
Function Documentation
int go_ (doublereal * hmod, doublereal * adress)
Definition at line 43 of file GO.c.
References aerr_(), apt211_(), apt241_(), c__0, c__20201, go2_(), ifxcor_1, ldef_1, and libsrevert_().
Referenced by xcall_().
 {
     extern /* Subroutine */ int go2_(doublereal *, doublereal *), libsrevert_(
         void), aerr_(integer *, char *, ftnlen);
     static integer idum;
     extern doublereal apt211_(integer *, char *, integer *, ftnlen);
     extern /* Subroutine */ int apt241_(void);
     static doublereal dummy;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*      IF(JDS) CALL APT211(0,'NOCS    ',IDUM) */
     /* Parameter adjustments */
     --adress;
     /* Function Body */
     if (ldef_1.jds) {
     dummy = apt211_(&c__0, "nocs    ", &idum, (ftnlen)8);
     }
 /* -IBM-      CALL APT241 */
     if (ifxcor_1.iaerr == 1) {
     goto L10;
     }
 /* -VAX-ESTABLISH CONDITION HANDLER */
     apt241_();
 L20:
     if (ifxcor_1.ictdef != 0 && ifxcor_1.igoto == 0) {
     aerr_(&c__20201, "GO      ", (ftnlen)8);
     }
     if (ifxcor_1.iaerr == 1) {
     goto L10;
     }
     go2_(hmod, &adress[1]);
     if (ifxcor_1.iaerr == 1) {
     goto L20;
     }
 /* -VAX- REVERT TO DEFAULT CONDITION HANDLER */
 /*   10 CALL LIB$REVERT */
 L10:
     libsrevert_();
     return 0;
 } /* go_ */
Variable Documentation
logical altmlt
Definition at line 18 of file GO.c.
logical bnderr
Definition at line 18 of file GO.c.
logical boundf
Definition at line 18 of file GO.c.
integer c__0 = 0 static
Definition at line 36 of file GO.c.
Referenced by go_().
integer c__20201 = 20201 static
Definition at line 37 of file GO.c.
Referenced by go_().
logical canflg
Definition at line 18 of file GO.c.
integer i3dflg
Definition at line 25 of file GO.c.
integer iaerr
Definition at line 25 of file GO.c.
integer iautps
Definition at line 25 of file GO.c.
integer ibegin
Definition at line 25 of file GO.c.
integer ic
Definition at line 25 of file GO.c.
integer icheck
Definition at line 25 of file GO.c.
integer icl
Definition at line 25 of file GO.c.
integer ics
Definition at line 25 of file GO.c.
integer icscnt
Definition at line 25 of file GO.c.
integer ictdef
Definition at line 25 of file GO.c.
integer icut
Definition at line 25 of file GO.c.
integer ids
Definition at line 25 of file GO.c.
integer ier
Definition at line 25 of file GO.c.
struct { ... } ifxcor_
integer igo
Definition at line 25 of file GO.c.
integer igoto
Definition at line 25 of file GO.c.
integer igoug
Definition at line 25 of file GO.c.
integer igs
Definition at line 25 of file GO.c.
integer inops
Definition at line 25 of file GO.c.
integer ips
Definition at line 25 of file GO.c.
integer ipsdef
Definition at line 25 of file GO.c.
integer ipt1
Definition at line 25 of file GO.c.
integer is
Definition at line 25 of file GO.c.
integer iseg
Definition at line 25 of file GO.c.
integer iseqno
Definition at line 25 of file GO.c.
integer isrch
Definition at line 25 of file GO.c.
integer istrup
Definition at line 25 of file GO.c.
integer it
Definition at line 25 of file GO.c.
integer jbr
Definition at line 25 of file GO.c.
logical jcs
Definition at line 18 of file GO.c.
logical jds
Definition at line 18 of file GO.c.
integer jsw
Definition at line 25 of file GO.c.
struct { ... } ldef_
integer lsv
Definition at line 25 of file GO.c.
integer lsv1
Definition at line 25 of file GO.c.
integer mantax
Definition at line 25 of file GO.c.
integer motmod
Definition at line 25 of file GO.c.
integer msav
Definition at line 25 of file GO.c.
integer mulout
Definition at line 25 of file GO.c.
integer nmbseg
Definition at line 25 of file GO.c.
integer nmpnts
Definition at line 25 of file GO.c.
integer nrec
Definition at line 25 of file GO.c.
integer numax
Definition at line 25 of file GO.c.
integer numcnt
Definition at line 25 of file GO.c.
integer nump
Definition at line 25 of file GO.c.
integer numpt1
Definition at line 25 of file GO.c.
integer numsfs
Definition at line 25 of file GO.c.
integer numsur
Definition at line 25 of file GO.c.
integer nw
Definition at line 25 of file GO.c.
integer nwds
Definition at line 25 of file GO.c.
logical pchlst
Definition at line 18 of file GO.c.
logical prnton
Definition at line 18 of file GO.c.
logical refflg
Definition at line 18 of file GO.c.
logical refmot
Definition at line 18 of file GO.c.
logical subflg
Definition at line 18 of file GO.c.
logical tabprt
Definition at line 18 of file GO.c.
logical unflag
Definition at line 18 of file GO.c.
logical zflag
Definition at line 18 of file GO.c.