My Project: GODLTA.c File Reference
GODLTA.c File Reference
#include "f2c.h"
Macros
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define ldef_1 ldef_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define aercom_1 aercom_
#define dsname_1 dsname_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define atemp (equiv_2)
#define itemp ((integer *)equiv_2)
Functions
int godlta_ (doublereal *vector, doublereal *decmal)
Variables
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
integer iaerfg
} aercom_
struct {
doublereal dsname
integer namsub
} dsname_
static integer c__0 = 0
static integer c__21301 = 21301
static integer c__3 = 3
Macro Definition Documentation
#define aercom_1 aercom_
Definition at line 76 of file GODLTA.c.
Referenced by godlta_().
#define atemp (equiv_2)
Referenced by godlta_().
#define charct_1 charct_
Definition at line 30 of file GODLTA.c.
Referenced by godlta_().
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dsname_1 dsname_
Definition at line 83 of file GODLTA.c.
Referenced by godlta_().
#define fxcor_1 fxcor_
Definition at line 24 of file GODLTA.c.
Referenced by godlta_().
#define ifxcor_1 ifxcor_
Definition at line 54 of file GODLTA.c.
Referenced by godlta_().
#define ishr18_1 ishr18_
Definition at line 62 of file GODLTA.c.
#define itemp ((integer *)equiv_2)
Referenced by godlta_().
#define knumbr_1 knumbr_
Definition at line 70 of file GODLTA.c.
#define ldef_1 ldef_
Definition at line 44 of file GODLTA.c.
Referenced by godlta_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define tlldat_1 tlldat_
Definition at line 37 of file GODLTA.c.
Function Documentation
int godlta_ (doublereal * vector, doublereal * decmal)
Definition at line 95 of file GODLTA.c.
References aercom_1, aerr_(), apt201_(), apt233_(), atemp, bcdf_(), c__0, c__21301, c__3, charct_1, dsname_1, fxcor_1, ifxcor_1, itemp, j, ldef_1, transm_(), and vector.
Referenced by xcall_().
 {
     /* Initialized data */
     static char hgdlta[6] = "GODLTA";
     static char hgoto[4] = "GOTO";
     /* System generated locals */
     static doublereal equiv_2[1];
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer j;
     static doublereal vec[3];
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     extern /* Subroutine */ int apt201_(integer *, char *, ftnlen), apt233_(
         void);
 #define atemp (equiv_2)
     static doublereal tasav[3];
 #define itemp ((integer *)equiv_2)
     extern /* Subroutine */ int transm_(doublereal *, doublereal *, integer *,
          integer *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*     25.   COMMON FOR AERR INFORMATION */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /*     23. DSNAME BLOCK */
 /* ...  CUTTER POSITION IS ADVANCED BY THE VECTOR, OR IS MOVED */
 /* ...  (DECMAL) INCHES ALONG THE TOOL AXIS */
     /* Parameter adjustments */
     --vector;
     /* Function Body */
     if (ifxcor_1.iaerr != 0) {
     goto L1000;
     }
     if (ldef_1.jds) {
     apt201_(&c__0, "NOCS    ", (ftnlen)8);
     }
     if (ifxcor_1.igoto <= 0) {
     goto L1;
     } else {
     goto L2;
     }
 L2:
     if (ifxcor_1.isrch <= 0) {
     goto L3;
     } else {
     goto L1000;
     }
 L3:
     aercom_1.iaerfg = 1;
     aerr_(&c__21301, "GODLTA  ", (ftnlen)8);
     ifxcor_1.iaerr = 0;
     goto L1000;
 L1:
     transm_(vec, &vector[1], &c__3, &c__3, &c__0);
     for (j = 1; j <= 3; ++j) {
     fxcor_1.tek[j - 1] = fxcor_1.te[j - 1];
 /* ...  EITHER DECMAL OR THE VECTOR COMPONENTS WILL BE ZERO */
 /* L10: */
     fxcor_1.te[j - 1] = vec[j - 1] + *decmal * fxcor_1.ta[j - 1];
     }
 /* ...  SET RECORD TYPE CODE FOR CLTAPE WRITER */
 /* L50: */
     s_copy(charct_1.modfer, hgdlta, (ftnlen)6, (ftnlen)6);
     for (j = 1; j <= 3; ++j) {
     tasav[j - 1] = fxcor_1.ta[j - 1];
 /* L55: */
     fxcor_1.ta[j - 1] = 0.f;
     }
     apt233_();
     for (j = 1; j <= 3; ++j) {
     fxcor_1.ta[j - 1] = tasav[j - 1];
 /* L60: */
     fxcor_1.te[j - 1] = fxcor_1.tek[j - 1] + fxcor_1.te[j - 1];
     }
     s_copy(charct_1.modfer, hgoto, (ftnlen)6, (ftnlen)4);
     itemp[0] = bcdf_("NONA", (ftnlen)4);
     itemp[1] = bcdf_("ME  ", (ftnlen)4);
     dsname_1.dsname = *atemp;
     apt233_();
 L1000:
     return 0;
 } /* godlta_ */
Variable Documentation
struct { ... } aercom_
doublereal alp
Definition at line 18 of file GODLTA.c.
logical altmlt
Definition at line 40 of file GODLTA.c.
doublereal ax4[3]
Definition at line 18 of file GODLTA.c.
logical bnderr
Definition at line 40 of file GODLTA.c.
logical boundf
Definition at line 40 of file GODLTA.c.
integer c__0 = 0 static
Definition at line 87 of file GODLTA.c.
Referenced by godlta_().
integer c__21301 = 21301 static
Definition at line 88 of file GODLTA.c.
Referenced by godlta_().
integer c__3 = 3 static
Definition at line 89 of file GODLTA.c.
Referenced by godlta_().
doublereal cagl
Definition at line 18 of file GODLTA.c.
logical canflg
Definition at line 40 of file GODLTA.c.
struct { ... } charct_
doublereal corrad[8]
Definition at line 33 of file GODLTA.c.
doublereal cutdat[7]
Definition at line 18 of file GODLTA.c.
doublereal dpmax
Definition at line 18 of file GODLTA.c.
doublereal dsname
Definition at line 79 of file GODLTA.c.
struct { ... } dsname_
struct { ... } fxcor_
doublereal gamma
Definition at line 18 of file GODLTA.c.
doublereal hi
Definition at line 18 of file GODLTA.c.
integer i3dflg
Definition at line 47 of file GODLTA.c.
integer iaerfg
Definition at line 73 of file GODLTA.c.
integer iaerr
Definition at line 47 of file GODLTA.c.
integer iamdct
Definition at line 57 of file GODLTA.c.
integer iautps
Definition at line 47 of file GODLTA.c.
integer ibegin
Definition at line 47 of file GODLTA.c.
integer ic
Definition at line 47 of file GODLTA.c.
integer icheck
Definition at line 47 of file GODLTA.c.
integer icl
Definition at line 47 of file GODLTA.c.
integer ics
Definition at line 47 of file GODLTA.c.
integer icscnt
Definition at line 47 of file GODLTA.c.
integer ictdef
Definition at line 47 of file GODLTA.c.
integer icut
Definition at line 47 of file GODLTA.c.
integer ids
Definition at line 47 of file GODLTA.c.
integer ier
Definition at line 47 of file GODLTA.c.
struct { ... } ifxcor_
integer igo
Definition at line 47 of file GODLTA.c.
integer igoto
Definition at line 47 of file GODLTA.c.
integer igoug
Definition at line 47 of file GODLTA.c.
integer igs
Definition at line 47 of file GODLTA.c.
integer inops
Definition at line 47 of file GODLTA.c.
integer ipdpl
Definition at line 57 of file GODLTA.c.
integer ips
Definition at line 47 of file GODLTA.c.
integer ipsdef
Definition at line 47 of file GODLTA.c.
integer ipt
Definition at line 57 of file GODLTA.c.
integer ipt1
Definition at line 47 of file GODLTA.c.
integer is
Definition at line 47 of file GODLTA.c.
integer iseg
Definition at line 47 of file GODLTA.c.
integer iseqno
Definition at line 47 of file GODLTA.c.
struct { ... } ishr18_
integer isrch
Definition at line 47 of file GODLTA.c.
integer istrup
Definition at line 47 of file GODLTA.c.
integer it
Definition at line 47 of file GODLTA.c.
integer iws
Definition at line 57 of file GODLTA.c.
integer j10
Definition at line 57 of file GODLTA.c.
integer j12
Definition at line 57 of file GODLTA.c.
integer j13
Definition at line 57 of file GODLTA.c.
integer j54
Definition at line 57 of file GODLTA.c.
integer jbr
Definition at line 47 of file GODLTA.c.
integer jckr
Definition at line 57 of file GODLTA.c.
integer jcnt1
Definition at line 57 of file GODLTA.c.
integer jcnt2
Definition at line 57 of file GODLTA.c.
integer jcnt3
Definition at line 57 of file GODLTA.c.
integer jcpr
Definition at line 57 of file GODLTA.c.
integer jcr
Definition at line 57 of file GODLTA.c.
logical jcs
Definition at line 40 of file GODLTA.c.
integer jdr
Definition at line 57 of file GODLTA.c.
logical jds
Definition at line 40 of file GODLTA.c.
integer jfind
Definition at line 57 of file GODLTA.c.
integer jgr
Definition at line 57 of file GODLTA.c.
integer jmin
Definition at line 57 of file GODLTA.c.
integer jminr
Definition at line 57 of file GODLTA.c.
integer jpr
Definition at line 57 of file GODLTA.c.
integer jpxr
Definition at line 57 of file GODLTA.c.
integer jsw
Definition at line 47 of file GODLTA.c.
integer jtkf
Definition at line 57 of file GODLTA.c.
integer jtr
Definition at line 57 of file GODLTA.c.
integer k0
Definition at line 65 of file GODLTA.c.
integer k1
Definition at line 65 of file GODLTA.c.
integer k10
Definition at line 65 of file GODLTA.c.
integer k1013
Definition at line 65 of file GODLTA.c.
integer k12
Definition at line 65 of file GODLTA.c.
integer k13
Definition at line 65 of file GODLTA.c.
integer k15
Definition at line 65 of file GODLTA.c.
integer k16
Definition at line 65 of file GODLTA.c.
integer k18
Definition at line 65 of file GODLTA.c.
integer k19
Definition at line 65 of file GODLTA.c.
integer k1e4
Definition at line 65 of file GODLTA.c.
integer k1e6
Definition at line 65 of file GODLTA.c.
integer k2
Definition at line 65 of file GODLTA.c.
integer k23
Definition at line 65 of file GODLTA.c.
integer k24
Definition at line 65 of file GODLTA.c.
integer k25
Definition at line 65 of file GODLTA.c.
integer k26
Definition at line 65 of file GODLTA.c.
integer k27
Definition at line 65 of file GODLTA.c.
integer k29
Definition at line 65 of file GODLTA.c.
integer k3
Definition at line 65 of file GODLTA.c.
integer k30
Definition at line 65 of file GODLTA.c.
integer k31
Definition at line 65 of file GODLTA.c.
integer k32
Definition at line 65 of file GODLTA.c.
integer k33
Definition at line 65 of file GODLTA.c.
integer k34
Definition at line 65 of file GODLTA.c.
integer k4
Definition at line 65 of file GODLTA.c.
integer k44
Definition at line 65 of file GODLTA.c.
integer k45
Definition at line 65 of file GODLTA.c.
integer k46
Definition at line 65 of file GODLTA.c.
integer k47
Definition at line 65 of file GODLTA.c.
integer k48
Definition at line 65 of file GODLTA.c.
integer k5
Definition at line 65 of file GODLTA.c.
integer k50
Definition at line 65 of file GODLTA.c.
integer k51
Definition at line 65 of file GODLTA.c.
integer k52
Definition at line 65 of file GODLTA.c.
integer k6
Definition at line 65 of file GODLTA.c.
integer k7
Definition at line 65 of file GODLTA.c.
integer k8
Definition at line 65 of file GODLTA.c.
integer k9
Definition at line 65 of file GODLTA.c.
integer km1
Definition at line 65 of file GODLTA.c.
struct { ... } knumbr_
struct { ... } ldef_
integer lsv
Definition at line 47 of file GODLTA.c.
integer lsv1
Definition at line 47 of file GODLTA.c.
integer mantax
Definition at line 47 of file GODLTA.c.
integer mdic
Definition at line 57 of file GODLTA.c.
char modfer[6]
Definition at line 27 of file GODLTA.c.
integer motmod
Definition at line 47 of file GODLTA.c.
integer msav
Definition at line 47 of file GODLTA.c.
integer mulout
Definition at line 47 of file GODLTA.c.
integer namsub
Definition at line 80 of file GODLTA.c.
integer nmbseg
Definition at line 47 of file GODLTA.c.
integer nmpnts
Definition at line 47 of file GODLTA.c.
integer nrec
Definition at line 47 of file GODLTA.c.
integer numax
Definition at line 47 of file GODLTA.c.
integer numcnt
Definition at line 47 of file GODLTA.c.
integer nump
Definition at line 47 of file GODLTA.c.
integer numpt1
Definition at line 47 of file GODLTA.c.
integer numsfs
Definition at line 47 of file GODLTA.c.
integer numsur
Definition at line 47 of file GODLTA.c.
integer nw
Definition at line 47 of file GODLTA.c.
integer nwds
Definition at line 47 of file GODLTA.c.
logical pchlst
Definition at line 40 of file GODLTA.c.
doublereal pmove[3]
Definition at line 18 of file GODLTA.c.
logical prnton
Definition at line 40 of file GODLTA.c.
doublereal ra
Definition at line 18 of file GODLTA.c.
doublereal rc1
Definition at line 18 of file GODLTA.c.
logical refflg
Definition at line 40 of file GODLTA.c.
logical refmot
Definition at line 40 of file GODLTA.c.
doublereal ri[8]
Definition at line 33 of file GODLTA.c.
doublereal sagl
Definition at line 18 of file GODLTA.c.
doublereal strtno
Definition at line 18 of file GODLTA.c.
logical subflg
Definition at line 40 of file GODLTA.c.
doublereal surd
Definition at line 18 of file GODLTA.c.
doublereal ta[3]
Definition at line 18 of file GODLTA.c.
logical tabprt
Definition at line 40 of file GODLTA.c.
doublereal tak[3]
Definition at line 18 of file GODLTA.c.
doublereal tal[3]
Definition at line 18 of file GODLTA.c.
doublereal tanhi[8]
Definition at line 33 of file GODLTA.c.
doublereal tanlo[8]
Definition at line 33 of file GODLTA.c.
doublereal tcont[9]
Definition at line 33 of file GODLTA.c.
doublereal te[3]
Definition at line 18 of file GODLTA.c.
doublereal tek[3]
Definition at line 18 of file GODLTA.c.
doublereal tel[3]
Definition at line 18 of file GODLTA.c.
doublereal tem[10]
Definition at line 18 of file GODLTA.c.
doublereal temp[24]
Definition at line 18 of file GODLTA.c.
doublereal ti[3]
Definition at line 18 of file GODLTA.c.
doublereal tik[3]
Definition at line 18 of file GODLTA.c.
doublereal til[3]
Definition at line 18 of file GODLTA.c.
doublereal tlhit
Definition at line 18 of file GODLTA.c.
doublereal tlhite[8]
Definition at line 33 of file GODLTA.c.
doublereal tlinc[9]
Definition at line 33 of file GODLTA.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 18 of file GODLTA.c.
doublereal umax[8]
Definition at line 33 of file GODLTA.c.
logical unflag
Definition at line 40 of file GODLTA.c.
doublereal vtem
Definition at line 18 of file GODLTA.c.
logical zflag
Definition at line 40 of file GODLTA.c.