My Project: GOTOPN.c File Reference
GOTOPN.c File Reference
#include "f2c.h"
Macros
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define znumbr_1 znumbr_
#define ifxcor_1 ifxcor_
#define knumbr_1 knumbr_
#define _BLNK__1 _BLNK__
#define can ((doublereal *)&_BLNK__1 + 40)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int gotopn_ (doublereal *pat, integer *iarg1, integer *iarg2, integer *iarg3, integer *iarg4, doublereal *omtlst, doublereal *avdlst)
Variables
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
doublereal com [36000]
} _BLNK__
static integer c__2 = 2
static integer c__45 = 45
static integer c__46 = 46
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 69 of file GOTOPN.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Referenced by gotopn_().
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define charct_1 charct_
Definition at line 30 of file GOTOPN.c.
Referenced by gotopn_().
#define cosl ((doublereal *)&tlldat_1 + 16)
#define fxcor_1 fxcor_
Definition at line 24 of file GOTOPN.c.
Referenced by gotopn_().
#define ifxcor_1 ifxcor_
Definition at line 55 of file GOTOPN.c.
Referenced by gotopn_().
#define knumbr_1 knumbr_
Definition at line 63 of file GOTOPN.c.
Referenced by gotopn_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define tlldat_1 tlldat_
Definition at line 37 of file GOTOPN.c.
#define znumbr_1 znumbr_
Definition at line 45 of file GOTOPN.c.
Referenced by gotopn_().
Function Documentation
int gotopn_ (doublereal * pat, integer * iarg1, integer * iarg2, integer * iarg3, integer * iarg4, doublereal * omtlst, doublereal * avdlst)
Definition at line 116 of file GOTOPN.c.
References apt094_(), apt202_(), apt233_(), apt299_(), bcanon, c__2, c__45, c__46, charct_1, ckdef_(), error_(), fxcor_1, hon, i__, ifxcor_1, j, knumbr_1, n, no, npat_(), pat, pt, and znumbr_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static char hnomor[6] = "NOMORE";
     static char hgoto[4] = "GOTO";
     static char hcycle[5] = "CYCLE";
     static char hon[2] = "ON";
     /* System generated locals */
     integer i__1, i__2;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, j, n;
     static doublereal pt;
     static integer no;
 #define can ((doublereal *)&_BLNK__1 + 40)
     static doublereal res[3];
     static integer ncol;
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static integer jsav;
     extern /* Subroutine */ int npat_(doublereal *, integer *), apt202_(
         doublereal *, integer *), apt233_(void), apt094_(integer *,
         doublereal *, doublereal *);
     static integer npat1, isva2, isva3;
     extern /* Subroutine */ int apt299_(integer *, char *, integer *, char *,
         ftnlen, ftnlen);
     extern logical ckdef_(doublereal *);
     static doublereal avddn;
 #define canon ((doublereal *)&_BLNK__1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     static doublereal avdup;
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
     static integer iparg3;
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     static doublereal avdend;
     static integer ncolmd;
     static doublereal tmpsav;
     static integer iavtyp;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
     /* Parameter adjustments */
     avdlst -= 4;
     omtlst -= 3;
     --pat;
     /* Function Body */
 /*          MOVE THE EXTERNAL CANONICAL FORM TO BCANON */
     if (ckdef_(&pat[1])) {
     goto L999;
     }
     apt094_(&c__2, &pat[1], bcanon);
     if (ckdef_(&pat[1])) {
     goto L999;
     }
 /*          DETERMINE NUMBER OF POINTS IN PATERN */
     n = (integer) (bcanon[3] + znumbr_1.z1em5);
 /*          IF ZIGZAG IS TO APPLY, PATERN MUST BE GRID */
     isva2 = *iarg2;
     if (isva2 == knumbr_1.k0) {
     goto L10;
     }
     if (bcanon[1] == znumbr_1.z3) {
     goto L5;
     }
     error_(&c__45, "GOTOPN  ", (ftnlen)8);
     isva2 = knumbr_1.k0;
     goto L10;
 /*          DETERMINE NUMBER OF POINTS IN FIRST SIDE OF GRID PATERN */
 L5:
     npat1 = (integer) (bcanon[6] + znumbr_1.z1em5);
 /*          IF OMTLST HAS ENTRIES, PUT THEM IN ORDER */
 L10:
     isva3 = *iarg3;
     if (isva3 < 1000) {
     goto L11;
     }
     isva3 = -(isva3 - 1000);
 L11:
     if (isva3 < 0) {
     goto L12;
     } else if (isva3 == 0) {
     goto L20;
     } else {
     goto L14;
     }
 L12:
     iparg3 = -isva3;
     goto L16;
 L14:
     iparg3 = isva3;
 L16:
     i__1 = iparg3;
     for (i__ = 1; i__ <= i__1; ++i__) {
     if (omtlst[(i__ << 1) + 1] <= omtlst[(i__ << 1) + 2]) {
         goto L18;
     }
     tmpsav = omtlst[(i__ << 1) + 1];
     omtlst[(i__ << 1) + 1] = omtlst[(i__ << 1) + 2];
     omtlst[(i__ << 1) + 2] = tmpsav;
 L18:
     ;
     }
 /*          CHECK FOR AVOID */
 L20:
     if (*iarg4 == knumbr_1.k0) {
     goto L70;
     }
 /*          PUT AVDLST ENTRIES IN ORDER */
     i__1 = *iarg4;
     for (i__ = 1; i__ <= i__1; ++i__) {
     if (avdlst[i__ * 3 + 2] < avdlst[i__ * 3 + 3]) {
         goto L40;
     }
     if (avdlst[i__ * 3 + 3] == znumbr_1.z0) {
         goto L22;
     }
 /*          REVERSE ORDER */
     tmpsav = avdlst[i__ * 3 + 2];
     avdlst[i__ * 3 + 2] = avdlst[i__ * 3 + 3];
     avdlst[i__ * 3 + 3] = tmpsav;
     goto L40;
 /*          INSERT AS END POINT THE NEXT NON-OMITTED POINT */
 L22:
     avdlst[i__ * 3 + 3] = avdlst[i__ * 3 + 2] + znumbr_1.z1;
     pt = (doublereal) n;
     if (isva3 < 0) {
         goto L24;
     } else if (isva3 == 0) {
         goto L60;
     } else {
         goto L32;
     }
 L24:
     i__2 = iparg3;
     for (j = 1; j <= i__2; ++j) {
         if (avdlst[i__ * 3 + 3] >= omtlst[(j << 1) + 1] && avdlst[i__ * 3
             + 3] <= omtlst[(j << 1) + 2]) {
         goto L46;
         }
 /* L26: */
     }
     if (avdlst[i__ * 3 + 3] >= pt) {
         goto L1000;
     }
     avdlst[i__ * 3 + 3] += znumbr_1.z1;
     goto L24;
 L32:
     i__2 = iparg3;
     for (j = 1; j <= i__2; ++j) {
         if (avdlst[i__ * 3 + 3] >= omtlst[(j << 1) + 1] && avdlst[i__ * 3
             + 3] <= omtlst[(j << 1) + 2]) {
         goto L38;
         }
 /* L36: */
     }
     goto L54;
 L38:
     if (avdlst[i__ * 3 + 3] >= pt) {
         goto L1000;
     }
     avdlst[i__ * 3 + 3] += znumbr_1.z1;
     goto L32;
 /*          CHECK FOR OMITTED FIRST OR END POINT IN AVOID STRING */
 L40:
     if (isva3 < 0) {
         goto L42;
     } else if (isva3 == 0) {
         goto L60;
     } else {
         goto L50;
     }
 L42:
     i__2 = iparg3;
     for (j = 1; j <= i__2; ++j) {
         if (avdlst[i__ * 3 + 3] >= omtlst[(j << 1) + 1] && avdlst[i__ * 3
             + 3] <= omtlst[(j << 1) + 2]) {
         goto L46;
         }
 /* L44: */
     }
     goto L1000;
 L46:
     i__2 = iparg3;
     for (j = 1; j <= i__2; ++j) {
         if (avdlst[i__ * 3 + 2] >= omtlst[(j << 1) + 1] && avdlst[i__ * 3
             + 2] <= omtlst[(j << 1) + 2]) {
         goto L60;
         }
 /* L48: */
     }
     goto L1000;
 L50:
     i__2 = iparg3;
     for (j = 1; j <= i__2; ++j) {
         if (avdlst[i__ * 3 + 3] >= omtlst[(j << 1) + 1] && avdlst[i__ * 3
             + 3] <= omtlst[(j << 1) + 2]) {
         goto L1000;
         }
 /* L52: */
     }
 L54:
     i__2 = iparg3;
     for (j = 1; j <= i__2; ++j) {
         if (avdlst[i__ * 3 + 2] >= omtlst[(j << 1) + 1] && avdlst[i__ * 3
             + 2] <= omtlst[(j << 1) + 2]) {
         goto L1000;
         }
 /* L58: */
     }
 L60:
     ;
     }
 L70:
     ifxcor_1.iaerr = 0;
     apt202_(&pat[1], &c__2);
     s_copy(charct_1.modfer, hgoto, (ftnlen)6, (ftnlen)4);
 /*          INITIALIZE FOR AVOID */
     iavtyp = knumbr_1.k1;
     avdend = znumbr_1.z0;
     jsav = knumbr_1.k0;
 /* L100: */
     i__1 = n;
     for (i__ = 1; i__ <= i__1; ++i__) {
     no = i__;
 /*          CHECK FOR INVERSE */
     if (*iarg1 == knumbr_1.k0) {
         goto L105;
     }
     no = n - i__ + knumbr_1.k1;
 /*          CHECK FOR ZIGZAG */
 L105:
     if (isva2 == knumbr_1.k0) {
         goto L110;
     }
     ncol = (no - knumbr_1.k1) / npat1;
     ncolmd = ncol % knumbr_1.k2;
     if (ncolmd == knumbr_1.k1 && *iarg1 == knumbr_1.k0 || ncolmd ==
         knumbr_1.k0 && *iarg1 == knumbr_1.k1) {
         no = npat1 * (knumbr_1.k2 * ncol + knumbr_1.k1) - no +
             knumbr_1.k1;
     }
 L110:
     pt = (doublereal) no;
 /*          CHECK FOR OMIT OR RETAIN */
     if (isva3 < 0) {
         goto L140;
     } else if (isva3 == 0) {
         goto L160;
     } else {
         goto L120;
     }
 /*          OMIT */
 L120:
     i__2 = iparg3;
     for (j = 1; j <= i__2; ++j) {
         if (pt >= omtlst[(j << 1) + 1] && pt <= omtlst[(j << 1) + 2]) {
         goto L900;
         }
 /* L124: */
     }
     goto L160;
 /*          RETAIN */
 L140:
     i__2 = iparg3;
     for (j = 1; j <= i__2; ++j) {
         if (pt >= omtlst[(j << 1) + 1] && pt <= omtlst[(j << 1) + 2]) {
         goto L160;
         }
 /* L144: */
     }
     goto L900;
 /*          CHECK FOR AVOID */
 L160:
     if (*iarg4 == knumbr_1.k0) {
         goto L200;
     }
 /*          AVOID */
     if (avdend != znumbr_1.z0) {
         goto L170;
     }
 /*          LOOK FOR FIRST POINT */
     i__2 = *iarg4;
     for (j = 1; j <= i__2; ++j) {
         if (pt != avdlst[j * 3 + 2]) {
         goto L163;
         }
         avdend = avdlst[j * 3 + 3];
 L162:
         jsav = j;
         avdup = avdlst[j * 3 + 1];
         avddn = avdlst[j * 3 + 1];
         iavtyp = knumbr_1.k2;
         goto L200;
 L163:
         if (pt != avdlst[j * 3 + 3]) {
         goto L164;
         }
         avdend = avdlst[j * 3 + 2];
         goto L162;
 L164:
         ;
     }
     goto L200;
 /*          LOOK FOR END POINT */
 L170:
     if (pt == avdend) {
         goto L180;
     }
     iavtyp = knumbr_1.k3;
     goto L200;
 /*          IS THIS END POINT A FIRST POINT OF NEXT STRING */
 L180:
     i__2 = *iarg4;
     for (j = 1; j <= i__2; ++j) {
         if (pt != avdlst[j * 3 + 2]) {
         goto L183;
         }
         if (j == jsav) {
         goto L184;
         }
         avdend = avdlst[j * 3 + 3];
 L182:
         avdup = avdlst[j * 3 + 1];
         iavtyp = knumbr_1.k3;
         goto L200;
 L183:
         if (pt != avdlst[j * 3 + 3] || j == jsav) {
         goto L184;
         }
         avdend = avdlst[j * 3 + 2];
         goto L182;
 L184:
         ;
     }
     jsav = knumbr_1.k0;
     avdend = znumbr_1.z0;
     iavtyp = knumbr_1.k4;
 /*          CALL NPAT TO DETERMINE COORDINATES OF POINT */
 L200:
     npat_(res, &no);
 /*          BRANCH ON IAVTYP */
 /*             1-AVOID DOES NOT APPLY     2-FIRST POINT IN AVOID STRING */
 /*             3-INTERMEDIATE POINT       4-END POINT */
     switch (iavtyp) {
         case 1:  goto L240;
         case 2:  goto L240;
         case 3:  goto L220;
         case 4:  goto L210;
     }
 L210:
     iavtyp = knumbr_1.k1;
 L220:
     for (j = 1; j <= 3; ++j) {
         fxcor_1.tek[j - 1] = fxcor_1.te[j - 1];
 /* L224: */
         fxcor_1.te[j - 1] = res[j - 1];
     }
     fxcor_1.te[2] += avddn;
     apt233_();
     apt299_(&knumbr_1.k1, hcycle, &knumbr_1.k2, hon, (ftnlen)5, (ftnlen)2)
         ;
     avddn = avdup;
 L240:
     for (j = 1; j <= 3; ++j) {
         fxcor_1.tek[j - 1] = fxcor_1.te[j - 1];
 /* L244: */
         fxcor_1.te[j - 1] = res[j - 1];
     }
     apt233_();
     if (iavtyp == knumbr_1.k1) {
         goto L900;
     }
     apt299_(&knumbr_1.k1, hcycle, &knumbr_1.k2, hnomor, (ftnlen)5, (
         ftnlen)6);
     for (j = 1; j <= 3; ++j) {
         fxcor_1.tek[j - 1] = fxcor_1.te[j - 1];
 /* L250: */
         fxcor_1.te[j - 1] = res[j - 1];
     }
     fxcor_1.te[2] += avdup;
     apt233_();
 L900:
     ;
     }
     ifxcor_1.igoto = 0;
 L999:
     return 0;
 /*          OMIT HAS BEEN APPLIED (OR RETAIN HAS NOT BEEN APPLIED) */
 /*             TO A FIRST OR AN END POINT OF AN AVOID STRING */
 L1000:
     error_(&c__46, "GOTOPN  ", (ftnlen)8);
     goto L999;
 } /* gotopn_ */
Variable Documentation
struct { ... } _BLNK__
doublereal alp
Definition at line 18 of file GOTOPN.c.
doublereal ax4[3]
Definition at line 18 of file GOTOPN.c.
integer c__2 = 2 static
Definition at line 73 of file GOTOPN.c.
Referenced by gotopn_().
integer c__45 = 45 static
Definition at line 74 of file GOTOPN.c.
Referenced by gotopn_().
integer c__46 = 46 static
Definition at line 75 of file GOTOPN.c.
Referenced by gotopn_().
doublereal cagl
Definition at line 18 of file GOTOPN.c.
struct { ... } charct_
doublereal com[36000]
Definition at line 66 of file GOTOPN.c.
doublereal corrad[8]
Definition at line 33 of file GOTOPN.c.
doublereal cutdat[7]
Definition at line 18 of file GOTOPN.c.
doublereal degrad
Definition at line 40 of file GOTOPN.c.
doublereal dpmax
Definition at line 18 of file GOTOPN.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 18 of file GOTOPN.c.
doublereal hi
Definition at line 18 of file GOTOPN.c.
integer i3dflg
Definition at line 48 of file GOTOPN.c.
integer iaerr
Definition at line 48 of file GOTOPN.c.
integer iautps
Definition at line 48 of file GOTOPN.c.
integer ibegin
Definition at line 48 of file GOTOPN.c.
integer ic
Definition at line 48 of file GOTOPN.c.
integer icheck
Definition at line 48 of file GOTOPN.c.
integer icl
Definition at line 48 of file GOTOPN.c.
integer ics
Definition at line 48 of file GOTOPN.c.
integer icscnt
Definition at line 48 of file GOTOPN.c.
integer ictdef
Definition at line 48 of file GOTOPN.c.
integer icut
Definition at line 48 of file GOTOPN.c.
integer ids
Definition at line 48 of file GOTOPN.c.
integer ier
Definition at line 48 of file GOTOPN.c.
struct { ... } ifxcor_
integer igo
Definition at line 48 of file GOTOPN.c.
integer igoto
Definition at line 48 of file GOTOPN.c.
integer igoug
Definition at line 48 of file GOTOPN.c.
integer igs
Definition at line 48 of file GOTOPN.c.
integer inops
Definition at line 48 of file GOTOPN.c.
integer ips
Definition at line 48 of file GOTOPN.c.
integer ipsdef
Definition at line 48 of file GOTOPN.c.
integer ipt1
Definition at line 48 of file GOTOPN.c.
integer is
Definition at line 48 of file GOTOPN.c.
integer iseg
Definition at line 48 of file GOTOPN.c.
integer iseqno
Definition at line 48 of file GOTOPN.c.
integer isrch
Definition at line 48 of file GOTOPN.c.
integer istrup
Definition at line 48 of file GOTOPN.c.
integer it
Definition at line 48 of file GOTOPN.c.
integer jbr
Definition at line 48 of file GOTOPN.c.
integer jsw
Definition at line 48 of file GOTOPN.c.
integer k0
Definition at line 58 of file GOTOPN.c.
integer k1
Definition at line 58 of file GOTOPN.c.
integer k10
Definition at line 58 of file GOTOPN.c.
integer k1013
Definition at line 58 of file GOTOPN.c.
integer k12
Definition at line 58 of file GOTOPN.c.
integer k13
Definition at line 58 of file GOTOPN.c.
integer k15
Definition at line 58 of file GOTOPN.c.
integer k16
Definition at line 58 of file GOTOPN.c.
integer k18
Definition at line 58 of file GOTOPN.c.
integer k19
Definition at line 58 of file GOTOPN.c.
integer k1e4
Definition at line 58 of file GOTOPN.c.
integer k1e6
Definition at line 58 of file GOTOPN.c.
integer k2
Definition at line 58 of file GOTOPN.c.
integer k23
Definition at line 58 of file GOTOPN.c.
integer k24
Definition at line 58 of file GOTOPN.c.
integer k25
Definition at line 58 of file GOTOPN.c.
integer k26
Definition at line 58 of file GOTOPN.c.
integer k27
Definition at line 58 of file GOTOPN.c.
integer k29
Definition at line 58 of file GOTOPN.c.
integer k3
Definition at line 58 of file GOTOPN.c.
integer k30
Definition at line 58 of file GOTOPN.c.
integer k31
Definition at line 58 of file GOTOPN.c.
integer k32
Definition at line 58 of file GOTOPN.c.
integer k33
Definition at line 58 of file GOTOPN.c.
integer k34
Definition at line 58 of file GOTOPN.c.
integer k4
Definition at line 58 of file GOTOPN.c.
integer k44
Definition at line 58 of file GOTOPN.c.
integer k45
Definition at line 58 of file GOTOPN.c.
integer k46
Definition at line 58 of file GOTOPN.c.
integer k47
Definition at line 58 of file GOTOPN.c.
integer k48
Definition at line 58 of file GOTOPN.c.
integer k5
Definition at line 58 of file GOTOPN.c.
integer k50
Definition at line 58 of file GOTOPN.c.
integer k51
Definition at line 58 of file GOTOPN.c.
integer k52
Definition at line 58 of file GOTOPN.c.
integer k6
Definition at line 58 of file GOTOPN.c.
integer k7
Definition at line 58 of file GOTOPN.c.
integer k8
Definition at line 58 of file GOTOPN.c.
integer k9
Definition at line 58 of file GOTOPN.c.
integer km1
Definition at line 58 of file GOTOPN.c.
struct { ... } knumbr_
integer lsv
Definition at line 48 of file GOTOPN.c.
integer lsv1
Definition at line 48 of file GOTOPN.c.
integer mantax
Definition at line 48 of file GOTOPN.c.
char modfer[6]
Definition at line 27 of file GOTOPN.c.
integer motmod
Definition at line 48 of file GOTOPN.c.
integer msav
Definition at line 48 of file GOTOPN.c.
integer mulout
Definition at line 48 of file GOTOPN.c.
integer nmbseg
Definition at line 48 of file GOTOPN.c.
integer nmpnts
Definition at line 48 of file GOTOPN.c.
integer nrec
Definition at line 48 of file GOTOPN.c.
integer numax
Definition at line 48 of file GOTOPN.c.
integer numcnt
Definition at line 48 of file GOTOPN.c.
integer nump
Definition at line 48 of file GOTOPN.c.
integer numpt1
Definition at line 48 of file GOTOPN.c.
integer numsfs
Definition at line 48 of file GOTOPN.c.
integer numsur
Definition at line 48 of file GOTOPN.c.
integer nw
Definition at line 48 of file GOTOPN.c.
integer nwds
Definition at line 48 of file GOTOPN.c.
doublereal pi
Definition at line 40 of file GOTOPN.c.
doublereal pmove[3]
Definition at line 18 of file GOTOPN.c.
doublereal ra
Definition at line 18 of file GOTOPN.c.
doublereal rc1
Definition at line 18 of file GOTOPN.c.
doublereal ri[8]
Definition at line 33 of file GOTOPN.c.
doublereal sagl
Definition at line 18 of file GOTOPN.c.
doublereal strtno
Definition at line 18 of file GOTOPN.c.
doublereal surd
Definition at line 18 of file GOTOPN.c.
doublereal ta[3]
Definition at line 18 of file GOTOPN.c.
doublereal tak[3]
Definition at line 18 of file GOTOPN.c.
doublereal tal[3]
Definition at line 18 of file GOTOPN.c.
doublereal tanhi[8]
Definition at line 33 of file GOTOPN.c.
doublereal tanlo[8]
Definition at line 33 of file GOTOPN.c.
doublereal tcont[9]
Definition at line 33 of file GOTOPN.c.
doublereal te[3]
Definition at line 18 of file GOTOPN.c.
doublereal tek[3]
Definition at line 18 of file GOTOPN.c.
doublereal tel[3]
Definition at line 18 of file GOTOPN.c.
doublereal tem[10]
Definition at line 18 of file GOTOPN.c.
doublereal temp[24]
Definition at line 18 of file GOTOPN.c.
doublereal ti[3]
Definition at line 18 of file GOTOPN.c.
doublereal tik[3]
Definition at line 18 of file GOTOPN.c.
doublereal til[3]
Definition at line 18 of file GOTOPN.c.
doublereal tlhit
Definition at line 18 of file GOTOPN.c.
doublereal tlhite[8]
Definition at line 33 of file GOTOPN.c.
doublereal tlinc[9]
Definition at line 33 of file GOTOPN.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 18 of file GOTOPN.c.
doublereal umax[8]
Definition at line 33 of file GOTOPN.c.
doublereal vtem
Definition at line 18 of file GOTOPN.c.
doublereal z0
Definition at line 40 of file GOTOPN.c.
doublereal z1
Definition at line 40 of file GOTOPN.c.
doublereal z10
Definition at line 40 of file GOTOPN.c.
doublereal z11em1
Definition at line 40 of file GOTOPN.c.
doublereal z12em1
Definition at line 40 of file GOTOPN.c.
doublereal z1e38
Definition at line 40 of file GOTOPN.c.
doublereal z1e6
Definition at line 40 of file GOTOPN.c.
doublereal z1em1
Definition at line 40 of file GOTOPN.c.
doublereal z1em2
Definition at line 40 of file GOTOPN.c.
doublereal z1em3
Definition at line 40 of file GOTOPN.c.
doublereal z1em5
Definition at line 40 of file GOTOPN.c.
doublereal z1em6
Definition at line 40 of file GOTOPN.c.
doublereal z1em7
Definition at line 40 of file GOTOPN.c.
doublereal z1em9
Definition at line 40 of file GOTOPN.c.
doublereal z2
Definition at line 40 of file GOTOPN.c.
doublereal z3
Definition at line 40 of file GOTOPN.c.
doublereal z5
Definition at line 40 of file GOTOPN.c.
doublereal z5em1
Definition at line 40 of file GOTOPN.c.
doublereal z5em6
Definition at line 40 of file GOTOPN.c.
doublereal z6em1
Definition at line 40 of file GOTOPN.c.
doublereal z90
Definition at line 40 of file GOTOPN.c.
doublereal z9em1
Definition at line 40 of file GOTOPN.c.
doublereal zm1
Definition at line 40 of file GOTOPN.c.
struct { ... } znumbr_