My Project: GSURF.c File Reference
GSURF.c File Reference
#include "f2c.h"
Macros
#define ldef_1 ldef_
#define knumbr_1 knumbr_
Functions
int gsurf_ (doublereal *coebuf, doublereal *canon, integer *mode, integer *isiz, logical *errflg)
Variables
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
Macro Definition Documentation
#define knumbr_1 knumbr_
Definition at line 30 of file GSURF.c.
Referenced by gsurf_().
#define ldef_1 ldef_
Definition at line 22 of file GSURF.c.
Referenced by gsurf_().
Function Documentation
int gsurf_ (doublereal * coebuf, doublereal * canon, integer * mode, integer * isiz, logical * errflg)
Definition at line 70 of file GSURF.c.
References canon, gcircl_(), gcone_(), gcyl_(), gplane_(), gquad_(), gspher_(), i__, ir, knumbr_1, ldef_1, m, refsrf, and transf_().
Referenced by apt104_().
 {
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__, m, ir;
     extern /* Subroutine */ int gcyl_(doublereal *, doublereal *), gcone_(
         doublereal *, doublereal *), gquad_(doublereal *, doublereal *),
         gcircl_(doublereal *, doublereal *), gplane_(doublereal *,
         doublereal *);
     static doublereal refsrf[10];
     extern /* Subroutine */ int gspher_(doublereal *, doublereal *), transf_(
         doublereal *, doublereal *, integer *, integer *, integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --canon;
     --coebuf;
     /* Function Body */
     i__1 = *isiz;
     for (i__ = 1; i__ <= i__1; ++i__) {
 /* L5: */
     refsrf[i__ - 1] = canon[i__];
     }
     *errflg = FALSE_;
 /*      MODE = 1   2   3   4   5   6   7   8   9 10  11  12  13  14  15 */
     switch (*mode) {
     case 1:  goto L101;
     case 2:  goto L101;
     case 3:  goto L103;
     case 4:  goto L104;
     case 5:  goto L105;
     case 6:  goto L106;
     case 7:  goto L106;
     case 8:  goto L106;
     case 9:  goto L109;
     case 10:  goto L106;
     case 11:  goto L130;
     case 12:  goto L130;
     case 13:  goto L130;
     case 14:  goto L106;
     case 15:  goto L130;
     case 16:  goto L130;
     case 17:  goto L130;
     case 18:  goto L130;
     case 19:  goto L130;
     case 20:  goto L130;
     case 21:  goto L130;
     case 22:  goto L130;
     case 23:  goto L130;
     case 24:  goto L130;
     case 25:  goto L130;
     case 26:  goto L130;
     }
 /*      MODE = 16 17  18  19  20  21  22  23  24  25  26 */
 /* ...  A LINE OR PLANE. */
 L10:
     gplane_(refsrf, &coebuf[1]);
     goto L100;
 /* ...  A CYLINDER. */
 L30:
     gcyl_(refsrf, &coebuf[1]);
     goto L100;
 /* ...  A CIRCLE. */
 L40:
     gcircl_(refsrf, &coebuf[1]);
     goto L100;
 /* ...  A SPHERE. */
 L50:
     gspher_(refsrf, &coebuf[1]);
     goto L100;
 /* ...  A HYPERBOLA, LCONIC, ELLIPSE, GCONIC, OR QUADRIC. */
 L60:
     gquad_(refsrf, &coebuf[1]);
     goto L100;
 /* ...  A CONE. */
 L90:
     gcone_(refsrf, &coebuf[1]);
 L100:
     return 0;
 /* ...  TRANSFORM TO LOCAL COORDINATE SYSTEM IF REFSYS IN EFFECT. */
 L101:
     ir = knumbr_1.k4;
     m = 0;
     goto L110;
 L103:
     ir = knumbr_1.k5;
     m = 1;
     goto L110;
 L104:
     ir = knumbr_1.k5;
     m = 2;
     goto L110;
 L105:
     ir = knumbr_1.k2;
     m = 3;
     goto L110;
 L106:
     ir = knumbr_1.k1;
     m = 4;
     goto L110;
 L109:
     ir = knumbr_1.k5;
     m = 5;
 L110:
     if (ldef_1.refflg) {
     transf_(refsrf, &canon[1], &ir, isiz, &knumbr_1.k0);
     }
     switch (m) {
     case 0: goto L10;
     case 1: goto L30;
     case 2: goto L40;
     case 3: goto L50;
     case 4: goto L60;
     case 5: goto L90;
     }
 L130:
     *errflg = TRUE_;
     goto L100;
 } /* gsurf_ */
Variable Documentation
logical altmlt
Definition at line 18 of file GSURF.c.
logical bnderr
Definition at line 18 of file GSURF.c.
logical boundf
Definition at line 18 of file GSURF.c.
logical canflg
Definition at line 18 of file GSURF.c.
logical jcs
Definition at line 18 of file GSURF.c.
logical jds
Definition at line 18 of file GSURF.c.
integer k0
Definition at line 25 of file GSURF.c.
integer k1
Definition at line 25 of file GSURF.c.
integer k10
Definition at line 25 of file GSURF.c.
integer k1013
Definition at line 25 of file GSURF.c.
integer k12
Definition at line 25 of file GSURF.c.
integer k13
Definition at line 25 of file GSURF.c.
integer k15
Definition at line 25 of file GSURF.c.
integer k16
Definition at line 25 of file GSURF.c.
integer k18
Definition at line 25 of file GSURF.c.
integer k19
Definition at line 25 of file GSURF.c.
integer k1e4
Definition at line 25 of file GSURF.c.
integer k1e6
Definition at line 25 of file GSURF.c.
integer k2
Definition at line 25 of file GSURF.c.
integer k23
Definition at line 25 of file GSURF.c.
integer k24
Definition at line 25 of file GSURF.c.
integer k25
Definition at line 25 of file GSURF.c.
integer k26
Definition at line 25 of file GSURF.c.
integer k27
Definition at line 25 of file GSURF.c.
integer k29
Definition at line 25 of file GSURF.c.
integer k3
Definition at line 25 of file GSURF.c.
integer k30
Definition at line 25 of file GSURF.c.
integer k31
Definition at line 25 of file GSURF.c.
integer k32
Definition at line 25 of file GSURF.c.
integer k33
Definition at line 25 of file GSURF.c.
integer k34
Definition at line 25 of file GSURF.c.
integer k4
Definition at line 25 of file GSURF.c.
integer k44
Definition at line 25 of file GSURF.c.
integer k45
Definition at line 25 of file GSURF.c.
integer k46
Definition at line 25 of file GSURF.c.
integer k47
Definition at line 25 of file GSURF.c.
integer k48
Definition at line 25 of file GSURF.c.
integer k5
Definition at line 25 of file GSURF.c.
integer k50
Definition at line 25 of file GSURF.c.
integer k51
Definition at line 25 of file GSURF.c.
integer k52
Definition at line 25 of file GSURF.c.
integer k6
Definition at line 25 of file GSURF.c.
integer k7
Definition at line 25 of file GSURF.c.
integer k8
Definition at line 25 of file GSURF.c.
integer k9
Definition at line 25 of file GSURF.c.
integer km1
Definition at line 25 of file GSURF.c.
struct { ... } knumbr_
struct { ... } ldef_
logical pchlst
Definition at line 18 of file GSURF.c.
logical prnton
Definition at line 18 of file GSURF.c.
logical refflg
Definition at line 18 of file GSURF.c.
logical refmot
Definition at line 18 of file GSURF.c.
logical subflg
Definition at line 18 of file GSURF.c.
logical tabprt
Definition at line 18 of file GSURF.c.
logical unflag
Definition at line 18 of file GSURF.c.
logical zflag
Definition at line 18 of file GSURF.c.