My Project: HELP.c File Reference
HELP.c File Reference
#include "f2c.h"
Functions
int help_ (void)
Function Documentation
int help_ (void)
Definition at line 31 of file HELP.c.
References i__, x, and y.
Referenced by apt301_(), apt314_(), eread_(), icmprs_(), init_(), input_(), intrp_(), larges_(), lib_(), maclbl_(), macrec_(), match_(), mcxtrn_(), mnproc_(), page_(), set_(), and xcanon_().
 {
     static integer i__;
     static real x, y[1];
 /* ...     CATASTROPHIC FAILURE */
 /* ...     PRODUCE EXECUTION FAILURE SO AS TO OBTAIN AUTOMATIC TRACE-BACK */
     for (i__ = 100000; i__ <= 1000000; i__ += 10) {
     x = y[i__ - 1];
 /* L10: */
     y[i__ - 1] = x;
     }
 /* L1: */
     return 0;
 } /* help_ */