My Project: HOLFRM.c File Reference
HOLFRM.c File Reference
#include "f2c.h"
Macros
#define sdp_1 sdp_
Functions
int holfrm_ (integer *iarr, char *str, integer *ist, integer *nchr, integer *nwd, ftnlen str_len)
Variables
struct {
integer nbchar
integer nbwrd
integer iwrd
integer ifac
} sdp_
Macro Definition Documentation
#define sdp_1 sdp_
Definition at line 21 of file HOLFRM.c.
Referenced by holfrm_().
Function Documentation
int holfrm_ (integer * iarr, char * str, integer * ist, integer * nchr, integer * nwd, ftnlen str_len)
Definition at line 64 of file HOLFRM.c.
References i__, j, jj, k, k1, and sdp_1.
Referenced by acntrl_(), apt090_(), apt102_(), apt103_(), apt107_(), apt108_(), apt109_(), apt110_(), apt202_(), apt211_(), apt234_(), apt298_(), apt301_(), apt302_(), apt309_(), apt310_(), apt311_(), apt312_(), apt331_(), apt335_(), avctrl_(), chksrf_(), cilout_(), cnsurf_(), cnvrt3_(), floseg_(), gclear_(), gencrv_(), gol_(), golovo_(), gougck_(), indirp_(), indirv_(), indrph_(), indrvh_(), intout_(), intrp_(), intsec_(), ldard_(), mesh_(), multax_(), npat_(), numf1_(), numf2_(), parmf1_(), parmf2_(), print_(), prtil_(), punch_(), recog_(), region_(), scon_(), sctra_(), smil_(), srfcom_(), srfvct_(), sstra_(), tlaxis_(), units_(), and wtdire_().
 {
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     integer i_len(char *, ftnlen), lbit_shift(integer, integer);
     /* Local variables */
     static integer i__, j, k, k1, jj, ival, jval, slen;
 /* .... SYSTEM DEPENDENT PARAMETERS */
     /* Parameter adjustments */
     --iarr;
     /* Function Body */
     slen = i_len(str, str_len);
     *nwd = *nchr / sdp_1.iwrd;
     if (*nchr > *nwd * sdp_1.iwrd) {
     ++(*nwd);
     }
     i__1 = *nwd;
     for (i__ = 1; i__ <= i__1; ++i__) {
     ival = iarr[i__];
     k1 = *ist + i__ * sdp_1.iwrd;
     for (j = sdp_1.iwrd; j >= 1; --j) {
         k = k1 - j;
         jj = sdp_1.nbchar * (j - 1);
         jval = lbit_shift(ival, -jj);
         if (k <= slen) {
         *(unsigned char *)&str[k - 1] = (char) jval;
         }
         ival -= lbit_shift(jval, jj);
 /* L10: */
     }
 /* L20: */
     }
     return 0;
 } /* holfrm_ */
Variable Documentation
integer ifac
Definition at line 18 of file HOLFRM.c.
integer iwrd
Definition at line 18 of file HOLFRM.c.
integer nbchar
Definition at line 18 of file HOLFRM.c.
integer nbwrd
Definition at line 18 of file HOLFRM.c.
struct { ... } sdp_