My Project: ICONV.c File Reference
ICONV.c File Reference
#include "f2c.h"
Functions
int iconv_ (integer *i__, char *a, integer *n, integer *k, ftnlen a_len)
Variables
static integer c__1 = 1
Function Documentation
int iconv_ (integer * i__, char * a, integer * n, integer * k, ftnlen a_len)
Definition at line 40 of file ICONV.c.
References c__1, i1, i2, j, k, l, and n.
Referenced by aerr2_(), aerr_(), alarm_(), apt089_(), apt104_(), apt107_(), apt108_(), apt301_(), apt302_(), apt309_(), apt330_(), apt331_(), apt335_(), apt336_(), aread_(), awrite_(), bad_(), chread_(), chwrit_(), cilout_(), errlod_(), error_(), filopn_(), fread_(), gol_(), init_(), intmsg_(), intout_(), intrp_(), ldard_(), lib_(), mesh_(), print_(), punch_(), read_(), resred_(), scpict_(), set_(), sprvis_0_(), srfcom_(), sspath_(), sspict_(), tapop_(), and xcanon_().
 {
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     integer s_wsfi(icilist *), do_fio(integer *, char *, ftnlen), e_wsfi(void)
         ;
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer j, l, i1, i2;
     static char intfil[11];
     /* Fortran I/O blocks */
     static icilist io___2 = { 0, intfil, 0, "(I11)", 11, 1 };
     s_wsfi(&io___2);
     do_fio(&c__1, (char *)&(*i__), (ftnlen)sizeof(integer));
     e_wsfi();
     for (j = 1; j <= 11; ++j) {
     if (*(unsigned char *)&intfil[j - 1] != ' ') {
         goto L20;
     }
 /* L10: */
     }
     j = 11;
 L20:
     l = 12 - j;
     if (l > *k) {
     goto L30;
     }
     i2 = *n + *k - 1;
     i1 = i2 - l + 1;
     s_copy(a + (i1 - 1), intfil + (j - 1), i2 - (i1 - 1), 11 - (j - 1));
     goto L99;
 /* ---- OVERFLOW */
 L30:
     i1 = *n;
     i__1 = *k;
     for (j = 1; j <= i__1; ++j) {
     *(unsigned char *)&a[i1 - 1] = '*';
 /* L35: */
     ++i1;
     }
 L99:
     return 0;
 } /* iconv_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 17 of file ICONV.c.
Referenced by iconv_().