My Project: IFTMP.c File Reference
IFTMP.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define code_1 code_
#define moduli_1 moduli_
#define temp ((integer *)&code_1 + 32)
#define modhlf ((integer *)&moduli_1 + 1)
#define modulo ((integer *)&moduli_1)
Functions
logical iftmp_ (integer *a)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer code [150]
} code_
struct {
integer moduli [2]
} moduli_
Macro Definition Documentation
#define cnamtb_1 cnamtb_
Definition at line 28 of file IFTMP.c.
#define code_1 code_
Definition at line 34 of file IFTMP.c.
#define modhlf ((integer *)&moduli_1 + 1)
Referenced by iftmp_().
#define moduli_1 moduli_
Definition at line 40 of file IFTMP.c.
#define modulo ((integer *)&moduli_1)
Referenced by iftmp_().
#define nametb_1 nametb_
Definition at line 22 of file IFTMP.c.
Referenced by iftmp_().
#define temp ((integer *)&code_1 + 32)
Referenced by iftmp_().
Function Documentation
logical iftmp_ (integer * a)
Definition at line 61 of file IFTMP.c.
References modhlf, modulo, nametb_1, and temp.
Referenced by boolif_(), inpat_(), macrec_(), pro020_(), recog_(), recogn_(), replac_(), and subcod_().
 {
     /* System generated locals */
     logical ret_val;
     /* Local variables */
 #define temp ((integer *)&code_1 + 32)
 #define modhlf ((integer *)&moduli_1 + 1)
 #define modulo ((integer *)&moduli_1)
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /* NAMMAX:      NAMTBL INDEX OF END OF THE PART PROGRAM NAME SECTION */
 /*        3.    METALINGUISTIC VARIABLE CLASS CODES */
 /* TEMP:        (1)=CODE CLASS 17000,(2)=NAMTBL INDEX OF 'TEMP  ' */
 /*       29.    CLASS CODE MODULI */
 /* MODULO:      NAMTBL CLASS AND CODE FACTOR 1000 TO DEVIDE OUT CLASS */
 /* MODHLF:      NORMAL MODE CODE LIMIT 500 */
 /* ** */
 /* ...     IS A THE NAMTBL INDEX OF A TEMPORARY LOCATION */
     if (*a > nametb_1.nammax) {
     goto L5;
     }
     if (nametb_1.namtbl[*a - 1] / *modulo == temp[0] / *modulo &&
         nametb_1.namtbl[*a - 1] - *modulo * (nametb_1.namtbl[*a - 1] / *
         modulo) < *modhlf) {
     goto L10;
     }
 /* ...     NO. RETURN IFTMP AS .FALSE. */
 L5:
     ret_val = FALSE_;
     return ret_val;
 /* ...     YES. RETURN IFTMP AS .TRUE. */
 L10:
     ret_val = TRUE_;
     return ret_val;
 } /* iftmp_ */
Variable Documentation
integer charnd
Definition at line 18 of file IFTMP.c.
integer charst
Definition at line 18 of file IFTMP.c.
char cnamtb[18000]
Definition at line 25 of file IFTMP.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file IFTMP.c.
integer code[150]
Definition at line 31 of file IFTMP.c.
struct { ... } code_
integer ifixnd
Definition at line 18 of file IFTMP.c.
integer ifixst
Definition at line 18 of file IFTMP.c.
integer inamnd
Definition at line 18 of file IFTMP.c.
integer inamst
Definition at line 18 of file IFTMP.c.
integer moduli[2]
Definition at line 37 of file IFTMP.c.
struct { ... } moduli_
integer namest
Definition at line 18 of file IFTMP.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file IFTMP.c.
integer namtbl[3000]
Definition at line 18 of file IFTMP.c.
integer numbnd
Definition at line 18 of file IFTMP.c.
integer numbst
Definition at line 18 of file IFTMP.c.