My Project: IMAIN.c File Reference
IMAIN.c File Reference
#include "f2c.h"
Functions
int imain_ (void)
Function Documentation
int imain_ (void)
Definition at line 18 of file IMAIN.c.
References init_(), and intrp_().
Referenced by exec_().
 {
     extern /* Subroutine */ int init_(void), intrp_(void);
 /* PURPOSE      THIS IS THE MAIN ROUTINE FOR THE INTERPRETIVE APPROACH. */
 /* NOTE THE MAIN ROUTINE FOR THE ASSEMBLY APPROACH */
 /* WILL BE CALLED AMAIN, WHEN IMPLEMENTED, & WHICH ROUTINE */
 /* IS USED DEPENDS ON THE APPROACH  REQUESTED BY THE PART PROGRAM. */
 /* CALLED BY    THE ROUTINE MAIN */
 /* ...  INITALIZE STORAGE */
     init_();
 /* ...  GO TO INTERPRETER */
     intrp_();
     return 0;
 } /* imain_ */