My Project: INTFA1.c File Reference
INTFA1.c File Reference
#include "f2c.h"
Functions
int intfa1_ (doublereal *face, doublereal *pl, doublereal *pf, integer *irc1)
Function Documentation
int intfa1_ (doublereal * face, doublereal * pl, doublereal * pf, integer * irc1)
Definition at line 17 of file INTFA1.c.
References cross_(), i__, pl, v2, and v3.
Referenced by intfa2_(), and polpol_().
 {
     static integer i__;
     static doublereal v2[3], v3[3];
     extern /* Subroutine */ int cross_(doublereal *, doublereal *, doublereal
         *);
     /* Parameter adjustments */
     --pf;
     --pl;
     face -= 7;
     /* Function Body */
     *irc1 = 0;
     for (i__ = 1; i__ <= 3; ++i__) {
     v2[0] = pf[1] - face[i__ * 6 + 1];
     v2[1] = pf[2] - face[i__ * 6 + 2];
     v2[2] = pf[3] - face[i__ * 6 + 3];
     cross_(v2, &face[i__ * 6 + 4], v3);
     if (pl[1] * v3[0] + pl[2] * v3[1] + pl[3] * v3[2] < 0.) {
         goto L20;
     }
 /* L10: */
     }
     *irc1 = 1;
 L20:
     return 0;
 } /* intfa1_ */