My Project: INTOUT.c File Reference
INTOUT.c File Reference
#include "f2c.h"
Macros
#define ifxcor_1 ifxcor_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define intcom_1 intcom_
#define ssarlm_1 ssarlm_
#define _BLNK__1 _BLNK__
#define symfil_1 symfil_
#define pt ((doublereal *)&equiv_9 + 1)
#define vn ((doublereal *)&equiv_10 + 1)
#define pt1 ((doublereal *)&equiv_9)
#define vt1 ((doublereal *)&equiv_10)
#define can ((doublereal *)&_BLNK__1 + 40)
#define spv ((doublereal *)&intcom_1)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define leit ((doublereal *)&equiv_4)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define ipnr ((integer *)&intcom_1 + 253)
#define canon ((doublereal *)&_BLNK__1)
#define ileit ((integer *)&equiv_4)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int intout_ (integer *iout, doublereal *ptt, integer *np, integer *iord, integer *j11, integer *j12, doublereal *sname, doublereal *sindex)
Variables
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
integer ikeep [255]
} intcom_
struct {
doublereal bb [256]
doublereal uu [4]
doublereal vv [4]
integer iitop [96]
integer iiflag [16]
integer ipnum [4]
} ssarlm_
struct {
doublereal com [36000]
} _BLNK__
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
static integer c__2 = 2
static integer c__3 = 3
static integer c__0 = 0
static integer c__1 = 1
static integer c__5 = 5
static integer c__7 = 7
static integer c__8 = 8
static integer c__4 = 4
static integer c__12 = 12
static integer c__20 = 20
static integer c__16 = 16
static integer c__6 = 6
static integer c__36 = 36
static integer c__37 = 37
static integer c__53 = 53
static integer c__54 = 54
static integer c__70 = 70
static integer c__79 = 79
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 93 of file INTOUT.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define charct_1 charct_
Definition at line 40 of file INTOUT.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define fxcor_1 fxcor_
Definition at line 34 of file INTOUT.c.
Referenced by intout_().
#define ifxcor_1 ifxcor_
Definition at line 25 of file INTOUT.c.
Referenced by intout_().
#define ileit ((integer *)&equiv_4)
Referenced by intout_().
#define intcom_1 intcom_
Definition at line 79 of file INTOUT.c.
#define ipnr ((integer *)&intcom_1 + 253)
Referenced by intout_().
#define leit ((doublereal *)&equiv_4)
Referenced by intout_().
#define pt ((doublereal *)&equiv_9 + 1)
Referenced by intout_().
#define pt1 ((doublereal *)&equiv_9)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define spv ((doublereal *)&intcom_1)
Referenced by intout_().
#define ssarlm_1 ssarlm_
Definition at line 87 of file INTOUT.c.
Referenced by intout_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
Referenced by intout_().
#define sv1_1 sv1_
Definition at line 73 of file INTOUT.c.
#define sv_1 sv_
Definition at line 64 of file INTOUT.c.
Referenced by intout_().
#define symfil_1 symfil_
Definition at line 102 of file INTOUT.c.
Referenced by intout_().
#define tlldat_1 tlldat_
Definition at line 47 of file INTOUT.c.
#define vn ((doublereal *)&equiv_10 + 1)
Referenced by intout_().
#define vt1 ((doublereal *)&equiv_10)
Function Documentation
int intout_ (integer * iout, doublereal * ptt, integer * np, integer * iord, integer * j11, integer * j12, doublereal * sname, doublereal * sindex)
Definition at line 127 of file INTOUT.c.
References atape_(), bcdf_(), c__0, c__1, c__12, c__16, c__2, c__20, c__3, c__36, c__37, c__4, c__5, c__53, c__54, c__6, c__7, c__70, c__79, c__8, cform_(), cnsurf_(), cprint_(), cpunch_(), cross_(), e_1, e_2, ewrite_(), fconv_(), first, fxcor_1, holfrm_(), i__, iconv_(), ifxcor_1, ileit, index, ipnr, ir, j, leit, lodpch_(), n, pt, record_(), spv, ssarlm_1, sscan, sv_1, symfil_1, transm_(), and vn.
Referenced by intsec_().
 {
     /* Initialized data */
     static logical first = TRUE_;
     static struct {
     doublereal e_1[4];
     } equiv_10 = { 2.003e7, 0., 0., 0. };
     static struct {
     integer e_1[18];
     doublereal e_2;
     } equiv_4 = { 0, 0, 1308622848, 0, 1308622848, 6, 1308622848, 1, 0, 0,
          1308622848, 0, 0, 0, 1308622848, 0, 1308622848, 0, 0. };
     static struct {
     doublereal e_1[4];
     } equiv_9 = { 1.903e7, 0., 0., 0. };
     /* System generated locals */
     integer i__1, i__2;
     doublereal d__1, d__2, d__3;
     /* Builtin functions */
     double sqrt(doublereal);
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, j, n;
     static doublereal dm[3];
     static char of[80];
     static integer ip;
 #define pt ((doublereal *)&equiv_9 + 1)
 #define vn ((doublereal *)&equiv_10 + 1)
     static integer nr, ir;
 #define pt1 ((doublereal *)&equiv_9)
 #define vt1 ((doublereal *)&equiv_10)
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer ipa;
 #define spv ((doublereal *)&intcom_1)
     static integer ipd;
     static doublereal vll;
     extern integer bcdf_(char *, ftnlen);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define leit ((doublereal *)&equiv_4)
 #define sinl ((doublereal *)&tlldat_1 + 8)
 #define ipnr ((integer *)&intcom_1 + 253)
     extern /* Subroutine */ int atape_(void);
 #define canon ((doublereal *)&_BLNK__1)
 #define ileit ((integer *)&equiv_4)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen), iconv_(integer *, char *, integer *, integer *,
         ftnlen), fconv_(doublereal *, char *, integer *, integer *,
         integer *, ftnlen);
     static integer itype;
     extern /* Subroutine */ int cross_(doublereal *, doublereal *, doublereal
         *);
     static integer index;
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int record_(integer *);
     static integer ipatch;
     extern /* Subroutine */ int lodpch_(doublereal *, doublereal *, integer *,
          integer *, integer *, integer *), ewrite_(integer *, integer *,
         doublereal *, integer *, integer *), cnsurf_(doublereal *,
         doublereal *, doublereal *, doublereal *, integer *, integer *),
         cprint_(char *, ftnlen), transm_(doublereal *, doublereal *,
         integer *, integer *, integer *), holfrm_(doublereal *, char *,
         integer *, integer *, integer *, ftnlen), cpunch_(char *, integer
         *, ftnlen);
 /*   OUTPUT OF INTERSECTION ROUTINES */
 /*   OUTPUT FIELD FOR CANON */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   COMMON FOR 2 SURFACE INTERSECTION */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   EVALUATION VECTOR FOR PS AND DS */
 /*   PATCH NUMBER FOR PS AND DS (SURFACE RECNO*1000 + PATCH NO) */
 /* SS - ARELEM - COMMON */
 /*  EXFILE INTRODUCTION */
 /*     BLANK-COMMON */
 /* SYSTEM - I/O NAMES */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /*   POINT STORAGE FOR TRANSFORMATION PURPOSE */
 /* ...                SYSTEM I/O FILES */
 /*   VECTOR STORAGE FOR TRANSFORMATION PURPOSE */
 /*  MOTION DIRECTION */
     /* Parameter adjustments */
     ptt -= 10;
     /* Function Body */
 /* AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA */
 /*     INITIALISE CHARACTER ITEMS FOR OUTPUT TO EXFILE */
     if (first) {
     ileit[0] = bcdf_("CLDA", (ftnlen)4);
     ileit[1] = bcdf_("TA  ", (ftnlen)4);
     ileit[8] = bcdf_("INTS", (ftnlen)4);
     ileit[9] = bcdf_("EC  ", (ftnlen)4);
     ileit[12] = bcdf_("    ", (ftnlen)4);
     ileit[13] = ileit[12];
     first = FALSE_;
     }
 /*  TYPE OF OPERATION */
     itype = *iout + 1;
 /*  START AND INCREMENTS FOR OUTPUT */
     ip = 1;
     if (*iord < 0) {
     ip = *np;
     }
     ipd = 1;
     if (*iord < 0) {
     ipd = -1;
     }
 /*  PREPARATION FOR EXFILE OUTPUT */
     if (itype != 1) {
     goto L10;
     }
     nr = 0;
     j = 18;
     record_(&ifxcor_1.iseqno);
     ileit[3] = ifxcor_1.iseqno;
 /*  NAME */
     leit[6] = *sname;
     ileit[15] = (integer) (*sindex);
     ileit[17] = 29;
     ewrite_(&symfil_1.exfile, &nr, leit, &j, &ir);
 /*  OUTPUT LOOP */
 L10:
     i__1 = *np;
     for (i__ = 1; i__ <= i__1; ++i__) {
     switch (itype) {
         case 1:  goto L20;
         case 2:  goto L30;
         case 3:  goto L40;
     }
     return 0;
 /*   EXFILE OUTPUT **************************************************** */
 /*  STORING INTERSECTION POINT */
 L20:
     for (j = 1; j <= 3; ++j) {
         fxcor_1.tek[j - 1] = fxcor_1.te[j - 1];
 /* L110: */
         pt[j - 1] = ptt[j + ip * 9];
     }
     transm_(fxcor_1.te, pt, &c__2, &c__3, &c__0);
 /* LOAD PS PATCH IF NECESSARY */
     ipatch = (integer) ptt[ip * 9 + 9];
     ipa = ipatch - ipatch / 1000 * 1000;
     if (ipnr[0] != ipatch) {
         lodpch_(&sscan[*j12], ssarlm_1.bb, ssarlm_1.iiflag,
             ssarlm_1.iitop, &ipa, &c__0);
     }
     ipnr[0] = ipatch;
 /* STORE (U,V,P)-VALUES OF PS FOR ATAPE */
     ssarlm_1.uu[0] = ptt[ip * 9 + 7];
     ssarlm_1.vv[0] = ptt[ip * 9 + 8];
     ssarlm_1.ipnum[0] = ipa;
 /*  EVALUATE POINT */
     cnsurf_(ssarlm_1.uu, ssarlm_1.vv, ssarlm_1.bb, spv, ssarlm_1.iiflag, &
         c__2);
 /* STORE SURFACE POINT WITH NORMAL FOR ATAPE */
     for (j = 1; j <= 3; ++j) {
         pt[j - 1] = ptt[j + ip * 9];
         vn[j - 1] = spv[j + 27];
 /* L120: */
     }
     transm_(&sv_1.sp[ifxcor_1.ips * 3 - 3], pt, &c__2, &c__3, &c__0);
     transm_(&sv_1.sn[ifxcor_1.ips * 3 - 3], vn, &c__3, &c__3, &c__0);
 /* LOAD DS PATCH IF NECESSARY */
     if (ssarlm_1.iiflag[4] <= 0) {
         goto L124;
     }
     ipatch = (integer) ptt[ip * 9 + 6];
     ipa = ipatch - ipatch / 1000 * 1000;
     if (ipnr[1] != ipatch) {
         lodpch_(&sscan[*j11], &ssarlm_1.bb[64], &ssarlm_1.iiflag[4], &
             ssarlm_1.iitop[24], &ipa, &c__0);
     }
     ipnr[1] = ipatch;
 /* STORE (U,V,P)-VALUES OF PS FOR ATAPE */
     ssarlm_1.uu[1] = ptt[ip * 9 + 4];
     ssarlm_1.vv[1] = ptt[ip * 9 + 5];
     ssarlm_1.ipnum[1] = ipa;
 /*  EVALUATE POINT */
     cnsurf_(&ssarlm_1.uu[1], &ssarlm_1.vv[1], &ssarlm_1.bb[64], &spv[32],
         &ssarlm_1.iiflag[4], &c__2);
     goto L126;
 /*  PLANE DS */
 L124:
     ssarlm_1.uu[1] = 0.;
     ssarlm_1.vv[1] = 0.;
     ssarlm_1.ipnum[1] = 0;
 /* STORE SURFACE POINT WITH NORMAL FOR ATAPE */
 L126:
     for (j = 1; j <= 3; ++j) {
         pt[j - 1] = ptt[j + ip * 9];
         if (ssarlm_1.iiflag[4] <= 0) {
         spv[j + 59] = ssarlm_1.bb[j + 63];
         }
         vn[j - 1] = spv[j + 59];
 /* L130: */
     }
     transm_(&sv_1.sp[ifxcor_1.ids * 3 - 3], pt, &c__2, &c__3, &c__0);
     transm_(&sv_1.sn[ifxcor_1.ids * 3 - 3], vn, &c__3, &c__3, &c__0);
 /*  NORMALIZE MOTION DIRECTION */
     cross_(&spv[60], &spv[28], dm);
 /* Computing 2nd power */
     d__1 = dm[0];
 /* Computing 2nd power */
     d__2 = dm[1];
 /* Computing 2nd power */
     d__3 = dm[2];
     vll = sqrt(d__1 * d__1 + d__2 * d__2 + d__3 * d__3);
     for (j = 1; j <= 3; ++j) {
         dm[j - 1] /= vll;
 /* L140: */
         vn[j - 1] = dm[j - 1];
     }
     transm_(fxcor_1.ti, vn, &c__3, &c__3, &c__0);
 /*  STORE POSITION ON EXFILE */
     ifxcor_1.icl = 2;
     if (i__ == *np) {
         ifxcor_1.icl = 3;
     }
     atape_();
     goto L49;
 /*   SSCAN OUTPUT ******************************************************* */
 L30:
 /*   PS PATCH INDEX FOR POINT NAME */
     ipa = (integer) ptt[ip * 9 + 9];
     s_copy(of, " ", (ftnlen)80, (ftnlen)1);
     i__2 = ipa + 10000;
     iconv_(&i__2, of, &c__1, &c__5, (ftnlen)80);
     cform_("PT", of, &c__1, &c__2, (ftnlen)2, (ftnlen)80);
     cform_("(", of, &c__7, &c__1, (ftnlen)1, (ftnlen)80);
 /*  POINT INDEX */
     iconv_(&i__, of, &c__8, &c__4, (ftnlen)80);
     cform_(")=POINT/", of, &c__12, &c__8, (ftnlen)8, (ftnlen)80);
 /*  X,Y,Z */
     fconv_(&ptt[ip * 9 + 1], of, &c__20, &c__16, &c__6, (ftnlen)80);
     cform_(",", of, &c__36, &c__1, (ftnlen)1, (ftnlen)80);
     fconv_(&ptt[ip * 9 + 2], of, &c__37, &c__16, &c__6, (ftnlen)80);
     cform_(",", of, &c__53, &c__1, (ftnlen)1, (ftnlen)80);
     fconv_(&ptt[ip * 9 + 3], of, &c__54, &c__16, &c__6, (ftnlen)80);
 /*  FILLER */
     cform_("  ", of, &c__70, &c__2, (ftnlen)2, (ftnlen)80);
     goto L48;
 /*   HEX OUTPUT ********************************************************* */
 L40:
     s_copy(of, " HEX OUTPUT NOT SUPPORTED IN THIS VERSION", (ftnlen)80, (
         ftnlen)41);
     cprint_(of, (ftnlen)80);
     goto L30;
 /*   PS PATCH INDEX FOR POINT NAME */
 /*      IPA=PTT(9,IP) */
 /*      CALL ICONV (IPA+10000,OF,1,5) */
 /*      CALL CFORM ('PT',OF,0,2) */
 /*      CALL CFORM ('  ',OF,6,2) */
 /*  POINT INDEX */
 /*      PP=I */
 /*      CALL CFORM (PP,OF,8,8) */
 /*  POINT TYPE AND LENGTH OF SSCANICAL FORM */
 /*      CALL CFORM (1,OF,16,4) */
 /*      CALL CFORM (6,OF,20,4) */
 /*  FILLER */
 /*      CALL CFORM (0.D0,OF,24,8) */
 /*  X,Y,Z */
 /*      CALL CFORM (PTT(1,IP),OF,32,8) */
 /*      CALL CFORM (PTT(2,IP),OF,40,8) */
 /*      CALL CFORM (PTT(3,IP),OF,48,8) */
 /*  FILLER */
 /*      CALL CFORM (0.D0,OF,56,8) */
 /*      CALL CFORM (0.D0,OF,64,8) */
 /*  COMMON OUTPUT OF SSCAN AND HEX */
 L48:
     holfrm_(sname, of + 72, &c__1, &c__6, &n, (ftnlen)8);
     cform_("  ", of, &c__79, &c__2, (ftnlen)2, (ftnlen)80);
     index = (integer) (*sindex);
     if (index != 0) {
         iconv_(&index, of, &c__79, &c__2, (ftnlen)80);
     }
     cpunch_(of, &c__1, (ftnlen)80);
 /*  POINT INDEX INCREMENTING */
 L49:
     ip += ipd;
 /* L50: */
     }
 /*  END PUNCH OUTPUT FOR HEX FORMAT */
 /*      IF(ITYPE.NE.3)GOTO 99 */
 /*      CALL CFORM ('(ENDPCH)',OF,1,8) */
 /*      DO 60 I=8,65,8 */
 /*      CALL CFORM ('        ',OF,I,8) */
 /*   60 CONTINUE */
 /*      CALL CFORM (-1,OF,73,4) */
 /*      CALL CFORM (-1,OF,77,4) */
 /*      CALL CPUNCH(OF,1) */
 /* L99: */
     return 0;
 } /* intout_ */
Variable Documentation
struct { ... } _BLNK__
doublereal alp
Definition at line 28 of file INTOUT.c.
doublereal ax4[3]
Definition at line 28 of file INTOUT.c.
integer axfile
Definition at line 96 of file INTOUT.c.
doublereal bb[256]
Definition at line 82 of file INTOUT.c.
integer c__0 = 0 static
Definition at line 108 of file INTOUT.c.
Referenced by intout_().
integer c__1 = 1 static
Definition at line 109 of file INTOUT.c.
Referenced by intout_().
integer c__12 = 12 static
Definition at line 114 of file INTOUT.c.
Referenced by intout_().
integer c__16 = 16 static
Definition at line 116 of file INTOUT.c.
Referenced by intout_().
integer c__2 = 2 static
Definition at line 106 of file INTOUT.c.
Referenced by intout_().
integer c__20 = 20 static
Definition at line 115 of file INTOUT.c.
Referenced by intout_().
integer c__3 = 3 static
Definition at line 107 of file INTOUT.c.
Referenced by intout_().
integer c__36 = 36 static
Definition at line 118 of file INTOUT.c.
Referenced by intout_().
integer c__37 = 37 static
Definition at line 119 of file INTOUT.c.
Referenced by intout_().
integer c__4 = 4 static
Definition at line 113 of file INTOUT.c.
Referenced by intout_().
integer c__5 = 5 static
Definition at line 110 of file INTOUT.c.
Referenced by intout_().
integer c__53 = 53 static
Definition at line 120 of file INTOUT.c.
Referenced by intout_().
integer c__54 = 54 static
Definition at line 121 of file INTOUT.c.
Referenced by intout_().
integer c__6 = 6 static
Definition at line 117 of file INTOUT.c.
Referenced by intout_().
integer c__7 = 7 static
Definition at line 111 of file INTOUT.c.
Referenced by intout_().
integer c__70 = 70 static
Definition at line 122 of file INTOUT.c.
Referenced by intout_().
integer c__79 = 79 static
Definition at line 123 of file INTOUT.c.
Referenced by intout_().
integer c__8 = 8 static
Definition at line 112 of file INTOUT.c.
Referenced by intout_().
doublereal cagl
Definition at line 28 of file INTOUT.c.
doublereal cc[15]
Definition at line 50 of file INTOUT.c.
struct { ... } charct_
integer clfil3
Definition at line 96 of file INTOUT.c.
integer clfile
Definition at line 96 of file INTOUT.c.
integer clfilp
Definition at line 96 of file INTOUT.c.
doublereal com[36000]
Definition at line 90 of file INTOUT.c.
doublereal corrad[8]
Definition at line 43 of file INTOUT.c.
doublereal cos1[5]
Definition at line 67 of file INTOUT.c.
integer cpfile
Definition at line 96 of file INTOUT.c.
doublereal cplfl[5]
Definition at line 67 of file INTOUT.c.
doublereal cptst[5]
Definition at line 67 of file INTOUT.c.
doublereal csd[5]
Definition at line 67 of file INTOUT.c.
doublereal cutdat[7]
Definition at line 28 of file INTOUT.c.
doublereal dplan[15]
Definition at line 67 of file INTOUT.c.
doublereal dpmax
Definition at line 28 of file INTOUT.c.
doublereal dpmx1[5]
Definition at line 67 of file INTOUT.c.
integer elfil1
Definition at line 96 of file INTOUT.c.
integer elfil2
Definition at line 96 of file INTOUT.c.
integer elfil3
Definition at line 96 of file INTOUT.c.
integer elfil4
Definition at line 96 of file INTOUT.c.
integer elfile
Definition at line 96 of file INTOUT.c.
doublereal eps1[5]
Definition at line 50 of file INTOUT.c.
doublereal eps2[5]
Definition at line 50 of file INTOUT.c.
doublereal eps3[5]
Definition at line 50 of file INTOUT.c.
doublereal eps4[5]
Definition at line 50 of file INTOUT.c.
doublereal eps6[5]
Definition at line 50 of file INTOUT.c.
doublereal eps8[5]
Definition at line 50 of file INTOUT.c.
integer exfile
Definition at line 96 of file INTOUT.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file INTOUT.c.
doublereal hi
Definition at line 28 of file INTOUT.c.
integer i3dflg
Definition at line 18 of file INTOUT.c.
integer iaerr
Definition at line 18 of file INTOUT.c.
integer iautps
Definition at line 18 of file INTOUT.c.
integer ibegin
Definition at line 18 of file INTOUT.c.
integer ic
Definition at line 18 of file INTOUT.c.
integer icheck
Definition at line 18 of file INTOUT.c.
integer icl
Definition at line 18 of file INTOUT.c.
integer ics
Definition at line 18 of file INTOUT.c.
integer icscnt
Definition at line 18 of file INTOUT.c.
integer ictdef
Definition at line 18 of file INTOUT.c.
integer icut
Definition at line 18 of file INTOUT.c.
integer ids
Definition at line 18 of file INTOUT.c.
integer ier
Definition at line 18 of file INTOUT.c.
struct { ... } ifxcor_
integer igo
Definition at line 18 of file INTOUT.c.
integer igoto
Definition at line 18 of file INTOUT.c.
integer igoug
Definition at line 18 of file INTOUT.c.
integer igs
Definition at line 18 of file INTOUT.c.
integer iiflag[16]
Definition at line 83 of file INTOUT.c.
integer iitop[96]
Definition at line 83 of file INTOUT.c.
integer ikeep[255]
Definition at line 76 of file INTOUT.c.
integer infile__
Definition at line 96 of file INTOUT.c.
integer inops
Definition at line 18 of file INTOUT.c.
struct { ... } intcom_
integer ipnum[4]
Definition at line 83 of file INTOUT.c.
integer ips
Definition at line 18 of file INTOUT.c.
integer ipsdef
Definition at line 18 of file INTOUT.c.
integer ipt1
Definition at line 18 of file INTOUT.c.
integer is
Definition at line 18 of file INTOUT.c.
integer iseg
Definition at line 18 of file INTOUT.c.
integer iseqno
Definition at line 18 of file INTOUT.c.
integer ispare[26]
Definition at line 96 of file INTOUT.c.
integer isrch
Definition at line 18 of file INTOUT.c.
integer istrup
Definition at line 18 of file INTOUT.c.
integer it
Definition at line 18 of file INTOUT.c.
integer jbr
Definition at line 18 of file INTOUT.c.
integer jsw
Definition at line 18 of file INTOUT.c.
integer ldafil
Definition at line 96 of file INTOUT.c.
integer libfil
Definition at line 96 of file INTOUT.c.
integer lsv
Definition at line 18 of file INTOUT.c.
integer lsv1
Definition at line 18 of file INTOUT.c.
integer mactxt
Definition at line 96 of file INTOUT.c.
integer mantax
Definition at line 18 of file INTOUT.c.
char modfer[6]
Definition at line 37 of file INTOUT.c.
integer motmod
Definition at line 18 of file INTOUT.c.
integer msav
Definition at line 18 of file INTOUT.c.
integer mulout
Definition at line 18 of file INTOUT.c.
integer nfil12
Definition at line 96 of file INTOUT.c.
integer nfil13
Definition at line 96 of file INTOUT.c.
integer nmbseg
Definition at line 18 of file INTOUT.c.
integer nmpnts
Definition at line 18 of file INTOUT.c.
integer nrec
Definition at line 18 of file INTOUT.c.
integer numax
Definition at line 18 of file INTOUT.c.
integer numcnt
Definition at line 18 of file INTOUT.c.
integer nump
Definition at line 18 of file INTOUT.c.
integer numpt1
Definition at line 18 of file INTOUT.c.
integer numsfs
Definition at line 18 of file INTOUT.c.
integer numsur
Definition at line 18 of file INTOUT.c.
integer nw
Definition at line 18 of file INTOUT.c.
integer nwds
Definition at line 18 of file INTOUT.c.
doublereal past[5]
Definition at line 50 of file INTOUT.c.
doublereal plncs[5]
Definition at line 67 of file INTOUT.c.
doublereal plnd[5]
Definition at line 50 of file INTOUT.c.
doublereal plnd1[5]
Definition at line 67 of file INTOUT.c.
doublereal plnv[15]
Definition at line 50 of file INTOUT.c.
doublereal pltst[5]
Definition at line 67 of file INTOUT.c.
doublereal pmove[3]
Definition at line 28 of file INTOUT.c.
integer pnchfl
Definition at line 96 of file INTOUT.c.
integer pofile
Definition at line 96 of file INTOUT.c.
integer pxfile
Definition at line 96 of file INTOUT.c.
doublereal ra
Definition at line 28 of file INTOUT.c.
doublereal rc[5]
Definition at line 50 of file INTOUT.c.
doublereal rc1
Definition at line 28 of file INTOUT.c.
doublereal ri[8]
Definition at line 43 of file INTOUT.c.
doublereal s[5]
Definition at line 50 of file INTOUT.c.
doublereal sagl
Definition at line 28 of file INTOUT.c.
doublereal save[5]
Definition at line 50 of file INTOUT.c.
doublereal sfvct[15]
Definition at line 50 of file INTOUT.c.
doublereal sk[15]
Definition at line 50 of file INTOUT.c.
doublereal slx[15]
Definition at line 50 of file INTOUT.c.
doublereal sn[15]
Definition at line 50 of file INTOUT.c.
doublereal snk[15]
Definition at line 50 of file INTOUT.c.
doublereal snl[15]
Definition at line 50 of file INTOUT.c.
doublereal sp[15]
Definition at line 50 of file INTOUT.c.
doublereal spk[15]
Definition at line 50 of file INTOUT.c.
doublereal spl[15]
Definition at line 50 of file INTOUT.c.
struct { ... } ssarlm_
doublereal stck[5]
Definition at line 67 of file INTOUT.c.
doublereal stck1[5]
Definition at line 67 of file INTOUT.c.
doublereal stck2[5]
Definition at line 67 of file INTOUT.c.
doublereal stckn[5]
Definition at line 67 of file INTOUT.c.
doublereal strtno
Definition at line 28 of file INTOUT.c.
doublereal surd
Definition at line 28 of file INTOUT.c.
struct { ... } sv1_
struct { ... } sv_
struct { ... } symfil_
doublereal ta[3]
Definition at line 28 of file INTOUT.c.
doublereal tak[3]
Definition at line 28 of file INTOUT.c.
doublereal tal[3]
Definition at line 28 of file INTOUT.c.
doublereal tanhi[8]
Definition at line 43 of file INTOUT.c.
doublereal tanlo[8]
Definition at line 43 of file INTOUT.c.
doublereal tau[5]
Definition at line 50 of file INTOUT.c.
doublereal tau1[5]
Definition at line 50 of file INTOUT.c.
doublereal tau2[5]
Definition at line 50 of file INTOUT.c.
doublereal tcont[9]
Definition at line 43 of file INTOUT.c.
doublereal te[3]
Definition at line 28 of file INTOUT.c.
doublereal tee[15]
Definition at line 67 of file INTOUT.c.
doublereal tek[3]
Definition at line 28 of file INTOUT.c.
doublereal tel[3]
Definition at line 28 of file INTOUT.c.
doublereal tem[10]
Definition at line 28 of file INTOUT.c.
doublereal temp[24]
Definition at line 28 of file INTOUT.c.
doublereal th[5]
Definition at line 50 of file INTOUT.c.
doublereal ti[3]
Definition at line 28 of file INTOUT.c.
integer tifile
Definition at line 96 of file INTOUT.c.
doublereal tik[3]
Definition at line 28 of file INTOUT.c.
doublereal til[3]
Definition at line 28 of file INTOUT.c.
doublereal tlhit
Definition at line 28 of file INTOUT.c.
doublereal tlhite[8]
Definition at line 43 of file INTOUT.c.
doublereal tlinc[9]
Definition at line 43 of file INTOUT.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file INTOUT.c.
doublereal tn[15]
Definition at line 50 of file INTOUT.c.
doublereal tnl[15]
Definition at line 67 of file INTOUT.c.
doublereal toolht[15]
Definition at line 50 of file INTOUT.c.
doublereal toolwd[5]
Definition at line 50 of file INTOUT.c.
doublereal tp[15]
Definition at line 50 of file INTOUT.c.
doublereal tpk[15]
Definition at line 50 of file INTOUT.c.
doublereal u1[15]
Definition at line 50 of file INTOUT.c.
doublereal u1k[15]
Definition at line 50 of file INTOUT.c.
doublereal umax[8]
Definition at line 43 of file INTOUT.c.
doublereal uu[4]
Definition at line 82 of file INTOUT.c.
doublereal varble[5]
Definition at line 50 of file INTOUT.c.
integer vlfile
Definition at line 96 of file INTOUT.c.
doublereal vndir[15]
Definition at line 50 of file INTOUT.c.
doublereal vt[15]
Definition at line 50 of file INTOUT.c.
doublereal vtem
Definition at line 28 of file INTOUT.c.
doublereal vv[4]
Definition at line 82 of file INTOUT.c.
integer xcan
Definition at line 96 of file INTOUT.c.
integer xnum
Definition at line 96 of file INTOUT.c.
doublereal z__[5]
Definition at line 50 of file INTOUT.c.