My Project: IPRLOG.c File Reference
IPRLOG.c File Reference
#include "f2c.h"
Macros
#define iltext_1 iltext_
#define textin ((integer *)&iltext_1 + 4)
#define optext ((integer *)&iltext_1 + 3)
#define tpntrx ((integer *)&iltext_1 + 2)
Functions
int iprlog_ (void)
Variables
struct {
integer iltext [94]
} iltext_
Macro Definition Documentation
#define iltext_1 iltext_
Definition at line 21 of file IPRLOG.c.
#define optext ((integer *)&iltext_1 + 3)
Referenced by iprlog_().
#define textin ((integer *)&iltext_1 + 4)
Referenced by iprlog_().
#define tpntrx ((integer *)&iltext_1 + 2)
Referenced by iprlog_().
Function Documentation
int iprlog_ (void)
Definition at line 35 of file IPRLOG.c.
References icmprs_(), name_(), optext, textin, and tpntrx.
Referenced by prolog_().
 {
     /* Initialized data */
     static char s21ts1[6] = "$21T$1";
     /* Local variables */
     extern integer name_(char *, ftnlen);
     extern /* Subroutine */ int icmprs_(void);
 #define textin ((integer *)&iltext_1 + 4)
 #define optext ((integer *)&iltext_1 + 3)
 #define tpntrx ((integer *)&iltext_1 + 2)
 /*       19.    INTERMEDIATE LANGUAGE TEXT */
 /* TPNTRX:      POINTER TO LAST TEXTIN ENTRY */
 /* OPTEXT:      CONTAINS COMMAND CODE FOR CURRENT I.L. COMMAND */
 /* TEXTIN:      STORAGE FOR CURRENTLY GENERATED I.L. COMMAND ARGUM.LIST */
 /* ** */
     icmprs_();
     *optext = 12;
     *tpntrx = 4;
     textin[0] = name_(s21ts1, (ftnlen)6);
     textin[1] = 21;
     textin[2] = 1;
     textin[3] = 1;
     return 0;
 } /* iprlog_ */
Variable Documentation
integer iltext[94]
Definition at line 18 of file IPRLOG.c.
struct { ... } iltext_