My Project: JUMPZZ.c File Reference
JUMPZZ.c File Reference
#include "f2c.h"
Macros
#define il_1 il_
#define jump ((integer *)&il_1 + 7)
Functions
int jumpzz_ (integer *index)
Variables
struct {
integer il [21]
} il_
Macro Definition Documentation
#define il_1 il_
Definition at line 21 of file JUMPZZ.c.
#define jump ((integer *)&il_1 + 7)
Referenced by jumpzz_().
Function Documentation
int jumpzz_ (integer * index)
Definition at line 36 of file JUMPZZ.c.
References jump, onearg_(), opcode_(), and rlslin_().
Referenced by comstr_(), and pro026_().
 {
     /* Local variables */
 #define jump ((integer *)&il_1 + 7)
     extern /* Subroutine */ int opcode_(integer *), onearg_(integer *),
         rlslin_(void);
 /*       16.    LITERALS FOR I. L. OPERATION CODES */
 /* JUMP:        CONTAINS COMMAND CODE ( 8) FOR JUMP COMMAND */
 /* * */
 /* PURPOSE      TO GENERATE  AND OUTPUT TO THE I.L. INTERNAL */
 /*              RECORD IMAGE (ILFILE) THE JUMP I.L. COMMAND. */
 /* ARGUMENTS    INDEX    NAME TABLE (NAMTBL) INDEX OF A LABEL. */
 /* ** */
 /* ...     GENERATE I.L. FOR JUMP COMMAND. */
     opcode_(jump);
     onearg_(index);
     rlslin_();
     return 0;
 } /* jumpzz_ */
Variable Documentation
integer il[21]
Definition at line 18 of file JUMPZZ.c.
struct { ... } il_