My Project: LABELZ.c File Reference
LABELZ.c File Reference
#include "f2c.h"
Macros
#define il_1 il_
#define labelx ((integer *)&il_1 + 5)
Functions
int labelz_ (integer *index)
Variables
struct {
integer il [21]
} il_
Macro Definition Documentation
#define il_1 il_
Definition at line 21 of file LABELZ.c.
#define labelx ((integer *)&il_1 + 5)
Referenced by labelz_().
Function Documentation
int labelz_ (integer * index)
Definition at line 39 of file LABELZ.c.
References labelx, onearg_(), opcode_(), and rlslin_().
Referenced by boolif_(), comstr_(), loop_(), macrec_(), match_(), and recog_().
 {
     /* Local variables */
 #define labelx ((integer *)&il_1 + 5)
     extern /* Subroutine */ int opcode_(integer *), onearg_(integer *),
         rlslin_(void);
 /*       16.    LITERALS FOR I. L. OPERATION CODES */
 /* LABELX:      CONTAINS COMMAND CODE ( 6) FOR LABEL COMMAND */
 /* * */
 /* PURPOSE      TO GENERATE AND OUTPUT TO THE I.L. RECORD IMAGE */
 /*              (ILFILE) THE LABEL I.L. COMMAND. */
 /* ARGUMENTS    INDEX    NAME TABLE (NAMTBL) INDEX OF LABEL. */
 /* ** */
     opcode_(labelx);
     onearg_(index);
     rlslin_();
     return 0;
 } /* labelz_ */
Variable Documentation
integer il[21]
Definition at line 18 of file LABELZ.c.
struct { ... } il_