My Project: LCLS.c File Reference
LCLS.c File Reference
#include "f2c.h"
Macros
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define ifxcor_1 ifxcor_
#define knumbr_1 knumbr_
#define _BLNK__1 _BLNK__
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int lcls_ (doublereal *u, doublereal *v, doublereal *ssp, doublereal *dderu, doublereal *dderv, integer *mmode)
Variables
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
doublereal com [36000]
} _BLNK__
static integer c__27003 = 27003
static integer c__27002 = 27002
static integer c_b15 = -27001
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 73 of file LCLS.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
Referenced by lcls_().
#define ifxcor_1 ifxcor_
Definition at line 59 of file LCLS.c.
Referenced by lcls_().
#define knumbr_1 knumbr_
Definition at line 67 of file LCLS.c.
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define sv1_1 sv1_
Definition at line 41 of file LCLS.c.
#define sv_1 sv_
Definition at line 32 of file LCLS.c.
Referenced by lcls_().
#define znumbr_1 znumbr_
Definition at line 49 of file LCLS.c.
Function Documentation
int lcls_ (doublereal * u, doublereal * v, doublereal * ssp, doublereal * dderu, doublereal * dderv, integer * mmode)
Definition at line 86 of file LCLS.c.
References aerr_(), c__27002, c__27003, c_b15, canon, cross_(), f, i__, ifxcor_1, r2, r3, sv_1, u2, v1, v2, and vnorm_().
Referenced by ddpara_().
 {
     /* Initialized data */
     static doublereal dd = 0.;
     /* Local variables */
     static integer i__;
     static doublereal r2[3], r3[3], u2, u4, v1, v2;
     static integer mm;
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer ker, kkk;
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen);
 #define canon ((doublereal *)&_BLNK__1)
     static doublereal dincx;
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int cross_(doublereal *, doublereal *, doublereal
         *), vnorm_(doublereal *, doublereal *);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
 /* ...CALLS TO PARCHK & FCN HAVE BEEN COMMENTED OUT AS THE PARSRF */
 /* ....FACILITY IS NOT PROVIDED.   24/9/86.   E.MCLELLAN. */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
     /* Parameter adjustments */
     --dderv;
     --dderu;
     --ssp;
     /* Function Body */
 /*  --------------------------------------------------------------~ */
     if (*mmode != 1) {
     goto L5;
     }
 /*      CALL PARCHK(CANON(IC),KER) */
     if (ker == 1) {
     aerr_(&c__27003, "LCLS    ", (ftnlen)8);
     }
 L5:
 /* ------MM=1  DERIV CASE.  MM=0  NODER CASE. */
 L4000:
     mm = (integer) canon[ifxcor_1.ic + 2];
     if (mm == 0) {
     goto L10;
     }
 /*      CALL FCN (CANON(IC),U,V,SSP,DDERU,DDERV,W1,W2,W3,W4,W5,W6) */
     if (*mmode == 1) {
     goto L1000;
     }
 L2000:
     goto L60;
 L10:
     dincx = 1e-4f;
 /* ------COMPUTE THE SURFACE POINT */
 /*      CALL FCN (CANON(IC),U,V,SSP,DDERU,DDERV,W1,W2,W3,W4,W5,W6) */
     if (*mmode == 1) {
     goto L1000;
     }
 L3000:
 /* ------COMPUTE THE PARTIAL DERIVATIVE WITH RESPECT TO U */
     u4 = *u + dincx;
 /*      CALL FCN (CANON(IC),U4,V,R3,DDERU,DDERV,W1,W2,W3,W4,W5,W6) */
     u2 = *u - dincx;
 /*      CALL FCN (CANON(IC),U2,V,R2,DDERU,DDERV,W1,W2,W3,W4,W5,W6) */
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L20: */
     dderu[i__] = (r3[i__ - 1] - r2[i__ - 1]) / (dincx * 2);
     }
 /* ------COMPUTE THE PARTIAL WITH RESPECT TO V */
     v1 = *v + dincx;
 /*      CALL FCN (CANON(IC),U,V1,R3,DDERV,DDERV,W1,W2,W3,W4,W5,W6) */
     v2 = *v - dincx;
 /*      CALL FCN (CANON(IC),U,V2,R2,DDERV,DDERV,W1,W2,W3,W4,W5,W6) */
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L30: */
     dderv[i__] = (r3[i__ - 1] - r2[i__ - 1]) / (dincx * 2);
     }
 L60:
     cross_(&dderu[1], &dderv[1], &sv_1.sn[ifxcor_1.is * 3 - 3]);
     vnorm_(&sv_1.sn[ifxcor_1.is * 3 - 3], &sv_1.sn[ifxcor_1.is * 3 - 3]);
     if (ifxcor_1.ier == 1) {
     aerr_(&c__27002, "LCLS    ", (ftnlen)8);
     }
     return 0;
 L1000:
     kkk = 1;
     if (dderu[1] == dd && dderu[2] == dd && dderu[3] == dd && dderv[1] == dd
         && dderv[2] == dd && dderv[3] == dd) {
     kkk = 0;
     }
     if (mm == 1 && kkk == 1) {
     goto L2000;
     }
     if (mm == 0 && kkk == 0) {
     goto L3000;
     }
     aerr_(&c_b15, "LCLS    ", (ftnlen)8);
     canon[ifxcor_1.ic + 2] = (doublereal) kkk;
     goto L4000;
 } /* lcls_ */
Variable Documentation
struct { ... } _BLNK__
integer c__27002 = 27002 static
Definition at line 78 of file LCLS.c.
Referenced by lcls_().
integer c__27003 = 27003 static
Definition at line 77 of file LCLS.c.
Referenced by lcls_().
integer c_b15 = -27001 static
Definition at line 79 of file LCLS.c.
Referenced by lcls_().
doublereal cc[15]
Definition at line 18 of file LCLS.c.
doublereal com[36000]
Definition at line 70 of file LCLS.c.
doublereal cos1[5]
Definition at line 35 of file LCLS.c.
doublereal cplfl[5]
Definition at line 35 of file LCLS.c.
doublereal cptst[5]
Definition at line 35 of file LCLS.c.
doublereal csd[5]
Definition at line 35 of file LCLS.c.
doublereal degrad
Definition at line 44 of file LCLS.c.
doublereal dplan[15]
Definition at line 35 of file LCLS.c.
doublereal dpmx1[5]
Definition at line 35 of file LCLS.c.
doublereal eps1[5]
Definition at line 18 of file LCLS.c.
doublereal eps2[5]
Definition at line 18 of file LCLS.c.
doublereal eps3[5]
Definition at line 18 of file LCLS.c.
doublereal eps4[5]
Definition at line 18 of file LCLS.c.
doublereal eps6[5]
Definition at line 18 of file LCLS.c.
doublereal eps8[5]
Definition at line 18 of file LCLS.c.
integer i3dflg
Definition at line 52 of file LCLS.c.
integer iaerr
Definition at line 52 of file LCLS.c.
integer iautps
Definition at line 52 of file LCLS.c.
integer ibegin
Definition at line 52 of file LCLS.c.
integer ic
Definition at line 52 of file LCLS.c.
integer icheck
Definition at line 52 of file LCLS.c.
integer icl
Definition at line 52 of file LCLS.c.
integer ics
Definition at line 52 of file LCLS.c.
integer icscnt
Definition at line 52 of file LCLS.c.
integer ictdef
Definition at line 52 of file LCLS.c.
integer icut
Definition at line 52 of file LCLS.c.
integer ids
Definition at line 52 of file LCLS.c.
integer ier
Definition at line 52 of file LCLS.c.
struct { ... } ifxcor_
integer igo
Definition at line 52 of file LCLS.c.
integer igoto
Definition at line 52 of file LCLS.c.
integer igoug
Definition at line 52 of file LCLS.c.
integer igs
Definition at line 52 of file LCLS.c.
integer inops
Definition at line 52 of file LCLS.c.
integer ips
Definition at line 52 of file LCLS.c.
integer ipsdef
Definition at line 52 of file LCLS.c.
integer ipt1
Definition at line 52 of file LCLS.c.
integer is
Definition at line 52 of file LCLS.c.
integer iseg
Definition at line 52 of file LCLS.c.
integer iseqno
Definition at line 52 of file LCLS.c.
integer isrch
Definition at line 52 of file LCLS.c.
integer istrup
Definition at line 52 of file LCLS.c.
integer it
Definition at line 52 of file LCLS.c.
integer jbr
Definition at line 52 of file LCLS.c.
integer jsw
Definition at line 52 of file LCLS.c.
integer k0
Definition at line 62 of file LCLS.c.
integer k1
Definition at line 62 of file LCLS.c.
integer k10
Definition at line 62 of file LCLS.c.
integer k1013
Definition at line 62 of file LCLS.c.
integer k12
Definition at line 62 of file LCLS.c.
integer k13
Definition at line 62 of file LCLS.c.
integer k15
Definition at line 62 of file LCLS.c.
integer k16
Definition at line 62 of file LCLS.c.
integer k18
Definition at line 62 of file LCLS.c.
integer k19
Definition at line 62 of file LCLS.c.
integer k1e4
Definition at line 62 of file LCLS.c.
integer k1e6
Definition at line 62 of file LCLS.c.
integer k2
Definition at line 62 of file LCLS.c.
integer k23
Definition at line 62 of file LCLS.c.
integer k24
Definition at line 62 of file LCLS.c.
integer k25
Definition at line 62 of file LCLS.c.
integer k26
Definition at line 62 of file LCLS.c.
integer k27
Definition at line 62 of file LCLS.c.
integer k29
Definition at line 62 of file LCLS.c.
integer k3
Definition at line 62 of file LCLS.c.
integer k30
Definition at line 62 of file LCLS.c.
integer k31
Definition at line 62 of file LCLS.c.
integer k32
Definition at line 62 of file LCLS.c.
integer k33
Definition at line 62 of file LCLS.c.
integer k34
Definition at line 62 of file LCLS.c.
integer k4
Definition at line 62 of file LCLS.c.
integer k44
Definition at line 62 of file LCLS.c.
integer k45
Definition at line 62 of file LCLS.c.
integer k46
Definition at line 62 of file LCLS.c.
integer k47
Definition at line 62 of file LCLS.c.
integer k48
Definition at line 62 of file LCLS.c.
integer k5
Definition at line 62 of file LCLS.c.
integer k50
Definition at line 62 of file LCLS.c.
integer k51
Definition at line 62 of file LCLS.c.
integer k52
Definition at line 62 of file LCLS.c.
integer k6
Definition at line 62 of file LCLS.c.
integer k7
Definition at line 62 of file LCLS.c.
integer k8
Definition at line 62 of file LCLS.c.
integer k9
Definition at line 62 of file LCLS.c.
integer km1
Definition at line 62 of file LCLS.c.
struct { ... } knumbr_
integer lsv
Definition at line 52 of file LCLS.c.
integer lsv1
Definition at line 52 of file LCLS.c.
integer mantax
Definition at line 52 of file LCLS.c.
integer motmod
Definition at line 52 of file LCLS.c.
integer msav
Definition at line 52 of file LCLS.c.
integer mulout
Definition at line 52 of file LCLS.c.
integer nmbseg
Definition at line 52 of file LCLS.c.
integer nmpnts
Definition at line 52 of file LCLS.c.
integer nrec
Definition at line 52 of file LCLS.c.
integer numax
Definition at line 52 of file LCLS.c.
integer numcnt
Definition at line 52 of file LCLS.c.
integer nump
Definition at line 52 of file LCLS.c.
integer numpt1
Definition at line 52 of file LCLS.c.
integer numsfs
Definition at line 52 of file LCLS.c.
integer numsur
Definition at line 52 of file LCLS.c.
integer nw
Definition at line 52 of file LCLS.c.
integer nwds
Definition at line 52 of file LCLS.c.
doublereal past[5]
Definition at line 18 of file LCLS.c.
doublereal pi
Definition at line 44 of file LCLS.c.
doublereal plncs[5]
Definition at line 35 of file LCLS.c.
doublereal plnd[5]
Definition at line 18 of file LCLS.c.
doublereal plnd1[5]
Definition at line 35 of file LCLS.c.
doublereal plnv[15]
Definition at line 18 of file LCLS.c.
doublereal pltst[5]
Definition at line 35 of file LCLS.c.
doublereal rc[5]
Definition at line 18 of file LCLS.c.
doublereal s[5]
Definition at line 18 of file LCLS.c.
doublereal save[5]
Definition at line 18 of file LCLS.c.
doublereal sfvct[15]
Definition at line 18 of file LCLS.c.
doublereal sk[15]
Definition at line 18 of file LCLS.c.
doublereal slx[15]
Definition at line 18 of file LCLS.c.
doublereal sn[15]
Definition at line 18 of file LCLS.c.
doublereal snk[15]
Definition at line 18 of file LCLS.c.
doublereal snl[15]
Definition at line 18 of file LCLS.c.
doublereal sp[15]
Definition at line 18 of file LCLS.c.
doublereal spk[15]
Definition at line 18 of file LCLS.c.
doublereal spl[15]
Definition at line 18 of file LCLS.c.
doublereal stck[5]
Definition at line 35 of file LCLS.c.
doublereal stck1[5]
Definition at line 35 of file LCLS.c.
doublereal stck2[5]
Definition at line 35 of file LCLS.c.
doublereal stckn[5]
Definition at line 35 of file LCLS.c.
struct { ... } sv1_
struct { ... } sv_
doublereal tau[5]
Definition at line 18 of file LCLS.c.
doublereal tau1[5]
Definition at line 18 of file LCLS.c.
doublereal tau2[5]
Definition at line 18 of file LCLS.c.
doublereal tee[15]
Definition at line 35 of file LCLS.c.
doublereal th[5]
Definition at line 18 of file LCLS.c.
doublereal tn[15]
Definition at line 18 of file LCLS.c.
doublereal tnl[15]
Definition at line 35 of file LCLS.c.
doublereal toolht[15]
Definition at line 18 of file LCLS.c.
doublereal toolwd[5]
Definition at line 18 of file LCLS.c.
doublereal tp[15]
Definition at line 18 of file LCLS.c.
doublereal tpk[15]
Definition at line 18 of file LCLS.c.
doublereal u1[15]
Definition at line 18 of file LCLS.c.
doublereal u1k[15]
Definition at line 18 of file LCLS.c.
doublereal varble[5]
Definition at line 18 of file LCLS.c.
doublereal vndir[15]
Definition at line 18 of file LCLS.c.
doublereal vt[15]
Definition at line 18 of file LCLS.c.
doublereal z0
Definition at line 44 of file LCLS.c.
doublereal z1
Definition at line 44 of file LCLS.c.
doublereal z10
Definition at line 44 of file LCLS.c.
doublereal z11em1
Definition at line 44 of file LCLS.c.
doublereal z12em1
Definition at line 44 of file LCLS.c.
doublereal z1e38
Definition at line 44 of file LCLS.c.
doublereal z1e6
Definition at line 44 of file LCLS.c.
doublereal z1em1
Definition at line 44 of file LCLS.c.
doublereal z1em2
Definition at line 44 of file LCLS.c.
doublereal z1em3
Definition at line 44 of file LCLS.c.
doublereal z1em5
Definition at line 44 of file LCLS.c.
doublereal z1em6
Definition at line 44 of file LCLS.c.
doublereal z1em7
Definition at line 44 of file LCLS.c.
doublereal z1em9
Definition at line 44 of file LCLS.c.
doublereal z2
Definition at line 44 of file LCLS.c.
doublereal z3
Definition at line 44 of file LCLS.c.
doublereal z5
Definition at line 44 of file LCLS.c.
doublereal z5em1
Definition at line 44 of file LCLS.c.
doublereal z5em6
Definition at line 44 of file LCLS.c.
doublereal z6em1
Definition at line 44 of file LCLS.c.
doublereal z90
Definition at line 44 of file LCLS.c.
doublereal z9em1
Definition at line 44 of file LCLS.c.
doublereal z__[5]
Definition at line 18 of file LCLS.c.
doublereal zm1
Definition at line 44 of file LCLS.c.
struct { ... } znumbr_