My Project: LIBOPC.c File Reference
LIBOPC.c File Reference
#include "f2c.h"
Macros
#define filtab_1 filtab_
#define ifiltb_1 ifiltb_
#define libcom_1 libcom_
#define libfil_1 libfil_
Functions
int libopc_ (integer *ind, integer *flag__)
Variables
struct {
char filnam [480]
char filacc [300]
char filfmt [330]
char opstat [210]
char clstat [180]
} filtab_
struct {
integer u [30]
integer rl [30]
integer nxtrec [30]
integer lstrec [30]
} ifiltb_
struct {
integer ieof
} libcom_
struct {
char aptlib [11]
char filenm [40]
char memnam [8]
} libfil_
static integer c__2 = 2
Macro Definition Documentation
#define filtab_1 filtab_
Definition at line 21 of file LIBOPC.c.
Referenced by libopc_().
#define ifiltb_1 ifiltb_
Definition at line 27 of file LIBOPC.c.
Referenced by libopc_().
#define libcom_1 libcom_
Definition at line 33 of file LIBOPC.c.
#define libfil_1 libfil_
Definition at line 39 of file LIBOPC.c.
Referenced by libopc_().
Function Documentation
int libopc_ (integer * ind, integer * flag__)
Definition at line 47 of file LIBOPC.c.
References c__2, filtab_1, id, ifiltb_1, and libfil_1.
Referenced by epilog_(), pro027_(), and resred_().
 {
     /* System generated locals */
     address a__1[2];
     integer i__1[2];
     char ch__1[16];
     cllist cl__1;
     inlist ioin__1;
     /* Builtin functions */
     /* Subroutine */ int s_cat(char *, char **, integer *, integer *, ftnlen);
     integer f_inqu(inlist *), f_clos(cllist *);
     /* Local variables */
     static integer id;
     static logical od, ex;
 /*  * LIBOPC *  VAX-11 FORTRAN VERSION  27.09.82  E.MCLELLAN */
 /*              PORTABLE F77 VERSION REVISED  8-OCT-1987 E.MCLELLAN */
 /*  PURPOSE     TO CHECK THE EXISTENCE OF APTLIB */
 /*              OR CLOSE UNIT REFERENCING APTLIB */
 /*  CALLING SEQUENCE */
 /*              CALL LIBOPC(IND,FLAG) */
 /*  ARGUMENTS */
 /*              IND   =1 DOES APTLIB EXIST */
 /*                    =2 CLOSE UNIT WHICH REFERENCES APTLIB */
 /*              FLAG  =0 APTLIB EXISTS */
 /*                    =1 APTLIB DOES NOT EXIST */
 /*                    =2 NOT USED */
 /*                    =3 ALREADY CLOSED (IND=2) */
 /*                    =4 IND IS NOT 1 OR 2 */
 /*  *  FILE ATTRIBUTES  * */
 /* .....UNIT NUMBER FOR APTLIB */
     id = ifiltb_1.u[23];
     if (*ind == 1) {
 /* .....DOES APTLIB EXIST */
     ioin__1.inerr = 0;
     ioin__1.infilen = 16;
 /* Writing concatenation */
     i__1[0] = 11, a__1[0] = libfil_1.aptlib;
     i__1[1] = 5, a__1[1] = "INDEX";
     s_cat(ch__1, a__1, i__1, &c__2, (ftnlen)16);
     ioin__1.infile = ch__1;
     ioin__1.inex = &ex;
     ioin__1.inopen = 0;
     ioin__1.innum = 0;
     ioin__1.innamed = 0;
     ioin__1.inname = 0;
     ioin__1.inacc = 0;
     ioin__1.inseq = 0;
     ioin__1.indir = 0;
     ioin__1.infmt = 0;
     ioin__1.inform = 0;
     ioin__1.inunf = 0;
     ioin__1.inrecl = 0;
     ioin__1.innrec = 0;
     ioin__1.inblank = 0;
     f_inqu(&ioin__1);
     if (ex) {
 /* .....APTLIB EXISTS */
         *flag__ = 0;
         return 0;
     } else {
 /* .....APTLIB DOES NOT EXIST */
         *flag__ = 1;
         return 0;
     }
     } else if (*ind == 2) {
 /* .....IS UNIT OPEN */
     ioin__1.inerr = 0;
     ioin__1.inunit = id;
     ioin__1.infile = 0;
     ioin__1.inex = 0;
     ioin__1.inopen = &od;
     ioin__1.innum = 0;
     ioin__1.innamed = 0;
     ioin__1.inname = 0;
     ioin__1.inacc = 0;
     ioin__1.inseq = 0;
     ioin__1.indir = 0;
     ioin__1.infmt = 0;
     ioin__1.inform = 0;
     ioin__1.inunf = 0;
     ioin__1.inrecl = 0;
     ioin__1.innrec = 0;
     ioin__1.inblank = 0;
     f_inqu(&ioin__1);
     if (od) {
 /* .....CLOSE UNIT */
         cl__1.cerr = 0;
         cl__1.cunit = id;
         cl__1.csta = filtab_1.clstat + 138;
         f_clos(&cl__1);
         return 0;
     } else {
 /* .....UNIT ALREADY CLOSED */
         *flag__ = 3;
         return 0;
     }
     } else {
 /* .....IND NOT 1 OR 2 */
     *flag__ = 4;
     }
     return 0;
 } /* libopc_ */
Variable Documentation
char aptlib[11]
Definition at line 36 of file LIBOPC.c.
integer c__2 = 2 static
Definition at line 43 of file LIBOPC.c.
Referenced by libopc_().
char clstat[180]
Definition at line 18 of file LIBOPC.c.
char filacc[300]
Definition at line 18 of file LIBOPC.c.
char filenm[40]
Definition at line 36 of file LIBOPC.c.
char filfmt[330]
Definition at line 18 of file LIBOPC.c.
char filnam[480]
Definition at line 18 of file LIBOPC.c.
struct { ... } filtab_
integer ieof
Definition at line 30 of file LIBOPC.c.
struct { ... } ifiltb_
struct { ... } libcom_
struct { ... } libfil_
integer lstrec[30]
Definition at line 24 of file LIBOPC.c.
char memnam[8]
Definition at line 36 of file LIBOPC.c.
integer nxtrec[30]
Definition at line 24 of file LIBOPC.c.
char opstat[210]
Definition at line 18 of file LIBOPC.c.
integer rl[30]
Definition at line 24 of file LIBOPC.c.
integer u[30]
Definition at line 24 of file LIBOPC.c.