My Project: LINKF.c File Reference
LINKF.c File Reference
#include "f2c.h"
Macros
#define darray_1 darray_
Functions
int linkf_ (char *phase, ftnlen phase_len)
Variables
struct {
char darray [120]
} darray_
static integer c__1 = 1
static integer c__25 = 25
static integer c__26 = 26
static integer c__18 = 18
static integer c__43 = 43
static integer c__8 = 8
Macro Definition Documentation
#define darray_1 darray_
Definition at line 21 of file LINKF.c.
Referenced by linkf_().
Function Documentation
int linkf_ (char * phase, ftnlen phase_len)
Definition at line 52 of file LINKF.c.
References abnend_(), acntrl_(), c__1, c__18, c__25, c__26, c__43, c__8, cform_(), cled_(), cprint_(), darray_1, exec_(), and start_().
Referenced by sprvis_0_().
 {
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     extern /* Subroutine */ int cled_(void), exec_(void), cform_(char *, char
         *, integer *, integer *, ftnlen, ftnlen), start_(void), abnend_(
         void), acntrl_(void), cprint_(char *, ftnlen);
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
     if (s_cmp(phase, "TRANSLAT", (ftnlen)8, (ftnlen)8) == 0) {
     start_();
     } else if (s_cmp(phase, "XECUTION", (ftnlen)8, (ftnlen)8) == 0) {
     exec_();
     } else if (s_cmp(phase, "CLEDITOR", (ftnlen)8, (ftnlen)8) == 0) {
     cled_();
     } else if (s_cmp(phase, "POSTEXEC", (ftnlen)8, (ftnlen)8) == 0) {
     acntrl_();
     } else {
     cform_("  *** FAILURE IN LINKF - ", darray_1.darray, &c__1, &c__25, (
         ftnlen)25, (ftnlen)120);
     cform_("REQUESTED PHASE = ", darray_1.darray, &c__26, &c__18, (ftnlen)
         18, (ftnlen)120);
     cform_(phase, darray_1.darray, &c__43, &c__8, (ftnlen)8, (ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     abnend_();
     }
     return 0;
 } /* linkf_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 25 of file LINKF.c.
Referenced by linkf_().
integer c__18 = 18 static
Definition at line 28 of file LINKF.c.
Referenced by linkf_().
integer c__25 = 25 static
Definition at line 26 of file LINKF.c.
Referenced by linkf_().
integer c__26 = 26 static
Definition at line 27 of file LINKF.c.
Referenced by linkf_().
integer c__43 = 43 static
Definition at line 29 of file LINKF.c.
Referenced by linkf_().
integer c__8 = 8 static
Definition at line 30 of file LINKF.c.
Referenced by linkf_().
char darray[120]
Definition at line 18 of file LINKF.c.
struct { ... } darray_