My Project: LNTHF.c File Reference
LNTHF.c File Reference
#include "f2c.h"
Macros
#define znumbr_1 znumbr_
#define knumbr_1 knumbr_
Functions
int lnthf_ (doublereal *res, doublereal *arg)
Variables
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__56 = 56
Macro Definition Documentation
#define knumbr_1 knumbr_
Definition at line 31 of file LNTHF.c.
#define znumbr_1 znumbr_
Definition at line 23 of file LNTHF.c.
Referenced by lnthf_().
Function Documentation
int lnthf_ (doublereal * res, doublereal * arg)
Definition at line 55 of file LNTHF.c.
References c__56, ckdef_(), error_(), and znumbr_1.
Referenced by xcall_().
 {
     /* System generated locals */
     doublereal d__1, d__2, d__3;
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /* ...     CHECK DEFINITION OF INPUT VECTOR */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --arg;
     /* Function Body */
     if (ckdef_(&arg[1])) {
     goto L20;
     }
 /* ...     COMPUTE LENGTH OF VECTOR */
 /* Computing 2nd power */
     d__1 = arg[1];
 /* Computing 2nd power */
     d__2 = arg[2];
 /* Computing 2nd power */
     d__3 = arg[3];
     *res = sqrt(d__1 * d__1 + d__2 * d__2 + d__3 * d__3);
     goto L9;
 /* ...     DIAGNOSE UNDEFINED INPUT */
 L20:
     error_(&c__56, "LNTHF   ", (ftnlen)8);
     *res = znumbr_1.z0;
 L9:
     return 0;
 } /* lnthf_ */
Variable Documentation
integer c__56 = 56 static
Definition at line 35 of file LNTHF.c.
Referenced by lnthf_().
doublereal degrad
Definition at line 18 of file LNTHF.c.
integer k0
Definition at line 26 of file LNTHF.c.
integer k1
Definition at line 26 of file LNTHF.c.
integer k10
Definition at line 26 of file LNTHF.c.
integer k1013
Definition at line 26 of file LNTHF.c.
integer k12
Definition at line 26 of file LNTHF.c.
integer k13
Definition at line 26 of file LNTHF.c.
integer k15
Definition at line 26 of file LNTHF.c.
integer k16
Definition at line 26 of file LNTHF.c.
integer k18
Definition at line 26 of file LNTHF.c.
integer k19
Definition at line 26 of file LNTHF.c.
integer k1e4
Definition at line 26 of file LNTHF.c.
integer k1e6
Definition at line 26 of file LNTHF.c.
integer k2
Definition at line 26 of file LNTHF.c.
integer k23
Definition at line 26 of file LNTHF.c.
integer k24
Definition at line 26 of file LNTHF.c.
integer k25
Definition at line 26 of file LNTHF.c.
integer k26
Definition at line 26 of file LNTHF.c.
integer k27
Definition at line 26 of file LNTHF.c.
integer k29
Definition at line 26 of file LNTHF.c.
integer k3
Definition at line 26 of file LNTHF.c.
integer k30
Definition at line 26 of file LNTHF.c.
integer k31
Definition at line 26 of file LNTHF.c.
integer k32
Definition at line 26 of file LNTHF.c.
integer k33
Definition at line 26 of file LNTHF.c.
integer k34
Definition at line 26 of file LNTHF.c.
integer k4
Definition at line 26 of file LNTHF.c.
integer k44
Definition at line 26 of file LNTHF.c.
integer k45
Definition at line 26 of file LNTHF.c.
integer k46
Definition at line 26 of file LNTHF.c.
integer k47
Definition at line 26 of file LNTHF.c.
integer k48
Definition at line 26 of file LNTHF.c.
integer k5
Definition at line 26 of file LNTHF.c.
integer k50
Definition at line 26 of file LNTHF.c.
integer k51
Definition at line 26 of file LNTHF.c.
integer k52
Definition at line 26 of file LNTHF.c.
integer k6
Definition at line 26 of file LNTHF.c.
integer k7
Definition at line 26 of file LNTHF.c.
integer k8
Definition at line 26 of file LNTHF.c.
integer k9
Definition at line 26 of file LNTHF.c.
integer km1
Definition at line 26 of file LNTHF.c.
struct { ... } knumbr_
doublereal pi
Definition at line 18 of file LNTHF.c.
doublereal z0
Definition at line 18 of file LNTHF.c.
doublereal z1
Definition at line 18 of file LNTHF.c.
doublereal z10
Definition at line 18 of file LNTHF.c.
doublereal z11em1
Definition at line 18 of file LNTHF.c.
doublereal z12em1
Definition at line 18 of file LNTHF.c.
doublereal z1e38
Definition at line 18 of file LNTHF.c.
doublereal z1e6
Definition at line 18 of file LNTHF.c.
doublereal z1em1
Definition at line 18 of file LNTHF.c.
doublereal z1em2
Definition at line 18 of file LNTHF.c.
doublereal z1em3
Definition at line 18 of file LNTHF.c.
doublereal z1em5
Definition at line 18 of file LNTHF.c.
doublereal z1em6
Definition at line 18 of file LNTHF.c.
doublereal z1em7
Definition at line 18 of file LNTHF.c.
doublereal z1em9
Definition at line 18 of file LNTHF.c.
doublereal z2
Definition at line 18 of file LNTHF.c.
doublereal z3
Definition at line 18 of file LNTHF.c.
doublereal z5
Definition at line 18 of file LNTHF.c.
doublereal z5em1
Definition at line 18 of file LNTHF.c.
doublereal z5em6
Definition at line 18 of file LNTHF.c.
doublereal z6em1
Definition at line 18 of file LNTHF.c.
doublereal z90
Definition at line 18 of file LNTHF.c.
doublereal z9em1
Definition at line 18 of file LNTHF.c.
doublereal zm1
Definition at line 18 of file LNTHF.c.
struct { ... } znumbr_