My Project: MACLBL.c File Reference
MACLBL.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
Functions
int maclbl_ (integer *label1, integer *label2, integer *label3)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
static integer c__15 = 15
static integer c__0 = 0
static integer c__8 = 8
Macro Definition Documentation
#define cnamtb_1 cnamtb_
Definition at line 28 of file MACLBL.c.
#define nametb_1 nametb_
Definition at line 22 of file MACLBL.c.
Function Documentation
int maclbl_ (integer * label1, integer * label2, integer * label3)
Definition at line 59 of file MACLBL.c.
References alarm_(), blk, c__0, c__15, c__8, count, help_(), i__, name_(), and shift_().
Referenced by boolif_(), comstr_(), input_(), loop_(), macrec_(), match_(), mnproc_(), motion_(), path_(), pro026_(), pro027_(), recog_(), and recogn_().
 {
     /* Initialized data */
     static char blk[1] = " ";
     static char charac[1*12] = "0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "Z"
         "$";
     static integer count = 0;
     static integer tabl[1800]   /* was [3][600] */ = { 0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
         0,0,0,0,0,0,0 };
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, decr;
     static char find[8];
     extern integer name_(char *, ftnlen);
     extern /* Subroutine */ int help_(void), alarm_(integer *, integer *,
         integer *, char *, ftnlen), shift_(char *, char *, ftnlen, ftnlen)
         ;
     static integer intger, symbol;
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /* * */
 /* PURPOSE      TO CONSTRUCT A UNIQUE LABEL NAME CORRESPONDING */
 /*              TO AN ORDERED PAIR OF NUMBERS. */
 /* ARGUMENTS    LABEL1    IS THE FIRST NUMBER OF THE PAIR */
 /*              LABEL2    IS THE SECOND NUMBER OF THE PAIR */
 /*              LABEL3    WILL CONTAIN THE NAME TABLE (NAMTBL) */
 /*                        INDEX OF THE GENERATED LABEL. */
 /* ...  COUNT IS THE TOTAL NUMBER OF GENERATED LABELS. */
 /* ...  TABL IS AN ARRAY CONTAINING EACH UNIQUE PAIR OF ARGUMENTS */
 /* ...    RECEIVED AND THE CORRESPONDING NAMTBL INDEX FOR THE */
 /* ...    GENERATED LABEL. */
 /* ** */
 /* ... */
 /* ...      INITIALIZE FIND WITH BLANKS */
     s_copy(find, blk, (ftnlen)8, (ftnlen)1);
 /* ...      IF ARGUMENT PAIR ISIIN TABLE THEN BRANCH - RETURN NAMTBL INDEX */
     i__1 = count;
     for (i__ = 1; i__ <= i__1; ++i__) {
     if (tabl[i__ * 3 - 3] != *label1) {
         goto L100;
     }
     if (tabl[i__ * 3 - 2] == *label2) {
         goto L200;
     }
 L100:
     ;
     }
 /* ...      OTHERWISE PUT ARGUMENTS IN TABLE- GENERATE LABEL */
     ++count;
     if (count <= 600) {
     goto L105;
     }
 /* TABL LENGTH EXCEEDED.  TERMINATE PROGRAM */
     alarm_(&c__15, &c__0, &c__8, "MACLBL  ", (ftnlen)8);
     help_();
 L105:
     tabl[count * 3 - 3] = *label1;
     tabl[count * 3 - 2] = *label2;
 /* ...      SHIFT Z$ INTO 1ST TWO POSITIONS OF LABEL BEING GENERATED */
     for (i__ = 1; i__ <= 2; ++i__) {
     shift_(find, charac + (i__ + 9), (ftnlen)8, (ftnlen)1);
 /* L110: */
     }
 /* ...      SHIFT CHARACTER EQUIVALENT OF TABLE INDEX INTO LABEL */
     intger = count;
     decr = 1000;
     for (i__ = 1; i__ <= 4; ++i__) {
     symbol = intger / decr;
     shift_(find, charac + symbol, (ftnlen)8, (ftnlen)1);
     intger -= decr * symbol;
     decr /= 10;
 /* L120: */
     }
 /* ...      PUT NAMTBL INDEX CORRESPONDING TO GENERATED LABEL IN TABLE */
     tabl[count * 3 - 1] = name_(find, (ftnlen)8);
     i__ = count;
 /* ...      ASSIGN NAMTBL INDEX OF GENERATED LABEL TO RETURN PARAMETER */
 L200:
     *label3 = tabl[i__ * 3 - 1];
     return 0;
 } /* maclbl_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 33 of file MACLBL.c.
Referenced by maclbl_().
integer c__15 = 15 static
Definition at line 32 of file MACLBL.c.
Referenced by maclbl_().
integer c__8 = 8 static
Definition at line 34 of file MACLBL.c.
Referenced by maclbl_().
integer charnd
Definition at line 18 of file MACLBL.c.
integer charst
Definition at line 18 of file MACLBL.c.
char cnamtb[18000]
Definition at line 25 of file MACLBL.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file MACLBL.c.
integer ifixnd
Definition at line 18 of file MACLBL.c.
integer ifixst
Definition at line 18 of file MACLBL.c.
integer inamnd
Definition at line 18 of file MACLBL.c.
integer inamst
Definition at line 18 of file MACLBL.c.
integer namest
Definition at line 18 of file MACLBL.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file MACLBL.c.
integer namtbl[3000]
Definition at line 18 of file MACLBL.c.
integer numbnd
Definition at line 18 of file MACLBL.c.
integer numbst
Definition at line 18 of file MACLBL.c.