My Project: MCXTRN.c File Reference
MCXTRN.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define prt_1 prt_
#define macxx1_1 macxx1_
#define macxx2_1 macxx2_
#define symfil_1 symfil_
#define ntbl_1 ntbl_
#define nmod ((integer *)&ntbl_1)
#define nndx ((integer *)&ntbl_1 + 2)
#define mbrec ((integer *)&macxx2_1)
#define mbuff ((integer *)&macxx2_1 + 2)
#define nlast ((integer *)&ntbl_1 + 3)
#define mbptr ((integer *)&macxx1_1 + 29)
#define ncrnt ((integer *)&ntbl_1 + 1)
#define macrtb ((integer *)&macxx2_1 + 702)
#define assemb ((logical *)&prt_1 + 3)
Functions
int mcxtrn_ (integer *ibr, integer *index, integer *info)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer prt [7]
} prt_
struct {
integer macxx1 [71]
} macxx1_
struct {
integer macxx2 [902]
} macxx2_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
struct {
integer ntbl [6]
} ntbl_
static integer c__35 = 35
static integer c__0 = 0
static integer c__8 = 8
static integer c__350 = 350
static integer c_n2 = -2
static integer c__36 = 36
Macro Definition Documentation
#define assemb ((logical *)&prt_1 + 3)
Referenced by mcxtrn_().
#define cnamtb_1 cnamtb_
Definition at line 28 of file MCXTRN.c.
Referenced by mcxtrn_().
#define macrtb ((integer *)&macxx2_1 + 702)
Referenced by mcxtrn_().
#define macxx1_1 macxx1_
Definition at line 40 of file MCXTRN.c.
#define macxx2_1 macxx2_
Definition at line 46 of file MCXTRN.c.
#define mbptr ((integer *)&macxx1_1 + 29)
Referenced by mcxtrn_().
#define mbrec ((integer *)&macxx2_1)
Referenced by mcxtrn_().
#define mbuff ((integer *)&macxx2_1 + 2)
Referenced by mcxtrn_().
#define nametb_1 nametb_
Definition at line 22 of file MCXTRN.c.
Referenced by mcxtrn_().
#define ncrnt ((integer *)&ntbl_1 + 1)
Referenced by mcxtrn_().
#define nlast ((integer *)&ntbl_1 + 3)
Referenced by mcxtrn_().
#define nmod ((integer *)&ntbl_1)
Referenced by mcxtrn_().
#define nndx ((integer *)&ntbl_1 + 2)
Referenced by mcxtrn_().
#define ntbl_1 ntbl_
Definition at line 61 of file MCXTRN.c.
#define prt_1 prt_
Definition at line 34 of file MCXTRN.c.
#define symfil_1 symfil_
Definition at line 55 of file MCXTRN.c.
Referenced by mcxtrn_().
Function Documentation
int mcxtrn_ (integer * ibr, integer * index, integer * info)
Definition at line 95 of file MCXTRN.c.
References alarm_(), aread_(), assemb, awrite_(), c__0, c__35, c__350, c__36, c__8, c_n2, chwrit_(), cnamtb_1, help_(), i__, irec, itmp, iwrd, j, l, macrtb, mbptr, mbrec, mbuff, nametb_1, ncrnt, nlast, nmod, nndx, nrec, symfil_1, and tapop_().
Referenced by alarm_(), inpat_(), input_(), macrec_(), motion_(), oppair_(), pro026_(), pro027_(), recog_(), reserv_(), and resred_().
 {
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, j, l, irec, nrec;
     extern /* Subroutine */ int help_(void);
 #define nmod ((integer *)&ntbl_1)
     static integer iret, iwrd;
 #define nndx ((integer *)&ntbl_1 + 2)
     static integer itmp;
     extern /* Subroutine */ int aread_();
 #define mbrec ((integer *)&macxx2_1)
     extern /* Subroutine */ int alarm_(integer *, integer *, integer *, char *
         , ftnlen);
 #define mbuff ((integer *)&macxx2_1 + 2)
 #define nlast ((integer *)&ntbl_1 + 3)
     extern /* Subroutine */ int tapop_(integer *, integer *);
 #define mbptr ((integer *)&macxx1_1 + 29)
 #define ncrnt ((integer *)&ntbl_1 + 1)
 #define macrtb ((integer *)&macxx2_1 + 702)
 #define assemb ((logical *)&prt_1 + 3)
     extern /* Subroutine */ int awrite_(integer *, integer *, integer *,
         integer *, integer *);
     static integer ibrtmp;
     extern /* Subroutine */ int chwrit_(integer *, integer *, char *, integer
         *, integer *, ftnlen);
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /* NUMBST:      NAMTBL INDEX OF BEGINNING OF NUMBER SECTION */
 /*       14.    I. L. LIST OPTION FLAGS */
 /* ASSEMB:      SET TRUE INDICATES ASSEMBLY APPROACH (CONTRL/ASMBLE) */
 /*       22.    MACRO PROCESSING VARIABLES */
 /* MBPTR:       POINTER TO LAST MBREC ENTRY */
 /*       23.    MACRO PROCESSING ARRAYS */
 /* MBREC:       IDENTIFIES THE RECORDS(350 WORD BLK) CURRENTLY IN MBUFF */
 /* BUFF:        BUFFER ARRAY IN ORDER TO READ OR WRITE ON EXTERNAL FILE */
 /* MACRTB:      BUFFER ARRAY OF THE EXTERNAL FILE */
 /*       33.    SYMBOLIC FILE DEFINITIONS */
 /* MACTXT:          EXTERNAL FILE  OF MACRO TEXT */
 /* XNUM  :          OVERFLOW NUMBER TABLE */
 /*       41.    NUMBER TABLE OVERFLOW VARIABLES */
 /* ...                SYSTEM I/O FILES */
 /* NMOD:        NUMBER OF ENTRIES PERMITTED IN INTERNAL NUMBER TABLE */
 /* NCRNT:       ACTUAL NUMBER TABLE BLOCK - INITIALLY 1 */
 /* NNDX:        CONVERSION BETWEEN ABS. AND VIRTUAL NUMBER TABLE POINTER */
 /* NLAST:       LAST NEW BLOCK NUMBER OF NUMBER TABLE ON THE EXTERN FILE */
 /* * */
 /* ARGUMENTS    IBR     SET TO 1 FOR STORE, 2 FOR RETRIEVE */
 /*              INDEX   POINTER TO REFERENCED MACRO TEXT WORD */
 /*              INFO    DATA TO BE STORED OR RETRIEVED */
 /* ** */
     if (*ibr > 2) {
     goto L500;
     }
 /* ...     DETERMINE RECORD NUMBER AND WORD NUMBER */
     itmp = (*index - 1) / 350;
     irec = itmp + 1;
     if (irec < 200) {
     goto L10;
     }
     alarm_(&c__35, &c__0, &c__8, "MCXTRN  ", (ftnlen)8);
     help_();
 L10:
     iwrd = *index - itmp * 350;
 /* ...  IS THIS RECORD IN THE BUFFERS */
     if (irec == mbrec[*mbptr - 1]) {
     goto L100;
     }
     *mbptr = 3 - *mbptr;
     if (irec == mbrec[*mbptr - 1]) {
     goto L100;
     }
 /* ...  WRITE OLD BUFFER TO EXTERNAL FILE */
     i__ = mbrec[*mbptr - 1];
     if (macrtb[i__ - 1] != 0) {
     goto L20;
     }
     nrec = 0;
     awrite_(&symfil_1.mactxt, &nrec, &mbuff[*mbptr * 350 - 350], &c__350, &
         iret);
     macrtb[i__ - 1] = nrec;
 /* ...  RECORD INDICATOR INDICATES NEW RECORD NUMBER */
 L20:
     mbrec[*mbptr - 1] = irec;
     if (macrtb[irec - 1] > 0) {
     goto L30;
     }
     if (*ibr == 2) {
     alarm_(&c__35, &c__0, &c__8, "MCXTRN  ", (ftnlen)8);
     }
     goto L100;
 /* ...  READ IN RECORD */
 L30:
     aread_(&symfil_1.mactxt, &macrtb[irec - 1], &mbuff[*mbptr * 350 - 350], &
         c__350, &iret);
 L100:
     if (*ibr == 2) {
     goto L200;
     }
 /* ...  STORE INFO */
     mbuff[iwrd + *mbptr * 350 - 351] = *info;
     if (macrtb[irec - 1] != 0) {
     macrtb[irec - 1] = 0;
     }
     goto L400;
 /* ...  READ INFO */
 L200:
     *info = mbuff[iwrd + *mbptr * 350 - 351];
     goto L400;
 /* ...     NUMBER TABLE OVERFLOW PROCESSING */
 L500:
     ibrtmp = *ibr - 2;
     switch (ibrtmp) {
     case 1:  goto L530;
     case 2:  goto L540;
     case 3:  goto L550;
     case 4:  goto L560;
     }
 /* ...  WRITE FIRST PART OF TABLE */
 L530:
     l = *nmod * 6;
     j = 0;
 /* ... 4TH ARGUMENT OF CHWRIT IS NUMBER OF BYTES */
     chwrit_(&symfil_1.xnum, &j, cnamtb_1.cnumtb + (nametb_1.numbst - 1) * 12,
         &l, &iret, (ftnlen)12);
     ++(*nlast);
     *nndx += *nmod / 2;
     l = nametb_1.numbst + *nmod / 2 - 1;
     i__1 = l;
     for (i__ = nametb_1.numbst; i__ <= i__1; ++i__) {
     s_copy(cnamtb_1.cnumtb + (i__ - 1) * 12, " ", (ftnlen)12, (ftnlen)1);
 /* L544: */
     }
     goto L400;
 /* .... WRITE SECOND PART OF TABLE */
 L540:
     if (*assemb) {
     goto L805;
     }
     j = 0;
     i__ = nametb_1.numbst + *nmod / 2;
     l = *nmod * 6;
 /* ... 4TH ARGUMENT OF CHWRIT IS NUMBER OF BYTES */
     chwrit_(&symfil_1.xnum, &j, cnamtb_1.cnumtb + (i__ - 1) * 12, &l, &iret, (
         ftnlen)12);
     ++(*nlast);
     *nndx += *nmod / 2;
     *ncrnt = 2;
     goto L400;
 /* .... READ IN BLOCK CONTAINING INDEX */
 L550:
     l = *nmod / 2;
     if (*index < nametb_1.numbst) {
     goto L400;
     }
     itmp = (*index - nametb_1.numbst) / l;
     *index -= itmp * l;
     if (itmp == *nlast) {
     goto L400;
     }
     *index += l;
     if (itmp + 1 == *ncrnt) {
     goto L400;
     }
     nrec = itmp + 1;
     i__ = nametb_1.numbst + l;
     l *= 12;
 /* ... 4TH ARGUMENT OF CHREAD IS NUMBER OF BYTES */
     aread_(&symfil_1.xnum, &nrec, cnamtb_1.cnumtb + (i__ - 1) * 12, &l, &iret)
         ;
     *ncrnt = nrec;
     goto L400;
 /* .... WRITE OUT FINAL RECORD */
 L560:
     tapop_(&symfil_1.xnum, &c_n2);
 L400:
     return 0;
 L805:
     alarm_(&c__36, &c__0, &c__8, "MCXTRN  ", (ftnlen)8);
     help_();
     return 0;
 } /* mcxtrn_ */
Variable Documentation
integer axfile
Definition at line 49 of file MCXTRN.c.
integer c__0 = 0 static
Definition at line 66 of file MCXTRN.c.
Referenced by mcxtrn_().
integer c__35 = 35 static
Definition at line 65 of file MCXTRN.c.
Referenced by mcxtrn_().
integer c__350 = 350 static
Definition at line 68 of file MCXTRN.c.
Referenced by mcxtrn_().
integer c__36 = 36 static
Definition at line 70 of file MCXTRN.c.
Referenced by mcxtrn_().
integer c__8 = 8 static
Definition at line 67 of file MCXTRN.c.
Referenced by mcxtrn_().
integer c_n2 = -2 static
Definition at line 69 of file MCXTRN.c.
Referenced by mcxtrn_().
integer charnd
Definition at line 18 of file MCXTRN.c.
integer charst
Definition at line 18 of file MCXTRN.c.
integer clfil3
Definition at line 49 of file MCXTRN.c.
integer clfile
Definition at line 49 of file MCXTRN.c.
integer clfilp
Definition at line 49 of file MCXTRN.c.
char cnamtb[18000]
Definition at line 25 of file MCXTRN.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file MCXTRN.c.
integer cpfile
Definition at line 49 of file MCXTRN.c.
integer elfil1
Definition at line 49 of file MCXTRN.c.
integer elfil2
Definition at line 49 of file MCXTRN.c.
integer elfil3
Definition at line 49 of file MCXTRN.c.
integer elfil4
Definition at line 49 of file MCXTRN.c.
integer elfile
Definition at line 49 of file MCXTRN.c.
integer exfile
Definition at line 49 of file MCXTRN.c.
integer ifixnd
Definition at line 18 of file MCXTRN.c.
integer ifixst
Definition at line 18 of file MCXTRN.c.
integer inamnd
Definition at line 18 of file MCXTRN.c.
integer inamst
Definition at line 18 of file MCXTRN.c.
integer infile__
Definition at line 49 of file MCXTRN.c.
integer ispare[26]
Definition at line 49 of file MCXTRN.c.
integer ldafil
Definition at line 49 of file MCXTRN.c.
integer libfil
Definition at line 49 of file MCXTRN.c.
integer mactxt
Definition at line 49 of file MCXTRN.c.
integer macxx1[71]
Definition at line 37 of file MCXTRN.c.
struct { ... } macxx1_
integer macxx2[902]
Definition at line 43 of file MCXTRN.c.
struct { ... } macxx2_
integer namest
Definition at line 18 of file MCXTRN.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file MCXTRN.c.
integer namtbl[3000]
Definition at line 18 of file MCXTRN.c.
integer nfil12
Definition at line 49 of file MCXTRN.c.
integer nfil13
Definition at line 49 of file MCXTRN.c.
integer ntbl[6]
Definition at line 58 of file MCXTRN.c.
struct { ... } ntbl_
integer numbnd
Definition at line 18 of file MCXTRN.c.
integer numbst
Definition at line 18 of file MCXTRN.c.
integer pnchfl
Definition at line 49 of file MCXTRN.c.
integer pofile
Definition at line 49 of file MCXTRN.c.
integer prt[7]
Definition at line 31 of file MCXTRN.c.
struct { ... } prt_
integer pxfile
Definition at line 49 of file MCXTRN.c.
struct { ... } symfil_
integer tifile
Definition at line 49 of file MCXTRN.c.
integer vlfile
Definition at line 49 of file MCXTRN.c.
integer xcan
Definition at line 49 of file MCXTRN.c.
integer xnum
Definition at line 49 of file MCXTRN.c.