My Project: MESCON.c File Reference
MESCON.c File Reference
#include "f2c.h"
Macros
#define ibugg_1 ibugg_
Functions
int mescon_ (doublereal *surf, doublereal *u, doublereal *v, integer *npat, doublereal *u1, doublereal *v1, integer *mode)
Variables
struct {
integer ibug
integer ipcolc
integer ipcolm
} ibugg_
static integer c_n1 = -1
static integer c__0 = 0
static integer c__1 = 1
Macro Definition Documentation
#define ibugg_1 ibugg_
Definition at line 21 of file MESCON.c.
Referenced by mescon_().
Function Documentation
int mescon_ (doublereal * surf, doublereal * u, doublereal * v, integer * npat, doublereal * u1, doublereal * v1, integer * mode)
Definition at line 31 of file MESCON.c.
References bad_(), c__0, c__1, c_n1, cprint_(), ibugg_1, one, and two.
Referenced by dgeom_(), and midpnt_().
 {
     /* Initialized data */
     static doublereal one = 1.;
     static doublereal two = 2.;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer iu, iv;
     extern /* Subroutine */ int bad_();
     static doublereal base, acrs, aspl;
     static char badmsg[20];
     extern /* Subroutine */ int cprint_(char *, ftnlen);
     static integer numcrs, numspl;
 /* --PURPOSE IS TO CONVERT GLOBAL MESH COORDINATES U,V */
 /* --INTO LOCAL PATCH NUMBER(NPAT) AND LOCAL PATCH COORDINATES */
 /* --U1,V1 IF MODE IS 1.  OTHERWISE THE REVERSE IF MODE IS 2 */
     /* Parameter adjustments */
     --surf;
     /* Function Body */
     numspl = (integer) surf[9];
     numcrs = (integer) surf[10];
     acrs = surf[10] - two;
     aspl = surf[9] - two;
     if (*mode > 1) {
     goto L100;
     }
 /* --CONVERT GLOBAL U,V TO LOCAL PATCH NUMBER NPAT AND LOCAL U1,V1 */
     iu = 1;
     if (*u < one) {
     goto L10;
     }
     iu = numcrs - 1;
     if (*u >= acrs) {
     goto L10;
     }
     iu = (integer) (*u) + 1;
 L10:
     base = (doublereal) (iu - 1);
     *u1 = *u - base;
     iv = 1;
     if (*v < one) {
     goto L20;
     }
     iv = numspl - 1;
     if (*v >= aspl) {
     goto L20;
     }
     iv = (integer) (*v) + 1;
 L20:
     base = (doublereal) (iv - 1);
     *v1 = *v - base;
     *npat = iu + (iv - 1) * (numcrs - 1);
     goto L999;
 L100:
 /* --CONVERT NPAT,U1,V1 TO GLOBAL U,V */
     iu = (*npat - 1) % (numcrs - 1) + 1;
     iv = (*npat - 1) / (numcrs - 1) + 1;
     *u = *u1 + iu - 1;
     *v = *v1 + iv - 1;
 L999:
     if (ibugg_1.ibug != 11) {
     goto L1999;
     }
     bad_(&c_n1, &c__0, " ", &c__0, (ftnlen)1);
     s_copy(badmsg, " AFTER MESCON", (ftnlen)20, (ftnlen)13);
     cprint_(badmsg, (ftnlen)20);
     bad_(&c__1, &c__1, "U   ", u, (ftnlen)4);
     bad_(&c__1, &c__1, "V   ", v, (ftnlen)4);
     bad_(&c__1, &c__0, "NPAT", npat, (ftnlen)4);
     bad_(&c__1, &c__1, "U1  ", u1, (ftnlen)4);
     bad_(&c_n1, &c__1, "V1  ", v1, (ftnlen)4);
     bad_(&c_n1, &c__0, "MODE", mode, (ftnlen)4);
 L1999:
     return 0;
 } /* mescon_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 26 of file MESCON.c.
Referenced by mescon_().
integer c__1 = 1 static
Definition at line 27 of file MESCON.c.
Referenced by mescon_().
integer c_n1 = -1 static
Definition at line 25 of file MESCON.c.
Referenced by mescon_().
integer ibug
Definition at line 18 of file MESCON.c.
struct { ... } ibugg_
integer ipcolc
Definition at line 18 of file MESCON.c.
integer ipcolm
Definition at line 18 of file MESCON.c.