My Project: MIDKUR.c File Reference
MIDKUR.c File Reference
#include "f2c.h"
Macros
#define ibugg_1 ibugg_
Functions
int midkur_ (doublereal *r__, doublereal *p0, doublereal *p1, doublereal *side, doublereal *sk)
Variables
struct {
integer ibug
integer ipcolc
integer ipcolm
} ibugg_
static integer c_n1 = -1
static integer c__1 = 1
Macro Definition Documentation
#define ibugg_1 ibugg_
Definition at line 21 of file MIDKUR.c.
Referenced by midkur_().
Function Documentation
int midkur_ (doublereal * r__, doublereal * p0, doublereal * p1, doublereal * side, doublereal * sk)
Definition at line 30 of file MIDKUR.c.
References bad_(), c__1, c_n1, cprint_(), cross_(), dotf_(), i__, ibugg_1, kursrf_(), p1, r__, and vnorm_().
Referenced by gchk_().
 {
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__;
     static doublereal ch[3], sx[24];
     extern /* Subroutine */ int bad_(integer *, integer *, char *, doublereal
         *, ftnlen);
     static doublereal vec[3];
     extern /* Subroutine */ int dotf_(doublereal *, doublereal *, doublereal *
         );
     static doublereal xcos, xsin;
     extern /* Subroutine */ int cross_(doublereal *, doublereal *, doublereal
         *), vnorm_(doublereal *, doublereal *);
     static char badmsg[20];
     extern /* Subroutine */ int cprint_(char *, ftnlen), kursrf_(doublereal *,
          doublereal *, doublereal *);
 /* .... COMPUTE PRINCIPLE CURVATURES ETC. AT MIDPOINT, R */
 /* .... DEBUG FLAGS */
     /* Parameter adjustments */
     --p1;
     --p0;
     --r__;
     /* Function Body */
     kursrf_(&r__[1], side, sx);
 /* .... COMPUTE CHORD DIRECTION */
     for (i__ = 1; i__ <= 3; ++i__) {
     ch[i__ - 1] = p1[i__] - p0[i__];
 /* L10: */
     }
     vnorm_(ch, ch);
 /* .... PROJECT CHORD VECTOR INTO SURFACE TANGENT PLANE */
     cross_(&r__[29], ch, vec);
     for (i__ = 1; i__ <= 3; ++i__) {
     vec[i__ - 1] = *side * vec[i__ - 1];
 /* L20: */
     }
     cross_(vec, &r__[29], vec);
     vnorm_(vec, vec);
 /* .... COMPUTE CURVATURE OF SURFACE IN DIRECTION OF CHORD */
     dotf_(&xcos, vec, &sx[4]);
     dotf_(&xsin, vec, &sx[8]);
     *sk = sx[0] * xcos * xcos + sx[1] * xsin * xsin;
     if (ibugg_1.ibug == 11) {
     s_copy(badmsg, " AFTER MIDKUR", (ftnlen)20, (ftnlen)13);
     cprint_(badmsg, (ftnlen)20);
     bad_(&c_n1, &c__1, "SK  ", sk, (ftnlen)4);
     }
     return 0;
 } /* midkur_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 26 of file MIDKUR.c.
Referenced by midkur_().
integer c_n1 = -1 static
Definition at line 25 of file MIDKUR.c.
Referenced by midkur_().
integer ibug
Definition at line 18 of file MIDKUR.c.
struct { ... } ibugg_
integer ipcolc
Definition at line 18 of file MIDKUR.c.
integer ipcolm
Definition at line 18 of file MIDKUR.c.