My Project: MIDPNT.c File Reference
MIDPNT.c File Reference
#include "f2c.h"
Macros
#define ibugg_1 ibugg_
Functions
int midpnt_ (doublereal *surf, integer *npat, doublereal *up, doublereal *vp, integer *npatl, doublereal *upl, doublereal *vpl, doublereal *rm)
Variables
struct {
integer ibug
integer ipcolc
integer ipcolm
} ibugg_
static integer c__2 = 2
static integer c__1 = 1
static integer c__0 = 0
static integer c_n1 = -1
static integer c_n3 = -3
Macro Definition Documentation
#define ibugg_1 ibugg_
Definition at line 21 of file MIDPNT.c.
Referenced by midpnt_().
Function Documentation
int midpnt_ (doublereal * surf, integer * npat, doublereal * up, doublereal * vp, integer * npatl, doublereal * upl, doublereal * vpl, doublereal * rm)
Definition at line 33 of file MIDPNT.c.
References b, bad_(), c__0, c__1, c__2, c_n1, c_n3, cnsurf_(), cprint_(), f, ibugg_1, iflag, itop, lodpch_(), mescon_(), u, u1, u2, v, v1, and v2.
Referenced by gchk_().
 {
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static doublereal b[64], u, v, u1, v1, u2, v2, um, vm;
     extern /* Subroutine */ int bad_();
     static integer itop[24] /* was [6][4] */, iflag[6], npatm;
     static char badmsg[20];
     extern /* Subroutine */ int lodpch_(doublereal *, doublereal *, integer *,
          integer *, integer *, integer *), mescon_(doublereal *,
         doublereal *, doublereal *, integer *, doublereal *, doublereal *,
          integer *), cprint_(char *, ftnlen), cnsurf_(doublereal *,
         doublereal *, doublereal *, doublereal *, integer *, integer *);
 /* .... COMPUTE GLOBAL PARAMETERS FOR CURRENT AND PREVIOUS POINTS */
 /* .... DEBUG FLAGS */
     /* Parameter adjustments */
     --rm;
     --surf;
     /* Function Body */
     mescon_(&surf[1], &u1, &v1, npat, up, vp, &c__2);
     mescon_(&surf[1], &u2, &v2, npatl, upl, vpl, &c__2);
 /* .... COMPUTE GLOBAL PARAMETERS OF MIDPOINT */
     u = (u1 + u2) / 2.f;
     v = (v1 + v2) / 2.f;
 /* .... COMPUTE PATCH NUMBER AND LOCAL PARAMETERS FOR MIDPOINT */
     mescon_(&surf[1], &u, &v, &npatm, &um, &vm, &c__1);
 /* .... LOAD PATCH COEFFICIENTS */
     lodpch_(&surf[1], b, iflag, itop, &npatm, &c__0);
 /* .... EVALUATE COORDINATES OF MIDPOINT */
     cnsurf_(&um, &vm, b, &rm[1], iflag, &c__1);
     if (ibugg_1.ibug == 11) {
     s_copy(badmsg, " AFTER MIDPNT", (ftnlen)20, (ftnlen)13);
     cprint_(badmsg, (ftnlen)20);
     bad_(&c__1, &c__0, "NPAT", npat, (ftnlen)4);
     bad_(&c__1, &c__1, "UP  ", up, (ftnlen)4);
     bad_(&c_n1, &c__1, "VP  ", vp, (ftnlen)4);
     bad_(&c__1, &c__0, "NPTL", npatl, (ftnlen)4);
     bad_(&c__1, &c__1, "UPL ", upl, (ftnlen)4);
     bad_(&c_n1, &c__1, "VPL ", vpl, (ftnlen)4);
     bad_(&c__1, &c__0, "NPTM", &npatm, (ftnlen)4);
     bad_(&c__1, &c__1, "UM  ", &um, (ftnlen)4);
     bad_(&c_n1, &c__1, "VM  ", &vm, (ftnlen)4);
     bad_(&c_n3, &c__1, "RM  ", &rm[1], (ftnlen)4);
     }
     return 0;
 } /* midpnt_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 27 of file MIDPNT.c.
Referenced by midpnt_().
integer c__1 = 1 static
Definition at line 26 of file MIDPNT.c.
Referenced by midpnt_().
integer c__2 = 2 static
Definition at line 25 of file MIDPNT.c.
Referenced by midpnt_().
integer c_n1 = -1 static
Definition at line 28 of file MIDPNT.c.
Referenced by midpnt_().
integer c_n3 = -3 static
Definition at line 29 of file MIDPNT.c.
Referenced by midpnt_().
integer ibug
Definition at line 18 of file MIDPNT.c.
struct { ... } ibugg_
integer ipcolc
Definition at line 18 of file MIDPNT.c.
integer ipcolm
Definition at line 18 of file MIDPNT.c.