My Project: MODE.c File Reference
MODE.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define code_1 code_
#define modx_1 modx_
#define moduli_1 moduli_
#define vbl ((integer *)&code_1 + 60)
#define real__ ((integer *)&modx_1 + 20)
#define temp ((integer *)&code_1 + 32)
#define modhlf ((integer *)&moduli_1 + 1)
#define number ((integer *)&code_1 + 26)
#define modulo ((integer *)&moduli_1)
Functions
integer mode_ (integer *index)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer code [150]
} code_
struct {
integer modx [32]
} modx_
struct {
integer moduli [2]
} moduli_
Macro Definition Documentation
#define cnamtb_1 cnamtb_
Definition at line 28 of file MODE.c.
#define code_1 code_
Definition at line 34 of file MODE.c.
#define modhlf ((integer *)&moduli_1 + 1)
Referenced by mode_().
#define moduli_1 moduli_
Definition at line 46 of file MODE.c.
#define modulo ((integer *)&moduli_1)
Referenced by mode_().
#define modx_1 modx_
Definition at line 40 of file MODE.c.
#define nametb_1 nametb_
Definition at line 22 of file MODE.c.
Referenced by mode_().
#define number ((integer *)&code_1 + 26)
Referenced by mode_().
#define real__ ((integer *)&modx_1 + 20)
Referenced by mode_().
#define temp ((integer *)&code_1 + 32)
Referenced by mode_().
#define vbl ((integer *)&code_1 + 60)
Referenced by mode_().
Function Documentation
integer mode_ (integer * index)
Definition at line 76 of file MODE.c.
References k, modhlf, modulo, nametb_1, number, real__, temp, and vbl.
Referenced by boolif_(), inpat_(), larges_(), lcanon_(), loop_(), macrec_(), match_(), motion_(), pro020_(), pro021_(), pro026_(), pro027_(), pro028_(), recog_(), recogn_(), refref_(), replac_(), resred_(), and subcod_().
 {
     /* System generated locals */
     integer ret_val;
     /* Local variables */
     static integer k;
 #define vbl ((integer *)&code_1 + 60)
 #define real__ ((integer *)&modx_1 + 20)
 #define temp ((integer *)&code_1 + 32)
 #define modhlf ((integer *)&moduli_1 + 1)
 #define number ((integer *)&code_1 + 26)
 #define modulo ((integer *)&moduli_1)
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /* NAMMAX:      NAMTBL INDEX OF END OF THE PART PROGRAM NAME SECTION */
 /*        3.    METALINGUISTIC VARIABLE CLASS CODES */
 /* NUMBER:      (1)=CODE CLASS 14000,(2)=NAMTBL INDEX OF 'NUMBER' */
 /* TEMP:        (1)=CODE CLASS 17000,(2)=NAMTBL INDEX OF 'TEMP  ' */
 /* VBL:         (1)=CODE CLASS 31000,(2)=NAMTBL INDEX OF 'VBL   ' */
 /*       17.    MODE CODES */
 /* REAL:        MODE CODE (21) FOR REAL */
 /*       29.    CLASS CODE MODULI */
 /* MODULO:      NAMTBL CLASS AND CODE FACTOR 1000 TO DEVIDE OUT CLASS */
 /* MODHLF:      NORMAL MODE CODE LIMIT 500 */
 /* * */
 /* ARGUMENTS    INDEX     NAME TABLE (NAMTBL) INDEX OF THE VARIABLE. */
 /* ** */
 /* ...     IS INDEX THAT OF A NUMBER */
     if (*index <= nametb_1.nammax) {
     goto L100;
     }
 /* ...     YES - MODE = REAL. */
 L10:
     ret_val = *real__;
     return ret_val;
 /* ...     SET K TO CLASS OF ITEM. */
 L100:
     k = *modulo * (nametb_1.namtbl[*index - 1] / *modulo);
 /* ...     IS IT OF CLASS NUMBER */
     if (k == number[0]) {
     goto L10;
     }
 /* ...     NO. IS IT OF CLASS VBL OR TEMP. IF SO RETURN CORRECT MODE. */
     if (k != vbl[0] && k != temp[0]) {
     goto L25;
     }
     ret_val = nametb_1.namtbl[*index - 1] - k;
 /* ...     IS IT A SUBSCRIPT. IF SO RETURN DERIVATIVE MODE. */
     if (ret_val >= *modhlf) {
     ret_val -= *modhlf;
     }
     return ret_val;
 /* ...     NOT NUMBER, VBL, OR TEMP - SO RETURN ZERO MODE. */
 L25:
     ret_val = 0;
     return ret_val;
 } /* mode_ */
Variable Documentation
integer charnd
Definition at line 18 of file MODE.c.
integer charst
Definition at line 18 of file MODE.c.
char cnamtb[18000]
Definition at line 25 of file MODE.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file MODE.c.
integer code[150]
Definition at line 31 of file MODE.c.
struct { ... } code_
integer ifixnd
Definition at line 18 of file MODE.c.
integer ifixst
Definition at line 18 of file MODE.c.
integer inamnd
Definition at line 18 of file MODE.c.
integer inamst
Definition at line 18 of file MODE.c.
integer moduli[2]
Definition at line 43 of file MODE.c.
struct { ... } moduli_
integer modx[32]
Definition at line 37 of file MODE.c.
struct { ... } modx_
integer namest
Definition at line 18 of file MODE.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file MODE.c.
integer namtbl[3000]
Definition at line 18 of file MODE.c.
integer numbnd
Definition at line 18 of file MODE.c.
integer numbst
Definition at line 18 of file MODE.c.