My Project: MULTAX.c File Reference
MULTAX.c File Reference
#include "f2c.h"
Macros
#define ifxcor_1 ifxcor_
Functions
int multax_ (doublereal *donoff)
Variables
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
static integer c__1 = 1
static integer c__2 = 2
static integer c__4 = 4
Macro Definition Documentation
#define ifxcor_1 ifxcor_
Definition at line 25 of file MULTAX.c.
Referenced by multax_().
Function Documentation
int multax_ (doublereal * donoff)
Definition at line 36 of file MULTAX.c.
References apt299_(), bcdf_(), c__1, c__2, c__4, holfrm_(), ifxcor_1, and test.
Referenced by xcall_().
 {
     /* Initialized data */
     static char doff[4] = "OFF ";
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer nwd;
     extern integer bcdf_(char *, ftnlen);
     static char test[4];
     extern /* Subroutine */ int apt299_(integer *, integer *, integer *,
         doublereal *), holfrm_(doublereal *, char *, integer *, integer *,
          integer *, ftnlen);
     static integer ppword[2];
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /* ...  ALL CUTTER CENTERS WILL BE OUTPUT WITH TOOL AXIS VECTORS */
 /* IF DONOFF .NE. 'OFF' */
     ppword[0] = bcdf_("MULT", (ftnlen)4);
     ppword[1] = bcdf_("AX  ", (ftnlen)4);
     apt299_(&c__1, ppword, &c__2, donoff);
     ifxcor_1.mulout = 1;
     holfrm_(donoff, test, &c__1, &c__4, &nwd, (ftnlen)4);
     if (s_cmp(test, doff, (ftnlen)4, (ftnlen)4) == 0) {
     ifxcor_1.mulout = 0;
     }
     return 0;
 } /* multax_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 29 of file MULTAX.c.
Referenced by multax_().
integer c__2 = 2 static
Definition at line 30 of file MULTAX.c.
Referenced by multax_().
integer c__4 = 4 static
Definition at line 31 of file MULTAX.c.
Referenced by multax_().
integer i3dflg
Definition at line 18 of file MULTAX.c.
integer iaerr
Definition at line 18 of file MULTAX.c.
integer iautps
Definition at line 18 of file MULTAX.c.
integer ibegin
Definition at line 18 of file MULTAX.c.
integer ic
Definition at line 18 of file MULTAX.c.
integer icheck
Definition at line 18 of file MULTAX.c.
integer icl
Definition at line 18 of file MULTAX.c.
integer ics
Definition at line 18 of file MULTAX.c.
integer icscnt
Definition at line 18 of file MULTAX.c.
integer ictdef
Definition at line 18 of file MULTAX.c.
integer icut
Definition at line 18 of file MULTAX.c.
integer ids
Definition at line 18 of file MULTAX.c.
integer ier
Definition at line 18 of file MULTAX.c.
struct { ... } ifxcor_
integer igo
Definition at line 18 of file MULTAX.c.
integer igoto
Definition at line 18 of file MULTAX.c.
integer igoug
Definition at line 18 of file MULTAX.c.
integer igs
Definition at line 18 of file MULTAX.c.
integer inops
Definition at line 18 of file MULTAX.c.
integer ips
Definition at line 18 of file MULTAX.c.
integer ipsdef
Definition at line 18 of file MULTAX.c.
integer ipt1
Definition at line 18 of file MULTAX.c.
integer is
Definition at line 18 of file MULTAX.c.
integer iseg
Definition at line 18 of file MULTAX.c.
integer iseqno
Definition at line 18 of file MULTAX.c.
integer isrch
Definition at line 18 of file MULTAX.c.
integer istrup
Definition at line 18 of file MULTAX.c.
integer it
Definition at line 18 of file MULTAX.c.
integer jbr
Definition at line 18 of file MULTAX.c.
integer jsw
Definition at line 18 of file MULTAX.c.
integer lsv
Definition at line 18 of file MULTAX.c.
integer lsv1
Definition at line 18 of file MULTAX.c.
integer mantax
Definition at line 18 of file MULTAX.c.
integer motmod
Definition at line 18 of file MULTAX.c.
integer msav
Definition at line 18 of file MULTAX.c.
integer mulout
Definition at line 18 of file MULTAX.c.
integer nmbseg
Definition at line 18 of file MULTAX.c.
integer nmpnts
Definition at line 18 of file MULTAX.c.
integer nrec
Definition at line 18 of file MULTAX.c.
integer numax
Definition at line 18 of file MULTAX.c.
integer numcnt
Definition at line 18 of file MULTAX.c.
integer nump
Definition at line 18 of file MULTAX.c.
integer numpt1
Definition at line 18 of file MULTAX.c.
integer numsfs
Definition at line 18 of file MULTAX.c.
integer numsur
Definition at line 18 of file MULTAX.c.
integer nw
Definition at line 18 of file MULTAX.c.
integer nwds
Definition at line 18 of file MULTAX.c.