My Project: NAME.c File Reference
NAME.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
Functions
integer name_ (char *str, ftnlen str_len)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
static integer c__3001 = 3001
static integer c__0 = 0
static integer c__8 = 8
Macro Definition Documentation
#define cnamtb_1 cnamtb_
Definition at line 28 of file NAME.c.
Referenced by name_().
#define nametb_1 nametb_
Definition at line 22 of file NAME.c.
Referenced by name_().
Function Documentation
integer name_ (char * str, ftnlen str_len)
Definition at line 62 of file NAME.c.
References alarm_(), bcdf_(), c__0, c__3001, c__8, cnamtb_1, i__, j, and nametb_1.
Referenced by comstr_(), gettmp_(), gopat_(), inpat_(), input_(), iprlog_(), maclbl_(), macrec_(), motion_(), pro026_(), pro027_(), recog_(), recogn_(), resrvz_(), tssmil_(), and vctprd_().
 {
     /* System generated locals */
     integer ret_val, i__1;
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, j;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int alarm_(integer *, integer *, integer *, char *
         , ftnlen);
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /* NAMEST:      NAMTBL INDEX OF BEGIN OF THE PART PROGRAM NAME SECTION */
 /* NAMMAX:      NAMTBL INDEX OF END OF THE PART PROGRAM NAME SECTION */
 /* * */
 /* ARGUMENTS    STR     A CHARACTER STRING CONTAINING THE ALPHA */
 /*                      NUMERIC CHARACTERS OF THE SYMBOL. */
 /* ** */
 /* L10: */
     j = bcdf_(str, (ftnlen)6) % (nametb_1.nammax - nametb_1.namest);
     if (j < 0) {
     j += nametb_1.nammax;
     } else {
     j += nametb_1.namest;
     }
     i__1 = nametb_1.nammax;
     for (i__ = j; i__ <= i__1; ++i__) {
     if (nametb_1.namtbl[i__ - 1] == 0) {
         goto L40;
     }
     if (s_cmp(cnamtb_1.cnamtb + (i__ - 1) * 6, str, (ftnlen)6, (ftnlen)6)
         == 0) {
         goto L100;
     }
 /* L20: */
     }
 /* ...       SCAN TABLE FROM BOTTOM UP */
     i__1 = j;
     for (i__ = nametb_1.namest; i__ <= i__1; ++i__) {
     if (nametb_1.namtbl[i__ - 1] == 0) {
         goto L40;
     }
     if (s_cmp(cnamtb_1.cnamtb + (i__ - 1) * 6, str, (ftnlen)6, (ftnlen)6)
         == 0) {
         goto L100;
     }
 /* L30: */
     }
 /* ...       TABLE FULL */
     alarm_(&c__3001, &c__0, &c__8, "NAME    ", (ftnlen)8);
     return ret_val;
 /* ...       NOT IN TABLE */
 L40:
     s_copy(cnamtb_1.cnamtb + (i__ - 1) * 6, str, (ftnlen)6, (ftnlen)6);
 /* ...       ENTRY IF NAME FOUND */
 L100:
     ret_val = i__;
     if (nametb_1.namtbl[i__ - 1] >= 0 || i__ > nametb_1.nammax) {
     return ret_val;
     }
     i__ = -nametb_1.namtbl[i__ - 1];
     goto L100;
 } /* name_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 33 of file NAME.c.
Referenced by name_().
integer c__3001 = 3001 static
Definition at line 32 of file NAME.c.
Referenced by name_().
integer c__8 = 8 static
Definition at line 34 of file NAME.c.
Referenced by name_().
integer charnd
Definition at line 18 of file NAME.c.
integer charst
Definition at line 18 of file NAME.c.
char cnamtb[18000]
Definition at line 25 of file NAME.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file NAME.c.
integer ifixnd
Definition at line 18 of file NAME.c.
integer ifixst
Definition at line 18 of file NAME.c.
integer inamnd
Definition at line 18 of file NAME.c.
integer inamst
Definition at line 18 of file NAME.c.
integer namest
Definition at line 18 of file NAME.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file NAME.c.
integer namtbl[3000]
Definition at line 18 of file NAME.c.
integer numbnd
Definition at line 18 of file NAME.c.
integer numbst
Definition at line 18 of file NAME.c.