My Project: NEWFUNCS.c File Reference
NEWFUNCS.c File Reference
#include "f2c.h"
Macros
#define neg ((doublereal *)&equiv_0)
#define ineg ((integer *)&equiv_0)
#define neg ((doublereal *)&equiv_0)
#define ineg ((integer *)&equiv_0)
Functions
int logf_ (doublereal *res, doublereal *arg)
int log10f_ (doublereal *res, doublereal *arg)
int tanf_ (doublereal *res, doublereal *arg)
int tanb_ (doublereal *res, doublereal *arg)
int cotanf_ (doublereal *res, doublereal *arg)
int cotanb_ (doublereal *res, doublereal *arg)
int sinb_ (doublereal *res, doublereal *arg)
int cosb_ (doublereal *res, doublereal *arg)
int atanb_ (doublereal *res, doublereal *arg)
int arsinf_ (doublereal *res, doublereal *arg)
int arsinb_ (doublereal *res, doublereal *arg)
int arcosf_ (doublereal *res, doublereal *arg)
int arcosb_ (doublereal *res, doublereal *arg)
int sinhf_ (doublereal *res, doublereal *arg)
int coshf_ (doublereal *res, doublereal *arg)
int tanhf_ (doublereal *res, doublereal *arg)
int intf_ (doublereal *res, doublereal *arg)
int modf_ (doublereal *res, doublereal *arg, doublereal *brg)
int signf_ (doublereal *res, doublereal *arg, doublereal *brg)
int atan2f_ (doublereal *res, doublereal *arg, doublereal *brg)
int atan2b_ (doublereal *res, doublereal *arg, doublereal *brg)
Variables
static integer c__20 = 20
static integer c__37 = 37
static integer c__36 = 36
static integer c__38 = 38
Macro Definition Documentation
#define ineg ((integer *)&equiv_0)
#define ineg ((integer *)&equiv_0)
#define neg ((doublereal *)&equiv_0)
Referenced by log10f_(), logf_(), and prtil_().
#define neg ((doublereal *)&equiv_0)
Function Documentation
int arcosb_ (doublereal * res, doublereal * arg)
Definition at line 344 of file NEWFUNCS.c.
References c__38, darcos_(), and error_().
Referenced by xcall_().
 {
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
     extern doublereal darcos_(doublereal *);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     if (abs(arg[1]) <= 1.) {
     goto L11;
     }
 /*    'ARSINF-ARCOSF ARGUMENT ABSOLUTE GREATER 1.:RESULT 0.' */
     error_(&c__38, "ARCOSB  ", (ftnlen)8);
     res[1] = 0.;
     return 0;
 L11:
     res[1] = darcos_(&arg[1]);
     return 0;
 } /* arcosb_ */
int arcosf_ (doublereal * res, doublereal * arg)
Definition at line 315 of file NEWFUNCS.c.
References c__38, darcos_(), and error_().
Referenced by xcall_().
 {
     /* Initialized data */
     static doublereal fact = .0174532925;
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
     extern doublereal darcos_(doublereal *);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     if (abs(arg[1]) <= 1.) {
     goto L11;
     }
 /*    'ARSINF-ARCOSF ARGUMENT ABSOLUTE GREATER 1.:RESULT 0.' */
     error_(&c__38, "ARCOSF  ", (ftnlen)8);
     res[1] = 0.;
     return 0;
 L11:
     res[1] = darcos_(&arg[1]);
     res[1] /= fact;
     return 0;
 } /* arcosf_ */
int arsinb_ (doublereal * res, doublereal * arg)
Definition at line 291 of file NEWFUNCS.c.
References c__38, darsin_(), and error_().
Referenced by xcall_().
 {
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
     extern doublereal darsin_(doublereal *);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     if (abs(arg[1]) <= 1.) {
     goto L9;
     }
 /*    'ARSINF-ARCOSF ARGUMENT ABSOLUTE GREATER 1.:RESULT 0.' */
     error_(&c__38, "ARSINB  ", (ftnlen)8);
     res[1] = 0.;
     return 0;
 L9:
     res[1] = darsin_(&arg[1]);
     return 0;
 } /* arsinb_ */
int arsinf_ (doublereal * res, doublereal * arg)
Definition at line 262 of file NEWFUNCS.c.
References c__38, darsin_(), and error_().
Referenced by xcall_().
 {
     /* Initialized data */
     static doublereal fact = .0174532925;
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
     extern doublereal darsin_(doublereal *);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     if (abs(arg[1]) <= 1.) {
     goto L9;
     }
 /*    'ARSINF-ARCOSF ARGUMENT ABSOLUTE GREATER 1.:RESULT 0.' */
     error_(&c__38, "ARSINF  ", (ftnlen)8);
     res[1] = 0.;
     return 0;
 L9:
     res[1] = darsin_(&arg[1]);
     res[1] /= fact;
     return 0;
 } /* arsinf_ */
int atan2b_ (doublereal * res, doublereal * arg, doublereal * brg)
Definition at line 490 of file NEWFUNCS.c.
Referenced by xcall_().
 {
     /* Builtin functions */
     double atan2(doublereal, doublereal);
     /* Parameter adjustments */
     --brg;
     --arg;
     --res;
     /* Function Body */
     res[1] = atan2(arg[1], brg[1]);
     return 0;
 } /* atan2b_ */
int atan2f_ (doublereal * res, doublereal * arg, doublereal * brg)
Definition at line 467 of file NEWFUNCS.c.
 {
     /* Initialized data */
     static doublereal fact = .0174532925;
     /* Builtin functions */
     double atan2(doublereal, doublereal);
     /* Parameter adjustments */
     --brg;
     --arg;
     --res;
     /* Function Body */
     res[1] = atan2(arg[1], brg[1]);
     res[1] /= fact;
     return 0;
 } /* atan2f_ */
int atanb_ (doublereal * res, doublereal * arg)
Definition at line 246 of file NEWFUNCS.c.
Referenced by xcall_().
 {
     /* Builtin functions */
     double atan(doublereal);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     res[1] = atan(arg[1]);
     return 0;
 } /* atanb_ */
int cosb_ (doublereal * res, doublereal * arg)
Definition at line 230 of file NEWFUNCS.c.
Referenced by xcall_().
 {
     /* Builtin functions */
     double cos(doublereal);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     res[1] = cos(arg[1]);
     return 0;
 } /* cosb_ */
int coshf_ (doublereal * res, doublereal * arg)
Definition at line 385 of file NEWFUNCS.c.
Referenced by xcall_().
 {
     /* Builtin functions */
     double cosh(doublereal);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     res[1] = cosh(arg[1]);
     return 0;
 } /* coshf_ */
int cotanb_ (doublereal * res, doublereal * arg)
Definition at line 197 of file NEWFUNCS.c.
References a, and dcotan_().
Referenced by xcall_().
 {
     static doublereal a;
     extern doublereal dcotan_(doublereal *);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     a = arg[1];
     res[1] = dcotan_(&a);
     return 0;
 } /* cotanb_ */
int cotanf_ (doublereal * res, doublereal * arg)
Definition at line 176 of file NEWFUNCS.c.
References a, and dcotan_().
Referenced by xcall_().
 {
     /* Initialized data */
     static doublereal fact = .0174532925;
     static doublereal a;
     extern doublereal dcotan_(doublereal *);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     a = arg[1] * fact;
     res[1] = dcotan_(&a);
     return 0;
 } /* cotanf_ */
int intf_ (doublereal * res, doublereal * arg)
Definition at line 417 of file NEWFUNCS.c.
References i__.
Referenced by xcall_().
 {
     static integer i__;
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     i__ = (integer) arg[1];
     res[1] = (doublereal) i__;
     return 0;
 } /* intf_ */
int log10f_ (doublereal * res, doublereal * arg)
Definition at line 80 of file NEWFUNCS.c.
References a, c__36, c__37, e_1, e_2, error_(), and neg.
Referenced by xcall_().
 {
     /* Initialized data */
     static struct {
     integer e_1[2];
     doublereal e_2;
     } equiv_0 = { -1, -1, 0. };
     /* Builtin functions */
     double d_lg10(doublereal *);
     /* Local variables */
     static doublereal a;
 #define neg ((doublereal *)&equiv_0)
 #define ineg ((integer *)&equiv_0)
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     a = arg[1];
     if (a < 0.) {
     goto L4;
     } else if (a == 0) {
     goto L2;
     } else {
     goto L5;
     }
 L4:
     a = -a;
 /*      'NEGATIVE LOGARITHM-ARGUMENT;CONTINUING WITH POSITIVE ARGUMENT' */
     error_(&c__36, "LOG10F  ", (ftnlen)8);
 L5:
     res[1] = d_lg10(&a);
     return 0;
 /*      'LOGARITHM-ARGUMENT ZERO;RESULT IS A NEGATIVE NUMBER' */
 L2:
     error_(&c__37, "LOG10F  ", (ftnlen)8);
     res[1] = *neg;
     return 0;
 } /* log10f_ */
int logf_ (doublereal * res, doublereal * arg)
Definition at line 28 of file NEWFUNCS.c.
References a, c__20, c__37, e_1, e_2, error_(), and neg.
Referenced by xcall_().
 {
     /* Initialized data */
     static struct {
     integer e_1[2];
     doublereal e_2;
     } equiv_0 = { -1, -1, 0. };
     /* Builtin functions */
     double log(doublereal);
     /* Local variables */
     static doublereal a;
 #define neg ((doublereal *)&equiv_0)
 #define ineg ((integer *)&equiv_0)
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     a = arg[1];
     if (a < 0.) {
     goto L1;
     } else if (a == 0) {
     goto L2;
     } else {
     goto L3;
     }
 L1:
     a = -a;
 /*      'NEGATIVE LOGARITHM-ARGUMENT;CONTINUING WITH POSITIVE ARGUMENT' */
     error_(&c__20, "LOGF    ", (ftnlen)8);
 L3:
     res[1] = log(a);
     return 0;
 /*      'LOGARITHM-ARGUMENT ZERO;RESULT IS A NEGATIVE NUMBER' */
 L2:
     error_(&c__37, "LOG10F  ", (ftnlen)8);
     res[1] = *neg;
     return 0;
 } /* logf_ */
int modf_ (doublereal * res, doublereal * arg, doublereal * brg)
Definition at line 433 of file NEWFUNCS.c.
Referenced by xcall_().
 {
     /* Builtin functions */
     double d_mod(doublereal *, doublereal *);
     /* Parameter adjustments */
     --brg;
     --arg;
     --res;
     /* Function Body */
     res[1] = d_mod(&arg[1], &brg[1]);
     return 0;
 } /* modf_ */
int signf_ (doublereal * res, doublereal * arg, doublereal * brg)
Definition at line 450 of file NEWFUNCS.c.
Referenced by xcall_().
 {
     /* Builtin functions */
     double d_sign(doublereal *, doublereal *);
     /* Parameter adjustments */
     --brg;
     --arg;
     --res;
     /* Function Body */
     res[1] = d_sign(&arg[1], &brg[1]);
     return 0;
 } /* signf_ */
int sinb_ (doublereal * res, doublereal * arg)
Definition at line 214 of file NEWFUNCS.c.
Referenced by xcall_().
 {
     /* Builtin functions */
     double sin(doublereal);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     res[1] = sin(arg[1]);
     return 0;
 } /* sinb_ */
int sinhf_ (doublereal * res, doublereal * arg)
Definition at line 369 of file NEWFUNCS.c.
Referenced by xcall_().
 {
     /* Builtin functions */
     double sinh(doublereal);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     res[1] = sinh(arg[1]);
     return 0;
 } /* sinhf_ */
int tanb_ (doublereal * res, doublereal * arg)
Definition at line 156 of file NEWFUNCS.c.
References a.
Referenced by xcall_().
 {
     /* Builtin functions */
     double tan(doublereal);
     /* Local variables */
     static doublereal a;
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     a = arg[1];
     res[1] = tan(a);
     return 0;
 } /* tanb_ */
int tanf_ (doublereal * res, doublereal * arg)
Definition at line 132 of file NEWFUNCS.c.
References a.
Referenced by xcall_().
 {
     /* Initialized data */
     static doublereal fact = .0174532925;
     /* Builtin functions */
     double tan(doublereal);
     /* Local variables */
     static doublereal a;
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     a = arg[1] * fact;
     res[1] = tan(a);
     return 0;
 } /* tanf_ */
int tanhf_ (doublereal * res, doublereal * arg)
Definition at line 401 of file NEWFUNCS.c.
Referenced by xcall_().
 {
     /* Builtin functions */
     double tanh(doublereal);
     /* Parameter adjustments */
     --arg;
     --res;
     /* Function Body */
     res[1] = tanh(arg[1]);
     return 0;
 } /* tanhf_ */
Variable Documentation
integer c__20 = 20 static
Definition at line 17 of file NEWFUNCS.c.
Referenced by logf_().
integer c__36 = 36 static
Definition at line 19 of file NEWFUNCS.c.
Referenced by log10f_().
integer c__37 = 37 static
Definition at line 18 of file NEWFUNCS.c.
Referenced by log10f_(), and logf_().
integer c__38 = 38 static
Definition at line 20 of file NEWFUNCS.c.
Referenced by arcosb_(), arcosf_(), arsinb_(), and arsinf_().