My Project: NORMA.c File Reference
NORMA.c File Reference
#include "f2c.h"
Functions
int norma_ (doublereal *x, doublereal *xnorm, doublereal *xmod)
Function Documentation
int norma_ (doublereal * x, doublereal * xnorm, doublereal * xmod)
Definition at line 17 of file NORMA.c.
References a, f, k, vecmod_(), and x.
Referenced by calct_(), and pencut_().
 {
     static doublereal a;
     static integer k;
     extern /* Subroutine */ int vecmod_(doublereal *, doublereal *);
 /*     GIVEN 3-D VECTOR X, CALCULATES NORMALISED (UNIT) VECTOR XNORM */
 /*     AND MODULUS OF X AS XMOD */
     /* Parameter adjustments */
     --xnorm;
     --x;
     /* Function Body */
     vecmod_(&x[1], xmod);
     if (*xmod < 1e-10f) {
     a = 0.;
     } else {
     a = 1 / *xmod;
     }
     for (k = 1; k <= 3; ++k) {
     xnorm[k] = a * x[k];
 /* L10: */
     }
     return 0;
 } /* norma_ */