My Project: NUMB.c File Reference
NUMB.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define numblk_1 numblk_
Functions
integer numb_ (char *str, ftnlen str_len)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer mnmbnd
integer numidx
integer nmbrs
integer lstchr
integer masgnd
} numblk_
Macro Definition Documentation
#define cnamtb_1 cnamtb_
Definition at line 28 of file NUMB.c.
Referenced by numb_().
#define nametb_1 nametb_
Definition at line 22 of file NUMB.c.
Referenced by numb_().
#define numblk_1 numblk_
Definition at line 34 of file NUMB.c.
Referenced by numb_().
Function Documentation
integer numb_ (char * str, ftnlen str_len)
Definition at line 54 of file NUMB.c.
References blk, cnamtb_1, i__, k, nametb_1, and numblk_1.
Referenced by goloft_(), inpat_(), isscod_(), lcanon_(), pro021_(), pro026_(), recog_(), ssdef_(), and tssmil_().
 {
     /* Initialized data */
     static char blk[12] = "            ";
     /* System generated locals */
     integer ret_val, i__1;
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, k;
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /* CNUMTB:      NUMBER TABLE */
 /* NUMBST:      INDEX OF BEGINNING OF NUMBER SECTION IN CNUMTB */
 /* NUMBND:      INDEX OF END OF NUMBER SECTION IN CNUMTB */
 /* MNMBND:      LAST NAME TABLE ENTRY TO MACRO ASSIGNED NUMBER SECTION */
 /* NUMIDX:      NAMTBL INDEX OF A NUMBER GIVEN IN THE CURRENT STATEMENT */
 /*  NMBRS:      QUANTITY OF NUMBERS IN THE CURRENT STATEMENT */
 /* LSTCHR:      LAST CHARACTER OF A NUMBER */
 /* MASGND:      NAME TABLE INDEX OF SECTION END FOR NUMBERS ASSIGNMENT */
 /* * */
 /* ARGUMENTS    STR     A CHARACTER VARIABLE CONTAINING THE */
 /*                      CHARACTERS OF THE NUMBER */
 /*       45.    NUMBER TABLE INDICES */
 /* MNMBND:      LAST NAME TABLE ENTRY TO MACRO ASSIGNED NUMBER SECTION */
 /* NUMIDX:      NAMTBL INDEX OF A NUMBER GIVEN IN THE CURRENT STATEMENT */
 /*  NMBRS:      QUANTITY OF NUMBERS IN THE CURRENT STATEMENT */
 /* LSTCHR:      LAST CHARACTER OF A NUMBER */
 /* MASGND:      NAME TABLE INDEX OF SECTION END FOR NUMBERS ASSIGNMENT */
 /* ** */
     k = numblk_1.numidx + 1;
     if (k <= nametb_1.numbnd) {
     numblk_1.numidx = k;
     } else {
     i__1 = nametb_1.numbnd;
     for (i__ = numblk_1.mnmbnd; i__ <= i__1; ++i__) {
         --k;
         if (s_cmp(cnamtb_1.cnumtb + (k - 1) * 12, blk, (ftnlen)12, (
             ftnlen)12) == 0) {
         goto L40;
         }
 /* L20: */
     }
     k = nametb_1.numbnd;
     }
 L40:
     s_copy(cnamtb_1.cnumtb + (k - 1) * 12, str, (ftnlen)12, (ftnlen)12);
     numblk_1.lstchr = numblk_1.numidx;
     ret_val = k;
     return ret_val;
 } /* numb_ */
Variable Documentation
integer charnd
Definition at line 18 of file NUMB.c.
integer charst
Definition at line 18 of file NUMB.c.
char cnamtb[18000]
Definition at line 25 of file NUMB.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file NUMB.c.
integer ifixnd
Definition at line 18 of file NUMB.c.
integer ifixst
Definition at line 18 of file NUMB.c.
integer inamnd
Definition at line 18 of file NUMB.c.
integer inamst
Definition at line 18 of file NUMB.c.
integer lstchr
Definition at line 31 of file NUMB.c.
integer masgnd
Definition at line 31 of file NUMB.c.
integer mnmbnd
Definition at line 31 of file NUMB.c.
integer namest
Definition at line 18 of file NUMB.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file NUMB.c.
integer namtbl[3000]
Definition at line 18 of file NUMB.c.
integer nmbrs
Definition at line 31 of file NUMB.c.
struct { ... } numblk_
integer numbnd
Definition at line 18 of file NUMB.c.
integer numbst
Definition at line 18 of file NUMB.c.
integer numidx
Definition at line 31 of file NUMB.c.