My Project: NUMF.c File Reference
NUMF.c File Reference
#include "f2c.h"
Macros
#define ifxcor_1 ifxcor_
#define _BLNK__1 _BLNK__
#define cldt_1 cldt_
#define chcldt_1 chcldt_
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int numf1_ (doublereal *result, doublereal *pat)
int numf2_ (doublereal *result, doublereal *pat, doublereal *arg2)
Variables
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
doublereal com [36000]
} _BLNK__
struct {
logical cldfg
integer iclcod
integer iclcnt
integer icline
integer iclblk
integer iclrcd
integer icltab [500]
integer iptvec [9]
} cldt_
struct {
char pntvct [72]
} chcldt_
static integer c__1 = 1
static integer c__8 = 8
static integer c__3 = 3
static integer c__36 = 36
static integer c__96 = 96
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 31 of file NUMF.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
Referenced by numf1_(), and numf2_().
#define canon ((doublereal *)&_BLNK__1)
#define chcldt_1 chcldt_
Definition at line 45 of file NUMF.c.
#define cldt_1 cldt_
Definition at line 39 of file NUMF.c.
Referenced by numf2_().
#define ifxcor_1 ifxcor_
Definition at line 25 of file NUMF.c.
Referenced by numf1_(), and numf2_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define sscan ((doublereal *)&_BLNK__1 + 40)
Function Documentation
int numf1_ (doublereal * result, doublereal * pat)
Definition at line 76 of file NUMF.c.
References apt094_(), c__1, c__3, c__36, c__8, c__96, canon, ckdef_(), error_(), holfrm_(), ifxcor_1, isize, isub, mode, pat, result, test, and unpack_().
Referenced by xcall_().
 {
     /* Initialized data */
     static char hclda[8] = "CLDATA  ";
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Local variables */
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer nwd, mode, iloc, isub;
     static char test[8];
     extern /* Subroutine */ int apt094_(integer *, doublereal *, integer *);
     extern logical ckdef_(doublereal *);
 #define canon ((doublereal *)&_BLNK__1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     static integer isize;
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int unpack_(doublereal *, integer *, integer *,
         integer *), holfrm_(doublereal *, char *, integer *, integer *,
         integer *, ftnlen);
 /* ...  REFERENCE TO LOCAL VARIABLE, IS, CHANGED TO ISIZE, */
 /* ...  BECAUSE IS OCCURS IN IFXCOR.INC */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
     /* Parameter adjustments */
     --pat;
     --result;
     /* Function Body */
     holfrm_(&pat[1], test, &c__1, &c__8, &nwd, (ftnlen)8);
     if (s_cmp(test, hclda, (ftnlen)8, (ftnlen)8) == 0) {
     goto L95;
     }
 /* L1: */
     if (ckdef_(&pat[1])) {
     goto L90;
     }
     unpack_(&pat[1], &mode, &isize, &isub);
     if (mode != 26 && mode != 29 && mode != 30) {
     goto L90;
     }
 /*          MOVE THE EXTERNAL CANONICAL FORM TO  CANON */
     apt094_(&c__3, &pat[1], &iloc);
     if (ckdef_(&pat[1])) {
     goto L90;
     }
     if (mode != 26) {
     goto L20;
     }
 /*  NUMBER OF POINTS IS NOW IN CANON(ILOC+3)  (PATERN) */
     result[1] = canon[iloc + 2];
     return 0;
 /*  COMPUTATIONS */
 /*      SCURV ? */
 L20:
     if (mode != 30) {
     goto L30;
     }
 /*         SCURV GIVEN */
 /*  OUTPUT NUMBER OF ARCS WITH >NUMF(C)< */
 /* L21: */
     result[1] = canon[iloc + 2];
     return 0;
 /*      SSURF ? */
 L30:
     if (mode != 29) {
     goto L90;
     }
 /*         SSURF GIVEN */
 /*  OUTPUT NUMBER OF PATCHES WITH >NUMF(S)< */
 /* L31: */
     result[1] = canon[iloc + 2];
     return 0;
 /*   OUTPUT OF NUMBER OF POINTS IN LAST CUTTER PATH WITH >NUMF(CLDATA)< */
 L95:
     result[1] = (doublereal) ifxcor_1.numcnt;
     return 0;
 /*     USED GEOMETRY UNDEFINED OR WRONG INPUT */
 L90:
     error_(&c__36, "NUMF1   ", (ftnlen)8);
 L120:
     result[1] = 0.;
     return 0;
 /*     ERROR DIAGNOSTIC 96 */
 /*     CLDAT SECTION NOT FOUND OR NOT CLOSED */
 /* L110: */
     error_(&c__96, "NUMF1   ", (ftnlen)8);
     goto L120;
 } /* numf1_ */
int numf2_ (doublereal * result, doublereal * pat, doublereal * arg2)
Definition at line 213 of file NUMF.c.
References apt094_(), arg2, c__1, c__3, c__36, c__8, c__96, canon, ckdef_(), cldt_1, error_(), holfrm_(), ifxcor_1, isize, isub, l, mode, pat, result, seg, test1, and unpack_().
Referenced by region_(), and xcall_().
 {
     /* Initialized data */
     static char hclda[8] = "CLDATA  ";
     static char arc[8] = "ARC     ";
     static char seg[8] = "SEG     ";
     static char patch[8] = "PATCH   ";
     static char spline[8] = "SPLINE  ";
     static char crsspl[8] = "CRSSPL  ";
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer l;
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer nwd, mode, iloc, isub, iarg2;
     extern /* Subroutine */ int apt094_(integer *, doublereal *, integer *);
     static char test1[8], test2[8];
     extern logical ckdef_(doublereal *);
 #define canon ((doublereal *)&_BLNK__1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     static integer isize;
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int unpack_(doublereal *, integer *, integer *,
         integer *), holfrm_(doublereal *, char *, integer *, integer *,
         integer *, ftnlen);
 /* ...  REFERENCE TO LOCAL VARIABLE, IS, CHANGED TO ISIZE, */
 /* ...  BECAUSE IS OCCURS IN IFXCOR.INC */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
     /* Parameter adjustments */
     --arg2;
     --pat;
     --result;
     /* Function Body */
     holfrm_(&pat[1], test1, &c__1, &c__8, &nwd, (ftnlen)8);
     holfrm_(&arg2[1], test2, &c__1, &c__8, &nwd, (ftnlen)8);
     if (s_cmp(test1, hclda, (ftnlen)8, (ftnlen)8) != 0) {
     goto L1;
     }
     iarg2 = (integer) arg2[1];
     i__1 = cldt_1.iclcnt;
     for (l = 1; l <= i__1; ++l) {
     if (iarg2 == cldt_1.icltab[l * 5 - 5]) {
         goto L100;
     }
 /* L15: */
     }
     goto L110;
 L1:
     if (ckdef_(&pat[1])) {
     goto L90;
     }
     unpack_(&pat[1], &mode, &isize, &isub);
     if (mode != 26 && mode != 29 && mode != 30) {
     goto L90;
     }
 /*          MOVE THE EXTERNAL CANONICAL FORM TO  CANON */
     apt094_(&c__3, &pat[1], &iloc);
     if (ckdef_(&pat[1])) {
     goto L90;
     }
     if (mode == 26) {
     goto L90;
     }
 /*  COMPUTATIONS */
 /*      SCURV ? */
 /* L20: */
     if (mode != 30) {
     goto L30;
     }
 /*         SCURV GIVEN */
     if (s_cmp(test2, arc, (ftnlen)8, (ftnlen)8) == 0) {
     goto L21;
     }
     if (s_cmp(test2, seg, (ftnlen)8, (ftnlen)8) == 0) {
     goto L22;
     }
     goto L90;
 /*  OUTPUT NUMBER OF ARCS WITH >NUMF(C,ARC)< */
 L21:
     result[1] = canon[iloc + 2];
     return 0;
 /*  OUTPUT NUMBER OF SEGMENTS WITH >NUMF(C,SEG)< */
 L22:
     result[1] = canon[iloc + 6];
     if (result[1] == 0.) {
     goto L90;
     }
     return 0;
 /*      SSURF ? */
 L30:
     if (mode != 29) {
     goto L90;
     }
 /*         SSURF GIVEN */
     if (s_cmp(test2, patch, (ftnlen)8, (ftnlen)8) == 0) {
     goto L31;
     }
 /*  ERROR , IF NOT MESH TYPE */
     if (canon[iloc + 3] != 2.) {
     goto L90;
     }
     if (s_cmp(test2, spline, (ftnlen)8, (ftnlen)8) == 0) {
     goto L32;
     }
     if (s_cmp(test2, crsspl, (ftnlen)8, (ftnlen)8) == 0) {
     goto L33;
     }
     goto L90;
 /*  OUTPUT NUMBER OF PATCHES WITH >NUMF(S,PATCH)< */
 L31:
     result[1] = canon[iloc + 2];
     return 0;
 /*  OUTPUT NUMBER OF SPLINES WITH >NUMF(S,SPLINE)< */
 L32:
     result[1] = canon[iloc + 7];
     return 0;
 /*  OUTPUT NUMBER OF CROSS SPLINES WITH >NUMF(S,CRSSPL)< */
 L33:
     result[1] = canon[iloc + 8];
     return 0;
 /*   OUTPUT OF NUMBER OF POINTS IN LAST CUTTER PATH WITH >NUMF(CLDATA)< */
 /* L95: */
     result[1] = (doublereal) ifxcor_1.numcnt;
     return 0;
 L100:
     result[1] = (doublereal) cldt_1.icltab[l * 5 - 4];
     return 0;
 /*     USED GEOMETRY UNDEFINED OR WRONG INPUT */
 L90:
     error_(&c__36, "NUMF2   ", (ftnlen)8);
 L120:
     result[1] = 0.;
     return 0;
 /*     ERROR DIAGNOSTIC 96 */
 /*     CLDAT SECTION NOT FOUND OR NOT CLOSED */
 L110:
     error_(&c__96, "NUMF2   ", (ftnlen)8);
     goto L120;
 } /* numf2_ */
Variable Documentation
struct { ... } _BLNK__
integer c__1 = 1 static
Definition at line 49 of file NUMF.c.
Referenced by numf1_(), and numf2_().
integer c__3 = 3 static
Definition at line 51 of file NUMF.c.
Referenced by numf1_(), and numf2_().
integer c__36 = 36 static
Definition at line 52 of file NUMF.c.
Referenced by numf1_(), and numf2_().
integer c__8 = 8 static
Definition at line 50 of file NUMF.c.
Referenced by numf1_(), and numf2_().
integer c__96 = 96 static
Definition at line 53 of file NUMF.c.
Referenced by numf1_(), and numf2_().
struct { ... } chcldt_
logical cldfg
Definition at line 34 of file NUMF.c.
struct { ... } cldt_
doublereal com[36000]
Definition at line 28 of file NUMF.c.
integer i3dflg
Definition at line 18 of file NUMF.c.
integer iaerr
Definition at line 18 of file NUMF.c.
integer iautps
Definition at line 18 of file NUMF.c.
integer ibegin
Definition at line 18 of file NUMF.c.
integer ic
Definition at line 18 of file NUMF.c.
integer icheck
Definition at line 18 of file NUMF.c.
integer icl
Definition at line 18 of file NUMF.c.
integer iclblk
Definition at line 35 of file NUMF.c.
integer iclcnt
Definition at line 35 of file NUMF.c.
integer iclcod
Definition at line 35 of file NUMF.c.
integer icline
Definition at line 35 of file NUMF.c.
integer iclrcd
Definition at line 35 of file NUMF.c.
integer icltab[500]
Definition at line 35 of file NUMF.c.
integer ics
Definition at line 18 of file NUMF.c.
integer icscnt
Definition at line 18 of file NUMF.c.
integer ictdef
Definition at line 18 of file NUMF.c.
integer icut
Definition at line 18 of file NUMF.c.
integer ids
Definition at line 18 of file NUMF.c.
integer ier
Definition at line 18 of file NUMF.c.
struct { ... } ifxcor_
integer igo
Definition at line 18 of file NUMF.c.
integer igoto
Definition at line 18 of file NUMF.c.
integer igoug
Definition at line 18 of file NUMF.c.
integer igs
Definition at line 18 of file NUMF.c.
integer inops
Definition at line 18 of file NUMF.c.
integer ips
Definition at line 18 of file NUMF.c.
integer ipsdef
Definition at line 18 of file NUMF.c.
integer ipt1
Definition at line 18 of file NUMF.c.
integer iptvec[9]
Definition at line 35 of file NUMF.c.
integer is
Definition at line 18 of file NUMF.c.
integer iseg
Definition at line 18 of file NUMF.c.
integer iseqno
Definition at line 18 of file NUMF.c.
integer isrch
Definition at line 18 of file NUMF.c.
integer istrup
Definition at line 18 of file NUMF.c.
integer it
Definition at line 18 of file NUMF.c.
integer jbr
Definition at line 18 of file NUMF.c.
integer jsw
Definition at line 18 of file NUMF.c.
integer lsv
Definition at line 18 of file NUMF.c.
integer lsv1
Definition at line 18 of file NUMF.c.
integer mantax
Definition at line 18 of file NUMF.c.
integer motmod
Definition at line 18 of file NUMF.c.
integer msav
Definition at line 18 of file NUMF.c.
integer mulout
Definition at line 18 of file NUMF.c.
integer nmbseg
Definition at line 18 of file NUMF.c.
integer nmpnts
Definition at line 18 of file NUMF.c.
integer nrec
Definition at line 18 of file NUMF.c.
integer numax
Definition at line 18 of file NUMF.c.
integer numcnt
Definition at line 18 of file NUMF.c.
integer nump
Definition at line 18 of file NUMF.c.
integer numpt1
Definition at line 18 of file NUMF.c.
integer numsfs
Definition at line 18 of file NUMF.c.
integer numsur
Definition at line 18 of file NUMF.c.
integer nw
Definition at line 18 of file NUMF.c.
integer nwds
Definition at line 18 of file NUMF.c.
char pntvct[72]
Definition at line 42 of file NUMF.c.