My Project: NUMPTS.c File Reference
NUMPTS.c File Reference
#include "f2c.h"
Macros
#define ifxcor_1 ifxcor_
Functions
int numpts_ (doublereal *xnumbr)
Variables
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
static integer c__1 = 1
Macro Definition Documentation
#define ifxcor_1 ifxcor_
Definition at line 25 of file NUMPTS.c.
Referenced by numpts_().
Function Documentation
int numpts_ (doublereal * xnumbr)
Definition at line 34 of file NUMPTS.c.
References apt299_(), bcdf_(), c__1, and ifxcor_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static char ppword[8] = "NUMPTS  ";
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt299_(integer *, integer *, integer *,
         doublereal *);
     static integer ippwrd[2];
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /* ...  USE THIS AS THE MAXIMUM NUMBER OF CUTTER CENTERS ON ONE */
 /* ...  ELEMENTARY CUT SEQUENCE */
     ippwrd[0] = bcdf_(ppword, (ftnlen)4);
     ippwrd[1] = bcdf_(ppword + 4, (ftnlen)4);
     apt299_(&c__1, ippwrd, &c__1, xnumbr);
     ifxcor_1.nmpnts = (integer) (*xnumbr);
     return 0;
 } /* numpts_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 29 of file NUMPTS.c.
Referenced by numpts_().
integer i3dflg
Definition at line 18 of file NUMPTS.c.
integer iaerr
Definition at line 18 of file NUMPTS.c.
integer iautps
Definition at line 18 of file NUMPTS.c.
integer ibegin
Definition at line 18 of file NUMPTS.c.
integer ic
Definition at line 18 of file NUMPTS.c.
integer icheck
Definition at line 18 of file NUMPTS.c.
integer icl
Definition at line 18 of file NUMPTS.c.
integer ics
Definition at line 18 of file NUMPTS.c.
integer icscnt
Definition at line 18 of file NUMPTS.c.
integer ictdef
Definition at line 18 of file NUMPTS.c.
integer icut
Definition at line 18 of file NUMPTS.c.
integer ids
Definition at line 18 of file NUMPTS.c.
integer ier
Definition at line 18 of file NUMPTS.c.
struct { ... } ifxcor_
integer igo
Definition at line 18 of file NUMPTS.c.
integer igoto
Definition at line 18 of file NUMPTS.c.
integer igoug
Definition at line 18 of file NUMPTS.c.
integer igs
Definition at line 18 of file NUMPTS.c.
integer inops
Definition at line 18 of file NUMPTS.c.
integer ips
Definition at line 18 of file NUMPTS.c.
integer ipsdef
Definition at line 18 of file NUMPTS.c.
integer ipt1
Definition at line 18 of file NUMPTS.c.
integer is
Definition at line 18 of file NUMPTS.c.
integer iseg
Definition at line 18 of file NUMPTS.c.
integer iseqno
Definition at line 18 of file NUMPTS.c.
integer isrch
Definition at line 18 of file NUMPTS.c.
integer istrup
Definition at line 18 of file NUMPTS.c.
integer it
Definition at line 18 of file NUMPTS.c.
integer jbr
Definition at line 18 of file NUMPTS.c.
integer jsw
Definition at line 18 of file NUMPTS.c.
integer lsv
Definition at line 18 of file NUMPTS.c.
integer lsv1
Definition at line 18 of file NUMPTS.c.
integer mantax
Definition at line 18 of file NUMPTS.c.
integer motmod
Definition at line 18 of file NUMPTS.c.
integer msav
Definition at line 18 of file NUMPTS.c.
integer mulout
Definition at line 18 of file NUMPTS.c.
integer nmbseg
Definition at line 18 of file NUMPTS.c.
integer nmpnts
Definition at line 18 of file NUMPTS.c.
integer nrec
Definition at line 18 of file NUMPTS.c.
integer numax
Definition at line 18 of file NUMPTS.c.
integer numcnt
Definition at line 18 of file NUMPTS.c.
integer nump
Definition at line 18 of file NUMPTS.c.
integer numpt1
Definition at line 18 of file NUMPTS.c.
integer numsfs
Definition at line 18 of file NUMPTS.c.
integer numsur
Definition at line 18 of file NUMPTS.c.
integer nw
Definition at line 18 of file NUMPTS.c.
integer nwds
Definition at line 18 of file NUMPTS.c.