My Project: ONEARG.c File Reference
ONEARG.c File Reference
#include "f2c.h"
Macros
#define iltext_1 iltext_
#define comfin ((logical *)&iltext_1)
#define textin ((integer *)&iltext_1 + 4)
#define tpntrx ((integer *)&iltext_1 + 2)
Functions
int onearg_ (integer *i__)
Variables
struct {
integer iltext [94]
} iltext_
static integer c__0 = 0
static integer c__8 = 8
Macro Definition Documentation
#define comfin ((logical *)&iltext_1)
Referenced by onearg_().
#define iltext_1 iltext_
Definition at line 21 of file ONEARG.c.
#define textin ((integer *)&iltext_1 + 4)
Referenced by onearg_().
#define tpntrx ((integer *)&iltext_1 + 2)
Referenced by onearg_().
Function Documentation
int onearg_ (integer * i__)
Definition at line 58 of file ONEARG.c.
References alarm_(), c__0, c__8, comfin, i__, ierror, textin, and tpntrx.
Referenced by asnadz_(), boolif_(), callzz_(), calmcx_(), goloft_(), isscod_(), jumpzz_(), labelz_(), larges_(), loop_(), macrec_(), mnproc_(), motion_(), pro026_(), pro027_(), pro028_(), recog_(), recogn_(), replac_(), retmcx_(), ssdef_(), subcod_(), and tssmil_().
 {
     /* Local variables */
     extern /* Subroutine */ int alarm_(integer *, integer *, integer *, char *
         , ftnlen);
 #define comfin ((logical *)&iltext_1)
     static integer ierror;
 #define textin ((integer *)&iltext_1 + 4)
 #define tpntrx ((integer *)&iltext_1 + 2)
 /*       19.    INTERMEDIATE LANGUAGE TEXT */
 /* COMFIN:      TRUE IF I.L. OPERATION CODE GIVEN */
 /* TPNTRX:      POINTER TO LAST TEXTIN ENTRY */
 /* TEXTIN:      STORAGE FOR CURRENTLY GENERATED I.L. COMMAND ARGUM.LIST */
 /* * */
 /* ARGUMENTS    I       NAME TABLE (NAMTBL) INDEX OF ARGUMENT */
 /* ** */
     if (*comfin) {
     goto L10;
     }
     ierror = 3;
     goto L90;
 L10:
     if (*tpntrx < 90) {
     goto L20;
     }
     ierror = 2;
 L90:
     alarm_(&ierror, &c__0, &c__8, "ONEARG  ", (ftnlen)8);
     goto L100;
 L20:
     textin[*tpntrx] = *i__;
     ++(*tpntrx);
 L100:
     return 0;
 } /* onearg_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 25 of file ONEARG.c.
Referenced by onearg_().
integer c__8 = 8 static
Definition at line 26 of file ONEARG.c.
Referenced by onearg_().
integer iltext[94]
Definition at line 18 of file ONEARG.c.
struct { ... } iltext_