My Project: OPCODE.c File Reference
OPCODE.c File Reference
#include "f2c.h"
Macros
#define iltext_1 iltext_
#define comfin ((logical *)&iltext_1)
#define length ((integer *)&iltext_1 + 1)
#define optext ((integer *)&iltext_1 + 3)
#define tpntrx ((integer *)&iltext_1 + 2)
Functions
int opcode_ (integer *i__)
Variables
struct {
integer iltext [94]
} iltext_
static integer c__4 = 4
static integer c__0 = 0
static integer c__8 = 8
Macro Definition Documentation
#define comfin ((logical *)&iltext_1)
Referenced by opcode_().
#define iltext_1 iltext_
Definition at line 21 of file OPCODE.c.
#define length ((integer *)&iltext_1 + 1)
Referenced by floseg_(), goloft_(), opcode_(), pro020_(), and pro028_().
#define optext ((integer *)&iltext_1 + 3)
Referenced by opcode_().
#define tpntrx ((integer *)&iltext_1 + 2)
Referenced by opcode_().
Function Documentation
int opcode_ (integer * i__)
Definition at line 66 of file OPCODE.c.
References alarm_(), c__0, c__4, c__8, comfin, i__, length, optext, and tpntrx.
Referenced by asnadz_(), asnjpz_(), boolif_(), callzz_(), calmcx_(), goloft_(), gopat_(), inpat_(), isscod_(), jumpzz_(), labelz_(), larges_(), lcanon_(), loop_(), macrec_(), mnproc_(), motion_(), pro021_(), pro026_(), pro027_(), pro028_(), recog_(), recogn_(), replac_(), resrvz_(), retmcx_(), ssdef_(), subcod_(), and tssmil_().
 {
     /* Local variables */
     extern /* Subroutine */ int alarm_(integer *, integer *, integer *, char *
         , ftnlen);
 #define comfin ((logical *)&iltext_1)
 #define length ((integer *)&iltext_1 + 1)
 #define optext ((integer *)&iltext_1 + 3)
 #define tpntrx ((integer *)&iltext_1 + 2)
 /*       19.    INTERMEDIATE LANGUAGE TEXT */
 /* COMFIN:      TRUE IF I.L. OPERATION CODE GIVEN */
 /* LENGTH:      NUMBER OF ITEMS IN CURRENT I.L. COMMAND ARGUMENT LIST */
 /* TPNTRX:      POINTER TO LAST TEXTIN ENTRY */
 /* OPTEXT:      CONTAINS COMMAND CODE FOR CURRENT I.L. COMMAND */
 /* * */
 /* ARGUMENTS    I     INTEGER CODE FOR CURRENT I.L. COMMAND */
 /* ** */
     if (*comfin) {
     alarm_(&c__4, &c__0, &c__8, "OPCODE  ", (ftnlen)8);
     }
     *optext = *i__;
     *length = 0;
     *tpntrx = 0;
     *comfin = TRUE_;
     return 0;
 } /* opcode_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 26 of file OPCODE.c.
Referenced by opcode_().
integer c__4 = 4 static
Definition at line 25 of file OPCODE.c.
Referenced by opcode_().
integer c__8 = 8 static
Definition at line 27 of file OPCODE.c.
Referenced by opcode_().
integer iltext[94]
Definition at line 18 of file OPCODE.c.
struct { ... } iltext_