My Project: OUTMSG.c File Reference
OUTMSG.c File Reference
#include "f2c.h"
Macros
#define symfil_1 symfil_
Functions
int outmsg_ (char *str, ftnlen str_len)
Variables
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
static integer c__1 = 1
static integer c__3 = 3
Macro Definition Documentation
#define symfil_1 symfil_
Definition at line 24 of file OUTMSG.c.
Referenced by outmsg_().
Function Documentation
int outmsg_ (char * str, ftnlen str_len)
Definition at line 61 of file OUTMSG.c.
References c__1, c__3, and symfil_1.
Referenced by acntrl_(), amind_(), apt211_(), avoid_(), and sspath_().
 {
     /* System generated locals */
     address a__1[3];
     integer i__1[3];
     /* Builtin functions */
     integer i_len(char *, ftnlen), s_wsfi(icilist *), do_fio(integer *, char *
         , ftnlen), e_wsfi(void);
     /* Subroutine */ int s_cat(char *, char **, integer *, integer *, ftnlen);
     integer s_wsfe(cilist *), e_wsfe(void);
     /* Local variables */
     static char f1[3];
     static integer slen;
     static char form[9];
     /* Fortran I/O blocks */
     static icilist io___3 = { 0, f1, 0, "(I3)", 3, 1 };
     static cilist io___5 = { 0, 0, 0, form, 0 };
 /* ...                SYSTEM I/O FILES */
     slen = i_len(str, str_len);
 /* .... SET UP FORMAT AND PRINT */
     s_wsfi(&io___3);
     do_fio(&c__1, (char *)&slen, (ftnlen)sizeof(integer));
     e_wsfi();
 /* Writing concatenation */
     i__1[0] = 5, a__1[0] = "(1X,A";
     i__1[1] = 3, a__1[1] = f1;
     i__1[2] = 1, a__1[2] = ")";
     s_cat(form, a__1, i__1, &c__3, (ftnlen)9);
     io___5.ciunit = symfil_1.vlfile;
     s_wsfe(&io___5);
     do_fio(&c__1, str, str_len);
     e_wsfe();
     return 0;
 } /* outmsg_ */
Variable Documentation
integer axfile
Definition at line 18 of file OUTMSG.c.
integer c__1 = 1 static
Definition at line 28 of file OUTMSG.c.
Referenced by outmsg_().
integer c__3 = 3 static
Definition at line 29 of file OUTMSG.c.
Referenced by outmsg_().
integer clfil3
Definition at line 18 of file OUTMSG.c.
integer clfile
Definition at line 18 of file OUTMSG.c.
integer clfilp
Definition at line 18 of file OUTMSG.c.
integer cpfile
Definition at line 18 of file OUTMSG.c.
integer elfil1
Definition at line 18 of file OUTMSG.c.
integer elfil2
Definition at line 18 of file OUTMSG.c.
integer elfil3
Definition at line 18 of file OUTMSG.c.
integer elfil4
Definition at line 18 of file OUTMSG.c.
integer elfile
Definition at line 18 of file OUTMSG.c.
integer exfile
Definition at line 18 of file OUTMSG.c.
integer infile__
Definition at line 18 of file OUTMSG.c.
integer ispare[26]
Definition at line 18 of file OUTMSG.c.
integer ldafil
Definition at line 18 of file OUTMSG.c.
integer libfil
Definition at line 18 of file OUTMSG.c.
integer mactxt
Definition at line 18 of file OUTMSG.c.
integer nfil12
Definition at line 18 of file OUTMSG.c.
integer nfil13
Definition at line 18 of file OUTMSG.c.
integer pnchfl
Definition at line 18 of file OUTMSG.c.
integer pofile
Definition at line 18 of file OUTMSG.c.
integer pxfile
Definition at line 18 of file OUTMSG.c.
struct { ... } symfil_
integer tifile
Definition at line 18 of file OUTMSG.c.
integer vlfile
Definition at line 18 of file OUTMSG.c.
integer xcan
Definition at line 18 of file OUTMSG.c.
integer xnum
Definition at line 18 of file OUTMSG.c.