My Project: PATH.c File Reference
PATH.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define macxx1_1 macxx1_
#define macxx7_1 macxx7_
#define way ((integer *)&macxx1_1 + 25)
#define nxtln ((integer *)&macxx1_1 + 68)
#define pathch ((integer *)&macxx1_1 + 70)
#define pathln ((integer *)&macxx1_1 + 67)
#define mcsavp ((integer *)&macxx1_1 + 4)
#define numarg ((integer *)&macxx1_1 + 60)
#define should ((logical *)&macxx1_1 + 69)
#define linusd ((integer *)&macxx7_1)
#define lnusdp ((integer *)&macxx1_1 + 50)
Functions
int path_ (void)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer macxx1 [71]
} macxx1_
struct {
integer macxx7 [182]
} macxx7_
static integer c__2 = 2
Macro Definition Documentation
#define cnamtb_1 cnamtb_
Definition at line 28 of file PATH.c.
#define linusd ((integer *)&macxx7_1)
Referenced by path_().
#define lnusdp ((integer *)&macxx1_1 + 50)
Referenced by path_().
#define macxx1_1 macxx1_
Definition at line 34 of file PATH.c.
#define macxx7_1 macxx7_
Definition at line 40 of file PATH.c.
#define mcsavp ((integer *)&macxx1_1 + 4)
Referenced by path_().
#define nametb_1 nametb_
Definition at line 22 of file PATH.c.
Referenced by path_().
#define numarg ((integer *)&macxx1_1 + 60)
Referenced by path_().
#define nxtln ((integer *)&macxx1_1 + 68)
Referenced by path_().
#define pathch ((integer *)&macxx1_1 + 70)
#define pathln ((integer *)&macxx1_1 + 67)
Referenced by path_().
#define should ((logical *)&macxx1_1 + 69)
Referenced by path_().
#define way ((integer *)&macxx1_1 + 25)
Referenced by path_().
Function Documentation
int path_ (void)
Definition at line 61 of file PATH.c.
References c__2, calmcx_(), i__, j, linusd, lnusdp, maclbl_(), mcsavp, nametb_1, numarg, nxtln, pathln, should, and way.
Referenced by input_(), pro020_(), pro026_(), recog_(), and replac_().
 {
     /* System generated locals */
     integer i__1, i__2;
     /* Local variables */
     static integer i__, j;
 #define way ((integer *)&macxx1_1 + 25)
 #define nxtln ((integer *)&macxx1_1 + 68)
     extern /* Subroutine */ int maclbl_(integer *, integer *, integer *);
 #define pathch ((integer *)&macxx1_1 + 70)
     extern /* Subroutine */ int calmcx_(integer *, integer *, integer *);
 #define pathln ((integer *)&macxx1_1 + 67)
 #define mcsavp ((integer *)&macxx1_1 + 4)
 #define numarg ((integer *)&macxx1_1 + 60)
 #define should ((logical *)&macxx1_1 + 69)
 #define linusd ((integer *)&macxx7_1)
 #define lnusdp ((integer *)&macxx1_1 + 50)
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /*       22.    MACRO PROCESSING VARIABLES */
 /* MCSAVP:      PRESENT NEST LEVEL DURING MACRO PROCESSING */
 /* WAY:         INDICATES TYPE OF MACRO PROCESSING */
 /* LNUSDP:      INDEX OF LAST LINUSD ENTRY */
 /* NUMARG:      NUMBER OF MACRO VARIABLES+1 FOR CURRENT MACRO */
 /* PATHLN:      CURRENT ACTUAL BRANCHING EXPRESSION. INITIALLY=NUMARG */
 /* NXTLN:       POINTER TO NEXT LINUSD POSITION TO BE EXAMINED */
 /* SHOULD:      MACRO INDICATOR. NORMALLY FALSE */
 /* PATHCH:      CURRENT ACTUAL BRANCHING EXPRESSION. INITIALLY=NUMARG */
 /*      26A.    MACRO PROCESSING ARRAYS */
 /* LINUSD:      NUMBERS OF EXPRESSIONS REQUIRING BRANCHING FOR MACROS */
 /* ** */
     ++(*pathln);
     if (*numarg == 0) {
     goto L1;
     }
     if (*nxtln <= *lnusdp) {
     goto L3;
     }
 L1:
     *should = TRUE_;
 /* L2: */
     return 0;
 L3:
     if (*pathln != linusd[*nxtln - 1]) {
     goto L1;
     }
     ++(*pathch);
     i__1 = -(*mcsavp);
     i__2 = -(*pathch);
     maclbl_(&i__1, &i__2, &i__);
     nametb_1.namtbl[i__ - 1] = 1;
     j = 0;
     if (*way == 5) {
     j = *mcsavp;
     }
     calmcx_(&i__, &j, &c__2);
     *should = FALSE_;
     ++(*nxtln);
     return 0;
 } /* path_ */
Variable Documentation
integer c__2 = 2 static
Definition at line 44 of file PATH.c.
Referenced by path_().
integer charnd
Definition at line 18 of file PATH.c.
integer charst
Definition at line 18 of file PATH.c.
char cnamtb[18000]
Definition at line 25 of file PATH.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file PATH.c.
integer ifixnd
Definition at line 18 of file PATH.c.
integer ifixst
Definition at line 18 of file PATH.c.
integer inamnd
Definition at line 18 of file PATH.c.
integer inamst
Definition at line 18 of file PATH.c.
integer macxx1[71]
Definition at line 31 of file PATH.c.
struct { ... } macxx1_
integer macxx7[182]
Definition at line 37 of file PATH.c.
struct { ... } macxx7_
integer namest
Definition at line 18 of file PATH.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file PATH.c.
integer namtbl[3000]
Definition at line 18 of file PATH.c.
integer numbnd
Definition at line 18 of file PATH.c.
integer numbst
Definition at line 18 of file PATH.c.