My Project: PCHG.c File Reference
PCHG.c File Reference
#include "f2c.h"
Macros
#define ibugg_1 ibugg_
Functions
int pchg_ (doublereal *pcur, doublereal *pdir, doublereal *pdel)
Variables
struct {
integer ibug
integer ipcolc
integer ipcolm
} ibugg_
static integer c_n1 = -1
static integer c__0 = 0
static integer c__1 = 1
Macro Definition Documentation
#define ibugg_1 ibugg_
Definition at line 21 of file PCHG.c.
Referenced by pchg_().
Function Documentation
int pchg_ (doublereal * pcur, doublereal * pdir, doublereal * pdel)
Definition at line 31 of file PCHG.c.
References a, bad_(), c__0, c__1, c_n1, cprint_(), i__, ibugg_1, smal1, and zero.
Referenced by cutreg_(), and sspath_().
 {
     /* Initialized data */
     static doublereal zero = 0.;
     static doublereal half = .5;
     static doublereal smal = 1e-14;
     static doublereal smal1 = 1e-10;
     /* System generated locals */
     doublereal d__1;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static doublereal a;
     static integer i__;
     static doublereal xx;
     extern /* Subroutine */ int bad_();
     static doublereal pin, pmax, phalf, ptarg;
     static char badmsg[20];
     extern /* Subroutine */ int cprint_(char *, ftnlen);
 /* --PURPOSE IS TO MODIFY THE PARAMETRIC CHANGE PDEL SO AS */
 /* --TO HIT OR APPROACH A JUNCTION POINT SMOOTHLY. */
     pin = *pdel;
     a = zero;
     xx = *pcur;
     i__ = (integer) xx;
     a = (doublereal) i__;
     if ((d__1 = a - *pcur, abs(d__1)) > smal) {
     goto L10;
     }
     *pdel = min(half,*pdel);
     goto L999;
 L10:
     ptarg = zero;
     xx = *pdir + *pcur;
     i__ = (integer) xx;
     ptarg = (doublereal) i__;
     pmax = (d__1 = ptarg - *pcur, abs(d__1));
     *pdel = min(pmax,*pdel);
     phalf = half * pmax;
     if (*pdel < pmax && *pdel > phalf) {
     *pdel = phalf;
     }
 L999:
     *pdel += smal1;
     if (ibugg_1.ibug != 11) {
     goto L1999;
     }
     bad_(&c_n1, &c__0, " ", &c__0, (ftnlen)1);
     s_copy(badmsg, " AFTER PCHG", (ftnlen)20, (ftnlen)11);
     cprint_(badmsg, (ftnlen)20);
     bad_(&c__1, &c__1, "PCUR", pcur, (ftnlen)4);
     bad_(&c__1, &c__1, "PDIR", pdir, (ftnlen)4);
     bad_(&c__1, &c__1, "PDEL", pdel, (ftnlen)4);
     bad_(&c_n1, &c__1, "PIN ", &pin, (ftnlen)4);
 L1999:
     return 0;
 } /* pchg_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 26 of file PCHG.c.
Referenced by pchg_().
integer c__1 = 1 static
Definition at line 27 of file PCHG.c.
Referenced by pchg_().
integer c_n1 = -1 static
Definition at line 25 of file PCHG.c.
Referenced by pchg_().
integer ibug
Definition at line 18 of file PCHG.c.
struct { ... } ibugg_
integer ipcolc
Definition at line 18 of file PCHG.c.
integer ipcolm
Definition at line 18 of file PCHG.c.