My Project: POLCON.c File Reference
POLCON.c File Reference
#include "f2c.h"
Functions
int polcon_ (real *srface, integer *number)
Function Documentation
int polcon_ (real * srface, integer * number)
Definition at line 18 of file POLCON.c.
Referenced by ajundd_(), ddrlsr_(), and ddst_().
 {
     return 0;
 } /* polcon_ */