My Project: PRTIL.c File Reference
PRTIL.c File Reference
#include "f2c.h"
Macros
#define sdp_1 sdp_
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define iltext_1 iltext_
#define symfil_1 symfil_
#define textin ((integer *)&iltext_1 + 4)
#define optext ((integer *)&iltext_1 + 3)
#define tpntrx ((integer *)&iltext_1 + 2)
Functions
int prtil_ (char *line, ftnlen line_len)
Variables
struct {
integer nbchar
integer nbwrd
integer iwrd
integer ifac
} sdp_
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer iltext [94]
} iltext_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
static integer c__116 = 116
static integer c__120 = 120
Macro Definition Documentation
#define cnamtb_1 cnamtb_
Definition at line 34 of file PRTIL.c.
Referenced by prtil_().
#define iltext_1 iltext_
Definition at line 40 of file PRTIL.c.
#define nametb_1 nametb_
Definition at line 28 of file PRTIL.c.
#define optext ((integer *)&iltext_1 + 3)
Referenced by prtil_().
#define sdp_1 sdp_
Definition at line 21 of file PRTIL.c.
Referenced by prtil_().
#define symfil_1 symfil_
Definition at line 49 of file PRTIL.c.
Referenced by prtil_().
#define textin ((integer *)&iltext_1 + 4)
Referenced by prtil_().
#define tpntrx ((integer *)&iltext_1 + 2)
Referenced by prtil_().
Function Documentation
int prtil_ (char * line, ftnlen line_len)
Definition at line 69 of file PRTIL.c.
References binbcd_(), blk, c__116, c__120, cnamtb_1, count, foutxx_(), holfrm_(), i1, i__, ii, j, k, l, neg, oppair_(), optext, sdp_1, symfil_1, textin, and tpntrx.
Referenced by rlslin_().
 {
     /* Initialized data */
     static char opbcd[6*21] = "FADD  " "FSUB  " "FMPY  " "FDIV  " "PEXP  "
         "LABEL " "ENTRY " "JUMP  " "SEQNCE" "RETMC " "CONJMP" "RESRV "
         "CVTSUB" "CALMC " "ASNADD" "ASNJMP" "REPL  " "CALL  " "MOVE  "
         "VBLJMP" "HOLDAT";
     static char blk[4] = "    ";
     static char neg[4] = "   -";
     /* System generated locals */
     integer i__1, i__2;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, j, k, l, i1, ii, nwd, limit, count, itext;
     extern /* Subroutine */ int binbcd_(integer *, char *, integer *, ftnlen),
          oppair_(char *, integer *, ftnlen), holfrm_(integer *, char *,
         integer *, integer *, integer *, ftnlen);
 #define textin ((integer *)&iltext_1 + 4)
 #define optext ((integer *)&iltext_1 + 3)
     extern /* Subroutine */ int foutxx_(integer *, char *, integer *, ftnlen);
 #define tpntrx ((integer *)&iltext_1 + 2)
 /*        0.    SYSTEM DEPENDENT PARAMETERS */
 /* IWRD:        NO. OF BYTES PER INTEGER WORD */
 /* IFAC:        BYTE LEFT SHIFT MULTIPLICATION FACTOR */
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /*       19.    INTERMEDIATE LANGUAGE TEXT */
 /* TPNTRX:      POINTER TO LAST TEXTIN ENTRY */
 /* OPTEXT:      CONTAINS COMMAND CODE FOR CURRENT I.L. COMMAND */
 /* TEXTIN:      STORAGE FOR CURRENTLY GENERATED I.L. COMMAND ARGUM.LIST */
 /*       33.    SYMBOLIC FILE DEFINITIONS */
 /* VLFILE:      VERIFICATION LISTING FILE */
 /* * */
 /* ARGUMENTS    LINE     OUTPUT ARRAY TO CONTAIN ALPHA- */
 /*                       NUMERIC EQUIVALENT OF BINARY I.L.. */
 /* ...                SYSTEM I/O FILES */
 /* ** */
     s_copy(line + 4, opbcd + (0 + (0 + (*optext - 1) * 6)), (ftnlen)120, (
         ftnlen)6);
     switch (*optext) {
     case 1:  goto L100;
     case 2:  goto L100;
     case 3:  goto L100;
     case 4:  goto L100;
     case 5:  goto L100;
     case 6:  goto L600;
     case 7:  goto L600;
     case 8:  goto L600;
     case 9:  goto L900;
     case 10:  goto L1000;
     case 11:  goto L1100;
     case 12:  goto L1200;
     case 13:  goto L1300;
     case 14:  goto L1400;
     case 15:  goto L1500;
     case 16:  goto L1600;
     case 17:  goto L1700;
     case 18:  goto L1800;
     case 19:  goto L1900;
     case 20:  goto L2000;
     case 21:  goto L2100;
     }
 /* ...  FADD,FSUB,FMPY,FDIV,FEXP */
 L100:
     l = 13;
     for (i__ = 1; i__ <= 5; i__ += 2) {
     oppair_(line + (l - 1), &textin[i__ - 1], 124 - (l - 1));
 /* L101: */
     l += 20;
     }
     k = 69;
     goto L9000;
 /* ...  LABEL,ENTRY,JUMP */
 L600:
     itext = textin[0];
     s_copy(line + 12, cnamtb_1.cnamtb + (itext - 1) * 6, (ftnlen)112, (ftnlen)
         6);
     k = 21;
     goto L9000;
 /* ...     SEQNCE */
 L900:
     s_copy(line + 12, blk, (ftnlen)112, (ftnlen)4);
     if (textin[0] >= 0) {
     goto L902;
     } else {
     goto L901;
     }
 L901:
     s_copy(line + 12, neg, (ftnlen)112, (ftnlen)4);
 L902:
     i__1 = abs(textin[0]);
     binbcd_(&i__1, line + 16, &count, (ftnlen)108);
     k = 25;
     goto L9000;
 /* ...     RETMC */
 L1000:
     binbcd_(textin, line + 12, &count, (ftnlen)112);
     k = 21;
     goto L9000;
 /* ...  CONJMP */
 L1100:
     oppair_(line + 12, textin, (ftnlen)112);
     for (i__ = 1; i__ <= 3; ++i__) {
     itext = textin[i__ + 1];
     i1 = (i__ << 3) + 25;
     s_copy(line + (i1 - 1), cnamtb_1.cnamtb + (itext - 1) * 6, 124 - (i1
         - 1), (ftnlen)6);
 /* L1101: */
     }
     k = 57;
     goto L9000;
 /* ...  RESRV */
 L1200:
     itext = textin[0];
     s_copy(line + 12, cnamtb_1.cnamtb + (itext - 1) * 6, (ftnlen)112, (ftnlen)
         6);
     for (i__ = 2; i__ <= 4; ++i__) {
 /* L1201: */
     i__1 = (i__ << 3) + 4;
     binbcd_(&textin[i__ - 1], line + i__1, &count, 124 - i__1);
     }
     k = 41;
     goto L9000;
 /* ...  CVTSUB */
 L1300:
     l = 13;
     for (i__ = 1; i__ <= 5; i__ += 2) {
     oppair_(line + (l - 1), &textin[i__ - 1], 124 - (l - 1));
 /* L1301: */
     l += 20;
     }
     binbcd_(&textin[6], line + 64, &count, (ftnlen)60);
     k = 81;
     goto L9000;
 /* ...  CALMC */
 L1400:
     itext = textin[0];
     s_copy(line + 12, cnamtb_1.cnamtb + (itext - 1) * 6, (ftnlen)112, (ftnlen)
         6);
     binbcd_(&textin[1], line + 20, &count, (ftnlen)104);
     binbcd_(&textin[2], line + 28, &count, (ftnlen)96);
     k = 33;
     goto L9000;
 /* ...  ASNADD */
 L1500:
     itext = textin[0];
     s_copy(line + 12, cnamtb_1.cnamtb + (itext - 1) * 6, (ftnlen)112, (ftnlen)
         6);
     oppair_(line + 24, &textin[1], (ftnlen)100);
     k = 41;
     goto L1601;
 /* ...  ASNJMP */
 L1600:
     itext = textin[0];
     s_copy(line + 12, cnamtb_1.cnamtb + (itext - 1) * 6, (ftnlen)112, (ftnlen)
         6);
     itext = textin[1];
     s_copy(line + 24, cnamtb_1.cnamtb + (itext - 1) * 6, (ftnlen)100, (ftnlen)
         6);
     k = 33;
 L1601:
     s_copy(line + 20, blk, (ftnlen)104, (ftnlen)4);
     goto L9000;
 /* ...  REPL */
 L1700:
     binbcd_(textin, line + 12, &count, (ftnlen)112);
     oppair_(line + 20, &textin[1], (ftnlen)104);
     oppair_(line + 40, &textin[3], (ftnlen)84);
     k = 61;
     goto L9000;
 /* ...  CALL */
 L1800:
     itext = textin[0];
     s_copy(line + 12, cnamtb_1.cnamtb + (itext - 1) * 6, (ftnlen)112, (ftnlen)
         6);
     s_copy(line + 20, blk, (ftnlen)12, (ftnlen)4);
     limit = *tpntrx - 9;
     j = 2;
     l = 33;
     if (limit <= 0) {
     goto L1804;
     } else {
     goto L1801;
     }
 L1801:
     i__1 = limit;
     for (i__ = 1; i__ <= i__1; i__ += 10) {
     for (ii = l; ii <= 100; ii += 20) {
         oppair_(line + (ii - 1), &textin[j - 1], 124 - (ii - 1));
 /* L1802: */
         j += 2;
     }
     foutxx_(&symfil_1.vlfile, line, &c__116, (ftnlen)124);
     l = 13;
     s_copy(line + 8, blk, (ftnlen)116, (ftnlen)4);
 /* L1803: */
     s_copy(line + 4, blk, (ftnlen)120, (ftnlen)4);
     }
 L1804:
     if (*tpntrx == 1) {
     goto L1807;
     }
     i__1 = *tpntrx;
     for (i__ = j; i__ <= i__1; i__ += 2) {
     oppair_(line + (l - 1), &textin[i__ - 1], 124 - (l - 1));
 /* L1805: */
     l += 20;
     }
 L1807:
     k = l;
     goto L9000;
 /* ...  MOVE */
 L1900:
     limit = *tpntrx - 11;
     j = 1;
     l = 13;
     if (limit <= 0) {
     goto L1804;
     } else {
     goto L1801;
     }
 /* ...  VBLJMP */
 L2000:
     oppair_(line + 12, textin, (ftnlen)112);
     itext = textin[1];
     s_copy(line + 20, cnamtb_1.cnamtb + (itext - 1) * 6, (ftnlen)104, (ftnlen)
         6);
     l = 29;
 L2006:
     j = 3;
     limit = *tpntrx - 20 + l / 4;
     if (limit <= 0) {
     goto L2004;
     } else {
     goto L2001;
     }
 L2001:
     i__1 = limit;
     for (i__ = 1; i__ <= i__1; i__ += 13) {
     for (ii = l; ii <= 112; ii += 8) {
         if (*optext > 20) {
         goto L2007;
         }
         itext = textin[j - 1];
         s_copy(line + (ii - 1), cnamtb_1.cnamtb + (itext - 1) * 6, 124 - (
             ii - 1), (ftnlen)6);
         goto L2002;
 L2007:
         holfrm_(&textin[j - 1], line, &ii, &sdp_1.iwrd, &nwd, (ftnlen)124)
             ;
         i__2 = ii + 3;
         s_copy(line + i__2, blk, ii + 7 - i__2, (ftnlen)4);
 L2002:
         ++j;
     }
     foutxx_(&symfil_1.vlfile, line, &c__120, (ftnlen)124);
     l = 13;
     s_copy(line + 8, blk, (ftnlen)4, (ftnlen)4);
 /* L2003: */
     s_copy(line + 4, line, (ftnlen)4, (ftnlen)4);
     }
 L2004:
     i__1 = *tpntrx;
     for (i__ = j; i__ <= i__1; ++i__) {
     if (*optext > 20) {
         goto L2008;
     }
     itext = textin[i__ - 1];
     s_copy(line + (l - 1), cnamtb_1.cnamtb + (itext - 1) * 6, 124 - (l -
         1), (ftnlen)6);
     goto L2005;
 L2008:
     holfrm_(&textin[i__ - 1], line, &l, &sdp_1.iwrd, &nwd, (ftnlen)124);
     i__2 = l + 3;
     s_copy(line + i__2, blk, l + 7 - i__2, (ftnlen)4);
 L2005:
     l += 8;
     }
     k = l;
 L9000:
     if (k > 120) {
     goto L9002;
     }
 /* L9001: */
     s_copy(line + (k - 1), blk, 124 - (k - 1), (ftnlen)4);
 L9002:
     foutxx_(&symfil_1.vlfile, line, &c__120, (ftnlen)124);
     return 0;
 /* ...  HOLDAT */
 L2100:
     itext = textin[0];
     s_copy(line + 12, blk, (ftnlen)112, (ftnlen)4);
     s_copy(line + 16, cnamtb_1.cnamtb + (itext - 1) * 6, (ftnlen)108, (ftnlen)
         6);
     s_copy(line + 24, blk, (ftnlen)100, (ftnlen)4);
     binbcd_(&textin[1], line + 28, &count, (ftnlen)96);
     l = 37;
     goto L2006;
 } /* prtil_ */
Variable Documentation
integer axfile
Definition at line 43 of file PRTIL.c.
integer c__116 = 116 static
Definition at line 53 of file PRTIL.c.
Referenced by prtil_().
integer c__120 = 120 static
Definition at line 54 of file PRTIL.c.
Referenced by prtil_().
integer charnd
Definition at line 24 of file PRTIL.c.
integer charst
Definition at line 24 of file PRTIL.c.
integer clfil3
Definition at line 43 of file PRTIL.c.
integer clfile
Definition at line 43 of file PRTIL.c.
integer clfilp
Definition at line 43 of file PRTIL.c.
char cnamtb[18000]
Definition at line 31 of file PRTIL.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 31 of file PRTIL.c.
integer cpfile
Definition at line 43 of file PRTIL.c.
integer elfil1
Definition at line 43 of file PRTIL.c.
integer elfil2
Definition at line 43 of file PRTIL.c.
integer elfil3
Definition at line 43 of file PRTIL.c.
integer elfil4
Definition at line 43 of file PRTIL.c.
integer elfile
Definition at line 43 of file PRTIL.c.
integer exfile
Definition at line 43 of file PRTIL.c.
integer ifac
Definition at line 18 of file PRTIL.c.
integer ifixnd
Definition at line 24 of file PRTIL.c.
integer ifixst
Definition at line 24 of file PRTIL.c.
integer iltext[94]
Definition at line 37 of file PRTIL.c.
struct { ... } iltext_
integer inamnd
Definition at line 24 of file PRTIL.c.
integer inamst
Definition at line 24 of file PRTIL.c.
integer infile__
Definition at line 43 of file PRTIL.c.
integer ispare[26]
Definition at line 43 of file PRTIL.c.
integer iwrd
Definition at line 18 of file PRTIL.c.
integer ldafil
Definition at line 43 of file PRTIL.c.
integer libfil
Definition at line 43 of file PRTIL.c.
integer mactxt
Definition at line 43 of file PRTIL.c.
integer namest
Definition at line 24 of file PRTIL.c.
struct { ... } nametb_
integer nammax
Definition at line 24 of file PRTIL.c.
integer namtbl[3000]
Definition at line 24 of file PRTIL.c.
integer nbchar
Definition at line 18 of file PRTIL.c.
integer nbwrd
Definition at line 18 of file PRTIL.c.
integer nfil12
Definition at line 43 of file PRTIL.c.
integer nfil13
Definition at line 43 of file PRTIL.c.
integer numbnd
Definition at line 24 of file PRTIL.c.
integer numbst
Definition at line 24 of file PRTIL.c.
integer pnchfl
Definition at line 43 of file PRTIL.c.
integer pofile
Definition at line 43 of file PRTIL.c.
integer pxfile
Definition at line 43 of file PRTIL.c.
struct { ... } sdp_
struct { ... } symfil_
integer tifile
Definition at line 43 of file PRTIL.c.
integer vlfile
Definition at line 43 of file PRTIL.c.
integer xcan
Definition at line 43 of file PRTIL.c.
integer xnum
Definition at line 43 of file PRTIL.c.