My Project: PUNCHC.c File Reference
PUNCHC.c File Reference
#include "f2c.h"
Macros
#define puntab_1 puntab_
#define darray_1 darray_
Functions
int punchc_0_ (int n__, integer *n, char *a, integer *j, integer *k, ftnlen a_len)
int punchc_ (integer *n, char *a, integer *j, integer *k, ftnlen a_len)
int punchd_ (integer *n, char *a, integer *j, integer *k, ftnlen a_len)
Variables
struct {
integer1 puncod [128]
} puntab_
struct {
char darray [120]
} darray_
static integer c__2 = 2
static integer c__48 = 48
Macro Definition Documentation
#define darray_1 darray_
Definition at line 27 of file PUNCHC.c.
Referenced by punchc_0_().
#define puntab_1 puntab_
Definition at line 21 of file PUNCHC.c.
Referenced by punchc_0_().
Function Documentation
int punchc_ (integer * n, char * a, integer * j, integer * k, ftnlen a_len)
Definition at line 156 of file PUNCHC.c.
References punchc_0_().
 {
     return punchc_0_(0, n, a, j, k, a_len);
     }
int punchc_0_ (int n__, integer * n, char * a, integer * j, integer * k, ftnlen a_len)
Definition at line 36 of file PUNCHC.c.
References c__2, c__48, cform_(), cprint_(), darray_1, i__, ic, l, m, n, puntab_1, and tapepn_().
Referenced by punchc_(), and punchd_().
 {
     /* Initialized data */
     static integer1 ilegal = 238;
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, l, m, ic, jc;
     static char infil[512];
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen), tapepn_(integer1 *, integer *), cprint_(char *,
         ftnlen);
     static char outfil[512];
     static integer1 punout[512];
 /*  * PUNCHC *   VAX-11 FORTRAN 77 VERSION 29.11.82 E.MCLELLAN */
 /*               REVISED FOR CHARACTER HANDLING 5.9.85 E.MCL. */
 /*  PURPOSE     TO GENERATE REQUIRED PAPER TAPE CODES FOR CHARACTERS */
 /*  CALLING SEQUENCE */
 /*              CALL PUNCHC(N,A,J,K) */
 /*  ARGUMENTS */
 /*              N NUMBER OF CHARACTERS IN A */
 /*              A CHARACTER STRING TO BE PUNCHED */
 /*              J NUMBER OF CHARACTERS PUNCHED */
 /*              K -2  BLANKS AND PERIODS IGNORED */
 /*                -1  PERIODS IGNORED */
 /*                 0  BLANKS IGNORED */
 /*                >0  BLANKS ARE PROCESSED */
 /*  ALTERNATE ENTRY */
 /*              CALL PUNCHD(N,A,J,K) */
 /* ...BYTE VARIABLES IN THIS VAX IMPLEMENTATION MIGHT BE ABLE TO BE LOGICA */
 /* ...ON OTHER SYSTEMS */
 /*      DATA ILEGAL/ZEE/ */
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
     switch(n__) {
     case 1: goto L_punchd;
     }
 L_punchd:
     s_copy(infil, a, (ftnlen)512, (ftnlen)512);
     m = *n;
     if (*k <= 0) {
     l = 1;
     i__1 = *n;
     for (i__ = 1; i__ <= i__1; ++i__) {
         if (*(unsigned char *)&infil[i__ - 1] == ' ' && (*k == 0 || *k ==
             -2)) {
         goto L10;
         } else if (*(unsigned char *)&infil[i__ - 1] == '.' && *k < 0) {
         goto L10;
         } else {
         *(unsigned char *)&outfil[l - 1] = *(unsigned char *)&infil[
             i__ - 1];
         ++l;
         }
 L10:
         ;
     }
     m = l - 1;
     } else {
     s_copy(outfil, infil, (ftnlen)512, (ftnlen)512);
     }
 /* .....CONVERT TO REQUIRED TAPE CODE */
     jc = 0;
     i__1 = m;
     for (i__ = 1; i__ <= i__1; ++i__) {
     ic = *(unsigned char *)&outfil[i__ - 1] + 1;
     if (puntab_1.puncod[ic - 1] == ilegal) {
         cform_("**** ILLEGAL CHARACTER CONVERSION IN PUNCHC ****",
             darray_1.darray, &c__2, &c__48, (ftnlen)48, (ftnlen)120);
         cprint_(darray_1.darray, (ftnlen)120);
         goto L100;
     }
     ++jc;
     punout[jc - 1] = puntab_1.puncod[ic - 1];
 L100:
     ;
     }
 /* .....OUTPUT TO PUNCH FILE, JC IS NO OF BYTES */
     tapepn_(punout, &jc);
     *j = jc;
     return 0;
 } /* punchc_ */
int punchd_ (integer * n, char * a, integer * j, integer * k, ftnlen a_len)
Definition at line 162 of file PUNCHC.c.
References punchc_0_().
 {
     return punchc_0_(1, n, a, j, k, a_len);
     }
Variable Documentation
integer c__2 = 2 static
Definition at line 31 of file PUNCHC.c.
Referenced by punchc_0_().
integer c__48 = 48 static
Definition at line 32 of file PUNCHC.c.
Referenced by punchc_0_().
char darray[120]
Definition at line 24 of file PUNCHC.c.
struct { ... } darray_
integer1 puncod[128]
Definition at line 18 of file PUNCHC.c.
struct { ... } puntab_