My Project: PUNIDN.c File Reference
PUNIDN.c File Reference
#include "f2c.h"
Macros
#define pun_1 pun_
Functions
int punidn_0_ (int n__, real *a, real *b, real *c__)
int punidn_ (real *a)
int punseq_ (real *b)
int punnum_ (real *c__)
Variables
struct {
real pnid
real pno
} pun_
Macro Definition Documentation
#define pun_1 pun_
Definition at line 21 of file PUNIDN.c.
Referenced by punidn_0_().
Function Documentation
int punidn_ (real * a)
Definition at line 63 of file PUNIDN.c.
References punidn_0_().
 {
     return punidn_0_(0, a, (real *)0, (real *)0);
     }
int punidn_0_ (int n__, real * a, real * b, real * c__)
Definition at line 25 of file PUNIDN.c.
References a, b, and pun_1.
Referenced by punidn_(), punnum_(), and punseq_().
 {
 /*  * PUNIDN *  VAX-11 FORTRAN 77 VERSION  21.10.82  E.MCLELLAN */
 /*  PURPOSE     TO SET UP CARD IDENTIFICATION AND SEQUENCE NUMBERS */
 /*  CALLING SEQUENCE */
 /*              CALL PUNIDN(A) */
 /*  ARGUMENTS */
 /*             A  ADDRESS FIELD OF 4 BCD CHARACTERS */
 /*  ALTERNATE ENTRIES */
 /*             CALL PUNSEQ(B) */
 /*             B  START SEQUENCE NUMBER TO BE PUNCHED - REAL*4 */
 /*             CALL PUNNUM(C) */
 /*             C  LATEST SEQUENCE NUMBER BEING PUNCHED - REAL*4 */
     switch(n__) {
     case 1: goto L_punseq;
     case 2: goto L_punnum;
     }
     pun_1.pnid = *a;
     return 0;
 L_punseq:
     pun_1.pno = *b;
     return 0;
 L_punnum:
     *c__ = pun_1.pno;
     return 0;
 } /* punidn_ */
int punnum_ (real * c__)
Definition at line 73 of file PUNIDN.c.
References punidn_0_().
 {
     return punidn_0_(2, (real *)0, (real *)0, c__);
     }
int punseq_ (real * b)
Definition at line 68 of file PUNIDN.c.
References punidn_0_().
 {
     return punidn_0_(1, (real *)0, b, (real *)0);
     }
Variable Documentation
real pnid
Definition at line 18 of file PUNIDN.c.
real pno
Definition at line 18 of file PUNIDN.c.
struct { ... } pun_