My Project: PUNIDS.c File Reference
PUNIDS.c File Reference
#include "f2c.h"
Macros
#define pun_1 pun_
Functions
doublereal punids_0_ (int n__)
doublereal punids_ (void)
doublereal punnom_ (void)
Variables
struct {
real pnid
real pno
} pun_
Macro Definition Documentation
#define pun_1 pun_
Definition at line 21 of file PUNIDS.c.
Referenced by punids_0_().
Function Documentation
doublereal punids_ (void)
Definition at line 60 of file PUNIDS.c.
References punids_0_().
 {
     return punids_0_(0);
     }
doublereal punids_0_ (int n__)
Definition at line 25 of file PUNIDS.c.
References pun_1.
Referenced by punids_(), and punnom_().
 {
     /* System generated locals */
     real ret_val;
 /*  * PUNIDS *  VAX-11 FORTRAN 77 VERSION  21.10.82  E.MCLELLAN */
 /*  PURPOSE     TO RETREIVE CARD IDENTIFICATION AND SEQUENCE NUMBER */
 /*  CALLING SEQUENCE */
 /*              VALUE = PUNIDS() */
 /*  ARGUMENT */
 /*              NONE    NOTE: PARENTHESIS MUST APPEAR */
 /*              VALUE   WILL CONTAIN 4 BCD CHARACTERS BEING IDENT */
 /*  ALTERNATE ENTRY */
 /*              VALUE = PUNNOM() */
 /*              VALUE   WILL CONTAIN REAL*4 VALUE BEING CURRENT */
 /*                      SEQUENCE NUMBER */
     switch(n__) {
     case 1: goto L_punnom;
     }
     ret_val = pun_1.pnid;
     return ret_val;
 L_punnom:
     ret_val = pun_1.pno;
     return ret_val;
 } /* punids_ */
doublereal punnom_ (void)
Definition at line 65 of file PUNIDS.c.
References punids_0_().
 {
     return punids_0_(1);
     }
Variable Documentation
real pnid
Definition at line 18 of file PUNIDS.c.
real pno
Definition at line 18 of file PUNIDS.c.
struct { ... } pun_