My Project: PUTTMP.c File Reference
PUTTMP.c File Reference
#include "f2c.h"
Macros
#define tmp_1 tmp_
#define symfil_1 symfil_
Functions
int puttmp_ (integer *mode)
Variables
struct {
integer txxxx [64]
} tmp_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
static integer c__24 = 24
Macro Definition Documentation
#define symfil_1 symfil_
Definition at line 30 of file PUTTMP.c.
Referenced by puttmp_().
#define tmp_1 tmp_
Definition at line 21 of file PUTTMP.c.
Referenced by puttmp_().
Function Documentation
int puttmp_ (integer * mode)
Definition at line 60 of file PUTTMP.c.
References binbcd_(), c__24, foutxx_(), i__, inam, symfil_1, and tmp_1.
Referenced by inpat_(), larges_(), lcanon_(), macrec_(), pro020_(), pro021_(), pro026_(), pro027_(), pro028_(), recog_(), recogn_(), replac_(), and subcod_().
 {
     /* Initialized data */
     static char inam[24] = " PUTTMP ERROR           ";
     static integer i__;
     extern /* Subroutine */ int binbcd_(integer *, char *, integer *, ftnlen),
          foutxx_(integer *, char *, integer *, ftnlen);
 /*        6.    GHOST STACK FOR OBJECT TIME TEMPORARY ALLOCATION */
 /*              LENGTH AND CURRENT NUMBER OF ACTIVE TEMPORARY STORAGE */
 /*       33.    SYMBOLIC FILE DEFINITIONS */
 /* ELFIL1:      OUTPUT OF PACKING FACTOR FOR CREATING PAGES (INTERPRETER) */
 /* * */
 /* ARGUMENT     MODE      MODE OF TEMPORARY STORAGE NAME TO BE RELEASED */
 /* ...                SYSTEM I/O FILES */
 /* ** */
     if (tmp_1.txxxx[(0 + (0 + (2 + (*mode << 1) - 3 << 2))) / 4] == 0) {
     goto L999;
     }
     --tmp_1.txxxx[(*mode << 1) - 1];
     return 0;
 /*     ERROR */
 L999:
     binbcd_(mode, inam + 16, &i__, (ftnlen)8);
     foutxx_(&symfil_1.elfil1, inam, &c__24, (ftnlen)24);
     return 0;
 } /* puttmp_ */
Variable Documentation
integer axfile
Definition at line 24 of file PUTTMP.c.
integer c__24 = 24 static
Definition at line 34 of file PUTTMP.c.
Referenced by puttmp_().
integer clfil3
Definition at line 24 of file PUTTMP.c.
integer clfile
Definition at line 24 of file PUTTMP.c.
integer clfilp
Definition at line 24 of file PUTTMP.c.
integer cpfile
Definition at line 24 of file PUTTMP.c.
integer elfil1
Definition at line 24 of file PUTTMP.c.
integer elfil2
Definition at line 24 of file PUTTMP.c.
integer elfil3
Definition at line 24 of file PUTTMP.c.
integer elfil4
Definition at line 24 of file PUTTMP.c.
integer elfile
Definition at line 24 of file PUTTMP.c.
integer exfile
Definition at line 24 of file PUTTMP.c.
integer infile__
Definition at line 24 of file PUTTMP.c.
integer ispare[26]
Definition at line 24 of file PUTTMP.c.
integer ldafil
Definition at line 24 of file PUTTMP.c.
integer libfil
Definition at line 24 of file PUTTMP.c.
integer mactxt
Definition at line 24 of file PUTTMP.c.
integer nfil12
Definition at line 24 of file PUTTMP.c.
integer nfil13
Definition at line 24 of file PUTTMP.c.
integer pnchfl
Definition at line 24 of file PUTTMP.c.
integer pofile
Definition at line 24 of file PUTTMP.c.
integer pxfile
Definition at line 24 of file PUTTMP.c.
struct { ... } symfil_
integer tifile
Definition at line 24 of file PUTTMP.c.
struct { ... } tmp_
integer txxxx[64]
Definition at line 18 of file PUTTMP.c.
integer vlfile
Definition at line 24 of file PUTTMP.c.
integer xcan
Definition at line 24 of file PUTTMP.c.
integer xnum
Definition at line 24 of file PUTTMP.c.