My Project: RADAR.c File Reference
RADAR.c File Reference
#include "f2c.h"
Macros
#define dshar4_1 dshar4_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define _BLNK__1 _BLNK__
#define can ((doublereal *)&_BLNK__1 + 40)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int radar_ (void)
Variables
struct {
doublereal a
doublereal b
doublereal c__
doublereal cendis
doublereal cmove [3]
doublereal com1
doublereal com4
doublereal dir [3]
doublereal dp
doublereal dpe
doublereal dpcnt
doublereal dpi
doublereal dpl
doublereal dp1
doublereal d1
doublereal d2a
doublereal flipck
doublereal fwd [3]
doublereal ogle [3]
doublereal p1 [3]
doublereal p2 [3]
doublereal rdrn
doublereal refpnt [3]
doublereal tangl
doublereal tes [3]
doublereal tew [3]
doublereal uvec [3]
doublereal u2 [3]
doublereal v [3]
doublereal vl
doublereal zl
doublereal zlnorm [3]
doublereal zlpnt [3]
doublereal zl1
doublereal param [6]
doublereal r__ [6]
doublereal savpar [4]
doublereal seg [9]
doublereal slope
doublereal sqroot
doublereal unn
doublereal upp
doublereal vint
doublereal vnn
doublereal vpp
} dshar4_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
doublereal com [36000]
} _BLNK__
static integer c__26803 = 26803
static integer c__26802 = 26802
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 113 of file RADAR.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
Referenced by radar_().
#define charct_1 charct_
Definition at line 40 of file RADAR.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define dshar4_1 dshar4_
Definition at line 25 of file RADAR.c.
#define fxcor_1 fxcor_
Definition at line 34 of file RADAR.c.
#define ifxcor_1 ifxcor_
Definition at line 99 of file RADAR.c.
Referenced by radar_().
#define ishr18_1 ishr18_
Definition at line 107 of file RADAR.c.
Referenced by radar_().
#define isv1_1 isv1_
Definition at line 89 of file RADAR.c.
#define isv_1 isv_
Definition at line 82 of file RADAR.c.
Referenced by radar_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define sv1_1 sv1_
Definition at line 73 of file RADAR.c.
#define sv_1 sv_
Definition at line 64 of file RADAR.c.
Referenced by radar_().
#define tlldat_1 tlldat_
Definition at line 47 of file RADAR.c.
Function Documentation
int radar_ (void)
Definition at line 123 of file RADAR.c.
References aerr_(), c__26802, c__26803, canon, cross_(), ddcyln_(), ddplan_(), ddquad_(), f, i__, ifxcor_1, ishr18_1, isv_1, kn, one, sv_1, vnorm_(), w1, and zero.
Referenced by ajundd_().
 {
     /* Initialized data */
     static doublereal one = 1.;
     static doublereal zlit1 = .8;
     static doublereal radang[5] = { .5255,.1309,1.0472,1.5707,.7854 };
     static integer kn = 9;
     static doublereal zero = 0.;
     /* Builtin functions */
     double cos(doublereal), sin(doublereal);
     /* Local variables */
     static integer i__;
     static doublereal w1;
 #define can ((doublereal *)&_BLNK__1 + 40)
     static doublereal crdr[3];
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static doublereal axis1[3], axis2[3], axis3[3];
     static integer jmdic;
 #define canon ((doublereal *)&_BLNK__1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int vnorm_(doublereal *, doublereal *), cross_(
         doublereal *, doublereal *, doublereal *);
     static integer iswiv;
     static doublereal aswiv;
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int ddplan_(doublereal *), ddquad_(doublereal *),
         ddcyln_(doublereal *);
     static integer ilayer, istsav;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /* C                 30 DEGS   7.5       60       90         45 DEGS */
 /*              /-PURPOSE OF RADAR IS TO MAKE ADDITIONAL TP,TN TO PIERCE */
 /*              /-SURFACE AFTER ONE CANDIDATE TP,TN FAILED. */
 L100:
 /*              /-MDIC IS THE COUNT OF RADAR TRIES WITHOUT SUCCESS */
     ++ishr18_1.mdic;
     if (ishr18_1.mdic == kn) {
     goto L130;
     }
     if (ishr18_1.mdic > kn) {
     goto L200;
     }
 /*             /-MDIC IS LES THAN KN, PRELIMINARY RESTART ATTEMPTS. */
 /*              /-FIRST ATTEMPT IS TO MOVE TP TOWARD LAST GOOD SP */
 /*              /-IF JENT IS 1 AND IAMDCT 0 NO SP IS AVAILABLE */
     if (ishr18_1.iamdct < isv_1.jent[ifxcor_1.is - 1]) {
     goto L130;
     }
 /*              /-TP LIES ONE HALF OF THE WAY BETWEEN TP AND SP */
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] += (sv_1.sp[i__ + ifxcor_1.is * 3
         - 4] - sv_1.tp[i__ + ifxcor_1.is * 3 - 4]) * .6f;
 /* L125: */
     }
     goto L999;
 /*              /-CONSTRUCT SURFACE NORMAL THRU EXT TP POINT AND USE THIS */
 /*              /-NORMAL FOR A NEW TN IF POSSIBLE */
 L130:
     ishr18_1.mdic = kn;
     if (isv_1.iunfl[ifxcor_1.is - 1] <= 0) {
     goto L100;
     }
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.sp[i__ + ifxcor_1.is * 3 - 4] = sv_1.tp[i__ + ifxcor_1.is * 3 -
         4];
 /* L134: */
     }
 /*              /-CALL DIRECTED DISTANCE ROUTINE FOR SURF WITH UNIT NORMA */
 /*              /- THRU EXTERIOR POINT CAPABILITY */
     ifxcor_1.ic = isv_1.icanon[ifxcor_1.is - 1];
     ifxcor_1.jsw = isv_1.isfidn[ifxcor_1.is - 1];
     istsav = ifxcor_1.istrup;
 /*             /-SET ISTRUP TO 5 FOR SPECIAL CALCULATION IN DD ROUTINES */
     ifxcor_1.istrup = 5;
     switch (ifxcor_1.jsw) {
     case 1:  goto L1;
     case 2:  goto L1;
     case 3:  goto L3;
     case 4:  goto L3;
     case 5:  goto L6;
     case 6:  goto L6;
     case 7:  goto L6;
     case 8:  goto L6;
     case 9:  goto L6;
     case 10:  goto L6;
     case 11:  goto L139;
     case 12:  goto L139;
     case 13:  goto L139;
     case 14:  goto L6;
     case 15:  goto L139;
     }
 L139:
     ifxcor_1.istrup = istsav;
     if (ifxcor_1.ier > 0) {
     goto L100;
     }
 /*              /-USE SN FOR NEW TN */
     w1 = one;
     if (isv_1.jtn[ifxcor_1.is - 1] == 0) {
     w1 = -one;
     }
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = w1 * sv_1.sn[i__ + ifxcor_1.is *
         3 - 4];
 /* L140: */
     }
     goto L999;
 L1:
     ddplan_(&canon[ifxcor_1.ic - 1]);
     goto L139;
 L3:
     ddcyln_(&canon[ifxcor_1.ic - 1]);
     goto L139;
 L6:
     ddquad_(&canon[ifxcor_1.ic - 1]);
     goto L139;
 /*              /-SEARCH PATTERN - SEND TOOL RAYS IN CONICAL LAYERS */
 /*              /-AROUND LAST GOOD TN. */
 L200:
     if (ishr18_1.mdic <= kn + 28) {
     goto L210;
     }
 /*              /-RADAR FAILED IN KN+28 TRIES SO TERMINATE */
     aerr_(&c__26803, "RADAR   ", (ftnlen)8);
     goto L999;
 L210:
     jmdic = ishr18_1.mdic - kn;
     if (jmdic != 1) {
     goto L220;
     }
 /*              /-SET UP BASE SYSTEM OF ORTHONORMAL VECTORS */
 /*              /-FIRST DETERMINE IF TN CAN BE USED */
     vnorm_(&sv_1.tn[ifxcor_1.is * 3 - 3], &sv_1.tn[ifxcor_1.is * 3 - 3]);
     if (ifxcor_1.ier <= 0) {
     goto L230;
     }
 /*              /-NO GOOD TOOL NORMAL, RADAR TERMINATES */
     aerr_(&c__26802, "RADAR   ", (ftnlen)8);
     goto L999;
 L230:
 /*              /-CONSTRUCT COORDINATE SYSTEM AROUND TN */
     for (i__ = 1; i__ <= 3; ++i__) {
     axis1[i__ - 1] = sv_1.tn[i__ + ifxcor_1.is * 3 - 4];
 /* L231: */
     axis2[i__ - 1] = zero;
     }
     w1 = abs(axis1[0]);
     if (w1 < zlit1) {
     axis2[0] = one;
     }
     if (w1 >= zlit1) {
     axis2[1] = one;
     }
     cross_(axis1, axis2, axis2);
     vnorm_(axis2, axis2);
     cross_(axis1, axis2, axis3);
 L220:
 /*              /-INDEX TO CONICAL ANGLE AROUND TN */
     ilayer = (jmdic - 1) / 8 + 1;
 /*              /-DETERMINE MULTIPLE OF SWIVEL ANGLE WITHIN THIS CONE */
     iswiv = jmdic - (ilayer - 1 << 3) - 1;
     aswiv = iswiv * radang[4];
     crdr[0] = cos(radang[ilayer - 1]);
     w1 = sin(radang[ilayer - 1]);
     crdr[1] = cos(aswiv) * w1;
     crdr[2] = sin(aswiv) * w1;
 /*              /-DETERMINE TN WITHIN CONICAL LAYER */
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = crdr[0] * axis1[i__ - 1] + crdr[
         1] * axis2[i__ - 1] + crdr[2] * axis3[i__ - 1];
 /* L240: */
     }
     vnorm_(&sv_1.tn[ifxcor_1.is * 3 - 3], &sv_1.tn[ifxcor_1.is * 3 - 3]);
     if (ifxcor_1.ier > 0) {
     goto L100;
     }
 L999:
     return 0;
 } /* radar_ */
Variable Documentation
struct { ... } _BLNK__
doublereal a
Definition at line 18 of file RADAR.c.
doublereal alp
Definition at line 28 of file RADAR.c.
doublereal ax4[3]
Definition at line 28 of file RADAR.c.
doublereal b
Definition at line 18 of file RADAR.c.
doublereal c__
Definition at line 18 of file RADAR.c.
integer c__26802 = 26802 static
Definition at line 118 of file RADAR.c.
Referenced by radar_().
integer c__26803 = 26803 static
Definition at line 117 of file RADAR.c.
Referenced by radar_().
doublereal cagl
Definition at line 28 of file RADAR.c.
doublereal cc[15]
Definition at line 50 of file RADAR.c.
doublereal cendis
Definition at line 18 of file RADAR.c.
struct { ... } charct_
doublereal cmove[3]
Definition at line 18 of file RADAR.c.
doublereal com[36000]
Definition at line 110 of file RADAR.c.
doublereal com1
Definition at line 18 of file RADAR.c.
doublereal com4
Definition at line 18 of file RADAR.c.
doublereal corrad[8]
Definition at line 43 of file RADAR.c.
doublereal cos1[5]
Definition at line 67 of file RADAR.c.
doublereal cplfl[5]
Definition at line 67 of file RADAR.c.
doublereal cptst[5]
Definition at line 67 of file RADAR.c.
doublereal csd[5]
Definition at line 67 of file RADAR.c.
doublereal cutdat[7]
Definition at line 28 of file RADAR.c.
doublereal d1
Definition at line 18 of file RADAR.c.
doublereal d2a
Definition at line 18 of file RADAR.c.
doublereal dir[3]
Definition at line 18 of file RADAR.c.
doublereal dp
Definition at line 18 of file RADAR.c.
doublereal dp1
Definition at line 18 of file RADAR.c.
doublereal dpcnt
Definition at line 18 of file RADAR.c.
doublereal dpe
Definition at line 18 of file RADAR.c.
doublereal dpi
Definition at line 18 of file RADAR.c.
doublereal dpl
Definition at line 18 of file RADAR.c.
doublereal dplan[15]
Definition at line 67 of file RADAR.c.
doublereal dpmax
Definition at line 28 of file RADAR.c.
doublereal dpmx1[5]
Definition at line 67 of file RADAR.c.
struct { ... } dshar4_
doublereal eps1[5]
Definition at line 50 of file RADAR.c.
doublereal eps2[5]
Definition at line 50 of file RADAR.c.
doublereal eps3[5]
Definition at line 50 of file RADAR.c.
doublereal eps4[5]
Definition at line 50 of file RADAR.c.
doublereal eps6[5]
Definition at line 50 of file RADAR.c.
doublereal eps8[5]
Definition at line 50 of file RADAR.c.
doublereal flipck
Definition at line 18 of file RADAR.c.
doublereal fwd[3]
Definition at line 18 of file RADAR.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file RADAR.c.
doublereal hi
Definition at line 28 of file RADAR.c.
integer i3dflg
Definition at line 92 of file RADAR.c.
integer iaerr
Definition at line 92 of file RADAR.c.
integer iafl[5]
Definition at line 76 of file RADAR.c.
integer iamdct
Definition at line 102 of file RADAR.c.
integer iautps
Definition at line 92 of file RADAR.c.
integer ibegin
Definition at line 92 of file RADAR.c.
integer ic
Definition at line 92 of file RADAR.c.
integer icanon[5]
Definition at line 76 of file RADAR.c.
integer icheck
Definition at line 92 of file RADAR.c.
integer icl
Definition at line 92 of file RADAR.c.
integer ics
Definition at line 92 of file RADAR.c.
integer icscnt
Definition at line 92 of file RADAR.c.
integer ictdef
Definition at line 92 of file RADAR.c.
integer icut
Definition at line 92 of file RADAR.c.
integer ids
Definition at line 92 of file RADAR.c.
integer ier
Definition at line 92 of file RADAR.c.
integer ifar[5]
Definition at line 85 of file RADAR.c.
integer ifl4[5]
Definition at line 85 of file RADAR.c.
struct { ... } ifxcor_
integer igo
Definition at line 92 of file RADAR.c.
integer igoto
Definition at line 92 of file RADAR.c.
integer igoug
Definition at line 92 of file RADAR.c.
integer igs
Definition at line 92 of file RADAR.c.
integer index[5]
Definition at line 76 of file RADAR.c.
integer indir__[5]
Definition at line 76 of file RADAR.c.
integer inops
Definition at line 92 of file RADAR.c.
integer iop[5]
Definition at line 76 of file RADAR.c.
integer iopset[5]
Definition at line 76 of file RADAR.c.
integer ipdpl
Definition at line 102 of file RADAR.c.
integer ipl[5]
Definition at line 76 of file RADAR.c.
integer ips
Definition at line 92 of file RADAR.c.
integer ipsdef
Definition at line 92 of file RADAR.c.
integer ipt
Definition at line 102 of file RADAR.c.
integer ipt1
Definition at line 92 of file RADAR.c.
integer is
Definition at line 92 of file RADAR.c.
integer iseg
Definition at line 92 of file RADAR.c.
integer iseqno
Definition at line 92 of file RADAR.c.
integer isfidn[5]
Definition at line 76 of file RADAR.c.
integer isftyp[5]
Definition at line 76 of file RADAR.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 76 of file RADAR.c.
integer isrch
Definition at line 92 of file RADAR.c.
integer istrup
Definition at line 92 of file RADAR.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 76 of file RADAR.c.
integer it
Definition at line 92 of file RADAR.c.
integer itlon[5]
Definition at line 76 of file RADAR.c.
integer itseg[5]
Definition at line 76 of file RADAR.c.
integer itsegk[5]
Definition at line 76 of file RADAR.c.
integer iunfl[5]
Definition at line 76 of file RADAR.c.
integer iws
Definition at line 102 of file RADAR.c.
integer j10
Definition at line 102 of file RADAR.c.
integer j12
Definition at line 102 of file RADAR.c.
integer j13
Definition at line 102 of file RADAR.c.
integer j20[5]
Definition at line 85 of file RADAR.c.
integer j21[5]
Definition at line 85 of file RADAR.c.
integer j22[5]
Definition at line 85 of file RADAR.c.
integer j23[5]
Definition at line 85 of file RADAR.c.
integer j50[5]
Definition at line 85 of file RADAR.c.
integer j51[5]
Definition at line 85 of file RADAR.c.
integer j54
Definition at line 102 of file RADAR.c.
integer jbr
Definition at line 92 of file RADAR.c.
integer jckr
Definition at line 102 of file RADAR.c.
integer jcnt1
Definition at line 102 of file RADAR.c.
integer jcnt2
Definition at line 102 of file RADAR.c.
integer jcnt3
Definition at line 102 of file RADAR.c.
integer jcpr
Definition at line 102 of file RADAR.c.
integer jcr
Definition at line 102 of file RADAR.c.
integer jdr
Definition at line 102 of file RADAR.c.
integer jent[5]
Definition at line 76 of file RADAR.c.
integer jfind
Definition at line 102 of file RADAR.c.
integer jgr
Definition at line 102 of file RADAR.c.
integer jiops[5]
Definition at line 76 of file RADAR.c.
integer jmin
Definition at line 102 of file RADAR.c.
integer jminr
Definition at line 102 of file RADAR.c.
integer jph[5]
Definition at line 85 of file RADAR.c.
integer jpr
Definition at line 102 of file RADAR.c.
integer jpxr
Definition at line 102 of file RADAR.c.
integer jsw
Definition at line 92 of file RADAR.c.
integer jtkf
Definition at line 102 of file RADAR.c.
integer jtlflg[5]
Definition at line 76 of file RADAR.c.
integer jtn[5]
Definition at line 76 of file RADAR.c.
integer jtr
Definition at line 102 of file RADAR.c.
integer ju1[5]
Definition at line 76 of file RADAR.c.
integer limfl[5]
Definition at line 76 of file RADAR.c.
integer lsv
Definition at line 92 of file RADAR.c.
integer lsv1
Definition at line 92 of file RADAR.c.
integer mantax
Definition at line 92 of file RADAR.c.
integer mdic
Definition at line 102 of file RADAR.c.
char modfer[6]
Definition at line 37 of file RADAR.c.
integer motmod
Definition at line 92 of file RADAR.c.
integer msav
Definition at line 92 of file RADAR.c.
integer mulout
Definition at line 92 of file RADAR.c.
integer nmbseg
Definition at line 92 of file RADAR.c.
integer nmpnts
Definition at line 92 of file RADAR.c.
integer notan[5]
Definition at line 85 of file RADAR.c.
integer nrec
Definition at line 92 of file RADAR.c.
integer numax
Definition at line 92 of file RADAR.c.
integer numcnt
Definition at line 92 of file RADAR.c.
integer nump
Definition at line 92 of file RADAR.c.
integer numpt1
Definition at line 92 of file RADAR.c.
integer numsfs
Definition at line 92 of file RADAR.c.
integer numsur
Definition at line 92 of file RADAR.c.
integer nw
Definition at line 92 of file RADAR.c.
integer nwds
Definition at line 92 of file RADAR.c.
doublereal ogle[3]
Definition at line 18 of file RADAR.c.
doublereal p1[3]
Definition at line 18 of file RADAR.c.
doublereal p2[3]
Definition at line 18 of file RADAR.c.
doublereal param[6]
Definition at line 18 of file RADAR.c.
doublereal past[5]
Definition at line 50 of file RADAR.c.
doublereal plncs[5]
Definition at line 67 of file RADAR.c.
doublereal plnd[5]
Definition at line 50 of file RADAR.c.
doublereal plnd1[5]
Definition at line 67 of file RADAR.c.
doublereal plnv[15]
Definition at line 50 of file RADAR.c.
doublereal pltst[5]
Definition at line 67 of file RADAR.c.
doublereal pmove[3]
Definition at line 28 of file RADAR.c.
doublereal r__[6]
Definition at line 18 of file RADAR.c.
doublereal ra
Definition at line 28 of file RADAR.c.
doublereal rc[5]
Definition at line 50 of file RADAR.c.
doublereal rc1
Definition at line 28 of file RADAR.c.
doublereal rdrn
Definition at line 18 of file RADAR.c.
doublereal refpnt[3]
Definition at line 18 of file RADAR.c.
doublereal ri[8]
Definition at line 43 of file RADAR.c.
doublereal s[5]
Definition at line 50 of file RADAR.c.
doublereal sagl
Definition at line 28 of file RADAR.c.
doublereal save[5]
Definition at line 50 of file RADAR.c.
doublereal savpar[4]
Definition at line 18 of file RADAR.c.
doublereal seg[9]
Definition at line 18 of file RADAR.c.
doublereal sfvct[15]
Definition at line 50 of file RADAR.c.
doublereal sk[15]
Definition at line 50 of file RADAR.c.
doublereal slope
Definition at line 18 of file RADAR.c.
doublereal slx[15]
Definition at line 50 of file RADAR.c.
doublereal sn[15]
Definition at line 50 of file RADAR.c.
doublereal snk[15]
Definition at line 50 of file RADAR.c.
doublereal snl[15]
Definition at line 50 of file RADAR.c.
doublereal sp[15]
Definition at line 50 of file RADAR.c.
doublereal spk[15]
Definition at line 50 of file RADAR.c.
doublereal spl[15]
Definition at line 50 of file RADAR.c.
doublereal sqroot
Definition at line 18 of file RADAR.c.
doublereal stck[5]
Definition at line 67 of file RADAR.c.
doublereal stck1[5]
Definition at line 67 of file RADAR.c.
doublereal stck2[5]
Definition at line 67 of file RADAR.c.
doublereal stckn[5]
Definition at line 67 of file RADAR.c.
doublereal strtno
Definition at line 28 of file RADAR.c.
doublereal surd
Definition at line 28 of file RADAR.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 28 of file RADAR.c.
doublereal tak[3]
Definition at line 28 of file RADAR.c.
doublereal tal[3]
Definition at line 28 of file RADAR.c.
doublereal tangl
Definition at line 18 of file RADAR.c.
doublereal tanhi[8]
Definition at line 43 of file RADAR.c.
doublereal tanlo[8]
Definition at line 43 of file RADAR.c.
doublereal tau[5]
Definition at line 50 of file RADAR.c.
doublereal tau1[5]
Definition at line 50 of file RADAR.c.
doublereal tau2[5]
Definition at line 50 of file RADAR.c.
doublereal tcont[9]
Definition at line 43 of file RADAR.c.
doublereal te[3]
Definition at line 28 of file RADAR.c.
doublereal tee[15]
Definition at line 67 of file RADAR.c.
doublereal tek[3]
Definition at line 28 of file RADAR.c.
doublereal tel[3]
Definition at line 28 of file RADAR.c.
doublereal tem[10]
Definition at line 28 of file RADAR.c.
doublereal temp[24]
Definition at line 28 of file RADAR.c.
doublereal tes[3]
Definition at line 18 of file RADAR.c.
doublereal tew[3]
Definition at line 18 of file RADAR.c.
doublereal th[5]
Definition at line 50 of file RADAR.c.
doublereal ti[3]
Definition at line 28 of file RADAR.c.
doublereal tik[3]
Definition at line 28 of file RADAR.c.
doublereal til[3]
Definition at line 28 of file RADAR.c.
doublereal tlhit
Definition at line 28 of file RADAR.c.
doublereal tlhite[8]
Definition at line 43 of file RADAR.c.
doublereal tlinc[9]
Definition at line 43 of file RADAR.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file RADAR.c.
doublereal tn[15]
Definition at line 50 of file RADAR.c.
doublereal tnl[15]
Definition at line 67 of file RADAR.c.
doublereal toolht[15]
Definition at line 50 of file RADAR.c.
doublereal toolwd[5]
Definition at line 50 of file RADAR.c.
doublereal tp[15]
Definition at line 50 of file RADAR.c.
doublereal tpk[15]
Definition at line 50 of file RADAR.c.
doublereal u1[15]
Definition at line 50 of file RADAR.c.
doublereal u1k[15]
Definition at line 50 of file RADAR.c.
doublereal u2[3]
Definition at line 18 of file RADAR.c.
doublereal umax[8]
Definition at line 43 of file RADAR.c.
doublereal unn
Definition at line 18 of file RADAR.c.
doublereal upp
Definition at line 18 of file RADAR.c.
doublereal uvec[3]
Definition at line 18 of file RADAR.c.
doublereal v[3]
Definition at line 18 of file RADAR.c.
doublereal varble[5]
Definition at line 50 of file RADAR.c.
doublereal vint
Definition at line 18 of file RADAR.c.
doublereal vl
Definition at line 18 of file RADAR.c.
doublereal vndir[15]
Definition at line 50 of file RADAR.c.
doublereal vnn
Definition at line 18 of file RADAR.c.
doublereal vpp
Definition at line 18 of file RADAR.c.
doublereal vt[15]
Definition at line 50 of file RADAR.c.
doublereal vtem
Definition at line 28 of file RADAR.c.
doublereal z__[5]
Definition at line 50 of file RADAR.c.
doublereal zl
Definition at line 18 of file RADAR.c.
doublereal zl1
Definition at line 18 of file RADAR.c.
doublereal zlnorm[3]
Definition at line 18 of file RADAR.c.
doublereal zlpnt[3]
Definition at line 18 of file RADAR.c.