My Project: RECORD.c File Reference
RECORD.c File Reference
#include "f2c.h"
Macros
#define sqnc_1 sqnc_
Functions
int record_ (integer *iseqno)
Variables
struct {
integer sqno
} sqnc_
Macro Definition Documentation
#define sqnc_1 sqnc_
Definition at line 21 of file RECORD.c.
Referenced by record_().
Function Documentation
int record_ (integer * iseqno)
Definition at line 26 of file RECORD.c.
References sqnc_1.
Referenced by aerr2_(), aerr_(), apt233_(), apt235_(), apt296_(), apt297_(), apt299_(), clput_(), ddssrf_(), error_(), fini_(), gol_(), gop_(), goretr_(), intout_(), intrp_(), mesh_(), pocket_(), print_(), region_(), scon_(), set_(), smil_(), sspath_(), tlconv_(), and units_().
 {
     *iseqno = sqnc_1.sqno;
     return 0;
 } /* record_ */
Variable Documentation
struct { ... } sqnc_
integer sqno
Definition at line 18 of file RECORD.c.