My Project: REFGEN.c File Reference
REFGEN.c File Reference
#include "f2c.h"
Macros
#define negptr_1 negptr_
#define sublst_1 sublst_
#define defext ((integer *)&sublst_1 + 81)
#define aptyyy ((integer *)&sublst_1 + 120)
Functions
int refgen_ (integer *iref, integer *namptr)
Variables
struct {
integer nonept
} negptr_
struct {
integer sublst [136]
} sublst_
Macro Definition Documentation
#define aptyyy ((integer *)&sublst_1 + 120)
Referenced by refgen_().
#define defext ((integer *)&sublst_1 + 81)
Referenced by refgen_().
#define negptr_1 negptr_
Definition at line 21 of file REFGEN.c.
Referenced by refgen_().
#define sublst_1 sublst_
Definition at line 27 of file REFGEN.c.
Function Documentation
int refgen_ (integer * iref, integer * namptr)
Definition at line 43 of file REFGEN.c.
References aptyyy, argcvt_(), callzz_(), defext, negptr_1, and rlslin_().
Referenced by pro021_(), pro026_(), pro027_(), pro028_(), and recogn_().
 {
     /* Local variables */
 #define defext ((integer *)&sublst_1 + 81)
     extern /* Subroutine */ int argcvt_(integer *), callzz_(integer *),
         rlslin_(void);
 #define aptyyy ((integer *)&sublst_1 + 120)
 /*       13.    NAMTBL POINTERS TO NEGATIVE NUMBERS */
 /*              NAMTBL POINTER TO -1. */
 /*       28.    OPERAND MODIFIERS */
 /* APTYYY:      NAMTBL POINTERS FOR XECUTION SUBROUTINE NAMES */
 /* DEFEXT:      NAMTBL POINTER FOR XECUTION SUBROUTINE DEFEXT */
 /* * */
 /* ARGUMENTS    IREF       APTYYY INDEX CONTAINING NAME TABLE */
 /*                         (NAMTBL) INDEX OF TRANSFORMATION ROUTINE. */
 /*              NAMPTR    NAME TABLE (NAMTBL) INDEX OF VARIABLE */
 /*                        TO BE TRANSFORMED. */
 /* NOTES        FOLLOWING IS A LIST OF EACH IREF VALUE WITH */
 /*              ITS ASSOCIATED SURFACE AND TRANSFORMATION ROUTINE NAME. */
 /*              IREF       VARIABLE MODE         TRANSFORMATION */
 /*              1             POINT, SPHERE         APT081 */
 /*              2             CIRCLE                APT083 */
 /*              3             VECTOR                ATP078 */
 /*              4             LINE, PLANE           APT077 */
 /*              5             QUADRIC SURFACE       APT079 */
 /* ** */
 /* L380: */
     callzz_(&aptyyy[*iref - 1]);
     argcvt_(namptr);
     argcvt_(&negptr_1.nonept);
     rlslin_();
     callzz_(defext);
     argcvt_(namptr);
     rlslin_();
     return 0;
 } /* refgen_ */
Variable Documentation
struct { ... } negptr_
integer nonept
Definition at line 18 of file REFGEN.c.
integer sublst[136]
Definition at line 24 of file REFGEN.c.
struct { ... } sublst_