My Project: REFREF.c File Reference
REFREF.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define stklst_1 stklst_
#define flags_1 flags_
#define modx_1 modx_
#define sublst_1 sublst_
#define apt085 ((integer *)&sublst_1 + 125)
#define refflg ((logical *)&flags_1 + 3)
#define argstk ((integer *)&stklst_1 + 201)
#define argtop ((integer *)&stklst_1 + 1)
#define matrix ((integer *)&modx_1 + 17)
#define refsys ((integer *)&sublst_1 + 133)
Functions
int refref_ (void)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer stklst [300]
} stklst_
struct {
integer flags [4]
} flags_
struct {
integer modx [32]
} modx_
struct {
integer sublst [136]
} sublst_
static integer c__2052 = 2052
static integer c__8 = 8
static integer c__1010 = 1010
static integer c__1011 = 1011
Macro Definition Documentation
#define apt085 ((integer *)&sublst_1 + 125)
Referenced by refref_().
#define argstk ((integer *)&stklst_1 + 201)
Referenced by refref_().
#define argtop ((integer *)&stklst_1 + 1)
Referenced by refref_().
#define cnamtb_1 cnamtb_
Definition at line 28 of file REFREF.c.
Referenced by refref_().
#define flags_1 flags_
Definition at line 40 of file REFREF.c.
#define matrix ((integer *)&modx_1 + 17)
Referenced by refref_().
#define modx_1 modx_
Definition at line 46 of file REFREF.c.
#define nametb_1 nametb_
Definition at line 22 of file REFREF.c.
#define refflg ((logical *)&flags_1 + 3)
Referenced by refref_().
#define refsys ((integer *)&sublst_1 + 133)
Referenced by refref_().
#define stklst_1 stklst_
Definition at line 34 of file REFREF.c.
#define sublst_1 sublst_
Definition at line 52 of file REFREF.c.
Function Documentation
int refref_ (void)
Definition at line 75 of file REFREF.c.
References alarm_(), apt085, argcvt_(), argstk, argtop, c__1010, c__1011, c__2052, c__8, callzz_(), cnamtb_1, i__, matrix, mode_(), refflg, refsys, rlslin_(), and top.
Referenced by pro026_().
 {
     /* Initialized data */
     static char cnmore[6] = "NOMORE";
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, ep, top;
     extern integer mode_(integer *);
 #define apt085 ((integer *)&sublst_1 + 125)
     extern /* Subroutine */ int alarm_(integer *, integer *, integer *, char *
         , ftnlen);
 #define refflg ((logical *)&flags_1 + 3)
     extern /* Subroutine */ int argcvt_(integer *);
 #define argstk ((integer *)&stklst_1 + 201)
 #define argtop ((integer *)&stklst_1 + 1)
     extern /* Subroutine */ int callzz_(integer *), rlslin_(void);
 #define matrix ((integer *)&modx_1 + 17)
 #define refsys ((integer *)&sublst_1 + 133)
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /* NAMMAX:      NAMTBL INDEX OF END OF THE PART PROGRAM NAME SECTION */
 /*        2.    STACK AND POINTER STORAGE */
 /* ARGTOP:      POINTER TO LAST ARGSTK ENTRY */
 /* ARGSTK:      ARGUMENT STACK */
 /*        5.    PROGRAM CONTROL FLAGS */
 /* REFFLG:      TRUE WHEN A REFSYS COMMAND ENCOUNTERED */
 /*       17.    MODE CODES */
 /* MATRIX:      MODE CODE (18) FOR MATRIX */
 /*       28.    OPERAND MODIFIERS */
 /* APT085:      NAMTBL POINTER FOR APT085 */
 /* REFSYS:      NAMTBL POINTER FOR XECUTION SUBROUTINE REFSYS */
 /* ** */
     ep = -1;
     if ((i__1 = *argtop - 1) < 0) {
     goto L20;
     } else if (i__1 == 0) {
     goto L40;
     } else {
     goto L30;
     }
 L20:
     ep = top;
     goto L35;
 L30:
     ep = 1 - *argtop;
 L35:
     alarm_(&c__2052, &ep, &c__8, "REFREF  ", (ftnlen)8);
 L40:
     if (*refflg) {
     goto L1000;
     }
 /*     REFSYS NOT IN EFFECT */
 /*     ARE PARAMETERS CORRECT */
     if (mode_(&argstk[*argtop - 1]) != *matrix) {
     i__1 = -(*argtop);
     alarm_(&c__1010, &i__1, &c__8, "REFREF  ", (ftnlen)8);
     }
     *refflg = TRUE_;
 L5:
     callzz_(refsys);
     argcvt_(&argstk[*argtop - 1]);
 L10:
     rlslin_();
 /* L50: */
     return 0;
 /*     REFSYS IN EFFECT */
 L1000:
     i__ = argstk[*argtop - 1];
     if (mode_(&argstk[*argtop - 1]) == *matrix) {
     goto L5;
     }
     if (s_cmp(cnamtb_1.cnamtb + (i__ - 1) * 6, cnmore, (ftnlen)6, (ftnlen)6)
         != 0) {
     i__1 = -(*argtop);
     alarm_(&c__1011, &i__1, &c__8, "REFREF  ", (ftnlen)8);
     }
     *refflg = FALSE_;
     callzz_(apt085);
     goto L10;
 } /* refref_ */
Variable Documentation
integer c__1010 = 1010 static
Definition at line 58 of file REFREF.c.
Referenced by refref_().
integer c__1011 = 1011 static
Definition at line 59 of file REFREF.c.
Referenced by refref_().
integer c__2052 = 2052 static
Definition at line 56 of file REFREF.c.
Referenced by refref_().
integer c__8 = 8 static
Definition at line 57 of file REFREF.c.
Referenced by refref_().
integer charnd
Definition at line 18 of file REFREF.c.
integer charst
Definition at line 18 of file REFREF.c.
char cnamtb[18000]
Definition at line 25 of file REFREF.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file REFREF.c.
integer flags[4]
Definition at line 37 of file REFREF.c.
struct { ... } flags_
integer ifixnd
Definition at line 18 of file REFREF.c.
integer ifixst
Definition at line 18 of file REFREF.c.
integer inamnd
Definition at line 18 of file REFREF.c.
integer inamst
Definition at line 18 of file REFREF.c.
integer modx[32]
Definition at line 43 of file REFREF.c.
struct { ... } modx_
integer namest
Definition at line 18 of file REFREF.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file REFREF.c.
integer namtbl[3000]
Definition at line 18 of file REFREF.c.
integer numbnd
Definition at line 18 of file REFREF.c.
integer numbst
Definition at line 18 of file REFREF.c.
integer stklst[300]
Definition at line 31 of file REFREF.c.
struct { ... } stklst_
integer sublst[136]
Definition at line 49 of file REFREF.c.
struct { ... } sublst_