My Project: REFSYS.c File Reference
REFSYS.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define ldef_1 ldef_
Functions
int refsys_ (doublereal *matrix)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
static integer c__53 = 53
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file REFSYS.c.
Referenced by refsys_().
#define dshar3_1 dshar3_
Definition at line 28 of file REFSYS.c.
Referenced by refsys_().
#define ldef_1 ldef_
Definition at line 35 of file REFSYS.c.
Referenced by refsys_().
Function Documentation
int refsys_ (doublereal * matrix)
Definition at line 64 of file REFSYS.c.
References apt067_(), c__53, ckdef_(), def_1, dshar3_1, error_(), i__, ldef_1, matrix, and zsurf_().
Referenced by xcall_().
 {
     static integer i__;
     extern /* Subroutine */ int apt067_(doublereal *, doublereal *);
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int error_(integer *, char *, ftnlen), zsurf_(
         doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /* ...     CHECK INPUT DEFINED */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
     /* Parameter adjustments */
     --matrix;
     /* Function Body */
     if (! ckdef_(&matrix[1])) {
     goto L10;
     }
     error_(&c__53, "REFSYS  ", (ftnlen)8);
     goto L9;
 /* ...     MOVE MATRIX TO A(1,2) AND THE INVERSE TO A(2,2) FOR TRANSF */
 L10:
     for (i__ = 1; i__ <= 12; ++i__) {
 /* L20: */
     def_1.a[i__ + 11] = matrix[i__];
     }
     apt067_(def_1.a, &def_1.a[12]);
 /* ...     IF ZSURF IS IN EFFECT TRANSFORM ZSURF PLANE */
     if (ldef_1.zflag) {
     goto L30;
     }
     for (i__ = 1; i__ <= 4; ++i__) {
 /* L25: */
     dshar3_1.sc[i__ - 1] = def_1.ref[(i__ << 1) - 2];
     }
     zsurf_(dshar3_1.sc);
 L30:
     ldef_1.refflg = TRUE_;
 L9:
     return 0;
 } /* refsys_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file REFSYS.c.
doublereal ahold[8]
Definition at line 18 of file REFSYS.c.
logical altmlt
Definition at line 31 of file REFSYS.c.
logical bnderr
Definition at line 31 of file REFSYS.c.
logical boundf
Definition at line 31 of file REFSYS.c.
doublereal c1[8]
Definition at line 18 of file REFSYS.c.
doublereal c__[7]
Definition at line 25 of file REFSYS.c.
integer c__53 = 53 static
Definition at line 39 of file REFSYS.c.
Referenced by refsys_().
logical canflg
Definition at line 31 of file REFSYS.c.
struct { ... } def_
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file REFSYS.c.
logical jcs
Definition at line 31 of file REFSYS.c.
logical jds
Definition at line 31 of file REFSYS.c.
doublereal l[4]
Definition at line 25 of file REFSYS.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file REFSYS.c.
doublereal p[16]
Definition at line 25 of file REFSYS.c.
logical pchlst
Definition at line 31 of file REFSYS.c.
logical prnton
Definition at line 31 of file REFSYS.c.
doublereal r__[10]
Definition at line 18 of file REFSYS.c.
doublereal ref[8]
Definition at line 18 of file REFSYS.c.
logical refflg
Definition at line 31 of file REFSYS.c.
logical refmot
Definition at line 31 of file REFSYS.c.
doublereal sc[16]
Definition at line 25 of file REFSYS.c.
logical subflg
Definition at line 31 of file REFSYS.c.
doublereal t[12]
Definition at line 25 of file REFSYS.c.
doublereal t1[12]
Definition at line 25 of file REFSYS.c.
logical tabprt
Definition at line 31 of file REFSYS.c.
logical unflag
Definition at line 31 of file REFSYS.c.
doublereal v[10]
Definition at line 25 of file REFSYS.c.
logical zflag
Definition at line 31 of file REFSYS.c.