My Project: REMINT.c File Reference
REMINT.c File Reference
#include "f2c.h"
Macros
#define inidat_1 inidat_
#define interf_1 interf_
#define ibugg_1 ibugg_
Functions
int remint_ (doublereal *te, doublereal *ta, doublereal *tul, doublereal *psurf, integer *ipsize, doublereal *pside, doublereal *pthick, doublereal *tolin, integer *lsusp, integer *nsusp)
Variables
struct {
doublereal cxhull [24000]
doublereal dulim [1000]
doublereal dvlim [1000]
doublereal curmax [1000]
doublereal curmin [1000]
integer ncxhul [1000]
integer ngp
integer icursf
} inidat_
struct {
doublereal dintr [1000]
doublereal uintr [1000]
doublereal vintr [1000]
doublereal ldintr [1000]
doublereal luintr [1000]
doublereal lvintr [1000]
doublereal tpintr [3000]
doublereal spintr [3000]
doublereal snintr [3000]
integer pintr [1000]
integer lpintr [1000]
integer iseg [1000]
integer npintr
integer lnpint
} interf_
struct {
integer ibug
integer ipcolc
integer ipcolm
} ibugg_
static integer c_n1 = -1
static integer c__0 = 0
static integer c__1 = 1
Macro Definition Documentation
#define ibugg_1 ibugg_
Definition at line 39 of file REMINT.c.
Referenced by remint_().
#define inidat_1 inidat_
Definition at line 23 of file REMINT.c.
Referenced by remint_().
#define interf_1 interf_
Definition at line 33 of file REMINT.c.
Referenced by remint_().
Function Documentation
int remint_ (doublereal * te, doublereal * ta, doublereal * tul, doublereal * psurf, integer * ipsize, doublereal * pside, doublereal * pthick, doublereal * tolin, integer * lsusp, integer * nsusp)
Definition at line 49 of file REMINT.c.
References bad_(), c__0, c__1, c_n1, i__, ibugg_1, iflag, inidat_1, interf_1, j, mixal_(), ta, and te.
Referenced by intchk_().
 {
     /* System generated locals */
     integer i__1, i__2;
     /* Local variables */
     static integer i__, j;
     extern /* Subroutine */ int bad_(integer *, integer *, char *, integer *,
         ftnlen);
     static integer ipen, npat;
     static doublereal upen, vpen;
     static integer iedge, iflag;
     extern /* Subroutine */ int mixal_(integer *, integer *, doublereal *,
         doublereal *, doublereal *, doublereal *, doublereal *,
         doublereal *, doublereal *, doublereal *, doublereal *,
         doublereal *, doublereal *, doublereal *, doublereal *,
         doublereal *, doublereal *, doublereal *, integer *, integer *,
         integer *, integer *);
     static doublereal pnorm[3];
     static integer nitera;
     static doublereal toolce[3], penmax, ppoint[3], tpoint[3], ustart, vstart;
 /*     PURPOSE : TO CHECK OUT SUSPECT REMOTE PATCHES AND IF ANY */
 /*               PENETRATION DETECTED STORE THE WORST PENETRATION */
 /*               FOR EACH PATCH IN THE INTERFERENCE TABLE */
 /*     ARGUMENTS: */
 /*     TE      -  TOOL END COORDINATES */
 /*     TA      -  TOOL AXIS VECTOR */
 /*     TUL     -  TOOL GEOMETRY */
 /*     PSURF   -  CANONICAL FORM OF PART SURFACE (SSURF) */
 /*     IPSIZE  -  SIZE OF CANONICAL FORM */
 /*     PSIDE   -  1 OR -1 TO AJUST SURFACE NORMAL (RU X RV) */
 /*     PTHICK  -  THICKNESS OFFSET FROM SURFACE */
 /*     TOLIN   -  TOLERANCE (PS INTOL) */
 /*     LSUSP   -  LIST OF SUSPECT PATCHES */
 /*     NSUSP   -  NUMBER OF SUSPECT PATCHES */
 /* .... INTERFERENCE CHECKING INITIAL DATA */
 /* .... SPHERICAL SURFACE ENCLOSURES (HULLS) */
 /* .... NUMBER OF HULLS */
 /* .... DU ITERATION LIMIT FOR PATCHES */
 /* .... DV ITERATION LIMIT FOR PATCHES */
 /* .... MAXIMUM AND MINIMUM CURVATURE OF PATCHES */
 /*     MXNP   -  MAXIMUM NUMBER OF PATCHES PER SURFACE */
 /*     NGP    -  NUMBER OF PATCHES IN CURRENT SURFACE */
 /*     ICURSF -  EXTERNAL LDA FILE RECORD NUMBER FOR CURRENT SURFACE */
 /*    INTERFERENCE TABLE */
 /*     LOCAL VARIABLES */
 /* .... DEBUG FLAGS */
 /* .... CALCULATE 'TOOL CENTER' FOR SIMPLE BE AND CRC CUTTERS */
     /* Parameter adjustments */
     --te;
     --ta;
     --tul;
     --psurf;
     --lsusp;
     /* Function Body */
     for (i__ = 1; i__ <= 3; ++i__) {
     toolce[i__ - 1] = te[i__] + (tul[4] + tul[1]) * ta[i__];
 /* L50: */
     }
     interf_1.npintr = 0;
 /* .... FOR EACH SUSPECT PATCH */
     i__1 = *nsusp;
     for (i__ = 1; i__ <= i__1; ++i__) {
     npat = lsusp[i__];
     if (interf_1.lnpint != 0) {
 /* .... THERE WAS AT LEAST ONE INTERFERENCE DETECTED AT PREVIOUS TOOL */
 /*     POSITION - CHECK IF ANY PENETRATION WITH THIS PATCH */
         i__2 = interf_1.lnpint;
         for (j = 1; j <= i__2; ++j) {
         if (npat == interf_1.lpintr[j - 1]) {
 /* .... TAKE U,V OF PREVIOUS INTERSECTION AS START VALUES */
             ustart = interf_1.luintr[j - 1];
             vstart = interf_1.lvintr[j - 1];
             goto L200;
         }
 /* L100: */
         }
     }
 /* .... OTHERWISE TAKE PARAMETRIC MID POINT AS START */
     ustart = .5f;
     vstart = .5f;
 L200:
 /* .... SEARCH THIS PATCH FOR INTERFERENCE */
     mixal_(&npat, ipsize, &psurf[1], pside, pthick, &tul[1], toolce, &ta[
         1], &ustart, &vstart, &inidat_1.dulim[npat - 1], &
         inidat_1.dvlim[npat - 1], &upen, &vpen, ppoint, tpoint, pnorm,
          &penmax, &ipen, &iflag, &iedge, &nitera);
 /* .... DEBUG PRINT */
     if (ibugg_1.ibug == 11) {
         bad_(&c_n1, &c__0, " ", &c__0, (ftnlen)1);
         bad_(&c__1, &c__0, "NPAT", &npat, (ftnlen)4);
         bad_(&c__1, &c__0, "ITER", &nitera, (ftnlen)4);
     }
     if (iflag == 0) {
         if (penmax > *tolin) {
 /* .... STORE IN INTERFERENCE TABLE */
         ++interf_1.npintr;
         interf_1.dintr[interf_1.npintr - 1] = penmax;
         interf_1.uintr[interf_1.npintr - 1] = upen;
         interf_1.vintr[interf_1.npintr - 1] = vpen;
         interf_1.pintr[interf_1.npintr - 1] = npat;
         for (j = 1; j <= 3; ++j) {
             interf_1.spintr[j + interf_1.npintr * 3 - 4] = ppoint[j -
                 1];
             interf_1.tpintr[j + interf_1.npintr * 3 - 4] = tpoint[j -
                 1];
             interf_1.snintr[j + interf_1.npintr * 3 - 4] = pnorm[j -
                 1];
 /* L300: */
         }
         interf_1.iseg[interf_1.npintr - 1] = ipen;
         }
     }
 /* L400: */
     }
     return 0;
 } /* remint_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 44 of file REMINT.c.
Referenced by remint_().
integer c__1 = 1 static
Definition at line 45 of file REMINT.c.
Referenced by remint_().
integer c_n1 = -1 static
Definition at line 43 of file REMINT.c.
Referenced by remint_().
doublereal curmax[1000]
Definition at line 18 of file REMINT.c.
doublereal curmin[1000]
Definition at line 18 of file REMINT.c.
doublereal cxhull[24000]
Definition at line 18 of file REMINT.c.
doublereal dintr[1000]
Definition at line 26 of file REMINT.c.
doublereal dulim[1000]
Definition at line 18 of file REMINT.c.
doublereal dvlim[1000]
Definition at line 18 of file REMINT.c.
integer ibug
Definition at line 36 of file REMINT.c.
struct { ... } ibugg_
integer icursf
Definition at line 20 of file REMINT.c.
struct { ... } inidat_
struct { ... } interf_
integer ipcolc
Definition at line 36 of file REMINT.c.
integer ipcolm
Definition at line 36 of file REMINT.c.
integer iseg[1000]
Definition at line 30 of file REMINT.c.
doublereal ldintr[1000]
Definition at line 26 of file REMINT.c.
integer lnpint
Definition at line 30 of file REMINT.c.
integer lpintr[1000]
Definition at line 30 of file REMINT.c.
doublereal luintr[1000]
Definition at line 26 of file REMINT.c.
doublereal lvintr[1000]
Definition at line 26 of file REMINT.c.
integer ncxhul[1000]
Definition at line 20 of file REMINT.c.
integer ngp
Definition at line 20 of file REMINT.c.
integer npintr
Definition at line 30 of file REMINT.c.
integer pintr[1000]
Definition at line 30 of file REMINT.c.
doublereal snintr[3000]
Definition at line 26 of file REMINT.c.
doublereal spintr[3000]
Definition at line 26 of file REMINT.c.
doublereal tpintr[3000]
Definition at line 26 of file REMINT.c.
doublereal uintr[1000]
Definition at line 26 of file REMINT.c.
doublereal vintr[1000]
Definition at line 26 of file REMINT.c.