My Project: REPLAC.c File Reference
REPLAC.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define stklst_1 stklst_
#define code_1 code_
#define tmp_1 tmp_
#define il_1 il_
#define macxx1_1 macxx1_
#define moduli_1 moduli_
#define errpos_1 errpos_
#define vbl ((integer *)&code_1 + 60)
#define way ((integer *)&macxx1_1 + 25)
#define top ((integer *)&stklst_1)
#define repl ((integer *)&il_1 + 16)
#define ident ((integer *)&code_1 + 68)
#define stack ((integer *)&stklst_1 + 3)
#define relat ((integer *)&code_1 + 52)
#define entry__ ((logical *)&macxx1_1 + 39)
#define finmac ((logical *)&macxx1_1 + 23)
#define congeo ((integer *)&code_1 + 76)
#define estack ((integer *)&errpos_1 + 102)
#define intmed ((integer *)&macxx1_1 + 21)
#define majwrd ((integer *)&macxx1_1 + 22)
#define argstk ((integer *)&stklst_1 + 201)
#define argtop ((integer *)&stklst_1 + 1)
#define should ((logical *)&macxx1_1 + 69)
#define modulo ((integer *)&moduli_1)
#define conpro ((integer *)&code_1 + 78)
#define ergstk ((integer *)&errpos_1 + 202)
Functions
int replac_ (void)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer stklst [300]
} stklst_
struct {
integer code [150]
} code_
struct {
integer txxxx [64]
} tmp_
struct {
integer il [21]
} il_
struct {
integer macxx1 [71]
} macxx1_
struct {
integer moduli [2]
} moduli_
struct {
integer errpos [302]
} errpos_
static integer c__1 = 1
static integer c__1012 = 1012
static integer c__8 = 8
Macro Definition Documentation
#define argstk ((integer *)&stklst_1 + 201)
Referenced by replac_().
#define argtop ((integer *)&stklst_1 + 1)
Referenced by replac_().
#define cnamtb_1 cnamtb_
Definition at line 28 of file REPLAC.c.
#define code_1 code_
Definition at line 40 of file REPLAC.c.
#define congeo ((integer *)&code_1 + 76)
Referenced by replac_().
#define conpro ((integer *)&code_1 + 78)
Referenced by replac_().
#define entry__ ((logical *)&macxx1_1 + 39)
Referenced by replac_().
#define ergstk ((integer *)&errpos_1 + 202)
Referenced by replac_().
#define errpos_1 errpos_
Definition at line 70 of file REPLAC.c.
#define estack ((integer *)&errpos_1 + 102)
#define finmac ((logical *)&macxx1_1 + 23)
Referenced by replac_().
#define ident ((integer *)&code_1 + 68)
Referenced by replac_().
#define il_1 il_
Definition at line 52 of file REPLAC.c.
#define intmed ((integer *)&macxx1_1 + 21)
Referenced by replac_().
#define macxx1_1 macxx1_
Definition at line 58 of file REPLAC.c.
#define majwrd ((integer *)&macxx1_1 + 22)
Referenced by replac_().
#define moduli_1 moduli_
Definition at line 64 of file REPLAC.c.
#define modulo ((integer *)&moduli_1)
Referenced by replac_().
#define nametb_1 nametb_
Definition at line 22 of file REPLAC.c.
Referenced by replac_().
#define relat ((integer *)&code_1 + 52)
Referenced by replac_().
#define repl ((integer *)&il_1 + 16)
Referenced by replac_().
#define should ((logical *)&macxx1_1 + 69)
Referenced by replac_().
#define stack ((integer *)&stklst_1 + 3)
Referenced by replac_().
#define stklst_1 stklst_
Definition at line 34 of file REPLAC.c.
#define tmp_1 tmp_
Definition at line 46 of file REPLAC.c.
Referenced by replac_().
#define top ((integer *)&stklst_1)
Referenced by replac_().
#define vbl ((integer *)&code_1 + 60)
Referenced by replac_().
#define way ((integer *)&macxx1_1 + 25)
Referenced by replac_().
Function Documentation
int replac_ (void)
Definition at line 99 of file REPLAC.c.
References alarm_(), argcvt_(), argstk, argtop, c__1, c__1012, c__8, congeo, conpro, entry__, ergstk, finmac, ident, iftmp_(), intmed, j, k, majwrd, match_(), mode_(), modulo, nametb_1, onearg_(), opcode_(), path_(), puttmp_(), relat, repl, resrvz_(), rlslin_(), setmod_(), should, stack, tmp_1, top, vbl, and way.
Referenced by loop_(), and recog_().
 {
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer j, k;
 #define vbl ((integer *)&code_1 + 60)
 #define way ((integer *)&macxx1_1 + 25)
 #define top ((integer *)&stklst_1)
     extern integer mode_(integer *);
     extern /* Subroutine */ int path_(void);
 #define repl ((integer *)&il_1 + 16)
     extern /* Subroutine */ int alarm_(integer *, integer *, integer *, char *
         , ftnlen), match_(void);
 #define ident ((integer *)&code_1 + 68)
 #define stack ((integer *)&stklst_1 + 3)
 #define relat ((integer *)&code_1 + 52)
     extern logical iftmp_(integer *);
     static integer modxx;
 #define entry__ ((logical *)&macxx1_1 + 39)
 #define finmac ((logical *)&macxx1_1 + 23)
     extern /* Subroutine */ int opcode_(integer *);
 #define congeo ((integer *)&code_1 + 76)
 #define estack ((integer *)&errpos_1 + 102)
     extern /* Subroutine */ int onearg_(integer *);
 #define intmed ((integer *)&macxx1_1 + 21)
 #define majwrd ((integer *)&macxx1_1 + 22)
     extern /* Subroutine */ int argcvt_(integer *);
 #define argstk ((integer *)&stklst_1 + 201)
 #define argtop ((integer *)&stklst_1 + 1)
 #define should ((logical *)&macxx1_1 + 69)
 #define modulo ((integer *)&moduli_1)
 #define conpro ((integer *)&code_1 + 78)
 #define ergstk ((integer *)&errpos_1 + 202)
     extern /* Subroutine */ int setmod_(integer *, integer *), rlslin_(void),
         puttmp_(integer *), resrvz_(integer *, integer *, integer *,
         integer *);
 /*              FUNCTION DECLARATION */
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /*        2.    STACK AND POINTER STORAGE */
 /* TOP:         POINTER TO LAST STACK ENTRY */
 /* ARGTOP:      POINTER TO LAST ARGSTK ENTRY */
 /* STACK:       WORKING STACK */
 /* ARGSTK:      ARGUMENT STACK */
 /*        3.    METALINGUISTIC VARIABLE CLASS CODES */
 /* RELAT:       (1)=CODE CLASS 27000,(2)=NAMTBL INDEX OF 'RELAT ' */
 /* VBL:         (1)=CODE CLASS 31000,(2)=NAMTBL INDEX OF 'VBL   ' */
 /* IDENT:       (1)=CODE CLASS 35000,(2)=NAMTBL INDEX OF 'IDENT ' */
 /* CONGEO:      (1)=CODE CLASS 39000,(2)=NAMTBL INDEX OF 'CONGEO' */
 /* CONPRO:      (1)=CODE CLASS 40000,(2)=NAMTBL INDEX OF 'CONPRO' */
 /*        6.    GHOST STACK FOR OBJECT TIME TEMPORARY ALLOCATION */
 /*              LENGTH AND CURRENT NUMBER OF ACTIVE TEMPORARY STORAGE */
 /*       16.    LITERALS FOR I. L. OPERATION CODES */
 /* REPL:        CONTAINS COMMAND CODE (17) FOR REPL COMMAND */
 /*       22.    MACRO PROCESSING VARIABLES */
 /* INTMED:      0=NO -,-1=INTERMEDIATE-,+1=FINAL MACRO PROCESSING */
 /* MAJWRD:      CONTAINS ACTUAL MAJOR WORD */
 /* FINMAC:      TRUE IF SECOND FINAL PASS OF MACRO PROCESSING */
 /* WAY:         INDICATES TYPE OF MACRO PROCESSING */
 /* ENTRY:       FALSE ON FIRST ENTRY TO MATCH FOR A MACRO EXPRESSION */
 /* SHOULD:      MACRO INDICATOR. NORMALLY FALSE */
 /*       29.    CLASS CODE MODULI */
 /* MODULO:      NAMTBL CLASS AND CODE FACTOR 1000 TO DEVIDE OUT CLASS */
 /*       44.    ERROR POSITION TABLE */
 /* ESTACK:      INPUT STATEMENT ERROR POSITION WHEN DETECTED IN STACK */
 /* ERGSTK:      INPUT STATEMENT ERROR POSITION WHEN DETECTED IN ARGSTK */
 /* ** */
     k = stack[(*top - 1 << 1) - 2];
     *majwrd = stack[(*top - 3 << 1) - 2];
     ergstk[99] = *top - 3;
     if (*intmed != 1) {
     goto L30;
     }
     *way = 4;
     if (*finmac) {
     goto L20;
     }
     *argtop = 1;
     argstk[0] = k;
 L10:
     match_();
     k = argstk[0];
     if (! (*entry__)) {
     goto L210;
     }
     goto L30;
 L20:
     path_();
     if (! (*should)) {
     goto L210;
     }
 L30:
     modxx = mode_(&k);
 /*          CHANGE CLASS IF IDENTIFIER */
     j = *modulo * (nametb_1.namtbl[*majwrd - 1] / *modulo);
     if (j != ident[0] && j != conpro[0] && j != congeo[0] && j != relat[0]) {
     goto L100;
     }
 /* L150: */
     resrvz_(majwrd, &modxx, &tmp_1.txxxx[(modxx << 1) - 2], &c__1);
     i__1 = *top - 3;
     setmod_(&i__1, vbl);
     nametb_1.namtbl[*majwrd - 1] += modxx;
     goto L200;
 L100:
     if (mode_(majwrd) == modxx) {
     goto L200;
     }
     i__1 = *top - 1;
     alarm_(&c__1012, &i__1, &c__8, "REPLAC  ", (ftnlen)8);
 L200:
     opcode_(repl);
     onearg_(&tmp_1.txxxx[(modxx << 1) - 2]);
     argcvt_(majwrd);
     argcvt_(&k);
     rlslin_();
     if (*entry__) {
     goto L10;
     }
 L210:
     *argtop = 0;
     if (iftmp_(&k)) {
     i__1 = mode_(&k);
     puttmp_(&i__1);
     }
 /* L300: */
     return 0;
 } /* replac_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 74 of file REPLAC.c.
Referenced by replac_().
integer c__1012 = 1012 static
Definition at line 75 of file REPLAC.c.
Referenced by replac_().
integer c__8 = 8 static
Definition at line 76 of file REPLAC.c.
Referenced by replac_().
integer charnd
Definition at line 18 of file REPLAC.c.
integer charst
Definition at line 18 of file REPLAC.c.
char cnamtb[18000]
Definition at line 25 of file REPLAC.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file REPLAC.c.
integer code[150]
Definition at line 37 of file REPLAC.c.
struct { ... } code_
integer errpos[302]
Definition at line 67 of file REPLAC.c.
struct { ... } errpos_
integer ifixnd
Definition at line 18 of file REPLAC.c.
integer ifixst
Definition at line 18 of file REPLAC.c.
integer il[21]
Definition at line 49 of file REPLAC.c.
struct { ... } il_
integer inamnd
Definition at line 18 of file REPLAC.c.
integer inamst
Definition at line 18 of file REPLAC.c.
integer macxx1[71]
Definition at line 55 of file REPLAC.c.
struct { ... } macxx1_
integer moduli[2]
Definition at line 61 of file REPLAC.c.
struct { ... } moduli_
integer namest
Definition at line 18 of file REPLAC.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file REPLAC.c.
integer namtbl[3000]
Definition at line 18 of file REPLAC.c.
integer numbnd
Definition at line 18 of file REPLAC.c.
integer numbst
Definition at line 18 of file REPLAC.c.
integer stklst[300]
Definition at line 31 of file REPLAC.c.
struct { ... } stklst_
struct { ... } tmp_
integer txxxx[64]
Definition at line 43 of file REPLAC.c.