My Project: RESRVZ.c File Reference
RESRVZ.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define code_1 code_
#define il_1 il_
#define modx_1 modx_
#define blkcfs_1 blkcfs_
#define vbl ((integer *)&code_1 + 60)
#define real__ ((integer *)&modx_1 + 20)
#define bool ((integer *)&modx_1 + 22)
#define resrv ((integer *)&il_1 + 11)
Functions
int resrvz_ (integer *index, integer *mode, integer *isize, integer *nnnber)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer code [150]
} code_
struct {
integer il [21]
} il_
struct {
integer modx [32]
} modx_
struct {
integer first [6]
} blkcfs_
static integer c__1 = 1
static integer c__2 = 2
Macro Definition Documentation
#define blkcfs_1 blkcfs_
Definition at line 52 of file RESRVZ.c.
Referenced by resrvz_().
#define bool ((integer *)&modx_1 + 22)
#define cnamtb_1 cnamtb_
Definition at line 28 of file RESRVZ.c.
#define code_1 code_
Definition at line 34 of file RESRVZ.c.
#define il_1 il_
Definition at line 40 of file RESRVZ.c.
#define modx_1 modx_
Definition at line 46 of file RESRVZ.c.
#define nametb_1 nametb_
Definition at line 22 of file RESRVZ.c.
Referenced by resrvz_().
#define real__ ((integer *)&modx_1 + 20)
Referenced by resrvz_().
#define resrv ((integer *)&il_1 + 11)
Referenced by resrvz_().
#define vbl ((integer *)&code_1 + 60)
Referenced by resrvz_().
Function Documentation
int resrvz_ (integer * index, integer * mode, integer * isize, integer * nnnber)
Definition at line 83 of file RESRVZ.c.
References blkcfs_1, c__1, c__2, i__, mode, name_(), nametb_1, opcode_(), real__, resrv, rlslin_(), twoarg_(), and vbl.
Referenced by gettmp_(), gopat_(), inpat_(), larges_(), lcanon_(), macrec_(), pro020_(), pro026_(), pro027_(), pro028_(), recog_(), recogn_(), replac_(), resred_(), and ssdef_().
 {
     /* Initialized data */
     static char dlrblk[6*3] = "      " "$$BLK2" "$$BLK3";
     /* Local variables */
     static integer i__, md;
 #define vbl ((integer *)&code_1 + 60)
     extern integer name_(char *, ftnlen);
 #define real__ ((integer *)&modx_1 + 20)
 #define bool ((integer *)&modx_1 + 22)
     static integer block;
 #define resrv ((integer *)&il_1 + 11)
     extern /* Subroutine */ int opcode_(integer *), twoarg_(integer *,
         integer *), rlslin_(void);
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /*        3.    METALINGUISTIC VARIABLE CLASS CODES */
 /* VBL:         (1)=CODE CLASS 31000,(2)=NAMTBL INDEX OF 'VBL   ' */
 /*       16.    LITERALS FOR I. L. OPERATION CODES */
 /* RESRV:       CONTAINS COMMAND CODE (12) FOR RESRV COMMAND */
 /*       17.    MODE CODES */
 /* REAL:        MODE CODE (21) FOR A SCALAR */
 /* BOOL:        MODE CODE (23) FOR BOOLEAN TYPE */
 /*       30.    NAMTBL POINTERS TO FIRST CANONICAL FORMS IN EACH BLOCK */
 /* * */
 /* ARGUMENT     INDEX     NAME TABLE (NAMTBL) INDEX OF */
 /*                        VARIABLE FOR WHICH OBJECT TIME */
 /*                        CANONICAL FORM SPACE IS BEING ALLOCATED. */
 /*              MODE      MODE OF VARIABLE. */
 /*              ISIZE     NUMBER OF ELEMENTS IN CANONICAL FORM */
 /*                        EXCLUDING SUBSCRIPT AND BCD NAME. */
 /*              NNNBER    UPPER SUBSCRIPT LIMIT (1 IF NON- */
 /*                        SUBSCRIPTED VARIABLE). */
 /* ** */
 /* ... DETERMINE WHICH BLOCK THE VARIABLE BELONGS IN */
     block = 4;
     md = *mode;
     if (md == *bool) {
     md = *real__;
     }
     if (md == *real__ && *nnnber == 1) {
     block = 1;
     }
     if (md == *real__ && *nnnber > 1) {
     block = 2;
     }
     if (md < *real__ && md > 0 || md >= 24) {
     block = 3;
     }
     if (block != 2 || blkcfs_1.first[3] != 0) {
     goto L5;
     }
 /* ... PUT FIRST ITEM IN CANONICAL FORM BLOCK 2. */
     i__ = name_(dlrblk + 6, (ftnlen)6);
     nametb_1.namtbl[i__ - 1] = vbl[0] + *mode;
     opcode_(resrv);
     twoarg_(&i__, mode);
     twoarg_(&c__1, &c__2);
     rlslin_();
     blkcfs_1.first[2] = i__;
     blkcfs_1.first[3] = 1;
 L5:
     opcode_(resrv);
     twoarg_(index, mode);
     twoarg_(isize, nnnber);
     rlslin_();
     if (block == 4) {
     goto L20;
     }
 /* ... IF FIRST CANONICAL FORM FOR THIS BLOCK, SAVE NAMTBL INDEX. */
     if (blkcfs_1.first[(block << 1) - 1] != 0) {
     goto L10;
     }
     blkcfs_1.first[(block << 1) - 2] = *index;
 /* ... INCREMENT COUNT OF NUMBER OF FORMS IN THIS BLOCK */
 L10:
     blkcfs_1.first[(block << 1) - 1] += *nnnber;
 L20:
     return 0;
 } /* resrvz_ */
Variable Documentation
struct { ... } blkcfs_
integer c__1 = 1 static
Definition at line 56 of file RESRVZ.c.
Referenced by resrvz_().
integer c__2 = 2 static
Definition at line 57 of file RESRVZ.c.
Referenced by resrvz_().
integer charnd
Definition at line 18 of file RESRVZ.c.
integer charst
Definition at line 18 of file RESRVZ.c.
char cnamtb[18000]
Definition at line 25 of file RESRVZ.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file RESRVZ.c.
integer code[150]
Definition at line 31 of file RESRVZ.c.
struct { ... } code_
integer first[6]
Definition at line 49 of file RESRVZ.c.
integer ifixnd
Definition at line 18 of file RESRVZ.c.
integer ifixst
Definition at line 18 of file RESRVZ.c.
integer il[21]
Definition at line 37 of file RESRVZ.c.
struct { ... } il_
integer inamnd
Definition at line 18 of file RESRVZ.c.
integer inamst
Definition at line 18 of file RESRVZ.c.
integer modx[32]
Definition at line 43 of file RESRVZ.c.
struct { ... } modx_
integer namest
Definition at line 18 of file RESRVZ.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file RESRVZ.c.
integer namtbl[3000]
Definition at line 18 of file RESRVZ.c.
integer numbnd
Definition at line 18 of file RESRVZ.c.
integer numbst
Definition at line 18 of file RESRVZ.c.