My Project: RETMCX.c File Reference
RETMCX.c File Reference
#include "f2c.h"
Macros
#define il_1 il_
#define retmc ((integer *)&il_1 + 9)
Functions
int retmcx_ (integer *indx)
Variables
struct {
integer il [21]
} il_
Macro Definition Documentation
#define il_1 il_
Definition at line 21 of file RETMCX.c.
#define retmc ((integer *)&il_1 + 9)
Referenced by retmcx_().
Function Documentation
int retmcx_ (integer * indx)
Definition at line 36 of file RETMCX.c.
References onearg_(), opcode_(), retmc, and rlslin_().
Referenced by comstr_(), and match_().
 {
     /* Local variables */
 #define retmc ((integer *)&il_1 + 9)
     extern /* Subroutine */ int opcode_(integer *), onearg_(integer *),
         rlslin_(void);
 /*       16.    LITERALS FOR I. L. OPERATION CODES */
 /* RETMC:       CONTAINS COMMAND CODE (10) FOR RETMC COMMAND */
 /* * */
 /* ARGUMENTS    INDX     INDEX REGISTER NUMBER */
 /* ** */
     opcode_(retmc);
     onearg_(indx);
     rlslin_();
     return 0;
 } /* retmcx_ */
Variable Documentation
integer il[21]
Definition at line 18 of file RETMCX.c.
struct { ... } il_