My Project: RLSBUF.c File Reference
RLSBUF.c File Reference
#include "f2c.h"
Macros
#define symfil_1 symfil_
#define outbuf_1 outbuf_
Functions
int rlsbuf_ (void)
Variables
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
struct {
integer pagpak
integer isc
integer iscarr
integer icform
integer ifloat
integer icom
integer macwds
integer ppwrds
logical macflg
logical labflg
logical rsvflg
integer lpage
integer buffer [256]
integer labbuf [256]
integer ibuf
integer ilbuf
integer pppage
integer mcpage
} outbuf_
static integer c__256 = 256
Macro Definition Documentation
#define outbuf_1 outbuf_
Definition at line 32 of file RLSBUF.c.
Referenced by rlsbuf_().
#define symfil_1 symfil_
Definition at line 24 of file RLSBUF.c.
Referenced by rlsbuf_().
Function Documentation
int rlsbuf_ (void)
Definition at line 51 of file RLSBUF.c.
References awrite_(), c__256, n, outbuf_1, symfil_1, and zero.
Referenced by cilout_(), icmprs_(), and ieplog_().
 {
     /* Initialized data */
     static integer zero = 0;
     static integer n, iret;
     extern /* Subroutine */ int awrite_(integer *, integer *, integer *,
         integer *, integer *);
 /*       33.    SYMBOLIC FILE DEFINITIONS */
 /* ELFIL1:          INTERMEDIATE LANGUAGE FILE */
 /* ELFIL2:          PART PROGRAMMING TEXT GENERATED BY INTERPRETER */
 /* ELFIL3:          MACRO TEXT GENERATED FOR INTERPRETER */
 /*       34.    COMMON BLOCK FOR INTERPRETIVE C.I.L. OUTPUT */
 /* ...                SYSTEM I/O FILES */
 /* MACFLG:      TRUE WHEN MACRO PROCESSING IN EFFECT (INTERPRETER) */
 /* LABFLG:      INDICATES I.L. COMMAND IS LABEL (INTERPRETER) */
 /* RSVFLG:      TRUE IF I.L. COMMAND IS A RESRV (INTERPRETER) */
 /* LPAGE:       NUMBER OF PAGES OF ENTRY,HOLDAT,LABEL AND RESRV COMMANDS */
 /* IBUF:        NUMBER OF RECORDS IN BUFFER ARRAY */
 /* ILBUF:       NUMBER OF ITEMS IN THE LABBUF ARRAY (INTERPRETER) */
 /* PPPAGE:      PAGE NUMBER OF PART PROGRAMMING TEXT (INTERPRETER) */
 /* MCPAGE:      NUMBER OF PAGES OF MACRO I.L. (INTERPRETER) */
 /* BUFFER:      TEMPORARY STORAGE FOR INTERPRETER OUTPUT (PAGES) */
 /* LABBUF:      TEMPORARY STORAGE FOR LABEL,HOLDAT ENTRY AND RESRV I.L. */
 /* * */
 /* ** */
 /* ...     TEST WHETHER THIS IS LABEL AND RESRV CODE */
     if (outbuf_1.labflg || outbuf_1.rsvflg) {
     goto L100;
     }
     if (outbuf_1.ibuf == 0) {
     return 0;
     }
 /* ...     NO. IS IT MACRO CODE */
     if (outbuf_1.macflg) {
     goto L300;
     }
 /* ...     NO. THIS IS PART-PROGRAM CODE AND IS WRITTEN TO FILE 2 */
 /* ...     FORM MARKER WORD, AND UPDATE PAGE COUNT */
 /* L200: */
     ++outbuf_1.pppage;
     n = 0;
     outbuf_1.buffer[0] = outbuf_1.pppage;
     outbuf_1.buffer[1] = outbuf_1.ibuf;
     awrite_(&symfil_1.elfil2, &n, outbuf_1.buffer, &c__256, &iret);
 /* ...     RESET BUFFER POINTER AND RETURN */
 L210:
     outbuf_1.ibuf = 0;
     return 0;
 /* ...     MACRO CODE IS WRITTEN TO FILE 3 */
 /* ...     FORM MARKER WORD, AND UPDATE PAGE COUNT */
 L300:
     ++outbuf_1.mcpage;
     n = 0;
     outbuf_1.buffer[0] = -outbuf_1.mcpage;
     outbuf_1.buffer[1] = outbuf_1.ibuf;
     awrite_(&symfil_1.elfil3, &n, outbuf_1.buffer, &c__256, &iret);
     goto L210;
 /* ...     LABEL AND RESRV CODE IS WRITTEN TO FILE 1 */
 /* ...     ITS PAGES HAVE ZERO PAGE NUMBERS */
 L100:
     ++outbuf_1.lpage;
     n = 0;
     outbuf_1.labbuf[0] = zero;
     outbuf_1.labbuf[1] = outbuf_1.ilbuf;
     awrite_(&symfil_1.elfil1, &n, outbuf_1.labbuf, &c__256, &iret);
 /* ...     RESET BUFFER POINTER AND RETURN */
     outbuf_1.ilbuf = 0;
     return 0;
 } /* rlsbuf_ */
Variable Documentation
integer axfile
Definition at line 18 of file RLSBUF.c.
integer buffer[256]
Definition at line 29 of file RLSBUF.c.
integer c__256 = 256 static
Definition at line 36 of file RLSBUF.c.
Referenced by rlsbuf_().
integer clfil3
Definition at line 18 of file RLSBUF.c.
integer clfile
Definition at line 18 of file RLSBUF.c.
integer clfilp
Definition at line 18 of file RLSBUF.c.
integer cpfile
Definition at line 18 of file RLSBUF.c.
integer elfil1
Definition at line 18 of file RLSBUF.c.
integer elfil2
Definition at line 18 of file RLSBUF.c.
integer elfil3
Definition at line 18 of file RLSBUF.c.
integer elfil4
Definition at line 18 of file RLSBUF.c.
integer elfile
Definition at line 18 of file RLSBUF.c.
integer exfile
Definition at line 18 of file RLSBUF.c.
integer ibuf
Definition at line 29 of file RLSBUF.c.
integer icform
Definition at line 27 of file RLSBUF.c.
integer icom
Definition at line 27 of file RLSBUF.c.
integer ifloat
Definition at line 27 of file RLSBUF.c.
integer ilbuf
Definition at line 29 of file RLSBUF.c.
integer infile__
Definition at line 18 of file RLSBUF.c.
integer isc
Definition at line 27 of file RLSBUF.c.
integer iscarr
Definition at line 27 of file RLSBUF.c.
integer ispare[26]
Definition at line 18 of file RLSBUF.c.
integer labbuf[256]
Definition at line 29 of file RLSBUF.c.
logical labflg
Definition at line 28 of file RLSBUF.c.
integer ldafil
Definition at line 18 of file RLSBUF.c.
integer libfil
Definition at line 18 of file RLSBUF.c.
integer lpage
Definition at line 29 of file RLSBUF.c.
logical macflg
Definition at line 28 of file RLSBUF.c.
integer mactxt
Definition at line 18 of file RLSBUF.c.
integer macwds
Definition at line 27 of file RLSBUF.c.
integer mcpage
Definition at line 29 of file RLSBUF.c.
integer nfil12
Definition at line 18 of file RLSBUF.c.
integer nfil13
Definition at line 18 of file RLSBUF.c.
struct { ... } outbuf_
integer pagpak
Definition at line 27 of file RLSBUF.c.
integer pnchfl
Definition at line 18 of file RLSBUF.c.
integer pofile
Definition at line 18 of file RLSBUF.c.
integer pppage
Definition at line 29 of file RLSBUF.c.
integer ppwrds
Definition at line 27 of file RLSBUF.c.
integer pxfile
Definition at line 18 of file RLSBUF.c.
logical rsvflg
Definition at line 28 of file RLSBUF.c.
struct { ... } symfil_
integer tifile
Definition at line 18 of file RLSBUF.c.
integer vlfile
Definition at line 18 of file RLSBUF.c.
integer xcan
Definition at line 18 of file RLSBUF.c.
integer xnum
Definition at line 18 of file RLSBUF.c.