My Project: RLSLIN.c File Reference
RLSLIN.c File Reference
#include "f2c.h"
Macros
#define seqcom_1 seqcom_
#define cseqcm_1 cseqcm_
#define prt_1 prt_
#define il_1 il_
#define iltext_1 iltext_
#define macxx1_1 macxx1_
#define symfil_1 symfil_
#define ilhlt ((logical *)&macxx1_1 + 13)
#define ilprt ((logical *)&prt_1 + 1)
#define resrv ((integer *)&il_1 + 11)
#define mchdng ((logical *)&prt_1 + 6)
#define comfin ((logical *)&iltext_1)
#define intmed ((integer *)&macxx1_1 + 21)
#define optext ((integer *)&iltext_1 + 3)
Functions
int rlslin_ (void)
Variables
struct {
integer seqno
} seqcom_
struct {
char seqnum [6]
} cseqcm_
struct {
integer prt [7]
} prt_
struct {
integer il [21]
} il_
struct {
integer iltext [94]
} iltext_
struct {
integer macxx1 [71]
} macxx1_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
static integer c__36 = 36
static integer c__44 = 44
Macro Definition Documentation
#define comfin ((logical *)&iltext_1)
Referenced by rlslin_().
#define cseqcm_1 cseqcm_
Definition at line 27 of file RLSLIN.c.
Referenced by rlslin_().
#define il_1 il_
Definition at line 39 of file RLSLIN.c.
#define ilhlt ((logical *)&macxx1_1 + 13)
Referenced by rlslin_().
#define ilprt ((logical *)&prt_1 + 1)
Referenced by rlslin_().
#define iltext_1 iltext_
Definition at line 45 of file RLSLIN.c.
#define intmed ((integer *)&macxx1_1 + 21)
Referenced by rlslin_().
#define macxx1_1 macxx1_
Definition at line 51 of file RLSLIN.c.
#define mchdng ((logical *)&prt_1 + 6)
Referenced by rlslin_().
#define optext ((integer *)&iltext_1 + 3)
Referenced by rlslin_().
#define prt_1 prt_
Definition at line 33 of file RLSLIN.c.
#define resrv ((integer *)&il_1 + 11)
Referenced by rlslin_().
#define seqcom_1 seqcom_
Definition at line 21 of file RLSLIN.c.
Referenced by rlslin_().
#define symfil_1 symfil_
Definition at line 60 of file RLSLIN.c.
Referenced by rlslin_().
Function Documentation
int rlslin_ (void)
Definition at line 108 of file RLSLIN.c.
References binbcd_(), c__36, c__44, comfin, comprs_(), cseqcm_1, foutxx_(), ilhlt, ilprt, intmed, line, mchdng, n, optext, prtil_(), resrv, seqcom_1, and symfil_1.
Referenced by asnadz_(), asnjpz_(), boolif_(), calmcx_(), comstr_(), goloft_(), gopat_(), inpat_(), isscod_(), jumpzz_(), labelz_(), larges_(), lcanon_(), loop_(), macrec_(), mnproc_(), motion_(), pro020_(), pro021_(), pro026_(), pro027_(), pro028_(), recog_(), recogn_(), refgen_(), refref_(), replac_(), resrvz_(), retmcx_(), ssdef_(), subcod_(), and tssmil_().
 {
     /* Initialized data */
     static char m1[36] = "0 ** FINAL MACRO I.L. PROCESSING ** ";
     static char m2[44] = "0GENERATED I.L. FOR MACRO AT SEQNCE         ";
     static char line[124] = "    ";
     static logical headng = TRUE_;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer n;
 #define ilhlt ((logical *)&macxx1_1 + 13)
 #define ilprt ((logical *)&prt_1 + 1)
     extern /* Subroutine */ int prtil_(char *, ftnlen);
 #define resrv ((integer *)&il_1 + 11)
     extern /* Subroutine */ int binbcd_(integer *, char *, integer *, ftnlen);
 #define mchdng ((logical *)&prt_1 + 6)
 #define comfin ((logical *)&iltext_1)
 #define intmed ((integer *)&macxx1_1 + 21)
     extern /* Subroutine */ int comprs_(void);
 #define optext ((integer *)&iltext_1 + 3)
     extern /* Subroutine */ int foutxx_(integer *, char *, integer *, ftnlen);
 /*       11.    SEQUENCE NUMBER STORAGE */
 /* SEQNO:       INTERNALLY GENERATED STATEMENT NUMBER */
 /* SEQNUM:      ALPHANUMERIC REPRESENTATION OF CURRRENT STATEMENT NUMBER */
 /*       14.    I. L. LIST OPTION FLAGS */
 /* ILPRT:       TRUE INDICATES I.L. PRINTING (PPOPTN/INTLNG,ON) */
 /* MCHDNG:      TRUE IF START OF NEW MACRO PROCESSING */
 /*       16.    LITERALS FOR I. L. OPERATION CODES */
 /* RESRV:       CONTAINS COMMAND CODE (12) FOR RESRV COMMAND */
 /*       19.    INTERMEDIATE LANGUAGE TEXT */
 /* COMFIN:      TRUE IF I.L. OPERATION CODE GIVEN */
 /* OPTEXT:      CONTAINS COMMAND CODE FOR CURRENT I.L. COMMAND */
 /*       22.    MACRO PROCESSING VARIABLES */
 /* ILHLT:       TRUE IF I.L. SHOULD NOT BE PLACED IN ILFILE */
 /* INTMED:      0=NO -,-1=INTERMEDIATE-,+1=FINAL MACRO PROCESSING */
 /*       33.    SYMBOLIC FILE DEFINITIONS */
 /* VLFILE:      VERIFICATION LISTING FILE */
 /* * */
 /* ...                SYSTEM I/O FILES */
 /* ** */
     *comfin = FALSE_;
     if (*ilhlt) {
     goto L6;
     }
 L1:
     if (! (*ilprt)) {
     goto L3;
     }
 /* ...CHECK FOR FINAL MACRO PROCESSING */
     if (*intmed <= 0) {
     goto L2;
     } else {
     goto L4;
     }
 L2:
     s_copy(line + 120, cseqcm_1.seqnum, (ftnlen)4, (ftnlen)4);
     prtil_(line, (ftnlen)124);
 L3:
     comprs_();
     goto L7;
 /* ...CHECK IF HEADING SHOULD BE PRINTED ON VLFILE */
 L4:
     if (! headng) {
     goto L5;
     }
     foutxx_(&symfil_1.vlfile, m1, &c__36, (ftnlen)36);
     headng = FALSE_;
 /* ...CHECK FOR START OF NEW MACRO I.L. */
 L5:
     if (! (*mchdng)) {
     goto L2;
     }
     binbcd_(&seqcom_1.seqno, cseqcm_1.seqnum, &n, (ftnlen)6);
     s_copy(m2 + 36, cseqcm_1.seqnum, (ftnlen)8, (ftnlen)6);
     foutxx_(&symfil_1.vlfile, m2, &c__44, (ftnlen)44);
     *mchdng = FALSE_;
     goto L2;
 L6:
     if (*optext == *resrv) {
     goto L1;
     }
 L7:
     return 0;
 } /* rlslin_ */
Variable Documentation
integer axfile
Definition at line 54 of file RLSLIN.c.
integer c__36 = 36 static
Definition at line 64 of file RLSLIN.c.
Referenced by rlslin_().
integer c__44 = 44 static
Definition at line 65 of file RLSLIN.c.
Referenced by rlslin_().
integer clfil3
Definition at line 54 of file RLSLIN.c.
integer clfile
Definition at line 54 of file RLSLIN.c.
integer clfilp
Definition at line 54 of file RLSLIN.c.
integer cpfile
Definition at line 54 of file RLSLIN.c.
struct { ... } cseqcm_
integer elfil1
Definition at line 54 of file RLSLIN.c.
integer elfil2
Definition at line 54 of file RLSLIN.c.
integer elfil3
Definition at line 54 of file RLSLIN.c.
integer elfil4
Definition at line 54 of file RLSLIN.c.
integer elfile
Definition at line 54 of file RLSLIN.c.
integer exfile
Definition at line 54 of file RLSLIN.c.
integer il[21]
Definition at line 36 of file RLSLIN.c.
struct { ... } il_
integer iltext[94]
Definition at line 42 of file RLSLIN.c.
struct { ... } iltext_
integer infile__
Definition at line 54 of file RLSLIN.c.
integer ispare[26]
Definition at line 54 of file RLSLIN.c.
integer ldafil
Definition at line 54 of file RLSLIN.c.
integer libfil
Definition at line 54 of file RLSLIN.c.
integer mactxt
Definition at line 54 of file RLSLIN.c.
integer macxx1[71]
Definition at line 48 of file RLSLIN.c.
struct { ... } macxx1_
integer nfil12
Definition at line 54 of file RLSLIN.c.
integer nfil13
Definition at line 54 of file RLSLIN.c.
integer pnchfl
Definition at line 54 of file RLSLIN.c.
integer pofile
Definition at line 54 of file RLSLIN.c.
integer prt[7]
Definition at line 30 of file RLSLIN.c.
struct { ... } prt_
integer pxfile
Definition at line 54 of file RLSLIN.c.
struct { ... } seqcom_
integer seqno
Definition at line 18 of file RLSLIN.c.
char seqnum[6]
Definition at line 24 of file RLSLIN.c.
struct { ... } symfil_
integer tifile
Definition at line 54 of file RLSLIN.c.
integer vlfile
Definition at line 54 of file RLSLIN.c.
integer xcan
Definition at line 54 of file RLSLIN.c.
integer xnum
Definition at line 54 of file RLSLIN.c.