My Project: SCDUMP.c File Reference
SCDUMP.c File Reference
#include "f2c.h"
Functions
int scdump_ (integer *in, doublereal *scan)
Variables
static integer c_n1 = -1
static integer c__0 = 0
static integer c__1 = 1
static integer c_n4 = -4
Function Documentation
int scdump_ (integer * in, doublereal * scan)
Definition at line 24 of file SCDUMP.c.
References bad_(), c__0, c__1, c_n1, c_n4, l, and scan.
Referenced by crsfit_(), curflo_(), gencrv_(), and mesh_().
 {
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer l, ik;
     extern /* Subroutine */ int bad_();
     static integer ntot;
     /* Parameter adjustments */
     --scan;
     /* Function Body */
     bad_(&c_n1, &c__0, " ", &c__0, (ftnlen)1);
     bad_(&c_n1, &c__0, "CHK=", in, (ftnlen)4);
     ntot = (integer) scan[12];
     if (ntot == 0) {
     ntot = (integer) ((scan[2] + scan[4]) * 24.f);
     }
     ik = -3;
     i__1 = ntot;
     for (l = 1; l <= i__1; l += 4) {
     if (l % 24 == 1) {
         bad_(&c_n1, &c__0, " ", &c__0, (ftnlen)1);
     }
     ik += 4;
     bad_(&c__1, &c__0, "KCT ", &ik, (ftnlen)4);
     bad_(&c_n4, &c__1, "SCAN", &scan[l], (ftnlen)4);
 /* L10: */
     }
     return 0;
 } /* scdump_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 18 of file SCDUMP.c.
Referenced by scdump_().
integer c__1 = 1 static
Definition at line 19 of file SCDUMP.c.
Referenced by scdump_().
integer c_n1 = -1 static
Definition at line 17 of file SCDUMP.c.
Referenced by scdump_().
integer c_n4 = -4 static
Definition at line 20 of file SCDUMP.c.
Referenced by scdump_().