My Project: SCHTB.c File Reference
SCHTB.c File Reference
#include "f2c.h"
Macros
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define ldef_1 ldef_
#define knumbr_1 knumbr_
Functions
int schtb_ (doublereal *tab)
Variables
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__11 = 11
Macro Definition Documentation
#define dshar3_1 dshar3_
Definition at line 21 of file SCHTB.c.
Referenced by schtb_().
#define knumbr_1 knumbr_
Definition at line 44 of file SCHTB.c.
#define ldef_1 ldef_
Definition at line 36 of file SCHTB.c.
Referenced by schtb_().
#define znumbr_1 znumbr_
Definition at line 29 of file SCHTB.c.
Referenced by schtb_().
Function Documentation
int schtb_ (doublereal * tab)
Definition at line 70 of file SCHTB.c.
References c__11, dshar3_1, error_(), f, i__, j, ldef_1, n, tab, and znumbr_1.
Referenced by apt011_(), apt034_(), and apt070_().
 {
     /* System generated locals */
     integer i__1;
     doublereal d__1;
     /* Local variables */
     static integer i__, j, n;
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --tab;
     /* Function Body */
     n = (integer) ((tab[12] - 2.f) * 7.f + 14.1f);
     i__1 = n;
     for (i__ = 14; i__ <= i__1; i__ += 7) {
     j = i__;
     if ((d__1 = tab[i__] - dshar3_1.p[0], abs(d__1)) > znumbr_1.z1em2) {
         goto L10;
     }
     if ((d__1 = tab[i__ + 1] - dshar3_1.p[1], abs(d__1)) <=
         znumbr_1.z1em2) {
         goto L20;
     }
 L10:
     ;
     }
     error_(&c__11, "SCHTB   ", (ftnlen)8);
     ldef_1.unflag = TRUE_;
     goto L9;
 L20:
     tab[13] = (doublereal) j;
     ldef_1.unflag = FALSE_;
 L9:
     return 0;
 } /* schtb_ */
Variable Documentation
logical altmlt
Definition at line 32 of file SCHTB.c.
logical bnderr
Definition at line 32 of file SCHTB.c.
logical boundf
Definition at line 32 of file SCHTB.c.
doublereal c__[7]
Definition at line 18 of file SCHTB.c.
integer c__11 = 11 static
Definition at line 48 of file SCHTB.c.
Referenced by schtb_().
logical canflg
Definition at line 32 of file SCHTB.c.
doublereal degrad
Definition at line 24 of file SCHTB.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 18 of file SCHTB.c.
logical jcs
Definition at line 32 of file SCHTB.c.
logical jds
Definition at line 32 of file SCHTB.c.
integer k0
Definition at line 39 of file SCHTB.c.
integer k1
Definition at line 39 of file SCHTB.c.
integer k10
Definition at line 39 of file SCHTB.c.
integer k1013
Definition at line 39 of file SCHTB.c.
integer k12
Definition at line 39 of file SCHTB.c.
integer k13
Definition at line 39 of file SCHTB.c.
integer k15
Definition at line 39 of file SCHTB.c.
integer k16
Definition at line 39 of file SCHTB.c.
integer k18
Definition at line 39 of file SCHTB.c.
integer k19
Definition at line 39 of file SCHTB.c.
integer k1e4
Definition at line 39 of file SCHTB.c.
integer k1e6
Definition at line 39 of file SCHTB.c.
integer k2
Definition at line 39 of file SCHTB.c.
integer k23
Definition at line 39 of file SCHTB.c.
integer k24
Definition at line 39 of file SCHTB.c.
integer k25
Definition at line 39 of file SCHTB.c.
integer k26
Definition at line 39 of file SCHTB.c.
integer k27
Definition at line 39 of file SCHTB.c.
integer k29
Definition at line 39 of file SCHTB.c.
integer k3
Definition at line 39 of file SCHTB.c.
integer k30
Definition at line 39 of file SCHTB.c.
integer k31
Definition at line 39 of file SCHTB.c.
integer k32
Definition at line 39 of file SCHTB.c.
integer k33
Definition at line 39 of file SCHTB.c.
integer k34
Definition at line 39 of file SCHTB.c.
integer k4
Definition at line 39 of file SCHTB.c.
integer k44
Definition at line 39 of file SCHTB.c.
integer k45
Definition at line 39 of file SCHTB.c.
integer k46
Definition at line 39 of file SCHTB.c.
integer k47
Definition at line 39 of file SCHTB.c.
integer k48
Definition at line 39 of file SCHTB.c.
integer k5
Definition at line 39 of file SCHTB.c.
integer k50
Definition at line 39 of file SCHTB.c.
integer k51
Definition at line 39 of file SCHTB.c.
integer k52
Definition at line 39 of file SCHTB.c.
integer k6
Definition at line 39 of file SCHTB.c.
integer k7
Definition at line 39 of file SCHTB.c.
integer k8
Definition at line 39 of file SCHTB.c.
integer k9
Definition at line 39 of file SCHTB.c.
integer km1
Definition at line 39 of file SCHTB.c.
struct { ... } knumbr_
doublereal l[4]
Definition at line 18 of file SCHTB.c.
struct { ... } ldef_
doublereal p[16]
Definition at line 18 of file SCHTB.c.
logical pchlst
Definition at line 32 of file SCHTB.c.
doublereal pi
Definition at line 24 of file SCHTB.c.
logical prnton
Definition at line 32 of file SCHTB.c.
logical refflg
Definition at line 32 of file SCHTB.c.
logical refmot
Definition at line 32 of file SCHTB.c.
doublereal sc[16]
Definition at line 18 of file SCHTB.c.
logical subflg
Definition at line 32 of file SCHTB.c.
doublereal t[12]
Definition at line 18 of file SCHTB.c.
doublereal t1[12]
Definition at line 18 of file SCHTB.c.
logical tabprt
Definition at line 32 of file SCHTB.c.
logical unflag
Definition at line 32 of file SCHTB.c.
doublereal v[10]
Definition at line 18 of file SCHTB.c.
doublereal z0
Definition at line 24 of file SCHTB.c.
doublereal z1
Definition at line 24 of file SCHTB.c.
doublereal z10
Definition at line 24 of file SCHTB.c.
doublereal z11em1
Definition at line 24 of file SCHTB.c.
doublereal z12em1
Definition at line 24 of file SCHTB.c.
doublereal z1e38
Definition at line 24 of file SCHTB.c.
doublereal z1e6
Definition at line 24 of file SCHTB.c.
doublereal z1em1
Definition at line 24 of file SCHTB.c.
doublereal z1em2
Definition at line 24 of file SCHTB.c.
doublereal z1em3
Definition at line 24 of file SCHTB.c.
doublereal z1em5
Definition at line 24 of file SCHTB.c.
doublereal z1em6
Definition at line 24 of file SCHTB.c.
doublereal z1em7
Definition at line 24 of file SCHTB.c.
doublereal z1em9
Definition at line 24 of file SCHTB.c.
doublereal z2
Definition at line 24 of file SCHTB.c.
doublereal z3
Definition at line 24 of file SCHTB.c.
doublereal z5
Definition at line 24 of file SCHTB.c.
doublereal z5em1
Definition at line 24 of file SCHTB.c.
doublereal z5em6
Definition at line 24 of file SCHTB.c.
doublereal z6em1
Definition at line 24 of file SCHTB.c.
doublereal z90
Definition at line 24 of file SCHTB.c.
doublereal z9em1
Definition at line 24 of file SCHTB.c.
logical zflag
Definition at line 32 of file SCHTB.c.
doublereal zm1
Definition at line 24 of file SCHTB.c.
struct { ... } znumbr_