My Project: SEARCH.c File Reference
SEARCH.c File Reference
#include "f2c.h"
Macros
#define sdp_1 sdp_
Functions
integer search_ (integer *source, integer *iadr, integer *prodct, integer *errpt)
Variables
struct {
integer nbchar
integer nbwrd
integer iwrd
integer ifac
} sdp_
Macro Definition Documentation
#define sdp_1 sdp_
Definition at line 21 of file SEARCH.c.
Referenced by search_().
Function Documentation
integer search_ (integer * source, integer * iadr, integer * prodct, integer * errpt)
Definition at line 51 of file SEARCH.c.
References andf_(), i__, j, k, origin, and sdp_1.
Referenced by goloft_(), gopat_(), inpat_(), larges_(), pro020_(), pro021_(), pro028_(), recog_(), ssdef_(), and tssmil_().
 {
     /* Initialized data */
     static integer z9999 = -1718026240;
     static integer zaaaa = -1431699456;
     static integer zcccc = -859045888;
     static integer zffff = -65536;
     /* System generated locals */
     integer ret_val;
     /* Local variables */
     static integer i__, j, k;
     extern integer andf_(integer *, integer *);
     static integer iadsav, origin, subpat;
 /*     IWRD: NO. OF BYTES PER WORD */
     /* Parameter adjustments */
     --prodct;
     --source;
     /* Function Body */
 /* .... SAVE INITIAL STACK ADDRESS */
     iadsav = *iadr;
 /* .... PRODCT ADDRESS */
     j = 1;
 /* .... INITIAL VALUE OF ERRPT */
 L5:
     k = *errpt;
 /* .... INITIAL STACK ADDRESS */
     i__ = iadsav;
 /* .... IS ADDRESS IN PRODCT A BREAK POINT ? */
     subpat = andf_(&prodct[j], &zffff);
     if (subpat == z9999) {
 /* .... YES - STORE THE BASIC ADDRESS, INCREMENT PRODCT ADDRESS BY 1 */
     origin = j;
     ++j;
     } else {
 /* .... NOT A BREAK POINT - DECREASE STACK ADDRESS BY 2 */
 /*                         DECREASE ERRPT BY 1 */
     i__ += -2;
     --k;
     }
 /* .... NEW PRODUCTION */
 L10:
     if (prodct[j] >= 0) {
 /* .... COMPARE IF NEXT INFORMATION IS AN ARGUMENT, */
 /*     IF SO CHANGE TO SEQUENTIAL MODE */
     if (prodct[j + 1] > 0) {
         goto L50;
     }
 /* ....COMPARE STACK AND PRODCT */
     subpat = andf_(&source[i__], &prodct[j]);
     if (source[i__] == subpat) {
 /* .... PRODUCTION STILL OK, INCREMENT PRODCT BY 1 */
 /*                          DECREMENT STACK BY 2 */
         ++j;
         i__ += -2;
 /* .... DECREMENT ERRPT */
         --k;
     } else {
 /* .... MAINTAIN STACK ADDRESS CONSTANT, INCREMENT PRODCT BY 2 */
 /*     AND SEARCH NEW PRODUCTION */
         j += 2;
     }
     goto L10;
     } else {
 /* .... IS PRODCT A PRODUCTION NUMBER */
     subpat = andf_(&prodct[j], &zffff);
     if (subpat == zcccc) {
         goto L80;
 /* .... IS IT A DISPLACEMENT */
     } else if (subpat == zaaaa) {
 /* .... YES */
         j = (prodct[j] - zaaaa) / sdp_1.iwrd;
         j += origin;
         goto L10;
     } else {
         goto L5;
     }
     }
 /* .... SEQUENTIAL SEARCHING */
 L50:
     subpat = andf_(&source[i__], &prodct[j]);
     if (source[i__] == subpat) {
 /* .... NEXT HIGHER PRODCT ADDRESS, NEXT LOWER STACK ADDRESS */
     ++j;
     i__ += -2;
 /* .... DECREMENT ERRPT */
     --k;
 /* .... IS PRODCT A PRODUCTION NUMBER */
     subpat = andf_(&prodct[j], &zffff);
     if (subpat == zcccc) {
         goto L80;
     } else {
         goto L50;
     }
     } else {
 /* .... SEARCHING FAILED. FINAL PROCESS. */
 /*     SEARCH FOR NEXT FINAL PRODUCTION NUMBER */
 L60:
     ++j;
     subpat = andf_(&prodct[j], &zffff);
     if (subpat == zcccc) {
         ++j;
         goto L80;
     } else {
         goto L60;
     }
     }
 /* .... PRODUCTION NUMBER */
 L80:
     ret_val = prodct[j] - zcccc;
     *errpt = k;
     return ret_val;
 } /* search_ */
Variable Documentation
integer ifac
Definition at line 18 of file SEARCH.c.
integer iwrd
Definition at line 18 of file SEARCH.c.
integer nbchar
Definition at line 18 of file SEARCH.c.
integer nbwrd
Definition at line 18 of file SEARCH.c.
struct { ... } sdp_