My Project: SET.c File Reference
SET.c File Reference
#include "f2c.h"
Macros
#define _BLNK__1 _BLNK__
#define work_1 work_
#define darray_1 darray_
#define cf ((doublereal *)&_BLNK__1)
#define ia ((doublereal *)&_BLNK__1)
#define nb ((doublereal *)&_BLNK__1)
#define cm ((integer *)&_BLNK__1)
#define fp ((doublereal *)&_BLNK__1)
#define pp ((integer *)&_BLNK__1)
#define mt ((integer *)&_BLNK__1)
#define nt ((integer *)&_BLNK__1)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int set_ (integer *ln)
Variables
struct {
doublereal com [36000]
} _BLNK__
struct {
integer pgc
integer pgcn
integer ilc
integer ixc
} work_
struct {
char darray [120]
} darray_
static integer c__1 = 1
static integer c__39 = 39
static integer c__40 = 40
static integer c__4 = 4
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 21 of file SET.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define cf ((doublereal *)&_BLNK__1)
#define cm ((integer *)&_BLNK__1)
#define darray_1 darray_
Definition at line 33 of file SET.c.
Referenced by set_().
#define fp ((doublereal *)&_BLNK__1)
#define ia ((doublereal *)&_BLNK__1)
#define mt ((integer *)&_BLNK__1)
#define nb ((doublereal *)&_BLNK__1)
#define nt ((integer *)&_BLNK__1)
#define pp ((integer *)&_BLNK__1)
Referenced by set_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define work_1 work_
Definition at line 27 of file SET.c.
Referenced by set_().
Function Documentation
int set_ (integer * ln)
Definition at line 46 of file SET.c.
References c__1, c__39, c__4, c__40, cform_(), cprint_(), darray_1, help_(), iconv_(), ln1, page_(), pp, record_(), sqnc, and work_1.
Referenced by intrp_().
 {
     /* Local variables */
 #define cf ((doublereal *)&_BLNK__1)
 #define ia ((doublereal *)&_BLNK__1)
 #define nb ((doublereal *)&_BLNK__1)
 #define cm ((integer *)&_BLNK__1)
 #define fp ((doublereal *)&_BLNK__1)
 #define pp ((integer *)&_BLNK__1)
 #define mt ((integer *)&_BLNK__1)
 #define nt ((integer *)&_BLNK__1)
     static integer ln1;
 #define can ((doublereal *)&_BLNK__1 + 40)
     extern integer page_(integer *);
     extern /* Subroutine */ int help_(void);
     static integer sqnc;
 #define canon ((doublereal *)&_BLNK__1)
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen);
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int iconv_(integer *, char *, integer *, integer *
         , ftnlen);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int record_(integer *), cprint_(char *, ftnlen);
 /* FORTRAN SUBROUTINE 'SET(LN)'  -- SET LOCATION COUNTER TO LINE */
 /* PURPOSE      'SET'    SETS THE INTERPRETER PSEUDOLOCATION  COUNTER, */
 /*              'ILC' AND OTHER DEPENDENT VARIABLES TO THE VALUES */
 /*              CORRESPONDING TO THE INPUT LINE. */
 /* LINKAGE      CALL SET(LN) */
 /*              WHERE */
 /*              LN IS ANY LINE */
 /* --------------------------------------------------------------CDE PAK */
 /* UNLABELED COMMON */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /* WORK--COMMON CONTAINING WORKING VARIABLES */
 /*     ------------------- */
 /* --------------------------------------------------------------------- */
 /*         LN IS ANY LINE(PAGE AND INDEX) */
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
     /* Parameter adjustments */
     --ln;
     /* Function Body */
     ln1 = abs(ln[1]);
     if (ln1 > 0 && ln1 <= 400 && (ln[2] > 0 && ln[2] <= 256)) {
     goto L100;
     }
     record_(&sqnc);
     cform_("029007 UNDEFINED LABEL REFERENCED. ISN=", darray_1.darray, &c__1,
         &c__39, (ftnlen)39, (ftnlen)120);
     iconv_(&sqnc, darray_1.darray, &c__40, &c__4, (ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     help_();
 /*        SET LOCATION COUNTER TO BEGINNING OF PAGE */
 L100:
     work_1.ilc = page_(&ln[1]);
 /*        SET NEW PAGE NUMBER AND INDEX */
     work_1.pgc = ln[1];
     work_1.ixc = ln[2];
 /*        SET NUMBER OF WORDS ON CURRENT PAGE */
     work_1.pgcn = pp[work_1.ilc] + 2;
 /*        ADVANCE LOCATION COUNTER TO INSTRUCTION */
     work_1.ilc = work_1.ilc + work_1.ixc - 1;
     return 0;
 } /* set_ */
Variable Documentation
struct { ... } _BLNK__
integer c__1 = 1 static
Definition at line 37 of file SET.c.
Referenced by set_().
integer c__39 = 39 static
Definition at line 38 of file SET.c.
Referenced by set_().
integer c__4 = 4 static
Definition at line 40 of file SET.c.
Referenced by set_().
integer c__40 = 40 static
Definition at line 39 of file SET.c.
Referenced by set_().
doublereal com[36000]
Definition at line 18 of file SET.c.
char darray[120]
Definition at line 30 of file SET.c.
struct { ... } darray_
integer ilc
Definition at line 24 of file SET.c.
integer ixc
Definition at line 24 of file SET.c.
integer pgc
Definition at line 24 of file SET.c.
integer pgcn
Definition at line 24 of file SET.c.
struct { ... } work_