My Project: SETCHR.c File Reference
SETCHR.c File Reference
#include "f2c.h"
Macros
#define stklst_1 stklst_
#define srctbl_1 srctbl_
#define moduli_1 moduli_
#define meta ((integer *)&srctbl_1 + 2)
#define stack ((integer *)&stklst_1 + 3)
#define modulo ((integer *)&moduli_1)
Functions
int setchr_ (integer *pntr, integer *class__)
Variables
struct {
integer stklst [300]
} stklst_
struct {
integer srctbl [502]
} srctbl_
struct {
integer moduli [2]
} moduli_
Macro Definition Documentation
#define meta ((integer *)&srctbl_1 + 2)
Referenced by setchr_().
#define moduli_1 moduli_
Definition at line 33 of file SETCHR.c.
#define modulo ((integer *)&moduli_1)
Referenced by setchr_().
#define srctbl_1 srctbl_
Definition at line 27 of file SETCHR.c.
#define stack ((integer *)&stklst_1 + 3)
Referenced by setchr_().
#define stklst_1 stklst_
Definition at line 21 of file SETCHR.c.
Function Documentation
int setchr_ (integer * pntr, integer * class__)
Definition at line 49 of file SETCHR.c.
References i__, meta, modulo, and stack.
Referenced by konast_(), loop_(), recog_(), and vctprd_().
 {
     /* Local variables */
     static integer i__;
 #define meta ((integer *)&srctbl_1 + 2)
 #define stack ((integer *)&stklst_1 + 3)
 #define modulo ((integer *)&moduli_1)
 /*        2.    STACK AND POINTER STORAGE */
 /* STACK:       WORKING STACK */
 /*        4.    PRODUCTION TABLE */
 /* META:        CONTAINS INTERNAL BIT CODES FOR METALINGUISTIC CLASSES */
 /*       29.    CLASS CODE MODULI */
 /* MODULO:      NAMTBL CLASS AND CODE FACTOR 1000 TO DEVIDE OUT CLASS */
 /* * */
 /* ARGUMENTS    PNTR      STACK INDEX OF ENTRY */
 /*              CLASS     TWO ELEMENT ARRAY WHERE CLASS(2) */
 /*                        CONTAINS NAME TABLE (NAMTBL) INDEX OF */
 /*                        DESIRED META-CHARACTER. */
 /*     CHANGE A CHARACTER */
 /* ** */
     /* Parameter adjustments */
     --class__;
     /* Function Body */
     stack[(*pntr << 1) - 2] = class__[2];
     i__ = class__[1] / *modulo;
     stack[(*pntr << 1) - 1] = meta[i__ - 1];
     return 0;
 } /* setchr_ */
Variable Documentation
integer moduli[2]
Definition at line 30 of file SETCHR.c.
struct { ... } moduli_
integer srctbl[502]
Definition at line 24 of file SETCHR.c.
struct { ... } srctbl_
integer stklst[300]
Definition at line 18 of file SETCHR.c.
struct { ... } stklst_