My Project: SETMOD.c File Reference
SETMOD.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define stklst_1 stklst_
#define code_1 code_
#define srctbl_1 srctbl_
#define moduli_1 moduli_
#define fcn ((integer *)&code_1 + 34)
#define meta ((integer *)&srctbl_1 + 2)
#define geom ((integer *)&code_1 + 30)
#define stack ((integer *)&stklst_1 + 3)
#define biggeo ((integer *)&code_1 + 86)
#define proced ((integer *)&code_1 + 36)
#define permid ((integer *)&code_1 + 38)
#define modulo ((integer *)&moduli_1)
Functions
int setmod_ (integer *pntr, integer *class__)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer stklst [300]
} stklst_
struct {
integer code [150]
} code_
struct {
integer srctbl [502]
} srctbl_
struct {
integer moduli [2]
} moduli_
Macro Definition Documentation
#define biggeo ((integer *)&code_1 + 86)
Referenced by setmod_().
#define cnamtb_1 cnamtb_
Definition at line 28 of file SETMOD.c.
#define code_1 code_
Definition at line 40 of file SETMOD.c.
#define fcn ((integer *)&code_1 + 34)
Referenced by setmod_().
#define geom ((integer *)&code_1 + 30)
Referenced by setmod_().
#define meta ((integer *)&srctbl_1 + 2)
Referenced by setmod_().
#define moduli_1 moduli_
Definition at line 52 of file SETMOD.c.
#define modulo ((integer *)&moduli_1)
Referenced by setmod_().
#define nametb_1 nametb_
Definition at line 22 of file SETMOD.c.
Referenced by setmod_().
#define permid ((integer *)&code_1 + 38)
Referenced by setmod_().
#define proced ((integer *)&code_1 + 36)
Referenced by setmod_().
#define srctbl_1 srctbl_
Definition at line 46 of file SETMOD.c.
#define stack ((integer *)&stklst_1 + 3)
Referenced by setmod_().
#define stklst_1 stklst_
Definition at line 34 of file SETMOD.c.
Function Documentation
int setmod_ (integer * pntr, integer * class__)
Definition at line 69 of file SETMOD.c.
References biggeo, fcn, geom, i__, j, meta, modulo, nametb_1, permid, proced, and stack.
Referenced by larges_(), pro020_(), recog_(), recogn_(), and replac_().
 {
     /* Local variables */
     static integer i__, j;
 #define fcn ((integer *)&code_1 + 34)
 #define meta ((integer *)&srctbl_1 + 2)
 #define geom ((integer *)&code_1 + 30)
 #define stack ((integer *)&stklst_1 + 3)
 #define biggeo ((integer *)&code_1 + 86)
 #define proced ((integer *)&code_1 + 36)
 #define permid ((integer *)&code_1 + 38)
 #define modulo ((integer *)&moduli_1)
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /*        2.    STACK AND POINTER STORAGE */
 /* STACK:       WORKING STACK */
 /*        3.    METALINGUISTIC VARIABLE CLASS CODES */
 /* GEOM:        (1)=CODE CLASS 16000,(2)=NAMTBL INDEX OF 'GEOM  ' */
 /* FCN:         (1)=CODE CLASS 18000,(2)=NAMTBL INDEX OF 'FCN   ' */
 /* PROCED:      (1)=CODE CLASS 19000,(2)=NAMTBL INDEX OF 'PROCED' */
 /* PERMID:      (1)=CODE CLASS 20000,(2)=NAMTBL INDEX OF 'PERMID' */
 /* BIGGEO:      (1)=CODE CLASS 44000,(2)=NAMTBL INDEX OF 'BIGGEO' */
 /*        4.    PRODUCTION TABLE */
 /* META:        CONTAINS INTERNAL BIT CODES FOR METALINGUISTIC CLASSES */
 /*       29.    CLASS CODE MODULI */
 /* MODULO:      NAMTBL CLASS AND CODE FACTOR 1000 TO DEVIDE OUT CLASS */
 /* * */
 /* ARGUMENTS    PNTR      WORKING STACK (STACK) POINTER OF */
 /*                        ITEM WHOSE CLASS IS TO BE CHANGED. */
 /*              CLASS     NEW META-LINQUISTIC CLASS ASSIGNMENT. */
 /* NOTES        IF CLASS IS PERMID, PROCED, OR GEOM, IT IS */
 /*              ASSUMED THAT PREVIOUS CLASS WAS IDENT, CONPRO, */
 /*              OR CONGEO, RESPECTIVELY, IN WHICH CASE THE */
 /*              ORIGINAL MODE IS RETAINED. */
 /*     CHANGE THE CLASS OF A CHARACTER */
 /* ** */
     /* Parameter adjustments */
     --class__;
     /* Function Body */
     i__ = stack[(*pntr << 1) - 2];
     j = class__[1];
     if (j == permid[0] || j == geom[0] || j == biggeo[0] || j == proced[0]) {
     goto L1;
     }
     if (j == fcn[0]) {
     goto L1;
     }
     nametb_1.namtbl[i__ - 1] = j;
     goto L2;
 L1:
     nametb_1.namtbl[i__ - 1] = j + (nametb_1.namtbl[i__ - 1] - *modulo * (
         nametb_1.namtbl[i__ - 1] / *modulo));
 L2:
     j /= *modulo;
     stack[(*pntr << 1) - 1] = meta[j - 1];
     return 0;
 } /* setmod_ */
Variable Documentation
integer charnd
Definition at line 18 of file SETMOD.c.
integer charst
Definition at line 18 of file SETMOD.c.
char cnamtb[18000]
Definition at line 25 of file SETMOD.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file SETMOD.c.
integer code[150]
Definition at line 37 of file SETMOD.c.
struct { ... } code_
integer ifixnd
Definition at line 18 of file SETMOD.c.
integer ifixst
Definition at line 18 of file SETMOD.c.
integer inamnd
Definition at line 18 of file SETMOD.c.
integer inamst
Definition at line 18 of file SETMOD.c.
integer moduli[2]
Definition at line 49 of file SETMOD.c.
struct { ... } moduli_
integer namest
Definition at line 18 of file SETMOD.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file SETMOD.c.
integer namtbl[3000]
Definition at line 18 of file SETMOD.c.
integer numbnd
Definition at line 18 of file SETMOD.c.
integer numbst
Definition at line 18 of file SETMOD.c.
integer srctbl[502]
Definition at line 43 of file SETMOD.c.
struct { ... } srctbl_
integer stklst[300]
Definition at line 31 of file SETMOD.c.
struct { ... } stklst_