My Project: SNORM.c File Reference
SNORM.c File Reference
#include "f2c.h"
Functions
int snorm_ (doublereal *a, doublereal *b, integer *irr)
Function Documentation
int snorm_ (doublereal * a, doublereal * b, integer * irr)
Definition at line 17 of file SNORM.c.
References a, b, and w.
Referenced by revolv_(), scpict_(), scurv_(), and ssplin_().
 {
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     static doublereal w;
     /* Parameter adjustments */
     --b;
     --a;
     /* Function Body */
     *irr = 1;
     w = sqrt(a[1] * a[1] + a[2] * a[2] + a[3] * a[3]);
     if (w < 1e-15) {
     return 0;
     }
     *irr = 0;
     b[1] = a[1] / w;
     b[2] = a[2] / w;
     b[3] = a[3] / w;
     return 0;
 } /* snorm_ */