My Project: SPATF.c File Reference
SPATF.c File Reference
#include "f2c.h"
Functions
int spatf_ (doublereal *res, doublereal *arg1, doublereal *arg2, doublereal *arg3)
Variables
static integer c__54 = 54
Function Documentation
int spatf_ (doublereal * res, doublereal * arg1, doublereal * arg2, doublereal * arg3)
Definition at line 38 of file SPATF.c.
References arg1, arg2, c__54, ckdef_(), error_(), is, mode, undef_(), and unpack_().
Referenced by xcall_().
 {
     /* Initialized data */
     static integer is[20] = { 1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1 };
     static integer isi, isu, mode;
     extern logical ckdef_(doublereal *);
     extern /* Subroutine */ int undef_(doublereal *), error_(integer *, char *
         , ftnlen), unpack_(doublereal *, integer *, integer *, integer *);
     /* Parameter adjustments */
     --arg3;
     --arg2;
     --arg1;
     --res;
     /* Function Body */
     if (ckdef_(&arg1[1]) || ckdef_(&arg2[1]) || ckdef_(&arg3[1])) {
     goto L30;
     }
     unpack_(&arg1[1], &mode, &isi, &isu);
     if (mode < 1 || mode > 20 || is[mode - 1] != 1) {
     goto L30;
     }
     unpack_(&arg2[1], &mode, &isi, &isu);
     if (mode < 1 || mode > 20 || is[mode - 1] != 1) {
     goto L30;
     }
     unpack_(&arg3[1], &mode, &isi, &isu);
     if (mode < 1 || mode > 20 || is[mode - 1] != 1) {
     goto L30;
     }
     res[1] = arg1[1] * (arg2[2] * arg3[3] - arg2[3] * arg3[2]) + arg1[2] * (
         arg2[3] * arg3[1] - arg2[1] * arg3[3]) + arg1[3] * (arg2[1] *
         arg3[2] - arg2[2] * arg3[1]);
     return 0;
 /*     'AT LEAST ONE OF THE VECTORS UNDEFINED OR WRONG INPUT' */
 L30:
     error_(&c__54, "SPATF   ", (ftnlen)8);
     undef_(&res[1]);
     return 0;
 } /* spatf_ */
Variable Documentation
integer c__54 = 54 static
Definition at line 17 of file SPATF.c.
Referenced by spatf_().