My Project: SRFDIR.c File Reference
SRFDIR.c File Reference
#include "f2c.h"
Macros
#define ibugg_1 ibugg_
Functions
int srfdir_ (doublereal *dr, doublereal *r__, doublereal *side, doublereal *pdir, doublereal *sx, doublereal *svec, doublereal *sk, integer *irr)
Variables
struct {
integer ibug
integer ipcolc
integer ipcolm
} ibugg_
static integer c_n1 = -1
static integer c__0 = 0
static integer c__1 = 1
static integer c_n2 = -2
static integer c_n3 = -3
Macro Definition Documentation
#define ibugg_1 ibugg_
Definition at line 21 of file SRFDIR.c.
Referenced by srfdir_().
Function Documentation
int srfdir_ (doublereal * dr, doublereal * r__, doublereal * side, doublereal * pdir, doublereal * sx, doublereal * svec, doublereal * sk, integer * irr)
Definition at line 33 of file SRFDIR.c.
References bad_(), c__0, c__1, c_n1, c_n2, c_n3, cprint_(), dotf_(), i__, ibugg_1, kursrf_(), r__, and zero.
Referenced by sspath_().
 {
     /* Initialized data */
     static doublereal zero = 0.;
     static doublereal smal = 1e-38;
     /* System generated locals */
     doublereal d__1, d__2;
     /* Builtin functions */
     double sqrt(doublereal);
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__;
     extern /* Subroutine */ int bad_();
     static doublereal fac;
     extern /* Subroutine */ int dotf_(doublereal *, doublereal *, doublereal *
         );
     static doublereal xcos, xsin;
     static char badmsg[20];
     extern /* Subroutine */ int cprint_(char *, ftnlen), kursrf_(doublereal *,
          doublereal *, doublereal *);
 /* ---PURPOSE IS TO COMPUTE SURFACE CURVATURE SK AND DIRECTION SVEC */
 /* --IN DIRECTION OF MOVEMENT INDICATED BY DRIVE GEOMETRY ARRAY */
 /* --DR. */
     /* Parameter adjustments */
     --svec;
     --sx;
     --r__;
     --dr;
     /* Function Body */
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L10: */
     svec[i__] = zero;
     }
     *sk = zero;
     kursrf_(&r__[1], side, &sx[1]);
 /* --PROJECT DRIVE TANGENT VECTOR INTO SURFACE TANGENT PLANE */
     dotf_(&fac, &r__[29], &dr[13]);
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L20: */
     svec[i__] = dr[i__ + 12] - fac * r__[i__ + 28];
     }
     dotf_(&fac, &svec[1], &svec[1]);
     if (fac < smal) {
     goto L999;
     }
     fac = sqrt(fac) * *pdir;
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L30: */
     svec[i__] = fac * svec[i__];
     }
 /* --NOW COMPUTE THE CURVATURE OF THE SURFACE IN THE SVEC DIRECTION */
     dotf_(&xcos, &svec[1], &sx[5]);
     dotf_(&xsin, &svec[1], &sx[9]);
 /* Computing 2nd power */
     d__1 = xcos;
 /* Computing 2nd power */
     d__2 = xsin;
     *sk = sx[1] * (d__1 * d__1) + sx[2] * (d__2 * d__2);
 L999:
     if (ibugg_1.ibug != 11) {
     goto L1999;
     }
     bad_(&c_n1, &c__0, " ", &c__0, (ftnlen)1);
     s_copy(badmsg, " AFTER SRFDIR", (ftnlen)20, (ftnlen)13);
     cprint_(badmsg, (ftnlen)20);
     bad_(&c__1, &c__0, "IRR ", irr, (ftnlen)4);
     bad_(&c__1, &c__1, "SK  ", sk, (ftnlen)4);
     bad_(&c_n2, &c__1, "SX  ", &sx[1], (ftnlen)4);
     bad_(&c_n3, &c__1, "SVEC", &svec[1], (ftnlen)4);
 L1999:
     return 0;
 } /* srfdir_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 26 of file SRFDIR.c.
Referenced by srfdir_().
integer c__1 = 1 static
Definition at line 27 of file SRFDIR.c.
Referenced by srfdir_().
integer c_n1 = -1 static
Definition at line 25 of file SRFDIR.c.
Referenced by srfdir_().
integer c_n2 = -2 static
Definition at line 28 of file SRFDIR.c.
Referenced by srfdir_().
integer c_n3 = -3 static
Definition at line 29 of file SRFDIR.c.
Referenced by srfdir_().
integer ibug
Definition at line 18 of file SRFDIR.c.
struct { ... } ibugg_
integer ipcolc
Definition at line 18 of file SRFDIR.c.
integer ipcolm
Definition at line 18 of file SRFDIR.c.