My Project: STEPCK.c File Reference
STEPCK.c File Reference
#include "f2c.h"
Macros
#define ibugg_1 ibugg_
Functions
int stepck_ (doublereal *side, doublereal *r__, doublereal *rx, doublereal *rk, doublereal *rl, doublereal *rxl, doublereal *rkl, doublereal *efrad, doublereal *tol, doublereal *srmin, doublereal *tlmin)
Variables
struct {
integer ibug
integer ipcolc
integer ipcolm
} ibugg_
static integer c_n1 = -1
static integer c__0 = 0
static integer c__1 = 1
Macro Definition Documentation
#define ibugg_1 ibugg_
Definition at line 21 of file STEPCK.c.
Referenced by stepck_().
Function Documentation
int stepck_ (doublereal * side, doublereal * r__, doublereal * rx, doublereal * rk, doublereal * rl, doublereal * rxl, doublereal * rkl, doublereal * efrad, doublereal * tol, doublereal * srmin, doublereal * tlmin)
Definition at line 31 of file STEPCK.c.
References bad_(), c__0, c__1, c_n1, cprint_(), dotf_(), i__, ibugg_1, r__, rl, srftol_(), and w.
Referenced by sspath_().
 {
     /* Initialized data */
     static doublereal smal = 1e-38;
     static doublereal big = 1e10;
     /* Builtin functions */
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__;
     static doublereal w;
     extern /* Subroutine */ int bad_();
     static doublereal rsq, rdif[3];
     extern /* Subroutine */ int dotf_(doublereal *, doublereal *, doublereal *
         );
     static doublereal smin, tmin;
     static char badmsg[20];
     extern /* Subroutine */ int cprint_(char *, ftnlen), srftol_(doublereal *,
          doublereal *, doublereal *, doublereal *, doublereal *);
     /* Parameter adjustments */
     --rxl;
     --rl;
     --rx;
     --r__;
     /* Function Body */
 /* --PURPOSE IS TO COMPUTE MINIMUM SURFACE (SRMIN) AND TOOL STEPS */
 /* --(TLMIN) BASED ON CURRENT AND LAST CONTACT POINTS */
     *srmin = big;
     *tlmin = big;
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L10: */
     rdif[i__ - 1] = r__[i__] - rl[i__];
     }
     dotf_(&rsq, rdif, rdif);
     srftol_(rk, efrad, tol, &smin, &tmin);
     *srmin = min(*srmin,smin);
     *tlmin = min(*tlmin,tmin);
     srftol_(rkl, efrad, tol, &smin, &tmin);
     *srmin = min(*srmin,smin);
     *tlmin = min(*tlmin,tmin);
     if (rsq < smal) {
     goto L999;
     }
     dotf_(&w, &r__[29], rdif);
     w = w * -2.f * *side / rsq;
     srftol_(&w, efrad, tol, &smin, &tmin);
     *srmin = min(*srmin,smin);
     *tlmin = min(*tlmin,tmin);
     dotf_(&w, &rl[29], rdif);
     w = w * 2.f * *side / rsq;
     srftol_(&w, efrad, tol, &smin, &tmin);
     *srmin = min(*srmin,smin);
     *tlmin = min(*tlmin,tmin);
 L999:
     if (ibugg_1.ibug != 11) {
     goto L1999;
     }
     bad_(&c_n1, &c__0, " ", &c__0, (ftnlen)1);
     s_copy(badmsg, " AFTER STEPCK", (ftnlen)20, (ftnlen)13);
     cprint_(badmsg, (ftnlen)20);
     bad_(&c__1, &c__1, "SIDE", side, (ftnlen)4);
     bad_(&c__1, &c__1, "RK  ", rk, (ftnlen)4);
     bad_(&c__1, &c__1, "RKL ", rkl, (ftnlen)4);
     bad_(&c__1, &c__1, "ERAD", efrad, (ftnlen)4);
     bad_(&c_n1, &c__1, "TOL ", tol, (ftnlen)4);
     bad_(&c__1, &c__1, "SRMN", srmin, (ftnlen)4);
     bad_(&c_n1, &c__1, "TLMN", tlmin, (ftnlen)4);
 L1999:
     return 0;
 } /* stepck_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 26 of file STEPCK.c.
Referenced by stepck_().
integer c__1 = 1 static
Definition at line 27 of file STEPCK.c.
Referenced by stepck_().
integer c_n1 = -1 static
Definition at line 25 of file STEPCK.c.
Referenced by stepck_().
integer ibug
Definition at line 18 of file STEPCK.c.
struct { ... } ibugg_
integer ipcolc
Definition at line 18 of file STEPCK.c.
integer ipcolm
Definition at line 18 of file STEPCK.c.