My Project: SUBCOD.c File Reference
SUBCOD.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define stklst_1 stklst_
#define code_1 code_
#define tmp_1 tmp_
#define sbscpt_1 sbscpt_
#define il_1 il_
#define modx_1 modx_
#define macxx1_1 macxx1_
#define moduli_1 moduli_
#define isscom_1 isscom_
#define vbl ((integer *)&code_1 + 60)
#define top ((integer *)&stklst_1)
#define temp ((integer *)&code_1 + 32)
#define range ((integer *)&sbscpt_1 + 1)
#define stack ((integer *)&stklst_1 + 3)
#define ilhlt ((logical *)&macxx1_1 + 13)
#define issfl ((logical *)&isscom_1 + 5)
#define rngpt ((integer *)&sbscpt_1)
#define modhlf ((integer *)&moduli_1 + 1)
#define intmed ((integer *)&macxx1_1 + 21)
#define modulo ((integer *)&moduli_1)
#define issmod ((integer *)&isscom_1 + 4)
#define subscr ((integer *)&modx_1 + 23)
#define cvtsub ((integer *)&il_1 + 12)
#define isstrm ((integer *)&isscom_1 + 7)
Functions
int subcod_ (integer *tpx)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer stklst [300]
} stklst_
struct {
integer code [150]
} code_
struct {
integer txxxx [64]
} tmp_
struct {
integer sbscpt [101]
} sbscpt_
struct {
integer il [21]
} il_
struct {
integer modx [32]
} modx_
struct {
integer macxx1 [71]
} macxx1_
struct {
integer moduli [2]
} moduli_
struct {
integer isscom [9]
} isscom_
static integer c__1013 = 1013
static integer c__8 = 8
Macro Definition Documentation
#define cnamtb_1 cnamtb_
Definition at line 28 of file SUBCOD.c.
#define code_1 code_
Definition at line 40 of file SUBCOD.c.
#define cvtsub ((integer *)&il_1 + 12)
Referenced by subcod_().
#define il_1 il_
Definition at line 58 of file SUBCOD.c.
#define ilhlt ((logical *)&macxx1_1 + 13)
Referenced by subcod_().
#define intmed ((integer *)&macxx1_1 + 21)
Referenced by subcod_().
#define isscom_1 isscom_
Definition at line 82 of file SUBCOD.c.
#define issfl ((logical *)&isscom_1 + 5)
Referenced by subcod_().
#define issmod ((integer *)&isscom_1 + 4)
Referenced by subcod_().
#define isstrm ((integer *)&isscom_1 + 7)
Referenced by subcod_().
#define macxx1_1 macxx1_
Definition at line 70 of file SUBCOD.c.
#define modhlf ((integer *)&moduli_1 + 1)
Referenced by subcod_().
#define moduli_1 moduli_
Definition at line 76 of file SUBCOD.c.
#define modulo ((integer *)&moduli_1)
Referenced by subcod_().
#define modx_1 modx_
Definition at line 64 of file SUBCOD.c.
#define nametb_1 nametb_
Definition at line 22 of file SUBCOD.c.
Referenced by subcod_().
#define range ((integer *)&sbscpt_1 + 1)
Referenced by subcod_().
#define rngpt ((integer *)&sbscpt_1)
Referenced by subcod_().
#define sbscpt_1 sbscpt_
Definition at line 52 of file SUBCOD.c.
#define stack ((integer *)&stklst_1 + 3)
Referenced by subcod_().
#define stklst_1 stklst_
Definition at line 34 of file SUBCOD.c.
#define subscr ((integer *)&modx_1 + 23)
Referenced by subcod_().
#define temp ((integer *)&code_1 + 32)
Referenced by subcod_().
#define tmp_1 tmp_
Definition at line 46 of file SUBCOD.c.
Referenced by subcod_().
#define top ((integer *)&stklst_1)
Referenced by subcod_().
#define vbl ((integer *)&code_1 + 60)
Referenced by subcod_().
Function Documentation
int subcod_ (integer * tpx)
Definition at line 108 of file SUBCOD.c.
References alarm_(), argcvt_(), c__1013, c__8, cvtsub, gettmp_(), i__, ierror, iftmp_(), ii, ilhlt, intmed, issfl, issmod, isstrm, j, m, mode_(), modhlf, modulo, n, nametb_1, onearg_(), opcode_(), puttmp_(), range, rlslin_(), rngpt, stack, subscr, temp, tmp_1, top, and vbl.
Referenced by recog_().
 {
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__, j, m, n, ii;
 #define vbl ((integer *)&code_1 + 60)
 #define top ((integer *)&stklst_1)
     extern integer mode_(integer *);
 #define temp ((integer *)&code_1 + 32)
     static integer rslt;
 #define range ((integer *)&sbscpt_1 + 1)
     extern /* Subroutine */ int alarm_(integer *, integer *, integer *, char *
         , ftnlen);
 #define stack ((integer *)&stklst_1 + 3)
 #define ilhlt ((logical *)&macxx1_1 + 13)
     extern logical iftmp_(integer *);
 #define issfl ((logical *)&isscom_1 + 5)
 #define rngpt ((integer *)&sbscpt_1)
 #define modhlf ((integer *)&moduli_1 + 1)
     extern /* Subroutine */ int opcode_(integer *), onearg_(integer *);
 #define intmed ((integer *)&macxx1_1 + 21)
     extern /* Subroutine */ int argcvt_(integer *);
 #define modulo ((integer *)&moduli_1)
 #define issmod ((integer *)&isscom_1 + 4)
 #define subscr ((integer *)&modx_1 + 23)
     extern integer gettmp_(integer *);
     extern /* Subroutine */ int rlslin_(void);
     static integer ierror;
 #define cvtsub ((integer *)&il_1 + 12)
 #define isstrm ((integer *)&isscom_1 + 7)
     extern /* Subroutine */ int puttmp_(integer *);
 /*              FUNCTION DECLARATION */
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
 /* CNAMTB:      NAME TABLE OR DICTIONARY */
 /* NAMMAX:      NAMTBL INDEX OF END OF THE PART PROGRAM NAME SECTION */
 /*        2.    STACK AND POINTER STORAGE */
 /* TOP:         POINTER TO LAST STACK ENTRY */
 /* STACK:       WORKING STACK */
 /*        3.    METALINGUISTIC VARIABLE CLASS CODES */
 /* TEMP:        (1)=CODE CLASS 17000,(2)=NAMTBL INDEX OF 'TEMP  ' */
 /* VBL:         (1)=CODE CLASS 31000,(2)=NAMTBL INDEX OF 'VBL   ' */
 /*        6.    GHOST STACK FOR OBJECT TIME TEMPORARY ALLOCATION */
 /*              LENGTH AND CURRENT NUMBER OF ACTIVE TEMPORARY STORAGE */
 /*       15.    ARRAY LIMIT STORAGE */
 /* RNGPT:       POINTER TO NEXT RANGE ENTRY */
 /* RANGE:       STORAGE FOR APT RESERVE STATEMENT INFORMATION */
 /*       16.    LITERALS FOR I. L. OPERATION CODES */
 /* CVTSUB:      CONTAINS COMMAND CODE (13) FOR CVTSUB COMMAND */
 /*       17.    MODE CODES */
 /* SUBSCR:      MODE CODE (24) FOR SUBSCRIPT */
 /*       22.    MACRO PROCESSING VARIABLES */
 /* ILHLT:       TRUE IF I.L. SHOULD NOT BE PLACED IN ILFILE */
 /* INTMED:      0=NO -,-1=INTERMEDIATE-,+1=FINAL MACRO PROCESSING */
 /*       29.    CLASS CODE MODULI */
 /* MODULO:      NAMTBL CLASS AND CODE FACTOR 1000 TO DEVIDE OUT CLASS */
 /* MODHLF:      NORMAL MODE CODE LIMIT 500 */
 /*       37.    INCLUSIVE SUBSCRIPT VARIABLES */
 /* ISSMOD:      MODE OF THE INCLUSIVE SUBSCRIPTED VARIABLE */
 /* ISSFL:       TRUE DURING INCLUSIVE SUBSCRIPT PROCESSING */
 /* ISSTRM:      SAVES THE STACK TOP ITEMS DURING SUBSCRIPT PROCESSING */
 /* * */
 /* ARGUMENTS    TPX       WORKING STACK (STACK) INDEX WHICH */
 /*                        POINTS TO THE VARIABLE NAME OF A */
 /* **                      SUBSCRIPTED VARIABLE. */
 /*     GET RESULT CELL */
     rslt = gettmp_(subscr);
     nametb_1.namtbl[rslt - 1] = temp[0] + *subscr;
 /*     FIND POSITION IN RANGE TABLE */
     if (*rngpt == 1) {
     goto L62;
     }
     j = *rngpt - 2;
     n = stack[(*tpx << 1) - 2];
     i__1 = j;
     for (i__ = 1; i__ <= i__1; i__ += 2) {
     if (range[i__ - 1] == n) {
         goto L20;
     }
 /* L10: */
     }
     goto L60;
 /*     GENERATE CODE */
 L20:
     ii = stack[(*tpx + 2 << 1) - 2];
     if (ii > nametb_1.nammax) {
     goto L30;
     }
     if (iftmp_(&ii)) {
     i__1 = nametb_1.namtbl[ii - 1] % *modulo;
     puttmp_(&i__1);
     }
 L30:
     i__ = mode_(&n);
     if (i__ == 0) {
     goto L65;
     }
     if (*issfl) {
     *issmod = i__;
     }
     opcode_(cvtsub);
     argcvt_(&rslt);
     argcvt_(&n);
     argcvt_(&stack[(*tpx + 2 << 1) - 2]);
     onearg_(&tmp_1.txxxx[(i__ << 1) - 2]);
     rlslin_();
 /* ...       MODIFY NAMTBL ENTRY TO MODE + 50 */
     nametb_1.namtbl[rslt - 1] = temp[0] + i__ + *modhlf;
 /*     MODIFY STACK */
     stack[(*tpx << 1) - 2] = rslt;
 L90:
     return 0;
 /*     ERROR */
 L60:
     if (*intmed < 0) {
     goto L61;
     } else if (*intmed == 0) {
     goto L62;
     } else {
     goto L63;
     }
 L61:
     *ilhlt = FALSE_;
     alarm_(&c__1013, tpx, &c__8, "SUBCOD  ", (ftnlen)8);
     *ilhlt = TRUE_;
     goto L72;
 L63:
     m = nametb_1.namtbl[n - 1];
     j = m / *modulo * *modulo;
     if (j == vbl[0] && m - j > *modhlf) {
     goto L20;
     }
 L62:
     ierror = 1013;
     goto L70;
 L65:
     ierror = 1014;
 L70:
     alarm_(&ierror, tpx, &c__8, "SUBCOD  ", (ftnlen)8);
 L72:
     if (! (*issfl)) {
     goto L90;
     }
     stack[(*top << 1) - 2] = isstrm[0];
     stack[(*top << 1) - 1] = isstrm[1];
     *issfl = FALSE_;
     goto L90;
 } /* subcod_ */
Variable Documentation
integer c__1013 = 1013 static
Definition at line 86 of file SUBCOD.c.
Referenced by subcod_().
integer c__8 = 8 static
Definition at line 87 of file SUBCOD.c.
Referenced by subcod_().
integer charnd
Definition at line 18 of file SUBCOD.c.
integer charst
Definition at line 18 of file SUBCOD.c.
char cnamtb[18000]
Definition at line 25 of file SUBCOD.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file SUBCOD.c.
integer code[150]
Definition at line 37 of file SUBCOD.c.
struct { ... } code_
integer ifixnd
Definition at line 18 of file SUBCOD.c.
integer ifixst
Definition at line 18 of file SUBCOD.c.
integer il[21]
Definition at line 55 of file SUBCOD.c.
struct { ... } il_
integer inamnd
Definition at line 18 of file SUBCOD.c.
integer inamst
Definition at line 18 of file SUBCOD.c.
integer isscom[9]
Definition at line 79 of file SUBCOD.c.
struct { ... } isscom_
integer macxx1[71]
Definition at line 67 of file SUBCOD.c.
struct { ... } macxx1_
integer moduli[2]
Definition at line 73 of file SUBCOD.c.
struct { ... } moduli_
integer modx[32]
Definition at line 61 of file SUBCOD.c.
struct { ... } modx_
integer namest
Definition at line 18 of file SUBCOD.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file SUBCOD.c.
integer namtbl[3000]
Definition at line 18 of file SUBCOD.c.
integer numbnd
Definition at line 18 of file SUBCOD.c.
integer numbst
Definition at line 18 of file SUBCOD.c.
integer sbscpt[101]
Definition at line 49 of file SUBCOD.c.
struct { ... } sbscpt_
integer stklst[300]
Definition at line 31 of file SUBCOD.c.
struct { ... } stklst_
struct { ... } tmp_
integer txxxx[64]
Definition at line 43 of file SUBCOD.c.