My Project: TAPOP.c File Reference
TAPOP.c File Reference
#include "f2c.h"
Macros
#define filtab_1 filtab_
#define ifiltb_1 ifiltb_
Functions
int tapop_ (integer *no, integer *n)
Variables
struct {
char filnam [480]
char filacc [300]
char filfmt [330]
char opstat [210]
char clstat [180]
} filtab_
struct {
integer u [30]
integer rl [30]
integer nxtrec [30]
integer lstrec [30]
} ifiltb_
static integer c__2 = 2
static integer c__35 = 35
static integer c__37 = 37
static integer c__40 = 40
static integer c__23 = 23
Macro Definition Documentation
#define filtab_1 filtab_
Definition at line 21 of file TAPOP.c.
Referenced by tapop_().
#define ifiltb_1 ifiltb_
Definition at line 27 of file TAPOP.c.
Referenced by tapop_().
Function Documentation
int tapop_ (integer * no, integer * n)
Definition at line 89 of file TAPOP.c.
References abnend_(), c__2, c__23, c__35, c__37, c__40, cform_(), cprint_(), darray, filopn_(), filtab_1, iconv_(), id, and ifiltb_1.
Referenced by abuftp_0_(), acntrl_(), apt094_(), apt108_(), apt298_(), apt301_(), apt313_(), atapop_0_(), fini_(), ieplog_(), init_(), mcxtrn_(), pocket_(), sprvis_0_(), and start_().
 {
     /* Initialized data */
     static char darray[80] = "                                              "
         "                                  ";
     /* System generated locals */
     integer i__1;
     cllist cl__1;
     alist al__1;
     inlist ioin__1;
     /* Builtin functions */
     integer f_clos(cllist *), f_inqu(inlist *), s_cmp(char *, char *, ftnlen,
         ftnlen), f_rew(alist *);
     /* Local variables */
     static integer id;
     static char iacc[12];
     static integer slen, posn;
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen), iconv_(integer *, char *, integer *, integer *,
         ftnlen), abnend_(void), filopn_(integer *), cprint_(char *,
         ftnlen);
 /*  *  FILE ATTRIBUTES  * */
     id = ifiltb_1.u[(0 + (0 + (*no - 1 << 2))) / 4];
     if (*n == -1) {
 /* ---- CLOSE FILE */
     cl__1.cerr = 1;
     cl__1.cunit = id;
     cl__1.csta = filtab_1.clstat + (*no - 1) * 6;
     i__1 = f_clos(&cl__1);
     if (i__1 != 0) {
         goto L91;
     }
 /* ---- OPEN FILE */
     filopn_(no);
     ifiltb_1.nxtrec[*no - 1] = 1;
     ifiltb_1.lstrec[*no - 1] = 0;
     } else if (*n == -2) {
     ioin__1.inerr = 0;
     ioin__1.inunit = id;
     ioin__1.infile = 0;
     ioin__1.inex = 0;
     ioin__1.inopen = 0;
     ioin__1.innum = 0;
     ioin__1.innamed = 0;
     ioin__1.inname = 0;
     ioin__1.inacclen = 12;
     ioin__1.inacc = iacc;
     ioin__1.inseq = 0;
     ioin__1.indir = 0;
     ioin__1.infmt = 0;
     ioin__1.inform = 0;
     ioin__1.inunf = 0;
     ioin__1.inrecl = 0;
     ioin__1.innrec = 0;
     ioin__1.inblank = 0;
     f_inqu(&ioin__1);
     if (s_cmp(iacc, "DIRECT", (ftnlen)12, (ftnlen)6) == 0) {
         ifiltb_1.nxtrec[*no - 1] = 1;
     } else {
         al__1.aerr = 0;
         al__1.aunit = id;
         f_rew(&al__1);
     }
     } else if (*n == -3) {
 /* ---- CLOSE FILE */
     cl__1.cerr = 1;
     cl__1.cunit = id;
     cl__1.csta = filtab_1.clstat + (*no - 1) * 6;
     i__1 = f_clos(&cl__1);
     if (i__1 != 0) {
         goto L91;
     }
     } else if (*n == -4) {
     ioin__1.inerr = 0;
     ioin__1.inunit = id;
     ioin__1.infile = 0;
     ioin__1.inex = 0;
     ioin__1.inopen = 0;
     ioin__1.innum = 0;
     ioin__1.innamed = 0;
     ioin__1.inname = 0;
     ioin__1.inacclen = 12;
     ioin__1.inacc = iacc;
     ioin__1.inseq = 0;
     ioin__1.indir = 0;
     ioin__1.infmt = 0;
     ioin__1.inform = 0;
     ioin__1.inunf = 0;
     ioin__1.inrecl = 0;
     ioin__1.innrec = 0;
     ioin__1.inblank = 0;
     f_inqu(&ioin__1);
     if (s_cmp(iacc, "DIRECT", (ftnlen)12, (ftnlen)6) == 0) {
         ifiltb_1.nxtrec[*no - 1] = 1;
     } else {
         al__1.aerr = 0;
         al__1.aunit = id;
         f_rew(&al__1);
     }
     } else if (*n == -5) {
     *n = ifiltb_1.lstrec[*no - 1] + 1;
     }
     return 0;
 /* L90: */
     slen = 0;
     cform_(" *** ERROR OPENING FILE :", darray, &c__2, &slen, (ftnlen)25, (
         ftnlen)80);
     posn = slen + 3;
     slen = 0;
     cform_(filtab_1.filnam + (*no - 1 << 4), darray, &posn, &slen, (ftnlen)16,
          (ftnlen)80);
     posn = posn + slen + 4;
     slen = 0;
     cform_("*** FROM ROUTINE: TAPOP", darray, &posn, &slen, (ftnlen)23, (
         ftnlen)80);
     cprint_(darray, (ftnlen)80);
     abnend_();
 L91:
     cform_(" *** ERROR CLOSING FORTRAN UNIT NO:", darray, &c__2, &c__35, (
         ftnlen)35, (ftnlen)80);
     iconv_(&ifiltb_1.u[*no - 1], darray, &c__37, &c__2, (ftnlen)80);
     cform_("*** FROM ROUTINE: TAPOP", darray, &c__40, &c__23, (ftnlen)23, (
         ftnlen)80);
     cprint_(darray, (ftnlen)80);
     return 0;
 } /* tapop_ */
Variable Documentation
integer c__2 = 2 static
Definition at line 31 of file TAPOP.c.
Referenced by tapop_().
integer c__23 = 23 static
Definition at line 35 of file TAPOP.c.
Referenced by tapop_().
integer c__35 = 35 static
Definition at line 32 of file TAPOP.c.
Referenced by tapop_().
integer c__37 = 37 static
Definition at line 33 of file TAPOP.c.
Referenced by tapop_().
integer c__40 = 40 static
Definition at line 34 of file TAPOP.c.
Referenced by tapop_().
char clstat[180]
Definition at line 18 of file TAPOP.c.
char filacc[300]
Definition at line 18 of file TAPOP.c.
char filfmt[330]
Definition at line 18 of file TAPOP.c.
char filnam[480]
Definition at line 18 of file TAPOP.c.
struct { ... } filtab_
struct { ... } ifiltb_
integer lstrec[30]
Definition at line 24 of file TAPOP.c.
integer nxtrec[30]
Definition at line 24 of file TAPOP.c.
char opstat[210]
Definition at line 18 of file TAPOP.c.
integer rl[30]
Definition at line 24 of file TAPOP.c.
integer u[30]
Definition at line 24 of file TAPOP.c.