My Project: TCSPHR.c File Reference
TCSPHR.c File Reference
#include "f2c.h"
Functions
int tcsphr_ (doublereal *te, doublereal *ta, doublereal *tul, doublereal *r__, doublereal *pside, doublereal *pthick, doublereal *tccent, doublereal *tcrad)
Function Documentation
int tcsphr_ (doublereal * te, doublereal * ta, doublereal * tul, doublereal * r__, doublereal * pside, doublereal * pthick, doublereal * tccent, doublereal * tcrad)
Definition at line 17 of file TCSPHR.c.
References cosa, dotf_(), i__, offset, r__, sina, ta, and te.
Referenced by avoid_(), and remscn_().
 {
     /* System generated locals */
     doublereal d__1;
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     static integer i__;
     static doublereal cosa, sina;
     extern /* Subroutine */ int dotf_(doublereal *, doublereal *, doublereal *
         );
     static doublereal offset;
 /*     PURPOSE: COMPUTE THE CENTRE AND RADIUS OF THE TOOL CONTACT SPHERE */
 /*     ARGUMENTS: */
 /*     TE      -  TOOL END COORDINATES */
 /*     TA      -  TOOL AXIS VECTOR */
 /*     TUL     -  TOOL GEOMETRY */
 /*     R       -  SURFACE CONTACT POINT AND DERIVATIVES */
 /*     PSIDE   -  1 OR -1 TO AJUST SURFACE NORMAL (RU X RV) */
 /*     PTHICK  -  THICKNESS OFFSET FROM SURFACE */
 /*     TCCENT  -  CENTRE OF TOOL CONTACT SPHERE */
 /*     TCRAD   -  RADIUS OF TOOL CONTACT SPHERE */
 /* .... LOCAL VARIABLES */
 /*     COSA    -  COSINE OF ANGLE BETWEEN SURFACE NORMAL AND TOOL AXIS */
 /*     SINA    -  SINE             (DITTO) */
 /*     OFFSET  -  POSITION OF CENTRE ALONG TA FROM TE */
     /* Parameter adjustments */
     --tccent;
     --r__;
     --tul;
     --ta;
     --te;
     /* Function Body */
     dotf_(&cosa, &r__[29], &ta[1]);
     if ((d__1 = 1. - cosa, abs(d__1)) <= 1e-6) {
 /* .... SN PARALLEL TO TA */
     for (i__ = 1; i__ <= 3; ++i__) {
         tccent[i__] = te[i__] + ta[i__] * 1e5;
 /* L10: */
     }
     *tcrad = 1e5;
     } else {
     sina = sqrt(1 - cosa * cosa);
 /* .... RADIUS = E/SINA + R */
     *tcrad = tul[3] / sina + tul[1];
 /* .... POSITION OF CENTRE ALONG TA FROM TE */
 /*            = F + (TCRAD-R)*COSA */
     offset = tul[4] + tul[1] + (*tcrad - tul[1]) * cosa;
     for (i__ = 1; i__ <= 3; ++i__) {
         tccent[i__] = te[i__] + offset * ta[i__];
 /* L20: */
     }
     }
     return 0;
 } /* tcsphr_ */