My Project: TEVAL.c File Reference
TEVAL.c File Reference
#include "f2c.h"
Macros
#define darray_1 darray_
Functions
int teval_ (char *name__, doublereal *trm, doublereal *data, ftnlen name_len)
Variables
struct {
char darray [120]
} darray_
static integer c__1 = 1
static integer c__8 = 8
Macro Definition Documentation
#define darray_1 darray_
Definition at line 21 of file TEVAL.c.
Referenced by teval_().
Function Documentation
int teval_ (char * name__, doublereal * trm, doublereal * data, ftnlen name_len)
Definition at line 30 of file TEVAL.c.
References abnend_(), c__1, c__8, cform_(), cprint_(), darray_1, tmdcs_(), ttorus_(), and tvdafs_().
Referenced by sstra_().
 {
     /* Builtin functions */
     integer s_cmp(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer slen, ipos;
     extern /* Subroutine */ int cform_(char *, char *, integer *, integer *,
         ftnlen, ftnlen), tmdcs_(doublereal *, doublereal *), abnend_(void)
         , tvdafs_(doublereal *, doublereal *), cprint_(char *, ftnlen),
         ttorus_(doublereal *, doublereal *);
 /*   ***  20.  DARRAY BLOCK  *** */
 /*   PRINT BUFFER */
     /* Parameter adjustments */
     --data;
     trm -= 5;
     /* Function Body */
     if (s_cmp(name__, "MDCS", (ftnlen)8, (ftnlen)4) == 0) {
     tmdcs_(&trm[5], &data[1]);
     } else if (s_cmp(name__, "TORUS", (ftnlen)8, (ftnlen)5) == 0) {
     ttorus_(&trm[5], &data[1]);
     } else if (s_cmp(name__, "VDAFS", (ftnlen)8, (ftnlen)5) == 0) {
     tvdafs_(&trm[5], &data[1]);
     } else {
     slen = 0;
     cform_("0 TRANSFORMATOR FOR NON-NATIVE SURFACE TYPE :",
         darray_1.darray, &c__1, &slen, (ftnlen)45, (ftnlen)120);
     ipos = slen + 2;
     cform_(name__, darray_1.darray, &ipos, &c__8, (ftnlen)8, (ftnlen)120);
     ipos += 10;
     slen = 0;
     cform_(": NOT AVAILABLE", darray_1.darray, &ipos, &slen, (ftnlen)15, (
         ftnlen)120);
     cprint_(darray_1.darray, (ftnlen)120);
     abnend_();
     }
     return 0;
 } /* teval_ */
Variable Documentation
integer c__1 = 1 static
Definition at line 25 of file TEVAL.c.
Referenced by teval_().
integer c__8 = 8 static
Definition at line 26 of file TEVAL.c.
Referenced by teval_().
char darray[120]
Definition at line 18 of file TEVAL.c.
struct { ... } darray_