My Project: TLCONV.c File Reference
TLCONV.c File Reference
#include "f2c.h"
Macros
#define ssprt_1 ssprt_
#define glflgs_1 glflgs_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define plgol_1 plgol_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int tlconv_ (void)
Variables
struct {
logical ssprt
logical sstest
} ssprt_
struct {
integer regflg
logical ringfg
integer motdir
integer iautog
} glflgs_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
integer iplgo [26]
integer jcseg
integer ncseg
integer icseg [10]
integer nlioci [10]
doublereal cosal [10]
doublereal sinal [10]
doublereal cuty [10]
doublereal cutx [10]
doublereal cutl [10]
doublereal vta [3]
} plgol_
static integer c__22218 = 22218
static integer c_n1 = -1
static integer c__0 = 0
static integer c__1 = 1
Macro Definition Documentation
#define charct_1 charct_
Definition at line 44 of file TLCONV.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
Referenced by tlconv_().
#define fxcor_1 fxcor_
Definition at line 38 of file TLCONV.c.
Referenced by tlconv_().
#define glflgs_1 glflgs_
Definition at line 29 of file TLCONV.c.
#define plgol_1 plgol_
Definition at line 58 of file TLCONV.c.
Referenced by tlconv_().
#define sinl ((doublereal *)&tlldat_1 + 8)
Referenced by tlconv_().
#define ssprt_1 ssprt_
Definition at line 21 of file TLCONV.c.
Referenced by tlconv_().
#define tlldat_1 tlldat_
Definition at line 51 of file TLCONV.c.
Referenced by tlconv_().
Function Documentation
int tlconv_ (void)
Definition at line 69 of file TLCONV.c.
References aerr_(), bad_(), c__0, c__1, c__22218, c_n1, cosl, cprint_(), fxcor_1, i__, j, n, plgol_1, record_(), sinl, ssprt_1, and tlldat_1.
Referenced by cutred_(), cutteh_(), and cuttes_().
 {
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     double sqrt(doublereal);
     /* Subroutine */ int s_copy(char *, char *, ftnlen, ftnlen);
     /* Local variables */
     static integer i__, j, n;
     extern /* Subroutine */ int bad_();
     static integer lioc;
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static integer nseq;
     static char badmsg[12];
     extern /* Subroutine */ int record_(integer *), cprint_(char *, ftnlen);
 /* ROUTINE WILL SET AND CONVERT TOOLDATA OF THE CUTTER */
 /*  CONTROL OF TEST-OUTPUT */
 /* .... GOLOFT FLAGS */
 /*     REGFLG:    REGION FLAG */
 /*     RINGFG:    RING CUTTER FLAG */
 /*     MOTDIR:    MOTION DIRECTION FLAG OF TLAXIS */
 /*     IAUTOG:    TLAXIS/...,AUTO FLAG */
 /*  COMMON FOR  >PLOTFT/GOLOFT< */
 /*  VALUES FOR  >PLOTFT/GOLOFT< */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*  USED CUTTER SEGMENT */
 /*  NUMBER OF VALID CUTTER SEGMENTS */
 /*  CUTTER SEGMENT IN TLLDAT ARRAYS */
 /*  NATURE OF SEGMENT */
 /*  COMPONENTS OF SEGMENT AND UNIT NORMAL POINTING INTO THE CUTTER */
 /*  DISTANCE PARALLEL TO THE CUTTER AXIS */
 /*  DISTANCE TO THE CUTTER AXIS */
 /*  ELEMENT LENGTH */
 /*  VECTOR COMPONENTS OF THE TOOL AXIS VECTOR */
 /* AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA */
 /*  THE FOLLOWING DATA ARE SET, IF CUTDAT(1).GE. 0.001: */
     if (fxcor_1.cutdat[0] < .001) {
     goto L999;
     }
     plgol_1.ncseg = 0;
     plgol_1.jcseg = 0;
 /* FIND THE NUMBER OF VALID SEGMENTS, ==> NCSEG */
     for (i__ = 0; i__ <= 7; ++i__) {
     if (tlldat_1.tcont[i__] != -1.) {
         goto L801;
     }
     n = i__ + 1;
     goto L802;
 L801:
     ;
     }
 L802:
     for (j = n; j <= 8; ++j) {
     if (tlldat_1.tcont[j] == 0.) {
         goto L800;
     }
     ++plgol_1.ncseg;
 /* NUMBER OF RELATET SEGMENT IN TLLDAT */
     plgol_1.icseg[plgol_1.ncseg - 1] = j;
 /* SEGMENT LINE OR CIRCLE */
     plgol_1.nlioci[plgol_1.ncseg - 1] = (integer) tlldat_1.tlinc[j];
     if (tlldat_1.tlinc[j] != 0.) {
         goto L10;
     }
 /* SEGMENT IS AN ARC (CIRCLE) */
     if (tlldat_1.tanhi[j - 1] > -1e38) {
         goto L11;
     }
     plgol_1.sinal[plgol_1.ncseg - 1] = 0.;
     goto L12;
 L11:
     plgol_1.sinal[plgol_1.ncseg - 1] = 1. / sqrt(tlldat_1.tanhi[j - 1] *
         tlldat_1.tanhi[j - 1] + 1.);
 L12:
     if (tlldat_1.tanhi[j - 1] > -1e38) {
         goto L13;
     }
     plgol_1.cosal[plgol_1.ncseg - 1] = -1.;
     goto L14;
 L13:
     plgol_1.cosal[plgol_1.ncseg - 1] = tlldat_1.tanhi[j - 1] *
         plgol_1.sinal[plgol_1.ncseg - 1];
 L14:
     plgol_1.cuty[plgol_1.ncseg - 1] = tlldat_1.tlhite[j - 1];
     plgol_1.cutx[plgol_1.ncseg - 1] = tlldat_1.ri[j - 1];
     plgol_1.cutl[plgol_1.ncseg - 1] = tlldat_1.corrad[j - 1];
     goto L800;
 L10:
     if (tlldat_1.tlinc[j] != 1.) {
         goto L20;
     }
 /* SEGMENT IS A LINE */
     plgol_1.sinal[plgol_1.ncseg - 1] = sinl[j - 1];
     plgol_1.cosal[plgol_1.ncseg - 1] = cosl[j - 1];
     plgol_1.cuty[plgol_1.ncseg - 1] = tlldat_1.tlhite[j - 1];
     plgol_1.cutx[plgol_1.ncseg - 1] = tlldat_1.ri[j - 1];
     plgol_1.cutl[plgol_1.ncseg - 1] = tlldat_1.umax[j - 1];
     goto L800;
 /* WRONG DATA IN TLINC, VALUE NOT LINE OR NOT CIRCLE */
 L20:
     aerr_(&c__22218, "TLCONV  ", (ftnlen)8);
 L800:
     ;
     }
 /* TEST PRINT-OUT OF THE CONVERTET AND CALCUALTED VALUES */
     if (! ssprt_1.sstest) {
     goto L999;
     }
     record_(&nseq);
     s_copy(badmsg, " NEW CUTTER:", (ftnlen)12, (ftnlen)12);
     cprint_(badmsg, (ftnlen)12);
     bad_(&c_n1, &c__0, "ISN ", &nseq, (ftnlen)4);
     i__1 = plgol_1.ncseg;
     for (i__ = 1; i__ <= i__1; ++i__) {
     lioc = plgol_1.nlioci[i__ - 1];
     bad_(&c__1, &c__0, "LIOC", &lioc, (ftnlen)4);
     bad_(&c__1, &c__1, "COAL", &plgol_1.cosal[i__ - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "SIAL", &plgol_1.sinal[i__ - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "CUTY", &plgol_1.cuty[i__ - 1], (ftnlen)4);
     bad_(&c__1, &c__1, "CUTX", &plgol_1.cutx[i__ - 1], (ftnlen)4);
     bad_(&c_n1, &c__1, "CUTL", &plgol_1.cutl[i__ - 1], (ftnlen)4);
 /* L808: */
     }
 L999:
     return 0;
 } /* tlconv_ */
Variable Documentation
doublereal alp
Definition at line 32 of file TLCONV.c.
doublereal ax4[3]
Definition at line 32 of file TLCONV.c.
integer c__0 = 0 static
Definition at line 64 of file TLCONV.c.
Referenced by tlconv_().
integer c__1 = 1 static
Definition at line 65 of file TLCONV.c.
Referenced by tlconv_().
integer c__22218 = 22218 static
Definition at line 62 of file TLCONV.c.
Referenced by tlconv_().
integer c_n1 = -1 static
Definition at line 63 of file TLCONV.c.
Referenced by tlconv_().
doublereal cagl
Definition at line 32 of file TLCONV.c.
struct { ... } charct_
doublereal corrad[8]
Definition at line 47 of file TLCONV.c.
doublereal cosal[10]
Definition at line 55 of file TLCONV.c.
doublereal cutdat[7]
Definition at line 32 of file TLCONV.c.
doublereal cutl[10]
Definition at line 55 of file TLCONV.c.
doublereal cutx[10]
Definition at line 55 of file TLCONV.c.
doublereal cuty[10]
Definition at line 55 of file TLCONV.c.
doublereal dpmax
Definition at line 32 of file TLCONV.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 32 of file TLCONV.c.
struct { ... } glflgs_
doublereal hi
Definition at line 32 of file TLCONV.c.
integer iautog
Definition at line 26 of file TLCONV.c.
integer icseg[10]
Definition at line 54 of file TLCONV.c.
integer iplgo[26]
Definition at line 54 of file TLCONV.c.
integer jcseg
Definition at line 54 of file TLCONV.c.
char modfer[6]
Definition at line 41 of file TLCONV.c.
integer motdir
Definition at line 26 of file TLCONV.c.
integer ncseg
Definition at line 54 of file TLCONV.c.
integer nlioci[10]
Definition at line 54 of file TLCONV.c.
struct { ... } plgol_
doublereal pmove[3]
Definition at line 32 of file TLCONV.c.
doublereal ra
Definition at line 32 of file TLCONV.c.
doublereal rc1
Definition at line 32 of file TLCONV.c.
integer regflg
Definition at line 24 of file TLCONV.c.
doublereal ri[8]
Definition at line 47 of file TLCONV.c.
logical ringfg
Definition at line 25 of file TLCONV.c.
doublereal sagl
Definition at line 32 of file TLCONV.c.
doublereal sinal[10]
Definition at line 55 of file TLCONV.c.
logical ssprt
Definition at line 18 of file TLCONV.c.
struct { ... } ssprt_
logical sstest
Definition at line 18 of file TLCONV.c.
doublereal strtno
Definition at line 32 of file TLCONV.c.
doublereal surd
Definition at line 32 of file TLCONV.c.
doublereal ta[3]
Definition at line 32 of file TLCONV.c.
doublereal tak[3]
Definition at line 32 of file TLCONV.c.
doublereal tal[3]
Definition at line 32 of file TLCONV.c.
doublereal tanhi[8]
Definition at line 47 of file TLCONV.c.
doublereal tanlo[8]
Definition at line 47 of file TLCONV.c.
doublereal tcont[9]
Definition at line 47 of file TLCONV.c.
doublereal te[3]
Definition at line 32 of file TLCONV.c.
doublereal tek[3]
Definition at line 32 of file TLCONV.c.
doublereal tel[3]
Definition at line 32 of file TLCONV.c.
doublereal tem[10]
Definition at line 32 of file TLCONV.c.
doublereal temp[24]
Definition at line 32 of file TLCONV.c.
doublereal ti[3]
Definition at line 32 of file TLCONV.c.
doublereal tik[3]
Definition at line 32 of file TLCONV.c.
doublereal til[3]
Definition at line 32 of file TLCONV.c.
doublereal tlhit
Definition at line 32 of file TLCONV.c.
doublereal tlhite[8]
Definition at line 47 of file TLCONV.c.
doublereal tlinc[9]
Definition at line 47 of file TLCONV.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 32 of file TLCONV.c.
doublereal umax[8]
Definition at line 47 of file TLCONV.c.
doublereal vta[3]
Definition at line 55 of file TLCONV.c.
doublereal vtem
Definition at line 32 of file TLCONV.c.