My Project: TLLFT.c File Reference
TLLFT.c File Reference
#include "f2c.h"
Macros
#define ldef_1 ldef_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
Functions
int tllft_ (void)
int tlrgt_ (void)
int tlon_ (void)
int tlonps_ (void)
int tlofps_ (void)
Variables
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
Macro Definition Documentation
#define ifxcor_1 ifxcor_
Definition at line 48 of file TLLFT.c.
Referenced by tllft_(), tlofps_(), tlon_(), tlonps_(), and tlrgt_().
#define isv1_1 isv1_
Definition at line 38 of file TLLFT.c.
#define isv_1 isv_
Definition at line 31 of file TLLFT.c.
Referenced by tllft_(), tlofps_(), tlon_(), tlonps_(), and tlrgt_().
#define ldef_1 ldef_
Definition at line 22 of file TLLFT.c.
Function Documentation
int tllft_ (void)
Definition at line 56 of file TLLFT.c.
References i__, ifxcor_1, isv_1, j, k, and l.
Referenced by xcall_().
 {
     static integer i__, j, k, l;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /* .... TOOL IS LEFT OF DS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
     i__ = 1;
     j = 1;
     k = 1;
     l = ifxcor_1.ids;
     ifxcor_1.motmod = i__;
     isv_1.isftyp[l - 1] = j;
     if (isv_1.itlon[l - 1] == k) {
     goto L10;
     }
     isv_1.itlon[l - 1] = k;
     isv_1.jent[l - 1] = 1;
 L10:
     return 0;
 } /* tllft_ */
int tlofps_ (void)
Definition at line 305 of file TLLFT.c.
References ifxcor_1, isv_1, j, k, and l.
Referenced by xcall_().
 {
     static integer j, k, l;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /* .... TOOL IS TANGENT TO PS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
     j = 1;
     k = 1;
     l = ifxcor_1.ips;
     isv_1.isftyp[l - 1] = j;
     if (isv_1.itlon[l - 1] == k) {
     goto L10;
     }
     isv_1.itlon[l - 1] = k;
     isv_1.jent[l - 1] = 1;
 L10:
     return 0;
 } /* tlofps_ */
int tlon_ (void)
Definition at line 181 of file TLLFT.c.
References i__, ifxcor_1, isv_1, j, k, and l.
Referenced by xcall_().
 {
     static integer i__, j, k, l;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /* .... TOOL END IS ON DS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
     i__ = 3;
     j = 3;
     k = 0;
     l = ifxcor_1.ids;
     ifxcor_1.motmod = i__;
     isv_1.isftyp[l - 1] = j;
     if (isv_1.itlon[l - 1] == k) {
     goto L10;
     }
     isv_1.itlon[l - 1] = k;
     isv_1.jent[l - 1] = 1;
 L10:
     return 0;
 } /* tlon_ */
int tlonps_ (void)
Definition at line 244 of file TLLFT.c.
References ifxcor_1, isv_1, j, k, and l.
Referenced by xcall_().
 {
     static integer j, k, l;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /* .... TOOL END IS ON PS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
     j = 3;
     k = 0;
     l = ifxcor_1.ips;
     isv_1.isftyp[l - 1] = j;
     if (isv_1.itlon[l - 1] == k) {
     goto L10;
     }
     isv_1.itlon[l - 1] = k;
     isv_1.jent[l - 1] = 1;
 L10:
     return 0;
 } /* tlonps_ */
int tlrgt_ (void)
Definition at line 118 of file TLLFT.c.
References i__, ifxcor_1, isv_1, j, k, and l.
Referenced by xcall_().
 {
     static integer i__, j, k, l;
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /* .... TOOL IS RIGHT OF DS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
     i__ = 2;
     j = 1;
     k = 1;
     l = ifxcor_1.ids;
     ifxcor_1.motmod = i__;
     isv_1.isftyp[l - 1] = j;
     if (isv_1.itlon[l - 1] == k) {
     goto L10;
     }
     isv_1.itlon[l - 1] = k;
     isv_1.jent[l - 1] = 1;
 L10:
     return 0;
 } /* tlrgt_ */
Variable Documentation
logical altmlt
Definition at line 18 of file TLLFT.c.
logical bnderr
Definition at line 18 of file TLLFT.c.
logical boundf
Definition at line 18 of file TLLFT.c.
logical canflg
Definition at line 18 of file TLLFT.c.
integer i3dflg
Definition at line 41 of file TLLFT.c.
integer iaerr
Definition at line 41 of file TLLFT.c.
integer iafl[5]
Definition at line 25 of file TLLFT.c.
integer iautps
Definition at line 41 of file TLLFT.c.
integer ibegin
Definition at line 41 of file TLLFT.c.
integer ic
Definition at line 41 of file TLLFT.c.
integer icanon[5]
Definition at line 25 of file TLLFT.c.
integer icheck
Definition at line 41 of file TLLFT.c.
integer icl
Definition at line 41 of file TLLFT.c.
integer ics
Definition at line 41 of file TLLFT.c.
integer icscnt
Definition at line 41 of file TLLFT.c.
integer ictdef
Definition at line 41 of file TLLFT.c.
integer icut
Definition at line 41 of file TLLFT.c.
integer ids
Definition at line 41 of file TLLFT.c.
integer ier
Definition at line 41 of file TLLFT.c.
integer ifar[5]
Definition at line 34 of file TLLFT.c.
integer ifl4[5]
Definition at line 34 of file TLLFT.c.
struct { ... } ifxcor_
integer igo
Definition at line 41 of file TLLFT.c.
integer igoto
Definition at line 41 of file TLLFT.c.
integer igoug
Definition at line 41 of file TLLFT.c.
integer igs
Definition at line 41 of file TLLFT.c.
integer index[5]
Definition at line 25 of file TLLFT.c.
integer indir__[5]
Definition at line 25 of file TLLFT.c.
integer inops
Definition at line 41 of file TLLFT.c.
integer iop[5]
Definition at line 25 of file TLLFT.c.
integer iopset[5]
Definition at line 25 of file TLLFT.c.
integer ipl[5]
Definition at line 25 of file TLLFT.c.
integer ips
Definition at line 41 of file TLLFT.c.
integer ipsdef
Definition at line 41 of file TLLFT.c.
integer ipt1
Definition at line 41 of file TLLFT.c.
integer is
Definition at line 41 of file TLLFT.c.
integer iseg
Definition at line 41 of file TLLFT.c.
integer iseqno
Definition at line 41 of file TLLFT.c.
integer isfidn[5]
Definition at line 25 of file TLLFT.c.
integer isftyp[5]
Definition at line 25 of file TLLFT.c.
integer isigcr[5]
Definition at line 25 of file TLLFT.c.
integer isrch
Definition at line 41 of file TLLFT.c.
integer istrup
Definition at line 41 of file TLLFT.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 25 of file TLLFT.c.
integer it
Definition at line 41 of file TLLFT.c.
integer itlon[5]
Definition at line 25 of file TLLFT.c.
integer itseg[5]
Definition at line 25 of file TLLFT.c.
integer itsegk[5]
Definition at line 25 of file TLLFT.c.
integer iunfl[5]
Definition at line 25 of file TLLFT.c.
integer j20[5]
Definition at line 34 of file TLLFT.c.
integer j21[5]
Definition at line 34 of file TLLFT.c.
integer j22[5]
Definition at line 34 of file TLLFT.c.
integer j23[5]
Definition at line 34 of file TLLFT.c.
integer j50[5]
Definition at line 34 of file TLLFT.c.
integer j51[5]
Definition at line 34 of file TLLFT.c.
integer jbr
Definition at line 41 of file TLLFT.c.
logical jcs
Definition at line 18 of file TLLFT.c.
logical jds
Definition at line 18 of file TLLFT.c.
integer jent[5]
Definition at line 25 of file TLLFT.c.
integer jiops[5]
Definition at line 25 of file TLLFT.c.
integer jph[5]
Definition at line 34 of file TLLFT.c.
integer jsw
Definition at line 41 of file TLLFT.c.
integer jtlflg[5]
Definition at line 25 of file TLLFT.c.
integer jtn[5]
Definition at line 25 of file TLLFT.c.
integer ju1[5]
Definition at line 25 of file TLLFT.c.
struct { ... } ldef_
integer limfl[5]
Definition at line 25 of file TLLFT.c.
integer lsv
Definition at line 41 of file TLLFT.c.
integer lsv1
Definition at line 41 of file TLLFT.c.
integer mantax
Definition at line 41 of file TLLFT.c.
integer motmod
Definition at line 41 of file TLLFT.c.
integer msav
Definition at line 41 of file TLLFT.c.
integer mulout
Definition at line 41 of file TLLFT.c.
integer nmbseg
Definition at line 41 of file TLLFT.c.
integer nmpnts
Definition at line 41 of file TLLFT.c.
integer notan[5]
Definition at line 34 of file TLLFT.c.
integer nrec
Definition at line 41 of file TLLFT.c.
integer numax
Definition at line 41 of file TLLFT.c.
integer numcnt
Definition at line 41 of file TLLFT.c.
integer nump
Definition at line 41 of file TLLFT.c.
integer numpt1
Definition at line 41 of file TLLFT.c.
integer numsfs
Definition at line 41 of file TLLFT.c.
integer numsur
Definition at line 41 of file TLLFT.c.
integer nw
Definition at line 41 of file TLLFT.c.
integer nwds
Definition at line 41 of file TLLFT.c.
logical pchlst
Definition at line 18 of file TLLFT.c.
logical prnton
Definition at line 18 of file TLLFT.c.
logical refflg
Definition at line 18 of file TLLFT.c.
logical refmot
Definition at line 18 of file TLLFT.c.
logical subflg
Definition at line 18 of file TLLFT.c.
logical tabprt
Definition at line 18 of file TLLFT.c.
logical unflag
Definition at line 18 of file TLLFT.c.
logical zflag
Definition at line 18 of file TLLFT.c.