My Project: TLNORM.c File Reference
TLNORM.c File Reference
#include "f2c.h"
Macros
#define dshar4_1 dshar4_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define znumbr_1 znumbr_
#define _BLNK__1 _BLNK__
#define chekfl_1 chekfl_
#define modess_1 modess_
#define can ((doublereal *)&_BLNK__1 + 40)
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
Functions
int tlnorm_ (doublereal *u1var)
Variables
struct {
doublereal a
doublereal b
doublereal c__
doublereal cendis
doublereal cmove [3]
doublereal com1
doublereal com4
doublereal dir [3]
doublereal dp
doublereal dpe
doublereal dpcnt
doublereal dpi
doublereal dpl
doublereal dp1
doublereal d1
doublereal d2a
doublereal flipck
doublereal fwd [3]
doublereal ogle [3]
doublereal p1 [3]
doublereal p2 [3]
doublereal rdrn
doublereal refpnt [3]
doublereal tangl
doublereal tes [3]
doublereal tew [3]
doublereal uvec [3]
doublereal u2 [3]
doublereal v [3]
doublereal vl
doublereal zl
doublereal zlnorm [3]
doublereal zlpnt [3]
doublereal zl1
doublereal param [6]
doublereal r__ [6]
doublereal savpar [4]
doublereal seg [9]
doublereal slope
doublereal sqroot
doublereal unn
doublereal upp
doublereal vint
doublereal vnn
doublereal vpp
} dshar4_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
doublereal com [36000]
} _BLNK__
struct {
integer ichekf
} chekfl_
struct {
integer modess
integer msschk
integer mssarl
} modess_
static integer c__26601 = 26601
static integer c_b63 = -26002
static integer c__26602 = 26602
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 113 of file TLNORM.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define charct_1 charct_
Definition at line 40 of file TLNORM.c.
#define chekfl_1 chekfl_
Definition at line 119 of file TLNORM.c.
Referenced by tlnorm_().
#define cosl ((doublereal *)&tlldat_1 + 16)
Referenced by tlnorm_().
#define dshar4_1 dshar4_
Definition at line 25 of file TLNORM.c.
Referenced by tlnorm_().
#define fxcor_1 fxcor_
Definition at line 34 of file TLNORM.c.
Referenced by tlnorm_().
#define ifxcor_1 ifxcor_
Definition at line 99 of file TLNORM.c.
Referenced by tlnorm_().
#define isv1_1 isv1_
Definition at line 89 of file TLNORM.c.
#define isv_1 isv_
Definition at line 82 of file TLNORM.c.
Referenced by tlnorm_().
#define modess_1 modess_
Definition at line 125 of file TLNORM.c.
Referenced by tlnorm_().
#define sinl ((doublereal *)&tlldat_1 + 8)
Referenced by tlnorm_().
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define sv1_1 sv1_
Definition at line 73 of file TLNORM.c.
Referenced by tlnorm_().
#define sv_1 sv_
Definition at line 64 of file TLNORM.c.
Referenced by tlnorm_().
#define tlldat_1 tlldat_
Definition at line 47 of file TLNORM.c.
Referenced by tlnorm_().
#define znumbr_1 znumbr_
Definition at line 107 of file TLNORM.c.
Referenced by tlnorm_().
Function Documentation
int tlnorm_ (doublereal * u1var)
Definition at line 137 of file TLNORM.c.
References aerr_(), ajundd_(), c__26601, c__26602, c_b63, ccurv_(), chekfl_1, cosl, ddst_(), dotf_(), dshar4_1, error_(), fxcor_1, i__, ifxcor_1, isv_1, jfind, ll, modess_1, nnn, one, sinl, sv1_1, sv_1, tlldat_1, vnorm_(), w1, zero, and znumbr_1.
Referenced by amind_(), and cplan_().
 {
     /* Initialized data */
     static doublereal z5em3 = .005;
     static doublereal z5em4 = 5e-4;
     static doublereal z700 = 700.;
     static doublereal z9999 = .9999;
     static doublereal z995 = .995;
     static doublereal zbig2 = 1e20;
     static doublereal zero = 0.;
     static doublereal one = 1.;
     static doublereal zbig = 1e30;
     static doublereal z4 = 4.;
     static doublereal z3em4 = 3e-4;
     /* System generated locals */
     doublereal d__1;
     /* Builtin functions */
     double sqrt(doublereal), d_sign(doublereal *, doublereal *);
     /* Local variables */
     static integer i__;
     static doublereal w1, w2;
     static integer ll, iw;
     static doublereal w11, am;
     static integer ibb;
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer nnn;
     static doublereal rrr, wfl1, wfl2;
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen), dotf_(
         doublereal *, doublereal *, doublereal *);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static integer itry;
     extern /* Subroutine */ int ddst_(void);
     static integer jfind;
 #define canon ((doublereal *)&_BLNK__1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     static doublereal tnold[3], tpold[3], snold[3], spold[3];
     extern /* Subroutine */ int vnorm_(doublereal *, doublereal *), error_(
         integer *, char *, ftnlen), ccurv_(integer *, doublereal *,
         doublereal *, doublereal *);
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
     extern /* Subroutine */ int ajundd_(void);
     static doublereal tpspdf[3];
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  4.  DSHARE BLOCK 4  *** */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /* ---- FLAG INTRODUCED BY VW - USED TO DETERMINE 'CORRECT' SIDE OF CUTTER */
     /* Parameter adjustments */
     --u1var;
     /* Function Body */
 /* ----------------------------------------------------------- */
 /*             /-JFIND IS -1 WHEN AT LEAST ONE TOOL SEG HAS LINED UP */
 /*             /-WITH THE CENTER OF CURVATURE */
 /*             /-IBB=-1 FOR 1ST PASS THRU TLNORM, =0 ON SECOND PASS */
     jfind = 1;
     ibb = -1;
 L805:
 /*              /-IT IS TOOL SEGMENT INDEX  =1 AT TIP,2,3,4 ETC */
 /*              /-IT=7 IS LAST SEGMENT, =8 IS DISC. IBEGIN IS FIRST */
 /*              /-SIGNIFICANT TOOL SEGMENT. */
     ifxcor_1.it = ifxcor_1.ibegin;
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L12: */
     dshar4_1.uvec[i__ - 1] = u1var[i__];
     }
     if (modess_1.msschk == 1) {
     goto L3029;
     }
 /* ----------------------------------------------------------- */
 /*              /-TEST FOR ROUTE */
 /*              /-ITLON IS 0 IF TOOL ON SURF, 1 OTHERWISE */
     if (isv_1.itlon[ifxcor_1.is - 1] == 0) {
     goto L1;
     }
 /*              /-IAFL=-1, GENERAL SURF, 0 PLANE PERP TO TA, 1 CYL LL TA */
 /*              /-JTLFLG=0 FOR NORMAL CUTTER, =1 FOR DISC TYPE. */
     iw = isv_1.iafl[ifxcor_1.is - 1] + isv_1.jtlflg[ifxcor_1.is - 1];
 /*              /-IAFL,JTLFLG = 0,1,  1,1,  OR 1,0 */
     if (iw > 0) {
     goto L401;
     }
 /*              /-IAFL,JTLFLG = -1,1, 0,0 */
     if (iw == 0) {
     goto L404;
     }
 /*              /-IAFL=-1,JTLFLG=0 */
     if (ifxcor_1.ipt1 != 0) {
     goto L84;
     }
     goto L1;
 /*              /-TA LL TO SURFACE ELEMENT */
 L401:
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] = fxcor_1.te[i__ - 1] +
         sv_1.toolwd[ifxcor_1.is - 1] * dshar4_1.uvec[i__ - 1] +
         sv_1.toolht[i__ + ifxcor_1.is * 3 - 4];
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = dshar4_1.uvec[i__ - 1];
 /* L402: */
     }
 /*              /-TP,TN FOUND, RETURN TO CALLING PROGRAM */
     goto L9999;
 /*              /-CASE OF POINT CUTTER */
 L1:
 /*              /-TEMP(1) IS +OR-1 TO SELECT CUTTER SIDE */
 /*              /-TEMP(2) IS 0 OR 1 */
     fxcor_1.temp[1] = zero;
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L21: */
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] = fxcor_1.te[i__ - 1];
     }
     isv_1.itseg[ifxcor_1.is - 1] = 1;
     goto L408;
 /* ----------------------------------------------------------- */
 /*              /-TLON, POINT TOOL, 5-AXIS RING ROUTES */
 L404:
     if (tlldat_1.ri[7] == zero) {
     goto L406;
     }
     fxcor_1.temp[0] = -one;
     fxcor_1.temp[1] = one;
     goto L407;
 L406:
     fxcor_1.temp[1] = zero;
 L407:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L405: */
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] = fxcor_1.te[i__ - 1] +
         tlldat_1.tlhite[7] * fxcor_1.ta[i__ - 1] + fxcor_1.temp[0] *
         tlldat_1.ri[7] * dshar4_1.uvec[i__ - 1];
     }
     isv_1.itseg[ifxcor_1.is - 1] = 8;
 L408:
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = sv_1.cc[i__ + ifxcor_1.is * 3 -
         4] - sv_1.tp[i__ + ifxcor_1.is * 3 - 4];
 /* L2: */
     }
 /*              /-LL MAY BE 3,4 OR 5 */
     ll = (integer) (fxcor_1.temp[0] * fxcor_1.temp[1] + z4);
     vnorm_(&sv_1.tn[ifxcor_1.is * 3 - 3], &sv_1.tn[ifxcor_1.is * 3 - 3]);
     if (ifxcor_1.ier == 0) {
     goto L8;
     }
 /* **** ERROR EXIT, TN CANNOT BE FOUND */
 L3:
     if (fxcor_1.temp[1] > zero) {
     goto L410;
     }
     aerr_(&c__26601, "TLNORM  ", (ftnlen)8);
     goto L9999;
 L410:
     fxcor_1.temp[ll - 1] = -one;
 L417:
     if (fxcor_1.temp[0] >= zero) {
     goto L418;
     }
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.temp[i__ + 4] = sv_1.tn[i__ + ifxcor_1.is * 3 - 4];
 /* L503: */
     fxcor_1.temp[i__ + 7] = sv_1.tp[i__ + ifxcor_1.is * 3 - 4];
     }
     fxcor_1.temp[0] = one;
     goto L407;
 L418:
     if (fxcor_1.temp[4] >= fxcor_1.temp[2]) {
     goto L505;
     }
 /*              /-TEMP(5) IS LT TEMP(3) */
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = fxcor_1.temp[i__ + 4];
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] = fxcor_1.temp[i__ + 7];
 /* L506: */
     }
 L505:
 /*              /-JTLFLG NE 1 MEANS IGNORE DISC CUTTER */
     if (isv_1.jtlflg[ifxcor_1.is - 1] != 1) {
     goto L9999;
     }
     if (isv_1.ipl[ifxcor_1.is - 1] != 1) {
     goto L9999;
     }
 /*              /-PLANAR SURFACE CASE */
     dotf_(&w1, fxcor_1.ta, &sv_1.sn[ifxcor_1.is * 3 - 3]);
     if (abs(w1) < z995) {
     goto L9999;
     }
 /*              /-SN AND TA ARE CLOSE, LOOK FURTHER */
     if (isv_1.jtn[ifxcor_1.is - 1] > 0) {
     goto L9999;
     }
 /*              /-SURFACE IS DS OR PS, CONTINUE */
     goto L413;
 L8:
     if (fxcor_1.temp[1] > zero) {
     goto L412;
     }
 /*              /-TEMP(2) IS LE ZERO */
     if (isv_1.jtn[ifxcor_1.is - 1] > 0) {
     goto L414;
     }
 L413:
 /*              /-JTN(IS) IS ZERO, NORMAL PS OR DS SURFACE */
     dotf_(&w1, &sv_1.sn[ifxcor_1.is * 3 - 3], &sv_1.tn[ifxcor_1.is * 3 - 3]);
 /*              /- WHEN TN AND SN ARE OPPOSED, FINISH */
     if (w1 <= zero) {
     goto L9999;
     }
 /*              /-ELSE CHECK FURTHER */
     goto L340;
 L414:
 /*              /-JTN NOT ZERO, CHECK SURFACE, TN CONTROL */
     dotf_(&w1, &sv_1.tn[ifxcor_1.is * 3 - 3], &sv1_1.tnl[ifxcor_1.is * 3 - 3])
         ;
 /*              /-LAST TWO TNS ALIGNED, THEN QUIT */
     if (w1 > zero) {
     goto L9999;
     }
     if (w1 < zero) {
     goto L340;
     }
 /*              /-CHECK FURTHER IF TN PERPEN TO TNL */
     dotf_(&w1, &sv_1.tn[ifxcor_1.is * 3 - 3], &sv_1.sn[ifxcor_1.is * 3 - 3]);
     if (w1 >= zero) {
     goto L9999;
     }
 L340:
 /*              /-REVERSE TN AND THEN TERMINATE */
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = -sv_1.tn[i__ + ifxcor_1.is * 3 -
         4];
 /* L341: */
     }
     goto L9999;
 L412:
     dotf_(&w1, &sv_1.tn[ifxcor_1.is * 3 - 3], dshar4_1.uvec);
     if (fxcor_1.temp[0] * w1 >= zero) {
     goto L502;
     }
 /*              /-REVERSE TN */
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = -sv_1.tn[i__ + ifxcor_1.is * 3 -
         4];
 /* L501: */
     }
 L502:
     if (isv_1.jtn[ifxcor_1.is - 1] <= 0) {
     dotf_(&w1, &sv_1.tn[ifxcor_1.is * 3 - 3], &sv_1.sn[ifxcor_1.is * 3 -
         3]);
     }
     if (isv_1.jtn[ifxcor_1.is - 1] <= 0) {
     fxcor_1.temp[ll - 1] = -w1;
     }
     if (isv_1.jtn[ifxcor_1.is - 1] > 0) {
     dotf_(&fxcor_1.temp[ll - 1], &sv_1.tn[ifxcor_1.is * 3 - 3], &
         sv1_1.tnl[ifxcor_1.is * 3 - 3]);
     }
     goto L417;
 /* ----------------------------------------------------------- */
 /*              /-START NORMAL ROUTE. SPECIAL PATH FOR END TOOL */
 L84:
     tlldat_1.tcont[8] = -one;
     nnn = 1;
     if (isv_1.jtn[ifxcor_1.is - 1] == 0) {
     ifxcor_1.it = isv_1.itseg[ifxcor_1.is - 1];
     }
 /* .... CONSIDER PRECEDING AS WELL AS CURRENT AND FOLLOWING TOOL SEGMENTS */
     if (ifxcor_1.it >= 4) {
     ifxcor_1.it += -2;
     }
     dshar4_1.cendis = zbig;
     wfl1 = zero;
     ifxcor_1.it -= nnn;
 /*              /-INCREMENT TOOL SEGMENT, TRY AGAIN */
 L2000:
     ifxcor_1.it += nnn;
 /*              /-TCONT=0 MEANS SEGMENT INSIGNIFICANT */
     if (tlldat_1.tcont[ifxcor_1.it] == zero) {
     goto L2000;
     }
 /*              /-TCONT=-1 MEANS ALL SEGS OF TOOL DONE, SELECT TN. */
     if (tlldat_1.tcont[ifxcor_1.it] >= zero) {
     goto L700;
     }
 /*              /-END OF TOOL.  ONLY ONE POSSIBLE TN. */
     if (jfind <= 0) {
     goto L9999;
     }
     fxcor_1.temp[0] = (doublereal) ((isv_1.jtn[ifxcor_1.is - 1] << 1) - 1);
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = fxcor_1.temp[0] * sv_1.sn[i__ +
         ifxcor_1.is * 3 - 4];
 /* L8223: */
     }
     dotf_(&dshar4_1.com1, fxcor_1.ta, &sv_1.tn[ifxcor_1.is * 3 - 3]);
     dshar4_1.com1 = -dshar4_1.com1;
 /* Computing 2nd power */
     d__1 = dshar4_1.com1;
     dshar4_1.com4 = sqrt(one - d__1 * d__1);
     if (dshar4_1.com4 <= znumbr_1.z1em3 && dshar4_1.com1 >= zero) {
     goto L605;
     }
     if (dshar4_1.com4 < znumbr_1.z1em3 && dshar4_1.com1 < zero) {
     goto L604;
     }
     dshar4_1.tangl = dshar4_1.com1 / dshar4_1.com4;
     ifxcor_1.it = ifxcor_1.ibegin;
 L704:
 /*              /-TCONT LT ZERO MEANS THIS IS LAST TOOL SEGMENT */
     if (tlldat_1.tcont[ifxcor_1.it] < zero) {
     goto L3;
     }
 /*              /-TCONT GT ZERO MEANS THIS IS ORDINARY TOOL SEGMENT */
     if (tlldat_1.tcont[ifxcor_1.it] > zero) {
     goto L706;
     }
 /*              /-TCONT EQ ZERO MEANS INSIGNIFICANT TOOL SEGMENT */
 L705:
     ++ifxcor_1.it;
     goto L704;
 L706:
     if (tlldat_1.tlinc[ifxcor_1.it] != zero) {
     goto L705;
     }
     if (dshar4_1.tangl < tlldat_1.tanhi[ifxcor_1.it - 1]) {
     goto L705;
     }
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L709: */
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] = fxcor_1.te[i__ - 1] +
         tlldat_1.tlhite[ifxcor_1.it - 1] * fxcor_1.ta[i__ - 1] +
         tlldat_1.ri[ifxcor_1.it - 1] * dshar4_1.uvec[i__ - 1] +
         tlldat_1.corrad[ifxcor_1.it - 1] * sv_1.tn[i__ + ifxcor_1.is *
          3 - 4];
     }
     goto L9999;
 L700:
 /*              /-CONTINUE SEARCH */
     for (i__ = 1; i__ <= 3; ++i__) {
     dshar4_1.refpnt[i__ - 1] = fxcor_1.te[i__ - 1] + tlldat_1.ri[
         ifxcor_1.it - 1] * dshar4_1.uvec[i__ - 1] + tlldat_1.tlhite[
         ifxcor_1.it - 1] * fxcor_1.ta[i__ - 1];
     dshar4_1.ogle[i__ - 1] = sv_1.cc[i__ + ifxcor_1.is * 3 - 4] -
         dshar4_1.refpnt[i__ - 1];
 /* L15: */
     }
     vnorm_(dshar4_1.ogle, dshar4_1.u2);
 /*              /-IF OGLE, CANDIDATE TN, IS SMALL, TRY NXT SEG */
     if (ifxcor_1.ier > 0) {
     goto L2000;
     }
 /*              /-IF SURFACE IS PLANAR, USE NORMAL RATHER THAN CC */
     if (isv_1.ipl[ifxcor_1.is - 1] < 1) {
     goto L155;
     }
     for (i__ = 1; i__ <= 3; ++i__) {
     dshar4_1.ogle[i__ - 1] = -sv_1.rc[ifxcor_1.is - 1] * sv_1.sn[i__ +
         ifxcor_1.is * 3 - 4];
     dshar4_1.u2[i__ - 1] = -d_sign(&one, &sv_1.rc[ifxcor_1.is - 1]) *
         sv_1.sn[i__ + ifxcor_1.is * 3 - 4];
 /* L153: */
     }
 L155:
     if (tlldat_1.tlinc[ifxcor_1.it] == zero) {
     goto L16;
     }
     tlldat_1.corrad[ifxcor_1.it - 1] = zero;
     for (i__ = 1; i__ <= 3; ++i__) {
     dshar4_1.u2[i__ - 1] = cosl[ifxcor_1.it - 1] * dshar4_1.uvec[i__ - 1]
         + sinl[ifxcor_1.it - 1] * fxcor_1.ta[i__ - 1];
 /* L41: */
     tlldat_1.corrad[ifxcor_1.it - 1] += dshar4_1.ogle[i__ - 1] *
         dshar4_1.u2[i__ - 1];
     }
 /*              /-IF CORNER RADIUS IS SMALL, GO TO NEXT SEG */
     if (tlldat_1.corrad[ifxcor_1.it - 1] < -z3em4) {
     goto L2000;
     }
 /*              /-OTHERWISE, GO TO PLANE CALC */
 /*              /-IF SURF IS A PLANE, TN MUST BE LL TO TOOL SEG */
 /* L43: */
     if (isv_1.ipl[ifxcor_1.is - 1] <= 0) {
     goto L643;
     }
     if (tlldat_1.corrad[ifxcor_1.it - 1] >= z5em3) {
     goto L2000;
     }
     tlldat_1.corrad[ifxcor_1.it - 1] = zero;
     goto L44;
 L643:
     if (tlldat_1.corrad[ifxcor_1.it - 1] >= tlldat_1.umax[ifxcor_1.it - 1] +
         z5em4) {
     goto L2000;
     }
 L44:
 /*              /-COSL IS HORIZONTAL AND SINL VERTICAL COMP OF LINEAR SEG */
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L45: */
     dshar4_1.zlnorm[i__ - 1] = sinl[ifxcor_1.it - 1] * dshar4_1.uvec[i__
         - 1] - cosl[ifxcor_1.it - 1] * fxcor_1.ta[i__ - 1];
     }
     goto L31;
 L16:
     dotf_(&dshar4_1.com1, dshar4_1.ogle, fxcor_1.ta);
     dotf_(&dshar4_1.com4, dshar4_1.ogle, dshar4_1.ogle);
 /* Computing 2nd power */
     d__1 = dshar4_1.com1;
     dshar4_1.com4 -= d__1 * d__1;
     fxcor_1.temp[0] = one;
     if (ifxcor_1.it == 7) {
     fxcor_1.temp[0] = -one;
     }
     dshar4_1.tangl = fxcor_1.temp[0] * zbig;
     if (dshar4_1.com4 > zero) {
     goto L19;
     }
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L50: */
     dshar4_1.u2[i__ - 1] = -fxcor_1.temp[0] * fxcor_1.ta[i__ - 1];
     }
     itry = 1;
     goto L25;
 L19:
     dshar4_1.com4 = sqrt(dshar4_1.com4);
     dshar4_1.tangl = -zbig;
     if (dshar4_1.com1 < z700 * dshar4_1.com4) {
     dshar4_1.tangl = -dshar4_1.com1 / dshar4_1.com4;
     }
     dotf_(&w1, dshar4_1.uvec, dshar4_1.ogle);
     itry = 0;
 L1900:
     if (w1 >= zero) {
     goto L25;
     }
 /*              /-REVERSE SIDE OF CUTTER */
     dshar4_1.tangl = -dshar4_1.tangl;
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L24: */
     dshar4_1.u2[i__ - 1] = -dshar4_1.u2[i__ - 1];
     }
 /* ----------------------------------------------------------- */
 /*              /-RESUME NORMAL PATH. COMPUTE ZLPNT,ZLNORM */
 L25:
 /*              /- TANHI.LT.TANGL.LT.TANLO IS CRITERIA FOR VALID TN */
     if (tlldat_1.tanlo[ifxcor_1.it - 1] >= dshar4_1.tangl && tlldat_1.tanhi[
         ifxcor_1.it - 1] <= dshar4_1.tangl) {
     for (i__ = 1; i__ <= 3; ++i__) {
         dshar4_1.zlnorm[i__ - 1] = dshar4_1.u2[i__ - 1];
 /* L30: */
     }
     } else {
     if (tlldat_1.tanlo[ifxcor_1.it - 1] < dshar4_1.tangl) {
 /*              /-TN CONTROL, SEARCH BACKWARDS ON TOOL */
         if (isv_1.jtn[ifxcor_1.is - 1] != 0) {
         nnn = -1;
         }
     }
     if (itry == 1) {
         goto L2000;
     }
     if (chekfl_1.ichekf != 1 && abs(w1) > .05) {
         goto L2000;
     }
     if (abs(w1) > 10.) {
         goto L2000;
     }
     itry = 1;
     w1 = -w1;
     goto L1900;
     }
 L31:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L32: */
     dshar4_1.zlpnt[i__ - 1] = dshar4_1.refpnt[i__ - 1] + tlldat_1.corrad[
         ifxcor_1.it - 1] * dshar4_1.u2[i__ - 1];
     }
     if (isv_1.jtn[ifxcor_1.is - 1] <= 0) {
     goto L237;
     }
 /*              /-NORMAL PATH. TN CONTROL */
     dotf_(&w1, &sv1_1.tnl[ifxcor_1.is * 3 - 3], dshar4_1.zlnorm);
 /*             /-TN.TNL POSITIVE, ACCEPT CURRENT TP,TN - RETURN */
     if (w1 >= zero) {
     goto L9998;
     }
     if (ibb < 0) {
     w11 = w1;
     } else {
     if (w11 > w1) {
         goto L8021;
     } else {
         if (w1 > -.08) {
         error_(&c_b63, "TLNORM", (ftnlen)6);
         goto L9998;
         }
     }
     }
     dotf_(&am, dshar4_1.zlnorm, fxcor_1.ta);
     if (abs(am) <= z9999) {
     goto L802;
     }
     if (isv_1.jtn[ifxcor_1.is - 1] == 0) {
     goto L603;
     }
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L601: */
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = -dshar4_1.zlnorm[i__ - 1];
     }
     if (am > zero) {
     goto L605;
     }
 /*              /-AM IS LE ZERO */
     goto L604;
 L802:
 /*             /-IBB =0 MEANS 2ND TIME THRU TLNORM, SO FAIL HERE. */
     if (ibb >= 0) {
     goto L804;
     }
 /*             /-RESTART MODE, SWITCH TO OTHER SIDE CUTTER, THEN RESTART */
 L8021:
     ibb = 0;
     isv_1.itseg[ifxcor_1.is - 1] = ifxcor_1.ibegin;
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L803: */
     u1var[i__] = -u1var[i__];
     }
 /*             /-BRANCH BACK TO START OF TLNORM, BEGIN AGAIN */
     goto L805;
 L804:
 /* ***** */
     aerr_(&c__26602, "TLNORM  ", (ftnlen)8);
 L603:
 /*             /-SET REFERENCE TP AT TOP OF TOOL */
     if (ifxcor_1.it == 7) {
     goto L605;
     }
 L604:
     ifxcor_1.it = 7;
     isv_1.itseg[ifxcor_1.is - 1] = 7;
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L3604: */
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] = fxcor_1.te[i__ - 1] +
         tlldat_1.tlhite[ifxcor_1.it - 1] * fxcor_1.ta[i__ - 1] +
         tlldat_1.ri[ifxcor_1.it - 1] * sv_1.u1[i__ + ifxcor_1.is * 3
         - 4];
     }
     goto L9999;
 L605:
     isv_1.itseg[ifxcor_1.is - 1] = ifxcor_1.ibegin;
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L3603: */
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] = fxcor_1.te[i__ - 1];
     }
     goto L9999;
 /*              /-SELECT CORRECT TN FROM MULTIPLE TN'S. */
 /*              /-TEMPORARILY REPLACE TP,TN WITH NEW TP,TN CANDIDATE */
 L237:
     for (i__ = 1; i__ <= 3; ++i__) {
     snold[i__ - 1] = sv_1.sn[i__ + ifxcor_1.is * 3 - 4];
     spold[i__ - 1] = sv_1.sp[i__ + ifxcor_1.is * 3 - 4];
     tnold[i__ - 1] = sv_1.tn[i__ + ifxcor_1.is * 3 - 4];
     tpold[i__ - 1] = sv_1.tp[i__ + ifxcor_1.is * 3 - 4];
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = dshar4_1.zlnorm[i__ - 1];
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] = dshar4_1.zlpnt[i__ - 1];
 /* L34: */
     }
     if (ifxcor_1.is == 1) {
     goto L7003;
     }
     if (isv_1.isfidn[ifxcor_1.is - 1] == 29 || isv_1.isfidn[ifxcor_1.is - 1]
         == 30) {
     goto L7003;
     }
 /*              /- */
     ddst_();
 /*              /- */
     if (ifxcor_1.ier == 0) {
     goto L7004;
     }
 L7003:
     sv_1.s[ifxcor_1.is - 1] = zbig2;
 L7004:
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.sn[i__ + ifxcor_1.is * 3 - 4] = snold[i__ - 1];
     sv_1.sp[i__ + ifxcor_1.is * 3 - 4] = spold[i__ - 1];
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = tnold[i__ - 1];
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] = tpold[i__ - 1];
 /* L4029: */
     }
     sv_1.s[ifxcor_1.is - 1] = (d__1 = sv_1.s[ifxcor_1.is - 1], abs(d__1));
     if (dshar4_1.cendis < sv_1.s[ifxcor_1.is - 1]) {
     goto L2000;
     }
 /* .... SELECT TN WHOS DIRECTION COINCIDES BEST WITH LAST SN */
 /* .... IE. WHOSE ABS VALUE OF TN.SN IS MAXIMAL */
     dotf_(&wfl2, &sv_1.sn[ifxcor_1.is * 3 - 3], dshar4_1.zlnorm);
     if (abs(wfl2) <= abs(wfl1)) {
     goto L2000;
     }
     wfl1 = wfl2;
 /*              /-NEW DISTANCE TO SURFACE LESS, SET JFIND TO SEARCH TOOL */
 /*             /-SET JFIND TO -1 TO SHOW A VALID DIST HAS BEEN FOUND */
     jfind = -1;
     dshar4_1.cendis = sv_1.s[ifxcor_1.is - 1];
 /*              /-UPDATE TP,TN AND EXIT IF JFIND =1. */
 L9998:
     isv_1.itseg[ifxcor_1.is - 1] = ifxcor_1.it;
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] = dshar4_1.zlpnt[i__ - 1];
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = dshar4_1.zlnorm[i__ - 1];
 /* L9222: */
     }
 /*             /-JFIND -1, SO CONTINUE SEARCHING FOR BETTER TOOL SEG */
     if (jfind < 0) {
     goto L2000;
     }
 /* **** */
 L9999:
     return 0;
 /* ************************************************************ */
 /* ----------------------------------------------------------- */
 L3029:
 /* --------  SPECIAL TREATMENT OF A BALL CUTTER BY SSURF */
 /*              /-RADIUS OF BALL EQUALS HALF DIAMETER OF TOOL */
     rrr = fxcor_1.cutdat[1];
 /*              /-TOOL ON OR POINT TOOL MEANS RRR IS ZERO */
     if (isv_1.itlon[ifxcor_1.is - 1] * ifxcor_1.ipt1 == 0) {
     rrr = zero;
     }
 /*              /-ISFTYP 1=TO, 2=PAST, 3=ON, 4=TANTO 8=PSTAN */
     if (isv_1.isftyp[ifxcor_1.is - 1] == 3) {
     rrr = zero;
     }
 /*              /-GENERATE POINT AT CENTER OF BALL OR TIP OF TOOL */
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] = fxcor_1.te[i__ - 1] + rrr *
         fxcor_1.ta[i__ - 1];
 /* L3030: */
     sv_1.spl[i__ + ifxcor_1.is * 3 - 4] = sv_1.sp[i__ + ifxcor_1.is * 3 -
         4];
     }
 /*             /-BRANCH TO DD ROUTINE TO ESTABLISH TOOL/SURF RELATION */
     modess_1.modess = 21;
     ajundd_();
     modess_1.modess = 0;
 /*             /-COMPUTE RELEVANT POINT ON TOOL SURFACE */
     w1 = one;
     if (isv_1.jtn[ifxcor_1.is - 1] == 0) {
     w1 = -w1;
     }
 /*             /-MODIFY TN FOR TN CONTROL SO THAT TN.TI IS POSITIVE */
     if (isv_1.jtn[ifxcor_1.is - 1] == 0) {
     goto L3032;
     }
 /*             /-MEASURE THE ANGLE BETWEEN TN AND TI */
     dotf_(&w2, &sv_1.sn[ifxcor_1.is * 3 - 3], fxcor_1.ti);
     w2 = w2 * w1 * sv_1.past[ifxcor_1.is - 1];
     if (w2 >= zero) {
     goto L3032;
     }
 /*             /-ALTER THE SIGN OF Z AND SN TO MAKE TN.TI.PAST POSITIVE */
     sv_1.z__[ifxcor_1.is - 1] = -sv_1.z__[ifxcor_1.is - 1];
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.sn[i__ + ifxcor_1.is * 3 - 4] = -sv_1.sn[i__ + ifxcor_1.is * 3 -
         4];
 /* L3034: */
     }
 L3032:
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.tn[i__ + ifxcor_1.is * 3 - 4] = w1 * sv_1.sn[i__ + ifxcor_1.is *
         3 - 4];
     sv_1.tp[i__ + ifxcor_1.is * 3 - 4] += rrr * sv_1.tn[i__ + ifxcor_1.is
         * 3 - 4];
     tpspdf[i__ - 1] = sv_1.sp[i__ + ifxcor_1.is * 3 - 4] - (sv_1.tp[i__ +
         ifxcor_1.is * 3 - 4] + sv_1.th[ifxcor_1.is - 1] * sv_1.tn[i__
         + ifxcor_1.is * 3 - 4]);
 /* L3033: */
     }
 /*             /-DISTANCE MEASURED FROM RELEVANT TP TO SP IN TN DIRECTION */
     dotf_(&sv_1.s[ifxcor_1.is - 1], tpspdf, &sv_1.tn[ifxcor_1.is * 3 - 3]);
     ccurv_(&ifxcor_1.is, &sv_1.sp[ifxcor_1.is * 3 - 3], &sv_1.spl[ifxcor_1.is
         * 3 - 3], &sv_1.sn[ifxcor_1.is * 3 - 3]);
     isv_1.itseg[ifxcor_1.is - 1] = 4;
     if (abs(rrr) < z5em4) {
     isv_1.itseg[ifxcor_1.is - 1] = 1;
     }
     dotf_(&w1, &sv_1.tn[ifxcor_1.is * 3 - 3], fxcor_1.ta);
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L3035: */
     u1var[i__] = sv_1.tn[i__ + ifxcor_1.is * 3 - 4] - w1 * fxcor_1.ta[i__
         - 1];
     }
     vnorm_(&u1var[1], &u1var[1]);
     ifxcor_1.ier = 0;
     return 0;
 } /* tlnorm_ */
Variable Documentation
struct { ... } _BLNK__
doublereal a
Definition at line 18 of file TLNORM.c.
doublereal alp
Definition at line 28 of file TLNORM.c.
doublereal ax4[3]
Definition at line 28 of file TLNORM.c.
doublereal b
Definition at line 18 of file TLNORM.c.
doublereal c__
Definition at line 18 of file TLNORM.c.
integer c__26601 = 26601 static
Definition at line 129 of file TLNORM.c.
Referenced by tlnorm_().
integer c__26602 = 26602 static
Definition at line 131 of file TLNORM.c.
Referenced by tlnorm_().
integer c_b63 = -26002 static
Definition at line 130 of file TLNORM.c.
Referenced by tlnorm_().
doublereal cagl
Definition at line 28 of file TLNORM.c.
doublereal cc[15]
Definition at line 50 of file TLNORM.c.
doublereal cendis
Definition at line 18 of file TLNORM.c.
struct { ... } charct_
struct { ... } chekfl_
doublereal cmove[3]
Definition at line 18 of file TLNORM.c.
doublereal com[36000]
Definition at line 110 of file TLNORM.c.
doublereal com1
Definition at line 18 of file TLNORM.c.
doublereal com4
Definition at line 18 of file TLNORM.c.
doublereal corrad[8]
Definition at line 43 of file TLNORM.c.
doublereal cos1[5]
Definition at line 67 of file TLNORM.c.
doublereal cplfl[5]
Definition at line 67 of file TLNORM.c.
doublereal cptst[5]
Definition at line 67 of file TLNORM.c.
doublereal csd[5]
Definition at line 67 of file TLNORM.c.
doublereal cutdat[7]
Definition at line 28 of file TLNORM.c.
doublereal d1
Definition at line 18 of file TLNORM.c.
doublereal d2a
Definition at line 18 of file TLNORM.c.
doublereal degrad
Definition at line 102 of file TLNORM.c.
doublereal dir[3]
Definition at line 18 of file TLNORM.c.
doublereal dp
Definition at line 18 of file TLNORM.c.
doublereal dp1
Definition at line 18 of file TLNORM.c.
doublereal dpcnt
Definition at line 18 of file TLNORM.c.
doublereal dpe
Definition at line 18 of file TLNORM.c.
doublereal dpi
Definition at line 18 of file TLNORM.c.
doublereal dpl
Definition at line 18 of file TLNORM.c.
doublereal dplan[15]
Definition at line 67 of file TLNORM.c.
doublereal dpmax
Definition at line 28 of file TLNORM.c.
doublereal dpmx1[5]
Definition at line 67 of file TLNORM.c.
struct { ... } dshar4_
doublereal eps1[5]
Definition at line 50 of file TLNORM.c.
doublereal eps2[5]
Definition at line 50 of file TLNORM.c.
doublereal eps3[5]
Definition at line 50 of file TLNORM.c.
doublereal eps4[5]
Definition at line 50 of file TLNORM.c.
doublereal eps6[5]
Definition at line 50 of file TLNORM.c.
doublereal eps8[5]
Definition at line 50 of file TLNORM.c.
doublereal flipck
Definition at line 18 of file TLNORM.c.
doublereal fwd[3]
Definition at line 18 of file TLNORM.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file TLNORM.c.
doublereal hi
Definition at line 28 of file TLNORM.c.
integer i3dflg
Definition at line 92 of file TLNORM.c.
integer iaerr
Definition at line 92 of file TLNORM.c.
integer iafl[5]
Definition at line 76 of file TLNORM.c.
integer iautps
Definition at line 92 of file TLNORM.c.
integer ibegin
Definition at line 92 of file TLNORM.c.
integer ic
Definition at line 92 of file TLNORM.c.
integer icanon[5]
Definition at line 76 of file TLNORM.c.
integer icheck
Definition at line 92 of file TLNORM.c.
integer ichekf
Definition at line 116 of file TLNORM.c.
integer icl
Definition at line 92 of file TLNORM.c.
integer ics
Definition at line 92 of file TLNORM.c.
integer icscnt
Definition at line 92 of file TLNORM.c.
integer ictdef
Definition at line 92 of file TLNORM.c.
integer icut
Definition at line 92 of file TLNORM.c.
integer ids
Definition at line 92 of file TLNORM.c.
integer ier
Definition at line 92 of file TLNORM.c.
integer ifar[5]
Definition at line 85 of file TLNORM.c.
integer ifl4[5]
Definition at line 85 of file TLNORM.c.
struct { ... } ifxcor_
integer igo
Definition at line 92 of file TLNORM.c.
integer igoto
Definition at line 92 of file TLNORM.c.
integer igoug
Definition at line 92 of file TLNORM.c.
integer igs
Definition at line 92 of file TLNORM.c.
integer index[5]
Definition at line 76 of file TLNORM.c.
integer indir__[5]
Definition at line 76 of file TLNORM.c.
integer inops
Definition at line 92 of file TLNORM.c.
integer iop[5]
Definition at line 76 of file TLNORM.c.
integer iopset[5]
Definition at line 76 of file TLNORM.c.
integer ipl[5]
Definition at line 76 of file TLNORM.c.
integer ips
Definition at line 92 of file TLNORM.c.
integer ipsdef
Definition at line 92 of file TLNORM.c.
integer ipt1
Definition at line 92 of file TLNORM.c.
integer is
Definition at line 92 of file TLNORM.c.
integer iseg
Definition at line 92 of file TLNORM.c.
integer iseqno
Definition at line 92 of file TLNORM.c.
integer isfidn[5]
Definition at line 76 of file TLNORM.c.
integer isftyp[5]
Definition at line 76 of file TLNORM.c.
integer isigcr[5]
Definition at line 76 of file TLNORM.c.
integer isrch
Definition at line 92 of file TLNORM.c.
integer istrup
Definition at line 92 of file TLNORM.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 76 of file TLNORM.c.
integer it
Definition at line 92 of file TLNORM.c.
integer itlon[5]
Definition at line 76 of file TLNORM.c.
integer itseg[5]
Definition at line 76 of file TLNORM.c.
integer itsegk[5]
Definition at line 76 of file TLNORM.c.
integer iunfl[5]
Definition at line 76 of file TLNORM.c.
integer j20[5]
Definition at line 85 of file TLNORM.c.
integer j21[5]
Definition at line 85 of file TLNORM.c.
integer j22[5]
Definition at line 85 of file TLNORM.c.
integer j23[5]
Definition at line 85 of file TLNORM.c.
integer j50[5]
Definition at line 85 of file TLNORM.c.
integer j51[5]
Definition at line 85 of file TLNORM.c.
integer jbr
Definition at line 92 of file TLNORM.c.
integer jent[5]
Definition at line 76 of file TLNORM.c.
integer jiops[5]
Definition at line 76 of file TLNORM.c.
integer jph[5]
Definition at line 85 of file TLNORM.c.
integer jsw
Definition at line 92 of file TLNORM.c.
integer jtlflg[5]
Definition at line 76 of file TLNORM.c.
integer jtn[5]
Definition at line 76 of file TLNORM.c.
integer ju1[5]
Definition at line 76 of file TLNORM.c.
integer limfl[5]
Definition at line 76 of file TLNORM.c.
integer lsv
Definition at line 92 of file TLNORM.c.
integer lsv1
Definition at line 92 of file TLNORM.c.
integer mantax
Definition at line 92 of file TLNORM.c.
integer modess
Definition at line 122 of file TLNORM.c.
struct { ... } modess_
char modfer[6]
Definition at line 37 of file TLNORM.c.
integer motmod
Definition at line 92 of file TLNORM.c.
integer msav
Definition at line 92 of file TLNORM.c.
integer mssarl
Definition at line 122 of file TLNORM.c.
integer msschk
Definition at line 122 of file TLNORM.c.
integer mulout
Definition at line 92 of file TLNORM.c.
integer nmbseg
Definition at line 92 of file TLNORM.c.
integer nmpnts
Definition at line 92 of file TLNORM.c.
integer notan[5]
Definition at line 85 of file TLNORM.c.
integer nrec
Definition at line 92 of file TLNORM.c.
integer numax
Definition at line 92 of file TLNORM.c.
integer numcnt
Definition at line 92 of file TLNORM.c.
integer nump
Definition at line 92 of file TLNORM.c.
integer numpt1
Definition at line 92 of file TLNORM.c.
integer numsfs
Definition at line 92 of file TLNORM.c.
integer numsur
Definition at line 92 of file TLNORM.c.
integer nw
Definition at line 92 of file TLNORM.c.
integer nwds
Definition at line 92 of file TLNORM.c.
doublereal ogle[3]
Definition at line 18 of file TLNORM.c.
doublereal p1[3]
Definition at line 18 of file TLNORM.c.
doublereal p2[3]
Definition at line 18 of file TLNORM.c.
doublereal param[6]
Definition at line 18 of file TLNORM.c.
doublereal past[5]
Definition at line 50 of file TLNORM.c.
doublereal pi
Definition at line 102 of file TLNORM.c.
doublereal plncs[5]
Definition at line 67 of file TLNORM.c.
doublereal plnd[5]
Definition at line 50 of file TLNORM.c.
doublereal plnd1[5]
Definition at line 67 of file TLNORM.c.
doublereal plnv[15]
Definition at line 50 of file TLNORM.c.
doublereal pltst[5]
Definition at line 67 of file TLNORM.c.
doublereal pmove[3]
Definition at line 28 of file TLNORM.c.
doublereal r__[6]
Definition at line 18 of file TLNORM.c.
doublereal ra
Definition at line 28 of file TLNORM.c.
doublereal rc[5]
Definition at line 50 of file TLNORM.c.
doublereal rc1
Definition at line 28 of file TLNORM.c.
doublereal rdrn
Definition at line 18 of file TLNORM.c.
doublereal refpnt[3]
Definition at line 18 of file TLNORM.c.
doublereal ri[8]
Definition at line 43 of file TLNORM.c.
doublereal s[5]
Definition at line 50 of file TLNORM.c.
doublereal sagl
Definition at line 28 of file TLNORM.c.
doublereal save[5]
Definition at line 50 of file TLNORM.c.
doublereal savpar[4]
Definition at line 18 of file TLNORM.c.
doublereal seg[9]
Definition at line 18 of file TLNORM.c.
doublereal sfvct[15]
Definition at line 50 of file TLNORM.c.
doublereal sk[15]
Definition at line 50 of file TLNORM.c.
doublereal slope
Definition at line 18 of file TLNORM.c.
doublereal slx[15]
Definition at line 50 of file TLNORM.c.
doublereal sn[15]
Definition at line 50 of file TLNORM.c.
doublereal snk[15]
Definition at line 50 of file TLNORM.c.
doublereal snl[15]
Definition at line 50 of file TLNORM.c.
doublereal sp[15]
Definition at line 50 of file TLNORM.c.
doublereal spk[15]
Definition at line 50 of file TLNORM.c.
doublereal spl[15]
Definition at line 50 of file TLNORM.c.
doublereal sqroot
Definition at line 18 of file TLNORM.c.
doublereal stck[5]
Definition at line 67 of file TLNORM.c.
doublereal stck1[5]
Definition at line 67 of file TLNORM.c.
doublereal stck2[5]
Definition at line 67 of file TLNORM.c.
doublereal stckn[5]
Definition at line 67 of file TLNORM.c.
doublereal strtno
Definition at line 28 of file TLNORM.c.
doublereal surd
Definition at line 28 of file TLNORM.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 28 of file TLNORM.c.
doublereal tak[3]
Definition at line 28 of file TLNORM.c.
doublereal tal[3]
Definition at line 28 of file TLNORM.c.
doublereal tangl
Definition at line 18 of file TLNORM.c.
doublereal tanhi[8]
Definition at line 43 of file TLNORM.c.
doublereal tanlo[8]
Definition at line 43 of file TLNORM.c.
doublereal tau[5]
Definition at line 50 of file TLNORM.c.
doublereal tau1[5]
Definition at line 50 of file TLNORM.c.
doublereal tau2[5]
Definition at line 50 of file TLNORM.c.
doublereal tcont[9]
Definition at line 43 of file TLNORM.c.
doublereal te[3]
Definition at line 28 of file TLNORM.c.
doublereal tee[15]
Definition at line 67 of file TLNORM.c.
doublereal tek[3]
Definition at line 28 of file TLNORM.c.
doublereal tel[3]
Definition at line 28 of file TLNORM.c.
doublereal tem[10]
Definition at line 28 of file TLNORM.c.
doublereal temp[24]
Definition at line 28 of file TLNORM.c.
doublereal tes[3]
Definition at line 18 of file TLNORM.c.
doublereal tew[3]
Definition at line 18 of file TLNORM.c.
doublereal th[5]
Definition at line 50 of file TLNORM.c.
doublereal ti[3]
Definition at line 28 of file TLNORM.c.
doublereal tik[3]
Definition at line 28 of file TLNORM.c.
doublereal til[3]
Definition at line 28 of file TLNORM.c.
doublereal tlhit
Definition at line 28 of file TLNORM.c.
doublereal tlhite[8]
Definition at line 43 of file TLNORM.c.
doublereal tlinc[9]
Definition at line 43 of file TLNORM.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file TLNORM.c.
doublereal tn[15]
Definition at line 50 of file TLNORM.c.
doublereal tnl[15]
Definition at line 67 of file TLNORM.c.
doublereal toolht[15]
Definition at line 50 of file TLNORM.c.
doublereal toolwd[5]
Definition at line 50 of file TLNORM.c.
doublereal tp[15]
Definition at line 50 of file TLNORM.c.
doublereal tpk[15]
Definition at line 50 of file TLNORM.c.
doublereal u1[15]
Definition at line 50 of file TLNORM.c.
doublereal u1k[15]
Definition at line 50 of file TLNORM.c.
doublereal u2[3]
Definition at line 18 of file TLNORM.c.
doublereal umax[8]
Definition at line 43 of file TLNORM.c.
doublereal unn
Definition at line 18 of file TLNORM.c.
doublereal upp
Definition at line 18 of file TLNORM.c.
doublereal uvec[3]
Definition at line 18 of file TLNORM.c.
doublereal v[3]
Definition at line 18 of file TLNORM.c.
doublereal varble[5]
Definition at line 50 of file TLNORM.c.
doublereal vint
Definition at line 18 of file TLNORM.c.
doublereal vl
Definition at line 18 of file TLNORM.c.
doublereal vndir[15]
Definition at line 50 of file TLNORM.c.
doublereal vnn
Definition at line 18 of file TLNORM.c.
doublereal vpp
Definition at line 18 of file TLNORM.c.
doublereal vt[15]
Definition at line 50 of file TLNORM.c.
doublereal vtem
Definition at line 28 of file TLNORM.c.
doublereal z0
Definition at line 102 of file TLNORM.c.
doublereal z1
Definition at line 102 of file TLNORM.c.
doublereal z10
Definition at line 102 of file TLNORM.c.
doublereal z11em1
Definition at line 102 of file TLNORM.c.
doublereal z12em1
Definition at line 102 of file TLNORM.c.
doublereal z1e38
Definition at line 102 of file TLNORM.c.
doublereal z1e6
Definition at line 102 of file TLNORM.c.
doublereal z1em1
Definition at line 102 of file TLNORM.c.
doublereal z1em2
Definition at line 102 of file TLNORM.c.
doublereal z1em3
Definition at line 102 of file TLNORM.c.
doublereal z1em5
Definition at line 102 of file TLNORM.c.
doublereal z1em6
Definition at line 102 of file TLNORM.c.
doublereal z1em7
Definition at line 102 of file TLNORM.c.
doublereal z1em9
Definition at line 102 of file TLNORM.c.
doublereal z2
Definition at line 102 of file TLNORM.c.
doublereal z3
Definition at line 102 of file TLNORM.c.
doublereal z5
Definition at line 102 of file TLNORM.c.
doublereal z5em1
Definition at line 102 of file TLNORM.c.
doublereal z5em6
Definition at line 102 of file TLNORM.c.
doublereal z6em1
Definition at line 102 of file TLNORM.c.
doublereal z90
Definition at line 102 of file TLNORM.c.
doublereal z9em1
Definition at line 102 of file TLNORM.c.
doublereal z__[5]
Definition at line 50 of file TLNORM.c.
doublereal zl
Definition at line 18 of file TLNORM.c.
doublereal zl1
Definition at line 18 of file TLNORM.c.
doublereal zlnorm[3]
Definition at line 18 of file TLNORM.c.
doublereal zlpnt[3]
Definition at line 18 of file TLNORM.c.
doublereal zm1
Definition at line 102 of file TLNORM.c.
struct { ... } znumbr_