My Project: TMDCS.c File Reference
TMDCS.c File Reference
#include "f2c.h"
Functions
int tmdcs_ (doublereal *trm, doublereal *data)
Variables
static integer c__97 = 97
static integer c__0 = 0
Function Documentation
int tmdcs_ (doublereal * trm, doublereal * data)
Definition at line 22 of file TMDCS.c.
References apt066_(), c__0, c__97, error_(), and i__.
Referenced by teval_().
 {
     /* Initialized data */
     static doublereal ntrm[12] = { 1.,0.,0.,0.,0.,1.,0.,0.,0.,0.,1.,0. };
     /* System generated locals */
     doublereal d__1, d__2, d__3, d__4, d__5, d__6, d__7, d__8;
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     static integer i__;
     static doublereal trm1[12];
     extern /* Subroutine */ int apt066_(doublereal *, doublereal *,
         doublereal *, integer *);
     static doublereal scale;
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
     static doublereal scales;
 /* PROGRAM TO TRANSFORM THE PATCH GEOMETRY */
 /*  OF "MASTER DIMENSION CONTOUR SURFACE" */
 /*   TRANSFORMATION MATRIX */
 /*   PATCH DATA */
 /*   AUXILIARY MATRIX */
 /*   'NO TRANSFORMATION' MATRIX */
 /*   SCALE FACTOR */
     /* Parameter adjustments */
     --data;
     --trm;
     /* Function Body */
 /*   TEST PRINT */
 /*     WRITE(6,100) */
 /* 100 FORMAT('0TMDCSSSS WAS CALLED') */
 /*    PRESET OF SCALE FACTOR */
     scale = 1.;
 /*    SQUARED SCALE FACTOR */
 /* Computing 2nd power */
     d__1 = trm[1];
 /* Computing 2nd power */
     d__2 = trm[2];
 /* Computing 2nd power */
     d__3 = trm[3];
     scales = d__1 * d__1 + d__2 * d__2 + d__3 * d__3;
 /*    COMPUTATION OF SCALE FACTOR */
     if ((d__1 = scales - 1., abs(d__1)) >= 1e-10) {
     scale = sqrt(scales);
     }
 /*    TEST IF ALL SCALE FACTORS EQUAL */
 /* Computing 2nd power */
     d__3 = trm[5];
 /* Computing 2nd power */
     d__4 = trm[6];
 /* Computing 2nd power */
     d__5 = trm[7];
 /* Computing 2nd power */
     d__6 = trm[9];
 /* Computing 2nd power */
     d__7 = trm[10];
 /* Computing 2nd power */
     d__8 = trm[11];
     if ((d__1 = d__3 * d__3 + d__4 * d__4 + d__5 * d__5 - scales, abs(d__1)) <
          1e-10 && (d__2 = d__6 * d__6 + d__7 * d__7 + d__8 * d__8 -
         scales, abs(d__2)) < 1e-10) {
     goto L1;
     }
 /*    NO TRANSFORMATION AND ERROR MESSAGE */
     error_(&c__97, "TMDCSSSS", (ftnlen)8);
     goto L99;
 /*    MOVE OLD MATRIX TO SCATCH AREA */
 L1:
     for (i__ = 1; i__ <= 12; ++i__) {
 /* L2: */
     trm1[i__ - 1] = data[i__ + 18];
     }
 /*    COMPUTE NEW TRANSFORMATION MATRIX */
     apt066_(&data[19], &trm[1], trm1, &c__0);
 /*    PRESET SCALE FACTOR OF MATRIX */
     data[18] = scale;
 /*    CHECK THE RESULT MATRIX FOR 'NO TRANSFORMATION' */
     for (i__ = 1; i__ <= 12; ++i__) {
     if ((d__1 = data[i__ + 18] - ntrm[i__ - 1], abs(d__1)) >= 1e-10) {
         goto L99;
     }
 /* L3: */
     }
 /*    SWITCH OFF TRANSFORMATION */
     data[18] = 0.;
 L99:
     return 0;
 } /* tmdcs_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 18 of file TMDCS.c.
Referenced by tmdcs_().
integer c__97 = 97 static
Definition at line 17 of file TMDCS.c.
Referenced by tmdcs_().