My Project: TOLER.c File Reference
TOLER.c File Reference
#include "f2c.h"
Macros
#define sv_1 sv_
#define sv1_1 sv1_
#define znumbr_1 znumbr_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define knumbr_1 knumbr_
#define hold_1 hold_
#define hsave_1 hsave_
#define number ((integer *)&hsave_1 + 8)
#define tolrns ((doublereal *)&hsave_1)
#define number ((integer *)&hsave_1 + 8)
#define tolrns ((doublereal *)&hsave_1)
#define number ((integer *)&hsave_1 + 8)
#define tolrns ((doublereal *)&hsave_1)
#define number ((integer *)&hsave_1 + 8)
#define tolrns ((doublereal *)&hsave_1)
#define number ((integer *)&hsave_1 + 8)
#define tolrns ((doublereal *)&hsave_1)
#define number ((integer *)&hsave_1 + 8)
#define tolrns ((doublereal *)&hsave_1)
Functions
int toler_ (integer *nmbr, doublereal *tlrns)
int intol_ (integer *nmbr, doublereal *tlrns)
int outtol_ (integer *nmbr, doublereal *tlrns)
int tolerh_ (integer *nmbr, doublereal *tlrns)
int intolh_ (integer *nmbr, doublereal *tlrns)
int outtoh_ (integer *nmbr, doublereal *tlrns)
Variables
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
struct {
integer jhldfg
integer ithcnt
integer itabh [100]
} hold_
struct {
doublereal saveh [50]
} hsave_
static integer c__1 = 1
static integer c__0 = 0
Macro Definition Documentation
#define hold_1 hold_
Definition at line 81 of file TOLER.c.
Referenced by intol_(), outtol_(), and toler_().
#define hsave_1 hsave_
Definition at line 87 of file TOLER.c.
#define ifxcor_1 ifxcor_
Definition at line 59 of file TOLER.c.
Referenced by toler_(), and tolerh_().
#define ishr18_1 ishr18_
Definition at line 67 of file TOLER.c.
#define knumbr_1 knumbr_
Definition at line 75 of file TOLER.c.
#define number ((integer *)&hsave_1 + 8)
Referenced by intol_(), intolh_(), outtoh_(), outtol_(), toler_(), and tolerh_().
#define number ((integer *)&hsave_1 + 8)
#define number ((integer *)&hsave_1 + 8)
#define number ((integer *)&hsave_1 + 8)
#define number ((integer *)&hsave_1 + 8)
#define number ((integer *)&hsave_1 + 8)
#define sv1_1 sv1_
Definition at line 41 of file TOLER.c.
#define sv_1 sv_
Definition at line 32 of file TOLER.c.
Referenced by intol_(), intolh_(), outtoh_(), outtol_(), toler_(), and tolerh_().
#define tolrns ((doublereal *)&hsave_1)
Referenced by apt232_(), intol_(), intolh_(), outtoh_(), outtol_(), toler_(), and tolerh_().
#define tolrns ((doublereal *)&hsave_1)
#define tolrns ((doublereal *)&hsave_1)
#define tolrns ((doublereal *)&hsave_1)
#define tolrns ((doublereal *)&hsave_1)
#define tolrns ((doublereal *)&hsave_1)
#define znumbr_1 znumbr_
Definition at line 49 of file TOLER.c.
Referenced by intol_(), intolh_(), outtoh_(), outtol_(), toler_(), and tolerh_().
Function Documentation
int intol_ (integer * nmbr, doublereal * tlrns)
Definition at line 231 of file TOLER.c.
References apt232_(), apt299_(), bcdf_(), c__0, c__1, hold_1, i__, ibtflg, j, number, sv_1, tolrns, and znumbr_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static char ppword[6*3] = "INTOL " "OUTTOL" "TOLER ";
     static integer ithval[3] = { 8,9,4 };
     /* System generated locals */
     integer i__1;
     doublereal d__1;
     /* Local variables */
     static integer i__, j;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt232_(integer *, doublereal *, doublereal *,
          doublereal *), apt299_();
     static integer icase, ibtflg;
 #define number ((integer *)&hsave_1 + 8)
     static integer ippwrd[2];
 #define tolrns ((doublereal *)&hsave_1)
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --tlrns;
     /* Function Body */
     icase = 1;
     for (i__ = 1; i__ <= 4; ++i__) {
 /* L5: */
     tolrns[i__ - 1] = tlrns[i__];
     }
     *number = *nmbr;
     if (hold_1.jhldfg == 0) {
     goto L100;
     }
     hold_1.itabh[hold_1.ithcnt - 1] = ithval[icase - 1];
     ++hold_1.ithcnt;
 L999:
     return 0;
 /* ---    INTOL, MAX DEVIATION SPECFD ON SIDE OF SURF AWAY FROM CUTTER */
 L100:
     if (ibtflg >= 0) {
     goto L110;
     }
     ibtflg = 0;
     sv_1.tau1[0] = znumbr_1.z0;
 L110:
     d__1 = -znumbr_1.z1;
     apt232_(number, tolrns, sv_1.tau2, &d__1);
 /* ---    OUTPUT PART PROGRAM COMMAND ON EXFILE */
 /* L400: */
     ippwrd[0] = bcdf_(ppword + (icase - 1) * 6, (ftnlen)4);
     ippwrd[1] = bcdf_(ppword + ((icase - 1) * 6 + 4), (ftnlen)2);
     apt299_(number, ippwrd, &c__1, tolrns);
     if (*number <= 1) {
     goto L999;
     }
     i__1 = *number;
     for (j = 2; j <= i__1; j += 2) {
     if (j != *number) {
         apt299_(&c__1, &tolrns[j - 1], &c__1, &tolrns[j]);
     } else {
         apt299_(&c__1, &tolrns[j - 1], &c__0, &znumbr_1.z0);
     }
 /* L30: */
     }
     goto L999;
 } /* intol_ */
int intolh_ (integer * nmbr, doublereal * tlrns)
Definition at line 608 of file TOLER.c.
References apt232_(), apt299_(), bcdf_(), c__0, c__1, ibtflg, j, number, sv_1, tolrns, and znumbr_1.
Referenced by apt211_().
 {
     /* Initialized data */
     static char ppword[6*3] = "INTOL " "OUTTOL" "TOLER ";
     /* System generated locals */
     integer i__1;
     doublereal d__1;
     /* Local variables */
     static integer j;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt232_(integer *, doublereal *, doublereal *,
          doublereal *), apt299_();
     static integer icase, ibtflg;
 #define number ((integer *)&hsave_1 + 8)
     static integer ippwrd[2];
 #define tolrns ((doublereal *)&hsave_1)
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     icase = 1;
 /* ---    INTOL, MAX DEVIATION SPECFD ON SIDE OF SURF AWAY FROM CUTTER */
 /* L100: */
     if (ibtflg >= 0) {
     goto L110;
     }
     ibtflg = 0;
     sv_1.tau1[0] = znumbr_1.z0;
 L110:
     d__1 = -znumbr_1.z1;
     apt232_(number, tolrns, sv_1.tau2, &d__1);
 /* ---    OUTPUT PART PROGRAM COMMAND ON EXFILE */
 /* L400: */
     ippwrd[0] = bcdf_(ppword + (icase - 1) * 6, (ftnlen)4);
     ippwrd[1] = bcdf_(ppword + ((icase - 1) * 6 + 4), (ftnlen)2);
     apt299_(number, ippwrd, &c__1, tolrns);
     if (*number <= 1) {
     goto L999;
     }
     i__1 = *number;
     for (j = 2; j <= i__1; j += 2) {
     if (j != *number) {
         apt299_(&c__1, &tolrns[j - 1], &c__1, &tolrns[j]);
     } else {
         apt299_(&c__1, &tolrns[j - 1], &c__0, &znumbr_1.z0);
     }
 /* L30: */
     }
 L999:
     return 0;
 } /* intolh_ */
int outtoh_ (integer * nmbr, doublereal * tlrns)
Definition at line 725 of file TOLER.c.
References apt232_(), apt299_(), bcdf_(), c__0, c__1, ibtflg, j, number, sv_1, tolrns, and znumbr_1.
Referenced by apt211_().
 {
     /* Initialized data */
     static char ppword[6*3] = "INTOL " "OUTTOL" "TOLER ";
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer j;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt232_(integer *, doublereal *, doublereal *,
          doublereal *), apt299_();
     static integer icase, ibtflg;
 #define number ((integer *)&hsave_1 + 8)
     static integer ippwrd[2];
 #define tolrns ((doublereal *)&hsave_1)
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     icase = 2;
 /* ---    OUTTOL, MAXDEVIATION SPECIFD ON CUTTER SIDE OF SURFACE */
 /* L200: */
     if (ibtflg < 0) {
     ibtflg = 0;
     }
 /* L210: */
     apt232_(number, tolrns, sv_1.tau1, &znumbr_1.z1);
     ippwrd[0] = bcdf_(ppword + (icase - 1) * 6, (ftnlen)4);
     ippwrd[1] = bcdf_(ppword + ((icase - 1) * 6 + 4), (ftnlen)2);
     apt299_(number, ippwrd, &c__1, tolrns);
     if (*number <= 1) {
     goto L999;
     }
     i__1 = *number;
     for (j = 2; j <= i__1; j += 2) {
     if (j != *number) {
         apt299_(&c__1, &tolrns[j - 1], &c__1, &tolrns[j]);
     } else {
         apt299_(&c__1, &tolrns[j - 1], &c__0, &znumbr_1.z0);
     }
 /* L30: */
     }
 L999:
     return 0;
 } /* outtoh_ */
int outtol_ (integer * nmbr, doublereal * tlrns)
Definition at line 365 of file TOLER.c.
References apt232_(), apt299_(), bcdf_(), c__0, c__1, hold_1, i__, ibtflg, j, number, sv_1, tolrns, and znumbr_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static char ppword[6*3] = "INTOL " "OUTTOL" "TOLER ";
     static integer ithval[3] = { 8,9,4 };
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__, j;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt232_(integer *, doublereal *, doublereal *,
          doublereal *), apt299_();
     static integer icase, ibtflg;
 #define number ((integer *)&hsave_1 + 8)
     static integer ippwrd[2];
 #define tolrns ((doublereal *)&hsave_1)
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --tlrns;
     /* Function Body */
     icase = 2;
     for (i__ = 1; i__ <= 4; ++i__) {
 /* L5: */
     tolrns[i__ - 1] = tlrns[i__];
     }
     *number = *nmbr;
     if (hold_1.jhldfg == 0) {
     goto L200;
     }
     hold_1.itabh[hold_1.ithcnt - 1] = ithval[icase - 1];
     ++hold_1.ithcnt;
 L999:
     return 0;
 /* ---    OUTTOL, MAXDEVIATION SPECIFD ON CUTTER SIDE OF SURFACE */
 L200:
     if (ibtflg < 0) {
     ibtflg = 0;
     }
 /* L210: */
     apt232_(number, tolrns, sv_1.tau1, &znumbr_1.z1);
     ippwrd[0] = bcdf_(ppword + (icase - 1) * 6, (ftnlen)4);
     ippwrd[1] = bcdf_(ppword + ((icase - 1) * 6 + 4), (ftnlen)2);
     apt299_(number, ippwrd, &c__1, tolrns);
     if (*number <= 1) {
     goto L999;
     }
     i__1 = *number;
     for (j = 2; j <= i__1; j += 2) {
     if (j != *number) {
         apt299_(&c__1, &tolrns[j - 1], &c__1, &tolrns[j]);
     } else {
         apt299_(&c__1, &tolrns[j - 1], &c__0, &znumbr_1.z0);
     }
 /* L30: */
     }
     goto L999;
 } /* outtol_ */
int toler_ (integer * nmbr, doublereal * tlrns)
Definition at line 100 of file TOLER.c.
References apt232_(), apt299_(), bcdf_(), c__0, c__1, hold_1, i__, ifxcor_1, j, number, sv_1, tolrns, and znumbr_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static char ppword[6*3] = "INTOL " "OUTTOL" "TOLER ";
     static integer ithval[3] = { 8,9,4 };
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__, j;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt232_(integer *, doublereal *, doublereal *,
          doublereal *), apt299_();
     static integer icase;
 #define number ((integer *)&hsave_1 + 8)
     static integer ippwrd[2];
 #define tolrns ((doublereal *)&hsave_1)
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --tlrns;
     /* Function Body */
     icase = 3;
     for (i__ = 1; i__ <= 4; ++i__) {
 /* L5: */
     tolrns[i__ - 1] = tlrns[i__];
     }
     *number = *nmbr;
     if (hold_1.jhldfg == 0) {
     goto L300;
     }
     hold_1.itabh[hold_1.ithcnt - 1] = ithval[icase - 1];
     ++hold_1.ithcnt;
 L999:
     return 0;
 /* ---    OUTTOL, MAX DEVIATION ZERO ON SIDE AWAY FROM CUTTER */
 L300:
     i__1 = ifxcor_1.numsfs;
     for (i__ = 1; i__ <= i__1; ++i__) {
     sv_1.tau2[i__ - 1] = znumbr_1.z0;
 /* L350: */
     }
     apt232_(number, tolrns, sv_1.tau1, &znumbr_1.z1);
 /* ---    OUTPUT PART PROGRAM COMMAND ON EXFILE */
     ippwrd[0] = bcdf_(ppword + (icase - 1) * 6, (ftnlen)4);
     ippwrd[1] = bcdf_(ppword + ((icase - 1) * 6 + 4), (ftnlen)2);
     apt299_(number, ippwrd, &c__1, tolrns);
     if (*number <= 1) {
     goto L999;
     }
     i__1 = *number;
     for (j = 2; j <= i__1; j += 2) {
     if (j != *number) {
         apt299_(&c__1, &tolrns[j - 1], &c__1, &tolrns[j]);
     } else {
         apt299_(&c__1, &tolrns[j - 1], &c__0, &znumbr_1.z0);
     }
 /* L30: */
     }
     goto L999;
 } /* toler_ */
int tolerh_ (integer * nmbr, doublereal * tlrns)
Definition at line 494 of file TOLER.c.
References apt232_(), apt299_(), bcdf_(), c__0, c__1, i__, ifxcor_1, j, number, sv_1, tolrns, and znumbr_1.
Referenced by apt211_().
 {
     /* Initialized data */
     static char ppword[6*3] = "INTOL " "OUTTOL" "TOLER ";
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__, j;
     extern integer bcdf_(char *, ftnlen);
     extern /* Subroutine */ int apt232_(integer *, doublereal *, doublereal *,
          doublereal *), apt299_();
     static integer icase;
 #define number ((integer *)&hsave_1 + 8)
     static integer ippwrd[2];
 #define tolrns ((doublereal *)&hsave_1)
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     icase = 3;
 /* ---    OUTTOL, MAX DEVIATION ZERO ON SIDE AWAY FROM CUTTER */
     i__1 = ifxcor_1.numsfs;
     for (i__ = 1; i__ <= i__1; ++i__) {
     sv_1.tau2[i__ - 1] = znumbr_1.z0;
 /* L350: */
     }
     apt232_(number, tolrns, sv_1.tau1, &znumbr_1.z1);
     ippwrd[0] = bcdf_(ppword + (icase - 1) * 6, (ftnlen)4);
     ippwrd[1] = bcdf_(ppword + ((icase - 1) * 6 + 4), (ftnlen)2);
     apt299_(number, ippwrd, &c__1, tolrns);
     if (*number <= 1) {
     goto L999;
     }
     i__1 = *number;
     for (j = 2; j <= i__1; j += 2) {
     if (j != *number) {
         apt299_(&c__1, &tolrns[j - 1], &c__1, &tolrns[j]);
     } else {
         apt299_(&c__1, &tolrns[j - 1], &c__0, &znumbr_1.z0);
     }
 /* L30: */
     }
 L999:
     return 0;
 } /* tolerh_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 92 of file TOLER.c.
Referenced by intol_(), intolh_(), outtoh_(), outtol_(), toler_(), and tolerh_().
integer c__1 = 1 static
Definition at line 91 of file TOLER.c.
Referenced by intol_(), intolh_(), outtoh_(), outtol_(), toler_(), and tolerh_().
doublereal cc[15]
Definition at line 18 of file TOLER.c.
doublereal cos1[5]
Definition at line 35 of file TOLER.c.
doublereal cplfl[5]
Definition at line 35 of file TOLER.c.
doublereal cptst[5]
Definition at line 35 of file TOLER.c.
doublereal csd[5]
Definition at line 35 of file TOLER.c.
doublereal degrad
Definition at line 44 of file TOLER.c.
doublereal dplan[15]
Definition at line 35 of file TOLER.c.
doublereal dpmx1[5]
Definition at line 35 of file TOLER.c.
doublereal eps1[5]
Definition at line 18 of file TOLER.c.
doublereal eps2[5]
Definition at line 18 of file TOLER.c.
doublereal eps3[5]
Definition at line 18 of file TOLER.c.
doublereal eps4[5]
Definition at line 18 of file TOLER.c.
doublereal eps6[5]
Definition at line 18 of file TOLER.c.
doublereal eps8[5]
Definition at line 18 of file TOLER.c.
struct { ... } hold_
struct { ... } hsave_
integer i3dflg
Definition at line 52 of file TOLER.c.
integer iaerr
Definition at line 52 of file TOLER.c.
integer iamdct
Definition at line 62 of file TOLER.c.
integer iautps
Definition at line 52 of file TOLER.c.
integer ibegin
Definition at line 52 of file TOLER.c.
integer ic
Definition at line 52 of file TOLER.c.
integer icheck
Definition at line 52 of file TOLER.c.
integer icl
Definition at line 52 of file TOLER.c.
integer ics
Definition at line 52 of file TOLER.c.
integer icscnt
Definition at line 52 of file TOLER.c.
integer ictdef
Definition at line 52 of file TOLER.c.
integer icut
Definition at line 52 of file TOLER.c.
integer ids
Definition at line 52 of file TOLER.c.
integer ier
Definition at line 52 of file TOLER.c.
struct { ... } ifxcor_
integer igo
Definition at line 52 of file TOLER.c.
integer igoto
Definition at line 52 of file TOLER.c.
integer igoug
Definition at line 52 of file TOLER.c.
integer igs
Definition at line 52 of file TOLER.c.
integer inops
Definition at line 52 of file TOLER.c.
integer ipdpl
Definition at line 62 of file TOLER.c.
integer ips
Definition at line 52 of file TOLER.c.
integer ipsdef
Definition at line 52 of file TOLER.c.
integer ipt
Definition at line 62 of file TOLER.c.
integer ipt1
Definition at line 52 of file TOLER.c.
integer is
Definition at line 52 of file TOLER.c.
integer iseg
Definition at line 52 of file TOLER.c.
integer iseqno
Definition at line 52 of file TOLER.c.
struct { ... } ishr18_
integer isrch
Definition at line 52 of file TOLER.c.
integer istrup
Definition at line 52 of file TOLER.c.
integer it
Definition at line 52 of file TOLER.c.
integer itabh[100]
Definition at line 78 of file TOLER.c.
integer ithcnt
Definition at line 78 of file TOLER.c.
integer iws
Definition at line 62 of file TOLER.c.
integer j10
Definition at line 62 of file TOLER.c.
integer j12
Definition at line 62 of file TOLER.c.
integer j13
Definition at line 62 of file TOLER.c.
integer j54
Definition at line 62 of file TOLER.c.
integer jbr
Definition at line 52 of file TOLER.c.
integer jckr
Definition at line 62 of file TOLER.c.
integer jcnt1
Definition at line 62 of file TOLER.c.
integer jcnt2
Definition at line 62 of file TOLER.c.
integer jcnt3
Definition at line 62 of file TOLER.c.
integer jcpr
Definition at line 62 of file TOLER.c.
integer jcr
Definition at line 62 of file TOLER.c.
integer jdr
Definition at line 62 of file TOLER.c.
integer jfind
Definition at line 62 of file TOLER.c.
integer jgr
Definition at line 62 of file TOLER.c.
integer jhldfg
Definition at line 78 of file TOLER.c.
integer jmin
Definition at line 62 of file TOLER.c.
integer jminr
Definition at line 62 of file TOLER.c.
integer jpr
Definition at line 62 of file TOLER.c.
integer jpxr
Definition at line 62 of file TOLER.c.
integer jsw
Definition at line 52 of file TOLER.c.
integer jtkf
Definition at line 62 of file TOLER.c.
integer jtr
Definition at line 62 of file TOLER.c.
integer k0
Definition at line 70 of file TOLER.c.
integer k1
Definition at line 70 of file TOLER.c.
integer k10
Definition at line 70 of file TOLER.c.
integer k1013
Definition at line 70 of file TOLER.c.
integer k12
Definition at line 70 of file TOLER.c.
integer k13
Definition at line 70 of file TOLER.c.
integer k15
Definition at line 70 of file TOLER.c.
integer k16
Definition at line 70 of file TOLER.c.
integer k18
Definition at line 70 of file TOLER.c.
integer k19
Definition at line 70 of file TOLER.c.
integer k1e4
Definition at line 70 of file TOLER.c.
integer k1e6
Definition at line 70 of file TOLER.c.
integer k2
Definition at line 70 of file TOLER.c.
integer k23
Definition at line 70 of file TOLER.c.
integer k24
Definition at line 70 of file TOLER.c.
integer k25
Definition at line 70 of file TOLER.c.
integer k26
Definition at line 70 of file TOLER.c.
integer k27
Definition at line 70 of file TOLER.c.
integer k29
Definition at line 70 of file TOLER.c.
integer k3
Definition at line 70 of file TOLER.c.
integer k30
Definition at line 70 of file TOLER.c.
integer k31
Definition at line 70 of file TOLER.c.
integer k32
Definition at line 70 of file TOLER.c.
integer k33
Definition at line 70 of file TOLER.c.
integer k34
Definition at line 70 of file TOLER.c.
integer k4
Definition at line 70 of file TOLER.c.
integer k44
Definition at line 70 of file TOLER.c.
integer k45
Definition at line 70 of file TOLER.c.
integer k46
Definition at line 70 of file TOLER.c.
integer k47
Definition at line 70 of file TOLER.c.
integer k48
Definition at line 70 of file TOLER.c.
integer k5
Definition at line 70 of file TOLER.c.
integer k50
Definition at line 70 of file TOLER.c.
integer k51
Definition at line 70 of file TOLER.c.
integer k52
Definition at line 70 of file TOLER.c.
integer k6
Definition at line 70 of file TOLER.c.
integer k7
Definition at line 70 of file TOLER.c.
integer k8
Definition at line 70 of file TOLER.c.
integer k9
Definition at line 70 of file TOLER.c.
integer km1
Definition at line 70 of file TOLER.c.
struct { ... } knumbr_
integer lsv
Definition at line 52 of file TOLER.c.
integer lsv1
Definition at line 52 of file TOLER.c.
integer mantax
Definition at line 52 of file TOLER.c.
integer mdic
Definition at line 62 of file TOLER.c.
integer motmod
Definition at line 52 of file TOLER.c.
integer msav
Definition at line 52 of file TOLER.c.
integer mulout
Definition at line 52 of file TOLER.c.
integer nmbseg
Definition at line 52 of file TOLER.c.
integer nmpnts
Definition at line 52 of file TOLER.c.
integer nrec
Definition at line 52 of file TOLER.c.
integer numax
Definition at line 52 of file TOLER.c.
integer numcnt
Definition at line 52 of file TOLER.c.
integer nump
Definition at line 52 of file TOLER.c.
integer numpt1
Definition at line 52 of file TOLER.c.
integer numsfs
Definition at line 52 of file TOLER.c.
integer numsur
Definition at line 52 of file TOLER.c.
integer nw
Definition at line 52 of file TOLER.c.
integer nwds
Definition at line 52 of file TOLER.c.
doublereal past[5]
Definition at line 18 of file TOLER.c.
doublereal pi
Definition at line 44 of file TOLER.c.
doublereal plncs[5]
Definition at line 35 of file TOLER.c.
doublereal plnd[5]
Definition at line 18 of file TOLER.c.
doublereal plnd1[5]
Definition at line 35 of file TOLER.c.
doublereal plnv[15]
Definition at line 18 of file TOLER.c.
doublereal pltst[5]
Definition at line 35 of file TOLER.c.
doublereal rc[5]
Definition at line 18 of file TOLER.c.
doublereal s[5]
Definition at line 18 of file TOLER.c.
doublereal save[5]
Definition at line 18 of file TOLER.c.
doublereal saveh[50]
Definition at line 84 of file TOLER.c.
doublereal sfvct[15]
Definition at line 18 of file TOLER.c.
doublereal sk[15]
Definition at line 18 of file TOLER.c.
doublereal slx[15]
Definition at line 18 of file TOLER.c.
doublereal sn[15]
Definition at line 18 of file TOLER.c.
doublereal snk[15]
Definition at line 18 of file TOLER.c.
doublereal snl[15]
Definition at line 18 of file TOLER.c.
doublereal sp[15]
Definition at line 18 of file TOLER.c.
doublereal spk[15]
Definition at line 18 of file TOLER.c.
doublereal spl[15]
Definition at line 18 of file TOLER.c.
doublereal stck[5]
Definition at line 35 of file TOLER.c.
doublereal stck1[5]
Definition at line 35 of file TOLER.c.
doublereal stck2[5]
Definition at line 35 of file TOLER.c.
doublereal stckn[5]
Definition at line 35 of file TOLER.c.
struct { ... } sv1_
struct { ... } sv_
doublereal tau[5]
Definition at line 18 of file TOLER.c.
doublereal tau1[5]
Definition at line 18 of file TOLER.c.
doublereal tau2[5]
Definition at line 18 of file TOLER.c.
doublereal tee[15]
Definition at line 35 of file TOLER.c.
doublereal th[5]
Definition at line 18 of file TOLER.c.
doublereal tn[15]
Definition at line 18 of file TOLER.c.
doublereal tnl[15]
Definition at line 35 of file TOLER.c.
doublereal toolht[15]
Definition at line 18 of file TOLER.c.
doublereal toolwd[5]
Definition at line 18 of file TOLER.c.
doublereal tp[15]
Definition at line 18 of file TOLER.c.
doublereal tpk[15]
Definition at line 18 of file TOLER.c.
doublereal u1[15]
Definition at line 18 of file TOLER.c.
doublereal u1k[15]
Definition at line 18 of file TOLER.c.
doublereal varble[5]
Definition at line 18 of file TOLER.c.
doublereal vndir[15]
Definition at line 18 of file TOLER.c.
doublereal vt[15]
Definition at line 18 of file TOLER.c.
doublereal z0
Definition at line 44 of file TOLER.c.
doublereal z1
Definition at line 44 of file TOLER.c.
doublereal z10
Definition at line 44 of file TOLER.c.
doublereal z11em1
Definition at line 44 of file TOLER.c.
doublereal z12em1
Definition at line 44 of file TOLER.c.
doublereal z1e38
Definition at line 44 of file TOLER.c.
doublereal z1e6
Definition at line 44 of file TOLER.c.
doublereal z1em1
Definition at line 44 of file TOLER.c.
doublereal z1em2
Definition at line 44 of file TOLER.c.
doublereal z1em3
Definition at line 44 of file TOLER.c.
doublereal z1em5
Definition at line 44 of file TOLER.c.
doublereal z1em6
Definition at line 44 of file TOLER.c.
doublereal z1em7
Definition at line 44 of file TOLER.c.
doublereal z1em9
Definition at line 44 of file TOLER.c.
doublereal z2
Definition at line 44 of file TOLER.c.
doublereal z3
Definition at line 44 of file TOLER.c.
doublereal z5
Definition at line 44 of file TOLER.c.
doublereal z5em1
Definition at line 44 of file TOLER.c.
doublereal z5em6
Definition at line 44 of file TOLER.c.
doublereal z6em1
Definition at line 44 of file TOLER.c.
doublereal z90
Definition at line 44 of file TOLER.c.
doublereal z9em1
Definition at line 44 of file TOLER.c.
doublereal z__[5]
Definition at line 18 of file TOLER.c.
doublereal zm1
Definition at line 44 of file TOLER.c.
struct { ... } znumbr_