My Project: TRANSM.c File Reference
TRANSM.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define ldef_1 ldef_
#define knumbr_1 knumbr_
#define t (equiv_0)
#define t1 (equiv_1)
#define t2 (equiv_2)
#define t3 (equiv_3)
#define xt (equiv_0)
#define xt1 (equiv_1)
#define xt2 (equiv_2)
#define xt3 (equiv_3)
Functions
int transm_ (doublereal *so, doublereal *si, integer *ir, integer *in, integer *ie)
int transf_ (doublereal *so, doublereal *si, integer *ir, integer *in, integer *ie)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file TRANSM.c.
Referenced by transf_(), and transm_().
#define knumbr_1 knumbr_
Definition at line 37 of file TRANSM.c.
Referenced by transf_(), and transm_().
#define ldef_1 ldef_
Definition at line 29 of file TRANSM.c.
Referenced by transf_(), and transm_().
#define t (equiv_0)
Referenced by transf_(), and transm_().
#define t1 (equiv_1)
Referenced by transf_(), and transm_().
#define t2 (equiv_2)
Referenced by abw_(), ddpara_(), forcub_(), gcubic_(), gop_(), krumm_(), and transf_().
#define t3 (equiv_3)
Referenced by gop_(), krumm_(), transf_(), and transm_().
#define xt (equiv_0)
Referenced by scurv_(), and transm_().
#define xt1 (equiv_1)
Referenced by transm_().
#define xt2 (equiv_2)
Referenced by transm_().
#define xt3 (equiv_3)
Referenced by transm_().
Function Documentation
int transf_ (doublereal * so, doublereal * si, integer * ir, integer * in, integer * ie)
Definition at line 357 of file TRANSM.c.
References apt076_(), apt086_(), cirdef_(), ckdef_(), def_1, i__, in, knumbr_1, ldef_1, lindef_(), m, t, t1, t2, and t3.
Referenced by anglb_(), anglf_(), apt001_(), apt074_(), apt077_(), apt078_(), apt079_(), apt081_(), apt083_(), apt105_(), apt109_(), canf_(), gsurf_(), print_(), punch_(), and xcall_().
 {
     /* System generated locals */
     integer i__1;
     /* Local variables */
     static integer i__, m;
     static doublereal t[16], t1[16], t2[16], t3[16];
     static integer m11;
     extern /* Subroutine */ int apt076_(doublereal *, doublereal *,
         doublereal *, integer *), apt086_(doublereal *, doublereal *,
         integer *);
     extern logical ckdef_(doublereal *), cirdef_(doublereal *, integer *),
         lindef_(doublereal *, integer *);
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /* ...  ISHR16.INC HAS BEEN OMITTED, AS USEAGE OF I,J, */
 /* ...  M & M11 SEEMS TO BE LOCAL. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --si;
     --so;
     /* Function Body */
     if (*ie < 0) {
     goto L5;
     }
     ldef_1.unflag = ckdef_(&si[1]);
     if (ldef_1.unflag) {
     goto L999;
     }
 /* ...     DETERMINE WHETHER INPUT SURFACE HAS BEEN DEFINED */
 L5:
     i__1 = *in;
     for (i__ = 1; i__ <= i__1; ++i__) {
     t[i__ - 1] = si[i__];
 /* L10: */
     }
 /* ...     IF REFSYS NOT IN EFFECT MOVE ARRAY TO OUTPUT ARRAY */
 /* ---    GEOMETRIC MODE IS IN EFFECT */
     if (ldef_1.refflg) {
     goto L90;
     }
 L20:
     if (*ie < 0) {
     goto L61;
     }
     i__1 = *in;
     for (i__ = 1; i__ <= i__1; ++i__) {
     so[i__] = t[i__ - 1];
 /* L31: */
     }
     if (*ie == 0) {
     goto L999;
     }
     switch (*ir) {
     case 1:  goto L999;
     case 2:  goto L999;
     case 3:  goto L999;
     case 4:  goto L41;
     case 5:  goto L51;
     }
 L41:
     ldef_1.unflag = lindef_(t, ie);
     goto L999;
 L51:
     ldef_1.unflag = cirdef_(t, ie);
     goto L999;
 L61:
     i__1 = *in;
     for (i__ = 1; i__ <= i__1; ++i__) {
     def_1.r__[i__ - 1] = t[i__ - 1];
 /* L71: */
     }
     goto L999;
 L999:
     return 0;
 /* ...     SET M=1 FOR BASE TO LOCAL OR M=2 FOR LOCAL TO BASE AND */
 /* ...     TRANSFORM CANONICAL FORMS */
 L90:
     i__1 = *in;
     for (i__ = 1; i__ <= i__1; ++i__) {
     t1[i__ - 1] = t[i__ - 1];
 /* L95: */
     }
     m = knumbr_1.k1;
     if (*ie < 0) {
     m = knumbr_1.k2;
     }
     m11 = knumbr_1.k3 - m;
     switch (*ir) {
     case 1:  goto L100;
     case 2:  goto L300;
     case 3:  goto L300;
     case 4:  goto L400;
     case 5:  goto L300;
     }
 /* ...     QUADRIC CANONICAL FORM TRANSFORMATION */
 L100:
     t[1] = t1[6];
     t[2] = t1[5];
     t[3] = t1[7];
     t[4] = t1[6];
     t[5] = t1[1];
     t[6] = t1[4];
     t[7] = t1[8];
     t[8] = t1[5];
     t[9] = t1[4];
     t[10] = t1[2];
     t[11] = t1[9];
     t[12] = t1[7];
     t[13] = t1[8];
     t[14] = t1[9];
     t[15] = t1[3];
     for (i__ = 1; i__ <= 12; ++i__) {
     t3[i__ - 1] = def_1.a[i__ + m11 * 12 - 13];
 /* L200: */
     }
     t3[12] = 0.f;
     t3[13] = 0.f;
     t3[14] = 0.f;
     t3[15] = 1.f;
 /* ---    GEOMETRIC TRANSFORM CASE */
     apt076_(t1, t, t3, &knumbr_1.k4);
     apt086_(t2, t3, &knumbr_1.k4);
     apt076_(t, t2, t1, &knumbr_1.k4);
     t[4] = t[6];
     t[6] = t[1];
     t[1] = t[5];
     t[5] = t[2];
     t[2] = t[10];
     t[8] = t[7];
     t[7] = t[3];
     t[3] = t[15];
     t[9] = t[11];
     goto L20;
 /* ...     VECTOR CANONICAL FORM TRANSFORMATION */
 L300:
     for (i__ = 1; i__ <= 3; ++i__) {
     t[i__ - 1] = def_1.a[(i__ << 2) - 3 + m * 12 - 13] * t1[0] + def_1.a[(
         i__ << 2) - 2 + m * 12 - 13] * t1[1] + def_1.a[(i__ << 2) - 1
         + m * 12 - 13] * t1[2];
 /* L310: */
     }
     switch (*ir) {
     case 1:  goto L20;
     case 2:  goto L320;
     case 3:  goto L20;
     case 4:  goto L20;
     case 5:  goto L320;
     }
 /* ...     FINISH TRANSFORMATION FOR POINTS */
 L320:
     for (i__ = 1; i__ <= 3; ++i__) {
     t[i__ - 1] += def_1.a[(i__ << 2) + m * 12 - 13];
 /* L330: */
     }
     if (*ir != knumbr_1.k5) {
     goto L20;
     }
 /* ...     FINISH TRANSFORMATION FOR CIRCLES */
     for (i__ = 4; i__ <= 6; ++i__) {
     t[i__ - 1] = def_1.a[(i__ << 2) - 15 + m * 12 - 13] * t1[3] + def_1.a[
         (i__ << 2) - 14 + m * 12 - 13] * t1[4] + def_1.a[(i__ << 2) -
         13 + m * 12 - 13] * t1[5];
 /* L340: */
     }
     goto L20;
 /* ...     TRANSFORM NORMAL DISTANCE FOR LINES */
 L400:
     t[3] = t1[3] - t1[0] * def_1.a[m11 * 12 - 9] - t1[1] * def_1.a[m11 * 12 -
         5] - t1[2] * def_1.a[m11 * 12 - 1];
     goto L300;
 } /* transf_ */
int transm_ (doublereal * so, doublereal * si, integer * ir, integer * in, integer * ie)
Definition at line 76 of file TRANSM.c.
References def_1, f, i__, in, isize, isub, j, knumbr_1, ldef_1, m, mode, t, t1, t3, unpack_(), xt, xt1, xt2, and xt3.
Referenced by apt234_(), from_(), godlta_(), gol_(), gop_(), goretr_(), goto_(), indirp_(), indirv_(), intout_(), intsec_(), srfvct_(), and tlaxis_().
 {
     /* System generated locals */
     integer i__1;
     static doublereal equiv_0[16], equiv_1[16], equiv_2[16], equiv_3[16];
     /* Local variables */
     static integer i__, j, m;
 #define t (equiv_0)
 #define t1 (equiv_1)
 #define t2 (equiv_2)
 #define t3 (equiv_3)
 #define xt (equiv_0)
     static integer m11;
 #define xt1 (equiv_1)
 #define xt2 (equiv_2)
 #define xt3 (equiv_3)
     static integer mode, isub, isize;
     extern /* Subroutine */ int unpack_(doublereal *, integer *, integer *,
         integer *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /* ...  ISHR16.INC HAS BEEN OMITTED, AS USEAGE OF I,J, */
 /* ...  M & M11 SEEMS TO BE LOCAL. */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
 /* ...     DETERMINE WHETHER INPUT SURFACE HAS BEEN DEFINED */
     /* Parameter adjustments */
     --si;
     --so;
     /* Function Body */
     i__1 = *in;
     for (i__ = 1; i__ <= i__1; ++i__) {
 /* L10: */
     t[i__ - 1] = si[i__];
     }
 /* ...     IF REFSYS NOT IN EFFECT MOVE ARRAY TO OUTPUT ARRAY */
     if (! ldef_1.refmot) {
     goto L20;
     }
     if (! ldef_1.refflg) {
     goto L20;
     }
     j = 0;
     if (si[j] >= 2.1e7f || si[j] < 999999.f) {
     goto L20;
     }
     unpack_(&si[1], &mode, &isize, &isub);
     if (mode <= 0 || mode > 20) {
     goto L20;
     }
     if (*ir == 3 && mode != 20) {
     goto L20;
     }
     goto L90;
 L20:
     i__1 = *in;
     for (i__ = 1; i__ <= i__1; ++i__) {
 /* L30: */
     so[i__] = t[i__ - 1];
     }
 /* L999: */
     return 0;
 /* ...     SET M=1 FOR BASE TO LOCAL OR M=2 FOR LOCAL TO BASE AND */
 /* ...     TRANSFORM CANONICAL FORMS */
 L90:
     i__1 = *in;
     for (i__ = 1; i__ <= i__1; ++i__) {
 /* L95: */
     t1[i__ - 1] = t[i__ - 1];
     }
     m = knumbr_1.k1;
     if (*ie < 0) {
     m = knumbr_1.k2;
     }
     m11 = knumbr_1.k3 - m;
     switch (*ir) {
     case 1:  goto L100;
     case 2:  goto L300;
     case 3:  goto L300;
     case 4:  goto L400;
     case 5:  goto L300;
     }
 /* ...     QUADRIC CANONICAL FORM TRANSFORMATION */
 L100:
     t[1] = t1[6];
     t[2] = t1[5];
     t[3] = t1[7];
     t[4] = t1[6];
     t[5] = t1[1];
     t[6] = t1[4];
     t[7] = t1[8];
     t[8] = t1[5];
     t[9] = t1[4];
     t[10] = t1[2];
     t[11] = t1[9];
     t[12] = t1[7];
     t[13] = t1[8];
     t[14] = t1[9];
     t[15] = t1[3];
     for (i__ = 1; i__ <= 12; ++i__) {
 /* L200: */
     t3[i__ - 1] = def_1.a[i__ + m11 * 12 - 13];
     }
     t3[12] = 0.f;
     t3[13] = 0.f;
     t3[14] = 0.f;
     t3[15] = 1.f;
     for (i__ = 1; i__ <= 4; ++i__) {
     for (j = 1; j <= 4; ++j) {
         xt1[i__ + (j << 2) - 5] = 0.f;
         for (m = 1; m <= 4; ++m) {
 /* L250: */
         xt1[i__ + (j << 2) - 5] += xt[m + (j << 2) - 5] * xt3[i__ + (
             m << 2) - 5];
         }
     }
     }
     for (i__ = 1; i__ <= 4; ++i__) {
     for (j = 1; j <= 4; ++j) {
 /* L260: */
         xt2[j + (i__ << 2) - 5] = xt3[i__ + (j << 2) - 5];
     }
     }
     for (i__ = 1; i__ <= 4; ++i__) {
     for (j = 1; j <= 4; ++j) {
         xt[i__ + (j << 2) - 5] = 0.f;
         for (m = 1; m <= 4; ++m) {
 /* L270: */
         xt[i__ + (j << 2) - 5] += xt2[m + (j << 2) - 5] * xt1[i__ + (
             m << 2) - 5];
         }
     }
     }
 /* L271: */
     t[4] = t[6];
     t[6] = t[1];
     t[1] = t[5];
     t[5] = t[2];
     t[2] = t[10];
     t[8] = t[7];
     t[7] = t[3];
     t[3] = t[15];
     t[9] = t[11];
     goto L20;
 /* ...     VECTOR CANONICAL FORM TRANSFORMATION */
 L300:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L310: */
     t[i__ - 1] = def_1.a[(i__ << 2) - 3 + m * 12 - 13] * t1[0] + def_1.a[(
         i__ << 2) - 2 + m * 12 - 13] * t1[1] + def_1.a[(i__ << 2) - 1
         + m * 12 - 13] * t1[2];
     }
     switch (*ir) {
     case 1:  goto L20;
     case 2:  goto L320;
     case 3:  goto L20;
     case 4:  goto L20;
     case 5:  goto L320;
     }
 /* ...     FINISH TRANSFORMATION FOR POINTS */
 L320:
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L330: */
     t[i__ - 1] += def_1.a[(i__ << 2) + m * 12 - 13];
     }
     if (*ir != knumbr_1.k5) {
     goto L20;
     }
 /* ...     FINISH TRANSFORMATION FOR CIRCLES */
     for (i__ = 4; i__ <= 6; ++i__) {
 /* L340: */
     t[i__ - 1] = def_1.a[(i__ << 2) - 15 + m * 12 - 13] * t1[3] + def_1.a[
         (i__ << 2) - 14 + m * 12 - 13] * t1[4] + def_1.a[(i__ << 2) -
         13 + m * 12 - 13] * t1[5];
     }
     goto L20;
 /* ...     TRANSFORM NORMAL DISTANCE FOR LINES */
 L400:
     t[3] = t1[3] - t1[0] * def_1.a[m11 * 12 - 9] - t1[1] * def_1.a[m11 * 12 -
         5] - t1[2] * def_1.a[m11 * 12 - 1];
     goto L300;
 } /* transm_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file TRANSM.c.
doublereal ahold[8]
Definition at line 18 of file TRANSM.c.
logical altmlt
Definition at line 25 of file TRANSM.c.
logical bnderr
Definition at line 25 of file TRANSM.c.
logical boundf
Definition at line 25 of file TRANSM.c.
doublereal c1[8]
Definition at line 18 of file TRANSM.c.
logical canflg
Definition at line 25 of file TRANSM.c.
struct { ... } def_
logical jcs
Definition at line 25 of file TRANSM.c.
logical jds
Definition at line 25 of file TRANSM.c.
integer k0
Definition at line 32 of file TRANSM.c.
integer k1
Definition at line 32 of file TRANSM.c.
integer k10
Definition at line 32 of file TRANSM.c.
integer k1013
Definition at line 32 of file TRANSM.c.
integer k12
Definition at line 32 of file TRANSM.c.
integer k13
Definition at line 32 of file TRANSM.c.
integer k15
Definition at line 32 of file TRANSM.c.
integer k16
Definition at line 32 of file TRANSM.c.
integer k18
Definition at line 32 of file TRANSM.c.
integer k19
Definition at line 32 of file TRANSM.c.
integer k1e4
Definition at line 32 of file TRANSM.c.
integer k1e6
Definition at line 32 of file TRANSM.c.
integer k2
Definition at line 32 of file TRANSM.c.
integer k23
Definition at line 32 of file TRANSM.c.
integer k24
Definition at line 32 of file TRANSM.c.
integer k25
Definition at line 32 of file TRANSM.c.
integer k26
Definition at line 32 of file TRANSM.c.
integer k27
Definition at line 32 of file TRANSM.c.
integer k29
Definition at line 32 of file TRANSM.c.
integer k3
Definition at line 32 of file TRANSM.c.
integer k30
Definition at line 32 of file TRANSM.c.
integer k31
Definition at line 32 of file TRANSM.c.
integer k32
Definition at line 32 of file TRANSM.c.
integer k33
Definition at line 32 of file TRANSM.c.
integer k34
Definition at line 32 of file TRANSM.c.
integer k4
Definition at line 32 of file TRANSM.c.
integer k44
Definition at line 32 of file TRANSM.c.
integer k45
Definition at line 32 of file TRANSM.c.
integer k46
Definition at line 32 of file TRANSM.c.
integer k47
Definition at line 32 of file TRANSM.c.
integer k48
Definition at line 32 of file TRANSM.c.
integer k5
Definition at line 32 of file TRANSM.c.
integer k50
Definition at line 32 of file TRANSM.c.
integer k51
Definition at line 32 of file TRANSM.c.
integer k52
Definition at line 32 of file TRANSM.c.
integer k6
Definition at line 32 of file TRANSM.c.
integer k7
Definition at line 32 of file TRANSM.c.
integer k8
Definition at line 32 of file TRANSM.c.
integer k9
Definition at line 32 of file TRANSM.c.
integer km1
Definition at line 32 of file TRANSM.c.
struct { ... } knumbr_
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file TRANSM.c.
logical pchlst
Definition at line 25 of file TRANSM.c.
logical prnton
Definition at line 25 of file TRANSM.c.
doublereal r__[10]
Definition at line 18 of file TRANSM.c.
doublereal ref[8]
Definition at line 18 of file TRANSM.c.
logical refflg
Definition at line 25 of file TRANSM.c.
logical refmot
Definition at line 25 of file TRANSM.c.
logical subflg
Definition at line 25 of file TRANSM.c.
logical tabprt
Definition at line 25 of file TRANSM.c.
logical unflag
Definition at line 25 of file TRANSM.c.
logical zflag
Definition at line 25 of file TRANSM.c.