My Project: TWOARG.c File Reference
TWOARG.c File Reference
#include "f2c.h"
Macros
#define nametb_1 nametb_
#define cnamtb_1 cnamtb_
#define iltext_1 iltext_
#define opmod_1 opmod_
#define numblk_1 numblk_
#define comfin ((logical *)&iltext_1)
#define hexdlr ((integer *)&opmod_1 + 6)
#define sptdlr ((integer *)&opmod_1 + 7)
#define textin ((integer *)&iltext_1 + 4)
#define tpntrx ((integer *)&iltext_1 + 2)
Functions
int twoarg_ (integer *i__, integer *j)
Variables
struct {
integer charst
integer charnd
integer inamst
integer inamnd
integer namest
integer nammax
integer ifixst
integer ifixnd
integer numbst
integer numbnd
integer namtbl [3000]
} nametb_
struct {
char cnamtb [18000]
char cnumtb [36000]
} cnamtb_
struct {
integer iltext [94]
} iltext_
struct {
integer opmod [8]
} opmod_
struct {
integer mnmbnd
integer numidx
integer nmbrs
integer lstchr
integer masgnd
} numblk_
static integer c__0 = 0
static integer c__8 = 8
Macro Definition Documentation
#define cnamtb_1 cnamtb_
Definition at line 28 of file TWOARG.c.
Referenced by twoarg_().
#define comfin ((logical *)&iltext_1)
Referenced by twoarg_().
#define hexdlr ((integer *)&opmod_1 + 6)
Referenced by twoarg_().
#define iltext_1 iltext_
Definition at line 34 of file TWOARG.c.
#define nametb_1 nametb_
Definition at line 22 of file TWOARG.c.
Referenced by twoarg_().
#define numblk_1 numblk_
Definition at line 46 of file TWOARG.c.
Referenced by twoarg_().
#define opmod_1 opmod_
Definition at line 40 of file TWOARG.c.
#define sptdlr ((integer *)&opmod_1 + 7)
Referenced by twoarg_().
#define textin ((integer *)&iltext_1 + 4)
Referenced by twoarg_().
#define tpntrx ((integer *)&iltext_1 + 2)
Referenced by twoarg_().
Function Documentation
int twoarg_ (integer * i__, integer * j)
Definition at line 82 of file TWOARG.c.
References alarm_(), c__0, c__8, cnamtb_1, comfin, hexdlr, i__, ierror, j, k, nametb_1, numblk_1, sptdlr, textin, and tpntrx.
Referenced by argcvt_(), asnjpz_(), boolif_(), calmcx_(), goloft_(), gopat_(), inpat_(), larges_(), lcanon_(), motion_(), pro020_(), pro021_(), pro026_(), pro027_(), pro028_(), recog_(), recogn_(), resrvz_(), ssdef_(), and tssmil_().
 {
     /* System generated locals */
     integer i__1;
     /* Builtin functions */
     integer i_indx(char *, char *, ftnlen, ftnlen), s_cmp(char *, char *,
         ftnlen, ftnlen);
     /* Local variables */
     static integer k, idp;
     extern /* Subroutine */ int alarm_(integer *, integer *, integer *, char *
         , ftnlen);
 #define comfin ((logical *)&iltext_1)
 #define hexdlr ((integer *)&opmod_1 + 6)
     static integer ierror;
 #define sptdlr ((integer *)&opmod_1 + 7)
 #define textin ((integer *)&iltext_1 + 4)
 #define tpntrx ((integer *)&iltext_1 + 2)
 /*        1.    NAME TABLE AND TABLE LIMITS */
 /* CNUMTB:      NUMBER TABLE */
 /*       19.    INTERMEDIATE LANGUAGE TEXT */
 /* COMFIN:      TRUE IF I.L. OPERATION CODE GIVEN */
 /* TPNTRX:      POINTER TO LAST TEXTIN ENTRY */
 /* TEXTIN:      STORAGE FOR CURRENTLY GENERATED I.L. COMMAND ARGUM.LIST */
 /*       27.    OPERAND MODIFIERS */
 /* HEXDLR:      CONTAINS OPERAND TYPE CODE 6 */
 /* SPTDLR:      CONTAINS OPERAND TYPE CODE 7 */
 /*       45.    NUMBER TABLE INDICES */
 /* MNMBND:      LAST NAME TABLE ENTRY TO MACRO ASSIGNED NUMBER SECTION */
 /* NMBRS:       QUANTITY OF NUMBERS IN THE CURRENT STATEMENT */
 /* * */
 /* ARGUMENTS    I         NORMALLY TYPE DESIGNATION OF */
 /*                        ARGUMENT J.  COULD BE A NAME */
 /*                        TABLE (NAMTBL) INDEX OF NUMBER. */
 /*              J         NAME TABLE (NAMTBL) INDEX OF */
 /* **                      ARGUMENT. */
 /*       45.    NUMBER TABLE INDICES */
 /* MNMBND:      LAST NAME TABLE ENTRY TO MACRO ASSIGNED NUMBER SECTION */
 /* NUMIDX:      NAMTBL INDEX OF A NUMBER GIVEN IN THE CURRENT STATEMENT */
 /*  NMBRS:      QUANTITY OF NUMBERS IN THE CURRENT STATEMENT */
 /* LSTCHR:      LAST CHARACTER OF A NUMBER */
 /* MASGND:      NAME TABLE INDEX OF SECTION END FOR NUMBERS ASSIGNMENT */
     if (*comfin) {
     goto L10;
     }
     ierror = 3;
     goto L90;
 L10:
     if (*tpntrx < 89) {
     goto L20;
     }
     ierror = 2;
 L90:
     alarm_(&ierror, &c__0, &c__8, "TWOARG  ", (ftnlen)8);
     goto L100;
 L20:
     k = *i__;
     if (*j <= numblk_1.mnmbnd + nametb_1.nammax) {
     goto L30;
     }
 /*     HEXDLR: INDICATES NON FRACTIONAL REAL LITERAL */
 /*     SPTDLR: INDICATES FRACTIONAL REAL LITERAL */
     k = *hexdlr;
     idp = i_indx(cnamtb_1.cnumtb + (*j - nametb_1.nammax - 1) * 12, ".", (
         ftnlen)12, (ftnlen)1);
     i__1 = idp;
     if (s_cmp(cnamtb_1.cnumtb + ((*j - nametb_1.nammax - 1) * 12 + i__1),
         " ", 12 - i__1, (ftnlen)1) == 0) {
     goto L30;
     }
     k = *sptdlr;
     ++numblk_1.nmbrs;
 L30:
     textin[*tpntrx] = k;
     textin[*tpntrx + 1] = *j;
     *tpntrx += 2;
 L100:
     return 0;
 } /* twoarg_ */
Variable Documentation
integer c__0 = 0 static
Definition at line 50 of file TWOARG.c.
Referenced by twoarg_().
integer c__8 = 8 static
Definition at line 51 of file TWOARG.c.
Referenced by twoarg_().
integer charnd
Definition at line 18 of file TWOARG.c.
integer charst
Definition at line 18 of file TWOARG.c.
char cnamtb[18000]
Definition at line 25 of file TWOARG.c.
struct { ... } cnamtb_
char cnumtb[36000]
Definition at line 25 of file TWOARG.c.
integer ifixnd
Definition at line 18 of file TWOARG.c.
integer ifixst
Definition at line 18 of file TWOARG.c.
integer iltext[94]
Definition at line 31 of file TWOARG.c.
struct { ... } iltext_
integer inamnd
Definition at line 18 of file TWOARG.c.
integer inamst
Definition at line 18 of file TWOARG.c.
integer lstchr
Definition at line 43 of file TWOARG.c.
integer masgnd
Definition at line 43 of file TWOARG.c.
integer mnmbnd
Definition at line 43 of file TWOARG.c.
integer namest
Definition at line 18 of file TWOARG.c.
struct { ... } nametb_
integer nammax
Definition at line 18 of file TWOARG.c.
integer namtbl[3000]
Definition at line 18 of file TWOARG.c.
integer nmbrs
Definition at line 43 of file TWOARG.c.
struct { ... } numblk_
integer numbnd
Definition at line 18 of file TWOARG.c.
integer numbst
Definition at line 18 of file TWOARG.c.
integer numidx
Definition at line 43 of file TWOARG.c.
integer opmod[8]
Definition at line 37 of file TWOARG.c.
struct { ... } opmod_