My Project: TXHULL.c File Reference
TXHULL.c File Reference
#include "f2c.h"
Functions
int txhull_ (doublereal *rc, doublereal *rcnorm, doublereal *r1, doublereal *r2, doublereal *r3, doublereal *tlen, doublereal *toolax, doublereal *tooltp, doublereal *toolce, doublereal *ct, doublereal *hrad, doublereal *hcent)
Function Documentation
int txhull_ (doublereal * rc, doublereal * rcnorm, doublereal * r1, doublereal * r2, doublereal * r3, doublereal * tlen, doublereal * toolax, doublereal * tooltp, doublereal * toolce, doublereal * ct, doublereal * hrad, doublereal * hcent)
Definition at line 17 of file TXHULL.c.
References a, b, c__, dotf_(), i__, ra, rc, rr1, vecmod_(), and w1.
Referenced by curint_().
 {
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     static doublereal a, b, c__;
     static integer i__;
     static doublereal w1[3], ra, tr, rr1;
     extern /* Subroutine */ int dotf_(doublereal *, doublereal *, doublereal *
         ), vecmod_(doublereal *, doublereal *);
 /* .... HULL CENTRE */
 /*     CALCULATE RADIUS OF MINIMUM ENCLOSING SPHERE */
     /* Parameter adjustments */
     --hcent;
     --toolce;
     --tooltp;
     --toolax;
     --rcnorm;
     --rc;
     /* Function Body */
     rr1 = *r1 * *r1;
     for (i__ = 1; i__ <= 3; ++i__) {
     w1[i__ - 1] = toolce[i__] - rc[i__];
 /* L10: */
     }
     dotf_(&b, w1, &toolax[1]);
     vecmod_(w1, &c__);
     ra = sqrt(c__ * c__ - b * b);
     if (ra + 1e-6 >= *r1 || ra <= *r3) {
     *hrad = 1e5;
     } else {
 /*     CALC RADIUS OF SPHERE ON R AND ON POINT ON TOP OF TOOL OPPOSITE TO */
     a = ra + *r1;
     b = *tlen - *r2 + b;
 /* .... HRAD IS RADIUS */
     *hrad = sqrt(a * a + b * b) * .5f;
     if (*hrad > 1e5) {
         *hrad = 1e5;
     } else {
 /*     CALC. MAXIMUM RADIUS OF CURVATURE OF TOOL AT R AS TR */
         dotf_(&a, &rcnorm[1], &toolax[1]);
         if (a < 1e-6 || abs(a) - 1. < 1e-6) {
         *hrad = 1e5;
         } else {
         tr = *r2 + *r3 / sqrt(1 - a * a);
         if (tr > 1e5) {
             *hrad = 1e5;
         } else {
             *hrad = max(*hrad,tr);
         }
         }
     }
     }
 /* .... CT IS CURVATURE OF ENCLOSING SPHERE ON R */
     *ct = 1 / *hrad;
     for (i__ = 1; i__ <= 3; ++i__) {
     hcent[i__] = rc[i__] + *hrad * rcnorm[i__];
 /* L40: */
     }
     return 0;
 } /* txhull_ */