My Project: U1COMP.c File Reference
U1COMP.c File Reference
#include "f2c.h"
Macros
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define ishr18_1 ishr18_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int u1comp_ (void)
Variables
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
integer iamdct
integer ipdpl
integer ipt
integer iws
integer jckr
integer jcnt1
integer jcnt2
integer jcnt3
integer jcpr
integer jcr
integer jdr
integer jfind
integer jgr
integer jmin
integer jminr
integer jpr
integer jpxr
integer jtkf
integer jtr
integer j10
integer j12
integer j13
integer j54
integer mdic
} ishr18_
static integer c__26401 = 26401
Macro Definition Documentation
#define charct_1 charct_
Definition at line 30 of file U1COMP.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define fxcor_1 fxcor_
Definition at line 24 of file U1COMP.c.
Referenced by u1comp_().
#define ifxcor_1 ifxcor_
Definition at line 89 of file U1COMP.c.
Referenced by u1comp_().
#define ishr18_1 ishr18_
Definition at line 97 of file U1COMP.c.
#define isv1_1 isv1_
Definition at line 79 of file U1COMP.c.
#define isv_1 isv_
Definition at line 72 of file U1COMP.c.
Referenced by u1comp_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sv1_1 sv1_
Definition at line 63 of file U1COMP.c.
#define sv_1 sv_
Definition at line 54 of file U1COMP.c.
Referenced by u1comp_().
#define tlldat_1 tlldat_
Definition at line 37 of file U1COMP.c.
Function Documentation
int u1comp_ (void)
Definition at line 106 of file U1COMP.c.
References aerr_(), c__26401, dotf_(), fxcor_1, i__, ifxcor_1, isv_1, one, sv_1, vnorm_(), w1, and zero.
Referenced by amind_(), and cplan_().
 {
     /* Initialized data */
     static doublereal zlit1 = 9e-5;
     static doublereal zlit2 = 1e-10;
     static doublereal zlit3 = 1e-4;
     static doublereal zero = 0.;
     static doublereal one = 1.;
     /* System generated locals */
     doublereal d__1, d__2;
     /* Local variables */
     static integer i__;
     static doublereal w1;
     extern /* Subroutine */ int aerr_(integer *, char *, ftnlen), dotf_(
         doublereal *, doublereal *, doublereal *);
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     extern /* Subroutine */ int vnorm_(doublereal *, doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*             /-COMPUTE UNIT VECTOR U1 PERPENDICULAR TO TA TO SELECT */
 /*             /-PROPER SIDE OF CUTTER */
 /*             /-U1 SHOULD POINT OUTWARD FROM TA */
 /*             /-CURRENT CENTER OF CURVATURE CC IS THE PRIMARY INPUT. */
 /*   *** 18.  ISHARE18 BLOCK  *** */
 /*   I,J,K,L,M,N HAVE BEEN REMOVED FROM FRONT OF THIS BLOCK, */
 /*   AS THEY APPEAR TO BE USED AS LOCAL VARIABLES. */
     for (i__ = 1; i__ <= 3; ++i__) {
     fxcor_1.temp[i__ - 1] = sv_1.cc[i__ + ifxcor_1.is * 3 - 4] -
         fxcor_1.te[i__ - 1];
 /* L1: */
     }
     dotf_(&w1, fxcor_1.temp, fxcor_1.ta);
 /*             /-INTIAL U1 POINTS FROM TA OUTWARD TO CC */
     for (i__ = 1; i__ <= 3; ++i__) {
 /* L2: */
     sv_1.u1[i__ + ifxcor_1.is * 3 - 4] = fxcor_1.temp[i__ - 1] - w1 *
         fxcor_1.ta[i__ - 1];
     }
     vnorm_(&sv_1.u1[ifxcor_1.is * 3 - 3], &sv_1.u1[ifxcor_1.is * 3 - 3]);
 /*             /-FIRST U1 POINTS DIRECTLY FROM CC TOWARD TOOL AXIS */
     if (ifxcor_1.ier != 0) {
     goto L3;
     }
 /*              /-U1 SHOULD BE PERPENDICULAR TO TA IN NORMAL CASE */
     dotf_(&w1, fxcor_1.ta, &sv_1.u1[ifxcor_1.is * 3 - 3]);
     if (abs(w1) < zlit3) {
     goto L18;
     }
 /*             /-U1 TOO SMALL, SELECT ANOTHER U1 */
 L3:
     if (abs(fxcor_1.ta[2]) >= zlit1) {
     goto L4;
     }
 /*             /-K OF TOOL AXIS TOO SMALL, GIVE U1 A K COMPONENT */
     sv_1.u1[ifxcor_1.is * 3 - 3] = zero;
     sv_1.u1[ifxcor_1.is * 3 - 2] = zero;
     sv_1.u1[ifxcor_1.is * 3 - 1] = one;
     goto L18;
 L4:
 /* Computing 2nd power */
     d__1 = fxcor_1.ta[0];
 /* Computing 2nd power */
     d__2 = fxcor_1.ta[1];
     w1 = d__1 * d__1 + d__2 * d__2;
     if (abs(w1) >= zlit2) {
     goto L5;
     }
 /*             /-TA IS INSIGNIFICANT, SET U1 IN I DIRECTION */
     sv_1.u1[ifxcor_1.is * 3 - 3] = one;
     sv_1.u1[ifxcor_1.is * 3 - 2] = zero;
     sv_1.u1[ifxcor_1.is * 3 - 1] = zero;
     goto L18;
 L5:
     fxcor_1.temp[0] = fxcor_1.ta[0];
     fxcor_1.temp[1] = fxcor_1.ta[1];
     fxcor_1.temp[2] = -w1 / fxcor_1.ta[2];
     vnorm_(fxcor_1.temp, &sv_1.u1[ifxcor_1.is * 3 - 3]);
     if (ifxcor_1.ier == 0) {
     goto L18;
     }
 /*             /-U1 IS NOT COMPUTABLE DUE TO POORLY CONDITIONED TA */
     aerr_(&c__26401, "U1COMP  ", (ftnlen)8);
     goto L999;
 L18:
 /*             /-U1 NOW SET, MODIFY SIGN DEPENDING ON TOOL TO SURF RELAT */
     dotf_(&w1, &sv_1.u1[ifxcor_1.is * 3 - 3], &sv_1.sn[ifxcor_1.is * 3 - 3]);
 /*             /-U1 OPPOSED TO SN FOR SN CONTROL */
     if (w1 < zlit3 && isv_1.jtn[ifxcor_1.is - 1] == 0) {
     goto L999;
     }
 /*             /-U1 AGREES WITH SN(AND TN) FOR TN CONTROL */
     if (w1 >= zero && isv_1.jtn[ifxcor_1.is - 1] != 0) {
     goto L999;
     }
 /*             /-REVERSE SIGN OF U1 */
     for (i__ = 1; i__ <= 3; ++i__) {
     sv_1.u1[i__ + ifxcor_1.is * 3 - 4] = -sv_1.u1[i__ + ifxcor_1.is * 3 -
         4];
 /* L12: */
     }
 L999:
     return 0;
 } /* u1comp_ */
Variable Documentation
doublereal alp
Definition at line 18 of file U1COMP.c.
doublereal ax4[3]
Definition at line 18 of file U1COMP.c.
integer c__26401 = 26401 static
Definition at line 101 of file U1COMP.c.
Referenced by u1comp_().
doublereal cagl
Definition at line 18 of file U1COMP.c.
doublereal cc[15]
Definition at line 40 of file U1COMP.c.
struct { ... } charct_
doublereal corrad[8]
Definition at line 33 of file U1COMP.c.
doublereal cos1[5]
Definition at line 57 of file U1COMP.c.
doublereal cplfl[5]
Definition at line 57 of file U1COMP.c.
doublereal cptst[5]
Definition at line 57 of file U1COMP.c.
doublereal csd[5]
Definition at line 57 of file U1COMP.c.
doublereal cutdat[7]
Definition at line 18 of file U1COMP.c.
doublereal dplan[15]
Definition at line 57 of file U1COMP.c.
doublereal dpmax
Definition at line 18 of file U1COMP.c.
doublereal dpmx1[5]
Definition at line 57 of file U1COMP.c.
doublereal eps1[5]
Definition at line 40 of file U1COMP.c.
doublereal eps2[5]
Definition at line 40 of file U1COMP.c.
doublereal eps3[5]
Definition at line 40 of file U1COMP.c.
doublereal eps4[5]
Definition at line 40 of file U1COMP.c.
doublereal eps6[5]
Definition at line 40 of file U1COMP.c.
doublereal eps8[5]
Definition at line 40 of file U1COMP.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 18 of file U1COMP.c.
doublereal hi
Definition at line 18 of file U1COMP.c.
integer i3dflg
Definition at line 82 of file U1COMP.c.
integer iaerr
Definition at line 82 of file U1COMP.c.
integer iafl[5]
Definition at line 66 of file U1COMP.c.
integer iamdct
Definition at line 92 of file U1COMP.c.
integer iautps
Definition at line 82 of file U1COMP.c.
integer ibegin
Definition at line 82 of file U1COMP.c.
integer ic
Definition at line 82 of file U1COMP.c.
integer icanon[5]
Definition at line 66 of file U1COMP.c.
integer icheck
Definition at line 82 of file U1COMP.c.
integer icl
Definition at line 82 of file U1COMP.c.
integer ics
Definition at line 82 of file U1COMP.c.
integer icscnt
Definition at line 82 of file U1COMP.c.
integer ictdef
Definition at line 82 of file U1COMP.c.
integer icut
Definition at line 82 of file U1COMP.c.
integer ids
Definition at line 82 of file U1COMP.c.
integer ier
Definition at line 82 of file U1COMP.c.
integer ifar[5]
Definition at line 75 of file U1COMP.c.
integer ifl4[5]
Definition at line 75 of file U1COMP.c.
struct { ... } ifxcor_
integer igo
Definition at line 82 of file U1COMP.c.
integer igoto
Definition at line 82 of file U1COMP.c.
integer igoug
Definition at line 82 of file U1COMP.c.
integer igs
Definition at line 82 of file U1COMP.c.
integer index[5]
Definition at line 66 of file U1COMP.c.
integer indir__[5]
Definition at line 66 of file U1COMP.c.
integer inops
Definition at line 82 of file U1COMP.c.
integer iop[5]
Definition at line 66 of file U1COMP.c.
integer iopset[5]
Definition at line 66 of file U1COMP.c.
integer ipdpl
Definition at line 92 of file U1COMP.c.
integer ipl[5]
Definition at line 66 of file U1COMP.c.
integer ips
Definition at line 82 of file U1COMP.c.
integer ipsdef
Definition at line 82 of file U1COMP.c.
integer ipt
Definition at line 92 of file U1COMP.c.
integer ipt1
Definition at line 82 of file U1COMP.c.
integer is
Definition at line 82 of file U1COMP.c.
integer iseg
Definition at line 82 of file U1COMP.c.
integer iseqno
Definition at line 82 of file U1COMP.c.
integer isfidn[5]
Definition at line 66 of file U1COMP.c.
integer isftyp[5]
Definition at line 66 of file U1COMP.c.
struct { ... } ishr18_
integer isigcr[5]
Definition at line 66 of file U1COMP.c.
integer isrch
Definition at line 82 of file U1COMP.c.
integer istrup
Definition at line 82 of file U1COMP.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 66 of file U1COMP.c.
integer it
Definition at line 82 of file U1COMP.c.
integer itlon[5]
Definition at line 66 of file U1COMP.c.
integer itseg[5]
Definition at line 66 of file U1COMP.c.
integer itsegk[5]
Definition at line 66 of file U1COMP.c.
integer iunfl[5]
Definition at line 66 of file U1COMP.c.
integer iws
Definition at line 92 of file U1COMP.c.
integer j10
Definition at line 92 of file U1COMP.c.
integer j12
Definition at line 92 of file U1COMP.c.
integer j13
Definition at line 92 of file U1COMP.c.
integer j20[5]
Definition at line 75 of file U1COMP.c.
integer j21[5]
Definition at line 75 of file U1COMP.c.
integer j22[5]
Definition at line 75 of file U1COMP.c.
integer j23[5]
Definition at line 75 of file U1COMP.c.
integer j50[5]
Definition at line 75 of file U1COMP.c.
integer j51[5]
Definition at line 75 of file U1COMP.c.
integer j54
Definition at line 92 of file U1COMP.c.
integer jbr
Definition at line 82 of file U1COMP.c.
integer jckr
Definition at line 92 of file U1COMP.c.
integer jcnt1
Definition at line 92 of file U1COMP.c.
integer jcnt2
Definition at line 92 of file U1COMP.c.
integer jcnt3
Definition at line 92 of file U1COMP.c.
integer jcpr
Definition at line 92 of file U1COMP.c.
integer jcr
Definition at line 92 of file U1COMP.c.
integer jdr
Definition at line 92 of file U1COMP.c.
integer jent[5]
Definition at line 66 of file U1COMP.c.
integer jfind
Definition at line 92 of file U1COMP.c.
integer jgr
Definition at line 92 of file U1COMP.c.
integer jiops[5]
Definition at line 66 of file U1COMP.c.
integer jmin
Definition at line 92 of file U1COMP.c.
integer jminr
Definition at line 92 of file U1COMP.c.
integer jph[5]
Definition at line 75 of file U1COMP.c.
integer jpr
Definition at line 92 of file U1COMP.c.
integer jpxr
Definition at line 92 of file U1COMP.c.
integer jsw
Definition at line 82 of file U1COMP.c.
integer jtkf
Definition at line 92 of file U1COMP.c.
integer jtlflg[5]
Definition at line 66 of file U1COMP.c.
integer jtn[5]
Definition at line 66 of file U1COMP.c.
integer jtr
Definition at line 92 of file U1COMP.c.
integer ju1[5]
Definition at line 66 of file U1COMP.c.
integer limfl[5]
Definition at line 66 of file U1COMP.c.
integer lsv
Definition at line 82 of file U1COMP.c.
integer lsv1
Definition at line 82 of file U1COMP.c.
integer mantax
Definition at line 82 of file U1COMP.c.
integer mdic
Definition at line 92 of file U1COMP.c.
char modfer[6]
Definition at line 27 of file U1COMP.c.
integer motmod
Definition at line 82 of file U1COMP.c.
integer msav
Definition at line 82 of file U1COMP.c.
integer mulout
Definition at line 82 of file U1COMP.c.
integer nmbseg
Definition at line 82 of file U1COMP.c.
integer nmpnts
Definition at line 82 of file U1COMP.c.
integer notan[5]
Definition at line 75 of file U1COMP.c.
integer nrec
Definition at line 82 of file U1COMP.c.
integer numax
Definition at line 82 of file U1COMP.c.
integer numcnt
Definition at line 82 of file U1COMP.c.
integer nump
Definition at line 82 of file U1COMP.c.
integer numpt1
Definition at line 82 of file U1COMP.c.
integer numsfs
Definition at line 82 of file U1COMP.c.
integer numsur
Definition at line 82 of file U1COMP.c.
integer nw
Definition at line 82 of file U1COMP.c.
integer nwds
Definition at line 82 of file U1COMP.c.
doublereal past[5]
Definition at line 40 of file U1COMP.c.
doublereal plncs[5]
Definition at line 57 of file U1COMP.c.
doublereal plnd[5]
Definition at line 40 of file U1COMP.c.
doublereal plnd1[5]
Definition at line 57 of file U1COMP.c.
doublereal plnv[15]
Definition at line 40 of file U1COMP.c.
doublereal pltst[5]
Definition at line 57 of file U1COMP.c.
doublereal pmove[3]
Definition at line 18 of file U1COMP.c.
doublereal ra
Definition at line 18 of file U1COMP.c.
doublereal rc[5]
Definition at line 40 of file U1COMP.c.
doublereal rc1
Definition at line 18 of file U1COMP.c.
doublereal ri[8]
Definition at line 33 of file U1COMP.c.
doublereal s[5]
Definition at line 40 of file U1COMP.c.
doublereal sagl
Definition at line 18 of file U1COMP.c.
doublereal save[5]
Definition at line 40 of file U1COMP.c.
doublereal sfvct[15]
Definition at line 40 of file U1COMP.c.
doublereal sk[15]
Definition at line 40 of file U1COMP.c.
doublereal slx[15]
Definition at line 40 of file U1COMP.c.
doublereal sn[15]
Definition at line 40 of file U1COMP.c.
doublereal snk[15]
Definition at line 40 of file U1COMP.c.
doublereal snl[15]
Definition at line 40 of file U1COMP.c.
doublereal sp[15]
Definition at line 40 of file U1COMP.c.
doublereal spk[15]
Definition at line 40 of file U1COMP.c.
doublereal spl[15]
Definition at line 40 of file U1COMP.c.
doublereal stck[5]
Definition at line 57 of file U1COMP.c.
doublereal stck1[5]
Definition at line 57 of file U1COMP.c.
doublereal stck2[5]
Definition at line 57 of file U1COMP.c.
doublereal stckn[5]
Definition at line 57 of file U1COMP.c.
doublereal strtno
Definition at line 18 of file U1COMP.c.
doublereal surd
Definition at line 18 of file U1COMP.c.
struct { ... } sv1_
struct { ... } sv_
doublereal ta[3]
Definition at line 18 of file U1COMP.c.
doublereal tak[3]
Definition at line 18 of file U1COMP.c.
doublereal tal[3]
Definition at line 18 of file U1COMP.c.
doublereal tanhi[8]
Definition at line 33 of file U1COMP.c.
doublereal tanlo[8]
Definition at line 33 of file U1COMP.c.
doublereal tau[5]
Definition at line 40 of file U1COMP.c.
doublereal tau1[5]
Definition at line 40 of file U1COMP.c.
doublereal tau2[5]
Definition at line 40 of file U1COMP.c.
doublereal tcont[9]
Definition at line 33 of file U1COMP.c.
doublereal te[3]
Definition at line 18 of file U1COMP.c.
doublereal tee[15]
Definition at line 57 of file U1COMP.c.
doublereal tek[3]
Definition at line 18 of file U1COMP.c.
doublereal tel[3]
Definition at line 18 of file U1COMP.c.
doublereal tem[10]
Definition at line 18 of file U1COMP.c.
doublereal temp[24]
Definition at line 18 of file U1COMP.c.
doublereal th[5]
Definition at line 40 of file U1COMP.c.
doublereal ti[3]
Definition at line 18 of file U1COMP.c.
doublereal tik[3]
Definition at line 18 of file U1COMP.c.
doublereal til[3]
Definition at line 18 of file U1COMP.c.
doublereal tlhit
Definition at line 18 of file U1COMP.c.
doublereal tlhite[8]
Definition at line 33 of file U1COMP.c.
doublereal tlinc[9]
Definition at line 33 of file U1COMP.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 18 of file U1COMP.c.
doublereal tn[15]
Definition at line 40 of file U1COMP.c.
doublereal tnl[15]
Definition at line 57 of file U1COMP.c.
doublereal toolht[15]
Definition at line 40 of file U1COMP.c.
doublereal toolwd[5]
Definition at line 40 of file U1COMP.c.
doublereal tp[15]
Definition at line 40 of file U1COMP.c.
doublereal tpk[15]
Definition at line 40 of file U1COMP.c.
doublereal u1[15]
Definition at line 40 of file U1COMP.c.
doublereal u1k[15]
Definition at line 40 of file U1COMP.c.
doublereal umax[8]
Definition at line 33 of file U1COMP.c.
doublereal varble[5]
Definition at line 40 of file U1COMP.c.
doublereal vndir[15]
Definition at line 40 of file U1COMP.c.
doublereal vt[15]
Definition at line 40 of file U1COMP.c.
doublereal vtem
Definition at line 18 of file U1COMP.c.
doublereal z__[5]
Definition at line 40 of file U1COMP.c.