My Project: UNDEF.c File Reference
UNDEF.c File Reference
#include "f2c.h"
Functions
int undef_ (doublereal *a)
Function Documentation
int undef_ (doublereal * a)
Definition at line 27 of file UNDEF.c.
References a, and strtsh_().
Referenced by apt040_(), apt071_(), apt090_(), apt094_(), apt103_(), apt107_(), apt108_(), canf_(), defext_(), distf_(), ldard_(), spatf_(), and xcall_().
 {
     extern /* Subroutine */ int strtsh_(doublereal *);
     /* Parameter adjustments */
     --a;
     /* Function Body */
     strtsh_(&a[1]);
     return 0;
 } /* undef_ */