My Project: UNITS.c File Reference
UNITS.c File Reference
#include "f2c.h"
Macros
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define sv_1 sv_
#define sv1_1 sv1_
#define isv_1 isv_
#define isv1_1 isv1_
#define ifxcor_1 ifxcor_
#define addcom_1 addcom_
#define symfil_1 symfil_
#define xunits_1 xunits_
#define xunitc_1 xunitc_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int units_ (integer *imod)
Variables
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
struct {
doublereal cc [15]
doublereal eps1 [5]
doublereal eps2 [5]
doublereal eps3 [5]
doublereal eps4 [5]
doublereal eps6 [5]
doublereal eps8 [5]
doublereal past [5]
doublereal plnd [5]
doublereal plnv [15]
doublereal rc [5]
doublereal s [5]
doublereal save [5]
doublereal sfvct [15]
doublereal slx [15]
doublereal sn [15]
doublereal snk [15]
doublereal snl [15]
doublereal sp [15]
doublereal spk [15]
doublereal spl [15]
doublereal tau [5]
doublereal tau1 [5]
doublereal tau2 [5]
doublereal th [5]
doublereal tn [15]
doublereal toolht [15]
doublereal toolwd [5]
doublereal tp [15]
doublereal tpk [15]
doublereal u1 [15]
doublereal vndir [15]
doublereal vt [15]
doublereal z__ [5]
doublereal varble [5]
doublereal u1k [15]
doublereal sk [15]
} sv_
struct {
doublereal cos1 [5]
doublereal cplfl [5]
doublereal cptst [5]
doublereal csd [5]
doublereal dplan [15]
doublereal dpmx1 [5]
doublereal plncs [5]
doublereal plnd1 [5]
doublereal pltst [5]
doublereal stck [5]
doublereal stckn [5]
doublereal stck1 [5]
doublereal stck2 [5]
doublereal tee [15]
doublereal tnl [15]
} sv1_
struct {
integer iafl [5]
integer icanon [5]
integer index [5]
integer indir__ [5]
integer iop [5]
integer iopset [5]
integer ipl [5]
integer isfidn [5]
integer isftyp [5]
integer isigcr [5]
integer isvfl [5]
integer itlon [5]
integer itseg [5]
integer iunfl [5]
integer jent [5]
integer jiops [5]
integer jtlflg [5]
integer jtn [5]
integer ju1 [5]
integer limfl [5]
integer itsegk [5]
} isv_
struct {
integer ifar [5]
integer ifl4 [5]
integer j20 [5]
integer j21 [5]
integer j22 [5]
integer j23 [5]
integer j50 [5]
integer j51 [5]
integer notan [5]
integer jph [5]
} isv1_
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
doublereal elmax
doublereal addc [24]
} addcom_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
struct {
doublereal tabext
doublereal ssext
integer iold
} xunits_
struct {
char oldmod [6]
} xunitc_
static integer c__91 = 91
static integer c__1 = 1
static integer c__4 = 4
static integer c__10 = 10
Macro Definition Documentation
#define addcom_1 addcom_
Definition at line 95 of file UNITS.c.
Referenced by units_().
#define charct_1 charct_
Definition at line 30 of file UNITS.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define fxcor_1 fxcor_
Definition at line 24 of file UNITS.c.
Referenced by units_().
#define ifxcor_1 ifxcor_
Definition at line 89 of file UNITS.c.
Referenced by units_().
#define isv1_1 isv1_
Definition at line 79 of file UNITS.c.
#define isv_1 isv_
Definition at line 72 of file UNITS.c.
Referenced by units_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define sv1_1 sv1_
Definition at line 63 of file UNITS.c.
#define sv_1 sv_
Definition at line 54 of file UNITS.c.
Referenced by units_().
#define symfil_1 symfil_
Definition at line 104 of file UNITS.c.
Referenced by units_().
#define tlldat_1 tlldat_
Definition at line 37 of file UNITS.c.
#define xunitc_1 xunitc_
Definition at line 117 of file UNITS.c.
Referenced by units_().
#define xunits_1 xunits_
Definition at line 111 of file UNITS.c.
Referenced by units_().
Function Documentation
int units_ (integer * imod)
Definition at line 129 of file UNITS.c.
References addcom_1, bcdf_(), c__1, c__10, c__4, c__91, cutred_(), error_(), ewrite_(), first, fxcor_1, holfrm_(), i__, ifxcor_1, ir, isv_1, j, numod, record_(), sv_1, symfil_1, w, xunitc_1, and xunits_1.
Referenced by xcall_().
 {
     /* Initialized data */
     static integer w[10] = { 0,0,1308622848,0,1308622848,2,1308622848,2,0,0 };
     static logical first = TRUE_;
     static doublereal unitc[4] = { 304.8,30.48,12.,1. };
     /* Local variables */
     static integer i__, j, nr, ir, ibl, ins, nwd;
     extern integer bcdf_(char *, ftnlen);
     static integer modc[4];
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
     static doublereal scale;
     static integer numod;
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
     static integer ioldmd;
     extern /* Subroutine */ int holfrm_(integer *, char *, integer *, integer
         *, integer *, ftnlen), cutred_(void), record_(integer *), ewrite_(
         integer *, integer *, integer *, integer *, integer *);
 /*        NEW ROUTINE TO HANDLE UNITS/ IMPLEMENTATION */
 /*        IMOD= FIRST FOUR CHAR. OF UNITS/ ARGUMENT */
 /*        CALLED BY NO OTHER ROUTINE */
 /*        CALLS SUBROUTINES  RECORD, ERROR, CUTTER(ENTRY CUTRED) */
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
 /*   *** 9.  SV BLOCK *** */
 /*   REAL SURFACE VARIABLES */
 /*   *** 12.  ISV BLOCK  *** */
 /*   INTEGER SURFACE VARIABLES */
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /* ...                SYSTEM I/O FILES */
     if (first) {
     w[0] = bcdf_("UNIT", (ftnlen)4);
     w[1] = bcdf_("S   ", (ftnlen)4);
     ibl = bcdf_("    ", (ftnlen)4);
     ins = bcdf_("ES  ", (ftnlen)4);
     modc[0] = bcdf_("MM  ", (ftnlen)4);
     modc[1] = bcdf_("CM  ", (ftnlen)4);
     modc[2] = bcdf_("INCH", (ftnlen)4);
     modc[3] = bcdf_("FEET", (ftnlen)4);
     first = FALSE_;
     }
     numod = *imod;
     ioldmd = bcdf_(xunitc_1.oldmod, (ftnlen)4);
     if (numod == ioldmd) {
     return 0;
     }
     for (i__ = 1; i__ <= 4; ++i__) {
 /* L1: */
     if (numod == modc[i__ - 1]) {
         goto L2;
     }
     }
     error_(&c__91, "UNITS   ", (ftnlen)8);
     return 0;
 L2:
     scale = unitc[i__ - 1] / unitc[xunits_1.iold - 1];
     ioldmd = numod;
     holfrm_(&ioldmd, xunitc_1.oldmod, &c__1, &c__4, &nwd, (ftnlen)6);
     xunits_1.iold = i__;
     xunits_1.tabext *= scale;
     xunits_1.ssext *= scale;
     fxcor_1.tlhit *= scale;
     for (i__ = 1; i__ <= 4; ++i__) {
 /* L3: */
     fxcor_1.cutdat[i__ - 1] *= scale;
     }
     fxcor_1.cutdat[0] *= 2.f;
     fxcor_1.cutdat[6] *= scale;
     fxcor_1.dpmax *= scale;
     addcom_1.elmax *= scale;
     fxcor_1.hi *= scale;
     fxcor_1.ra *= scale;
     fxcor_1.rc1 *= scale;
     i__ = ifxcor_1.ips;
     j = 1;
 L10:
     sv_1.tau[i__ - 1] *= scale;
     sv_1.tau1[i__ - 1] *= scale;
     sv_1.tau2[i__ - 1] *= scale;
     sv_1.eps1[i__ - 1] *= scale;
     sv_1.eps2[i__ - 1] *= scale;
     sv_1.eps3[i__ - 1] *= scale;
     sv_1.eps4[i__ - 1] *= scale;
     sv_1.eps6[i__ - 1] *= scale;
     sv_1.eps8[i__ - 1] *= scale;
     if (i__ - ifxcor_1.ics >= 0) {
     goto L5;
     } else {
     goto L4;
     }
 L4:
     i__ += ifxcor_1.lsv;
     ++j;
     goto L10;
 L5:
     if (j - 4 >= 0) {
     goto L7;
     } else {
     goto L6;
     }
 L6:
     i__ += ifxcor_1.lsv1;
     ++j;
     goto L10;
 L7:
     cutred_();
     isv_1.jent[ifxcor_1.ips - 1] = 1;
     isv_1.jent[ifxcor_1.ips + ifxcor_1.lsv - 1] = 1;
     record_(&w[3]);
     w[8] = ioldmd;
     w[9] = ibl;
     if (xunits_1.iold == 3) {
     w[9] = ins;
     }
     nr = 0;
     ewrite_(&symfil_1.exfile, &nr, w, &c__10, &ir);
     return 0;
 } /* units_ */
Variable Documentation
doublereal addc[24]
Definition at line 92 of file UNITS.c.
struct { ... } addcom_
doublereal alp
Definition at line 18 of file UNITS.c.
doublereal ax4[3]
Definition at line 18 of file UNITS.c.
integer axfile
Definition at line 98 of file UNITS.c.
integer c__1 = 1 static
Definition at line 122 of file UNITS.c.
Referenced by units_().
integer c__10 = 10 static
Definition at line 124 of file UNITS.c.
Referenced by units_().
integer c__4 = 4 static
Definition at line 123 of file UNITS.c.
Referenced by units_().
integer c__91 = 91 static
Definition at line 121 of file UNITS.c.
Referenced by units_().
doublereal cagl
Definition at line 18 of file UNITS.c.
doublereal cc[15]
Definition at line 40 of file UNITS.c.
struct { ... } charct_
integer clfil3
Definition at line 98 of file UNITS.c.
integer clfile
Definition at line 98 of file UNITS.c.
integer clfilp
Definition at line 98 of file UNITS.c.
doublereal corrad[8]
Definition at line 33 of file UNITS.c.
doublereal cos1[5]
Definition at line 57 of file UNITS.c.
integer cpfile
Definition at line 98 of file UNITS.c.
doublereal cplfl[5]
Definition at line 57 of file UNITS.c.
doublereal cptst[5]
Definition at line 57 of file UNITS.c.
doublereal csd[5]
Definition at line 57 of file UNITS.c.
doublereal cutdat[7]
Definition at line 18 of file UNITS.c.
doublereal dplan[15]
Definition at line 57 of file UNITS.c.
doublereal dpmax
Definition at line 18 of file UNITS.c.
doublereal dpmx1[5]
Definition at line 57 of file UNITS.c.
integer elfil1
Definition at line 98 of file UNITS.c.
integer elfil2
Definition at line 98 of file UNITS.c.
integer elfil3
Definition at line 98 of file UNITS.c.
integer elfil4
Definition at line 98 of file UNITS.c.
integer elfile
Definition at line 98 of file UNITS.c.
doublereal elmax
Definition at line 92 of file UNITS.c.
Referenced by smil_().
doublereal eps1[5]
Definition at line 40 of file UNITS.c.
doublereal eps2[5]
Definition at line 40 of file UNITS.c.
doublereal eps3[5]
Definition at line 40 of file UNITS.c.
doublereal eps4[5]
Definition at line 40 of file UNITS.c.
doublereal eps6[5]
Definition at line 40 of file UNITS.c.
doublereal eps8[5]
Definition at line 40 of file UNITS.c.
integer exfile
Definition at line 98 of file UNITS.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 18 of file UNITS.c.
doublereal hi
Definition at line 18 of file UNITS.c.
integer i3dflg
Definition at line 82 of file UNITS.c.
integer iaerr
Definition at line 82 of file UNITS.c.
integer iafl[5]
Definition at line 66 of file UNITS.c.
integer iautps
Definition at line 82 of file UNITS.c.
integer ibegin
Definition at line 82 of file UNITS.c.
integer ic
Definition at line 82 of file UNITS.c.
integer icanon[5]
Definition at line 66 of file UNITS.c.
integer icheck
Definition at line 82 of file UNITS.c.
integer icl
Definition at line 82 of file UNITS.c.
integer ics
Definition at line 82 of file UNITS.c.
integer icscnt
Definition at line 82 of file UNITS.c.
integer ictdef
Definition at line 82 of file UNITS.c.
integer icut
Definition at line 82 of file UNITS.c.
integer ids
Definition at line 82 of file UNITS.c.
integer ier
Definition at line 82 of file UNITS.c.
integer ifar[5]
Definition at line 75 of file UNITS.c.
integer ifl4[5]
Definition at line 75 of file UNITS.c.
struct { ... } ifxcor_
integer igo
Definition at line 82 of file UNITS.c.
integer igoto
Definition at line 82 of file UNITS.c.
integer igoug
Definition at line 82 of file UNITS.c.
integer igs
Definition at line 82 of file UNITS.c.
integer index[5]
Definition at line 66 of file UNITS.c.
integer indir__[5]
Definition at line 66 of file UNITS.c.
integer infile__
Definition at line 98 of file UNITS.c.
integer inops
Definition at line 82 of file UNITS.c.
integer iold
Definition at line 108 of file UNITS.c.
integer iop[5]
Definition at line 66 of file UNITS.c.
integer iopset[5]
Definition at line 66 of file UNITS.c.
integer ipl[5]
Definition at line 66 of file UNITS.c.
integer ips
Definition at line 82 of file UNITS.c.
integer ipsdef
Definition at line 82 of file UNITS.c.
integer ipt1
Definition at line 82 of file UNITS.c.
integer is
Definition at line 82 of file UNITS.c.
integer iseg
Definition at line 82 of file UNITS.c.
integer iseqno
Definition at line 82 of file UNITS.c.
integer isfidn[5]
Definition at line 66 of file UNITS.c.
integer isftyp[5]
Definition at line 66 of file UNITS.c.
integer isigcr[5]
Definition at line 66 of file UNITS.c.
integer ispare[26]
Definition at line 98 of file UNITS.c.
integer isrch
Definition at line 82 of file UNITS.c.
integer istrup
Definition at line 82 of file UNITS.c.
struct { ... } isv1_
struct { ... } isv_
integer isvfl[5]
Definition at line 66 of file UNITS.c.
integer it
Definition at line 82 of file UNITS.c.
integer itlon[5]
Definition at line 66 of file UNITS.c.
integer itseg[5]
Definition at line 66 of file UNITS.c.
integer itsegk[5]
Definition at line 66 of file UNITS.c.
integer iunfl[5]
Definition at line 66 of file UNITS.c.
integer j20[5]
Definition at line 75 of file UNITS.c.
integer j21[5]
Definition at line 75 of file UNITS.c.
integer j22[5]
Definition at line 75 of file UNITS.c.
integer j23[5]
Definition at line 75 of file UNITS.c.
integer j50[5]
Definition at line 75 of file UNITS.c.
integer j51[5]
Definition at line 75 of file UNITS.c.
integer jbr
Definition at line 82 of file UNITS.c.
integer jent[5]
Definition at line 66 of file UNITS.c.
integer jiops[5]
Definition at line 66 of file UNITS.c.
integer jph[5]
Definition at line 75 of file UNITS.c.
integer jsw
Definition at line 82 of file UNITS.c.
integer jtlflg[5]
Definition at line 66 of file UNITS.c.
integer jtn[5]
Definition at line 66 of file UNITS.c.
integer ju1[5]
Definition at line 66 of file UNITS.c.
integer ldafil
Definition at line 98 of file UNITS.c.
integer libfil
Definition at line 98 of file UNITS.c.
integer limfl[5]
Definition at line 66 of file UNITS.c.
integer lsv
Definition at line 82 of file UNITS.c.
integer lsv1
Definition at line 82 of file UNITS.c.
integer mactxt
Definition at line 98 of file UNITS.c.
integer mantax
Definition at line 82 of file UNITS.c.
char modfer[6]
Definition at line 27 of file UNITS.c.
integer motmod
Definition at line 82 of file UNITS.c.
integer msav
Definition at line 82 of file UNITS.c.
integer mulout
Definition at line 82 of file UNITS.c.
integer nfil12
Definition at line 98 of file UNITS.c.
integer nfil13
Definition at line 98 of file UNITS.c.
integer nmbseg
Definition at line 82 of file UNITS.c.
integer nmpnts
Definition at line 82 of file UNITS.c.
integer notan[5]
Definition at line 75 of file UNITS.c.
integer nrec
Definition at line 82 of file UNITS.c.
integer numax
Definition at line 82 of file UNITS.c.
integer numcnt
Definition at line 82 of file UNITS.c.
integer nump
Definition at line 82 of file UNITS.c.
integer numpt1
Definition at line 82 of file UNITS.c.
integer numsfs
Definition at line 82 of file UNITS.c.
integer numsur
Definition at line 82 of file UNITS.c.
integer nw
Definition at line 82 of file UNITS.c.
integer nwds
Definition at line 82 of file UNITS.c.
char oldmod[6]
Definition at line 114 of file UNITS.c.
doublereal past[5]
Definition at line 40 of file UNITS.c.
doublereal plncs[5]
Definition at line 57 of file UNITS.c.
doublereal plnd[5]
Definition at line 40 of file UNITS.c.
doublereal plnd1[5]
Definition at line 57 of file UNITS.c.
doublereal plnv[15]
Definition at line 40 of file UNITS.c.
doublereal pltst[5]
Definition at line 57 of file UNITS.c.
doublereal pmove[3]
Definition at line 18 of file UNITS.c.
integer pnchfl
Definition at line 98 of file UNITS.c.
integer pofile
Definition at line 98 of file UNITS.c.
integer pxfile
Definition at line 98 of file UNITS.c.
doublereal ra
Definition at line 18 of file UNITS.c.
doublereal rc[5]
Definition at line 40 of file UNITS.c.
doublereal rc1
Definition at line 18 of file UNITS.c.
doublereal ri[8]
Definition at line 33 of file UNITS.c.
doublereal s[5]
Definition at line 40 of file UNITS.c.
doublereal sagl
Definition at line 18 of file UNITS.c.
doublereal save[5]
Definition at line 40 of file UNITS.c.
doublereal sfvct[15]
Definition at line 40 of file UNITS.c.
doublereal sk[15]
Definition at line 40 of file UNITS.c.
doublereal slx[15]
Definition at line 40 of file UNITS.c.
doublereal sn[15]
Definition at line 40 of file UNITS.c.
doublereal snk[15]
Definition at line 40 of file UNITS.c.
doublereal snl[15]
Definition at line 40 of file UNITS.c.
doublereal sp[15]
Definition at line 40 of file UNITS.c.
doublereal spk[15]
Definition at line 40 of file UNITS.c.
doublereal spl[15]
Definition at line 40 of file UNITS.c.
doublereal ssext
Definition at line 107 of file UNITS.c.
doublereal stck[5]
Definition at line 57 of file UNITS.c.
doublereal stck1[5]
Definition at line 57 of file UNITS.c.
doublereal stck2[5]
Definition at line 57 of file UNITS.c.
doublereal stckn[5]
Definition at line 57 of file UNITS.c.
doublereal strtno
Definition at line 18 of file UNITS.c.
doublereal surd
Definition at line 18 of file UNITS.c.
struct { ... } sv1_
struct { ... } sv_
struct { ... } symfil_
doublereal ta[3]
Definition at line 18 of file UNITS.c.
doublereal tabext
Definition at line 107 of file UNITS.c.
doublereal tak[3]
Definition at line 18 of file UNITS.c.
doublereal tal[3]
Definition at line 18 of file UNITS.c.
doublereal tanhi[8]
Definition at line 33 of file UNITS.c.
doublereal tanlo[8]
Definition at line 33 of file UNITS.c.
doublereal tau[5]
Definition at line 40 of file UNITS.c.
doublereal tau1[5]
Definition at line 40 of file UNITS.c.
doublereal tau2[5]
Definition at line 40 of file UNITS.c.
doublereal tcont[9]
Definition at line 33 of file UNITS.c.
doublereal te[3]
Definition at line 18 of file UNITS.c.
doublereal tee[15]
Definition at line 57 of file UNITS.c.
doublereal tek[3]
Definition at line 18 of file UNITS.c.
doublereal tel[3]
Definition at line 18 of file UNITS.c.
doublereal tem[10]
Definition at line 18 of file UNITS.c.
doublereal temp[24]
Definition at line 18 of file UNITS.c.
doublereal th[5]
Definition at line 40 of file UNITS.c.
doublereal ti[3]
Definition at line 18 of file UNITS.c.
integer tifile
Definition at line 98 of file UNITS.c.
doublereal tik[3]
Definition at line 18 of file UNITS.c.
doublereal til[3]
Definition at line 18 of file UNITS.c.
doublereal tlhit
Definition at line 18 of file UNITS.c.
doublereal tlhite[8]
Definition at line 33 of file UNITS.c.
doublereal tlinc[9]
Definition at line 33 of file UNITS.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 18 of file UNITS.c.
doublereal tn[15]
Definition at line 40 of file UNITS.c.
doublereal tnl[15]
Definition at line 57 of file UNITS.c.
doublereal toolht[15]
Definition at line 40 of file UNITS.c.
doublereal toolwd[5]
Definition at line 40 of file UNITS.c.
doublereal tp[15]
Definition at line 40 of file UNITS.c.
doublereal tpk[15]
Definition at line 40 of file UNITS.c.
doublereal u1[15]
Definition at line 40 of file UNITS.c.
doublereal u1k[15]
Definition at line 40 of file UNITS.c.
doublereal umax[8]
Definition at line 33 of file UNITS.c.
doublereal varble[5]
Definition at line 40 of file UNITS.c.
integer vlfile
Definition at line 98 of file UNITS.c.
doublereal vndir[15]
Definition at line 40 of file UNITS.c.
doublereal vt[15]
Definition at line 40 of file UNITS.c.
doublereal vtem
Definition at line 18 of file UNITS.c.
integer xcan
Definition at line 98 of file UNITS.c.
integer xnum
Definition at line 98 of file UNITS.c.
struct { ... } xunitc_
struct { ... } xunits_
doublereal z__[5]
Definition at line 40 of file UNITS.c.