My Project: UNPACK.c File Reference
UNPACK.c File Reference
#include "f2c.h"
Functions
int unpack_ (doublereal *result, integer *imode, integer *isize, integer *isub)
Function Documentation
int unpack_ (doublereal * result, integer * imode, integer * isize, integer * isub)
Definition at line 33 of file UNPACK.c.
References j, and result.
Referenced by anglb_(), anglf_(), apt010_(), apt033_(), apt040_(), apt102_(), apt103_(), apt104_(), apt107_(), apt108_(), apt109_(), apt202_(), apt234_(), canf_(), defext_(), distf_(), gol_(), intrp_(), intsec_(), ldard_(), numf1_(), numf2_(), parmf1_(), parmf2_(), print_(), punch_(), spatf_(), and transm_().
 {
     /* Initialized data */
     static integer klit1 = 1000000;
     static integer klit2 = 10000;
     /* System generated locals */
     doublereal d__1;
     /* Local variables */
     static integer j, ipack;
     /* Parameter adjustments */
     --result;
     /* Function Body */
     j = 0;
 /* L10: */
     ipack = (d__1 = result[j], (integer) abs(d__1));
     *imode = ipack / klit1;
     *isize = (ipack - *imode * klit1) / klit2;
     *isub = ipack - *imode * klit1 - *isize * klit2;
     return 0;
 } /* unpack_ */