My Project: UTILTY.c File Reference
UTILTY.c File Reference
#include "f2c.h"
Macros
#define ifxcor_1 ifxcor_
#define fxcor_1 fxcor_
#define charct_1 charct_
#define tlldat_1 tlldat_
#define cosl ((doublereal *)&tlldat_1 + 16)
#define sinl ((doublereal *)&tlldat_1 + 8)
Functions
int absf_ (doublereal *res, doublereal *arg)
int atanf_ (doublereal *res, doublereal *arg)
int cosf_ (doublereal *res, doublereal *arg)
int sinf_ (doublereal *res, doublereal *arg)
int expf_ (doublereal *res, doublereal *arg)
int sqrtf_ (doublereal *res, doublereal *arg)
int vnorm_ (doublereal *va, doublereal *v3)
int cross_ (doublereal *v1, doublereal *v2, doublereal *v3)
int crossv_ (doublereal *v1, doublereal *v2, doublereal *v3)
int dotv_ (doublereal *res, doublereal *v1, doublereal *v2)
Variables
struct {
integer iaerr
integer iautps
integer ibegin
integer ic
integer icl
integer ics
integer icscnt
integer ictdef
integer icut
integer ids
integer ier
integer igo
integer igoto
integer igoug
integer igs
integer inops
integer ipsdef
integer ips
integer ipt1
integer is
integer iseqno
integer isrch
integer istrup
integer it
integer i3dflg
integer jbr
integer jsw
integer lsv
integer lsv1
integer motmod
integer mulout
integer mantax
integer nmpnts
integer nrec
integer numax
integer numcnt
integer nump
integer numpt1
integer numsfs
integer numsur
integer nw
integer icheck
integer iseg
integer nmbseg
integer nwds
integer msav
} ifxcor_
struct {
doublereal ax4 [3]
doublereal cagl
doublereal cutdat [7]
doublereal gamma
doublereal hi
doublereal pmove [3]
doublereal ra
doublereal rc1
doublereal sagl
doublereal surd
doublereal ta [3]
doublereal tak [3]
doublereal te [3]
doublereal tek [3]
doublereal tel [3]
doublereal tem [10]
doublereal temp [24]
doublereal ti [3]
doublereal tik [3]
doublereal til [3]
doublereal tm [3]
doublereal vtem
doublereal alp
doublereal tal [3]
doublereal dpmax
doublereal strtno
doublereal tlhit
} fxcor_
struct {
char modfer [6]
} charct_
struct {
doublereal tlhite [8]
doublereal tanhi [8]
doublereal tanlo [8]
doublereal umax [8]
doublereal ri [8]
doublereal corrad [8]
doublereal tcont [9]
doublereal tlinc [9]
} tlldat_
static integer c__20 = 20
Macro Definition Documentation
#define charct_1 charct_
Definition at line 40 of file UTILTY.c.
#define cosl ((doublereal *)&tlldat_1 + 16)
#define fxcor_1 fxcor_
Definition at line 34 of file UTILTY.c.
Referenced by vnorm_().
#define ifxcor_1 ifxcor_
Definition at line 25 of file UTILTY.c.
Referenced by vnorm_().
#define sinl ((doublereal *)&tlldat_1 + 8)
#define tlldat_1 tlldat_
Definition at line 47 of file UTILTY.c.
Function Documentation
int absf_ (doublereal * res, doublereal * arg)
Definition at line 61 of file UTILTY.c.
Referenced by xcall_().
 {
     *res = abs(*arg);
     return 0;
 } /* absf_ */
int atanf_ (doublereal * res, doublereal * arg)
Definition at line 72 of file UTILTY.c.
Referenced by xcall_().
 {
     /* Builtin functions */
     double atan(doublereal);
     *res = atan(*arg) / .0174532925f;
     return 0;
 } /* atanf_ */
int cosf_ (doublereal * res, doublereal * arg)
Definition at line 86 of file UTILTY.c.
References f.
Referenced by xcall_().
 {
     /* Builtin functions */
     double cos(doublereal);
     *res = cos(*arg * .0174532925f);
     return 0;
 } /* cosf_ */
int cross_ (doublereal * v1, doublereal * v2, doublereal * v3)
Definition at line 235 of file UTILTY.c.
References i__, v1, v2, v3, and vt.
Referenced by ader_(), apt013_(), apt033_(), apt041_(), apt043_(), apt065_(), apt073_(), apt075_(), apt109_(), apt211_(), arlm3_(), calcb_(), centr_(), cnsurf_(), cplan_(), cpldst_(), crossv_(), curflo_(), curint_(), ddcyln_(), ddpara_(), ddrlsr_(), dgeom_(), go2_(), gop_(), intfa1_(), intout_(), kursrf_(), lcls_(), midkur_(), pocket_(), polpol_(), puvloc_(), radar_(), remscn_(), revolv_(), scpict_(), scurv_(), shella_(), ssplin_(), sycurv_(), tecalc_(), tinkr_(), and tulpos_().
 {
     static integer i__;
     static doublereal vt[3];
     /* Parameter adjustments */
     --v3;
     --v2;
     --v1;
     /* Function Body */
     vt[0] = v1[2] * v2[3] - v1[3] * v2[2];
     vt[1] = v1[3] * v2[1] - v1[1] * v2[3];
     vt[2] = v1[1] * v2[2] - v1[2] * v2[1];
     for (i__ = 1; i__ <= 3; ++i__) {
     v3[i__] = vt[i__ - 1];
 /* L10: */
     }
     return 0;
 } /* cross_ */
int crossv_ (doublereal * v1, doublereal * v2, doublereal * v3)
Definition at line 269 of file UTILTY.c.
References cross_(), v1, v2, v3, vnorm_(), and vt.
Referenced by calcb_(), tecalc_(), tulpos_(), and xtpcal_().
 {
     static doublereal vt[3];
     extern /* Subroutine */ int cross_(doublereal *, doublereal *, doublereal
         *), vnorm_(doublereal *, doublereal *);
     /* Parameter adjustments */
     --v3;
     --v2;
     --v1;
     /* Function Body */
     cross_(&v1[1], &v2[1], vt);
     vnorm_(vt, &v3[1]);
     return 0;
 } /* crossv_ */
int dotv_ (doublereal * res, doublereal * v1, doublereal * v2)
Definition at line 300 of file UTILTY.c.
References v1, and v2.
Referenced by aprix_(), apt109_(), avoid_(), balsrf_(), baltol_(), cnsurf_(), ddssrf_(), kursrf_(), puvloc_(), tecalc_(), and tulpos_().
 {
     /* Parameter adjustments */
     --v2;
     --v1;
     /* Function Body */
     *res = v1[1] * v2[1] + v1[2] * v2[2] + v1[3] * v2[3];
     return 0;
 } /* dotv_ */
int expf_ (doublereal * res, doublereal * arg)
Definition at line 114 of file UTILTY.c.
Referenced by xcall_().
 {
     /* Builtin functions */
     double exp(doublereal);
     *res = exp(*arg);
     return 0;
 } /* expf_ */
int sinf_ (doublereal * res, doublereal * arg)
Definition at line 100 of file UTILTY.c.
References f.
Referenced by xcall_().
 {
     /* Builtin functions */
     double sin(doublereal);
     *res = sin(*arg * .0174532925f);
     return 0;
 } /* sinf_ */
int sqrtf_ (doublereal * res, doublereal * arg)
Definition at line 128 of file UTILTY.c.
References c__20, and error_().
Referenced by xcall_().
 {
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     extern /* Subroutine */ int error_(integer *, char *, ftnlen);
     if (*arg < 0.) {
     error_(&c__20, "SQRTF   ", (ftnlen)8);
     *arg = abs(*arg);
     }
     *res = sqrt(*arg);
     return 0;
 } /* sqrtf_ */
int vnorm_ (doublereal * va, doublereal * v3)
Definition at line 155 of file UTILTY.c.
References f, fxcor_1, i__, ifxcor_1, v3, and va.
Referenced by amind_(), apt012_(), apt013_(), apt016_(), apt022_(), apt033_(), apt040_(), apt041_(), apt043_(), apt046_(), apt065_(), apt069_(), apt073_(), apt090_(), apt211_(), apt233_(), apt236_(), arlm2_(), arlm3_(), avoid_(), axset_(), calcb_(), calct_(), ccurv_(), centr_(), check_(), cplan_(), crossv_(), crvlen_(), curflo_(), curint_(), ddpara_(), ddquad_(), ddrlsr_(), go2_(), gol_(), indirp_(), indirv_(), indrph_(), indrvh_(), kursrf_(), lcls_(), midkur_(), pchprc_(), pocket_(), radar_(), srfvct_(), tecalc_(), tinkr_(), tlaxis_(), tlnorm_(), tulpos_(), u1comp_(), and xtpcal_().
 {
     /* Builtin functions */
     double sqrt(doublereal);
     /* Local variables */
     static integer i__;
 #define cosl ((doublereal *)&tlldat_1 + 16)
 #define sinl ((doublereal *)&tlldat_1 + 8)
 /*    *** 15.  IFXCOR BLOCK  *** */
 /*    INVIOLATE ARELEM INTEGER VARIABLES */
 /*    *** 7.  FXCOR BLOCK  *** */
 /*    REAL VARIABLES USED BY ARELEM, WHICH MUST REMAIN INVIOLATE */
 /*    SEPARATE /CHARCT/ COMMON BLOCK FOR MODFER, WHICH WAS PART OF FXCOR. */
 /*    TOOL DATA STORAGE */
 /*    NOTE: 'TANHI' AND 'SINL' SHARE LOCATIONS AS DO 'TANLO' AND 'COSL' */
 /*           THIS IS DELIBERATE. */
     /* Parameter adjustments */
     --v3;
     --va;
     /* Function Body */
     fxcor_1.vtem = sqrt(va[1] * va[1] + va[2] * va[2] + va[3] * va[3]);
     if (abs(fxcor_1.vtem) < 1e-24f) {
     ifxcor_1.ier = 1;
     for (i__ = 1; i__ <= 3; ++i__) {
         v3[i__] = va[i__];
 /* L25: */
     }
     } else {
     ifxcor_1.ier = 0;
     for (i__ = 1; i__ <= 3; ++i__) {
         v3[i__] = va[i__] / fxcor_1.vtem;
 /* L26: */
     }
     }
     return 0;
 } /* vnorm_ */
Variable Documentation
doublereal alp
Definition at line 28 of file UTILTY.c.
doublereal ax4[3]
Definition at line 28 of file UTILTY.c.
integer c__20 = 20 static
Definition at line 51 of file UTILTY.c.
Referenced by sqrtf_().
doublereal cagl
Definition at line 28 of file UTILTY.c.
struct { ... } charct_
doublereal corrad[8]
Definition at line 43 of file UTILTY.c.
doublereal cutdat[7]
Definition at line 28 of file UTILTY.c.
doublereal dpmax
Definition at line 28 of file UTILTY.c.
struct { ... } fxcor_
doublereal gamma
Definition at line 28 of file UTILTY.c.
doublereal hi
Definition at line 28 of file UTILTY.c.
integer i3dflg
Definition at line 18 of file UTILTY.c.
integer iaerr
Definition at line 18 of file UTILTY.c.
integer iautps
Definition at line 18 of file UTILTY.c.
integer ibegin
Definition at line 18 of file UTILTY.c.
integer ic
Definition at line 18 of file UTILTY.c.
integer icheck
Definition at line 18 of file UTILTY.c.
integer icl
Definition at line 18 of file UTILTY.c.
integer ics
Definition at line 18 of file UTILTY.c.
integer icscnt
Definition at line 18 of file UTILTY.c.
integer ictdef
Definition at line 18 of file UTILTY.c.
integer icut
Definition at line 18 of file UTILTY.c.
integer ids
Definition at line 18 of file UTILTY.c.
integer ier
Definition at line 18 of file UTILTY.c.
struct { ... } ifxcor_
integer igo
Definition at line 18 of file UTILTY.c.
integer igoto
Definition at line 18 of file UTILTY.c.
integer igoug
Definition at line 18 of file UTILTY.c.
integer igs
Definition at line 18 of file UTILTY.c.
integer inops
Definition at line 18 of file UTILTY.c.
integer ips
Definition at line 18 of file UTILTY.c.
integer ipsdef
Definition at line 18 of file UTILTY.c.
integer ipt1
Definition at line 18 of file UTILTY.c.
integer is
Definition at line 18 of file UTILTY.c.
integer iseg
Definition at line 18 of file UTILTY.c.
integer iseqno
Definition at line 18 of file UTILTY.c.
integer isrch
Definition at line 18 of file UTILTY.c.
integer istrup
Definition at line 18 of file UTILTY.c.
integer it
Definition at line 18 of file UTILTY.c.
integer jbr
Definition at line 18 of file UTILTY.c.
integer jsw
Definition at line 18 of file UTILTY.c.
integer lsv
Definition at line 18 of file UTILTY.c.
integer lsv1
Definition at line 18 of file UTILTY.c.
integer mantax
Definition at line 18 of file UTILTY.c.
char modfer[6]
Definition at line 37 of file UTILTY.c.
integer motmod
Definition at line 18 of file UTILTY.c.
integer msav
Definition at line 18 of file UTILTY.c.
integer mulout
Definition at line 18 of file UTILTY.c.
integer nmbseg
Definition at line 18 of file UTILTY.c.
integer nmpnts
Definition at line 18 of file UTILTY.c.
integer nrec
Definition at line 18 of file UTILTY.c.
integer numax
Definition at line 18 of file UTILTY.c.
integer numcnt
Definition at line 18 of file UTILTY.c.
integer nump
Definition at line 18 of file UTILTY.c.
integer numpt1
Definition at line 18 of file UTILTY.c.
integer numsfs
Definition at line 18 of file UTILTY.c.
integer numsur
Definition at line 18 of file UTILTY.c.
integer nw
Definition at line 18 of file UTILTY.c.
integer nwds
Definition at line 18 of file UTILTY.c.
doublereal pmove[3]
Definition at line 28 of file UTILTY.c.
doublereal ra
Definition at line 28 of file UTILTY.c.
doublereal rc1
Definition at line 28 of file UTILTY.c.
doublereal ri[8]
Definition at line 43 of file UTILTY.c.
doublereal sagl
Definition at line 28 of file UTILTY.c.
doublereal strtno
Definition at line 28 of file UTILTY.c.
doublereal surd
Definition at line 28 of file UTILTY.c.
doublereal ta[3]
Definition at line 28 of file UTILTY.c.
doublereal tak[3]
Definition at line 28 of file UTILTY.c.
doublereal tal[3]
Definition at line 28 of file UTILTY.c.
doublereal tanhi[8]
Definition at line 43 of file UTILTY.c.
doublereal tanlo[8]
Definition at line 43 of file UTILTY.c.
doublereal tcont[9]
Definition at line 43 of file UTILTY.c.
doublereal te[3]
Definition at line 28 of file UTILTY.c.
doublereal tek[3]
Definition at line 28 of file UTILTY.c.
doublereal tel[3]
Definition at line 28 of file UTILTY.c.
doublereal tem[10]
Definition at line 28 of file UTILTY.c.
doublereal temp[24]
Definition at line 28 of file UTILTY.c.
doublereal ti[3]
Definition at line 28 of file UTILTY.c.
doublereal tik[3]
Definition at line 28 of file UTILTY.c.
doublereal til[3]
Definition at line 28 of file UTILTY.c.
doublereal tlhit
Definition at line 28 of file UTILTY.c.
doublereal tlhite[8]
Definition at line 43 of file UTILTY.c.
doublereal tlinc[9]
Definition at line 43 of file UTILTY.c.
struct { ... } tlldat_
doublereal tm[3]
Definition at line 28 of file UTILTY.c.
doublereal umax[8]
Definition at line 43 of file UTILTY.c.
doublereal vtem
Definition at line 28 of file UTILTY.c.