My Project: VECMOD.c File Reference
VECMOD.c File Reference
#include "f2c.h"
Functions
int vecmod_ (doublereal *x, doublereal *xmod)
Function Documentation
int vecmod_ (doublereal * x, doublereal * xmod)
Definition at line 17 of file VECMOD.c.
References x.
Referenced by algo1_(), calct_(), hulcut_(), norma_(), remscn_(), shellb_(), and txhull_().
 {
     /* Builtin functions */
     double sqrt(doublereal);
 /*     GIVEN 3-D VECTOR X, CALCULATES MODULUS XMOD */
     /* Parameter adjustments */
     --x;
     /* Function Body */
     *xmod = sqrt(x[1] * x[1] + x[2] * x[2] + x[3] * x[3]);
     return 0;
 } /* vecmod_ */