My Project: VSCALE.c File Reference
VSCALE.c File Reference
#include "f2c.h"
Functions
int vscale_ (doublereal *s, doublereal *v1, doublereal *v2)
Function Documentation
int vscale_ (doublereal * s, doublereal * v1, doublereal * v2)
Definition at line 17 of file VSCALE.c.
References i__, v1, and v2.
Referenced by avoid_(), sspath_(), and tulpos_().
 {
     static integer i__;
 /*    PURPOSE: TO APPLY A SCALE FACTOR TO A VECTOR  ( V2=S*V1 ) */
     /* Parameter adjustments */
     --v2;
     --v1;
     /* Function Body */
     for (i__ = 1; i__ <= 3; ++i__) {
     v2[i__] = *s * v1[i__];
 /* L10: */
     }
     return 0;
 } /* vscale_ */