My Project: XNUMBR.c File Reference
XNUMBR.c File Reference
#include "f2c.h"
Macros
#define _BLNK__1 _BLNK__
#define stor_1 stor_
#define symfil_1 symfil_
#define cf ((doublereal *)&_BLNK__1)
#define ia ((doublereal *)&_BLNK__1)
#define nb ((doublereal *)&_BLNK__1)
#define cm ((integer *)&_BLNK__1)
#define fp ((doublereal *)&_BLNK__1)
#define pp ((integer *)&_BLNK__1)
#define mt ((integer *)&_BLNK__1)
#define nt ((integer *)&_BLNK__1)
#define can ((doublereal *)&_BLNK__1 + 40)
#define ipage ((integer *)&stor_1 + 20)
#define canon ((doublereal *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define numod ((integer *)&stor_1 + 17)
#define ndaflg ((integer *)&stor_1 + 18)
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define nrecst ((integer *)&stor_1 + 19)
#define numbst ((integer *)&stor_1 + 16)
Functions
int xnumbr_ (integer *ipntr)
Variables
struct {
doublereal com [36000]
} _BLNK__
struct {
integer ntb
integer fpb
integer ppb
integer comn
integer cfb
integer nblk
integer nrecrd [10]
integer ntparm [10]
} stor_
struct {
integer clfilp
integer clfile
integer clfil3
integer exfile
integer infile__
integer vlfile
integer pnchfl
integer xcan
integer mactxt
integer xnum
integer elfil1
integer elfil2
integer elfil3
integer elfil4
integer cpfile
integer axfile
integer pofile
integer elfile
integer ldafil
integer tifile
integer pxfile
integer nfil12
integer nfil13
integer libfil
integer ispare [26]
} symfil_
Macro Definition Documentation
#define _BLNK__1 _BLNK__
Definition at line 21 of file XNUMBR.c.
#define bcanon ((doublereal *)&_BLNK__1 + 40)
#define can ((doublereal *)&_BLNK__1 + 40)
#define canon ((doublereal *)&_BLNK__1)
#define cf ((doublereal *)&_BLNK__1)
#define cm ((integer *)&_BLNK__1)
#define fp ((doublereal *)&_BLNK__1)
Referenced by xnumbr_().
#define ia ((doublereal *)&_BLNK__1)
#define ipage ((integer *)&stor_1 + 20)
Referenced by xnumbr_().
#define mt ((integer *)&_BLNK__1)
#define nb ((doublereal *)&_BLNK__1)
#define ndaflg ((integer *)&stor_1 + 18)
#define nrecst ((integer *)&stor_1 + 19)
#define nt ((integer *)&_BLNK__1)
#define numbst ((integer *)&stor_1 + 16)
Referenced by xnumbr_().
#define numod ((integer *)&stor_1 + 17)
Referenced by xnumbr_().
#define pp ((integer *)&_BLNK__1)
#define sscan ((doublereal *)&_BLNK__1 + 40)
#define stor_1 stor_
Definition at line 27 of file XNUMBR.c.
Referenced by xnumbr_().
#define symfil_1 symfil_
Definition at line 36 of file XNUMBR.c.
Referenced by xnumbr_().
Function Documentation
int xnumbr_ (integer * ipntr)
Definition at line 43 of file XNUMBR.c.
References fp, fread_(), ipage, ir, l, numbst, numod, stor_1, and symfil_1.
Referenced by get_(), and lib_().
 {
     /* Local variables */
     static integer l;
 #define cf ((doublereal *)&_BLNK__1)
 #define ia ((doublereal *)&_BLNK__1)
 #define nb ((doublereal *)&_BLNK__1)
 #define cm ((integer *)&_BLNK__1)
 #define fp ((doublereal *)&_BLNK__1)
     static integer ir;
 #define pp ((integer *)&_BLNK__1)
 #define mt ((integer *)&_BLNK__1)
 #define nt ((integer *)&_BLNK__1)
 #define can ((doublereal *)&_BLNK__1 + 40)
     static integer jrec;
     extern /* Subroutine */ int fread_(integer *, integer *, doublereal *,
         integer *, integer *);
 #define ipage ((integer *)&stor_1 + 20)
 #define canon ((doublereal *)&_BLNK__1)
 #define sscan ((doublereal *)&_BLNK__1 + 40)
     static integer ipmod;
 #define numod ((integer *)&stor_1 + 17)
     static integer nstrt;
 #define ndaflg ((integer *)&stor_1 + 18)
 #define bcanon ((doublereal *)&_BLNK__1 + 40)
 #define nrecst ((integer *)&stor_1 + 19)
 #define numbst ((integer *)&stor_1 + 16)
 /* -----PURPOSE.......TO PROVIDE ACCESS TO THE NUMBER TABLE VALUES WHEN */
 /*                   PASSED ON DIRECT ACCESS FILE FROM THE TRANSLATOR */
 /* -----ARGUMENTS.....IPNTR - VIRTUAL POINTER TO NUMBER TABLE VALUE - */
 /*                   CHANGED TO ACTUAL POINTER TO VALUE UPON EXIT */
 /* -----CALLED BY.....GET, LIB */
 /* -----SUBSIDIARIES..NONE */
 /* -----DIAGNOSTICS...NONE */
 /* --------**** COMMON AREAS NEEDED FOR THIS ROUTINE **** */
 /* --------UNLABELED COMMON - COM */
 /*     UNLABELLED COMMON */
 /* ---     SIZE OF BLANK COMMON IS ALLOCATED RIGHT HERE. */
 /* STOR--COMMON CONTAINING STORAGE PARAMETERS */
 /*     ------------------- */
 /*   ADDITIONAL STOR PARAMETERS USED FOR NUMBER TABLE DIRECT ACCESS */
 /* ...  20. SYSTEM I/O FILE NAMES */
 /*  ------------------------------------------------------------------ */
 /* --------CALCULATE VIRTUAL PAGE POINTER AND ACTUAL NUMBER TABLE */
 /* --------POINTER USING CURRENT VIRTUAL NUMBER TABLE POINTER */
 /* ...                SYSTEM I/O FILES */
     if (*ipntr < *numbst) {
     goto L999;
     }
     ipmod = (*ipntr - *numbst) / *numod + 1;
     *ipntr -= (ipmod - 1) * *numod;
 /* --------IF NEW PAGE IS CURRENTLY IN COMMON AREA - RETURN */
     if (ipmod == *ipage) {
     goto L999;
     }
     jrec = (ipmod << 1) - 1;
     nstrt = stor_1.ntb + *numbst;
     l = *numod / 2;
     fread_(&symfil_1.xnum, &jrec, &fp[nstrt - 1], &l, &ir);
     nstrt += l;
     ++jrec;
     fread_(&symfil_1.xnum, &jrec, &fp[nstrt - 1], &l, &ir);
 /* --------SET CURRENT PAGE POINTER AND RETURN */
     *ipage = ipmod;
 L999:
     return 0;
 } /* xnumbr_ */
Variable Documentation
struct { ... } _BLNK__
integer axfile
Definition at line 30 of file XNUMBR.c.
integer cfb
Definition at line 24 of file XNUMBR.c.
integer clfil3
Definition at line 30 of file XNUMBR.c.
integer clfile
Definition at line 30 of file XNUMBR.c.
integer clfilp
Definition at line 30 of file XNUMBR.c.
doublereal com[36000]
Definition at line 18 of file XNUMBR.c.
integer comn
Definition at line 24 of file XNUMBR.c.
integer cpfile
Definition at line 30 of file XNUMBR.c.
integer elfil1
Definition at line 30 of file XNUMBR.c.
integer elfil2
Definition at line 30 of file XNUMBR.c.
integer elfil3
Definition at line 30 of file XNUMBR.c.
integer elfil4
Definition at line 30 of file XNUMBR.c.
integer elfile
Definition at line 30 of file XNUMBR.c.
integer exfile
Definition at line 30 of file XNUMBR.c.
integer fpb
Definition at line 24 of file XNUMBR.c.
integer infile__
Definition at line 30 of file XNUMBR.c.
integer ispare[26]
Definition at line 30 of file XNUMBR.c.
integer ldafil
Definition at line 30 of file XNUMBR.c.
integer libfil
Definition at line 30 of file XNUMBR.c.
integer mactxt
Definition at line 30 of file XNUMBR.c.
integer nblk
Definition at line 24 of file XNUMBR.c.
integer nfil12
Definition at line 30 of file XNUMBR.c.
integer nfil13
Definition at line 30 of file XNUMBR.c.
integer nrecrd[10]
Definition at line 24 of file XNUMBR.c.
integer ntb
Definition at line 24 of file XNUMBR.c.
integer ntparm[10]
Definition at line 24 of file XNUMBR.c.
integer pnchfl
Definition at line 30 of file XNUMBR.c.
integer pofile
Definition at line 30 of file XNUMBR.c.
integer ppb
Definition at line 24 of file XNUMBR.c.
integer pxfile
Definition at line 30 of file XNUMBR.c.
struct { ... } stor_
struct { ... } symfil_
integer tifile
Definition at line 30 of file XNUMBR.c.
integer vlfile
Definition at line 30 of file XNUMBR.c.
integer xcan
Definition at line 30 of file XNUMBR.c.
integer xnum
Definition at line 30 of file XNUMBR.c.