My Project: ZSURF.c File Reference
ZSURF.c File Reference
#include "f2c.h"
Macros
#define def_1 def_
#define dshar3_1 dshar3_
#define znumbr_1 znumbr_
#define ldef_1 ldef_
#define knumbr_1 knumbr_
Functions
int zsurf_ (doublereal *pl)
Variables
struct {
doublereal a [24]
doublereal ahold [8]
doublereal c1 [8]
doublereal ln1 [5]
doublereal r__ [10]
doublereal ref [8]
} def_
struct {
doublereal c__ [7]
doublereal g [10]
doublereal l [4]
doublereal p [16]
doublereal sc [16]
doublereal t [12]
doublereal t1 [12]
doublereal v [10]
} dshar3_
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
struct {
logical jcs
logical prnton
logical refflg
logical subflg
logical unflag
logical zflag
logical jds
logical boundf
logical pchlst
logical canflg
logical bnderr
logical tabprt
logical refmot
logical altmlt
} ldef_
struct {
integer k0
integer k1
integer k2
integer k3
integer k4
integer k5
integer k6
integer k7
integer k8
integer k9
integer k10
integer k12
integer k13
integer k15
integer k16
integer k18
integer k19
integer k23
integer k24
integer k25
integer k26
integer k27
integer k29
integer k30
integer k31
integer k32
integer k33
integer k34
integer k44
integer k45
integer k46
integer k47
integer k48
integer k50
integer k51
integer k52
integer k1013
integer k1e4
integer k1e6
integer km1
} knumbr_
static integer c__49 = 49
Macro Definition Documentation
#define def_1 def_
Definition at line 22 of file ZSURF.c.
Referenced by zsurf_().
#define dshar3_1 dshar3_
Definition at line 28 of file ZSURF.c.
Referenced by zsurf_().
#define knumbr_1 knumbr_
Definition at line 51 of file ZSURF.c.
Referenced by zsurf_().
#define ldef_1 ldef_
Definition at line 43 of file ZSURF.c.
Referenced by zsurf_().
#define znumbr_1 znumbr_
Definition at line 36 of file ZSURF.c.
Function Documentation
int zsurf_ (doublereal * pl)
Definition at line 79 of file ZSURF.c.
References apt077_(), c__49, def_1, dshar3_1, error_(), i__, knumbr_1, ldef_1, and pl.
Referenced by apt085_(), refsys_(), and xcall_().
 {
     /* Initialized data */
     static doublereal zlit1 = .1;
     static integer i__;
     extern /* Subroutine */ int apt077_(doublereal *, integer *), error_(
         integer *, char *, ftnlen);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  2.  DEF BLOCK    *** */
 /*   REAL VARIABLES USED BY DEFINITION ROUTINES */
 /*   WHICH MUST REMAIN INVIOLATE */
 /*   ***  3.  DSHARE BLOCK 3  *** */
 /*   USED FOR REAL VARIABLES AND SHARED WITH ARELEM */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
 /* ...  13. IBRKPT BLOCK. USED FOR DYNDMP BREAKPNTS. INTEGER EQUIVALENCED */
 /* ...      TO ISV(30). */
 /*   ***  11.  LDEF BLOCK  *** */
 /*   LOGICAL VARIABLES WHICH MUST REMAIN INVIOLATE */
 /*   *** 16.  ISHARE16 BLOCK *** */
 /*   THESE ALL APPEAR TO BE USED AS LOCAL VARIABLES */
 /*   I.E.  I,J,K,M,N,J11,L11,M11 */
 /*   ***  19.  KNUMBR BLOCK  *** */
 /*      INTEGER LITERALS */
     /* Parameter adjustments */
     --pl;
     /* Function Body */
 /* ...     CHECK VALIDITY AND TRANSFORM */
     apt077_(&pl[1], &knumbr_1.k0);
     if (ldef_1.unflag) {
     goto L30;
     }
 /* .... ERROR WHEN ZSURF IS PARALEL TO ZAXIS OF LOCAL SYSTEM */
     if (abs(dshar3_1.l[2]) < zlit1) {
     goto L30;
     }
     ldef_1.zflag = FALSE_;
 /* ...     MOVE ZSURF INTO REF ARRAY */
     for (i__ = 1; i__ <= 4; ++i__) {
     def_1.ref[(i__ << 1) - 2] = pl[i__];
 /* L10: */
     def_1.ref[(i__ << 1) - 1] = dshar3_1.l[i__ - 1];
     }
 L20:
     return 0;
 L30:
     error_(&c__49, "ZSURF   ", (ftnlen)8);
     goto L20;
 } /* zsurf_ */
Variable Documentation
doublereal a[24]
Definition at line 18 of file ZSURF.c.
doublereal ahold[8]
Definition at line 18 of file ZSURF.c.
logical altmlt
Definition at line 39 of file ZSURF.c.
logical bnderr
Definition at line 39 of file ZSURF.c.
logical boundf
Definition at line 39 of file ZSURF.c.
doublereal c1[8]
Definition at line 18 of file ZSURF.c.
doublereal c__[7]
Definition at line 25 of file ZSURF.c.
integer c__49 = 49 static
Definition at line 55 of file ZSURF.c.
Referenced by zsurf_().
logical canflg
Definition at line 39 of file ZSURF.c.
struct { ... } def_
doublereal degrad
Definition at line 31 of file ZSURF.c.
struct { ... } dshar3_
doublereal g[10]
Definition at line 25 of file ZSURF.c.
logical jcs
Definition at line 39 of file ZSURF.c.
logical jds
Definition at line 39 of file ZSURF.c.
integer k0
Definition at line 46 of file ZSURF.c.
integer k1
Definition at line 46 of file ZSURF.c.
integer k10
Definition at line 46 of file ZSURF.c.
integer k1013
Definition at line 46 of file ZSURF.c.
integer k12
Definition at line 46 of file ZSURF.c.
integer k13
Definition at line 46 of file ZSURF.c.
integer k15
Definition at line 46 of file ZSURF.c.
integer k16
Definition at line 46 of file ZSURF.c.
integer k18
Definition at line 46 of file ZSURF.c.
integer k19
Definition at line 46 of file ZSURF.c.
integer k1e4
Definition at line 46 of file ZSURF.c.
integer k1e6
Definition at line 46 of file ZSURF.c.
integer k2
Definition at line 46 of file ZSURF.c.
integer k23
Definition at line 46 of file ZSURF.c.
integer k24
Definition at line 46 of file ZSURF.c.
integer k25
Definition at line 46 of file ZSURF.c.
integer k26
Definition at line 46 of file ZSURF.c.
integer k27
Definition at line 46 of file ZSURF.c.
integer k29
Definition at line 46 of file ZSURF.c.
integer k3
Definition at line 46 of file ZSURF.c.
integer k30
Definition at line 46 of file ZSURF.c.
integer k31
Definition at line 46 of file ZSURF.c.
integer k32
Definition at line 46 of file ZSURF.c.
integer k33
Definition at line 46 of file ZSURF.c.
integer k34
Definition at line 46 of file ZSURF.c.
integer k4
Definition at line 46 of file ZSURF.c.
integer k44
Definition at line 46 of file ZSURF.c.
integer k45
Definition at line 46 of file ZSURF.c.
integer k46
Definition at line 46 of file ZSURF.c.
integer k47
Definition at line 46 of file ZSURF.c.
integer k48
Definition at line 46 of file ZSURF.c.
integer k5
Definition at line 46 of file ZSURF.c.
integer k50
Definition at line 46 of file ZSURF.c.
integer k51
Definition at line 46 of file ZSURF.c.
integer k52
Definition at line 46 of file ZSURF.c.
integer k6
Definition at line 46 of file ZSURF.c.
integer k7
Definition at line 46 of file ZSURF.c.
integer k8
Definition at line 46 of file ZSURF.c.
integer k9
Definition at line 46 of file ZSURF.c.
integer km1
Definition at line 46 of file ZSURF.c.
struct { ... } knumbr_
doublereal l[4]
Definition at line 25 of file ZSURF.c.
struct { ... } ldef_
doublereal ln1[5]
Definition at line 18 of file ZSURF.c.
doublereal p[16]
Definition at line 25 of file ZSURF.c.
logical pchlst
Definition at line 39 of file ZSURF.c.
doublereal pi
Definition at line 31 of file ZSURF.c.
logical prnton
Definition at line 39 of file ZSURF.c.
doublereal r__[10]
Definition at line 18 of file ZSURF.c.
doublereal ref[8]
Definition at line 18 of file ZSURF.c.
logical refflg
Definition at line 39 of file ZSURF.c.
logical refmot
Definition at line 39 of file ZSURF.c.
doublereal sc[16]
Definition at line 25 of file ZSURF.c.
logical subflg
Definition at line 39 of file ZSURF.c.
doublereal t[12]
Definition at line 25 of file ZSURF.c.
doublereal t1[12]
Definition at line 25 of file ZSURF.c.
logical tabprt
Definition at line 39 of file ZSURF.c.
logical unflag
Definition at line 39 of file ZSURF.c.
doublereal v[10]
Definition at line 25 of file ZSURF.c.
doublereal z0
Definition at line 31 of file ZSURF.c.
doublereal z1
Definition at line 31 of file ZSURF.c.
doublereal z10
Definition at line 31 of file ZSURF.c.
doublereal z11em1
Definition at line 31 of file ZSURF.c.
doublereal z12em1
Definition at line 31 of file ZSURF.c.
doublereal z1e38
Definition at line 31 of file ZSURF.c.
doublereal z1e6
Definition at line 31 of file ZSURF.c.
doublereal z1em1
Definition at line 31 of file ZSURF.c.
doublereal z1em2
Definition at line 31 of file ZSURF.c.
doublereal z1em3
Definition at line 31 of file ZSURF.c.
doublereal z1em5
Definition at line 31 of file ZSURF.c.
doublereal z1em6
Definition at line 31 of file ZSURF.c.
doublereal z1em7
Definition at line 31 of file ZSURF.c.
doublereal z1em9
Definition at line 31 of file ZSURF.c.
doublereal z2
Definition at line 31 of file ZSURF.c.
doublereal z3
Definition at line 31 of file ZSURF.c.
doublereal z5
Definition at line 31 of file ZSURF.c.
doublereal z5em1
Definition at line 31 of file ZSURF.c.
doublereal z5em6
Definition at line 31 of file ZSURF.c.
doublereal z6em1
Definition at line 31 of file ZSURF.c.
doublereal z90
Definition at line 31 of file ZSURF.c.
doublereal z9em1
Definition at line 31 of file ZSURF.c.
logical zflag
Definition at line 39 of file ZSURF.c.
doublereal zm1
Definition at line 31 of file ZSURF.c.
struct { ... } znumbr_