My Project: ZVECT.c File Reference
ZVECT.c File Reference
#include "f2c.h"
Macros
#define znumbr_1 znumbr_
Functions
logical zvect_ (doublereal *result)
Variables
struct {
doublereal z0
doublereal z1
doublereal z2
doublereal z3
doublereal z5
doublereal z10
doublereal z90
doublereal z1e6
doublereal z1e38
doublereal z5em1
doublereal z6em1
doublereal z9em1
doublereal z11em1
doublereal z12em1
doublereal z1em2
doublereal z1em3
doublereal z1em5
doublereal z5em6
doublereal z1em6
doublereal z1em7
doublereal z1em9
doublereal z1em1
doublereal zm1
doublereal degrad
doublereal pi
} znumbr_
Macro Definition Documentation
#define znumbr_1 znumbr_
Definition at line 23 of file ZVECT.c.
Referenced by zvect_().
Function Documentation
logical zvect_ (doublereal * result)
Definition at line 43 of file ZVECT.c.
References ckdef_(), result, and znumbr_1.
Referenced by apt012_(), apt047_(), apt055_(), apt056_(), apt073_(), and apt088_().
 {
     /* System generated locals */
     logical ret_val;
     /* Local variables */
     extern logical ckdef_(doublereal *);
 /*    THE ORIGINAL COMMON-DIMENSION-EQUIVALENCE (CDE) PACKAGE TOTAL */
 /*    HAS BEEN REPLACED BY INDIVIDUAL COMMON BLOCKS, AND EQUIVALENCE */
 /*    STATEMENTS HAVE BEEN ELIMINATED AS FAR AS POSSIBLE. */
 /*   ***  10.  ZNUMBR BLOCK  *** */
 /*   REAL LITERALS */
     /* Parameter adjustments */
     --result;
     /* Function Body */
     ret_val = ! ckdef_(&result[1]) && abs(result[1]) + abs(result[2]) + abs(
         result[3]) > znumbr_1.z5em6;
     return ret_val;
 } /* zvect_ */
Variable Documentation
doublereal degrad
Definition at line 18 of file ZVECT.c.
doublereal pi
Definition at line 18 of file ZVECT.c.
doublereal z0
Definition at line 18 of file ZVECT.c.
doublereal z1
Definition at line 18 of file ZVECT.c.
doublereal z10
Definition at line 18 of file ZVECT.c.
doublereal z11em1
Definition at line 18 of file ZVECT.c.
doublereal z12em1
Definition at line 18 of file ZVECT.c.
doublereal z1e38
Definition at line 18 of file ZVECT.c.
doublereal z1e6
Definition at line 18 of file ZVECT.c.
doublereal z1em1
Definition at line 18 of file ZVECT.c.
doublereal z1em2
Definition at line 18 of file ZVECT.c.
doublereal z1em3
Definition at line 18 of file ZVECT.c.
doublereal z1em5
Definition at line 18 of file ZVECT.c.
doublereal z1em6
Definition at line 18 of file ZVECT.c.
doublereal z1em7
Definition at line 18 of file ZVECT.c.
doublereal z1em9
Definition at line 18 of file ZVECT.c.
doublereal z2
Definition at line 18 of file ZVECT.c.
doublereal z3
Definition at line 18 of file ZVECT.c.
doublereal z5
Definition at line 18 of file ZVECT.c.
doublereal z5em1
Definition at line 18 of file ZVECT.c.
doublereal z5em6
Definition at line 18 of file ZVECT.c.
doublereal z6em1
Definition at line 18 of file ZVECT.c.
doublereal z90
Definition at line 18 of file ZVECT.c.
doublereal z9em1
Definition at line 18 of file ZVECT.c.
doublereal zm1
Definition at line 18 of file ZVECT.c.
struct { ... } znumbr_