**** SOURCE FILE : DDPARS00.ORG   ***
*
      SUBROUTINE DDPARS(PCANON)
*
*  * DDPARS *  VAX-11 FORTRAN 77 VERSION  29.8.86  E.MCLELLAN
*
*  PURPOSE     TO SET THE ADDRESSES OF THE PARAMETERS U AND V
*              IN THE ARGUMENT LIST FOR A CALL TO DDPARA AND
*              TO SERVE AS A DISPATCHER BETWEEN DDST AND DDPARA
*
*  CALLING SEQUENCE
*              CALL DDPARS(PCANON)
*  ARGUMENTS
*              PCANON   ARRAY CONTAINING THE CANONICAL FORM OF
*                      A PARAMTRIC SURFACE
*
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
C
      INCLUDE 'LDEF.INC'
      INCLUDE 'BLANKCOM.INC'
C
C
      INTEGER XCANON
      EXTERNAL XCANON
C
      DIMENSION PCANON(10)
C
C
C.....PICK UP VIRTUAL ADDRESSES OF U AND V FROM PCANON ARRAY
C
      IU=INT(PCANON(2))
      IV=INT(PCANON(3))
C
C.....CONVERT TO ACTUAL ADDRESSES
C
      IF (CANFLG) IU=XCANON(IU)
      U=COM(IU)
      IF (CANFLG) IV=XCANON(IV)
      V=COM(IV)
C
C.....CALL DDPARA(U,V)
C
      CALL DDPARA(U,V)
C
      RETURN
      END
