**** SOURCE FILE : M0002840.V05   ***
*
CCCCCCCCC
C....    FORTRAN SUBROUTINE ....  LCLS             RC  4/70
C
      SUBROUTINE LCLS(U,V,SSP,DDERU,DDERV,MMODE)
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
C
C...CALLS TO PARCHK & FCN HAVE BEEN COMMENTED OUT AS THE PARSRF
C....FACILITY IS NOT PROVIDED.   24/9/86.   E.MCLELLAN.
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'SV.INC'
      INCLUDE 'ZNUMBR.INC'
      INCLUDE 'IFXCOR.INC'
      INCLUDE 'KNUMBR.INC'
      INCLUDE 'BLANKCOM.INC'
C
      DIMENSION SSP(3),DDERU(3),DDERV(3),R2(3),R3(3)
      DATA DD/0.0D0/
C
C  --------------------------------------------------------------~
C
      IF(MMODE.NE.1) GO TO 5
C      CALL PARCHK(CANON(IC),KER)
      IF(KER.EQ.1) CALL AERR(27003,'LCLS    ')
    5 CONTINUE
C------MM=1  DERIV CASE.  MM=0  NODER CASE.
 4000 MM=CANON(IC+3)
      IF(MM.EQ.0) GO TO 10
C      CALL FCN (CANON(IC),U,V,SSP,DDERU,DDERV,W1,W2,W3,W4,W5,W6)
      IF(MMODE.EQ.1) GO TO 1000
 2000 CONTINUE
      GO TO 60
C
   10 DINCX=0.0001
C------COMPUTE THE SURFACE POINT
C      CALL FCN (CANON(IC),U,V,SSP,DDERU,DDERV,W1,W2,W3,W4,W5,W6)
      IF(MMODE.EQ.1) GO TO 1000
 3000 CONTINUE
C------COMPUTE THE PARTIAL DERIVATIVE WITH RESPECT TO U
      U4=U+DINCX
C      CALL FCN (CANON(IC),U4,V,R3,DDERU,DDERV,W1,W2,W3,W4,W5,W6)
      U2=U-DINCX
C      CALL FCN (CANON(IC),U2,V,R2,DDERU,DDERV,W1,W2,W3,W4,W5,W6)
      DO 20 I=1,3
   20 DDERU(I)=(R3(I)-R2(I))/(2*DINCX)
C------COMPUTE THE PARTIAL WITH RESPECT TO V
      V1=V+DINCX
C      CALL FCN (CANON(IC),U,V1,R3,DDERV,DDERV,W1,W2,W3,W4,W5,W6)
      V2=V-DINCX
C      CALL FCN (CANON(IC),U,V2,R2,DDERV,DDERV,W1,W2,W3,W4,W5,W6)
      DO 30 I=1,3
   30 DDERV(I)=(R3(I)-R2(I))/(2*DINCX)
C
   60 CALL CROSS(DDERU(1),DDERV(1),SN(1,IS))
      CALL VNORM(SN(1,IS),SN(1,IS))
      IF(IER.EQ.1) CALL AERR(27002,'LCLS    ')
      RETURN
 1000 KKK=1
      IF(DDERU(1).EQ.DD.AND.DDERU(2).EQ.DD.AND.DDERU(3).EQ.DD.AND.
     C   DDERV(1).EQ.DD.AND.DDERV(2).EQ.DD.AND.DDERV(3).EQ.DD) KKK=0
      IF(MM.EQ.1.AND.KKK.EQ.1) GO TO 2000
      IF(MM.EQ.0.AND.KKK.EQ.0) GO TO 3000
      CALL AERR(-27001,'LCLS    ')
      CANON(IC+3)=KKK
      GO TO 4000
      END
