**** SOURCE FILE : M0004345.V14   ***
*
      SUBROUTINE APT108(A,A1,A2,A3)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C---  PURPOSE  IS TO ACCEPT PART PROGRAMMERS INPUT FOR THE DEFINITION
C---  OF A SYNTHETIC CURVE AND PROCESS THIS  INTO  COONS RATIONAL
C---   PARAMETRIC CUBIC SEGMENTS.  THE PROCESSED DATA BASE IS THEN
C---   DISPLAYED ON THE VLFILE(SPRINT) AND SAVED(APT094) AS A LARGE DATA
C---  DATA ARRAY.
C---   A(3) INPUT  CONTAINS 1 AND 2 THE INTERNAL CANON FORM OF THE
C---               SYNTHETIC CURVE .  A(3) IS THE PP NAME
C---   BLANK COMMON CANON(41 THRU ... ) CONTAINS THE PART PROGRAMMERS
C---           INPUT STREAM
C---  SC IS THE WORK ARRAY WHICH IS USED TO BUILD UP THE ANALYTIC DEFIN
C---               ITION OF THE CURVE
C
      COMMON/IBUGG/IBUG,IPCOLC,IPCOMC
C
      INCLUDE 'TOTAL.INC'
C
C
      DIMENSION A(*)
C
      INCLUDE 'BLANKCOM.INC'
C
C---     SC(4,6,31) HOLDS BASIC CURVE, REST HOLDS FLOW EDITED INPUT
C
      INCLUDE 'SSPAD.INC'
      DIMENSION SC(4,6,32)
      EQUIVALENCE (SCAN(1),SC(1,1,1))
C
      DIMENSION XMATRX(12)
C
      DIMENSION SCI(72),SCB(24),SCV0(24),SCV1(24),SCV2(24)
      EQUIVALENCE (SCI(1),SC(1,1,1)),(SCB(1),SC(1,1,4)),
     * (SCV0(1),SC(1,1,5)),(SCV1(1),SC(1,1,6)),(SCV2(1),SC(1,1,7))
C
      LOGICAL CKDEF
      INCLUDE 'SYMFIL.INC'
      COMMON/SSPRT/SSPRT,SSTEST
      LOGICAL SSPRT,SSTEST
      INTEGER IZAL1(9),IZAL2(5),IZAL3(10),IZAL4(6)
      CHARACTER*8 RNAM1,RNAM2,RNAM3,RNAM4,RNAMA,RNAME,BLA,SUBSC
      CHARACTER*6 CURSEG,SPLINE,COMBIN,END,TRAF,TEST,TEST1,TEST2
      CHARACTER*16 SCNAME
C
      DOUBLE PRECISION LENGTH,LIMIT,NORMAL
C
C---     THE FOLLOWING ARRAY IS SHARED FOR PRINTING
      INCLUDE 'DARRAY.INC'
C
      DATA MAXNOP/30/
      DATA NHD/1/
      DATA POINT /19./
      DATA VECTOR/20./
      DATA AREAL /21./
      DATA TANSPL/136./
      DATA CRSSPL/137./
      DATA NORMAL/013./
      DATA WEIGHT/138./
      DATA LIMIT /139./
      DATA CURSEG/'CURSEG'/
      DATA SPLINE/'SPLINE'/
      DATA COMBIN/'COMBIN'/
      DATA END/'END   '/
      DATA TRAF/'TRFORM'/
      DATA ZERO,ONE,SMAL,BIG/0.0D0, 1.0D0, 1.0D-7, 99999999.0D0/
      DATA SMAL1,SMAL2/1.D-5,1.D-3/
      DATA SUBSC/' (     )'/
C
      DATA BLA/'        '/
C
      DATA    RNAM1   /'APT108  '/,RNAM2   /'SCURV   '/,
     *          RNAM3   /'SSPLIN  '/,RNAM4   /'SMOOTH  '/,
     *          RNAMA   /'APT108??'/,RNAME   /'        '/
      DATA IMAX1/ 9/, IZAL1
     *                    / 5121, 5122, 5123, 5124, 5125,
     *                      5126, 5127, 5128, 5129/
      DATA IMAX2/ 5/, IZAL2
     *                    / 5751, 5752, 5760, 5770, 5771/
      DATA IMAX3/10/, IZAL3
     *                    / 5901, 5902, 5903, 5904, 5905,
     *                      5906, 5907, 5908, 5909, 5910/
      DATA IMAX4/ 6/, IZAL4
     *                    / 5921, 5922, 5923, 5924, 5925,
     *                      5926/
C
      CALL HOLFRM(A(3),SCNAME,1,8,NWD)
      SCNAME(9:16)=BLA
C---     IF SUBSCRIPT IS BIGGER  THAN ONE, ONLY SUBCRIPT IS SHOWN
      CALL UNPACK(A(1),MODE,ISIZE,ISUB)
      IF(ISUB.LT.1)GOTO 8
      SCNAME(9:16)=SUBSC
      CALL ICONV(ISUB,SCNAME,10,4)
      CALL HOLFRM(A(ISUB*ISIZE+ISUB),SCNAME,1,8,NWD)
    8 CONTINUE
      NP=0
      NH=41
      NHD1=NHD+1
      NSIZE=CANON(NH+4)+39
      NSZSAV=NSIZE
      M1=MAXNOP+NHD
      NS=NH+8
C
C...SET TEST1 & TEST2 TO BE CHARACTER EQUIVALENTS OF A1 & A2.
      CALL HOLFRM(A1,TEST1,1,6,NWD)
      CALL HOLFRM(A2,TEST2,1,6,NWD)
C
C---      FETCH THE TRFORM MATRIX IF PRESENT AND THEN TRUNCATE
C---      THE LENGTH OF INPUT DATA TO IGNORE THE TRAILING MATRIX
      IF(TEST2.NE.TRAF) GO TO 9
      L=CANON(45)-12-1+40
      DO 7 I=1,12
      XMATRX(I)=CANON(L+I)
    7 CONTINUE
      NSIZE=NSIZE-14
      NSZSAV=NSIZE
    9 CONTINUE
C
C---      SCAN INPUT STREAM FOR FLOW/SEG DATA.  IF FOUND IFLSEG=1 ELSE 0
      CALL FLOSEG(NSIZE,NSZSAV,1,IFLSEG,IRR)
      IF(IRR.NE.0) GO TO 995
C
C
C---    NOW REDUCE SIZE PARAMETER SINCE ALL FLOW/SEGMENT
C---     INFORMATION HAS BEEN STORED IN THE STEMP BUFFER
      NSIZE=NSZSAV
C
C
C---     NORMAL PHYSICAL SHAPE OF CURVE IS PROCESSED NOW
C--------------------------------------------------------
C---     BRANCH TO SPECIAL PROCESSING FOR MODE COMBINE.
      IF(TEST1.EQ.COMBIN) GO TO 3000
C
C----     SCAN AND ORGANIZE INPUT DATA FOR SPLINE OR CURSEG DEFN.
C--- INITIALIZE THE SCRATCH PAD AREA FOR A CURVE
      DO 1 L=1,M1
      DO 2 K=1,6
      DO 2 J=1,4
    2 SC(J,K,L)=ZERO
      IF(L.GT.NHD) SC(1,5,L)=ONE
      IF(L.GT.NHD) SC(2,5,L)=ZERO
    1 CONTINUE
C****  FIRST WORD MUST BE SPLINE OR CURSEG
      SC(2,1,1)=NHD
      IRR=1
      CALL HOLFRM(CANON(NS),TEST,1,6,NWD)
      IF(TEST.NE.SPLINE.AND.TEST.NE.CURSEG) GO TO 998
      IF(TEST.EQ.SPLINE) SC(3,1,1)=2.0
      IF(TEST.EQ.CURSEG) SC(3,1,1)=3.0
      NS=NS+1
C
   10 CONTINUE
      T=CANON(NS)
      CALL HOLFRM(T,TEST,1,6,NWD)
      IF(TEST.EQ.END.OR.NS.GT.NSIZE) GO TO 1000
      IF(T.EQ.POINT) GO TO 100
      IF(T.EQ.TANSPL.OR.T.EQ.CRSSPL.OR.T.EQ.NORMAL) GO TO 200
      IF(T.EQ.WEIGHT) GO TO 300
      IF(T.EQ.LIMIT) GO TO 400
C****  ILLEGAL TERM IN INPUT STREAM
      IRR=2
      GO TO 998
C---   PROCESS AN INPUT POINT
  100 CONTINUE
      NP=NP+1
      IRR=3
      IF(NP.GT.MAXNOP) GO TO 998
      DO 110 L=1,3
  110 SC(L,1,NP+NHD)=CANON(NS+L)
      NS=NS+4
C
      GO TO 10
C---  PROCESS VECTOR CONSTRAINTS
  200 CONTINUE
C****  IF NO POINTS HAVE BEEN ENTERED, QUIT
      IRR=4
      IF(NP.EQ.0) GO TO 998
      K=2
      IF(T.EQ.CRSSPL) K=3
      IF(T.EQ.NORMAL) K=4
C***   GEOMETRIC ENTRY SHOULD BE A VECTOR
      IRR=5
      IF(CANON(NS+2).NE.VECTOR) GO TO 998
      DO 210 L=1,3
  210 SC(L,K,NP+NHD)=CANON(NS+L+2)
      SC(4,K,NP+NHD)=ONE
      NS=NS+6
C
      GO TO 10
  300 CONTINUE
C****  GEOMETRIC ARGUMENT MUST BE REAL
      IRR=6
      IF(CANON(NS+2).NE.AREAL) GO TO 998
      WT=DMAX1(SMAL,CANON(NS+3))
      WT=DMIN1(ONE,WT)
      SC(1,5,NP+NHD)=WT
      NS=NS+4
C
      IF(NP.GT.0) GO TO 10
C---   IF WEIGHT COMES BEFORE THE FIRST POINT, THIS WEIGHT IS APPLIED
C---  TO ALL POINTS
      DO 350 I=NHD1,M1
  350 SC(1,5,I)=WT
C
      GO TO 10
C---  PROCESS INPUT LIMIT CONSTRAINT
  400 CONTINUE
C****  GEOMETRIC ARGUMENT MUST BE REAL
      IRR=6
      IF(CANON(NS+2).NE.AREAL) GO TO 998
      AL=DMAX1(ZERO,CANON(NS+3))
      AL=DMIN1(BIG,AL)
      SC(2,5,NHD+NP)=AL
      NS=NS+4
C
      IF(NP.GT.0) GO TO 10
      DO 450 I=NHD1,M1
  450 SC(2,5,I)=AL
C
      GO TO 10
C---   INPUT HAS BEEN FORMALLY LOADED INTO THE SC ARRAY
C---  NOW CALL FOR ANALYTIC PROCESSING
 1000 CONTINUE
      SC(4,1,1)=NP
C
      IF(SSPRT.AND.SSTEST) CALL SCPICT(SC,SCNAME,0)
C
      CALL SCURV(SC,IRR)
      IF(IRR.NE.0) IERROR=IRR
      IF(IRR.NE.0) GO TO 996
C
C---   MOVE THE CURVE DATA FROM THE SCRATCH AREA TO BLANK COMMON
      KKC=40
      NPPLUS=NP+SC(2,1,1)
      DO 9020 K=1,NPPLUS
      DO 9020 J=1,6
      DO 9020 I=1,4
      KKC=KKC+1
 9020 CANON(KKC)=SC(I,J,K)
C
      GO TO 9000
C
C---      FETCH ALL CURVES FROM A SCURV/COMBIN COMMAND
C---      NOTE LOGIC FOR TREATMENT OF CONFLICTING CRSSPL AND NORMAL
C---      CONSTRAINT VECTORS AT CURVE JUNCTIONS.
 3000 NP=CANON(NH+3)
      K=0
      DO 3100 I=NS,NSIZE
      K=K+1
 3100 SCI(K)=CANON(I)
      NS=NH
      I=1
      NBLK=0
 4000 II=2*I-1
      JMODE=2
      IRR=7
      IF(CKDEF(SCI(II))) GO TO 998
C
C---     READ IN THE NEXT CURVE FROM THE INPUT STREAM.
C
      CALL APT094(JMODE,SCI(II),CANON(NS))
C****
C****    CURVES WITH A FLOW RATE CANNOT BE COMBINED YET
C***      AT MOST ONE FLOW CURVE CAN BE COMBINED AT PRESENT
      IF(I.GT.1.AND.CANON(NS+2).GT.9.0) GO TO 998
      NS1=NS
      NS2=NS+24
      NBLK1=CANON(NS+3)
      NBLK=NBLK+NBLK1
      NS=NBLK1*24+NS
      IF(I.EQ.1) GO TO 3200
C
      CALL CNCURV(ZERO,CANON(NS2),SCV1,1)
      SCV2(1)=DABS(SCV1(1)-SCV0(1))
      SCV2(2)=DABS(SCV1(2)-SCV0(2))
      SCV2(3)=DABS(SCV1(3)-SCV0(3))
      DDMAX=DMAX1(SCV2(1),SCV2(2),SCV2(3))
C****
      IRR=8
      IF(DDMAX.GT.SMAL1) GO TO 998
      IF(DDMAX.LT.SMAL) GO TO 3300
      DDMAX=CANON(NS2+12)
      CANON(NS2)=SCV0(1)*DDMAX
      CANON(NS2+4)=SCV0(2)*DDMAX
      CANON(NS2+8)=SCV0(3)*DDMAX
 3300 DDMAX=DABS(SCV0(13)*SCV1(13)+SCV0(14)*SCV1(14)
     *   +SCV0(15)*SCV1(15)-ONE)
C****
      IRR=9
      IF(DDMAX.GT.SMAL2) GO TO 998
C
 3400 DO 3600 J=20,24,4
      IF(DABS(SCB(J)).GT.SMAL) GO TO 3600
      IF(DABS(CANON(NS1+J-1)).LT.SMAL) GO TO 3600
      DO 3500 K=1,4
 3500 SCB(J+K-4)=CANON(NS1+J+K-5)
 3600 CONTINUE
      DO 3700 K=1,24
 3700 CANON(NS1+K-1)=SCB(K)
 3200 I=I+1
      IF(I.GT.NP) GO TO 3800
      DO 3900 K=1,24
 3900 SCB(K)=CANON(NS+K-1)
      CALL CNCURV(ONE,SCB,SCV0,1)
      GO TO 4000
C
 3800 CANON(NH+3)=NBLK
      CANON(NH+2)=4.
C
C---     NORMAL PHYSICAL SHAPE OF CURVE HAS NOW BEEN GENERATED
C---     FLOW/SEGMENTATION PROCESSING NOW FOLLOWS.
C
 9000 CONTINUE
      CANON(NH+4)=CANON(NH+1)*24.+ONE
C---     NOW ZERO OUT PART OF THE HEADER TABLE CAREFULLY
      NN=10
      DO 1005 I=1,NN
      CANON(NH+I+5)=ZERO
 1005 CONTINUE
C
C---     IF NO FLOW INPUT IS AVAILABLE, SAVE THE CURVE DATA
C---     ON AN EXTERNAL FILE
      IF(IFLSEG.EQ.0) GO TO 9010
C
      CALL FLOSEG(NSIZE,NSZSAV,2,IFLSEG,IRR)
      IF(IRR.NE.0) GO TO 995
C
C
 9010 CONTINUE
C---     SAVE SURFACE ON EXTERNAL FILE
C---      FIRST SAVE THE SIZE OF THE ARRAY IN THE INTERNAL FORM
C
      CANON(NH+4)=CANON(NH+1)*24.+ONE
      IF(CANON(NH+7).LT.SMAL) CANON(NH+11)=(CANON(NH+1)+CANON(NH+3))*24.
      IF(CANON(NH+7).LT.SMAL) CANON(NH+12)=ONE
C
      A(2)=CANON(NH+11)
 6100 CONTINUE
C
C   BESTIMMUNG DER APT-RECORD-NR.
      IREC=-5
      CALL TAPOP(AXFILE,IREC)
      CANON(NH)=IREC
      ISPRNT=2
      IF(SSTEST) ISPRNT=3
      IF(SSPRT) CALL SCPICT(CANON(NH),SCNAME,ISPRNT)
      IF(TEST2.EQ.TRAF)CALL SCTRA(XMATRX(1),A(1),CANON(NH),ISPRNT)
      KKMODE=1
      CALL APT094(KKMODE,A,CANON(NH))
      IRR=0
C
C---     SET THE MODE FOR LEVEL OF VERIFICATION PRINT
      GO TO 9999
C
C****    AREA OF CODE TO HANDLE MOST ERROR MESSAGES AND TERMINATIONS
  998 CONTINUE
      IERROR=5120+IRR
  996 RNAME=RNAMA
      DO 7001 IL1=1,IMAX1
 7001 IF (IERROR.EQ.IZAL1(IL1)) RNAME=RNAM1
      DO 7002 IL2=1,IMAX2
 7002 IF (IERROR.EQ.IZAL2(IL2)) RNAME=RNAM2
      DO 7003 IL3=1,IMAX3
 7003 IF (IERROR.EQ.IZAL3(IL3)) RNAME=RNAM3
      DO 7004 IL4=1,IMAX4
 7004 IF (IERROR.EQ.IZAL4(IL4)) RNAME=RNAM4
      CALL ERROR(IERROR,RNAME)
      IF(IRR.EQ.9) GOTO 3400
      IF(TEST1.EQ.COMBIN) GO TO  995
C
      IF(SSPRT.AND.SSTEST) CALL SCPICT(SC,SCNAME,1)
  995 CONTINUE
      CALL UNDEF(A(1))
C
C****    TERMINATION OF ERROR HANDLING CODE
C
C---    QUIT PROCESSING HERE
 9999 CONTINUE
C
      IF(IBUG.NE.11) GO TO 9711
C---      DUMP THE ENTIRE SCURV ARRAY
      NTOP=CANON(NH+11)+NH-1
      NBOT=NH
      DO 9712 I=NBOT,NTOP,4
      IF(MOD(I-NBOT,24).EQ.0) CALL BAD(-1,0,' ',0)
      CALL BAD(-4,1,'CANN',CANON(I))
 9712 CONTINUE
 9711 CONTINUE
C
      RETURN
      END
