**** SOURCE FILE : M0000680.V02   ***
*
      SUBROUTINE TOPGEN(SS)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C---     ROUTINE TO GENERATE A TOPOLOGY TABLE FOR AN OTHERWISE COMPLETE
C---      SS DATA STRUCTURE
      DIMENSION SS(*)
      DIMENSION P(3,4),PT(3,4),NSZ(4),NBOUN(8)
      DATA NSZ/1,4,12,16/,NBOUN/1,2,1,3,2,4,3,4/
      DATA ZERO,SMAL/0.0D0,1.0D-10/
      DATA IZERO/0/
C
C---     NTOT IS THE TOTAL NUMBER OF PATCHES IN THE SS ARRAY
      NTOT=SS(4)
C---    SPECIAL HANDLING FOR A GENCUR SURFACE
      IF(SS(6).LT.5.999.OR.SS(6).GT.6.001) GO TO 10
      ITOP1=11+NTOT*6+SS(2)
      GO TO 25
C
   10 CONTINUE
C---   TOPOLOGY TABLE IS ASSUMED REGULAR(CONTACT AT CORNER POINTS ONLY)
C---     FILL IN POINTERS FROM EACH PATCH HEADER TO TOPOLOGY TABLE
C---     ALSO ZERO OUT THE TOPOLOGY TABLE ENTRIES
      ITOP1=10+6*(NTOT-1)+5
      ITOP1=SS(ITOP1)
C---     ITOP1 IS THE LOCATION OF THE LAST PATCH COEFFICIENT ARRAY
      DO 20 K=1,4
      I=SS(10+6*NTOT-6+K)
      ITOP1=ITOP1+NSZ(I)
   20 CONTINUE
   25 CONTINUE
C---     ITOP1 IS THE SS LOCATION OF THE FIRST TOPOLOGY TABLE ENTRY
C---      FILL POINTERS TO THE TOPOLOGY TABLE FOR EACH PATCH
      DO 30 K=1,NTOT
      SS(10+6*K)=ITOP1+4*(K-1)
      KT=SS(10+6*K)-1
C---     ZERO OUT THE TOPOLOGY TABLE ENTRIES
      DO 30 KK=1,4
      SS(KT+KK)=0.
   30 CONTINUE
C---  NOW SEPARATE THE CASE OF A MESH SURFACE FROM PNTSON,PNTVEC,POLYGN
      NTYPE=SS(5)
      IF(NTYPE.NE.2) GO TO 200
C---     SURFACE IS A MESH TYPE
C------NUMBER OF PATCHES IN A STRIP ALONG THE MAJOR SPLINE DIRECTION
      NP=SS(10)-1
C---     NUMBER OF PATCHES IN A STRIP ALONG THE CROSS SPLINE DIRECTION
      NS=SS(9)-1
C---     PATCHES ARE STORED LINEARLY AS I,J WHERE I=1 TO NP AND THEN
C---     J = 1 TO NS
C---     GENERATE TOPOLOGY TABLE FOR EACH PATCH IN SUCCESSION
      DO 40 J=1,NS
      DO 40 I=1,NP
      ITOP=10+6*((J-1)*NP+I)
      ITOP=SS(ITOP)
      NCUR=I+(J-1)*NP
      NLOWER=(J-1)*NP+1
      NUPPER=J*NP
C---     FIRST BOUNDARY ( U= 0 TO 1= 1 WHILE V=0)
      SS(ITOP)=MAX0(IZERO,NCUR-NP)
      ITOP=ITOP+1
C---     SECOND BOUNDARY ( U=0 WHILE V= 0 TO 1 )
      KTEMP=NCUR-1
      IF(KTEMP.LT.NLOWER) KTEMP=0
      SS(ITOP)=KTEMP
      ITOP=ITOP+1
C---     THIRD BOUNDARY ( U=1 WHILE V= 0 TO 1)
      KTEMP=NCUR+1
      IF(KTEMP.GT.NUPPER) KTEMP=0
      SS(ITOP)=KTEMP
      ITOP=ITOP+1
C---     FOURTH BOUNDARY (U=0 TO 1 WHILE V=1)
      KTEMP=NCUR+NP
      IF(KTEMP.GT.NTOT) KTEMP=0
      SS(ITOP)=KTEMP
C---     THIS COMPLETES THE TOPOLOGY TABLE FOR THE MESH DEFINITION
   40 CONTINUE
      GO TO 9999
C
C
C---     THE NEXT SURFACE IS PNTSON,POLYGN OR PNTVEC
C---     ASSUMPTIONS:  THE PATCHES HAVE FLAGS 4,4,4,1
C---     ASSUMPTIONS:  TWO ADJACENT PATCHES HAVE CONTACT IN TWO CORNER
C---     POINTS
  200 CONTINUE
C---     RESOLVE TOPOLOGY RELATIONS ONE PATCH AT A TIME
      DO 210 I=1,NTOT
      ITOP=SS(10+6*I)
      IPREL=SS(10+6*I-1)-1
C---     LOAD THE CORNER POINTS(USING THE MATRIX ASSUMPTION)
      DO 220 K=1,3
      KK=(K-1)*16
      P(K,1)=SS(IPREL+KK+1)
      P(K,2)=SS(IPREL+KK+2)
      P(K,3)=SS(IPREL+KK+5)
  220 P(K,4)=SS(IPREL+KK+6)
C---     COMPARE EACH BOUNDARY OF THE I TH PATCH TO OTHER PATCHES
      DO 230 J=1,4
C---     BOUNDARY 1  POINTS P(,1) TO P(,2)
C---     BOUNDARY 2  POINTS P(,1) TO P(,3)
C---     BOUNDARY 3  POINTS P(,2) TO P(,4)
C---     BOUNDARY 4  POINTS P(,3) TO P(,4)
      JA=NBOUN(2*J-1)
      JB=NBOUN(2*J)
C---     CHECK EACH PATCH AGAINST BOUNDARY J OF PATCH I
      DO 240 L=1,NTOT
      IF (L.EQ.I) GO TO 240
      IPRELT=SS(10+6*L-1)-1
C---     LOAD CORNER POINTS OF PATCH L
      DO 250 K=1,3
      KK=(K-1)*16
      PT(K,1)=SS(IPRELT+KK+1)
      PT(K,2)=SS(IPRELT+KK+2)
      PT(K,3)=SS(IPRELT+KK+5)
  250 PT(K,4)=SS(IPRELT+KK+6)
      DO 260 M=1,4
      MA=NBOUN(2*M-1)
      MB=NBOUN(2*M)
      D=ZERO
      DO 280 NN=1,3
  280 D=D+(P(NN,JA)-PT(NN,MA))**2+(P(NN,JB)-PT(NN,MB))**2
      IF (D.GT.SMAL) GO TO 290
      GO TO 300
  290 D=ZERO
      DO 310  NN=1,3
  310 D=D+(P(NN,JA)-PT(NN,MB))**2+(P(NN,JB)-PT(NN,MA))**2
      IF(D.GT.SMAL) GO TO 260
C---     BOUNDARY CHECK IS POSITIVE LTH PATCH LIES ACROSS J TH BOUNDARY
C---     OF THE I TH PATCH
  300 ITOPIJ=10+6*I
      ITOPIJ=SS(ITOPIJ)
      SS(ITOPIJ-1+J)=L
  260 CONTINUE
  240 CONTINUE
  230 CONTINUE
  210 CONTINUE
C
C
 9999 CONTINUE
      RETURN
      END
