*
*
*  *  LINKF  *   FORTRAN 77 SUBROUTINE   6-DEC-85   E.MCLELLAN
*
*  PURPOSE:     TO CALL NEXT PHASE
*
*  CALLING SEQUENCE:
*                   CALL LINKF(PHASE)
*  ARGUMENTS:
*                   TYPE       DESCRIPTION
*           PHASE   CHARACTER  PHASE NAME
*
*  GLOBAL VARIABLES: NONE
*
*  LOCAL VARIABLES: NONE
*
*  FILES: NONE
*
*  SUBSIDIARIES: NONE
*
      SUBROUTINE LINKF(PHASE)
C
      CHARACTER*8 PHASE
C
      INCLUDE 'DARRAY.INC'
C
      IF (PHASE.EQ.'TRANSLAT') THEN
         CALL START
      ELSE IF (PHASE.EQ.'XECUTION') THEN
         CALL EXEC
      ELSE IF (PHASE.EQ.'CLEDITOR') THEN
         CALL CLED
      ELSE IF (PHASE.EQ.'POSTEXEC') THEN
         CALL ACNTRL
      ELSE
         CALL CFORM('  *** FAILURE IN LINKF - ',DARRAY,1,25)
         CALL CFORM('REQUESTED PHASE = ',DARRAY,26,18)
         CALL CFORM(PHASE,DARRAY,43,8)
         CALL CPRINT(DARRAY)
         CALL ABNEND
      END IF
C
      RETURN
      END
