**** SOURCE FILE : ABCDBN00.ORG   ***
*
*
*  * ABCDBN *    FORTRAN 77 VERSION  11-JUL-1986  E.MCLELLAN
*
*   PURPOSE      TO CONVERT FLOATING POINT NUMBERS
*                FROM LEFT JUSTIFIED CHARACTER FORM
*                TO DOUBLE PRECISION VALUES
*
*   CALLING SEQUENCE
*                CALL ABCDBN(STR,VALUE,NUM)
*
*   ARGUMENTS
*       STR     CHARACTER   STRING ARRAY CONTAINING NUMBERS
*                           LEFT JUSTIFIEDIN 12 BYTES,
*                           TO BE CONVERTED TO FLOATING POINT
*       VALUE   DOUBLE      ARRAY TO CONTAIN CONVERTED NUMBERS
*               PRECISION
*       NUM     INTEGER     NUMBER OF ITEMS IN ARRAY
*
      SUBROUTINE ABCDBN(STR,VALUE,NUM)
C
      INTEGER NUM
      CHARACTER*12 STR(NUM),TSTR
      DOUBLE PRECISION VALUE(NUM)
C
      DO 10 I=1,NUM
        TSTR=STR(I)
        K=INDEX(TSTR,'.')
        IF (K.EQ.0) THEN
          J=INDEX(TSTR,' ')
          IF (J.NE.0) THEN
            TSTR(J:J)='.'
          ENDIF
        ENDIF
        READ (TSTR,'(F12.0)') VALUE(I)
 10   CONTINUE
      RETURN
      END
