**** SOURCE FILE : BADNAM00.V01   ***
*
*
*  * BADNAM *    FORTRAN 77 SUBROUTINE   15-JUL-1986  E.MCLELLAN
*
*   PURPOSE:  TO RETURN THE BCD EQUIVALENT OF 'BADNAM  '
*
*   CALLING SEQUENCE:
*                    CALL BADNAM(IWORD)
*
*   ARGUMENTS:
*         IWORD  INTEGER  ARRAY INTO WHICH 'BADNAM  ' IS TO BE LOADED
*
*   GLOBAL VARIABLES: NONE
*
*   LOCAL VARIABLES:
*                   TYPE        DESCRIPTION
*         IBDNAM    INTEGER     INTEGER ARRAY TO BUILD UP BCDF
*         FIRST     LOGICAL     FLAG INDICATING FIRST CALL
*
*   SUBSIDIARIES:  BCDF
*
      SUBROUTINE BADNAM(IWORD)
C
      INTEGER BCDF
C
      INTEGER IBDNAM(2),IWORD(2)
      LOGICAL FIRST
      SAVE IBDNAM,FIRST
      DATA FIRST/.TRUE./
                        
      IF (FIRST) THEN
        IBDNAM(1) = BCDF('BADN')
        IBDNAM(2) = BCDF('AM  ')
        FIRST=.FALSE.
      ENDIF
C
      IWORD(1)=IBDNAM(1)
      IWORD(2)=IBDNAM(2)
      RETURN
      END
