**** SOURCE FILE : FCONV000.ORG   ***
*
*
*  *  FCONV  *    VAX11  FORTRAN VERSION 8.6.82  E.MCLELLAN
*
*                          IMPROVED      25.06.82  E.MCLELLAN
*                          MODIFIED      16.07.85  E.MCLELLAN
*
*  PURPOSE     TO CONVERT FLOATING POINT NUMBERS TO ALPHAMERIC
*              REPRESENTATION
*  CALLING SEQUENCE
*              CALL FCONV(F,A,N,I,J)
*  ARGUMENTS
*              F   DOUBLE PRECISION NUMBER TO BE CONVERTED
*              A   CHARACTER STRING TO CONTAIN THE CHARACTERS
*              N   INTEGER INDICATING THE STARTING BYTE POSITION
*                  FROM THE LEFT, TO STORE THE CHARACTERS IN A
*              I   NUMBER OF CHARCTERS DESIRED
*              J   NUMBER OF FRACTIONAL DIGITS REQUIRED
*
      SUBROUTINE FCONV(F,A,N,I,J)
C
      DOUBLE PRECISION F,DLSD,TENTOJ,FJ
      CHARACTER*(*) A
      CHARACTER*35 INFIL
C
C.... CHECK SIZE OF VALUE F
C
      IF ((F.LT.-2.**31).OR.(F.GT.(2.**31-1)).OR.
     1  (F.LE.-10.**(I-J-2)).OR.(F.GE.10.**(I-J-1))) THEN
C.... FOR LARGE NUMBERS AND VALUES WHICH WOULD OVERFLOW
C     REQUESTED FIELD - OUTPUT IN D FORMAT
C
        WRITE (INFIL,'(D35.15)') F
        K=14
        IF (INFIL(K:K).EQ.' ') K=15
C.... STORE MANTISSA TO MAX NO OF SIGNIFICANT FIGS FOR FIELD
        I1=N
        I2=N+I-5
        K1=K+I-5
        A(I1:I2)=INFIL(K:K1)
C.... NOW ADD EXPONENT
        I1=I2+1
        I2=I2+4
        A(I1:I2)=INFIL(32:35)
C
      ELSE
C
C.... NORMAL ROUTE
C
C.... ROUND F TO J DECIMAL PLACES
      TENTOJ=10.D0**J
      MSD=INT(F)
      DLSD=F-DFLOAT(MSD)
      LSD=INT(DLSD*TENTOJ+DSIGN(0.5D0,F))
      FJ=DFLOAT(MSD)+DFLOAT(LSD)/TENTOJ
      WRITE (INFIL,'(F35.10)') FJ
      DO 10 K=1,35
      IF (INFIL(K:K).NE.' ') GOTO 20
   10 CONTINUE
      K=35
C
   20 L=25-K+1+J
C
      I2=N+I-1
      I1=I2-L+1
      K1=25+J
      A(I1:I2)=INFIL(K:K1)
C
      ENDIF
C
      RETURN
      END
