**** SOURCE FILE : BDINT.ORG   ***
*
      BLOCK DATA BDINT
C
C.... INITIALIZE INTERFERENCE TABLE
C
      INCLUDE 'INTERF.INC'
C
      INTEGER MAXNP3
      PARAMETER (MAXNP3=3*MAXNP)
      DATA DINTR/MAXNP*0.D0/,UINTR/MAXNP*0.D0/,VINTR/MAXNP*0.D0/
      DATA LDINTR/MAXNP*0.D0/,LUINTR/MAXNP*0.D0/,LVINTR/MAXNP*0.D0/
      DATA TPINTR/MAXNP3*0.D0/,SPINTR/MAXNP3*0.D0/,SNINTR/MAXNP3*0.D0/
      DATA PINTR/MAXNP*0/,LPINTR/MAXNP*0/,ISEG/MAXNP*0/
      DATA NPINTR/0/,LNPINT/0/
C
      END
         
