**** SOURCE FILE : CURCAL.V01   ***
*
      SUBROUTINE CURCAL(RU,RV,RUU,RUV,RVV,RNORM,SIDE,CURVE1,CURVE2)
C
C     PURPOSE: TO CALCULATE PRINCIPAL CURVATURES CURVE1,CURVE2
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DIMENSION RU(3),RV(3),RUU(3),RUV(3),RVV(3),RNORM(3)
C.... WORKSPACE
      DIMENSION W(3)
C
      INCLUDE 'ZNUMBR.INC'
C
C     CALC. 1ST FUNDAMENTAL MATRIX G
      CALL DOTF(G11,RU,RU)
      CALL DOTF(G22,RV,RV)
      CALL DOTF(G12,RU,RV)
C
C     CALC. 2ND FUNDAMENTAL MATRIX D
C
C.... TAKE SURFACE NORMAL POINTING TOWARDS TOOL
C
      DO 10 I=1,3
        W(I)=SIDE*RNORM(I)
  10  CONTINUE
C
      CALL DOTF(D11,W,RUU)
      CALL DOTF(D12,W,RUV)
      CALL DOTF(D22,W,RVV)
C
C     CALC. COEFFS. FOR QUADRATIC IN CURVATURE
C
      A1=G11*G22-G12*G12
      A2=-G11*D22-G22*D11+2.D0*G12*D12
      A3=D11*D22-D12*D12
C
C     SOLVE FOR CURVATURES
C
      DISC=A2*A2-Z4*A1*A3
      DISC=MAX(ZERO,DISC)
      DISC=SQRT(DISC)
C
      DENOM=A1+A1
C
      CURVE1=(-A2+DISC)/DENOM
      CURVE2=(-A2-DISC)/DENOM
C
      END
