**** SOURCE FILE : INEX.ORG   ***
*
      SUBROUTINE INEX(GEO,SIDE,TOLI,TOLO)
C
C     INTERFERENCE CHECKING INITIALISATION PROCEDURE
C
C     CALCULATES: MAXIMUM AND MINIMUM CURVATURES      CURMAX,CURMIN
C                 ITERATION LIMITS                    DULIM, DVLIM
C                 CONVEX HULLS                        CXHULL
C
C     ARGUMENTS:
C            GEO   SURFACE CANONICAL FORM
C            SIDE  TOOL SIDE OF SURFACE W.R.T. SURFACE NORMAL
C            TOLI  SURFACE INTOL
C            TOLO  SURFACE OUTTOL
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      INCLUDE 'INIDAT.INC'
C
      DIMENSION GEO(*)
C
      DIMENSION R(3),RU(3),RV(3),RUU(3),RUV(3),RVV(3),RNORM(3)
C.... MESH DIMENSION
      PARAMETER (NGRID=5)
C.... MESH POINTS
      DIMENSION RNET(NGRID*NGRID,3)
C.... PATCH CORNER POINTS
      DIMENSION NCOR(4)
      DIMENSION RCORN1(4,3),RCORN2(4,3)
C.... PATCH CORNER VECTORS
      DIMENSION CV1(4,3),CV2(4,3)
C.... POINTERS FOR ABOVE
      DIMENSION M1(4),M2(4)
      DIMENSION CENT(3),SCENT(4,3)
      DIMENSION SRAD(4)
      DIMENSION NFLAGS(4)
      DIMENSION V1(4,3),V2(6,3)
      DIMENSION W(3),W1(3)
C
C     CXHULL(I,J,K)   RETURNS CONVEX HULL DATA FOR K TH PATCH
C     I = 1 TO 3      CENTRE COORDINATES
C     I = 4           RADIUS
C     WHERE HULLS ARE CALCULATED, LOADED IN J-ORDER:-
C     MINIMUM ENCLOSING SPHERE
C     UP TO 4 "EDGE" SPHERES
C     "LID" SPHERE
C     NCXHUL(K)       NUMBER OF HULLS FOR THE K TH PATCH
C
      DATA M1/1,2,4,3/M2/4,1,3,2/
C
C.... CHECK IF THIS SURFACE HAS ALREADY BEEN PROCESSED BY INEX
C
C.... EXTERNAL LDA FILE RECORD NUMBER FOR THIS SURFACE
C
      IREC=NINT(GEO(1))
C
      IF ( (ICURSF.EQ.0).OR.(IREC.NE.ICURSF) ) THEN
C.... CURRENT SURFACE NOT PREVIOUSLY PROCESSED BY INEX
C
        ICURSF=IREC
C.... NUMBER OF PATCHES
        NGP=NINT(GEO(4))
C.... SIZE OF CANONICAL FORM
        ISIZE=NINT(GEO(8))
C
        N3=3
        N4=4
C
C     TO SET UP MESH PARAMETERS
C
C.... NUMBER OF MESH POINTS
        NNGRID=NGRID*NGRID
        N=NGRID-1
C.... MESH SIZE
        AMESH=FLOAT(1)/FLOAT(N)
        NCOR(1)=1
        NCOR(2)=NGRID
        NCOR(4)=NNGRID
        NCOR(3)=NCOR(4)-NGRID+1
C.... ALL DERIVATIVES FROM EVALUATOR
        MODE=3
C.... DISTANCE TOLERANCE
        TOLIN=(TOLI+TOLO)*0.5D0
C
C.... FOR ALL PATCHES
        DO 1000 NPATCH=1,NGP
          CRVMIN=1D6
          CRVMAX=-1.D6
          M=1
C     CALC. MESH U,V
          DO 500 K=0,N
            U=K*AMESH
            DO 400 J=0,N
              V=J*AMESH
              L=5*K+J+1
C
              CALL EVALSS(NPATCH,U,V,ISIZE,GEO,MODE,
     1                  R,RU,RV,RUU,RUV,RVV,RNORM,NORMOK)
              DO 20 I=1,3
                RNET(L,I)=R(I)
20            CONTINUE
C     IF CORNER, STORE CORNER POINTS AND EDGE VECTORS
              IF (L.EQ.NCOR(M)) THEN
                DO 30 I=1,3
                  RCORN1(M1(M),I)=R(I)
                  RCORN2(M2(M),I)=R(I)
C
                  IF (M.EQ.1 .OR. M.EQ.4) THEN
                    CV1(M1(M),I)=RV(I)
                    CV2(M2(M),I)=RU(I)
                  ELSE
                    CV1(M1(M),I)=RU(I)
                    CV2(M2(M),I)=RV(I)
                  END IF
C
30              CONTINUE
                M=M+1
              END IF
C
C     CALC. PRINCIPAL CURVATURES
C
              CALL CURCAL(RU,RV,RUU,RUV,RVV,RNORM,SIDE,CURVE1,CURVE2)
C
              CRVMAX=MAX(CRVMAX,CURVE1,CURVE2)
              CRVMIN=MIN(CRVMIN,CURVE1,CURVE2)
400         CONTINUE
500       CONTINUE
C
C     TO STORE MAXIMUM AND MINIMUM CURVATURE
          CURMAX(NPATCH)=CRVMAX
          CURMIN(NPATCH)=CRVMIN
C
C     TO CALCULATE DULIM, DVLIM
C.... A IS SUM OF U-DISTANCES BETWEEN CORNER POINTS
          A=0.D0
C.... B IS SUM OF V-DISTANCES BETWEEN CORNER POINTS
          B=0.D0
          DO 150 I=1,3
            DO 100 J=1,4
              C=RCORN1(J,I)-RCORN2(J,I)
              IF (J.EQ.1 .OR. J.EQ.3) THEN
                B=B+C*C
              ELSE
                A=A+C*C
              END IF
100         CONTINUE
150       CONTINUE
C
          DULIM(NPATCH)=TOLIN/SQRT(A)
          DVLIM(NPATCH)=TOLIN/SQRT(B)
C     DU, DV LIMITS CALCULATED
C
C     TO CALCULATE SPHERICAL CONVEX HULLS
          NHULL=0
          CALL SHELLA(RCORN1,RNET,NNGRID,N3,W,RAD)
          IF (RAD.GT.TOLIN) THEN
            NHULL=NHULL+1
            DO 200 I=1,3
              CXHULL(I,NHULL,NPATCH)=W(I)
200         CONTINUE
            CXHULL(4,NHULL,NPATCH)=RAD
          END IF
C
          CALL SHELLB(NNGRID,N3,N4,RCORN1,RCORN2,CV1,CV2,RNET,
     1              SCENT,SRAD,NFLAGS)
          DO 210 K=1,4
            IF (NFLAGS(K).EQ.1) THEN
              NHULL=NHULL+1
              DO 220 I=1,3
                CXHULL(I,NHULL,NPATCH)=SCENT(K,I)
220           CONTINUE
              CXHULL(4,NHULL,NPATCH)=SRAD(K)
            END IF
210       CONTINUE
          NCXHUL(NPATCH)=NHULL
C
1000    CONTINUE
C
      ENDIF
C
      END
