**** SOURCE FILE : INTMSG.ORG   ***
*
      SUBROUTINE INTMSG(TE,TA,INTLOC)
C
C     PURPOSE: TO PRINT MESSAGE AND RELEVANT DATA IF INTERFERENCE
C              HAS BEEN DETECTED
C
C     ARGUMENTS:
C
C     TE      -  TOOL END COORDINATES
C     TA      -  TOOL AXIS VECTOR
C     INTLOC  -  LOCATION INTERFERENCE TABLE OF WORST PENETRATION
C
      DOUBLE PRECISION TE,TA
      INTEGER INTLOC
      CHARACTER MSG*120
C
      DIMENSION TE(3),TA(3)
C
      INCLUDE 'INTERF.INC'
C
C..... PRINT MESSAGE
C
      MSG='0INTERFERENCE DETECTED'
      CALL CPRINT(MSG)
      CALL CFORM(' TE =',MSG,1,5)
      CALL FCONV(TE(1),MSG,7,13,6)
      CALL FCONV(TE(2),MSG,21,13,6)
      CALL FCONV(TE(3),MSG,35,13,6)
      CALL CFORM('TA =',MSG,52,4)
      CALL FCONV(TA(1),MSG,57,13,6)
      CALL FCONV(TA(2),MSG,71,13,6)
      CALL FCONV(TA(3),MSG,85,13,6)
      CALL CPRINT(MSG)
C
      CALL CFORM(' WORST PENETRATION =',MSG,1,20)
      CALL FCONV(DINTR(INTLOC),MSG,22,13,6)
      CALL CFORM('AT PATCH =',MSG,37,10)
      CALL ICONV(PINTR(INTLOC),MSG,48,4)
      CALL CFORM('U =',MSG,53,3)
      CALL FCONV(UINTR(INTLOC),MSG,57,9,6)
      CALL CFORM('V =',MSG,67,3)
      CALL FCONV(VINTR(INTLOC),MSG,71,9,6)
      CALL CPRINT(MSG)
C
      END
