**** SOURCE FILE : PENCUT.V01   ***
*
      SUBROUTINE PENCUT(R,RN,TOOLCE,TOOLAX,TUL,PSIDE,PTHICK,
     1      T,TN,PEN,ISEG)
C
C     CALCS. PENETRATION OF POINT R INTO CUTTER
C
C
C     T            NEAREST POINT ON TOOL TO R
C     TN           TOOL NORMAL AT T
C     ISEG  =  0   T ON:-   BOTTOM FLAT
C              1            BALL OR CORNER RADIUS
C              2            CYLINDRICAL SHANK
C     PEN      = PENETRATION: DISTANCE R-T (+VE FOR HIT)
C     PSIDE    = TOOL SIDE OF SURFACE
C     PTHICK   = PART SURFACE THICKNESS
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C.... SURFACE POINT AND NORMAL
      DIMENSION R(3),RN(3)
C.... TOOL AXIS
      DIMENSION TOOLAX(3)
C.... TOOLCENTRE
      DIMENSION TOOLCE(3)
C.... CUTTER GEOMETRY
      DIMENSION TUL(7)
C
C.... WORKSPACE
      DIMENSION V(3),V1(3),W(3)
C.... ASSOCIATED CORNER RADIUS CENTER
      DIMENSION XR(3)
C.... ASSOCIATED POINT ON TOOL AND TOOL NORMAL
      DIMENSION T(3)
      DIMENSION TN(3)
C
      DOUBLE PRECISION ETA6
      PARAMETER (ETA6=1.D-6)
C
C.... CALCULATE HEIGHT,A OF POINT R ABOVE TOOL CENTER
C
      DO 10 K=1,3
        V(K)=R(K)-TOOLCE(K)
10    CONTINUE
      CALL DOTF(A,V,TOOLAX)
C
C.... CALCULATE RADIAL DIRECTION,W AND DISTANCE,B FROM TOOL AXIS
C
      DO 20 K=1,3
        V1(K)=V(K)-A*TOOLAX(K)
20    CONTINUE
      CALL NORMA(V1,W,B)
C
C.... COMPUTE SURFACE SIDE OF TOOL
C
      IF (B.GT.TUL(2)) THEN
        S=-PSIDE
      ELSE
        CALL DOTF(S,RN,W)
        S=S*PSIDE
        S=SIGN(1.D0,S)
      ENDIF
C
C.... COMPUTATION OF ASSOCIATED POINT, TOOL NORMAL AND PENETRATION
C     WILL DEPEND ON RELATIVE LOCATION OF SURFACE POINT TO TOOL CENTER
C
      IF (A.GE.0.D0) THEN
C.... CYLINDER CASES
        IF (B.GE.TUL(3)) THEN
C.... 'OUTER' CYLINDER CASE
          ISEG=2
          PEN=TUL(2) + S*B + PTHICK
          DO 30 K=1,3
            TN(K)=S*W(K)
            T(K)=TOOLCE(K) - TUL(2)*TN(K) + A*TOOLAX(K)
30        CONTINUE
C
        ELSE
C.... 'INNER' CYLINDER CASE
          DO 40 K=1,3
            XR(K)=TOOLCE(K) - S*TUL(3)*W(K)
            V1(K)=R(K)-XR(K)
40        CONTINUE
          CALL NORMA(V1,TN,X)
          ISEG=1
          PEN=X + TUL(1) + PTHICK
          DO 50 K=1,3
            T(K)=XR(K) - TUL(1)*TN(K)
50        CONTINUE
        ENDIF
C
      ELSE
C.... CORNER RADIUS OR BASE
        IF (B.LE.TUL(3)) THEN
C     BOTTOM FLAT CASE
          ISEG=0
          PEN=TUL(4)+TUL(1) + A + PTHICK
          DO 60 K=1,3
            TN(K)=TOOLAX(K)
            T(K)=TOOLCE(K) + V1(K)-(TUL(4)+TUL(1))*TOOLAX(K)
60        CONTINUE
        ELSE
C     CORNER RADIUS
          ISEG=1
          DO 70 K=1,3
            XR(K)=TOOLCE(K)+TUL(3)*W(K)
70        CONTINUE
C
          DO 80 K=1,3
            V1(K)=XR(K)-R(K)
80        CONTINUE
          CALL NORMA(V1,TN,X)
C
          PEN=TUL(1) - X + PTHICK
C
          DO 90 K=1,3
            T(K)=XR(K)-TUL(1)*TN(K)
90        CONTINUE
C
        ENDIF
C
      ENDIF
C
      END
