**** SOURCE FILE : RESTOR.ORG   ***
*
      SUBROUTINE RESTOR
C
C     PURPOSE: TO RESTORE INTERFERENCE TABLE FOR USE AS START VALUES
C              FOR NEXT INTEFERENCE CHECK AFTER AVOIDING INTERFERENCE
C
      INCLUDE 'INTERF.INC'
C
C
      DO 200 I=1,LNPINT
C
        DINTR(I)=LDINTR(I)
        PINTR(I)=LPINTR(I)
        UINTR(I)=LUINTR(I)
        VINTR(I)=LVINTR(I)
C
  200 CONTINUE
C
      NPINTR=LNPINT
C
      END
