**** SOURCE FILE : TCSPHR.V01   ***
*
      SUBROUTINE TCSPHR(TE,TA,TUL,R,PSIDE,PTHICK,TCCENT,TCRAD)
C
C     PURPOSE: COMPUTE THE CENTRE AND RADIUS OF THE TOOL CONTACT SPHERE
C
C
C     ARGUMENTS:
C
C     TE      -  TOOL END COORDINATES
C     TA      -  TOOL AXIS VECTOR
C     TUL     -  TOOL GEOMETRY
C     R       -  SURFACE CONTACT POINT AND DERIVATIVES
C     PSIDE   -  1 OR -1 TO AJUST SURFACE NORMAL (RU X RV)
C     PTHICK  -  THICKNESS OFFSET FROM SURFACE
C     TCCENT  -  CENTRE OF TOOL CONTACT SPHERE
C     TCRAD   -  RADIUS OF TOOL CONTACT SPHERE
C
      DOUBLE PRECISION TE,TA,TUL,R,PSIDE,PTHICK,TCCENT,TCRAD
C
      DIMENSION TE(3),TA(3),TUL(7),R(32),TCCENT(3)
C
      DOUBLE PRECISION BIG5,ETA6,ONE
C
      PARAMETER (BIG5=1D5,ETA6=1D-6,ONE=1D0)
C
C.... LOCAL VARIABLES
C
C     COSA    -  COSINE OF ANGLE BETWEEN SURFACE NORMAL AND TOOL AXIS
C     SINA    -  SINE             (DITTO)
C     OFFSET  -  POSITION OF CENTRE ALONG TA FROM TE
C
      DOUBLE PRECISION COSA,SINA,OFFSET
C
      CALL DOTF(COSA,R(29),TA)
C
      IF (ABS(ONE-COSA).LE.ETA6) THEN
C
C.... SN PARALLEL TO TA
C
        DO 10 I=1,3
          TCCENT(I)=TE(I)+BIG5*TA(I)
   10   CONTINUE
        TCRAD=BIG5
C
      ELSE
        SINA=SQRT(1-COSA*COSA)
C
C.... RADIUS = E/SINA + R
C
        TCRAD=TUL(3)/SINA + TUL(1)
C
C.... POSITION OF CENTRE ALONG TA FROM TE
C
C            = F + (TCRAD-R)*COSA
C
        OFFSET=TUL(4)+TUL(1) + (TCRAD-TUL(1))*COSA
        DO 20 I=1,3
          TCCENT(I)=TE(I) + OFFSET*TA(I)
   20   CONTINUE
C
      ENDIF
C
      END
