**** SOURCE FILE : TXHULL.V01   ***
*
      SUBROUTINE TXHULL(RC,RCNORM,R1,R2,R3,TLEN,TOOLAX,TOOLTP,
     1      TOOLCE,CT,HRAD,HCENT)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DIMENSION RC(3),RCNORM(3)
      DIMENSION TOOLAX(3),TOOLCE(3),TOOLTP(3)
C.... HULL CENTRE
      DIMENSION HCENT(3)
      DIMENSION W1(3),W2(3)
C
      PARAMETER (AMEG5=1D5,ETA6=1D-6,HALF=0.5)
C
C     CALCULATE RADIUS OF MINIMUM ENCLOSING SPHERE
      RR1=R1*R1
      DO 10 I=1,3
        W1(I)=TOOLCE(I)-RC(I)
10    CONTINUE
      CALL DOTF(B,W1,TOOLAX)
      CALL VECMOD(W1,C)
      RA=SQRT(C*C-B*B)
      IF ((RA+ETA6).GE.R1 .OR. RA.LE.R3) THEN
        HRAD=AMEG5
      ELSE
C
C     CALC RADIUS OF SPHERE ON R AND ON POINT ON TOP OF TOOL OPPOSITE TO
        A=RA+R1
        B=TLEN-R2+B
C.... HRAD IS RADIUS
        HRAD=.5*SQRT(A*A+B*B)
        IF (HRAD.GT.AMEG5) THEN
          HRAD=AMEG5
        ELSE
C
C     CALC. MAXIMUM RADIUS OF CURVATURE OF TOOL AT R AS TR
          CALL DOTF(A,RCNORM,TOOLAX)
          IF ( A.LT.ETA6 .OR.( (ABS(A)-1.D0).LT.ETA6) ) THEN
            HRAD=AMEG5
          ELSE
            TR=R2+R3/SQRT(1-A*A)
            IF (TR.GT.AMEG5) THEN
              HRAD=AMEG5
            ELSE
              HRAD=MAX(HRAD,TR)
            ENDIF
          ENDIF
        ENDIF
      ENDIF
C.... CT IS CURVATURE OF ENCLOSING SPHERE ON R
      CT=1/HRAD
C
      DO 40 I=1,3
        HCENT(I)=RC(I)+HRAD*RCNORM(I)
40    CONTINUE
C
      END
