**** SOURCE FILE : VECMOD.ORG   ***
*
      SUBROUTINE VECMOD(X,XMOD)
C
C     GIVEN 3-D VECTOR X, CALCULATES MODULUS XMOD
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION X(3)
C
      XMOD=SQRT(X(1)*X(1)+X(2)*X(2)+X(3)*X(3))
C
      END
