**** SOURCE FILE : M0000500.V03   ***
*
C
C.....IMPLEMENTATION DEPENDENT SUBROUTINE ...BCDBIN   8/68          HG
C.... IMPLEMENTATION DEPENDENT   ....BCDBIN....   HLG  12/67      ..CD.
C PURPOSE      TO CONVERT AN INTEGER FROM BCD TO BINARY.
C
C LINKAGE      CALL BCDBIN (WORD, I, COUNT)
C
C ARGUMENTS    WORD     CONTAINS THE BCD REPRESENTATION OF
C                       THE NUMBER, LEFT JUSTIFIED.
C              I        WILL CONTAIN THE BINARY INTEGER
C              COUNT    WILL CONTAIN A COUNT OF THE NUMBER
C                       OF DIGITS IN THE NUMBER.
C
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          HELP
C
C
      SUBROUTINE BCDBIN(WORD,I,COUNT)
C
      INTEGER I,COUNT,NUM
      CHARACTER WORD*8,W*8,CHAR,ZERO,PERIOD,BLANK
C
      DATA PERIOD/'.'/,BLANK/' '/,ZERO/'0'/
C
      W=WORD
      I=0
      DO 300 J=1,8
      COUNT=J
      CHAR=W(J:J)
      IF( CHAR   .EQ.PERIOD.OR. CHAR   .EQ.BLANK) GOTO 100
      NUM=ICHAR(CHAR)-ICHAR(ZERO)
      IF(NUM.GT.9.OR.NUM.LT.0) GOTO 400
      I=I*10+NUM
  300 CONTINUE
  200 RETURN
  100 COUNT=COUNT-1
      GOTO 200
  400 COUNT = -1
      GOTO 200
      END
