**** SOURCE FILE : M0006641.V06   ***
*
C
C...  FORTRAN BLOCK DATA ROUTINE       IPL       8/81      FE353
C
      BLOCK DATA BDIPL
C
      IMPLICIT INTEGER (A-Z)
C
C...        34.    COMMON BLOCK FOR INTERPRETIVE C.I.L. OUTPUT
C
      INCLUDE 'OUTBUF.INC'
C
C...        20.    IO - ARRAY
C
      INCLUDE 'DARRAY.INC'
C
C...        34.    COMMON BLOCK FOR INTERPRETIVE C.I.L. OUTPUT
C
      DATA PPPAGE,MCPAGE,PAGPAK,ISC,ISCARR,ICFORM,MACWDS,IBUF,ILBUF,
     1PPWRDS,LPAGE,MACFLG,LABFLG,RSVFLG/0,0,65536,8*0,3*.FALSE./,
     2 IFLOAT,ICOM/2*0/
C
C...        20.    IO - ARRAY
C
c      DATA DARRAY/' '/
      END
