**** SOURCE FILE : M0006675.V03   ***
*
C
C              FORTRAN SUBROUTINE REFREF
C
C LINKAGE      SUBROUTINE REFREF
C
C          SUBSIDIARIES                  CALLED BY
C          TYPE          ENTRY           TYPE          ENTRY
C          SUBROUTINE    CALLZZ          SUBROUTINE    PRO026
C          SUBROUTINE    ARGCVT
C          SUBROUTINE    ALARM
C          SUBROUTINE    RLSLIN
C
      SUBROUTINE REFREF
C
      IMPLICIT INTEGER (A-Z)
C
C
C        1.    NAME TABLE AND TABLE LIMITS
C
      INCLUDE 'NAMETB.INC'
C NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY
C CNAMTB:      NAME TABLE OR DICTIONARY
C NAMMAX:      NAMTBL INDEX OF END OF THE PART PROGRAM NAME SECTION
C
C        2.    STACK AND POINTER STORAGE
C
      COMMON/STKLST/STKLST
      DIMENSION STKLST(300),ARGSTK(99)
C ARGTOP:      POINTER TO LAST ARGSTK ENTRY
      EQUIVALENCE (ARGTOP,STKLST(2))
C ARGSTK:      ARGUMENT STACK
      EQUIVALENCE (ARGSTK(1),STKLST(202))
C
C        5.    PROGRAM CONTROL FLAGS
C
      COMMON/FLAGS/FLAGS
      LOGICAL REFFLG
      DIMENSION FLAGS(4)
C REFFLG:      TRUE WHEN A REFSYS COMMAND ENCOUNTERED
      EQUIVALENCE (REFFLG,FLAGS(4))
C
C       17.    MODE CODES
C
      COMMON/MODX/MODX
      DIMENSION MODX(32)
C MATRIX:      MODE CODE (18) FOR MATRIX
      EQUIVALENCE (MATRIX,MODX(18))
C
C       28.    OPERAND MODIFIERS
C
      COMMON/SUBLST/SUBLST
      DIMENSION SUBLST(136)
C APT085:      NAMTBL POINTER FOR APT085
      EQUIVALENCE (APT085,SUBLST(126))
C REFSYS:      NAMTBL POINTER FOR XECUTION SUBROUTINE REFSYS
      EQUIVALENCE (REFSYS,SUBLST(134))
C**
      CHARACTER*6 CNMORE
      DATA CNMORE/'NOMORE'/
      external alarm
      EP=-1
      IF(ARGTOP-1)20,40,30
   20 EP=TOP
      GOTO 35
   30 EP=1-ARGTOP
   35 CALL ALARM(2052,EP,8,'REFREF  ')
   40 IF (REFFLG) GO TO 1000
C     REFSYS NOT IN EFFECT
C     ARE PARAMETERS CORRECT
      IF(MODE(ARGSTK(ARGTOP)).NE.MATRIX)
     *CALL ALARM(1010,-ARGTOP,8,'REFREF  ')
      REFFLG = .TRUE.
    5 CALL CALLZZ(REFSYS)
      CALL ARGCVT (ARGSTK(ARGTOP))
   10 CALL RLSLIN
   50 RETURN
C     REFSYS IN EFFECT
 1000 I=ARGSTK(ARGTOP)
      IF (MODE(ARGSTK(ARGTOP)).EQ.MATRIX) GO TO 5
      IF (CNAMTB(I).NE.CNMORE) CALL ALARM(1011,
     *-ARGTOP,8,'REFREF  ')
      REFFLG=.FALSE.
      CALL CALLZZ(APT085)
      GO TO 10
       END
