**** SOURCE FILE : M0006680.V01   ***
*
C
C              FORTRAN SUBROUTINE RETMCX
C
C LINKAGE      SUBROUTINE RETMCX(INDX)
C
C          SUBSIDIARIES                  CALLED BY
C          TYPE          ENTRY           TYPE          ENTRY
C          SUBROUTINE    ONEARG          SUBROUTINE    COMSTR
C          SUBROUTINE    OPCODE          SUBROUTINE    MATCH
C          SUBROUTINE    RLSLIN
C
      SUBROUTINE RETMCX(INDX)
C
      IMPLICIT INTEGER (A-Z)
C
C       16.    LITERALS FOR I. L. OPERATION CODES
C
      COMMON/IL/IL
      DIMENSION IL(21)
C RETMC:       CONTAINS COMMAND CODE (10) FOR RETMC COMMAND
      EQUIVALENCE (RETMC,IL(10))
C*
C ARGUMENTS    INDX     INDEX REGISTER NUMBER
C**
      CALL OPCODE(RETMC)
      CALL ONEARG(INDX)
      CALL RLSLIN
      RETURN
       END
