**** SOURCE FILE : CPUTIM00.IBM;1   ***
*
C.... INTEGER FUNCTION CPUTIM
C     UTILIZING IBM FORTRAN UTILITY DATETM ( TXTLIB UTILITY )
C
      INTEGER FUNCTION CPUTIM()
      CHARACTER*23 DATTIM
      REAL ECPU,ETIME,ETCPU
C
      CALL DATETM(DATTIM,ECPU,ETIME,ETCPU)
C
      CPUTIM=INT(ECPU*100.0)
      RETURN
      END
