**** SOURCE FILE : M0004132.IBM;2   ***
*
C
C
      SUBROUTINE GO(HMOD,ADRESS)
      IMPLICIT DOUBLE PRECISION(A-H),DOUBLE PRECISION(O-Z)
C
      INCLUDE (TOTAL)
      INCLUDE (LDEF)
      INCLUDE (IFXCOR)
C
      DIMENSION ADRESS(*)
      IF(JDS) CALL APT211(0,'NOCS    ',IDUM)
      CALL APT241
      IF(IAERR.EQ.1)GO TO 10
C-VAX-ESTABLISH CONDITION HANDLER
C      CALL APT241
   20 IF(ICTDEF.NE.0.AND.IGOTO.EQ.0)CALL AERR(20201,'GO      ')
C     IF (IAERR.EQ.1) GOTO 10
      CALL GO2(HMOD,ADRESS)
C     IF (IAERR.EQ.1) GOTO 20
   10 CONTINUE
      RETURN
      END
