**** SOURCE FILE : WTDIRE00.IBM;1   ***
*
*                MODIFIED                23-FEB-1988  E.MCLELLAN
*
      SUBROUTINE WTDIRE(IU,MEMBER,USERD,NCH,IRET)
C
      INTEGER IU,ID,NCH,IRET
      DOUBLE PRECISION MEMBER,USERD
C
      LOGICAL EX
C
      CHARACTER FLNAME*20,TYPE*4,MODE*2,CMEM*8
      INTEGER NWD,NLEN,JRET
C
C
      DATA TYPE/' LDA'/,MODE/' A'/
C
      ID=ABS(IU)
C
C.... SET UP FILENAME
C
      CALL HOLFRM(MEMBER,CMEM,1,8,NWD)
      NLEN=8
      K=INDEX(CMEM,' ')
      IF (K.NE.0) NLEN=K-1
      FLNAME=CMEM(:NLEN)//TYPE//MODE
      NLEN=NLEN+6
C
C.... INQUIRE IF FILE EXISTS
C
c      CALL UOPEN(ID,FLNAME(:NLEN),1,4,80,0,'U',0,JRET)
      write(*,*)'TODO: uopen command, WTDIRE.f'
      IF (JRET.EQ.0) THEN
C.... FILE ALREADY EXISTS - SHOULD A NEW VERSION BE WRITTEN
        IF (IU.LT.0) THEN
C.... YES - OPEN ATTACHED TO UNIT ID
c          CALL UOPEN(ID,FLNAME(:NLEN),1,2,80,0,'U',0,JRET)
      write(*,*)'TODO: uopen command, WTDIRE.f'
          IF (JRET.NE.0) GOTO 20
          IRET=0
        ELSE
          IRET=9
        ENDIF
      ELSE
C.... FILE DOES NOT EXIST - OPEN ATTACHED TO UNIT ID
c          CALL UOPEN(ID,FLNAME(:NLEN),1,2,80,0,'U',0,JRET)
      write(*,*)'TODO: uopen command, WTDIRE.f'
          IF (JRET.NE.0) GOTO 20
        IRET=0
      ENDIF
      RETURN
C.... ERROR OPENING FILE
  20  IRET=5
      RETURN
      END
