**** SOURCE FILE : M0000788.V02   ***
*
C.....FORTRAN SUBROUTINE             APT038...              3/1/68   GK
C
C              FORTRAN SUBROUTINE APT038
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A VECTOR DEFINED
C              AS THE CROSS PRODUCT OF TWO VECTORS BY THE FOLLOWING
C              APT STATEMENT
C              RESULT = VECTOR/VEC1, CROSS, VEC2
C
C LINKAGE      CALL APT038 (RESULT, VEC1, VEC2)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM OF
C                      THE RESULTING VECTOR
C              VEC1    ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE FIRST INPUT VECTOR
C              VEC2    ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE SECOND INPUT VECTOR
C
C SUBSIDIARIES TYPE                ENTRY
C              LOGICAL FUNCTION    CKDEF
C              SUBROUTINE          DEFEXT
C              REMAINDERING FUNCTION MOD
C
      SUBROUTINE APT038 (RESULT,VEC1,VEC2)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION RESULT(3),VEC1(3),VEC2(3)
      LOGICAL CKDEF
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'LDEF.INC'
      INCLUDE 'ISHR16.INC'
      INCLUDE 'KNUMBR.INC'
C
C
C
C
      DO 10 I=1,3
      SC(I)=VEC1(I)
   10 SC(I+3) =VEC2(I)
      UNFLAG =CKDEF(SC).OR.CKDEF(SC(4))
      DO 20 K=1,3
      I=MOD(K,K3)+K1
      J=MOD(I,K3)+K1
   20 R(K) =SC(I)*SC(J+3) -SC(J)*SC(I+3)
      CALL DEFEXT(RESULT)
      RETURN
       END
