**** SOURCE FILE : M0000771.V02   ***
*
C.....FORTRAN SUBROUTINE              APT021               3/26/68
C
C              FORTRAN SUBROUTINE APT021
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A LINE DEFINED
C              AS HAVING A GIVEN SLOPE (OR FORMING A GIVEN ANGLE WITH
C              THE POSITIVE XAXIS) AND A GIVEN X OR Y - INTERCEPT
C              BY THE FOLLOWING APT STATEMENTS
C              RESULT = LINE/MN,PSI,INTERC,IAX,YIN
C
C LINKAGE      CALL APT021 (RESULT,MN,PSI,IAX,YIN)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM OF THE
C                      RESULTING LINE
C              MN      INTEGER EQUIVALENT OF THE MODIFIER
C                      1 = ATANGL  2 = SLOPE
C              PSI     REAL VARIABLE CONTAINING THE VALUE OF THE
C                      ANGLE (IN DEGREES) OR SLOPE
C              IAX     INTEGER EQUIVALENT OF THE AXIS
C                      1 = XAXIS  2 = YAXIS
C              YIN     REAL VARIABLE CONTAINING THE VALUE OF THE
C                      X OR Y - INTERCEPT
C
C SUBSIDIARIES TYPE                ENTRY
C              SUBROUTINE          APT012
C              REAL FUNCTION       TAN
C
      SUBROUTINE APT021 (RESULT,MN,PSI,IAX,YIN)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION(O-Z)
      DIMENSION RESULT(4)
C
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'ZNUMBR.INC'
      INCLUDE 'ISHR16.INC'
C
C
C
C...     USE APT012 TO FIND LINE THRU TWO POINTS
C
C
      PS = PSI
      IF (MN.EQ.2) GO TO 10
      PS = PS*DEGRAD
      PS = DTAN(PS)
   10 IF (IAX.EQ.2) GO TO 20
      CALL APT012 (RESULT,YIN,Z0,YIN+Z1/PS,Z1)
      GO TO 30
   20 CALL APT012 (RESULT,Z0,YIN,Z1,PS+YIN)
   30 CONTINUE
      RETURN
       END
