**** SOURCE FILE : M0000785.V02   ***
*
C     FORTRAN SUBROUTINE               APT035    4/69      SR
C
C              FORTRAN SUBROUTINE APT035
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A VECTOR DEFINED
C              FROM ONE VECTOR (OR POINT) TO ANOTHER OR AS THE
C              DIFFERENCE OF TWO VECTORS BY THE FOLLOWING APT
C              STATEMENTS
C              RESULT = VECTOR/PN1, PN2
C              RESULT = VECTOR/PN2, MINUS, PN1
C
C LINKAGE      CALL APT035 (RESULT, PN1, PN2)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM OF
C                      THE RESULTING VECTOR
C              PN1     ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE FIRST INPUT POINT OR VECTOR
C              PN2     ARRAY CONTAINING THE CANONICAL FORM OF
C                      THE SECOND INPUT POINT OR VECTOR
C
C SUBSIDIARIES TYPE                ENTRY
C              LOGICAL FUNCTION    CKDEF
C              SUBROUTINE          DEFEXT
C
      SUBROUTINE APT035 (RESULT,PN1,PN2)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION RESULT(3),PN1(3),PN2(3)
      LOGICAL CKDEF
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'LDEF.INC'
      INCLUDE 'ISHR16.INC'
C
C
C
C...     CHECK VALIDITY OF PN1,PN2
C
      UNFLAG=CKDEF(PN1).OR.CKDEF(PN2)
      DO 10 I=1,3
   10 R(I)=PN2(I)-PN1(I)
      CALL DEFEXT(RESULT)
      RETURN
       END
