**** SOURCE FILE : M0000802.V02   ***
*
C.....FORTRAN SUBROUTINE             APT052...              3/1/68   GK
C
C              FORTRAN SUBROUTINE APT052
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A SPHERE
C              DEFINED AS HAVING ITS CENTER AT A GIVEN POINT
C              AND TANGENT TO A GIVEN PLANE BY THE FOLLOWING
C              APT STATEMENT
C              RESULT = SPHERE/CENTER, PN, TANTO, PL
C
C LINKAGE      CALL APT052 (RESULT, PN, PL)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM
C                      OF THE RESULTING SPHERE
C              PN      ARRAY CONTAINING THE CANONICAL FORM
C                      OF THE INPUT POINT
C              PL      ARRAY CONTAINING THE CANONICAL FORM
C                      OF THE INPUT PLANE
C
C SUBSIDIARIES TYPE                ENTRY
C              REAL FUNCTION       ABS
C              LOGICAL FUNCTION    CKDEF
C              SUBROUTINE          DEFEXT
C
      SUBROUTINE APT052 (RESULT,PN,PL)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION RESULT(4),PN(3),PL(4)
      LOGICAL CKDEF
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'LDEF.INC'
      INCLUDE 'ISHR16.INC'
C
C
C
C...     COMPUTE RADIUS OF RESULT, MOVE PN TO CENTER
C
      DO 10 I=1,3
      R(I)=PN(I)
   10 R(4)=R(4)+R(I)*PL(I)
      R(4)=DABS(R(4)-PL(4))
      UNFLAG=CKDEF(R).OR.CKDEF(PL)
      CALL DEFEXT(RESULT)
      RETURN
       END
