**** SOURCE FILE : M0000813.V02   ***
*
C.....FORTRAN SUBROUTINE             APT063...              3/1/68   GK
C
C              FORTRAN SUBROUTINE APT063
C
C PURPOSE      TO GENERATE THE CANONICAL FORM OF A TRANSLATION
C              MATRIX FROM THE FOLLOWING APT STATEMENT
C              RESULT = MATRIX/TRANSL, D1, D2, D3
C
C LINKAGE      CALL APT063 (RESULT, D1, D2, D3)
C
C ARGUMENTS    RESULT  ARRAY TO CONTAIN THE CANONICAL FORM OF
C                      THE RESULTING MATRIX
C              D1      REAL VARIABLE CONTAINING THE AMOUNT OF
C                      TRANSLATION IN THE X DIRECTION
C              D2      REAL VARIABLE CONTAINING THE AMOUNT OF
C                      TRANSLATION IN THE Y DIRECTION
C              D3      REAL VARIABLE CONTAINING THE AMOUNT OF
C                      TRANSLATION IN THE Z DIRECTION
C
C SUBSIDIARIES NONE
C
      SUBROUTINE APT063 (RESULT,D1,D2,D3)
      IMPLICIT DOUBLE PRECISION (A-H),DOUBLE PRECISION (O-Z)
      DIMENSION RESULT(12)
C
C
C
      INCLUDE 'TOTAL.INC'
      INCLUDE 'DEF.INC'
      INCLUDE 'DSHAR3.INC'
      INCLUDE 'ZNUMBR.INC'
      INCLUDE 'ISHR16.INC'
C
C
C
C...     ROTATION MATRIX IS IDENTITY MATRIX
C
      RESULT(1) = Z1
      DO 10 I =2,10
   10 RESULT(I) =R(I)
      RESULT(11) =Z1
C
C...     ADD TRANSLATION PART OF MATRIX
C
      RESULT(4) = D1
      RESULT(8) = D2
      RESULT(12) = D3
      RETURN
       END
