/* BDEXER.f -- translated by f2c (version 20100827).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/* Common Block Declarations */

struct exerrw_1_ {
    integer errad1[389], errad2[389];
};

#define exerrw_1 (*(struct exerrw_1_ *) &exerrw_)

struct exerrt_1_ {
    char errtxt[25152];
};

#define exerrt_1 (*(struct exerrt_1_ *) &exerrt_)

/* Initialized data */

struct {
    integer e_1[778];
    } exerrw_ = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 
	    18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 
	    34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 
	    50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 61, 62, 63, 64, 65, 66, 
	    67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 82, 83, 
	    84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 200, 
	    1001, 1002, 1003, 1004, 1005, 1006, 1007, 3501, 3502, 3503, 3504, 
	    3506, 3507, 3510, 3521, 3522, 3523, 3524, 3551, 3552, 3553, 3554, 
	    3555, 3561, 3562, 3563, 3564, 3565, 3566, 3567, 5000, 5001, 5002, 
	    5003, 5004, 5005, 5006, 5007, 5011, 5012, 5013, 5016, 5019, 5021, 
	    5022, 5023, 5024, 5025, 5026, 5027, 5028, 5029, 5030, 5031, 5032, 
	    5033, 5034, 5035, 5036, 5037, 5038, 5039, 5040, 5041, 5043, 5044, 
	    5045, 5060, 5061, 5062, 5121, 5122, 5123, 5124, 5125, 5126, 5127, 
	    5128, 5129, 5130, 5152, 5153, 5154, 5155, 5156, 5157, 5158, 5159, 
	    5160, 5210, 5211, 5212, 5213, 5214, 5215, 5216, 5217, 5218, 5219, 
	    5220, 5222, 5300, 5331, 5352, 5353, 5354, 5355, 5356, 5371, 5373, 
	    5374, 5375, 5376, 5377, 5378, 5379, 5391, 5392, 5393, 5396, 5402, 
	    5403, 5501, 5502, 5503, 5504, 5505, 5506, 5507, 5508, 5509, 5510, 
	    5511, 5512, 5513, 5514, 5515, 5516, 5517, 5518, 5519, 5520, 5521, 
	    5522, 5523, 5751, 5752, 5753, 5760, 5770, 5771, 5772, 5901, 5902, 
	    5903, 5904, 5905, 5906, 5907, 5908, 5909, 5910, 5921, 5922, 5923, 
	    5924, 5925, 5926, 20001, 20101, 20102, 20103, 20104, 20105, 20106,
	     20107, 20108, 20109, 20110, 20201, 20202, 20203, 20204, 20205, 
	    20206, 20901, 20902, 20903, 21001, 21002, 21003, 21101, 21102, 
	    21301, 22001, 22002, 22003, 22004, 22201, 22202, 22203, 22204, 
	    22205, 22206, 22207, 22208, 22209, 22210, 22211, 22212, 22213, 
	    22214, 22215, 22216, 22217, 22218, 22219, 22220, 22221, 22222, 
	    22223, 22300, 22301, 22401, 22701, 22801, 22802, 22803, 22804, 
	    22805, 22806, 22830, 22831, 22832, 22833, 22834, 23401, 23500, 
	    23901, 23902, 23903, 23904, 23905, 23908, 24001, 24002, 24003, 
	    24004, 24005, 24006, 24007, 24201, 24202, 24401, 24402, 24403, 
	    24404, 25001, 25002, 25003, 25004, 25005, 25007, 25008, 25009, 
	    25402, 25403, 26001, 26002, 26201, 26202, 26203, 26204, 26401, 
	    26601, 26602, 26801, 26802, 26803, 27001, 27002, 27003, 27004, 
	    27005, 27206, 28801, 29001, 29002, 29003, 29004, 29006, 29007, 18,
	     38, 58, 78, 93, 107, 121, 140, 159, 180, 194, 215, 237, 246, 261,
	     283, 296, 312, 331, 351, 372, 393, 415, 441, 470, 490, 515, 531, 
	    545, 561, 582, 591, 599, 614, 631, 655, 670, 689, 713, 740, 760, 
	    781, 800, 822, 834, 861, 880, 895, 915, 937, 949, 965, 983, 1006, 
	    1026, 1047, 1061, 1081, 1100, 1120, 1141, 1167, 1191, 1205, 1224, 
	    1243, 1261, 1271, 1285, 1293, 1303, 1314, 1323, 1330, 1342, 1350, 
	    1359, 1372, 1396, 1411, 1422, 1433, 1444, 1465, 1479, 1487, 1510, 
	    1534, 1545, 1551, 1560, 1589, 1605, 1615, 1633, 1655, 1667, 1675, 
	    1684, 1691, 1697, 1708, 1718, 1726, 1736, 1748, 1758, 1770, 1778, 
	    1805, 1815, 1838, 1852, 1868, 1879, 1898, 1934, 1955, 1974, 1987, 
	    2010, 2024, 2040, 2051, 2075, 2101, 2125, 2136, 2147, 2160, 2177, 
	    2185, 2204, 2217, 2236, 2245, 2254, 2265, 2282, 2296, 2312, 2327, 
	    2341, 2357, 2371, 2384, 2395, 2406, 2417, 2435, 2449, 2460, 2476, 
	    2493, 2507, 2518, 2541, 2563, 2579, 2601, 2617, 2636, 2655, 2668, 
	    2683, 2690, 2702, 2724, 2742, 2762, 2778, 2799, 2814, 2849, 2871, 
	    2899, 2925, 2937, 2948, 2958, 2971, 2982, 2993, 2998, 3009, 3018, 
	    3032, 3053, 3059, 3071, 3087, 3096, 3112, 3128, 3144, 3153, 3169, 
	    3197, 3206, 3217, 3227, 3242, 3258, 3272, 3282, 3291, 3298, 3308, 
	    3313, 3322, 3334, 3348, 3356, 3366, 3377, 3384, 3393, 3413, 3436, 
	    3467, 3493, 3528, 3573, 3616, 3664, 3745, 3784, 3840, 3876, 3891, 
	    3945, 3979, 4004, 4031, 4068, 4095, 4123, 4155, 4166, 4190, 4211, 
	    4237, 4254, 4274, 4287, 4308, 4327, 4345, 4359, 4371, 4385, 4399, 
	    4406, 4414, 4430, 4446, 4464, 4479, 4503, 4519, 4527, 4539, 4549, 
	    4566, 4584, 4597, 4604, 4618, 4632, 4647, 4657, 4677, 4691, 4698, 
	    4716, 4729, 4743, 4750, 4763, 4775, 4785, 4799, 4807, 4823, 4834, 
	    4842, 4858, 4869, 4877, 4888, 4904, 919, 4941, 4958, 4979, 4988, 
	    4996, 5003, 5015, 5023, 5037, 5045, 5055, 5074, 5095, 5111, 5134, 
	    5150, 5166, 5186, 5201, 5209, 5219, 5235, 5248, 5256, 5265, 5272, 
	    5298, 5316, 5340, 5361, 5373, 5383, 5391, 5401, 5410, 5418, 5432, 
	    5439, 5465, 5491, 5507, 5522, 5532, 5545, 5554, 5563, 5575, 5589, 
	    5596, 5607, 5616, 5633, 5655, 5671, 5683, 5693, 5701, 5717, 5730, 
	    5751, 5763, 5779, 5794, 5806, 5829, 5838, 5852, 5858, 5876, 5900, 
	    5916, 5934, 5942, 5961, 5976, 5996, 6008, 6015, 6039, 6056, 6068, 
	    6076, 6088, 6104, 6131, 6159, 6172, 6185, 6198, 6216, 6233, 6244, 
	    6254, 6259, 6269, 6281, 6288 };

struct {
    char e_1[25152];
    } exerrt_ = { "CANONICAL FORM NOT PREVIOUSLY CORRECTLY DEFINED IS BEING "
	    " REFERENCED.   THE FIRST LINE GIVEN FOR THE DEFINITION OF THE PO"
	    "INT IS NOT  A VERTICAL PLANE.  THE SECOND LINE GIVEN FOR THE DEF"
	    "INITION OF THE POINT IS NOT  A VERTICAL PLANE. POINT UNDEFINED. "
	    "INTERSECTION OF TWO LINES WHICH ARE TOO CLOSE  TO PARALLEL.    L"
	    "INE INVOLVED IS NOT VERTICAL PLANE. POINT IS UNDEFINED.    LINE "
	    "AND CIRCLE DO NOT INTERSECT. POINT IS UNDEFINED.   CIRCLE IS NOT"
	    " A VERTICAL CYLINDER. POINT IS UNDEFINED.  THE GIVEN LINE IS VER"
	    "TICAL. SUBSTITUTE Y FOR X IN  'XLARGE' OR 'XSMALL'.    THE GIVEN"
	    " LINE IS HORIZONTAL. SUBSTITUTE X FOR Y IN 'YLARGE' OR 'YSMALL'."
	    "   A VECTOR OPERAND IN A DOT PRODUCT COMPUTATION IS UNDEFINED.  "
	    "THE RESULT IS ZERO.    INPUT POINT IS NOT ON TABCYL, NEAR INTERS"
	    "ECTION POINT.  THE FIRST CIRCLE GIVEN FOR THE DEFINITION OF THE "
	    "POINT IS NOT  A VERTICAL CYLINDER. THE SECOND CIRCLE GIVEN FOR T"
	    "HE DEFINITION OF THE POINT IS NOT  A VERTICAL CYLINDER.    TRANS"
	    "FORMATION MATRIX UNDEFINED.    THE LINE AND CONIC DO NOT INTERSE"
	    "CT. POINT IS UNDEFINED.    THE GENERAL CONIC EQUATION SHOULD NOT"
	    " CONTAIN THE Z COORDINATE.  POINT IS UNDEFINED.    TOO MANY TABC"
	    "YLS INVOLVED IN THIS MOTION STATEMENT. ONE OF THE INPUT PLANES I"
	    "S UNDEFINED. THE POINT IS UNDEFINED.   THE TWO GIVEN POINTS ARE "
	    "TOO CLOSE TOGETHER. THE LINE CANNOT  BE DEFINED.   THE ARGUMENT "
	    "OF THE FUNCTION IS NEGATIVE; GOING ON WITH  THE POSITIVE ARGUMEN"
	    "T. THE FIRST CIRCLE GIVEN IN THE DEFINITION OF THE LINE IS NOT  "
	    "A VERTICAL CYLINDER.   THE SECOND CIRCLE GIVEN IN THE DEFINITION"
	    " OF THE LINE IS NOT  A VERTICAL CYLINDER.  THE CIRCLES USED IN T"
	    "HE DEFINITION OF THE LINE ARE CONCENTRIC.  THE LINE IS UNDEFINED"
	    ".  ONE OF THE CIRCLES USED IN THE DEFINITION OF THE LINE IS WHOL"
	    "LY INSIDE OF THE OTHER. LINE IS UNDEFINED. THE CIRCLES USED IN T"
	    "HE LINE DEFINITION INTERSECT, AND THE  MODIFIERS ARE NOT 'LEFT',"
	    " 'LEFT' OR 'RIGHT', 'RIGHT'.   THE LINE GIVEN IN THE DEFINITION "
	    "IS NOT A VERTICAL PLANE.  LINE IS UNDEFINED.   THE DESIRED LINE "
	    "IS UNDEFINED. THE GIVEN PLANES ARE EITHER  PARALLEL, COINCIDENT "
	    "OR BOTH VERTICAL.  THE INPUT LINE IS NOT A VERTICAL PLANE. CIRCL"
	    "E IS UNDEFINED.    CIRCLE UNDEFINED. THE THREE GIVEN POINTS ARE "
	    "COLLINEAR. THE THREE GIVEN POINTS ARE NOT IN THE SAME  HORIZONTA"
	    "L PLANE.   CIRCLE UNDEFINED. THE CIRCLE GIVEN IN THE DEFINITION "
	    "IS NOT  A VERTICAL CYLINDER.   VECTOR FOR CANTED TABCYL UNDEFINE"
	    "D. TABCYL INPUT POINT UNDEFINED.   CONSECUTIVE INPUT POINTS ARE "
	    "IDENTICAL. TABCYL UNDEFINED.   FOR XYZ-CASE, INCORRECT PARAMETER"
	    "S SPECIFIED.  TABCYL UNDEFINED.    THE INPUT-GEOMETRIE OF THE NU"
	    "MBER-FUNCTION IS UNDEFINED  OR OF A WRONG KIND; THE RESULT IS 0."
	    "   THE LOG ARGUMENT IS ZERO; THE RESULT IS A NEGATIVE NUMBER.  T"
	    "HE ARSIN-ARCOS ARGUMENT IS ABSOLUT GREATER THAN 1;  THE RESULT I"
	    "S ZERO.    THE INPUT-GEOMETRIE AT THE VALUE-FETCHING IS UNDEFINE"
	    "D  OR OF A WRONG KIND; THE RESULT IS 0.    THE FETCH-INDEX AT TH"
	    "E VALUE-FETCHING IS UNDEFINED  OR THE CANONICAL FORM IS TOO SHOR"
	    "T; THE RESULT IS 0.    THE FETCH-INDEX AT THE VALUE-FETCHING IS "
	    "LESS OR EQUAL  ZERO; THE RESULT IS 0.  THE PARAMETER-DELIVERY PR"
	    "ECEDES NO EQUIVALENT  INTERSECTION-STMT; THE RESULT IS 0.  THE P"
	    "ARAMETER-DELIVERY-FUNCTION IS NOT CORRECT SUPPLIED;  THE RESULT "
	    "IS 0.  THE SUM OF THE SQUARES OF THE COEFFICIENTS OF X, Y  AN Z "
	    "IS ZERO. PLANE NOT DEFINED.    'ZIGZAG' IS IGNORED SINCE PATERN "
	    "IS NOT GRID.   'OMIT' HAS BEEN APPLIED (OR 'RETAIN' HAS NOT BEEN"
	    " APPLIED)  TO THE FIRST OR LAST POINT IN AN AVOID STRING.  CONE "
	    "UNDEFINED. THE AXIS VECTOR GIVEN IN THE DEFINITION HAS  ZERO VAL"
	    "UE.    CONE UNDEFINED. THE GIVEN ANGLE IS GREATER THAN 90 DEGREE"
	    "S. PLANE USED IN 'ZSURF' STATEMENT IS UNDEFINED.  'ZSURF' STATEM"
	    "ENT IS IGNORED.    PLANE USED IN 'ZSURF' STATEMENT IS PARALLEL T"
	    "O  Z AXIS. 'ZSURF' STATEMENT IS IGNORED.   INPUT VECTORS ARE PAR"
	    "ALLEL. PLANE UNDEFINED.    THE THREE SIMULTANEOUS EQUATIONS DO N"
	    "OT HAVE A UNIQUE SOLUTION. 'REFSYS' GIVEN WITH UNDEFINED MATRIX."
	    " TRANSFORMS WILL BE  UNDEFINED.    AT LEAST ONE INPUT-ELEMENT OF"
	    " THE SPAT-FUNCTION IS WRONG OR  UNDEFINED; THE RESULT IS 0.    A"
	    "T LEAST ONE INPUT-ELEMENT OF THE DIST-FUNCTION IS UNDEFINED;  TH"
	    "E RESULT IS 0. THE VECTOR WHOSE LENGTH IS TO BE COMPUTED IS UNDE"
	    "FINED. A LENGTH OF ZERO IS USED.   SPHERE UNDEFINED. THE FOUR GI"
	    "VEN POINTS ARE COMPLANAR.  CYLINDER UNDEFINED. THE AXIS VECTOR G"
	    "IVEN IN THE DEFINITION HAS  ZERO VALUE.    GIVEN PLANE IS PERPEN"
	    "DICULAR TO AN AXIS. MODIFIER MUST CONTAIN  THIS AXIS.  THE INPUT"
	    "-ELEMENT OF THE DIST-FUNCTION IS OF A WRONG KIND;  THE RESULT IS"
	    " 0.    THE TWO PLANES OR LINES OF THE DIST-FUNCTION ARE NOT PARA"
	    "LLEL;  THE RESULT IS 0.    THE REQUESTED NUMBER OF ROWS OR COLUM"
	    "NS IN A GRID OR PERIPHERAL  PATERN IS ZERO OR A NEGATIVE NUMBER."
	    "   INCREMENT OR NUMBER OF INCREMENTS IN A PATERN DEFINITION  INC"
	    "REMENT LIST IS NEGATIVE OR ZERO.   VECTOR SUPPLIED IN A PATERN D"
	    "EFINITION HAS LENGTH ZERO. THE REQUESTED NUMBER OF POINTS IN A P"
	    "ATERN IS ZERO OR A  NEGATIVE NUMBER.   THE PATERN USED IN A GRID"
	    " OR PERIPHERAL PATERN DEFINITION MUST  BE LINEAR.  A RANDOM PATE"
	    "RN MAY NOT BE USED IN THE DEFINITION OF A RANDOM  PATERN.  INPUT"
	    " POINT FOR LCONIC IS UNDEFINED.    TWO INPUT POINTS COINCIDE. TH"
	    "E CONIC CANNOT BE DEFINED. THIS IS A DEGENERATIC CONIC.    TABCY"
	    "L INTERSECTION POINT IS NOT FOUND. MORE THAN 1 POINT IN TANGENCY"
	    " ON TABCYL.    TABCYL TANGENT LINE IS NOT FOUND.   TABCYL TANGEN"
	    "T LINE FAILED. ARGUMENT FOR TABCYL TANGENT LINE IS UNDEFINED.  T"
	    "ABCYL MODIFIER INDETERMINATE.  TABCYL TANGENT CIRCLE IS NOT FOUN"
	    "D. ARGUMENT FOR TABCYL TANGENT CIRCLE IS UNDEFINED.    AT LEAST "
	    "ONE INPUT OF THE ANGL-FUNCTION IS UNDEFINED OR OF A  WRONG KIND;"
	    " THE RESULT IS ZERO.   A RANDOM PATERN OCCURS AS A SUB ELEMENT O"
	    "F A RANDOM PATERN. RESTART DUE TO DEFINITION OR SYNTAX ERROR.  H"
	    "ALF SPACE MODIFIER NOT PROPERLY SPECIFIED. REFERENCED ELEMENT NO"
	    "T PROPERLY DEFINED.    BOUNDED GEOMETRY ELEMENT HAS BEEN REDEFIN"
	    "ED WITH A DIFFERENT  NUMBER OF ELEMENTS.   THE DIFFERENCE BETWEE"
	    "N >P1< AND >P2< IS LESS THAN .01 . >V1< IS PARALLEL TO THE CHORD"
	    ".  INVALID OR ERRONEOUS CANONICAL FORM ENCOUNTERED. BOUNDED  GEO"
	    "METRY PROCESSING TERMINATED.   TOO MUCH EMBEDDEDNESS IN BOUNDS A"
	    "ND OBJECT STATEMENTS. BOUNDED  GEOMETRY PROCESSING TERMINATED. I"
	    "NCORRECT ARGUMENT IN 'UNITS' STATEMENT.    PLANE IS NOT VERTICAL"
	    ".  SPECIFIED CL POINT DOES NOT EXIST.  CLDAT INDEXES ARE DIFFERE"
	    "NT (FIRST INDEX REMAINS VALID) OR MULTIPLE DEFINED CLDAT-SECTION"
	    " (FORMER SECTION DELETED). ICLTAB FILLED. USE A FORMER USED INDE"
	    "X OR REDIMENSION ARRAY.    CLDAT SECTION NOT FOUND OR NOT CLOSED"
	    ".  TRANSFORMATION MATRIX HAS UNEQUAL SCALE FUNCTION IN X-, Y- OR"
	    " Z-AXIS.   MOTION COMMAND DOES NOT CONTAIN PART OR DRIVE SURFACE"
	    " TO PRODUCECL - DEFINITION WANTED. WRONG ARGUMENT IN PARTPROGRAM"
	    " CALLING FUNCTION. WANTED MODULE CANNOT BE FOUND.  EXTERNAL REFE"
	    "RENCE IS NOT SOLVED.   NOT ENOUGH CORE AVAILABLE.  MODULE NOT IN"
	    " LIBRARY.  CESD TABLE FOR LOADER MODULES TOO SHORT.    CESD TABL"
	    "E FOR LOAD-MODULE TOO SHORT.   TO MANY MODULES TO BE LOADED.   P"
	    "OCKET INPUT CONTAINS DUPLICATE POINTS. POCKET INPUT CONTAINS THR"
	    "EE COLLINEAR POINTS.   POCKET INPUT POINTS ARE NOT COMPLANAR.  P"
	    "OCKET INPUT POINTS DESCRIBE CONCAVE FIGURE.    AN INPUT POINT IS"
	    " UNDEFINED.    THE ANGLE BETWEEN THE TOOL AXIS AND THE PLANE OF "
	    "THE POCKET  BOTTOM IS TOO SMALL (LESS THAN 12 DEGREES).    LESS "
	    "THAN 3 POINTS HAVE BEEN GENERATED. A MINOR WORD OR CANONICAL FOR"
	    "M IN THE INPUT STREAM IS IN THE  WRONG POSITION OR INVALID.    A"
	    "N INPUT CANONICAL FORM HAS NOT BEEN DEFINED PROPERLY.  AN INPUT "
	    "CANONICAL FORM IS NOT SUITABLE FOR THIS APPLICATION.   TOO MANY "
	    "OR FEW PARAMETERS HAVE BEEN INPUT. THE CUTTER COULD NOT CONTACT "
	    "THE PART SURFACE FROM THE PRESENT  POSITION.   AT THE LAST POINT"
	    " DURING PATH GENERATION, THE SYSTEM COULD NOT  MAKE A CUTTER STE"
	    "POUT THAT SATISFIED ALL CURVATURE AND  TOLERANCE CONDITIONS.   M"
	    "ORE CL POINTS WERE GENERATED IN A SINGLE PATH THAN PERMITTED  BY"
	    " 'NUMPTS' SETTING. THE TOTAL LENGTH OF THE CURRENT CUTTER PATH E"
	    "XCEEDED THE  'MAXDP' SETTINUNABLE TO AVOID INTERFERENCE WITH CUR"
	    "RENT PARAMETERSG.  A MINOR WORD OR CANONICAL FORM IN THE INPUT S"
	    "TREAM IS IN THE  WRONG POSITION OR INVALID.    AN INPUT CANONICA"
	    "L FORM HAS NOT BEEN DEFINED PROPERLY.  AN INPUT CANONICAL FORM I"
	    "S NOT SUITABLE FOR THIS APPLICATION.   TOO MANY OR FEW PARAMETER"
	    "S HAVE BEEN INPUT. AN 'SCON' DATA AREA (DS,PS,FEED,ETC.) HAS NOT"
	    " BEEN DEFINED OR  HAS BEEN INCORRECTLY DEFINED.    GENERAL APT A"
	    "RELEM CONDITIONS FOR REGIONAL MILLING ARE INVALID  (PROBABLY UNA"
	    "CCEPTABLE CUTTER TYPE).    PART OR DRIVE GEOMETRY COULD NOT BE F"
	    "ETCHED BECAUSE OF  DEFINITION ERROR OR SPACE LIMITATION.   LARGE"
	    " DATA COULD NOT BE STORED INTERNALY.   WRONG SECOND PARAMETER IN"
	    " SMESH DEFINITION. THE REQUESTED SYNTHETIC CURVE WAS NOT AVAILAB"
	    "LE.    THE WORD 'AXIS' WAS NOT IN PROPER POSITION IN THE  INPUT "
	    "STREAM.    A VALID AXIS WAS NOT DEFINED.   THE WORDS 'CCLW' OR '"
	    "CLW' WERE NOT IN PROPER POSITION IN THE  INPUT STREAM. TWO ANGLE"
	    "S ARE REQUIRED FOR SURFACE OF REVOLUTION.  TWO POINTS OR ONE VEC"
	    "TOR ARE REQUIRED TO SPECIFY  AN AXIS OF A CYLINDER.    THE FIRST"
	    " SURFACE IS NOT DEFINED.   THE FIRST SURFACE IS NOT DEFINED.   T"
	    "HE COMBINATION OF SURFACES IS TOO LARGE.   THERE IS NOT ENOUGH S"
	    "PACE IN >SSPAD< TO HOLD  PATCH CORNER POINTS.  ONE OR MORE PATCH"
	    "ES ARE DISCONNECTED FROM ALL OTHERS.   SEGMENT REFERENCED FOR DI"
	    "SSECTION ON FLOW CURVE IS OUT OF RANGE.THERE IS NOT ENOUGH ROOM "
	    "IN BUFFER FOR DISSECTED SEGMENT.   THERE IS NOT ENOUGH ROOM IN B"
	    "UFFER TO DISSECT ONE ARC.  AN ARC REFERENCED FOR DISSECTION IS O"
	    "UT OF RANGE FOR THIS CURVE.THE WORD 'CROSS' WAS ENCOUNTERED TWIC"
	    "E IN A DEFINITION. LESS THAN TWO SPLINES WERE INPUT BEFORE 'CROS"
	    "S'.    AN INPUT CURVE WAS NOT PROPERLY DEFINED.    THE FIRST INP"
	    "UT CURVE COULD NOT BE FETCHED. THE FIRST INPUT CURVE WAS NOT A F"
	    "LOW CURVE. TOO MANY CURVES HAVE BEEN INPUT FOR THE CURVE. DIRECT"
	    "ORY  TABLE SIZE.   THERE IS NOT ENOUGH BUFFER SPACE TO LOAD THIS"
	    " CURVE.    AN INPUT SPLINE CURVE COULD NOT BE FETCHED. THE NUMBE"
	    "R OF FLOW SEGMENTS DIFFERED BETWEEN TWO SPLINE CURVES. THERE IS "
	    "NOT ENOUGH ROOM IN THE DIRECTORY TABLE FOR CROSS  CURVES.  THERE"
	    " IS NOT ENOUGH BUFFER SPACE TO HOLD A CROSS CURVE. AN INPUT CROS"
	    "S CURVE COULD NOT BE FETCHED.  THE NUMBER OF FLOW SEGMENTS IN A "
	    "CROSS CURVE DID NOT MATCH THE  NUMBER OF SPLINES LESS ONE. THERE"
	    " IS NO MATCH AT A SEGMENT JUNCTION POINT BETWEEN A SPLINE  AND C"
	    "ROSS SPLINE CURVE. TWO CROSS CURVES PASS THROUGH THE SAME SPLINE"
	    " JUNCTION POINTS.  THERE IS NOT ENOUGH BUFFER SPACE TO FIT A CRO"
	    "SS CURVE THROUGH  SPLINE JUNCTION POINTS.  AN ERROR WAS ENCOUNTE"
	    "RED IN TRYING TO CROSS FIT A CROSS CURVE.  THERE IS NOT ENOUGH B"
	    "UFFER SPACE FOR A FLOW STRUCTURE ON A  CROSS CURVE.    THERE IS "
	    "NOT ENOUGH BUFFER SPACE TO DETERMINE CROSS VECTORS BY  SPLINING."
	    "   CROSS FITTING FAILED AT A SEGMENT INTERIOR POINT.   ERROR DUR"
	    "ING READ OF A LARGE DATA ARRAY >LDA< FROM FILE 9.  NOT ENOUGH RO"
	    "OM IN >LDA<.   NOT ENOUGH ROOM ON FILE 9. (EXTERNAL >LDA<).    T"
	    "HE FIRST WORD IN THE SCURV DEFINITION DID NOT CORRESPOND TO  ONE"
	    " OF THESE PROGRAMMED.  AN ARGUMENT IN A PRIMARY CURVE DEFINITION"
	    " WAS NOT A  RECOGNIZED ONE.    THE MAXIMUM NUMBER OF POINTS IN A"
	    " PRIMARY CURVE DEFINITION  HAS BEEN EXCEEDED.  A VECTOR CONSTRAI"
	    "NT HAS BEEN INPUT PRIOR TO THE FIRST POINT.    A VECTOR ARGUMENT"
	    " DID NOT FOLLOW A MINOR WORD WHICH REQUIRED  A VECTOR CONSTRAINT"
	    ".  A 'REAL' ARGUMENT DID NOT FOLLOW A 'WEIGHT' SPECIFICATION.  A"
	    " 'REAL' ARGUMENT DID NOT FOLLOW A 'LIMIT' SPECIFICATION OR AN  I"
	    "NPUT CURVE TO THE 'COMBIN' STATEMENT HAS NOT BEEN  SUCCESSFULLY "
	    "DEFINED.   THE JUNCTION POINTS OF TWO CONSECUTIVE CURVES IN 'COM"
	    "BIN'  DEFINITION DID NOT MATCH.    THE TANGENT VECTORS AT THE JU"
	    "NCTION OF CONSECUTIVE CURVES IN A  'COMBIN' DEFINITION HAD DIFFE"
	    "RENT DIRECTIONS.   CURVES WITH FLOW STRUCTURE CANNOT BE COMBINED"
	    " YET. ERRORS  IMPOSING FLOW RATES ACROSS SYNTHETIC CURVES. SEGME"
	    "NT NUMBER OF THE 'SCURV' IS NOT CORRECT.   PATCH NUMBER OF THE '"
	    "SSURF' IS NOT CORRECT. PARAMETER SPECIFICATION IS NOT CORRECT. T"
	    "HE LENGHT OF A VECTOR IS TOO SMALL TO NORMALIZE.   THE INTERSECT"
	    "ION POINT CANNOT BE DEFINED.   INPUT CANON FORM NOT PREVIOUSLY D"
	    "EFINED.    DEFINITION ERROR.   SPECIFIED VECTOR OR POINT DOSE NO"
	    "T EXISTSURFACE NORMAL NOT PROPERLY DEFINED .   MAXIMUM BUFFER SP"
	    "ACE FOR A 'MESH' DEFINITION EXCEEDED.  TOO MANY POINTS IN ONE SP"
	    "LINE OR CROSS SPLINE FOR CURRENT CURVE  FITTING ALGORITHM. A POI"
	    "NT WAS MISSING.    TOO MANY POINTS FOR SPACE AVAILABLE IN SSPAD."
	    "   THE NEXT ENTRY SHOULD BE 'NORMAL', BUT IT WAS NOT RECOGNIZABL"
	    "E. THE NEXT ENTRY SHOULD BE A VECTOR.  THE NEXT ENTRY SHOULD BE "
	    "'TANSPL', BUT IT WAS NOT RECOGNIZABLE. THE NEXT ENTRY SHOULD BE "
	    "'CRSSPL', BUT IT WAS NOT RECOGNIZABLE. THE NEXT ENTRY SHOULD BE "
	    "'WEIGHT', BUT IT WAS NOT RECOGNIZABLE. THE NEXT ENTRY SHOULD BE "
	    "A SCALAR.  THE NEXT ENTRY SHOULD BE 'LIMIT', BUT IT WAS NOT RECO"
	    "GNIZABLE.  UNRECOGNIZED DATA WAS ENCOUNTERED IN THE MESH INPUT S"
	    "TREAM  OR ELSE THE NUMBER OF INPUT POINTS WAS INCORRECT.   SMESH"
	    " INPUT POINTS ARE NOT LINEAR.  TYPE DEFINITION IS MISSING IN 'ME"
	    "SH' INPUT. NUMBER OF SPLINES MUST BE AT LEAST TWO. THE SURFACE S"
	    "IZE EXCEEDED A PROGRAMMED MAXIMUM IN 'REVOLV'  THE AXIS VECTOR O"
	    "F THE CYLINDER WAS NOT SPECIFIED CORRECTLY.    ALL POINTS OF THE"
	    " CURVE LIE ON THE AXIS OF REVOLUTION.  CROSS SECTION CURVE DEFIN"
	    "ITION FAILS.   NOT ENOUGH SPACE TO FETCH CURVE.    CURVE COULD N"
	    "OT BE FETCHED. NOT ENOUGH SPACE TO FETCH CROSS CURVE.  CURVE NOT"
	    " DEFINED.  CROSS CURVE COULD NOT BE FETCHED.   CHECK FOR ENOUGH "
	    "ROOM FOR SURFACE IN 'SURF'.    SYSTEM ERROR. ARRAY >IB< DIMENSIO"
	    "N MUST BE INCREASED.   INVALID INDEX, SYSTEM ERROR.    SPLINE CU"
	    "RVE COULD NOT BE GENERATED.    CROSS SPLINE CURVE COULD NOT BE G"
	    "ENERATED.  PROBLEMS WITH INNER POINTS. TWIST VECTORS CANNOT BE C"
	    "OMPUTED.   COULD NOT FIND THE MINIMUM DISTANCE BETWEEN CUTTER AN"
	    "D A SCULPTURED SURFACE.    SS ROUTINE CALLED EXCESSIVE NUMBER OF"
	    " TIMES WITHOUT A SUCCESSFUL TOOL POSITION BEING FOUND. COULD NOT"
	    " FIT PERCENT OF ARC FLOW ACROSS A CURVE AT SOME POINTS. CHECK CU"
	    "RVE FOR UNUSUAL SHAPE OR FLOW RATE AT SOME POINT.  LENGTH OF NOR"
	    "MAL VECTOR WHICH CONTROLS DIRECTION OF CHORDAL  PROJECTION IS TO"
	    "O SMALL. VECTOR IS ZERO.   ANGLE BETWEEN CHORD AND THE DIRECTION"
	    " OF CHORDAL PROJECTION IS  TOO CLOSE TO ZERO. CHORDAL DIRECTION "
	    ">D< AND VECTOR >V< ARE  PERPENDICULAR. ANGLE BETWEEN SOME TANGEN"
	    "T VECTORS ON THE CURVE AND THE  PROJECTION CHORD IS TOO CLOSE TO"
	    " 90 DEGREES. A PARTICULAR  TANGENT VECTOR ON THE CURVE AND VECTO"
	    "R >V< ARE PERPENDICULAR.   AT SOME POINT THE CURVE HAS REVERSED "
	    "ITS DIRECTION ON THE CHORD  OF PROJECTION. A PARTICULAR TANGENT "
	    "VECTOR ON THE CURVE AND  VECTOR >V< ARE MOVING IN OPPOSITE DIREC"
	    "TIONS. COULD NOT FIT PROJECTION FLOW ON THE CHORD USING AVAILABL"
	    "E  SPACE. CHECK CHORD TO CURVE RELATIONSHIP OR ELSE INCREASE  BU"
	    "FFER SPACE. THE AVAILABLE SPACE FOR FLOW SPLINE >FL< HAS  BEEN F"
	    "ILLED. THE CHORDAL PROJECTION FLOW RATE COULD NOT BE FIT AT SOME"
	    " POINT OF THE CURVE. CHECK CURVE TO CHORD RELATIONSHIP. NOTE: CU"
	    "RVE SHOULD NEVER BE PERPENDICULAR TO CHORD. AN ARC HAS BEEN  SUB"
	    "DIVIDED 10 TIMES AT THE CURRENT POSITION WITHOUT BEING ABLE  TO "
	    "SUCCESSFULLY FIT THE FLOW OF 'COONS' PARAMETER IN THE  CHORDAL P"
	    "ARAMETER.  COULD NOT FIT ANGULAR FLOW WITHIN AVAILABLE SPACE. CH"
	    "ECK CURVE  TO FOCAL POINT RELATIONSHIP OR INCREASE BUFFER SPACE."
	    " THE  AVAILABLE SPACE IN >FL< USED UP. FAILED TO SUCCESSFULLY FI"
	    "T RATE OF CHANGE OF ANGLE AROUND SOME  CURVE POINT WITH RESPECT "
	    "TO FOCAL POINT. CHECK CURVE TO FOCAL  POINT RELATIONSHIP. ANGLE "
	    "FLOW COULD NOT FIT IN VICINITY OF A  CURVE POINT AFTER 10 ITERAT"
	    "IONS.  FOCAL POINT OF ANGULAR SPAN AND A CURVE POINT ARE TOO CLO"
	    "SE  TOGETHER FOR DEFINITE MEASUREMENT OF ANGLE. RATE OF CHANGE  "
	    "BECOMES ILL DEFINED.   THE CURVE IS TOO CLOSE TO THE POINT TO ME"
	    "ASURE THE ANGLE.   THE CURVE IS MOVING IN A NEAR RADIAL DIRECTIO"
	    "N TO THE FOCAL  POINT. PROPER MEASUREMENT OF ANGULAR RATE OF CHA"
	    "NGE NOT  POSSIBLE. THE CURVE TANGENT NEARLY PASSES THROUGH THE P"
	    "OINT  MAKING THE DERIVATIVES TOO LARGE.    THE LAST JUNCTION POI"
	    "NT REFERENCED ON A PREVIOUS 'FLOW' DETAIL  COMMAND DID NOT EQUAL"
	    " THE FIRST JUNCTION POINT IN THE DETAIL  COMMAND.  AN ARC JUNCTI"
	    "ON POINT REFERENCED IN A 'FLOW' DETAIL COMMAND WAS  NOT WITHIN R"
	    "ANGE FOR THE CURVE.    THE FINAL JUNCTION POINT REFERENCED IN TH"
	    "E FINAL FLOW DETAIL  COMMAND WAS NOT THE LAST POINT OF THE CURVE"
	    ".  THE LAST JUNCTION POINT REFERENCED IN A PREVIOUS 'SEGMENT'  D"
	    "ETAIL COMMAND DID NOT EQUAL THE FIRST JUNCTION POINT IN THE  PRE"
	    "SENT DETAIL COMMAND.   AN ARC JUNCTION POINT REFERENCED IN A 'SE"
	    "GMENT' DETAIL COMMAND  COMMAND WAS NOT WITHIN RANGE FOR THE CURV"
	    "E. THE FINAL JUNCTION POINT REFERENCED IN THE FINAL 'SEGMENT'  D"
	    "ETAIL COMMAND WAS NOT THE LAST POINT OF THE CURVE. PROJECTION OF"
	    " A CURVE POINT INTO PLANE FOR ANGULAR MEASUREMENT  IS TOO CLOSE "
	    "TO FOCAL POINT FOR DEFINITE MEASUREMENT OF ANGLE.  A 'FLOW' DETA"
	    "IL COMMAND WORD IS INVALID.    THE TWO POINTS AVAILABLE FOR DEFI"
	    "NING A PROJECTION CHORD ARE  TOO CLOSE TO DETERMINE A CHORD.   T"
	    "HERE WAS NOT ENOUGH BUFFER SPACE FOR A 'FLOW' DETAIL  PARAMETERI"
	    "ZATION COMMAND.    LENGTH OF NORMAL VECTOR WHICH CONTROLS DIRECT"
	    "ION OF CHORDAL  PROJECTION IS TOO SMALL. VECTOR IS ZERO.   IN A "
	    "'CURSEG' DEFINITION ALL OF THE POINTS DO NOT LIE IN A  PLANE.  I"
	    "N A 'CURSEG' DEFINITION ALL OF THE TANGENT CONSTRAINTS DO NOT  L"
	    "IE IN A PLANE. MORE THAN 5 CONDITIONS IN A 'CURSEG' DEFINITION. "
	    "   IN A 'CURSEG' DEFINITION END SLOPES ARE PARALLEL (THAT IS,  T"
	    "HEY DO NOT INTERSECT). IN A 'CURSEG' DEFINITION, THE POINTS INDI"
	    "CATE AN IMPOSSIBLE  INFLECTION.    IN A 'CURSEG' DEFINITION, NOR"
	    "MALS AT THE CURVE ENDS DO NOT  INTERSECT.  NO SUITABLE CONIC CUR"
	    "VE FITS THE SPECIFIED CONDITIONS.  THERE ARE FEWER THAN TWO POIN"
	    "TS IN THE SPLINE.  TWO CONSECUTIVE POINTS ARE IDENTICAL ('SPLINE"
	    "' CASE).   TWO OF THE INPUT POINTS ARE IDENTICAL ('CURSEG' CASE)"
	    ".  SMOOTHING ALGORITHM FAILED. A VECTOR CONSTRAINT WAS ZERO.   P"
	    "ROJECTION OF >TANSPL< ON THE PLANE PERPTO NORMAL IS TOO SMALL. P"
	    "ROJECTION OF >CRSSPL< ON THE PLANE PERPTO NORMAL IS TOO SMALL. T"
	    "WO OR MORE CONSTRAINT VECTORS AT ONE POINT LIE IN THE SAME  DIRE"
	    "CTION. PARABOLIC INTERPOLATION FAILED AT ONE END OF A 'SPLINE'. "
	    "   THE MID POINT OF THREE CONSECUTIVE POINTS PROJECTED OUTSIDE  "
	    "THE RANGE OF THE SURROUNDING TWO.  A DISTANCE BETWEEN TWO CONSEC"
	    "UTIVE INPUT POINTS IS  TOO SMALL.  INPUT >IDC< IS NOT SIGNIFICAN"
	    "T. ERROR IN SOLVING SIMULTANEOUS LINEAR EQUATIONS. NUMBER OF INP"
	    "UT POINTS IS LESS THAN 3.  A DISTANCE BETWEEN TWO CONSECUTIVE OU"
	    "TPUT POINTS IS  IS TOO SMALL.  AN OUTPUT FIRST ORDER DERIVATIVE "
	    "HAS A MAGNITUDE WHICH  IS TOO SMALL.   MORE THAN 2 CHECK SURFACE"
	    "S FOR THIS CUT SEQUENCE.   PART SURFACE IS A POINT.    CUTTER WA"
	    "S NOT WITHIN TOLERANCE OF DS AT START OF CUT.  CUTTER WAS NOT WI"
	    "THIN TOLERANCE OF PS AT START OF CUT.  UNABLE TO DETERMINE GENER"
	    "AL DIRECTION OF FIRST CUT VECTOR.  FWD DIRECTION COULD NOT BE DE"
	    "TERMINED.  INITIAL MOTION DIRECTION VECTOR OR ITS ORIENTATION CO"
	    "ULD NOT  BE DETERMINED.    CUTTER NOT DEFINED PRIOR TO CUT SEQUE"
	    "NCE CALCULATION.   'FROM' POINT NOT SPECIFIED. 'MOTION' MODIFIER"
	    " ('ON','TO','PAST','TANTO','PSTAN') NOT  SPECIFIED.    CHECK SUR"
	    "FACE MISSING FOR THIS 'MOTION' STATEMENT.  CUTTER NOT DEFINED PR"
	    "IOR TO CUT SEQUENCE CALCULATION.   FROM POINT NOT SPECIFIED.   M"
	    "ORE THAN ONE CHECK SURFACE SPECIFIED IN A STARTUP. 'NOPS' IN EFF"
	    "ECT, BUT PS SPECIFIED IN STARTUP.  STARTUP ITERATION FAILED TO C"
	    "ONVERGE.   INVALID DATA FOR STARTUP. (SEE COMPUTER PROGRAMMER). "
	    "   INDIRP VECTOR HAS NO LENGTH.    DIRECTION OF MOTION GIVEN WIT"
	    "HOUT A STARTING POINT BEING GIVEN. CANNOT DETERMINE SURFACE TYPE"
	    ". DS ASSUMED.  INDIRV VECTOR HAS NO LENGTH.    DIRECTION OF MOTI"
	    "ON GIVEN WITHOUT A STARTING POINT BEING GIVEN. CANNOT DETERMINE "
	    "SURFACE TYPE. DS ASSUMED.  SRFVCT VECTOR HAS NO LENGTH.    CANNO"
	    "T DETERMINE SURFACE TYPE. DS ASSUMED.  DIRECTION OF MOTION GIVEN"
	    " WITHOUT A STARTING POINT BEING GIVEN. NO DRIVE SURFACE NAMED AF"
	    "TER GO/. ENTERING RESTART MODE.    ITEM NOT 'FEDRAT','TO','ON','"
	    "PAST' OR SURFACE FOUND AFTER GO/.  ENTERING RESTART MODE.  ILLEG"
	    "AL PERMANENT IDENTIFIER FOLLOWS GO/. ENTERING RESTART  MODE.   I"
	    "LLEGAL LANGUAGE USAGE ENCOUNTERED BEFORE DRIVE SURFACE.  ENTERIN"
	    "G RESTART MODE.    INVALID CUTTER DEFINITION FORMAT.   CUTTER DI"
	    "AMETER IS NEGATIVE.    CUTTER HEIGHT IS NEGATIVE.  CUTTER ANGLES"
	    " (ALPHA AND BETA) ARE TOO LARGE.   CUTTER ANGLE ALPHA IS NEGATIV"
	    "E. DIAMETER, ALPHA AND HEIGHT OF CUTTER ARE INCONSISTENT.  CUTTE"
	    "R ANGLE BETA IS NEGATIVE.  CORNER RADIUS OF CUTTER IS NEGATIVE. "
	    "   CORNER CIRCLE CENTER IS INCONSISTENT WITH UPPER LINE SEGMENT "
	    " OF CUTTER.    CORNER CIRCLE OF CUTTER INTERCEPTS LOWER LINE SEG"
	    "MENT AT AN  UNACCEPTABLE ANGLE.    INCONSISTENT CUTTER DEFINITIO"
	    "N. LOWER LINE SEGMENT  IGNORED.    NO UPPER LINE SEGMENT ON CUTT"
	    "ER, OR CORNER CIRCLE MEETS LOWER  LINE SEGMENT INCORRECTLY.    C"
	    "ORNER CIRCLE OF CUTTER DOES NOT INTERSECT LOWER LINE SEGMENT.  C"
	    "ORNER CIRCLE OF CUTTER DOES NOT INTERSECT UPPER LINE SEGMENT.  C"
	    "ORNER CIRCLE OF CUTTER INTERSECTS UPPER LINE SEGMENT AT  UNACCEP"
	    "TABLE ANGLE.   INCONSISTENT CUTTER DEFINITION. UPPER LINE SEGMEN"
	    "T IGNORED. CUTTER DEFINITION NOT VALID.WRONG DATA IN TLINC, NO A"
	    "RC OR NO LINE  NO CUTTER DEFINED TO COMPUTE DISC RADIUS RA OR DI"
	    "SC HEIGHT HI.  POINT IS OUTSIDE OF THE U/V PARAMETERS OF A PATCH"
	    ".  R1 IS LESS THAN THE TOLERANCE.  THE TOOL AXIS CANNOT BE COMPU"
	    "TED.   WRONG TOOL AXIS INFORMATION.    A 'TLAXIS' COMMAND HAS BE"
	    "EN USED WITHOUT A PREVIOUS  'MULTAX' COMMAND. NO TOOLAXIS VALUES"
	    " OUTPUT        TOO MANY PARAMETERS IN A 'TLAXIS' STATEMENT. EXCE"
	    "SS VALUES  IGNORED.    A 'MULTAX' COMMAND HAS BEEN USED FOLLOWIN"
	    "G PREVIOUS  MOTION OUTPUT WITHOUT TOOL AXIS VALUES.    'THICK' G"
	    "IVEN FOR MORE THAN THE ALLOWED NUMBER OF  SURFACES. EXTRA VALUES"
	    " IGNOREREGION DATA BELONGS TO MORE THAN ONE SURFACE.   LESS THAN"
	    " 3 POINTS AS REGION BOUNDARY.  REGION BOUNDARY IS INCORRECT.   R"
	    "EGION BOUNDARY CONTAINS INTERSECTIONS. TOO MANY REGION POINTS TO"
	    " PROCESS.  REGION DATA CANNOT BE FETCHED.  GEOMETRY ELEMENT IS N"
	    "OT DEFINED - RETURN WITHOUT RESULT.NO INTERSECTION POSSIBLE.   S"
	    "AME SSURF FOUND TWICE BEFORE >WITH< ONLY FIRST FOUND SSURF IN FI"
	    "RST PART OF THE STATEMENT WILL BE USED.SAME SSURF FOUND TWICE AF"
	    "TER >WITH< ONLY FIRST FOUND SSURF IN SECOND PART OF THE STATEMEN"
	    "T WILL BE USED.SAME SSURF WILL BE INTERSECTED BY ITSELF THIS IS "
	    "NOT POSSIBLE.  D.  SURFACE TYPE NOT IDENTIFIABLE. (SEE COMPUTER "
	    "PROGRAMMER).   CANONICAL FORM OF SURFACE UNDEFINED.    CUTTER NO"
	    "T WITHIN TOLERANCE OF DS AT START OF CUT.  DS AND CS CIRCLES HAV"
	    "E SAME CENTER. DS AND CS NOT TANGENT AS STARTED.   REQUESTED FIN"
	    "AL CUTTER POSITION NOT POSSIBLE.   DS DOES NOT INTERSECT CS GOIN"
	    "G IN SPECIFIED DIRECTION.  CS AND DS DO NOT INTERSECT. CUT VECTO"
	    "R ITERATION TO DS AND PS FAILED.   CUT VECTOR ITERATION TO CS FA"
	    "ILED.  'NUMPTS' COUNT EXHAUSTED. MISSED CS OR CUT SEQUENCE IS TO"
	    "O  LONG.   COULD NOT DETERMINE TRIAL MOVE ALONG DS AND PS. CHECK"
	    " CUTTER  TO SURFACE CONFIGURATION. MAXIMUM CUT SEQUENCE LENGTH E"
	    "XCEEDED. CS COULD NOT BE FOUND.    MULTIPLE CS ERROR. (SEE COMPU"
	    "TER PROGRAMMER)NEGATIVE DISTANCE TO CS AT START OF CUT .   CUTTE"
	    "R IS MOVING AWAY FROM CS.  DISTANCE TO TANGENT CS STOPPING POSIT"
	    "ION CANNOT BE  DETERMINED. ITERATION TO PS, DS, CS GONE THRU RES"
	    "TART ROUTE.    CENTER CSNR EXIT TAKEN DURING PLANE ROUTINE ITERA"
	    "TION.  (SEE COMPUTER PROGRAMMER).  CS NOT FOUND IN MOVE ALONG DS"
	    " AND PS PLANES.    MAXIMUM CUT SEQUENCE LENGTH EXCEEDED. CS COUL"
	    "D NOT BE FOUND.    DIFFICULTY ENCOUNTERED IN ITERATING CUTTER TO"
	    "  SURFACES.    CANNOT ITERATE CUTTER INTO SPECIFIED SURFACES.  C"
	    "OULD NOT DETERMINE NEW TOOL AXIS DURING 5 AXIS CALCULATION.  (SE"
	    "E COMPUTER PROGRAMMER).    5 AXIS ITERATION DID NOT CONVERGE.  T"
	    "ANGENT CS STOPPING POSITION COULD NOT BE DETERMINED.   5 AXIS CO"
	    "UNT EXHAUSTED. TANGENT CS AND PS/DS-NORMALS NEARLY ORTHOGONAL.  "
	    "CHECK PART PROGRAM.    TWO PLANES, NOT PERPENDICULAR TO THE XY P"
	    "LANE,  CANNOT BE USED AS DS AND CS FOR 'TANTO' CASE.   COULD NOT"
	    " FIND AN INTERSECTION BETWEEN TOOL RAY AND SURFACE.    TOO MANY "
	    "CALLS TO DDSSRF WITHOUT DETERMINING A NEW CUTTER  POSITION.    M"
	    "ODIFIED FLIPCK TEST PASSED.    COULD NOT DETERMINE NORMAL DISTAN"
	    "CE DIRECTION BETWEEN CUTTER  AND SURFACE.  INITIAL PREFERRED DIR"
	    "ECTION DOES NOT INTERSECT  SURFACE.    COULD NOT CALCULATE SURFA"
	    "CE NORMAL AT SURFACE POINT  (SEE COMPUTER PROGRAMMER). SYNTHETIC"
	    " CURVE NOT NOW PROGRAMMED FOR ARELEM   RADAR EXHAUSTED ALL TRIES"
	    "   COULD NOT CALCULATE UI VECTOR STARTING WITH TWO OR MORE  DIRE"
	    "CTIONS. (SEE COMPUTER PROGRAMMER). CUTTER REFERENCE POINT AND SU"
	    "RFACE CENTER OF CURVATURE  COINCIDE.   UNABLE TO CALCULATE SATIS"
	    "FACTORY TOOL NORMAL.   DIFFICULTY IN LOCATING SURFACE. ZERO TOOL"
	    " NORMAL. (SEE COMPUTER PROGRAMMER).    COULD NOT FIND DIRECTION "
	    "VECTOR THAT INTERSECTS THE SURFACE.    'NODER' OR 'DERIV' NOT DE"
	    "FINED. INCONSISTENT WITH  PARAMETRIC SURFACE SOUBROUTINE. MODIFI"
	    "ER DISREGARDED.    COULD NOT PERFORM ARELEM COMPUTATION DUE TO Z"
	    "ERO SURFACE  NORMAL. CHECK DERIVATIVES IN PARAMETRIC SUBROUTINE."
	    "   PARAMETRIC SURFACE FAMILY PARAMETER IS NOT DEFINED. PARAMETRI"
	    "C SURFACE PARAMETER >U< IS NOT DEFINED.    PARAMETRIC SURFACE PA"
	    "RAMETER >V< IS NOT DEFINED.    THE PARAMETRIC SUBROUTINE (LOAD M"
	    "ODULE) DOES NOT EXIST  IN JOB LIBRARY. CANNOT ITERATE TO A ROOT "
	    "OF THE CUBIC EQUATION IN  THIS SEGMENT.    TOO MANY STATEMENTS I"
	    "N THIS PART PROGRAM.   LARGEST CANONICAL FORM IS TOO LARGE.    I"
	    "NDEX OUT OF RANGE. SYSTEM ERROR. ILLEGAL I.L. INSTRUCTION. SYSTE"
	    "M ERROR. ILLEGAL CALL I.L. INSTRUCTION.    UNDEFINED LABEL REFER"
	    "ENCED. " };


/* *** SOURCE FILE : BDEXER.V01   *** */


/* ...FORTRAN BLOCK DATA SEGMENT EXERRW */

/* Subroutine */ int bdexer_(void)
{
    return 0;
} /* bdexer_ */









/* ...ERRAD1:    EXECUTION PHASE ERROR & WARNING NUMBERS. */
/* ...ERRAD2:    START POSITIONS OF ERROR MESSAGES IN ERRTXT */



