/* CLERRW.f -- translated by f2c (version 20100827).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/* Common Block Declarations */

struct clerrw_1_ {
    integer cerdm, cercnt, cerad1[34], cerad2[34];
};

#define clerrw_1 (*(struct clerrw_1_ *) &clerrw_)

struct clerrt_1_ {
    char certxt[2280];
};

#define clerrt_1 (*(struct clerrt_1_ *) &clerrt_)

/* Initialized data */

struct {
    integer e_1[70];
    } clerrw_ = { 34, 570, 30001, 30002, 30003, 30004, 30005, 30006, 30008, 
	    30009, 30010, 30011, 30012, 30013, 30014, 30015, 30016, 30017, 
	    30018, 30019, 30020, 30021, 30024, 30025, 30026, 30027, 30030, 
	    30031, 30032, 30034, 30035, 30036, 30037, 30038, 30039, 30040, 7, 
	    32, 52, 76, 94, 110, 126, 141, 153, 171, 189, 199, 206, 219, 232, 
	    246, 272, 279, 287, 294, 314, 324, 345, 369, 379, 400, 410, 434, 
	    461, 487, 514, 521, 553, 570 };

struct {
    char e_1[2280];
    } clerrt_ = { "INVALID VTLAXS STATEMENT.   A VTLAXS/OFF COMMAND WAS GIVE"
	    "N WITHOUT A VTLAXS/ON COMMAND OR  A PREVIOUS VTLAXS ERROR OCCURR"
	    "ED.    TWO VTLAXS/ON COMMANDS WERE GIVEN WITHOUT A VTLAXS/OFF CO"
	    "MMAND BETWEEN THEM.    A FROM COMMAND WAS GIVEN BETWEEN A VTLAXS"
	    "/ON COMMAND AND ITS  CORRESPONDING VTLAXS/OFF COMMAND. A VTLAXS "
	    "COMMAND WAS GIVEN WITHOUT A PREVIOUS MOTION OR FROM  COMMAND.  A"
	    " VTLAXS COMMAND WAS GIVEN WITHOUT A PREVIOUS MULTAX COMMAND.   V"
	    "TLAXS ERROR. CORNER RADIUS IS GREATER THAN THE CUTTER RADIUS.  V"
	    "TLAXS ERROR. CORNER RADIUS MUST BE ZERO WHEN USING ZSMALL. NO MO"
	    "TION BETWEEN A VTLAXS/ON AND A VTLAXS/OFF. TRACUT WAS GIVEN BETW"
	    "EEN A VTLAXS/ON AND ITS CORRESPONDING  VTLAXS/OFF. COPY WAS GIVE"
	    "N BETWEEN A VTLAXS/ON AND ITS CORRESPONDING  VTLAXS/OFF.   INCOR"
	    "RECT MODIFIER IN A COPY COMMAND.   INDEX NUMBER NOT DEFINED.   I"
	    "NCORRECT NUMBER OF PARAMETERS IN THE COPY COMMAND. THE PARAMETER"
	    " 'N' IN THE COPY IS ZERO OR NEGATIVE.  MIRROR, MIRROR ON THE WAL"
	    "L, YOU ARE NOT ALLOWED AT ALL. COPY LOGIC ERROR. CHECK PART PROG"
	    "RAM FOR OVERLAPPING COPY AREAS  OR AN ILLEGAL TRANSFER INTO COPY"
	    " LOOP. COPY IS OVER 3 NEST LEVELS. INDEX NUMBER PREVIOUSLY USED."
	    "   TOO MANY INDEX/N COMMANDS.  SYSTEM FAILURE. POSITIONING ERROR"
	    " IN COPY LOGIC.  CHECK COMPUTER PROGRAMMER.    BAD PARAMETER IN "
	    "THIS CLDAT STATEMENT.  THE FIRST RECORD NUMBER GIVEN IN THE CLDA"
	    "T STATEMENT WAS NOT  FOUND IN OLD CLFILE.  EXFILE FORMAT ERROR. "
	    "UNRECOGNIZABLE COMMAND. FRAME SIZE IS  LESS THAN ZERO IN WIDTH O"
	    "R LENGTH.  UNIDENTIFIED POST PROCESSOR COMMAND.    THE LAST RECO"
	    "RD NUMBER GIVEN IN THE CLDAT STATEMENT WAS NOT  FOUND IN OLD CLF"
	    "ILE.   INVALID CLFILE RECORD. RUN TERMINATED.  NO COPY TRANSFORM"
	    "ATION HAS BEEN PERFORMED BECAUSE AN ERROR  HAS OCCURED INSIDE TH"
	    "E COPY LOOP.   THE LIMIT ON THE NUMBER OF LENGTH OF POSTPROCESSO"
	    "R TYPE  COMMANDS AFTER A HOLDPP COMMAND HAS BEEN EXCEEDED. THE F"
	    "OLLOWING VTLAXS SEQUENCE HAS NOT BEEN PROCESSED BECAUSE  AN AREL"
	    "EM ERROR HAS OCCURRED WITHIN IT.   AN ARELEM RESTART ERROR HAS C"
	    "AUSED CL PRINTOUT STARTING AT THE  CL POINT PRECEDING THE ERROR "
	    "INFORMATION.   ERRONEOUS UNITS COMMAND.    TOO EXTENSIVE COPY CO"
	    "MMANDS, COMMON NCFSTO TOO SMALL: SUBDIVIDE  COPY-SEQUENCE, OR IN"
	    "CREASE NCFSTO-STORAGE (SYSTEM PROGRAMMER). COPY OR TRACUT PROCES"
	    "SING FOR EXTENDED CLDATA FORMATS NOT MOUNTED.  " };


/* *** SOURCE FILE : M0011541.W01   *** */


/* ...FORTRAN SUBROUTINE CLERRW  (BLOCK DATA) */

/* Subroutine */ int bdcler_(void)
{
    return 0;
} /* bdcler_ */





/* ...COMMON/CLERR/ SPLIT INTO /CLERRW/ FOR INTEGERS & /CLERRT/ FOR TEXT */









/* ...CERAD1 : ERROR & WARNING NUMBERS FOR CL EDITOR */
/* ...CERAD2 : POSITION IN ARRAY CERTXT OF END OF ERROR MESSAGE */




