/* ERRWRD.f -- translated by f2c (version 20100827).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/* Common Block Declarations */

struct errwr_1_ {
    integer errad1[159], errad2[159];
};

#define errwr_1 (*(struct errwr_1_ *) &errwr_)

struct errtxt_1_ {
    char errtxt[7940];
};

#define errtxt_1 (*(struct errtxt_1_ *) &errtxt_)

/* Initialized data */

struct {
    integer e_1[318];
    } errwr_ = { 1, 2, 3, 4, 7, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	     22, 24, 26, 27, 28, 29, 31, 32, 34, 35, 36, 37, 38, 40, 50, 52, 
	    53, 55, 56, 71, 72, 73, 74, 1001, 1002, 1003, 1004, 1005, 1007, 
	    1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 
	    1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1028, 1029, 1032, 
	    1035, 1036, 1037, 1038, 1039, 1040, 1041, 1050, 1111, 1201, 1203, 
	    1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1215, 
	    1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1227, 
	    1228, 1229, 1230, 1232, 1233, 1235, 2001, 2002, 2003, 2004, 2005, 
	    2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2015, 2017, 2018, 
	    2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 
	    2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2041, 
	    2042, 2044, 2045, 2046, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 
	    2058, 3001, 3002, 11, 25, 37, 50, 64, 80, 98, 106, 119, 131, 145, 
	    158, 178, 188, 206, 225, 244, 266, 284, 302, 317, 340, 361, 380, 
	    401, 416, 421, 428, 435, 457, 472, 499, 522, 537, 551, 565, 590, 
	    609, 622, 643, 670, 683, 687, 690, 697, 704, 709, 719, 724, 729, 
	    732, 738, 744, 757, 763, 772, 781, 790, 796, 804, 810, 821, 835, 
	    842, 853, 864, 879, 892, 918, 930, 940, 946, 950, 961, 970, 985, 
	    999, 1009, 1019, 1028, 1038, 1049, 1061, 1068, 1077, 1088, 1101, 
	    1110, 1120, 1131, 1143, 1159, 1166, 1173, 1180, 1184, 1196, 1209, 
	    1219, 1235, 1244, 1253, 1260, 1267, 1279, 1291, 1304, 1316, 1327, 
	    1334, 1347, 1366, 1381, 1404, 1426, 1445, 1455, 1471, 1477, 1482, 
	    1500, 1512, 1530, 1542, 1562, 1568, 1579, 1595, 1613, 1620, 1637, 
	    1653, 1663, 1674, 1694, 1711, 1723, 1733, 1739, 1755, 1766, 1780, 
	    1800, 1817, 1825, 1836, 1846, 1854, 1868, 1878, 1891, 1900, 1917, 
	    1924, 1933, 1945, 1961, 1973, 1985 };

struct {
    char e_1[4608];
    char fill_2[16];
    char e_3[3316];
    } errtxt_ = { "INVALID CHARACTER IN PRECEDING STATEMENT    I.L. STORAGE "
	    "EXHAUSTED. FURTHER CALLS CAUSE DATA LOSS   ARGUMENTS CANNOT PREC"
	    "EDE OPCODE. CALL IGNORED   OPCODE CALL PRECEDED RELEASE. PREVIOU"
	    "S LINE LOST    PARAMETRIC SURFACE IS NOT NAMED. SURFACE IS UNDEF"
	    "INED   PARAMETRIC SURFACE VARIABLE IS NOT A SCALAR.SURFACE IS UN"
	    "DEFINEDPARAMETRIC SURFACE MODIFIER IS NOT DERIV OR NODER. SURFAC"
	    "E IS UNDEFINED NO PARAMETERS FOLLOW COMMAND    NO SURFACE IS NAM"
	    "ED. COMMAND IGNORED, CONTINUING    TAGTBL MAY OVERFLOW. TOO MANY"
	    " CHECK SURFACES    TOO MANY SYSTEM-GENERATED LABELS; TABLE LENGT"
	    "H EXCEEDED SYMBOL EXCEEDS SIX CHARACTERS; IT MAY BE TRUNCATED  N"
	    "AME FOLLOWING CALL/ IS NOT A PREVIOUSLY DEFINED MACRO NOR IT IS "
	    "A SYSTEM MACRO UNKNOWN FORMAT USED IN OBTAIN STATEMENT TOO MANY "
	    "ARGUMENTS IN CANON OR OBTAIN STATEMENT;CANSTK ARRAY EXCEEDED   L"
	    "INUSD TABLE USED IN MACRO PROCESSING IS FILLED. SEE APT SYSTEM P"
	    "ROGRAMMER  TOO MANY MACRO VARIABLES IN PART PROGRAM. MACDF1 AND "
	    "MACDF2 TABLES EXCEEDED TOO MANY VALUES ASSIGNED TO THE MACRO VAR"
	    "IABLES IN PART PROGRAM. MACHST TABLE EXCEEDED  MACRO NEST LEVEL "
	    "MAXIMUM EXCEEDED. MACSV1,MACSV2,MACSV3 TABLES EXCEEDED MAS TABLE"
	    " USED IN MACRO PROCESSING IS FILLED. SEE APT SYSTEM PROGRAMMER M"
	    "ORE THAN 50 MACROS IN PART PROGRAM. MACSEQ TABLE EXCEEDED  TOO M"
	    "ANY MACRO VARIABLES HAVE BEEN ASSIGNED MACRO NAMES. MNMVB AND MN"
	    "MVC TABLES EXCEEDED    VBLSAV TABLE OVERFLOW.REDUCE NUMBER OF MA"
	    "CRO CALLS AND/OR NUMBER OF MACRO VARIABLES MACSPD TABLE USED IN "
	    "MACRO PROCESSING IS FILLED.SEE APT SYSTEM PROGRAMMER   TOO MANY "
	    "MACRO VARIABLES IN A SINGLE EXPRESSION. MRGSTK OR MACVAR TABLE O"
	    "VERFLOW    KSC TABLE FILLED. TOO MANY SCULPTURED SURFACE DEFINIT"
	    "IONS   TOO MUCH MACRO TEXT NUMERIC NAME TABLE OVERFLOW INVALID U"
	    "SE OF WORD TERMAC  SUPPOSED PROCEDURE DOES NOT HAVE CLASS PROCED"
	    "URE OR FUNCTION. SEE APT SYSTEM PROGRAMMER LABARY TABLE FILLED. "
	    "NO FURTHER SEARCH FOR MISSING LABELS   GEOMETRIC VARIABLE BEING "
	    "USED HAS BEEN PREVIOUSLY DEFINED WITH THE SAME MODE. FIRST DEFIN"
	    "ITION OVERRIDDEN   SCULPTURED SURFACE VARIABLE BEING USED HAS BE"
	    "EN PREVIOUSLY DEFINED. FIRST DEF. OVERRIDDEN   TOO MANY LARGE DA"
	    "TA ARRAY DEFINITIONS. CANSIZ TABLE FILLED  MISSING FINI. FINI IN"
	    "SERTED AND PROCESSING CONTINUES    MISSING TERMAC. FINI INSERTED"
	    " AND PROCESSING CONTINUES  SEGMENT READ OR FIRST CALL TO SYSTEM "
	    "MACRO CANNOT BE CONTAINED IN A SEGMENT READ OR A SYSTEM MACRO  U"
	    "NABLE TO OPEN LIBRARY APTLIB. COULD RESULT FROM CALL TO UNDEFINE"
	    "D MACRO    SEGMENT NAMED IN READ/ STATEMENT IS NOT IN APTLIB   U"
	    "NABLE TO READ A RECORD FROM APTLIB; I/O ERROR OR ILLEGAL BLOCKSI"
	    "ZE OR RECORD SIZE  GEOMETRIC VARIABLE BEING USED HAS BEEN PREVIO"
	    "USLY DEFINED WITH A DIFFERENT MODE. FIRST DEFINITION RETAINED  M"
	    "ISSING LABEL STATEMENT ADDRESSED BY JUMPTO OR IF   DUPLICATE LAB"
	    "EL MIXED MODE  INVALID USE OF MINUS SIGN   INVALID STATEMENT IGN"
	    "ORED   IMPROPER ARGUMENT   MISSING LABEL. STATEMENT NOT REACHABL"
	    "E  MATRIX MUST FOLLOW  NOMORE MUST FOLLOW  MIXED MODE  VARIABLE "
	    "IS UNRESERVED  NO TYPE FOR VARIABLE    SURFACE TYPE CHANGED IN N"
	    "ESTED GEOMETRIC DEFINITION MACRO DEFINITION NESTED MACRO NAME NO"
	    "T PRECEEDED BY CALL    DUMMY VARIABLE EXPECTS MACRO NAME   DUMMY"
	    " VARIABLE REJECTS MACRO NAME   UNKNOWN MACRO VARIABLE  ERROR IN "
	    "FINAL MACRO PROCESSING RECURSIVE USE OF MACROS ILLEGAL MODE FOR "
	    "TEMPORARY IN CALL TO MACRO VARIABLE NAME IN CANON DEFINITION IS "
	    "OF INCORRECT MODE  INVALID TABCYL DEFINITION   INVALID TABCYL US"
	    "ED IN RLDSRF DEFINITION    INPUT STATEMENT IS TOO LONG. STACK OV"
	    "ERFLOW BOUNDED GEOMETRY MUST NOT BE SUBSCRIPTED. STATEMENT IGNOR"
	    "ED INVALID ARGUMENT IN A LARGE DATA CANON STATEMENT    OBTAIN ST"
	    "ATEMENT SPECIFIES MORE VARIABLES THAN THERE ARE ELEMENTS IN INDI"
	    "CATED SURFACE CANONICAL FORM   TOO MANY DO-ARGUMENTS OR ARGUMENT"
	    " WITHOUT VALUE DO-LOOP NOT CLOSED AT FINI OR TERMAC    MORE THAN"
	    " 10 DO NESTED  BAD NESTED DO   IDENTICAL NAMES OF VARIABLES IN N"
	    "ESTED DO   ILLEGAL PATERN DEFINITION FORMAT    WRONG SURFACE ASS"
	    "OCIATED WITH VARIABLE IN OBTAIN STATEMENT  ILLEGAL SUBSCRIPTED V"
	    "ARIABLE. CHECK FOR MISSING RESERV  MORE THAN 30 RESP. 5 POINT DE"
	    "FINITIONS  MORE THAN 30 RESP. 5 SPLINE DEFINITIONS SURFACE DEFIN"
	    "ITION IS NOT COMPLETE  TOO MANY SEGMENTS IN THE FLOW SECTION   I"
	    "NCORRECT DEFINITION OF THE FLOW SEGMENT    TOO MANY OR INCORRECT"
	    " ITEMS IN THE FLOW SECTION TOO MANY SEG DEFINITIONS    MULTIPLE "
	    "DEFINED LIMIT OR WEIGHT    TANSPL,CRSSPL OR NORMAL MULTIPLE DEFI"
	    "NED    USE OF CRSSPL ONLY CORRECT AT START AND END POINT   MODIF"
	    "ICATOR OR DEFINITION REPEATING MORE THAN 30 SURFACES DEFINE A CO"
	    "MBIN   MORE THAN ONE PATCH DEFINE A PATCH/PNTSON   TRFORM,MATRIX"
	    " NOT ALLOWED IN THIS DEFINITION    TRFORM,MATRIX SHOULD BE DEFIN"
	    "ED AT T", {0}, "FINITION    MATRIX DEFINITION EXPECTED  POINT DE"
	    "FINITION EXPECTED   VECTOR DEFINITION EXPECTED  SCALAR EXPECTED "
	    "POINT DEFINITION NOT PERMITTED IN THIS POSITION VECTOR DEFINITIO"
	    "N NOT PERMITTED IN THIS POSITION    SCALAR NOT PERMITTED IN THIS"
	    " POSITION   VARIOUS NUMBERS OF POINTS OR LESS THAN TWO POINTS IN"
	    " THE SPLINESSTK TABLE FILLED. SURFACE UNDEFINED TRIPLE NESTED SU"
	    "RFACE DEFINITION    SSURF DEFINITION EXPECTED   SCURV DEFINITION"
	    " EXPECTED   SSURF DEFINITION NOT PERMITTED IN THIS POSITION SCUR"
	    "V DEFINITION NOT PERMITTED IN THIS POSITION SURFACE DEFINITION A"
	    "ND ITS SIZE IS NOT TO BE FOUND  FORMAT UNKNOWN OR SOME PARAMETER"
	    "S ARE UNDEFINED ILLEGAL ARGUMENT IN POSTPROCESSOR STATEMENT ILLE"
	    "GAL GODLTA STATEMENT    NO DRIVE SURFACE NAMED AFTER GO/, ENTERI"
	    "NG RESTART  ITEM NOT FEDRAT, TO, ON, PAST OR SURFACE FOUND AFTER"
	    " GO/. ENTERING RESTART  ILLEGAL PERMANENT IDENTIFIER FOLLOWS GO/"
	    ". ENTERING RESTART  A LOGICALLY COMPLETE GO/ COMMAND WAS FOLLOWE"
	    "D BY OTHER DATA. SURPLUS CHECK SURFACES IGNORED MORE THAN ONE CH"
	    "ECK SURFACE FOUND AFTER A GO COMMAND. SURPLUS CHECK SURFACES IGN"
	    "ORED    ILLEGAL LANGUAGE USAGE ENCOUNTERED BEFORE DRIVE SURFACE."
	    "ENTERING RESTART    FIRST NOT DRIVE SURFACE. DS IS ASSUMED  STAT"
	    "EMENT WITH WRONG ARGUMENTS: TOO LONG OR ILLEGAL GEOMETRY    PARA"
	    "METER LIST TOO LONG ILLEGAL ARGUMENT    APPROPRIATE SURFACE IS N"
	    "OT NAMED AFTER PSIS.COMMAND IGNORED.CONTINUING  INPROPER FORMAT "
	    "FOR JUMPTO. STATEMENT IGNORED   SYN OR RESERV STATEMENT HAS NO A"
	    "RGUMENTS OR AN ODD NUMBER OF ARGUMENTS  SYN STATEMENT HAS A VALU"
	    "E OR AN ILLEGAL WORD    NO DRIVE SURFACE FOUND PRECEDING OTHERWI"
	    "SE ACCEPTABLE FORMATS. ENTERING RESTART ARGUMENT MODE IS WRONG  "
	    "AN ACCEPTABLE CHECK SURFACE IS NOT NAMED    IDENTIFIER NOT PRECE"
	    "DED BY ACCEPTABLE SURFACE. ENTERING RESTART THE WORD INTOF WAS N"
	    "OT PRECEDED BY A NUMBER.FIRST INTERSECTION ASSUMED  MACRO VARIAB"
	    "LE NOT FUNCTION TOO MANY DIMENSIONED VARIABLES IN PART PROGRAM. "
	    "RANGE TABLE FILLED  INCORRECT FORMAT FOR RESERV STATEMENT. MUST "
	    "BE SYMBOL,NUMBER    NO ARGUMENTS DESIRED. ARGUMENTS IGNORED ARGU"
	    "MENT FOLLOWING ZSURF/ IS NOT A PLANE    NO ARGUMENTS FOLLOW PRIN"
	    "T/,PUNCH/,CFSAVE/,CONTRL/ OR PPOPTN/. STATEMENT IGNORED INVALID "
	    "ARGUMENT FOLLOWS PRINT/, PUNCH/ OR CFSAVE/.ARGUMENT IGNORED INVA"
	    "LID NUMBER OF ARGUMENTS IN CANON DEFINITION INVALID ARGUMENT IN "
	    "CANON DEFINITION    INVALID POCKET FORMAT   A SYNONYM ARGUMENT P"
	    "AIR CONTAINS NO VARIABLE OR TWO VARIABLES   INPROPER ARGUMENT IN"
	    " GOTO/PATERN STATEMENT  BOTH OMIT AND RETAIN SPECIFIED IN GOTO/P"
	    "ATERN STATEMENT TOO MANY ARGUMENTS SPECIFIED IN GOTO/PATERN STAT"
	    "EMENT. ARGSTK TABLE OVERFLOW    ILLEGAL ARGUMENT OR UNEVEN NUMBE"
	    "R OF ARGUMENTS IN PPOPTN STATEMENT  TOO MANY ARGUMENTS IN INCR L"
	    "IST INVALID CONTROL STATEMENT. ARGUMENT IGNORED DUPLICATE NAME O"
	    "F DIMENSIONED VARIABLES RESERV INVALID IN MACRO PROGRAM CLDAT SE"
	    "CTION NESTED OR STATEMENT IN WRONG SEQUENCE.    INVALID ARGUMENT"
	    " IN OBTAIN STATEMENT    INCORRECT NUMBER OF ARGUMENTS OR INVALID"
	    " ARGUMENT   INVALID INCLUSIV SUBSCRIPT FORMAT   A,B AND C IN INC"
	    "LUSIVE SUBSCRIPT FORMAT MUST BE EXPLICIT INTEGERS   UNEVEN NUMBE"
	    "R OF ARGUMENTS  INVALID ARGUMENT SHOULD BE ON OR OFFINVALID ARGU"
	    "MENT SHOULD BE PS OR A SSURF NAME   THERE IS NO ASSIGNMENT TO AR"
	    "GUMENT: ........ IN MACRO : ........SYMBOLIC NAME TABLE OVERFLOW"
	    ". SYMBOL IGNORED    TABLE OVERFLOW FOR NUMERICAL MACRO ASSIGNMEN"
	    "TS. " };


/* *** SOURCE FILE : M0004613.W03   *** */


/*     FORTRAN SUBROUTINE ERRWRD */

/* Subroutine */ int trerrw_(void)
{
    return 0;
} /* trerrw_ */












