/* IEPLOG.f -- translated by f2c (version 20100827).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/* Common Block Declarations */

struct {
    integer charst, charnd, inamst, inamnd, namest, nammax, ifixst, ifixnd, 
	    numbst, numbnd, namtbl[3000];
} nametb_;

#define nametb_1 nametb_

struct {
    char cnamtb[18000], cnumtb[36000];
} cnamtb_;

#define cnamtb_1 cnamtb_

struct {
    integer cfsize[205];
} cfsize_;

#define cfsize_1 cfsize_

struct {
    integer prt[7];
} prt_;

#define prt_1 prt_

struct {
    integer clfilp, clfile, clfil3, exfile, infile__, vlfile, pnchfl, xcan, 
	    mactxt, xnum, elfil1, elfil2, elfil3, elfil4, cpfile, axfile, 
	    pofile, elfile, ldafil, tifile, pxfile, nfil12, nfil13, libfil, 
	    ispare[26];
} symfil_;

#define symfil_1 symfil_

struct {
    integer pagpak, isc, iscarr, icform, ifloat, icom, macwds, ppwrds;
    logical macflg, labflg, rsvflg;
    integer lpage, buffer[256], labbuf[256], ibuf, ilbuf, pppage, mcpage;
} outbuf_;

#define outbuf_1 outbuf_

struct {
    integer ntbl[6];
} ntbl_;

#define ntbl_1 ntbl_

struct {
    integer mnmbnd, numidx, nmbrs, lstchr, masgnd;
} numblk_;

#define numblk_1 numblk_

/* Table of constant values */

static integer c_n2 = -2;
static integer c__23 = 23;
static integer c_n3 = -3;

/* *** SOURCE FILE : M0006636.W02   *** */


/*              FORTRAN SUBROUTINE IEPLOG */

/* LINKAGE      SUBROUTINE IEPLOG */

/*          SUBSIDIARIES                  CALLED BY */
/*          TYPE          ENTRY           TYPE          ENTRY */
/*          SUBROUTINE    AWRITE          SUBROUTINE    EPILOG */
/*          SUBROUTINE    MCXTRN */
/*          SUBROUTINE    NTSHFT */
/*          SUBROUTINE    RLSBUF */
/*          SUBROUTINE    TAPOP */

/* Subroutine */ int ieplog_(void)
{
    /* Local variables */
    static integer i__;
#define buf ((integer *)&outbuf_1)
    static integer irec;
#define jbuf ((integer *)&outbuf_1 + 12)
#define nmod ((integer *)&ntbl_1)
    static integer iret;
#define nstr ((integer *)&ntbl_1 + 4)
#define iname ((integer *)&outbuf_1 + 13)
#define inumb ((integer *)&outbuf_1 + 12)
#define nlast ((integer *)&ntbl_1 + 3)
    extern /* Subroutine */ int tapop_(integer *, integer *);
#define cilprt ((logical *)&prt_1)
#define lcilpr ((logical *)&outbuf_1 + 17)
#define maxsiz ((integer *)&cfsize_1 + 3)
    extern /* Subroutine */ int rlsbuf_(void), awrite_(integer *, integer *, 
	    integer *, integer *, integer *), chwrit_(integer *, integer *, 
	    char *, integer *, integer *, ftnlen);



/*        1.    NAME TABLE AND TABLE LIMITS */

/* NAMTBL:      INTEGER CORRESPONDING TO NAME TABLE ENTRY */
/* CNAMTB:      NAME TABLE OR DICTIONARY */
/* INAMST:      BEGIN GEOMETRIC DEFINITION ROUTINE NAME SECTION(NAMTBL) */
/* NAMMAX:      NAMTBL INDEX OF END OF THE PART PROGRAM NAME SECTION */
/* IFIXST:      NAMTBL INDEX OF BEGINNING OF FIXED POINT NUMBER SECTION */
/* IFIXND:      NAMTBL INDEX OF START OF FIXED POINT NUMBER SECTION */
/* NUMBST:      NAMTBL INDEX OF BEGINNING OF NUMBER SECTION */
/* NUMBND:      NAMTBL INDEX OF END OF NUMBER SECTION */

/*       12.    LARGE DATA ARRAY STORAGE REQUIREMENTS */







/* MAXSIZ:      SIZE OF THE LAST LARGEST LARGE DATA ARRAY */

/*       14.    I. L. LIST OPTION FLAGS */

/* CILPRT:      TRUE WHEN COMPRESSED I.L. PRINTING REQUESTED */

/*       33.    SYMBOLIC FILE DEFINITIONS */

/* MACTXT:      EXTERNAL FILE  OF MACRO TEXT */
/* ELFIL1:      PACKING FACTOR FOR CREATING PAGES (INTERPRETER) */
/* ELFIL2:      PART PROGRAMMING TEXT GENERATED BY INTERPRETER */
/* ELFIL3:      MACRO TEXT GENERATED FOR INTERPRETER */
/* ELFIL4:      MACRO TEXT GENERATED FOR INTERPRETER */

/*       34.    COMMON BLOCK FOR INTERPRETIVE C.I.L. OUTPUT */


/* ...                SYSTEM I/O FILES */



/* PAGPAK:      PACKING FACTOR FOR CREATING PAGES (INTERPRETER) */
/* MACFLG:      TRUE WHEN MACRO PROCESSING IN EFFECT (INTERPRETER) */
/* LABFLG:      INDICATES I.L. COMMAND IS LABEL (INTERPRETER) */
/* PPPAGE:      PAGE NUMBER OF PART PROGRAMMING TEXT (INTERPRETER) */
/* MCPAGE:      NUMBER OF PAGES OF MACRO I.L. (INTERPRETER) */



/* INUMB:       NUMBER OF ITEMS IN THE LABBUF ARRAY (INTERPRETER) */
/* INAME: */
/* LCILPR: */

/*       41.    NUMBER TABLE OVERFLOW VARIABLES */

/* NMOD:        NUMBER OF ENTRIES PERMITTED IN INTERNAL NUMBER TABLE */
/* NLAST:       LAST NEW BLOCK NUMBER OF NUMBER TABLE ON THE EXTERN FILE */
/* NSTR:        NUMBER OF FIRST MACTXT RECORD AVAILABLE FOR NUMBER TABLE */

/*       45.    NUMBER TABLE INDICES */

/* MNMBND:      LAST NAME TABLE ENTRY TO MACRO ASSIGNED NUMBER SECTION */
/* * */
/* ** */
/* ...     CLEAR BUFFERS AND REWIND FILES 2 AND 3 */


/*       45.    NUMBER TABLE INDICES */


/* MNMBND:      LAST NAME TABLE ENTRY TO MACRO ASSIGNED NUMBER SECTION */
/* NUMIDX:      NAMTBL INDEX OF A NUMBER GIVEN IN THE CURRENT STATEMENT */
/*  NMBRS:      QUANTITY OF NUMBERS IN THE CURRENT STATEMENT */
/* LSTCHR:      LAST CHARACTER OF A NUMBER */
/* MASGND:      NAME TABLE INDEX OF SECTION END FOR NUMBERS ASSIGNMENT */

    if (! outbuf_1.macflg) {
	goto L1;
    }
    rlsbuf_();
    tapop_(&symfil_1.elfil3, &c_n2);
L1:
    outbuf_1.labflg = TRUE_;
    rlsbuf_();
    tapop_(&symfil_1.elfil2, &c_n2);
    tapop_(&symfil_1.elfil1, &c_n2);

/* ...       ALL USEFUL ITEMS IN THE NAMTBL ARE STORED IN BUFFER */
/* ...       TOGETHER WITH ALL RELEVANT PARAMETERS */

    *iname = nametb_1.nammax - nametb_1.inamst + 1;
    *inumb = numblk_1.mnmbnd - nametb_1.ifixst + 1;
    jbuf[2] = outbuf_1.pppage;
    jbuf[3] = outbuf_1.mcpage;
    jbuf[4] = nametb_1.inamst;
    *lcilpr = *cilprt;
    jbuf[6] = nametb_1.numbst;
    jbuf[7] = *nlast;
    jbuf[8] = *nstr;
    jbuf[9] = maxsiz[0];
    jbuf[10] = maxsiz[1];
    irec = 0;
    awrite_(&symfil_1.elfil4, &irec, buf, &c__23, &iret);

/* ...     WRITE NAME TABLE */
    irec = 0;
/* ...  4TH ARGUMENT OF CHWRIT IS NUMBER OF BYTES */
    i__ = *iname * 6;
    chwrit_(&symfil_1.elfil4, &irec, cnamtb_1.cnamtb + (nametb_1.inamst - 1) *
	     6, &i__, &iret, (ftnlen)6);
/* ...  4TH ARGUMENT OF CHWRIT IS NUMBER OF BYTES */
    i__ = *inumb * 12;
    irec = 0;
    chwrit_(&symfil_1.elfil4, &irec, cnamtb_1.cnumtb + (nametb_1.ifixst - 1) *
	     12, &i__, &iret, (ftnlen)12);

/* ...     ALL TABLES AND PARAMETERS NOW WRITTEN.  REWIND FILES 4 AND 9. */

    tapop_(&symfil_1.elfil4, &c_n2);
    tapop_(&symfil_1.mactxt, &c_n3);
    return 0;
} /* ieplog_ */

#undef maxsiz
#undef lcilpr
#undef cilprt
#undef nlast
#undef inumb
#undef iname
#undef nstr
#undef nmod
#undef jbuf
#undef buf


