/* RLSBUF.f -- translated by f2c (version 20100827).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/* Common Block Declarations */

struct {
    integer clfilp, clfile, clfil3, exfile, infile__, vlfile, pnchfl, xcan, 
	    mactxt, xnum, elfil1, elfil2, elfil3, elfil4, cpfile, axfile, 
	    pofile, elfile, ldafil, tifile, pxfile, nfil12, nfil13, libfil, 
	    ispare[26];
} symfil_;

#define symfil_1 symfil_

struct {
    integer pagpak, isc, iscarr, icform, ifloat, icom, macwds, ppwrds;
    logical macflg, labflg, rsvflg;
    integer lpage, buffer[256], labbuf[256], ibuf, ilbuf, pppage, mcpage;
} outbuf_;

#define outbuf_1 outbuf_

/* Table of constant values */

static integer c__256 = 256;

/* *** SOURCE FILE : M0006681.V05   *** */


/*              FORTRAN SUBROUTINE RLSBUF */

/* LINKAGE      SUBROUTINE RLSBUF */

/*          SUBSIDIARIES                  CALLED BY */
/*          TYPE          ENTRY           TYPE          ENTRY */
/*          SUBROUTINE    AWRITE          SUBROUTINE    CILOUT */
/*                                        SUBROUTINE    ICMPRS */
/*                                        SUBROUTINE    IEPLOG */

/* Subroutine */ int rlsbuf_(void)
{
    /* Initialized data */

    static integer zero = 0;

    static integer n, iret;
    extern /* Subroutine */ int awrite_(integer *, integer *, integer *, 
	    integer *, integer *);



/*       33.    SYMBOLIC FILE DEFINITIONS */

/* ELFIL1:          INTERMEDIATE LANGUAGE FILE */
/* ELFIL2:          PART PROGRAMMING TEXT GENERATED BY INTERPRETER */
/* ELFIL3:          MACRO TEXT GENERATED FOR INTERPRETER */

/*       34.    COMMON BLOCK FOR INTERPRETIVE C.I.L. OUTPUT */


/* ...                SYSTEM I/O FILES */



/* MACFLG:      TRUE WHEN MACRO PROCESSING IN EFFECT (INTERPRETER) */
/* LABFLG:      INDICATES I.L. COMMAND IS LABEL (INTERPRETER) */
/* RSVFLG:      TRUE IF I.L. COMMAND IS A RESRV (INTERPRETER) */
/* LPAGE:       NUMBER OF PAGES OF ENTRY,HOLDAT,LABEL AND RESRV COMMANDS */
/* IBUF:        NUMBER OF RECORDS IN BUFFER ARRAY */
/* ILBUF:       NUMBER OF ITEMS IN THE LABBUF ARRAY (INTERPRETER) */
/* PPPAGE:      PAGE NUMBER OF PART PROGRAMMING TEXT (INTERPRETER) */
/* MCPAGE:      NUMBER OF PAGES OF MACRO I.L. (INTERPRETER) */
/* BUFFER:      TEMPORARY STORAGE FOR INTERPRETER OUTPUT (PAGES) */
/* LABBUF:      TEMPORARY STORAGE FOR LABEL,HOLDAT ENTRY AND RESRV I.L. */
/* * */



/* ** */
/* ...     TEST WHETHER THIS IS LABEL AND RESRV CODE */

    if (outbuf_1.labflg || outbuf_1.rsvflg) {
	goto L100;
    }


    if (outbuf_1.ibuf == 0) {
	return 0;
    }

/* ...     NO. IS IT MACRO CODE */

    if (outbuf_1.macflg) {
	goto L300;
    }

/* ...     NO. THIS IS PART-PROGRAM CODE AND IS WRITTEN TO FILE 2 */
/* ...     FORM MARKER WORD, AND UPDATE PAGE COUNT */

/* L200: */
    ++outbuf_1.pppage;
    n = 0;
    outbuf_1.buffer[0] = outbuf_1.pppage;
    outbuf_1.buffer[1] = outbuf_1.ibuf;
    awrite_(&symfil_1.elfil2, &n, outbuf_1.buffer, &c__256, &iret);

/* ...     RESET BUFFER POINTER AND RETURN */

L210:
    outbuf_1.ibuf = 0;
    return 0;

/* ...     MACRO CODE IS WRITTEN TO FILE 3 */
/* ...     FORM MARKER WORD, AND UPDATE PAGE COUNT */

L300:
    ++outbuf_1.mcpage;
    n = 0;
    outbuf_1.buffer[0] = -outbuf_1.mcpage;
    outbuf_1.buffer[1] = outbuf_1.ibuf;
    awrite_(&symfil_1.elfil3, &n, outbuf_1.buffer, &c__256, &iret);
    goto L210;

/* ...     LABEL AND RESRV CODE IS WRITTEN TO FILE 1 */
/* ...     ITS PAGES HAVE ZERO PAGE NUMBERS */

L100:
    ++outbuf_1.lpage;
    n = 0;
    outbuf_1.labbuf[0] = zero;
    outbuf_1.labbuf[1] = outbuf_1.ilbuf;
    awrite_(&symfil_1.elfil1, &n, outbuf_1.labbuf, &c__256, &iret);

/* ...     RESET BUFFER POINTER AND RETURN */

    outbuf_1.ilbuf = 0;
    return 0;
} /* rlsbuf_ */

