C
C   ***  19.  KNUMBR BLOCK  ***
C
C      INTEGER LITERALS
C
      INTEGER          K0,   K1,   K2,   K3,   K4,   K5,   K6,   K7,
     1                 K8,   K9,  K10,  K12,  K13,  K15,  K16,  K18,
     2                K19,  K23,  K24,  K25,  K26,  K27,  K29,  K30,
     3                K31,  K32,  K33,  K34,  K44,  K45,  K46,  K47,
     4                K48,  K50,  K51,  K52,K1013, K1E4, K1E6,  KM1
C
      COMMON/KNUMBR/   K0,   K1,   K2,   K3,   K4,   K5,   K6,   K7,
     1                 K8,   K9,  K10,  K12,  K13,  K15,  K16,  K18,
     2                K19,  K23,  K24,  K25,  K26,  K27,  K29,  K30,
     3                K31,  K32,  K33,  K34,  K44,  K45,  K46,  K47,
     4                K48,  K50,  K51,  K52,K1013, K1E4, K1E6,  KM1
C
 
