C
C   *** 9.  SV BLOCK ***
C
C   REAL SURFACE VARIABLES
C
      DOUBLE PRECISION CC(3,5),EPS1(5),EPS2(5),EPS3(5),EPS4(5),
     +                 EPS6(5),EPS8(5),PAST(5),PLND(5),PLNV(3,5),
     +                 RC(5),S(5),SAVE(5),SFVCT(3,5),SLX(3,5),SN(3,5),
     +                 SNK(3,5),SNL(3,5),SP(3,5),SPK(3,5),SPL(3,5),
     +                 TAU(5),TAU1(5),TAU2(5),TH(5),TN(3,5),TOOLHT(3,5),
     +                 TOOLWD(5),TP(3,5),TPK(3,5),U1(3,5),VNDIR(3,5),
     +                 VT(3,5),Z(5),VARBLE(5),U1K(3,5),SK(3,5)
C
      COMMON/SV/CC,EPS1,EPS2,EPS3,EPS4,EPS6,EPS8,PAST,PLND,PLNV,
     +          RC,S,SAVE,SFVCT,SLX,SN,SNK,SNL,SP,SPK,SPL,TAU,TAU1,
     +          TAU2,TH,TN,TOOLHT,TOOLWD,TP,TPK,U1,VNDIR,VT,Z,
     +          VARBLE,U1K,SK
C
      DOUBLE PRECISION COS1(5),CPLFL(5),CPTST(5),CSD(5),DPLAN(3,5),
     +                 DPMX1(5),PLNCS(5),PLND1(5),PLTST(5),STCK(5),
     +                 STCKN(5),STCK1(5),STCK2(5),TEE(3,5),TNL(3,5)
C
      COMMON/SV1/COS1,CPLFL,CPTST,CSD,DPLAN,DPMX1,PLNCS,PLND1,
     +           PLTST,STCK,STCKN,STCK1,STCK2,TEE,TNL
C
