C
C   ***  10.  ZNUMBR BLOCK  ***
C
C   REAL LITERALS
C
      DOUBLE PRECISION  Z0,    Z1,    Z2,    Z3,    Z5,
     1                 Z10,   Z90,  Z1E6, Z1E38, Z5EM1,
     2               Z6EM1, Z9EM1,Z11EM1,Z12EM1, Z1EM2,
     3               Z1EM3, Z1EM5, Z5EM6, Z1EM6, Z1EM7,
     4               Z1EM9, Z1EM1,   ZM1,DEGRAD,    PI
C
      COMMON/ZNUMBR/    Z0,    Z1,    Z2,    Z3,    Z5,
     1                 Z10,   Z90,  Z1E6, Z1E38, Z5EM1,
     2               Z6EM1, Z9EM1,Z11EM1,Z12EM1, Z1EM2,
     3               Z1EM3, Z1EM5, Z5EM6, Z1EM6, Z1EM7,
     4               Z1EM9, Z1EM1,   ZM1,DEGRAD,    PI
C
